/**
 * Copy of the Apex Today widgets, all five locales (typed: a missing key in any
 * locale fails the build). Anything the main dictionary already has (rank
 * names, challenge units, "days left", feed titles) is reused from `t`.
 */
import type { LocaleId } from '../../i18n';

const en = {
  // picker names
  nChallenge: 'Challenge',
  nRank: 'Rank & mastery',
  nAwards: 'Awards',
  nFeed: 'Apex feed',
  nMastery: 'Mastery',
  nNextFeat: 'Next feat',
  nFeatsBoard: 'Feats board',
  nLevelUp: 'Level-up countdown',
  nYearFeats: 'Year in feats',
  // challenge
  challenge: 'Challenge',
  ofN: (n: string) => `of ${n}`,
  endsOn: (d: string) => `ends ${d}`,
  pace: (x: string) => `≈ ${x} a day to finish`,
  targetReached: 'Target reached',
  timeUp: 'Time is up',
  moreActive: (n: number) => `+${n} more active`,
  browseChallenges: 'Browse challenges',
  open: 'Open',
  // rank
  closestRank: (lift: string) => `Closest rank · ${lift}`,
  toTier: (tier: string) => `To ${tier}`,
  kgTo: (kg: number, tier: string) => `${kg} kg to ${tier}`,
  xBw: (x: string) => `${x}× BW`,
  ranks: 'Ranks',
  masteryN: (n: number) => `Mastery ${n}`,
  closestLine: (lift: string, tier: string) => `Closest: ${lift} → ${tier}`,
  unranked: 'Unranked',
  noRanks: 'No strength ranks yet',
  needBody: 'Add sex and body weight to get ranked',
  needLift: 'Log a main lift to get ranked',
  topTier: 'Top tier reached',
  openRanks: 'Open ranks',
  // awards
  awards: 'Awards',
  unlockedOn: (d: string) => `Unlocked ${d}`,
  nextLine: (title: string) => `Next · ${title}`,
  unlockedOf: (n: number, total: number) => `${n} of ${total} unlocked`,
  lockedMore: (n: number) => `Locked · ${n} more`,
  noAwards: 'No awards yet',
  noAwardsSub: 'Finish a session to unlock the first',
  allAwards: 'All awards',
  // feed
  feed: 'Apex feed',
  newWord: 'new',
  newInApex: (n: number) => `${n} new in Apex`,
  feedNew: (n: number) => `Apex feed · ${n} new`,
  caughtUp: 'All caught up',
  noFeed: 'No milestones yet',
  noFeedSub: 'PRs, feats and streaks land here',
  // mastery
  mastery: 'Mastery',
  of1000: '/ 1000',
  ofThousand: 'of 1000',
  ptsTo: (n: number, label: string) => `${n} pts to ${label}`,
  rankOf: (i: number, n: number) => `Rank ${i} of ${n}`,
  weekDelta: (x: string) => `${x} this week`,
  whatMoves: 'What moves it',
  topLevel: 'Top of the ladder',
  calibrating: (n: number) => `Calibrating · ${n} more sessions`,
  masteryLine: (n: number, rank: string) => `Mastery ${n} · ${rank}`,
  masteryEmpty: 'Not rated yet',
  masteryEmptySub: 'Log sessions to get your rating',
  openMastery: 'Open Mastery',
  // level up
  levelUp: 'Level up',
  levelUpTo: (label: string) => `Level up · ${label}`,
  pts: 'pts',
  ptsToGo: 'pts to go',
  toLabel: (label: string) => `to ${label}`,
  atRating: (label: string, n: number) => `${label} at ${n}`,
  workoutsAway: (n: number) => `≈ ${n} workouts at this pace`,
  workoutsShort: (n: number) => `≈ ${n} workouts`,
  noPace: 'Train this week to set a pace',
  fastest: 'Fastest ways to earn',
  startWorkout: 'Start a workout',
  // feats
  nextFeat: 'Next feat',
  left: (x: string) => `${x} left`,
  then: (title: string) => `Then · ${title}`,
  upNext: 'Up next',
  axesTiers: (axes: number, n: number, total: number) => `${axes} axes · ${n} / ${total} tiers`,
  allFeats: 'All feats',
  sessionsAway: (n: number) => `≈ ${n} sessions`,
  featsEmpty: 'Your first session unlocks feats',
  allUnlocked: 'Every feat unlocked',
  feats: 'Feats',
  featsBoard: 'Feats board',
  tiersOf: (n: number, total: number) => `${n} / ${total} tiers`,
  featsLine: (n: number, total: number) => `Feats ${n} / ${total} tiers`,
  axesStarted: (n: number, total: number) => `${n} of ${total} axes started`,
  closestFeat: (title: string, p: number) => `Closest · ${title} ${p}%`,
  // year in feats
  yearK: (y: number) => `Feats · ${y}`,
  yearInK: (y: number) => `Year in feats · ${y}`,
  unlocks: 'unlocks',
  vsLast: (n: number, y: number) => `vs ${n} in ${y}`,
  unlockedIn: (n: number, y: number) => `${n} feats unlocked in ${y}`,
  latest: (title: string, d: string) => `Latest · ${title}, ${d}`,
  noYear: (y: number) => `No feats yet in ${y}`,
};

export type ApexStrings = typeof en;

const uk: ApexStrings = {
  nChallenge: 'Челендж',
  nRank: 'Ранг і майстерність',
  nAwards: 'Нагороди',
  nFeed: 'Стрічка Apex',
  nMastery: 'Майстерність',
  nNextFeat: 'Наступне досягнення',
  nFeatsBoard: 'Дошка досягнень',
  nLevelUp: 'До нового рівня',
  nYearFeats: 'Рік у досягненнях',
  challenge: 'Челендж',
  ofN: (n) => `з ${n}`,
  endsOn: (d) => `до ${d}`,
  pace: (x) => `≈ ${x} на день, щоб встигнути`,
  targetReached: 'Мету досягнуто',
  timeUp: 'Час вийшов',
  moreActive: (n) => `ще ${n} активних`,
  browseChallenges: 'Обрати челендж',
  open: 'Відкрити',
  closestRank: (lift) => `Найближчий ранг · ${lift}`,
  toTier: (tier) => `До ${tier}`,
  kgTo: (kg, tier) => `${kg} кг до ${tier}`,
  xBw: (x) => `${x}× ваги тіла`,
  ranks: 'Ранги',
  masteryN: (n) => `Майстерність ${n}`,
  closestLine: (lift, tier) => `Найближче: ${lift} → ${tier}`,
  unranked: 'Без рангу',
  noRanks: 'Ще немає силових рангів',
  needBody: 'Вкажіть стать і вагу, щоб отримати ранг',
  needLift: 'Запишіть базову вправу, щоб отримати ранг',
  topTier: 'Найвищий рівень',
  openRanks: 'Відкрити ранги',
  awards: 'Нагороди',
  unlockedOn: (d) => `Відкрито ${d}`,
  nextLine: (title) => `Далі · ${title}`,
  unlockedOf: (n, total) => `${n} з ${total} відкрито`,
  lockedMore: (n) => `Закрито · ще ${n}`,
  noAwards: 'Ще немає нагород',
  noAwardsSub: 'Завершіть тренування, щоб відкрити першу',
  allAwards: 'Усі нагороди',
  feed: 'Стрічка Apex',
  newWord: 'нових',
  newInApex: (n) => `${n} нових в Apex`,
  feedNew: (n) => `Стрічка Apex · ${n} нових`,
  caughtUp: 'Усе переглянуто',
  noFeed: 'Ще немає віх',
  noFeedSub: 'Тут з’являться рекорди, досягнення і серії',
  mastery: 'Майстерність',
  of1000: '/ 1000',
  ofThousand: 'з 1000',
  ptsTo: (n, label) => `${n} балів до ${label}`,
  rankOf: (i, n) => `Ранг ${i} з ${n}`,
  weekDelta: (x) => `${x} за тиждень`,
  whatMoves: 'Що впливає',
  topLevel: 'Вершина драбини',
  calibrating: (n) => `Калібрування · ще ${n} тренувань`,
  masteryLine: (n, rank) => `Майстерність ${n} · ${rank}`,
  masteryEmpty: 'Ще без рейтингу',
  masteryEmptySub: 'Записуйте тренування, щоб отримати рейтинг',
  openMastery: 'Відкрити майстерність',
  levelUp: 'Новий рівень',
  levelUpTo: (label) => `Новий рівень · ${label}`,
  pts: 'балів',
  ptsToGo: 'балів лишилось',
  toLabel: (label) => `до ${label}`,
  atRating: (label, n) => `${label} на ${n}`,
  workoutsAway: (n) => `≈ ${n} тренувань у цьому темпі`,
  workoutsShort: (n) => `≈ ${n} тренувань`,
  noPace: 'Потренуйтеся цього тижня, щоб задати темп',
  fastest: 'Як заробити найшвидше',
  startWorkout: 'Почати тренування',
  nextFeat: 'Наступне досягнення',
  left: (x) => `лишилось ${x}`,
  then: (title) => `Потім · ${title}`,
  upNext: 'Далі',
  axesTiers: (axes, n, total) => `${axes} осей · ${n} / ${total} рівнів`,
  allFeats: 'Усі досягнення',
  sessionsAway: (n) => `≈ ${n} тренувань`,
  featsEmpty: 'Перше тренування відкриє досягнення',
  allUnlocked: 'Усі досягнення відкрито',
  feats: 'Досягнення',
  featsBoard: 'Дошка досягнень',
  tiersOf: (n, total) => `${n} / ${total} рівнів`,
  featsLine: (n, total) => `Досягнення ${n} / ${total} рівнів`,
  axesStarted: (n, total) => `Розпочато ${n} з ${total} осей`,
  closestFeat: (title, p) => `Найближче · ${title} ${p}%`,
  yearK: (y) => `Досягнення · ${y}`,
  yearInK: (y) => `Рік у досягненнях · ${y}`,
  unlocks: 'відкрито',
  vsLast: (n, y) => `проти ${n} у ${y}`,
  unlockedIn: (n, y) => `${n} досягнень відкрито у ${y}`,
  latest: (title, d) => `Останнє · ${title}, ${d}`,
  noYear: (y) => `У ${y} ще немає досягнень`,
};

const pl: ApexStrings = {
  nChallenge: 'Wyzwanie',
  nRank: 'Ranga i mistrzostwo',
  nAwards: 'Nagrody',
  nFeed: 'Kanał Apex',
  nMastery: 'Mistrzostwo',
  nNextFeat: 'Następne osiągnięcie',
  nFeatsBoard: 'Tablica osiągnięć',
  nLevelUp: 'Do awansu',
  nYearFeats: 'Rok w osiągnięciach',
  challenge: 'Wyzwanie',
  ofN: (n) => `z ${n}`,
  endsOn: (d) => `koniec ${d}`,
  pace: (x) => `≈ ${x} dziennie, by zdążyć`,
  targetReached: 'Cel osiągnięty',
  timeUp: 'Czas minął',
  moreActive: (n) => `+${n} aktywnych`,
  browseChallenges: 'Przeglądaj wyzwania',
  open: 'Otwórz',
  closestRank: (lift) => `Najbliższa ranga · ${lift}`,
  toTier: (tier) => `Do ${tier}`,
  kgTo: (kg, tier) => `${kg} kg do ${tier}`,
  xBw: (x) => `${x}× masy ciała`,
  ranks: 'Rangi',
  masteryN: (n) => `Mistrzostwo ${n}`,
  closestLine: (lift, tier) => `Najbliżej: ${lift} → ${tier}`,
  unranked: 'Bez rangi',
  noRanks: 'Brak rang siłowych',
  needBody: 'Podaj płeć i masę ciała, by dostać rangę',
  needLift: 'Zapisz główny bój, by dostać rangę',
  topTier: 'Najwyższy poziom',
  openRanks: 'Otwórz rangi',
  awards: 'Nagrody',
  unlockedOn: (d) => `Odblokowano ${d}`,
  nextLine: (title) => `Dalej · ${title}`,
  unlockedOf: (n, total) => `${n} z ${total} odblokowanych`,
  lockedMore: (n) => `Zablokowane · jeszcze ${n}`,
  noAwards: 'Brak nagród',
  noAwardsSub: 'Ukończ trening, by odblokować pierwszą',
  allAwards: 'Wszystkie nagrody',
  feed: 'Kanał Apex',
  newWord: 'nowe',
  newInApex: (n) => `${n} nowe w Apex`,
  feedNew: (n) => `Kanał Apex · ${n} nowe`,
  caughtUp: 'Wszystko przeczytane',
  noFeed: 'Brak kamieni milowych',
  noFeedSub: 'Tu trafią rekordy, osiągnięcia i serie',
  mastery: 'Mistrzostwo',
  of1000: '/ 1000',
  ofThousand: 'z 1000',
  ptsTo: (n, label) => `${n} pkt do ${label}`,
  rankOf: (i, n) => `Ranga ${i} z ${n}`,
  weekDelta: (x) => `${x} w tym tygodniu`,
  whatMoves: 'Co na to wpływa',
  topLevel: 'Szczyt drabiny',
  calibrating: (n) => `Kalibracja · jeszcze ${n} treningów`,
  masteryLine: (n, rank) => `Mistrzostwo ${n} · ${rank}`,
  masteryEmpty: 'Jeszcze bez oceny',
  masteryEmptySub: 'Zapisuj treningi, by dostać ocenę',
  openMastery: 'Otwórz mistrzostwo',
  levelUp: 'Awans',
  levelUpTo: (label) => `Awans · ${label}`,
  pts: 'pkt',
  ptsToGo: 'pkt do celu',
  toLabel: (label) => `do ${label}`,
  atRating: (label, n) => `${label} przy ${n}`,
  workoutsAway: (n) => `≈ ${n} treningów w tym tempie`,
  workoutsShort: (n) => `≈ ${n} treningów`,
  noPace: 'Potrenuj w tym tygodniu, by ustalić tempo',
  fastest: 'Najszybsze sposoby',
  startWorkout: 'Zacznij trening',
  nextFeat: 'Następne osiągnięcie',
  left: (x) => `zostało ${x}`,
  then: (title) => `Potem · ${title}`,
  upNext: 'Następne',
  axesTiers: (axes, n, total) => `${axes} osi · ${n} / ${total} poziomów`,
  allFeats: 'Wszystkie osiągnięcia',
  sessionsAway: (n) => `≈ ${n} treningów`,
  featsEmpty: 'Pierwszy trening odblokuje osiągnięcia',
  allUnlocked: 'Wszystko odblokowane',
  feats: 'Osiągnięcia',
  featsBoard: 'Tablica osiągnięć',
  tiersOf: (n, total) => `${n} / ${total} poziomów`,
  featsLine: (n, total) => `Osiągnięcia ${n} / ${total} poziomów`,
  axesStarted: (n, total) => `Rozpoczęto ${n} z ${total} osi`,
  closestFeat: (title, p) => `Najbliżej · ${title} ${p}%`,
  yearK: (y) => `Osiągnięcia · ${y}`,
  yearInK: (y) => `Rok w osiągnięciach · ${y}`,
  unlocks: 'odblokowań',
  vsLast: (n, y) => `wobec ${n} w ${y}`,
  unlockedIn: (n, y) => `${n} osiągnięć odblokowanych w ${y}`,
  latest: (title, d) => `Ostatnie · ${title}, ${d}`,
  noYear: (y) => `Brak osiągnięć w ${y}`,
};

const lt: ApexStrings = {
  nChallenge: 'Iššūkis',
  nRank: 'Rangas ir meistriškumas',
  nAwards: 'Apdovanojimai',
  nFeed: 'Apex srautas',
  nMastery: 'Meistriškumas',
  nNextFeat: 'Kitas pasiekimas',
  nFeatsBoard: 'Pasiekimų lenta',
  nLevelUp: 'Iki kito lygio',
  nYearFeats: 'Metai pasiekimuose',
  challenge: 'Iššūkis',
  ofN: (n) => `iš ${n}`,
  endsOn: (d) => `baigiasi ${d}`,
  pace: (x) => `≈ ${x} per dieną, kad spėtum`,
  targetReached: 'Tikslas pasiektas',
  timeUp: 'Laikas baigėsi',
  moreActive: (n) => `dar ${n} aktyvūs`,
  browseChallenges: 'Rinktis iššūkį',
  open: 'Atidaryti',
  closestRank: (lift) => `Artimiausias rangas · ${lift}`,
  toTier: (tier) => `Iki ${tier}`,
  kgTo: (kg, tier) => `${kg} kg iki ${tier}`,
  xBw: (x) => `${x}× kūno svorio`,
  ranks: 'Rangai',
  masteryN: (n) => `Meistriškumas ${n}`,
  closestLine: (lift, tier) => `Artimiausia: ${lift} → ${tier}`,
  unranked: 'Be rango',
  noRanks: 'Jėgos rangų dar nėra',
  needBody: 'Nurodyk lytį ir svorį, kad gautum rangą',
  needLift: 'Užrašyk pagrindinį pratimą, kad gautum rangą',
  topTier: 'Aukščiausias lygis',
  openRanks: 'Atidaryti rangus',
  awards: 'Apdovanojimai',
  unlockedOn: (d) => `Atrakinta ${d}`,
  nextLine: (title) => `Toliau · ${title}`,
  unlockedOf: (n, total) => `${n} iš ${total} atrakinta`,
  lockedMore: (n) => `Užrakinta · dar ${n}`,
  noAwards: 'Apdovanojimų dar nėra',
  noAwardsSub: 'Baik treniruotę ir atrakink pirmąjį',
  allAwards: 'Visi apdovanojimai',
  feed: 'Apex srautas',
  newWord: 'nauji',
  newInApex: (n) => `${n} nauji Apex`,
  feedNew: (n) => `Apex srautas · ${n} nauji`,
  caughtUp: 'Viskas peržiūrėta',
  noFeed: 'Etapų dar nėra',
  noFeedSub: 'Čia atsiras rekordai, pasiekimai ir serijos',
  mastery: 'Meistriškumas',
  of1000: '/ 1000',
  ofThousand: 'iš 1000',
  ptsTo: (n, label) => `${n} tšk. iki ${label}`,
  rankOf: (i, n) => `Rangas ${i} iš ${n}`,
  weekDelta: (x) => `${x} per savaitę`,
  whatMoves: 'Kas lemia',
  topLevel: 'Kopėčių viršūnė',
  calibrating: (n) => `Kalibruojama · dar ${n} treniruotės`,
  masteryLine: (n, rank) => `Meistriškumas ${n} · ${rank}`,
  masteryEmpty: 'Dar neįvertinta',
  masteryEmptySub: 'Užrašyk treniruotes ir gausi įvertinimą',
  openMastery: 'Atidaryti meistriškumą',
  levelUp: 'Naujas lygis',
  levelUpTo: (label) => `Naujas lygis · ${label}`,
  pts: 'tšk.',
  ptsToGo: 'tšk. liko',
  toLabel: (label) => `iki ${label}`,
  atRating: (label, n) => `${label} ties ${n}`,
  workoutsAway: (n) => `≈ ${n} treniruotės tokiu tempu`,
  workoutsShort: (n) => `≈ ${n} treniruotės`,
  noPace: 'Pasitreniruok šią savaitę ir nustatyk tempą',
  fastest: 'Greičiausi būdai uždirbti',
  startWorkout: 'Pradėti treniruotę',
  nextFeat: 'Kitas pasiekimas',
  left: (x) => `liko ${x}`,
  then: (title) => `Po to · ${title}`,
  upNext: 'Toliau',
  axesTiers: (axes, n, total) => `${axes} ašys · ${n} / ${total} lygių`,
  allFeats: 'Visi pasiekimai',
  sessionsAway: (n) => `≈ ${n} treniruotės`,
  featsEmpty: 'Pirmoji treniruotė atrakins pasiekimus',
  allUnlocked: 'Visi pasiekimai atrakinti',
  feats: 'Pasiekimai',
  featsBoard: 'Pasiekimų lenta',
  tiersOf: (n, total) => `${n} / ${total} lygių`,
  featsLine: (n, total) => `Pasiekimai ${n} / ${total} lygių`,
  axesStarted: (n, total) => `Pradėta ${n} iš ${total} ašių`,
  closestFeat: (title, p) => `Artimiausias · ${title} ${p}%`,
  yearK: (y) => `Pasiekimai · ${y}`,
  yearInK: (y) => `Metai pasiekimuose · ${y}`,
  unlocks: 'atrakinta',
  vsLast: (n, y) => `palyginti su ${n} ${y} m.`,
  unlockedIn: (n, y) => `${n} pasiekimai atrakinti ${y} m.`,
  latest: (title, d) => `Naujausias · ${title}, ${d}`,
  noYear: (y) => `${y} m. pasiekimų dar nėra`,
};

const et: ApexStrings = {
  nChallenge: 'Väljakutse',
  nRank: 'Auaste ja meisterlikkus',
  nAwards: 'Auhinnad',
  nFeed: 'Apexi voog',
  nMastery: 'Meisterlikkus',
  nNextFeat: 'Järgmine saavutus',
  nFeatsBoard: 'Saavutuste tahvel',
  nLevelUp: 'Järgmise tasemeni',
  nYearFeats: 'Aasta saavutustes',
  challenge: 'Väljakutse',
  ofN: (n) => `/ ${n}`,
  endsOn: (d) => `lõpeb ${d}`,
  pace: (x) => `≈ ${x} päevas, et jõuda`,
  targetReached: 'Eesmärk saavutatud',
  timeUp: 'Aeg sai läbi',
  moreActive: (n) => `veel ${n} aktiivset`,
  browseChallenges: 'Vali väljakutse',
  open: 'Ava',
  closestRank: (lift) => `Lähim auaste · ${lift}`,
  toTier: (tier) => `Kuni ${tier}`,
  kgTo: (kg, tier) => `${kg} kg kuni ${tier}`,
  xBw: (x) => `${x}× kehakaal`,
  ranks: 'Auastmed',
  masteryN: (n) => `Meisterlikkus ${n}`,
  closestLine: (lift, tier) => `Lähim: ${lift} → ${tier}`,
  unranked: 'Auastmeta',
  noRanks: 'Jõuauastmeid veel pole',
  needBody: 'Lisa sugu ja kehakaal, et auaste saada',
  needLift: 'Logi põhiharjutus, et auaste saada',
  topTier: 'Kõrgeim tase',
  openRanks: 'Ava auastmed',
  awards: 'Auhinnad',
  unlockedOn: (d) => `Avatud ${d}`,
  nextLine: (title) => `Järgmine · ${title}`,
  unlockedOf: (n, total) => `${n} / ${total} avatud`,
  lockedMore: (n) => `Lukus · veel ${n}`,
  noAwards: 'Auhindu veel pole',
  noAwardsSub: 'Lõpeta trenn, et esimene avada',
  allAwards: 'Kõik auhinnad',
  feed: 'Apexi voog',
  newWord: 'uut',
  newInApex: (n) => `${n} uut Apexis`,
  feedNew: (n) => `Apexi voog · ${n} uut`,
  caughtUp: 'Kõik loetud',
  noFeed: 'Verstaposte veel pole',
  noFeedSub: 'Siia jõuavad rekordid, saavutused ja seeriad',
  mastery: 'Meisterlikkus',
  of1000: '/ 1000',
  ofThousand: '/ 1000',
  ptsTo: (n, label) => `${n} p kuni ${label}`,
  rankOf: (i, n) => `Auaste ${i} / ${n}`,
  weekDelta: (x) => `${x} sel nädalal`,
  whatMoves: 'Mis seda liigutab',
  topLevel: 'Redeli tipp',
  calibrating: (n) => `Kalibreerimine · veel ${n} trenni`,
  masteryLine: (n, rank) => `Meisterlikkus ${n} · ${rank}`,
  masteryEmpty: 'Veel hindamata',
  masteryEmptySub: 'Logi trenne, et hinnang saada',
  openMastery: 'Ava meisterlikkus',
  levelUp: 'Uus tase',
  levelUpTo: (label) => `Uus tase · ${label}`,
  pts: 'p',
  ptsToGo: 'p veel',
  toLabel: (label) => `kuni ${label}`,
  atRating: (label, n) => `${label} tasemel ${n}`,
  workoutsAway: (n) => `≈ ${n} trenni selles tempos`,
  workoutsShort: (n) => `≈ ${n} trenni`,
  noPace: 'Treeni sel nädalal, et tempo paika saada',
  fastest: 'Kiireimad teenimise viisid',
  startWorkout: 'Alusta trenni',
  nextFeat: 'Järgmine saavutus',
  left: (x) => `jäänud ${x}`,
  then: (title) => `Siis · ${title}`,
  upNext: 'Järgmisena',
  axesTiers: (axes, n, total) => `${axes} telge · ${n} / ${total} taset`,
  allFeats: 'Kõik saavutused',
  sessionsAway: (n) => `≈ ${n} trenni`,
  featsEmpty: 'Esimene trenn avab saavutused',
  allUnlocked: 'Kõik saavutused avatud',
  feats: 'Saavutused',
  featsBoard: 'Saavutuste tahvel',
  tiersOf: (n, total) => `${n} / ${total} taset`,
  featsLine: (n, total) => `Saavutused ${n} / ${total} taset`,
  axesStarted: (n, total) => `Alustatud ${n} / ${total} telge`,
  closestFeat: (title, p) => `Lähim · ${title} ${p}%`,
  yearK: (y) => `Saavutused · ${y}`,
  yearInK: (y) => `Aasta saavutustes · ${y}`,
  unlocks: 'avatud',
  vsLast: (n, y) => `vs ${n} aastal ${y}`,
  unlockedIn: (n, y) => `${n} saavutust avatud aastal ${y}`,
  latest: (title, d) => `Viimane · ${title}, ${d}`,
  noYear: (y) => `Aastal ${y} veel saavutusi pole`,
};

const DICT: Record<LocaleId, ApexStrings> = { en, uk, pl, lt, et };

export function axs(locale: LocaleId): ApexStrings {
  return DICT[locale];
}
