/**
 * Copy of the Body & recovery widgets (body.tsx + bodyplus.tsx), all five
 * locales. Typed: a key missing in any locale fails the build.
 */
import type { LocaleId } from '../../i18n';

const en = {
  // Energy today
  energyToday: 'Energy today',
  burnedToday: 'Burned today',
  kcal: 'kcal',
  activeN: (n: string) => `${n} active`,
  kcalToday: (n: string) => `${n} kcal today`,
  activeResting: (a: string, r: string) => `${a} active · ${r} resting`,
  resting: 'Resting',
  workout: 'Workout',
  activities: 'Activities',
  total: 'Total',
  energyOn: (d: string) => `Energy · ${d}`,
  byHour: 'by hour',
  noEnergy: 'No energy data yet',
  noEnergySub: 'Log your weight to estimate the day',
  dayHistory: 'Day history',
  minN: (n: number) => `${n} min`,
  // Rehab
  rehab: 'Rehab',
  rehabPlan: 'Rehab plan',
  rehabOf: (part: string) => `Rehab · ${part}`,
  stageOf: (n: number, total: number) => `Stage ${n} of ${total}`,
  dayN: (n: number) => `day ${n}`,
  goodCheckins: (n: number, need: number) => `${n} of ${need} good check-ins to move up`,
  readyMoveUp: 'Ready to move up',
  lastCheckin: (feel: string, date: string) => `Last check-in · ${feel} · ${date}`,
  checkinNext: 'Check in after your next session',
  protectedLoad: 'Protected muscles · load',
  outOfTraining: 'out',
  noRehab: 'No active rehab',
  noRehabSub: 'Hurt? Start a guided plan',
  startRehab: 'Start rehab plan',
  // Sleep debt
  sleepDebt: 'Sleep debt',
  debtSub: (goal: string) => `under ${goal} goal · 7 nights`,
  debtRow: (goal: string, bed: string) => `7 nights vs ${goal} · bed by ${bed} tonight`,
  debtRowNoPlan: (goal: string) => `7 nights vs ${goal}`,
  debtKicker: 'Sleep debt · 7 nights',
  goalX: (g: string) => `goal ${g}`,
  bedByCut: (bed: string, cut: string) => `Bed by ${bed} tonight to cut ${cut}`,
  vsLastWeek: (x: string) => `${x} vs last week`,
  worstNight: (d: string) => `Worst night · ${d}`,
  avgSleep: 'Average sleep',
  napsCounted: 'Naps counted',
  clearIn: (bed: string, n: number) => `Bed by ${bed} · clear in ~${n} nights`,
  planBedtime: 'Plan bedtime',
  noDebt: 'No sleep debt',
  noDebtSub: 'On goal across the last 7 nights',
  needNights: 'Log a few nights to see it',
  // Bedtime consistency
  bedtime: 'Bedtime',
  bedtimeConsistency: 'Bedtime consistency',
  spreadMin: (m: number) => `±${m} min`,
  spread: 'spread',
  usualLate: (u: string, n: number) => (n > 0 ? `Usual ${u} · ${n} late` : `Usual ${u}`),
  usualLast: (u: string, l: string) => `Usual ${u} · last night ${l}`,
  bedtime7: 'Bedtime · 7 nights',
  usualX: (u: string) => `usual ${u}`,
  lateNights: (n: number) => (n === 1 ? '1 late night' : `${n} late nights`),
  latestX: (d: string) => `Latest · ${d}`,
  avgWake: 'Avg wake-up',
  onRhythm: 'On rhythm · 14 d',
  windDown: (x: string) => `Wind down at ${x} tonight`,
  setSchedule: 'Set schedule',
  needTwoNights: 'Log 2+ nights to see your rhythm',
  // Naps
  naps: 'Naps',
  napsWeek: 'Naps · this week',
  napsN: (n: number) => (n === 1 ? '1 nap' : `${n} naps`),
  totalX: (x: string) => `${x} total`,
  avgX: (x: string) => `avg ${x}`,
  noNaps: 'No naps this week',
  logNap: 'Log nap',
  debtOffset: 'Sleep debt offset',
  // Body composition
  bodyComp: 'Body composition',
  bodyComp30: 'Body composition · 30 d',
  bodyFat: 'Body fat',
  bmi: 'BMI',
  muscle: 'Muscle',
  leanMass: 'Lean mass',
  chest: 'Chest',
  waist: 'Waist',
  hip: 'Hip',
  fatShort: (x: string) => `fat ${x}%`,
  muscleShort: (x: string) => `muscle ${x}%`,
  waistShort: (x: string) => `waist ${x} cm`,
  inDays30: (x: string) => `${x} in 30 d`,
  noComp: 'No body measurements yet',
  addMeasures: 'Add measurements',
  updateMeasures: 'Update measurements',
  // Resting energy
  restingEnergy: 'Resting energy',
  perDayBmr: 'per day · BMR',
  kcalDay: 'kcal / day',
  bmrRow: (n: string) => `BMR ${n} kcal/day`,
  restingBmr: 'Resting energy · BMR',
  resting30: 'Resting energy · 30 d',
  dailyLife: 'Daily life',
  trainingToday: 'Training today',
  totalEstimate: 'Total daily estimate',
  lifestyle: 'Lifestyle',
  lifestyleLevel: {
    sedentary: 'Sedentary',
    light: 'Light',
    moderate: 'Moderate',
    active: 'Active',
  } as Record<string, string>,
  fatPctShort: (x: string) => `${x}% fat`,
  noBmr: 'Needs height, age and sex',
  completeProfile: 'Complete body profile',
  // Physique goal
  physiqueGoal: 'Physique goal',
  pctThere: (name: string, p: number) => `${name} · ${p}% there`,
  kgToGo: (x: string) => `${x} kg to go`,
  onPace: (d: string) => `On pace for ${d}`,
  targetKg: (x: string) => `Target ${x} kg`,
  overall: 'Overall',
  startedX: (d: string) => `started ${d}`,
  weight: 'Weight',
  now: 'now',
  noPhysique: 'No physique goal yet',
  pickPhysique: 'Pick a physique goal',
  setTarget: 'Set a target weight',
  adjustGoal: 'Adjust goal',
  reached: 'Goal weight reached',
  // Rest & illness log
  restLog: 'Rest & illness log',
  rest30: 'Rest · 30 d',
  restIllness30: 'Rest & illness · 30 d',
  daysOff: 'days off',
  streakKept: (n: number) => `Streak ${n} kept ✓`,
  restSickOff: (r: number, s: number, o: number) => `${r} rest · ${s} sick · ${o} off`,
  last30Safe: (n: number) => `Last 30 days · streak ${n} safe ✓`,
  kindTrain: 'Train',
  kindRest: 'Rest',
  kindSick: 'Sick',
  kindOff: 'Off',
  modeName: { active: 'Active rest', off: 'Day off', illness: 'Sick' } as Record<string, string>,
  noneBroke: 'None of these broke the streak',
  logDay: 'Log a day',
  noRest: 'Nothing logged in 30 days',
};

export type BodyStrings = typeof en;

const uk: BodyStrings = {
  energyToday: 'Енергія сьогодні',
  burnedToday: 'Спалено сьогодні',
  kcal: 'ккал',
  activeN: (n) => `${n} активно`,
  kcalToday: (n) => `${n} ккал сьогодні`,
  activeResting: (a, r) => `${a} активно · ${r} у спокої`,
  resting: 'У спокої',
  workout: 'Тренування',
  activities: 'Активності',
  total: 'Разом',
  energyOn: (d) => `Енергія · ${d}`,
  byHour: 'по годинах',
  noEnergy: 'Ще немає даних про енергію',
  noEnergySub: 'Запишіть вагу, щоб оцінити день',
  dayHistory: 'Історія дня',
  minN: (n) => `${n} хв`,
  rehab: 'Реабілітація',
  rehabPlan: 'План реабілітації',
  rehabOf: (part) => `Реабілітація · ${part}`,
  stageOf: (n, total) => `Етап ${n} з ${total}`,
  dayN: (n) => `день ${n}`,
  goodCheckins: (n, need) => `${n} з ${need} добрих check-in до наступного етапу`,
  readyMoveUp: 'Можна переходити далі',
  lastCheckin: (feel, date) => `Останній check-in · ${feel} · ${date}`,
  checkinNext: 'Зробіть check-in після наступного тренування',
  protectedLoad: 'Захищені м’язи · навантаження',
  outOfTraining: 'поза',
  noRehab: 'Немає активної реабілітації',
  noRehabSub: 'Травма? Почніть план із підказками',
  startRehab: 'Почати план реабілітації',
  sleepDebt: 'Борг сну',
  debtSub: (goal) => `нижче цілі ${goal} · 7 ночей`,
  debtRow: (goal, bed) => `7 ночей проти ${goal} · лягти до ${bed}`,
  debtRowNoPlan: (goal) => `7 ночей проти ${goal}`,
  debtKicker: 'Борг сну · 7 ночей',
  goalX: (g) => `ціль ${g}`,
  bedByCut: (bed, cut) => `Ляжте до ${bed}, щоб зменшити на ${cut}`,
  vsLastWeek: (x) => `${x} до мин. тижня`,
  worstNight: (d) => `Найгірша ніч · ${d}`,
  avgSleep: 'Середній сон',
  napsCounted: 'Враховано денний сон',
  clearIn: (bed, n) => `Лягти до ${bed} · закриєте за ~${n} ноч.`,
  planBedtime: 'Спланувати відбій',
  noDebt: 'Боргу сну немає',
  noDebtSub: 'Ціль виконана за останні 7 ночей',
  needNights: 'Запишіть кілька ночей',
  bedtime: 'Відбій',
  bedtimeConsistency: 'Стабільність відбою',
  spreadMin: (m) => `±${m} хв`,
  spread: 'розкид',
  usualLate: (u, n) => (n > 0 ? `Зазвичай ${u} · пізніх: ${n}` : `Зазвичай ${u}`),
  usualLast: (u, l) => `Зазвичай ${u} · вчора ${l}`,
  bedtime7: 'Відбій · 7 ночей',
  usualX: (u) => `зазвичай ${u}`,
  lateNights: (n) => `пізніх ночей: ${n}`,
  latestX: (d) => `Найпізніше · ${d}`,
  avgWake: 'Середній підйом',
  onRhythm: 'У ритмі · 14 дн',
  windDown: (x) => `Готуйтеся до сну о ${x}`,
  setSchedule: 'Розклад сну',
  needTwoNights: 'Запишіть 2+ ночі, щоб побачити ритм',
  naps: 'Денний сон',
  napsWeek: 'Денний сон · цей тиждень',
  napsN: (n) => `Денний сон: ${n}`,
  totalX: (x) => `${x} разом`,
  avgX: (x) => `сер. ${x}`,
  noNaps: 'Цього тижня без денного сну',
  logNap: 'Додати сон',
  debtOffset: 'Мінус до боргу сну',
  bodyComp: 'Склад тіла',
  bodyComp30: 'Склад тіла · 30 дн',
  bodyFat: 'Жир',
  bmi: 'ІМТ',
  muscle: 'М’язи',
  leanMass: 'Суха маса',
  chest: 'Груди',
  waist: 'Талія',
  hip: 'Стегна',
  fatShort: (x) => `жир ${x}%`,
  muscleShort: (x) => `м’язи ${x}%`,
  waistShort: (x) => `талія ${x} см`,
  inDays30: (x) => `${x} за 30 дн`,
  noComp: 'Ще немає замірів тіла',
  addMeasures: 'Додати заміри',
  updateMeasures: 'Оновити заміри',
  restingEnergy: 'Енергія спокою',
  perDayBmr: 'на добу · BMR',
  kcalDay: 'ккал / доба',
  bmrRow: (n) => `BMR ${n} ккал/доба`,
  restingBmr: 'Енергія спокою · BMR',
  resting30: 'Енергія спокою · 30 дн',
  dailyLife: 'Побутова активність',
  trainingToday: 'Тренування сьогодні',
  totalEstimate: 'Оцінка за добу',
  lifestyle: 'Спосіб життя',
  lifestyleLevel: {
    sedentary: 'Сидячий',
    light: 'Легкий',
    moderate: 'Помірний',
    active: 'Активний',
  },
  fatPctShort: (x) => `${x}% жиру`,
  noBmr: 'Потрібні зріст, вік і стать',
  completeProfile: 'Заповнити профіль тіла',
  physiqueGoal: 'Ціль фізики',
  pctThere: (name, p) => `${name} · ${p}% шляху`,
  kgToGo: (x) => `ще ${x} кг`,
  onPace: (d) => `У темпі до ${d}`,
  targetKg: (x) => `Ціль ${x} кг`,
  overall: 'Загалом',
  startedX: (d) => `старт ${d}`,
  weight: 'Вага',
  now: 'зараз',
  noPhysique: 'Ціль фізики не обрана',
  pickPhysique: 'Обрати ціль фізики',
  setTarget: 'Задайте цільову вагу',
  adjustGoal: 'Змінити ціль',
  reached: 'Цільову вагу досягнуто',
  restLog: 'Відпочинок і хвороба',
  rest30: 'Відпочинок · 30 дн',
  restIllness30: 'Відпочинок і хвороба · 30 дн',
  daysOff: 'днів поза залом',
  streakKept: (n) => `Серія ${n} збережена ✓`,
  restSickOff: (r, s, o) => `${r} відпоч. · ${s} хвор. · ${o} вихідн.`,
  last30Safe: (n) => `Останні 30 днів · серія ${n} у безпеці ✓`,
  kindTrain: 'Трен.',
  kindRest: 'Відпоч.',
  kindSick: 'Хвор.',
  kindOff: 'Вихідн.',
  modeName: { active: 'Активний відпочинок', off: 'Вихідний', illness: 'Хвороба' },
  noneBroke: 'Жоден із цих днів не обнулив серію',
  logDay: 'Додати день',
  noRest: 'За 30 днів нічого не записано',
};

const pl: BodyStrings = {
  energyToday: 'Energia dziś',
  burnedToday: 'Spalone dziś',
  kcal: 'kcal',
  activeN: (n) => `${n} aktywnie`,
  kcalToday: (n) => `${n} kcal dziś`,
  activeResting: (a, r) => `${a} aktywnie · ${r} spoczynkowo`,
  resting: 'Spoczynek',
  workout: 'Trening',
  activities: 'Aktywności',
  total: 'Razem',
  energyOn: (d) => `Energia · ${d}`,
  byHour: 'godzinowo',
  noEnergy: 'Brak danych o energii',
  noEnergySub: 'Zapisz wagę, by oszacować dzień',
  dayHistory: 'Historia dnia',
  minN: (n) => `${n} min`,
  rehab: 'Rehabilitacja',
  rehabPlan: 'Plan rehabilitacji',
  rehabOf: (part) => `Rehabilitacja · ${part}`,
  stageOf: (n, total) => `Etap ${n} z ${total}`,
  dayN: (n) => `dzień ${n}`,
  goodCheckins: (n, need) => `${n} z ${need} dobrych check-inów do awansu`,
  readyMoveUp: 'Gotowe na kolejny etap',
  lastCheckin: (feel, date) => `Ostatni check-in · ${feel} · ${date}`,
  checkinNext: 'Zrób check-in po następnym treningu',
  protectedLoad: 'Chronione mięśnie · obciążenie',
  outOfTraining: 'poza',
  noRehab: 'Brak aktywnej rehabilitacji',
  noRehabSub: 'Kontuzja? Zacznij plan z przewodnikiem',
  startRehab: 'Zacznij plan rehabilitacji',
  sleepDebt: 'Dług snu',
  debtSub: (goal) => `poniżej celu ${goal} · 7 nocy`,
  debtRow: (goal, bed) => `7 nocy vs ${goal} · spać do ${bed}`,
  debtRowNoPlan: (goal) => `7 nocy vs ${goal}`,
  debtKicker: 'Dług snu · 7 nocy',
  goalX: (g) => `cel ${g}`,
  bedByCut: (bed, cut) => `Połóż się do ${bed}, by odjąć ${cut}`,
  vsLastWeek: (x) => `${x} vs zeszły tydzień`,
  worstNight: (d) => `Najgorsza noc · ${d}`,
  avgSleep: 'Średni sen',
  napsCounted: 'Wliczone drzemki',
  clearIn: (bed, n) => `Spać do ${bed} · spłata za ~${n} nocy`,
  planBedtime: 'Zaplanuj sen',
  noDebt: 'Brak długu snu',
  noDebtSub: 'Cel spełniony przez ostatnie 7 nocy',
  needNights: 'Zapisz kilka nocy',
  bedtime: 'Pora snu',
  bedtimeConsistency: 'Regularność snu',
  spreadMin: (m) => `±${m} min`,
  spread: 'rozrzut',
  usualLate: (u, n) => (n > 0 ? `Zwykle ${u} · późne: ${n}` : `Zwykle ${u}`),
  usualLast: (u, l) => `Zwykle ${u} · wczoraj ${l}`,
  bedtime7: 'Pora snu · 7 nocy',
  usualX: (u) => `zwykle ${u}`,
  lateNights: (n) => `późne noce: ${n}`,
  latestX: (d) => `Najpóźniej · ${d}`,
  avgWake: 'Średnia pobudka',
  onRhythm: 'W rytmie · 14 dni',
  windDown: (x) => `Wycisz się o ${x}`,
  setSchedule: 'Harmonogram snu',
  needTwoNights: 'Zapisz 2+ noce, by zobaczyć rytm',
  naps: 'Drzemki',
  napsWeek: 'Drzemki · ten tydzień',
  napsN: (n) => `Drzemki: ${n}`,
  totalX: (x) => `${x} razem`,
  avgX: (x) => `śr. ${x}`,
  noNaps: 'Brak drzemek w tym tygodniu',
  logNap: 'Dodaj drzemkę',
  debtOffset: 'Odjęte od długu snu',
  bodyComp: 'Skład ciała',
  bodyComp30: 'Skład ciała · 30 dni',
  bodyFat: 'Tłuszcz',
  bmi: 'BMI',
  muscle: 'Mięśnie',
  leanMass: 'Beztłuszczowa masa',
  chest: 'Klatka',
  waist: 'Talia',
  hip: 'Biodra',
  fatShort: (x) => `tłuszcz ${x}%`,
  muscleShort: (x) => `mięśnie ${x}%`,
  waistShort: (x) => `talia ${x} cm`,
  inDays30: (x) => `${x} w 30 dni`,
  noComp: 'Brak pomiarów ciała',
  addMeasures: 'Dodaj pomiary',
  updateMeasures: 'Zaktualizuj pomiary',
  restingEnergy: 'Energia spoczynkowa',
  perDayBmr: 'na dobę · BMR',
  kcalDay: 'kcal / doba',
  bmrRow: (n) => `BMR ${n} kcal/doba`,
  restingBmr: 'Energia spoczynkowa · BMR',
  resting30: 'Energia spoczynkowa · 30 dni',
  dailyLife: 'Codzienna aktywność',
  trainingToday: 'Trening dziś',
  totalEstimate: 'Szacunek dobowy',
  lifestyle: 'Styl życia',
  lifestyleLevel: {
    sedentary: 'Siedzący',
    light: 'Lekki',
    moderate: 'Umiarkowany',
    active: 'Aktywny',
  },
  fatPctShort: (x) => `${x}% tłuszczu`,
  noBmr: 'Potrzebny wzrost, wiek i płeć',
  completeProfile: 'Uzupełnij profil ciała',
  physiqueGoal: 'Cel sylwetki',
  pctThere: (name, p) => `${name} · ${p}% drogi`,
  kgToGo: (x) => `jeszcze ${x} kg`,
  onPace: (d) => `W tempie na ${d}`,
  targetKg: (x) => `Cel ${x} kg`,
  overall: 'Ogółem',
  startedX: (d) => `start ${d}`,
  weight: 'Waga',
  now: 'teraz',
  noPhysique: 'Brak celu sylwetki',
  pickPhysique: 'Wybierz cel sylwetki',
  setTarget: 'Ustaw wagę docelową',
  adjustGoal: 'Zmień cel',
  reached: 'Waga docelowa osiągnięta',
  restLog: 'Odpoczynek i choroba',
  rest30: 'Odpoczynek · 30 dni',
  restIllness30: 'Odpoczynek i choroba · 30 dni',
  daysOff: 'dni wolnych',
  streakKept: (n) => `Seria ${n} utrzymana ✓`,
  restSickOff: (r, s, o) => `${r} odp. · ${s} chor. · ${o} wolne`,
  last30Safe: (n) => `Ostatnie 30 dni · seria ${n} bezpieczna ✓`,
  kindTrain: 'Trening',
  kindRest: 'Odp.',
  kindSick: 'Chor.',
  kindOff: 'Wolne',
  modeName: { active: 'Aktywny odpoczynek', off: 'Dzień wolny', illness: 'Choroba' },
  noneBroke: 'Żaden z tych dni nie przerwał serii',
  logDay: 'Dodaj dzień',
  noRest: 'Nic nie zapisano przez 30 dni',
};

const lt: BodyStrings = {
  energyToday: 'Energija šiandien',
  burnedToday: 'Sudeginta šiandien',
  kcal: 'kcal',
  activeN: (n) => `${n} aktyviai`,
  kcalToday: (n) => `${n} kcal šiandien`,
  activeResting: (a, r) => `${a} aktyviai · ${r} ramybėje`,
  resting: 'Ramybėje',
  workout: 'Treniruotė',
  activities: 'Veiklos',
  total: 'Iš viso',
  energyOn: (d) => `Energija · ${d}`,
  byHour: 'pagal valandas',
  noEnergy: 'Dar nėra energijos duomenų',
  noEnergySub: 'Įrašykite svorį, kad įvertintume dieną',
  dayHistory: 'Dienos istorija',
  minN: (n) => `${n} min`,
  rehab: 'Reabilitacija',
  rehabPlan: 'Reabilitacijos planas',
  rehabOf: (part) => `Reabilitacija · ${part}`,
  stageOf: (n, total) => `Etapas ${n} iš ${total}`,
  dayN: (n) => `${n} diena`,
  goodCheckins: (n, need) => `${n} iš ${need} gerų check-in iki kito etapo`,
  readyMoveUp: 'Galima pereiti toliau',
  lastCheckin: (feel, date) => `Paskutinis check-in · ${feel} · ${date}`,
  checkinNext: 'Atlikite check-in po kitos treniruotės',
  protectedLoad: 'Saugomi raumenys · krūvis',
  outOfTraining: 'ne',
  noRehab: 'Nėra aktyvios reabilitacijos',
  noRehabSub: 'Trauma? Pradėkite planą su gairėmis',
  startRehab: 'Pradėti reabilitacijos planą',
  sleepDebt: 'Miego skola',
  debtSub: (goal) => `žemiau ${goal} tikslo · 7 naktys`,
  debtRow: (goal, bed) => `7 naktys vs ${goal} · gulti iki ${bed}`,
  debtRowNoPlan: (goal) => `7 naktys vs ${goal}`,
  debtKicker: 'Miego skola · 7 naktys',
  goalX: (g) => `tikslas ${g}`,
  bedByCut: (bed, cut) => `Gulkite iki ${bed}, kad sumažintumėte ${cut}`,
  vsLastWeek: (x) => `${x} vs praėjusi sav.`,
  worstNight: (d) => `Blogiausia naktis · ${d}`,
  avgSleep: 'Vidutinis miegas',
  napsCounted: 'Įskaičiuoti snūduriai',
  clearIn: (bed, n) => `Gulti iki ${bed} · padengsite per ~${n} n.`,
  planBedtime: 'Planuoti miegą',
  noDebt: 'Miego skolos nėra',
  noDebtSub: 'Tikslas pasiektas per paskutines 7 naktis',
  needNights: 'Įrašykite kelias naktis',
  bedtime: 'Ėjimas miegoti',
  bedtimeConsistency: 'Miego pastovumas',
  spreadMin: (m) => `±${m} min`,
  spread: 'sklaida',
  usualLate: (u, n) => (n > 0 ? `Įprastai ${u} · vėlyvų: ${n}` : `Įprastai ${u}`),
  usualLast: (u, l) => `Įprastai ${u} · vakar ${l}`,
  bedtime7: 'Ėjimas miegoti · 7 naktys',
  usualX: (u) => `įprastai ${u}`,
  lateNights: (n) => `vėlyvų naktų: ${n}`,
  latestX: (d) => `Vėliausiai · ${d}`,
  avgWake: 'Vid. kėlimasis',
  onRhythm: 'Ritme · 14 d.',
  windDown: (x) => `Ruoškitės miegui ${x}`,
  setSchedule: 'Miego grafikas',
  needTwoNights: 'Įrašykite 2+ naktis, kad matytumėte ritmą',
  naps: 'Snūduriai',
  napsWeek: 'Snūduriai · ši savaitė',
  napsN: (n) => `Snūduriai: ${n}`,
  totalX: (x) => `${x} iš viso`,
  avgX: (x) => `vid. ${x}`,
  noNaps: 'Šią savaitę snūdurių nebuvo',
  logNap: 'Įrašyti snūdurį',
  debtOffset: 'Atimta iš miego skolos',
  bodyComp: 'Kūno sudėtis',
  bodyComp30: 'Kūno sudėtis · 30 d.',
  bodyFat: 'Riebalai',
  bmi: 'KMI',
  muscle: 'Raumenys',
  leanMass: 'Liesoji masė',
  chest: 'Krūtinė',
  waist: 'Liemuo',
  hip: 'Klubai',
  fatShort: (x) => `riebalai ${x}%`,
  muscleShort: (x) => `raumenys ${x}%`,
  waistShort: (x) => `liemuo ${x} cm`,
  inDays30: (x) => `${x} per 30 d.`,
  noComp: 'Dar nėra kūno matmenų',
  addMeasures: 'Pridėti matmenis',
  updateMeasures: 'Atnaujinti matmenis',
  restingEnergy: 'Ramybės energija',
  perDayBmr: 'per parą · BMR',
  kcalDay: 'kcal / para',
  bmrRow: (n) => `BMR ${n} kcal/para`,
  restingBmr: 'Ramybės energija · BMR',
  resting30: 'Ramybės energija · 30 d.',
  dailyLife: 'Kasdienė veikla',
  trainingToday: 'Treniruotė šiandien',
  totalEstimate: 'Paros įvertis',
  lifestyle: 'Gyvenimo būdas',
  lifestyleLevel: {
    sedentary: 'Sėslus',
    light: 'Lengvas',
    moderate: 'Vidutinis',
    active: 'Aktyvus',
  },
  fatPctShort: (x) => `${x}% riebalų`,
  noBmr: 'Reikia ūgio, amžiaus ir lyties',
  completeProfile: 'Užpildyti kūno profilį',
  physiqueGoal: 'Kūno tikslas',
  pctThere: (name, p) => `${name} · ${p}% kelio`,
  kgToGo: (x) => `liko ${x} kg`,
  onPace: (d) => `Tokiu tempu iki ${d}`,
  targetKg: (x) => `Tikslas ${x} kg`,
  overall: 'Bendrai',
  startedX: (d) => `pradėta ${d}`,
  weight: 'Svoris',
  now: 'dabar',
  noPhysique: 'Kūno tikslas nepasirinktas',
  pickPhysique: 'Pasirinkti kūno tikslą',
  setTarget: 'Nustatykite tikslinį svorį',
  adjustGoal: 'Keisti tikslą',
  reached: 'Tikslinis svoris pasiektas',
  restLog: 'Poilsis ir liga',
  rest30: 'Poilsis · 30 d.',
  restIllness30: 'Poilsis ir liga · 30 d.',
  daysOff: 'laisvų d.',
  streakKept: (n) => `Serija ${n} išsaugota ✓`,
  restSickOff: (r, s, o) => `${r} poils. · ${s} liga · ${o} laisv.`,
  last30Safe: (n) => `Paskutinės 30 d. · serija ${n} saugi ✓`,
  kindTrain: 'Trenir.',
  kindRest: 'Poils.',
  kindSick: 'Liga',
  kindOff: 'Laisv.',
  modeName: { active: 'Aktyvus poilsis', off: 'Laisva diena', illness: 'Liga' },
  noneBroke: 'Nė viena iš šių dienų nenutraukė serijos',
  logDay: 'Įrašyti dieną',
  noRest: 'Per 30 d. nieko neįrašyta',
};

const et: BodyStrings = {
  energyToday: 'Energia täna',
  burnedToday: 'Täna kulutatud',
  kcal: 'kcal',
  activeN: (n) => `${n} aktiivselt`,
  kcalToday: (n) => `${n} kcal täna`,
  activeResting: (a, r) => `${a} aktiivselt · ${r} puhkeolekus`,
  resting: 'Puhkeolek',
  workout: 'Treening',
  activities: 'Tegevused',
  total: 'Kokku',
  energyOn: (d) => `Energia · ${d}`,
  byHour: 'tundide kaupa',
  noEnergy: 'Energiaandmeid veel pole',
  noEnergySub: 'Sisesta kaal, et päeva hinnata',
  dayHistory: 'Päeva ajalugu',
  minN: (n) => `${n} min`,
  rehab: 'Taastus',
  rehabPlan: 'Taastusplaan',
  rehabOf: (part) => `Taastus · ${part}`,
  stageOf: (n, total) => `Etapp ${n}/${total}`,
  dayN: (n) => `päev ${n}`,
  goodCheckins: (n, need) => `${n}/${need} head check-ini järgmise etapini`,
  readyMoveUp: 'Valmis edasi liikuma',
  lastCheckin: (feel, date) => `Viimane check-in · ${feel} · ${date}`,
  checkinNext: 'Tee check-in pärast järgmist treeningut',
  protectedLoad: 'Kaitstud lihased · koormus',
  outOfTraining: 'väljas',
  noRehab: 'Aktiivset taastust pole',
  noRehabSub: 'Vigastus? Alusta juhendatud plaani',
  startRehab: 'Alusta taastusplaani',
  sleepDebt: 'Unevõlg',
  debtSub: (goal) => `alla ${goal} eesmärgi · 7 ööd`,
  debtRow: (goal, bed) => `7 ööd vs ${goal} · voodisse ${bed}`,
  debtRowNoPlan: (goal) => `7 ööd vs ${goal}`,
  debtKicker: 'Unevõlg · 7 ööd',
  goalX: (g) => `eesmärk ${g}`,
  bedByCut: (bed, cut) => `Mine magama ${bed}, et vähendada ${cut}`,
  vsLastWeek: (x) => `${x} vs eelmine nädal`,
  worstNight: (d) => `Halvim öö · ${d}`,
  avgSleep: 'Keskmine uni',
  napsCounted: 'Arvestatud uinakud',
  clearIn: (bed, n) => `Voodisse ${bed} · tasud ~${n} ööga`,
  planBedtime: 'Planeeri uneaeg',
  noDebt: 'Unevõlga pole',
  noDebtSub: 'Eesmärk täidetud viimasel 7 ööl',
  needNights: 'Sisesta paar ööd',
  bedtime: 'Uneaeg',
  bedtimeConsistency: 'Uneaja püsivus',
  spreadMin: (m) => `±${m} min`,
  spread: 'hajuvus',
  usualLate: (u, n) => (n > 0 ? `Tavaliselt ${u} · hiliseid: ${n}` : `Tavaliselt ${u}`),
  usualLast: (u, l) => `Tavaliselt ${u} · eile ${l}`,
  bedtime7: 'Uneaeg · 7 ööd',
  usualX: (u) => `tavaliselt ${u}`,
  lateNights: (n) => `hiliseid öid: ${n}`,
  latestX: (d) => `Hiliseim · ${d}`,
  avgWake: 'Kesk. ärkamine',
  onRhythm: 'Rütmis · 14 p',
  windDown: (x) => `Rahune maha kell ${x}`,
  setSchedule: 'Unegraafik',
  needTwoNights: 'Sisesta 2+ ööd, et rütmi näha',
  naps: 'Uinakud',
  napsWeek: 'Uinakud · see nädal',
  napsN: (n) => `Uinakuid: ${n}`,
  totalX: (x) => `${x} kokku`,
  avgX: (x) => `kesk. ${x}`,
  noNaps: 'Sel nädalal uinakuid pole',
  logNap: 'Lisa uinak',
  debtOffset: 'Unevõlast maha',
  bodyComp: 'Keha koostis',
  bodyComp30: 'Keha koostis · 30 p',
  bodyFat: 'Rasv',
  bmi: 'KMI',
  muscle: 'Lihased',
  leanMass: 'Rasvavaba mass',
  chest: 'Rind',
  waist: 'Talje',
  hip: 'Puusad',
  fatShort: (x) => `rasv ${x}%`,
  muscleShort: (x) => `lihased ${x}%`,
  waistShort: (x) => `talje ${x} cm`,
  inDays30: (x) => `${x} 30 p jooksul`,
  noComp: 'Kehamõõte veel pole',
  addMeasures: 'Lisa mõõdud',
  updateMeasures: 'Uuenda mõõte',
  restingEnergy: 'Puhkeenergia',
  perDayBmr: 'ööpäevas · BMR',
  kcalDay: 'kcal / ööp',
  bmrRow: (n) => `BMR ${n} kcal/ööp`,
  restingBmr: 'Puhkeenergia · BMR',
  resting30: 'Puhkeenergia · 30 p',
  dailyLife: 'Igapäevaelu',
  trainingToday: 'Treening täna',
  totalEstimate: 'Ööpäeva hinnang',
  lifestyle: 'Eluviis',
  lifestyleLevel: {
    sedentary: 'Istuv',
    light: 'Kerge',
    moderate: 'Mõõdukas',
    active: 'Aktiivne',
  },
  fatPctShort: (x) => `${x}% rasva`,
  noBmr: 'Vaja on pikkust, vanust ja sugu',
  completeProfile: 'Täida kehaprofiil',
  physiqueGoal: 'Kehaeesmärk',
  pctThere: (name, p) => `${name} · ${p}% teest`,
  kgToGo: (x) => `veel ${x} kg`,
  onPace: (d) => `Selle tempoga ${d}`,
  targetKg: (x) => `Eesmärk ${x} kg`,
  overall: 'Kokku',
  startedX: (d) => `algus ${d}`,
  weight: 'Kaal',
  now: 'praegu',
  noPhysique: 'Kehaeesmärki pole valitud',
  pickPhysique: 'Vali kehaeesmärk',
  setTarget: 'Määra sihtkaal',
  adjustGoal: 'Muuda eesmärki',
  reached: 'Sihtkaal saavutatud',
  restLog: 'Puhkus ja haigus',
  rest30: 'Puhkus · 30 p',
  restIllness30: 'Puhkus ja haigus · 30 p',
  daysOff: 'vaba päeva',
  streakKept: (n) => `Seeria ${n} säilis ✓`,
  restSickOff: (r, s, o) => `${r} puhk. · ${s} haige · ${o} vaba`,
  last30Safe: (n) => `Viimased 30 p · seeria ${n} ohutu ✓`,
  kindTrain: 'Trenn',
  kindRest: 'Puhk.',
  kindSick: 'Haige',
  kindOff: 'Vaba',
  modeName: { active: 'Aktiivne puhkus', off: 'Vaba päev', illness: 'Haigus' },
  noneBroke: 'Ükski neist päevadest ei katkestanud seeriat',
  logDay: 'Lisa päev',
  noRest: '30 päeva jooksul pole midagi sisestatud',
};

const DICT: Record<LocaleId, BodyStrings> = { en, uk, pl, lt, et };

export function bs(locale: LocaleId): BodyStrings {
  return DICT[locale];
}
