/** Copy of the Calendar widgets (calendar.tsx), all five locales. */
import type { LocaleId } from '../../i18n';

const en = {
  calendar: 'Calendar',
  yearPixels: 'Year in pixels',
  last30: 'Last 30 days',
  daysTrained: 'days trained',
  trainedN: (n: number) => `${n} trained`,
  restN: (n: number) => `${n} rest`,
  sickN: (n: number) => `${n} sick`,
  offN: (n: number) => `${n} off`,
  injuryN: (n: number) => `${n} injury`,
  prsN: (n: number) => (n === 1 ? '1 PR' : `${n} PRs`),
  loggedN: (n: number) => `${n} logged`,
  thisWeekTrained: (n: number) => `${n} trained this week`,
  workout: 'Workout',
  activity: 'Activity',
  sleep: 'Sleep',
  pr: 'PR',
  rest: 'Rest',
  sick: 'Sick',
  off: 'Day off',
  injury: 'Injury',
  planned: 'Planned',
  restSick: 'Rest · sick',
  trained: 'Trained',
  activityOnly: 'Activity only',
  openCalendar: 'Open calendar',
  monthSummary: (month: string, n: number, t: string) => `${month}: ${n} trained · ${t} t`,
  inPixels: (y: number) => `${y} in pixels`,
  everyDay: (y: number) => `${y} · every day`,
  loggedOf: (a: number, b: number) => `${a} logged of ${b}`,
  days: 'days',
  loggedTrained: (n: number) => `logged · ${n} trained`,
  daysLoggedYear: (n: number, y: number) => `${n} days logged · ${y}`,
  longestStreak: (n: number) => `longest streak ${n}`,
  loggedPct: (p: number) => `logged · ${p}%`,
  pixelsTitle: (y: number) => `Year in pixels · ${y}`,
  nothingYet: 'Nothing logged yet',
  fillHint: 'Log a workout, activity or sleep to fill it',
  todayRinged: 'Today ringed',
};
export type CalendarStrings = typeof en;

const uk: CalendarStrings = {
  calendar: 'Календар',
  yearPixels: 'Рік у пікселях',
  last30: 'Останні 30 днів',
  daysTrained: 'днів тренувань',
  trainedN: (n) => `${n} тренувань`,
  restN: (n) => `${n} відпочинку`,
  sickN: (n) => `${n} хвороби`,
  offN: (n) => `${n} вихідних`,
  injuryN: (n) => `${n} травми`,
  prsN: (n) => `${n} PR`,
  loggedN: (n) => `${n} залоговано`,
  thisWeekTrained: (n) => `${n} тренувань цього тижня`,
  workout: 'Тренування',
  activity: 'Активність',
  sleep: 'Сон',
  pr: 'PR',
  rest: 'Відпочинок',
  sick: 'Хвороба',
  off: 'Вихідний',
  injury: 'Травма',
  planned: 'Заплановано',
  restSick: 'Відпочинок · хвороба',
  trained: 'Тренування',
  activityOnly: 'Лише активність',
  openCalendar: 'Відкрити календар',
  monthSummary: (month, n, t) => `${month}: ${n} тренувань · ${t} т`,
  inPixels: (y) => `${y} у пікселях`,
  everyDay: (y) => `${y} · кожен день`,
  loggedOf: (a, b) => `${a} залоговано з ${b}`,
  days: 'днів',
  loggedTrained: (n) => `залоговано · ${n} тренувань`,
  daysLoggedYear: (n, y) => `${n} днів залоговано · ${y}`,
  longestStreak: (n) => `найдовша серія ${n}`,
  loggedPct: (p) => `залоговано · ${p}%`,
  pixelsTitle: (y) => `Рік у пікселях · ${y}`,
  nothingYet: 'Ще нічого не залоговано',
  fillHint: 'Залогуй тренування, активність чи сон, щоб заповнити',
  todayRinged: 'Сьогодні в рамці',
};

const pl: CalendarStrings = {
  calendar: 'Kalendarz',
  yearPixels: 'Rok w pikselach',
  last30: 'Ostatnie 30 dni',
  daysTrained: 'dni treningowych',
  trainedN: (n) => `${n} treningów`,
  restN: (n) => `${n} odpoczynku`,
  sickN: (n) => `${n} choroby`,
  offN: (n) => `${n} wolnych`,
  injuryN: (n) => `${n} kontuzji`,
  prsN: (n) => `${n} PR`,
  loggedN: (n) => `${n} zapisanych`,
  thisWeekTrained: (n) => `${n} treningów w tym tygodniu`,
  workout: 'Trening',
  activity: 'Aktywność',
  sleep: 'Sen',
  pr: 'PR',
  rest: 'Odpoczynek',
  sick: 'Choroba',
  off: 'Dzień wolny',
  injury: 'Kontuzja',
  planned: 'Zaplanowane',
  restSick: 'Odpoczynek · choroba',
  trained: 'Trening',
  activityOnly: 'Tylko aktywność',
  openCalendar: 'Otwórz kalendarz',
  monthSummary: (month, n, t) => `${month}: ${n} treningów · ${t} t`,
  inPixels: (y) => `${y} w pikselach`,
  everyDay: (y) => `${y} · każdy dzień`,
  loggedOf: (a, b) => `${a} zapisanych z ${b}`,
  days: 'dni',
  loggedTrained: (n) => `zapisanych · ${n} treningów`,
  daysLoggedYear: (n, y) => `${n} dni zapisanych · ${y}`,
  longestStreak: (n) => `najdłuższa seria ${n}`,
  loggedPct: (p) => `zapisanych · ${p}%`,
  pixelsTitle: (y) => `Rok w pikselach · ${y}`,
  nothingYet: 'Jeszcze nic nie zapisano',
  fillHint: 'Zapisz trening, aktywność lub sen, aby go wypełnić',
  todayRinged: 'Dziś w ramce',
};

const lt: CalendarStrings = {
  calendar: 'Kalendorius',
  yearPixels: 'Metai pikseliais',
  last30: 'Paskutinės 30 dienų',
  daysTrained: 'treniruočių dienos',
  trainedN: (n) => `${n} treniruotės`,
  restN: (n) => `${n} poilsio`,
  sickN: (n) => `${n} ligos`,
  offN: (n) => `${n} laisvos`,
  injuryN: (n) => `${n} traumos`,
  prsN: (n) => `${n} PR`,
  loggedN: (n) => `${n} įrašyta`,
  thisWeekTrained: (n) => `${n} treniruotės šią savaitę`,
  workout: 'Treniruotė',
  activity: 'Veikla',
  sleep: 'Miegas',
  pr: 'PR',
  rest: 'Poilsis',
  sick: 'Liga',
  off: 'Laisva diena',
  injury: 'Trauma',
  planned: 'Suplanuota',
  restSick: 'Poilsis · liga',
  trained: 'Treniruotė',
  activityOnly: 'Tik veikla',
  openCalendar: 'Atidaryti kalendorių',
  monthSummary: (month, n, t) => `${month}: ${n} treniruotės · ${t} t`,
  inPixels: (y) => `${y} pikseliais`,
  everyDay: (y) => `${y} · kiekviena diena`,
  loggedOf: (a, b) => `${a} įrašyta iš ${b}`,
  days: 'dienų',
  loggedTrained: (n) => `įrašyta · ${n} treniruotės`,
  daysLoggedYear: (n, y) => `${n} dienų įrašyta · ${y}`,
  longestStreak: (n) => `ilgiausia serija ${n}`,
  loggedPct: (p) => `įrašyta · ${p}%`,
  pixelsTitle: (y) => `Metai pikseliais · ${y}`,
  nothingYet: 'Dar nieko neįrašyta',
  fillHint: 'Įrašyk treniruotę, veiklą ar miegą, kad užpildytum',
  todayRinged: 'Šiandien apibrėžta',
};

const et: CalendarStrings = {
  calendar: 'Kalender',
  yearPixels: 'Aasta pikslites',
  last30: 'Viimased 30 päeva',
  daysTrained: 'treeningpäeva',
  trainedN: (n) => `${n} treeningut`,
  restN: (n) => `${n} puhkust`,
  sickN: (n) => `${n} haigust`,
  offN: (n) => `${n} vaba`,
  injuryN: (n) => `${n} vigastust`,
  prsN: (n) => `${n} PR`,
  loggedN: (n) => `${n} logitud`,
  thisWeekTrained: (n) => `${n} treeningut sel nädalal`,
  workout: 'Treening',
  activity: 'Tegevus',
  sleep: 'Uni',
  pr: 'PR',
  rest: 'Puhkus',
  sick: 'Haige',
  off: 'Vaba päev',
  injury: 'Vigastus',
  planned: 'Planeeritud',
  restSick: 'Puhkus · haige',
  trained: 'Treening',
  activityOnly: 'Ainult tegevus',
  openCalendar: 'Ava kalender',
  monthSummary: (month, n, t) => `${month}: ${n} treeningut · ${t} t`,
  inPixels: (y) => `${y} pikslites`,
  everyDay: (y) => `${y} · iga päev`,
  loggedOf: (a, b) => `${a} logitud ${b}-st`,
  days: 'päeva',
  loggedTrained: (n) => `logitud · ${n} treeningut`,
  daysLoggedYear: (n, y) => `${n} päeva logitud · ${y}`,
  longestStreak: (n) => `pikim seeria ${n}`,
  loggedPct: (p) => `logitud · ${p}%`,
  pixelsTitle: (y) => `Aasta pikslites · ${y}`,
  nothingYet: 'Veel pole midagi logitud',
  fillHint: 'Logi treening, tegevus või uni, et seda täita',
  todayRinged: 'Täna raamitud',
};

const DICT: Record<LocaleId, CalendarStrings> = { en, uk, pl, lt, et };
export function cs(locale: LocaleId): CalendarStrings {
  return DICT[locale];
}
