/** Copy of the Cardio widgets (cardio.tsx), all five locales. */
import type { LocaleId } from '../../i18n';

const en = {
  distanceWeek: 'Distance this week',
  lastRoute: 'Last route',
  paceTrend: 'Pace trend',
  cardioMachine: 'Cardio machine',
  activeMinutes: 'Active minutes',
  favSport: 'Favourite sport',
  recoveryRituals: 'Recovery rituals',
  activityKcal: 'Activity calories',
  thisWeek: 'This week',
  kmThisWeek: (x: string) => `${x} km this week`,
  vsLastWeek: (x: string) => `${x} vs last week`,
  distanceKicker: 'Distance · this week',
  distanceRange: (r: string) => `Distance · ${r}`,
  lastWeek: (x: string) => `last week ${x}`,
  gymCardio: 'Gym cardio',
  noDistance: 'No distance this week',
  distanceHint: 'Log a run, walk or ride',
  logActivity: 'Log activity',
  today: 'Today',
  yesterday: 'Yesterday',
  lastRouteKicker: (type: string) => `Last route · ${type}`,
  distance: 'Distance',
  time: 'Time',
  pace: 'Pace',
  speed: 'Speed',
  burned: 'Burned',
  noRoute: 'No run, walk or ride yet',
  paceRuns: (n: number) => `Pace · ${n} runs`,
  paceLastN: (n: number) => `Pace · last ${n} runs`,
  faster: (s: number) => `↑ ${s} s faster`,
  slower: (s: number) => `↓ ${s} s slower`,
  fasterOver: (s: number, n: number) => `↑ ${s} s faster over ${n} runs`,
  slowerOver: (s: number, n: number) => `↓ ${s} s slower over ${n} runs`,
  lastRun: 'last run',
  avg: (x: string) => `avg ${x}`,
  best: 'best',
  noRuns: 'Log 2 runs with distance to see your pace',
  logRun: 'Log a run',
  atGym: (x: string) => `at ${x}`,
  pbPace: 'PB pace',
  machineTrend: (m: string, n: number) => `${m} · ${n} sessions`,
  startCardio: 'Start cardio session',
  noMachine: 'No machine cardio yet',
  noMachineHint: 'Add a treadmill, rower or bike to a session',
  activeWeek: 'Active min · week',
  ofGoal: (g: number) => `of ${g} min · week`,
  activeOf: (a: number, g: number) => `${a} / ${g} active min`,
  toGo: (n: number) => `${n} min to go`,
  daysLeft: (n: number) => (n === 1 ? '1 day left' : `${n} days left`),
  perDay: (n: number) => `~${n} min/day`,
  goalReached: 'Weekly goal reached',
  activeRange: (r: string) => `Active minutes · ${r}`,
  who: (g: number) => `WHO ${g}`,
  of: (g: number) => `of ${g}`,
  topSport30: 'Top sport · 30 d',
  timesTotal: (n: number, d: string) => `${n}× · ${d} total`,
  times30: (x: string, n: number) => `${x} · ${n}× in 30 days`,
  next: (x: string) => `Next: ${x}`,
  onlyOne: 'Your only sport this month',
  topSports30: 'Top sports · 30 days',
  sessionsN: (n: number) => (n === 1 ? '1 session' : `${n} sessions`),
  favKicker: 'Favourite sport · 30 days',
  usuallyOn: (d: string) => `Usually on ${d}`,
  seeAll: 'See all activities',
  noSport: 'No activities in 30 days',
  noSportHint: 'Log a sport or a cardio session',
  recoveryMonth: (m: string) => `Recovery · ${m}`,
  recoverySessions: (n: number) => (n === 1 ? '1 recovery session' : `${n} recovery sessions`),
  lastWas: (x: string, when: string) => `Last: ${x} · ${when}`,
  ritualsMonth: (m: string) => `Recovery rituals · ${m}`,
  totalN: (n: number) => `${n} total`,
  moreThan: (n: number, m: string) => `↑ ${n} more than ${m}`,
  fewerThan: (n: number, m: string) => `↓ ${n} fewer than ${m}`,
  sameAs: (m: string) => `Same as ${m}`,
  logRecovery: 'Log recovery',
  noRecovery: 'No sauna, cold or massage this month',
  activitiesWeek: 'Activities · week',
  kcalFromAct: (x: string) => `${x} kcal from activities`,
  topThisWeek: (x: string) => `This week · top: ${x}`,
  kcalKicker: 'Activity calories · this week',
  kcalRange: (r: string) => `Activity calories · ${r}`,
  openDayHistory: 'Open day history',
  noKcal: 'No activities this week',
  sessionsUnit: 'sessions',
};
export type CardioStrings = typeof en;

const uk: CardioStrings = {
  distanceWeek: 'Дистанція за тиждень',
  lastRoute: 'Останній маршрут',
  paceTrend: 'Динаміка темпу',
  cardioMachine: 'Кардіотренажер',
  activeMinutes: 'Активні хвилини',
  favSport: 'Улюблений спорт',
  recoveryRituals: 'Ритуали відновлення',
  activityKcal: 'Калорії активностей',
  thisWeek: 'Цей тиждень',
  kmThisWeek: (x) => `${x} км цього тижня`,
  vsLastWeek: (x) => `${x} до минулого тижня`,
  distanceKicker: 'Дистанція · цей тиждень',
  distanceRange: (r) => `Дистанція · ${r}`,
  lastWeek: (x) => `минулого тижня ${x}`,
  gymCardio: 'Кардіо в залі',
  noDistance: 'Цього тижня без дистанції',
  distanceHint: 'Залогуй біг, ходьбу чи вело',
  logActivity: 'Залогувати активність',
  today: 'Сьогодні',
  yesterday: 'Вчора',
  lastRouteKicker: (type) => `Останній маршрут · ${type}`,
  distance: 'Дистанція',
  time: 'Час',
  pace: 'Темп',
  speed: 'Швидкість',
  burned: 'Спалено',
  noRoute: 'Ще немає бігу, ходьби чи вело',
  paceRuns: (n) => `Темп · ${n} пробіжок`,
  paceLastN: (n) => `Темп · останні ${n} пробіжок`,
  faster: (s) => `↑ на ${s} с швидше`,
  slower: (s) => `↓ на ${s} с повільніше`,
  fasterOver: (s, n) => `↑ на ${s} с швидше за ${n} пробіжок`,
  slowerOver: (s, n) => `↓ на ${s} с повільніше за ${n} пробіжок`,
  lastRun: 'остання пробіжка',
  avg: (x) => `середній ${x}`,
  best: 'найкращий',
  noRuns: 'Залогуй 2 пробіжки з дистанцією, щоб побачити темп',
  logRun: 'Залогувати біг',
  atGym: (x) => `у ${x}`,
  pbPace: 'Рекордний темп',
  machineTrend: (m, n) => `${m} · ${n} сесій`,
  startCardio: 'Почати кардіосесію',
  noMachine: 'Ще немає кардіо на тренажерах',
  noMachineHint: 'Додай доріжку, гребний чи велотренажер у сесію',
  activeWeek: 'Активні хв · тиждень',
  ofGoal: (g) => `з ${g} хв · тиждень`,
  activeOf: (a, g) => `${a} / ${g} активних хв`,
  toGo: (n) => `ще ${n} хв`,
  daysLeft: (n) => `залишилось днів: ${n}`,
  perDay: (n) => `~${n} хв/день`,
  goalReached: 'Тижневу ціль досягнуто',
  activeRange: (r) => `Активні хвилини · ${r}`,
  who: (g) => `ВООЗ ${g}`,
  of: (g) => `з ${g}`,
  topSport30: 'Топ-спорт · 30 дн',
  timesTotal: (n, d) => `${n}× · ${d} разом`,
  times30: (x, n) => `${x} · ${n}× за 30 днів`,
  next: (x) => `Далі: ${x}`,
  onlyOne: 'Єдиний спорт цього місяця',
  topSports30: 'Топ-спорт · 30 днів',
  sessionsN: (n) => `${n} сесій`,
  favKicker: 'Улюблений спорт · 30 днів',
  usuallyOn: (d) => `Зазвичай у ${d}`,
  seeAll: 'Усі активності',
  noSport: 'Немає активностей за 30 днів',
  noSportHint: 'Залогуй спорт чи кардіосесію',
  recoveryMonth: (m) => `Відновлення · ${m}`,
  recoverySessions: (n) => `${n} сесій відновлення`,
  lastWas: (x, when) => `Остання: ${x} · ${when}`,
  ritualsMonth: (m) => `Ритуали відновлення · ${m}`,
  totalN: (n) => `${n} разом`,
  moreThan: (n, m) => `↑ на ${n} більше, ніж ${m}`,
  fewerThan: (n, m) => `↓ на ${n} менше, ніж ${m}`,
  sameAs: (m) => `Як у ${m}`,
  logRecovery: 'Залогувати відновлення',
  noRecovery: 'Цього місяця без сауни, холоду чи масажу',
  activitiesWeek: 'Активності · тиждень',
  kcalFromAct: (x) => `${x} ккал з активностей`,
  topThisWeek: (x) => `Цей тиждень · топ: ${x}`,
  kcalKicker: 'Калорії активностей · тиждень',
  kcalRange: (r) => `Калорії активностей · ${r}`,
  openDayHistory: 'Відкрити історію днів',
  noKcal: 'Цього тижня без активностей',
  sessionsUnit: 'сесій',
};

const pl: CardioStrings = {
  distanceWeek: 'Dystans w tym tygodniu',
  lastRoute: 'Ostatnia trasa',
  paceTrend: 'Trend tempa',
  cardioMachine: 'Maszyna cardio',
  activeMinutes: 'Aktywne minuty',
  favSport: 'Ulubiony sport',
  recoveryRituals: 'Rytuały regeneracji',
  activityKcal: 'Kalorie z aktywności',
  thisWeek: 'Ten tydzień',
  kmThisWeek: (x) => `${x} km w tym tygodniu`,
  vsLastWeek: (x) => `${x} vs poprzedni tydzień`,
  distanceKicker: 'Dystans · ten tydzień',
  distanceRange: (r) => `Dystans · ${r}`,
  lastWeek: (x) => `poprzedni tydzień ${x}`,
  gymCardio: 'Cardio na siłowni',
  noDistance: 'Brak dystansu w tym tygodniu',
  distanceHint: 'Zapisz bieg, spacer lub jazdę',
  logActivity: 'Zapisz aktywność',
  today: 'Dziś',
  yesterday: 'Wczoraj',
  lastRouteKicker: (type) => `Ostatnia trasa · ${type}`,
  distance: 'Dystans',
  time: 'Czas',
  pace: 'Tempo',
  speed: 'Prędkość',
  burned: 'Spalone',
  noRoute: 'Brak biegu, spaceru czy jazdy',
  paceRuns: (n) => `Tempo · ${n} biegów`,
  paceLastN: (n) => `Tempo · ostatnie ${n} biegów`,
  faster: (s) => `↑ ${s} s szybciej`,
  slower: (s) => `↓ ${s} s wolniej`,
  fasterOver: (s, n) => `↑ ${s} s szybciej w ${n} biegach`,
  slowerOver: (s, n) => `↓ ${s} s wolniej w ${n} biegach`,
  lastRun: 'ostatni bieg',
  avg: (x) => `śr. ${x}`,
  best: 'najlepszy',
  noRuns: 'Zapisz 2 biegi z dystansem, aby zobaczyć tempo',
  logRun: 'Zapisz bieg',
  atGym: (x) => `w ${x}`,
  pbPace: 'Rekordowe tempo',
  machineTrend: (m, n) => `${m} · ${n} sesji`,
  startCardio: 'Rozpocznij sesję cardio',
  noMachine: 'Brak cardio na maszynach',
  noMachineHint: 'Dodaj bieżnię, wioślarza lub rower do sesji',
  activeWeek: 'Aktywne min · tydzień',
  ofGoal: (g) => `z ${g} min · tydzień`,
  activeOf: (a, g) => `${a} / ${g} aktywnych min`,
  toGo: (n) => `jeszcze ${n} min`,
  daysLeft: (n) => (n === 1 ? 'został 1 dzień' : `zostało dni: ${n}`),
  perDay: (n) => `~${n} min/dzień`,
  goalReached: 'Cel tygodnia osiągnięty',
  activeRange: (r) => `Aktywne minuty · ${r}`,
  who: (g) => `WHO ${g}`,
  of: (g) => `z ${g}`,
  topSport30: 'Top sport · 30 dni',
  timesTotal: (n, d) => `${n}× · ${d} łącznie`,
  times30: (x, n) => `${x} · ${n}× w 30 dni`,
  next: (x) => `Dalej: ${x}`,
  onlyOne: 'Jedyny sport w tym miesiącu',
  topSports30: 'Top sporty · 30 dni',
  sessionsN: (n) => `${n} sesji`,
  favKicker: 'Ulubiony sport · 30 dni',
  usuallyOn: (d) => `Zwykle w ${d}`,
  seeAll: 'Wszystkie aktywności',
  noSport: 'Brak aktywności w 30 dni',
  noSportHint: 'Zapisz sport lub sesję cardio',
  recoveryMonth: (m) => `Regeneracja · ${m}`,
  recoverySessions: (n) => `${n} sesji regeneracji`,
  lastWas: (x, when) => `Ostatnio: ${x} · ${when}`,
  ritualsMonth: (m) => `Rytuały regeneracji · ${m}`,
  totalN: (n) => `${n} łącznie`,
  moreThan: (n, m) => `↑ o ${n} więcej niż ${m}`,
  fewerThan: (n, m) => `↓ o ${n} mniej niż ${m}`,
  sameAs: (m) => `Tyle samo co ${m}`,
  logRecovery: 'Zapisz regenerację',
  noRecovery: 'Brak sauny, zimna czy masażu w tym miesiącu',
  activitiesWeek: 'Aktywności · tydzień',
  kcalFromAct: (x) => `${x} kcal z aktywności`,
  topThisWeek: (x) => `Ten tydzień · top: ${x}`,
  kcalKicker: 'Kalorie z aktywności · tydzień',
  kcalRange: (r) => `Kalorie z aktywności · ${r}`,
  openDayHistory: 'Otwórz historię dni',
  noKcal: 'Brak aktywności w tym tygodniu',
  sessionsUnit: 'sesji',
};

const lt: CardioStrings = {
  distanceWeek: 'Atstumas šią savaitę',
  lastRoute: 'Paskutinis maršrutas',
  paceTrend: 'Tempo tendencija',
  cardioMachine: 'Kardio treniruoklis',
  activeMinutes: 'Aktyvios minutės',
  favSport: 'Mėgstamiausia sporto šaka',
  recoveryRituals: 'Atsigavimo ritualai',
  activityKcal: 'Veiklos kalorijos',
  thisWeek: 'Ši savaitė',
  kmThisWeek: (x) => `${x} km šią savaitę`,
  vsLastWeek: (x) => `${x} lyginant su praėjusia savaite`,
  distanceKicker: 'Atstumas · ši savaitė',
  distanceRange: (r) => `Atstumas · ${r}`,
  lastWeek: (x) => `praėjusią savaitę ${x}`,
  gymCardio: 'Kardio sporto salėje',
  noDistance: 'Šią savaitę atstumo nėra',
  distanceHint: 'Įrašyk bėgimą, ėjimą ar važiavimą',
  logActivity: 'Įrašyti veiklą',
  today: 'Šiandien',
  yesterday: 'Vakar',
  lastRouteKicker: (type) => `Paskutinis maršrutas · ${type}`,
  distance: 'Atstumas',
  time: 'Laikas',
  pace: 'Tempas',
  speed: 'Greitis',
  burned: 'Sudeginta',
  noRoute: 'Dar nėra bėgimo, ėjimo ar važiavimo',
  paceRuns: (n) => `Tempas · ${n} bėgimai`,
  paceLastN: (n) => `Tempas · paskutiniai ${n} bėgimai`,
  faster: (s) => `↑ ${s} s greičiau`,
  slower: (s) => `↓ ${s} s lėčiau`,
  fasterOver: (s, n) => `↑ ${s} s greičiau per ${n} bėgimus`,
  slowerOver: (s, n) => `↓ ${s} s lėčiau per ${n} bėgimus`,
  lastRun: 'paskutinis bėgimas',
  avg: (x) => `vid. ${x}`,
  best: 'geriausias',
  noRuns: 'Įrašyk 2 bėgimus su atstumu, kad matytum tempą',
  logRun: 'Įrašyti bėgimą',
  atGym: (x) => `${x}`,
  pbPace: 'Rekordinis tempas',
  machineTrend: (m, n) => `${m} · ${n} sesijos`,
  startCardio: 'Pradėti kardio sesiją',
  noMachine: 'Dar nėra kardio ant treniruoklių',
  noMachineHint: 'Pridėk bėgimo takelį, irklavimo ar dviračio treniruoklį',
  activeWeek: 'Aktyvios min · savaitė',
  ofGoal: (g) => `iš ${g} min · savaitė`,
  activeOf: (a, g) => `${a} / ${g} aktyvių min`,
  toGo: (n) => `liko ${n} min`,
  daysLeft: (n) => `liko dienų: ${n}`,
  perDay: (n) => `~${n} min/d.`,
  goalReached: 'Savaitės tikslas pasiektas',
  activeRange: (r) => `Aktyvios minutės · ${r}`,
  who: (g) => `PSO ${g}`,
  of: (g) => `iš ${g}`,
  topSport30: 'Top sportas · 30 d.',
  timesTotal: (n, d) => `${n}× · iš viso ${d}`,
  times30: (x, n) => `${x} · ${n}× per 30 d.`,
  next: (x) => `Toliau: ${x}`,
  onlyOne: 'Vienintelė šio mėnesio sporto šaka',
  topSports30: 'Top sportas · 30 dienų',
  sessionsN: (n) => `${n} sesijos`,
  favKicker: 'Mėgstamiausia sporto šaka · 30 dienų',
  usuallyOn: (d) => `Dažniausiai: ${d}`,
  seeAll: 'Visos veiklos',
  noSport: 'Per 30 dienų veiklų nėra',
  noSportHint: 'Įrašyk sportą ar kardio sesiją',
  recoveryMonth: (m) => `Atsigavimas · ${m}`,
  recoverySessions: (n) => `${n} atsigavimo sesijos`,
  lastWas: (x, when) => `Paskutinė: ${x} · ${when}`,
  ritualsMonth: (m) => `Atsigavimo ritualai · ${m}`,
  totalN: (n) => `iš viso ${n}`,
  moreThan: (n, m) => `↑ ${n} daugiau nei ${m}`,
  fewerThan: (n, m) => `↓ ${n} mažiau nei ${m}`,
  sameAs: (m) => `Tiek pat kaip ${m}`,
  logRecovery: 'Įrašyti atsigavimą',
  noRecovery: 'Šį mėnesį nei pirties, nei šalčio, nei masažo',
  activitiesWeek: 'Veiklos · savaitė',
  kcalFromAct: (x) => `${x} kcal iš veiklų`,
  topThisWeek: (x) => `Ši savaitė · top: ${x}`,
  kcalKicker: 'Veiklos kalorijos · ši savaitė',
  kcalRange: (r) => `Veiklos kalorijos · ${r}`,
  openDayHistory: 'Atidaryti dienų istoriją',
  noKcal: 'Šią savaitę veiklų nėra',
  sessionsUnit: 'sesijos',
};

const et: CardioStrings = {
  distanceWeek: 'Selle nädala distants',
  lastRoute: 'Viimane marsruut',
  paceTrend: 'Tempo trend',
  cardioMachine: 'Kardiomasin',
  activeMinutes: 'Aktiivsed minutid',
  favSport: 'Lemmikspordiala',
  recoveryRituals: 'Taastumisrituaalid',
  activityKcal: 'Tegevuste kalorid',
  thisWeek: 'See nädal',
  kmThisWeek: (x) => `${x} km sel nädalal`,
  vsLastWeek: (x) => `${x} vs eelmine nädal`,
  distanceKicker: 'Distants · see nädal',
  distanceRange: (r) => `Distants · ${r}`,
  lastWeek: (x) => `eelmine nädal ${x}`,
  gymCardio: 'Kardio jõusaalis',
  noDistance: 'Sel nädalal distantsi pole',
  distanceHint: 'Logi jooks, kõnd või sõit',
  logActivity: 'Logi tegevus',
  today: 'Täna',
  yesterday: 'Eile',
  lastRouteKicker: (type) => `Viimane marsruut · ${type}`,
  distance: 'Distants',
  time: 'Aeg',
  pace: 'Tempo',
  speed: 'Kiirus',
  burned: 'Kulutatud',
  noRoute: 'Veel pole jooksu, kõndi ega sõitu',
  paceRuns: (n) => `Tempo · ${n} jooksu`,
  paceLastN: (n) => `Tempo · viimased ${n} jooksu`,
  faster: (s) => `↑ ${s} s kiiremini`,
  slower: (s) => `↓ ${s} s aeglasemalt`,
  fasterOver: (s, n) => `↑ ${s} s kiiremini ${n} jooksuga`,
  slowerOver: (s, n) => `↓ ${s} s aeglasemalt ${n} jooksuga`,
  lastRun: 'viimane jooks',
  avg: (x) => `keskm. ${x}`,
  best: 'parim',
  noRuns: 'Logi 2 distantsiga jooksu, et tempot näha',
  logRun: 'Logi jooks',
  atGym: (x) => `· ${x}`,
  pbPace: 'Rekordtempo',
  machineTrend: (m, n) => `${m} · ${n} sessiooni`,
  startCardio: 'Alusta kardiosessiooni',
  noMachine: 'Masinakardiot veel pole',
  noMachineHint: 'Lisa sessiooni jooksulint, sõudemasin või ratas',
  activeWeek: 'Aktiivsed min · nädal',
  ofGoal: (g) => `${g} min-st · nädal`,
  activeOf: (a, g) => `${a} / ${g} aktiivset min`,
  toGo: (n) => `veel ${n} min`,
  daysLeft: (n) => `päevi jäänud: ${n}`,
  perDay: (n) => `~${n} min/päevas`,
  goalReached: 'Nädala eesmärk täidetud',
  activeRange: (r) => `Aktiivsed minutid · ${r}`,
  who: (g) => `WHO ${g}`,
  of: (g) => `${g}-st`,
  topSport30: 'Top spordiala · 30 p',
  timesTotal: (n, d) => `${n}× · kokku ${d}`,
  times30: (x, n) => `${x} · ${n}× 30 päevaga`,
  next: (x) => `Järgmised: ${x}`,
  onlyOne: 'Selle kuu ainus spordiala',
  topSports30: 'Top spordialad · 30 päeva',
  sessionsN: (n) => `${n} sessiooni`,
  favKicker: 'Lemmikspordiala · 30 päeva',
  usuallyOn: (d) => `Tavaliselt: ${d}`,
  seeAll: 'Kõik tegevused',
  noSport: '30 päeva jooksul tegevusi pole',
  noSportHint: 'Logi spordiala või kardiosessioon',
  recoveryMonth: (m) => `Taastumine · ${m}`,
  recoverySessions: (n) => `${n} taastumissessiooni`,
  lastWas: (x, when) => `Viimane: ${x} · ${when}`,
  ritualsMonth: (m) => `Taastumisrituaalid · ${m}`,
  totalN: (n) => `kokku ${n}`,
  moreThan: (n, m) => `↑ ${n} rohkem kui ${m}`,
  fewerThan: (n, m) => `↓ ${n} vähem kui ${m}`,
  sameAs: (m) => `Sama palju kui ${m}`,
  logRecovery: 'Logi taastumine',
  noRecovery: 'Sel kuul pole sauna, külma ega massaaži',
  activitiesWeek: 'Tegevused · nädal',
  kcalFromAct: (x) => `${x} kcal tegevustest`,
  topThisWeek: (x) => `See nädal · top: ${x}`,
  kcalKicker: 'Tegevuste kalorid · see nädal',
  kcalRange: (r) => `Tegevuste kalorid · ${r}`,
  openDayHistory: 'Ava päevade ajalugu',
  noKcal: 'Sel nädalal tegevusi pole',
  sessionsUnit: 'sessiooni',
};

const DICT: Record<LocaleId, CardioStrings> = { en, uk, pl, lt, et };
export function cds(locale: LocaleId): CardioStrings {
  return DICT[locale];
}
