/**
 * Copy of the Discover & daily widgets (design L4), all five locales. Typed from
 * `en`, so a missing key in any locale fails the build. Muscle / activity names
 * and moon phases come from the main dictionary.
 */
import type { LocaleId } from '../../i18n';

interface Tip {
  /** The lift the tip is about (display name). */
  lift: string;
  /** Short headline (S / M). */
  short: string;
  /** Full tip (L / XL). */
  text: string;
  /** Why it matters (XL box). */
  why: string;
  checks: [string, string, string];
}

const en = {
  names: {
    exercise: 'Exercise of the day',
    tip: 'Tip of the day',
    kit: 'Kit spotlight',
    onThisDay: 'On this day',
    lifetime: 'Lifetime lifted',
    nightSky: 'Night sky',
    challenge: 'Challenge to try',
    restIdea: 'Rest-day idea',
  },
  daily: 'Daily',
  // Exercise of the day
  addToday: '+ Add to today',
  plusToday: '+ Today',
  why: 'Why',
  skip: 'Skip',
  added: (x: string) => `${x} added to today`,
  mech: { compound: 'Compound', isolation: 'Isolation' } as Record<string, string>,
  level: { beginner: 'Beginner', intermediate: 'Intermediate', expert: 'Advanced' } as Record<
    string,
    string
  >,
  newForYou: 'New for you · fits your gym',
  // Tip of the day
  tipKicker: 'Tip',
  tipFor: (x: string) => `For today’s ${x}`,
  tipForKicker: (x: string) => `Tip for today · ${x}`,
  seeTechnique: 'See full technique',
  tips: {
    bench: {
      lift: 'Bench press',
      short: 'Tuck elbows ~45°',
      text: 'Tuck your elbows ~45° at the bottom — shoulders stay happy, the press gets stronger.',
      why: 'Flared at 90° loads the shoulder joint; ~45° keeps the press in the chest and triceps.',
      checks: ['Grip just outside shoulders', 'Bar touches lower chest', 'Drive feet, glutes down'],
    },
    squat: {
      lift: 'Squat',
      short: 'Knees track over toes',
      text: 'Let your knees travel out over your toes — it opens the hips and keeps you upright.',
      why: 'Knees caving in shift the load to the ligaments; tracking over the toes keeps it in quads and glutes.',
      checks: ['Brace before you descend', 'Whole foot on the floor', 'Depth you can own'],
    },
    deadlift: {
      lift: 'Deadlift',
      short: 'Push the floor away',
      text: 'Think “push the floor away”, not “pull the bar” — the back stays neutral, the legs do the work.',
      why: 'Yanking with the back rounds the spine; leg drive keeps the bar close and the load where it belongs.',
      checks: ['Bar over mid-foot', 'Take the slack out first', 'Lock out with the glutes'],
    },
    ohp: {
      lift: 'Overhead press',
      short: 'Glutes tight, ribs down',
      text: 'Squeeze your glutes and keep the ribs down so the bar goes straight up, not into your lower back.',
      why: 'An arched back turns the press into an incline press and loads the lumbar spine.',
      checks: ['Bar starts on the front delts', 'Head through at the top', 'Forearms vertical'],
    },
    row: {
      lift: 'Row',
      short: 'Lead with the elbows',
      text: 'Pull with your elbows, not your hands — the back works, the biceps just hold on.',
      why: 'Hand-led rows turn into curls; elbow-led rows load the lats and mid-back.',
      checks: ['Chest up, neutral spine', 'Pause at the top', 'Control the way down'],
    },
    pullup: {
      lift: 'Pull-up',
      short: 'Start from the shoulders',
      text: 'Pull your shoulder blades down first, then drive the elbows toward your ribs.',
      why: 'Packed shoulders protect the joint and switch the lats on before the arms take over.',
      checks: ['Full hang at the bottom', 'Chest toward the bar', 'No kipping'],
    },
    rdl: {
      lift: 'Romanian deadlift',
      short: 'Hips back, soft knees',
      text: 'Push your hips back with soft knees until the hamstrings stretch — then stand up tall.',
      why: 'Bending at the waist instead of hinging moves the work from the hamstrings to the lower back.',
      checks: ['Bar slides along the thighs', 'Neutral spine', 'Stop at the stretch'],
    },
    dip: {
      lift: 'Dips',
      short: 'Slight forward lean',
      text: 'Lean slightly forward and lower until the shoulders are just below the elbows.',
      why: 'Going very deep and upright strains the front of the shoulder; a small lean shares it with the chest.',
      checks: ['Shoulders away from ears', 'Elbows track back', 'Lock out at the top'],
    },
    lunge: {
      lift: 'Lunge',
      short: 'Take a long enough stride',
      text: 'Step long enough that the front shin stays roughly vertical at the bottom.',
      why: 'A short stride shoves the knee forward and puts the load on it instead of the glute.',
      checks: ['Torso tall', 'Back knee near the floor', 'Push through the front heel'],
    },
    curl: {
      lift: 'Curl',
      short: 'Pin your elbows',
      text: 'Keep the elbows pinned at your sides — if they drift forward, the shoulders steal the rep.',
      why: 'Swinging moves the load off the biceps; strict reps grow them faster with less weight.',
      checks: ['No hip swing', 'Full stretch at the bottom', 'Squeeze at the top'],
    },
    hipthrust: {
      lift: 'Hip thrust',
      short: 'Chin tucked, ribs down',
      text: 'Tuck the chin and keep the ribs down so the hips — not the lower back — finish the rep.',
      why: 'Arching at the top turns a glute lift into a back extension.',
      checks: ['Shins vertical at the top', 'Pause and squeeze', 'Bench under the shoulder blades'],
    },
    brace: {
      lift: 'Any lift',
      short: 'Brace before every rep',
      text: 'Big breath into the belly, brace as if someone is about to push you, then move.',
      why: 'A braced trunk is a stable base: more force reaches the bar and the spine stays safe.',
      checks: [
        'Breathe in at the top',
        'Hold through the hard part',
        'Exhale past the sticking point',
      ],
    },
  } satisfies Record<string, Tip>,
  // Kit spotlight
  kitAt: (gym: string) => `At ${gym}`,
  kitKicker: (gym: string) => `Kit spotlight · ${gym}`,
  neverUsedMoves: (n: number) => `Never used · ${n} moves`,
  titleNeverUsed: (x: string) => `${x} — never used`,
  kitBlurb: 'You’ve never used it here.',
  seeMoves: (n: number) => `See ${n} moves`,
  noGym: 'Save your gym',
  noGymSub: 'Kit ideas come from your gym’s equipment',
  noKit: 'No equipment listed',
  noKitSub: 'Tick what your gym has to get ideas',
  allUsed: 'You’ve tried all of it',
  allUsedSub: (n: number) => `${n} pieces of kit used`,
  openGym: 'Open gym',
  // On this day
  agoMonth: '1 month ago',
  agoHalf: '6 months ago',
  agoYear: '1 year ago',
  onThisDayYear: (y: string) => `On this day · ${y}`,
  agoLift: (ago: string, lift: string, kg: number) => `${ago}: ${lift} ${kg} kg`,
  nowE1: (kg: number, d: string) => `Now e1RM ${kg} kg · ${d}`,
  liftThenNow: (lift: string, a: number, b: number) => `${lift} ${a} → ${b} kg`,
  thenL: 'Then',
  nowL: 'Now',
  growthL: 'Growth',
  sinceThen: (lift: string) => `${lift} e1RM · since then`,
  openSession: 'Open that session',
  noFlashback: 'No flashback yet',
  flashbackOn: (date: string) => `The first one lands on ${date}`,
  nothingThisDay: 'Nothing logged on this date',
  checkTomorrow: 'Check back tomorrow',
  // Lifetime lifted
  lifetimeK: 'Lifetime',
  liftedEver: (x: string) => `${x} t lifted, ever`,
  sessionsN: (n: number) => `${n} sessions`,
  hoursN: (n: number) => `${n} h`,
  approx: (n: number, what: string) => `≈ ${n} × ${what}`,
  nextObj: (what: string) => `Next: ${what}`,
  byMonth: 'Tonnage by month',
  openProgress: 'Open progress',
  firstLift: 'Your first session starts the count',
  /** Order matches the tonnes list in discover.tsx. */
  objects: [
    'Car',
    'Elephant',
    'T. rex',
    'City bus',
    'Blue whale',
    'Statue of Liberty',
    'Boeing 747',
    'Space station',
    'Eiffel Tower ironwork',
    'Titanic',
  ],
  // Night sky
  tonight: 'Tonight',
  bedPlan: (b: string, w: string) => `Bed ${b} → ${w}`,
  bedIn: (x: string) => `Bed in ${x}`,
  inX: (x: string) => `in ${x}`,
  pastBed: 'Past bedtime',
  sleepingNow: 'Sleeping now',
  fullIn: (n: number) => `Full moon in ${n} days`,
  fullTonight: 'Full moon tonight',
  lighter: 'sleep often runs lighter',
  noSchedule: 'No sleep plan yet',
  setSchedule: 'Set a sleep schedule',
  bedL: 'Bed',
  wakeL: 'Wake',
  inL: 'In',
  // Challenge to try
  tryX: (x: string) => `Try: ${x}`,
  fitsYou: (d: string) => `${d} · fits you`,
  start: 'Start',
  startChallenge: 'Start challenge',
  another: 'Another',
  youreAt: (x: string) => `You’re at ${x} now`,
  startedToast: (x: string) => `Challenge started: ${x}`,
  activeN: (n: number) => `${n} active`,
  allStarted: 'Every challenge is running',
  // Rest-day idea
  restDay: 'Rest day',
  restIdeaK: 'Rest-day idea',
  tryMin: (min: number, act: string) => `Rest day · try ${min} min ${act}`,
  stillAt: (m: string, p: number) => `${m} still at ${p}%`,
  keepEasy: (m: string, p: number) => `${m} still at ${p}% — keep it easy, blood flow helps.`,
  allFresh: 'Muscles are fresh — move easy, stay loose.',
  recoveryK: 'Muscle recovery · keep it easy',
  startX: (x: string) => `Start ${x}`,
  trainingDay: 'Training day',
  trainingSub: 'Rest ideas show up on rest days',
  nextRestL: 'Next rest day',
  noRestPlan: 'Not planned',
  readyK: 'Muscle readiness',
  minN: (n: number) => `${n} min`,
};

export type DiscoverStrings = typeof en;

const uk: DiscoverStrings = {
  names: {
    exercise: 'Вправа дня',
    tip: 'Порада дня',
    kit: 'Тренажер у фокусі',
    onThisDay: 'Цього дня',
    lifetime: 'Піднято за весь час',
    nightSky: 'Нічне небо',
    challenge: 'Челендж на спробу',
    restIdea: 'Ідея на день відпочинку',
  },
  daily: 'Щодня',
  addToday: '+ Додати на сьогодні',
  plusToday: '+ Сьогодні',
  why: 'Чому',
  skip: 'Пропустити',
  added: (x) => `${x} додано на сьогодні`,
  mech: { compound: 'Базова', isolation: 'Ізоляція' },
  level: { beginner: 'Новачок', intermediate: 'Середній', expert: 'Досвідчений' },
  newForYou: 'Нова для тебе · є у твоєму залі',
  tipKicker: 'Порада',
  tipFor: (x) => `До сьогоднішньої вправи: ${x}`,
  tipForKicker: (x) => `Порада на сьогодні · ${x}`,
  seeTechnique: 'Уся техніка',
  tips: {
    bench: {
      lift: 'Жим лежачи',
      short: 'Лікті ~45° до тулуба',
      text: 'Внизу тримай лікті ~45° до тулуба — плечам комфортно, а жим сильніший.',
      why: 'Лікті під 90° навантажують плечовий суглоб; ~45° тримає роботу в грудях і трицепсі.',
      checks: [
        'Хват трохи ширше плечей',
        'Гриф торкається низу грудей',
        'Упор ногами, сідниці на лаві',
      ],
    },
    squat: {
      lift: 'Присідання',
      short: 'Коліна за носками',
      text: 'Веди коліна в напрямку носків — таз розкривається, а корпус лишається рівним.',
      why: 'Коліна, що заходять всередину, вантажать зв’язки; по лінії носків — працюють квадрицепс і сідниці.',
      checks: ['Напруж корпус перед спуском', 'Уся стопа на підлозі', 'Глибина, яку контролюєш'],
    },
    deadlift: {
      lift: 'Станова тяга',
      short: 'Відштовхуй підлогу',
      text: 'Думай «відштовхни підлогу», а не «тягни гриф» — спина нейтральна, працюють ноги.',
      why: 'Ривок спиною округлює хребет; робота ніг тримає гриф близько, а навантаження — де треба.',
      checks: ['Гриф над серединою стопи', 'Спершу вибери слабину', 'Завершуй сідницями'],
    },
    ohp: {
      lift: 'Жим стоячи',
      short: 'Сідниці напружені, ребра вниз',
      text: 'Стисни сідниці й опусти ребра — гриф іде вгору, а не в поперек.',
      why: 'Прогин у спині перетворює жим на жим під кутом і вантажить поперек.',
      checks: ['Гриф стартує з передніх дельт', 'Голова вперед угорі', 'Передпліччя вертикальні'],
    },
    row: {
      lift: 'Тяга',
      short: 'Веди ліктями',
      text: 'Тягни ліктями, а не кистями — працює спина, біцепс лише тримає.',
      why: 'Тяга кистями перетворюється на згинання; тяга ліктями вантажить найширші й середину спини.',
      checks: ['Груди вгору, спина рівна', 'Пауза вгорі', 'Контроль униз'],
    },
    pullup: {
      lift: 'Підтягування',
      short: 'Почни з лопаток',
      text: 'Спершу опусти лопатки, потім веди лікті до ребер.',
      why: 'Зібрані плечі бережуть суглоб і вмикають найширші раніше за руки.',
      checks: ['Повний вис унизу', 'Груди до перекладини', 'Без розгойдування'],
    },
    rdl: {
      lift: 'Румунська тяга',
      short: 'Таз назад, коліна м’які',
      text: 'Відводь таз назад на м’яких колінах до розтягнення задньої поверхні — потім випрямляйся.',
      why: 'Нахил у попереку замість руху тазом переносить роботу з біцепса стегна на поперек.',
      checks: ['Гриф ковзає по стегнах', 'Нейтральна спина', 'Стоп на розтягненні'],
    },
    dip: {
      lift: 'Віджимання на брусах',
      short: 'Легкий нахил уперед',
      text: 'Трохи нахились уперед і опускайся, доки плечі не будуть трохи нижче ліктів.',
      why: 'Дуже глибоко й вертикально — стрес для передньої частини плеча; невеликий нахил ділить роботу з грудьми.',
      checks: ['Плечі далеко від вух', 'Лікті йдуть назад', 'Повне випрямлення вгорі'],
    },
    lunge: {
      lift: 'Випади',
      short: 'Достатньо довгий крок',
      text: 'Роби крок такий, щоб гомілка передньої ноги внизу була майже вертикальною.',
      why: 'Короткий крок виштовхує коліно вперед і вантажить його замість сідниць.',
      checks: ['Корпус рівний', 'Заднє коліно біля підлоги', 'Штовхайся п’ятою'],
    },
    curl: {
      lift: 'Згинання на біцепс',
      short: 'Лікті притиснуті',
      text: 'Тримай лікті біля тулуба — якщо вони їдуть уперед, повтор «краде» плече.',
      why: 'Розгойдування знімає навантаження з біцепса; чисті повтори ростять його швидше з меншою вагою.',
      checks: ['Без розгойдування тазом', 'Повне розтягнення внизу', 'Стисни вгорі'],
    },
    hipthrust: {
      lift: 'Ягодичний міст',
      short: 'Підборіддя вниз, ребра вниз',
      text: 'Підборіддя до грудей і ребра вниз — повтор завершує таз, а не поперек.',
      why: 'Прогин угорі перетворює вправу на сідниці на розгинання спини.',
      checks: ['Гомілки вертикальні вгорі', 'Пауза і стискання', 'Лава під лопатками'],
    },
    brace: {
      lift: 'Будь-яка вправа',
      short: 'Напружуй корпус щоповтору',
      text: 'Глибокий вдих у живіт, напружся, ніби тебе зараз штовхнуть, — і рухайся.',
      why: 'Напружений корпус — стабільна основа: більше сили йде в гриф, а хребет у безпеці.',
      checks: ['Вдих угорі', 'Тримай у важкій фазі', 'Видих після мертвої точки'],
    },
  },
  kitAt: (gym) => `У ${gym}`,
  kitKicker: (gym) => `Тренажер у фокусі · ${gym}`,
  neverUsedMoves: (n) => `Ще не пробував · вправ: ${n}`,
  titleNeverUsed: (x) => `${x} — ще не пробував`,
  kitBlurb: 'Ти ще жодного разу не користувався ним тут.',
  seeMoves: (n) => `Вправи (${n})`,
  noGym: 'Збережи свій зал',
  noGymSub: 'Ідеї беруться з обладнання твого залу',
  noKit: 'Обладнання не вказане',
  noKitSub: 'Познач, що є у залі, щоб отримувати ідеї',
  allUsed: 'Ти спробував усе',
  allUsedSub: (n) => `Використано одиниць обладнання: ${n}`,
  openGym: 'Відкрити зал',
  agoMonth: 'Місяць тому',
  agoHalf: 'Пів року тому',
  agoYear: 'Рік тому',
  onThisDayYear: (y) => `Цього дня · ${y}`,
  agoLift: (ago, lift, kg) => `${ago}: ${lift} ${kg} кг`,
  nowE1: (kg, d) => `Зараз e1RM ${kg} кг · ${d}`,
  liftThenNow: (lift, a, b) => `${lift} ${a} → ${b} кг`,
  thenL: 'Тоді',
  nowL: 'Зараз',
  growthL: 'Приріст',
  sinceThen: (lift) => `${lift} e1RM · відтоді`,
  openSession: 'Відкрити ту сесію',
  noFlashback: 'Спогадів ще немає',
  flashbackOn: (date) => `Перший з’явиться ${date}`,
  nothingThisDay: 'Цієї дати нічого не записано',
  checkTomorrow: 'Зазирни завтра',
  lifetimeK: 'За весь час',
  liftedEver: (x) => `${x} т піднято за весь час`,
  sessionsN: (n) => `сесій: ${n}`,
  hoursN: (n) => `${n} год`,
  approx: (n, what) => `≈ ${n} × ${what}`,
  nextObj: (what) => `Далі: ${what}`,
  byMonth: 'Тоннаж за місяцями',
  openProgress: 'Відкрити прогрес',
  firstLift: 'Перша сесія запустить лічильник',
  objects: [
    'Автомобіль',
    'Слон',
    'Тиранозавр',
    'Міський автобус',
    'Синій кит',
    'Статуя Свободи',
    'Boeing 747',
    'Космічна станція',
    'Металоконструкція Ейфелевої вежі',
    'Титанік',
  ],
  tonight: 'Сьогодні вночі',
  bedPlan: (b, w) => `Сон ${b} → ${w}`,
  bedIn: (x) => `До сну ${x}`,
  inX: (x) => `через ${x}`,
  pastBed: 'Час спати минув',
  sleepingNow: 'Спиш',
  fullIn: (n) => `Повня через ${n} дн.`,
  fullTonight: 'Сьогодні повня',
  lighter: 'сон часто легший',
  noSchedule: 'Плану сну ще немає',
  setSchedule: 'Задати графік сну',
  bedL: 'Сон',
  wakeL: 'Підйом',
  inL: 'Через',
  tryX: (x) => `Спробуй: ${x}`,
  fitsYou: (d) => `${d} · під твій рівень`,
  start: 'Почати',
  startChallenge: 'Почати челендж',
  another: 'Інший',
  youreAt: (x) => `Зараз у тебе ${x}`,
  startedToast: (x) => `Челендж розпочато: ${x}`,
  activeN: (n) => `активних: ${n}`,
  allStarted: 'Усі челенджі вже запущені',
  restDay: 'День відпочинку',
  restIdeaK: 'Ідея на відпочинок',
  tryMin: (min, act) => `Відпочинок · спробуй ${act}, ${min} хв`,
  stillAt: (m, p) => `${m}: відновлення ${p}%`,
  keepEasy: (m, p) => `${m}: відновлення ${p}% — легко, кровообіг допоможе.`,
  allFresh: 'М’язи свіжі — рухайся легко.',
  recoveryK: 'Відновлення м’язів · легко',
  startX: (x) => `Почати: ${x}`,
  trainingDay: 'Тренувальний день',
  trainingSub: 'Ідеї з’являються в дні відпочинку',
  nextRestL: 'Наступний відпочинок',
  noRestPlan: 'Не заплановано',
  readyK: 'Готовність м’язів',
  minN: (n) => `${n} хв`,
};

const pl: DiscoverStrings = {
  names: {
    exercise: 'Ćwiczenie dnia',
    tip: 'Wskazówka dnia',
    kit: 'Sprzęt w centrum uwagi',
    onThisDay: 'Tego dnia',
    lifetime: 'Podniesione łącznie',
    nightSky: 'Nocne niebo',
    challenge: 'Wyzwanie do spróbowania',
    restIdea: 'Pomysł na dzień odpoczynku',
  },
  daily: 'Codziennie',
  addToday: '+ Dodaj na dziś',
  plusToday: '+ Dziś',
  why: 'Dlaczego',
  skip: 'Pomiń',
  added: (x) => `${x} dodano na dziś`,
  mech: { compound: 'Wielostawowe', isolation: 'Izolowane' },
  level: { beginner: 'Początkujący', intermediate: 'Średni', expert: 'Zaawansowany' },
  newForYou: 'Nowe dla ciebie · jest na twojej siłowni',
  tipKicker: 'Wskazówka',
  tipFor: (x) => `Do dzisiejszego ćwiczenia: ${x}`,
  tipForKicker: (x) => `Wskazówka na dziś · ${x}`,
  seeTechnique: 'Pełna technika',
  tips: {
    bench: {
      lift: 'Wyciskanie na ławce',
      short: 'Łokcie ~45° do tułowia',
      text: 'Na dole trzymaj łokcie ~45° do tułowia — barki są zadowolone, a wyciskanie mocniejsze.',
      why: 'Łokcie pod kątem 90° obciążają staw barkowy; ~45° zostawia pracę klatce i tricepsom.',
      checks: [
        'Chwyt tuż szerzej niż barki',
        'Sztanga dotyka dołu klatki',
        'Nogi zaparte, pośladki na ławce',
      ],
    },
    squat: {
      lift: 'Przysiad',
      short: 'Kolana nad palcami',
      text: 'Prowadź kolana w linii palców — biodra się otwierają, a tułów zostaje wyprostowany.',
      why: 'Kolana uciekające do środka obciążają więzadła; w linii palców pracują czworogłowe i pośladki.',
      checks: ['Napnij brzuch przed zejściem', 'Cała stopa na podłodze', 'Głębokość pod kontrolą'],
    },
    deadlift: {
      lift: 'Martwy ciąg',
      short: 'Odepchnij podłogę',
      text: 'Myśl „odepchnij podłogę”, nie „ciągnij sztangę” — plecy neutralne, pracują nogi.',
      why: 'Szarpanie plecami zaokrągla kręgosłup; praca nóg trzyma sztangę blisko i obciążenie tam, gdzie trzeba.',
      checks: ['Sztanga nad środkiem stopy', 'Najpierw wybierz luz', 'Kończ pośladkami'],
    },
    ohp: {
      lift: 'Wyciskanie nad głowę',
      short: 'Pośladki spięte, żebra w dół',
      text: 'Spnij pośladki i trzymaj żebra w dół — sztanga idzie w górę, a nie w lędźwie.',
      why: 'Wygięte plecy zmieniają ruch w wyciskanie skośne i obciążają odcinek lędźwiowy.',
      checks: [
        'Start z przednich naramiennych',
        'Głowa do przodu na górze',
        'Przedramiona pionowo',
      ],
    },
    row: {
      lift: 'Wiosłowanie',
      short: 'Prowadź łokciami',
      text: 'Ciągnij łokciami, nie dłońmi — pracują plecy, biceps tylko trzyma.',
      why: 'Ciągnięcie dłońmi zamienia ruch w uginanie; łokciami — obciąża najszersze i środek pleców.',
      checks: ['Klatka w górę, plecy proste', 'Pauza na górze', 'Kontrola w dół'],
    },
    pullup: {
      lift: 'Podciąganie',
      short: 'Zacznij od łopatek',
      text: 'Najpierw ściągnij łopatki w dół, potem prowadź łokcie do żeber.',
      why: 'Ustabilizowane barki chronią staw i włączają najszersze przed rękami.',
      checks: ['Pełny zwis na dole', 'Klatka do drążka', 'Bez bujania'],
    },
    rdl: {
      lift: 'Rumuński martwy ciąg',
      short: 'Biodra w tył, miękkie kolana',
      text: 'Wypychaj biodra w tył na miękkich kolanach aż do rozciągnięcia dwugłowych — potem się wyprostuj.',
      why: 'Zginanie w pasie zamiast w biodrach przenosi pracę z dwugłowych na lędźwie.',
      checks: ['Sztanga sunie po udach', 'Neutralne plecy', 'Stop przy rozciągnięciu'],
    },
    dip: {
      lift: 'Pompki na poręczach',
      short: 'Lekki pochył w przód',
      text: 'Pochyl się lekko w przód i opuszczaj, aż barki będą tuż poniżej łokci.',
      why: 'Bardzo głęboko i pionowo to stres dla przodu barku; lekki pochył dzieli pracę z klatką.',
      checks: ['Barki z dala od uszu', 'Łokcie idą w tył', 'Pełny wyprost na górze'],
    },
    lunge: {
      lift: 'Wykroki',
      short: 'Wystarczająco długi krok',
      text: 'Rób tak długi krok, by piszczel przedniej nogi była na dole prawie pionowa.',
      why: 'Krótki krok wypycha kolano do przodu i obciąża je zamiast pośladka.',
      checks: ['Tułów wyprostowany', 'Tylne kolano przy podłodze', 'Odpychaj się piętą'],
    },
    curl: {
      lift: 'Uginanie na biceps',
      short: 'Łokcie przy tułowiu',
      text: 'Trzymaj łokcie przy bokach — gdy uciekają do przodu, barki kradną powtórzenie.',
      why: 'Bujanie zdejmuje obciążenie z bicepsa; czyste powtórzenia budują go szybciej mniejszym ciężarem.',
      checks: ['Bez bujania biodrami', 'Pełne rozciągnięcie na dole', 'Spięcie na górze'],
    },
    hipthrust: {
      lift: 'Hip thrust',
      short: 'Broda w dół, żebra w dół',
      text: 'Broda do klatki i żebra w dół — powtórzenie kończą biodra, nie lędźwie.',
      why: 'Wygięcie na górze zamienia ćwiczenie na pośladki w prostowanie pleców.',
      checks: ['Piszczele pionowo na górze', 'Pauza i spięcie', 'Ławka pod łopatkami'],
    },
    brace: {
      lift: 'Każde ćwiczenie',
      short: 'Napnij tułów przed każdym powtórzeniem',
      text: 'Głęboki wdech do brzucha, napnij się, jakby ktoś miał cię popchnąć, i dopiero ruch.',
      why: 'Napięty tułów to stabilna baza: więcej siły trafia w sztangę, a kręgosłup jest bezpieczny.',
      checks: ['Wdech na górze', 'Trzymaj w trudnej fazie', 'Wydech za martwym punktem'],
    },
  },
  kitAt: (gym) => `W ${gym}`,
  kitKicker: (gym) => `Sprzęt w centrum uwagi · ${gym}`,
  neverUsedMoves: (n) => `Nieużywany · ćwiczeń: ${n}`,
  titleNeverUsed: (x) => `${x} — nieużywany`,
  kitBlurb: 'Nigdy nie używałeś go tutaj.',
  seeMoves: (n) => `Ćwiczenia (${n})`,
  noGym: 'Zapisz swoją siłownię',
  noGymSub: 'Pomysły biorą się ze sprzętu twojej siłowni',
  noKit: 'Brak listy sprzętu',
  noKitSub: 'Zaznacz, co jest na siłowni, by dostawać pomysły',
  allUsed: 'Wypróbowałeś wszystko',
  allUsedSub: (n) => `Użyty sprzęt: ${n}`,
  openGym: 'Otwórz siłownię',
  agoMonth: 'Miesiąc temu',
  agoHalf: 'Pół roku temu',
  agoYear: 'Rok temu',
  onThisDayYear: (y) => `Tego dnia · ${y}`,
  agoLift: (ago, lift, kg) => `${ago}: ${lift} ${kg} kg`,
  nowE1: (kg, d) => `Teraz e1RM ${kg} kg · ${d}`,
  liftThenNow: (lift, a, b) => `${lift} ${a} → ${b} kg`,
  thenL: 'Wtedy',
  nowL: 'Teraz',
  growthL: 'Wzrost',
  sinceThen: (lift) => `${lift} e1RM · od tamtej pory`,
  openSession: 'Otwórz tamtą sesję',
  noFlashback: 'Brak wspomnień',
  flashbackOn: (date) => `Pierwsze pojawi się ${date}`,
  nothingThisDay: 'Tego dnia nic nie zapisano',
  checkTomorrow: 'Zajrzyj jutro',
  lifetimeK: 'Łącznie',
  liftedEver: (x) => `${x} t podniesione łącznie`,
  sessionsN: (n) => `sesje: ${n}`,
  hoursN: (n) => `${n} h`,
  approx: (n, what) => `≈ ${n} × ${what}`,
  nextObj: (what) => `Następne: ${what}`,
  byMonth: 'Tonaż według miesięcy',
  openProgress: 'Otwórz postępy',
  firstLift: 'Pierwsza sesja uruchomi licznik',
  objects: [
    'Samochód',
    'Słoń',
    'Tyranozaur',
    'Autobus miejski',
    'Płetwal błękitny',
    'Statua Wolności',
    'Boeing 747',
    'Stacja kosmiczna',
    'Konstrukcja wieży Eiffla',
    'Titanic',
  ],
  tonight: 'Dziś w nocy',
  bedPlan: (b, w) => `Sen ${b} → ${w}`,
  bedIn: (x) => `Sen za ${x}`,
  inX: (x) => `za ${x}`,
  pastBed: 'Pora snu minęła',
  sleepingNow: 'Śpisz',
  fullIn: (n) => `Pełnia za ${n} dni`,
  fullTonight: 'Dziś pełnia',
  lighter: 'sen bywa płytszy',
  noSchedule: 'Brak planu snu',
  setSchedule: 'Ustaw plan snu',
  bedL: 'Sen',
  wakeL: 'Pobudka',
  inL: 'Za',
  tryX: (x) => `Spróbuj: ${x}`,
  fitsYou: (d) => `${d} · pasuje do ciebie`,
  start: 'Start',
  startChallenge: 'Rozpocznij wyzwanie',
  another: 'Inne',
  youreAt: (x) => `Teraz masz ${x}`,
  startedToast: (x) => `Wyzwanie rozpoczęte: ${x}`,
  activeN: (n) => `aktywne: ${n}`,
  allStarted: 'Wszystkie wyzwania już trwają',
  restDay: 'Dzień odpoczynku',
  restIdeaK: 'Pomysł na odpoczynek',
  tryMin: (min, act) => `Odpoczynek · spróbuj: ${act}, ${min} min`,
  stillAt: (m, p) => `${m}: regeneracja ${p}%`,
  keepEasy: (m, p) => `${m}: regeneracja ${p}% — lekko, krążenie pomoże.`,
  allFresh: 'Mięśnie świeże — ruszaj się lekko.',
  recoveryK: 'Regeneracja mięśni · lekko',
  startX: (x) => `Start: ${x}`,
  trainingDay: 'Dzień treningowy',
  trainingSub: 'Pomysły pojawiają się w dni odpoczynku',
  nextRestL: 'Następny odpoczynek',
  noRestPlan: 'Nie zaplanowano',
  readyK: 'Gotowość mięśni',
  minN: (n) => `${n} min`,
};

const lt: DiscoverStrings = {
  names: {
    exercise: 'Dienos pratimas',
    tip: 'Dienos patarimas',
    kit: 'Treniruoklis dėmesio centre',
    onThisDay: 'Šią dieną',
    lifetime: 'Pakelta per visą laiką',
    nightSky: 'Naktinis dangus',
    challenge: 'Iššūkis išbandyti',
    restIdea: 'Poilsio dienos idėja',
  },
  daily: 'Kasdien',
  addToday: '+ Pridėti šiandienai',
  plusToday: '+ Šiandien',
  why: 'Kodėl',
  skip: 'Praleisti',
  added: (x) => `${x} pridėta šiandienai`,
  mech: { compound: 'Kompleksinis', isolation: 'Izoliuotas' },
  level: { beginner: 'Pradedantysis', intermediate: 'Vidutinis', expert: 'Pažengęs' },
  newForYou: 'Nauja tau · yra tavo sporto salėje',
  tipKicker: 'Patarimas',
  tipFor: (x) => `Šiandienos pratimui: ${x}`,
  tipForKicker: (x) => `Patarimas šiandienai · ${x}`,
  seeTechnique: 'Visa technika',
  tips: {
    bench: {
      lift: 'Spaudimas gulint',
      short: 'Alkūnės ~45° kampu',
      text: 'Apačioje laikyk alkūnes ~45° kampu į liemenį — pečiams patogu, o spaudimas stipresnis.',
      why: 'Alkūnės 90° kampu apkrauna peties sąnarį; ~45° palieka darbą krūtinei ir tricepsui.',
      checks: [
        'Suėmimas šiek tiek plačiau pečių',
        'Grifas liečia krūtinės apačią',
        'Kojos įremtos, sėdmenys ant suoliuko',
      ],
    },
    squat: {
      lift: 'Pritūpimas',
      short: 'Keliai virš pirštų',
      text: 'Vesk kelius pirštų kryptimi — klubai atsiveria, o liemuo lieka tiesus.',
      why: 'Į vidų krentantys keliai apkrauna raiščius; pirštų linijoje dirba keturgalvis ir sėdmenys.',
      checks: ['Įtempk liemenį prieš leidžiantis', 'Visa pėda ant grindų', 'Gylis, kurį valdai'],
    },
    deadlift: {
      lift: 'Mirties trauka',
      short: 'Atstumk grindis',
      text: 'Galvok „atstumk grindis“, o ne „trauk grifą“ — nugara neutrali, dirba kojos.',
      why: 'Trūkčiojimas nugara apvalina stuburą; kojų darbas laiko grifą arti ir krūvį ten, kur reikia.',
      checks: ['Grifas virš pėdos vidurio', 'Pirmiau išrink laisvumą', 'Užbaik sėdmenimis'],
    },
    ohp: {
      lift: 'Spaudimas virš galvos',
      short: 'Sėdmenys įtempti, šonkauliai žemyn',
      text: 'Suspausk sėdmenis ir laikyk šonkaulius žemyn — grifas kyla tiesiai, o ne į juosmenį.',
      why: 'Išlenkta nugara paverčia judesį spaudimu kampu ir apkrauna juosmenį.',
      checks: ['Startas nuo priekinių deltų', 'Galva į priekį viršuje', 'Dilbiai vertikalūs'],
    },
    row: {
      lift: 'Trauka',
      short: 'Vesk alkūnėmis',
      text: 'Trauk alkūnėmis, ne plaštakomis — dirba nugara, bicepsas tik laiko.',
      why: 'Trauka plaštakomis virsta lenkimu; alkūnėmis — apkrauna plačiuosius ir nugaros vidurį.',
      checks: ['Krūtinė aukštyn, nugara tiesi', 'Pauzė viršuje', 'Kontrolė žemyn'],
    },
    pullup: {
      lift: 'Prisitraukimai',
      short: 'Pradėk nuo mentių',
      text: 'Pirmiausia nuleisk mentes, tada vesk alkūnes link šonkaulių.',
      why: 'Stabilūs pečiai saugo sąnarį ir įjungia plačiuosius anksčiau nei rankas.',
      checks: ['Pilnas kabėjimas apačioje', 'Krūtinė link skersinio', 'Be siūbavimo'],
    },
    rdl: {
      lift: 'Rumuniška trauka',
      short: 'Klubai atgal, keliai minkšti',
      text: 'Stumk klubus atgal minkštais keliais, kol įsitemps šlaunų užpakalinė pusė, — tada išsitiesk.',
      why: 'Lenkimasis juosmeniu vietoj klubų perkelia darbą į apatinę nugarą.',
      checks: ['Grifas slysta šlaunimis', 'Neutrali nugara', 'Stok ties tempimu'],
    },
    dip: {
      lift: 'Atsispaudimai ant lygiagrečių',
      short: 'Lengvas pasvirimas į priekį',
      text: 'Šiek tiek pasvirk į priekį ir leiskis, kol pečiai bus truputį žemiau alkūnių.',
      why: 'Labai giliai ir vertikaliai — stresas peties priekiui; lengvas pasvirimas dalijasi darbu su krūtine.',
      checks: ['Pečiai toli nuo ausų', 'Alkūnės eina atgal', 'Pilnas ištiesimas viršuje'],
    },
    lunge: {
      lift: 'Įtūpstai',
      short: 'Pakankamai ilgas žingsnis',
      text: 'Ženk taip toli, kad priekinės kojos blauzda apačioje būtų beveik vertikali.',
      why: 'Trumpas žingsnis stumia kelį į priekį ir apkrauna jį vietoj sėdmenų.',
      checks: ['Liemuo tiesus', 'Galinis kelis prie grindų', 'Stumkis kulnu'],
    },
    curl: {
      lift: 'Bicepso lenkimas',
      short: 'Alkūnės prie liemens',
      text: 'Laikyk alkūnes prie šonų — jei jos slenka į priekį, pečiai pavagia pakartojimą.',
      why: 'Siūbavimas nuima krūvį nuo bicepso; švarūs pakartojimai augina jį greičiau su mažesniu svoriu.',
      checks: ['Be klubų siūbavimo', 'Pilnas ištempimas apačioje', 'Suspausk viršuje'],
    },
    hipthrust: {
      lift: 'Klubų kėlimas',
      short: 'Smakras žemyn, šonkauliai žemyn',
      text: 'Smakrą prie krūtinės ir šonkaulius žemyn — pakartojimą užbaigia klubai, ne juosmuo.',
      why: 'Išsilenkimas viršuje paverčia sėdmenų pratimą nugaros tiesimu.',
      checks: ['Blauzdos vertikalios viršuje', 'Pauzė ir suspaudimas', 'Suoliukas po mentėmis'],
    },
    brace: {
      lift: 'Bet koks pratimas',
      short: 'Įtempk liemenį prieš kiekvieną kartą',
      text: 'Gilus įkvėpimas į pilvą, įsitempk lyg tave tuoj kas stums, ir tik tada judėk.',
      why: 'Įtemptas liemuo — stabilus pagrindas: daugiau jėgos pasiekia grifą, o stuburas saugus.',
      checks: ['Įkvėpk viršuje', 'Laikyk sunkiausioje fazėje', 'Iškvėpk po sunkiausio taško'],
    },
  },
  kitAt: (gym) => `${gym}`,
  kitKicker: (gym) => `Treniruoklis dėmesio centre · ${gym}`,
  neverUsedMoves: (n) => `Nenaudotas · pratimų: ${n}`,
  titleNeverUsed: (x) => `${x} — nenaudotas`,
  kitBlurb: 'Čia jo dar niekada nenaudojai.',
  seeMoves: (n) => `Pratimai (${n})`,
  noGym: 'Išsaugok savo salę',
  noGymSub: 'Idėjos kyla iš tavo salės įrangos',
  noKit: 'Įranga nenurodyta',
  noKitSub: 'Pažymėk, kas yra salėje, ir gausi idėjų',
  allUsed: 'Išbandei viską',
  allUsedSub: (n) => `Panaudota įrangos: ${n}`,
  openGym: 'Atidaryti salę',
  agoMonth: 'Prieš mėnesį',
  agoHalf: 'Prieš pusmetį',
  agoYear: 'Prieš metus',
  onThisDayYear: (y) => `Šią dieną · ${y}`,
  agoLift: (ago, lift, kg) => `${ago}: ${lift} ${kg} kg`,
  nowE1: (kg, d) => `Dabar e1RM ${kg} kg · ${d}`,
  liftThenNow: (lift, a, b) => `${lift} ${a} → ${b} kg`,
  thenL: 'Tada',
  nowL: 'Dabar',
  growthL: 'Augimas',
  sinceThen: (lift) => `${lift} e1RM · nuo tada`,
  openSession: 'Atidaryti tą treniruotę',
  noFlashback: 'Prisiminimų dar nėra',
  flashbackOn: (date) => `Pirmasis pasirodys ${date}`,
  nothingThisDay: 'Šią datą nieko neužrašyta',
  checkTomorrow: 'Užsuk rytoj',
  lifetimeK: 'Per visą laiką',
  liftedEver: (x) => `${x} t pakelta per visą laiką`,
  sessionsN: (n) => `treniruočių: ${n}`,
  hoursN: (n) => `${n} val.`,
  approx: (n, what) => `≈ ${n} × ${what}`,
  nextObj: (what) => `Toliau: ${what}`,
  byMonth: 'Tonažas pagal mėnesius',
  openProgress: 'Atidaryti progresą',
  firstLift: 'Pirma treniruotė paleis skaitiklį',
  objects: [
    'Automobilis',
    'Dramblys',
    'Tiranozauras',
    'Miesto autobusas',
    'Mėlynasis banginis',
    'Laisvės statula',
    'Boeing 747',
    'Kosminė stotis',
    'Eifelio bokšto konstrukcija',
    'Titanikas',
  ],
  tonight: 'Šiąnakt',
  bedPlan: (b, w) => `Miegas ${b} → ${w}`,
  bedIn: (x) => `Miegoti po ${x}`,
  inX: (x) => `po ${x}`,
  pastBed: 'Miego laikas praėjo',
  sleepingNow: 'Miegi',
  fullIn: (n) => `Pilnatis po ${n} d.`,
  fullTonight: 'Šiąnakt pilnatis',
  lighter: 'miegas dažnai lengvesnis',
  noSchedule: 'Miego plano dar nėra',
  setSchedule: 'Nustatyti miego grafiką',
  bedL: 'Miegas',
  wakeL: 'Kėlimasis',
  inL: 'Po',
  tryX: (x) => `Išbandyk: ${x}`,
  fitsYou: (d) => `${d} · tinka tau`,
  start: 'Pradėti',
  startChallenge: 'Pradėti iššūkį',
  another: 'Kitas',
  youreAt: (x) => `Dabar turi ${x}`,
  startedToast: (x) => `Iššūkis pradėtas: ${x}`,
  activeN: (n) => `aktyvių: ${n}`,
  allStarted: 'Visi iššūkiai jau vyksta',
  restDay: 'Poilsio diena',
  restIdeaK: 'Poilsio idėja',
  tryMin: (min, act) => `Poilsis · išbandyk: ${act}, ${min} min`,
  stillAt: (m, p) => `${m}: atsigavimas ${p}%`,
  keepEasy: (m, p) => `${m}: atsigavimas ${p}% — lengvai, kraujotaka padės.`,
  allFresh: 'Raumenys žvalūs — judėk lengvai.',
  recoveryK: 'Raumenų atsigavimas · lengvai',
  startX: (x) => `Pradėti: ${x}`,
  trainingDay: 'Treniruotės diena',
  trainingSub: 'Idėjos rodomos poilsio dienomis',
  nextRestL: 'Kita poilsio diena',
  noRestPlan: 'Nesuplanuota',
  readyK: 'Raumenų pasirengimas',
  minN: (n) => `${n} min`,
};

const et: DiscoverStrings = {
  names: {
    exercise: 'Päeva harjutus',
    tip: 'Päeva nõuanne',
    kit: 'Masin tähelepanu all',
    onThisDay: 'Sel päeval',
    lifetime: 'Kokku tõstetud',
    nightSky: 'Öötaevas',
    challenge: 'Proovi väljakutset',
    restIdea: 'Puhkepäeva idee',
  },
  daily: 'Iga päev',
  addToday: '+ Lisa tänasesse',
  plusToday: '+ Täna',
  why: 'Miks',
  skip: 'Jäta vahele',
  added: (x) => `${x} lisatud tänasesse`,
  mech: { compound: 'Mitmeliigese', isolation: 'Isoleeriv' },
  level: { beginner: 'Algaja', intermediate: 'Keskmine', expert: 'Edasijõudnu' },
  newForYou: 'Sulle uus · sinu saalis olemas',
  tipKicker: 'Nõuanne',
  tipFor: (x) => `Tänaseks harjutuseks: ${x}`,
  tipForKicker: (x) => `Tänane nõuanne · ${x}`,
  seeTechnique: 'Kogu tehnika',
  tips: {
    bench: {
      lift: 'Lamades surumine',
      short: 'Küünarnukid ~45° nurga all',
      text: 'All hoia küünarnukid kehaga ~45° nurga all — õlgadel on mugav ja surumine tugevam.',
      why: '90° nurga all küünarnukid koormavad õlaliigest; ~45° jätab töö rinnale ja triitsepsile.',
      checks: [
        'Haare veidi õlgadest laiem',
        'Kang puudutab rinna alaosa',
        'Jalad toetavad, tuharad pingil',
      ],
    },
    squat: {
      lift: 'Kükk',
      short: 'Põlved varvaste suunas',
      text: 'Juhi põlved varvaste suunas — puusad avanevad ja keha püsib püsti.',
      why: 'Sissepoole vajuvad põlved koormavad sidemeid; varvaste joonel töötavad reie nelipea ja tuharad.',
      checks: ['Pinguta kere enne laskumist', 'Kogu jalatald maas', 'Sügavus, mida kontrollid'],
    },
    deadlift: {
      lift: 'Jõutõmme',
      short: 'Suru põrand eemale',
      text: 'Mõtle „suru põrand eemale“, mitte „tõmba kangi“ — selg on neutraalne, tööd teevad jalad.',
      why: 'Seljaga rabelemine ümardab selgroo; jalgade töö hoiab kangi lähedal ja koormuse õiges kohas.',
      checks: ['Kang keskjala kohal', 'Võta lõtk enne välja', 'Lõpeta tuharatega'],
    },
    ohp: {
      lift: 'Pealt surumine',
      short: 'Tuharad pingul, ribid alla',
      text: 'Pinguta tuharaid ja hoia ribid all — kang liigub otse üles, mitte alaselga.',
      why: 'Nõgus selg muudab liigutuse kaldsurumiseks ja koormab nimmepiirkonda.',
      checks: ['Start eesmistelt deltadelt', 'Pea ette üleval', 'Küünarvarred vertikaalsed'],
    },
    row: {
      lift: 'Sõudmine',
      short: 'Juhi küünarnukkidega',
      text: 'Tõmba küünarnukkidega, mitte kätega — töötab selg, biitseps ainult hoiab.',
      why: 'Kätega tõmme muutub painutuseks; küünarnukkidega koormab see laiu seljalihaseid.',
      checks: ['Rind üleval, selg sirge', 'Paus üleval', 'Kontrolli laskumist'],
    },
    pullup: {
      lift: 'Lõuatõmme',
      short: 'Alusta abaluudest',
      text: 'Tõmba esmalt abaluud alla, siis vii küünarnukid ribide poole.',
      why: 'Stabiilsed õlad kaitsevad liigest ja lülitavad laiad seljalihased sisse enne käsi.',
      checks: ['Täisripe all', 'Rind kangi poole', 'Ilma hoota'],
    },
    rdl: {
      lift: 'Rumeenia jõutõmme',
      short: 'Puusad taha, põlved pehmed',
      text: 'Lükka puusad pehmete põlvedega taha, kuni reie tagakülg venib — siis tõuse sirgeks.',
      why: 'Vööst painutamine puusade asemel viib töö reie tagaküljelt alaseljale.',
      checks: ['Kang libiseb mööda reisi', 'Neutraalne selg', 'Peatu venituse juures'],
    },
    dip: {
      lift: 'Rööbaspuudel surumine',
      short: 'Kerge kalle ette',
      text: 'Kaldu veidi ette ja laskumine kuni õlad on küünarnukkidest veidi madalamal.',
      why: 'Väga sügavale ja püstiasendis — stress õla esiosale; väike kalle jagab tööd rinnaga.',
      checks: ['Õlad kõrvadest eemal', 'Küünarnukid liiguvad taha', 'Täielik sirutus üleval'],
    },
    lunge: {
      lift: 'Väljaastted',
      short: 'Piisavalt pikk samm',
      text: 'Astu nii pikalt, et eesmise jala säär oleks all peaaegu vertikaalne.',
      why: 'Lühike samm lükkab põlve ette ja koormab seda tuharate asemel.',
      checks: ['Keha püsti', 'Tagumine põlv maa lähedal', 'Tõuka kannaga'],
    },
    curl: {
      lift: 'Biitsepsi painutus',
      short: 'Küünarnukid keha küljes',
      text: 'Hoia küünarnukid külgede vastas — kui need liiguvad ette, varastavad õlad korduse.',
      why: 'Hoog võtab koormuse biitsepsilt; puhtad kordused kasvatavad seda kiiremini väiksema raskusega.',
      checks: ['Ilma puusade hoota', 'Täielik venitus all', 'Pigista üleval'],
    },
    hipthrust: {
      lift: 'Puusatõste',
      short: 'Lõug alla, ribid alla',
      text: 'Lõug rinnale ja ribid alla — korduse lõpetavad puusad, mitte alaselg.',
      why: 'Nõgusaks tõmbumine üleval muudab tuharaharjutuse selja sirutuseks.',
      checks: ['Sääred üleval vertikaalsed', 'Paus ja pigistus', 'Pink abaluude all'],
    },
    brace: {
      lift: 'Iga harjutus',
      short: 'Pinguta kere enne iga kordust',
      text: 'Sügav sissehingamine kõhtu, pinguta nagu keegi kohe lükkaks — ja alles siis liigu.',
      why: 'Pingul kere on stabiilne alus: rohkem jõudu jõuab kangini ja selgroog on kaitstud.',
      checks: ['Hinga sisse üleval', 'Hoia raskes faasis', 'Hinga välja pärast surnud punkti'],
    },
  },
  kitAt: (gym) => `${gym}`,
  kitKicker: (gym) => `Masin tähelepanu all · ${gym}`,
  neverUsedMoves: (n) => `Kasutamata · harjutusi: ${n}`,
  titleNeverUsed: (x) => `${x} — kasutamata`,
  kitBlurb: 'Sa pole seda siin kunagi kasutanud.',
  seeMoves: (n) => `Harjutused (${n})`,
  noGym: 'Salvesta oma saal',
  noGymSub: 'Ideed tulevad sinu saali varustusest',
  noKit: 'Varustus märkimata',
  noKitSub: 'Märgi, mis saalis on, et ideid saada',
  allUsed: 'Oled kõike proovinud',
  allUsedSub: (n) => `Kasutatud varustust: ${n}`,
  openGym: 'Ava saal',
  agoMonth: 'Kuu aega tagasi',
  agoHalf: 'Pool aastat tagasi',
  agoYear: 'Aasta tagasi',
  onThisDayYear: (y) => `Sel päeval · ${y}`,
  agoLift: (ago, lift, kg) => `${ago}: ${lift} ${kg} kg`,
  nowE1: (kg, d) => `Nüüd e1RM ${kg} kg · ${d}`,
  liftThenNow: (lift, a, b) => `${lift} ${a} → ${b} kg`,
  thenL: 'Siis',
  nowL: 'Nüüd',
  growthL: 'Kasv',
  sinceThen: (lift) => `${lift} e1RM · sellest ajast`,
  openSession: 'Ava see trenn',
  noFlashback: 'Mälestusi veel pole',
  flashbackOn: (date) => `Esimene ilmub ${date}`,
  nothingThisDay: 'Sel kuupäeval pole midagi logitud',
  checkTomorrow: 'Vaata homme uuesti',
  lifetimeK: 'Kokku',
  liftedEver: (x) => `${x} t kokku tõstetud`,
  sessionsN: (n) => `trenne: ${n}`,
  hoursN: (n) => `${n} h`,
  approx: (n, what) => `≈ ${n} × ${what}`,
  nextObj: (what) => `Järgmine: ${what}`,
  byMonth: 'Tonnaaž kuude kaupa',
  openProgress: 'Ava areng',
  firstLift: 'Esimene trenn käivitab loenduri',
  objects: [
    'Auto',
    'Elevant',
    'Türannosaurus',
    'Linnabuss',
    'Sinivaal',
    'Vabadussammas',
    'Boeing 747',
    'Kosmosejaam',
    'Eiffeli torni raudkonstruktsioon',
    'Titanic',
  ],
  tonight: 'Täna öösel',
  bedPlan: (b, w) => `Uni ${b} → ${w}`,
  bedIn: (x) => `Magama ${x} pärast`,
  inX: (x) => `${x} pärast`,
  pastBed: 'Magamisaeg on möödas',
  sleepingNow: 'Magad',
  fullIn: (n) => `Täiskuu ${n} päeva pärast`,
  fullTonight: 'Täna on täiskuu',
  lighter: 'uni on sageli kergem',
  noSchedule: 'Uneplaani veel pole',
  setSchedule: 'Määra unegraafik',
  bedL: 'Uni',
  wakeL: 'Ärkamine',
  inL: 'Pärast',
  tryX: (x) => `Proovi: ${x}`,
  fitsYou: (d) => `${d} · sobib sulle`,
  start: 'Alusta',
  startChallenge: 'Alusta väljakutset',
  another: 'Teine',
  youreAt: (x) => `Praegu on sul ${x}`,
  startedToast: (x) => `Väljakutse alustatud: ${x}`,
  activeN: (n) => `aktiivseid: ${n}`,
  allStarted: 'Kõik väljakutsed juba käivad',
  restDay: 'Puhkepäev',
  restIdeaK: 'Puhkepäeva idee',
  tryMin: (min, act) => `Puhkepäev · proovi: ${act}, ${min} min`,
  stillAt: (m, p) => `${m}: taastumine ${p}%`,
  keepEasy: (m, p) => `${m}: taastumine ${p}% — võta rahulikult, vereringe aitab.`,
  allFresh: 'Lihased on värsked — liigu kergelt.',
  recoveryK: 'Lihaste taastumine · rahulikult',
  startX: (x) => `Alusta: ${x}`,
  trainingDay: 'Treeningpäev',
  trainingSub: 'Ideed ilmuvad puhkepäevadel',
  nextRestL: 'Järgmine puhkepäev',
  noRestPlan: 'Pole planeeritud',
  readyK: 'Lihaste valmisolek',
  minN: (n) => `${n} min`,
};

const DICT: Record<LocaleId, DiscoverStrings> = { en, uk, pl, lt, et };

export function ds(locale: LocaleId): DiscoverStrings {
  return DICT[locale];
}
