/** Copy of the Fun & tools widgets (fun.tsx), all five locales. */
import type { LocaleId } from '../../i18n';

const en = {
  // names
  wildcard: 'Wildcard session',
  milestones: 'Milestone countdown',
  shareCard: 'Share card',
  eventCountdown: 'Event countdown',
  progressPhotos: 'Progress photos',
  motto: 'Personal motto',
  checkIn: 'Daily check-in',
  timer: 'Timer',
  syncStatus: 'Sync status',
  notifications: 'Notifications',
  beatLastWeek: 'Beat last week',
  // common
  save: 'Save',
  cancel: 'Cancel',
  remove: 'Remove',
  // wildcard
  wildcardShort: 'Wildcard',
  wildcardTitle: (x: string) => `Wildcard: ${x}`,
  minExercises: (m: number, n: number) => `${m} min · ${n} exercises`,
  fitsReadiness: (m: number, p: number) => `${m} min · fits readiness ${p}%`,
  staysResting: (x: string) => `${x} stay resting`,
  allFresh: 'Everything else is fresh',
  roll: (n: number) => `Roll ${n}`,
  reroll: 'Reroll',
  start: 'Start',
  startSession: 'Start session',
  why: (x: string, p: number) => `Why: ${x} recovered, readiness ${p}%.`,
  whyGym: (x: string) => `All at ${x}.`,
  noWildcard: 'Log a few sessions to unlock wildcards',
  // milestones
  nextMilestone: 'Next milestone',
  sessionsTo: (left: number, target: number) => `${left} sessions to ${target}`,
  toSessions: (target: number) => `to ${target} sessions`,
  sessionsUnit: 'sessions',
  doneAbout: (n: number, d: string) => `${n} done · about ${d}`,
  doneN: (n: number) => `${n} done`,
  tonsTo: (left: string, target: string) => `${left} t to ${target} t lifted`,
  streakTo: (left: number, target: number) => `${left} days to a ${target}-day streak`,
  milestonesK: 'Milestones',
  inReach: (n: number) => `${n} in reach`,
  atPace: (n: string, d: string) => `At ${n} sessions a week you hit it around ${d}.`,
  ofN: (n: number) => `of ${n}`,
  allMilestones: 'All milestones',
  // share card
  weekN: (n: number) => `Week ${n}`,
  cardReady: (n: number) => `Week ${n} card is ready`,
  sessionsShort: 'sessions',
  lifted: 'lifted',
  prs: 'PRs',
  prsN: (n: number) => (n === 1 ? '1 PR' : `${n} PRs`),
  share: 'Share',
  yourWeekCard: 'Your week card',
  shareYourWeek: 'Share your week',
  shareText: (w: number, n: number, t: string, p: number) =>
    `Spotter · week ${w}: ${n} sessions, ${t} t lifted, ${p} PRs.`,
  copied: 'Copied to clipboard',
  emptyWeek: 'Your week card fills as you train',
  // event
  countdown: 'Countdown',
  daysUnit: 'days',
  inDays: (x: string, n: number) => `${x} in ${n} days`,
  eventToday: (x: string) => `${x} is today`,
  eventPast: (n: number) => `Done ${n} days ago`,
  countdownK: (x: string) => `Countdown · ${x}`,
  setEvent: 'Set an event',
  setEventHint: 'A meet, a holiday, a photo shoot — count down to it',
  editEvent: 'Edit event',
  eventName: 'Event',
  eventDate: 'Date',
  kindMeet: 'Competition',
  kindOther: 'Other',
  defaultEvent: 'Event',
  build: 'Build',
  peak: 'Peak',
  deload: 'Deload',
  buildHint: 'heavy work now',
  peakHint: 'openers',
  deloadHint: 'rest',
  youWeigh: (x: string) => `you weigh ${x}`,
  todayWord: 'Today',
  // photos
  thenNow: 'Then / now',
  addPhoto: 'Photo',
  newPhoto: 'New photo',
  firstPhoto: 'Take your first progress photo',
  photosLocal: 'Photos stay on this device',
  progress: 'Progress',
  daysN: (n: number) => `${n} days`,
  nextOn: (d: string) => `next ${d}`,
  nextReminder: 'Next reminder',
  time: 'Time',
  weight: 'Weight',
  sessions: 'Sessions',
  photosTitle: 'Progress photos',
  deletePhoto: 'Delete photo',
  photoFailed: 'Couldn’t save the photo',
  // motto
  myMotto: 'My motto',
  writtenOn: (d: string) => `Written ${d} · tap to edit`,
  sinceSessions: (d: string, n: number) => `Since ${d} · ${n} sessions`,
  earlierMottos: 'Earlier mottos',
  editMotto: 'Edit motto',
  setMotto: 'Write your motto',
  mottoHint: 'One line to remind you why',
  mottoPlaceholder: 'Show up. Add a plate.',
  // check-in
  howFeel: 'How do you feel?',
  tapToLog: 'Tap to log today',
  scoreLabels: ['Awful', 'Low', 'Okay', 'Good', 'Great'],
  scoreOf: (n: number, l: string) => `${n} / 5 · ${l}`,
  loggedAt: (x: string) => `Logged ${x}`,
  checkInK: (d: string) => `Check-in · ${d}`,
  avg7: (x: string) => `7-day avg ${x}`,
  lowDay: (d: string, note: string) => `Low day ${d}: “${note}”`,
  addNote: 'Add note',
  editNote: 'Edit note',
  notePlaceholder: 'Slept well, shoulder feels fine…',
  // timer
  stopwatch: 'Stopwatch',
  emom: 'EMOM',
  tabata: 'Tabata',
  running: 'running',
  paused: 'paused',
  ready: 'ready',
  roundOf: (n: number, m: number) => `Round ${n} of ${m}`,
  work: 'Work',
  restPhase: 'Rest',
  leftInMinute: 'left in minute',
  leftInPhase: 'left',
  elapsedOf: (a: string, b: string) => `Elapsed ${a} · total ${b}`,
  elapsed: (a: string) => `Elapsed ${a}`,
  pause: 'Pause',
  resume: 'Start',
  reset: 'Reset',
  finished: 'Done',
  emomDesc: '10 rounds · every minute on the minute',
  tabataDesc: '8 rounds · 20 s work / 10 s rest',
  stopwatchDesc: 'Count up, no limit',
  // sync
  allSaved: 'All changes saved',
  syncing: 'Syncing…',
  offline: 'Offline',
  syncFailed: 'Sync failed',
  lastSync: (x: string) => `Last sync ${x}`,
  neverSynced: 'Not synced yet',
  savedOnPhone: 'Saved on this phone · uploads when back online',
  syncedCloud: 'Your data is backed up to your account',
  retry: 'Retry',
  retryNow: 'Retry now',
  backupSettings: 'Backup settings',
  latestOnPhone: 'Latest on this phone',
  weighIn: (x: string) => `Weigh-in · ${x}`,
  // notifications
  inbox: 'Inbox',
  unreadN: (n: number) => `${n} unread`,
  unread: 'unread',
  notificationsK: 'Notifications',
  markAllRead: 'Mark all read',
  openInbox: 'Open inbox',
  allCaughtUp: 'All caught up',
  appGym: 'Gym',
  appApex: 'Apex',
  appAtlas: 'Atlas',
  // beat last week
  vsLastWeek: 'vs last week',
  toMatchK: 'To match last week',
  aheadK: 'Ahead of last week',
  soFarBy: (a: string, b: string, d: string) => `${a} t so far · last week ${b} t by ${d}`,
  tUnit: 't',
  aheadOf: (x: string) => `${x} t ahead of last week`,
  behind: (x: string) => `${x} t behind last week`,
  xVsY: (a: string, b: string) => `${a} t vs ${b} t`,
  xVsYBy: (a: string, b: string, d: string) => `${a} t vs ${b} t by ${d}`,
  aheadShort: (x: string) => `${x} t ahead`,
  behindShort: (x: string) => `${x} t behind`,
  thisWeekRow: 'This week',
  lastWeekBy: (d: string) => `Last week · by ${d}`,
  toPass: (x: string, y: string) => `${x} t to pass last week’s ${y} t`,
  passed: (y: string) => `Already past last week’s ${y} t`,
  weekVs: (a: number, b: number) => `Week ${a} vs ${b}`,
  weeklyVolume: 'Weekly volume',
  raceEmpty: 'Train this week to race last week',
};
export type FunStrings = typeof en;

const uk: FunStrings = {
  wildcard: 'Випадкова сесія',
  milestones: 'Відлік до рубежу',
  shareCard: 'Картка для шерингу',
  eventCountdown: 'Відлік до події',
  progressPhotos: 'Фото прогресу',
  motto: 'Особисте гасло',
  checkIn: 'Щоденний чек-ін',
  timer: 'Таймер',
  syncStatus: 'Синхронізація',
  notifications: 'Сповіщення',
  beatLastWeek: 'Побий минулий тиждень',
  save: 'Зберегти',
  cancel: 'Скасувати',
  remove: 'Видалити',
  wildcardShort: 'Випадкова',
  wildcardTitle: (x) => `Випадкова: ${x}`,
  minExercises: (m, n) => `${m} хв · ${n} вправ`,
  fitsReadiness: (m, p) => `${m} хв · під готовність ${p}%`,
  staysResting: (x) => `${x} відпочивають`,
  allFresh: 'Решта свіжі',
  roll: (n) => `Спроба ${n}`,
  reroll: 'Інша',
  start: 'Почати',
  startSession: 'Почати сесію',
  why: (x, p) => `Чому: ${x} відновились, готовність ${p}%.`,
  whyGym: (x) => `Усе є в ${x}.`,
  noWildcard: 'Залогуй кілька сесій, щоб відкрити випадкові',
  nextMilestone: 'Наступний рубіж',
  sessionsTo: (left, target) => `${left} сесій до ${target}`,
  toSessions: (target) => `до ${target} сесій`,
  sessionsUnit: 'сесій',
  doneAbout: (n, d) => `${n} зроблено · приблизно ${d}`,
  doneN: (n) => `${n} зроблено`,
  tonsTo: (left, target) => `${left} т до ${target} т піднятого`,
  streakTo: (left, target) => `${left} днів до серії ${target}`,
  milestonesK: 'Рубежі',
  inReach: (n) => `${n} поруч`,
  atPace: (n, d) => `При ${n} сесіях на тиждень — приблизно ${d}.`,
  ofN: (n) => `з ${n}`,
  allMilestones: 'Усі рубежі',
  weekN: (n) => `Тиждень ${n}`,
  cardReady: (n) => `Картка тижня ${n} готова`,
  sessionsShort: 'сесій',
  lifted: 'піднято',
  prs: 'PR',
  prsN: (n) => `${n} PR`,
  share: 'Поділитись',
  yourWeekCard: 'Твоя картка тижня',
  shareYourWeek: 'Поділись тижнем',
  shareText: (w, n, t, p) => `Spotter · тиждень ${w}: ${n} сесій, ${t} т піднято, ${p} PR.`,
  copied: 'Скопійовано',
  emptyWeek: 'Картка тижня наповнюється з тренуваннями',
  countdown: 'Відлік',
  daysUnit: 'днів',
  inDays: (x, n) => `${x} через ${n} днів`,
  eventToday: (x) => `${x} сьогодні`,
  eventPast: (n) => `Минуло ${n} днів`,
  countdownK: (x) => `Відлік · ${x}`,
  setEvent: 'Задати подію',
  setEventHint: 'Змагання, відпустка, фотосесія — відлік до дати',
  editEvent: 'Змінити подію',
  eventName: 'Подія',
  eventDate: 'Дата',
  kindMeet: 'Змагання',
  kindOther: 'Інше',
  defaultEvent: 'Подія',
  build: 'Набір',
  peak: 'Пік',
  deload: 'Розвантаження',
  buildHint: 'важка робота зараз',
  peakHint: 'стартові ваги',
  deloadHint: 'відпочинок',
  youWeigh: (x) => `твоя вага ${x}`,
  todayWord: 'Сьогодні',
  thenNow: 'Тоді / зараз',
  addPhoto: 'Фото',
  newPhoto: 'Нове фото',
  firstPhoto: 'Зроби перше фото прогресу',
  photosLocal: 'Фото зберігаються лише на пристрої',
  progress: 'Прогрес',
  daysN: (n) => `${n} днів`,
  nextOn: (d) => `наступне ${d}`,
  nextReminder: 'Наступне нагадування',
  time: 'Час',
  weight: 'Вага',
  sessions: 'Сесії',
  photosTitle: 'Фото прогресу',
  deletePhoto: 'Видалити фото',
  photoFailed: 'Не вдалося зберегти фото',
  myMotto: 'Моє гасло',
  writtenOn: (d) => `Написано ${d} · тапни, щоб змінити`,
  sinceSessions: (d, n) => `З ${d} · ${n} сесій`,
  earlierMottos: 'Попередні гасла',
  editMotto: 'Змінити гасло',
  setMotto: 'Напиши своє гасло',
  mottoHint: 'Один рядок, що нагадує навіщо',
  mottoPlaceholder: 'Приходь. Додай блін.',
  howFeel: 'Як почуваєшся?',
  tapToLog: 'Тапни, щоб відмітити',
  scoreLabels: ['Жахливо', 'Погано', 'Нормально', 'Добре', 'Чудово'],
  scoreOf: (n, l) => `${n} / 5 · ${l}`,
  loggedAt: (x) => `Відмічено ${x}`,
  checkInK: (d) => `Чек-ін · ${d}`,
  avg7: (x) => `середнє за 7 днів ${x}`,
  lowDay: (d, note) => `Слабкий день ${d}: «${note}»`,
  addNote: 'Додати нотатку',
  editNote: 'Змінити нотатку',
  notePlaceholder: 'Добре виспався, плече в нормі…',
  stopwatch: 'Секундомір',
  emom: 'EMOM',
  tabata: 'Табата',
  running: 'йде',
  paused: 'пауза',
  ready: 'готово',
  roundOf: (n, m) => `Раунд ${n} з ${m}`,
  work: 'Робота',
  restPhase: 'Відпочинок',
  leftInMinute: 'до кінця хвилини',
  leftInPhase: 'лишилось',
  elapsedOf: (a, b) => `Минуло ${a} · всього ${b}`,
  elapsed: (a) => `Минуло ${a}`,
  pause: 'Пауза',
  resume: 'Старт',
  reset: 'Скинути',
  finished: 'Готово',
  emomDesc: '10 раундів · щохвилини',
  tabataDesc: '8 раундів · 20 с робота / 10 с відпочинок',
  stopwatchDesc: 'Відлік без ліміту',
  allSaved: 'Усі зміни збережено',
  syncing: 'Синхронізація…',
  offline: 'Офлайн',
  syncFailed: 'Помилка синхронізації',
  lastSync: (x) => `Остання синхронізація ${x}`,
  neverSynced: 'Ще не синхронізовано',
  savedOnPhone: 'Збережено на телефоні · завантажиться, коли буде мережа',
  syncedCloud: 'Дані збережено в акаунті',
  retry: 'Повторити',
  retryNow: 'Повторити зараз',
  backupSettings: 'Налаштування бекапу',
  latestOnPhone: 'Останнє на цьому телефоні',
  weighIn: (x) => `Зважування · ${x}`,
  inbox: 'Вхідні',
  unreadN: (n) => `${n} непрочитаних`,
  unread: 'непрочит.',
  notificationsK: 'Сповіщення',
  markAllRead: 'Прочитати всі',
  openInbox: 'Відкрити вхідні',
  allCaughtUp: 'Усе прочитано',
  appGym: 'Зал',
  appApex: 'Apex',
  appAtlas: 'Atlas',
  vsLastWeek: 'до минулого тижня',
  toMatchK: 'Щоб зрівнятися',
  aheadK: 'Попереду минулого тижня',
  soFarBy: (a, b, d) => `${a} т зараз · минулого тижня ${b} т на ${d}`,
  tUnit: 'т',
  aheadOf: (x) => `на ${x} т попереду минулого тижня`,
  behind: (x) => `на ${x} т позаду минулого тижня`,
  xVsY: (a, b) => `${a} т проти ${b} т`,
  xVsYBy: (a, b, d) => `${a} т проти ${b} т на ${d}`,
  aheadShort: (x) => `на ${x} т попереду`,
  behindShort: (x) => `на ${x} т позаду`,
  thisWeekRow: 'Цей тиждень',
  lastWeekBy: (d) => `Минулий · на ${d}`,
  toPass: (x, y) => `${x} т, щоб перевершити ${y} т минулого тижня`,
  passed: (y) => `Вже більше за ${y} т минулого тижня`,
  weekVs: (a, b) => `Тиждень ${a} проти ${b}`,
  weeklyVolume: 'Тижневий обʼєм',
  raceEmpty: 'Тренуйся цього тижня, щоб змагатися з минулим',
};

const pl: FunStrings = {
  wildcard: 'Sesja niespodzianka',
  milestones: 'Odliczanie do celu',
  shareCard: 'Karta do udostępnienia',
  eventCountdown: 'Odliczanie do wydarzenia',
  progressPhotos: 'Zdjęcia postępów',
  motto: 'Osobiste motto',
  checkIn: 'Codzienny check-in',
  timer: 'Minutnik',
  syncStatus: 'Synchronizacja',
  notifications: 'Powiadomienia',
  beatLastWeek: 'Pobij poprzedni tydzień',
  save: 'Zapisz',
  cancel: 'Anuluj',
  remove: 'Usuń',
  wildcardShort: 'Niespodzianka',
  wildcardTitle: (x) => `Niespodzianka: ${x}`,
  minExercises: (m, n) => `${m} min · ${n} ćwiczeń`,
  fitsReadiness: (m, p) => `${m} min · pasuje do gotowości ${p}%`,
  staysResting: (x) => `${x} odpoczywają`,
  allFresh: 'Reszta jest świeża',
  roll: (n) => `Losowanie ${n}`,
  reroll: 'Losuj',
  start: 'Start',
  startSession: 'Rozpocznij sesję',
  why: (x, p) => `Dlaczego: ${x} zregenerowane, gotowość ${p}%.`,
  whyGym: (x) => `Wszystko w ${x}.`,
  noWildcard: 'Zapisz kilka sesji, aby odblokować losowanie',
  nextMilestone: 'Następny cel',
  sessionsTo: (left, target) => `${left} sesji do ${target}`,
  toSessions: (target) => `do ${target} sesji`,
  sessionsUnit: 'sesji',
  doneAbout: (n, d) => `${n} za tobą · około ${d}`,
  doneN: (n) => `${n} za tobą`,
  tonsTo: (left, target) => `${left} t do ${target} t podniesionych`,
  streakTo: (left, target) => `${left} dni do serii ${target}`,
  milestonesK: 'Cele',
  inReach: (n) => `${n} w zasięgu`,
  atPace: (n, d) => `Przy ${n} sesjach w tygodniu osiągniesz to około ${d}.`,
  ofN: (n) => `z ${n}`,
  allMilestones: 'Wszystkie cele',
  weekN: (n) => `Tydzień ${n}`,
  cardReady: (n) => `Karta tygodnia ${n} gotowa`,
  sessionsShort: 'sesji',
  lifted: 'podniesione',
  prs: 'PR',
  prsN: (n) => `${n} PR`,
  share: 'Udostępnij',
  yourWeekCard: 'Twoja karta tygodnia',
  shareYourWeek: 'Udostępnij tydzień',
  shareText: (w, n, t, p) => `Spotter · tydzień ${w}: ${n} sesji, ${t} t podniesione, ${p} PR.`,
  copied: 'Skopiowano',
  emptyWeek: 'Karta tygodnia wypełnia się z treningami',
  countdown: 'Odliczanie',
  daysUnit: 'dni',
  inDays: (x, n) => `${x} za ${n} dni`,
  eventToday: (x) => `${x} dzisiaj`,
  eventPast: (n) => `Minęło ${n} dni`,
  countdownK: (x) => `Odliczanie · ${x}`,
  setEvent: 'Ustaw wydarzenie',
  setEventHint: 'Zawody, urlop, sesja zdjęciowa — odliczaj do daty',
  editEvent: 'Edytuj wydarzenie',
  eventName: 'Wydarzenie',
  eventDate: 'Data',
  kindMeet: 'Zawody',
  kindOther: 'Inne',
  defaultEvent: 'Wydarzenie',
  build: 'Budowa',
  peak: 'Szczyt',
  deload: 'Roztrenowanie',
  buildHint: 'ciężka praca teraz',
  peakHint: 'podejścia otwierające',
  deloadHint: 'odpoczynek',
  youWeigh: (x) => `ważysz ${x}`,
  todayWord: 'Dziś',
  thenNow: 'Wtedy / teraz',
  addPhoto: 'Zdjęcie',
  newPhoto: 'Nowe zdjęcie',
  firstPhoto: 'Zrób pierwsze zdjęcie postępów',
  photosLocal: 'Zdjęcia zostają na tym urządzeniu',
  progress: 'Postęp',
  daysN: (n) => `${n} dni`,
  nextOn: (d) => `następne ${d}`,
  nextReminder: 'Następne przypomnienie',
  time: 'Czas',
  weight: 'Waga',
  sessions: 'Sesje',
  photosTitle: 'Zdjęcia postępów',
  deletePhoto: 'Usuń zdjęcie',
  photoFailed: 'Nie udało się zapisać zdjęcia',
  myMotto: 'Moje motto',
  writtenOn: (d) => `Napisane ${d} · stuknij, aby edytować`,
  sinceSessions: (d, n) => `Od ${d} · ${n} sesji`,
  earlierMottos: 'Wcześniejsze motta',
  editMotto: 'Edytuj motto',
  setMotto: 'Napisz swoje motto',
  mottoHint: 'Jedna linijka, która przypomina po co',
  mottoPlaceholder: 'Przyjdź. Dołóż talerz.',
  howFeel: 'Jak się czujesz?',
  tapToLog: 'Stuknij, aby zapisać dziś',
  scoreLabels: ['Fatalnie', 'Słabo', 'W porządku', 'Dobrze', 'Świetnie'],
  scoreOf: (n, l) => `${n} / 5 · ${l}`,
  loggedAt: (x) => `Zapisano ${x}`,
  checkInK: (d) => `Check-in · ${d}`,
  avg7: (x) => `śr. 7 dni ${x}`,
  lowDay: (d, note) => `Słabszy dzień ${d}: „${note}”`,
  addNote: 'Dodaj notatkę',
  editNote: 'Edytuj notatkę',
  notePlaceholder: 'Dobrze spałem, bark w porządku…',
  stopwatch: 'Stoper',
  emom: 'EMOM',
  tabata: 'Tabata',
  running: 'trwa',
  paused: 'pauza',
  ready: 'gotowy',
  roundOf: (n, m) => `Runda ${n} z ${m}`,
  work: 'Praca',
  restPhase: 'Przerwa',
  leftInMinute: 'do końca minuty',
  leftInPhase: 'zostało',
  elapsedOf: (a, b) => `Minęło ${a} · razem ${b}`,
  elapsed: (a) => `Minęło ${a}`,
  pause: 'Pauza',
  resume: 'Start',
  reset: 'Reset',
  finished: 'Koniec',
  emomDesc: '10 rund · co minutę',
  tabataDesc: '8 rund · 20 s praca / 10 s przerwa',
  stopwatchDesc: 'Liczenie w górę bez limitu',
  allSaved: 'Wszystkie zmiany zapisane',
  syncing: 'Synchronizacja…',
  offline: 'Offline',
  syncFailed: 'Błąd synchronizacji',
  lastSync: (x) => `Ostatnia synchronizacja ${x}`,
  neverSynced: 'Jeszcze nie zsynchronizowano',
  savedOnPhone: 'Zapisane w telefonie · wyśle się po powrocie sieci',
  syncedCloud: 'Dane są zapisane na koncie',
  retry: 'Ponów',
  retryNow: 'Ponów teraz',
  backupSettings: 'Ustawienia kopii',
  latestOnPhone: 'Ostatnie w tym telefonie',
  weighIn: (x) => `Ważenie · ${x}`,
  inbox: 'Skrzynka',
  unreadN: (n) => `${n} nieprzeczytane`,
  unread: 'nieprzecz.',
  notificationsK: 'Powiadomienia',
  markAllRead: 'Oznacz wszystkie',
  openInbox: 'Otwórz skrzynkę',
  allCaughtUp: 'Wszystko przeczytane',
  appGym: 'Siłownia',
  appApex: 'Apex',
  appAtlas: 'Atlas',
  vsLastWeek: 'vs poprzedni tydzień',
  toMatchK: 'Do wyrównania',
  aheadK: 'Przed poprzednim tygodniem',
  soFarBy: (a, b, d) => `${a} t na razie · poprzedni tydzień ${b} t do ${d}`,
  tUnit: 't',
  aheadOf: (x) => `${x} t przed poprzednim tygodniem`,
  behind: (x) => `${x} t za poprzednim tygodniem`,
  xVsY: (a, b) => `${a} t vs ${b} t`,
  xVsYBy: (a, b, d) => `${a} t vs ${b} t do ${d}`,
  aheadShort: (x) => `${x} t przed`,
  behindShort: (x) => `${x} t za`,
  thisWeekRow: 'Ten tydzień',
  lastWeekBy: (d) => `Poprzedni · do ${d}`,
  toPass: (x, y) => `${x} t, by przebić ${y} t z poprzedniego tygodnia`,
  passed: (y) => `Już ponad ${y} t z poprzedniego tygodnia`,
  weekVs: (a, b) => `Tydzień ${a} vs ${b}`,
  weeklyVolume: 'Objętość tygodnia',
  raceEmpty: 'Trenuj w tym tygodniu, by ścigać się z poprzednim',
};

const lt: FunStrings = {
  wildcard: 'Atsitiktinė sesija',
  milestones: 'Iki etapo',
  shareCard: 'Kortelė dalinimuisi',
  eventCountdown: 'Iki įvykio',
  progressPhotos: 'Pažangos nuotraukos',
  motto: 'Asmeninis šūkis',
  checkIn: 'Dienos savijauta',
  timer: 'Laikmatis',
  syncStatus: 'Sinchronizacija',
  notifications: 'Pranešimai',
  beatLastWeek: 'Pranok praėjusią savaitę',
  save: 'Išsaugoti',
  cancel: 'Atšaukti',
  remove: 'Pašalinti',
  wildcardShort: 'Atsitiktinė',
  wildcardTitle: (x) => `Atsitiktinė: ${x}`,
  minExercises: (m, n) => `${m} min · ${n} pratimai`,
  fitsReadiness: (m, p) => `${m} min · tinka pasirengimui ${p}%`,
  staysResting: (x) => `${x} ilsisi`,
  allFresh: 'Visa kita pailsėję',
  roll: (n) => `Bandymas ${n}`,
  reroll: 'Kita',
  start: 'Pradėti',
  startSession: 'Pradėti sesiją',
  why: (x, p) => `Kodėl: ${x} atsigavę, pasirengimas ${p}%.`,
  whyGym: (x) => `Viskas yra: ${x}.`,
  noWildcard: 'Įrašyk kelias sesijas, kad atrakintum atsitiktines',
  nextMilestone: 'Kitas etapas',
  sessionsTo: (left, target) => `${left} sesijos iki ${target}`,
  toSessions: (target) => `iki ${target} sesijų`,
  sessionsUnit: 'sesijos',
  doneAbout: (n, d) => `${n} atlikta · apie ${d}`,
  doneN: (n) => `${n} atlikta`,
  tonsTo: (left, target) => `${left} t iki ${target} t pakelta`,
  streakTo: (left, target) => `${left} d. iki ${target} d. serijos`,
  milestonesK: 'Etapai',
  inReach: (n) => `${n} pasiekiami`,
  atPace: (n, d) => `Treniruojantis ${n} k. per savaitę pasieksi apie ${d}.`,
  ofN: (n) => `iš ${n}`,
  allMilestones: 'Visi etapai',
  weekN: (n) => `${n} savaitė`,
  cardReady: (n) => `${n} savaitės kortelė paruošta`,
  sessionsShort: 'sesijos',
  lifted: 'pakelta',
  prs: 'PR',
  prsN: (n) => `${n} PR`,
  share: 'Dalintis',
  yourWeekCard: 'Tavo savaitės kortelė',
  shareYourWeek: 'Pasidalink savaite',
  shareText: (w, n, t, p) => `Spotter · ${w} savaitė: ${n} sesijos, ${t} t pakelta, ${p} PR.`,
  copied: 'Nukopijuota',
  emptyWeek: 'Savaitės kortelė pildosi treniruojantis',
  countdown: 'Atgalinis skaičiavimas',
  daysUnit: 'd.',
  inDays: (x, n) => `${x} po ${n} d.`,
  eventToday: (x) => `${x} šiandien`,
  eventPast: (n) => `Praėjo ${n} d.`,
  countdownK: (x) => `Skaičiavimas · ${x}`,
  setEvent: 'Nustatyti įvykį',
  setEventHint: 'Varžybos, atostogos, fotosesija — skaičiuok dienas',
  editEvent: 'Redaguoti įvykį',
  eventName: 'Įvykis',
  eventDate: 'Data',
  kindMeet: 'Varžybos',
  kindOther: 'Kita',
  defaultEvent: 'Įvykis',
  build: 'Krūvis',
  peak: 'Pikas',
  deload: 'Iškrova',
  buildHint: 'sunkus darbas dabar',
  peakHint: 'pradiniai svoriai',
  deloadHint: 'poilsis',
  youWeigh: (x) => `sveri ${x}`,
  todayWord: 'Šiandien',
  thenNow: 'Tada / dabar',
  addPhoto: 'Nuotrauka',
  newPhoto: 'Nauja nuotrauka',
  firstPhoto: 'Padaryk pirmą pažangos nuotrauką',
  photosLocal: 'Nuotraukos lieka šiame įrenginyje',
  progress: 'Pažanga',
  daysN: (n) => `${n} d.`,
  nextOn: (d) => `kita ${d}`,
  nextReminder: 'Kitas priminimas',
  time: 'Laikas',
  weight: 'Svoris',
  sessions: 'Sesijos',
  photosTitle: 'Pažangos nuotraukos',
  deletePhoto: 'Ištrinti nuotrauką',
  photoFailed: 'Nepavyko išsaugoti nuotraukos',
  myMotto: 'Mano šūkis',
  writtenOn: (d) => `Parašyta ${d} · bakstelk, kad redaguotum`,
  sinceSessions: (d, n) => `Nuo ${d} · ${n} sesijos`,
  earlierMottos: 'Ankstesni šūkiai',
  editMotto: 'Redaguoti šūkį',
  setMotto: 'Parašyk savo šūkį',
  mottoHint: 'Viena eilutė, primenanti kodėl',
  mottoPlaceholder: 'Ateik. Pridėk diską.',
  howFeel: 'Kaip jautiesi?',
  tapToLog: 'Bakstelk, kad pažymėtum',
  scoreLabels: ['Siaubingai', 'Prastai', 'Normaliai', 'Gerai', 'Puikiai'],
  scoreOf: (n, l) => `${n} / 5 · ${l}`,
  loggedAt: (x) => `Pažymėta ${x}`,
  checkInK: (d) => `Savijauta · ${d}`,
  avg7: (x) => `7 d. vid. ${x}`,
  lowDay: (d, note) => `Prastesnė diena ${d}: „${note}“`,
  addNote: 'Pridėti pastabą',
  editNote: 'Redaguoti pastabą',
  notePlaceholder: 'Gerai išsimiegojau, petys gerai…',
  stopwatch: 'Chronometras',
  emom: 'EMOM',
  tabata: 'Tabata',
  running: 'vyksta',
  paused: 'pauzė',
  ready: 'paruošta',
  roundOf: (n, m) => `Raundas ${n} iš ${m}`,
  work: 'Darbas',
  restPhase: 'Poilsis',
  leftInMinute: 'liko minutėje',
  leftInPhase: 'liko',
  elapsedOf: (a, b) => `Praėjo ${a} · iš viso ${b}`,
  elapsed: (a) => `Praėjo ${a}`,
  pause: 'Pauzė',
  resume: 'Pradėti',
  reset: 'Iš naujo',
  finished: 'Baigta',
  emomDesc: '10 raundų · kas minutę',
  tabataDesc: '8 raundai · 20 s darbas / 10 s poilsis',
  stopwatchDesc: 'Skaičiuoja be ribos',
  allSaved: 'Visi pakeitimai išsaugoti',
  syncing: 'Sinchronizuojama…',
  offline: 'Neprisijungta',
  syncFailed: 'Sinchronizacija nepavyko',
  lastSync: (x) => `Paskutinė sinchronizacija ${x}`,
  neverSynced: 'Dar nesinchronizuota',
  savedOnPhone: 'Išsaugota telefone · bus įkelta atsiradus ryšiui',
  syncedCloud: 'Duomenys išsaugoti paskyroje',
  retry: 'Kartoti',
  retryNow: 'Kartoti dabar',
  backupSettings: 'Atsarginių kopijų nustatymai',
  latestOnPhone: 'Naujausia šiame telefone',
  weighIn: (x) => `Svėrimasis · ${x}`,
  inbox: 'Gautieji',
  unreadN: (n) => `${n} neperskaityti`,
  unread: 'neperskaityti',
  notificationsK: 'Pranešimai',
  markAllRead: 'Pažymėti visus',
  openInbox: 'Atidaryti gautuosius',
  allCaughtUp: 'Viskas perskaityta',
  appGym: 'Salė',
  appApex: 'Apex',
  appAtlas: 'Atlas',
  vsLastWeek: 'lyginant su praėjusia savaite',
  toMatchK: 'Iki praėjusios savaitės',
  aheadK: 'Lenki praėjusią savaitę',
  soFarBy: (a, b, d) => `${a} t kol kas · praėjusią savaitę ${b} t iki ${d}`,
  tUnit: 't',
  aheadOf: (x) => `${x} t daugiau nei praėjusią savaitę`,
  behind: (x) => `${x} t mažiau nei praėjusią savaitę`,
  xVsY: (a, b) => `${a} t prieš ${b} t`,
  xVsYBy: (a, b, d) => `${a} t prieš ${b} t iki ${d}`,
  aheadShort: (x) => `${x} t priekyje`,
  behindShort: (x) => `${x} t atsilieka`,
  thisWeekRow: 'Ši savaitė',
  lastWeekBy: (d) => `Praėjusi · iki ${d}`,
  toPass: (x, y) => `${x} t, kad viršytum praėjusios savaitės ${y} t`,
  passed: (y) => `Jau viršyta praėjusios savaitės ${y} t`,
  weekVs: (a, b) => `${a} savaitė prieš ${b}`,
  weeklyVolume: 'Savaitės apimtis',
  raceEmpty: 'Treniruokis šią savaitę, kad lenktyniautum su praėjusia',
};

const et: FunStrings = {
  wildcard: 'Üllatussessioon',
  milestones: 'Verstaposti loendur',
  shareCard: 'Jagamiskaart',
  eventCountdown: 'Sündmuse loendur',
  progressPhotos: 'Edenemise fotod',
  motto: 'Isiklik moto',
  checkIn: 'Päeva enesetunne',
  timer: 'Taimer',
  syncStatus: 'Sünkroonimine',
  notifications: 'Teavitused',
  beatLastWeek: 'Löö eelmist nädalat',
  save: 'Salvesta',
  cancel: 'Tühista',
  remove: 'Eemalda',
  wildcardShort: 'Üllatus',
  wildcardTitle: (x) => `Üllatus: ${x}`,
  minExercises: (m, n) => `${m} min · ${n} harjutust`,
  fitsReadiness: (m, p) => `${m} min · sobib valmisolekuga ${p}%`,
  staysResting: (x) => `${x} puhkavad`,
  allFresh: 'Kõik muu on värske',
  roll: (n) => `Katse ${n}`,
  reroll: 'Uus',
  start: 'Alusta',
  startSession: 'Alusta sessiooni',
  why: (x, p) => `Miks: ${x} taastunud, valmisolek ${p}%.`,
  whyGym: (x) => `Kõik on olemas: ${x}.`,
  noWildcard: 'Logi paar sessiooni, et üllatused avada',
  nextMilestone: 'Järgmine verstapost',
  sessionsTo: (left, target) => `${left} sessiooni ${target}-ni`,
  toSessions: (target) => `${target} sessioonini`,
  sessionsUnit: 'sessiooni',
  doneAbout: (n, d) => `${n} tehtud · umbes ${d}`,
  doneN: (n) => `${n} tehtud`,
  tonsTo: (left, target) => `${left} t kuni ${target} t tõstetud`,
  streakTo: (left, target) => `${left} päeva ${target}-päevase seeriani`,
  milestonesK: 'Verstapostid',
  inReach: (n) => `${n} käeulatuses`,
  atPace: (n, d) => `${n} sessiooniga nädalas jõuad sinna umbes ${d}.`,
  ofN: (n) => `${n}-st`,
  allMilestones: 'Kõik verstapostid',
  weekN: (n) => `Nädal ${n}`,
  cardReady: (n) => `Nädala ${n} kaart on valmis`,
  sessionsShort: 'sessiooni',
  lifted: 'tõstetud',
  prs: 'PR',
  prsN: (n) => `${n} PR`,
  share: 'Jaga',
  yourWeekCard: 'Sinu nädala kaart',
  shareYourWeek: 'Jaga oma nädalat',
  shareText: (w, n, t, p) => `Spotter · nädal ${w}: ${n} sessiooni, ${t} t tõstetud, ${p} PR.`,
  copied: 'Kopeeritud',
  emptyWeek: 'Nädala kaart täitub treenides',
  countdown: 'Loendur',
  daysUnit: 'päeva',
  inDays: (x, n) => `${x} ${n} päeva pärast`,
  eventToday: (x) => `${x} on täna`,
  eventPast: (n) => `Möödus ${n} päeva`,
  countdownK: (x) => `Loendur · ${x}`,
  setEvent: 'Määra sündmus',
  setEventHint: 'Võistlus, puhkus, fotosessioon — loe päevi',
  editEvent: 'Muuda sündmust',
  eventName: 'Sündmus',
  eventDate: 'Kuupäev',
  kindMeet: 'Võistlus',
  kindOther: 'Muu',
  defaultEvent: 'Sündmus',
  build: 'Ehitus',
  peak: 'Tipp',
  deload: 'Kergendus',
  buildHint: 'raske töö praegu',
  peakHint: 'avakatsed',
  deloadHint: 'puhkus',
  youWeigh: (x) => `kaalud ${x}`,
  todayWord: 'Täna',
  thenNow: 'Siis / nüüd',
  addPhoto: 'Foto',
  newPhoto: 'Uus foto',
  firstPhoto: 'Tee esimene edenemise foto',
  photosLocal: 'Fotod jäävad sellesse seadmesse',
  progress: 'Edenemine',
  daysN: (n) => `${n} päeva`,
  nextOn: (d) => `järgmine ${d}`,
  nextReminder: 'Järgmine meeldetuletus',
  time: 'Aeg',
  weight: 'Kaal',
  sessions: 'Sessioonid',
  photosTitle: 'Edenemise fotod',
  deletePhoto: 'Kustuta foto',
  photoFailed: 'Fotot ei õnnestunud salvestada',
  myMotto: 'Minu moto',
  writtenOn: (d) => `Kirjutatud ${d} · puuduta muutmiseks`,
  sinceSessions: (d, n) => `Alates ${d} · ${n} sessiooni`,
  earlierMottos: 'Varasemad motod',
  editMotto: 'Muuda motot',
  setMotto: 'Kirjuta oma moto',
  mottoHint: 'Üks rida, mis meenutab, miks',
  mottoPlaceholder: 'Tule kohale. Lisa ketas.',
  howFeel: 'Kuidas end tunned?',
  tapToLog: 'Puuduta, et tänane märkida',
  scoreLabels: ['Kohutav', 'Kehv', 'Normaalne', 'Hea', 'Suurepärane'],
  scoreOf: (n, l) => `${n} / 5 · ${l}`,
  loggedAt: (x) => `Märgitud ${x}`,
  checkInK: (d) => `Enesetunne · ${d}`,
  avg7: (x) => `7 päeva keskm. ${x}`,
  lowDay: (d, note) => `Kehvem päev ${d}: „${note}“`,
  addNote: 'Lisa märkus',
  editNote: 'Muuda märkust',
  notePlaceholder: 'Magasin hästi, õlg on korras…',
  stopwatch: 'Stopper',
  emom: 'EMOM',
  tabata: 'Tabata',
  running: 'käib',
  paused: 'paus',
  ready: 'valmis',
  roundOf: (n, m) => `Ring ${n}/${m}`,
  work: 'Töö',
  restPhase: 'Puhkus',
  leftInMinute: 'minutist jäänud',
  leftInPhase: 'jäänud',
  elapsedOf: (a, b) => `Möödas ${a} · kokku ${b}`,
  elapsed: (a) => `Möödas ${a}`,
  pause: 'Paus',
  resume: 'Start',
  reset: 'Lähtesta',
  finished: 'Valmis',
  emomDesc: '10 ringi · iga minuti alguses',
  tabataDesc: '8 ringi · 20 s töö / 10 s puhkus',
  stopwatchDesc: 'Loeb üles, piiranguta',
  allSaved: 'Kõik muudatused salvestatud',
  syncing: 'Sünkroonin…',
  offline: 'Võrguühenduseta',
  syncFailed: 'Sünkroonimine ebaõnnestus',
  lastSync: (x) => `Viimane sünk ${x}`,
  neverSynced: 'Veel sünkroonimata',
  savedOnPhone: 'Salvestatud telefoni · laetakse üles, kui võrk tuleb',
  syncedCloud: 'Andmed on kontole salvestatud',
  retry: 'Proovi uuesti',
  retryNow: 'Proovi kohe',
  backupSettings: 'Varunduse seaded',
  latestOnPhone: 'Viimane selles telefonis',
  weighIn: (x) => `Kaalumine · ${x}`,
  inbox: 'Postkast',
  unreadN: (n) => `${n} lugemata`,
  unread: 'lugemata',
  notificationsK: 'Teavitused',
  markAllRead: 'Märgi kõik loetuks',
  openInbox: 'Ava postkast',
  allCaughtUp: 'Kõik loetud',
  appGym: 'Jõusaal',
  appApex: 'Apex',
  appAtlas: 'Atlas',
  vsLastWeek: 'vs eelmine nädal',
  toMatchK: 'Eelmise nädalani',
  aheadK: 'Eelmisest nädalast ees',
  soFarBy: (a, b, d) => `${a} t seni · eelmine nädal ${b} t seisuga ${d}`,
  tUnit: 't',
  aheadOf: (x) => `${x} t eelmisest nädalast ees`,
  behind: (x) => `${x} t eelmisest nädalast maas`,
  xVsY: (a, b) => `${a} t vs ${b} t`,
  xVsYBy: (a, b, d) => `${a} t vs ${b} t seisuga ${d}`,
  aheadShort: (x) => `${x} t ees`,
  behindShort: (x) => `${x} t maas`,
  thisWeekRow: 'See nädal',
  lastWeekBy: (d) => `Eelmine · seisuga ${d}`,
  toPass: (x, y) => `${x} t, et ületada eelmise nädala ${y} t`,
  passed: (y) => `Eelmise nädala ${y} t juba ületatud`,
  weekVs: (a, b) => `Nädal ${a} vs ${b}`,
  weeklyVolume: 'Nädala maht',
  raceEmpty: 'Treeni sel nädalal, et eelmisega võidu joosta',
};

const DICT: Record<LocaleId, FunStrings> = { en, uk, pl, lt, et };
export function fs(locale: LocaleId): FunStrings {
  return DICT[locale];
}
