/**
 * Copy of the Learn & Atlas Today widgets, all five locales (typed: a missing
 * key in any locale fails the build). Counts are written as "Label · n" so no
 * locale needs plural rules.
 */
import type { LocaleId } from '../../i18n';

export interface Fact {
  short: string;
  text: string;
  src: string;
}

const en = {
  names: {
    learnNext: 'Learn · next lesson',
    lessonDay: 'Lesson of the day',
    saved: 'Saved lessons',
    topics: 'Learn topics',
    fact: 'Did you know',
    insight: 'Atlas insight',
    ask: 'Ask Atlas',
    plan: 'Atlas plan for today',
    debrief: 'Atlas debrief',
    mood: 'Atlas mood',
    notes: 'Atlas notes',
    weekly: 'Atlas weekly review',
    quickAsk: 'Ask Atlas · one tap',
  },
  // Learn
  learn: 'Learn',
  lessons: 'lessons',
  lessonsWatched: 'lessons watched',
  watchedOf: (a: number, b: number) => `${a} of ${b} lessons`,
  continueL: 'Continue',
  startLearning: 'Start learning',
  nextLesson: 'Next lesson',
  upNext: 'Up next',
  upNextIn: (topic: string) => `Up next · ${topic}`,
  libraryProgress: 'Library progress',
  soon: 'video soon',
  fresh: 'new',
  watched: 'Watched',
  watch: 'Watch',
  daily: 'Daily',
  savedK: 'Saved',
  savedN: (n: number) => `Saved lessons · ${n}`,
  noSaved: 'Nothing saved yet',
  noSavedSub: 'Bookmark a lesson in Learn to watch it later',
  unwatched: (n: number) => `Unwatched · ${n}`,
  playAll: 'Play all',
  next: (x: string) => `Next: ${x}`,
  topicsDone: (a: number, b: number) => `Topics done · ${a} of ${b}`,
  finish: (x: string) => `Next: finish ${x}`,
  allWatched: 'All lessons watched',
  allWatchedSub: 'Rewatch any of them in Learn',
  openLearn: 'Open Learn',
  // Did you know
  didYouKnow: 'Did you know',
  science: 'Science',
  factOf: (i: number, n: number) => `${i} of ${n}`,
  source: 'Source',
  facts: [
    {
      short: 'Sets near failure build muscle',
      text: 'Sets taken close to failure build more muscle — stopping 0–3 reps short works about as well as going all the way.',
      src: 'Robinson et al., 2024 · meta-analysis',
    },
    {
      short: 'Light or heavy — both grow muscle',
      text: 'From about 30% to 80%+ of your max, loads build similar muscle when sets end near failure. Heavy still wins for strength.',
      src: 'Schoenfeld et al., 2017 · meta-analysis',
    },
    {
      short: 'More weekly sets, more growth',
      text: 'Muscle growth rises with hard sets per muscle per week — 10 or more a week beats a handful.',
      src: 'Schoenfeld, Ogborn & Krieger, 2017 · meta-analysis',
    },
    {
      short: 'Protein tops out near 1.6 g/kg',
      text: 'Extra protein stops adding muscle at around 1.6 g per kg of body weight a day.',
      src: 'Morton et al., 2018 · meta-analysis',
    },
    {
      short: 'Split weekly sets as you like',
      text: 'With the same weekly sets, training a muscle once or twice a week grows it about equally — split the work however fits your week.',
      src: 'Schoenfeld, Grgic & Krieger, 2019 · meta-analysis',
    },
    {
      short: 'Longer rest, more gains',
      text: 'Resting 3 minutes between heavy sets built more muscle and strength than resting 1 minute.',
      src: 'Schoenfeld et al., 2016 · trial',
    },
    {
      short: 'Creatine really works',
      text: 'Creatine monohydrate, 3–5 g a day, adds to the strength and muscle you gain from training.',
      src: 'Kreider et al., 2017 · ISSN position stand',
    },
    {
      short: 'A short night costs strength',
      text: 'Too little sleep lowers strength on big compound lifts the next day.',
      src: 'Knowles et al., 2018 · meta-analysis',
    },
  ] as Fact[],
  // Atlas — common
  atlas: 'Atlas',
  meetAtlas: 'Meet Atlas',
  atlasOffSub: 'A coach who reads every set you log',
  turnOn: 'Turn on Atlas',
  openChat: 'Open chat',
  askAtlas: 'Ask Atlas',
  askAnything: 'Ask anything…',
  tryAsking: 'Try asking',
  lastAsked: (q: string) => `Last: “${q}”`,
  chipTrain: 'What should I train today?',
  chipRecovered: 'Am I recovered?',
  chipWeek: 'How was my week?',
  chipRest: 'How long should I rest?',
  chipLift: (x: string) => `How is my ${x} going?`,
  chipPlan: 'Make me a plan',
  chipSquat: 'How to squat properly?',
  tapToAsk: 'Tap to ask',
  betweenSets: 'A quick question between sets',
  // Insight
  noInsight: 'Nothing to flag',
  noInsightSub: 'Atlas speaks up when he spots a trend',
  gap: 'gap',
  setsOf: (m: string) => `${m} · sets`,
  kind: {
    intro: 'Atlas',
    session: 'Session',
    pr: 'Record',
    stall: 'Stall',
    restShort: 'Rest',
    setDrop: 'Reps',
    skipped: 'Missed',
    imbalance: 'Balance',
    week: 'Week',
    comeback: 'Comeback',
    shortSleep: 'Sleep',
    streak: 'Streak',
    bodyweight: 'Body weight',
  } as Record<string, string>,
  hImbalance: (low: string, high: string, p: number) => `${low} ${p}% under ${high}`,
  hStall: (ex: string, kg: string) => `${ex} stuck at ${kg}`,
  hRest: (ex: string) => `${ex}: rest cut short`,
  hDrop: (ex: string) => `${ex}: reps dropped`,
  hSleep: (h: string) => `Short night · ${h} h`,
  hComeback: (d: number) => `Back after a break · ${d} d`,
  hPr: (ex: string, kg: string) => `${ex} record · ${kg}`,
  hBody: (p: string) => `Body weight ${p}%`,
  hStreak: (n: number) => `Streak · ${n} d`,
  hWeek: (a: number, b: number) => `Week · ${a} of ${b} sessions`,
  hSkipped: 'Missed a session',
  hSession: (n: number) => `Session · ${n} sets`,
  hIntro: 'Atlas is in your corner',
  // Plan
  planToday: 'Atlas · today',
  planFor: (d: string) => `Atlas · plan for ${d}`,
  train: 'Train',
  light: 'Light',
  rest: 'Rest',
  exercisesN: (n: number) => `Exercises · ${n}`,
  minN: (n: number) => `~${n} min`,
  focus: 'Focus',
  start: 'Start',
  startX: (x: string) => `Start ${x}`,
  noPlan: 'No plan from Atlas',
  noPlanSub: 'Make Atlas your main coach — he writes the programme',
  restDay: 'Rest day',
  nextPlanDay: (d: string) => `Next session · ${d}`,
  doneToday: 'Done for today',
  doneTodaySub: 'Recover — Atlas plans the next one',
  readiness: 'Readiness',
  readinessP: (p: number) => `Readiness ${p}%`,
  stillRecovering: (m: string) => `${m} still recovering`,
  allFresh: 'Everything is fresh',
  // Debrief
  debrief: 'Debrief',
  winsChanges: (w: number, c: number) => `Wins ${w} · changes ${c}`,
  noDebrief: 'No session to review',
  noDebriefSub: 'Finish a workout — Atlas breaks it down',
  wentWell: 'Went well',
  nextTime: 'Next time',
  volume: 'Volume',
  sets: 'Sets',
  prShort: 'PR',
  time: 'Time',
  cleanSession: 'Clean session — nothing to change',
  winPr: (ex: string, set: string) => `${ex} ${set} — new best`,
  winComeback: (d: number) => `Back after ${d} days off — well done`,
  winSets: (n: number) => `All ${n} working sets done`,
  fixStall: (ex: string, kg: string) => `${ex} stuck at ${kg} — add a rep before adding weight`,
  fixRest: (ex: string, a: string, b: string) => `${ex}: rested ${a}, the plan was ${b}`,
  openSession: 'Open session',
  // Mood
  moodK: 'Atlas mood',
  whyMood: 'Why this mood',
  streak: 'Streak',
  daysN: (n: number) => `${n} d`,
  thisWeek: 'Sessions this week',
  soften: {
    injury: 'Injury — going easy on you',
    illness: 'Unwell — going easy on you',
    sleep: 'Short night — going easy on you',
    comeback: 'Comeback — going easy on you',
  } as Record<string, string>,
  normalDay: 'A normal day — your chosen temper',
  muted: 'Muted for today',
  talk: 'Talk to Atlas',
  // Notes
  notesK: 'Atlas notes',
  unread: (n: number) => `Unread · ${n}`,
  allRead: 'All caught up',
  allReadSub: 'Atlas writes after your next session',
  more: (n: number) => `+${n} more`,
  markRead: 'Mark all read',
  openNotes: 'Open notes',
  justNow: 'now',
  agoM: (n: number) => `${n} min`,
  agoH: (n: number) => `${n} h`,
  agoD: (n: number) => `${n} d`,
  // Weekly
  weekReview: 'Week review',
  sessionsOf: (a: number, b: number) => `${a} / ${b}`,
  sessionsK: 'Sessions',
  lifted: 'Lifted',
  records: 'Records',
  noWeek: 'No sessions last week',
  noWeekSub: 'Train this week — Atlas sums it up on Monday',
  fullReview: 'Full review',
  lineSessions: (a: number, b: number, t: string) => `${a} of ${b} sessions, ${t} lifted.`,
  lineRecord: (ex: string, set: string) => `New best: ${ex} ${set}.`,
  lineNoRecord: 'No new records — consistency first.',
  lineVolume: (d: string) => `Volume ${d}% vs the week before.`,
};

export type LearnAtlasStrings = typeof en;

const uk: LearnAtlasStrings = {
  names: {
    learnNext: 'Learn · наступний урок',
    lessonDay: 'Урок дня',
    saved: 'Збережені уроки',
    topics: 'Теми Learn',
    fact: 'А ти знав',
    insight: 'Порада Atlas',
    ask: 'Спитай Atlas',
    plan: 'План Atlas на сьогодні',
    debrief: 'Розбір від Atlas',
    mood: 'Настрій Atlas',
    notes: 'Нотатки Atlas',
    weekly: 'Тижневий підсумок Atlas',
    quickAsk: 'Спитай Atlas · один тап',
  },
  learn: 'Learn',
  lessons: 'уроків',
  lessonsWatched: 'уроків переглянуто',
  watchedOf: (a, b) => `${a} з ${b} уроків`,
  continueL: 'Продовжити',
  startLearning: 'Почати навчання',
  nextLesson: 'Наступний урок',
  upNext: 'Далі',
  upNextIn: (topic) => `Далі · ${topic}`,
  libraryProgress: 'Прогрес бібліотеки',
  soon: 'відео скоро',
  fresh: 'нове',
  watched: 'Переглянуто',
  watch: 'Дивитись',
  daily: 'Щодня',
  savedK: 'Збережені',
  savedN: (n) => `Збережені уроки · ${n}`,
  noSaved: 'Ще нічого не збережено',
  noSavedSub: 'Збережи урок у Learn, щоб подивитись пізніше',
  unwatched: (n) => `Не переглянуто · ${n}`,
  playAll: 'Дивитись усі',
  next: (x) => `Далі: ${x}`,
  topicsDone: (a, b) => `Тем завершено · ${a} з ${b}`,
  finish: (x) => `Далі: заверши ${x}`,
  allWatched: 'Усі уроки переглянуто',
  allWatchedSub: 'Переглядай будь-який знову в Learn',
  openLearn: 'Відкрити Learn',
  didYouKnow: 'А ти знав',
  science: 'Наука',
  factOf: (i, n) => `${i} з ${n}`,
  source: 'Джерело',
  facts: [
    {
      short: 'Підходи близько до відмови будують мʼязи',
      text: 'Підходи близько до відмови дають більше мʼязів — зупинитись за 0–3 повтори до відмови працює майже так само, як іти до кінця.',
      src: 'Robinson et al., 2024 · метааналіз',
    },
    {
      short: 'Легка чи важка вага — ростуть обидві',
      text: 'Від ~30% до 80%+ від максимуму вага дає схожий ріст мʼязів, якщо підхід закінчується близько до відмови. Для сили важка все ж краща.',
      src: 'Schoenfeld et al., 2017 · метааналіз',
    },
    {
      short: 'Більше підходів на тиждень — більше росту',
      text: 'Ріст мʼязів зростає з кількістю важких підходів на мʼяз за тиждень — 10 і більше кращі за кілька.',
      src: 'Schoenfeld, Ogborn & Krieger, 2017 · метааналіз',
    },
    {
      short: 'Білок працює до ~1,6 г/кг',
      text: 'Понад ~1,6 г білка на кг ваги тіла на день додатковий білок уже не додає мʼязів.',
      src: 'Morton et al., 2018 · метааналіз',
    },
    {
      short: 'Розподіляй підходи як зручно',
      text: 'За однакової кількості підходів на тиждень тренувати мʼяз раз чи двічі на тиждень — ріст приблизно однаковий. Розподіляй як зручно.',
      src: 'Schoenfeld, Grgic & Krieger, 2019 · метааналіз',
    },
    {
      short: 'Довший відпочинок — більше результату',
      text: 'Відпочинок 3 хвилини між важкими підходами дав більше мʼязів і сили, ніж 1 хвилина.',
      src: 'Schoenfeld et al., 2016 · дослідження',
    },
    {
      short: 'Креатин справді працює',
      text: 'Креатин моногідрат, 3–5 г на день, додає до сили й мʼязів, які ти набираєш тренуваннями.',
      src: 'Kreider et al., 2017 · позиція ISSN',
    },
    {
      short: 'Коротка ніч забирає силу',
      text: 'Недосип знижує силу в базових вправах наступного дня.',
      src: 'Knowles et al., 2018 · метааналіз',
    },
  ],
  atlas: 'Atlas',
  meetAtlas: 'Знайомся: Atlas',
  atlasOffSub: 'Тренер, який читає кожен твій підхід',
  turnOn: 'Увімкнути Atlas',
  openChat: 'Відкрити чат',
  askAtlas: 'Спитай Atlas',
  askAnything: 'Питай що завгодно…',
  tryAsking: 'Спробуй спитати',
  lastAsked: (q) => `Востаннє: «${q}»`,
  chipTrain: 'Що тренувати сьогодні?',
  chipRecovered: 'Я відновився?',
  chipWeek: 'Як мій тиждень?',
  chipRest: 'Скільки відпочивати?',
  chipLift: (x) => `Як прогресує ${x}?`,
  chipPlan: 'Склади мені план',
  chipSquat: 'Як правильно присідати?',
  tapToAsk: 'Тапни, щоб спитати',
  betweenSets: 'Швидке питання між підходами',
  noInsight: 'Нічого тривожного',
  noInsightSub: 'Atlas скаже, коли помітить тренд',
  gap: 'розрив',
  setsOf: (m) => `${m} · підходи`,
  kind: {
    intro: 'Atlas',
    session: 'Тренування',
    pr: 'Рекорд',
    stall: 'Застій',
    restShort: 'Відпочинок',
    setDrop: 'Повтори',
    skipped: 'Пропуск',
    imbalance: 'Баланс',
    week: 'Тиждень',
    comeback: 'Повернення',
    shortSleep: 'Сон',
    streak: 'Серія',
    bodyweight: 'Вага тіла',
  },
  hImbalance: (low, high, p) => `${low} на ${p}% менше за ${high}`,
  hStall: (ex, kg) => `${ex} стоїть на ${kg}`,
  hRest: (ex) => `${ex}: відпочинок закороткий`,
  hDrop: (ex) => `${ex}: повтори просіли`,
  hSleep: (h) => `Коротка ніч · ${h} год`,
  hComeback: (d) => `Повернення після перерви · ${d} дн`,
  hPr: (ex, kg) => `${ex}: рекорд · ${kg}`,
  hBody: (p) => `Вага тіла ${p}%`,
  hStreak: (n) => `Серія · ${n} дн`,
  hWeek: (a, b) => `Тиждень · ${a} з ${b} тренувань`,
  hSkipped: 'Пропущене тренування',
  hSession: (n) => `Тренування · підходів ${n}`,
  hIntro: 'Atlas на твоєму боці',
  planToday: 'Atlas · сьогодні',
  planFor: (d) => `Atlas · план на ${d}`,
  train: 'Тренування',
  light: 'Легко',
  rest: 'Відпочинок',
  exercisesN: (n) => `Вправ · ${n}`,
  minN: (n) => `~${n} хв`,
  focus: 'Фокус',
  start: 'Почати',
  startX: (x) => `Почати: ${x}`,
  noPlan: 'Atlas ще не склав план',
  noPlanSub: 'Зроби Atlas головним тренером — він напише програму',
  restDay: 'День відпочинку',
  nextPlanDay: (d) => `Наступне тренування · ${d}`,
  doneToday: 'На сьогодні все',
  doneTodaySub: 'Відновлюйся — Atlas спланує наступне',
  readiness: 'Готовність',
  readinessP: (p) => `Готовність ${p}%`,
  stillRecovering: (m) => `${m} ще відновлюється`,
  allFresh: 'Усе свіже',
  debrief: 'Розбір',
  winsChanges: (w, c) => `Вдалося ${w} · змінити ${c}`,
  noDebrief: 'Немає тренування для розбору',
  noDebriefSub: 'Заверши тренування — Atlas його розбере',
  wentWell: 'Що вдалося',
  nextTime: 'Наступного разу',
  volume: 'Обʼєм',
  sets: 'Підходи',
  prShort: 'PR',
  time: 'Час',
  cleanSession: 'Чисте тренування — нічого не змінюй',
  winPr: (ex, set) => `${ex} ${set} — новий рекорд`,
  winComeback: (d) => `Повернувся після ${d} дн перерви — так тримати`,
  winSets: (n) => `Усі робочі підходи (${n}) виконано`,
  fixStall: (ex, kg) => `${ex} стоїть на ${kg} — спершу додай повтор, потім вагу`,
  fixRest: (ex, a, b) => `${ex}: відпочинок ${a}, за планом ${b}`,
  openSession: 'Відкрити тренування',
  moodK: 'Настрій Atlas',
  whyMood: 'Чому такий настрій',
  streak: 'Серія',
  daysN: (n) => `${n} дн`,
  thisWeek: 'Тренувань цього тижня',
  soften: {
    injury: 'Травма — Atlas мʼякший',
    illness: 'Хворієш — Atlas мʼякший',
    sleep: 'Коротка ніч — Atlas мʼякший',
    comeback: 'Повернення — Atlas мʼякший',
  },
  normalDay: 'Звичайний день — обраний темперамент',
  muted: 'Вимкнено на сьогодні',
  talk: 'Поговорити з Atlas',
  notesK: 'Нотатки Atlas',
  unread: (n) => `Непрочитані · ${n}`,
  allRead: 'Усе прочитано',
  allReadSub: 'Atlas напише після наступного тренування',
  more: (n) => `+${n} ще`,
  markRead: 'Прочитати все',
  openNotes: 'Відкрити нотатки',
  justNow: 'щойно',
  agoM: (n) => `${n} хв`,
  agoH: (n) => `${n} год`,
  agoD: (n) => `${n} дн`,
  weekReview: 'Підсумок тижня',
  sessionsOf: (a, b) => `${a} / ${b}`,
  sessionsK: 'Тренування',
  lifted: 'Піднято',
  records: 'Рекорди',
  noWeek: 'Минулого тижня тренувань не було',
  noWeekSub: 'Тренуйся цього тижня — Atlas підсумує в понеділок',
  fullReview: 'Повний розбір',
  lineSessions: (a, b, t) => `${a} з ${b} тренувань, піднято ${t}.`,
  lineRecord: (ex, set) => `Новий рекорд: ${ex} ${set}.`,
  lineNoRecord: 'Без нових рекордів — спершу регулярність.',
  lineVolume: (d) => `Обʼєм ${d}% до попереднього тижня.`,
};

const pl: LearnAtlasStrings = {
  names: {
    learnNext: 'Learn · następna lekcja',
    lessonDay: 'Lekcja dnia',
    saved: 'Zapisane lekcje',
    topics: 'Tematy Learn',
    fact: 'Czy wiesz, że',
    insight: 'Wskazówka Atlasa',
    ask: 'Zapytaj Atlasa',
    plan: 'Plan Atlasa na dziś',
    debrief: 'Omówienie Atlasa',
    mood: 'Nastrój Atlasa',
    notes: 'Notatki Atlasa',
    weekly: 'Podsumowanie tygodnia Atlasa',
    quickAsk: 'Zapytaj Atlasa · jedno dotknięcie',
  },
  learn: 'Learn',
  lessons: 'lekcji',
  lessonsWatched: 'lekcji obejrzanych',
  watchedOf: (a, b) => `${a} z ${b} lekcji`,
  continueL: 'Kontynuuj',
  startLearning: 'Zacznij naukę',
  nextLesson: 'Następna lekcja',
  upNext: 'Dalej',
  upNextIn: (topic) => `Dalej · ${topic}`,
  libraryProgress: 'Postęp biblioteki',
  soon: 'wideo wkrótce',
  fresh: 'nowa',
  watched: 'Obejrzane',
  watch: 'Oglądaj',
  daily: 'Codziennie',
  savedK: 'Zapisane',
  savedN: (n) => `Zapisane lekcje · ${n}`,
  noSaved: 'Nic jeszcze nie zapisano',
  noSavedSub: 'Zapisz lekcję w Learn, by obejrzeć ją później',
  unwatched: (n) => `Nieobejrzane · ${n}`,
  playAll: 'Odtwórz wszystko',
  next: (x) => `Dalej: ${x}`,
  topicsDone: (a, b) => `Ukończone tematy · ${a} z ${b}`,
  finish: (x) => `Dalej: dokończ ${x}`,
  allWatched: 'Wszystkie lekcje obejrzane',
  allWatchedSub: 'Obejrzyj dowolną ponownie w Learn',
  openLearn: 'Otwórz Learn',
  didYouKnow: 'Czy wiesz, że',
  science: 'Nauka',
  factOf: (i, n) => `${i} z ${n}`,
  source: 'Źródło',
  facts: [
    {
      short: 'Serie blisko upadku budują mięśnie',
      text: 'Serie blisko upadku mięśniowego budują więcej mięśni — przerwanie 0–3 powtórzenia przed upadkiem działa prawie tak samo jak dojście do końca.',
      src: 'Robinson et al., 2024 · metaanaliza',
    },
    {
      short: 'Lekko czy ciężko — rosną obie',
      text: 'Od ok. 30% do 80%+ maksimum ciężar buduje podobnie mięśnie, gdy seria kończy się blisko upadku. Dla siły ciężko wciąż wygrywa.',
      src: 'Schoenfeld et al., 2017 · metaanaliza',
    },
    {
      short: 'Więcej serii w tygodniu, więcej wzrostu',
      text: 'Wzrost mięśni rośnie z liczbą ciężkich serii na mięsień w tygodniu — 10 i więcej wygrywa z kilkoma.',
      src: 'Schoenfeld, Ogborn & Krieger, 2017 · metaanaliza',
    },
    {
      short: 'Białko przestaje działać ok. 1,6 g/kg',
      text: 'Powyżej ok. 1,6 g białka na kg masy ciała dziennie dodatkowe białko nie dokłada już mięśni.',
      src: 'Morton et al., 2018 · metaanaliza',
    },
    {
      short: 'Dziel serie tygodniowe dowolnie',
      text: 'Przy tej samej liczbie serii w tygodniu trening mięśnia raz lub dwa razy w tygodniu daje podobny wzrost — dziel pracę, jak ci pasuje.',
      src: 'Schoenfeld, Grgic & Krieger, 2019 · metaanaliza',
    },
    {
      short: 'Dłuższa przerwa, lepsze efekty',
      text: 'Przerwa 3 minut między ciężkimi seriami dała więcej mięśni i siły niż 1 minuta.',
      src: 'Schoenfeld et al., 2016 · badanie',
    },
    {
      short: 'Kreatyna naprawdę działa',
      text: 'Monohydrat kreatyny, 3–5 g dziennie, zwiększa przyrost siły i mięśni z treningu.',
      src: 'Kreider et al., 2017 · stanowisko ISSN',
    },
    {
      short: 'Krótka noc kosztuje siłę',
      text: 'Za mało snu obniża siłę w dużych ćwiczeniach wielostawowych następnego dnia.',
      src: 'Knowles et al., 2018 · metaanaliza',
    },
  ],
  atlas: 'Atlas',
  meetAtlas: 'Poznaj Atlasa',
  atlasOffSub: 'Trener, który czyta każdą twoją serię',
  turnOn: 'Włącz Atlasa',
  openChat: 'Otwórz czat',
  askAtlas: 'Zapytaj Atlasa',
  askAnything: 'Zapytaj o cokolwiek…',
  tryAsking: 'Spróbuj zapytać',
  lastAsked: (q) => `Ostatnio: „${q}”`,
  chipTrain: 'Co dziś trenować?',
  chipRecovered: 'Czy jestem zregenerowany?',
  chipWeek: 'Jak minął mój tydzień?',
  chipRest: 'Ile odpoczywać?',
  chipLift: (x) => `Jak idzie ${x}?`,
  chipPlan: 'Ułóż mi plan',
  chipSquat: 'Jak poprawnie robić przysiad?',
  tapToAsk: 'Dotknij, aby zapytać',
  betweenSets: 'Szybkie pytanie między seriami',
  noInsight: 'Nic do zgłoszenia',
  noInsightSub: 'Atlas odezwie się, gdy zauważy trend',
  gap: 'różnica',
  setsOf: (m) => `${m} · serie`,
  kind: {
    intro: 'Atlas',
    session: 'Trening',
    pr: 'Rekord',
    stall: 'Zastój',
    restShort: 'Przerwa',
    setDrop: 'Powtórzenia',
    skipped: 'Pominięty',
    imbalance: 'Balans',
    week: 'Tydzień',
    comeback: 'Powrót',
    shortSleep: 'Sen',
    streak: 'Seria dni',
    bodyweight: 'Masa ciała',
  },
  hImbalance: (low, high, p) => `${low} o ${p}% poniżej ${high}`,
  hStall: (ex, kg) => `${ex} stoi na ${kg}`,
  hRest: (ex) => `${ex}: za krótka przerwa`,
  hDrop: (ex) => `${ex}: spadły powtórzenia`,
  hSleep: (h) => `Krótka noc · ${h} h`,
  hComeback: (d) => `Powrót po przerwie · ${d} dni`,
  hPr: (ex, kg) => `${ex}: rekord · ${kg}`,
  hBody: (p) => `Masa ciała ${p}%`,
  hStreak: (n) => `Seria · ${n} dni`,
  hWeek: (a, b) => `Tydzień · ${a} z ${b} treningów`,
  hSkipped: 'Pominięty trening',
  hSession: (n) => `Trening · serie ${n}`,
  hIntro: 'Atlas jest po twojej stronie',
  planToday: 'Atlas · dziś',
  planFor: (d) => `Atlas · plan na ${d}`,
  train: 'Trening',
  light: 'Lekko',
  rest: 'Odpoczynek',
  exercisesN: (n) => `Ćwiczenia · ${n}`,
  minN: (n) => `~${n} min`,
  focus: 'Cel',
  start: 'Start',
  startX: (x) => `Start: ${x}`,
  noPlan: 'Brak planu od Atlasa',
  noPlanSub: 'Zrób Atlasa głównym trenerem — napisze program',
  restDay: 'Dzień odpoczynku',
  nextPlanDay: (d) => `Następny trening · ${d}`,
  doneToday: 'Na dziś koniec',
  doneTodaySub: 'Regeneruj się — Atlas zaplanuje następny',
  readiness: 'Gotowość',
  readinessP: (p) => `Gotowość ${p}%`,
  stillRecovering: (m) => `${m} jeszcze się regeneruje`,
  allFresh: 'Wszystko wypoczęte',
  debrief: 'Omówienie',
  winsChanges: (w, c) => `Sukcesy ${w} · zmiany ${c}`,
  noDebrief: 'Brak treningu do omówienia',
  noDebriefSub: 'Skończ trening — Atlas go omówi',
  wentWell: 'Poszło dobrze',
  nextTime: 'Następnym razem',
  volume: 'Objętość',
  sets: 'Serie',
  prShort: 'PR',
  time: 'Czas',
  cleanSession: 'Czysty trening — nic do zmiany',
  winPr: (ex, set) => `${ex} ${set} — nowy rekord`,
  winComeback: (d) => `Powrót po ${d} dniach przerwy — brawo`,
  winSets: (n) => `Wszystkie serie robocze (${n}) zrobione`,
  fixStall: (ex, kg) => `${ex} stoi na ${kg} — najpierw dodaj powtórzenie, potem ciężar`,
  fixRest: (ex, a, b) => `${ex}: przerwa ${a}, w planie ${b}`,
  openSession: 'Otwórz trening',
  moodK: 'Nastrój Atlasa',
  whyMood: 'Skąd ten nastrój',
  streak: 'Seria',
  daysN: (n) => `${n} dni`,
  thisWeek: 'Treningi w tym tygodniu',
  soften: {
    injury: 'Kontuzja — Atlas łagodniejszy',
    illness: 'Choroba — Atlas łagodniejszy',
    sleep: 'Krótka noc — Atlas łagodniejszy',
    comeback: 'Powrót — Atlas łagodniejszy',
  },
  normalDay: 'Zwykły dzień — wybrany temperament',
  muted: 'Wyciszony na dziś',
  talk: 'Porozmawiaj z Atlasem',
  notesK: 'Notatki Atlasa',
  unread: (n) => `Nieprzeczytane · ${n}`,
  allRead: 'Wszystko przeczytane',
  allReadSub: 'Atlas napisze po następnym treningu',
  more: (n) => `+${n} więcej`,
  markRead: 'Oznacz jako przeczytane',
  openNotes: 'Otwórz notatki',
  justNow: 'teraz',
  agoM: (n) => `${n} min`,
  agoH: (n) => `${n} godz.`,
  agoD: (n) => `${n} d.`,
  weekReview: 'Podsumowanie tygodnia',
  sessionsOf: (a, b) => `${a} / ${b}`,
  sessionsK: 'Treningi',
  lifted: 'Podniesiono',
  records: 'Rekordy',
  noWeek: 'Brak treningów w zeszłym tygodniu',
  noWeekSub: 'Trenuj w tym tygodniu — Atlas podsumuje w poniedziałek',
  fullReview: 'Pełne omówienie',
  lineSessions: (a, b, t) => `${a} z ${b} treningów, podniesiono ${t}.`,
  lineRecord: (ex, set) => `Nowy rekord: ${ex} ${set}.`,
  lineNoRecord: 'Bez nowych rekordów — najpierw regularność.',
  lineVolume: (d) => `Objętość ${d}% względem poprzedniego tygodnia.`,
};

const lt: LearnAtlasStrings = {
  names: {
    learnNext: 'Learn · kita pamoka',
    lessonDay: 'Dienos pamoka',
    saved: 'Išsaugotos pamokos',
    topics: 'Learn temos',
    fact: 'Ar žinojai',
    insight: 'Atlas įžvalga',
    ask: 'Klausk Atlas',
    plan: 'Atlas planas šiandienai',
    debrief: 'Atlas aptarimas',
    mood: 'Atlas nuotaika',
    notes: 'Atlas pastabos',
    weekly: 'Atlas savaitės apžvalga',
    quickAsk: 'Klausk Atlas · vienu palietimu',
  },
  learn: 'Learn',
  lessons: 'pamokų',
  lessonsWatched: 'pamokų peržiūrėta',
  watchedOf: (a, b) => `${a} iš ${b} pamokų`,
  continueL: 'Tęsti',
  startLearning: 'Pradėti mokytis',
  nextLesson: 'Kita pamoka',
  upNext: 'Toliau',
  upNextIn: (topic) => `Toliau · ${topic}`,
  libraryProgress: 'Bibliotekos pažanga',
  soon: 'vaizdo įrašas netrukus',
  fresh: 'nauja',
  watched: 'Peržiūrėta',
  watch: 'Žiūrėti',
  daily: 'Kasdien',
  savedK: 'Išsaugota',
  savedN: (n) => `Išsaugotos pamokos · ${n}`,
  noSaved: 'Dar nieko neišsaugota',
  noSavedSub: 'Išsaugok pamoką Learn ir peržiūrėk vėliau',
  unwatched: (n) => `Neperžiūrėta · ${n}`,
  playAll: 'Leisti visas',
  next: (x) => `Toliau: ${x}`,
  topicsDone: (a, b) => `Baigta temų · ${a} iš ${b}`,
  finish: (x) => `Toliau: užbaik ${x}`,
  allWatched: 'Visos pamokos peržiūrėtos',
  allWatchedSub: 'Bet kurią gali peržiūrėti Learn dar kartą',
  openLearn: 'Atidaryti Learn',
  didYouKnow: 'Ar žinojai',
  science: 'Mokslas',
  factOf: (i, n) => `${i} iš ${n}`,
  source: 'Šaltinis',
  facts: [
    {
      short: 'Serijos arti nesėkmės augina raumenis',
      text: 'Serijos arti raumenų nesėkmės augina daugiau raumenų — sustoti likus 0–3 pakartojimams veikia beveik taip pat, kaip eiti iki galo.',
      src: 'Robinson et al., 2024 · metaanalizė',
    },
    {
      short: 'Lengvas ar sunkus — auga abu',
      text: 'Nuo ~30% iki 80%+ maksimumo svoris augina raumenis panašiai, jei serija baigiasi arti nesėkmės. Jėgai sunkus vis tiek geresnis.',
      src: 'Schoenfeld et al., 2017 · metaanalizė',
    },
    {
      short: 'Daugiau serijų per savaitę — daugiau augimo',
      text: 'Raumenų augimas didėja su sunkių serijų skaičiumi raumeniui per savaitę — 10 ir daugiau pranoksta kelias.',
      src: 'Schoenfeld, Ogborn & Krieger, 2017 · metaanalizė',
    },
    {
      short: 'Baltymų nauda baigiasi ties ~1,6 g/kg',
      text: 'Virš ~1,6 g baltymų kilogramui kūno svorio per dieną papildomi baltymai raumenų nebeprideda.',
      src: 'Morton et al., 2018 · metaanalizė',
    },
    {
      short: 'Savaitės serijas skirstyk kaip patogu',
      text: 'Esant tam pačiam serijų skaičiui per savaitę, raumenį treniruojant kartą ar du kartus per savaitę jis auga panašiai — skirstyk darbą kaip patogu.',
      src: 'Schoenfeld, Grgic & Krieger, 2019 · metaanalizė',
    },
    {
      short: 'Ilgesnis poilsis — daugiau naudos',
      text: '3 minučių poilsis tarp sunkių serijų davė daugiau raumenų ir jėgos nei 1 minutė.',
      src: 'Schoenfeld et al., 2016 · tyrimas',
    },
    {
      short: 'Kreatinas tikrai veikia',
      text: 'Kreatino monohidratas, 3–5 g per dieną, padidina treniruotėmis įgyjamą jėgą ir raumenis.',
      src: 'Kreider et al., 2017 · ISSN pozicija',
    },
    {
      short: 'Trumpa naktis atima jėgą',
      text: 'Per mažai miego kitą dieną sumažina jėgą pagrindiniuose kompleksiniuose pratimuose.',
      src: 'Knowles et al., 2018 · metaanalizė',
    },
  ],
  atlas: 'Atlas',
  meetAtlas: 'Susipažink su Atlas',
  atlasOffSub: 'Treneris, kuris skaito kiekvieną tavo seriją',
  turnOn: 'Įjungti Atlas',
  openChat: 'Atidaryti pokalbį',
  askAtlas: 'Klausk Atlas',
  askAnything: 'Klausk ko nori…',
  tryAsking: 'Pabandyk paklausti',
  lastAsked: (q) => `Paskutinis: „${q}“`,
  chipTrain: 'Ką šiandien treniruoti?',
  chipRecovered: 'Ar atsigavau?',
  chipWeek: 'Kaip sekėsi savaitė?',
  chipRest: 'Kiek ilsėtis?',
  chipLift: (x) => `Kaip sekasi ${x}?`,
  chipPlan: 'Sudaryk man planą',
  chipSquat: 'Kaip taisyklingai pritūpti?',
  tapToAsk: 'Paliesk ir klausk',
  betweenSets: 'Greitas klausimas tarp serijų',
  noInsight: 'Nieko ypatingo',
  noInsightSub: 'Atlas prabils, kai pastebės tendenciją',
  gap: 'skirtumas',
  setsOf: (m) => `${m} · serijos`,
  kind: {
    intro: 'Atlas',
    session: 'Treniruotė',
    pr: 'Rekordas',
    stall: 'Sąstingis',
    restShort: 'Poilsis',
    setDrop: 'Pakartojimai',
    skipped: 'Praleista',
    imbalance: 'Balansas',
    week: 'Savaitė',
    comeback: 'Sugrįžimas',
    shortSleep: 'Miegas',
    streak: 'Serija',
    bodyweight: 'Kūno svoris',
  },
  hImbalance: (low, high, p) => `${low} ${p}% mažiau nei ${high}`,
  hStall: (ex, kg) => `${ex} stovi ties ${kg}`,
  hRest: (ex) => `${ex}: per trumpas poilsis`,
  hDrop: (ex) => `${ex}: krito pakartojimai`,
  hSleep: (h) => `Trumpa naktis · ${h} val.`,
  hComeback: (d) => `Sugrįžimas po pertraukos · ${d} d.`,
  hPr: (ex, kg) => `${ex}: rekordas · ${kg}`,
  hBody: (p) => `Kūno svoris ${p}%`,
  hStreak: (n) => `Serija · ${n} d.`,
  hWeek: (a, b) => `Savaitė · ${a} iš ${b} treniruočių`,
  hSkipped: 'Praleista treniruotė',
  hSession: (n) => `Treniruotė · serijų ${n}`,
  hIntro: 'Atlas tavo pusėje',
  planToday: 'Atlas · šiandien',
  planFor: (d) => `Atlas · planas ${d}`,
  train: 'Treniruotė',
  light: 'Lengvai',
  rest: 'Poilsis',
  exercisesN: (n) => `Pratimai · ${n}`,
  minN: (n) => `~${n} min.`,
  focus: 'Dėmesys',
  start: 'Pradėti',
  startX: (x) => `Pradėti: ${x}`,
  noPlan: 'Atlas plano dar nėra',
  noPlanSub: 'Padaryk Atlas pagrindiniu treneriu — jis parašys programą',
  restDay: 'Poilsio diena',
  nextPlanDay: (d) => `Kita treniruotė · ${d}`,
  doneToday: 'Šiandienai viskas',
  doneTodaySub: 'Atsigauk — Atlas suplanuos kitą',
  readiness: 'Pasirengimas',
  readinessP: (p) => `Pasirengimas ${p}%`,
  stillRecovering: (m) => `${m} dar atsigauna`,
  allFresh: 'Viskas pailsėję',
  debrief: 'Aptarimas',
  winsChanges: (w, c) => `Pavyko ${w} · keisti ${c}`,
  noDebrief: 'Nėra treniruotės aptarimui',
  noDebriefSub: 'Baik treniruotę — Atlas ją aptars',
  wentWell: 'Kas pavyko',
  nextTime: 'Kitą kartą',
  volume: 'Apimtis',
  sets: 'Serijos',
  prShort: 'PR',
  time: 'Laikas',
  cleanSession: 'Švari treniruotė — nieko nekeisk',
  winPr: (ex, set) => `${ex} ${set} — naujas rekordas`,
  winComeback: (d) => `Sugrįžai po ${d} d. pertraukos — šaunu`,
  winSets: (n) => `Atliktos visos darbinės serijos (${n})`,
  fixStall: (ex, kg) => `${ex} stovi ties ${kg} — pirma pridėk pakartojimą, paskui svorį`,
  fixRest: (ex, a, b) => `${ex}: ilsėjaisi ${a}, plane ${b}`,
  openSession: 'Atidaryti treniruotę',
  moodK: 'Atlas nuotaika',
  whyMood: 'Kodėl tokia nuotaika',
  streak: 'Serija',
  daysN: (n) => `${n} d.`,
  thisWeek: 'Treniruotės šią savaitę',
  soften: {
    injury: 'Trauma — Atlas švelnesnis',
    illness: 'Sergi — Atlas švelnesnis',
    sleep: 'Trumpa naktis — Atlas švelnesnis',
    comeback: 'Sugrįžimas — Atlas švelnesnis',
  },
  normalDay: 'Įprasta diena — pasirinktas temperamentas',
  muted: 'Nutildytas šiandien',
  talk: 'Kalbėtis su Atlas',
  notesK: 'Atlas pastabos',
  unread: (n) => `Neskaitytos · ${n}`,
  allRead: 'Viskas perskaityta',
  allReadSub: 'Atlas parašys po kitos treniruotės',
  more: (n) => `+${n} daugiau`,
  markRead: 'Pažymėti perskaitytomis',
  openNotes: 'Atidaryti pastabas',
  justNow: 'dabar',
  agoM: (n) => `${n} min.`,
  agoH: (n) => `${n} val.`,
  agoD: (n) => `${n} d.`,
  weekReview: 'Savaitės apžvalga',
  sessionsOf: (a, b) => `${a} / ${b}`,
  sessionsK: 'Treniruotės',
  lifted: 'Pakelta',
  records: 'Rekordai',
  noWeek: 'Praėjusią savaitę treniruočių nebuvo',
  noWeekSub: 'Treniruokis šią savaitę — Atlas apibendrins pirmadienį',
  fullReview: 'Visa apžvalga',
  lineSessions: (a, b, t) => `${a} iš ${b} treniruočių, pakelta ${t}.`,
  lineRecord: (ex, set) => `Naujas rekordas: ${ex} ${set}.`,
  lineNoRecord: 'Naujų rekordų nėra — pirmiausia reguliarumas.',
  lineVolume: (d) => `Apimtis ${d}% palyginti su ankstesne savaite.`,
};

const et: LearnAtlasStrings = {
  names: {
    learnNext: 'Learn · järgmine tund',
    lessonDay: 'Päeva tund',
    saved: 'Salvestatud tunnid',
    topics: 'Learni teemad',
    fact: 'Kas teadsid',
    insight: 'Atlase tähelepanek',
    ask: 'Küsi Atlaselt',
    plan: 'Atlase tänane plaan',
    debrief: 'Atlase kokkuvõte',
    mood: 'Atlase meeleolu',
    notes: 'Atlase märkmed',
    weekly: 'Atlase nädalaülevaade',
    quickAsk: 'Küsi Atlaselt · ühe puutega',
  },
  learn: 'Learn',
  lessons: 'tundi',
  lessonsWatched: 'tundi vaadatud',
  watchedOf: (a, b) => `${a} / ${b} tundi`,
  continueL: 'Jätka',
  startLearning: 'Alusta õppimist',
  nextLesson: 'Järgmine tund',
  upNext: 'Järgmisena',
  upNextIn: (topic) => `Järgmisena · ${topic}`,
  libraryProgress: 'Kogu edenemine',
  soon: 'video peagi',
  fresh: 'uus',
  watched: 'Vaadatud',
  watch: 'Vaata',
  daily: 'Iga päev',
  savedK: 'Salvestatud',
  savedN: (n) => `Salvestatud tunnid · ${n}`,
  noSaved: 'Midagi pole veel salvestatud',
  noSavedSub: 'Salvesta tund Learnis, et seda hiljem vaadata',
  unwatched: (n) => `Vaatamata · ${n}`,
  playAll: 'Esita kõik',
  next: (x) => `Järgmisena: ${x}`,
  topicsDone: (a, b) => `Teemasid tehtud · ${a} / ${b}`,
  finish: (x) => `Järgmisena: lõpeta ${x}`,
  allWatched: 'Kõik tunnid vaadatud',
  allWatchedSub: 'Vaata ükskõik millist Learnis uuesti',
  openLearn: 'Ava Learn',
  didYouKnow: 'Kas teadsid',
  science: 'Teadus',
  factOf: (i, n) => `${i} / ${n}`,
  source: 'Allikas',
  facts: [
    {
      short: 'Seeriad väsimuse lähedal kasvatavad lihast',
      text: 'Lihasväsimuse lähedale viidud seeriad kasvatavad rohkem lihast — 0–3 kordust enne lõppu peatumine toimib peaaegu sama hästi kui lõpuni minek.',
      src: 'Robinson et al., 2024 · metaanalüüs',
    },
    {
      short: 'Kerge või raske — kasvavad mõlemad',
      text: 'Umbes 30%-st kuni 80%+ maksimumist kasvatab koormus lihast sarnaselt, kui seeria lõpeb väsimuse lähedal. Jõu jaoks on raske siiski parem.',
      src: 'Schoenfeld et al., 2017 · metaanalüüs',
    },
    {
      short: 'Rohkem seeriaid nädalas, rohkem kasvu',
      text: 'Lihaskasv suureneb raskete seeriate arvuga lihase kohta nädalas — 10 või rohkem on parem kui paar.',
      src: 'Schoenfeld, Ogborn & Krieger, 2017 · metaanalüüs',
    },
    {
      short: 'Valgu kasu lõpeb ~1,6 g/kg juures',
      text: 'Üle ~1,6 g valku kehakaalu kilo kohta päevas lisavalk enam lihast juurde ei anna.',
      src: 'Morton et al., 2018 · metaanalüüs',
    },
    {
      short: 'Jaga nädala seeriad, kuidas sobib',
      text: 'Sama nädalase seeriate arvu juures kasvab lihas üks või kaks korda nädalas treenides umbes võrdselt — jaga töö, kuidas sobib.',
      src: 'Schoenfeld, Grgic & Krieger, 2019 · metaanalüüs',
    },
    {
      short: 'Pikem puhkus, parem tulemus',
      text: '3-minutiline puhkus raskete seeriate vahel andis rohkem lihast ja jõudu kui 1 minut.',
      src: 'Schoenfeld et al., 2016 · uuring',
    },
    {
      short: 'Kreatiin tõesti toimib',
      text: 'Kreatiinmonohüdraat, 3–5 g päevas, suurendab treeninguga saadavat jõudu ja lihasmassi.',
      src: 'Kreider et al., 2017 · ISSN seisukoht',
    },
    {
      short: 'Lühike öö võtab jõudu',
      text: 'Liiga vähene uni vähendab järgmisel päeval jõudu suurtes liitharjutustes.',
      src: 'Knowles et al., 2018 · metaanalüüs',
    },
  ],
  atlas: 'Atlas',
  meetAtlas: 'Tutvu Atlasega',
  atlasOffSub: 'Treener, kes loeb iga su seeriat',
  turnOn: 'Lülita Atlas sisse',
  openChat: 'Ava vestlus',
  askAtlas: 'Küsi Atlaselt',
  askAnything: 'Küsi mida tahes…',
  tryAsking: 'Proovi küsida',
  lastAsked: (q) => `Viimati: „${q}“`,
  chipTrain: 'Mida täna treenida?',
  chipRecovered: 'Kas olen taastunud?',
  chipWeek: 'Kuidas mu nädal läks?',
  chipRest: 'Kui kaua puhata?',
  chipLift: (x) => `Kuidas ${x} edeneb?`,
  chipPlan: 'Tee mulle plaan',
  chipSquat: 'Kuidas õigesti kükitada?',
  tapToAsk: 'Puuduta ja küsi',
  betweenSets: 'Kiire küsimus seeriate vahel',
  noInsight: 'Midagi märkimisväärset pole',
  noInsightSub: 'Atlas annab märku, kui näeb trendi',
  gap: 'vahe',
  setsOf: (m) => `${m} · seeriad`,
  kind: {
    intro: 'Atlas',
    session: 'Treening',
    pr: 'Rekord',
    stall: 'Seisak',
    restShort: 'Puhkus',
    setDrop: 'Kordused',
    skipped: 'Vahele jäänud',
    imbalance: 'Tasakaal',
    week: 'Nädal',
    comeback: 'Tagasitulek',
    shortSleep: 'Uni',
    streak: 'Seeria',
    bodyweight: 'Kehakaal',
  },
  hImbalance: (low, high, p) => `${low} ${p}% alla ${high}`,
  hStall: (ex, kg) => `${ex} seisab ${kg} juures`,
  hRest: (ex) => `${ex}: puhkus liiga lühike`,
  hDrop: (ex) => `${ex}: kordused langesid`,
  hSleep: (h) => `Lühike öö · ${h} h`,
  hComeback: (d) => `Tagasi pärast pausi · ${d} p`,
  hPr: (ex, kg) => `${ex}: rekord · ${kg}`,
  hBody: (p) => `Kehakaal ${p}%`,
  hStreak: (n) => `Seeria · ${n} p`,
  hWeek: (a, b) => `Nädal · ${a} / ${b} treeningut`,
  hSkipped: 'Vahele jäänud treening',
  hSession: (n) => `Treening · seeriaid ${n}`,
  hIntro: 'Atlas on sinu poolel',
  planToday: 'Atlas · täna',
  planFor: (d) => `Atlas · plaan: ${d}`,
  train: 'Treening',
  light: 'Kerge',
  rest: 'Puhkus',
  exercisesN: (n) => `Harjutusi · ${n}`,
  minN: (n) => `~${n} min`,
  focus: 'Fookus',
  start: 'Alusta',
  startX: (x) => `Alusta: ${x}`,
  noPlan: 'Atlasel pole veel plaani',
  noPlanSub: 'Tee Atlas oma peatreeneriks — ta kirjutab kava',
  restDay: 'Puhkepäev',
  nextPlanDay: (d) => `Järgmine treening · ${d}`,
  doneToday: 'Tänaseks tehtud',
  doneTodaySub: 'Taastu — Atlas planeerib järgmise',
  readiness: 'Valmisolek',
  readinessP: (p) => `Valmisolek ${p}%`,
  stillRecovering: (m) => `${m} alles taastub`,
  allFresh: 'Kõik on värske',
  debrief: 'Kokkuvõte',
  winsChanges: (w, c) => `Õnnestumisi ${w} · muuta ${c}`,
  noDebrief: 'Pole treeningut, mida arutada',
  noDebriefSub: 'Lõpeta treening — Atlas teeb kokkuvõtte',
  wentWell: 'Läks hästi',
  nextTime: 'Järgmine kord',
  volume: 'Maht',
  sets: 'Seeriad',
  prShort: 'PR',
  time: 'Aeg',
  cleanSession: 'Puhas treening — midagi pole muuta',
  winPr: (ex, set) => `${ex} ${set} — uus rekord`,
  winComeback: (d) => `Tagasi pärast ${d}-päevast pausi — tubli`,
  winSets: (n) => `Kõik tööseeriad (${n}) tehtud`,
  fixStall: (ex, kg) => `${ex} seisab ${kg} juures — lisa enne kordus, siis raskus`,
  fixRest: (ex, a, b) => `${ex}: puhkasid ${a}, plaanis ${b}`,
  openSession: 'Ava treening',
  moodK: 'Atlase meeleolu',
  whyMood: 'Miks selline meeleolu',
  streak: 'Seeria',
  daysN: (n) => `${n} p`,
  thisWeek: 'Treeninguid sel nädalal',
  soften: {
    injury: 'Vigastus — Atlas on leebem',
    illness: 'Haige — Atlas on leebem',
    sleep: 'Lühike öö — Atlas on leebem',
    comeback: 'Tagasitulek — Atlas on leebem',
  },
  normalDay: 'Tavaline päev — valitud temperament',
  muted: 'Täna vaigistatud',
  talk: 'Räägi Atlasega',
  notesK: 'Atlase märkmed',
  unread: (n) => `Lugemata · ${n}`,
  allRead: 'Kõik loetud',
  allReadSub: 'Atlas kirjutab pärast järgmist treeningut',
  more: (n) => `+${n} veel`,
  markRead: 'Märgi loetuks',
  openNotes: 'Ava märkmed',
  justNow: 'nüüd',
  agoM: (n) => `${n} min`,
  agoH: (n) => `${n} h`,
  agoD: (n) => `${n} p`,
  weekReview: 'Nädala ülevaade',
  sessionsOf: (a, b) => `${a} / ${b}`,
  sessionsK: 'Treeningud',
  lifted: 'Tõstetud',
  records: 'Rekordid',
  noWeek: 'Eelmisel nädalal treeninguid polnud',
  noWeekSub: 'Treeni sel nädalal — Atlas teeb esmaspäeval kokkuvõtte',
  fullReview: 'Täielik ülevaade',
  lineSessions: (a, b, t) => `${a} / ${b} treeningut, tõstetud ${t}.`,
  lineRecord: (ex, set) => `Uus rekord: ${ex} ${set}.`,
  lineNoRecord: 'Uusi rekordeid pole — kõigepealt järjepidevus.',
  lineVolume: (d) => `Maht ${d}% võrreldes eelmise nädalaga.`,
};

const DICT: Record<LocaleId, LearnAtlasStrings> = { en, uk, pl, lt, et };

export function las(locale: LocaleId): LearnAtlasStrings {
  return DICT[locale];
}
