/**
 * Copy of the Muscles & consistency widgets (board L7), all five locales.
 * Typed: a missing key in any locale fails the build. Muscle names come from
 * the main dictionary (t.muscleGroups).
 */
import type { LocaleId } from '../../i18n';

type Ppl = { push: string; pull: string; legs: string };
type Four = [string, string, string, string];

const en = {
  sets: 'sets',
  save: 'Save',
  start: 'Start',
  reps: 'Reps',
  openTrends: 'Open trends',
  openVolume: 'Open volume',
  todayWord: 'today',
  // Muscle map
  muscleMap: 'Muscle map',
  last7: 'Last 7 days',
  mapKicker: 'Muscle map · last 7 days',
  volume7: 'Volume · 7 days',
  mapEmpty: 'No sets in the last 7 days',
  mapEmptySub: 'Log a session to light up the map',
  leads: (m: string, n: number) => `${m} leads · ${n} sets`,
  mapSub: (total: number, m: string, n: number) => `${total} sets in 7 days · ${m} only ${n}`,
  most: 'Most',
  mostLeast: (a: string, b: string) => `Most ${a} · least ${b}`,
  details: 'Details',
  setsLegend: 'Sets',
  // Volume landmarks
  landmarks: 'Volume landmarks',
  landmarksShort: 'Landmarks',
  landmarks7: 'Volume landmarks · 7 days',
  lmEmptySub: 'Personal MEV / MAV / MRV fill in as you train',
  overMrv: (m: string, n: string) => `${m} over MRV · ${n} sets`,
  underMev: (m: string, n: string) => `${m} under MEV · ${n} sets`,
  allInRange: 'Every muscle is in its productive range',
  inRangeOf: (a: number, b: number) => `${a} of ${b} muscles in range`,
  ofInRange: (b: number) => `/ ${b} in range`,
  setsWeek: 'sets / week',
  overNote: (m: string, n: string, u: string | null) =>
    u
      ? `${m} is over MRV — move ~${n} sets to ${u} next week.`
      : `${m} is over MRV — trim ~${n} sets next week.`,
  underNote: (m: string, n: string) => `${m} is under MEV — add ~${n} sets this week.`,
  sweetSpot: 'MEV–MAV sweet spot',
  tip: 'Tip',
  // Stimulus left
  stimulus: 'Stimulus left today',
  leftToday: 'Left today',
  leftTodayOf: (d: string) => `Left today · ${d}`,
  stimEmpty: 'No muscles planned today',
  stimEmptySub: 'Pick a program day or start a session',
  doneMark: 'done ✓',
  nLeft: (n: number) => `${n} left`,
  setsLeftTitle: (n: number) => `${n} productive sets left`,
  allDone: 'Everything planned is done',
  toMav: 'to MAV',
  readiness: (p: number) => `Readiness ${p}%`,
  continueWorkout: 'Continue workout',
  setsLeft: 'sets left',
  ofDone: (d: string, t: number) => `${d} of ${t} productive sets done`,
  minutes: (n: number) => `~${n} min at your pace`,
  // Left / right
  lr: 'Left / right balance',
  lrKicker: 'Left / right · e1RM',
  lrTitle: 'Test left vs right',
  lrHint: 'The log records one side. Do a set per side and enter both — kept on this device.',
  liftName: 'Exercise',
  left: 'Left',
  right: 'Right',
  l: 'L',
  r: 'R',
  even: 'even ✓',
  sideTag: (side: string, p: number) => `${side} −${p}%`,
  pctSide: (side: string) => `% ${side}`,
  lrEmpty: 'No side test yet',
  lrEmptySub: (x: string) => `Try ${x}: one set per side`,
  testLift: 'Test a lift',
  leftSide: 'Left side',
  rightSide: 'Right side',
  balancedLr: 'Both sides even',
  weaker: (side: string, p: number) => `${side} ${p}% weaker`,
  startWeaker: (side: string) => `Start sets with the weaker side (${side.toLowerCase()})`,
  // Muscle of the week
  muscleWeek: 'Muscle of the week',
  focusWeek: 'Focus · week',
  focus: (m: string) => `Focus: ${m}`,
  mwSub: (d: string, g: number, n: number, day: string) =>
    n > 0 ? `${d} of ${g} sets · ${n} to go by ${day}` : `${d} of ${g} sets · done`,
  ofSets: (g: number) => `/ ${g} sets`,
  addMore: (n: number, ex: string) => `${n} more sets of ${ex} close the gap.`,
  addSets: (n: number) => `${n} more sets close the gap.`,
  goalHit: 'Weekly target reached',
  furthest: 'Furthest below MAV over 4 weeks',
  toGoBy: (n: number, day: string) => `${n} sets to go by ${day}`,
  nowShort: 'now',
  nSets: (n: number) => `${n} sets`,
  openMuscle: 'Open muscle',
  mwEmpty: 'Needs two weeks of training',
  mwEmptySub: 'Then the lagging muscle gets the spotlight',
  // Frequency
  frequency: 'Frequency',
  freqWeek: 'Frequency · this week',
  target2: 'target 2×',
  target2Muscle: 'target 2× per muscle',
  hitTwice: (a: number, b: number) => `${a} of ${b} muscles hit 2×`,
  atTwice: (b: number) => `/ ${b} at 2×`,
  onlyX: (m: string, n: number) => `${m} only ${n}× this week`,
  allTwice: 'Every muscle hit at least twice',
  trained: 'Trained',
  planned: 'Planned',
  plannedLower: 'planned',
  freqEmpty: 'No sessions yet',
  freqEmptySub: 'Dots fill in as you train each muscle',
  // PPL
  ppl: 'Push / Pull / Legs',
  pplName: { push: 'Push', pull: 'Pull', legs: 'Legs' } as Ppl,
  split4: 'Volume split · 4 weeks',
  weeks4: '4 weeks',
  pplBalanced: 'Close to the 35 / 35 / 30 target',
  pplBalancedShort: 'Balanced',
  heavy: (x: string) => `${x}-heavy`,
  below: (x: string, d: number) => `${x} ${d}% below target`,
  above: (x: string, d: number) => `${x} ${d}% above target`,
  setsTarget: (n: number, t: number) => `${n} · target ${t}%`,
  byWeek: 'By week',
  pplEmpty: 'No strength sets in 4 weeks',
  pplEmptySub: 'The split appears after a few sessions',
  // Heatmap
  heatmap: 'Consistency heatmap',
  consistency: 'Consistency',
  weeks16: '16 weeks',
  days52: 'Training days · 52 weeks',
  weekStreak: (n: number) => `${n}-week streak`,
  wkStreak: 'week streak',
  wk: 'wk',
  sessions16: (n: number, p: string) => `${n} sessions in 16 weeks · ${p} / week`,
  bestN: (n: number) => `Best ${n}`,
  perWeek: (p: string) => `${p} / week`,
  nSessions: (n: number) => `${n} sessions`,
  streak: 'Streak',
  longest: 'Longest',
  nWeeks: (n: number) => `${n} wk`,
  inYear: (y: number) => `In ${y}`,
  less: 'Less',
  more: 'More',
  heatEmpty: 'No sessions yet',
  heatEmptySub: 'Your training days will fill this in',
  // Weekly goal
  weeklyGoal: 'Weekly goal',
  goalKicker: (g: number) => `Weekly goal · ${g} sessions`,
  goalWeek: (r: string) => `Weekly goal · ${r}`,
  goalOf: (d: number, g: number) => `Weekly goal · ${d} of ${g}`,
  goalDone: 'Goal reached',
  nToGo: (n: number) => `${n} to go`,
  toGoBy2: (n: number, day: string) => `${n} to go by ${day}`,
  byDay: (day: string) => `by ${day}`,
  nextOn: (name: string, when: string) => `Next: ${name} ${when}`,
  streakWeeks: (n: number) => `${n}-week goal streak`,
  daysLeft: (n: number) => `${n} days left`,
  last6: (x: string) => `Last 6 weeks: ${x}`,
  editGoal: 'Edit goal',
  goalTitle: 'Sessions per week',
  goalHint: 'Kept on this device. Defaults to your program’s training days.',
  perWk: '/ week',
  // Sessions this month
  sessionsMonth: 'Sessions this month',
  sessionsUnit: 'sessions',
  inMonth: (n: number, m: string) => `${n} sessions in ${m}`,
  vsMonth: (d: string, m: string) => `${d} vs ${m}`,
  monthVs: (a: string, b: string) => `Sessions · ${a} vs ${b}`,
  vsN: (n: number) => `vs ${n}`,
  vsIn: (n: number, m: string) => `vs ${n} in ${m}`,
  last14: 'Last 14 days',
  sessions14: (n: number) => `${n} sessions in 14 days`,
  sessionsOf: (m: string) => `Sessions · ${m}`,
  best6: 'best in 6 months',
  hoursTotal: (h: string, avg: number) => `${h} h total · avg ${avg} min`,
  chunk: (n: number, h: string) => `${n} sessions · ${h} h`,
  openHistory: 'Open history',
  // Best time
  bestTime: 'Best training time',
  bestTimeShort: 'Best time',
  slotName: ['Morning', 'Midday', 'Afternoon', 'Evening'] as Four,
  slotShort: ['AM', 'Mid', 'PM', 'Eve'] as Four,
  slotRange: ['6–10', '10–14', '14–18', '18–22'] as Four,
  strongest: (d: string, s: string) => `Strongest: ${d} ${s}`,
  topSets: (x: string) => `Top sets ${x} vs your average`,
  topSetsShort: (x: string) => `${x} top sets`,
  fromN: (n: number) => `from ${n} sessions`,
  vsAvg12: 'e1RM vs avg · 12 wk',
  weakest: (l: string, x: string) => `Weakest: ${l} ${x}`,
  valuesNote: (n: number) => `Values = % vs your average top set · ${n} sessions`,
  bestNote: (d: string, s: string, x: string) => `${d} ${s} is your strongest slot (${x}).`,
  btEmpty: 'Not enough sessions yet',
  btEmptySub: '6+ sessions with repeated lifts in 12 weeks',
  // Back on track
  backOnTrack: 'Back on track',
  onTrack: 'On track',
  onTrackNote: 'no break to ease back from',
  lastAgo: (n: number, d: string) => (n === 0 ? `Trained today` : `Last session ${n} d ago · ${d}`),
  daysSince: 'days since',
  welcome: (n: number) => `Welcome back · ${n} days off`,
  rampStep: (n: number) => `Easing back · session ${n} of 3`,
  firstLighter: (l: number) => `This session lighter: ${l}% load`,
  pctLoad: '% load',
  offSession: (d: number, n: number) => `${d} days off · session ${n} of 3`,
  botKicker: (d: number) => `Back on track · ${d} days off`,
  ease: 'Ease back in over 3 sessions',
  minus: (p: number) => `−${p}% weight · −1 set`,
  startLight: 'Start light',
  todayCap: 'Today',
  nextCap: 'Next',
  thenCap: 'Then',
  sessionN: (n: number) => `Session ${n}`,
  fullLoad: 'Full load',
  backToPlan: 'Full load · back to plan',
  loadSets: (l: number) => `${l}% · ${l < 90 ? '3 sets / lift' : 'full sets'}`,
  lastSession: (d: string) => `last session ${d}`,
  daysOffUnit: 'days off',
  example0: 'Example',
  example: (ex: string, kg: string, full: string) => `${ex} today: ${kg} kg instead of ${full} kg`,
  lighter: 'Take every lift ~20% lighter today',
  warmNote: 'Lighter warm-up · stop 2–3 reps short',
};

export type MusclesStrings = typeof en;

const uk: MusclesStrings = {
  sets: 'підх.',
  save: 'Зберегти',
  start: 'Почати',
  reps: 'Повтори',
  openTrends: 'Відкрити тренди',
  openVolume: 'Відкрити обсяг',
  todayWord: 'сьогодні',
  muscleMap: 'Мапа м’язів',
  last7: 'Останні 7 днів',
  mapKicker: 'Мапа м’язів · 7 днів',
  volume7: 'Обсяг · 7 днів',
  mapEmpty: 'Жодного підходу за 7 днів',
  mapEmptySub: 'Запиши сесію, щоб мапа засвітилась',
  leads: (m, n) => `${m} лідирує · ${n} підх.`,
  mapSub: (total, m, n) => `${total} підх. за 7 днів · ${m} лише ${n}`,
  most: 'Найбільше',
  mostLeast: (a, b) => `Найбільше ${a} · найменше ${b}`,
  details: 'Деталі',
  setsLegend: 'Підходи',
  landmarks: 'Орієнтири обсягу',
  landmarksShort: 'Орієнтири',
  landmarks7: 'Орієнтири обсягу · 7 днів',
  lmEmptySub: 'Особисті MEV / MAV / MRV з’являться з тренуваннями',
  overMrv: (m, n) => `${m} понад MRV · ${n} підх.`,
  underMev: (m, n) => `${m} нижче MEV · ${n} підх.`,
  allInRange: 'Усі м’язи в продуктивному діапазоні',
  inRangeOf: (a, b) => `${a} з ${b} м’язів у діапазоні`,
  ofInRange: (b) => `/ ${b} у діапазоні`,
  setsWeek: 'підх. / тиж.',
  overNote: (m, n, u) =>
    u
      ? `${m} понад MRV — перенеси ~${n} підх. на: ${u} наступного тижня.`
      : `${m} понад MRV — зріж ~${n} підх. наступного тижня.`,
  underNote: (m, n) => `${m} нижче MEV — додай ~${n} підх. цього тижня.`,
  sweetSpot: 'MEV–MAV оптимум',
  tip: 'Порада',
  stimulus: 'Стимул на сьогодні',
  leftToday: 'Лишилось сьогодні',
  leftTodayOf: (d) => `Лишилось сьогодні · ${d}`,
  stimEmpty: 'Сьогодні м’язи не заплановані',
  stimEmptySub: 'Обери день програми або почни сесію',
  doneMark: 'готово ✓',
  nLeft: (n) => `ще ${n}`,
  setsLeftTitle: (n) => `Ще ${n} продуктивних підх.`,
  allDone: 'Усе заплановане виконано',
  toMav: 'до MAV',
  readiness: (p) => `Готовність ${p}%`,
  continueWorkout: 'Продовжити',
  setsLeft: 'підх. лишилось',
  ofDone: (d, t) => `${d} з ${t} продуктивних підх. виконано`,
  minutes: (n) => `~${n} хв у твоєму темпі`,
  lr: 'Баланс ліва / права',
  lrKicker: 'Ліва / права · e1RM',
  lrTitle: 'Тест ліва vs права',
  lrHint:
    'Журнал записує одну сторону. Зроби підхід на кожну і введи обидва — зберігається на цьому пристрої.',
  liftName: 'Вправа',
  left: 'Ліва',
  right: 'Права',
  l: 'Л',
  r: 'П',
  even: 'рівно ✓',
  sideTag: (side, p) => `${side} −${p}%`,
  pctSide: (side) => `% ${side}`,
  lrEmpty: 'Ще немає тесту сторін',
  lrEmptySub: (x) => `Спробуй ${x}: по підходу на бік`,
  testLift: 'Протестувати',
  leftSide: 'Ліва сторона',
  rightSide: 'Права сторона',
  balancedLr: 'Обидві сторони рівні',
  weaker: (side, p) => `${side} слабша на ${p}%`,
  startWeaker: (side) => `Починай підходи зі слабшої сторони (${side.toLowerCase()})`,
  muscleWeek: 'М’яз тижня',
  focusWeek: 'Фокус · тиждень',
  focus: (m) => `Фокус: ${m}`,
  mwSub: (d, g, n, day) =>
    n > 0 ? `${d} з ${g} підх. · ще ${n} до ${day}` : `${d} з ${g} підх. · готово`,
  ofSets: (g) => `/ ${g} підх.`,
  addMore: (n, ex) => `Ще ${n} підх. «${ex}» закриють розрив.`,
  addSets: (n) => `Ще ${n} підх. закриють розрив.`,
  goalHit: 'Тижневу ціль досягнуто',
  furthest: 'Найдалі від MAV за 4 тижні',
  toGoBy: (n, day) => `ще ${n} підх. до ${day}`,
  nowShort: 'зараз',
  nSets: (n) => `${n} підх.`,
  openMuscle: 'Відкрити м’яз',
  mwEmpty: 'Потрібно два тижні тренувань',
  mwEmptySub: 'Потім відсталий м’яз отримає увагу',
  frequency: 'Частота',
  freqWeek: 'Частота · цей тиждень',
  target2: 'ціль 2×',
  target2Muscle: 'ціль 2× на м’яз',
  hitTwice: (a, b) => `${a} з ${b} м’язів 2×`,
  atTwice: (b) => `/ ${b} на 2×`,
  onlyX: (m, n) => `${m} лише ${n}× цього тижня`,
  allTwice: 'Кожен м’яз щонайменше двічі',
  trained: 'Натреновано',
  planned: 'Заплановано',
  plannedLower: 'заплановано',
  freqEmpty: 'Ще немає сесій',
  freqEmptySub: 'Крапки заповнюються з тренуваннями',
  ppl: 'Жим / Тяга / Ноги',
  pplName: { push: 'Жим', pull: 'Тяга', legs: 'Ноги' },
  split4: 'Розподіл обсягу · 4 тижні',
  weeks4: '4 тижні',
  pplBalanced: 'Близько до цілі 35 / 35 / 30',
  pplBalancedShort: 'Збалансовано',
  heavy: (x) => `Перекіс: ${x}`,
  below: (x, d) => `${x} на ${d}% нижче цілі`,
  above: (x, d) => `${x} на ${d}% вище цілі`,
  setsTarget: (n, t) => `${n} · ціль ${t}%`,
  byWeek: 'По тижнях',
  pplEmpty: 'Немає силових підходів за 4 тижні',
  pplEmptySub: 'Розподіл з’явиться після кількох сесій',
  heatmap: 'Теплокарта регулярності',
  consistency: 'Регулярність',
  weeks16: '16 тижнів',
  days52: 'Тренувальні дні · 52 тижні',
  weekStreak: (n) => `Серія ${n} тиж.`,
  wkStreak: 'тижнів поспіль',
  wk: 'тиж.',
  sessions16: (n, p) => `${n} сесій за 16 тижнів · ${p} / тиж.`,
  bestN: (n) => `Рекорд ${n}`,
  perWeek: (p) => `${p} / тиж.`,
  nSessions: (n) => `${n} сесій`,
  streak: 'Серія',
  longest: 'Найдовша',
  nWeeks: (n) => `${n} тиж.`,
  inYear: (y) => `У ${y}`,
  less: 'Менше',
  more: 'Більше',
  heatEmpty: 'Ще немає сесій',
  heatEmptySub: 'Тут з’являться твої тренувальні дні',
  weeklyGoal: 'Тижнева ціль',
  goalKicker: (g) => `Тижнева ціль · ${g} сесій`,
  goalWeek: (r) => `Тижнева ціль · ${r}`,
  goalOf: (d, g) => `Тижнева ціль · ${d} з ${g}`,
  goalDone: 'Ціль виконано',
  nToGo: (n) => `ще ${n}`,
  toGoBy2: (n, day) => `ще ${n} до ${day}`,
  byDay: (day) => `до ${day}`,
  nextOn: (name, when) => `Далі: ${name} ${when}`,
  streakWeeks: (n) => `${n} тиж. поспіль з ціллю`,
  daysLeft: (n) => `лишилось днів: ${n}`,
  last6: (x) => `Останні 6 тижнів: ${x}`,
  editGoal: 'Змінити ціль',
  goalTitle: 'Сесій на тиждень',
  goalHint: 'Зберігається на цьому пристрої. За замовчуванням — дні твоєї програми.',
  perWk: '/ тиж.',
  sessionsMonth: 'Сесії за місяць',
  sessionsUnit: 'сесій',
  inMonth: (n, m) => `${m}: ${n} сесій`,
  vsMonth: (d, m) => `${d} vs ${m}`,
  monthVs: (a, b) => `Сесії · ${a} vs ${b}`,
  vsN: (n) => `vs ${n}`,
  vsIn: (n: number, m: string) => `vs ${n} in ${m}`,
  last14: 'Last 14 days',
  sessions14: (n: number) => `${n} sessions in 14 days`,
  sessionsOf: (m) => `Сесії · ${m}`,
  best6: 'найкраще за 6 місяців',
  hoursTotal: (h, avg) => `${h} год загалом · в середньому ${avg} хв`,
  chunk: (n, h) => `${n} сесій · ${h} год`,
  openHistory: 'Відкрити історію',
  bestTime: 'Найкращий час',
  bestTimeShort: 'Найкращий час',
  slotName: ['Ранок', 'Полудень', 'День', 'Вечір'],
  slotShort: ['Ран', 'Пол', 'День', 'Веч'],
  slotRange: ['6–10', '10–14', '14–18', '18–22'],
  strongest: (d, s) => `Найсильніше: ${d}, ${s}`,
  topSets: (x) => `Топ-сети ${x} від твого середнього`,
  topSetsShort: (x) => `${x} топ-сети`,
  fromN: (n) => `з ${n} сесій`,
  vsAvg12: 'e1RM від сер. · 12 тиж.',
  weakest: (l, x) => `Найслабше: ${l} ${x}`,
  valuesNote: (n) => `Значення = % від середнього топ-сету · ${n} сесій`,
  bestNote: (d, s, x) => `${d}, ${s} — твій найсильніший слот (${x}).`,
  btEmpty: 'Замало сесій',
  btEmptySub: '6+ сесій із повторюваними вправами за 12 тижнів',
  backOnTrack: 'Повернення в ритм',
  onTrack: 'У ритмі',
  onTrackNote: 'перерви немає',
  lastAgo: (n, d) => (n === 0 ? 'Тренування сьогодні' : `Остання сесія ${n} дн. тому · ${d}`),
  daysSince: 'днів з того часу',
  welcome: (n) => `З поверненням · ${n} днів перерви`,
  rampStep: (n) => `Повернення · сесія ${n} з 3`,
  firstLighter: (l) => `Ця сесія легша: ${l}% навантаження`,
  pctLoad: '% навант.',
  offSession: (d, n) => `${d} днів перерви · сесія ${n} з 3`,
  botKicker: (d) => `Повернення · ${d} днів перерви`,
  ease: 'Плавне повернення за 3 сесії',
  minus: (p) => `−${p}% ваги · −1 підхід`,
  startLight: 'Почати легко',
  todayCap: 'Сьогодні',
  nextCap: 'Далі',
  thenCap: 'Потім',
  sessionN: (n) => `Сесія ${n}`,
  fullLoad: 'Повне навант.',
  backToPlan: 'Повне навантаження · за планом',
  loadSets: (l) => `${l}% · ${l < 90 ? '3 підх. / вправу' : 'повні підходи'}`,
  lastSession: (d) => `остання сесія ${d}`,
  daysOffUnit: 'днів перерви',
  example0: 'Приклад',
  example: (ex, kg, full) => `${ex} сьогодні: ${kg} кг замість ${full} кг`,
  lighter: 'Сьогодні кожна вправа на ~20% легша',
  warmNote: 'Легша розминка · зупиняйся за 2–3 повтори до відмови',
};

const pl: MusclesStrings = {
  sets: 'serii',
  save: 'Zapisz',
  start: 'Start',
  reps: 'Powt.',
  openTrends: 'Otwórz trendy',
  openVolume: 'Otwórz objętość',
  todayWord: 'dziś',
  muscleMap: 'Mapa mięśni',
  last7: 'Ostatnie 7 dni',
  mapKicker: 'Mapa mięśni · 7 dni',
  volume7: 'Objętość · 7 dni',
  mapEmpty: 'Brak serii w 7 dni',
  mapEmptySub: 'Zapisz sesję, by mapa się zapaliła',
  leads: (m, n) => `${m} prowadzi · ${n} serii`,
  mapSub: (total, m, n) => `${total} serii w 7 dni · ${m} tylko ${n}`,
  most: 'Najwięcej',
  mostLeast: (a, b) => `Najwięcej ${a} · najmniej ${b}`,
  details: 'Szczegóły',
  setsLegend: 'Serie',
  landmarks: 'Progi objętości',
  landmarksShort: 'Progi',
  landmarks7: 'Progi objętości · 7 dni',
  lmEmptySub: 'Osobiste MEV / MAV / MRV pojawią się z treningami',
  overMrv: (m, n) => `${m} ponad MRV · ${n} serii`,
  underMev: (m, n) => `${m} poniżej MEV · ${n} serii`,
  allInRange: 'Każdy mięsień w produktywnym zakresie',
  inRangeOf: (a, b) => `${a} z ${b} mięśni w zakresie`,
  ofInRange: (b) => `/ ${b} w zakresie`,
  setsWeek: 'serie / tydz.',
  overNote: (m, n, u) =>
    u
      ? `${m} ponad MRV — przenieś ~${n} serii na: ${u} w przyszłym tygodniu.`
      : `${m} ponad MRV — utnij ~${n} serii w przyszłym tygodniu.`,
  underNote: (m, n) => `${m} poniżej MEV — dodaj ~${n} serii w tym tygodniu.`,
  sweetSpot: 'MEV–MAV optimum',
  tip: 'Wskazówka',
  stimulus: 'Bodziec na dziś',
  leftToday: 'Zostało dziś',
  leftTodayOf: (d) => `Zostało dziś · ${d}`,
  stimEmpty: 'Na dziś brak zaplanowanych mięśni',
  stimEmptySub: 'Wybierz dzień programu lub zacznij sesję',
  doneMark: 'gotowe ✓',
  nLeft: (n) => `jeszcze ${n}`,
  setsLeftTitle: (n) => `Jeszcze ${n} produktywnych serii`,
  allDone: 'Wszystko z planu zrobione',
  toMav: 'do MAV',
  readiness: (p) => `Gotowość ${p}%`,
  continueWorkout: 'Kontynuuj trening',
  setsLeft: 'serii zostało',
  ofDone: (d, t) => `${d} z ${t} produktywnych serii zrobione`,
  minutes: (n) => `~${n} min w twoim tempie`,
  lr: 'Balans lewa / prawa',
  lrKicker: 'Lewa / prawa · e1RM',
  lrTitle: 'Test lewa vs prawa',
  lrHint:
    'Dziennik zapisuje jedną stronę. Zrób serię na każdą i wpisz obie — zapis na tym urządzeniu.',
  liftName: 'Ćwiczenie',
  left: 'Lewa',
  right: 'Prawa',
  l: 'L',
  r: 'P',
  even: 'równo ✓',
  sideTag: (side, p) => `${side} −${p}%`,
  pctSide: (side) => `% ${side}`,
  lrEmpty: 'Brak testu stron',
  lrEmptySub: (x) => `Spróbuj ${x}: jedna seria na stronę`,
  testLift: 'Testuj',
  leftSide: 'Lewa strona',
  rightSide: 'Prawa strona',
  balancedLr: 'Obie strony równe',
  weaker: (side, p) => `${side} słabsza o ${p}%`,
  startWeaker: (side) => `Zaczynaj serie od słabszej strony (${side.toLowerCase()})`,
  muscleWeek: 'Mięsień tygodnia',
  focusWeek: 'Fokus · tydzień',
  focus: (m) => `Fokus: ${m}`,
  mwSub: (d, g, n, day) =>
    n > 0 ? `${d} z ${g} serii · jeszcze ${n} do ${day}` : `${d} z ${g} serii · gotowe`,
  ofSets: (g) => `/ ${g} serii`,
  addMore: (n, ex) => `Jeszcze ${n} serii „${ex}” domknie lukę.`,
  addSets: (n) => `Jeszcze ${n} serii domknie lukę.`,
  goalHit: 'Cel tygodnia osiągnięty',
  furthest: 'Najdalej poniżej MAV w 4 tygodnie',
  toGoBy: (n, day) => `jeszcze ${n} serii do ${day}`,
  nowShort: 'teraz',
  nSets: (n) => `${n} serii`,
  openMuscle: 'Otwórz mięsień',
  mwEmpty: 'Potrzeba dwóch tygodni treningu',
  mwEmptySub: 'Potem zaległy mięsień dostanie uwagę',
  frequency: 'Częstotliwość',
  freqWeek: 'Częstotliwość · ten tydzień',
  target2: 'cel 2×',
  target2Muscle: 'cel 2× na mięsień',
  hitTwice: (a, b) => `${a} z ${b} mięśni 2×`,
  atTwice: (b) => `/ ${b} na 2×`,
  onlyX: (m, n) => `${m} tylko ${n}× w tym tygodniu`,
  allTwice: 'Każdy mięsień co najmniej dwa razy',
  trained: 'Trenowane',
  planned: 'Zaplanowane',
  plannedLower: 'w planie',
  freqEmpty: 'Brak sesji',
  freqEmptySub: 'Kropki wypełniają się z treningami',
  ppl: 'Push / Pull / Nogi',
  pplName: { push: 'Push', pull: 'Pull', legs: 'Nogi' },
  split4: 'Podział objętości · 4 tyg.',
  weeks4: '4 tygodnie',
  pplBalanced: 'Blisko celu 35 / 35 / 30',
  pplBalancedShort: 'Zbalansowane',
  heavy: (x) => `Przewaga: ${x}`,
  below: (x, d) => `${x} ${d}% poniżej celu`,
  above: (x, d) => `${x} ${d}% powyżej celu`,
  setsTarget: (n, t) => `${n} · cel ${t}%`,
  byWeek: 'Tygodniowo',
  pplEmpty: 'Brak serii siłowych w 4 tygodnie',
  pplEmptySub: 'Podział pojawi się po kilku sesjach',
  heatmap: 'Mapa regularności',
  consistency: 'Regularność',
  weeks16: '16 tygodni',
  days52: 'Dni treningowe · 52 tygodnie',
  weekStreak: (n) => `Seria ${n} tyg.`,
  wkStreak: 'tyg. z rzędu',
  wk: 'tyg.',
  sessions16: (n, p) => `${n} sesji w 16 tygodni · ${p} / tydz.`,
  bestN: (n) => `Rekord ${n}`,
  perWeek: (p) => `${p} / tydz.`,
  nSessions: (n) => `${n} sesji`,
  streak: 'Seria',
  longest: 'Najdłuższa',
  nWeeks: (n) => `${n} tyg.`,
  inYear: (y) => `W ${y}`,
  less: 'Mniej',
  more: 'Więcej',
  heatEmpty: 'Brak sesji',
  heatEmptySub: 'Tu pojawią się twoje dni treningowe',
  weeklyGoal: 'Cel tygodnia',
  goalKicker: (g) => `Cel tygodnia · ${g} sesji`,
  goalWeek: (r) => `Cel tygodnia · ${r}`,
  goalOf: (d, g) => `Cel tygodnia · ${d} z ${g}`,
  goalDone: 'Cel osiągnięty',
  nToGo: (n) => `jeszcze ${n}`,
  toGoBy2: (n, day) => `jeszcze ${n} do ${day}`,
  byDay: (day) => `do ${day}`,
  nextOn: (name, when) => `Dalej: ${name} ${when}`,
  streakWeeks: (n) => `${n} tyg. z rzędu z celem`,
  daysLeft: (n) => `zostało dni: ${n}`,
  last6: (x) => `Ostatnie 6 tygodni: ${x}`,
  editGoal: 'Zmień cel',
  goalTitle: 'Sesje w tygodniu',
  goalHint: 'Zapis na tym urządzeniu. Domyślnie dni twojego programu.',
  perWk: '/ tydz.',
  sessionsMonth: 'Sesje w miesiącu',
  sessionsUnit: 'sesji',
  inMonth: (n, m) => `${m}: ${n} sesji`,
  vsMonth: (d, m) => `${d} vs ${m}`,
  monthVs: (a, b) => `Sesje · ${a} vs ${b}`,
  vsN: (n) => `vs ${n}`,
  vsIn: (n: number, m: string) => `vs ${n} in ${m}`,
  last14: 'Last 14 days',
  sessions14: (n: number) => `${n} sessions in 14 days`,
  sessionsOf: (m) => `Sesje · ${m}`,
  best6: 'najlepiej od 6 miesięcy',
  hoursTotal: (h, avg) => `${h} h łącznie · śr. ${avg} min`,
  chunk: (n, h) => `${n} sesji · ${h} h`,
  openHistory: 'Otwórz historię',
  bestTime: 'Najlepsza pora treningu',
  bestTimeShort: 'Najlepsza pora',
  slotName: ['Rano', 'Południe', 'Popołudnie', 'Wieczór'],
  slotShort: ['Rano', 'Poł', 'Pop', 'Wiecz'],
  slotRange: ['6–10', '10–14', '14–18', '18–22'],
  strongest: (d, s) => `Najsilniej: ${d}, ${s}`,
  topSets: (x) => `Serie szczytowe ${x} od twojej średniej`,
  topSetsShort: (x) => `${x} serie szczytowe`,
  fromN: (n) => `z ${n} sesji`,
  vsAvg12: 'e1RM vs średnia · 12 tyg.',
  weakest: (l, x) => `Najsłabiej: ${l} ${x}`,
  valuesNote: (n) => `Wartości = % względem średniej serii szczytowej · ${n} sesji`,
  bestNote: (d, s, x) => `${d}, ${s} to twoja najsilniejsza pora (${x}).`,
  btEmpty: 'Za mało sesji',
  btEmptySub: '6+ sesji z powtarzanymi bojami w 12 tygodni',
  backOnTrack: 'Powrót do rytmu',
  onTrack: 'W rytmie',
  onTrackNote: 'bez przerwy do nadrobienia',
  lastAgo: (n, d) => (n === 0 ? 'Trening dziś' : `Ostatnia sesja ${n} dni temu · ${d}`),
  daysSince: 'dni od sesji',
  welcome: (n) => `Witaj z powrotem · ${n} dni przerwy`,
  rampStep: (n) => `Powrót · sesja ${n} z 3`,
  firstLighter: (l) => `Ta sesja lżejsza: ${l}% obciążenia`,
  pctLoad: '% obciąż.',
  offSession: (d, n) => `${d} dni przerwy · sesja ${n} z 3`,
  botKicker: (d) => `Powrót · ${d} dni przerwy`,
  ease: 'Łagodny powrót przez 3 sesje',
  minus: (p) => `−${p}% ciężaru · −1 seria`,
  startLight: 'Zacznij lżej',
  todayCap: 'Dziś',
  nextCap: 'Potem',
  thenCap: 'Dalej',
  sessionN: (n) => `Sesja ${n}`,
  fullLoad: 'Pełne obciąż.',
  backToPlan: 'Pełne obciążenie · wg planu',
  loadSets: (l) => `${l}% · ${l < 90 ? '3 serie / ćw.' : 'pełne serie'}`,
  lastSession: (d) => `ostatnia sesja ${d}`,
  daysOffUnit: 'dni przerwy',
  example0: 'Przykład',
  example: (ex, kg, full) => `${ex} dziś: ${kg} kg zamiast ${full} kg`,
  lighter: 'Dziś każde ćwiczenie ~20% lżej',
  warmNote: 'Lżejsza rozgrzewka · kończ 2–3 powt. przed upadkiem',
};

const lt: MusclesStrings = {
  sets: 'ser.',
  save: 'Išsaugoti',
  start: 'Pradėti',
  reps: 'Kart.',
  openTrends: 'Atidaryti tendencijas',
  openVolume: 'Atidaryti apimtį',
  todayWord: 'šiandien',
  muscleMap: 'Raumenų žemėlapis',
  last7: 'Paskutinės 7 d.',
  mapKicker: 'Raumenų žemėlapis · 7 d.',
  volume7: 'Apimtis · 7 d.',
  mapEmpty: 'Per 7 dienas serijų nėra',
  mapEmptySub: 'Įrašyk sesiją ir žemėlapis nušvis',
  leads: (m, n) => `${m} pirmauja · ${n} ser.`,
  mapSub: (total, m, n) => `${total} ser. per 7 d. · ${m} tik ${n}`,
  most: 'Daugiausia',
  mostLeast: (a, b) => `Daugiausia ${a} · mažiausiai ${b}`,
  details: 'Išsamiau',
  setsLegend: 'Serijos',
  landmarks: 'Apimties gairės',
  landmarksShort: 'Gairės',
  landmarks7: 'Apimties gairės · 7 d.',
  lmEmptySub: 'Asmeniniai MEV / MAV / MRV atsiras treniruojantis',
  overMrv: (m, n) => `${m} virš MRV · ${n} ser.`,
  underMev: (m, n) => `${m} žemiau MEV · ${n} ser.`,
  allInRange: 'Visi raumenys produktyviame intervale',
  inRangeOf: (a, b) => `${a} iš ${b} raumenų intervale`,
  ofInRange: (b) => `/ ${b} intervale`,
  setsWeek: 'ser. / sav.',
  overNote: (m, n, u) =>
    u
      ? `${m} virš MRV — kitą savaitę perkelk ~${n} ser.: ${u}.`
      : `${m} virš MRV — kitą savaitę sumažink ~${n} ser.`,
  underNote: (m, n) => `${m} žemiau MEV — šią savaitę pridėk ~${n} ser.`,
  sweetSpot: 'MEV–MAV optimumas',
  tip: 'Patarimas',
  stimulus: 'Likęs stimulas šiandien',
  leftToday: 'Liko šiandien',
  leftTodayOf: (d) => `Liko šiandien · ${d}`,
  stimEmpty: 'Šiandien raumenys nesuplanuoti',
  stimEmptySub: 'Pasirink programos dieną arba pradėk sesiją',
  doneMark: 'atlikta ✓',
  nLeft: (n) => `liko ${n}`,
  setsLeftTitle: (n) => `Liko ${n} produktyvių ser.`,
  allDone: 'Viskas suplanuota atlikta',
  toMav: 'iki MAV',
  readiness: (p) => `Pasirengimas ${p}%`,
  continueWorkout: 'Tęsti treniruotę',
  setsLeft: 'ser. liko',
  ofDone: (d, t) => `${d} iš ${t} produktyvių ser. atlikta`,
  minutes: (n) => `~${n} min tavo tempu`,
  lr: 'Kairės / dešinės balansas',
  lrKicker: 'Kairė / dešinė · e1RM',
  lrTitle: 'Kairės ir dešinės testas',
  lrHint:
    'Žurnale įrašoma viena pusė. Atlik seriją kiekvienai ir įvesk abi — saugoma šiame įrenginyje.',
  liftName: 'Pratimas',
  left: 'Kairė',
  right: 'Dešinė',
  l: 'K',
  r: 'D',
  even: 'lygu ✓',
  sideTag: (side, p) => `${side} −${p}%`,
  pctSide: (side) => `% ${side}`,
  lrEmpty: 'Pusių testo dar nėra',
  lrEmptySub: (x) => `Išbandyk ${x}: po seriją kiekvienai pusei`,
  testLift: 'Testuoti',
  leftSide: 'Kairė pusė',
  rightSide: 'Dešinė pusė',
  balancedLr: 'Abi pusės lygios',
  weaker: (side, p) => `${side} silpnesnė ${p}%`,
  startWeaker: (side) => `Serijas pradėk silpnesne puse (${side.toLowerCase()})`,
  muscleWeek: 'Savaitės raumuo',
  focusWeek: 'Fokusas · savaitė',
  focus: (m) => `Fokusas: ${m}`,
  mwSub: (d, g, n, day) =>
    n > 0 ? `${d} iš ${g} ser. · liko ${n} iki ${day}` : `${d} iš ${g} ser. · atlikta`,
  ofSets: (g) => `/ ${g} ser.`,
  addMore: (n, ex) => `Dar ${n} ser. „${ex}“ užpildys spragą.`,
  addSets: (n) => `Dar ${n} ser. užpildys spragą.`,
  goalHit: 'Savaitės tikslas pasiektas',
  furthest: 'Toliausiai žemiau MAV per 4 sav.',
  toGoBy: (n, day) => `liko ${n} ser. iki ${day}`,
  nowShort: 'dabar',
  nSets: (n) => `${n} ser.`,
  openMuscle: 'Atidaryti raumenį',
  mwEmpty: 'Reikia dviejų savaičių treniruočių',
  mwEmptySub: 'Tada atsiliekantis raumuo gaus dėmesio',
  frequency: 'Dažnis',
  freqWeek: 'Dažnis · ši savaitė',
  target2: 'tikslas 2×',
  target2Muscle: 'tikslas 2× raumeniui',
  hitTwice: (a, b) => `${a} iš ${b} raumenų 2×`,
  atTwice: (b) => `/ ${b} po 2×`,
  onlyX: (m, n) => `${m} tik ${n}× šią savaitę`,
  allTwice: 'Kiekvienas raumuo bent du kartus',
  trained: 'Treniruota',
  planned: 'Suplanuota',
  plannedLower: 'suplanuota',
  freqEmpty: 'Sesijų dar nėra',
  freqEmptySub: 'Taškai užsipildys treniruojantis',
  ppl: 'Stūmimas / Traukimas / Kojos',
  pplName: { push: 'Stūmimas', pull: 'Traukimas', legs: 'Kojos' },
  split4: 'Apimties pasiskirstymas · 4 sav.',
  weeks4: '4 savaitės',
  pplBalanced: 'Arti tikslo 35 / 35 / 30',
  pplBalancedShort: 'Subalansuota',
  heavy: (x) => `Persvara: ${x}`,
  below: (x, d) => `${x} ${d}% žemiau tikslo`,
  above: (x, d) => `${x} ${d}% virš tikslo`,
  setsTarget: (n, t) => `${n} · tikslas ${t}%`,
  byWeek: 'Pagal savaites',
  pplEmpty: 'Per 4 sav. jėgos serijų nėra',
  pplEmptySub: 'Pasiskirstymas atsiras po kelių sesijų',
  heatmap: 'Reguliarumo žemėlapis',
  consistency: 'Reguliarumas',
  weeks16: '16 savaičių',
  days52: 'Treniruočių dienos · 52 sav.',
  weekStreak: (n) => `${n} sav. serija`,
  wkStreak: 'sav. iš eilės',
  wk: 'sav.',
  sessions16: (n, p) => `${n} sesijos per 16 sav. · ${p} / sav.`,
  bestN: (n) => `Rekordas ${n}`,
  perWeek: (p) => `${p} / sav.`,
  nSessions: (n) => `${n} sesijos`,
  streak: 'Serija',
  longest: 'Ilgiausia',
  nWeeks: (n) => `${n} sav.`,
  inYear: (y) => `${y} m.`,
  less: 'Mažiau',
  more: 'Daugiau',
  heatEmpty: 'Sesijų dar nėra',
  heatEmptySub: 'Čia atsiras tavo treniruočių dienos',
  weeklyGoal: 'Savaitės tikslas',
  goalKicker: (g) => `Savaitės tikslas · ${g} sesijos`,
  goalWeek: (r) => `Savaitės tikslas · ${r}`,
  goalOf: (d, g) => `Savaitės tikslas · ${d} iš ${g}`,
  goalDone: 'Tikslas pasiektas',
  nToGo: (n) => `liko ${n}`,
  toGoBy2: (n, day) => `liko ${n} iki ${day}`,
  byDay: (day) => `iki ${day}`,
  nextOn: (name, when) => `Toliau: ${name} ${when}`,
  streakWeeks: (n) => `${n} sav. iš eilės su tikslu`,
  daysLeft: (n) => `liko dienų: ${n}`,
  last6: (x) => `Paskutinės 6 sav.: ${x}`,
  editGoal: 'Keisti tikslą',
  goalTitle: 'Sesijos per savaitę',
  goalHint: 'Saugoma šiame įrenginyje. Numatyta — tavo programos dienos.',
  perWk: '/ sav.',
  sessionsMonth: 'Sesijos per mėnesį',
  sessionsUnit: 'sesijos',
  inMonth: (n, m) => `${m}: ${n} sesijos`,
  vsMonth: (d, m) => `${d} vs ${m}`,
  monthVs: (a, b) => `Sesijos · ${a} vs ${b}`,
  vsN: (n) => `vs ${n}`,
  vsIn: (n: number, m: string) => `vs ${n} in ${m}`,
  last14: 'Last 14 days',
  sessions14: (n: number) => `${n} sessions in 14 days`,
  sessionsOf: (m) => `Sesijos · ${m}`,
  best6: 'geriausia per 6 mėn.',
  hoursTotal: (h, avg) => `iš viso ${h} h · vid. ${avg} min`,
  chunk: (n, h) => `${n} sesijos · ${h} h`,
  openHistory: 'Atidaryti istoriją',
  bestTime: 'Geriausias treniruotės laikas',
  bestTimeShort: 'Geriausias laikas',
  slotName: ['Rytas', 'Vidurdienis', 'Popietė', 'Vakaras'],
  slotShort: ['Ryt', 'Vid', 'Pop', 'Vak'],
  slotRange: ['6–10', '10–14', '14–18', '18–22'],
  strongest: (d, s) => `Stipriausia: ${d}, ${s}`,
  topSets: (x) => `Geriausios serijos ${x} nuo tavo vidurkio`,
  topSetsShort: (x) => `${x} geriausios serijos`,
  fromN: (n) => `iš ${n} sesijų`,
  vsAvg12: 'e1RM vs vid. · 12 sav.',
  weakest: (l, x) => `Silpniausia: ${l} ${x}`,
  valuesNote: (n) => `Reikšmės = % nuo vidutinės geriausios serijos · ${n} sesijos`,
  bestNote: (d, s, x) => `${d}, ${s} — tavo stipriausias laikas (${x}).`,
  btEmpty: 'Per mažai sesijų',
  btEmptySub: '6+ sesijos su pasikartojančiais pratimais per 12 sav.',
  backOnTrack: 'Grįžimas į ritmą',
  onTrack: 'Ritme',
  onTrackNote: 'pertraukos nebuvo',
  lastAgo: (n, d) => (n === 0 ? 'Treniruotė šiandien' : `Paskutinė sesija prieš ${n} d. · ${d}`),
  daysSince: 'd. nuo sesijos',
  welcome: (n) => `Sveikas sugrįžęs · ${n} d. pertrauka`,
  rampStep: (n) => `Grįžimas · sesija ${n} iš 3`,
  firstLighter: (l) => `Ši sesija lengvesnė: ${l}% krūvio`,
  pctLoad: '% krūvio',
  offSession: (d, n) => `${d} d. pertrauka · sesija ${n} iš 3`,
  botKicker: (d) => `Grįžimas · ${d} d. pertrauka`,
  ease: 'Švelnus grįžimas per 3 sesijas',
  minus: (p) => `−${p}% svorio · −1 serija`,
  startLight: 'Pradėti lengvai',
  todayCap: 'Šiandien',
  nextCap: 'Toliau',
  thenCap: 'Tada',
  sessionN: (n) => `Sesija ${n}`,
  fullLoad: 'Pilnas krūvis',
  backToPlan: 'Pilnas krūvis · pagal planą',
  loadSets: (l) => `${l}% · ${l < 90 ? '3 ser. / pratimui' : 'pilnos serijos'}`,
  lastSession: (d) => `paskutinė sesija ${d}`,
  daysOffUnit: 'd. pertrauka',
  example0: 'Pavyzdys',
  example: (ex, kg, full) => `${ex} šiandien: ${kg} kg vietoj ${full} kg`,
  lighter: 'Šiandien kiekvienas pratimas ~20% lengvesnis',
  warmNote: 'Lengvesnis apšilimas · sustok 2–3 kart. iki nesėkmės',
};

const et: MusclesStrings = {
  sets: 'seeriat',
  save: 'Salvesta',
  start: 'Alusta',
  reps: 'Kordused',
  openTrends: 'Ava trendid',
  openVolume: 'Ava maht',
  todayWord: 'täna',
  muscleMap: 'Lihaste kaart',
  last7: 'Viimased 7 päeva',
  mapKicker: 'Lihaste kaart · 7 päeva',
  volume7: 'Maht · 7 päeva',
  mapEmpty: '7 päevaga pole seeriaid',
  mapEmptySub: 'Logi trenn ja kaart süttib',
  leads: (m, n) => `${m} juhib · ${n} seeriat`,
  mapSub: (total, m, n) => `${total} seeriat 7 päevaga · ${m} ainult ${n}`,
  most: 'Enim',
  mostLeast: (a, b) => `Enim ${a} · vähim ${b}`,
  details: 'Detailid',
  setsLegend: 'Seeriad',
  landmarks: 'Mahu piirid',
  landmarksShort: 'Piirid',
  landmarks7: 'Mahu piirid · 7 päeva',
  lmEmptySub: 'Isiklikud MEV / MAV / MRV tekivad treenides',
  overMrv: (m, n) => `${m} üle MRV · ${n} seeriat`,
  underMev: (m, n) => `${m} alla MEV · ${n} seeriat`,
  allInRange: 'Kõik lihased on produktiivses vahemikus',
  inRangeOf: (a, b) => `${a}/${b} lihast vahemikus`,
  ofInRange: (b) => `/ ${b} vahemikus`,
  setsWeek: 'seeriat / näd',
  overNote: (m, n, u) =>
    u
      ? `${m} on üle MRV — vii järgmisel nädalal ~${n} seeriat üle: ${u}.`
      : `${m} on üle MRV — kärbi järgmisel nädalal ~${n} seeriat.`,
  underNote: (m, n) => `${m} on alla MEV — lisa sel nädalal ~${n} seeriat.`,
  sweetSpot: 'MEV–MAV optimum',
  tip: 'Nõuanne',
  stimulus: 'Tänane stiimul alles',
  leftToday: 'Täna alles',
  leftTodayOf: (d) => `Täna alles · ${d}`,
  stimEmpty: 'Täna pole lihaseid planeeritud',
  stimEmptySub: 'Vali programmi päev või alusta trenni',
  doneMark: 'tehtud ✓',
  nLeft: (n) => `${n} alles`,
  setsLeftTitle: (n) => `${n} produktiivset seeriat alles`,
  allDone: 'Kõik planeeritu tehtud',
  toMav: 'MAV-ini',
  readiness: (p) => `Valmisolek ${p}%`,
  continueWorkout: 'Jätka trenni',
  setsLeft: 'seeriat alles',
  ofDone: (d, t) => `${d}/${t} produktiivset seeriat tehtud`,
  minutes: (n) => `~${n} min sinu tempoga`,
  lr: 'Vasak / parem tasakaal',
  lrKicker: 'Vasak / parem · e1RM',
  lrTitle: 'Vasaku ja parema test',
  lrHint:
    'Logi salvestab ühe poole. Tee seeria kummalegi ja sisesta mõlemad — hoitakse selles seadmes.',
  liftName: 'Harjutus',
  left: 'Vasak',
  right: 'Parem',
  l: 'V',
  r: 'P',
  even: 'võrdne ✓',
  sideTag: (side, p) => `${side} −${p}%`,
  pctSide: (side) => `% ${side}`,
  lrEmpty: 'Poolte testi veel pole',
  lrEmptySub: (x) => `Proovi ${x}: seeria kummalegi poolele`,
  testLift: 'Testi',
  leftSide: 'Vasak pool',
  rightSide: 'Parem pool',
  balancedLr: 'Mõlemad pooled võrdsed',
  weaker: (side, p) => `${side} ${p}% nõrgem`,
  startWeaker: (side) => `Alusta seeriaid nõrgema poolega (${side.toLowerCase()})`,
  muscleWeek: 'Nädala lihas',
  focusWeek: 'Fookus · nädal',
  focus: (m) => `Fookus: ${m}`,
  mwSub: (d, g, n, day) =>
    n > 0 ? `${d}/${g} seeriat · veel ${n} kuni ${day}` : `${d}/${g} seeriat · tehtud`,
  ofSets: (g) => `/ ${g} seeriat`,
  addMore: (n, ex) => `Veel ${n} seeriat „${ex}“ sulgeb vahe.`,
  addSets: (n) => `Veel ${n} seeriat sulgeb vahe.`,
  goalHit: 'Nädala eesmärk täidetud',
  furthest: '4 nädalaga MAV-ist kõige kaugemal',
  toGoBy: (n, day) => `veel ${n} seeriat kuni ${day}`,
  nowShort: 'nüüd',
  nSets: (n) => `${n} seeriat`,
  openMuscle: 'Ava lihas',
  mwEmpty: 'Vaja kaks nädalat trenni',
  mwEmptySub: 'Siis saab mahajääv lihas tähelepanu',
  frequency: 'Sagedus',
  freqWeek: 'Sagedus · see nädal',
  target2: 'eesmärk 2×',
  target2Muscle: 'eesmärk 2× lihase kohta',
  hitTwice: (a, b) => `${a}/${b} lihast 2×`,
  atTwice: (b) => `/ ${b} 2× tabatud`,
  onlyX: (m, n) => `${m} ainult ${n}× sel nädalal`,
  allTwice: 'Iga lihas vähemalt kaks korda',
  trained: 'Treenitud',
  planned: 'Planeeritud',
  plannedLower: 'planeeritud',
  freqEmpty: 'Trenne veel pole',
  freqEmptySub: 'Täpid täituvad treenides',
  ppl: 'Surumine / Tõmme / Jalad',
  pplName: { push: 'Surumine', pull: 'Tõmme', legs: 'Jalad' },
  split4: 'Mahu jaotus · 4 näd',
  weeks4: '4 nädalat',
  pplBalanced: 'Lähedal eesmärgile 35 / 35 / 30',
  pplBalancedShort: 'Tasakaalus',
  heavy: (x) => `Ülekaal: ${x}`,
  below: (x, d) => `${x} ${d}% alla eesmärgi`,
  above: (x, d) => `${x} ${d}% üle eesmärgi`,
  setsTarget: (n, t) => `${n} · eesmärk ${t}%`,
  byWeek: 'Nädalate kaupa',
  pplEmpty: '4 nädalaga pole jõuseeriaid',
  pplEmptySub: 'Jaotus ilmub paari trenni järel',
  heatmap: 'Järjepidevuse kaart',
  consistency: 'Järjepidevus',
  weeks16: '16 nädalat',
  days52: 'Trennipäevad · 52 nädalat',
  weekStreak: (n) => `${n} nädala seeria`,
  wkStreak: 'nädalat järjest',
  wk: 'näd',
  sessions16: (n, p) => `${n} trenni 16 nädalaga · ${p} / näd`,
  bestN: (n) => `Rekord ${n}`,
  perWeek: (p) => `${p} / näd`,
  nSessions: (n) => `${n} trenni`,
  streak: 'Seeria',
  longest: 'Pikim',
  nWeeks: (n) => `${n} näd`,
  inYear: (y) => `${y}. a`,
  less: 'Vähem',
  more: 'Rohkem',
  heatEmpty: 'Trenne veel pole',
  heatEmptySub: 'Siia ilmuvad sinu trennipäevad',
  weeklyGoal: 'Nädala eesmärk',
  goalKicker: (g) => `Nädala eesmärk · ${g} trenni`,
  goalWeek: (r) => `Nädala eesmärk · ${r}`,
  goalOf: (d, g) => `Nädala eesmärk · ${d}/${g}`,
  goalDone: 'Eesmärk täidetud',
  nToGo: (n) => `veel ${n}`,
  toGoBy2: (n, day) => `veel ${n} kuni ${day}`,
  byDay: (day) => `kuni ${day}`,
  nextOn: (name, when) => `Järgmine: ${name} ${when}`,
  streakWeeks: (n) => `${n} nädalat järjest eesmärgiga`,
  daysLeft: (n) => `päevi jäänud: ${n}`,
  last6: (x) => `Viimased 6 nädalat: ${x}`,
  editGoal: 'Muuda eesmärki',
  goalTitle: 'Trenne nädalas',
  goalHint: 'Hoitakse selles seadmes. Vaikimisi sinu programmi päevad.',
  perWk: '/ näd',
  sessionsMonth: 'Trennid kuus',
  sessionsUnit: 'trenni',
  inMonth: (n, m) => `${m}: ${n} trenni`,
  vsMonth: (d, m) => `${d} vs ${m}`,
  monthVs: (a, b) => `Trennid · ${a} vs ${b}`,
  vsN: (n) => `vs ${n}`,
  vsIn: (n: number, m: string) => `vs ${n} in ${m}`,
  last14: 'Last 14 days',
  sessions14: (n: number) => `${n} sessions in 14 days`,
  sessionsOf: (m) => `Trennid · ${m}`,
  best6: 'parim 6 kuuga',
  hoursTotal: (h, avg) => `kokku ${h} h · keskm. ${avg} min`,
  chunk: (n, h) => `${n} trenni · ${h} h`,
  openHistory: 'Ava ajalugu',
  bestTime: 'Parim trenniaeg',
  bestTimeShort: 'Parim aeg',
  slotName: ['Hommik', 'Keskpäev', 'Pärastlõuna', 'Õhtu'],
  slotShort: ['Hom', 'Kesk', 'Pl', 'Õhtu'],
  slotRange: ['6–10', '10–14', '14–18', '18–22'],
  strongest: (d, s) => `Tugevaim: ${d}, ${s}`,
  topSets: (x) => `Tippseeriad ${x} sinu keskmisest`,
  topSetsShort: (x) => `${x} tippseeriad`,
  fromN: (n) => `${n} trenni põhjal`,
  vsAvg12: 'e1RM vs keskm. · 12 näd',
  weakest: (l, x) => `Nõrgim: ${l} ${x}`,
  valuesNote: (n) => `Väärtused = % keskmisest tippseeriast · ${n} trenni`,
  bestNote: (d, s, x) => `${d}, ${s} on sinu tugevaim aeg (${x}).`,
  btEmpty: 'Liiga vähe trenne',
  btEmptySub: '6+ trenni korduvate harjutustega 12 nädalaga',
  backOnTrack: 'Tagasi rütmi',
  onTrack: 'Rütmis',
  onTrackNote: 'pausi pole',
  lastAgo: (n, d) => (n === 0 ? 'Trenn täna' : `Viimane trenn ${n} p tagasi · ${d}`),
  daysSince: 'päeva möödas',
  welcome: (n) => `Tere tulemast tagasi · ${n} p pausi`,
  rampStep: (n) => `Tagasi rütmi · trenn ${n}/3`,
  firstLighter: (l) => `See trenn kergem: ${l}% koormust`,
  pctLoad: '% koormust',
  offSession: (d, n) => `${d} p pausi · trenn ${n}/3`,
  botKicker: (d) => `Tagasi rütmi · ${d} p pausi`,
  ease: 'Sujuv naasmine 3 trenniga',
  minus: (p) => `−${p}% raskust · −1 seeria`,
  startLight: 'Alusta kergelt',
  todayCap: 'Täna',
  nextCap: 'Järgmine',
  thenCap: 'Siis',
  sessionN: (n) => `Trenn ${n}`,
  fullLoad: 'Täiskoormus',
  backToPlan: 'Täiskoormus · plaani järgi',
  loadSets: (l) => `${l}% · ${l < 90 ? '3 seeriat / harj.' : 'täisseeriad'}`,
  lastSession: (d) => `viimane trenn ${d}`,
  daysOffUnit: 'p pausi',
  example0: 'Näide',
  example: (ex, kg, full) => `${ex} täna: ${kg} kg ${full} kg asemel`,
  lighter: 'Täna iga harjutus ~20% kergem',
  warmNote: 'Kergem soojendus · lõpeta 2–3 kordust enne väsimust',
};

const DICT: Record<LocaleId, MusclesStrings> = { en, uk, pl, lt, et };

export function ms(locale: LocaleId): MusclesStrings {
  return DICT[locale];
}
