/**
 * Copy of the Plan & sessions widgets (design L5), all five locales. Typed from
 * `en`, so a missing key in any locale fails the build. Muscle names, day
 * labels and "Workout" come from the main dictionary.
 */
import type { LocaleId } from '../../i18n';

const en = {
  names: {
    next: 'Next workout',
    builder: 'Quick session builder',
    warmup: 'Warm-up',
    program: 'Program progress',
    week: 'This week’s plan',
    time: 'Time to train',
    rest: 'Rest timer',
    last: 'Last session',
    muscles: 'Last session muscles',
    energy: 'Session energy',
    effort: 'Effort trend',
    length: 'Session length',
    home: 'Home sets',
  },
  today: 'today',
  tomorrow: 'tomorrow',
  yesterday: 'yesterday',
  todayCap: 'Today',
  minN: (n: number) => `${n} min`,
  lastKg: (kg: number) => `last ${kg} kg`,
  setsN: (n: number) => `${n} sets`,
  sessionsN: (n: number) => `${n} sessions`,
  start: 'Start',
  summary: 'Summary',
  noSession: 'No sessions yet',
  noSessionSub: 'Log your first workout to see it here',
  // Next workout
  nextUp: 'Next up',
  noPlan: 'No workout planned',
  noPlanSub: 'Pick a program or log a few sessions',
  buildOne: 'Build a session',
  exercisesN: (n: number) => `${n} exercises`,
  dayOf: (a: number, b: number) => `Day ${a} of ${b}`,
  nextOf: (p: string) => `Next workout · ${p}`,
  nextWeek: (w: number) => `Next workout · week ${w}`,
  lastDone: (x: string) => `Last done ${x}`,
  // Quick session builder
  quick: 'Quick session',
  buildMe: 'Build me a session',
  build: 'Build',
  generate: 'Generate',
  regenerate: 'Regenerate',
  lengthL: 'Session length',
  aboutEx: (n: number) => `~${n} exercises`,
  startMin: (n: number) => `Start · ${n} min`,
  focus: {
    auto: 'Auto',
    upper: 'Upper',
    push: 'Push',
    pull: 'Pull',
    legs: 'Legs',
    full: 'Full',
  },
  // Warm-up
  warmupFor: (x: string) => `Warm-up · ${x}`,
  rampTo: (n: number, kg: string) => `${n} ramp sets → ${kg}`,
  noRamp: 'Light lift — mobility is enough',
  plusMobility: '+ mobility',
  mobilityMin: (n: number) => `Mobility · ${n} min`,
  bar: 'Bar',
  work: (kg: string) => `work ${kg}`,
  working: (kg: string) => `Working ${kg}`,
  startSession: 'Start session',
  mobUpper: ['Arm circles 30s', 'Band pull-apart ×15', 'T-spine rotation ×8', 'Scap push-up ×10'],
  mobLower: ['Leg swings ×10', 'Hip circles ×8', 'Goblet squat hold 30s', 'Ankle rocks ×10'],
  // Program progress
  noProgram: 'No program yet',
  noProgramSub: 'Assign or build one to track weeks',
  openPrograms: 'Programs',
  openProgram: 'Open program',
  programK: (p: string) => `Program · ${p}`,
  weekN: (n: number) => `Week ${n}`,
  weekOf: (a: number, b: number) => `Week ${a} of ${b}`,
  weekShort: 'week',
  ofWeeks: (n: number) => `of ${n} weeks`,
  ofN: (n: number) => `of ${n}`,
  ofSessions: (n: number) => `of ${n} sessions`,
  doneOf: (a: number, b: number) => `${a} of ${b} sessions`,
  adherence: (p: number) => `${p}% adherence`,
  adherenceWord: 'adherence',
  doneN: (n: number) => `${n} done`,
  missedN: (n: number) => `${n} missed`,
  toGoN: (n: number) => `${n} to go`,
  endsOn: (x: string) => `Ends ${x}`,
  missedL: 'Missed',
  thisWeekL: 'This week',
  // This week's plan
  thisWeek: 'This week',
  rest: 'Rest',
  recover: 'recover',
  planWeek: 'Plan your week',
  planWeekSub: 'A program or a few sessions fill it in',
  doneOfN: (a: number, b: number) => `${a} of ${b} done`,
  nextX: (x: string) => `Next: ${x}`,
  nextWeekStarts: (x: string) => `Next week starts ${x}`,
  // Time to train
  usualTime: 'Usual time',
  timeLast60: 'Time to train · last 60 days',
  usualStart: 'usual start',
  usuallyAt: (x: string) => `You usually train at ${x}`,
  learningTime: 'Learning your rhythm',
  learningTimeSub: 'Log a few sessions to see your usual time',
  doneToday: 'Done today',
  inX: (x: string) => `in ${x}`,
  nowTime: 'Now’s the time',
  laterToday: 'Later than usual today',
  fromN: (n: number) => `from ${n} sessions`,
  weekend: 'weekend',
  startNow: 'Start now',
  // Rest timer
  quickRest: 'Quick rest',
  quickRestSub: 'Tap a preset to start',
  readyNext: 'Ready for the next set',
  ofX: (x: string) => `of ${x}`,
  restRunning: 'Rest · running',
  restOver: 'Rest is over',
  restK: (x: string) => `Rest · ${x}`,
  skip: 'Skip',
  skipRest: 'Skip',
  setN: (x: string) => `set ${x}`,
  lastSetX: (x: string) => `Last: ${x}`,
  upNext: (x: string) => `Up next · ${x}`,
  // Last session
  prN: (n: number) => `${n} PR`,
  pr: 'PR',
  timeL: 'time',
  volumeL: 'volume',
  setsL: 'sets',
  prsL: 'PRs',
  // Last session muscles
  worked: 'Worked',
  workedWhen: (x: string) => `Worked · ${x}`,
  plusSecondary: (n: number) => `+${n} secondary`,
  setsGroups: (a: number, b: number) => `${a} sets · ${b} muscle groups`,
  // Session energy
  lastWorkout: 'Last workout',
  needWeight: 'Add your weight',
  needWeightSub: 'Energy is estimated from your body weight',
  logWeight: 'Log weight',
  perMin: (x: string) => `${x} kcal/min`,
  energyK: (x: string) => `Session energy · ${x}`,
  vsAvg: (x: string) => `${x} vs avg`,
  lastNAvg: (n: number, avg: number) => `last ${n} · avg ${avg}`,
  weekKcal: (k: number, n: number) => `This week ${k} kcal · ${n} sessions`,
  // Effort trend
  effortK: 'Effort · RPE',
  noRpe: 'No effort data yet',
  noRpeSub: 'Rate a few sets (RPE) to see the trend',
  zone: (x: string) => `zone ${x}`,
  inZone: 'in zone',
  belowZone: 'below zone',
  aboveZone: 'above zone',
  adviceLow: 'Room to push a little harder',
  adviceHigh: 'Running hot — consider an easier week',
  adviceZone: 'Right in the zone — keep it up',
  avgRpe: (x: string) => `Avg RPE ${x}`,
  avgRpeUnit: 'avg RPE',
  avg: 'avg',
  lastNSessions: (n: number) => `last ${n} sessions`,
  effortLast: (n: number) => `Effort · last ${n} sessions`,
  inZoneN: (a: number, b: number) => `${a}/${b} in zone`,
  progress: 'Progress',
  // Session length
  avgSession: 'Avg session',
  noRecent: 'Nothing in the last 30 days',
  vsPrev: (x: string) => `${x} vs previous 30 days`,
  avgPer: (x: string) => `Avg ${x} per session`,
  days30: '30 days',
  lengthLast: (n: number) => `Session length · last ${n}`,
  length30: 'Session length · 30 days',
  history: 'History',
  avgLongest: (x: string) => `avg ${x} · longest`,
  avgX: (x: string) => `avg ${x}`,
  // Home sets
  noHome: 'No home sets yet',
  noHomeSub: 'Save a template to start it in one tap',
  newTemplate: 'New template',
  homeN: (n: number) => `Home sets · ${n} templates`,
  lastX: (x: string) => `last: ${x}`,
  weekTimes: (n: number) => `${n}× this week`,
  noGym: 'No gym needed · counts to streak',
  reps: 'reps',
  vsLast: (x: string) => `${x} vs last time`,
};

export type PlanStrings = typeof en;

const uk: PlanStrings = {
  names: {
    next: 'Наступне тренування',
    builder: 'Швидкий конструктор сесії',
    warmup: 'Розминка',
    program: 'Прогрес програми',
    week: 'План на тиждень',
    time: 'Час тренуватись',
    rest: 'Таймер відпочинку',
    last: 'Остання сесія',
    muscles: 'М’язи останньої сесії',
    energy: 'Енергія сесії',
    effort: 'Тренд зусиль',
    length: 'Тривалість сесії',
    home: 'Домашні сети',
  },
  today: 'сьогодні',
  tomorrow: 'завтра',
  yesterday: 'вчора',
  todayCap: 'Сьогодні',
  minN: (n) => `${n} хв`,
  lastKg: (kg) => `минулого разу ${kg} кг`,
  setsN: (n) => `підходів: ${n}`,
  sessionsN: (n) => `сесій: ${n}`,
  start: 'Почати',
  summary: 'Підсумок',
  noSession: 'Сесій ще немає',
  noSessionSub: 'Запиши перше тренування, щоб побачити його тут',
  nextUp: 'Далі',
  noPlan: 'Тренування не заплановане',
  noPlanSub: 'Обери програму або запиши кілька сесій',
  buildOne: 'Зібрати сесію',
  exercisesN: (n) => `вправ: ${n}`,
  dayOf: (a, b) => `День ${a} з ${b}`,
  nextOf: (p) => `Наступне · ${p}`,
  nextWeek: (w) => `Наступне · тиждень ${w}`,
  lastDone: (x) => `Востаннє ${x}`,
  quick: 'Швидка сесія',
  buildMe: 'Збери мені сесію',
  build: 'Зібрати',
  generate: 'Згенерувати',
  regenerate: 'Інший варіант',
  lengthL: 'Тривалість сесії',
  aboutEx: (n) => `~${n} вправ`,
  startMin: (n) => `Почати · ${n} хв`,
  focus: {
    auto: 'Авто',
    upper: 'Верх',
    push: 'Жим',
    pull: 'Тяга',
    legs: 'Ноги',
    full: 'Усе тіло',
  },
  warmupFor: (x) => `Розминка · ${x}`,
  rampTo: (n, kg) => `${n} розминкових → ${kg}`,
  noRamp: 'Легка вправа — вистачить мобільності',
  plusMobility: '+ мобільність',
  mobilityMin: (n) => `Мобільність · ${n} хв`,
  bar: 'Гриф',
  work: (kg) => `робоча ${kg}`,
  working: (kg) => `Робоча ${kg}`,
  startSession: 'Почати сесію',
  mobUpper: [
    'Кола руками 30 с',
    'Розтягування гуми ×15',
    'Ротації грудного відділу ×8',
    'Віджимання лопатками ×10',
  ],
  mobLower: [
    'Махи ногами ×10',
    'Кола тазом ×8',
    'Кубковий присід, утримання 30 с',
    'Розминка гомілкостопу ×10',
  ],
  noProgram: 'Програми ще немає',
  noProgramSub: 'Признач або створи її, щоб стежити за тижнями',
  openPrograms: 'Програми',
  openProgram: 'Відкрити програму',
  programK: (p) => `Програма · ${p}`,
  weekN: (n) => `Тиждень ${n}`,
  weekOf: (a, b) => `Тиждень ${a} з ${b}`,
  weekShort: 'тиждень',
  ofWeeks: (n) => `з ${n} тижнів`,
  ofN: (n) => `з ${n}`,
  ofSessions: (n) => `з ${n} сесій`,
  doneOf: (a, b) => `${a} з ${b} сесій`,
  adherence: (p) => `${p}% дотримання`,
  adherenceWord: 'дотримання',
  doneN: (n) => `виконано: ${n}`,
  missedN: (n) => `пропущено: ${n}`,
  toGoN: (n) => `лишилось: ${n}`,
  endsOn: (x) => `Завершення ${x}`,
  missedL: 'Пропущено',
  thisWeekL: 'Цей тиждень',
  thisWeek: 'Цей тиждень',
  rest: 'Відпочинок',
  recover: 'відновлення',
  planWeek: 'Сплануй тиждень',
  planWeekSub: 'Програма або кілька сесій заповнять його',
  doneOfN: (a, b) => `${a} з ${b} виконано`,
  nextX: (x) => `Далі: ${x}`,
  nextWeekStarts: (x) => `Наступний тиждень з ${x}`,
  usualTime: 'Звичний час',
  timeLast60: 'Час тренування · 60 днів',
  usualStart: 'звичний старт',
  usuallyAt: (x) => `Зазвичай тренуєшся о ${x}`,
  learningTime: 'Вивчаємо твій ритм',
  learningTimeSub: 'Запиши кілька сесій, щоб побачити звичний час',
  doneToday: 'Сьогодні виконано',
  inX: (x) => `через ${x}`,
  nowTime: 'Саме час',
  laterToday: 'Сьогодні пізніше, ніж зазвичай',
  fromN: (n) => `за ${n} сесіями`,
  weekend: 'вихідний',
  startNow: 'Почати зараз',
  quickRest: 'Швидкий відпочинок',
  quickRestSub: 'Обери пресет, щоб почати',
  readyNext: 'Готовий до наступного підходу',
  ofX: (x) => `з ${x}`,
  restRunning: 'Відпочинок · триває',
  restOver: 'Відпочинок завершено',
  restK: (x) => `Відпочинок · ${x}`,
  skip: 'Пропустити',
  skipRest: 'Далі',
  setN: (x) => `підхід ${x}`,
  lastSetX: (x) => `Останній: ${x}`,
  upNext: (x) => `Далі · ${x}`,
  prN: (n) => `${n} PR`,
  pr: 'PR',
  timeL: 'час',
  volumeL: 'обсяг',
  setsL: 'підходи',
  prsL: 'рекорди',
  worked: 'Опрацьовано',
  workedWhen: (x) => `Опрацьовано · ${x}`,
  plusSecondary: (n) => `+${n} допоміжних`,
  setsGroups: (a, b) => `${a} підходів · ${b} груп м’язів`,
  lastWorkout: 'Останнє тренування',
  needWeight: 'Додай свою вагу',
  needWeightSub: 'Енергію оцінюємо з ваги тіла',
  logWeight: 'Записати вагу',
  perMin: (x) => `${x} ккал/хв`,
  energyK: (x) => `Енергія сесії · ${x}`,
  vsAvg: (x) => `${x} до середнього`,
  lastNAvg: (n, avg) => `останні ${n} · сер. ${avg}`,
  weekKcal: (k, n) => `Цього тижня ${k} ккал · сесій: ${n}`,
  effortK: 'Зусилля · RPE',
  noRpe: 'Даних про зусилля ще немає',
  noRpeSub: 'Оціни кілька підходів (RPE), щоб бачити тренд',
  zone: (x) => `зона ${x}`,
  inZone: 'у зоні',
  belowZone: 'нижче зони',
  aboveZone: 'вище зони',
  adviceLow: 'Є запас трохи піднажати',
  adviceHigh: 'Забагато — подумай про легший тиждень',
  adviceZone: 'Саме в зоні — так тримати',
  avgRpe: (x) => `Сер. RPE ${x}`,
  avgRpeUnit: 'сер. RPE',
  avg: 'сер.',
  lastNSessions: (n) => `останні ${n} сесій`,
  effortLast: (n) => `Зусилля · останні ${n} сесій`,
  inZoneN: (a, b) => `${a}/${b} у зоні`,
  progress: 'Прогрес',
  avgSession: 'Середня сесія',
  noRecent: 'Нічого за останні 30 днів',
  vsPrev: (x) => `${x} до попередніх 30 днів`,
  avgPer: (x) => `У середньому ${x} на сесію`,
  days30: '30 днів',
  lengthLast: (n) => `Тривалість · останні ${n}`,
  length30: 'Тривалість · 30 днів',
  history: 'Історія',
  avgLongest: (x) => `сер. ${x} · найдовша`,
  avgX: (x) => `сер. ${x}`,
  noHome: 'Домашніх сетів ще немає',
  noHomeSub: 'Збережи шаблон, щоб запускати в один дотик',
  newTemplate: 'Новий шаблон',
  homeN: (n) => `Домашні сети · шаблонів: ${n}`,
  lastX: (x) => `востаннє: ${x}`,
  weekTimes: (n) => `${n}× цього тижня`,
  noGym: 'Без залу · зараховується у серію',
  reps: 'повт.',
  vsLast: (x) => `${x} до минулого разу`,
};

const pl: PlanStrings = {
  names: {
    next: 'Następny trening',
    builder: 'Szybki kreator sesji',
    warmup: 'Rozgrzewka',
    program: 'Postęp programu',
    week: 'Plan na tydzień',
    time: 'Pora na trening',
    rest: 'Minutnik przerwy',
    last: 'Ostatnia sesja',
    muscles: 'Mięśnie ostatniej sesji',
    energy: 'Energia sesji',
    effort: 'Trend wysiłku',
    length: 'Długość sesji',
    home: 'Zestawy domowe',
  },
  today: 'dziś',
  tomorrow: 'jutro',
  yesterday: 'wczoraj',
  todayCap: 'Dziś',
  minN: (n) => `${n} min`,
  lastKg: (kg) => `ostatnio ${kg} kg`,
  setsN: (n) => `serie: ${n}`,
  sessionsN: (n) => `sesje: ${n}`,
  start: 'Start',
  summary: 'Podsumowanie',
  noSession: 'Brak sesji',
  noSessionSub: 'Zapisz pierwszy trening, by zobaczyć go tutaj',
  nextUp: 'Następne',
  noPlan: 'Brak zaplanowanego treningu',
  noPlanSub: 'Wybierz program lub zapisz kilka sesji',
  buildOne: 'Zbuduj sesję',
  exercisesN: (n) => `ćwiczenia: ${n}`,
  dayOf: (a, b) => `Dzień ${a} z ${b}`,
  nextOf: (p) => `Następny trening · ${p}`,
  nextWeek: (w) => `Następny trening · tydzień ${w}`,
  lastDone: (x) => `Ostatnio ${x}`,
  quick: 'Szybka sesja',
  buildMe: 'Zbuduj mi sesję',
  build: 'Zbuduj',
  generate: 'Generuj',
  regenerate: 'Inna wersja',
  lengthL: 'Długość sesji',
  aboutEx: (n) => `~${n} ćwiczeń`,
  startMin: (n) => `Start · ${n} min`,
  focus: {
    auto: 'Auto',
    upper: 'Góra',
    push: 'Pchanie',
    pull: 'Ciąganie',
    legs: 'Nogi',
    full: 'Całe ciało',
  },
  warmupFor: (x) => `Rozgrzewka · ${x}`,
  rampTo: (n, kg) => `${n} serie wstępne → ${kg}`,
  noRamp: 'Lekkie ćwiczenie — wystarczy mobilność',
  plusMobility: '+ mobilność',
  mobilityMin: (n) => `Mobilność · ${n} min`,
  bar: 'Gryf',
  work: (kg) => `robocze ${kg}`,
  working: (kg) => `Robocze ${kg}`,
  startSession: 'Rozpocznij sesję',
  mobUpper: [
    'Krążenia ramion 30 s',
    'Rozciąganie gumy ×15',
    'Rotacje piersiowe ×8',
    'Pompki łopatkowe ×10',
  ],
  mobLower: [
    'Wymachy nóg ×10',
    'Krążenia bioder ×8',
    'Przysiad goblet 30 s',
    'Mobilizacja kostek ×10',
  ],
  noProgram: 'Brak programu',
  noProgramSub: 'Przypisz lub zbuduj go, by śledzić tygodnie',
  openPrograms: 'Programy',
  openProgram: 'Otwórz program',
  programK: (p) => `Program · ${p}`,
  weekN: (n) => `Tydzień ${n}`,
  weekOf: (a, b) => `Tydzień ${a} z ${b}`,
  weekShort: 'tydzień',
  ofWeeks: (n) => `z ${n} tygodni`,
  ofN: (n) => `z ${n}`,
  ofSessions: (n) => `z ${n} sesji`,
  doneOf: (a, b) => `${a} z ${b} sesji`,
  adherence: (p) => `${p}% realizacji`,
  adherenceWord: 'realizacja',
  doneN: (n) => `zrobione: ${n}`,
  missedN: (n) => `pominięte: ${n}`,
  toGoN: (n) => `zostało: ${n}`,
  endsOn: (x) => `Koniec ${x}`,
  missedL: 'Pominięte',
  thisWeekL: 'Ten tydzień',
  thisWeek: 'Ten tydzień',
  rest: 'Odpoczynek',
  recover: 'regeneracja',
  planWeek: 'Zaplanuj tydzień',
  planWeekSub: 'Program lub kilka sesji go wypełni',
  doneOfN: (a, b) => `${a} z ${b} zrobione`,
  nextX: (x) => `Następne: ${x}`,
  nextWeekStarts: (x) => `Następny tydzień od ${x}`,
  usualTime: 'Zwykła pora',
  timeLast60: 'Pora treningu · 60 dni',
  usualStart: 'zwykły start',
  usuallyAt: (x) => `Zwykle trenujesz o ${x}`,
  learningTime: 'Uczymy się twojego rytmu',
  learningTimeSub: 'Zapisz kilka sesji, by zobaczyć zwykłą porę',
  doneToday: 'Dziś zrobione',
  inX: (x) => `za ${x}`,
  nowTime: 'Właśnie teraz',
  laterToday: 'Dziś później niż zwykle',
  fromN: (n) => `z ${n} sesji`,
  weekend: 'weekend',
  startNow: 'Zacznij teraz',
  quickRest: 'Szybka przerwa',
  quickRestSub: 'Wybierz ustawienie, by zacząć',
  readyNext: 'Gotowy na następną serię',
  ofX: (x) => `z ${x}`,
  restRunning: 'Przerwa · trwa',
  restOver: 'Koniec przerwy',
  restK: (x) => `Przerwa · ${x}`,
  skip: 'Pomiń',
  skipRest: 'Dalej',
  setN: (x) => `seria ${x}`,
  lastSetX: (x) => `Ostatnia: ${x}`,
  upNext: (x) => `Następne · ${x}`,
  prN: (n) => `${n} PR`,
  pr: 'PR',
  timeL: 'czas',
  volumeL: 'objętość',
  setsL: 'serie',
  prsL: 'rekordy',
  worked: 'Pracowały',
  workedWhen: (x) => `Pracowały · ${x}`,
  plusSecondary: (n) => `+${n} pomocnicze`,
  setsGroups: (a, b) => `${a} serii · ${b} grup mięśni`,
  lastWorkout: 'Ostatni trening',
  needWeight: 'Dodaj swoją wagę',
  needWeightSub: 'Energię szacujemy z masy ciała',
  logWeight: 'Zapisz wagę',
  perMin: (x) => `${x} kcal/min`,
  energyK: (x) => `Energia sesji · ${x}`,
  vsAvg: (x) => `${x} vs średnia`,
  lastNAvg: (n, avg) => `ostatnie ${n} · śr. ${avg}`,
  weekKcal: (k, n) => `W tym tygodniu ${k} kcal · sesje: ${n}`,
  effortK: 'Wysiłek · RPE',
  noRpe: 'Brak danych o wysiłku',
  noRpeSub: 'Oceń kilka serii (RPE), by zobaczyć trend',
  zone: (x) => `strefa ${x}`,
  inZone: 'w strefie',
  belowZone: 'poniżej strefy',
  aboveZone: 'powyżej strefy',
  adviceLow: 'Jest zapas, by docisnąć',
  adviceHigh: 'Za gorąco — rozważ lżejszy tydzień',
  adviceZone: 'Idealnie w strefie — tak trzymaj',
  avgRpe: (x) => `Śr. RPE ${x}`,
  avgRpeUnit: 'śr. RPE',
  avg: 'śr.',
  lastNSessions: (n) => `ostatnie ${n} sesji`,
  effortLast: (n) => `Wysiłek · ostatnie ${n} sesji`,
  inZoneN: (a, b) => `${a}/${b} w strefie`,
  progress: 'Postępy',
  avgSession: 'Średnia sesja',
  noRecent: 'Nic w ostatnich 30 dniach',
  vsPrev: (x) => `${x} vs poprzednie 30 dni`,
  avgPer: (x) => `Średnio ${x} na sesję`,
  days30: '30 dni',
  lengthLast: (n) => `Długość sesji · ostatnie ${n}`,
  length30: 'Długość sesji · 30 dni',
  history: 'Historia',
  avgLongest: (x) => `śr. ${x} · najdłuższa`,
  avgX: (x) => `śr. ${x}`,
  noHome: 'Brak zestawów domowych',
  noHomeSub: 'Zapisz szablon, by startować jednym dotknięciem',
  newTemplate: 'Nowy szablon',
  homeN: (n) => `Zestawy domowe · szablony: ${n}`,
  lastX: (x) => `ostatnio: ${x}`,
  weekTimes: (n) => `${n}× w tym tygodniu`,
  noGym: 'Bez siłowni · liczy się do serii',
  reps: 'powt.',
  vsLast: (x) => `${x} vs poprzednio`,
};

const lt: PlanStrings = {
  names: {
    next: 'Kita treniruotė',
    builder: 'Greitas treniruotės kūrėjas',
    warmup: 'Apšilimas',
    program: 'Programos progresas',
    week: 'Savaitės planas',
    time: 'Laikas treniruotis',
    rest: 'Poilsio laikmatis',
    last: 'Paskutinė treniruotė',
    muscles: 'Paskutinės treniruotės raumenys',
    energy: 'Treniruotės energija',
    effort: 'Pastangų tendencija',
    length: 'Treniruotės trukmė',
    home: 'Namų rinkiniai',
  },
  today: 'šiandien',
  tomorrow: 'rytoj',
  yesterday: 'vakar',
  todayCap: 'Šiandien',
  minN: (n) => `${n} min`,
  lastKg: (kg) => `praeitą kartą ${kg} kg`,
  setsN: (n) => `serijų: ${n}`,
  sessionsN: (n) => `treniruočių: ${n}`,
  start: 'Pradėti',
  summary: 'Suvestinė',
  noSession: 'Treniruočių dar nėra',
  noSessionSub: 'Užrašyk pirmą treniruotę ir ji atsiras čia',
  nextUp: 'Toliau',
  noPlan: 'Treniruotė nesuplanuota',
  noPlanSub: 'Pasirink programą arba užrašyk kelias treniruotes',
  buildOne: 'Sukurti treniruotę',
  exercisesN: (n) => `pratimų: ${n}`,
  dayOf: (a, b) => `${a} diena iš ${b}`,
  nextOf: (p) => `Kita treniruotė · ${p}`,
  nextWeek: (w) => `Kita treniruotė · ${w} savaitė`,
  lastDone: (x) => `Paskutinį kartą ${x}`,
  quick: 'Greita treniruotė',
  buildMe: 'Sukurk man treniruotę',
  build: 'Sukurti',
  generate: 'Generuoti',
  regenerate: 'Kitas variantas',
  lengthL: 'Treniruotės trukmė',
  aboutEx: (n) => `~${n} pratimai`,
  startMin: (n) => `Pradėti · ${n} min`,
  focus: {
    auto: 'Auto',
    upper: 'Viršus',
    push: 'Stūmimas',
    pull: 'Traukimas',
    legs: 'Kojos',
    full: 'Visas kūnas',
  },
  warmupFor: (x) => `Apšilimas · ${x}`,
  rampTo: (n, kg) => `${n} apšilimo serijos → ${kg}`,
  noRamp: 'Lengvas pratimas — pakanka mobilumo',
  plusMobility: '+ mobilumas',
  mobilityMin: (n) => `Mobilumas · ${n} min`,
  bar: 'Grifas',
  work: (kg) => `darbinis ${kg}`,
  working: (kg) => `Darbinis ${kg}`,
  startSession: 'Pradėti treniruotę',
  mobUpper: [
    'Rankų sukimai 30 s',
    'Gumos tempimas ×15',
    'Krūtinės sukimai ×8',
    'Menčių atsispaudimai ×10',
  ],
  mobLower: ['Kojų mostai ×10', 'Klubų sukimai ×8', 'Taurės pritūpimas 30 s', 'Čiurnų mankšta ×10'],
  noProgram: 'Programos dar nėra',
  noProgramSub: 'Priskirk arba sukurk, kad sektum savaites',
  openPrograms: 'Programos',
  openProgram: 'Atidaryti programą',
  programK: (p) => `Programa · ${p}`,
  weekN: (n) => `${n} savaitė`,
  weekOf: (a, b) => `${a} savaitė iš ${b}`,
  weekShort: 'savaitė',
  ofWeeks: (n) => `iš ${n} savaičių`,
  ofN: (n) => `iš ${n}`,
  ofSessions: (n) => `iš ${n} treniruočių`,
  doneOf: (a, b) => `${a} iš ${b} treniruočių`,
  adherence: (p) => `${p}% laikymasis`,
  adherenceWord: 'laikymasis',
  doneN: (n) => `atlikta: ${n}`,
  missedN: (n) => `praleista: ${n}`,
  toGoN: (n) => `liko: ${n}`,
  endsOn: (x) => `Baigiasi ${x}`,
  missedL: 'Praleista',
  thisWeekL: 'Ši savaitė',
  thisWeek: 'Ši savaitė',
  rest: 'Poilsis',
  recover: 'atsigavimas',
  planWeek: 'Suplanuok savaitę',
  planWeekSub: 'Programa arba kelios treniruotės ją užpildys',
  doneOfN: (a, b) => `${a} iš ${b} atlikta`,
  nextX: (x) => `Toliau: ${x}`,
  nextWeekStarts: (x) => `Kita savaitė prasideda ${x}`,
  usualTime: 'Įprastas laikas',
  timeLast60: 'Treniruočių laikas · 60 d.',
  usualStart: 'įprasta pradžia',
  usuallyAt: (x) => `Paprastai treniruojiesi ${x}`,
  learningTime: 'Mokomės tavo ritmo',
  learningTimeSub: 'Užrašyk kelias treniruotes ir pamatysi įprastą laiką',
  doneToday: 'Šiandien atlikta',
  inX: (x) => `po ${x}`,
  nowTime: 'Pats laikas',
  laterToday: 'Šiandien vėliau nei įprastai',
  fromN: (n) => `iš ${n} treniruočių`,
  weekend: 'savaitgalis',
  startNow: 'Pradėti dabar',
  quickRest: 'Greitas poilsis',
  quickRestSub: 'Pasirink nustatymą ir pradėk',
  readyNext: 'Pasiruošęs kitai serijai',
  ofX: (x) => `iš ${x}`,
  restRunning: 'Poilsis · vyksta',
  restOver: 'Poilsis baigėsi',
  restK: (x) => `Poilsis · ${x}`,
  skip: 'Praleisti',
  skipRest: 'Toliau',
  setN: (x) => `serija ${x}`,
  lastSetX: (x) => `Paskutinė: ${x}`,
  upNext: (x) => `Toliau · ${x}`,
  prN: (n) => `${n} PR`,
  pr: 'PR',
  timeL: 'laikas',
  volumeL: 'apimtis',
  setsL: 'serijos',
  prsL: 'rekordai',
  worked: 'Dirbo',
  workedWhen: (x) => `Dirbo · ${x}`,
  plusSecondary: (n) => `+${n} pagalbiniai`,
  setsGroups: (a, b) => `${a} serijų · ${b} raumenų grupės`,
  lastWorkout: 'Paskutinė treniruotė',
  needWeight: 'Pridėk savo svorį',
  needWeightSub: 'Energija vertinama pagal kūno svorį',
  logWeight: 'Užrašyti svorį',
  perMin: (x) => `${x} kcal/min`,
  energyK: (x) => `Treniruotės energija · ${x}`,
  vsAvg: (x) => `${x} lyginant su vidurkiu`,
  lastNAvg: (n, avg) => `paskutinės ${n} · vid. ${avg}`,
  weekKcal: (k, n) => `Šią savaitę ${k} kcal · treniruočių: ${n}`,
  effortK: 'Pastangos · RPE',
  noRpe: 'Pastangų duomenų dar nėra',
  noRpeSub: 'Įvertink kelias serijas (RPE), kad matytum tendenciją',
  zone: (x) => `zona ${x}`,
  inZone: 'zonoje',
  belowZone: 'žemiau zonos',
  aboveZone: 'virš zonos',
  adviceLow: 'Yra rezervo paspausti',
  adviceHigh: 'Per karšta — apsvarstyk lengvesnę savaitę',
  adviceZone: 'Tiksliai zonoje — taip ir toliau',
  avgRpe: (x) => `Vid. RPE ${x}`,
  avgRpeUnit: 'vid. RPE',
  avg: 'vid.',
  lastNSessions: (n) => `paskutinės ${n} treniruotės`,
  effortLast: (n) => `Pastangos · paskutinės ${n}`,
  inZoneN: (a, b) => `${a}/${b} zonoje`,
  progress: 'Progresas',
  avgSession: 'Vid. treniruotė',
  noRecent: 'Per 30 dienų nieko',
  vsPrev: (x) => `${x} lyginant su ankstesnėmis 30 d.`,
  avgPer: (x) => `Vidutiniškai ${x} treniruotei`,
  days30: '30 dienų',
  lengthLast: (n) => `Trukmė · paskutinės ${n}`,
  length30: 'Trukmė · 30 dienų',
  history: 'Istorija',
  avgLongest: (x) => `vid. ${x} · ilgiausia`,
  avgX: (x) => `vid. ${x}`,
  noHome: 'Namų rinkinių dar nėra',
  noHomeSub: 'Išsaugok šabloną ir pradėk vienu paspaudimu',
  newTemplate: 'Naujas šablonas',
  homeN: (n) => `Namų rinkiniai · šablonų: ${n}`,
  lastX: (x) => `paskutinį kartą: ${x}`,
  weekTimes: (n) => `${n}× šią savaitę`,
  noGym: 'Salės nereikia · skaičiuojama į seriją',
  reps: 'kart.',
  vsLast: (x) => `${x} lyginant su praeitu kartu`,
};

const et: PlanStrings = {
  names: {
    next: 'Järgmine trenn',
    builder: 'Kiire trenni koostaja',
    warmup: 'Soojendus',
    program: 'Programmi edenemine',
    week: 'Nädala plaan',
    time: 'Trenni aeg',
    rest: 'Puhkuse taimer',
    last: 'Viimane trenn',
    muscles: 'Viimase trenni lihased',
    energy: 'Trenni energia',
    effort: 'Pingutuse trend',
    length: 'Trenni pikkus',
    home: 'Kodused kavad',
  },
  today: 'täna',
  tomorrow: 'homme',
  yesterday: 'eile',
  todayCap: 'Täna',
  minN: (n) => `${n} min`,
  lastKg: (kg) => `viimati ${kg} kg`,
  setsN: (n) => `seeriaid: ${n}`,
  sessionsN: (n) => `trenne: ${n}`,
  start: 'Alusta',
  summary: 'Kokkuvõte',
  noSession: 'Trenne veel pole',
  noSessionSub: 'Logi esimene trenn, et seda siin näha',
  nextUp: 'Järgmisena',
  noPlan: 'Trenni pole planeeritud',
  noPlanSub: 'Vali programm või logi paar trenni',
  buildOne: 'Koosta trenn',
  exercisesN: (n) => `harjutusi: ${n}`,
  dayOf: (a, b) => `Päev ${a}/${b}`,
  nextOf: (p) => `Järgmine trenn · ${p}`,
  nextWeek: (w) => `Järgmine trenn · nädal ${w}`,
  lastDone: (x) => `Viimati ${x}`,
  quick: 'Kiire trenn',
  buildMe: 'Koosta mulle trenn',
  build: 'Koosta',
  generate: 'Genereeri',
  regenerate: 'Teine variant',
  lengthL: 'Trenni pikkus',
  aboutEx: (n) => `~${n} harjutust`,
  startMin: (n) => `Alusta · ${n} min`,
  focus: {
    auto: 'Auto',
    upper: 'Ülakeha',
    push: 'Surumine',
    pull: 'Tõmme',
    legs: 'Jalad',
    full: 'Kogu keha',
  },
  warmupFor: (x) => `Soojendus · ${x}`,
  rampTo: (n, kg) => `${n} soojendusseeriat → ${kg}`,
  noRamp: 'Kerge harjutus — piisab liikuvusest',
  plusMobility: '+ liikuvus',
  mobilityMin: (n) => `Liikuvus · ${n} min`,
  bar: 'Kang',
  work: (kg) => `töö ${kg}`,
  working: (kg) => `Tööraskus ${kg}`,
  startSession: 'Alusta trenni',
  mobUpper: [
    'Käteringid 30 s',
    'Kummi venitus ×15',
    'Rinnaku rotatsioon ×8',
    'Abaluude surumine ×10',
  ],
  mobLower: ['Jalahood ×10', 'Puusaringid ×8', 'Pokaalkükk 30 s', 'Hüppeliigese kallutused ×10'],
  noProgram: 'Programmi veel pole',
  noProgramSub: 'Määra või koosta see, et nädalaid jälgida',
  openPrograms: 'Programmid',
  openProgram: 'Ava programm',
  programK: (p) => `Programm · ${p}`,
  weekN: (n) => `Nädal ${n}`,
  weekOf: (a, b) => `Nädal ${a}/${b}`,
  weekShort: 'nädal',
  ofWeeks: (n) => `${n} nädalast`,
  ofN: (n) => `/ ${n}`,
  ofSessions: (n) => `/ ${n} trennist`,
  doneOf: (a, b) => `${a}/${b} trenni`,
  adherence: (p) => `${p}% järgimine`,
  adherenceWord: 'järgimine',
  doneN: (n) => `tehtud: ${n}`,
  missedN: (n) => `vahele jäänud: ${n}`,
  toGoN: (n) => `jäänud: ${n}`,
  endsOn: (x) => `Lõpeb ${x}`,
  missedL: 'Vahele jäänud',
  thisWeekL: 'See nädal',
  thisWeek: 'See nädal',
  rest: 'Puhkus',
  recover: 'taastumine',
  planWeek: 'Planeeri nädal',
  planWeekSub: 'Programm või paar trenni täidavad selle',
  doneOfN: (a, b) => `${a}/${b} tehtud`,
  nextX: (x) => `Järgmine: ${x}`,
  nextWeekStarts: (x) => `Järgmine nädal algab ${x}`,
  usualTime: 'Tavaline aeg',
  timeLast60: 'Trenni aeg · 60 päeva',
  usualStart: 'tavaline algus',
  usuallyAt: (x) => `Tavaliselt treenid kell ${x}`,
  learningTime: 'Õpime sinu rütmi',
  learningTimeSub: 'Logi paar trenni, et näha oma tavalist aega',
  doneToday: 'Täna tehtud',
  inX: (x) => `${x} pärast`,
  nowTime: 'Just praegu',
  laterToday: 'Täna tavalisest hiljem',
  fromN: (n) => `${n} trenni põhjal`,
  weekend: 'nädalavahetus',
  startNow: 'Alusta kohe',
  quickRest: 'Kiire puhkus',
  quickRestSub: 'Alustamiseks vali eelseade',
  readyNext: 'Valmis järgmiseks seeriaks',
  ofX: (x) => `/ ${x}`,
  restRunning: 'Puhkus · käib',
  restOver: 'Puhkus läbi',
  restK: (x) => `Puhkus · ${x}`,
  skip: 'Jäta vahele',
  skipRest: 'Edasi',
  setN: (x) => `seeria ${x}`,
  lastSetX: (x) => `Viimane: ${x}`,
  upNext: (x) => `Järgmisena · ${x}`,
  prN: (n) => `${n} PR`,
  pr: 'PR',
  timeL: 'aeg',
  volumeL: 'maht',
  setsL: 'seeriad',
  prsL: 'rekordid',
  worked: 'Töötasid',
  workedWhen: (x) => `Töötasid · ${x}`,
  plusSecondary: (n) => `+${n} abilihast`,
  setsGroups: (a, b) => `${a} seeriat · ${b} lihasgruppi`,
  lastWorkout: 'Viimane trenn',
  needWeight: 'Lisa oma kaal',
  needWeightSub: 'Energiat hinnatakse kehakaalu järgi',
  logWeight: 'Logi kaal',
  perMin: (x) => `${x} kcal/min`,
  energyK: (x) => `Trenni energia · ${x}`,
  vsAvg: (x) => `${x} vs keskmine`,
  lastNAvg: (n, avg) => `viimased ${n} · kesk. ${avg}`,
  weekKcal: (k, n) => `Sel nädalal ${k} kcal · trenne: ${n}`,
  effortK: 'Pingutus · RPE',
  noRpe: 'Pingutuse andmeid veel pole',
  noRpeSub: 'Hinda paari seeriat (RPE), et trendi näha',
  zone: (x) => `tsoon ${x}`,
  inZone: 'tsoonis',
  belowZone: 'alla tsooni',
  aboveZone: 'üle tsooni',
  adviceLow: 'Ruumi veidi rohkem pingutada',
  adviceHigh: 'Liiga kõvasti — kaalu kergemat nädalat',
  adviceZone: 'Täpselt tsoonis — jätka samamoodi',
  avgRpe: (x) => `Kesk. RPE ${x}`,
  avgRpeUnit: 'kesk. RPE',
  avg: 'kesk.',
  lastNSessions: (n) => `viimased ${n} trenni`,
  effortLast: (n) => `Pingutus · viimased ${n} trenni`,
  inZoneN: (a, b) => `${a}/${b} tsoonis`,
  progress: 'Areng',
  avgSession: 'Keskmine trenn',
  noRecent: 'Viimase 30 päeva jooksul midagi pole',
  vsPrev: (x) => `${x} vs eelmised 30 päeva`,
  avgPer: (x) => `Keskmiselt ${x} trenni kohta`,
  days30: '30 päeva',
  lengthLast: (n) => `Trenni pikkus · viimased ${n}`,
  length30: 'Trenni pikkus · 30 päeva',
  history: 'Ajalugu',
  avgLongest: (x) => `kesk. ${x} · pikim`,
  avgX: (x) => `kesk. ${x}`,
  noHome: 'Koduseid kavasid veel pole',
  noHomeSub: 'Salvesta mall, et alustada ühe puutega',
  newTemplate: 'Uus mall',
  homeN: (n) => `Kodused kavad · malle: ${n}`,
  lastX: (x) => `viimati: ${x}`,
  weekTimes: (n) => `${n}× sel nädalal`,
  noGym: 'Saali pole vaja · läheb seeriasse arvesse',
  reps: 'korda',
  vsLast: (x) => `${x} vs eelmine kord`,
};

const DICT: Record<LocaleId, PlanStrings> = { en, uk, pl, lt, et };

export function ps(locale: LocaleId): PlanStrings {
  return DICT[locale];
}
