/**
 * Copy of the Strength widgets (board L6), all five locales. Typed: a missing
 * key in any locale fails the build. Muscle / rank names come from the main
 * dictionary (t.muscleGroups, t.rankShort).
 */
import type { LocaleId } from '../../i18n';

type Lifts = { squat: string; bench: string; deadlift: string; ohp: string };

const en = {
  liftShort: { squat: 'S', bench: 'B', deadlift: 'D', ohp: 'OHP' } as Lifts,
  liftName: { squat: 'Squat', bench: 'Bench', deadlift: 'Deadlift', ohp: 'OHP' } as Lifts,
  weeks: (n: number) => `${n} weeks`,
  reps: 'reps',
  weight: 'Weight',
  save: 'Save',
  start: 'Start',
  today: 'today',
  openTrends: 'Open trends',
  logWeight: 'Log weight',
  e1rm: 'e1RM',
  // Top lifts
  topLifts: 'Top lifts',
  topLifts4: 'Top lifts · 4 wk',
  topLiftsE1: 'Top lifts · e1RM',
  ofUp: (n: number) => `of ${n} up`,
  upCount: (n: number) => `${n} ↑`,
  big3: (x: string) => `Big-3 total ${x} kg`,
  allLifts: 'All lifts',
  topLiftsEmpty: 'No main lifts yet',
  topLiftsEmptySub: 'Log squat, bench, deadlift or OHP',
  // Next target
  nextTarget: 'Next target',
  nextKicker: (d: string) => `Next · ${d}`,
  nextTargetKicker: (d: string) => `Next target · ${d}`,
  nextTargetsKicker: (d: string) => `Next targets · ${d}`,
  dayToday: (d: string) => `${d} today`,
  lastSession: 'Last session',
  repeat: 'Repeat',
  setsX: (n: number) => `× ${n} sets`,
  lastLine: (x: string) => `Last: ${x}`,
  firstTimeHint: (lo: number, hi: number) => `First time — aim for ${lo}–${hi} reps`,
  plusRep: '+1 rep',
  deload: 'deload',
  firstTime: 'first time',
  hold: 'hold',
  progressionNote:
    'Double progression: hit the top of the rep range on all sets → add weight next time.',
  startDay: (d: string) => `Start ${d}`,
  nextEmpty: 'No lifts to target yet',
  nextEmptySub: 'Log a session or pick a program',
  // PR forecast
  prForecast: 'PR forecast',
  prForecastOf: (l: string) => `PR forecast · ${l}`,
  prBy: (l: string, kg: string, d: string) => `${l} ${kg} kg by ${d}`,
  reachedLine: (l: string, kg: string) => `${l} ${kg} kg reached`,
  noEtaLine: (l: string, kg: string) => `${l} → ${kg} kg: no ETA yet`,
  perWeek: (x: string) => `${x} kg / week`,
  now: (x: string) => `${x} now`,
  inWeeks: (n: number) => `in ~${n} wk`,
  atPace: (kg: string, d: string) => `At this pace: ${kg} kg by ${d}`,
  targetLabel: (kg: string) => `${kg} target`,
  byDate: (d: string) => `by ${d}`,
  nowPerWk: (now: string, sl: string) => `${now} now · ${sl} / wk`,
  noEta: 'no ETA',
  reached: 'reached',
  changeTargets: 'Change targets',
  targetsTitle: 'Target e1RM',
  targetsHint: 'The forecast shows when your current pace reaches these.',
  prEmpty: 'Not enough history yet',
  prEmptySub: '3+ sessions of a main lift in 12 weeks',
  // Recent PRs
  recentPrs: 'Recent PRs',
  thisMonthUnit: 'this month',
  prsThisMonth: (n: number) => `${n} this month`,
  latest: (x: string) => `Latest: ${x}`,
  prLabel: (x: string) => `PR: ${x}`,
  moreThisMonth: (n: number) => `${n} more this month`,
  plusReps: (n: number) => `+${n} rep${n === 1 ? '' : 's'}`,
  repsAtWeight: 'reps at weight',
  allRecords: 'All records',
  prsEmpty: 'No PRs yet',
  prsEmptySub: 'Beat a previous best and it shows here',
  // 1RM
  oneRm: '1RM calculator',
  est1rm: 'Est. 1RM',
  fromSet: (set: string, l: string) => `from ${set} · ${l}`,
  fromLast: (l: string) => `est. 1RM · from last ${l} set`,
  estimated: 'Estimated 1RM',
  epley: 'Epley',
  upTo10: 'Use 1–10 reps',
  oneRmEmpty: 'Enter a set to estimate',
  tapToEdit: 'Weight × reps → your 1RM',
  enterSet: 'Enter a set',
  // Plates
  plates: 'Plates',
  plateCalc: 'Plate calculator',
  platesPerSide: 'Plates · per side',
  perSide: (x: string) => `per side ${x}`,
  bar20: 'per side · 20 kg bar',
  barPerSide: 'Bar 20 kg · per side',
  barOnly: 'Bar only',
  warmup: (p: number) => `Warm-up ${p}%`,
  topSet: 'Top set',
  closest: (x: string) => `closest to ${x}`,
  // Balance
  balance: 'Strength balance',
  balanceVsDl: 'Balance · vs deadlift',
  typical: 'typical',
  lags: (l: string) => `${l} lags`,
  lagsBy: (l: string, kg: string) => `${l} lags by ~${kg} kg`,
  vsTypical: (x: string) => `vs typical for DL ${x}`,
  balanced: 'Balanced',
  balancedSub: 'Close to typical proportions',
  ratioSub: (typ: string) => `Squat : Bench : Deadlift · typical ${typ}`,
  e1rm12: 'e1RM · best',
  you: 'You',
  typicalFor: 'Typical for your strongest lift',
  lagNote: (l: string, kg: string) => `${l} is ~${kg} kg under typical proportions.`,
  tierNote: (l: string, s: string) => `By class it sits a full tier behind ${s} (${l}).`,
  balanceEmpty: 'Needs squat, bench & deadlift',
  balanceEmptySub: 'Log all three to compare',
  // Standards
  standards: 'Standards',
  cls: (x: string) => `Class ${x}`,
  classKicker: (c: string) => `Class · ${c} kg`,
  stdKickerL: (c: string) => `Standards · ${c} kg · total`,
  stdKickerXL: (c: string) => `Standards · ${c} kg category`,
  cat: (c: string) => `${c} kg cat.`,
  toNext: (kg: string, x: string) => `${kg} kg to ${x}`,
  toGo: (x: string) => `+${x} to go`,
  totalLine: (x: string) => `total ${x}`,
  kgTotal: (x: string) => `${x} kg total`,
  rawTotal: 'raw total',
  youMark: ' · you',
  topRank: 'Top class reached',
  openStandards: 'Open standards',
  stdNeedWeight: 'Add a weigh-in',
  stdNeedWeightSub: 'Classes depend on bodyweight',
  stdEmpty: 'No total yet',
  // Powerlifting total
  plTotal: 'Powerlifting total',
  total: 'Total',
  totalKg: (x: string) => `Total ${x} kg`,
  days30: (x: string) => `${x} · 30 d`,
  since: (x: string, d: string) => `${x} since ${d}`,
  clsTo: (c: string, kg: string, n: string) => `Class ${c} · ${kg} kg to Class ${n}`,
  viewProgress: 'View progress',
  // Relative strength
  relStrength: 'Relative strength',
  xBw: (l: string) => `${l} × BW`,
  bwKicker: (bw: string) => `× bodyweight · ${bw} kg`,
  scale: (x: string) => `scale 0 – ${x}×`,
  bwTimes: (l: string, r: string) => `${l} ${r}× bodyweight`,
  nextMilestone: 'next milestone',
  totalBw: (x: string) => `total ${x} ÷ BW`,
  closestMilestone: 'Closest milestone',
  milestone: (l: string, r: string, kg: string) => `${l} ${r}× = ${kg} kg`,
  toGoLabel: 'To go',
  in30: 'in 30 d',
  relEmpty: 'Log a weigh-in',
  relEmptySub: 'Lifts are shown as × bodyweight',
  // Rep PRs
  repPrs: 'Rep PRs',
  repPrOf: (l: string) => `Rep PR · ${l}`,
  repPrsOf: (l: string) => `Rep PRs · ${l}`,
  repsUnit: 'reps',
  atKg: (kg: string, d: string) => `@ ${kg} kg · ${d}`,
  repTitle: (l: string, kg: string, n: number) => `${l} @ ${kg} kg: ${n} reps`,
  bestSet: (d: string) => `Latest rep record · ${d}`,
  bestReps: 'best reps',
  chances: 'Next rep PR at your heaviest weights',
  bestOn: (n: number, d: string) => `best ${n} · ${d}`,
  isPr: (n: number) => `${n} = PR`,
  exerciseHistory: 'Exercise history',
  repEmpty: 'No rep records yet',
  // Stalled
  stalled: 'Stalled lifts',
  stalledK: 'Stalled',
  lifts: 'lifts',
  stalledN: (n: number) => (n === 1 ? '1 lift stalled' : `${n} lifts stalled`),
  sessionsAt: (n: number, set: string) => `${n} sessions at ${set}`,
  sessionsDot: (n: number, set: string) => `${n} sessions · ${set}`,
  stuckAt: (n: number, set: string) => `${n} sessions · stuck at ${set}`,
  noGain: 'no e1RM gain',
  deloadTo: (set: string) => `Deload 10% → ${set}, build back up`,
  swapTo: (x: string) => `Swap → ${x}`,
  deloadShort: 'Deload 10%',
  swapShort: 'Swap',
  watching: (l: string, n: number) => `Watching: ${l} · ${n} sessions`,
  stalledHint: 'Flat top weight for 3+ sessions',
  noStalls: 'No stalls',
  noStallsSub: 'Every lift is still moving',
  // Smart swap
  smartSwap: 'Smart swap',
  swapOf: (l: string) => `Swap · ${l}`,
  swapKicker: (g: string) => `Smart swap · ${g}`,
  busy: (a: string, b: string) => `${a} busy? ${b}`,
  sameMuscles: (p: number) => `${p}% same muscles`,
  pctMatch: (p: number) => `${p}% match`,
  match: 'match',
  replacing: 'Replacing',
  swap: 'Swap',
  view: 'View',
  liveNow: 'now',
  atGym: (g: string) => `at ${g}`,
  available: 'available here',
  needs: (x: string) => `needs ${x}`,
  anyGym: 'any gym',
  swapEmpty: 'Nothing to swap yet',
  swapEmptySub: 'Plan or start a session',
};

export type StrengthStrings = typeof en;

const uk: StrengthStrings = {
  liftShort: { squat: 'П', bench: 'Ж', deadlift: 'Т', ohp: 'ЖС' },
  liftName: { squat: 'Присід', bench: 'Жим', deadlift: 'Тяга', ohp: 'Жим стоячи' },
  weeks: (n) => `${n} тиж.`,
  reps: 'повт.',
  weight: 'Вага',
  save: 'Зберегти',
  start: 'Почати',
  today: 'сьогодні',
  openTrends: 'Відкрити тренди',
  logWeight: 'Записати вагу',
  e1rm: 'e1RM',
  topLifts: 'Топ-вправи',
  topLifts4: 'Топ-вправи · 4 тиж.',
  topLiftsE1: 'Топ-вправи · e1RM',
  ofUp: (n) => `з ${n} ростуть`,
  upCount: (n) => `${n} ↑`,
  big3: (x) => `Сума трьох ${x} кг`,
  allLifts: 'Усі вправи',
  topLiftsEmpty: 'Ще немає основних вправ',
  topLiftsEmptySub: 'Запиши присід, жим, тягу чи жим стоячи',
  nextTarget: 'Наступна ціль',
  nextKicker: (d) => `Далі · ${d}`,
  nextTargetKicker: (d) => `Наступна ціль · ${d}`,
  nextTargetsKicker: (d) => `Наступні цілі · ${d}`,
  dayToday: (d) => `${d} сьогодні`,
  lastSession: 'Минула сесія',
  repeat: 'Повтор',
  setsX: (n) => `× ${n} підх.`,
  lastLine: (x) => `Минулого разу: ${x}`,
  firstTimeHint: (lo, hi) => `Уперше — цілься в ${lo}–${hi} повторів`,
  plusRep: '+1 повт.',
  deload: 'розвантаж.',
  firstTime: 'уперше',
  hold: 'тримай',
  progressionNote:
    'Подвійна прогресія: виконав верх діапазону в усіх підходах → наступного разу додай вагу.',
  startDay: (d) => `Почати ${d}`,
  nextEmpty: 'Ще немає цілей',
  nextEmptySub: 'Запиши сесію або обери програму',
  prForecast: 'Прогноз рекорду',
  prForecastOf: (l) => `Прогноз · ${l}`,
  prBy: (l, kg, d) => `${l} ${kg} кг до ${d}`,
  reachedLine: (l, kg) => `${l} ${kg} кг досягнуто`,
  noEtaLine: (l, kg) => `${l} → ${kg} кг: поки без дати`,
  perWeek: (x) => `${x} кг / тиж.`,
  now: (x) => `зараз ${x}`,
  inWeeks: (n) => `за ~${n} тиж.`,
  atPace: (kg, d) => `У цьому темпі: ${kg} кг до ${d}`,
  targetLabel: (kg) => `ціль ${kg}`,
  byDate: (d) => `до ${d}`,
  nowPerWk: (now, sl) => `зараз ${now} · ${sl} / тиж.`,
  noEta: 'без дати',
  reached: 'досягнуто',
  changeTargets: 'Змінити цілі',
  targetsTitle: 'Цільовий e1RM',
  targetsHint: 'Прогноз покаже, коли поточний темп їх досягне.',
  prEmpty: 'Замало історії',
  prEmptySub: '3+ сесії основної вправи за 12 тижнів',
  recentPrs: 'Свіжі рекорди',
  thisMonthUnit: 'цього місяця',
  prsThisMonth: (n) => `${n} цього місяця`,
  latest: (x) => `Останній: ${x}`,
  prLabel: (x) => `Рекорд: ${x}`,
  moreThisMonth: (n) => `ще ${n} цього місяця`,
  plusReps: (n) => `+${n} повт.`,
  repsAtWeight: 'повтори на вазі',
  allRecords: 'Усі рекорди',
  prsEmpty: 'Ще немає рекордів',
  prsEmptySub: 'Побий попередній найкращий результат — і він з’явиться тут',
  oneRm: 'Калькулятор 1ПМ',
  est1rm: 'Оцінка 1ПМ',
  fromSet: (set, l) => `з ${set} · ${l}`,
  fromLast: (l) => `оцінка 1ПМ · з останнього підходу: ${l}`,
  estimated: 'Оцінка 1ПМ',
  epley: 'Еплі',
  upTo10: '1–10 повторів',
  oneRmEmpty: 'Введи підхід для оцінки',
  tapToEdit: 'Вага × повтори → твій 1ПМ',
  enterSet: 'Ввести підхід',
  plates: 'Млинці',
  plateCalc: 'Калькулятор млинців',
  platesPerSide: 'Млинці · на бік',
  perSide: (x) => `на бік ${x}`,
  bar20: 'на бік · гриф 20 кг',
  barPerSide: 'Гриф 20 кг · на бік',
  barOnly: 'Лише гриф',
  warmup: (p) => `Розминка ${p}%`,
  topSet: 'Робочий',
  closest: (x) => `найближче до ${x}`,
  balance: 'Баланс сили',
  balanceVsDl: 'Баланс · до тяги',
  typical: 'типово',
  lags: (l) => `${l} відстає`,
  lagsBy: (l, kg) => `${l} відстає на ~${kg} кг`,
  vsTypical: (x) => `від типового для тяги ${x}`,
  balanced: 'Збалансовано',
  balancedSub: 'Близько до типових пропорцій',
  ratioSub: (typ) => `Присід : Жим : Тяга · типово ${typ}`,
  e1rm12: 'e1RM · найкращі',
  you: 'Ти',
  typicalFor: 'Типово для найсильнішої вправи',
  lagNote: (l, kg) => `${l}: ~${kg} кг нижче типових пропорцій.`,
  tierNote: (l, s) => `За розрядами — цілий щабель позаду: ${s} (${l}).`,
  balanceEmpty: 'Потрібні присід, жим і тяга',
  balanceEmptySub: 'Запиши всі три, щоб порівняти',
  standards: 'Нормативи',
  cls: (x) => `Розряд ${x}`,
  classKicker: (c) => `Розряд · ${c} кг`,
  stdKickerL: (c) => `Нормативи · ${c} кг · сума`,
  stdKickerXL: (c) => `Нормативи · категорія ${c} кг`,
  cat: (c) => `кат. ${c} кг`,
  toNext: (kg, x) => `${kg} кг до: ${x}`,
  toGo: (x) => `ще +${x}`,
  totalLine: (x) => `сума ${x}`,
  kgTotal: (x) => `сума ${x} кг`,
  rawTotal: 'сума без екіпіровки',
  youMark: ' · ти',
  topRank: 'Найвищий розряд',
  openStandards: 'Відкрити нормативи',
  stdNeedWeight: 'Додай зважування',
  stdNeedWeightSub: 'Розряди залежать від ваги тіла',
  stdEmpty: 'Ще немає суми',
  plTotal: 'Сума троєборства',
  total: 'Сума',
  totalKg: (x) => `Сума ${x} кг`,
  days30: (x) => `${x} · 30 дн.`,
  since: (x, d) => `${x} з ${d}`,
  clsTo: (c, kg, n) => `Розряд ${c} · ${kg} кг до ${n}`,
  viewProgress: 'Прогрес',
  relStrength: 'Відносна сила',
  xBw: (l) => `${l} × вага тіла`,
  bwKicker: (bw) => `× вага тіла · ${bw} кг`,
  scale: (x) => `шкала 0 – ${x}×`,
  bwTimes: (l, r) => `${l} ${r}× ваги тіла`,
  nextMilestone: 'наступна віха',
  totalBw: (x) => `сума ${x} ÷ вага`,
  closestMilestone: 'Найближча віха',
  milestone: (l, r, kg) => `${l} ${r}× = ${kg} кг`,
  toGoLabel: 'Залишилось',
  in30: 'за 30 дн.',
  relEmpty: 'Запиши вагу тіла',
  relEmptySub: 'Вправи показуються як × вага тіла',
  repPrs: 'Рекорди повторів',
  repPrOf: (l) => `Рекорд повторів · ${l}`,
  repPrsOf: (l) => `Рекорди повторів · ${l}`,
  repsUnit: 'повт.',
  atKg: (kg, d) => `@ ${kg} кг · ${d}`,
  repTitle: (l, kg, n) => `${l} @ ${kg} кг: ${n} повт.`,
  bestSet: (d) => `Останній рекорд повторів · ${d}`,
  bestReps: 'найбільше повторів',
  chances: 'Наступний рекорд на найбільших вагах',
  bestOn: (n, d) => `рекорд ${n} · ${d}`,
  isPr: (n) => `${n} = рекорд`,
  exerciseHistory: 'Історія вправи',
  repEmpty: 'Ще немає рекордів повторів',
  stalled: 'Застій',
  stalledK: 'Застій',
  lifts: 'вправ',
  stalledN: (n) => `Застій: ${n}`,
  sessionsAt: (n, set) => `${n} сесій на ${set}`,
  sessionsDot: (n, set) => `${n} сесій · ${set}`,
  stuckAt: (n, set) => `${n} сесій · застряг на ${set}`,
  noGain: 'без росту e1RM',
  deloadTo: (set) => `Розвантаж 10% → ${set}, далі нарощуй`,
  swapTo: (x) => `Заміна → ${x}`,
  deloadShort: 'Мінус 10%',
  swapShort: 'Замінити',
  watching: (l, n) => `Під наглядом: ${l} · ${n} сесії`,
  stalledHint: 'Робоча вага стоїть 3+ сесії',
  noStalls: 'Застою немає',
  noStallsSub: 'Усі вправи ростуть',
  smartSwap: 'Розумна заміна',
  swapOf: (l) => `Заміна · ${l}`,
  swapKicker: (g) => `Розумна заміна · ${g}`,
  busy: (a, b) => `${a} зайнято? ${b}`,
  sameMuscles: (p) => `${p}% ті самі м’язи`,
  pctMatch: (p) => `${p}% збіг`,
  match: 'збіг',
  replacing: 'Замість',
  swap: 'Замінити',
  view: 'Переглянути',
  liveNow: 'зараз',
  atGym: (g) => `у ${g}`,
  available: 'є в залі',
  needs: (x) => `потрібно: ${x}`,
  anyGym: 'будь-який зал',
  swapEmpty: 'Поки нічого замінювати',
  swapEmptySub: 'Сплануй або почни сесію',
};

const pl: StrengthStrings = {
  liftShort: { squat: 'P', bench: 'W', deadlift: 'M', ohp: 'OHP' },
  liftName: { squat: 'Przysiad', bench: 'Wyciskanie', deadlift: 'Martwy ciąg', ohp: 'OHP' },
  weeks: (n) => `${n} tyg.`,
  reps: 'powt.',
  weight: 'Ciężar',
  save: 'Zapisz',
  start: 'Start',
  today: 'dziś',
  openTrends: 'Otwórz trendy',
  logWeight: 'Zapisz wagę',
  e1rm: 'e1RM',
  topLifts: 'Główne boje',
  topLifts4: 'Główne boje · 4 tyg.',
  topLiftsE1: 'Główne boje · e1RM',
  ofUp: (n) => `z ${n} w górę`,
  upCount: (n) => `${n} ↑`,
  big3: (x) => `Suma trójboju ${x} kg`,
  allLifts: 'Wszystkie',
  topLiftsEmpty: 'Brak głównych bojów',
  topLiftsEmptySub: 'Zapisz przysiad, wyciskanie, martwy lub OHP',
  nextTarget: 'Następny cel',
  nextKicker: (d) => `Dalej · ${d}`,
  nextTargetKicker: (d) => `Następny cel · ${d}`,
  nextTargetsKicker: (d) => `Następne cele · ${d}`,
  dayToday: (d) => `${d} dziś`,
  lastSession: 'Ostatnia sesja',
  repeat: 'Powtórka',
  setsX: (n) => `× ${n} serie`,
  lastLine: (x) => `Ostatnio: ${x}`,
  firstTimeHint: (lo, hi) => `Pierwszy raz — celuj w ${lo}–${hi} powt.`,
  plusRep: '+1 powt.',
  deload: 'deload',
  firstTime: 'pierwszy raz',
  hold: 'utrzymaj',
  progressionNote:
    'Podwójna progresja: górny zakres powtórzeń we wszystkich seriach → następnym razem dodaj ciężar.',
  startDay: (d) => `Start: ${d}`,
  nextEmpty: 'Brak celów',
  nextEmptySub: 'Zapisz sesję lub wybierz program',
  prForecast: 'Prognoza rekordu',
  prForecastOf: (l) => `Prognoza · ${l}`,
  prBy: (l, kg, d) => `${l} ${kg} kg do ${d}`,
  reachedLine: (l, kg) => `${l} ${kg} kg osiągnięte`,
  noEtaLine: (l, kg) => `${l} → ${kg} kg: brak daty`,
  perWeek: (x) => `${x} kg / tydz.`,
  now: (x) => `teraz ${x}`,
  inWeeks: (n) => `za ~${n} tyg.`,
  atPace: (kg, d) => `W tym tempie: ${kg} kg do ${d}`,
  targetLabel: (kg) => `cel ${kg}`,
  byDate: (d) => `do ${d}`,
  nowPerWk: (now, sl) => `teraz ${now} · ${sl} / tydz.`,
  noEta: 'brak daty',
  reached: 'osiągnięte',
  changeTargets: 'Zmień cele',
  targetsTitle: 'Docelowy e1RM',
  targetsHint: 'Prognoza pokaże, kiedy obecne tempo je osiągnie.',
  prEmpty: 'Za mało historii',
  prEmptySub: '3+ sesje głównego boju w 12 tygodni',
  recentPrs: 'Ostatnie rekordy',
  thisMonthUnit: 'w tym mies.',
  prsThisMonth: (n) => `${n} w tym miesiącu`,
  latest: (x) => `Ostatni: ${x}`,
  prLabel: (x) => `Rekord: ${x}`,
  moreThisMonth: (n) => `jeszcze ${n} w tym mies.`,
  plusReps: (n) => `+${n} powt.`,
  repsAtWeight: 'powtórzenia na ciężarze',
  allRecords: 'Wszystkie rekordy',
  prsEmpty: 'Brak rekordów',
  prsEmptySub: 'Pobij poprzedni wynik, a pojawi się tutaj',
  oneRm: 'Kalkulator 1RM',
  est1rm: 'Szac. 1RM',
  fromSet: (set, l) => `z ${set} · ${l}`,
  fromLast: (l) => `szac. 1RM · z ostatniej serii: ${l}`,
  estimated: 'Szacowany 1RM',
  epley: 'Epley',
  upTo10: '1–10 powtórzeń',
  oneRmEmpty: 'Wpisz serię do oszacowania',
  tapToEdit: 'Ciężar × powtórzenia → twój 1RM',
  enterSet: 'Wpisz serię',
  plates: 'Talerze',
  plateCalc: 'Kalkulator talerzy',
  platesPerSide: 'Talerze · na stronę',
  perSide: (x) => `na stronę ${x}`,
  bar20: 'na stronę · gryf 20 kg',
  barPerSide: 'Gryf 20 kg · na stronę',
  barOnly: 'Sam gryf',
  warmup: (p) => `Rozgrzewka ${p}%`,
  topSet: 'Seria główna',
  closest: (x) => `najbliżej ${x}`,
  balance: 'Balans siły',
  balanceVsDl: 'Balans · do martwego',
  typical: 'typowo',
  lags: (l) => `${l} odstaje`,
  lagsBy: (l, kg) => `${l} odstaje o ~${kg} kg`,
  vsTypical: (x) => `od typowego dla MC ${x}`,
  balanced: 'Zbalansowane',
  balancedSub: 'Blisko typowych proporcji',
  ratioSub: (typ) => `Przysiad : Wyciskanie : Martwy · typowo ${typ}`,
  e1rm12: 'e1RM · najlepsze',
  you: 'Ty',
  typicalFor: 'Typowo dla najsilniejszego boju',
  lagNote: (l, kg) => `${l}: ~${kg} kg poniżej typowych proporcji.`,
  tierNote: (l, s) => `W klasach to cały stopień za: ${s} (${l}).`,
  balanceEmpty: 'Potrzebne przysiad, wyciskanie i martwy',
  balanceEmptySub: 'Zapisz wszystkie trzy, by porównać',
  standards: 'Normy',
  cls: (x) => `Klasa ${x}`,
  classKicker: (c) => `Klasa · ${c} kg`,
  stdKickerL: (c) => `Normy · ${c} kg · suma`,
  stdKickerXL: (c) => `Normy · kategoria ${c} kg`,
  cat: (c) => `kat. ${c} kg`,
  toNext: (kg, x) => `${kg} kg do: ${x}`,
  toGo: (x) => `jeszcze +${x}`,
  totalLine: (x) => `suma ${x}`,
  kgTotal: (x) => `suma ${x} kg`,
  rawTotal: 'suma raw',
  youMark: ' · ty',
  topRank: 'Najwyższa klasa',
  openStandards: 'Otwórz normy',
  stdNeedWeight: 'Dodaj ważenie',
  stdNeedWeightSub: 'Klasy zależą od masy ciała',
  stdEmpty: 'Brak sumy',
  plTotal: 'Suma trójboju',
  total: 'Suma',
  totalKg: (x) => `Suma ${x} kg`,
  days30: (x) => `${x} · 30 dni`,
  since: (x, d) => `${x} od ${d}`,
  clsTo: (c, kg, n) => `Klasa ${c} · ${kg} kg do ${n}`,
  viewProgress: 'Postęp',
  relStrength: 'Siła względna',
  xBw: (l) => `${l} × masa ciała`,
  bwKicker: (bw) => `× masa ciała · ${bw} kg`,
  scale: (x) => `skala 0 – ${x}×`,
  bwTimes: (l, r) => `${l} ${r}× masy ciała`,
  nextMilestone: 'następny próg',
  totalBw: (x) => `suma ${x} ÷ masa`,
  closestMilestone: 'Najbliższy próg',
  milestone: (l, r, kg) => `${l} ${r}× = ${kg} kg`,
  toGoLabel: 'Brakuje',
  in30: 'w 30 dni',
  relEmpty: 'Zapisz masę ciała',
  relEmptySub: 'Boje pokazane jako × masa ciała',
  repPrs: 'Rekordy powtórzeń',
  repPrOf: (l) => `Rekord powt. · ${l}`,
  repPrsOf: (l) => `Rekordy powt. · ${l}`,
  repsUnit: 'powt.',
  atKg: (kg, d) => `@ ${kg} kg · ${d}`,
  repTitle: (l, kg, n) => `${l} @ ${kg} kg: ${n} powt.`,
  bestSet: (d) => `Ostatni rekord powtórzeń · ${d}`,
  bestReps: 'najwięcej powt.',
  chances: 'Następny rekord na największych ciężarach',
  bestOn: (n, d) => `rekord ${n} · ${d}`,
  isPr: (n) => `${n} = rekord`,
  exerciseHistory: 'Historia ćwiczenia',
  repEmpty: 'Brak rekordów powtórzeń',
  stalled: 'Stagnacja',
  stalledK: 'Stagnacja',
  lifts: 'ćw.',
  stalledN: (n) => `Stagnacja: ${n}`,
  sessionsAt: (n, set) => `${n} sesji na ${set}`,
  sessionsDot: (n, set) => `${n} sesji · ${set}`,
  stuckAt: (n, set) => `${n} sesji · utknięte na ${set}`,
  noGain: 'bez wzrostu e1RM',
  deloadTo: (set) => `Deload 10% → ${set}, potem w górę`,
  swapTo: (x) => `Zamień → ${x}`,
  deloadShort: 'Deload 10%',
  swapShort: 'Zamień',
  watching: (l, n) => `Obserwuję: ${l} · ${n} sesje`,
  stalledHint: 'Ciężar stoi 3+ sesje',
  noStalls: 'Brak stagnacji',
  noStallsSub: 'Wszystkie boje idą w górę',
  smartSwap: 'Sprytna zamiana',
  swapOf: (l) => `Zamiana · ${l}`,
  swapKicker: (g) => `Sprytna zamiana · ${g}`,
  busy: (a, b) => `${a} zajęte? ${b}`,
  sameMuscles: (p) => `${p}% te same mięśnie`,
  pctMatch: (p) => `${p}% zgodności`,
  match: 'zgodność',
  replacing: 'Zamiast',
  swap: 'Zamień',
  view: 'Zobacz',
  liveNow: 'teraz',
  atGym: (g) => `w ${g}`,
  available: 'dostępne tutaj',
  needs: (x) => `wymaga: ${x}`,
  anyGym: 'dowolna siłownia',
  swapEmpty: 'Na razie nic do zamiany',
  swapEmptySub: 'Zaplanuj lub zacznij sesję',
};

const lt: StrengthStrings = {
  liftShort: { squat: 'P', bench: 'S', deadlift: 'T', ohp: 'OHP' },
  liftName: { squat: 'Pritūpimas', bench: 'Spaudimas', deadlift: 'Mirties trauka', ohp: 'OHP' },
  weeks: (n) => `${n} sav.`,
  reps: 'kart.',
  weight: 'Svoris',
  save: 'Išsaugoti',
  start: 'Pradėti',
  today: 'šiandien',
  openTrends: 'Atidaryti tendencijas',
  logWeight: 'Įrašyti svorį',
  e1rm: 'e1RM',
  topLifts: 'Pagrindiniai pratimai',
  topLifts4: 'Pagrindiniai · 4 sav.',
  topLiftsE1: 'Pagrindiniai · e1RM',
  ofUp: (n) => `iš ${n} kyla`,
  upCount: (n) => `${n} ↑`,
  big3: (x) => `Trikovės suma ${x} kg`,
  allLifts: 'Visi pratimai',
  topLiftsEmpty: 'Dar nėra pagrindinių pratimų',
  topLiftsEmptySub: 'Įrašyk pritūpimą, spaudimą, trauką ar OHP',
  nextTarget: 'Kitas tikslas',
  nextKicker: (d) => `Toliau · ${d}`,
  nextTargetKicker: (d) => `Kitas tikslas · ${d}`,
  nextTargetsKicker: (d) => `Kiti tikslai · ${d}`,
  dayToday: (d) => `${d} šiandien`,
  lastSession: 'Paskutinė sesija',
  repeat: 'Kartojimas',
  setsX: (n) => `× ${n} ser.`,
  lastLine: (x) => `Praėjusį kartą: ${x}`,
  firstTimeHint: (lo, hi) => `Pirmas kartas — siek ${lo}–${hi} kart.`,
  plusRep: '+1 kart.',
  deload: 'iškrova',
  firstTime: 'pirmas kartas',
  hold: 'išlaikyk',
  progressionNote:
    'Dviguba progresija: pasiekei viršutinę ribą visose serijose → kitą kartą pridėk svorio.',
  startDay: (d) => `Pradėti: ${d}`,
  nextEmpty: 'Dar nėra tikslų',
  nextEmptySub: 'Įrašyk sesiją arba pasirink programą',
  prForecast: 'Rekordo prognozė',
  prForecastOf: (l) => `Prognozė · ${l}`,
  prBy: (l, kg, d) => `${l} ${kg} kg iki ${d}`,
  reachedLine: (l, kg) => `${l} ${kg} kg pasiekta`,
  noEtaLine: (l, kg) => `${l} → ${kg} kg: datos dar nėra`,
  perWeek: (x) => `${x} kg / sav.`,
  now: (x) => `dabar ${x}`,
  inWeeks: (n) => `po ~${n} sav.`,
  atPace: (kg, d) => `Tokiu tempu: ${kg} kg iki ${d}`,
  targetLabel: (kg) => `tikslas ${kg}`,
  byDate: (d) => `iki ${d}`,
  nowPerWk: (now, sl) => `dabar ${now} · ${sl} / sav.`,
  noEta: 'be datos',
  reached: 'pasiekta',
  changeTargets: 'Keisti tikslus',
  targetsTitle: 'Tikslinis e1RM',
  targetsHint: 'Prognozė parodys, kada dabartiniu tempu juos pasieksi.',
  prEmpty: 'Per mažai istorijos',
  prEmptySub: '3+ pagrindinio pratimo sesijos per 12 savaičių',
  recentPrs: 'Nauji rekordai',
  thisMonthUnit: 'šį mėn.',
  prsThisMonth: (n) => `${n} šį mėnesį`,
  latest: (x) => `Naujausias: ${x}`,
  prLabel: (x) => `Rekordas: ${x}`,
  moreThisMonth: (n) => `dar ${n} šį mėn.`,
  plusReps: (n) => `+${n} kart.`,
  repsAtWeight: 'kartojimai su svoriu',
  allRecords: 'Visi rekordai',
  prsEmpty: 'Dar nėra rekordų',
  prsEmptySub: 'Pagerink ankstesnį rezultatą ir jis atsiras čia',
  oneRm: '1RM skaičiuoklė',
  est1rm: 'Įvert. 1RM',
  fromSet: (set, l) => `iš ${set} · ${l}`,
  fromLast: (l) => `įvert. 1RM · iš paskutinės serijos: ${l}`,
  estimated: 'Įvertintas 1RM',
  epley: 'Epley',
  upTo10: '1–10 kartojimų',
  oneRmEmpty: 'Įvesk seriją įvertinimui',
  tapToEdit: 'Svoris × kartojimai → tavo 1RM',
  enterSet: 'Įvesti seriją',
  plates: 'Diskai',
  plateCalc: 'Diskų skaičiuoklė',
  platesPerSide: 'Diskai · vienai pusei',
  perSide: (x) => `pusei ${x}`,
  bar20: 'pusei · 20 kg grifas',
  barPerSide: 'Grifas 20 kg · pusei',
  barOnly: 'Tik grifas',
  warmup: (p) => `Apšilimas ${p}%`,
  topSet: 'Darbinė serija',
  closest: (x) => `arčiausiai ${x}`,
  balance: 'Jėgos balansas',
  balanceVsDl: 'Balansas · su trauka',
  typical: 'įprasta',
  lags: (l) => `${l} atsilieka`,
  lagsBy: (l, kg) => `${l} atsilieka ~${kg} kg`,
  vsTypical: (x) => `nuo įprasto traukai ${x}`,
  balanced: 'Subalansuota',
  balancedSub: 'Arti įprastų proporcijų',
  ratioSub: (typ) => `Pritūpimas : Spaudimas : Trauka · įprasta ${typ}`,
  e1rm12: 'e1RM · geriausi',
  you: 'Tu',
  typicalFor: 'Įprasta stipriausiam pratimui',
  lagNote: (l, kg) => `${l}: ~${kg} kg žemiau įprastų proporcijų.`,
  tierNote: (l, s) => `Pagal atskyrius — visa pakopa už: ${s} (${l}).`,
  balanceEmpty: 'Reikia pritūpimo, spaudimo ir traukos',
  balanceEmptySub: 'Įrašyk visus tris palyginimui',
  standards: 'Normatyvai',
  cls: (x) => `Atskyris ${x}`,
  classKicker: (c) => `Atskyris · ${c} kg`,
  stdKickerL: (c) => `Normatyvai · ${c} kg · suma`,
  stdKickerXL: (c) => `Normatyvai · ${c} kg kategorija`,
  cat: (c) => `${c} kg kat.`,
  toNext: (kg, x) => `${kg} kg iki: ${x}`,
  toGo: (x) => `dar +${x}`,
  totalLine: (x) => `suma ${x}`,
  kgTotal: (x) => `suma ${x} kg`,
  rawTotal: 'raw suma',
  youMark: ' · tu',
  topRank: 'Aukščiausias atskyris',
  openStandards: 'Atidaryti normatyvus',
  stdNeedWeight: 'Pridėk svėrimą',
  stdNeedWeightSub: 'Atskyriai priklauso nuo kūno svorio',
  stdEmpty: 'Dar nėra sumos',
  plTotal: 'Trikovės suma',
  total: 'Suma',
  totalKg: (x) => `Suma ${x} kg`,
  days30: (x) => `${x} · 30 d.`,
  since: (x, d) => `${x} nuo ${d}`,
  clsTo: (c, kg, n) => `Atskyris ${c} · ${kg} kg iki ${n}`,
  viewProgress: 'Progresas',
  relStrength: 'Santykinė jėga',
  xBw: (l) => `${l} × kūno svoris`,
  bwKicker: (bw) => `× kūno svoris · ${bw} kg`,
  scale: (x) => `skalė 0 – ${x}×`,
  bwTimes: (l, r) => `${l} ${r}× kūno svorio`,
  nextMilestone: 'kitas etapas',
  totalBw: (x) => `suma ${x} ÷ svoris`,
  closestMilestone: 'Artimiausias etapas',
  milestone: (l, r, kg) => `${l} ${r}× = ${kg} kg`,
  toGoLabel: 'Liko',
  in30: 'per 30 d.',
  relEmpty: 'Įrašyk kūno svorį',
  relEmptySub: 'Pratimai rodomi kaip × kūno svoris',
  repPrs: 'Kartojimų rekordai',
  repPrOf: (l) => `Kart. rekordas · ${l}`,
  repPrsOf: (l) => `Kart. rekordai · ${l}`,
  repsUnit: 'kart.',
  atKg: (kg, d) => `@ ${kg} kg · ${d}`,
  repTitle: (l, kg, n) => `${l} @ ${kg} kg: ${n} kart.`,
  bestSet: (d) => `Naujausias kartojimų rekordas · ${d}`,
  bestReps: 'daugiausia kart.',
  chances: 'Kitas rekordas su didžiausiais svoriais',
  bestOn: (n, d) => `rekordas ${n} · ${d}`,
  isPr: (n) => `${n} = rekordas`,
  exerciseHistory: 'Pratimo istorija',
  repEmpty: 'Dar nėra kartojimų rekordų',
  stalled: 'Sąstingis',
  stalledK: 'Sąstingis',
  lifts: 'prat.',
  stalledN: (n) => `Sąstingis: ${n}`,
  sessionsAt: (n, set) => `${n} sesijos su ${set}`,
  sessionsDot: (n, set) => `${n} sesijos · ${set}`,
  stuckAt: (n, set) => `${n} sesijos · įstrigo ties ${set}`,
  noGain: 'e1RM neauga',
  deloadTo: (set) => `Iškrova 10% → ${set}, tada vėl kelk`,
  swapTo: (x) => `Keisk → ${x}`,
  deloadShort: 'Iškrova 10%',
  swapShort: 'Keisti',
  watching: (l, n) => `Stebima: ${l} · ${n} sesijos`,
  stalledHint: 'Svoris stovi 3+ sesijas',
  noStalls: 'Sąstingio nėra',
  noStallsSub: 'Visi pratimai dar auga',
  smartSwap: 'Išmanus keitimas',
  swapOf: (l) => `Keitimas · ${l}`,
  swapKicker: (g) => `Išmanus keitimas · ${g}`,
  busy: (a, b) => `${a} užimta? ${b}`,
  sameMuscles: (p) => `${p}% tie patys raumenys`,
  pctMatch: (p) => `${p}% atitikimas`,
  match: 'atitikimas',
  replacing: 'Vietoj',
  swap: 'Keisti',
  view: 'Peržiūrėti',
  liveNow: 'dabar',
  atGym: (g) => `${g}`,
  available: 'yra čia',
  needs: (x) => `reikia: ${x}`,
  anyGym: 'bet kuri sporto salė',
  swapEmpty: 'Kol kas nėra ką keisti',
  swapEmptySub: 'Suplanuok arba pradėk sesiją',
};

const et: StrengthStrings = {
  liftShort: { squat: 'K', bench: 'L', deadlift: 'J', ohp: 'OHP' },
  liftName: { squat: 'Kükk', bench: 'Lamades surumine', deadlift: 'Jõutõmme', ohp: 'OHP' },
  weeks: (n) => `${n} näd`,
  reps: 'kordust',
  weight: 'Raskus',
  save: 'Salvesta',
  start: 'Alusta',
  today: 'täna',
  openTrends: 'Ava trendid',
  logWeight: 'Lisa kaal',
  e1rm: 'e1RM',
  topLifts: 'Põhiharjutused',
  topLifts4: 'Põhiharjutused · 4 näd',
  topLiftsE1: 'Põhiharjutused · e1RM',
  ofUp: (n) => `${n}-st tõusus`,
  upCount: (n) => `${n} ↑`,
  big3: (x) => `Kolmevõistluse summa ${x} kg`,
  allLifts: 'Kõik harjutused',
  topLiftsEmpty: 'Põhiharjutusi veel pole',
  topLiftsEmptySub: 'Logi kükk, surumine, jõutõmme või OHP',
  nextTarget: 'Järgmine eesmärk',
  nextKicker: (d) => `Edasi · ${d}`,
  nextTargetKicker: (d) => `Järgmine eesmärk · ${d}`,
  nextTargetsKicker: (d) => `Järgmised eesmärgid · ${d}`,
  dayToday: (d) => `${d} täna`,
  lastSession: 'Eelmine trenn',
  repeat: 'Kordus',
  setsX: (n) => `× ${n} seeriat`,
  lastLine: (x) => `Eelmisel korral: ${x}`,
  firstTimeHint: (lo, hi) => `Esimest korda — sihi ${lo}–${hi} kordust`,
  plusRep: '+1 kordus',
  deload: 'kergendus',
  firstTime: 'esimest korda',
  hold: 'hoia',
  progressionNote:
    'Topeltprogressioon: kõigis seeriates vahemiku ülemine piir → järgmisel korral lisa raskust.',
  startDay: (d) => `Alusta: ${d}`,
  nextEmpty: 'Eesmärke veel pole',
  nextEmptySub: 'Logi trenn või vali programm',
  prForecast: 'Rekordi prognoos',
  prForecastOf: (l) => `Prognoos · ${l}`,
  prBy: (l, kg, d) => `${l} ${kg} kg ${d}`,
  reachedLine: (l, kg) => `${l} ${kg} kg saavutatud`,
  noEtaLine: (l, kg) => `${l} → ${kg} kg: kuupäeva veel pole`,
  perWeek: (x) => `${x} kg / näd`,
  now: (x) => `praegu ${x}`,
  inWeeks: (n) => `~${n} näd pärast`,
  atPace: (kg, d) => `Selle tempoga: ${kg} kg ${d}`,
  targetLabel: (kg) => `eesmärk ${kg}`,
  byDate: (d) => `${d}`,
  nowPerWk: (now, sl) => `praegu ${now} · ${sl} / näd`,
  noEta: 'kuupäevata',
  reached: 'saavutatud',
  changeTargets: 'Muuda eesmärke',
  targetsTitle: 'Siht-e1RM',
  targetsHint: 'Prognoos näitab, millal praegune tempo need saavutab.',
  prEmpty: 'Liiga vähe ajalugu',
  prEmptySub: '3+ põhiharjutuse trenni 12 nädalaga',
  recentPrs: 'Värsked rekordid',
  thisMonthUnit: 'sel kuul',
  prsThisMonth: (n) => `${n} sel kuul`,
  latest: (x) => `Viimane: ${x}`,
  prLabel: (x) => `Rekord: ${x}`,
  moreThisMonth: (n) => `veel ${n} sel kuul`,
  plusReps: (n) => `+${n} kordust`,
  repsAtWeight: 'kordused raskusel',
  allRecords: 'Kõik rekordid',
  prsEmpty: 'Rekordeid veel pole',
  prsEmptySub: 'Ületa eelmine tipp ja see ilmub siia',
  oneRm: '1RM kalkulaator',
  est1rm: 'Hinnang 1RM',
  fromSet: (set, l) => `${set} põhjal · ${l}`,
  fromLast: (l) => `1RM hinnang · viimasest seeriast: ${l}`,
  estimated: 'Hinnanguline 1RM',
  epley: 'Epley',
  upTo10: '1–10 kordust',
  oneRmEmpty: 'Sisesta seeria hinnanguks',
  tapToEdit: 'Raskus × kordused → sinu 1RM',
  enterSet: 'Sisesta seeria',
  plates: 'Kettad',
  plateCalc: 'Ketaste kalkulaator',
  platesPerSide: 'Kettad · ühele poole',
  perSide: (x) => `poolele ${x}`,
  bar20: 'poolele · 20 kg kang',
  barPerSide: 'Kang 20 kg · poolele',
  barOnly: 'Ainult kang',
  warmup: (p) => `Soojendus ${p}%`,
  topSet: 'Tööseeria',
  closest: (x) => `lähim ${x}-le`,
  balance: 'Jõu tasakaal',
  balanceVsDl: 'Tasakaal · jõutõmbe suhtes',
  typical: 'tüüpiline',
  lags: (l) => `${l} jääb maha`,
  lagsBy: (l, kg) => `${l} jääb maha ~${kg} kg`,
  vsTypical: (x) => `tüüpilisest JT ${x} puhul`,
  balanced: 'Tasakaalus',
  balancedSub: 'Lähedal tüüpilistele proportsioonidele',
  ratioSub: (typ) => `Kükk : Surumine : Jõutõmme · tüüpiline ${typ}`,
  e1rm12: 'e1RM · parimad',
  you: 'Sina',
  typicalFor: 'Tüüpiline tugevaimale harjutusele',
  lagNote: (l, kg) => `${l}: ~${kg} kg alla tüüpiliste proportsioonide.`,
  tierNote: (l, s) => `Järkude järgi terve aste maas: ${s} (${l}).`,
  balanceEmpty: 'Vaja kükki, surumist ja jõutõmmet',
  balanceEmptySub: 'Logi kõik kolm võrdluseks',
  standards: 'Normid',
  cls: (x) => `Järk ${x}`,
  classKicker: (c) => `Järk · ${c} kg`,
  stdKickerL: (c) => `Normid · ${c} kg · summa`,
  stdKickerXL: (c) => `Normid · ${c} kg kaalukategooria`,
  cat: (c) => `${c} kg kat.`,
  toNext: (kg, x) => `${kg} kg järgmiseni: ${x}`,
  toGo: (x) => `veel +${x}`,
  totalLine: (x) => `summa ${x}`,
  kgTotal: (x) => `summa ${x} kg`,
  rawTotal: 'raw summa',
  youMark: ' · sina',
  topRank: 'Kõrgeim järk',
  openStandards: 'Ava normid',
  stdNeedWeight: 'Lisa kaalumine',
  stdNeedWeightSub: 'Järgud sõltuvad kehakaalust',
  stdEmpty: 'Summat veel pole',
  plTotal: 'Kolmevõistluse summa',
  total: 'Summa',
  totalKg: (x) => `Summa ${x} kg`,
  days30: (x) => `${x} · 30 p`,
  since: (x, d) => `${x} alates ${d}`,
  clsTo: (c, kg, n) => `Järk ${c} · ${kg} kg järguni ${n}`,
  viewProgress: 'Areng',
  relStrength: 'Suhteline jõud',
  xBw: (l) => `${l} × kehakaal`,
  bwKicker: (bw) => `× kehakaal · ${bw} kg`,
  scale: (x) => `skaala 0 – ${x}×`,
  bwTimes: (l, r) => `${l} ${r}× kehakaalu`,
  nextMilestone: 'järgmine verstapost',
  totalBw: (x) => `summa ${x} ÷ kaal`,
  closestMilestone: 'Lähim verstapost',
  milestone: (l, r, kg) => `${l} ${r}× = ${kg} kg`,
  toGoLabel: 'Puudu',
  in30: '30 päevaga',
  relEmpty: 'Lisa kehakaal',
  relEmptySub: 'Harjutused kui × kehakaal',
  repPrs: 'Korduste rekordid',
  repPrOf: (l) => `Korduste rekord · ${l}`,
  repPrsOf: (l) => `Korduste rekordid · ${l}`,
  repsUnit: 'kordust',
  atKg: (kg, d) => `@ ${kg} kg · ${d}`,
  repTitle: (l, kg, n) => `${l} @ ${kg} kg: ${n} kordust`,
  bestSet: (d) => `Viimane korduste rekord · ${d}`,
  bestReps: 'enim kordusi',
  chances: 'Järgmine rekord suurimatel raskustel',
  bestOn: (n, d) => `rekord ${n} · ${d}`,
  isPr: (n) => `${n} = rekord`,
  exerciseHistory: 'Harjutuse ajalugu',
  repEmpty: 'Korduste rekordeid veel pole',
  stalled: 'Seisak',
  stalledK: 'Seisak',
  lifts: 'harj.',
  stalledN: (n) => `Seisak: ${n}`,
  sessionsAt: (n, set) => `${n} trenni ${set} juures`,
  sessionsDot: (n, set) => `${n} trenni · ${set}`,
  stuckAt: (n, set) => `${n} trenni · kinni ${set} juures`,
  noGain: 'e1RM ei kasva',
  deloadTo: (set) => `Kergendus 10% → ${set}, siis tõsta uuesti`,
  swapTo: (x) => `Vaheta → ${x}`,
  deloadShort: 'Kergendus 10%',
  swapShort: 'Vaheta',
  watching: (l, n) => `Jälgin: ${l} · ${n} trenni`,
  stalledHint: 'Raskus seisab 3+ trenni',
  noStalls: 'Seisakut pole',
  noStallsSub: 'Kõik harjutused arenevad',
  smartSwap: 'Nutikas asendus',
  swapOf: (l) => `Asendus · ${l}`,
  swapKicker: (g) => `Nutikas asendus · ${g}`,
  busy: (a, b) => `${a} hõivatud? ${b}`,
  sameMuscles: (p) => `${p}% samad lihased`,
  pctMatch: (p) => `${p}% sobivus`,
  match: 'sobivus',
  replacing: 'Asemel',
  swap: 'Vaheta',
  view: 'Vaata',
  liveNow: 'praegu',
  atGym: (g) => `${g}`,
  available: 'saadaval siin',
  needs: (x) => `vaja: ${x}`,
  anyGym: 'iga saal',
  swapEmpty: 'Veel pole midagi asendada',
  swapEmptySub: 'Planeeri või alusta trenni',
};

const DICT: Record<LocaleId, StrengthStrings> = { en, uk, pl, lt, et };

export function ss(locale: LocaleId): StrengthStrings {
  return DICT[locale];
}
