/**
 * Copy of the Training group's Today widgets, all five locales (typed: a
 * missing key in any locale fails the build). Muscle, activity and archetype
 * names come from the main dictionary.
 */
import type { LocaleId } from '../../i18n';

/** uk: 1 / 2–4 / 5+ (and 11–14). */
function pUk(n: number, one: string, few: string, many: string): string {
  const d = n % 10;
  const h = n % 100;
  if (d === 1 && h !== 11) return one;
  if (d >= 2 && d <= 4 && (h < 12 || h > 14)) return few;
  return many;
}
/** pl: 1 / 2–4 / 5+ (and 12–14). */
function pPl(n: number, one: string, few: string, many: string): string {
  if (n === 1) return one;
  const d = n % 10;
  const h = n % 100;
  if (d >= 2 && d <= 4 && (h < 12 || h > 14)) return few;
  return many;
}
/** lt: 1 (not 11) / 2–9 (not 12–19) / 0, 10–20. */
function pLt(n: number, one: string, few: string, many: string): string {
  const d = n % 10;
  const h = n % 100;
  if (d === 1 && h !== 11) return one;
  if (d >= 2 && (h < 12 || h > 19)) return few;
  return many;
}

const en = {
  // picker names
  nLiftRecord: 'Lift record',
  nActivities: 'Activities',
  nWeeklyRecap: 'Weekly recap',
  nGoals: 'Goals',
  nPlaybook: 'Playbook',
  nWeakPoints: 'Weak points',
  nFatigue: 'Fatigue & deload',
  nGyms: 'Gyms',

  // lift record
  e1rmOf: (lift: string) => `${lift} e1RM`,
  e1rmShort: 'est. 1RM',
  liftXl: (lift: string) => `${lift} · e1RM`,
  delta4w: (d: string) => `${d} · 4 wks`,
  prAgo: (n: number) => (n === 0 ? 'PR · today' : `PR · ${n} d ago`),
  noLifts: 'No lifts yet',
  noLiftsSub: 'Log a session to track your 1RM',
  startSession: 'Start a session',
  changeLift: 'Change lift',
  pickLift: 'Pick a lift to follow',
  autoLift: 'Latest PR (auto)',
  sessionsN: (n: number) => `${n} ${n === 1 ? 'session' : 'sessions'}`,

  // activities
  activeWeek: 'Active this week',
  activitiesN: (n: number) => `${n} ${n === 1 ? 'activity' : 'activities'}`,
  minActive: (n: number) => `${n} min active`,
  activitiesWeek: 'Activities · this week',
  kcal: (n: string) => `${n} kcal`,
  noActivities: 'No activities this week',
  noActivitiesSub: 'Cardio, sport and recovery count here',
  logActivity: 'Log activity',
  min: 'min',

  // weekly recap
  recap: 'Recap',
  recapRange: (r: string) => `Recap · ${r}`,
  weekReady: 'Your week is ready',
  prsN: (n: number) => `${n} ${n === 1 ? 'PR' : 'PRs'}`,
  bigSessions: (n: number) => `${n} ${n === 1 ? 'session' : 'sessions'}.`,
  bigTonnes: (x: string) => `${x} tonnes.`,
  bigPrs: (n: number) => (n > 0 ? `${n} new ${n === 1 ? 'PR' : 'PRs'}.` : 'Steady, no new PRs.'),
  bestWeekIn: (n: number) => `Your biggest week in ${n} weeks.`,
  bestWeekEver: 'Your biggest week on record.',
  topMuscle: (m: string, n: number) => `Most work: ${m} · ${n} sets`,
  watchRecap: (period: string) => `Watch ${period} recap`,
  openHistory: 'Open history',
  noRecap: 'No recap yet',
  noRecapSub: 'Train this week — the recap lands when it closes',

  // goals
  goal: 'Goal',
  goalOf: (n: string) => `Goal · ${n}`,
  goalArchetype: 'Goal · archetype',
  focus: 'Focus',
  inFocus: (n: number) => `${n} ${n === 1 ? 'muscle' : 'muscles'} in focus`,
  inFocusShort: (n: number) => `${n} in focus`,
  growList: (list: string) => `Grow ${list}`,
  grow: 'Grow',
  hold: 'Hold',
  ease: 'Ease',
  easeLine: (list: string) => `Ease: ${list} · rest on hold`,
  restHold: 'Everything else on hold',
  since: (d: string) => `since ${d}`,
  planWeek: 'This week vs target',
  setsOf: (a: number, b: number) => `${a} / ${b} sets`,
  editGoal: 'Edit goal',
  noGoal: 'No goal set',
  noGoalSub: 'Pick a shape and the muscles to grow',
  setGoal: 'Set a goal',

  // playbook
  playsN: (n: number) => `${n} ${n === 1 ? 'play' : 'plays'}`,
  playsLearned: (n: number) => `${n} ${n === 1 ? 'play' : 'plays'} learned`,
  todayPlay: (p: string) => `Today: ${p}`,
  playOf: (i: number, n: number) => `${i} of ${n}`,
  playbookOf: (i: number, n: number) => `Playbook · play ${i} of ${n}`,
  playMeta: (ex: number, s: number) => `${ex} exercises · from ${s} sessions`,
  startWith: 'Start with these:',
  start: 'Start',
  startPlay: 'Start this play',
  allPlays: 'All plays',
  sugFavorite: (ex: string) => `Add ${ex} — a favourite`,
  sugGap: (m: string) => `${m} isn't covered`,
  sugPlateau: (ex: string) => `${ex} stalled — vary it`,
  noPlays: 'No plays yet',
  noPlaysSub: 'Repeat a day twice and Spotter learns it',

  // weak points
  lagging: 'lagging',
  weakN: (n: number) => `${n} weak ${n === 1 ? 'point' : 'points'}`,
  noWeak: 'No weak points',
  noWeakSub: 'Every muscle meets its minimum',
  weakNeedHistory: 'Needs 3+ weeks of training',
  weakWeeks: (n: number) => `Weak points · ${n} weeks`,
  underWeeks: (u: number, tot: number) => `Under minimum ${u} of ${tot} weeks`,
  fixAt: (g: string) => `Fix-it · at ${g}`,
  fixIt: 'Fix-it',
  add: 'Add',

  // fatigue
  fatigue: 'Fatigue',
  fatigue6: 'Fatigue · 6 weeks',
  level: { fresh: 'Fresh', moderate: 'Moderate', high: 'High', fried: 'Fried' },
  fatigueIs: (l: string) => `Fatigue: ${l.toLowerCase()}`,
  deloadNone: 'No deload needed',
  deloadLocal: (m: string) => `Ease off ${m} this week`,
  deloadSystemic: 'Time for a deload week',
  of100: (l: string) => `/ 100 · ${l.toLowerCase()}`,
  stalled: 'stalled',
  stalledTitle: (m: string) => `${m} stalled`,
  lowFatigue: 'Recovering well',
  nearLimit: (a: number, b: number) => `${a} / ${b} sets`,
  volumeWeek: 'Weekly volume',
  vs4: (x: string) => `${x} vs 4-wk avg`,
  planDeload: 'Plan deload week',
  openFatigue: 'Open fatigue map',
  noFatigue: 'Nothing to recover from',

  // gyms
  myGym: 'My gym',
  km: (x: string) => `${x} km`,
  daysAgo: (n: number) => (n <= 0 ? 'today' : n === 1 ? 'yesterday' : `${n} days ago`),
  lastVisit: (x: string) => `Last visit ${x}`,
  visitsMonth: (n: number) => `${n} ${n === 1 ? 'visit' : 'visits'} this month`,
  noVisits: 'No visits logged yet',
  startHere: 'Start here',
  noGym: 'No gym saved',
  noGymSub: 'Save your gym to start there in one tap',
  findGym: 'Find a gym',
  fitsHere: (p: string) => `${p} fits here · all exercises available`,
  partlyFits: (p: string, a: number, n: number) => `${p}: ${a} of ${n} exercises available`,
  noInventory: 'Equipment not listed yet',
};

export type TrainingStrings = typeof en;

const uk: TrainingStrings = {
  nLiftRecord: 'Рекорд у вправі',
  nActivities: 'Активності',
  nWeeklyRecap: 'Підсумок тижня',
  nGoals: 'Цілі',
  nPlaybook: 'Плейбук',
  nWeakPoints: 'Слабкі місця',
  nFatigue: 'Втома і розвантаження',
  nGyms: 'Зали',

  e1rmOf: (lift) => `${lift} · 1ПМ`,
  e1rmShort: 'оцінка 1ПМ',
  liftXl: (lift) => `${lift} · 1ПМ`,
  delta4w: (d) => `${d} · 4 тиж`,
  prAgo: (n) => (n === 0 ? 'Рекорд · сьогодні' : `Рекорд · ${n} дн тому`),
  noLifts: 'Ще немає підходів',
  noLiftsSub: 'Запиши тренування, щоб бачити свій 1ПМ',
  startSession: 'Почати тренування',
  changeLift: 'Змінити вправу',
  pickLift: 'Обери вправу для відстеження',
  autoLift: 'Останній рекорд (авто)',
  sessionsN: (n) => `${n} ${pUk(n, 'тренування', 'тренування', 'тренувань')}`,

  activeWeek: 'Активність за тиждень',
  activitiesN: (n) => `${n} ${pUk(n, 'активність', 'активності', 'активностей')}`,
  minActive: (n) => `${n} хв активності`,
  activitiesWeek: 'Активності · цей тиждень',
  kcal: (n) => `${n} ккал`,
  noActivities: 'Цього тижня активностей немає',
  noActivitiesSub: 'Тут рахуються кардіо, спорт і відновлення',
  logActivity: 'Додати активність',
  min: 'хв',

  recap: 'Підсумок',
  recapRange: (r) => `Підсумок · ${r}`,
  weekReady: 'Твій тиждень готовий',
  prsN: (n) => `${n} ${pUk(n, 'рекорд', 'рекорди', 'рекордів')}`,
  bigSessions: (n) => `${n} ${pUk(n, 'тренування', 'тренування', 'тренувань')}.`,
  bigTonnes: (x) => `${x} тонн.`,
  bigPrs: (n) =>
    n > 0
      ? `${n} ${pUk(n, 'новий рекорд', 'нові рекорди', 'нових рекордів')}.`
      : 'Рівно, без нових рекордів.',
  bestWeekIn: (n) => `Найбільший тиждень за ${n} тиж.`,
  bestWeekEver: 'Найбільший тиждень за весь час.',
  topMuscle: (m, n) => `Найбільше: ${m} · ${n} підх.`,
  watchRecap: (period) => `Дивитися підсумок: ${period}`,
  openHistory: 'Відкрити історію',
  noRecap: 'Підсумку ще немає',
  noRecapSub: 'Тренуйся цього тижня — підсумок з’явиться, коли він закриється',

  goal: 'Ціль',
  goalOf: (n) => `Ціль · ${n}`,
  goalArchetype: 'Ціль · тип фігури',
  focus: 'Фокус',
  inFocus: (n) => `${n} ${pUk(n, 'м’яз', 'м’язи', 'м’язів')} у фокусі`,
  inFocusShort: (n) => `${n} у фокусі`,
  growList: (list) => `Ростимо: ${list}`,
  grow: 'Ріст',
  hold: 'Тримаємо',
  ease: 'Менше',
  easeLine: (list) => `Менше: ${list} · решту тримаємо`,
  restHold: 'Решту тримаємо',
  since: (d) => `з ${d}`,
  planWeek: 'Цей тиждень проти цілі',
  setsOf: (a, b) => `${a} / ${b} підх.`,
  editGoal: 'Змінити ціль',
  noGoal: 'Ціль не задано',
  noGoalSub: 'Обери форму і м’язи, які ростимо',
  setGoal: 'Задати ціль',

  playsN: (n) => `${n} ${pUk(n, 'плей', 'плеї', 'плеїв')}`,
  playsLearned: (n) => `${n} ${pUk(n, 'плей', 'плеї', 'плеїв')} з історії`,
  todayPlay: (p) => `Сьогодні: ${p}`,
  playOf: (i, n) => `${i} з ${n}`,
  playbookOf: (i, n) => `Плейбук · плей ${i} з ${n}`,
  playMeta: (ex, s) => `${ex} вправ · з ${s} тренувань`,
  startWith: 'Почни з цих:',
  start: 'Почати',
  startPlay: 'Почати цей плей',
  allPlays: 'Усі плеї',
  sugFavorite: (ex) => `Додай ${ex} — улюблена`,
  sugGap: (m) => `${m} не охоплено`,
  sugPlateau: (ex) => `${ex} стоїть — зміни варіант`,
  noPlays: 'Плеїв ще немає',
  noPlaysSub: 'Повтори день двічі — і Spotter його запам’ятає',

  lagging: 'відстають',
  weakN: (n) => `${n} ${pUk(n, 'слабке місце', 'слабкі місця', 'слабких місць')}`,
  noWeak: 'Слабких місць немає',
  noWeakSub: 'Кожен м’яз отримує свій мінімум',
  weakNeedHistory: 'Потрібно 3+ тижні тренувань',
  weakWeeks: (n) => `Слабкі місця · ${n} тиж`,
  underWeeks: (u, tot) => `Нижче мінімуму ${u} з ${tot} тиж`,
  fixAt: (g) => `Виправити · ${g}`,
  fixIt: 'Виправити',
  add: 'Додати',

  fatigue: 'Втома',
  fatigue6: 'Втома · 6 тижнів',
  level: { fresh: 'Свіжість', moderate: 'Помірна', high: 'Висока', fried: 'Перевтома' },
  fatigueIs: (l) => `Втома: ${l.toLowerCase()}`,
  deloadNone: 'Розвантаження не потрібне',
  deloadLocal: (m) => `Цього тижня менше: ${m}`,
  deloadSystemic: 'Час на тиждень розвантаження',
  of100: (l) => `/ 100 · ${l.toLowerCase()}`,
  stalled: 'застій',
  stalledTitle: (m) => `${m}: застій`,
  lowFatigue: 'Відновлюєшся добре',
  nearLimit: (a, b) => `${a} / ${b} підх.`,
  volumeWeek: 'Обсяг тижня',
  vs4: (x) => `${x} до сер. за 4 тиж`,
  planDeload: 'Запланувати розвантаження',
  openFatigue: 'Відкрити карту втоми',
  noFatigue: 'Нема від чого відновлюватися',

  myGym: 'Мій зал',
  km: (x) => `${x} км`,
  daysAgo: (n) =>
    n <= 0 ? 'сьогодні' : n === 1 ? 'вчора' : `${n} ${pUk(n, 'день', 'дні', 'днів')} тому`,
  lastVisit: (x) => `Останній візит ${x}`,
  visitsMonth: (n) => `${n} ${pUk(n, 'візит', 'візити', 'візитів')} цього місяця`,
  noVisits: 'Візитів ще немає',
  startHere: 'Почати тут',
  noGym: 'Зал не збережено',
  noGymSub: 'Збережи свій зал, щоб починати там в один дотик',
  findGym: 'Знайти зал',
  fitsHere: (p) => `${p} підходить · усі вправи доступні`,
  partlyFits: (p, a, n) => `${p}: доступно ${a} з ${n} вправ`,
  noInventory: 'Обладнання ще не вказано',
};

const pl: TrainingStrings = {
  nLiftRecord: 'Rekord w ćwiczeniu',
  nActivities: 'Aktywności',
  nWeeklyRecap: 'Podsumowanie tygodnia',
  nGoals: 'Cele',
  nPlaybook: 'Playbook',
  nWeakPoints: 'Słabe punkty',
  nFatigue: 'Zmęczenie i deload',
  nGyms: 'Siłownie',

  e1rmOf: (lift) => `${lift} · e1RM`,
  e1rmShort: 'szac. 1RM',
  liftXl: (lift) => `${lift} · e1RM`,
  delta4w: (d) => `${d} · 4 tyg.`,
  prAgo: (n) => (n === 0 ? 'Rekord · dziś' : `Rekord · ${n} dni temu`),
  noLifts: 'Brak serii',
  noLiftsSub: 'Zapisz trening, by śledzić swój 1RM',
  startSession: 'Zacznij trening',
  changeLift: 'Zmień ćwiczenie',
  pickLift: 'Wybierz ćwiczenie do śledzenia',
  autoLift: 'Ostatni rekord (auto)',
  sessionsN: (n) => `${n} ${pPl(n, 'trening', 'treningi', 'treningów')}`,

  activeWeek: 'Aktywność w tym tygodniu',
  activitiesN: (n) => `${n} ${pPl(n, 'aktywność', 'aktywności', 'aktywności')}`,
  minActive: (n) => `${n} min aktywności`,
  activitiesWeek: 'Aktywności · ten tydzień',
  kcal: (n) => `${n} kcal`,
  noActivities: 'Brak aktywności w tym tygodniu',
  noActivitiesSub: 'Liczy się tu cardio, sport i regeneracja',
  logActivity: 'Dodaj aktywność',
  min: 'min',

  recap: 'Podsumowanie',
  recapRange: (r) => `Podsumowanie · ${r}`,
  weekReady: 'Twój tydzień jest gotowy',
  prsN: (n) => `${n} ${pPl(n, 'rekord', 'rekordy', 'rekordów')}`,
  bigSessions: (n) => `${n} ${pPl(n, 'trening', 'treningi', 'treningów')}.`,
  bigTonnes: (x) => `${x} ton.`,
  bigPrs: (n) =>
    n > 0
      ? `${n} ${pPl(n, 'nowy rekord', 'nowe rekordy', 'nowych rekordów')}.`
      : 'Równo, bez nowych rekordów.',
  bestWeekIn: (n) => `Największy tydzień od ${n} tyg.`,
  bestWeekEver: 'Największy tydzień w historii.',
  topMuscle: (m, n) => `Najwięcej: ${m} · ${n} serii`,
  watchRecap: (period) => `Zobacz podsumowanie: ${period}`,
  openHistory: 'Otwórz historię',
  noRecap: 'Brak podsumowania',
  noRecapSub: 'Trenuj w tym tygodniu — podsumowanie pojawi się po jego końcu',

  goal: 'Cel',
  goalOf: (n) => `Cel · ${n}`,
  goalArchetype: 'Cel · sylwetka',
  focus: 'Fokus',
  inFocus: (n) => `${n} ${pPl(n, 'mięsień', 'mięśnie', 'mięśni')} w fokusie`,
  inFocusShort: (n) => `${n} w fokusie`,
  growList: (list) => `Rozwijamy: ${list}`,
  grow: 'Rozwój',
  hold: 'Utrzymanie',
  ease: 'Mniej',
  easeLine: (list) => `Mniej: ${list} · reszta bez zmian`,
  restHold: 'Reszta bez zmian',
  since: (d) => `od ${d}`,
  planWeek: 'Ten tydzień vs cel',
  setsOf: (a, b) => `${a} / ${b} serii`,
  editGoal: 'Edytuj cel',
  noGoal: 'Brak celu',
  noGoalSub: 'Wybierz sylwetkę i mięśnie do rozwoju',
  setGoal: 'Ustaw cel',

  playsN: (n) => `${n} ${pPl(n, 'zagranie', 'zagrania', 'zagrań')}`,
  playsLearned: (n) => `${n} ${pPl(n, 'zagranie', 'zagrania', 'zagrań')} z historii`,
  todayPlay: (p) => `Dziś: ${p}`,
  playOf: (i, n) => `${i} z ${n}`,
  playbookOf: (i, n) => `Playbook · zagranie ${i} z ${n}`,
  playMeta: (ex, s) => `${ex} ćwiczeń · z ${s} treningów`,
  startWith: 'Zacznij od tych:',
  start: 'Start',
  startPlay: 'Zacznij to zagranie',
  allPlays: 'Wszystkie',
  sugFavorite: (ex) => `Dodaj ${ex} — ulubione`,
  sugGap: (m) => `${m} bez pokrycia`,
  sugPlateau: (ex) => `${ex} stoi — zmień wariant`,
  noPlays: 'Brak zagrań',
  noPlaysSub: 'Powtórz dzień dwa razy, a Spotter go zapamięta',

  lagging: 'odstają',
  weakN: (n) => `${n} ${pPl(n, 'słaby punkt', 'słabe punkty', 'słabych punktów')}`,
  noWeak: 'Brak słabych punktów',
  noWeakSub: 'Każdy mięsień dostaje swoje minimum',
  weakNeedHistory: 'Potrzeba 3+ tygodni treningów',
  weakWeeks: (n) => `Słabe punkty · ${n} tyg.`,
  underWeeks: (u, tot) => `Poniżej minimum ${u} z ${tot} tyg.`,
  fixAt: (g) => `Napraw · ${g}`,
  fixIt: 'Napraw',
  add: 'Dodaj',

  fatigue: 'Zmęczenie',
  fatigue6: 'Zmęczenie · 6 tygodni',
  level: { fresh: 'Świeżość', moderate: 'Umiarkowane', high: 'Wysokie', fried: 'Przemęczenie' },
  fatigueIs: (l) => `Zmęczenie: ${l.toLowerCase()}`,
  deloadNone: 'Deload niepotrzebny',
  deloadLocal: (m) => `W tym tygodniu mniej: ${m}`,
  deloadSystemic: 'Czas na tydzień deloadu',
  of100: (l) => `/ 100 · ${l.toLowerCase()}`,
  stalled: 'zastój',
  stalledTitle: (m) => `${m}: zastój`,
  lowFatigue: 'Dobrze się regenerujesz',
  nearLimit: (a, b) => `${a} / ${b} serii`,
  volumeWeek: 'Objętość tygodnia',
  vs4: (x) => `${x} vs śr. 4 tyg.`,
  planDeload: 'Zaplanuj deload',
  openFatigue: 'Otwórz mapę zmęczenia',
  noFatigue: 'Nie ma z czego się regenerować',

  myGym: 'Moja siłownia',
  km: (x) => `${x} km`,
  daysAgo: (n) => (n <= 0 ? 'dziś' : n === 1 ? 'wczoraj' : `${n} dni temu`),
  lastVisit: (x) => `Ostatnia wizyta ${x}`,
  visitsMonth: (n) => `${n} ${pPl(n, 'wizyta', 'wizyty', 'wizyt')} w tym miesiącu`,
  noVisits: 'Brak wizyt',
  startHere: 'Zacznij tutaj',
  noGym: 'Brak zapisanej siłowni',
  noGymSub: 'Zapisz siłownię, by zaczynać tam jednym dotknięciem',
  findGym: 'Znajdź siłownię',
  fitsHere: (p) => `${p} pasuje · wszystkie ćwiczenia dostępne`,
  partlyFits: (p, a, n) => `${p}: dostępne ${a} z ${n} ćwiczeń`,
  noInventory: 'Sprzęt jeszcze nie podany',
};

const lt: TrainingStrings = {
  nLiftRecord: 'Pratimo rekordas',
  nActivities: 'Veiklos',
  nWeeklyRecap: 'Savaitės apžvalga',
  nGoals: 'Tikslai',
  nPlaybook: 'Planų knyga',
  nWeakPoints: 'Silpnosios vietos',
  nFatigue: 'Nuovargis ir iškrova',
  nGyms: 'Sporto salės',

  e1rmOf: (lift) => `${lift} · e1RM`,
  e1rmShort: 'apyt. 1RM',
  liftXl: (lift) => `${lift} · e1RM`,
  delta4w: (d) => `${d} · 4 sav.`,
  prAgo: (n) => (n === 0 ? 'Rekordas · šiandien' : `Rekordas · prieš ${n} d.`),
  noLifts: 'Dar nėra serijų',
  noLiftsSub: 'Užregistruok treniruotę, kad matytum 1RM',
  startSession: 'Pradėti treniruotę',
  changeLift: 'Keisti pratimą',
  pickLift: 'Pasirink sekamą pratimą',
  autoLift: 'Paskutinis rekordas (auto)',
  sessionsN: (n) => `${n} ${pLt(n, 'treniruotė', 'treniruotės', 'treniruočių')}`,

  activeWeek: 'Aktyvumas šią savaitę',
  activitiesN: (n) => `${n} ${pLt(n, 'veikla', 'veiklos', 'veiklų')}`,
  minActive: (n) => `${n} min aktyvumo`,
  activitiesWeek: 'Veiklos · ši savaitė',
  kcal: (n) => `${n} kcal`,
  noActivities: 'Šią savaitę veiklų nėra',
  noActivitiesSub: 'Čia skaičiuojamas kardio, sportas ir atsigavimas',
  logActivity: 'Pridėti veiklą',
  min: 'min',

  recap: 'Apžvalga',
  recapRange: (r) => `Apžvalga · ${r}`,
  weekReady: 'Tavo savaitė paruošta',
  prsN: (n) => `${n} ${pLt(n, 'rekordas', 'rekordai', 'rekordų')}`,
  bigSessions: (n) => `${n} ${pLt(n, 'treniruotė', 'treniruotės', 'treniruočių')}.`,
  bigTonnes: (x) => `${x} t.`,
  bigPrs: (n) =>
    n > 0
      ? `${n} ${pLt(n, 'naujas rekordas', 'nauji rekordai', 'naujų rekordų')}.`
      : 'Tolygiai, be naujų rekordų.',
  bestWeekIn: (n) => `Didžiausia savaitė per ${n} sav.`,
  bestWeekEver: 'Didžiausia savaitė per visą laiką.',
  topMuscle: (m, n) => `Daugiausia: ${m} · ${n} ser.`,
  watchRecap: (period) => `Žiūrėti apžvalgą: ${period}`,
  openHistory: 'Atidaryti istoriją',
  noRecap: 'Apžvalgos dar nėra',
  noRecapSub: 'Treniruokis šią savaitę — apžvalga pasirodys jai pasibaigus',

  goal: 'Tikslas',
  goalOf: (n) => `Tikslas · ${n}`,
  goalArchetype: 'Tikslas · figūra',
  focus: 'Fokusas',
  inFocus: (n) => `${n} ${pLt(n, 'raumuo', 'raumenys', 'raumenų')} fokuse`,
  inFocusShort: (n) => `${n} fokuse`,
  growList: (list) => `Auginame: ${list}`,
  grow: 'Auginti',
  hold: 'Išlaikyti',
  ease: 'Mažinti',
  easeLine: (list) => `Mažinti: ${list} · kiti išlaikomi`,
  restHold: 'Kiti išlaikomi',
  since: (d) => `nuo ${d}`,
  planWeek: 'Ši savaitė vs tikslas',
  setsOf: (a, b) => `${a} / ${b} ser.`,
  editGoal: 'Keisti tikslą',
  noGoal: 'Tikslas nenustatytas',
  noGoalSub: 'Pasirink figūrą ir raumenis auginimui',
  setGoal: 'Nustatyti tikslą',

  playsN: (n) => `${n} ${pLt(n, 'planas', 'planai', 'planų')}`,
  playsLearned: (n) => `${n} ${pLt(n, 'planas', 'planai', 'planų')} iš istorijos`,
  todayPlay: (p) => `Šiandien: ${p}`,
  playOf: (i, n) => `${i} iš ${n}`,
  playbookOf: (i, n) => `Planų knyga · ${i} iš ${n}`,
  playMeta: (ex, s) => `${ex} pratimai · iš ${s} treniruočių`,
  startWith: 'Pradėk nuo šių:',
  start: 'Pradėti',
  startPlay: 'Pradėti šį planą',
  allPlays: 'Visi planai',
  sugFavorite: (ex) => `Pridėk ${ex} — mėgstamas`,
  sugGap: (m) => `${m} neapimta`,
  sugPlateau: (ex) => `${ex} stovi — keisk variantą`,
  noPlays: 'Planų dar nėra',
  noPlaysSub: 'Pakartok dieną du kartus ir Spotter ją išmoks',

  lagging: 'atsilieka',
  weakN: (n) => `${n} ${pLt(n, 'silpnoji vieta', 'silpnosios vietos', 'silpnųjų vietų')}`,
  noWeak: 'Silpnųjų vietų nėra',
  noWeakSub: 'Kiekvienas raumuo gauna savo minimumą',
  weakNeedHistory: 'Reikia 3+ savaičių treniruočių',
  weakWeeks: (n) => `Silpnosios vietos · ${n} sav.`,
  underWeeks: (u, tot) => `Žemiau minimumo ${u} iš ${tot} sav.`,
  fixAt: (g) => `Taisyti · ${g}`,
  fixIt: 'Taisyti',
  add: 'Pridėti',

  fatigue: 'Nuovargis',
  fatigue6: 'Nuovargis · 6 savaitės',
  level: { fresh: 'Žvalus', moderate: 'Vidutinis', high: 'Didelis', fried: 'Pervargimas' },
  fatigueIs: (l) => `Nuovargis: ${l.toLowerCase()}`,
  deloadNone: 'Iškrovos nereikia',
  deloadLocal: (m) => `Šią savaitę mažiau: ${m}`,
  deloadSystemic: 'Laikas iškrovos savaitei',
  of100: (l) => `/ 100 · ${l.toLowerCase()}`,
  stalled: 'sąstingis',
  stalledTitle: (m) => `${m}: sąstingis`,
  lowFatigue: 'Gerai atsigauni',
  nearLimit: (a, b) => `${a} / ${b} ser.`,
  volumeWeek: 'Savaitės apimtis',
  vs4: (x) => `${x} vs 4 sav. vid.`,
  planDeload: 'Planuoti iškrovą',
  openFatigue: 'Atidaryti nuovargio žemėlapį',
  noFatigue: 'Nėra nuo ko atsigauti',

  myGym: 'Mano salė',
  km: (x) => `${x} km`,
  daysAgo: (n) => (n <= 0 ? 'šiandien' : n === 1 ? 'vakar' : `prieš ${n} d.`),
  lastVisit: (x) => `Paskutinis apsilankymas ${x}`,
  visitsMonth: (n) => `${n} ${pLt(n, 'apsilankymas', 'apsilankymai', 'apsilankymų')} šį mėnesį`,
  noVisits: 'Apsilankymų dar nėra',
  startHere: 'Pradėti čia',
  noGym: 'Salė neišsaugota',
  noGymSub: 'Išsaugok savo salę ir pradėk ten vienu paspaudimu',
  findGym: 'Rasti salę',
  fitsHere: (p) => `${p} tinka · visi pratimai prieinami`,
  partlyFits: (p, a, n) => `${p}: prieinama ${a} iš ${n} pratimų`,
  noInventory: 'Įranga dar nenurodyta',
};

const et: TrainingStrings = {
  nLiftRecord: 'Harjutuse rekord',
  nActivities: 'Tegevused',
  nWeeklyRecap: 'Nädala kokkuvõte',
  nGoals: 'Eesmärgid',
  nPlaybook: 'Mänguraamat',
  nWeakPoints: 'Nõrgad kohad',
  nFatigue: 'Väsimus ja deload',
  nGyms: 'Jõusaalid',

  e1rmOf: (lift) => `${lift} · e1RM`,
  e1rmShort: 'hinnang. 1RM',
  liftXl: (lift) => `${lift} · e1RM`,
  delta4w: (d) => `${d} · 4 näd`,
  prAgo: (n) => (n === 0 ? 'Rekord · täna' : `Rekord · ${n} p tagasi`),
  noLifts: 'Seeriaid veel pole',
  noLiftsSub: 'Logi trenn, et oma 1RM-i jälgida',
  startSession: 'Alusta trenni',
  changeLift: 'Vaheta harjutust',
  pickLift: 'Vali jälgitav harjutus',
  autoLift: 'Viimane rekord (auto)',
  sessionsN: (n) => `${n} ${n === 1 ? 'trenn' : 'trenni'}`,

  activeWeek: 'Aktiivsus sel nädalal',
  activitiesN: (n) => `${n} ${n === 1 ? 'tegevus' : 'tegevust'}`,
  minActive: (n) => `${n} min aktiivsust`,
  activitiesWeek: 'Tegevused · see nädal',
  kcal: (n) => `${n} kcal`,
  noActivities: 'Sel nädalal tegevusi pole',
  noActivitiesSub: 'Siia lähevad kardio, sport ja taastumine',
  logActivity: 'Lisa tegevus',
  min: 'min',

  recap: 'Kokkuvõte',
  recapRange: (r) => `Kokkuvõte · ${r}`,
  weekReady: 'Sinu nädal on valmis',
  prsN: (n) => `${n} ${n === 1 ? 'rekord' : 'rekordit'}`,
  bigSessions: (n) => `${n} ${n === 1 ? 'trenn' : 'trenni'}.`,
  bigTonnes: (x) => `${x} tonni.`,
  bigPrs: (n) =>
    n > 0 ? `${n} ${n === 1 ? 'uus rekord' : 'uut rekordit'}.` : 'Ühtlane, uusi rekordeid pole.',
  bestWeekIn: (n) => `Suurim nädal ${n} nädala jooksul.`,
  bestWeekEver: 'Kõigi aegade suurim nädal.',
  topMuscle: (m, n) => `Enim tööd: ${m} · ${n} seeriat`,
  watchRecap: (period) => `Vaata kokkuvõtet: ${period}`,
  openHistory: 'Ava ajalugu',
  noRecap: 'Kokkuvõtet veel pole',
  noRecapSub: 'Treeni sel nädalal — kokkuvõte tuleb nädala lõppedes',

  goal: 'Eesmärk',
  goalOf: (n) => `Eesmärk · ${n}`,
  goalArchetype: 'Eesmärk · kehatüüp',
  focus: 'Fookus',
  inFocus: (n) => `${n} ${n === 1 ? 'lihas' : 'lihast'} fookuses`,
  inFocusShort: (n) => `${n} fookuses`,
  growList: (list) => `Kasvatame: ${list}`,
  grow: 'Kasvata',
  hold: 'Hoia',
  ease: 'Vähenda',
  easeLine: (list) => `Vähenda: ${list} · ülejäänu hoiame`,
  restHold: 'Ülejäänu hoiame',
  since: (d) => `alates ${d}`,
  planWeek: 'See nädal vs eesmärk',
  setsOf: (a, b) => `${a} / ${b} seeriat`,
  editGoal: 'Muuda eesmärki',
  noGoal: 'Eesmärki pole',
  noGoalSub: 'Vali kehakuju ja lihased, mida kasvatada',
  setGoal: 'Sea eesmärk',

  playsN: (n) => `${n} kava`,
  playsLearned: (n) => `${n} kava ajaloost`,
  todayPlay: (p) => `Täna: ${p}`,
  playOf: (i, n) => `${i} / ${n}`,
  playbookOf: (i, n) => `Mänguraamat · kava ${i} / ${n}`,
  playMeta: (ex, s) => `${ex} harjutust · ${s} trennist`,
  startWith: 'Alusta nendega:',
  start: 'Alusta',
  startPlay: 'Alusta seda kava',
  allPlays: 'Kõik kavad',
  sugFavorite: (ex) => `Lisa ${ex} — lemmik`,
  sugGap: (m) => `${m} pole kaetud`,
  sugPlateau: (ex) => `${ex} seisab — vaheta varianti`,
  noPlays: 'Kavasid veel pole',
  noPlaysSub: 'Korda päeva kaks korda ja Spotter õpib selle ära',

  lagging: 'maas',
  weakN: (n) => `${n} ${n === 1 ? 'nõrk koht' : 'nõrka kohta'}`,
  noWeak: 'Nõrku kohti pole',
  noWeakSub: 'Iga lihas saab oma miinimumi',
  weakNeedHistory: 'Vaja 3+ nädalat treeningut',
  weakWeeks: (n) => `Nõrgad kohad · ${n} näd`,
  underWeeks: (u, tot) => `Alla miinimumi ${u} / ${tot} näd`,
  fixAt: (g) => `Paranda · ${g}`,
  fixIt: 'Paranda',
  add: 'Lisa',

  fatigue: 'Väsimus',
  fatigue6: 'Väsimus · 6 nädalat',
  level: { fresh: 'Värske', moderate: 'Mõõdukas', high: 'Kõrge', fried: 'Ülekoormus' },
  fatigueIs: (l) => `Väsimus: ${l.toLowerCase()}`,
  deloadNone: 'Deloadi pole vaja',
  deloadLocal: (m) => `Sel nädalal vähem: ${m}`,
  deloadSystemic: 'Aeg deload-nädalaks',
  of100: (l) => `/ 100 · ${l.toLowerCase()}`,
  stalled: 'seisak',
  stalledTitle: (m) => `${m}: seisak`,
  lowFatigue: 'Taastud hästi',
  nearLimit: (a, b) => `${a} / ${b} seeriat`,
  volumeWeek: 'Nädala maht',
  vs4: (x) => `${x} vs 4 näd keskm.`,
  planDeload: 'Planeeri deload',
  openFatigue: 'Ava väsimuse kaart',
  noFatigue: 'Pole millest taastuda',

  myGym: 'Minu jõusaal',
  km: (x) => `${x} km`,
  daysAgo: (n) => (n <= 0 ? 'täna' : n === 1 ? 'eile' : `${n} päeva tagasi`),
  lastVisit: (x) => `Viimane külastus ${x}`,
  visitsMonth: (n) => `${n} ${n === 1 ? 'külastus' : 'külastust'} sel kuul`,
  noVisits: 'Külastusi veel pole',
  startHere: 'Alusta siin',
  noGym: 'Jõusaali pole salvestatud',
  noGymSub: 'Salvesta oma saal, et seal ühe puudutusega alustada',
  findGym: 'Leia jõusaal',
  fitsHere: (p) => `${p} sobib · kõik harjutused olemas`,
  partlyFits: (p, a, n) => `${p}: olemas ${a} / ${n} harjutust`,
  noInventory: 'Varustust pole veel märgitud',
};

const DICT: Record<LocaleId, TrainingStrings> = { en, uk, pl, lt, et };

export function trs(locale: LocaleId): TrainingStrings {
  return DICT[locale];
}
