/**
 * GOLD set for the Atlas grammar analyser — realistic gym-chat sentences,
 * annotated by hand BEFORE the analyser was written.
 *
 * One row = one sentence: [lang, text, spec]. `spec` is
 *   'type[/questionKind[/whWord]] | clauses | pred subj tense neg person | quantities | timeRef'
 *
 *  type          s = statement, q = question, c = command, e = exclamation
 *  questionKind  yesno | wh | choice | tag | rhetorical  (empty for non-questions)
 *  whWord        canonical wh of the interrogative clause, else of an embedded
 *                complement clause ("tell me how…", "не знаю що…")
 *  clauses       surface order of clause starts: main | coord | sub:<kind>
 *                (kinds: cond caus temp conc purp rel comp res compar)
 *  pred          lemma of the MAIN clause predicate ('-' = none): the lexical verb
 *                (modals/aux/"want to"/"буду"/"можна" pass through to the
 *                infinitive), else the predicative word, else the copula
 *  subj          user | atlas | other | none   (imperatives → atlas, "let's"/"we" → user,
 *                dative experiencer with an impersonal predicate → that person)
 *  tense         past | present | future | none   (English perfect → past;
 *                infinitive-only / imperative / verbless → none; zero copula → present)
 *  neg           '+' negated main clause, '-' not
 *  person        1 | 2 | 3 | 0 (none)
 *  quantities    'value unit, value unit' — only with an explicit numeral
 *  timeRef       first explicit time reference (today, yesterday, this_week, sun…)
 *
 * Annotation guidelines (the rules the numbers are measured against):
 *  - A clause needs a predicate (finite verb, imperative, predicative word,
 *    infinitive heading a question/impersonal clause, zero-copula predicate).
 *    Verbless segments merge into a neighbour, except wh-/particle-led
 *    elliptic questions ("why not?", "чи можна жим") which stay clauses.
 *  - Non-finite complements ("want to squat", "хочу присідати", "to lose weight")
 *    are NOT separate clauses — except when introduced by a subordinator
 *    (щоб, in order to, so that) or a wh-word ("how to squat", "що їсти").
 *  - Coordinated verb phrases sharing one subject (однорідні присудки) are one
 *    clause; a coordinate clause needs its own subject, a result connector
 *    (so, тому, тож) or a predicate that cannot share the previous subject.
 *  - The first independent clause is 'main'; later independent ones are 'coord'.
 *  - Tag questions ("…, right?") are not separate clauses.
 */
export type GoldLang = 'en' | 'uk' | 'ru' | 'pl' | 'lt' | 'et';
/** Row language: 'uk-tr'/'ru-tr' = Latin transliteration, 'sz' = surzhyk (uk or ru accepted). */
export type RowLang = GoldLang | 'uk-tr' | 'ru-tr' | 'sz';
export type GoldRow = [RowLang, string, string];

export const GOLD: GoldRow[] = [
  // ───────────────────────── English ─────────────────────────
  [
    'en',
    'I danced for 2 hours today, why not commenting on that?',
    'q/wh/why | main,coord | dance user past - 1 | 2 h | today',
  ],
  ['en', 'how many sets should i do for biceps', 'q/wh/how_many | main | do user present - 1 | |'],
  ['en', 'What should I eat after a workout?', 'q/wh/what | main | eat user present - 1 | |'],
  [
    'en',
    'Why does my lower back hurt after deadlifts?',
    'q/wh/why | main | hurt other present - 3 | |',
  ],
  [
    'en',
    'Can I train legs two days in a row?',
    'q/yesno | main | train user present - 1 | 2 day |',
  ],
  [
    'en',
    'I benched 100kg for 5 reps yesterday',
    's | main | bench user past - 1 | 100 kg, 5 rep | yesterday',
  ],
  ['en', 'Should I do cardio or weights first?', 'q/choice | main | do user present - 1 | |'],
  ['en', "You didn't answer my question", 's | main | answer atlas past + 2 | |'],
  ['en', 'Give me a leg workout', 'c | main | give atlas none - 2 | |'],
  ['en', 'Please make me a plan for this week', 'c | main | make atlas none - 2 | | this_week'],
  [
    'en',
    'I think I overtrained this week',
    's | main,sub:comp | think user present - 1 | | this_week',
  ],
  [
    'en',
    'If my knee hurts during squats, what should I do?',
    'q/wh/what | sub:cond,main | do user present - 1 | |',
  ],
  ['en', 'When I squat my knees cave in', 's | sub:temp,main | cave other present - 3 | |'],
  [
    'en',
    'I ran 5k this morning and my legs are dead',
    's | main,coord | run user past - 1 | 5 km | this_morning',
  ],
  ['en', 'how long should i rest between sets', 'q/wh/how_long | main | rest user present - 1 | |'],
  ['en', 'How often should I train abs?', 'q/wh/how_often | main | train user present - 1 | |'],
  [
    'en',
    'Where do I put my feet on the leg press?',
    'q/wh/where | main | put user present - 1 | |',
  ],
  [
    'en',
    'Which is better for mass, dips or bench?',
    'q/wh/which | main | be other present - 3 | |',
  ],
  ['en', 'Who designed this program?', 'q/wh/who | main | design other past - 3 | |'],
  ['en', 'How much protein do I need per day?', 'q/wh/how_much | main | need user present - 1 | |'],
  [
    'en',
    "Is it bad to train when you're sore?",
    'q/yesno | main,sub:temp | be other present - 3 | |',
  ],
  ['en', "I haven't slept well for 3 days", 's | main | sleep user past + 1 | 3 day |'],
  ['en', 'My shoulder hurts when I bench', 's | main,sub:temp | hurt other present - 3 | |'],
  ['en', "I'm going to do legs tomorrow", 's | main | do user future - 1 | | tomorrow'],
  [
    'en',
    "I'll skip the gym today because I'm exhausted",
    's | main,sub:caus | skip user future - 1 | | today',
  ],
  [
    'en',
    "Although I sleep 8 hours I'm always tired",
    's | sub:conc,main | be user present - 1 | 8 h |',
  ],
  ['en', 'Tell me how to deadlift properly', 'c//how | main,sub:comp | tell atlas none - 2 | |'],
  [
    'en',
    'Can you explain why my bench is stuck?',
    'q/wh/why | main,sub:comp | explain atlas present - 2 | |',
  ],
  ['en', 'You always ignore my cardio', 's | main | ignore atlas present - 2 | |'],
  ['en', "Why don't you ever count my runs?", 'q/wh/why | main | count atlas present + 2 | |'],
  ['en', 'Wow, new PR on deadlift!', 'e | main | - none none - 0 | |'],
  ['en', "Let's do chest today", 'c | main | do user none - 1 | | today'],
  ['en', 'I did 3x10 squats at 80 kg', 's | main | do user past - 1 | 3 set, 10 rep, 80 kg |'],
  [
    'en',
    'i dont know what to eat before training',
    's//what | main,sub:comp | know user present + 1 | |',
  ],
  ['en', 'is creatine safe', 'q/yesno | main | be other present - 3 | |'],
  ['en', 'do i need a belt for squats', 'q/yesno | main | need user present - 1 | |'],
  ['en', 'my back is killing me', 's | main | kill other present - 3 | |'],
  [
    'en',
    "I've been training for 2 years but my bench is still weak",
    's | main,coord | train user past - 1 | 2 year |',
  ],
  [
    'en',
    'Should I stretch before or after lifting?',
    'q/choice | main | stretch user present - 1 | |',
  ],
  ['en', 'How do I fix my squat depth?', 'q/wh/how | main | fix user present - 1 | |'],
  [
    'en',
    "What's a good split for 4 days a week?",
    'q/wh/what | main | be other present - 3 | 4 day |',
  ],
  ['en', 'Why is my grip failing before my back?', 'q/wh/why | main | fail other present - 3 | |'],
  ['en', "I can't do a single pull-up", 's | main | do user present + 1 | |'],
  ['en', 'Could you give me a warm-up routine?', 'q/yesno | main | give atlas present - 2 | |'],
  ['en', 'I would like to lose 5 kg by summer', 's | main | lose user present - 1 | 5 kg |'],
  [
    'en',
    'If I eat more protein, will I gain muscle faster?',
    'q/yesno | sub:cond,main | gain user future - 1 | |',
  ],
  ['en', 'Stop telling me to rest', 'c | main | stop atlas none - 2 | |'],
  ['en', "That's not what I asked", 's | main,sub:rel | be other present + 3 | |'],
  [
    'en',
    "My legs are sore from yesterday's workout",
    's | main | be other present - 3 | | yesterday',
  ],
  ['en', 'Is 6 hours of sleep enough?', 'q/yesno | main | be other present - 3 | 6 h |'],
  [
    'en',
    'How many calories should I eat to lose weight?',
    'q/wh/how_many | main | eat user present - 1 | |',
  ],
  ['en', 'I want to get bigger arms', 's | main | get user present - 1 | |'],
  ['en', 'What do you think about my program?', 'q/wh/what | main | think atlas present - 2 | |'],
  ['en', 'you said rest but i feel fine', 's | main,coord | say atlas past - 2 | |'],
  ['en', 'The program you gave me is too hard', 's | main,sub:rel | be other present - 3 | |'],
  [
    'en',
    'I train at the gym that is near my office',
    's | main,sub:rel | train user present - 1 | |',
  ],
  ['en', 'When is the best time to do cardio?', 'q/wh/when | main | be other present - 3 | |'],
  ['en', 'When should I deload?', 'q/wh/when | main | deload user present - 1 | |'],
  [
    'en',
    'I missed two workouts this week so I feel guilty',
    's | main,coord | miss user past - 1 | 2 session | this_week',
  ],
  ['en', 'Is it normal that my knees crack?', 'q/yesno | main,sub:comp | be other present - 3 | |'],
  ['en', "right now i'm at 85 kg and want to cut", 's | main | be user present - 1 | 85 kg | now'],
  ['en', 'i hate burpees lol', 's | main | hate user present - 1 | |'],
  ['en', 'can u make the workout shorter pls', 'q/yesno | main | make atlas present - 2 | |'],
  ['en', 'hwo do i do a proper pushup', 'q/wh/how | main | do user present - 1 | |'],
  [
    'en',
    'whats the difference between rdl and deadlift',
    'q/wh/what | main | be other present - 3 | |',
  ],
  [
    'en',
    "I didn't go to the gym yesterday because my son was sick",
    's | main,sub:caus | go user past + 1 | | yesterday',
  ],
  [
    'en',
    'After I finish my workout I usually drink a shake',
    's | sub:temp,main | drink user present - 1 | |',
  ],
  ['en', 'I usually drink a shake after my workout', 's | main | drink user present - 1 | |'],
  [
    'en',
    "Why can't I get past 60 kg on overhead press?",
    'q/wh/why | main | get user present + 1 | 60 kg |',
  ],
  [
    'en',
    'How do you know how much I lifted?',
    'q/wh/how | main,sub:comp | know atlas present - 2 | |',
  ],
  ['en', 'Do you remember my squat max?', 'q/yesno | main | remember atlas present - 2 | |'],
  [
    'en',
    "I'm not sure if I should go heavy today",
    's | main,sub:comp | be user present + 1 | | today',
  ],
  [
    'en',
    'I slept 5 hours last night, should I still train?',
    'q/yesno | main,coord | sleep user past - 1 | 5 h | last_night',
  ],
  ['en', 'Great session today!', 'e | main | - none none - 0 | | today'],
  ['en', 'Thanks, that helps', 's | main | help other present - 3 | |'],
  ['en', "You're wrong about the rest times", 's | main | be atlas present - 2 | |'],
  ['en', 'Why not?', 'q/wh/why | main | - none none - 0 | |'],
  ['en', 'Who cares about abs anyway?', 'q/rhetorical/who | main | care other present - 3 | |'],
  ['en', "You're tracking my sleep, right?", 'q/tag | main | track atlas present - 2 | |'],
  ['en', "I did legs yesterday, didn't I?", 'q/tag | main | do user past - 1 | | yesterday'],
  ['en', 'Add 5 kg to my squat next week', 'c | main | add atlas none - 2 | 5 kg | next_week'],
  ['en', "Don't give me any more rest days", 'c | main | give atlas none + 2 | |'],
  ['en', 'I have been doing push ups every day', 's | main | do user past - 1 | |'],
  ['en', "I'm doing push-ups every day now", 's | main | do user present - 1 | | now'],
  [
    'en',
    'Will I lose muscle if I stop for a week?',
    'q/yesno | main,sub:cond | lose user future - 1 | |',
  ],
  ['en', 'I will run a half marathon in 3 months', 's | main | run user future - 1 | 3 month |'],
  [
    'en',
    'is it ok to do abs every day or is that too much',
    'q/choice | main,coord | be other present - 3 | |',
  ],
  ['en', 'my knee hurts, can i still squat?', 'q/yesno | main,coord | hurt other present - 3 | |'],
  ['en', "I can squat 120 but I can't bench 80", 's | main,coord | squat user present - 1 | |'],
  ['en', 'What muscles do lunges work?', 'q/wh/what | main | work other present - 3 | |'],
  ['en', 'How heavy should my deadlift be?', 'q/wh/how_much | main | be other present - 3 | |'],
  [
    'en',
    'i ate like 3000 calories today and feel bloated',
    's | main | eat user past - 1 | 3000 kcal | today',
  ],
  [
    'en',
    'Whenever I do overhead press my shoulder clicks',
    's | sub:temp,main | click other present - 3 | |',
  ],
  [
    'en',
    'Since I started creatine I gained 2 kg',
    's | sub:temp,main | gain user past - 1 | 2 kg |',
  ],
  ['en', "Since you're the coach, you decide", 's | sub:caus,main | decide atlas present - 2 | |'],
  ['en', "I'm tired so I'll keep it short today", 's | main,coord | be user present - 1 | | today'],
  ['en', "It's too hot to run outside", 's | main | be other present - 3 | |'],
  ['en', "Where's my progress chart?", 'q/wh/where | main | be other present - 3 | |'],
  [
    'en',
    'What time should I go to bed for recovery?',
    'q/wh/when | main | go user present - 1 | |',
  ],
  [
    'en',
    'Is walking 10k steps a day enough cardio?',
    'q/yesno | main | be other present - 3 | 10000 step |',
  ],
  ['en', "I don't feel like training today", 's | main | feel user present + 1 | | today'],
  [
    'en',
    'Do you think I should add a fifth day?',
    'q/yesno | main,sub:comp | think atlas present - 2 | |',
  ],
  ['en', 'Honestly the new plan is great', 's | main | be other present - 3 | |'],
  ['en', "I've never done a deadlift before", 's | main | do user past + 1 | |'],
  ['en', 'Nothing hurts today', 's | main | hurt other present + 3 | | today'],
  ['en', 'Show me my stats for last week', 'c | main | show atlas none - 2 | | last_week'],
  ['en', 'Can you track my swimming?', 'q/yesno | main | track atlas present - 2 | |'],
  [
    'en',
    "Why didn't you log my run yesterday?",
    'q/wh/why | main | log atlas past + 2 | | yesterday',
  ],
  [
    'en',
    "If you can't count dancing, what's the point of logging it?",
    'q/wh/what | sub:cond,main | be other present - 3 | |',
  ],
  [
    'en',
    'I squatted 3 sets of 5 at 100 kg, is that good for my weight?',
    'q/yesno | main,coord | squat user past - 1 | 3 set, 5 rep, 100 kg |',
  ],
  [
    'en',
    'how should i breathe during a heavy squat',
    'q/wh/how | main | breathe user present - 1 | |',
  ],
  [
    'en',
    'What happens if I skip leg day?',
    'q/wh/what | main,sub:cond | happen other present - 3 | |',
  ],
  [
    'en',
    'Is there a better alternative to barbell rows?',
    'q/yesno | main | be other present - 3 | |',
  ],
  ['en', 'I only have dumbbells at home', 's | main | have user present - 1 | |'],
  [
    'en',
    'I only have 30 minutes, what can I do?',
    'q/wh/what | main,coord | have user present - 1 | 30 min |',
  ],
  ['en', 'Make it harder', 'c | main | make atlas none - 2 | |'],
  ['en', 'I walked for 1.5 hours', 's | main | walk user past - 1 | 1.5 h |'],
  ['en', 'My wife says I train too much', 's | main,sub:comp | say other present - 3 | |'],
  [
    'en',
    'The coach told me that I should rest more',
    's | main,sub:comp | tell other past - 3 | |',
  ],
  ['en', 'I feel like my form is off', 's | main,sub:comp | feel user present - 1 | |'],
  [
    'en',
    "I was sick last week so I didn't train",
    's | main,coord | be user past - 1 | | last_week',
  ],
  ['en', 'Did you see my new max?', 'q/yesno | main | see atlas past - 2 | |'],
  [
    'en',
    'Have I improved since last month?',
    'q/yesno | main | improve user past - 1 | | last_month',
  ],
  ['en', 'Am I eating enough protein?', 'q/yesno | main | eat user present - 1 | |'],
  ['en', 'Are rest days important?', 'q/yesno | main | be other present - 3 | |'],
  ['en', 'Does running kill gains?', 'q/yesno | main | kill other present - 3 | |'],
  ['en', 'Was my volume too high this week?', 'q/yesno | main | be other past - 3 | | this_week'],
  ['en', 'Why am I always so sore after chest day?', 'q/wh/why | main | be user present - 1 | |'],
  [
    'en',
    'i did 45 min of cycling and 20 min rowing',
    's | main | do user past - 1 | 45 min, 20 min |',
  ],
  [
    'en',
    'Swimming 2 km takes me about 50 minutes',
    's | main | take other present - 3 | 2 km, 50 min |',
  ],
  [
    'en',
    'i want to build muscle but i also want to lose fat',
    's | main,coord | build user present - 1 | |',
  ],
  ['en', 'Help me plan my week', 'c | main | help atlas none - 2 | |'],
  ['en', 'Could I get a program for powerlifting?', 'q/yesno | main | get user present - 1 | |'],
  [
    'en',
    'How long does it take to see results?',
    'q/wh/how_long | main | take other present - 3 | |',
  ],
  ['en', 'How long did I run on Sunday?', 'q/wh/how_long | main | run user past - 1 | | sun'],
  [
    'en',
    'Which exercises target the rear delts?',
    'q/wh/which | main | target other present - 3 | |',
  ],
  ['en', 'Who should I ask about my diet?', 'q/wh/who | main | ask user present - 1 | |'],
  ['en', 'What if I train twice a day?', 'q/wh/what | main | train user present - 1 | 2 time |'],
  ['en', 'How about some mobility work today?', 'q/wh/what | main | - none none - 0 | | today'],
  ['en', 'What about cardio?', 'q/wh/what | main | - none none - 0 | |'],
  [
    'en',
    "I'm 35, is it too late to start lifting?",
    'q/yesno | main,coord | be user present - 1 | |',
  ],
  [
    'en',
    'I need a plan that fits 3 days a week',
    's | main,sub:rel | need user present - 1 | 3 day |',
  ],
  [
    'en',
    'The squat rack was busy so I did lunges instead',
    's | main,coord | be other past - 3 | |',
  ],
  ['en', 'Although you said to rest, I went for a run', 's | sub:conc,main | go user past - 1 | |'],
  [
    'en',
    'I went for a run even though you told me to rest',
    's | main,sub:conc | go user past - 1 | |',
  ],
  [
    'en',
    "Unless my back hurts I'll deadlift tomorrow",
    's | sub:cond,main | deadlift user future - 1 | | tomorrow',
  ],
  [
    'en',
    "I stretch so that I don't get injured",
    's | main,sub:purp | stretch user present - 1 | |',
  ],
  ['en', 'I eat oats in order to have energy', 's | main,sub:purp | eat user present - 1 | |'],
  ['en', 'My bench is heavier than my squat', 's | main | be other present - 3 | |'],
  [
    'en',
    'I lift more than I did last year',
    's | main,sub:compar | lift user present - 1 | | last_year',
  ],
  ['en', 'why u ignoring me', 'q/wh/why | main | ignore atlas present - 2 | |'],
  [
    'en',
    'yo atlas what should i train today',
    'q/wh/what | main | train user present - 1 | | today',
  ],
  ['en', 'lol ok', 's | main | - none none - 0 | |'],
  [
    'en',
    "Next week I'm traveling, can you adjust my plan?",
    'q/yesno | main,coord | travel user present - 1 | | next_week',
  ],
  [
    'en',
    "i've been doing this for months and nothing changes",
    's | main,coord | do user past - 1 | |',
  ],
  ['en', 'Is this a good weight to start with?', 'q/yesno | main | be other present - 3 | |'],
  [
    'en',
    'How much weight should I add each week?',
    'q/wh/how_much | main | add user present - 1 | |',
  ],
  ['en', 'It hurts', 's | main | hurt other present - 3 | |'],
  ['en', 'Walk me through a proper hip thrust', 'c | main | walk atlas none - 2 | |'],
  [
    'en',
    'Should I be worried about my heart rate at 180?',
    'q/yesno | main | be user present - 1 | |',
  ],
  ['en', 'My heart rate hit 180 bpm during sprints', 's | main | hit other past - 3 | 180 bpm |'],
  ['en', 'I keep failing at the lockout', 's | main | keep user present - 1 | |'],
  ['en', 'You are the best coach ever', 's | main | be atlas present - 2 | |'],
  ['en', 'stop', 'c | main | stop atlas none - 2 | |'],
  [
    'en',
    'so yesterday i did chest and triceps and today my shoulders are really sore is that normal',
    'q/yesno | main,coord,coord | do user past - 1 | | yesterday',
  ],
  ['en', 'i wanted to run but it rained', 's | main,coord | run user past - 1 | |'],
  [
    'en',
    'Before you answer, remember I have a bad knee',
    'c | sub:temp,main,sub:comp | remember atlas none - 2 | |',
  ],
  [
    'en',
    'What exercise can I do instead of squats if my knee hurts?',
    'q/wh/what | main,sub:cond | do user present - 1 | |',
  ],
  [
    'en',
    'is it better to train in the morning or evening',
    'q/choice | main | be other present - 3 | |',
  ],
  [
    'en',
    'I trained hard all week, I deserve a cheat meal, right?',
    'q/tag | main,coord | train user past - 1 | |',
  ],
  [
    'en',
    'My goal is to bench 100 kg by the end of the year',
    's | main | be other present - 3 | 100 kg |',
  ],
  ['en', 'Can you count dancing as cardio?', 'q/yesno | main | count atlas present - 2 | |'],
  ['en', 'I danced salsa for 90 minutes', 's | main | dance user past - 1 | 90 min |'],
  ['en', 'We did a 10 km hike on Saturday', 's | main | do user past - 1 | 10 km | sat'],
  [
    'en',
    'my coach wants me to squat 3 times a week',
    's | main | want other present - 3 | 3 time |',
  ],
  [
    'en',
    'Do squats work the glutes or just the quads?',
    'q/choice | main | work other present - 3 | |',
  ],
  [
    'en',
    'I feel dizzy when I stand up after squats',
    's | main,sub:temp | feel user present - 1 | |',
  ],
  ['en', 'Did I sleep enough last night?', 'q/yesno | main | sleep user past - 1 | | last_night'],
  ['en', 'Tomorrow I will try a new program', 's | main | try user future - 1 | | tomorrow'],
  [
    'en',
    "I couldn't finish the last set because my arms were shaking",
    's | main,sub:caus | finish user past + 1 | |',
  ],
  ['en', 'You never listen to me!', 'e | main | listen atlas present + 2 | |'],
  [
    'en',
    'Explain the difference between hypertrophy and strength training',
    'c | main | explain atlas none - 2 | |',
  ],

  // ───────────────────────── Ukrainian ─────────────────────────
  [
    'uk',
    'вчора пробіг 5 км а сьогодні ноги вбиті чи можна жим',
    'q/yesno | main,coord,coord | пробігти user past - 1 | 5 km | yesterday',
  ],
  [
    'uk',
    'якщо в мене болить коліно то що мені робити з присідом',
    'q/wh/what | sub:cond,main | робити user none - 1 | |',
  ],
  ['uk', 'скільки підходів робити на біцепс', 'q/wh/how_many | main | робити none none - 0 | |'],
  ['uk', 'Що їсти після тренування?', 'q/wh/what | main | їсти none none - 0 | |'],
  [
    'uk',
    'Чому в мене болить поперек після станової?',
    'q/wh/why | main | боліти other present - 3 | |',
  ],
  [
    'uk',
    'Чи можна тренувати ноги два дні поспіль?',
    'q/yesno | main | тренувати none present - 0 | 2 day |',
  ],
  [
    'uk',
    'Я вчора жав 100 кг на 5 разів',
    's | main | жати user past - 1 | 100 kg, 5 rep | yesterday',
  ],
  ['uk', 'Спочатку кардіо чи залізо?', 'q/choice | main | - none none - 0 | |'],
  ['uk', 'Ти не відповів на моє питання', 's | main | відповісти atlas past + 2 | |'],
  ['uk', 'Дай мені тренування на ноги', 'c | main | дати atlas none - 2 | |'],
  [
    'uk',
    'Склади план на цей тиждень будь ласка',
    'c | main | скласти atlas none - 2 | | this_week',
  ],
  [
    'uk',
    'Думаю, я перетренувався цього тижня',
    's | main,sub:comp | думати user present - 1 | | this_week',
  ],
  [
    'uk',
    'Коли присідаю, коліна зводяться всередину',
    's | sub:temp,main | зводитися other present - 3 | |',
  ],
  ['uk', 'Коли краще робити кардіо?', 'q/wh/when | main | робити none present - 0 | |'],
  [
    'uk',
    'Скільки відпочивати між підходами?',
    'q/wh/how_much | main | відпочивати none none - 0 | |',
  ],
  ['uk', 'Як часто качати прес?', 'q/wh/how_often | main | качати none none - 0 | |'],
  ['uk', 'Де ставити ноги на жимі ногами?', 'q/wh/where | main | ставити none none - 0 | |'],
  [
    'uk',
    'Що краще для маси: бруси чи жим лежачи?',
    'q/wh/what | main | краще other present - 3 | |',
  ],
  ['uk', 'Хто склав цю програму?', 'q/wh/who | main | скласти other past - 3 | |'],
  ['uk', 'Скільки білка мені треба на день?', 'q/wh/how_much | main | треба user present - 1 | |'],
  [
    'uk',
    "Чи погано тренуватися, коли болять м'язи?",
    'q/yesno | main,sub:temp | тренуватися none present - 0 | |',
  ],
  ['uk', 'Я вже три дні погано сплю', 's | main | спати user present - 1 | 3 day |'],
  ['uk', 'Плече болить, коли жму лежачи', 's | main,sub:temp | боліти other present - 3 | |'],
  ['uk', 'Завтра буду робити ноги', 's | main | робити user future - 1 | | tomorrow'],
  [
    'uk',
    'Сьогодні пропущу зал, бо дуже втомився',
    's | main,sub:caus | пропустити user future - 1 | | today',
  ],
  [
    'uk',
    'Хоча сплю по 8 годин, постійно втомлений',
    's | sub:conc,main | втомлений user present - 1 | 8 h |',
  ],
  [
    'uk',
    'Розкажи, як правильно робити станову',
    'c//how | main,sub:comp | розказати atlas none - 2 | |',
  ],
  [
    'uk',
    'Можеш пояснити, чому мій жим стоїть на місці?',
    'q/wh/why | main,sub:comp | пояснити atlas present - 2 | |',
  ],
  ['uk', 'Ти завжди ігноруєш моє кардіо', 's | main | ігнорувати atlas present - 2 | |'],
  [
    'uk',
    'Чому ти ніколи не рахуєш мої пробіжки?',
    'q/wh/why | main | рахувати atlas present + 2 | |',
  ],
  ['uk', 'Ура, новий рекорд у становій!', 'e | main | - none none - 0 | |'],
  ['uk', 'Давай сьогодні зробимо груди', 'c | main | зробити user none - 1 | | today'],
  [
    'uk',
    'Зробив 3 по 10 присідань з 80 кг',
    's | main | зробити user past - 1 | 3 set, 10 rep, 80 kg |',
  ],
  [
    'uk',
    'не знаю що їсти перед тренуванням',
    's//what | main,sub:comp | знати user present + 1 | |',
  ],
  ['uk', 'креатин безпечний?', 'q/yesno | main | безпечний other present - 3 | |'],
  ['uk', 'чи потрібен пояс для присідань', 'q/yesno | main | потрібний other present - 3 | |'],
  ['uk', 'спина просто вбиває', 's | main | вбивати other present - 3 | |'],
  [
    'uk',
    'Займаюсь уже 2 роки, але жим досі слабкий',
    's | main,coord | займатися user present - 1 | 2 year |',
  ],
  [
    'uk',
    'Розтягуватись до чи після тренування?',
    'q/choice | main | розтягуватися none none - 0 | |',
  ],
  ['uk', 'Як виправити глибину присіду?', 'q/wh/how | main | виправити none none - 0 | |'],
  [
    'uk',
    'Який спліт кращий на 4 дні на тиждень?',
    'q/wh/which | main | кращий other present - 3 | 4 day |',
  ],
  ['uk', 'Не можу підтягнутися жодного разу', 's | main | підтягнутися user present + 1 | |'],
  ['uk', 'Можеш дати мені розминку?', 'q/yesno | main | дати atlas present - 2 | |'],
  ['uk', 'Хочу скинути 5 кг до літа', 's | main | скинути user present - 1 | 5 kg |'],
  [
    'uk',
    "Якщо їстиму більше білка, я швидше наберу м'язи?",
    'q/yesno | sub:cond,main | набрати user future - 1 | |',
  ],
  ['uk', 'Перестань казати мені відпочивати', 'c | main | перестати atlas none - 2 | |'],
  ['uk', 'Я не про це питав', 's | main | питати user past + 1 | |'],
  [
    'uk',
    'Ноги болять після вчорашнього тренування',
    's | main | боліти other present - 3 | | yesterday',
  ],
  ['uk', '6 годин сну достатньо?', 'q/yesno | main | достатньо other present - 3 | 6 h |'],
  [
    'uk',
    'Скільки калорій їсти, щоб схуднути?',
    'q/wh/how_many | main,sub:purp | їсти none none - 0 | |',
  ],
  ['uk', 'Хочу накачати великі руки', 's | main | накачати user present - 1 | |'],
  ['uk', 'Що ти думаєш про мою програму?', 'q/wh/what | main | думати atlas present - 2 | |'],
  [
    'uk',
    'ти сказав відпочивати але я почуваюсь норм',
    's | main,coord | сказати atlas past - 2 | |',
  ],
  ['uk', 'Програма, яку ти дав, занадто важка', 's | main,sub:rel | важкий other present - 3 | |'],
  [
    'uk',
    'Тренуюсь у залі, який біля роботи',
    's | main,sub:rel | тренуватися user present - 1 | |',
  ],
  ['uk', 'Коли мені робити розвантаження?', 'q/wh/when | main | робити user none - 1 | |'],
  [
    'uk',
    'Пропустив два тренування цього тижня, тому почуваюся винним',
    's | main,coord | пропустити user past - 1 | 2 session | this_week',
  ],
  [
    'uk',
    'Це нормально, що коліна хрустять?',
    'q/yesno | main,sub:comp | нормально other present - 3 | |',
  ],
  ['uk', 'зараз важу 85 кг і хочу сушитись', 's | main | важити user present - 1 | 85 kg | now'],
  ['uk', 'ненавиджу берпі', 's | main | ненавидіти user present - 1 | |'],
  ['uk', 'можеш зробити тренування коротшим плз', 'q/yesno | main | зробити atlas present - 2 | |'],
  ['uk', 'як правильно робити віджимання', 'q/wh/how | main | робити none none - 0 | |'],
  [
    'uk',
    'яка різниця між румунською і класичною становою',
    'q/wh/which | main | - other present - 3 | |',
  ],
  [
    'uk',
    'Вчора не пішов у зал, бо син захворів',
    's | main,sub:caus | піти user past + 1 | | yesterday',
  ],
  ['uk', "Після тренування зазвичай п'ю протеїн", 's | main | пити user present - 1 | |'],
  ['uk', "Коли закінчую тренування, п'ю протеїн", 's | sub:temp,main | пити user present - 1 | |'],
  [
    'uk',
    'Чому я не можу пожати більше 60 кг?',
    'q/wh/why | main | пожати user present + 1 | 60 kg |',
  ],
  [
    'uk',
    'Звідки ти знаєш, скільки я підняв?',
    'q/wh/where | main,sub:comp | знати atlas present - 2 | |',
  ],
  [
    'uk',
    "Ти пам'ятаєш мій максимум у присіді?",
    "q/yesno | main | пам'ятати atlas present - 2 | |",
  ],
  [
    'uk',
    'Не впевнений, чи варто сьогодні йти важко',
    's | main,sub:comp | впевнений user present + 1 | | today',
  ],
  [
    'uk',
    'Спав 5 годин, чи варто тренуватися?',
    'q/yesno | main,coord | спати user past - 1 | 5 h |',
  ],
  ['uk', 'Класне тренування сьогодні!', 'e | main | - none none - 0 | | today'],
  ['uk', 'Дякую, це допомогло', 's | main | допомогти other past - 3 | |'],
  ['uk', 'Ти помиляєшся щодо відпочинку', 's | main | помилятися atlas present - 2 | |'],
  ['uk', 'А чому ні?', 'q/wh/why | main | - none none - 0 | |'],
  ['uk', 'Та кому той прес потрібен?', 'q/rhetorical/who | main | потрібний other present - 3 | |'],
  ['uk', 'Ти ж рахуєш мій сон, так?', 'q/tag | main | рахувати atlas present - 2 | |'],
  [
    'uk',
    'Додай 5 кг до присіду наступного тижня',
    'c | main | додати atlas none - 2 | 5 kg | next_week',
  ],
  ['uk', 'Не давай мені більше днів відпочинку', 'c | main | давати atlas none + 2 | |'],
  ['uk', 'Я роблю віджимання щодня', 's | main | робити user present - 1 | |'],
  [
    'uk',
    "Чи втрачу я м'язи, якщо зроблю перерву на тиждень?",
    'q/yesno | main,sub:cond | втратити user future - 1 | |',
  ],
  ['uk', 'Через 3 місяці пробіжу півмарафон', 's | main | пробігти user future - 1 | 3 month |'],
  [
    'uk',
    'нормально качати прес кожен день чи це забагато',
    'q/choice | main,coord | качати none present - 0 | |',
  ],
  [
    'uk',
    'коліно болить, можна ще присідати?',
    'q/yesno | main,coord | боліти other present - 3 | |',
  ],
  ['uk', 'Присідаю 120, але жим 80 не можу', 's | main | присідати user present - 1 | |'],
  ['uk', "Які м'язи працюють у випадах?", 'q/wh/which | main | працювати other present - 3 | |'],
  ['uk', 'Скільки має бути моя станова?', 'q/wh/how_much | main | бути other present - 3 | |'],
  [
    'uk',
    "Сьогодні з'їв 3000 калорій і відчуваю здуття",
    "s | main | з'їсти user past - 1 | 3000 kcal | today",
  ],
  [
    'uk',
    'Коли роблю жим стоячи, щоразу клацає плече',
    's | sub:temp,main | клацати other present - 3 | |',
  ],
  ['uk', "Відколи п'ю креатин, набрав 2 кг", 's | sub:temp,main | набрати user past - 1 | 2 kg |'],
  ['uk', 'Раз ти тренер, то вирішуй', 'c | sub:caus,main | вирішувати atlas none - 2 | |'],
  [
    'uk',
    'Я втомився, тож сьогодні зроблю коротке тренування',
    's | main,coord | втомитися user past - 1 | | today',
  ],
  [
    'uk',
    'Надто спекотно, щоб бігати на вулиці',
    's | main,sub:purp | спекотно none present - 0 | |',
  ],
  ['uk', 'Де мій графік прогресу?', 'q/wh/where | main | - other present - 3 | |'],
  ['uk', 'О котрій лягати спати для відновлення?', 'q/wh/when | main | лягати none none - 0 | |'],
  [
    'uk',
    '10 тисяч кроків на день — це достатньо кардіо?',
    'q/yesno | main | достатньо other present - 3 | 10000 step |',
  ],
  ['uk', 'Сьогодні не хочеться тренуватися', 's | main | тренуватися none present + 0 | | today'],
  [
    'uk',
    "Думаєш, варто додати п'ятий день?",
    'q/yesno | main,sub:comp | думати atlas present - 2 | |',
  ],
  ['uk', 'Чесно, нова програма супер', 's | main | супер other present - 3 | |'],
  ['uk', 'Ніколи не робив станову', 's | main | робити user past + 1 | |'],
  ['uk', 'Сьогодні нічого не болить', 's | main | боліти other present + 3 | | today'],
  [
    'uk',
    'Покажи мою статистику за минулий тиждень',
    'c | main | показати atlas none - 2 | | last_week',
  ],
  ['uk', 'Ти можеш рахувати плавання?', 'q/yesno | main | рахувати atlas present - 2 | |'],
  [
    'uk',
    'Чому ти не записав мою пробіжку вчора?',
    'q/wh/why | main | записати atlas past + 2 | | yesterday',
  ],
  [
    'uk',
    'Якщо ти не рахуєш танці, навіщо тоді їх записувати?',
    'q/wh/why | sub:cond,main | записувати none none - 0 | |',
  ],
  [
    'uk',
    'Присів 3 підходи по 5 зі 100 кг, це добре для моєї ваги?',
    'q/yesno | main,coord | присісти user past - 1 | 3 set, 5 rep, 100 kg |',
  ],
  [
    'uk',
    'як правильно дихати під час важкого присіду',
    'q/wh/how | main | дихати none none - 0 | |',
  ],
  [
    'uk',
    'Що буде, якщо пропустити день ніг?',
    'q/wh/what | main,sub:cond | бути other future - 3 | |',
  ],
  ['uk', 'Є краща заміна тязі штанги в нахилі?', 'q/yesno | main | бути other present - 3 | |'],
  ['uk', 'Вдома в мене тільки гантелі', 's | main | - other present - 3 | |'],
  [
    'uk',
    'Маю лише 30 хвилин, що можна зробити?',
    'q/wh/what | main,coord | мати user present - 1 | 30 min |',
  ],
  ['uk', 'Зроби складніше', 'c | main | зробити atlas none - 2 | |'],
  [
    'uk',
    'Дружина каже, що я забагато тренуюсь',
    's | main,sub:comp | казати other present - 3 | |',
  ],
  ['uk', 'Тренер сказав мені більше відпочивати', 's | main | сказати other past - 3 | |'],
  ['uk', 'Відчуваю, що техніка поїхала', 's | main,sub:comp | відчувати user present - 1 | |'],
  [
    'uk',
    'Минулого тижня хворів, тому не тренувався',
    's | main,coord | хворіти user past - 1 | | last_week',
  ],
  ['uk', 'Ти бачив мій новий максимум?', 'q/yesno | main | бачити atlas past - 2 | |'],
  [
    'uk',
    'Я прогресую з минулого місяця?',
    'q/yesno | main | прогресувати user present - 1 | | last_month',
  ],
  ['uk', 'Я їм достатньо білка?', 'q/yesno | main | їсти user present - 1 | |'],
  ['uk', 'Дні відпочинку важливі?', 'q/yesno | main | важливий other present - 3 | |'],
  ['uk', "Біг вбиває м'язи?", 'q/yesno | main | вбивати other present - 3 | |'],
  [
    'uk',
    'Чому після дня грудей у мене все болить?',
    'q/wh/why | main | боліти other present - 3 | |',
  ],
  [
    'uk',
    'покрутив 45 хв велик і 20 хв гріб',
    's | main | покрутити user past - 1 | 45 min, 20 min |',
  ],
  ['uk', "Хочу набрати м'язи, але й скинути жир", 's | main | набрати user present - 1 | |'],
  ['uk', 'Допоможи спланувати тиждень', 'c | main | допомогти atlas none - 2 | |'],
  [
    'uk',
    'Скільки часу треба, щоб побачити результат?',
    'q/wh/how_long | main,sub:purp | треба none present - 0 | |',
  ],
  ['uk', 'Скільки я бігав у неділю?', 'q/wh/how_much | main | бігати user past - 1 | | sun'],
  ['uk', 'Які вправи на задню дельту?', 'q/wh/which | main | - other present - 3 | |'],
  ['uk', 'А як щодо кардіо?', 'q/wh/what | main | - none none - 0 | |'],
  [
    'uk',
    'Потрібен план, який підходить під 3 дні на тиждень',
    's | main,sub:rel | потрібний other present - 3 | 3 day |',
  ],
  ['uk', 'Стійка була зайнята, тому робив випади', 's | main,coord | бути other past - 3 | |'],
  ['uk', 'Хоч ти й казав відпочити, я пішов бігати', 's | sub:conc,main | піти user past - 1 | |'],
  [
    'uk',
    'Пішов на пробіжку, хоча ти сказав відпочивати',
    's | main,sub:conc | піти user past - 1 | |',
  ],
  [
    'uk',
    'Якщо спина не болітиме, завтра зроблю станову',
    's | sub:cond,main | зробити user future - 1 | | tomorrow',
  ],
  [
    'uk',
    'Розтягуюся, щоб не травмуватися',
    's | main,sub:purp | розтягуватися user present - 1 | |',
  ],
  ['uk', 'Мій жим більший, ніж присід', 's | main | більший other present - 3 | |'],
  ['uk', 'Піднімаю більше, ніж торік', 's | main | піднімати user present - 1 | | last_year'],
  ['uk', 'чого ти мене ігноруєш', 'q/wh/why | main | ігнорувати atlas present - 2 | |'],
  [
    'uk',
    'атлас що мені сьогодні тренувати',
    'q/wh/what | main | тренувати user none - 1 | | today',
  ],
  [
    'uk',
    'Наступного тижня їду у відрядження, можеш підлаштувати план?',
    'q/yesno | main,coord | їхати user present - 1 | | next_week',
  ],
  [
    'uk',
    'займаюсь вже кілька місяців і нічого не міняється',
    's | main,coord | займатися user present - 1 | |',
  ],
  ['uk', 'Болить', 's | main | боліти other present - 3 | |'],
  [
    'uk',
    'Поясни, як робити ягодичний міст',
    'c//how | main,sub:comp | пояснити atlas none - 2 | |',
  ],
  [
    'uk',
    'Чи варто хвилюватися через пульс 180?',
    'q/yesno | main | хвилюватися none present - 0 | |',
  ],
  [
    'uk',
    'Пульс піднявся до 180 ударів на спринтах',
    's | main | піднятися other past - 3 | 180 bpm |',
  ],
  ['uk', 'Постійно не можу дотиснути в кінці', 's | main | дотиснути user present + 1 | |'],
  ['uk', 'Ти найкращий тренер', 's | main | найкращий atlas present - 2 | |'],
  [
    'uk',
    'короче вчора зробив груди і трицепс а сьогодні плечі дуже болять це нормально',
    'q/yesno | main,coord,coord | зробити user past - 1 | | yesterday',
  ],
  ['uk', 'Хотів бігати, але пішов дощ', 's | main,coord | бігати user past - 1 | |'],
  [
    'uk',
    "Перш ніж відповіси, пам'ятай, що в мене погане коліно",
    "c | sub:temp,main,sub:comp | пам'ятати atlas none - 2 | |",
  ],
  [
    'uk',
    'Яку вправу можна робити замість присідань, якщо болить коліно?',
    'q/wh/which | main,sub:cond | робити none present - 0 | |',
  ],
  [
    'uk',
    'краще тренуватися зранку чи ввечері',
    'q/choice | main | тренуватися none present - 0 | |',
  ],
  [
    'uk',
    'Цілий тиждень тренувався, заслужив читмил, так?',
    'q/tag | main | тренуватися user past - 1 | |',
  ],
  [
    'uk',
    'Моя мета — пожати 100 кг до кінця року',
    's | main | пожати other present - 3 | 100 kg |',
  ],
  ['uk', 'Можеш зарахувати танці як кардіо?', 'q/yesno | main | зарахувати atlas present - 2 | |'],
  ['uk', 'Танцював сальсу 90 хвилин', 's | main | танцювати user past - 1 | 90 min |'],
  [
    'uk',
    'Я сьогодні протанцювала дві години, чому ти це не коментуєш?',
    'q/wh/why | main,coord | протанцювати user past - 1 | 2 h | today',
  ],
  [
    'uk',
    'Скільки разів на тиждень треба тренувати спину?',
    'q/wh/how_many | main | тренувати none present - 0 | |',
  ],
  ['uk', 'Ми з другом у суботу пройшли 10 км', 's | main | пройти user past - 1 | 10 km | sat'],
  [
    'uk',
    'Тренер хоче, щоб я присідав тричі на тиждень',
    's | main,sub:comp | хотіти other present - 3 | 3 time |',
  ],
  [
    'uk',
    'Присідання качають сідниці чи тільки квадрицепс?',
    'q/choice | main | качати other present - 3 | |',
  ],
  [
    'uk',
    'Паморочиться голова, коли встаю після присідань',
    's | main,sub:temp | паморочитися other present - 3 | |',
  ],
  ['uk', 'Я вчора достатньо спав?', 'q/yesno | main | спати user past - 1 | | yesterday'],
  ['uk', 'Завтра спробую нову програму', 's | main | спробувати user future - 1 | | tomorrow'],
  [
    'uk',
    'Не зміг закінчити останній підхід, бо тремтіли руки',
    's | main,sub:caus | закінчити user past + 1 | |',
  ],
  ['uk', 'Ти мене ніколи не слухаєш!', 'e | main | слухати atlas present + 2 | |'],
  [
    'uk',
    'Поясни різницю між гіпертрофією і силовим тренуванням',
    'c | main | пояснити atlas none - 2 | |',
  ],
  [
    'uk',
    'Я займаюся в залі три рази на тиждень',
    's | main | займатися user present - 1 | 3 time |',
  ],
  [
    'uk',
    'Скільки треба спати, щоб відновлюватися?',
    'q/wh/how_much | main,sub:purp | спати none present - 0 | |',
  ],
  [
    'uk',
    'Ти порахував мій біг за вчора?',
    'q/yesno | main | порахувати atlas past - 2 | | yesterday',
  ],
  [
    'uk',
    'Мені здається, що я погано відновлююсь',
    's | main,sub:comp | здаватися user present - 1 | |',
  ],
  ['uk', 'Я вийшов на пробіжку о шостій ранку', 's | main | вийти user past - 1 | |'],
  [
    'uk',
    'Скажи чесно, в мене погана техніка?',
    'q/yesno | main,coord | сказати atlas none - 2 | |',
  ],
  [
    'uk',
    'У понеділок я присідав 90 кг на 6 повторень',
    's | main | присідати user past - 1 | 90 kg, 6 rep | mon',
  ],
  ['uk', 'Треба більше спати чи більше їсти?', 'q/choice | main | спати none present - 0 | |'],
  [
    'uk',
    'Як довго триває відновлення після марафону?',
    'q/wh/how_long | main | тривати other present - 3 | |',
  ],

  // ───────────────── Russian / surzhyk / transliteration ─────────────────
  [
    'ru',
    'Вчера пробежал 10 км, сегодня ноги болят',
    's | main,coord | пробежать user past - 1 | 10 km | yesterday',
  ],
  ['ru', 'Сколько подходов делать на бицепс?', 'q/wh/how_many | main | делать none none - 0 | |'],
  [
    'ru',
    'Почему у меня болит поясница после становой?',
    'q/wh/why | main | болеть other present - 3 | |',
  ],
  [
    'ru',
    'Можно ли тренироваться каждый день?',
    'q/yesno | main | тренироваться none present - 0 | |',
  ],
  [
    'ru',
    'Я вчера жал 100 кг на 8 раз',
    's | main | жать user past - 1 | 100 kg, 8 rep | yesterday',
  ],
  [
    'ru',
    'Что лучше для похудения: бег или велосипед?',
    'q/wh/what | main | лучше other present - 3 | |',
  ],
  ['ru', 'Ты не ответил на мой вопрос', 's | main | ответить atlas past + 2 | |'],
  ['ru', 'Составь мне программу на неделю', 'c | main | составить atlas none - 2 | |'],
  [
    'ru',
    'Если болит колено, что делать с приседом?',
    'q/wh/what | sub:cond,main | делать none none - 0 | |',
  ],
  ['ru', 'Завтра буду делать ноги', 's | main | делать user future - 1 | | tomorrow'],
  [
    'ru',
    'Не знаю, что есть перед тренировкой',
    's//what | main,sub:comp | знать user present + 1 | |',
  ],
  ['ru', 'Как правильно делать становую тягу?', 'q/wh/how | main | делать none none - 0 | |'],
  ['ru', 'Когда лучше делать кардио?', 'q/wh/when | main | делать none present - 0 | |'],
  [
    'ru',
    'Сегодня пропущу зал, потому что очень устал',
    's | main,sub:caus | пропустить user future - 1 | | today',
  ],
  ['ru', 'Ты же считаешь мой сон, да?', 'q/tag | main | считать atlas present - 2 | |'],
  [
    'ru',
    'Почему ты не считаешь мои тренировки?',
    'q/wh/why | main | считать atlas present + 2 | |',
  ],
  ['ru', 'Сколько белка мне нужно в день?', 'q/wh/how_much | main | нужно user present - 1 | |'],
  ['ru', 'Хочу сбросить 5 кг к лету', 's | main | сбросить user present - 1 | 5 kg |'],
  ['ru', 'Где ставить ноги в жиме ногами?', 'q/wh/where | main | ставить none none - 0 | |'],
  [
    'ru',
    'Я сделал 3 подхода по 12 повторений',
    's | main | сделать user past - 1 | 3 set, 12 rep |',
  ],
  ['sz', 'шо робить якщо болить спина', 'q/wh/what | main,sub:cond | робити none none - 0 | |'],
  [
    'sz',
    'я вчора хотів качать спину но не було сил',
    's | main,coord | качати user past - 1 | | yesterday',
  ],
  [
    'sz',
    'скільки раз в неділю треба качать прес',
    'q/wh/how_many | main | качати none present - 0 | |',
  ],
  ['sz', 'сьогодні ноги болять шо капец', 's | main | боліти other present - 3 | | today'],
  [
    'sz',
    'короче зробив присід 100 на 5 нормально чи ні',
    'q/yesno | main,coord | зробити user past - 1 | 100 kg, 5 rep |',
  ],
  ['sz', 'мені нада больше білка чи ні', 'q/yesno | main | надо user present - 1 | |'],
  [
    'sz',
    'чого в мене так болять ікри після бігу',
    'q/wh/why | main | боліти other present - 3 | |',
  ],
  ['sz', 'ти вообще рахуєш мої тренування?', 'q/yesno | main | рахувати atlas present - 2 | |'],
  [
    'uk-tr',
    'vchora probig 5 km a sogodni nogy vbyti chy mozhna zhym',
    'q/yesno | main,coord,coord | пробігти user past - 1 | 5 km | yesterday',
  ],
  ['uk-tr', 'skilky pidhodiv robyty na biceps', 'q/wh/how_many | main | робити none none - 0 | |'],
  ['uk-tr', 'chomu v mene bolyt kolino', 'q/wh/why | main | боліти other present - 3 | |'],
  ['uk-tr', 'shcho yisty pislia trenuvannia', 'q/wh/what | main | їсти none none - 0 | |'],
  [
    'uk-tr',
    'ya ne znayu yak robyty stanovu',
    's//how | main,sub:comp | знати user present + 1 | |',
  ],
  ['uk-tr', 'daj meni plan na tyzhden', 'c | main | дати atlas none - 2 | |'],
  [
    'uk-tr',
    'chy mozhna trenuvatys kozhen den',
    'q/yesno | main | тренуватися none present - 0 | |',
  ],
  [
    'uk-tr',
    'zrobyv 3 pidhody po 10 prysidan',
    's | main | зробити user past - 1 | 3 set, 10 rep |',
  ],
  ['uk-tr', 'zavtra budu robyty nogy', 's | main | робити user future - 1 | | tomorrow'],
  ['uk-tr', 'ty ne vidpoviv na moie pytannia', 's | main | відповісти atlas past + 2 | |'],
  ['ru-tr', 'kak pravilno delat prised', 'q/wh/how | main | делать none none - 0 | |'],
  [
    'ru-tr',
    'segodnya ne hochu trenirovatsya',
    's | main | тренироваться user present + 1 | | today',
  ],

  // ───────────────────────── Polish ─────────────────────────
  [
    'pl',
    'Wczoraj przebiegłem 5 km, a dziś bolą mnie nogi',
    's | main,coord | przebiec user past - 1 | 5 km | yesterday',
  ],
  ['pl', 'Ile serii robić na biceps?', 'q/wh/how_many | main | robić none none - 0 | |'],
  [
    'pl',
    'Dlaczego boli mnie kolano po przysiadach?',
    'q/wh/why | main | boleć other present - 3 | |',
  ],
  [
    'pl',
    'Czy mogę trenować nogi dwa dni z rzędu?',
    'q/yesno | main | trenować user present - 1 | 2 day |',
  ],
  ['pl', 'Co jeść po treningu?', 'q/wh/what | main | jeść none none - 0 | |'],
  ['pl', 'Nie odpowiedziałeś na moje pytanie', 's | main | odpowiedzieć atlas past + 2 | |'],
  ['pl', 'Daj mi plan na ten tydzień', 'c | main | dać atlas none - 2 | | this_week'],
  ['pl', 'Jutro będę robić nogi', 's | main | robić user future - 1 | | tomorrow'],
  [
    'pl',
    'Jeśli boli mnie kolano, co mam robić z przysiadem?',
    'q/wh/what | sub:cond,main | robić user present - 1 | |',
  ],
  [
    'pl',
    'Zrobiłem 3 serie po 10 powtórzeń ze 100 kg',
    's | main | zrobić user past - 1 | 3 set, 10 rep, 100 kg |',
  ],
  [
    'pl',
    'Nie wiem, co jeść przed treningiem',
    's//what | main,sub:comp | wiedzieć user present + 1 | |',
  ],
  ['pl', 'Kiedy najlepiej robić cardio?', 'q/wh/when | main | robić none present - 0 | |'],
  ['pl', 'Jak często trenować brzuch?', 'q/wh/how_often | main | trenować none none - 0 | |'],
  ['pl', 'Czy kreatyna jest bezpieczna?', 'q/yesno | main | być other present - 3 | |'],
  [
    'pl',
    'Dzisiaj nie idę na siłownię, bo jestem zmęczony',
    's | main,sub:caus | iść user present + 1 | | today',
  ],
  ['pl', 'Chcę schudnąć 5 kg do lata', 's | main | schudnąć user present - 1 | 5 kg |'],
  ['pl', 'Dlaczego nie liczysz moich treningów?', 'q/wh/why | main | liczyć atlas present + 2 | |'],
  [
    'pl',
    'Ile białka potrzebuję dziennie?',
    'q/wh/how_much | main | potrzebować user present - 1 | |',
  ],
  ['pl', 'Pokaż mi moje statystyki', 'c | main | pokazać atlas none - 2 | |'],
  [
    'pl',
    'Tańczyłam dwie godziny, dlaczego tego nie komentujesz?',
    'q/wh/why | main,coord | tańczyć user past - 1 | 2 h |',
  ],

  // ───────────────────────── Lithuanian ─────────────────────────
  [
    'lt',
    'Vakar nubėgau 5 km, o šiandien skauda kojas',
    's | main,coord | nubėgti user past - 1 | 5 km | yesterday',
  ],
  ['lt', 'Kiek serijų daryti bicepsui?', 'q/wh/how_many | main | daryti none none - 0 | |'],
  [
    'lt',
    'Kodėl man skauda nugarą po treniruotės?',
    'q/wh/why | main | skaudėti user present - 1 | |',
  ],
  [
    'lt',
    'Ar galiu treniruoti kojas dvi dienas iš eilės?',
    'q/yesno | main | treniruoti user present - 1 | 2 day |',
  ],
  ['lt', 'Ką valgyti po treniruotės?', 'q/wh/what | main | valgyti none none - 0 | |'],
  ['lt', 'Tu neatsakei į mano klausimą', 's | main | atsakyti atlas past + 2 | |'],
  ['lt', 'Duok man planą šiai savaitei', 'c | main | duoti atlas none - 2 | | this_week'],
  ['lt', 'Rytoj darysiu kojas', 's | main | daryti user future - 1 | | tomorrow'],
  [
    'lt',
    'Jei skauda kelį, ką daryti su pritūpimais?',
    'q/wh/what | sub:cond,main | daryti none none - 0 | |',
  ],
  [
    'lt',
    'Padariau 3 serijas po 10 kartų su 100 kg',
    's | main | padaryti user past - 1 | 3 set, 10 rep, 100 kg |',
  ],
  [
    'lt',
    'Nežinau, ką valgyti prieš treniruotę',
    's//what | main,sub:comp | žinoti user present + 1 | |',
  ],
  ['lt', 'Kada geriausia daryti kardio?', 'q/wh/when | main | daryti none present - 0 | |'],
  ['lt', 'Kaip dažnai treniruoti presą?', 'q/wh/how_often | main | treniruoti none none - 0 | |'],
  ['lt', 'Ar kreatinas saugus?', 'q/yesno | main | saugus other present - 3 | |'],
  [
    'lt',
    'Šiandien neisiu į sporto salę, nes esu pavargęs',
    's | main,sub:caus | eiti user future + 1 | | today',
  ],
  ['lt', 'Noriu numesti 5 kg iki vasaros', 's | main | numesti user present - 1 | 5 kg |'],
  [
    'lt',
    'Kodėl neskaičiuoji mano treniruočių?',
    'q/wh/why | main | skaičiuoti atlas present + 2 | |',
  ],
  [
    'lt',
    'Kiek baltymų man reikia per dieną?',
    'q/wh/how_much | main | reikėti user present - 1 | |',
  ],
  ['lt', 'Parodyk mano statistiką', 'c | main | parodyti atlas none - 2 | |'],
  [
    'lt',
    'Šokau dvi valandas, kodėl nekomentuoji?',
    'q/wh/why | main,coord | šokti user past - 1 | 2 h |',
  ],

  // ───────────────────────── Estonian ─────────────────────────
  [
    'et',
    'Eile jooksin 5 km ja täna on jalad valusad',
    's | main,coord | jooksma user past - 1 | 5 km | yesterday',
  ],
  ['et', 'Mitu seeriat biitsepsile teha?', 'q/wh/how_many | main | tegema none none - 0 | |'],
  [
    'et',
    'Miks mul selg pärast jõutõmmet valutab?',
    'q/wh/why | main | valutama other present - 3 | |',
  ],
  [
    'et',
    'Kas ma võin jalgu kaks päeva järjest treenida?',
    'q/yesno | main | treenima user present - 1 | 2 day |',
  ],
  ['et', 'Mida pärast trenni süüa?', 'q/wh/what | main | sööma none none - 0 | |'],
  ['et', 'Sa ei vastanud mu küsimusele', 's | main | vastama atlas past + 2 | |'],
  ['et', 'Anna mulle selle nädala plaan', 'c | main | andma atlas none - 2 | | this_week'],
  ['et', 'Homme teen jalgu', 's | main | tegema user present - 1 | | tomorrow'],
  [
    'et',
    'Kui põlv valutab, mida kükkidega teha?',
    'q/wh/what | sub:cond,main | tegema none none - 0 | |',
  ],
  [
    'et',
    'Tegin 3 seeriat 10 kordust 100 kg-ga',
    's | main | tegema user past - 1 | 3 set, 10 rep, 100 kg |',
  ],
  [
    'et',
    'Ma ei tea, mida enne trenni süüa',
    's//what | main,sub:comp | teadma user present + 1 | |',
  ],
  ['et', 'Millal on parim aeg kardiot teha?', 'q/wh/when | main | olema other present - 3 | |'],
  ['et', 'Kui tihti kõhulihaseid treenida?', 'q/wh/how_often | main | treenima none none - 0 | |'],
  ['et', 'Kas kreatiin on ohutu?', 'q/yesno | main | olema other present - 3 | |'],
  [
    'et',
    'Täna ma jõusaali ei lähe, sest olen väsinud',
    's | main,sub:caus | minema user present + 1 | | today',
  ],
  ['et', 'Tahan suveks 5 kg alla võtta', 's | main | võtma user present - 1 | 5 kg |'],
  ['et', 'Miks sa mu treeninguid ei loe?', 'q/wh/why | main | lugema atlas present + 2 | |'],
  [
    'et',
    'Kui palju valku mul päevas vaja on?',
    'q/wh/how_much | main | olema user present - 1 | |',
  ],
  ['et', 'Näita mu statistikat', 'c | main | näitama atlas none - 2 | |'],
  [
    'et',
    'Tantsisin kaks tundi, miks sa seda ei kommenteeri?',
    'q/wh/why | main,coord | tantsima user past - 1 | 2 h |',
  ],
];

/** Sentence splitting: message → expected sentence count. */
export const GOLD_SPLIT: [string, number][] = [
  ['can i swap bench for push ups today? my shoulder is sore', 2],
  ['Did squats today. Knees fine. What next?', 3],
  ['Вчора пробіг 5 км. Сьогодні болять ноги! Що робити?', 3],
  ['ok thanks', 1],
  ['I lifted 2.5 kg more than last week. Nice!', 2],
  ['Привіт! Як справи?', 2],
  ['Що таке RPE? І як його рахувати?', 2],
  ['hey atlas\nwhat should i do today', 2],
  ['I did 3x10... felt heavy', 1],
  ['Спав 5 год. Тренуватись чи ні?', 2],
  ['Zrobiłem trening. Co dalej?', 2],
  ['Täna tegin trenni. Mis edasi?', 2],
  ['Šiandien sportavau. Ką daryti toliau?', 2],
  ['💪💪 did it!!! new PR', 2],
  ['My max is 102.5kg. Is that good?', 2],
  ['ok. so. what now?', 3],
  ['лол) ну ок', 1],
  ['What?! You forgot my run', 2],
  ['Жим 82,5 кг на 5. Норм?', 2],
  ['e.g. squats and lunges are fine', 1],
];
