/**
 * HELD-OUT set: written after the analyser was tuned on gold.ts and scored
 * once, blind. Same format and guidelines as gold.ts. Its first-run numbers are
 * the honest estimate of accuracy on unseen chat messages.
 */
import type { GoldRow } from './gold';

export const HOLDOUT: GoldRow[] = [
  [
    'en',
    'My elbows hurt when I do skull crushers',
    's | main,sub:temp | hurt other present - 3 | |',
  ],
  [
    'en',
    "What's the best way to warm up before squats?",
    'q/wh/what | main | be other present - 3 | |',
  ],
  ['en', 'i skipped breakfast and now i feel weak', 's | main,coord | skip user past - 1 | | now'],
  ['en', 'Can you add a rest day on Wednesday?', 'q/yesno | main | add atlas present - 2 | | wed'],
  ['en', 'Why do my calves cramp at night?', 'q/wh/why | main | cramp other present - 3 | |'],
  ['en', "I've lost 3 kg since last month", 's | main | lose user past - 1 | 3 kg | last_month'],
  [
    'en',
    'How many rest days do I need per week?',
    'q/wh/how_many | main | need user present - 1 | |',
  ],
  ['en', "Don't count my walks as workouts", 'c | main | count atlas none + 2 | |'],
  [
    'en',
    'The app crashed while I was logging my sets',
    's | main,sub:temp | crash other past - 3 | |',
  ],
  ['en', 'Should I eat carbs before a morning run?', 'q/yesno | main | eat user present - 1 | |'],
  ['en', "I'm not sure my form is right", 's | main,sub:comp | be user present + 1 | |'],
  ['en', 'Which muscles does the plank train?', 'q/wh/which | main | train other present - 3 | |'],
  [
    'en',
    'yesterday was leg day and i can barely walk',
    's | main,coord | be other past - 3 | | yesterday',
  ],
  ['en', 'Give me three exercises for my lower back', 'c | main | give atlas none - 2 | |'],
  ['en', 'Is it okay if I train fasted?', 'q/yesno | main,sub:cond | be other present - 3 | |'],
  [
    'en',
    'You keep suggesting burpees even though I hate them',
    's | main,sub:conc | keep atlas present - 2 | |',
  ],
  ['en', 'When will I see abs?', 'q/wh/when | main | see user future - 1 | |'],
  [
    'en',
    "I bench 3 times a week but my chest isn't growing",
    's | main,coord | bench user present - 1 | 3 time |',
  ],
  ['en', 'Where can I log my swim?', 'q/wh/where | main | log user present - 1 | |'],
  ['en', 'Thanks for the plan!', 'e | main | - none none - 0 | |'],
  ['en', "Tell me if I'm overtraining", 'c | main,sub:comp | tell atlas none - 2 | |'],
  [
    'en',
    'How long should a deload week last?',
    'q/wh/how_long | main | last other present - 3 | |',
  ],
  [
    'en',
    "I've been stuck at 100 kg for months, what should I change?",
    'q/wh/what | main,coord | be user past - 1 | 100 kg |',
  ],
  [
    'en',
    'My friend says creatine is bad for kidneys',
    's | main,sub:comp | say other present - 3 | |',
  ],
  ['en', "Let's plan my next week", 'c | main | plan user none - 1 | | next_week'],
  ['en', 'i ran 10k in 55 minutes', 's | main | run user past - 1 | 10 km, 55 min |'],
  [
    'en',
    'Is 20 minutes of cardio enough to lose weight?',
    'q/yesno | main | be other present - 3 | 20 min |',
  ],
  [
    'en',
    "Why didn't my sleep sync last night?",
    'q/wh/why | main | sync other past + 3 | | last_night',
  ],
  [
    'en',
    'If I miss a workout, should I do it tomorrow?',
    'q/yesno | sub:cond,main | do user present - 1 | | tomorrow',
  ],
  ['en', 'Can I swap deadlifts for hip thrusts?', 'q/yesno | main | swap user present - 1 | |'],
  ['en', "I don't have time to train today", 's | main | have user present + 1 | | today'],
  ['en', 'What should I do after my run?', 'q/wh/what | main | do user present - 1 | |'],
  ['en', 'Great, I will try that tomorrow', 's | main | try user future - 1 | | tomorrow'],
  ['en', 'How do I stop my knees from caving in?', 'q/wh/how | main | stop user present - 1 | |'],
  [
    'en',
    'My back cracked during deadlifts, is that dangerous?',
    'q/yesno | main,coord | crack other past - 3 | |',
  ],
  ['en', 'Please remind me to stretch', 'c | main | remind atlas none - 2 | |'],
  ['en', 'I usually train in the evening after work', 's | main | train user present - 1 | |'],
  [
    'en',
    'Are you sure that 4 sets is enough?',
    'q/yesno | main,sub:comp | be atlas present - 2 | 4 set |',
  ],
  ['en', 'Since my knee surgery I avoid heavy squats', 's | main | avoid user present - 1 | |'],
  [
    'en',
    "Could my diet be the reason I'm tired?",
    'q/yesno | main,sub:rel | be other present - 3 | |',
  ],

  ['uk', 'Після станової болить низ спини', 's | main | боліти other present - 3 | |'],
  [
    'uk',
    'Що робити, якщо не хочеться йти в зал?',
    'q/wh/what | main,sub:cond | робити none none - 0 | |',
  ],
  [
    'uk',
    'Сьогодні пробіг 7 км за 40 хвилин',
    's | main | пробігти user past - 1 | 7 km, 40 min | today',
  ],
  [
    'uk',
    'Можна мені замінити присід на жим ногами?',
    'q/yesno | main | замінити user present - 1 | |',
  ],
  ['uk', 'Чому ти не порахував мої кроки?', 'q/wh/why | main | порахувати atlas past + 2 | |'],
  [
    'uk',
    'Я не встигаю відновлюватися між тренуваннями',
    's | main | встигати user present + 1 | |',
  ],
  ['uk', 'Скільки води пити під час тренування?', 'q/wh/how_much | main | пити none none - 0 | |'],
  ['uk', 'Покажи мій прогрес за місяць', 'c | main | показати atlas none - 2 | |'],
  [
    'uk',
    'Коли я роблю підтягування, болить лікоть',
    's | sub:temp,main | боліти other present - 3 | |',
  ],
  [
    'uk',
    'Не забудь, що в неділю в мене забіг',
    'c | main,sub:comp | забути atlas none + 2 | | sun',
  ],
  ['uk', 'Як правильно тримати спину під час тяги?', 'q/wh/how | main | тримати none none - 0 | |'],
  ['uk', 'Мені подобається твоя програма', 's | main | подобатися other present - 3 | |'],
  ['uk', 'Чи варто пити протеїн перед сном?', 'q/yesno | main | пити none present - 0 | |'],
  [
    'uk',
    'Завтра не зможу тренуватися, бо їду в гори',
    's | main,sub:caus | тренуватися user future + 1 | | tomorrow',
  ],
  ['uk', 'Який найкращий час для кардіо?', 'q/wh/which | main | - other present - 3 | |'],
  [
    'uk',
    'Ти порадив відпочивати, але я все одно пішов у зал',
    's | main,coord | порадити atlas past - 2 | |',
  ],
  [
    'uk',
    'Скільки кілограмів додати наступного разу?',
    'q/wh/how_many | main | додати none none - 0 | |',
  ],
  ['uk', 'У мене болить голова після тренувань', 's | main | боліти other present - 3 | |'],
  ['uk', 'Я займаюся бігом уже пів року', 's | main | займатися user present - 1 | 0.5 year |'],
  [
    'uk',
    'Це нормально, що після кардіо хочеться спати?',
    'q/yesno | main,sub:comp | нормально other present - 3 | |',
  ],
  ['uk', 'Зроби мені план на три дні', 'c | main | зробити atlas none - 2 | 3 day |'],
  ['uk', 'Хто тебе створив?', 'q/wh/who | main | створити other past - 3 | |'],
  ['uk', 'Вчора не спав і сьогодні нема сил', 's | main,coord | спати user past + 1 | | yesterday'],
  [
    'uk',
    'Як часто потрібно міняти програму?',
    'q/wh/how_often | main | міняти none present - 0 | |',
  ],
  [
    'uk',
    'Скажи, скільки я сьогодні пройшов кроків',
    'c//how_many | main,sub:comp | сказати atlas none - 2 | | today',
  ],
  ['uk', "Болять м'язи після вчорашнього", 's | main | боліти other present - 3 | | yesterday'],
  ['uk', 'Чи правильно я роблю випади?', 'q/yesno | main | робити user present - 1 | |'],
  [
    'uk',
    'Якщо я буду спати по 6 годин, то чи буде прогрес?',
    'q/yesno | sub:cond,main | бути other future - 3 | 6 h |',
  ],
  ['uk', 'Хотів піти в зал, але дуже болить спина', 's | main,coord | піти user past - 1 | |'],
  [
    'uk',
    'Давай наступного тижня додамо ще один день',
    'c | main | додати user none - 1 | 1 day | next_week',
  ],
  [
    'uk',
    "Мій тренер каже, що кардіо вбиває м'язи",
    's | main,sub:comp | казати other present - 3 | |',
  ],
  ['uk', 'Що ти порадиш для схуднення?', 'q/wh/what | main | порадити atlas future - 2 | |'],
  ['uk', 'Не можу заснути після вечірнього тренування', 's | main | заснути user present + 1 | |'],
  ['uk', 'Навіщо робити розминку?', 'q/wh/why | main | робити none none - 0 | |'],
  ['uk', 'Ти врахував мій пульс?', 'q/yesno | main | врахувати atlas past - 2 | |'],
  [
    'uk',
    'Ноги трясуться після присідань, це погано?',
    'q/yesno | main,coord | трястися other present - 3 | |',
  ],
  ['uk', 'Раніше я жав 80, а зараз ледве 70', 's | main | жати user past - 1 | | now'],
  ['uk', 'Порадь вправи для пресу вдома', 'c | main | порадити atlas none - 2 | |'],
  [
    'uk',
    'Скільки часу займає відновлення після травми?',
    'q/wh/how_long | main | займати other present - 3 | |',
  ],
  ['uk', 'Я схуд на 4 кг за місяць!', 'e | main | схуднути user past - 1 | 4 kg |'],

  [
    'ru',
    'Что делать, если болит плечо после жима?',
    'q/wh/what | main,sub:cond | делать none none - 0 | |',
  ],
  ['ru', 'Я сегодня не выспался', 's | main | выспаться user past + 1 | | today'],
  [
    'ru',
    'Сколько раз в неделю нужно тренировать ноги?',
    'q/wh/how_many | main | тренировать none present - 0 | |',
  ],
  ['ru', 'Почему ты не записал мою пробежку?', 'q/wh/why | main | записать atlas past + 2 | |'],
  ['ru', 'Дай мне план на неделю', 'c | main | дать atlas none - 2 | |'],
  ['ru', 'Можно ли пить кофе перед тренировкой?', 'q/yesno | main | пить none present - 0 | |'],
  ['sz', 'шо мені їсти після треніровки', 'q/wh/what | main | їсти user none - 1 | |'],
  [
    'sz',
    'в мене всьо болить після вчорашнього',
    's | main | боліти other present - 3 | | yesterday',
  ],
  ['sz', 'нада більше спать чи ні', 'q/yesno | main | спати none present - 0 | |'],
  [
    'uk-tr',
    'chomu ty ne rahuyesh moi trenuvannia',
    'q/wh/why | main | рахувати atlas present + 2 | |',
  ],
  ['uk-tr', 'skilky bilka treba na den', 'q/wh/how_much | main | треба none present - 0 | |'],
  ['uk-tr', 'vchora ne trenuvavsia', 's | main | тренуватися user past + 1 | | yesterday'],
  ['uk-tr', 'dai meni trenuvannia na nogy', 'c | main | дати atlas none - 2 | |'],
  ['ru-tr', 'pochemu bolit spina posle stanovoy', 'q/wh/why | main | болеть other present - 3 | |'],
  ['ru-tr', 'skolko belka nuzhno v den', 'q/wh/how_much | main | нужно none present - 0 | |'],

  ['pl', 'Co mam zjeść po treningu?', 'q/wh/what | main | zjeść user present - 1 | |'],
  ['pl', 'Boli mnie ramię od wczoraj', 's | main | boleć other present - 3 | | yesterday'],
  ['pl', 'Czy mogę ćwiczyć codziennie?', 'q/yesno | main | ćwiczyć user present - 1 | |'],
  ['pl', 'Pokaż mi plan na jutro', 'c | main | pokazać atlas none - 2 | | tomorrow'],
  ['pl', 'Nie spałem dobrze tej nocy', 's | main | spać user past + 1 | | last_night'],
  ['pl', 'Dlaczego nie liczysz spacerów?', 'q/wh/why | main | liczyć atlas present + 2 | |'],
  ['pl', 'Jutro chcę pobiegać 10 km', 's | main | pobiegać user present - 1 | 10 km | tomorrow'],
  ['pl', 'Ile godzin snu potrzebuję?', 'q/wh/how_many | main | potrzebować user present - 1 | |'],

  ['lt', 'Ką daryti, jei skauda kelį?', 'q/wh/what | main,sub:cond | daryti none none - 0 | |'],
  ['lt', 'Vakar nemiegojau gerai', 's | main | miegoti user past + 1 | | yesterday'],
  ['lt', 'Ar galiu bėgioti kasdien?', 'q/yesno | main | bėgioti user present - 1 | |'],
  ['lt', 'Parodyk mano rezultatus', 'c | main | parodyti atlas none - 2 | |'],
  ['lt', 'Kodėl neskaičiuoji mano žingsnių?', 'q/wh/why | main | skaičiuoti atlas present + 2 | |'],
  ['lt', 'Šiandien nubėgau 10 km', 's | main | nubėgti user past - 1 | 10 km | today'],
  [
    'lt',
    'Kiek vandens reikia gerti per dieną?',
    'q/wh/how_much | main | gerti none present - 0 | |',
  ],
  ['lt', 'Rytoj noriu pailsėti', 's | main | pailsėti user present - 1 | | tomorrow'],

  ['et', 'Mida teha, kui põlv valutab?', 'q/wh/what | main,sub:cond | tegema none none - 0 | |'],
  ['et', 'Eile ma ei maganud hästi', 's | main | magama user past + 1 | | yesterday'],
  ['et', 'Kas ma võin iga päev joosta?', 'q/yesno | main | jooksma user present - 1 | |'],
  ['et', 'Näita mu tulemusi', 'c | main | näitama atlas none - 2 | |'],
  ['et', 'Miks sa mu samme ei loe?', 'q/wh/why | main | lugema atlas present + 2 | |'],
  ['et', 'Täna jooksin 10 km', 's | main | jooksma user past - 1 | 10 km | today'],
  ['et', 'Kui palju vett peaks päevas jooma?', 'q/wh/how_much | main | jooma none present - 0 | |'],
  ['et', 'Homme tahan puhata', 's | main | puhkama user present - 1 | | tomorrow'],
];
