/**
 * Copy of the Today widgets, all five locales (typed: a missing key in any
 * locale fails the build, like i18n/Strings). Widget chrome that already
 * exists in the main dictionaries (muscle names, weekdays) is reused from there.
 */
import { useT, type LocaleId } from '../i18n';

const en = {
  groups: {
    training: 'Training',
    plan: 'Plan & sessions',
    strength: 'Strength',
    muscles: 'Muscles & consistency',
    cardio: 'Cardio & gyms',
    fun: 'Fun & tools',
    calendar: 'Calendar',
    body: 'Body & recovery',
    apex: 'Apex',
    learn: 'Learn',
    atlas: 'Atlas',
    discover: 'Discover',
    shortcuts: 'Shortcuts',
    train: 'Train',
    health: 'Health & body',
    activity: 'Activities',
  } as Record<string, string>,
  readiness: 'Readiness',
  muscleReadiness: 'Muscle readiness',
  allReady: 'All muscles ready',
  recovering: (n: number) => `${n} recovering`,
  readyPct: (p: number) => `Readiness ${p}%`,
  openMuscles: 'Open muscles',
  lastNight: 'Last night',
  sleep7: 'Sleep · 7 nights',
  noNight: 'No night logged yet',
  avg7: (x: string) => `7-night avg ${x}`,
  slept: (x: string) => `Slept ${x}`,
  logSleep: 'Log sleep',
  bodyWeight: 'Body weight',
  weight30: 'Body weight · 30 days',
  noWeight: 'No weigh-ins yet',
  weekDelta: (x: string) => `${x} this week`,
  logWeight: 'Log weight',
  thisWeek: 'This week',
  volume8: 'Volume · 8 weeks',
  vsAvg: (x: string) => `${x} vs 8-week avg`,
  volumeWeek: (x: string) => `${x} t this week`,
  streak: 'Streak',
  days: 'days',
  dayStreak: (n: number) => `${n}-day streak`,
  keepToday: 'Train or rest today to keep it',
  openApex: 'Open Apex',
  noData: 'Nothing logged yet',
  bed: 'Bed',
  wake: 'Wake',
  todaysDay: 'Today’s day',
  logSleepShort: 'Sleep',
  weighIn: 'Weigh-in',
  scAuto: 'Auto session',
  scActiveRest: 'Active rest',
  scDayOff: 'Day off',
  scUnwell: 'Unwell',
  scInjury: 'Injury',
  scNextLesson: 'Next lesson',
  scAskAtlas: 'Ask Atlas',
};

export type TodayStrings = typeof en;

const uk: TodayStrings = {
  groups: {
    training: 'Тренування',
    plan: 'План і сесії',
    strength: 'Сила',
    muscles: 'М’язи й регулярність',
    cardio: 'Кардіо й зали',
    fun: 'Розваги й інструменти',
    calendar: 'Календар',
    body: 'Тіло й відновлення',
    apex: 'Apex',
    learn: 'Learn',
    atlas: 'Atlas',
    discover: 'Відкриття',
    shortcuts: 'Шорткати',
    train: 'Тренування',
    health: 'Здоров’я і тіло',
    activity: 'Активності',
  },
  readiness: 'Готовність',
  muscleReadiness: 'Готовність м’язів',
  allReady: 'Усі м’язи готові',
  recovering: (n) => `${n} відновлюються`,
  readyPct: (p) => `Готовність ${p}%`,
  openMuscles: 'Відкрити м’язи',
  lastNight: 'Минула ніч',
  sleep7: 'Сон · 7 ночей',
  noNight: 'Ще немає записаних ночей',
  avg7: (x) => `Середнє за 7 ночей ${x}`,
  slept: (x) => `Сон ${x}`,
  logSleep: 'Записати сон',
  bodyWeight: 'Вага тіла',
  weight30: 'Вага · 30 днів',
  noWeight: 'Ще немає зважувань',
  weekDelta: (x) => `${x} за тиждень`,
  logWeight: 'Записати вагу',
  thisWeek: 'Цей тиждень',
  volume8: 'Обсяг · 8 тижнів',
  vsAvg: (x) => `${x} від середнього`,
  volumeWeek: (x) => `${x} т цього тижня`,
  streak: 'Серія',
  days: 'днів',
  dayStreak: (n) => `Серія ${n} дн.`,
  keepToday: 'Тренуйся або відпочивай — серія триває',
  openApex: 'Відкрити Apex',
  noData: 'Поки нічого не записано',
  bed: 'Ліг',
  wake: 'Прокинувся',
  todaysDay: 'День програми',
  logSleepShort: 'Сон',
  weighIn: 'Зважування',
  scAuto: 'Авто-сесія',
  scActiveRest: 'Активний відпочинок',
  scDayOff: 'Вихідний',
  scUnwell: 'Нездужаю',
  scInjury: 'Травма',
  scNextLesson: 'Наступний урок',
  scAskAtlas: 'Спитати Atlas',
};

const pl: TodayStrings = {
  groups: {
    training: 'Trening',
    plan: 'Plan i sesje',
    strength: 'Siła',
    muscles: 'Mięśnie i regularność',
    cardio: 'Cardio i siłownie',
    fun: 'Rozrywka i narzędzia',
    calendar: 'Kalendarz',
    body: 'Ciało i regeneracja',
    apex: 'Apex',
    learn: 'Learn',
    atlas: 'Atlas',
    discover: 'Odkrywaj',
    shortcuts: 'Skróty',
    train: 'Trening',
    health: 'Zdrowie i ciało',
    activity: 'Aktywności',
  },
  readiness: 'Gotowość',
  muscleReadiness: 'Gotowość mięśni',
  allReady: 'Wszystkie mięśnie gotowe',
  recovering: (n) => `${n} w regeneracji`,
  readyPct: (p) => `Gotowość ${p}%`,
  openMuscles: 'Otwórz mięśnie',
  lastNight: 'Ostatnia noc',
  sleep7: 'Sen · 7 nocy',
  noNight: 'Brak zapisanych nocy',
  avg7: (x) => `Średnia z 7 nocy ${x}`,
  slept: (x) => `Sen ${x}`,
  logSleep: 'Zapisz sen',
  bodyWeight: 'Masa ciała',
  weight30: 'Masa ciała · 30 dni',
  noWeight: 'Brak ważeń',
  weekDelta: (x) => `${x} w tym tygodniu`,
  logWeight: 'Zapisz wagę',
  thisWeek: 'Ten tydzień',
  volume8: 'Objętość · 8 tygodni',
  vsAvg: (x) => `${x} vs średnia`,
  volumeWeek: (x) => `${x} t w tym tygodniu`,
  streak: 'Seria',
  days: 'dni',
  dayStreak: (n) => `Seria ${n} dni`,
  keepToday: 'Trenuj lub odpocznij dziś, by ją utrzymać',
  openApex: 'Otwórz Apex',
  noData: 'Jeszcze nic nie zapisano',
  bed: 'Sen od',
  wake: 'Pobudka',
  todaysDay: 'Dzień planu',
  logSleepShort: 'Sen',
  weighIn: 'Ważenie',
  scAuto: 'Auto sesja',
  scActiveRest: 'Aktywny odpoczynek',
  scDayOff: 'Dzień wolny',
  scUnwell: 'Choroba',
  scInjury: 'Kontuzja',
  scNextLesson: 'Następna lekcja',
  scAskAtlas: 'Zapytaj Atlasa',
};

const lt: TodayStrings = {
  groups: {
    training: 'Treniruotės',
    plan: 'Planas ir sesijos',
    strength: 'Jėga',
    muscles: 'Raumenys ir reguliarumas',
    cardio: 'Kardio ir sporto salės',
    fun: 'Pramogos ir įrankiai',
    calendar: 'Kalendorius',
    body: 'Kūnas ir atsigavimas',
    apex: 'Apex',
    learn: 'Learn',
    atlas: 'Atlas',
    discover: 'Atraskite',
    shortcuts: 'Nuorodos',
    train: 'Treniruotė',
    health: 'Sveikata ir kūnas',
    activity: 'Veiklos',
  },
  readiness: 'Pasirengimas',
  muscleReadiness: 'Raumenų pasirengimas',
  allReady: 'Visi raumenys pasiruošę',
  recovering: (n) => `${n} atsigauna`,
  readyPct: (p) => `Pasirengimas ${p}%`,
  openMuscles: 'Atidaryti raumenis',
  lastNight: 'Praėjusi naktis',
  sleep7: 'Miegas · 7 naktys',
  noNight: 'Dar nėra įrašytų naktų',
  avg7: (x) => `7 naktų vidurkis ${x}`,
  slept: (x) => `Miegota ${x}`,
  logSleep: 'Įrašyti miegą',
  bodyWeight: 'Kūno svoris',
  weight30: 'Kūno svoris · 30 d.',
  noWeight: 'Dar nėra svėrimų',
  weekDelta: (x) => `${x} per savaitę`,
  logWeight: 'Įrašyti svorį',
  thisWeek: 'Ši savaitė',
  volume8: 'Apimtis · 8 savaitės',
  vsAvg: (x) => `${x} nuo vidurkio`,
  volumeWeek: (x) => `${x} t šią savaitę`,
  streak: 'Serija',
  days: 'd.',
  dayStreak: (n) => `${n} d. serija`,
  keepToday: 'Treniruokitės arba ilsėkitės šiandien',
  openApex: 'Atidaryti Apex',
  noData: 'Dar nieko neįrašyta',
  bed: 'Atsigulta',
  wake: 'Pabusta',
  todaysDay: 'Šios dienos treniruotė',
  logSleepShort: 'Miegas',
  weighIn: 'Svėrimas',
  scAuto: 'Auto treniruotė',
  scActiveRest: 'Aktyvus poilsis',
  scDayOff: 'Laisva diena',
  scUnwell: 'Negaluoju',
  scInjury: 'Trauma',
  scNextLesson: 'Kita pamoka',
  scAskAtlas: 'Klausti Atlas',
};

const et: TodayStrings = {
  groups: {
    training: 'Treening',
    plan: 'Plaan ja sessioonid',
    strength: 'Jõud',
    muscles: 'Lihased ja järjepidevus',
    cardio: 'Kardio ja jõusaalid',
    fun: 'Lõbu ja tööriistad',
    calendar: 'Kalender',
    body: 'Keha ja taastumine',
    apex: 'Apex',
    learn: 'Learn',
    atlas: 'Atlas',
    discover: 'Avasta',
    shortcuts: 'Otseteed',
    train: 'Treening',
    health: 'Tervis ja keha',
    activity: 'Tegevused',
  },
  readiness: 'Valmisolek',
  muscleReadiness: 'Lihaste valmisolek',
  allReady: 'Kõik lihased on valmis',
  recovering: (n) => `${n} taastub`,
  readyPct: (p) => `Valmisolek ${p}%`,
  openMuscles: 'Ava lihased',
  lastNight: 'Eelmine öö',
  sleep7: 'Uni · 7 ööd',
  noNight: 'Ühtegi ööd pole veel logitud',
  avg7: (x) => `7 öö keskmine ${x}`,
  slept: (x) => `Magasid ${x}`,
  logSleep: 'Logi uni',
  bodyWeight: 'Kehakaal',
  weight30: 'Kehakaal · 30 päeva',
  noWeight: 'Kaalumisi pole veel',
  weekDelta: (x) => `${x} sel nädalal`,
  logWeight: 'Logi kaal',
  thisWeek: 'See nädal',
  volume8: 'Maht · 8 nädalat',
  vsAvg: (x) => `${x} vs keskmine`,
  volumeWeek: (x) => `${x} t sel nädalal`,
  streak: 'Seeria',
  days: 'päeva',
  dayStreak: (n) => `${n}-päevane seeria`,
  keepToday: 'Treeni või puhka täna, et seeria jätkuks',
  openApex: 'Ava Apex',
  noData: 'Veel pole midagi logitud',
  bed: 'Magama',
  wake: 'Ärkamine',
  todaysDay: 'Tänane päev',
  logSleepShort: 'Uni',
  weighIn: 'Kaalumine',
  scAuto: 'Automaatne trenn',
  scActiveRest: 'Aktiivne puhkus',
  scDayOff: 'Vaba päev',
  scUnwell: 'Haige',
  scInjury: 'Vigastus',
  scNextLesson: 'Järgmine tund',
  scAskAtlas: 'Küsi Atlaselt',
};

const DICT: Record<LocaleId, TodayStrings> = { en, uk, pl, lt, et };

export function useTw(): TodayStrings {
  const { locale } = useT();
  return DICT[locale];
}
