/**
 * Phrasings of the app topics in appTips.ts — for the understanding index only.
 * English, Polish, Lithuanian, Estonian and Latin-typed Ukrainian ride in `ex`;
 * Ukrainian, surzhyk and Russian in `exUk`.
 */
export const APP_MORE_EX: Record<string, { ex: string[]; exUk: string[] }> = {
  app_tips: {
    ex: [
      'tips',
      'any tips',
      'give me some tips',
      'app tips',
      'tips for using the app',
      'more tips',
      'another tip',
      'give me more tips',
      'any tricks for the app',
      'hidden features',
      'what should i know about this app',
      'porady do aplikacji',
      'więcej wskazówek',
      'daugiau patarimų',
      'patarimai programėlei',
      'rohkem nõuandeid',
      'äpi nõuanded',
      'dai porady',
      'shche porady',
    ],
    exUk: [
      'поради',
      'дай поради',
      'є якісь поради',
      'поради щодо додатка',
      'ще поради',
      'дай ще порад',
      'ще одну пораду',
      'лайфхаки для додатка',
      'що корисно знати про цей додаток',
      'які є фішки в додатку',
      'дай советы по приложению',
      'еще советы',
    ],
  },
  app_tour: {
    ex: [
      'how do i use this app',
      'how does this app work',
      'what can this app do',
      'what can the app do',
      'explain the app to me',
      'give me a tour of the app',
      'where do i start in this app',
      'im new here how does spotter work',
      'what are the tabs for',
      'jak korzystać z tej aplikacji',
      'co potrafi ta aplikacja',
      'kaip naudotis šia programėle',
      'ką moka ši programėlė',
      'kuidas seda äppi kasutada',
      'mida see äpp oskab',
      'yak korystuvatysia tsym dodatkom',
    ],
    exUk: [
      'як користуватися цим додатком',
      'як працює цей додаток',
      'що вміє додаток',
      'що може ця апка',
      'поясни як тут все влаштовано',
      'проведи екскурсію по додатку',
      'я тут новенький як цим користуватись',
      'для чого вкладки внизу',
      'как пользоваться этим приложением',
      'что умеет приложение',
    ],
  },
  app_start_session: {
    ex: [
      'how do i start a session',
      'how to start a workout in the app',
      'where is the start button',
      'how do i begin training here',
      'start a workout from my program',
      'what does the plus button do',
      'jak rozpocząć trening w aplikacji',
      'kaip pradėti treniruotę programėlėje',
      'kuidas äpis trenni alustada',
      'yak pochaty trenuvannia v dodatku',
    ],
    exUk: [
      'як почати тренування',
      'як почати тренування в додатку',
      'де кнопка старт',
      'що робить кнопка плюс',
      'як запустити тренування з програми',
      'як почати сесію',
      'как начать тренировку в приложении',
    ],
  },
  app_auto_session: {
    ex: [
      'how does the auto session work',
      'what is auto session',
      'can the app build my workout for today',
      'auto build a workout',
      'build your day wizard',
      'generate a workout for me in the app',
      'jak działa automatyczny trening',
      'kaip veikia automatinė treniruotė',
      'kuidas automaatne treening töötab',
      'avto trenuvannia yak pratsiuie',
    ],
    exUk: [
      'як працює авто тренування',
      'що таке авто-тренування',
      'додаток може сам зібрати тренування',
      'зібрати день автоматично',
      'авто збірка тренування',
      'как работает авто тренировка',
    ],
  },
  app_finish_session: {
    ex: [
      'how do i finish a workout',
      'how to end a session',
      'where is the finish button',
      'i forgot to finish my workout',
      'how do i discard a session',
      'stop the workout in the app',
      'jak zakończyć trening w aplikacji',
      'kur mygtukas užbaigti sesiją programėlėje',
      'kuidas trenn lõpetada',
      'yak zavershyty trenuvannia',
    ],
    exUk: [
      'як завершити тренування',
      'як закінчити сесію',
      'де кнопка завершити',
      'забув завершити тренування',
      'як скасувати тренування',
      'как завершить тренировку',
    ],
  },
  app_home_set: {
    ex: [
      'how do i log a workout at home',
      'log pull ups at home',
      'what is a home set',
      'track push ups without the gym',
      'home workout in the app',
      'jak zapisać trening w domu',
      'kaip įrašyti treniruotę namuose',
      'kuidas kodust trenni kirja panna',
      'yak zapysaty trenuvannia vdoma',
    ],
    exUk: [
      'як записати тренування вдома',
      'що таке домашній сет',
      'записати підтягування вдома',
      'як записати віджимання без залу',
      'как записать тренировку дома',
    ],
  },
  app_rest_period: {
    ex: [
      'how do i pause training for a vacation',
      'going on holiday how do i tell the app',
      'mark a rest period',
      'im sick how do i pause my plan',
      'log a vacation so my streak doesnt break',
      'active recovery week in the app',
      'jak zaznaczyć urlop w aplikacji',
      'kaip pažymėti atostogas programėlėje',
      'kuidas äpis puhkust märkida',
      'yak postavyty pauzu na vidpustku',
    ],
    exUk: [
      'як поставити тренування на паузу через відпустку',
      'їду у відпустку як позначити в додатку',
      'як почати період відпочинку',
      'я захворів як поставити план на паузу',
      'як відмітити відпустку щоб не злетіла серія',
      'как поставить паузу на время отпуска',
    ],
  },
  app_week_start: {
    ex: [
      'how do i change the start of the week',
      'set week start to sunday',
      'week starts on monday setting',
      'my week should start on saturday',
      'change first day of the week',
      'jak zmienić pierwszy dzień tygodnia',
      'kaip pakeisti savaitės pradžią',
      'kuidas muuta nädala algust',
      'yak zminyty pochatok tyzhnia',
    ],
    exUk: [
      'як змінити день початку тижня',
      'тиждень з неділі як налаштувати',
      'де змінити початок тижня',
      'хочу щоб тиждень починався з суботи',
      'как изменить начало недели',
    ],
  },
  app_assign_program: {
    ex: [
      'how do i assign a program to a client',
      'give my client a program',
      'assign a program to members',
      'as a trainer how do i send a plan to my client',
      'assign workout plan to trainee',
      'jak przypisać program klientowi',
      'kaip priskirti programą klientui',
      'kuidas kliendile programmi määrata',
      'yak pryznachyty prohramu kliientu',
    ],
    exUk: [
      'як призначити програму клієнту',
      'як дати клієнту програму',
      'призначити програму учасникам',
      'я тренер як відправити план підопічному',
      'как назначить программу клиенту',
    ],
  },
  app_apex: {
    ex: [
      'what is apex',
      'how does apex work',
      'how do i start a challenge',
      'where are challenges',
      'what are ranks in apex',
      'where are my awards',
      'co to jest apex',
      'kas yra apex',
      'mis on apex',
      'shcho take apex',
    ],
    exUk: [
      'що таке apex',
      'як працює апекс',
      'як почати челендж',
      'де челенджі',
      'що таке розряди в апекс',
      'де мої нагороди',
      'что такое апекс',
    ],
  },
  app_nutrition: {
    ex: [
      'how does the nutrition app work',
      'can i track food in spotter',
      'how do i log a meal',
      'calorie tracking in the app',
      'scan a barcode for food',
      'nutrition says coming soon',
      'jak działa aplikacja odżywianie',
      'kaip veikia mitybos programėlė',
      'kuidas toitumise äpp töötab',
      'yak pratsiuie kharchuvannia v dodatku',
    ],
    exUk: [
      'як працює харчування',
      'як записати їжу в додатку',
      'як рахувати калорії в спотері',
      'сканер штрихкоду для їжі',
      'харчування пише незабаром',
      'как записать еду в приложении',
    ],
  },
  app_learn: {
    ex: [
      'what is the learn app',
      'are there video tutorials',
      'how to videos for the app',
      'where are the lessons',
      'learn app videos coming soon',
      'co to jest aplikacja nauka',
      'kas yra mokymosi programėlė',
      'mis on õppe äpp',
      'shcho take navchannia v dodatku',
    ],
    exUk: [
      'що таке навчання в додатку',
      'є відео уроки',
      'де уроки як користуватися',
      'відео інструкції до додатка',
      'где обучающие видео',
    ],
  },
  app_people: {
    ex: [
      'where is my profile',
      'where are the settings',
      'how do i open settings',
      'where is the people app',
      'how do i see my clients',
      'where do i sign out',
      'gdzie są ustawienia',
      'kur mano profilis ir paskyros nustatymai',
      'kus on seaded',
      'de nalashtuvannia',
    ],
    exUk: [
      'де мій профіль',
      'де налаштування',
      'як відкрити налаштування',
      'де мої клієнти',
      'де вийти з акаунта',
      'где настройки',
    ],
  },
  app_switch_apps: {
    ex: [
      'how do i switch between apps',
      'where is the app switcher',
      'what is the apps button',
      'how do i get to apex',
      'switch to nutrition app',
      'jak przełączać się między aplikacjami',
      'kaip perjungti programėles',
      'kuidas äppide vahel vahetada',
      'yak perekliuchatysia mizh zastosunkamy',
    ],
    exUk: [
      'як перемикатися між застосунками',
      'де перемикач додатків',
      'що за кнопка застосунки',
      'як перейти в апекс',
      'как переключаться между приложениями',
    ],
  },
  app_progress_view: {
    ex: [
      'where do i see my progress',
      'where are my charts',
      'where can i see my records in the app',
      'where is the progress screen',
      'how to see progress by muscle',
      'gdzie zobaczę postępy',
      'kur matyti progresą',
      'kus näen oma progressi',
      'de podyvytysia prohres',
    ],
    exUk: [
      'де подивитися прогрес',
      'де мої графіки',
      'де побачити рекорди в додатку',
      'де екран прогресу',
      'где посмотреть прогресс',
    ],
  },
  app_lens: {
    ex: [
      'what is the lens in progress',
      'how do i see fatigue per muscle',
      'readiness lens',
      'volume fatigue readiness view',
      'where is the readiness map',
      'which muscles are recovered map',
      'co to jest soczewka w postępach',
      'kas yra lęšis progrese',
      'mis on lääts progressis',
      'shcho take linza',
    ],
    exUk: [
      'що таке лінза в прогресі',
      'де подивитися втому по мʼязах',
      'лінза готовність',
      'вигляд обʼєму втома готовність',
      'де карта відновлення мʼязів',
      'что такое линза в прогрессе',
    ],
  },
};

/** More phrasings for app topics of the earlier rounds (how-to wording people use). */
export const KB_APP_EXTRA: Record<string, { ex: string[]; exUk: string[] }> = {
  app_activity: {
    ex: [
      'how do i log activities',
      'how do i log an activity',
      'where do i add a bike ride',
      'log yoga in the app',
      'how to record a hike',
      'jak dodać aktywność',
      'kaip įrašyti veiklą',
      'kuidas tegevust lisada',
    ],
    exUk: [
      'як записати активність',
      'як додати активність',
      'де записати велосипед чи прогулянку',
      'як записати йогу в додатку',
    ],
  },
  app_goals: {
    ex: [
      'how do i set goals',
      'how to set my goals in the app',
      'where do i choose muscles to focus on',
      'set physique target',
      'jak ustawić cele',
      'kaip nustatyti tikslus',
      'kuidas eesmärke seada',
    ],
    exUk: [
      'як поставити цілі',
      'де вибрати фокус на мʼязи',
      'як задати ціль фігури',
      'где поставить цели в приложении',
    ],
  },
  app_injury_log: {
    ex: [
      'how do i log an injury in the app',
      'where do i set up a rehab plan',
      'injury and rehab in the app',
      'jak zapisać kontuzję',
      'kaip įrašyti traumą',
      'kuidas vigastust lisada',
    ],
    exUk: [
      'як записати травму в додатку',
      'де налаштувати план реабілітації',
      'як додати травму',
      'как записать травму в приложении',
    ],
  },
  app_programs: {
    ex: [
      'how do i build a program',
      'how do i make my own program in the app',
      'where is new program',
      'how to activate a program',
      'jak stworzyć program',
      'kaip sukurti programą',
      'kuidas programmi luua',
    ],
    exUk: [
      'як скласти програму в додатку',
      'як створити свою програму',
      'де нова програма',
      'как создать программу в приложении',
    ],
  },
  app_backfill: {
    ex: [
      'how do i log a past workout',
      'where is log past',
      'add yesterdays workout',
      'jak dodać wczorajszy trening',
      'kaip įrašyti vakarykštę treniruotę',
      'kuidas eilset trenni lisada',
    ],
    exUk: [
      'як записати минуле тренування',
      'де кнопка минуле',
      'як додати вчорашнє тренування',
      'как добавить вчерашнюю тренировку',
    ],
  },
};
