/** Round 10: indirect, everyday wording for the narrow topics (no textbook terms). */
export const KB_R10: Record<string, { ex: string[]; exUk: string[] }> = {
  k_bench_arch: {
    ex: [
      'when i press lying down my lower back lifts way off the pad, like a bridge, is that allowed',
      'guys at my gym make a huge curve under their back when benching, should i copy that',
      'is it legit to push my chest up to the ceiling so the bar travels less on flat press',
      'saw a powerlifting girl bench with her back like a rainbow, isnt that basically cheating',
      'my spine makes a gap you could fit a fist under when i bench, too much?',
      'should my butt and shoulders be the only things touching the bench with a big hollow in between',
      'flat bench: keep the back glued down or curve it up?',
      'does squeezing my shoulder blades and lifting my ribcage on the bench wreck my lower back',
      'coach told me to make a tunnel under my back on bench press, why',
      'back bent like a bow on chest press day, safe or dumb',
      'how much gap under the lower back is normal when u bench',
      'is the bridge thing on bench only for comps or for normal gym guys too',
      'flat back vs curved back on the bench, which one for a regular lifter',
      'my lower back cramps from arching up when i lie down to press the bar',
      'is it ok to raise my chest high and make the ROM shorter on bench or is that ego lifting',
    ],
    exUk: [
      'коли жму лежачи поперек сильно відривається від лави, як місток, так можна',
      'хлопці в залі роблять величезний вигин спини на жимі, мені теж так треба',
      'чи нормально піднімати груди до стелі щоб штанга менше ходила на жимі лежачи',
      'бачила пауерліфтерку яка жме з мостом як веселка, це ж чітинг ні?',
      'під спиною на лаві дірка що кулак пролазить, це забагато?',
      'на жимі лежачи спину тримати пласкою чи вигинати дугою',
      'зводжу лопатки і піднімаю грудну клітку на лаві, поперек від цього не постраждає?',
      'тренер сказав робити тунель під спиною на жимі, навіщо',
      'спина вигнута як лук на жимі, безпечно чи тупо',
      'скільки має бути просвіт під попереком коли жмеш',
      'міст на жимі це тільки для змагань чи й для звичайних людей',
      'пласка спина чи прогин на лаві для звичайного качка',
      'поперек зводить судомою від прогину коли лягаю жати штангу',
      'підняти груди високо і вкоротити амплітуду на жимі це нормально чи понти',
      'жму і поперек дугою відривається від лавки, чи так правильно',
    ],
  },
  k_knees_cave: {
    ex: [
      'my legs make an X shape when i stand up with the bar',
      'friend filmed me and my kneecaps point inward as i push out of the hole',
      'on the way up from a deep squat my knees roll in like a knock kneed kid',
      'why do my knees fold in towards the middle when the weight gets heavy',
      'knees go inside my feet line when i squat, how do i keep them out',
      'legs wobble inward on goblet squats',
      'my knees kiss when i do lunges and squats lol',
      'is it my glutes being weak if my knees pinch in coming up',
      'knee collapse inward on heavy squat reps how to stop it',
      'kneecaps drifting in over my big toes when i rise',
      'on jump squats i land and my knees snap inward',
      'coach says push knees out but they keep falling in anyway',
      'my knees turn in on the way up, not about them going past the toes, about them going IN',
    ],
    exUk: [
      'ноги стають буквою Х коли піднімаюсь зі штангою',
      'коліна майже стукаються внизу присіду, що це',
      'друг зняв на відео, коліна дивляться всередину коли виходжу з низу',
      'чому коліна завалюються до середини коли вага важка',
      'коліна заходять всередину від лінії стоп на присіді, як тримати їх назовні',
      'на гоблет присіданнях ноги хитаються всередину',
      'коліна цілуються на випадах і присідах хаха',
      'це слабкі сідниці якщо коліна зводяться на підйомі?',
      'на важких повторах коліна їдуть всередину як зупинити',
      'колінні чашечки зміщуються всередину над великим пальцем коли встаю',
      'після стрибка приземляюсь і коліна клацають всередину',
      'тренер каже розводь коліна а вони все одно падають всередину',
      'коліна повертаються всередину на підйомі, не про те що за носки, а саме всередину',
    ],
  },
  k_butt_wink: {
    ex: [
      'my lower back flips round only in the hole when i squat deep',
      'the butt tucking thing at the bottom of squats, how do i stop it',
      'pelvis rolls under when i go ass to grass',
      'why does my back lose its curve right at the bottom of a deep squat but not on the way up',
      'squat: all good until the last few cm then my hips tilt under',
      'my tail kinda tucks under like a dog at the bottom of goblet squats',
      'is going so deep that my pelvis flips bad for my discs',
      'should i stop squatting just above where my lower back starts to round',
      'hips curl under in the bottom position, tight hamstrings or what',
      'friend said i wink at the bottom of my squat, what does that mean',
      'bum tucks in at the bottom of squat, not deadlift, only squat',
      'at the bottom of the squat my back goes from straight to rounded for a split second',
    ],
    exUk: [
      'в самому низу присіду куприк підгортається, це проблема?',
      'на відео таз ніби закручується під себе в найнижчій точці присіду',
      'поперек округлюється тільки внизу коли присідаю глибоко',
      'попа підкручується внизу присіду, як це прибрати',
      "таз заходить під себе коли сідаю повністю в дупу до п'ят",
      'чому спина втрачає прогин саме внизу глибокого присіду',
      'присід норм до останніх кількох сантиметрів а потім таз підвертається',
      'внизу гоблет присіду хвіст підгортається як у собаки',
      'якщо сідаю так глибоко що таз перевертається це погано для дисків?',
      'може присідати трохи вище за точку де поперек почне круглитись',
      'таз підкручується в нижній позиції, це тугі біцепси стегна чи що',
      'друг сказав що в мене підмигування тазом внизу присіду, що це',
      'дупа підвертається внизу присіду, не на становій а саме на присіді',
      'на фронтальному присіді низ спини згинається в самому низу',
      'в низу присіду спина на мить з рівної стає круглою',
    ],
  },
  k_ohp_lean: {
    ex: [
      'when i press the bar over my head i end up bending backwards like im doing a limbo',
      'standing shoulder press turns into me leaning back like a banana',
      'my hips shoot forward and torso tilts back to get the bar up overhead',
      'pressing overhead standing and my belly sticks out and back bends, bad?',
      'every overhead rep i look like im doing an incline bench standing up',
      'how do i stay upright when pushing the barbell above my head',
      'lower back feels pinched when i press weight overhead standing',
      'i lean way back to finish the rep on military press, how to fix',
      'on dumbbell press standing my torso goes backward to cheat it up',
      'how to keep ribs down when pushing the bar up from the shoulders',
      'the bar goes up and i go backward, standing press',
      'overhead: back arches like crazy on the last reps',
      'is leaning back on shoulder press cheating or just normal',
      'my spine looks like a C sideways when i do standing press',
      'squeezing glutes on overhead press to stop back bending, does that work',
    ],
    exUk: [
      'коли жму штангу над головою відхиляюсь назад як у лімбо',
      'армійський жим перетворюється на те що я вигинаюсь назад бананом',
      'таз вилітає вперед а корпус назад щоб вижати штангу над головою',
      'жму стоячи над головою і живіт випирає а спина прогинається, погано?',
      'кожен повтор над головою виглядає як жим на похилій стоячи',
      'як стояти рівно коли вижимаю штангу над головою',
      'поперек затискає коли жму вагу вгору стоячи',
      'сильно відкидаюсь назад щоб дожати на армійському, як виправити',
      'як тримати ребра внизу коли виштовхую штангу від плечей вгору',
      'штанга йде вгору а я назад, жим стоячи',
      'над головою спина прогинається як скажена на останніх повторах',
      'відхилятись назад на жимі на плечі це чітинг чи норм',
      'хребет виглядає як буква С боком коли жму стоячи',
      'стискати сідниці на жимі над головою щоб не прогинатись це допомагає?',
    ],
  },
  k_sumo_conventional: {
    ex: [
      'pulling from the floor with feet super wide and hands inside the legs vs normal narrow stance, which one',
      'my buddy pulls with his legs spread wide like a frog, is that easier than normal pulling',
      'wide stance deadlift or hip width deadlift for someone with long legs',
      'is the wide legs version of the floor pull a cheat because the bar moves less',
      'should i try deadlifting with my feet way out by the plates',
      'which deadlift stance is for me, tall guy short arms',
      'i hate how my back feels on regular pulls, would a wide foot pull fix it',
      'hands between knees deadlift vs hands outside knees deadlift',
      'is the wide deadlift legit in powerlifting or considered fake',
      'which pulling style moves more weight, wide or narrow feet',
      'switching my deadlift stance to wide, good idea for hips?',
      'frog stance deadlift vs regular one, pros cons',
      'does pulling wide hit more legs and less back',
      "i'm a girl with wide hips, is the wide feet pull better for me",
      'the deadlift where you stand wide like a sumo wrestler, should beginners do it',
    ],
    exUk: [
      'тягнути з підлоги з дуже широкими ногами і руками всередині чи звичайно вузько, що краще',
      'друг тягне з ногами розставленими як жаба, це легше ніж звичайна',
      'широка постановка на становій чи на ширині тазу для людини з довгими ногами',
      'широка тяга це чіт бо штанга менше проходить?',
      'спробувати тягнути з ногами аж біля блинів?',
      'яка постановка станової мені, високий і короткі руки',
      'ненавиджу як спина почувається на звичайній тязі, широкі ноги допоможуть?',
      'руки між колінами на тязі чи руки ззовні колін',
      'широка станова в пауерліфтингу це норм чи вважається несправжньою',
      'яким стилем тяги піднімеш більше, широко чи вузько ногами',
      'переходжу на широку постановку в тязі, для тазостегнових норм?',
      "тяга жаб'ячою стійкою проти класичної плюси мінуси",
      'широка тяга більше ноги і менше спину?',
      'я дівчина з широким тазом, мені краще тягнути з широкими ногами?',
      'станова де стоїш широко як борець сумо, новачкам варто?',
    ],
  },
  k_smith_machine: {
    ex: [
      'the barbell thing that slides up and down on metal rails, is it any good for squats',
      'bar stuck in a track that you twist to rack, worth using or garbage',
      'my gym has no free squat rack only the guided bar on runners, can i still build legs',
      'is benching on the fixed path bar cheating compared to a real barbell',
      'the locked in bar machine for squats, do stabilizers get lazy',
      'people at my gym call the rail bar a noob machine, why',
      'can i do all my squats on the bar that moves on rods',
      'guided barbell vs free bar for bench, which is safer alone',
      'that frame where the bar clicks into hooks every few inches, useful?',
      'is lunging in the bar-on-rails rack a good idea',
      'does the machine where the bar only goes straight up and down hurt knees',
      'hip thrusts on the track bar or free barbell',
      'is the fixed bar rack fake strength',
      'inclined press on the rail machine vs normal incline',
      'my numbers on the sliding bar are way higher than with a normal bar, why',
    ],
    exUk: [
      'штанга яка ковзає вгору-вниз по металевих напрямних, для присідань норм?',
      'гриф в рейках який треба повернути щоб повісити, варто юзати чи мотлох',
      'в моєму залі нема стійки тільки гриф на напрямних, ноги накачаю?',
      'жим на грифі з фіксованою траєкторією це чітинг порівняно зі звичайною штангою',
      'машина з закріпленим грифом для присіду, стабілізатори лінуються?',
      'в залі кажуть що штанга на рейках це тренажер для нубів, чому',
      'можна всі присідання робити на грифі що їздить по штангах-напрямних',
      'гриф на напрямних чи вільна штанга для жиму, що безпечніше самому',
      'та рама де гриф чіпляється на гачки кожні кілька сантиметрів, корисна?',
      'випади в рамі з грифом на рейках це нормальна ідея',
      'тренажер де штанга ходить тільки прямо вгору-вниз шкодить колінам?',
      'ягодичний міст на грифі в рейках чи з вільною штангою',
      'сила на рейковому грифі несправжня?',
      'жим на похилій у рамі з напрямними проти звичайного',
      'на ковзному грифі цифри набагато більші ніж зі звичайною штангою, чому',
    ],
  },
  k_test_max: {
    ex: [
      'i want to find out the heaviest i can lift once on bench, how do i go about that day',
      'how do i work up to one all out single without getting hurt',
      'planning a day to see what my absolute top squat is, how many jumps',
      "what's a safe way to check my heaviest single deadlift",
      'should i actually try a one and done heaviest lift or just estimate it',
      'how to pick attempts when going for a new heaviest single',
      'is it dumb to try a max lift every month',
      'on the day i go for my heaviest single, how long rest between attempts',
      'estimate my one rep limit from a set of 5 or test it for real',
      'how often should you check your top single strength',
      'going for my heaviest ever squat on saturday how do i build up to it',
      'whats the protocol for a max out day',
      'can i find my ceiling lift without a spotter or comp setup',
      'one rep all out test vs rep max test, which to do',
    ],
    exUk: [
      'як дійти до одного повтору на всі сили і не травмуватись',
      'планую день щоб побачити свій абсолютний максимум у присіді, скільки кроків',
      'як безпечно перевірити найважчий разовий підйом у становій',
      'варто реально пробувати один максимальний повтор чи просто прикинути',
      'як вибрати спроби коли йдеш на новий разовий максимум',
      'тупо пробувати максимальну вагу щомісяця?',
      'хочу подивитись скільки вижму на один раз, вперше, поради',
      'в день спроби на разовий максимум скільки відпочивати між підходами',
      'порахувати свій разовий ліміт з сету на 5 чи перевірити по-справжньому',
      'як часто перевіряти свою максимальну силу на один раз',
      "в суботу йду на найважчий присід в житті, як до нього розім'ятись по вагах",
      'який протокол для дня перевірки максимуму',
      'можна перевірити стелю на один раз без страхувальника',
      'тест на один раз на всі сили чи тест на кількість повторів, що краще',
    ],
  },
  k_shift_work: {
    ex: [
      'i do 12s at the hospital, three on four off, how do i fit lifting around that',
      'work nights at a warehouse, when is the best time to hit the gym, before or after',
      'nurse doing overnights, should i lift when i wake up at 3pm',
      'i get home at 7am after a night, can i train then or should i sleep first',
      'police shifts all over the place, how do i keep lifting consistent',
      'factory job rotating mornings afternoons nights, gym plan?',
      'i sleep during the day and work at night, when do i eat and lift',
      'firefighter on 24h shifts, how to schedule workouts',
      'how to lift when my work hours change every week',
      'is training at 2am after my shift bad for gains',
      '4 on 4 off twelve hour shifts, how many gym days realistic',
      'shift worker here always tired, how to structure the week',
      'flight attendant with crazy hours and timezones, how to keep training',
      'doing graveyard shift, should i work out before going in or when i get off',
    ],
    exUk: [
      'працюю добами в лікарні, три через чотири, як вписати зал',
      'працюю вночі на складі, коли краще в зал, до чи після',
      'графік міняється з денних на нічні кожен тиждень, як тримати режим',
      'медсестра на нічних, тренуватись коли прокидаюсь о 15:00?',
      'приходжу о 7 ранку після ночі, можна тренуватись чи спочатку спати',
      'в поліції зміни як попало, як тренуватись стабільно',
      'на заводі зміни ранок день ніч по черзі, як планувати зал',
      'сплю вдень працюю вночі, коли їсти і тренуватись',
      'рятувальник на добових чергуваннях, як розкласти тренування',
      'як качатись коли години роботи міняються щотижня',
      'тренуватись о 2 ночі після зміни погано для результату?',
      'чотири через чотири по 12 годин, скільки днів у залі реально',
      'працюю позмінно вічно втомлений, як побудувати тиждень',
      'стюардеса з божевільним графіком і часовими поясами, як тренуватись',
      'працюю в нічну зміну, качатись перед роботою чи після',
    ],
  },
  k_maintenance: {
    ex: [
      'exams coming for 6 weeks, whats the least gym i can do and not shrink',
      'new baby at home, can i just keep what i have with like 1 short session a week',
      'just want to hold my muscle for now not grow, how much training is enough',
      'work is crazy this quarter, bare minimum to not go backwards',
      'if i only hit each muscle once a week will i keep my size',
      'how few sets per week keeps my strength from dropping',
      "i'm happy with my body, how do i just keep it without killing myself in the gym",
      'moving house next month, 2 quick workouts a week enough to not lose anything',
      'does cutting volume in half make me lose muscle if i keep the weights heavy',
      'cruise mode: how do i coast without losing progress',
      'can i drop to twice a week and hold onto my gains',
      'during a stressful period what is the lowest dose of lifting that works',
      'keep muscle with minimal effort possible?',
      'busy season at work, idc about progress, just dont wanna lose it',
      'how long can i do a skeleton routine before i start losing strength',
    ],
    exUk: [
      'сесія на 6 тижнів, який мінімум залу щоб не здутись',
      'народилась дитина, можна просто тримати форму одним коротким тренуванням на тиждень',
      "хочу поки просто зберегти м'язи а не рости, скільки треба тренуватись",
      'на роботі завал цей квартал, абсолютний мінімум щоб не відкотитись',
      "якщо кожен м'яз раз на тиждень, я збережу об'єми?",
      'скільки мінімум підходів на тиждень щоб сила не падала',
      'мене все влаштовує в тілі, як просто утримати без вбивання в залі',
      'переїжджаю наступного місяця, двох швидких тренувань на тиждень вистачить щоб нічого не втратити',
      "якщо урізати обсяг вдвічі але лишити важкі ваги м'язи підуть?",
      'режим круїзу, як плисти і не втратити прогрес',
      'можна перейти на двічі на тиждень і втримати результат',
      'в стресовий період яка найменша доза заліза працює',
      "зберегти м'язи з мінімальними зусиллями можливо?",
      'гарячий сезон на роботі, пофіг на прогрес, просто не хочу втратити',
      'як довго можна на урізаній програмі поки сила не почне падати',
    ],
  },
  k_holidays: {
    ex: [
      "going to my parents for two weeks over xmas and there's no gym, what now",
      'family dinners every day this december, how do i not undo my year',
      "new year's week gym is shut, will i lose everything",
      'christmas break, should i take it off completely or do something',
      'stuffing myself at every holiday party, is my progress ruined',
      'between christmas and new year i wont be able to train normally, plan?',
      'festive season with cookies everywhere, how to keep lifting on track',
      'easter weekend gym closed 4 days, is that a problem',
      'visiting in-laws over the holidays, quick hotel room stuff?',
      'holiday season always kills my routine, how do people handle it',
      'gonna be at a ski resort for new years, how to keep the gains',
      'overate at the christmas table 3 days in a row, how bad is it',
      'public holidays next week, gym has weird hours, how do i adjust',
      'is a week off over the festive season actually good for me',
    ],
    exUk: [
      'їду до батьків на два тижні на різдво а залу там нема, що робити',
      'сімейні застілля кожен день у грудні, як не звести нанівець рік',
      'тиждень нового року зал закритий, все втрачу?',
      'різдвяні канікули, повністю відпочити чи щось робити',
      "об'їдаюсь на кожному святковому застіллі, прогрес зруйновано?",
      'між різдвом і новим роком не зможу нормально тренуватись, план?',
      'святковий сезон печиво всюди, як тримати тренування',
      'на великдень зал закритий 4 дні, це проблема?',
      'гостюю у родичів на свята, щось швидке в кімнаті?',
      'нормально просто їсти і відпочивати на святковому тижні',
      'святковий сезон завжди вбиває мій режим, як люди з цим справляються',
      'буду на гірськолижному курорті на новий рік, як зберегти форму',
      'три дні поспіль переїв за святковим столом, наскільки погано',
      'наступного тижня вихідні дні, у залу дивний графік, як підлаштуватись',
      'тиждень без залу на свята це взагалі корисно?',
    ],
  },
  k_heat: {
    ex: [
      'sweating buckets and dizzy between sets in july',
      'my garage gym turns into an oven in summer, tips',
      'why does my bench feel heavier on those hot sticky days',
      "is it dangerous to deadlift when it's like a sauna in the gym",
      'how much water should i drink training in a heatwave',
      'summer training outside in the sun, what should i watch for',
      'no air conditioning, felt faint after squats, is it the heat',
      'gym is like a greenhouse in august, should i train lighter',
      "i live somewhere tropical, how do i train when it's humid all the time",
      'cramps and headache after lifting on a scorching day',
      'should i move my workout to early morning when it gets super hot out',
      'electrolytes for sweaty summer gym sessions?',
      'felt sick and weak during the heat wave workout, normal?',
      'how to not overheat in a stuffy basement gym',
    ],
    exUk: [
      'надворі 35 градусів а вентилятори в залі ледве крутять, як тренуватись і не здохнути',
      'піт ллє відрами і голова крутиться між підходами в липні',
      'мій гаражний зал влітку перетворюється на духовку, поради',
      'чому жим здається важчим в спекотні душні дні',
      'небезпечно робити станову коли в залі як у сауні?',
      'скільки води пити тренуючись у спеку',
      'тренування влітку на вулиці на сонці, на що зважати',
      'кондиціонера нема, після присідань мало не знепритомнів, це від спеки?',
      'зал як теплиця в серпні, тренуватись легше?',
      'живу в тропіках, як тренуватись коли постійно волого і жарко',
      'судоми і головний біль після тренування в пекельний день',
      'переносити тренування на ранок коли на вулиці дуже жарко?',
      'електроліти на спітнілі літні тренування?',
      'в спеку на тренуванні стало погано і слабкість, це нормально?',
      'як не перегрітись у задушливому підвальному залі',
    ],
  },
  k_teen_lifting: {
    ex: [
      '9th grade, too early to start lifting?',
      "i'm in middle school and want to get strong, can i use real weights",
      'my 13 yo daughter wants to join me at the gym, will it hurt her growth',
      'am i too young to squat with a barbell, im turning 15',
      'kid in year 8 asking if dumbbells will make him shorter',
      "does heavy stuff mess up growth plates when you're still growing",
      'high school freshman here, what should i do in the weight room safely',
      'parents wont let me lift because im 14, are they right',
      'is it ok for a 12 year old to do push ups and light weights',
      'should a teenager avoid maxing out while still growing',
      "i'm 16, can i deadlift heavy or wait till 18",
      'son plays football and coach wants him lifting at 14, safe?',
      'school age lifting program for my boy, how light should it be',
      'still in school and havent finished growing, is the gym bad for me',
    ],
    exUk: [
      '9 клас, не рано починати качатись?',
      'я в середній школі і хочу стати сильним, можна брати справжні ваги',
      'моя 13-річна донька хоче зі мною в зал, це не зашкодить росту?',
      'я не замалий щоб присідати зі штангою, мені скоро 15',
      'восьмикласник питає чи гантелі зроблять його нижчим',
      'важкі ваги пошкоджують зони росту поки ще ростеш?',
      'я в старшій школі, що безпечно робити в тренажерці',
      'батьки не пускають мене в зал бо мені 14, вони праві?',
      '12-річному можна віджимання і легкі ваги?',
      'підлітку краще не йти на максимальні ваги поки росте?',
      'мені 16, можна тягнути важко чи чекати до 18',
      'син грає у футбол і тренер хоче щоб він качався в 14, це безпечно?',
      'з якого віку дітям можна в тренажерний зал',
      'програма для школяра, наскільки легкою вона має бути',
      'я ще школяр і не доріс, зал мені шкодить?',
    ],
  },
  k_older_lifter: {
    ex: [
      'just turned 52 and my body doesnt bounce back like at 30, how should i adjust training',
      'grandpa here, want to keep lifting, what should i change',
      'at my age joints complain more, should i lift lighter and more reps',
      "i'm in my late 50s, how many days a week is smart",
      "retired and want to start weights, 67, what's different for me",
      'menopause and in my 50s, how should my lifting change',
      'over 40 now and every session leaves me wrecked for days, adjust how',
      'aging lifter, keep going heavy or back off',
      'how do guys in their 60s keep strong without getting hurt',
      'since hitting 45 i need longer between leg days, is that just age',
      'should older people still do squats and deadlifts',
      'my dad is 70 and wants a program, what should it focus on',
      'is it too late to build muscle at 55',
      "midlife lifter, what's the priority now, strength, muscle or mobility",
      'old man strength: how to train smart after half a century',
    ],
    exUk: [
      'мені щойно 52 і тіло не відновлюється як у 30, як змінити тренування',
      'я вже дідусь, хочу далі качатись, що міняти',
      'в моєму віці суглоби скаржаться більше, легше і більше повторів?',
      'мені під 60, скільки днів на тиждень розумно',
      'на пенсії хочу почати з вагами, мені 67, що для мене інакше',
      'менопауза і мені за 50, як має змінитись тренування',
      'мені вже за 40 і кожне тренування вибиває на кілька днів, як підлаштуватись',
      'качок у віці, продовжувати важко чи скинути',
      'як чоловіки за 60 лишаються сильними і не травмуються',
      'після 45 треба більше часу між днями ніг, це просто вік?',
      'людям старшого віку ще варто присідати і тягнути?',
      'татові 70 і він хоче програму, на чому зосередитись',
      "в 55 вже пізно набирати м'язи?",
      "середній вік, що тепер пріоритет, сила м'язи чи рухливість",
      'як тренуватись розумно після півстоліття',
    ],
  },
  k_women_training: {
    ex: [
      "i'm a woman, do i need a different kind of program than my boyfriend",
      'should a girl lift the same way guys do or is it different for our bodies',
      'as a female can i do the same heavy stuff as the men in the gym',
      'do women recover faster between sets than men',
      'does my period cycle mean i should train differently certain weeks',
      'my husband and i want to follow one plan, does it need changes for me',
      'are ladies supposed to do more reps and lighter weight',
      "women's workouts vs men's, is there actually a difference",
      'female lifter here, do i need more volume than a man',
      'can girls do barbell squats and bench like the guys',
      'is there a separate routine for women or is that marketing',
      'does being a woman change how many days i should lift',
      "i'm a girl, is heavy lifting safe for my hormones",
      'why are gym programs for women always pink dumbbells and cardio',
      "should a woman's plan focus on glutes or train everything like a man",
    ],
    exUk: [
      'я жінка, мені потрібна інша програма ніж у мого хлопця?',
      'дівчині тренуватись так само як хлопцям чи для нашого тіла інакше',
      'як жінка можу робити такі ж важкі вправи як чоловіки в залі?',
      'жінки відновлюються між підходами швидше ніж чоловіки?',
      'через цикл треба тренуватись по-різному в різні тижні?',
      'ми з чоловіком хочемо один план, для мене треба щось міняти?',
      'дамам треба більше повторів і менша вага?',
      'жіночі тренування проти чоловічих, є реальна різниця?',
      'я дівчина-атлет, мені потрібен більший обсяг ніж чоловікові?',
      'дівчата можуть присідати зі штангою і жати як хлопці?',
      'є окрема програма для жінок чи це маркетинг',
      'те що я жінка впливає на кількість днів у залі?',
      'я дівчина, важкі ваги безпечні для гормонів?',
      'чому програми для жінок завжди рожеві гантельки і кардіо',
      'жіночий план має бути про сідниці чи все як у чоловіків',
    ],
  },
  k_pushup_progression: {
    ex: [
      'i collapse flat on my face when i try to push myself up off the floor, where do i start',
      "can't lift my body off the ground even once with my arms, what easier version",
      'doing them against the wall now, when do i move down to the floor',
      'on my knees i can do 8, how do i get to real ones on toes',
      'hands on the kitchen counter pushing up, next step?',
      'zero floor presses with bodyweight, how do i build up',
      'my arms shake and i sink halfway on the floor press up thing',
      'only managing the lowering part of a push up, is that a good way to learn',
      "what's the ladder from wall to full push ups",
      'how many weeks to go from none to 10 proper push ups',
      'chest keeps hitting the floor and i cant push back up, help',
      'incline on a bench or knees down, which gets me to a real pushup faster',
      "i'm a total noob at bodyweight, can't even do one pushup from the ground",
      'slow negatives for pushups, do they work',
      "gf wants to be able to do push ups, she's at zero, plan?",
    ],
    exUk: [
      'падаю обличчям у підлогу коли пробую відтиснутись, з чого почати',
      'зараз відтискаюсь від стіни, коли переходити на підлогу',
      'з колін роблю 8, як дійти до нормальних на носках',
      'відтискаюсь від кухонної стільниці, що далі?',
      'нуль віджимань від підлоги, як натренувати',
      'руки трусяться і я провалююсь на пів дорозі у віджиманні',
      'виходить тільки повільно опуститись, так можна навчитись?',
      'яка драбинка від стіни до повних віджимань',
      'скільки тижнів від нуля до 10 нормальних віджимань',
      'груди лягають на підлогу і не можу відтиснутись назад, допоможіть',
      'від лавки чи з колін, що швидше приведе до справжнього віджимання',
      'я повний нуль у вправах з власною вагою, навіть раз від підлоги не віджимаюсь',
      'повільні опускання для віджимань працюють?',
      'дівчина хоче навчитись віджиматись, зараз нуль, план?',
    ],
  },
  k_etiquette: {
    ex: [
      'some dude has been sitting on the bench on his phone for 20 min, can i say something',
      'am i supposed to wipe the seat after i use it',
      'is it rude to ask to share a machine between sets',
      'how do i ask the guy hogging the rack if im allowed to jump in',
      'left my plates on the bar and got yelled at, whats the rule',
      'can i leave my towel on a bench to save it while i go do something else',
      'should i rerack dumbbells even if they were lying on the floor when i got there',
      'someone was filming in the gym and i walked into their shot, am i the bad guy',
      'is it weird to give someone form advice without them asking',
      'how close can i stand to someone doing dumbbell presses in front of the mirror',
      'girl at the gym, is it ok to ask a stranger to spot me',
      'dropping the weights loudly, is that frowned upon',
      "polite way to tell someone they're in my way at the mirror",
      'busy gym at 6pm, how do i not annoy people while doing circuits',
      'is grunting loud on heavy sets bad manners',
    ],
    exUk: [
      'якийсь тип сидить на лаві в телефоні 20 хвилин, можна щось сказати',
      'я маю протирати сидіння після себе?',
      'грубо попросити по черзі користуватись тренажером між підходами?',
      'як попросити хлопця що займає стійку дозволити мені підходити разом',
      'лишив блини на грифі і на мене накричали, яке правило',
      'можна лишити рушник на лаві щоб зайняти поки роблю інше',
      'треба ставити гантелі на місце навіть якщо вони вже валялися на підлозі',
      'хтось знімав відео в залі а я пройшов в кадр, я винен?',
      'дивно давати пораду по техніці якщо не просили?',
      'наскільки близько можна стати до когось хто жме гантелі перед дзеркалом',
      'я дівчина, норм попросити незнайомця пострахувати',
      'кидати ваги з гуркотом це погано?',
      'як ввічливо сказати що людина заважає мені біля дзеркала',
      'повний зал о 18:00, як не бісити людей роблячи коло',
      'голосно кричати на важких підходах це невиховано?',
    ],
  },
  k_beta_alanine: {
    ex: [
      'pre workout gave me itchy tingly skin, which ingredient is that and is it useful',
      'the stuff that buffers lactic burn for high rep sets, worth buying',
      'does the tingle ingredient help with 15 rep sets or is it placebo',
      'my lips and ears get pins and needles 20 min after preworkout, should i worry',
      'carnosine booster supplement, any real benefit for lifting',
      'should i load the itchy amino acid daily or just take it before training',
      'is there a supplement that lets me squeeze out 1-2 more reps when the burn hits',
      'my face tingles like crazy after my scoop, dangerous or harmless',
      'stuff that helps with muscle burn on long sets, which one',
      'that tingling amino in preworkouts, how many grams a day',
      'can i split the dose to avoid the prickly skin feeling',
      'does the pins and needles supplement do anything for strength or only endurance',
      'buying pure powder of the tingle stuff instead of preworkout, smart?',
      'that ingredient that makes you itchy, does it work for crossfit style workouts',
    ],
    exUk: [
      'порошок від якого обличчя і руки колються як голками, реально допомагає?',
      'від передтрену свербить і поколює шкіру, що це за інгредієнт і чи він корисний',
      "штука що буферизує печіння в м'язах на багатоповторних сетах, варто купувати",
      'інгредієнт що поколює допомагає на сетах по 15 чи це плацебо',
      'губи і вуха колють через 20 хв після передтрену, хвилюватись?',
      'добавка для карнозину, є реальна користь для залу',
      'ту амінокислоту що свербить пити щодня чи тільки перед тренуванням',
      "є добавка щоб вичавити ще 1-2 повтори коли печуть м'язи",
      'обличчя шалено поколює після мірної ложки, небезпечно чи ні',
      "щось що допомагає від печіння м'язів на довгих сетах, що саме",
      'та амінокислота що поколює в передтренах, скільки грам на день',
      'можна ділити дозу щоб не було відчуття голочок на шкірі',
      'добавка з поколюванням щось дає для сили чи тільки для витривалості',
      'купити чистий порошок того що поколює замість передтрену, розумно?',
      'інгредієнт від якого свербиш, працює для кросфіт тренувань?',
    ],
  },
  k_fish_oil: {
    ex: [
      'those big yellow capsules from fish, do lifters actually need them',
      'my mom says i should take the fish capsules for my joints, legit for gym',
      'the omega pills, do they help sore muscles recover',
      'cod liver stuff, worth it for someone who trains 4x a week',
      'i hate eating salmon, should i just take the fishy capsules instead',
      'do the fish pills make you build muscle faster or is that hype',
      'fishy burps from my supplement, is it even doing anything',
      'krill capsules vs the regular fish ones for training',
      'how many grams of the fish capsules per day for joints and recovery',
      'is swallowing fish oil pills pointless if i eat sardines',
      'those gel caps with epa dha, do they matter for muscle',
      'vegan alternative to fish capsules, algae ones any good for lifters',
      'will the fish capsules reduce inflammation after heavy leg day',
      'should i take the omega capsule in the morning or with dinner',
    ],
    exUk: [
      'ті великі жовті капсули з риби, качкам вони реально потрібні?',
      'мама каже пити рибні капсули для суглобів, це реально для залу',
      "таблетки омега допомагають м'язам відновлюватись після крепатури?",
      'печінка тріски в капсулах, варто якщо тренуюсь 4 рази на тиждень',
      'ненавиджу лосося, може просто пити рибні капсули замість нього',
      "рибні таблетки допомагають швидше набирати м'язи чи це хайп",
      'після добавки відрижка рибою, вона взагалі щось робить?',
      'капсули з крилю проти звичайних рибних для тренувань',
      'скільки грамів рибних капсул на день для суглобів і відновлення',
      'ковтати рибні капсули безглуздо якщо я їм сардини?',
      "желатинові капсули з EPA DHA, мають значення для м'язів?",
      'веганська альтернатива рибним капсулам, водорості норм для спортсменів',
      'рибні капсули зменшать запалення після важкого дня ніг?',
      'варто витрачати гроші на рибні таблетки новачку в залі',
      'капсулу омеги пити зранку чи з вечерею',
    ],
  },
  k_core_stability: {
    ex: [
      'want a stronger trunk so my squat doesnt fold, which moves',
      'my middle feels like jelly under a heavy bar, how do i toughen it up',
      'planks bore me, what else trains the belly muscles for lifting',
      'exercises where you resist twisting, are they good for the stomach area',
      'need a stronger torso for carrying heavy stuff, what to add',
      'ab wheel vs hanging leg raise vs pallof thing, which for a solid midsection',
      'i do 100 crunches a day but still feel weak in the middle when lifting',
      'how often should i train my tummy muscles',
      "what's the point of carrying heavy dumbbells walking around, core?",
      'side planks and dead bugs, enough for a strong trunk',
      'lower back and belly both feel weak, what drills do i add',
      'exercises to stop my body swaying when i do one arm presses',
      'best way to make my midsection rock solid for deadlifts',
      'should i train my stomach with weights or bodyweight only',
    ],
    exUk: [
      'хочу сильніший корпус щоб у присіді не складатись, які вправи',
      'середина тіла як желе під важкою штангою, як укріпити',
      "планка набридла, що ще тренує м'язи живота для залізу",
      'вправи де опираєшся скручуванню, корисні для живота?',
      'потрібен сильніший тулуб щоб носити важке, що додати',
      'ролик для преса чи підйом ніг у висі чи ота паллоф штука, що для міцного корпусу',
      'роблю 100 скручувань на день але в середині слабкість коли піднімаю',
      "як часто тренувати м'язи живота",
      'який сенс ходити з важкими гантелями в руках, це на кор?',
      'бокова планка і мертвий жук, вистачить для сильного тулуба',
      'поперек і живіт обидва слабкі, які вправи додати',
      'вправи щоб тіло не хиталось коли жму однією рукою',
      "як зробити середину тіла кам'яною для станової",
      'живіт тренувати з вагою чи тільки з власною вагою',
    ],
  },
  k_ankle_mobility: {
    ex: [
      'when i sit down low my weight goes to my toes and my heels pop off the floor',
      "i can't squat deep without falling backward unless i put something under my heels",
      "my feet feel stuck and i can't bend at the lower leg enough to get low",
      'why do i need a plate under my feet to get to the bottom',
      'heels rise off the floor when i try a deep bodyweight squat',
      'my shins wont tilt forward much, is that why my squat stops high',
      'stiff lower legs from years of running, how do i loosen them for squatting',
      'knee to wall test i fail badly, what stretches',
      'should i buy those raised heel lifting shoes because my feet are tight',
      "can't do a full deep sit on my heels like asians do, calves too tight?",
      'calf and achilles tightness is stopping my squat depth',
      'i tip onto my toes at the bottom of goblet squats',
      'heel wedges for squatting, crutch or fine',
      'old ankle sprain and now my squat is limited on one side, what to do',
      'how do i get more bend at the joint above my foot for deeper squats',
    ],
    exUk: [
      "коли сідаю низько вага йде на носки і п'яти відриваються від підлоги",
      "не можу глибоко присісти не падаючи назад якщо не підкласти щось під п'яти",
      'стопи ніби застрягли і гомілка не нахиляється щоб сісти низько',
      'чому мені треба блин під ногами щоб сісти до низу',
      "п'яти піднімаються коли пробую глибокий присід без ваги",
      'гомілки майже не нахиляються вперед, тому присід зупиняється високо?',
      'тугі литки після років бігу, як розробити для присідань',
      'тест коліно до стіни провалюю, які розтяжки',
      'купити штангетки з підйомом бо стопи тугі?',
      "не можу сісти глибоко на п'яти як азіати, литки тугі?",
      'литки і ахілл тугі і не дають присісти глибше',
      'внизу гоблет присіду перекочуюсь на носки',
      "клини під п'яти для присіду, милиця чи норм",
      'старе розтягнення гомілкостопа і тепер присід обмежений з одного боку, що робити',
      'як отримати більше згину в суглобі над стопою для глибшого присіду',
    ],
  },
  k_gassed: {
    ex: [
      'my lungs quit before my legs do on anything over 10 reps',
      "i'm fine strength wise but huffing like a dog halfway through a set of lunges",
      'heart rate through the roof after one round of kettlebell swings, how do i build stamina',
      "can't catch my breath between sets even with 3 min rest",
      "muscles have more in them but i'm panting and have to rack it",
      'breathing is my weak link in the gym not strength',
      'how do i get fitter so leg day doesnt leave me wheezing',
      'puffing hard after a set of 20 squats, is my cardio just trash',
      'my stamina sucks in the gym, i run out of air before the reps are done',
      'i get dizzy and short of breath on high rep sets, conditioning?',
      'how to stop gasping for air after every set of burpees',
      'what should i add so i dont run out of gas during a workout',
      'my engine is weak, strength ok but i blow up on circuits',
      'friend can do sets back to back, im sucking wind after one, why',
      'air runs out on long sets, any drills for better wind',
    ],
    exUk: [
      'легені здаються раніше за ноги на всьому що більше 10 повторів',
      'по силі норм але дихаю як пес на половині підходу випадів',
      'пульс зашкалює після одного раунду махів гирею, як набрати витривалість',
      'не можу віддихатись між підходами навіть з відпочинком 3 хв',
      "в м'язах ще є сили але я задихаюсь і кладу штангу",
      'в залі моє слабке місце дихання а не сила',
      'як стати витривалішим щоб після дня ніг не хрипіти',
      'важко дихаю після 20 присідань, в мене просто погане кардіо?',
      'витривалість в залі жахлива, повітря закінчується раніше ніж повтори',
      'на багатоповторних підходах паморочиться і не вистачає дихання, це кондиції?',
      'як перестати хапати повітря після кожного сету берпі',
      'що додати щоб не видихатись посеред тренування',
      'мотор слабкий, сила норм але на колових здуваюсь',
      'друг робить підходи один за одним а я після одного задихаюсь, чому',
      'повітря закінчується на довгих сетах, які вправи для дихалки',
    ],
  },
  k_sticking_point: {
    ex: [
      'bar flies off my chest then just freezes about 10cm up',
      'i get out of the bottom of my squat fine but die right above parallel',
      'deadlift leaves the floor then stops dead at my knees',
      'the last few inches of my bench press are where i always get stuck',
      'halfway up everything grinds to a halt, how do i get past that spot',
      'my overhead press stalls right at forehead height',
      'what do i do about the part of the lift where the bar stops moving',
      'i can lower it fine but always stall at the same spot coming up on bench',
      'stuck just before lockout on my deadlift, hips wont finish',
      'the bar slows to a crawl in the middle of my press, what exercises help',
      'pin presses for the spot where i get stuck, do they work',
      'i lose the rep just out of the hole every time',
      'weak at the top of my bench, arms cant straighten',
      'same point of failure every heavy squat, just above the bottom',
      'how to get stronger at the exact spot where the lift dies',
    ],
    exUk: [
      'гриф злітає з грудей а потім завмирає сантиметрів на 10 вище',
      'з низу присіду виходжу норм але вмираю трохи вище паралелі',
      'станова відривається від підлоги і зупиняється на колінах',
      'останні сантиметри жиму лежачи це де я завжди застрягаю',
      'на пів дорозі все зупиняється, як пройти це місце',
      'армійський жим застрягає рівно на рівні лоба',
      'що робити з тією частиною руху де штанга перестає рухатись',
      'опускаю нормально але завжди застрягаю в тому ж місці на підйомі в жимі',
      'застрягаю перед фіксацією у становій, таз не дотискає',
      'штанга ледве повзе посередині жиму, які вправи допоможуть',
      'жим від упорів для місця де застрягаю, працює?',
      'щоразу втрачаю повтор одразу після виходу з низу',
      'слабкий у верхній частині жиму, руки не випрямляються',
      'та сама точка відмови на кожному важкому присіді, трохи вище низу',
      'як стати сильнішим саме в тому місці де рух помирає',
    ],
  },
  k_mind_muscle: {
    ex: [
      'when i do rows its all biceps burning and my back feels nothing',
      'i do chest press but only my shoulders get tired, how to make my chest do the work',
      'doing hip thrusts and i feel it in my hamstrings and lower back, not my bum',
      'how do i actually sense the target muscle squeezing during a rep',
      'lat pulldown only my forearms feel it, how do i connect with my back',
      'do i need to think about the muscle working for it to grow',
      "my legs don't feel anything on leg press, just my knees",
      'how do bodybuilders feel their muscle contracting on every single rep',
      'rear delt flyes i just feel my traps, what am i missing',
      'should i go lighter so i can focus on feeling the muscle',
      'squeeze and hold at the top to feel the muscle, is that a real thing',
      'i never get that pump feeling in my back like other people describe',
      'how to learn to contract my glutes on purpose',
      "on flyes i don't feel my pecs stretch or squeeze at all",
      'focusing on the working muscle vs just moving the weight, does it matter',
    ],
    exUk: [
      'коли роблю тягу тільки біцепси горять а спина нічого не відчуває',
      'роблю жим на груди але втомлюються тільки плечі, як змусити груди працювати',
      'на ягодичному мості відчуваю в задній поверхні стегна і попереку а не в сідницях',
      "як реально відчути що цільовий м'яз скорочується на повторі",
      'на тязі верхнього блоку відчувають тільки передпліччя, як включити спину',
      "треба думати про м'яз щоб він ріс?",
      'ноги нічого не відчувають на жимі ногами, тільки коліна',
      "як бодібілдери відчувають скорочення м'яза на кожному повторі",
      'на розведеннях на задню дельту відчуваю тільки трапецію, що не так',
      "може взяти легше щоб зосередитись на відчутті м'яза",
      "затримка і стискання вгорі щоб відчути м'яз, це реально працює?",
      'ніколи не маю того відчуття напомпованої спини як інші розповідають',
      'як навчитись свідомо напружувати сідниці',
      'на розведеннях взагалі не відчуваю розтягнення чи стискання грудних',
      "фокус на робочому м'язі чи просто рухати вагу, є різниця?",
    ],
  },
  k_partial_reps: {
    ex: [
      'i only lower the bar halfway on bench, am i shortchanging myself',
      'guy at gym does tiny little bounces at the bottom of curls, is that a thing',
      'do i have to straighten my arms all the way every rep or is half enough',
      'going only a quarter of the way down on leg press lets me use way more weight, worth it?',
      'should the bar touch my chest every time or can i stop a few inches above',
      "when i'm too tired for full reps can i keep doing half ones",
      "i don't lock out on pushdowns, just keep it in the middle range, bad?",
      'top half only squats, waste of time?',
      'is doing the bottom half of a movement better for growth than the top half',
      'my reps are getting shorter and shorter as the set goes on, should i allow that',
      'full stretch full squeeze or just pump out the middle bit',
      'doing mini reps at the end of a set after failure, good idea',
      'the depth of each rep, how much does it actually matter',
      'cutting the motion short so i can lift heavier, cheating or smart',
    ],
    exUk: [
      'опускаю штангу тільки до половини на жимі, я себе обкрадаю?',
      'хлопець у залі робить маленькі пружинки внизу на біцепс, це щось означає',
      'треба до кінця розгинати руки кожен повтор чи половини вистачить',
      'на жимі ногами опускаю лише на чверть і беру більше ваги, варто?',
      "короткі пружинні повтори в розтягнутому положенні будують м'язи?",
      'штанга має торкатись грудей кожен раз чи можна зупинитись вище',
      'коли вже немає сил на повні повтори можна добивати половинками',
      'не розгинаю руки до кінця на блоці на трицепс, тримаю посередині, погано?',
      'присідання тільки верхня половина, марна трата часу?',
      'нижня половина руху краща для росту ніж верхня?',
      'повтори стають все коротшими до кінця сету, дозволяти це?',
      'повне розтягнення і повне стискання чи просто качати середину',
      'міні повтори в кінці сету після відмови, гарна ідея',
      'глибина кожного повтору наскільки реально важлива',
      'вкорочую рух щоб підняти більше, чітинг чи розумно',
    ],
  },
  k_bands: {
    ex: [
      'those stretchy rubber loops, can they actually replace dumbbells',
      'bought a set of elastic tubes with handles, can i get jacked with them',
      'travel a lot, is a pack of stretch cords enough to keep muscle',
      'the colored latex strips from amazon, real training or a toy',
      'can rubber tension build as much muscle as iron plates',
      'doing rows with an elastic tied to a door, is that legit training',
      'is the pull from a stretchy cord too easy at the start of the movement',
      'mini loops around my knees for glutes, do they grow anything',
      'heavy duty pull up assist rubber things, what else can i do with them',
      'is it worth adding elastic to my barbell like the powerlifters do',
      'physio gave me rubber strips, can i build real strength with them',
      'which strength of stretchy loop should i buy, the black or the red',
      'full workout with only elastic resistance, does it work for biceps and chest',
      'elastic vs free weights, can my legs grow with just stretch bands',
      'resistance from rubber vs gravity weight, which builds more',
    ],
    exUk: [
      'ті розтяжні гумові петлі реально можуть замінити гантелі?',
      'купив набір еластичних трубок з ручками, можна з ними накачатись',
      "багато їжджу, набору гумових джгутів вистачить щоб тримати м'язи",
      'кольорові латексні стрічки з розетки, це тренування чи іграшка',
      "опір гуми будує стільки ж м'язів як залізні блини?",
      "роблю тягу з гумою прив'язаною до дверей, це нормальне тренування",
      'тяга від гуми занадто легка на початку руху?',
      'міні петлі навколо колін для сідниць, щось ростуть від цього?',
      'товсті гуми для допомоги в підтягуваннях, що ще з ними робити',
      'варто чіпляти гуму на штангу як пауерліфтери?',
      'фізіотерапевт дав гумові стрічки, можна набрати справжню силу',
      'яку жорсткість петлі купити, чорну чи червону',
      'повне тренування тільки з еластичним опором працює на біцепс і груди?',
      'гума проти вільних ваг, ноги виростуть тільки з джгутами?',
      'опір від гуми чи вага гравітації, що краще будує',
    ],
  },
  k_program_hopping: {
    ex: [
      'i start a new routine from youtube every couple weeks, is that why im not getting anywhere',
      'get bored and switch plans all the time, bad habit?',
      'do muscles need to be surprised with new stuff every week',
      'how long should i stick with one workout plan before changing',
      'i jump from one influencer program to another monthly, is that hurting me',
      'is keeping the same exercises for months boring my muscles',
      'someone said my body adapts so i need to shock it constantly, true?',
      'how many weeks does it take to see if a routine is working',
      'been doing 5 different programs this year, still same strength lol',
      'should i change up my workout the moment it gets boring',
      'is it ok to run the same plan for 6 months straight',
      'keep the program or find a new one each month for variety',
      'i can never stay on one plan, what do i lose by switching',
      'changing gym routine every few weeks to keep it fresh, smart or not',
      'is doing totally different workouts each session a good way to grow',
    ],
    exUk: [
      'починаю нову програму з ютубу кожні пару тижнів, тому і не росту?',
      'набридає і постійно міняю плани, погана звичка?',
      "м'язи треба дивувати новим щотижня?",
      'скільки часу триматись однієї програми перш ніж міняти',
      'щомісяця перестрибую з програми одного блогера на іншу, це шкодить?',
      "одні й ті самі вправи місяцями набридають м'язам?",
      'хтось сказав що тіло звикає і його треба постійно шокувати, правда?',
      'скільки тижнів треба щоб зрозуміти чи програма працює',
      'цього року вже 5 різних програм, сила та сама хаха',
      'міняти тренування одразу як стає нудно?',
      'нормально ганяти один план 6 місяців поспіль',
      'лишити програму чи шукати нову щомісяця для різноманіття',
      'ніколи не можу втриматись на одному плані, що я втрачаю від змін',
      'міняти програму в залі кожні кілька тижнів щоб було свіжо, розумно чи ні',
      'робити зовсім різні тренування кожного разу це добрий спосіб рости?',
    ],
  },
  k_cardio_order: {
    ex: [
      'do i hop on the bike before touching the weights or at the end',
      'i jog 20 min and then lift, is that stealing my strength',
      'running and lifting on the same day, which goes first',
      'should the stairmaster be my warm up or my finisher',
      'if i swim and lift in one visit, what order',
      'doing the elliptical first makes my legs tired for squats, should i flip it',
      'want to lose fat and gain strength, treadmill at start or end of session',
      'rowing machine 30 min then weights, or weights then rowing',
      'a long run before leg day, does it ruin the lifting part',
      'cycling class then gym floor, is that a bad combo',
      "i do my jog after lifting but i'm dead, should i run first",
      'cardio at the end of weights for fat burning myth or legit',
      'same session: 5k run and upper body, which one goes first',
      'hiit on the bike before my strength work or after',
      'should my walk on the incline treadmill come before or after lifting',
    ],
    exUk: [
      'біжу 20 хв а потім качаюсь, це краде в мене силу?',
      'біг і зал в один день, що першим',
      'степер має бути розминкою чи добиванням у кінці',
      'якщо плаваю і качаюсь за один візит, в якому порядку',
      'орбітрек спочатку втомлює ноги для присідань, поміняти?',
      'хочу скинути жир і набрати силу, доріжка на початку чи в кінці',
      'гребний тренажер 30 хв потім ваги, чи ваги потім гребля',
      'довгий біг перед днем ніг зіпсує силову частину?',
      'сайкл тренування а потім зал, погана комбінація?',
      'бігаю після заліза але вже мертвий, може бігти першим',
      'кардіо після силових для спалення жиру міф чи правда',
      'одне тренування: 5 км біг і верх тіла, що першим',
      'інтервали на велику до силової чи після',
      'ходьба під нахилом на доріжці має бути до чи після ваг',
    ],
  },
  k_exercise_order: {
    ex: [
      'which comes first in a session, the big barbell moves or the small arm stuff',
      'is it bad to do curls before rows',
      "should i do my heavy squats at the start while i'm fresh or can they go last",
      'arranging my workout: bench then flyes or flyes then bench',
      'does it matter if i do leg extensions before squats',
      'in what sequence should my lifts go within one gym visit',
      'i always leave deadlifts for the end of the workout, mistake?',
      'abs first or at the end of my training',
      'if i want bigger shoulders should lateral raises come before presses',
      'how to line up the exercises in my session for best results',
      'pre exhausting a muscle with a single joint move first, good or not',
      'should the hardest lift of the day be the first thing i do',
      'my plan has triceps work before bench, is that the wrong way round',
      'within a leg day what goes first lunges, squats or curls',
      'does the sequence of movements inside a workout change gains',
    ],
    exUk: [
      'що першим на тренуванні, великі вправи зі штангою чи дрібні на руки',
      'погано робити біцепс перед тягою?',
      'важкі присідання на початку поки свіжий чи можна в кінці',
      'як розставити вправи: жим потім розведення чи навпаки',
      'має значення якщо роблю розгинання ніг перед присіданнями',
      'в якій послідовності мають йти вправи за одне тренування',
      'завжди лишаю станову на кінець тренування, це помилка?',
      'качати прес до основних вправ чи вже наприкінці',
      'якщо хочу більші плечі махи мають бути перед жимом?',
      'як вишикувати вправи в тренуванні для найкращого результату',
      "попередньо втомити м'яз ізолюючою вправою спочатку, добре чи ні",
      'найважча вправа дня має бути першою?',
      'в плані трицепс перед жимом лежачи, це не навпаки?',
      'в день ніг що першим випади, присідання чи згинання',
      'послідовність рухів всередині тренування впливає на результат?',
    ],
  },
  k_imbalance: {
    ex: [
      'when i look in the mirror one shoulder looks smaller than the other',
      'bar goes up crooked on my press, one arm always lags',
      'my left quad is visibly thinner than my right after a knee injury',
      'one side of my back is more developed, is that fixable',
      'asymmetric chest, one side sticks out more',
      'can i just do extra sets on the weaker side to catch up',
      "i'm right handed and everything on that side is stronger, normal?",
      'the bar shifts toward one side when i squat, why',
      'my left bicep has a lower peak and is smaller, what to do',
      'should i always start with my weak side on single arm stuff',
      'lopsided body after years of playing tennis, how to balance it',
      'is a small difference between left and right sides something to worry about',
      'weak side can only do 8 reps while strong side does 12, what now',
    ],
    exUk: [
      'в дзеркалі одне плече виглядає меншим за інше',
      'штанга йде криво на жимі, одна рука завжди відстає',
      'ліве стегно помітно тонше за праве після травми коліна',
      'одна сторона спини розвинена більше, це можна виправити?',
      'асиметричні груди, одна сторона випирає більше',
      'можна просто робити додаткові підходи на слабку сторону щоб наздогнати',
      'я правша і все з того боку сильніше, це нормально?',
      'одна сідниця більша за іншу хаха як виправити',
      'штанга зміщується в один бік коли присідаю, чому',
      'лівий біцепс нижчий і менший, що робити',
      'завжди починати зі слабкої сторони на вправах однією рукою?',
      'тіло кривобоке після років тенісу, як збалансувати',
      'невелика різниця між лівою і правою стороною це привід хвилюватись?',
      'слабка сторона робить 8 повторів а сильна 12, що тепер',
    ],
  },
  k_bail_squat: {
    ex: [
      "how to dump the bar behind you if you can't stand up",
      'scared of getting pinned under the bar in the squat rack, how to set it up',
      'where should the metal catch arms be when i squat by myself',
      'if i fail a squat do i drop it back or just sit down onto the rails',
      'how low should i put the side supports so they catch the bar but dont block my depth',
      'straps or pins in the rack for squatting solo, which is safer',
      'practice failing a squat on purpose, is that a thing',
      "i got stuck under a squat last week and panicked, what's the correct way out",
      'no spotter at home, how do i squat heavy without dying',
      'my rack has no safeties, is it dumb to squat heavy in it',
      'how do you ditch a squat safely when your legs give out',
      'whats the technique to escape from under a failed squat rep',
      'safeties set at what height for someone who squats below parallel',
      'can i squat in a rack without spotter arms if i go lighter',
    ],
    exUk: [
      'що робити якщо застряг внизу присіду зі штангою на спині а поруч нікого',
      'як скинути штангу назад якщо не можеш встати',
      'боюсь застрягти під штангою в стійці для присідань, як налаштувати',
      'на якій висоті мають бути металеві упори коли присідаю сам',
      'якщо не встаю з присіду кидати назад чи просто сідати на упори',
      'на яку висоту ставити бокові упори щоб ловили штангу але не заважали глибині',
      'ремені чи упори в рамі для присіду наодинці, що безпечніше',
      'тренувати невдалий присід навмисно, таке роблять?',
      'минулого тижня застряг під штангою і запанікував, як правильно вибратись',
      'страхувальника вдома нема, як присідати важко і не вбитись',
      'в моїй стійці нема страховки, тупо присідати там важко?',
      'як безпечно покинути присід коли ноги відмовили',
      'яка техніка щоб вибратись з-під невдалого повтору присіду',
      'на якій висоті страховки для того хто присідає нижче паралелі',
      'можна присідати в стійці без страхувальних упорів якщо брати легше',
    ],
  },
  k_personal_trainer: {
    ex: [
      'is a coach worth it after 2 years alone in the gym',
      'thinking of paying someone to train me in person, is it money well spent',
      'how do i know if the guy offering sessions at my gym is any good',
      'would hiring somebody to watch my lifts help me more than youtube',
      'my gym sells 10 sessions packages with a trainer, should i buy',
      'online guy on instagram sells programs and check-ins, worth it vs a real person',
      'what should i look for when picking someone to coach me',
      'been lifting on my own forever, would paying a pro speed things up',
      'how much should one-on-one gym coaching cost and is it worth it',
      'is paying for a trainer only for beginners or do experienced people use them too',
      'red flags in a gym coach before i pay him',
      'should i hire someone for a few sessions just to learn the basics',
      'do i need a certified trainer or can a strong guy at the gym teach me',
      'my trainer just counts reps and talks, is that normal for what i pay',
      'coach over zoom vs someone standing next to me, which is better for me',
    ],
    exUk: [
      'чи варто наймати тренера після 2 років самостійно в залі',
      'думаю платити комусь щоб тренував мене особисто, це варті гроші?',
      'як зрозуміти чи хороший той хлопець що пропонує заняття в моєму залі',
      'найняти когось хто дивитиметься мою техніку допоможе більше ніж ютуб?',
      'мій зал продає пакет з 10 занять з інструктором, брати?',
      'хлопець в інстаграмі продає програми і перевірки, варто чи краще живу людину',
      'на що дивитись коли вибираю кого найняти тренувати мене',
      'давно качаюсь сам, якщо платити профі це прискорить прогрес?',
      'скільки має коштувати індивідуальне ведення в залі і чи воно того варте',
      'платний тренер тільки для новачків чи досвідчені теж беруть',
      'тривожні ознаки у фітнес-тренера перш ніж йому платити',
      'може найняти когось на кілька занять просто щоб навчитись основ',
      'мені треба сертифікований тренер чи сильний хлопець у залі навчить',
      'мій тренер тільки рахує повтори і балакає, це норм за такі гроші?',
      'тренер по зуму чи людина поруч, що краще для мене',
    ],
  },
};
