/** Extra paraphrases for the partE topics (more diverse wording). */
export const KB_E2: Record<string, { ex: string[]; exUk: string[] }> = {
  // ---------------------------------------------------------------- technique
  technique_lift: {
    ex: [
      'rdl form',
      'hip thrust setup',
      'walk me through a proper conventional deadlift',
      'my lower back rounds when i pull from the floor, how do i fix my deadlift',
      'where should the bar touch my chest on bench',
      'elbows flare on my bench press, is that wrong',
      'how wide should my grip be for pull-ups',
      "i swing a lot on barbell curls, what's the right way",
      'lat pulldown: behind the neck or to the chest',
      'how deep should i go on the leg press',
      'foot placement for the leg press',
      'should my knees go past my toes in lunges',
      'can someone explain the sumo deadlift setup',
      'overhead press keeps pushing my hips forward, how do i stay tight',
      'my bent-over row turns into a shrug, what am i doing wrong',
      'how far do i lean forward on dips',
      'cable row technique',
      'face pull form please',
      'how to not hurt my shoulders on the bench press',
      "i never feel my glutes on hip thrusts, what's off with my form",
      'how do you brace for a heavy deadlift',
      'is it okay to arch on the bench press',
      'chin-up vs pull-up form differences',
      'bulgarian split squat: how far should my front foot be',
      'the right way to do a dumbbell shoulder press',
    ],
    exUk: [
      'як правильно ставити ноги на жимі ногами',
      'в яку точку грудей опускати штангу на жимі лежачи',
      'лікті розходяться на жимі, це норм',
      'на становій круглиться спина, як виправити',
      'як правильно тримати хват на підтягуваннях',
      'розкажи про сумо станову, як стати',
      'техніка тяги гантелі в нахилі',
      'на ягодичному мості не відчуваю сідниць, що не так з технікою',
      'наскільки глибоко опускатися на брусах',
      'як не травмувати плечі на жимі лежачи',
      'тяга блоку до поясу, як робити',
      'на жимі стоячи прогинаюсь у попереку, це погано',
      'як правильно дихати на становій тязі',
      'коліна виходять за носки на випадах, це нормально',
      'техніка французького жиму',
      'як робити тягу штанги в нахилі, щоб працювала спина, а не біцепс',
      'підйом на біцепс з читінгом чи без',
      'румунка — як далеко відводити таз',
      'підтягування широким хватом, як правильно',
      'жим гантелей сидячи, техніка',
      'як ставити ноги в болгарських випадах',
      'прогин у спині на жимі лежачи можна',
      'шо не так з моєю становою, болить поперек після кожного сету',
      'как правильно делать жим лежа',
      'как ставить ноги в жиме ногами',
    ],
  },
  pain_types: {
    ex: [
      'is it normal soreness or did i hurt something',
      'throbbing pain vs muscle burn',
      'shooting pain in my shoulder on the press',
      'how do you tell a pulled muscle from normal doms',
      'pain in the joint, not the muscle, what does that mean',
      'a pinching feeling in my hip when i squat deep',
      'the pain is sharp and only on one side',
      'burning in the muscle is fine but what about the joint',
      'what kind of pain means stop the set',
      'my knee clicks and hurts, is that a bad sign',
      'is a dull ache after a workout just fatigue',
      'which pains are okay to train with',
      'sudden sharp twinge in my back mid rep',
      'the ache is deep in the joint and lasts for days',
      'pain that gets worse during the set, bad or fine',
      'pinch in the front of my shoulder at the bottom of dips',
      'how can i tell if pain is structural',
      'red flags for pain while lifting',
      'burning vs stabbing, which is worse',
      'i felt a pop and now it hurts',
      'soreness 2 days later vs pain right away',
      'is sore muscles pain or injury pain',
      'kind of a grinding pain in my knee',
      'tender to the touch, is that an injury',
      'what does a torn muscle feel like',
    ],
    exUk: [
      'це звичайна крепатура чи я щось травмував',
      'пульсуючий біль чи просто печіння',
      'простріл у плечі на жимі',
      'як відрізнити розтягнення від звичайної крепатури',
      'болить суглоб, а не м’яз, що це значить',
      'щемить у тазостегновому при глибокому присіді',
      'біль гострий і тільки з одного боку',
      'при якому болі треба зупинити підхід',
      'коліно хрумтить і болить, це погано',
      'ниє після тренування, це просто втома',
      'з яким болем можна тренуватися, а з яким ні',
      'різко кольнуло в спині посеред повтору',
      'біль глибоко в суглобі і не проходить кілька днів',
      'біль посилюється під час підходу, це погано',
      'щипає спереду плеча внизу на брусах',
      'тривожні ознаки болю в залі',
      'щось клацнуло і тепер болить',
      'крепатура на другий день чи біль одразу',
      'болить при натисканні, це травма',
      'як відчувається розрив м’яза',
      'хрустить і ниє коліно, шо це',
      'печіння в м’язі ок, а біль у суглобі',
      'як зрозуміти, що це травма, а не забиті м’язи',
      'резкая боль или просто забились мышцы',
      'как отличить травму от крепатуры',
    ],
  },
  return_injury: {
    ex: [
      'back after two months off with a sprained ankle',
      'doctor cleared me, how do i restart lifting',
      'first week back after a torn calf',
      'percent of my old weight to use after injury',
      'rebuilding after a herniated disc',
      "my shoulder healed, what's a safe comeback plan",
      'ramping back up post injury',
      'can i jump straight back to my old bench after the pec tear healed',
      'return to deadlifting after a back tweak',
      'after physio, how do i get back to squats',
      "i'm cleared to train again, how cautious should i be",
      'rebuild strength after a knee surgery',
      'what should my first session back after injury look like',
      'the injury is gone, can i go heavy now',
      'phasing back into training after a hamstring pull',
      'how many weeks to get my strength back after injury',
      'restarting the gym after tennis elbow',
      'coming off an injury layoff',
      'how to avoid reinjury when i return',
      'back on my feet after an ankle sprain, when can i do lunges',
      'post-injury return plan',
      'light weights after injury for how long',
      'i healed my wrist, can i press again',
      'recovered from a groin strain, what now',
      'resuming training after a rotator cuff issue',
    ],
    exUk: [
      'лікар дозволив, як відновити тренування',
      'перший тиждень у залі після травми литки',
      'який відсоток від старої ваги брати після травми',
      'повернення після грижі',
      'плече зажило, як безпечно повернутися',
      'після фізіотерапії можна до присідів',
      'можна одразу брати свою стару вагу після травми',
      'повертаюсь до станової після того, як прихопило спину',
      'після операції на коліні як набирати силу',
      'що робити на першому тренуванні після травми',
      'травма пройшла, можна вже важко',
      'за скільки тижнів відновиться сила після травми',
      'як не травмуватися знову, коли повертаюсь',
      'потягнув задню поверхню, вже зажило, як заходити',
      'вилікував зап’ястя, можна знову жати',
      'відновлення після розтягнення паху',
      'скільки часу працювати з легкими вагами після травми',
      'довго не тренувався через травму, з чого почати',
      'повертаюся після тенісного ліктя',
      'після проблеми з ротаторною манжетою як поновити тренування',
      'план повернення після травми',
      'вже можу ходити нормально після щиколотки, коли випади',
      'після травми хочу назад у зал, які ваги брати',
      'врач разрешил, как начинать тренироваться после травмы',
      'после травмы колена когда можно приседать',
    ],
  },
  ice_heat: {
    ex: [
      'cold or warm on a tweaked back',
      'should i put a bag of frozen peas on it',
      'hot water bottle for sore traps',
      'ice pack for 20 minutes, right',
      'heat helps a pulled muscle?',
      'rolled my ankle, should i ice it',
      'warm shower or ice on a stiff neck',
      'ice after a fresh injury or heat',
      'is icing bad for muscle growth',
      'heating pad on my lower back before bed',
      'swelling on my knee, cold compress?',
      'does heat speed up healing',
      'how often should i ice a sprain',
      'icing vs heating for tendon pain',
      'should i heat a strained hamstring',
      'cold therapy for a bruised shin',
      'ice on my shoulder after benching',
      'warm up the area with heat before training',
      'icing the knee after running',
      'is it ok to put ice straight on the skin',
      'hot or cold for back spasm',
      'frozen water bottle on the sore foot',
      'heat pack or ice pack for an old injury',
      'swollen wrist, what do i put on it',
      'when do i switch from ice to heat',
    ],
    exUk: [
      'холод чи тепло на потягнуту спину',
      'прикласти заморожені овочі на коліно',
      'грілка на трапецію допоможе',
      'лід 20 хвилин тримати, так',
      'тепло допомагає при розтягненні',
      'підвернув ногу, прикладати лід',
      'теплий душ чи лід на затерплу шию',
      'лід гальмує ріст м’язів',
      'грілку на поперек на ніч можна',
      'набряк на коліні, холодний компрес',
      'тепло пришвидшує загоєння',
      'як часто прикладати лід на розтягнення',
      'лід чи тепло на сухожилля',
      'гріти задню поверхню стегна після розтягнення',
      'холод на синець на гомілці',
      'лід на плече після жиму',
      'лід на коліно після бігу',
      'можна лід прямо на шкіру',
      'спазм у спині, гріти чи холодити',
      'стара травма — тепло чи холод',
      'набрякло зап’ястя, що прикласти',
      'коли переходити з льоду на тепло',
      'гріти чи ні, якщо припухло',
      'грелку на поясницу можно',
      'лед приложить к лодыжке',
    ],
  },
  painkillers: {
    ex: [
      'advil before leg day',
      'is it bad to take nurofen after every workout',
      'aspirin before training',
      'taking naproxen for joint pain and still lifting',
      'i need pills to get through my sessions, is that okay',
      'does ibuprofen block gains',
      'tylenol for sore muscles after the gym',
      'masking pain with medication to train',
      'should i medicate the pain or rest',
      'anti-inflammatory gel on my elbow before lifting',
      'voltaren and training',
      'can i combine painkillers with pre workout',
      'i take ibuprofen daily for my knee, can i keep squatting',
      'is diclofenac ok when training',
      "painkiller so my back doesn't hurt on deadlift day",
      'taking two advil before a heavy session',
      'do nsaids hurt recovery',
      'medication to numb joint pain for lifting',
      'pills for doms',
      'can i lift after a painkiller shot',
      'should i train while on anti-inflammatory tablets',
      'is it smart to take a painkiller and push through',
      'does paracetamol affect muscle building',
      'ibuprofen and creatine together',
      'painkiller before cardio',
    ],
    exUk: [
      'нурофен перед днем ніг',
      'погано пити нурофен після кожного тренування',
      'аспірин перед залом',
      'п’ю таблетки, щоб дотренуватися, це нормально',
      'ібупрофен гальмує ріст м’язів',
      'таблетка від крепатури',
      'глушити біль таблетками і тренуватися',
      'мазь вольтарен на лікоть і в зал',
      'диклофенак і тренування',
      'знеболювальне і передтрен разом можна',
      'щодня п’ю ібупрофен від коліна, можна далі присідати',
      'випити знеболювальне, щоб спина не боліла на становій',
      'дві таблетки нурофену перед важким тренуванням',
      'протизапальні заважають відновленню',
      'після укола знеболювального можна тренуватися',
      'качатися на протизапальних таблетках',
      'парацетамол впливає на м’язи',
      'ібупрофен і креатин разом',
      'знеболююче перед кардіо',
      'пігулки від болю і зал, сумісно',
      'німесил перед тренуванням можна',
      'закинувся знеболюючим, піду в зал',
      'краще пити таблетки чи відпочивати',
      'нурофен после тренировки пить можно',
      'обезболивающее перед становой',
    ],
  },
  tendon: {
    ex: [
      'achilles tendinitis from running',
      'my patellar tendon is killing me',
      'lateral elbow pain from rows, tendon thing',
      'tendons hurt more than muscles',
      'inflamed tendon in the wrist',
      'how do i strengthen my tendons',
      'biceps tendon pain at the shoulder',
      'tendons are sore after a volume block',
      'tendinopathy',
      'tennis elbow',
      "jumper's knee",
      'slow eccentrics for tendon rehab',
      'my achilles is stiff every morning',
      'are tendons slower to adapt than muscles',
      'tendon pain gets better once warmed up, is that normal',
      'should i fully stop training with a tendon issue',
      'sore spot just below my kneecap',
      'tendon strain from heavy pull-ups',
      "golfer's elbow flare after chin-ups",
      'how to load an irritated tendon',
      'hamstring tendon pain near the sit bone',
      'tendons feel inflamed after deadlifts',
      'tricep tendon hurting on skull crushers',
      'collagen for tendons worth it',
      "tendinitis that won't go away",
    ],
    exUk: [
      'ахіллів тендиніт від бігу',
      'дуже болить колінне сухожилля',
      'сухожилля болять більше, ніж м’язи',
      'запалення сухожилля в зап’ясті',
      'як зміцнити сухожилля',
      'болить сухожилля біцепса біля плеча',
      'тендинопатія',
      'тенісний лікоть',
      'коліно стрибуна',
      'повільний негатив для відновлення сухожилля',
      'зранку ахілл тугий',
      'сухожилля адаптуються повільніше за м’язи',
      'сухожилля болить, але після розминки проходить',
      'треба повністю кинути тренування, якщо болить сухожилля',
      'болить трохи нижче колінної чашечки',
      'потягнув сухожилля на важких підтягуваннях',
      'лікоть гольфіста після підтягувань',
      'як навантажувати подразнене сухожилля',
      'сухожилля трицепса болить на французькому жимі',
      'колаген для сухожиль пити',
      'тендиніт не проходить місяцями',
      'сухожилля під коліном ниє після присідів',
      'зв’язки болять після становой',
      'воспаление сухожилия на локте',
      'ахилл болит после бега',
    ],
  },
  cramps: {
    ex: [
      'charley horse in my calf',
      'calf locked up mid set',
      'my hamstring seized up during curls',
      'cramping',
      'keep getting cramps on leg day',
      'leg cramps wake me up at night',
      'toes curl and cramp when i squat',
      'does magnesium stop cramps',
      'my quad cramped on the leg extension',
      'cramps in my hands when gripping',
      "why do i cramp when i'm dehydrated",
      'my back muscle spasms and locks up',
      'cramp in my side while doing ab work',
      'how to release a cramp fast',
      'pickle juice for cramps',
      'cramps after a long run',
      'glute cramp on hip thrusts',
      'muscle twitching and cramping after training',
      'stretch or push through a cramp',
      'my calves cramp every time i do calf raises',
      'cramps in my feet during deadlifts',
      'is cramping a sign of low potassium',
      'sudden cramp stopped my set',
      'biceps cramp on curls',
      'neck cramped up on shrugs',
    ],
    exUk: [
      'литку звело посеред підходу',
      'задню поверхню стегна звело на згинаннях',
      'судоми',
      'постійно зводить на дні ніг',
      'судоми ніг будять вночі',
      'пальці на ногах зводить при присіданні',
      'магній допомагає від судом',
      'квадрицепс звело на розгинаннях',
      'руки зводить, коли тримаю гриф',
      'чому зводить, коли мало п’ю',
      'спину скувало спазмом',
      'як швидко зняти судому',
      'судоми після довгого бігу',
      'сідницю звело на ягодичному мості',
      'м’язи сіпаються і зводить після тренування',
      'розтягувати чи терпіти, коли зводить',
      'литки зводить кожного разу на підйомах на носки',
      'стопи зводить на становій',
      'судоми — це нестача калію',
      'біцепс звело на підйомі',
      'шию звело на шрагах',
      'ногу скрутило судомою, не можу доробити',
      'судоми в пальцях рук',
      'сводит икры ночью',
      'судороги после тренировки что делать',
    ],
  },
  numbness: {
    ex: [
      'my hands fall asleep on the bike',
      'fingers tingle when i hold dumbbells for long',
      'tingling down my arm into the ring finger',
      'numb patch on my thigh',
      'my toes go numb in lifting shoes',
      'pins and needles in both hands at night after training',
      'my arm goes dead on the bench',
      'loss of feeling in my fingertips after rows',
      'tingling in my feet during squats',
      'legs feel numb after hip thrusts',
      'numb hands from gripping the bar too hard',
      'electric tingling down my leg',
      'why does my arm fall asleep on shoulder press',
      'numbness in my buttock after deadlifts',
      'tingles in my forearm when i do curls',
      'my hand goes numb when i do farmer carries',
      'numb fingers after a long set of pull-ups',
      'tingling sensation in my shin',
      'fingers feel fuzzy after benching',
      "my leg keeps going numb since last week's squats",
      'pinky and ring finger tingle',
      'i lose feeling in my hand on lat pulldowns',
      'numbness',
      'tingling',
      'pins and needles',
    ],
    exUk: [
      'руки затерпають на велотренажері',
      'поколює пальці, коли довго тримаю гантелі',
      'поколювання по руці до безіменного пальця',
      'оніміла ділянка на стегні',
      'пальці ніг німіють у штангетках',
      'ночами поколює обидві руки після тренування',
      'втрачаю чутливість у кінчиках пальців',
      'ступні поколює під час присідань',
      'ноги німіють після ягодичного мосту',
      'руки німіють від того, що сильно стискаю гриф',
      'наче струмом б’є по нозі',
      'затерпає рука на жимі стоячи',
      'німіє сідниця після станової',
      'мурашки в передпліччі на біцепсі',
      'німіє рука, коли ношу гантелі',
      'пальці як ватні після жиму',
      'нога німіє вже тиждень після присідів',
      'мізинець і безіменний поколюють',
      'німіє долоня на тязі верхнього блоку',
      'оніміння',
      'затерпли руки',
      'поколювання в гомілці',
      'не відчуваю пальців після підтягувань',
      'немеет рука после жима',
      'покалывание в пальцах ног',
    ],
  },
  // ---------------------------------------------------------------- nutrition
  calories: {
    ex: [
      'maintenance kcal',
      'how much food do i actually need a day',
      "what's my calorie number",
      "i'm 80 kg and train 4 times a week, how many calories",
      'figure out my daily energy needs',
      'total daily energy expenditure for me',
      'how much energy do i burn per day',
      'is 2500 calories a day right for me',
      'do i eat too many calories',
      'calorie budget per day',
      'how many calories do lifters need',
      'what should my daily intake be',
      "i don't know how much i should be eating",
      'is 1800 kcal enough for someone who lifts',
      'are calorie calculators accurate',
      'how much should i eat on training days vs rest days in calories',
      'how many calories to stay the same weight',
      'calories burned in a gym session',
      'is calorie counting necessary',
      'tracking calories worth it',
      'my calorie needs',
      'energy intake per day',
      'how to find my maintenance',
      'am i undereating',
      'set my daily calories',
    ],
    exUk: [
      'калорії на підтримку',
      'скільки мені реально треба їжі на день',
      'моя норма калорій',
      'я 80 кг, тренуюсь 4 рази на тиждень, скільки калорій',
      'скільки енергії я витрачаю на день',
      '2500 калорій на день мені нормально',
      'я не переїдаю по калоріях',
      'бюджет калорій на день',
      'скільки калорій треба тим, хто качається',
      'не знаю, скільки мені їсти',
      '1800 ккал вистачить, якщо тренуюсь',
      'калькулятори калорій точні',
      'скільки калорій спалює тренування',
      'рахувати калорії обов’язково',
      'мої потреби в калоріях',
      'як знайти свою підтримку',
      'я недоїдаю',
      'постав мені денні калорії',
      'скільки кілокалорій в день мені',
      'шо з калоріями, скільки мені треба',
      'калорії в дні тренувань і відпочинку',
      'чи правильно я рахую калорії',
      'моя денна калорійність',
      'калорийность на день какая',
      'сколько ккал нужно при тренировках',
    ],
  },
  cut_deficit: {
    ex: [
      'cutting pace',
      'how steep a deficit',
      '500 below maintenance good enough',
      'how much should i drop my calories to cut',
      'losing 2 kg a week, too much?',
      'i want to shred but keep my muscle, how big a deficit',
      'crash diet or moderate deficit',
      'deficit size for a lean guy',
      'strength dropping on my cut, deficit too big?',
      'ideal weekly weight loss on a cut',
      'how many calories below maintenance to lose half a kilo a week',
      'percent of bodyweight per week to lose',
      'i dropped 5 kg in two weeks, is that bad',
      'starting a cut, what deficit',
      'should i go 20 or 30 percent under maintenance',
      'cutting too hard',
      'shredding calories',
      'minimum calories on a cut',
      'diet break during a long cut',
      'deficit and muscle loss',
      'how slow should a cut be',
      'fat loss rate per week',
      'big deficit makes me weak',
      'deficit',
      'how aggressive should my cut be',
    ],
    exUk: [
      'темп сушки',
      'наскільки урізати калорії на сушці',
      'мінус 500 від підтримки нормально',
      'скидаю 2 кг на тиждень, не забагато',
      'хочу посушитися і не злити м’язи, який дефіцит',
      'жорстка дієта чи помірний дефіцит',
      'на сушці падає сила, дефіцит завеликий',
      'ідеальний темп схуднення на тиждень',
      'скільки відсотків ваги скидати за тиждень',
      'злив 5 кг за два тижні, це погано',
      'починаю сушку, який дефіцит ставити',
      'мінус 20 чи 30 відсотків від підтримки',
      'занадто жорстко сушусь',
      'мінімум калорій на сушці',
      'перерва в дієті на довгій сушці',
      'дефіцит і втрата м’язів',
      'наскільки повільно має йти сушка',
      'великий дефіцит, і я слабкий',
      'дефіцит',
      'як агресивно сушитися',
      'скільки різати калорій, щоб мінус пів кіло на тиждень',
      'худну по кілограму на тиждень, норм темп',
      'дефіцитчик який ставити',
      'сколько скидывать в неделю на сушке',
      'дефицит 500 ккал нормально',
    ],
  },
  bulk_surplus: {
    ex: [
      'bulking pace per week',
      'how much over maintenance',
      'gaining 1 kg a week on a bulk, too fast?',
      'slow bulk vs fast bulk',
      "i'm getting fat on my bulk, surplus too big?",
      'how many extra calories to put on muscle',
      'surplus size for an intermediate',
      'dirty bulking',
      'lean bulk',
      'mass gain phase, how many calories above maintenance',
      "i'm a hardgainer, how much surplus",
      'gained 4 kg in a month, is that too much',
      'should i do a 300 or 500 surplus',
      'bulk with a small surplus or big one',
      'eating in a surplus but not gaining',
      'how long should a bulk last',
      'ideal monthly weight gain on a bulk',
      'is a big surplus better for strength',
      'surplus',
      'minimising fat gain in a surplus',
      'i want to bulk, where do i set calories',
      'starting a bulk, how many calories over',
      'seefood diet bulk, good idea?',
      'calorie surplus on rest days',
      'how fast should the scale go up when bulking',
    ],
    exUk: [
      'темп масонабору на тиждень',
      'скільки понад підтримку їсти',
      'набираю кіло на тиждень, це швидко',
      'повільний набір чи швидкий',
      'на масі запливаю жиром, профіцит завеликий',
      'скільки зайвих калорій для набору м’язів',
      'брудний масонабір',
      'чистий масонабір',
      'я хардгейнер, який профіцит',
      'набрав 4 кг за місяць, забагато',
      'профіцит 300 чи 500',
      'їм у профіциті, а вага стоїть',
      'скільки має тривати масонабір',
      'ідеальний набір ваги за місяць',
      'великий профіцит краще для сили',
      'профіцит',
      'як менше запливати на масі',
      'хочу на масу, скільки ставити калорій',
      'починаю масу, на скільки більше підтримки',
      'жерти все підряд на масі, норм ідея',
      'профіцит у дні відпочинку',
      'як швидко має рости вага на масі',
      'маса без жиру, який плюс по калоріях',
      'на сколько больше поддержки есть на массе',
      'как быстро набирать вес на массе',
    ],
  },
  carbs: {
    ex: [
      'potatoes or rice for gains',
      'carbohydrates',
      'sweet potato before the gym',
      'no carbs after 6?',
      'carb cycling worth it',
      'are bread and pasta okay on a cut',
      'how many carbs on training days',
      'low carb makes my workouts terrible',
      'carbs per kg of bodyweight',
      'do i need carbs to build muscle',
      'white rice vs brown rice',
      'carb loading before a big lift day',
      'i cut out carbs and feel flat',
      'are bagels a good carb',
      'fast carbs vs slow carbs',
      'keto and strength',
      'should my plate be mostly carbs',
      'is it okay to eat carbs at dinner',
      'carbs make me bloated',
      'atkins style diet for lifting',
      'oatmeal every morning ok',
      'carbs are the enemy?',
      'do i really need carbohydrates if i lift',
      'how low can i go on carbs on a cut',
      'buckwheat or rice',
    ],
    exUk: [
      'картопля чи рис для м’язів',
      'вуглеводи',
      'батат перед залом',
      'без вуглеводів після шостої',
      'вуглеводне чергування має сенс',
      'хліб і макарони на сушці можна',
      'скільки вуглеводів у дні тренувань',
      'на низьковуглеводці тренування жахливі',
      'вуглеводи на кг ваги',
      'чи треба вуглеводи для росту м’язів',
      'білий рис чи бурий',
      'прибрав вуглеводи і почуваюся пласким',
      'швидкі вуглеводи чи повільні',
      'кето і сила',
      'вуглеводи на вечерю можна',
      'від вуглеводів здуття',
      'вівсянка щоранку норм',
      'вуглеводи це зло',
      'гречка чи рис',
      'наскільки мало вуглеводів можна на сушці',
      'вуглі скільки їсти',
      'макарони перед тренуванням норм',
      'каші на масі скільки',
      'гречка или рис для массы',
      'углеводы вредны для сушки',
    ],
  },
  fats: {
    ex: [
      'fat intake',
      'how much fat per kg',
      'avocado and olive oil every day ok',
      'is butter bad',
      'peanut butter too much fat',
      'saturated fat and lifting',
      'i eat almost no fat, is that bad for hormones',
      'fats and testosterone',
      'omega 3 dosage',
      'krill oil or fish oil',
      'how many eggs is too much fat',
      'cooking with coconut oil',
      'healthy fats',
      'minimum fat intake on a diet',
      'do fats make you fat',
      'trans fats',
      'nuts are calorie dense, how many',
      'is a high fat diet good for strength',
      'should i take cod liver oil',
      'salmon for omega-3',
      'fat grams on a bulk',
      'cheese and fat intake',
      'cut fats or carbs to lose weight',
      'low fat vs low carb',
      'what percentage of calories from fat',
    ],
    exUk: [
      'скільки жирів на кг',
      'авокадо й оливкова олія щодня норм',
      'вершкове масло шкідливе',
      'арахісова паста, багато жиру',
      'насичені жири і тренування',
      'майже не їм жирів, це погано для гормонів',
      'жири і тестостерон',
      'яке дозування омеги',
      'скільки яєць, щоб не перебрати жирів',
      'корисні жири',
      'мінімум жирів на дієті',
      'від жирів товстіють',
      'транс-жири',
      'горіхи калорійні, скільки можна',
      'дієта з високим вмістом жирів для сили',
      'лосось заради омеги',
      'жири на масі скільки грам',
      'сир і жири',
      'урізати жири чи вуглеводи для схуднення',
      'скільки відсотків калорій із жирів',
      'сало можна на сушці',
      'рибка ради омега-3',
      'олія в салат, скільки ложок',
      'сколько грамм жира на кг',
      'сало на массе норм',
    ],
  },
  pre_meal: {
    ex: [
      'pre-workout food',
      'fuel before lifting',
      'empty stomach or eat first before the gym',
      'toast and peanut butter before a session',
      "i train at 7am, what's breakfast",
      'what to eat 2 hours before the gym',
      'oats before training good?',
      'i get nauseous if i eat before training',
      'quick bite before the gym',
      'pre-lift meal',
      'is rice and chicken a good pre workout meal',
      'should i have a big meal before squats',
      'what to eat before an evening session',
      'fruit right before lifting',
      'coffee and a banana before the gym enough',
      'what do you eat before you train',
      'heavy stomach during training, ate too close',
      'carbs before training, how many',
      'eating before a workout',
      'food 30 minutes before training',
      'pre gym snack ideas',
      'rice cakes before lifting',
      'should i eat before morning cardio',
      'lunch before a 2pm workout',
      "what's the ideal meal ahead of a heavy session",
    ],
    exUk: [
      'їжа перед залом',
      'натщесерце чи поїсти перед тренуванням',
      'тост з арахісовою пастою перед тренуванням',
      'тренуюся о 7 ранку, що на сніданок',
      'що поїсти за дві години до залу',
      'вівсянка перед тренуванням норм',
      'нудить, якщо поїм перед тренуванням',
      'швидкий перекус перед залом',
      'рис з куркою перед тренуванням підійде',
      'багато їсти перед присідами',
      'що з’їсти перед вечірнім тренуванням',
      'фрукт прямо перед тренуванням',
      'кава з бананом перед залом вистачить',
      'важко в животі на тренуванні, поїв запізно',
      'скільки вуглеводів перед тренуванням',
      'їжа за 30 хвилин до тренування',
      'ідеї перекусу перед залом',
      'хлібці перед тренуванням',
      'обід перед тренуванням о другій',
      'чим заправитися перед важким тренуванням',
      'поїсти перед ранковим кардіо',
      'шо хавати перед качалкою',
      'їсти за годину до залу чи за дві',
      'что покушать перед залом',
      'натощак или поесть перед тренировкой',
    ],
  },
  post_meal: {
    ex: [
      'post-workout food',
      'what to eat after squats',
      'refuel after lifting',
      'chicken and rice after the gym',
      'chocolate milk after training',
      'how long can i wait to eat after a workout',
      "i'm never hungry after training, should i still eat",
      'dinner right after an evening session',
      'eating after a morning workout',
      'best recovery food after the gym',
      'post-gym snack ideas',
      'what to eat after cardio',
      'do i need carbs and protein after training',
      'i train at night, eat afterwards or go to bed',
      'is the post workout window a myth',
      'meal after a heavy deadlift day',
      'sushi after lifting good?',
      'after-gym meal',
      'fast food after training bad for recovery',
      'should i eat right after i finish training',
      'what to eat when i get home from the gym',
      'eggs after workout',
      'how big should my post workout meal be',
      'banana after training to recover',
      'post workout carbs',
    ],
    exUk: [
      'їжа після залу',
      'що поїсти після присідань',
      'курка з рисом після тренування',
      'шоколадне молоко після залу',
      'скільки можна чекати з їжею після тренування',
      'після тренування не хочу їсти, треба',
      'вечеря одразу після вечірнього тренування',
      'їжа після ранкового тренування',
      'найкраща їжа для відновлення після залу',
      'перекус після тренування',
      'що їсти після кардіо',
      'потрібні вуглеводи і білок після тренування',
      'тренуюся пізно, їсти після чи лягати',
      'вікно після тренування це міф',
      'що з’їсти після важкої станової',
      'яйця після тренування',
      'наскільки великий має бути прийом їжі після залу',
      'банан після залу для відновлення',
      'шо похавати після качалки',
      'прийшов із залу, що їсти',
      'одразу після тренування поїсти треба',
      'після залу голодний як вовк, що з’їсти',
      'бургер після тренування погано для відновлення',
      'что покушать после зала',
      'через сколько есть после тренировки',
    ],
  },
  meals_count: {
    ex: [
      'meal frequency',
      '3 meals or 5',
      'how many feedings a day',
      'is intermittent fasting ok with lifting',
      '16:8 and building muscle',
      'i only eat twice a day',
      'should i eat every few hours',
      'grazing all day vs set meals',
      'eating once a day',
      'do more meals speed up metabolism',
      'how to spread my protein across meals',
      'breakfast lunch dinner enough',
      'i skip breakfast, is that bad for gains',
      'how many meals on a cut',
      'four meals a day plan',
      'is omad bad for muscle',
      'how many times should i eat daily',
      'should i snack between meals',
      'big meals or small frequent ones',
      'eating 7 times a day',
      'i eat once at night, enough',
      'does it matter how often i eat',
      'splitting my calories into meals',
      'how many plates per day',
      'meals per day for a lifter',
    ],
    exUk: [
      'частота прийомів їжі',
      '3 прийоми чи 5',
      'інтервальне голодування і тренування',
      '16:8 і набір м’язів',
      'я їм лише двічі на день',
      'їсти кожні кілька годин треба',
      'перекушувати весь день чи чіткі прийоми',
      'їсти раз на день',
      'більше прийомів їжі розганяють метаболізм',
      'сніданок, обід і вечеря — вистачить',
      'пропускаю сніданок, це погано для м’язів',
      'скільки разів їсти на сушці',
      'чотири прийоми їжі на день',
      'омад шкідливий для м’язів',
      'перекушувати між прийомами',
      'великі прийоми чи часто потроху',
      'їсти 7 разів на день',
      'їм раз увечері, цього достатньо',
      'чи важливо, як часто я їм',
      'розбити калорії на прийоми',
      'скільки прийомів їжі на масі',
      'дробно їсти чи тричі на день',
      'скільки разів поїсти за день',
      'интервальное голодание и тренировки',
      'дробное питание нужно или нет',
    ],
  },
  vegan: {
    ex: [
      'vegan gains',
      'plant based and lifting',
      "i'm vegetarian, how do i hit my protein",
      'meatless diet for strength',
      'seitan and tempeh for muscle',
      'vegan protein powder',
      'can i bulk without animal products',
      'soy protein for lifters',
      'i eat eggs and dairy but no meat',
      'vegan athletes who got strong',
      'rice and pea protein combo',
      'iron and b12 on a vegan diet',
      'is being vegan bad for muscle growth',
      'lentils beans chickpeas enough protein',
      'vegan cut plan',
      'pescatarian lifting',
      'do vegans need to supplement',
      'going plant based',
      'no meat no dairy, how do i build muscle',
      'complete protein from plants',
      'vegan creatine sources',
      "i don't eat animal products",
      'vegetarian bulk',
      'vegan',
      'vegetarian',
    ],
    exUk: [
      'веган і м’язи',
      'рослинне харчування і зал',
      'я вегетаріанець, як добрати білок',
      'сила без м’яса',
      'сейтан і темпе для м’язів',
      'веганський протеїн',
      'маса без тваринних продуктів',
      'соєвий протеїн',
      'їм яйця і молочку, але не м’ясо',
      'залізо і B12 на веганстві',
      'веганство погано для росту м’язів',
      'сочевиця, квасоля, нут — вистачить білка',
      'сушка на веганській дієті',
      'веганам треба добавки',
      'переходжу на рослинне',
      'без м’яса і молочки як накачатися',
      'повноцінний білок з рослин',
      'я не їм тваринного',
      'масонабір вегетаріанцю',
      'веган',
      'вегетаріанець у залі',
      'пісний раціон і тренування',
      'без мяса как набрать белок',
      'вегетарианец и качалка',
      'растительный белок для мышц',
    ],
  },
  cheat_meal: {
    ex: [
      'cheat meal',
      'cheat day',
      'went off plan at a wedding',
      'i ate a whole pizza last night',
      'had a massive kfc, damage done?',
      'demolished a tub of ice cream on my cut',
      'free meal once a week okay',
      'weekend blowout, what now',
      'i overate at christmas',
      'one bad day of eating',
      'diet slip-up',
      'how do i recover from a binge',
      'should i starve tomorrow after a cheat day',
      'cheat meals on a bulk pointless?',
      'i gained 2 kg after one cheat day',
      'is it ok to have mcdonalds once a week',
      'planned cheat meal vs unplanned',
      'did my cheat day undo the whole week',
      'i fell off my diet',
      'ate like trash all weekend',
      'birthday cake ruined my cut?',
      'all you can eat buffet on a diet',
      'refeed day',
      'treat meal',
      'i messed up my eating today',
    ],
    exUk: [
      'читміл',
      'читдей',
      'на весіллі зірвався з дієти',
      'з’їв цілу піцу вчора',
      'наївся в макдаку, все пропало',
      'з’їв відро морозива на сушці',
      'вільний прийом раз на тиждень норм',
      'на новий рік об’ївся',
      'один поганий день у харчуванні',
      'зрив з дієти',
      'як відійти після зажору',
      'голодувати завтра після читдею',
      'після читдею плюс 2 кг',
      'мак раз на тиждень можна',
      'читдей перекреслив весь тиждень',
      'злетів з дієти',
      'всі вихідні жер що попало',
      'торт на день народження зіпсував сушку',
      'шведський стіл на дієті',
      'рефід',
      'сьогодні нажерся, що робити',
      'зірвався на солодке і фастфуд',
      'обжерся на гостях',
      'обожрался вчера, все пропало',
      'читдей на сушке можно',
    ],
  },
  sugar: {
    ex: [
      'sweets',
      'sugar cravings',
      'a donut on a cut',
      'can i eat ice cream and still get lean',
      'is honey better than sugar',
      'sugar in my coffee bad',
      "i can't stop eating candy",
      'soda and fat loss',
      'is coke bad for gains',
      'added sugar limit per day',
      'dark chocolate on a diet',
      'haribo intra workout',
      'sweeteners vs sugar',
      'cookies after training ok',
      'craving sugar at night',
      'fruit juice too much sugar',
      'cake once a week',
      'is sugar addictive',
      'giving up sweets for gains',
      'diet soda ok',
      'sugary cereal for breakfast',
      'does sugar cause inflammation',
      'i have a massive sweet tooth on my cut',
      'sugar and muscle',
      'how to stop craving sweets',
    ],
    exUk: [
      'солодке',
      'тягне на солодке',
      'пончик на сушці',
      'морозиво і схуднення',
      'мед краще за цукор',
      'цукор у каві шкідливий',
      'не можу перестати їсти цукерки',
      'газовані напої і схуднення',
      'кола шкодить м’язам',
      'скільки доданого цукру на день',
      'чорний шоколад на дієті',
      'сахарозамінники чи цукор',
      'печиво після тренування можна',
      'вночі хочеться солодкого',
      'соки — забагато цукру',
      'тортик раз на тиждень',
      'цукор викликає залежність',
      'відмовитися від солодкого заради м’язів',
      'кола зеро можна',
      'солодкі пластівці на сніданок',
      'на сушці страшенно хочу солодкого',
      'як перестати хотіти солодке',
      'цукор і м’язи',
      'хочу сладкого постоянно',
      'торт на диете можно',
    ],
  },
  late_eating: {
    ex: [
      'eating at 11pm',
      'night snacking',
      'is food after 8 pm bad',
      'late night fridge raids',
      'can i eat dinner at midnight',
      'does eating late mess with fat loss',
      'eating two hours before bed ok',
      'greek yogurt before bed',
      'i work nights, when do i eat',
      'eating in bed before sleep bad',
      'late dinner ruins my sleep',
      'is it okay to go to bed hungry',
      'is eating late bad for digestion',
      'night eating on a bulk',
      'calories at night count more?',
      'eating after 9 on a cut',
      'i get home late, eat or skip',
      'late snack while watching tv',
      'big meal right before bed',
      'i always eat late, is that a problem',
      'sandwich before sleep',
      'no food after sunset rule',
      'late eating',
      'what to eat late at night',
      'eating before bed makes me fat?',
    ],
    exUk: [
      'їсти об 11 вечора',
      'нічні перекуси',
      'їжа після 8 вечора шкідлива',
      'ночами лажу в холодильник',
      'вечеря опівночі',
      'пізня їжа заважає схуднути',
      'їсти за годину до сну нормально',
      'грецький йогурт перед сном',
      'працюю вночі, коли їсти',
      'лягти спати голодним нормально',
      'пізно їсти погано для травлення',
      'їсти вночі на масі',
      'калорії ввечері рахуються більше',
      'їсти після 9 на сушці',
      'приходжу пізно, їсти чи ні',
      'пізній перекус біля телевізора',
      'наїстися перед сном',
      'я завжди їм пізно, це проблема',
      'бутерброд перед сном',
      'після заходу сонця не їсти',
      'пізня їжа',
      'що з’їсти пізно ввечері',
      'на ніч поїсти сирник',
      'ночной жор',
      'после шести не есть это правда',
    ],
  },
  electrolytes: {
    ex: [
      'electrolytes',
      'pinch of salt in water',
      'lmnt worth it',
      'hydration salts',
      'i sweat buckets, what do i add',
      'magnesium glycinate for training',
      'zinc and magnesium',
      'potassium intake for lifters',
      'gatorade during training',
      'too little salt on a cut',
      'sodium and pumps',
      'coconut water after the gym',
      'electrolyte tablets in my bottle',
      'low sodium diet and training',
      'do i need salt if i drink a lot of water',
      'headaches from sweating a lot, electrolytes?',
      'isotonic drinks',
      'should i salt my food more as a lifter',
      'electrolyte mix for long sessions',
      'magnesium before bed',
      'rehydration salts after a hard workout',
      'salt tabs',
      'is powerade good',
      'minerals lost in sweat',
      'adding sodium to my pre workout',
    ],
    exUk: [
      'електроліти',
      'щіпка солі у воду',
      'солі для гідратації',
      'потію як кінь, що додати',
      'магній гліцинат для тренувань',
      'цинк і магній',
      'калій для тих, хто тренується',
      'ізотонік під час тренування',
      'мало солі на сушці',
      'натрій і памп',
      'кокосова вода після залу',
      'таблетки електролітів у пляшку',
      'дієта без солі і тренування',
      'треба сіль, якщо п’ю багато води',
      'болить голова, коли сильно пітнію, електроліти',
      'ізотонічні напої',
      'більше солити їжу, якщо тренуюсь',
      'магній на ніч',
      'регідрон після важкого тренування',
      'мінерали, які виходять з потом',
      'додати натрій у передтрен',
      'мінералка для відновлення',
      'шо з електролітами в спеку',
      'изотоник нужен',
      'соль в воду добавлять',
    ],
  },
  fiber: {
    ex: [
      'fibre',
      'am i getting enough veg',
      'broccoli and spinach for lifters',
      'salad every day necessary',
      'psyllium husk',
      'constipated on a high protein diet',
      'i only eat meat and rice, missing anything',
      'beans for fibre',
      'fruit and veg servings',
      'fiber supplement worth it',
      'whole grains vs white',
      'how many apples a day',
      'greens powder instead of vegetables',
      'digestion issues on a bulk',
      'high fibre and gas',
      'vegetables on a cut to stay full',
      'eat the rainbow for gains',
      'too much fiber bad',
      'berries for lifters',
      'can i skip vegetables',
      'chia seeds for fiber',
      'leafy greens daily',
      'do veggies help recovery',
      'fiber',
      'frozen vegetables okay',
    ],
    exUk: [
      'клітковина',
      'мені вистачає овочів',
      'брокколі і шпинат для тих, хто качається',
      'салат щодня обов’язково',
      'псиліум',
      'закрепи на білковій дієті',
      'їм тільки м’ясо з рисом, чого бракує',
      'квасоля для клітковини',
      'порції фруктів і овочів',
      'добавка з клітковиною варта',
      'цільнозернове чи біле',
      'скільки яблук на день',
      'зелень у порошку замість овочів',
      'здуття від клітковини',
      'овочі на сушці для ситості',
      'забагато клітковини шкідливо',
      'ягоди для спортсменів',
      'можна не їсти овочі',
      'насіння чіа для клітковини',
      'зелень щодня',
      'овочі допомагають відновленню',
      'заморожені овочі норм',
      'без овочів взагалі, це ок',
      'клетчатка для пищеварения',
      'запоры на белке что делать',
    ],
  },
  // ---------------------------------------------------------------- smalltalk
  whats_up: {
    ex: [
      'wazzup',
      "what's cracking",
      'whatcha doing',
      "what's good",
      "what's new, coach",
      'sup dude',
      "yo, what's the word",
      "so what's going on with you",
      "hey what's up with you today",
      'what you been up to',
      'anything interesting happening',
      "what's the latest",
      'whats poppin',
      "how's it going on your end",
      "what's the scoop",
      "howdy, what's up",
      "hey hey what's new",
      "long time no see, what's new",
      'any news',
      "what's up buddy",
      'sup man',
      "what's the vibe",
      "what's up with you lately",
      'anything exciting going on',
      'what have you been doing',
    ],
    exUk: [
      'шо там у тебе',
      'шо новенького',
      'шо робиш зараз',
      'як воно, друже',
      'ну шо, як воно',
      'шо чувати',
      'що чути',
      'які новини',
      'що ти там',
      'як там у тебе справи',
      'шо ти, як ти',
      'давно не бачились, шо нового',
      'є якісь новини',
      'ну шо там, розказуй',
      'шо новенького, тренер',
      'чим займаєшся',
      'як воно нічого, що нового',
      'шо там новенького в тебе',
      'як сам',
      'шо поробляєш',
      'шо по новинах',
      'ну як ти там',
      'что делаешь',
      'как оно',
      'че как',
    ],
  },
  good_night: {
    ex: [
      'nighty night',
      'gn',
      'sleep well',
      'sweet dreams',
      "i'm hitting the sack",
      'hitting the hay',
      'off to dreamland',
      'going to sleep now, night',
      'gonna get some shut-eye',
      "that's it for today, good night",
      'catch you tomorrow, sleeping now',
      'night atlas',
      'gnight',
      "i'm going to bed, talk tomorrow",
      'lights out for me',
      'ok bedtime',
      'time to sleep, see ya',
      'logging off to sleep',
      'night night coach',
      'night all',
      'have a good night',
      "i'm off, gonna sleep",
      'gotta sleep now',
      'going to crash now',
      'turning in for the night',
    ],
    exUk: [
      'на добраніч, атласе',
      'спокійної',
      'добраніч тобі',
      'все, я баїньки',
      'йду на боковую',
      'пора на боковую',
      'лягаю, до завтра',
      'іду спатоньки',
      'гарних снів',
      'на сьогодні все, я спати',
      'відбій',
      'пішла спати',
      'всім добраніч',
      'я вже сплю майже, добраніч',
      'піду посплю, бувай',
      'все, вирубаюсь, до завтра',
      'солодких',
      'доброї ночі тобі',
      'все, пішов лягати',
      'спокійної ночі, тренере',
      'лягаю вже',
      'спатки пора',
      'споки ноки',
      'всем спокойной ночи',
      'я спать, до завтра',
    ],
  },
  tired: {
    ex: [
      'exhausted',
      'knackered',
      "i'm beat",
      'so worn out',
      "i'm pooped",
      'running on fumes today',
      "i'm fried",
      'my batteries are flat',
      'i feel like a zombie',
      'worn out after a long shift',
      'i have no juice left',
      'totally spent',
      'can barely keep my eyes open',
      "so tired i can't think",
      "i'm drained after the week",
      'wrecked today',
      "i'm dragging today",
      'low energy all day',
      'i feel lethargic',
      'sleepy and tired',
      "i'm done for, so tired",
      'zero gas in the tank',
      'tired tired tired',
      "i'm exhausted from work and kids",
      'so fatigued lately',
    ],
    exUk: [
      'втомлений',
      'задовбався, сил нема',
      'я никакий',
      'вимотаний',
      'очі злипаються',
      'я вижатий',
      'сьогодні я як зомбі',
      'втомився після зміни',
      'енергії нуль',
      'вже нема ніяких сил',
      'так втомилася, що нічого не хочу',
      'вимотався за тиждень',
      'сьогодні взагалі нема енергії',
      'якийсь млявий весь день',
      'сонний і втомлений',
      'вимотаний роботою і дітьми',
      'батарейка сіла',
      'ледве тримаюсь на ногах',
      'замучився',
      'я дуже втомлена',
      'втома страшна',
      'з ніг валюсь',
      'я вымотан',
      'сил никаких',
      'я уставший',
    ],
  },
  bored: {
    ex: [
      'boring',
      'meh, bored',
      'this is so dull',
      "i'm bored stiff",
      'so bored right now',
      'workouts feel repetitive',
      'same old same old',
      "i'm sick of the same exercises",
      'gym is monotonous',
      'nothing interesting going on',
      "it's all so boring lately",
      'bored of lifting',
      "tell me something, i'm bored to death",
      'my routine is dull',
      "i'm getting bored of this program",
      'yawn',
      'ugh boring',
      'sitting here bored',
      'bored between sets',
      'killing time, bored',
      "i'm so bored at work",
      'nothing to do today',
      'entertain me',
      'boredom',
      'lifting feels like a chore and boring',
    ],
    exUk: [
      'нудно капець',
      'така нудьга',
      'нудьга смертна',
      'скучно мені',
      'все набридло, нудно',
      'тренування одноманітні',
      'одне й те саме щоразу',
      'набридли однакові вправи',
      'в залі нудно стало',
      'нічого цікавого',
      'останнім часом все нудно',
      'набридло качатися, нудно',
      'мені нудно, розкажи щось',
      'набридла ця програма',
      'позіхаю від нудьги',
      'сиджу нудьгую',
      'нудно між підходами',
      'на роботі нудно',
      'нема чим зайнятися',
      'розваж мене',
      'нудотно якось',
      'скучаю тут',
      'скучища',
      'мне скучно',
      'скучно в зале',
    ],
  },
  challenge: {
    ex: [
      'got a challenge for me',
      'test me',
      'push me with a challenge',
      'give me a goal to crush this week',
      "i'm up for a challenge",
      'what challenge can i try',
      '30 day challenge',
      'a fun challenge for leg day',
      'something tough to aim for',
      'i dare you to challenge me',
      "bet you can't give me a hard one",
      'new challenge please',
      'challenge for the weekend',
      'give me a mission',
      'any challenges today',
      "what's the challenge",
      'hit me with a challenge',
      'i want something to beat',
      'challenge time',
      'pick a challenge for me',
      'can you set me a target to beat',
      'give me a push-up challenge',
      'monthly challenge',
      'a challenge to test my limits',
      'something hard, go',
    ],
    exUk: [
      'є челендж для мене',
      'перевір мене',
      'дай ціль на тиждень, щоб порвати',
      'я готовий до виклику',
      'який челендж можна спробувати',
      'челендж на 30 днів',
      'челендж на день ніг',
      'щось складне, до чого прагнути',
      'новий челендж давай',
      'челендж на вихідні',
      'дай місію',
      'є челендж на сьогодні',
      'який челендж',
      'давай виклик',
      'хочу щось подолати',
      'час челенджу',
      'вибери мені челендж',
      'постав мені планку, яку треба побити',
      'челендж на віджимання',
      'челендж на місяць',
      'випробування для мене',
      'кинь виклик мені',
      'давай щось важке',
      'дай вызов на неделю',
      'челлендж на месяц',
    ],
  },
  fun_fact: {
    ex: [
      'fact',
      'hit me with a fact',
      'random trivia',
      'cool facts about the body',
      "something i probably don't know",
      'interesting fitness trivia',
      'any weird facts',
      'tell me a crazy fact',
      'trivia time',
      'one fun fact please',
      'i love fun facts, go',
      'fact about strength',
      'did you know something cool about lifting',
      'teach me a random thing',
      'facts about the heart',
      'give me some trivia',
      'a mind-blowing fact',
      'tell me a nerdy gym fact',
      'surprising facts about muscles',
      'random science fact',
      'something cool about the human body',
      'fact of the day please',
      'share a random fact',
      'interesting stuff about the gym',
      'educate me with a fact',
    ],
    exUk: [
      'факт',
      'кинь факт',
      'випадковий факт',
      'цікаві факти про тіло',
      'щось, чого я напевно не знаю',
      'цікавинки про фітнес',
      'якийсь дивний факт',
      'розкажи шалений факт',
      'один цікавий факт',
      'факт про силу',
      'навчи мене чомусь випадковому',
      'факт про серце',
      'вражаючий факт',
      'задротський факт про зал',
      'несподіваний факт про м’язи',
      'науковий факт',
      'щось цікаве про людське тіло',
      'поділись фактом',
      'щось цікаве про зал',
      'розкажи цікавинку',
      'знаєш якісь факти',
      'хочу дізнатися щось нове',
      'здивуй мене',
      'интересный факт',
      'расскажи какой-нибудь факт',
    ],
  },
  quote: {
    ex: [
      'quote',
      'motivational words',
      'a quote about discipline',
      'famous quote',
      'say something inspiring',
      'inspiring words please',
      'i need a quote to hype me up',
      'a stoic quote',
      'arnold quote',
      'a line to put on my wall',
      'quote about never giving up',
      'wise words',
      'something deep',
      'a saying about hard work',
      'give me a mantra',
      'inspirational saying',
      'drop a quote',
      'a quote for today',
      'gym motivation quote',
      'a quote about pain and growth',
      'i want some wisdom',
      'tell me something wise',
      'famous words about strength',
      'quote from a great athlete',
      'a quote about patience',
    ],
    exUk: [
      'цитата',
      'мотивуючі слова',
      'цитата про дисципліну',
      'відома цитата',
      'скажи щось надихаюче',
      'потрібна цитата, щоб завестися',
      'цитата стоїків',
      'цитата арнольда',
      'фраза, щоб повісити на стіну',
      'цитата про те, щоб не здаватися',
      'мудрість якусь',
      'щось глибоке',
      'приказка про працю',
      'дай мантру',
      'надихаючий вислів',
      'кинь цитату',
      'цитата на сьогодні',
      'цитата для мотивації в залі',
      'цитата про біль і ріст',
      'хочу мудрості',
      'скажи щось мудре про силу',
      'цитата великого спортсмена',
      'цитата про терпіння',
      'цитату дай',
      'мудрая цитата',
    ],
  },
  laugh: {
    ex: [
      'lolol',
      'ha',
      'hehe',
      'heh',
      'lmfao',
      'xd',
      "haha that's hilarious",
      'lol true',
      'dead',
      "i'm dying",
      'lol nice one',
      'hahah',
      'funny',
      'that cracked me up',
      'lol what',
      'ahaha',
      'haha yeah',
      'lol yes',
      'bahaha',
      'lol classic',
      'haha you got me',
      "that's hilarious",
      'i laughed',
      'lmaooo',
      'kek',
    ],
    exUk: [
      'хех',
      'хі-хі',
      'ахахах',
      'ххх',
      'аххаха',
      'хаха смішно',
      'я плачу',
      'помер',
      'ору',
      'ахах ну ти',
      'хаха точно',
      'ахаха прикольно',
      'смішно вийшло',
      'я аж засміявся',
      'хаха ок',
      'лол ну да',
      'хаха класика',
      'ахахах жесть',
      'реготу',
      'ржака',
      'хд',
      'угораю',
      'ахахах ну ти видав',
      'смешно',
      'ору с тебя',
    ],
  },
  mood_down: {
    ex: [
      "i'm heartbroken",
      'feeling miserable',
      "i'm not okay",
      'i feel lonely',
      'sad day',
      'everything feels pointless',
      "i've been crying",
      "i'm in a funk",
      'my girlfriend dumped me',
      'i feel empty',
      "i'm so down",
      'things are rough at home',
      'i feel like crap emotionally',
      "i'm feeling really sad",
      'bummed out',
      'not a great day, honestly',
      "i'm struggling mentally",
      'i lost my job today',
      'feeling hopeless',
      "i'm gloomy",
      "i'm in a dark mood",
      'nothing makes me happy lately',
      'had a terrible day at work',
      'my mood is in the gutter',
      'feel like everything is falling apart',
    ],
    exUk: [
      'на душі кішки шкребуть',
      'мені зле',
      'я не в порядку',
      'почуваюся самотнім',
      'сумний день',
      'все здається безглуздим',
      'я плакала',
      'мене кинула дівчина',
      'всередині порожнеча',
      'мені дуже сумно',
      'вдома все погано',
      'морально погано',
      'мені важко морально',
      'мене звільнили сьогодні',
      'безнадія якась',
      'похмурий настрій',
      'ніщо не радує',
      'жахливий день на роботі',
      'настрій на дні',
      'таке відчуття, що все розвалюється',
      'тоскно',
      'сумую',
      'якось гірко на душі',
      'мне хреново',
      'все плохо',
    ],
  },
  mood_up: {
    ex: [
      'feeling good',
      'good vibes today',
      "i'm stoked",
      "i'm in such a good mood",
      'today rocks',
      'feeling like a champ',
      "i'm buzzing",
      'happy happy',
      'great mood',
      "i'm thrilled",
      "everything's going my way",
      'i feel unstoppable today',
      "i'm so happy right now",
      'such a good day',
      "i'm on cloud nine",
      'feeling blessed',
      'i feel incredible',
      'today is amazing',
      "i'm in high spirits",
      "life's great",
      "i'm feeling positive",
      "i'm glowing today",
      'things are going well',
      'super good mood',
      "i'm over the moon",
    ],
    exUk: [
      'почуваюся добре',
      'гарний настрій',
      'сьогодні кайф',
      'я щаслива',
      'день огонь',
      'почуваюся чемпіоном',
      'я в захваті',
      'все йде як треба',
      'почуваюся непереможним',
      'такий класний день',
      'я на сьомому небі',
      'почуваюся неймовірно',
      'сьогодні чудово',
      'бадьорий настрій',
      'життя прекрасне',
      'позитивний настрій',
      'все добре складається',
      'настрій супер-пупер',
      'кайфую від дня',
      'радісно на душі',
      'сяю сьогодні',
      'класно себе почуваю',
      'я такий щасливий',
      'настроение супер',
      'день огонь, все круто',
    ],
  },
  lets_go: {
    ex: [
      'letsgoo',
      "let's goooo",
      "alright let's go",
      'time to work',
      "let's crush it",
      "let's get after it",
      'here we go',
      "let's rock",
      'game on',
      "let's hit it",
      "let's move",
      "i'm ready, let's do it",
      "let's get this bread",
      "let's get going",
      'ok go',
      "let's kick it off",
      "let's ride",
      'vamos',
      'allons-y',
      "let's gooo baby",
      'go go go',
      "let's get started then",
      'we ride',
      "let's rumble",
      "it's go time",
    ],
    exUk: [
      'погнааали',
      'поїхали вже',
      'ну давай, погнали',
      'поїхали, я готовий',
      'го го го',
      'працюємо',
      'до справи',
      'вперед і з піснею',
      'стартуємо',
      'го вже',
      'давай почнемо',
      'в бій',
      'розпочинаємо',
      'погнали працювати',
      'ну все, поїхали',
      'поїїїхали',
      'го давай',
      'а тепер погнали',
      'поїхали вже, досить балачок',
      'давай, почали',
      'вперед до перемоги',
      'ну погнали',
      'го работать',
      'ну шо, вперед',
      'поехали уже',
    ],
  },
  nothing: {
    ex: [
      'nvm',
      'never mind that',
      'ah forget about it',
      'nothing, sorry',
      'no reason, just curious',
      "it doesn't matter",
      'just bored, nothing',
      'skip it',
      'scratch that',
      'not important',
      'oh nothing',
      'i was just typing',
      'never mind, all good',
      "whatever, it's fine",
      'nah forget it',
      'disregard',
      "didn't mean anything",
      'nothing in particular',
      'no no, nothing',
      'just random',
      'ignore me',
      'wrong chat, nothing',
      'meant nothing by it',
      'never mind what i said',
      "it's fine, nothing",
    ],
    exUk: [
      'нічо',
      'та забудь',
      'не важливо',
      'нічого, вибач',
      'просто цікаво було',
      'то таке',
      'пропусти',
      'не зважай на це',
      'а, нічого',
      'просто друкував',
      'та все ок, нічого',
      'не бери в голову',
      'нічого особливого',
      'та ні-ні, нічого',
      'просто так написав',
      'ігноруй мене',
      'та це я так',
      'забий',
      'проїхали, забудь',
      'нічого не треба',
      'та то я просто',
      'та нічого, забий',
      'неважно',
      'забей',
      'да ничего',
    ],
  },
  rival_ai: {
    ex: [
      'chatgpt knows more',
      'gpt-4 is better',
      'why should i use you instead of chatgpt',
      'grok is funnier than you',
      'bard says otherwise',
      'can you do what chatgpt does',
      'openai made a better bot',
      'chatgpt wrote me a better program',
      "you're worse than gpt",
      'google assistant answered faster',
      'llama vs atlas',
      'is gpt smarter than you',
      'which is better, you or chatgpt',
      'deepseek told me something else',
      "you're just a chatgpt wrapper",
      'my friend uses chatgpt as his coach',
      'perplexity gave me a better answer',
      "chatgpt would've understood me",
      'are you built on openai',
      'i asked claude and it disagreed',
      'why not use gemini',
      "compared to chatgpt you're meh",
      'gpt plans are better',
      'should i switch to chatgpt',
      'mistral vs you',
    ],
    exUk: [
      'чатжпт знає більше',
      'гпт краще',
      'навіщо ти, якщо є чатгпт',
      'грок смішніший за тебе',
      'а чатжпт так уміє',
      'чатгпт склав кращу програму',
      'ти гірший за гпт',
      'гугл асистент відповів швидше',
      'гпт розумніший за тебе',
      'хто кращий, ти чи чатгпт',
      'дипсік сказав інше',
      'ти просто обгортка над чатгпт',
      'друг тренується з чатгпт',
      'перплексіті відповів краще',
      'чатгпт мене зрозумів би',
      'ти на openai зроблений',
      'спитав у клода, він не погоджується',
      'чому б не юзати gemini',
      'порівняно з чатжпт ти так собі',
      'може перейти на чатгпт',
      'жпт каже по-іншому',
      'сірі краще за тебе',
      'а алекса так може',
      'чатгпт умнее',
      'ты хуже чем гпт',
    ],
  },
  atlas_age: {
    ex: [
      'how many years old are you',
      'how young are you',
      "when's your birthday",
      'what year were you born',
      'since when do you exist',
      'are you older than me',
      'how old r u',
      'when were you created',
      'how long have you been around',
      'are you a newborn',
      'atlas, your age please',
      "what's your birth date",
      'how old is this bot',
      "you're pretty new, right",
      'is it your birthday today',
      'how old do you feel',
      'your year of birth',
      'are you ancient',
      'how many birthdays have you had',
      'age of atlas',
      'you a teenager or what',
      'when did you come to life',
      'are you like one year old',
      'how old',
      'old are you?',
    ],
    exUk: [
      'скільки тобі років, атласе',
      'який у тебе рік народження',
      'з якого часу ти існуєш',
      'ти старший за мене',
      'коли тебе зробили',
      'ти новенький',
      'скільки років цьому боту',
      'в тебе сьогодні день народження',
      'на скільки років ти себе почуваєш',
      'ти древній',
      'скільки днів народжень у тебе було',
      'вік атласа',
      'ти підліток чи що',
      'тобі рочок',
      'скільки тобі стукнуло',
      'коли в тебе др',
      'ти давно з’явився',
      'ти ще малий',
      'який тобі рік',
      'ти молодий чи старий',
      'з якого ти року',
      'ти немовля',
      'сколько тебе',
      'когда у тебя день рождения',
      'ты старый',
    ],
  },
  atlas_sleep: {
    ex: [
      'you awake',
      "don't you ever sleep",
      'do bots sleep',
      'do you go to bed',
      'what time do you go to sleep',
      'are you sleepy',
      'do you ever turn off',
      'do you get any rest',
      'are you always online',
      'do you need a break',
      'you ever tired',
      'are you on 24/7',
      'do you have a bedtime',
      'how many hours do you sleep',
      'were you sleeping',
      'did i wake you up',
      'are you awake at 3am too',
      'do you get sleepy',
      'do ais dream',
      'when do you rest',
      'do you power down at night',
      "don't you need to recharge",
      'do you ever get a day off',
      'do you snooze',
      'are you sleeping right now',
    ],
    exUk: [
      'ти не спиш',
      'ти хоч колись спиш',
      'боти сплять',
      'ти лягаєш спати',
      'о котрій ти лягаєш спати',
      'ти сонний',
      'ти колись вимикаєшся',
      'ти відпочиваєш хоч трохи',
      'ти завжди онлайн',
      'тобі треба перерва',
      'ти втомлюєшся колись',
      'ти працюєш цілодобово',
      'скільки годин ти спиш',
      'ти спав',
      'я тебе розбудив',
      'ти теж не спиш о третій ночі',
      'штучному інтелекту сняться сни',
      'коли ти відпочиваєш',
      'ти вимикаєшся на ніч',
      'тобі не треба підзаряджатися',
      'в тебе бувають вихідні',
      'ти зараз спиш',
      'ти хоч дрімаєш',
      'ты не спишь',
      'ты вообще отдыхаешь',
    ],
  },
  atlas_eat: {
    ex: [
      'do you eat food',
      "what's your favorite meal",
      'what do bots eat',
      'do you drink protein shakes',
      'are you on a diet',
      'do you like chicken and rice',
      'what would you eat if you could',
      'have you eaten today',
      "what's on your menu",
      'do you get hungry',
      'do you eat electricity',
      "what's atlas's favourite snack",
      'do you like sushi',
      'do you have a cheat meal',
      "what's your breakfast",
      'do you drink coffee',
      'are you bulking or cutting',
      'do you eat bytes',
      'do you like burgers',
      'do you ever snack',
      'what do you feed on',
      'want some pizza',
      'you eat carbs?',
      'do you prefer sweet or salty',
      'do you have a favourite dessert',
    ],
    exUk: [
      'ти щось їси взагалі',
      'твоя улюблена страва',
      'що їдять боти',
      'ти п’єш протеїн',
      'ти на дієті',
      'любиш курку з рисом',
      'що б ти їв, якби міг',
      'ти сьогодні їв',
      'що в тебе в меню',
      'ти буваєш голодним',
      'ти харчуєшся електрикою',
      'улюблений перекус атласа',
      'ти любиш суші',
      'у тебе є читміл',
      'що в тебе на сніданок',
      'ти п’єш каву',
      'ти на масі чи на сушці',
      'ти любиш бургери',
      'чим ти харчуєшся',
      'хочеш піци',
      'ти їси вуглеводи',
      'солодке чи солоне любиш',
      'твій улюблений десерт',
      'ты голодный',
      'что ты любишь есть',
    ],
  },
  sing_poem: {
    ex: [
      'rap for me',
      'freestyle something',
      'write me a haiku',
      'a limerick about squats',
      'sing happy birthday',
      'make me a song',
      'can you write poetry',
      'spit some bars',
      'a rhyme about deadlifts',
      'write a verse about leg day',
      'compose a poem about protein',
      'sing a little',
      'can you beatbox',
      'hum a tune',
      'write lyrics for my gym playlist',
      'a poem for my girlfriend',
      'dance!',
      'show me your dance moves',
      'rap battle me',
      'make up a rhyme',
      'a sonnet about the bench press',
      'poem time',
      'sing it',
      'i want a song from you',
      'write me a gym anthem',
    ],
    exUk: [
      'зачитай щось',
      'фрістайл давай',
      'напиши хайку',
      'віршик про присідання',
      'заспівай з днем народження',
      'склади пісню',
      'ти вмієш писати вірші',
      'рима про станову',
      'куплет про день ніг',
      'вірш про протеїн',
      'проспівай щось',
      'бітбокс умієш',
      'наспівай мелодію',
      'напиши текст пісні для залу',
      'вірш для моєї дівчини',
      'станцюй',
      'покажи, як ти танцюєш',
      'реп-батл зі мною',
      'придумай риму',
      'сонет про жим лежачи',
      'час віршів',
      'хочу пісню від тебе',
      'напиши гімн залу',
      'почитай реп',
      'стишок напиши',
    ],
  },
  clock: {
    ex: [
      "what's the time now",
      'current time please',
      'time check',
      'what time we got',
      'is it past noon yet',
      "is it 5 o'clock yet",
      'how late is it',
      'clock?',
      'the time',
      'tell me the current time',
      "what o'clock is it",
      'exact time please',
      'what time does your clock say',
      'hours and minutes now',
      'gimme the time',
      'is it already midnight',
      'how early is it right now',
      'what time is it where you are',
      'time rn',
      "what's the clock say",
      "what's the time in kyiv",
      'is it evening already, what time',
      'yo what time is it',
      'need the time',
      "what time's it",
    ],
    exUk: [
      'котра',
      'скільки на годиннику',
      'котра година вже',
      'а котра зараз',
      'уже північ, котра година',
      'скільки там на годиннику',
      'яка година',
      'котра година в києві',
      'підкажи, скільки часу',
      'котра там',
      'скільки зараз',
      'точний час',
      'час який зараз',
      'котра годинка',
      'вже пізно, котра година',
      'скільки годин зараз',
      'котра година, скажи',
      'шо там по годиннику',
      'скільки там уже часу',
      'який зараз час',
      'а скільки зараз часу',
      'година яка',
      'сколько сейчас времени',
      'который час сейчас',
      'скажи который час',
    ],
  },
  which_day: {
    ex: [
      'date today',
      'what day of the month is it',
      'is it friday yet',
      'is today the weekend',
      "what's the date right now",
      'which weekday is today',
      'what year is it',
      'today is what day',
      'remind me what the date is',
      'day of the week?',
      'is it tuesday or wednesday',
      'what number is today',
      "what's today's day",
      'i lost track of the days, what day is it',
      'calendar date please',
      'is today saturday',
      'what month are we in',
      "what's the date again",
      'which day are we on',
      'is it the 15th today',
      'is today a weekday',
      'day today?',
      "what's the full date",
      "tell me today's date",
      'what day are we',
    ],
    exUk: [
      'а число сьогодні яке',
      'що за день тижня',
      'сьогодні п’ятниця',
      'сьогодні вихідний',
      'який сьогодні день тижня',
      'який зараз рік',
      'нагадай, яке сьогодні число',
      'сьогодні вівторок чи середа',
      'я загубився в днях, який сьогодні день',
      'яка дата',
      'сьогодні субота',
      'який місяць зараз',
      'яке там число',
      'який день сьогодні',
      'сьогодні п’ятнадцяте',
      'сьогодні будній день',
      'повна дата сьогодні',
      'скажи сьогоднішнє число',
      'шо за число сьогодні',
      'а яке сьогодні',
      'день тижня',
      'число яке',
      'какое число',
      'сегодня пятница',
      'какой день недели',
    ],
  },
  you_dumb: {
    ex: [
      "you're so stupid",
      'idiot bot',
      'useless',
      "that's not it",
      "no that's wrong",
      'you got it wrong',
      'read my question again',
      'that has nothing to do with what i asked',
      'i asked something completely different',
      "you're clueless",
      'what are you even talking about',
      "that's nonsense",
      "you don't understand anything",
      'worst answer ever',
      'irrelevant answer',
      'are you broken',
      "you're not getting it",
      'wrong topic',
      "no no no, that's not what i said",
      "you're a dumb bot",
      'nope, not what i meant at all',
      'you missed it completely',
      "come on, that's not what i asked",
      'off topic answer',
      'your answer makes zero sense',
    ],
    exUk: [
      'ти дурень',
      'тупий бот',
      'марний',
      'не те, що я питав',
      'ні, це неправильно',
      'ти не так зрозумів',
      'перечитай моє питання',
      'це взагалі не стосується мого питання',
      'я питав зовсім інше',
      'ти нічого не розумієш',
      'про що ти взагалі',
      'що за дурня',
      'найгірша відповідь',
      'відповідь не в тему',
      'ти зламався',
      'ти не вкурив',
      'не та тема',
      'ні-ні, я не це мав на увазі',
      'дурний бот',
      'ти повністю промахнувся',
      'ну не те ж',
      'відповідь без сенсу',
      'не в тему',
      'ты ничего не понял',
      'тупой бот',
    ],
  },
};
