export const KB_R1: Record<string, { ex: string[]; exUk: string[] }> = {
  pain: {
    ex: [
      'my shoulder is killing me after pressing, what do i do',
      'got a sharp pain in my hip mid set, should i stop',
      'tweaked my lower back, how do i handle it',
      'wrist hurts every time i do push ups',
      'something in my knee clicks and hurts, help',
      'i think i pulled something in my hamstring',
      'pain in my elbow wont go away, train through it or rest?',
      'hurt my neck on shrugs what now',
      'i felt a pinch in my back during rows',
      'my knee has been aching for a week, what should i do',
      'is it ok to keep lifting if my shoulder hurts',
      'injured my lower back yesterday, can i still train',
      'sharp pain in the front of my shoulder, whats the move',
      'my joints hurt after leg day, what do i do about it',
      'ow my back, i think i strained it',
    ],
    exUk: [
      'в мене болить плече після тренування, що робити',
      'щось стрельнуло в спині, тренуватись далі?',
      'коліно ниє вже тиждень, що мені робити',
      'потягнув спину на тязі, як бути',
      'болить лікоть, можна тренуватись через біль?',
      'здається я травмував плече',
      'гострий біль у стегні під час підходу, зупинятись?',
      'шия болить після шрагів, шо робить',
      'запʼястя болить на віджиманнях',
      'у меня болит колено, что делать',
      'потянул поясницу, можно ли тренироваться',
      'резкая боль в плече на жиме, что делать',
      'boli mnie kolano, co mam robić',
      'naciągnąłem plecy, mogę dalej ćwiczyć',
      'ostry ból w barku przy wyciskaniu, co robić',
    ],
  },
  rest: {
    ex: [
      'how many seconds between sets',
      'is 60 seconds rest enough between sets',
      'should i rest 3 minutes between heavy sets',
      'how long do i wait before the next set',
      'rest period between sets for hypertrophy?',
      'how much break between sets for strength',
      'can i rest only 30 sec between sets',
      "what's the ideal pause between sets",
      'how long of a breather between sets on deadlift',
      'do i need longer rest between sets on compound lifts',
      'rest between sets for isolation exercises how long',
      'how long should the timer be between sets',
      'should i shorten my rest between sets',
      'is 2 min rest between sets too long',
      'whats a good rest interval between my sets',
    ],
    exUk: [
      'скільки секунд відпочивати між підходами',
      'хвилини між сетами достатньо?',
      'скільки чекати перед наступним підходом',
      'яку паузу робити між підходами на становій',
      '3 хвилини відпочинку між сетами це нормально?',
      'скільки відпочивати між сетами на масу',
      'скільки перерва між підходами на силу',
      'відпочинок між підходами на ізоляції скільки',
      'яка має бути пауза між сетами',
      'сколько отдыхать между подходами',
      'сколько секунд отдых между сетами',
      'какой перерыв между подходами на присед',
      'ile odpoczywać między seriami',
      'ile przerwy między seriami na przysiadach',
      'czy minuta przerwy między seriami wystarczy',
    ],
  },
  next_weight: {
    ex: [
      'how many kg should i load on bench next session',
      'what should i put on the bar for squats on thursday',
      'give me my working weight for deadlift next time',
      'what weight do i start with on ohp next workout',
      'next session bench, what number',
      'tell me what to lift on squats next workout',
      'what kg for my top set on bench next time',
      "what's my target weight for deadlift tomorrow",
      'which weight should i pick for rows next session',
      'how heavy should my bench be on monday',
      'set me the bench weight for my next workout',
      'what load for squat sets next time i train',
      'whats the plan weight for bench tmrw',
      'what weight do i use for incline press next session',
      'how many plates on squat next time',
    ],
    exUk: [
      'скільки кг вішати на жим наступного тренування',
      'яку робочу вагу брати на присід у четвер',
      'з якою вагою робити станову завтра',
      'яка вага на жим стоячи наступного разу',
      'скажи вагу на жим на наступне тренування',
      'скільки блінів вішати на присід наступного разу',
      'яку вагу на тягу в нахилі наступного разу',
      'яку вагу ставити на жим в понеділок',
      'скок кг на станову наступного разу',
      'какой вес ставить на жим в следующий раз',
      'сколько кг на присед на следующей тренировке',
      'с каким весом делать становую завтра',
      'jaki ciężar na wyciskanie następnym razem',
      'ile kg na przysiad na następnym treningu',
      'jaki ciężar dać na martwy ciąg jutro',
    ],
  },
  best: {
    ex: [
      'what are all my personal records',
      'list my prs',
      'show me my record on every lift',
      'my all time best on squat bench and deadlift',
      "what's my bench pr in reps and weight",
      'which records do i hold on each exercise',
      'show my pr board',
      "what's my best set ever on bench",
      'my top lifts so far',
      'what are my records on the big three',
      'personal best on deadlift?',
      'pr list please',
      'whats my squat pr for 5 reps',
      'best performance on overhead press',
      'all my lifting records',
    ],
    exUk: [
      'покажи всі мої рекорди',
      'які мої особисті рекорди по вправах',
      'мій рекорд на жимі лежачи який',
      'список моїх рекордів',
      'мої найкращі результати в базі',
      'який мій пр на присіді',
      'рекорд на станову на 5 повторів',
      'мої рекорди по всіх вправах',
      'найкращий підхід на жимі за весь час',
      'какие мои личные рекорды',
      'покажи мои рекорды',
      'мой рекорд в жиме лежа',
      'jakie są moje rekordy',
      'pokaż moje rekordy życiowe',
      'mój rekord w wyciskaniu',
    ],
  },
  progress_lift: {
    ex: [
      'is my bench going up over time',
      'how has my squat changed over the last months',
      'show my deadlift progress chart',
      'am i getting stronger on overhead press',
      'trend of my bench over the last 8 weeks',
      'has my squat gone up since i started',
      'is my deadlift stalling or growing',
      'compare my bench now vs two months ago',
      'how much has my bench improved',
      'bench progression so far?',
      'am i progressing on rows',
      'my squat numbers trending up?',
      'how fast is my deadlift growing',
      'track my ohp improvement',
      'is my pull up getting better',
    ],
    exUk: [
      'чи росте мій жим з часом',
      'як змінився мій присід за останні місяці',
      'покажи графік прогресу по становій',
      'я стаю сильнішим у жимі стоячи?',
      'тренд мого жиму за 8 тижнів',
      'наскільки виріс мій жим',
      'чи є прогрес на тязі в нахилі',
      'порівняй мій жим зараз і два місяці тому',
      'станова росте чи стоїть',
      'как прогрессирует мой жим',
      'растет ли мой присед',
      'есть ли прогресс в становой',
      'jak idzie mój postęp w wyciskaniu',
      'czy mój przysiad rośnie',
      'postęp w martwym ciągu',
    ],
  },
  volume_muscle: {
    ex: [
      'weekly sets for chest so far',
      'how much back volume have i done this week',
      'did i hit enough sets for legs this week',
      'count my shoulder sets for the current week',
      'how many hard sets for biceps so far this week',
      'sets per muscle this week',
      'am i under 10 sets for chest this week',
      'is my weekly volume for quads enough',
      'how many sets should i do per week for back',
      "this week's set count for glutes",
      'how many chest sets do i still need this week',
      'whats my weekly volume per muscle group',
      'recommended weekly sets for arms',
      'did i do too many sets for chest this week',
      'triceps sets this week?',
    ],
    exUk: [
      'скільки сетів на ноги я зробив цього тижня',
      'тижневий обсяг на спину',
      'скільки підходів на плечі за цей тиждень',
      'чи достатньо сетів на груди на тиждень',
      'скільки сетів на тиждень треба на спину',
      'обсяг по мʼязах за поточний тиждень',
      'скільки ще підходів на груди до кінця тижня',
      'скільки сетів на біцепс цього тижня',
      'забагато сетів на груди цього тижня?',
      'сколько подходов на грудь на этой неделе',
      'недельный объем на спину',
      'сколько сетов в неделю на ноги нужно',
      'ile serii na klatkę w tym tygodniu',
      'tygodniowa objętość na plecy',
      'ile serii na nogi tygodniowo',
    ],
  },
  weak: {
    ex: [
      'which muscle groups am i ignoring',
      'what body part is behind the rest',
      'where am i weakest overall',
      'what should i focus on more in my training',
      'which muscles get the least work',
      'am i skipping any muscle group',
      'what am i neglecting in my program',
      'which lifts are my weakest compared to others',
      'is my back lagging behind my chest',
      'do i train legs too little compared to upper body',
      "what's missing from my training",
      'find my weak spots',
      'is any muscle group behind',
      'what needs more attention in my workouts',
      "what's my weakest body part",
    ],
    exUk: [
      'які мʼязові групи я ігнорую',
      'що в мене відстає по тренуваннях',
      'де моє слабке місце',
      'на що мені більше звернути увагу',
      'які мʼязи отримують найменше навантаження',
      'чи я не пропускаю якусь групу мʼязів',
      'спина відстає від грудей?',
      'чи мало я качаю ноги порівняно з верхом',
      'знайди мої слабкі місця',
      'какие у меня слабые места',
      'какая мышца отстает',
      'что я недотренировываю',
      'jakie mam słabe punkty',
      'która partia mięśni odstaje',
      'co zaniedbuję w treningu',
    ],
  },
  recovery: {
    ex: [
      'are my shoulders recovered from monday',
      'is my back ready to be trained again',
      'how recovered are my legs right now',
      'which body parts still need recovery',
      'am i fully recovered for chest day',
      'my quads are still sore, are they recovered',
      'recovery status of my muscles',
      'is it too soon to hit chest again after tuesday',
      'have my hamstrings recovered yet',
      'what muscles are fresh today',
      "how's my recovery looking",
      'am i recovered enough to go heavy',
      'still sore from deadlifts, am i recovered?',
      'which muscle groups are fatigued',
      'show my muscle recovery',
    ],
    exUk: [
      'чи відновились плечі після понеділка',
      'спина вже готова до тренування?',
      'наскільки відновлені мої ноги',
      'які мʼязи ще не відновились',
      'я повністю відновився для грудей?',
      'квадрицепси ще болять, вони відновились?',
      'статус відновлення мʼязів',
      'що в мене свіже сьогодні',
      'чи відновився я щоб працювати важко',
      'я восстановился?',
      'восстановились ли ноги',
      'какие мышцы еще не восстановились',
      'czy jestem zregenerowany',
      'czy moje nogi się zregenerowały',
      'które mięśnie są już wypoczęte',
    ],
  },
  today: {
    ex: [
      'what should i train today',
      'what do i train today',
      'which muscles today',
      'what am i training today',
      'what do i hit today',
      'which workout is scheduled for today',
      'what muscle group should i hit today',
      "give me today's session",
      "i'm at the gym, what do i do now",
      'legs or push today?',
      'what should my workout be right now',
      'what am i training this evening',
      'pick a workout for me today',
      "what's today's training day",
      'which day of my program is today',
      'tell me what to lift today',
      'whats the session for today',
      'what exercises are on for today',
      'i have an hour today, what should i train',
    ],
    exUk: [
      'що тренувати сьогодні',
      'що мені сьогодні тренувати',
      'що сьогодні качаємо',
      'що в мене сьогодні по плану в залі',
      'яке тренування на сьогодні заплановане',
      'яку групу мʼязів качати сьогодні',
      'дай тренування на сьогодні',
      'я в залі, що робити',
      'ноги чи жими сьогодні?',
      'що тренувати сьогодні ввечері',
      'підбери мені тренування на сьогодні',
      'шо сьодні тренуєм',
      'что тренировать сегодня',
      'какая тренировка сегодня',
      'что делаем сегодня в зале',
      'co dziś trenować',
      'jaki trening na dziś',
      'co robimy dzisiaj na siłowni',
    ],
  },
  last_session: {
    ex: [
      'how did my previous workout go',
      'recap my last training',
      'what exercises did i do in my last session',
      'how many sets did i do last workout',
      'show me the last session i logged',
      'how was the workout on tuesday',
      'what did my last gym session look like',
      'review my most recent workout',
      'last time at the gym what did i do',
      'details of my last session',
      'how did i perform in my last workout',
      'what weights did i use last session',
      'summarize my latest workout',
      'was my last session any good',
      'what did i lift last time i trained',
    ],
    exUk: [
      'як пройшло моє минуле тренування',
      'розкажи як пройшло останнє тренування',
      'які вправи я робив минулого разу',
      'скільки сетів я зробив на останньому тренуванні',
      'покажи моє останнє записане тренування',
      'як я відпрацював минулого разу',
      'які ваги були на останньому тренуванні',
      'огляд мого останнього тренування',
      'шо я робив минулого разу в залі',
      'как прошла последняя тренировка',
      'что я делал на прошлой тренировке',
      'покажи последнюю тренировку',
      'jak poszedł ostatni trening',
      'co robiłem na ostatnim treningu',
      'podsumuj mój ostatni trening',
    ],
  },
  week: {
    ex: [
      'how did my training go this week overall',
      'give me a recap of this week at the gym',
      'was this a good training week',
      'how many times did i lift this week',
      'weekly report please',
      'how did i do the past 7 days',
      'rate my week of workouts',
      'sum up my gym week',
      'did i hit my weekly goal of sessions',
      'what did this week of training look like',
      "how's my week going so far",
      'week in review for my lifting',
      'how productive was my training week',
      "this week's workouts, how'd they go",
      'show my stats for this week',
    ],
    exUk: [
      'як пройшов мій тренувальний тиждень',
      'підсумуй мій тиждень у залі',
      'чи був це хороший тиждень',
      'скільки разів я тренувався за тиждень',
      'звіт за тиждень',
      'як я потренувався за останні 7 днів',
      'оціни мій тиждень',
      'як іде тиждень поки що',
      'статистика за цей тиждень',
      'как прошла моя неделя',
      'итоги недели по тренировкам',
      'сколько раз я тренировался на этой неделе',
      'jak minął mój tydzień',
      'podsumowanie tygodnia',
      'ile razy trenowałem w tym tygodniu',
    ],
  },
  streak: {
    ex: [
      'how many days in a row have i trained',
      "what's my current streak count",
      'is my streak still alive',
      'how many weeks straight have i worked out',
      'did i lose my streak yesterday',
      'my longest streak ever?',
      'streak status',
      'how long have i kept my streak going',
      "what's my best streak",
      'am i still on a streak',
      'how many consecutive workouts do i have',
      'check my streak',
      'did missing monday reset my streak',
      'streak number please',
      'how many days without missing',
    ],
    exUk: [
      'скільки днів поспіль я тренуюсь',
      'яка моя поточна серія',
      'моя серія ще триває?',
      'скільки тижнів підряд я займаюсь',
      'я втратив серію вчора?',
      'мій найдовший стрік',
      'перевір мою серію',
      'скільки тренувань поспіль без пропусків',
      'стрік не збився?',
      'какая у меня серия',
      'сколько дней подряд я тренируюсь',
      'я не прервал серию?',
      'jaka jest moja seria',
      'ile dni z rzędu trenuję',
      'czy moja seria jest nadal aktywna',
    ],
  },
  total: {
    ex: [
      'how many workouts have i logged overall',
      'total number of sessions since i started',
      'count all my workouts',
      'how many times have i been to the gym in total',
      'all time workout count',
      'how many trainings in the app so far',
      'lifetime number of workouts',
      'how many sessions total since day one',
      'whats my total workout number',
      'how many gym visits have i recorded',
      'total trainings ever',
      'how many workouts have i finished altogether',
      'number of workouts completed all time',
      'have i hit 100 workouts yet',
      'how many total sessions do i have',
    ],
    exUk: [
      'скільки всього тренувань я записав',
      'загальна кількість тренувань з початку',
      'порахуй усі мої тренування',
      'скільки разів я був у залі загалом',
      'кількість тренувань за весь час',
      'скільки тренувань у додатку всього',
      'я вже зробив 100 тренувань?',
      'скільки тренувань я закінчив загалом',
      'скок всього тренувань',
      'сколько всего тренировок',
      'общее количество тренировок',
      'сколько раз я был в зале за все время',
      'ile mam wszystkich treningów',
      'łączna liczba treningów',
      'ile treningów zrobiłem od początku',
    ],
  },
  sleep: {
    ex: [
      'how many hours did i sleep last night',
      'is my sleep good enough for gains',
      'does poor sleep hurt my lifts',
      "how's my sleep been lately",
      'slept 5 hours, should i still train',
      'average hours of sleep this week',
      'am i getting enough sleep to build muscle',
      'how does bad sleep affect my workouts',
      'my sleep score this week',
      'i only slept 4 hours, what now',
      'how much sleep do i need for recovery',
      'did i sleep better this week',
      'does sleep matter for strength',
      'went to bed late, is my training affected',
      'sleep hours trend',
    ],
    exUk: [
      'скільки годин я спав минулої ночі',
      'чи достатньо я сплю для росту',
      'поганий сон впливає на тренування?',
      'як я спав останнім часом',
      'спав 5 годин, тренуватись?',
      'середній сон за тиждень',
      'скільки треба спати для відновлення',
      'чи сон впливає на силу',
      'ліг пізно, це погано для тренування?',
      'сколько часов я спал',
      'влияет ли сон на тренировки',
      'я мало сплю, это плохо для массы',
      'ile spałem ostatniej nocy',
      'czy sen wpływa na trening',
      'ile godzin snu potrzebuję',
    ],
  },
  plan: {
    ex: [
      'what does my current program look like',
      'show me my weekly training plan',
      "what's in my programme this week",
      'which days are what in my plan',
      'remind me of my routine',
      'what split am i running right now',
      'show all workouts in my program',
      'my program schedule for the week',
      "what's my current routine",
      'open my plan',
      'what exercises are in my program',
      'how is my program structured',
      "what's my weekly schedule of workouts",
      'tell me my current training block',
      'what plan am i on',
    ],
    exUk: [
      'як виглядає моя поточна програма',
      'покажи мій тренувальний план на тиждень',
      'що в моїй програмі',
      'нагадай мій розклад тренувань',
      'який у мене зараз спліт',
      'покажи всі тренування з програми',
      'які вправи в моїй програмі',
      'по якому плану я займаюсь',
      'відкрий мою програму',
      'какая у меня программа',
      'покажи мой план тренировок',
      'мое расписание тренировок',
      'jaki jest mój plan treningowy',
      'pokaż mój program',
      'jaki mam rozkład treningów',
    ],
  },
  skip: {
    ex: [
      'is it fine if i miss the gym today',
      'would skipping today ruin my progress',
      'can i take today off',
      "i'm busy today, ok to skip the workout",
      'is one missed session a big deal',
      "can i move today's workout to tomorrow",
      "should i skip training because i'm tired",
      'what happens if i skip leg day today',
      'is it bad to skip a session this week',
      "can i bail on today's workout",
      'skip today and do double tomorrow?',
      "ok if i don't go today",
      'i feel sick, should i skip',
      'can i skip and make it up later',
      'is it alright to take an unplanned rest day',
    ],
    exUk: [
      'нормально якщо я сьогодні пропущу зал',
      'можна сьогодні не йти на тренування',
      'пропуск одного тренування це страшно?',
      'можна перенести тренування на завтра',
      'втомився, пропустити сьогодні?',
      'шо буде якщо я пропущу ноги',
      'я захворів, пропускати тренування?',
      'можна взяти незапланований вихідний',
      'сьогодні нема часу, пропущу ок?',
      'можно пропустить тренировку сегодня',
      'ничего если я пропущу зал',
      'перенести тренировку на завтра можно',
      'czy mogę dziś odpuścić trening',
      'czy mogę dziś opuścić siłownię',
      'co jeśli pominę dzisiejszy trening',
    ],
  },
  motivation: {
    ex: [
      "i just can't make myself go lately",
      'lost my drive to lift',
      "i've been unmotivated for weeks",
      'feeling burnt out on the gym',
      'i keep procrastinating my workouts',
      "how do i stay consistent when i don't feel like it",
      'gym feels boring lately',
      "i can't get off the couch",
      'zero energy and zero will to train',
      'i hate going to the gym these days',
      'how do people stay motivated long term',
      'i keep making excuses not to lift',
      "i've lost interest in training",
      'feel like quitting the gym',
      'no drive to work out at all',
    ],
    exUk: [
      'нема мотивації тренуватись',
      'останнім часом зовсім не хочеться в зал',
      'я вигорів від залу',
      'постійно відкладаю тренування',
      'як не кидати коли не хочеться',
      'зал став нудним',
      'лінь страшна, не можу себе змусити',
      'хочеться все кинути',
      'втратив інтерес до тренувань',
      'нет мотивации',
      'не могу заставить себя идти в зал',
      'пропал интерес к тренировкам',
      'nie mam motywacji',
      'nie chce mi się ćwiczyć',
      'straciłem chęć do treningów',
    ],
  },
  warmup: {
    ex: [
      "what's a good warm up before squats",
      'how many warm up sets before my working sets',
      'best way to warm up my shoulders before bench',
      'warm up routine before leg day',
      'should i stretch or do light sets to warm up',
      'how to ramp up weight before heavy deadlifts',
      'what warm up sets for a 100kg bench',
      'is 5 min on the bike a good warm up',
      'dynamic warm up ideas before lifting',
      'how do i prepare my joints before training',
      'what to do before my first working set',
      'warm up for upper body day?',
      'how should i warm up my knees',
      'how many minutes to warm up before the gym',
      'give me a warm up for push day',
    ],
    exUk: [
      'як розімʼятись перед присідом',
      'скільки розминочних підходів перед робочими',
      'як розігріти плечі перед жимом',
      'розминка перед днем ніг',
      'розтяжка чи легкі підходи для розминки',
      'як підводити вагу перед важкою становою',
      'дай розминку на верх',
      'скільки хвилин розминатись перед тренуванням',
      'як правильно розминатись перед залом',
      'как размяться перед тренировкой',
      'сколько разминочных подходов делать',
      'разминка перед жимом лежа',
      'jak się rozgrzać przed treningiem',
      'ile serii rozgrzewkowych przed przysiadem',
      'rozgrzewka przed wyciskaniem',
    ],
  },
  cooldown: {
    ex: [
      'what should i do to cool down after leg day',
      'is stretching after lifting necessary',
      'how long should my cool-down be',
      'best cool down after a heavy session',
      'should i walk on the treadmill after lifting to cool down',
      'do i need a cooldown or can i just leave',
      'how to cool down properly',
      'is foam rolling after the gym a good cool down',
      'cool down after deadlifts?',
      'does cooling down reduce soreness',
      'what stretches to do after training',
      'should i do a cooldown after cardio',
      'is a cooldown a waste of time',
      '5 min cooldown ideas',
    ],
    exUk: [
      'як зробити заминку після ніг',
      'чи треба розтяжка після тренування',
      'скільки має тривати заминка',
      'яка найкраща заминка після важкого тренування',
      'заминка потрібна чи можна просто йти додому',
      'розтяжка після залу обовʼязкова?',
      'чи зменшує заминка крепатуру',
      'які вправи на розтяжку після тренування',
      'як правильно робити заминку',
      'нужна ли заминка после тренировки',
      'растяжка после тренировки нужна?',
      'как сделать заминку',
      'czy potrzebuję schłodzenia po treningu',
      'rozciąganie po siłowni, warto?',
      'jak się wyciszyć po treningu',
    ],
  },
  cardio: {
    ex: [
      'how many minutes of cardio a week should i do',
      'is cardio necessary if i lift',
      'how much cardio for fat loss while lifting',
      'will cardio kill my gains',
      'how many cardio sessions per week is ideal',
      'should i add cardio to my routine',
      'is 20 min of cardio enough',
      'what type of cardio is best for heart health',
      'hiit or steady state cardio for me',
      'do i need cardio on a bulk',
      'how often should i do cardio',
      'should i do cardio on rest days',
      'cardio amount recommendation?',
      'is too much cardio bad for muscle',
      'how many hours of cardio weekly',
    ],
    exUk: [
      'скільки хвилин кардіо на тиждень робити',
      'чи потрібне кардіо якщо я качаюсь',
      'скільки кардіо для схуднення',
      'кардіо зʼїсть мʼязи?',
      'скільки разів на тиждень кардіо',
      'додати кардіо в програму?',
      '20 хвилин кардіо достатньо?',
      'хііт чи рівномірне кардіо',
      'треба кардіо на масі?',
      'сколько кардио нужно делать',
      'кардио сжигает мышцы?',
      'как часто делать кардио',
      'ile cardio powinienem robić',
      'czy cardio jest potrzebne na masie',
      'ile razy w tygodniu cardio',
    ],
  },
  reps: {
    ex: [
      "what's the best rep range for building muscle",
      'should i do 5 reps or 10 reps per set',
      'how many reps per set for fat loss',
      'high reps or low reps for size',
      'is 3 reps too few for hypertrophy',
      'what rep scheme should i use on squats',
      'how many repetitions in each set',
      'reps for strength vs reps for size',
      'should my sets be 6 to 8 reps',
      'are 20 rep sets useful',
      'how many reps for biceps curls',
      'what rep count per set for beginners',
      'is doing 15 reps a set ok',
      'how many reps should each set be for bench',
      'ideal reps per set?',
    ],
    exUk: [
      'скільки повторень робити в підході',
      'який діапазон повторів для росту мʼязів',
      '5 повторів чи 10 на сет',
      'багато повторів чи мало на масу',
      'скільки повторень для сили',
      'скільки повторів на біцепс',
      'по скільки разів робити в підході',
      '15 повторів у сеті це нормально?',
      'скільки повторів у підході новачку',
      'сколько повторений делать',
      'какой диапазон повторений на массу',
      'сколько повторов в подходе на силу',
      'ile powtórzeń robić w serii',
      'jaki zakres powtórzeń na masę',
      'ile powtórzeń na siłę',
    ],
  },
  failure: {
    ex: [
      "should i push every set until i can't do another rep",
      'is going to muscle failure necessary for growth',
      'last set to failure or leave reps?',
      'does training to failure cause more fatigue',
      'should i fail on squats or only on isolation',
      'is it dangerous to go to failure on bench',
      'failure training good or bad',
      'should i grind until my muscles give out',
      'how often should i hit failure',
      'do i need to fail every workout to grow',
      'can i go to failure on deadlifts',
      'stop short of failure or go all out',
      'is failure better for hypertrophy',
      'should the last set be to absolute failure',
      'training to failure on every exercise ok?',
    ],
    exUk: [
      'чи треба робити кожен підхід до відмови',
      'відмова обовʼязкова для росту мʼязів?',
      'останній підхід до відмови чи залишати повтори',
      'чи небезпечно до відмови на жимі',
      'до відмови на присіді чи тільки на ізоляції',
      'як часто працювати до відмови',
      'відмова це добре чи погано',
      'до відказу треба качатись?',
      'без відмови мʼязи ростуть?',
      'нужно ли тренироваться до отказа',
      'до отказа на каждом подходе нормально?',
      'отказ обязателен для роста',
      'czy trenować do upadku mięśniowego',
      'czy każda seria do upadku',
      'trening do upadku dobry czy zły',
    ],
  },
  bodyweight: {
    ex: [
      'what does the scale say for me lately',
      'how much did i weigh this morning',
      'my current weight in the app',
      "what's my latest bodyweight entry",
      'have i gained weight this month',
      'how has my bodyweight changed',
      'show my weight trend',
      'am i heavier than last week',
      'what was my weight a month ago',
      'did i lose any weight',
      'my weigh in history',
      'how many kg am i right now',
      'bodyweight chart please',
      "what's my weight today",
      'am i losing or gaining weight',
    ],
    exUk: [
      'скільки я зараз важу',
      'моя поточна вага в додатку',
      'останнє зважування яке',
      'чи я набрав вагу цього місяця',
      'як змінилась моя вага',
      'покажи графік ваги',
      'я важчий ніж минулого тижня?',
      'яка була вага місяць тому',
      'я схуд чи набрав',
      'сколько я вешу',
      'мой последний вес',
      'как изменился мой вес',
      'ile ważę',
      'moja aktualna waga',
      'jak zmieniła się moja waga',
    ],
  },
  session_length: {
    ex: [
      'how many minutes should my gym session last',
      'is a 2 hour workout too long',
      'how long is the ideal training session',
      'can a 30 minute workout be effective',
      'how long was my workout on average this month',
      'are my sessions too long',
      'total time i spend per workout',
      'should my workouts be shorter than an hour',
      "what's the typical length of my training",
      'is 45 minutes enough for a full workout',
      'how long do i usually stay in the gym',
      'how long did my last few workouts take start to finish',
      'optimal workout duration for muscle',
      'my average session time',
      'is 90 min in the gym too much',
    ],
    exUk: [
      'скільки хвилин має тривати тренування',
      '2 години в залі це забагато?',
      'яка ідеальна тривалість тренування',
      '30 хвилин тренування це ефективно?',
      'скільки в середньому триває моє тренування',
      'мої тренування занадто довгі?',
      'скільки часу я проводжу в залі за раз',
      '45 хвилин на тренування достатньо?',
      'скок часу має бути тренування',
      'сколько должна длиться тренировка',
      'сколько длятся мои тренировки',
      'полтора часа в зале это много?',
      'ile powinien trwać trening',
      'jak długo trwają moje treningi',
      'czy godzina treningu wystarczy',
    ],
  },
  swap: {
    ex: [
      'replace this exercise in my workout',
      'swap bench for dumbbell press in my plan',
      "change an exercise in today's session",
      'i want to switch leg press for something in my program',
      'how do i change exercises in my routine',
      'put a different exercise instead of this one in my plan',
      'can you swap out lunges in my workout',
      'change pull ups to lat pulldown in my program',
      'remove squats and put in something else',
      'rack is busy, swap this exercise for me',
      'switch the next exercise please',
      'can i exchange an exercise in the app',
      "i don't like this exercise, swap it",
      'change deadlift in my plan',
      'how to substitute an exercise in my routine',
    ],
    exUk: [
      'заміни цю вправу в моєму тренуванні',
      'поміняй жим лежачи на гантелі в програмі',
      'як змінити вправу в плані',
      'хочу замінити жим ногами в програмі',
      'стійка зайнята, заміни вправу',
      'заміни наступну вправу',
      'не подобається вправа, заміни її',
      'прибери присід і постав щось інше',
      'поміняй підтягування на тягу верхнього блока',
      'как заменить упражнение в программе',
      'замени это упражнение',
      'поменяй жим на гантели',
      'jak zamienić ćwiczenie',
      'zamień to ćwiczenie w planie',
      'zmień przysiady na coś innego',
    ],
  },
  technique: {
    ex: [
      'how can i tell if my form is right',
      'can you check my form from a video',
      'what are the key cues for good form',
      'how do i know if my technique is bad',
      'should i film myself to check form',
      'is my technique ok, how would i know',
      'how to self check my lifting form',
      'common form mistakes i should look for',
      'how do i fix bad technique',
      'tips to improve my lifting technique',
      'form check please',
      'what should i look for when i watch my lifting video',
      'how to learn proper technique as a beginner',
      'am i doing it right, how do i check',
      'should i use a mirror to check my form',
    ],
    exUk: [
      'як зрозуміти що техніка правильна',
      'перевір мою техніку по відео',
      'як самому перевірити техніку',
      'чи варто знімати себе на відео для техніки',
      'які типові помилки в техніці',
      'як виправити погану техніку',
      'поради як покращити техніку',
      'як новачку поставити техніку',
      'чи дивитись у дзеркало щоб контролювати техніку',
      'как проверить технику',
      'как понять что техника правильная',
      'проверь мою технику',
      'jak sprawdzić swoją technikę',
      'czy moja technika jest dobra',
      'jak poprawić technikę',
    ],
  },
  protein: {
    ex: [
      'how many grams of protein should i eat a day',
      'is 150g protein enough for me',
      'protein intake for bulking',
      'do i need protein shakes',
      'how much protein per kg of bodyweight',
      'how much protein per meal',
      'what foods have the most protein',
      'is too much protein bad',
      'protein target on a cut',
      'how much protein to build muscle fast',
      'do i need protein on rest days',
      'best protein sources for lifters',
      'can i build muscle without much protein',
      'how much whey should i take',
      'daily protein goal for me',
    ],
    exUk: [
      'скільки грам білка їсти на день',
      '150 г білка мені достатньо?',
      'скільки білка на масу',
      'чи потрібен протеїн',
      'скільки білка на кг ваги',
      'скільки білка за один прийом їжі',
      'в яких продуктах найбільше білка',
      'забагато білка це погано?',
      'скільки протеїну пити',
      'сколько белка нужно в день',
      'сколько протеина на кг веса',
      'нужен ли протеин',
      'ile białka dziennie',
      'ile białka na kilogram masy',
      'czy potrzebuję odżywki białkowej',
    ],
  },
  temper: {
    ex: [
      'can you change your tone',
      'your tone is too aggressive',
      'can i adjust how strict you are',
      'stop yelling at me',
      "i don't like how you talk to me",
      'switch to a softer coaching style',
      'can you be less brutal',
      'why do you roast me all the time',
      'make your tone more friendly',
      'you sound like a drill sergeant, tone it down',
      'change coach personality',
      'can you talk more gently',
      'less harsh please',
      'i want a calmer coach voice',
      'how do i set your tone to soft',
    ],
    exUk: [
      'зміни свій тон',
      'у тебе занадто агресивний тон',
      'можна зробити тебе менш суворим',
      'не кричи на мене',
      'мені не подобається як ти зі мною говориш',
      'перейди на мʼякший стиль',
      'будь менш жорстким',
      'чому ти мене весь час підколюєш',
      'як змінити тон тренера',
      'ты слишком грубый',
      'поменяй тон',
      'говори со мной мягче',
      'zmień ton',
      'jesteś zbyt surowy',
      'mów do mnie łagodniej',
    ],
  },
  who: {
    ex: [
      'what can you help me with',
      'what are you for',
      'what features do you have',
      'tell me about yourself',
      'what kind of questions can i ask you',
      'how can you help my training',
      'what is atlas',
      'introduce yourself',
      'what are your abilities',
      'what do you know how to do',
      'how do i use you',
      'show me what you can do',
      'are you my coach',
    ],
    exUk: [
      'з чим ти можеш допомогти',
      'для чого ти',
      'що ти можеш',
      'розкажи про себе',
      'які питання тобі можна ставити',
      'як ти можеш допомогти з тренуваннями',
      'що таке атлас',
      'представся',
      'з ким я говорю',
      'що ти знаєш',
      'кто ты',
      'что ты умеешь',
      'расскажи о себе',
      'kim jesteś',
      'co potrafisz',
    ],
  },
  greeting: {
    ex: [
      'hey there',
      'yo atlas',
      'good morning',
      'hello coach',
      'hiya',
      'sup',
      'morning atlas',
      'good evening',
      'hey coach',
      'whats up',
      'hola',
      'hi atlas',
      'helloo',
      'heya',
    ],
    exUk: [
      'привіт атлас',
      'добрий день',
      'доброго ранку',
      'хай',
      'вітаннячко',
      'здоровенькі були',
      'привітик',
      'добрий вечір',
      'салют',
      'привет',
      'здравствуй',
      'добрый день',
      'cześć',
      'dzień dobry',
      'siema',
    ],
  },
  muscle_last: {
    ex: [
      'how many days since i trained chest',
      'when was the last time i worked my back',
      'last leg day was when',
      'when did i last hit arms',
      'how long ago did i train shoulders',
      'when was my last glute workout',
      'last time i trained triceps?',
      'when did i last do anything for calves',
      'date of my last chest session',
      'have i trained back since monday',
      'how long since my last abs workout',
      'when did i train hamstrings last',
      'when were legs last trained',
      'last session that hit my chest',
      'been a while since legs? when was it',
    ],
    exUk: [
      'скільки днів минуло відколи я тренував груди',
      'коли востаннє я качав спину',
      'коли був останній день ніг',
      'коли я останній раз тренував руки',
      'як давно я тренував плечі',
      'коли востаннє качав сідниці',
      'коли останній раз тренував трицепс',
      'чи тренував я спину після понеділка',
      'коли були ноги останній раз',
      'когда я последний раз тренировал грудь',
      'когда был последний день ног',
      'как давно я качал спину',
      'kiedy ostatnio trenowałem klatkę',
      'kiedy był ostatni dzień nóg',
      'kiedy ostatnio ćwiczyłem plecy',
    ],
  },
  lift_last: {
    ex: [
      'when was the last time i did bench press',
      'how many days since my last squat',
      'date i last deadlifted',
      'when did i last do pull ups',
      'last time i did rows?',
      'how long since i benched',
      'when did i last do romanian deadlifts',
      'when did i do incline bench last',
      'when was my most recent squat set',
      'how long ago did i last deadlift',
      'have i done ohp since last week',
      'last date i did lunges',
      'when did i last curl',
      'how long has it been since i squatted',
    ],
    exUk: [
      'коли я востаннє робив жим лежачи',
      'скільки днів з мого останнього присіду',
      'коли я останній раз робив підтягування',
      'коли була остання тяга в нахилі',
      'як давно я жав лежачи',
      'коли я робив румунську тягу востаннє',
      'коли востаннє робив жим на похилій',
      'як давно я робив станову',
      'коли останній раз присідав',
      'когда я последний раз жал лежа',
      'когда я последний раз делал присед',
      'как давно я делал становую',
      'kiedy ostatnio robiłem wyciskanie',
      'kiedy ostatnio robiłem przysiady',
      'kiedy ostatnio robiłem martwy ciąg',
    ],
  },
  lift_count: {
    ex: [
      'how many times did i bench this month',
      'how many squat sessions have i logged',
      "number of times i've done deadlifts",
      'how often does bench show up in my workouts',
      'count my overhead press sessions',
      'how many workouts included pull ups',
      'how many times a week do i squat on average',
      'how regularly do i do rows',
      'how many deadlift days this year',
      'how often have i done lunges',
      'times i did bench in total',
      'how many sessions had squats in them',
      'how frequently do i hit deadlifts',
      'how many times have i curled this month',
      'am i benching often enough, how many times',
    ],
    exUk: [
      'скільки разів я жав лежачи цього місяця',
      'скільки тренувань з присідом я записав',
      'скільки разів я робив станову',
      'як часто в мене буває жим',
      'скільки разів я робив підтягування',
      'як часто я присідаю в середньому',
      'скільки днів зі становою цього року',
      'скільки разів загалом я робив жим',
      'як часто я роблю тягу в нахилі',
      'сколько раз я делал жим лежа',
      'как часто я приседаю',
      'сколько раз я делал становую',
      'ile razy robiłem wyciskanie',
      'jak często robię przysiady',
      'ile razy robiłem martwy ciąg',
    ],
  },
  e1rm: {
    ex: [
      'what could i max on bench based on my sets',
      'estimated one rep max for my squat',
      'calculate my 1rm from my last sets',
      "what's my theoretical max on deadlift",
      "based on 100x5 what's my one rep max",
      'predicted max bench',
      'how much could i lift for one rep on squat',
      'e1rm for bench from my latest workout',
      'one rep max estimate on ohp',
      'what would my single be on deadlift',
      'estimated max from my working sets',
      'calc 1rm squat',
      'if i went for a single on bench, how much',
      "what's my projected 1rm",
      '1rm calculator for my bench',
    ],
    exUk: [
      'який мій розрахунковий одноповторний максимум на присіді',
      'порахуй мій 1пм на жимі',
      'скільки я можу пожати на раз',
      'теоретичний максимум на становій',
      '100 на 5, який мій максимум на раз',
      'прогнозований максимум на жимі',
      'розрахуй мій одноповторний максимум',
      'скільки я присяду на раз по розрахунку',
      'який мій орієнтовний 1пм',
      'посчитай мой разовый максимум',
      'расчетный максимум в жиме',
      'сколько я пожму на раз',
      'jaki jest mój szacowany max',
      'oblicz mój 1rm na przysiadzie',
      'ile wycisnę na jeden raz',
    ],
  },
  tonnage: {
    ex: [
      'total kg lifted this week',
      'how much total volume in kg did i move today',
      "what's my tonnage for the month",
      'sum of all weight lifted in my last session',
      'how many tons did i lift this year',
      'total load lifted last workout',
      'workout tonnage today?',
      'how much weight in total did i move on leg day',
      'tonnage trend over the last weeks',
      'kg moved per session on average',
      'total pounds lifted this month',
      'how much did i lift overall today in kg',
      'sum of weight times reps this week',
      "what's my total tonnage all time",
      'how many tonnes have i moved',
    ],
    exUk: [
      'скільки кг я підняв загалом цього тижня',
      'тоннаж за сьогоднішнє тренування',
      'який мій тоннаж за місяць',
      'скільки тонн я підняв цього року',
      'загальна вага за останнє тренування',
      'скільки всього кг я перетягав на ногах',
      'тоннаж за тиждень',
      'сума ваги на повтори за тиждень',
      'скільки тонн я підняв за весь час',
      'какой у меня тоннаж',
      'сколько кг я поднял за неделю',
      'общий тоннаж за месяц',
      'ile kg podniosłem w tym tygodniu',
      'jaki jest mój tonaż',
      'łączny ciężar podniesiony dzisiaj',
    ],
  },
  muscle_frequency: {
    ex: [
      'how many times a week should i hit chest',
      'is training back once a week enough',
      'how often should legs be trained weekly',
      'should i train arms twice a week',
      'how frequently do i train shoulders each week',
      'ideal frequency for training glutes',
      'can i train chest every other day',
      'how many times per week do i work biceps',
      'is hitting each muscle twice a week better',
      'how often per week should i do abs',
      'how many days a week do i train back',
      'frequency per muscle group',
      'do i train legs often enough',
      'how often can i train the same muscle',
      'calves how many times a week',
    ],
    exUk: [
      'скільки разів на тиждень качати груди',
      'одного разу на тиждень на спину достатньо?',
      'як часто треба качати ноги на тиждень',
      'руки двічі на тиждень тренувати?',
      'як часто я треную плечі',
      'як часто треба тренувати сідниці',
      'можна груди через день?',
      'скільки разів на тиждень я треную біцепс',
      'кожен мʼяз двічі на тиждень це краще?',
      'как часто тренировать грудь',
      'сколько раз в неделю качать спину',
      'как часто я тренирую ноги',
      'jak często trenować klatkę',
      'ile razy w tygodniu trenować nogi',
      'jak często ćwiczę plecy',
    ],
  },
  days_per_week: {
    ex: [
      'how many gym days per week is best for me',
      'is training 4 days a week better than 3',
      'should i lift 5 or 6 days a week',
      'how many days a week do i usually train',
      'ideal weekly training frequency',
      'is 2 days per week enough to build muscle',
      "what's my average number of training days per week",
      'can i train 6 times a week',
      'how many days a week should a beginner lift',
      'how many sessions per week do you recommend',
      'how often per week do i actually hit the gym',
      'is going every day of the week too much',
      "what's the right number of gym days weekly",
      'how many weekly workouts for fat loss',
      'should i go 3 or 4 times a week',
    ],
    exUk: [
      'скільки днів на тиждень мені тренуватись',
      '4 рази на тиждень краще за 3?',
      'тренуватись 5 чи 6 днів на тиждень',
      'скільки разів на тиждень я зазвичай тренуюсь',
      '2 рази на тиждень достатньо для мʼязів?',
      'можна тренуватись 6 разів на тиждень',
      'скільки днів на тиждень новачку',
      'скільки тренувань на тиждень радиш',
      '3 чи 4 рази на тиждень ходити в зал',
      'сколько раз в неделю тренироваться',
      'сколько дней в неделю ходить в зал',
      '3 тренировки в неделю достаточно?',
      'ile razy w tygodniu trenować',
      'ile dni w tygodniu chodzić na siłownię',
      'czy 3 treningi w tygodniu wystarczą',
    ],
  },
  how_am_i_doing: {
    ex: [
      'give me an overall review of my training',
      'am i on the right track',
      'grade my training so far',
      "honest feedback on how i'm doing",
      "what's your verdict on my training",
      'am i doing well overall',
      "how's my training looking in general",
      'any feedback on my workouts overall',
      'am i doing ok as a lifter',
      'overall assessment please',
      "tell me how i'm doing so far",
      'what do you think of my training',
      'is my training going well overall',
      'evaluate my overall progress',
      'report card on my training',
    ],
    exUk: [
      'дай загальну оцінку моїх тренувань',
      'я на правильному шляху?',
      'оціни мої тренування загалом',
      'чесний фідбек як я тренуюсь',
      'як тобі мої тренування',
      'я загалом молодець?',
      'як у мене справи з тренуваннями',
      'оціни мій загальний прогрес',
      'що скажеш про мої тренування',
      'как у меня дела с тренировками',
      'оцени мои тренировки',
      'я на правильном пути?',
      'jak mi idzie',
      'oceń mój trening',
      'jak ogólnie wyglądają moje treningi',
    ],
  },
  prs_today: {
    ex: [
      "did i beat any records in today's workout",
      'any new personal bests this session',
      "did today's workout have a pr",
      'new pr today?',
      'did i break a record on bench today',
      "prs from today's session",
      'was anything today a personal record',
      'any records in the workout i just finished',
      'did i set a new best today',
      'which lifts did i pr today',
      'did i improve any record this workout',
      'any pb today',
      "today's new records?",
      'did i crush any pr just now',
      'check if i set records this session',
    ],
    exUk: [
      'чи побив я якийсь рекорд сьогодні',
      'нові особисті рекорди на цьому тренуванні?',
      'сьогодні був пр?',
      'я побив рекорд на жимі сьогодні?',
      'рекорди з сьогоднішнього тренування',
      'в яких вправах я сьогодні поставив рекорд',
      'чи є нові рекорди за це тренування',
      'шо, сьогодні рекорд був?',
      'покращив якийсь рекорд сьогодні?',
      'были ли сегодня рекорды',
      'я побил рекорд сегодня?',
      'новые рекорды на этой тренировке',
      'czy pobiłem dziś rekord',
      'nowe rekordy na dzisiejszym treningu',
      'czy był dziś jakiś rekord',
    ],
  },
};
