import type { Kb } from './types';

export const KB_E: Kb = {
  // ---------------------------------------------------------------- technique
  technique_lift: {
    ex: [
      'how to squat properly',
      'bench press form',
      "what's the correct deadlift technique",
      'how do i do a romanian deadlift',
      'cues for the overhead press',
      'am i doing pull-ups right',
      'proper form for barbell rows',
      'how to perform a hip thrust',
      'teach me the lat pulldown',
      'what is good technique on the leg press',
      'how should i do bulgarian split squats',
      'tips for a cleaner bench press',
      'deadlift form check',
      'how do you do dips correctly',
      'correct way to do a bicep curl',
      'how to do lunges without messing it up',
      'what should my back look like on the deadlift',
      'overhead press technique cues please',
    ],
    exUk: [
      'техніка станової',
      'як правильно присідати',
      'техніка жиму лежачи',
      'як робити румунську тягу',
      'як правильно підтягуватися',
      'підкажи техніку жиму стоячи',
      'як виконувати тягу штанги в нахилі',
      'правильна техніка ягодичного мосту',
      'як робити випади правильно',
      'техніка тяги верхнього блоку',
      'шо по техніці жиму ногами',
      'як нормально робити болгарські присіди',
      'покажи як робити віджимання на брусах',
      'чи правильно я роблю станову',
      'як правильно робити підйом на біцепс',
      'техніка приседа со штангой',
      'как правильно делать становую тягу',
    ],
    facets: {
      why: [
        'Good technique puts the load on the target muscles, keeps joints safe and lets you keep adding weight for years.',
        'Правильна техніка спрямовує навантаження на потрібні м’язи, береже суглоби й дає змогу роками додавати вагу.',
      ],
      how: [
        'Control the lowering, use the full range you can own, no swinging. Film a set from the side and compare it with the cues.',
        'Контрольоване опускання, повна амплітуда, яку контролюєш, без ривків. Зніми сет збоку й порівняй з підказками.',
      ],
      where: [
        'Open the exercise in the library: it has photos, cues and the Learn video.',
        'Відкрий вправу в бібліотеці: там фото, підказки й відео з Learn.',
      ],
      should: [
        'Yes, film yourself now and then, especially when adding weight. If form breaks down, drop the weight until it’s clean again.',
        'Так, час від часу знімай себе, особливо коли додаєш вагу. Якщо техніка сиплеться — зменш вагу, доки знову не буде чисто.',
      ],
    },
  },

  // ---------------------------------------------------------------- injuries
  pain_types: {
    ex: [
      'sharp pain vs dull pain',
      'is a burning feeling in the muscle normal',
      "what's the difference between soreness and injury pain",
      'i have a stabbing pain in my knee when i squat',
      'dull ache in my shoulder, is that bad',
      'how do i know if pain is good or bad pain',
      'sharp pain in my lower back during deadlifts',
      'is burning during a set okay',
      'when is pain a warning sign',
      'good pain or bad pain',
      'my elbow has a sharp pain on curls',
      'aching muscles vs joint pain',
      'stabbing feeling in my wrist when pressing',
      'should i worry about a sharp pain',
      'how can i tell doms from an injury',
    ],
    exUk: [
      'гострий біль чи тупий',
      'пекучий біль у м’язі це нормально',
      'як відрізнити крепатуру від травми',
      'гострий біль у коліні при присіданні',
      'ниючий біль у плечі, це погано',
      'який біль нормальний, а який ні',
      'стріляє в попереку на становій',
      'пече в м’язах під час сету, це ок',
      'різкий біль у лікті на біцепсі',
      'тупий біль у суглобі після тренування',
      'як зрозуміти, що це не просто забиті м’язи',
      'коли біль — це тривожний сигнал',
      'колючий біль у зап’ясті на жимі',
      'острая боль или просто крепатура',
      'ноющая боль в плече после жима',
    ],
    facets: {
      what: [
        'Normal soreness is a dull, spread-out ache in the muscle that fades in a day or two. Warning pain is sharp, in a joint, worse with load, or comes with swelling.',
        'Звичайна крепатура — тупий розлитий біль у м’язі, що минає за день-два. Тривожний біль — гострий, у суглобі, гіршає з вагою або з набряком.',
      ],
      should: [
        'Training with mild soreness is fine. With sharp or joint pain, stop that lift rather than pushing through.',
        'Тренуватися з легкою крепатурою — нормально. Якщо біль гострий чи в суглобі — зупини цю вправу, не терпи.',
      ],
      when: [
        'See a doctor if the pain is sharp and doesn’t settle, there’s swelling, you can’t bear weight or numbness spreads.',
        'До лікаря — якщо гострий біль не минає, є набряк, не можеш стати на ногу або оніміння поширюється.',
      ],
      where: [
        'Log it in the Injury screen so the plan works around that area.',
        'Запиши це на екрані «Травми», щоб план обходив цю зону.',
      ],
    },
  },

  return_injury: {
    ex: [
      'when can i return to lifting after an injury',
      'how to come back after a back injury',
      'getting back into training after a shoulder injury',
      'how much weight should i use after an injury',
      'when is it safe to start again after hurting my knee',
      'coming back from an injury, where do i start',
      'how fast can i progress after an injury',
      'return to the gym after a strained hamstring',
      "i'm healed, how do i get back to my old weights",
      'can i train again now that the pain is gone',
      'rehab back to squatting after injury',
      'how long before i can lift heavy again after injury',
      'easing back in after a hurt wrist',
      'starting again after a pulled muscle',
      'when can i bench again after a pec strain',
    ],
    exUk: [
      'коли можна повернутися до тренувань після травми',
      'як повертатися після травми спини',
      'з якої ваги почати після травми',
      'коли можна знову присідати після травми коліна',
      'повернення в зал після розтягнення',
      'біль пройшов, коли можна тренуватися',
      'як швидко додавати вагу після травми',
      'після травми плеча з чого починати',
      'вже не болить, можна повертатись до старих ваг',
      'скільки часу треба, щоб повернутися після травми',
      'як не зірватися знову після травми',
      'відновлення після травми, як заходити назад у зал',
      'коли можна знову жати після травми грудних',
      'когда можно вернуться в зал после травмы',
      'как вернуться к тренировкам после травмы',
    ],
    facets: {
      when: [
        'When everyday movement is pain-free. If a doctor is involved, follow their clearance first.',
        'Коли звичайні рухи вже без болю. Якщо тебе веде лікар — спершу його дозвіл.',
      ],
      howMuch: [
        'Start at about 50% of the old weight and add 10–20% a week if it’s quiet the next morning.',
        'Почни з ~50% старої ваги й додавай 10–20% на тиждень, якщо наступного ранку спокійно.',
      ],
      how: [
        'Build back gradually and use the next morning as the test: no extra pain means you can progress, pain means hold or step back.',
        'Повертайся поступово, а наступний ранок — твій тест: немає болю — можна додавати, болить — тримай або відступи на крок.',
      ],
      where: [
        'The Injury screen runs the return stage by stage.',
        'Екран «Травми» веде повернення поетапно.',
      ],
      should: [
        'Don’t jump straight back to old weights. If pain returns with swelling or you can’t bear weight, stop and see a doctor.',
        'Не стрибай одразу на старі ваги. Якщо біль повертається з набряком або не можеш стати на ногу — зупинись і до лікаря.',
      ],
    },
  },

  ice_heat: {
    ex: [
      'ice or heat',
      'should i ice my knee',
      'heat or cold for sore muscles',
      'does a heating pad help a stiff back',
      'put ice on a sprain',
      'cold pack after a knock',
      'is icing good after training',
      'how long should i ice it',
      'heat for a tight neck',
      'should i use ice or a hot bath for soreness',
      'my ankle is swollen, ice?',
      'does ice help recovery',
      'warm compress or ice pack',
      'when do you use heat instead of ice',
      'icing a swollen elbow',
    ],
    exUk: [
      'лід чи тепло',
      'прикладати лід на коліно',
      'грілка на поперек допоможе',
      'холод чи тепло на забиті м’язи',
      'скільки тримати лід',
      'набрякла щиколотка, лід прикласти',
      'тепло на скуту шию',
      'холодний компрес після удару',
      'чи треба прикладати холод після тренування',
      'коли тепло, а коли холод',
      'гріти чи охолоджувати розтягнення',
      'льод на лікоть допомагає',
      'грілку можна на спину',
      'лед или тепло на травму',
      'прикладывать ли холод к колену',
    ],
    facets: {
      when: [
        'Cold for a fresh knock or swelling; heat for stiff, achy muscles.',
        'Холод — на свіжий удар чи набряк; тепло — на скуті, ниючі м’язи.',
      ],
      howMuch: [
        'Cold for about 10–15 minutes at a time, with a cloth between the ice and the skin.',
        'Холод — приблизно 10–15 хвилин за раз, через тканину, не на голу шкіру.',
      ],
      what: [
        'Both are for comfort. Neither heals the injury; easy movement does.',
        'І те, й інше — для полегшення. Лікує не це, а легкий рух.',
      ],
      should: [
        'Use whichever feels better. If swelling is large, you can’t bear weight or it isn’t improving, see a doctor.',
        'Користуйся тим, від чого краще. Якщо набряк великий, не можеш стати на ногу або не покращується — до лікаря.',
      ],
    },
  },

  painkillers: {
    ex: [
      'can i take ibuprofen before training',
      'painkillers to train through pain',
      'is it ok to lift on paracetamol',
      'should i take an nsaid for sore muscles',
      'ibuprofen after the gym',
      'pop a painkiller and keep training?',
      'do painkillers slow muscle growth',
      'what painkiller should i take for my back',
      'is taking pills before a workout bad',
      'can i train if i took ibuprofen',
      'anti-inflammatories for knee pain',
      'using painkillers so i can finish the program',
      'painkiller before heavy deadlifts',
      'is paracetamol safe with lifting',
    ],
    exUk: [
      'можна пити ібупрофен перед тренуванням',
      'знеболювальне, щоб тренуватися з болем',
      'випити таблетку і в зал',
      'чи можна тренуватися на знеболюючих',
      'ібупрофен після залу',
      'яке знеболювальне пити від болю в спині',
      'чи шкодять таблетки від болю росту м’язів',
      'прийняв знеболююче, можна качатися',
      'протизапальні від болю в коліні',
      'пити парацетамол перед тренуванням нормально',
      'таблетки від болю перед становою',
      'знеболювальне після важкого тренування',
      'можно ли тренироваться на обезболивающих',
      'обезбол перед тренировкой',
    ],
    facets: {
      should: [
        'Don’t take painkillers to train through pain; the pain is the signal you need.',
        'Не пий знеболювальне, щоб тренуватися крізь біль, — біль і є потрібний сигнал.',
      ],
      why: [
        'Masking pain lets you load an injured area and make it worse.',
        'Заглушений біль дає навантажити травмовану зону й погіршити її.',
      ],
      who: [
        'A doctor or pharmacist can say what is right for you, including doses and interactions.',
        'Що тобі підходить, включно з дозами й взаємодією, — скаже лікар чи фармацевт.',
      ],
    },
  },

  tendon: {
    ex: [
      'tendon pain',
      'how to fix tendinitis',
      'my achilles tendon hurts',
      'patellar tendon pain from squats',
      'tennis elbow from lifting',
      'should i rest a sore tendon',
      'tendinopathy rehab exercises',
      'how long does a tendon take to heal',
      "golfer's elbow and curls",
      'sore tendon in my shoulder',
      'isometric holds for tendons',
      'can i lift with tendinitis',
      "jumper's knee and training",
      'what helps inflamed tendons',
      'tendon keeps flaring up',
    ],
    exUk: [
      'болить сухожилля',
      'як лікувати тендиніт',
      'болить ахілл',
      'біль у сухожиллі під коліном від присідань',
      'тенісний лікоть від тренувань',
      'чи треба відпочивати, якщо болить сухожилля',
      'вправи при тендинопатії',
      'скільки заживає сухожилля',
      'ізометрія для сухожиль',
      'можна тренуватися з тендинітом',
      'сухожилля в плечі ниє',
      'запалення сухожилля, що робити',
      'знову загострився тендиніт',
      'болит сухожилие что делать',
      'тендинит и тренировки',
    ],
    facets: {
      what: [
        'Tendon pain (tendinopathy) is usually an overload problem: the tendon got more load than it was ready for.',
        'Біль у сухожиллі (тендинопатія) зазвичай від перевантаження: сухожилля отримало більше, ніж було готове.',
      ],
      how: [
        'Slow, heavy-ish reps or isometric holds that keep pain under 3/10 during and the next day.',
        'Повільні досить важкі повтори або ізометричні утримання, щоб біль був до 3/10 під час і наступного дня.',
      ],
      howMuch: [
        '3–4 sessions a week for 6–12 weeks; tendons adapt slowly.',
        '3–4 рази на тиждень протягом 6–12 тижнів — сухожилля адаптуються повільно.',
      ],
      why: [
        'Tendons like steady load, not rest; complete rest makes them weaker and more sensitive.',
        'Сухожилля люблять рівномірне навантаження, а не спокій; повний спокій робить їх слабшими й чутливішими.',
      ],
      when: [
        'See a doctor if there is sudden sharp pain with a pop, visible swelling, or it gets worse despite reduced load.',
        'До лікаря — якщо був різкий біль із клацанням, помітний набряк або гіршає навіть після зменшення навантаження.',
      ],
    },
  },

  cramps: {
    ex: [
      'i get cramps during sets',
      'why do my calves cramp',
      'muscle cramp mid workout',
      'hamstring cramps on leg curls',
      'how to stop cramps',
      'cramping at night after leg day',
      'my foot cramps when i squat',
      'what causes muscle cramps',
      'cramp in my calf, what do i do',
      'frequent cramps when training',
      'does salt help with cramps',
      'abs cramping during crunches',
      'how to prevent cramping in the gym',
      "got a cramp and can't finish the set",
    ],
    exUk: [
      'судоми під час тренування',
      'зводить литку',
      'чому зводить м’язи',
      'судома посеред сету',
      'як позбутися судом',
      'вночі зводить ноги після тренування',
      'судоми в задній поверхні стегна',
      'ногу звело, що робити',
      'часто зводить м’язи в залі',
      'сіль допомагає від судом',
      'спазм м’язу на тренуванні',
      'як не допустити судом',
      'стопу зводить на присіданнях',
      'судорога в икре что делать',
      'сводит мышцы на тренировке',
    ],
    facets: {
      why: [
        'Usually muscle fatigue; low fluids, low salt and poor sleep make them more likely.',
        'Зазвичай це втома м’яза; мало води, солі й сну — роблять їх імовірнішими.',
      ],
      how: [
        'Stretch the muscle gently until it lets go and sip water with a pinch of salt.',
        'М’яко розтягни м’яз, доки не відпустить, і випий води з дрібкою солі.',
      ],
      should: [
        'Occasional cramps are harmless. If they’re frequent, come at rest, or with swelling or weakness, see a doctor.',
        'Поодинокі судоми не шкідливі. Якщо часто, у спокої або з набряком чи слабкістю — до лікаря.',
      ],
    },
  },

  numbness: {
    ex: [
      'my hands go numb when i deadlift',
      'tingling in my fingers after bench',
      'pins and needles in my arm',
      'numb leg after squats',
      'why do my fingers tingle during pull-ups',
      'numbness down my leg',
      'my foot goes numb on the leg press',
      'tingling in my hand after overhead press',
      'arm feels numb after training',
      'is numbness normal after lifting',
      'tingly feeling in my thigh',
      'fingers numb on rows',
      'numb pinky after curls',
      'pins and needles when i sit after leg day',
    ],
    exUk: [
      'німіють руки на становій',
      'поколювання в пальцях після жиму',
      'оніміння в руці',
      'німіє нога після присідань',
      'мурашки по руці на підтягуваннях',
      'оніміння йде вниз по нозі',
      'стопа німіє на жимі ногами',
      'поколює в долоні після жиму стоячи',
      'рука як ватна після тренування',
      'чи нормально, що німіють пальці',
      'німіє мізинець після біцепса',
      'поколювання в стегні',
      'немеют пальцы после жима',
      'онемение в ноге после приседаний',
    ],
    facets: {
      what: [
        'Numbness or tingling points to a nerve, not a muscle.',
        'Оніміння чи поколювання вказує на нерв, а не на м’яз.',
      ],
      should: [
        'Stop the lift that brings it on; don’t keep loading through it.',
        'Зупини вправу, яка це викликає; не навантажуй далі крізь це.',
      ],
      when: [
        'See a doctor if it stays, spreads, or comes with weakness, or with loss of bladder or bowel control (urgent).',
        'До лікаря — якщо не минає, поширюється чи є слабкість; при проблемах із сечовим міхуром чи кишківником — терміново.',
      ],
    },
  },

  // ---------------------------------------------------------------- nutrition
  calories: {
    ex: [
      'how many calories should i eat',
      'my maintenance calories',
      'how many kcal a day do i need',
      'calorie intake for lifting',
      'what are my daily calories',
      'calculate my calories',
      'how much should i eat in calories to gain muscle',
      'calories for my goal',
      'am i eating enough calories',
      "what's my tdee",
      'how many calories to maintain weight',
      'daily calorie target',
      'should i count calories',
      'how do i know my maintenance',
      'kcal per day for someone who trains',
    ],
    exUk: [
      'скільки калорій мені їсти',
      'яка в мене підтримка по калоріях',
      'скільки ккал на день треба',
      'порахуй мої калорії',
      'калораж для набору м’язів',
      'скільки калорій, щоб тримати вагу',
      'чи достатньо я їм калорій',
      'денна норма калорій',
      'чи треба рахувати калорії',
      'мій калораж на день',
      'скільки калорій спалюю за день',
      'яка норма ккал при тренуваннях',
      'шо по калоріям мені',
      'сколько калорий мне есть',
      'норма калорий в день',
    ],
    facets: {
      howMuch: [
        'Rough rule: about 30–33 kcal per kg of bodyweight a day for an active lifter to maintain.',
        'Орієнтир: ~30–33 ккал на кг ваги на день для підтримки в людини, що тренується.',
      ],
      how: [
        'Start from the estimate, watch the scale for 2 weeks and adjust by about 200 kcal.',
        'Почни з оцінки, два тижні стеж за вагою й коригуй приблизно на 200 ккал.',
      ],
      what: [
        'Maintenance is the intake that keeps your weight stable; below it you lose, above it you gain.',
        'Підтримка — це кількість, за якої вага стабільна; менше — худнеш, більше — набираєш.',
      ],
      where: [
        'Log your bodyweight in the app and Atlas estimates your calories from the latest entry and your goal.',
        'Запиши вагу в застосунку — Atlas порахує калорії за останнім записом і твоєю метою.',
      ],
    },
  },

  cut_deficit: {
    ex: [
      'how big should my calorie deficit be',
      'what deficit to lose fat',
      'how fast should i lose weight on a cut',
      'is a 1000 calorie deficit too much',
      'how much weight per week on a cut',
      'deficit without losing muscle',
      'aggressive deficit or slow cut',
      'how many calories under maintenance',
      'safe rate of weight loss',
      'keeping muscle in a deficit',
      'how fast lose fat without losing strength',
      "what's a good deficit for cutting",
      'am i losing weight too fast',
      'how much to cut calories',
    ],
    exUk: [
      'який дефіцит калорій робити',
      'як швидко худнути, щоб не втратити м’язи',
      'скільки скидати на тиждень',
      'дефіцит 1000 ккал це забагато',
      'на скільки зменшити калорії для сушки',
      'як не втратити м’язи на дефіциті',
      'швидко чи повільно сушитися',
      'який безпечний темп схуднення',
      'скільки кг на тиждень нормально скидати',
      'я не занадто швидко худну',
      'дефіцит для сушки який',
      'мінус скільки калорій від підтримки',
      'какой дефицит калорий нужен',
      'как быстро можно худеть',
    ],
    facets: {
      howMuch: [
        'About 300–500 kcal below maintenance, losing 0.5–1% of bodyweight a week.',
        'Приблизно 300–500 ккал нижче підтримки, мінус 0,5–1% ваги на тиждень.',
      ],
      how: [
        'Keep lifting heavy and keep protein around 2 g/kg; that is what preserves muscle.',
        'Далі важко тренуйся й тримай білок ~2 г/кг — саме це зберігає м’язи.',
      ],
      why: [
        'A moderate deficit loses fat while keeping strength and muscle; very large deficits cost muscle, energy and sleep.',
        'Помірний дефіцит забирає жир і зберігає силу й м’язи; дуже великий — коштує м’язів, енергії та сну.',
      ],
      should: [
        'Avoid crash diets. If you lose more than about 1% a week and strength drops, eat a bit more.',
        'Уникай жорстких дієт. Якщо скидаєш більше ~1% на тиждень і падає сила — їж трохи більше.',
      ],
    },
  },

  bulk_surplus: {
    ex: [
      'how big should my surplus be',
      'lean bulk or dirty bulk',
      'how many calories over maintenance to bulk',
      'how fast should i gain weight on a bulk',
      'is a dirty bulk worth it',
      'calorie surplus for muscle gain',
      'how much weight per month when bulking',
      'am i gaining too fast on my bulk',
      'clean bulk calories',
      'how to bulk without getting fat',
      'what surplus for a beginner',
      'is 500 calories surplus too much',
      'bulking pace',
      'should i eat everything to bulk',
    ],
    exUk: [
      'який профіцит калорій робити',
      'чистий набір чи брудний',
      'скільки калорій понад підтримку на масу',
      'як швидко набирати вагу на масонаборі',
      'брудний набір має сенс',
      'профіцит для росту м’язів',
      'скільки кг на місяць набирати',
      'я не занадто швидко набираю',
      'як набирати масу без жиру',
      'профіцит для новачка',
      'плюс 500 ккал це забагато',
      'їсти все підряд на масу норм',
      'какой профицит нужен для массы',
      'грязный набор или чистый',
    ],
    facets: {
      howMuch: [
        'About +200–300 kcal a day, gaining roughly 0.25–0.5% of bodyweight a month; beginners can gain a bit faster.',
        'Приблизно +200–300 ккал на день, +0,25–0,5% ваги на місяць; новачкам можна трохи швидше.',
      ],
      what: [
        'A lean bulk is a small, controlled surplus; a dirty bulk is eating everything, which mostly adds fat.',
        'Чистий набір — невеликий контрольований профіцит; брудний — їсти все підряд, що здебільшого додає жир.',
      ],
      why: [
        'Muscle grows slowly, so a bigger surplus doesn’t build it faster; the extra is stored as fat.',
        'М’язи ростуть повільно, тож більший профіцит їх не прискорює — надлишок іде в жир.',
      ],
      who: [
        'Beginners and people returning after a break gain muscle fastest and tolerate a slightly larger surplus.',
        'Новачки й ті, хто повертається після перерви, набирають м’язи найшвидше й можуть мати трохи більший профіцит.',
      ],
    },
  },

  carbs: {
    ex: [
      'how many carbs should i eat',
      'are carbs bad',
      'carbs for lifting',
      'should i go low carb',
      'rice or pasta before training',
      'how many grams of carbs per day',
      'do carbs make you fat',
      'best carbs for the gym',
      'is keto good for lifting',
      'carbs on rest days',
      'should i cut carbs to lose fat',
      'oats for energy',
      'when to eat carbs',
      'carb intake for muscle gain',
    ],
    exUk: [
      'скільки вуглеводів їсти',
      'вуглеводи шкідливі',
      'чи переходити на низьковуглеводну',
      'скільки грамів вуглеводів на день',
      'від вуглеводів товстіють',
      'які вуглеводи найкращі для залу',
      'кето для тренувань норм',
      'вуглеводи у день відпочинку',
      'прибрати вуглеводи, щоб схуднути',
      'вівсянка для енергії',
      'коли краще їсти вуглеводи',
      'рис чи макарони',
      'вуглі на масі скільки',
      'сколько углеводов нужно в день',
      'углеводы вечером можно',
    ],
    facets: {
      howMuch: [
        'About 3–5 g per kg of bodyweight a day works for most lifters.',
        'Приблизно 3–5 г на кг ваги на день підходить більшості.',
      ],
      when: [
        'Put more of them around training, in the meals before and after.',
        'Більше — навколо тренування, у прийомах до й після.',
      ],
      why: [
        'Carbs are the main fuel for hard sets and help you train with more volume.',
        'Вуглеводи — основне паливо для важких сетів і допомагають витримати більший об’єм.',
      ],
      should: [
        'Low-carb works for fat loss if you enjoy it, but sessions may feel flatter.',
        'Низьковуглеводна дієта теж працює для схуднення, якщо подобається, але тренування можуть бути «пласкішими».',
      ],
    },
  },

  fats: {
    ex: [
      'how much fat should i eat',
      'dietary fat intake for lifters',
      'is fish oil worth taking',
      'do i need omega 3',
      'grams of fat per day',
      'is dietary fat bad',
      'best fats to eat',
      'low fat diet for the gym',
      'fat intake on a cut',
      'are eggs and nuts too much fat',
      'healthy fats sources',
      'omega-3 supplements for muscle',
      'can i eat fats on a bulk',
      'too little fat in my diet',
    ],
    exUk: [
      'скільки жирів їсти',
      'норма жирів на день',
      'чи варто пити риб’ячий жир',
      'омега 3 потрібна',
      'скільки грамів жиру на кг',
      'жири шкідливі',
      'які жири корисні',
      'жири на сушці скільки',
      'горіхи і яйця це не забагато жирів',
      'омега-3 для м’язів',
      'мало жирів у раціоні',
      'рибячий жир пити чи ні',
      'сколько жиров нужно в день',
      'омега 3 нужна ли',
    ],
    facets: {
      howMuch: [
        'About 0.6–1 g of fat per kg of bodyweight a day.',
        'Приблизно 0,6–1 г жиру на кг ваги на день.',
      ],
      what: [
        'Good sources: olive oil, nuts, eggs, fish and avocado; keep fried and processed fats as extras.',
        'Хороші джерела: оливкова олія, горіхи, яйця, риба, авокадо; смажене й оброблене — як доповнення.',
      ],
      why: [
        'Fats support hormones, vitamin absorption and satiety; going very low isn’t helpful.',
        'Жири потрібні для гормонів, засвоєння вітамінів і ситості; дуже мало — не на користь.',
      ],
      should: [
        'Two fish meals a week cover omega-3 for most people; fish oil makes sense if you rarely eat fish.',
        'Дві рибні страви на тиждень покривають омега-3 для більшості; риб’ячий жир має сенс, якщо рибу майже не їси.',
      ],
    },
  },

  pre_meal: {
    ex: [
      'what to eat before a workout',
      'pre workout meal',
      'how long before training should i eat',
      'eat before the gym or not',
      'best food before lifting',
      'snack before training',
      'what should i eat an hour before the gym',
      'can i eat right before a workout',
      'meal before morning training',
      'banana before the gym',
      'how much to eat before a workout',
      'pre-training food ideas',
      'i feel weak, what to eat before training',
      'food before leg day',
    ],
    exUk: [
      'що їсти перед тренуванням',
      'за скільки до тренування поїсти',
      'їсти перед залом чи ні',
      'що поїсти за годину до тренування',
      'перекус перед тренуванням',
      'банан перед залом норм',
      'їжа перед ранковим тренуванням',
      'можна поїсти прямо перед тренуванням',
      'скільки їсти перед тренуванням',
      'шо закинути перед залом',
      'перед днем ніг що поїсти',
      'їм перед тренуванням і важко, що робити',
      'что есть перед тренировкой',
      'за сколько до тренировки кушать',
    ],
    facets: {
      when: [
        'A normal meal 1–3 hours before, or something small 30–60 minutes before.',
        'Звичайна їжа за 1–3 години або щось невелике за 30–60 хвилин.',
      ],
      what: [
        'Carbs plus protein: rice and chicken, oats and yoghurt. Close to training: a banana or a yoghurt.',
        'Вуглеводи з білком: рис і курка, вівсянка й йогурт. Ближче до тренування — банан або йогурт.',
      ],
      howMuch: [
        'A normal-sized meal 1–3 hours out; closer to training keep it small and light so it sits well.',
        'За 1–3 години — звичайна порція; ближче до тренування — невелике й легке, щоб не заважало.',
      ],
      why: [
        'Food before training gives energy for hard sets and helps avoid feeling weak or dizzy.',
        'Їжа перед тренуванням дає енергію для важких сетів і допомагає не відчувати слабкості чи запаморочення.',
      ],
    },
  },

  post_meal: {
    ex: [
      'what to eat after a workout',
      'post workout meal',
      'how soon after training should i eat',
      'is the anabolic window real',
      'best food after lifting',
      'what should i eat after the gym',
      'do i need to eat within 30 minutes after training',
      'post-training food ideas',
      'meal after an evening workout',
      'how much to eat after training',
      'can i skip eating after the gym',
      'recovery meal after leg day',
      'eat carbs after a workout?',
      'food after training to build muscle',
    ],
    exUk: [
      'що їсти після тренування',
      'через скільки після тренування їсти',
      'анаболічне вікно існує',
      'що поїсти після залу',
      'чи треба їсти протягом 30 хвилин після тренування',
      'їжа після вечірнього тренування',
      'скільки їсти після тренування',
      'можна не їсти після залу',
      'вуглеводи після тренування потрібні',
      'що з’їсти після дня ніг',
      'після тренування одразу їсти',
      'шо поїсти після качалки',
      'что есть после тренировки',
      'углеводное окно после тренировки',
    ],
    facets: {
      when: [
        'Within a few hours after training is fine; there is no need to rush.',
        'Протягом кількох годин після тренування — нормально, поспішати не треба.',
      ],
      what: [
        'A meal with protein and some carbs, for example chicken and rice or yoghurt with fruit.',
        'Прийом із білком і трохи вуглеводів, наприклад курка з рисом або йогурт із фруктами.',
      ],
      howMuch: [
        'About 25–40 g of protein plus some carbs.',
        'Приблизно 25–40 г білка й трохи вуглеводів.',
      ],
      should: [
        'The “30-minute window” is mostly a myth; the day’s total matters more.',
        '«Вікно 30 хвилин» — здебільшого міф; важливіший підсумок за день.',
      ],
    },
  },

  meals_count: {
    ex: [
      'how many meals a day should i eat',
      'how often should i eat',
      'is eating 3 times a day enough',
      '6 small meals or 3 big ones',
      'do i need to eat every 3 hours',
      'meal frequency for muscle gain',
      'is two meals a day ok',
      'how many times a day to eat when bulking',
      'does meal frequency matter',
      'one meal a day and lifting',
      'should i eat more often to build muscle',
      'how to split food across the day',
      'number of meals per day',
      'eating 5 times a day necessary?',
    ],
    exUk: [
      'скільки разів на день їсти',
      'скільки прийомів їжі потрібно',
      '3 рази на день достатньо',
      '6 маленьких прийомів чи 3 великих',
      'чи треба їсти кожні 3 години',
      'два прийоми їжі на день нормально',
      'скільки разів їсти на масі',
      'чи важлива частота прийомів їжі',
      'їсти раз на день і тренуватися',
      'як розбити їжу на день',
      'часто їсти для м’язів треба',
      'дробне харчування потрібне',
      'сколько раз в день есть',
      'сколько приемов пищи нужно',
    ],
    facets: {
      howMuch: [
        '3–5 meals a day, each with about 0.4 g of protein per kg of bodyweight.',
        '3–5 прийомів на день, у кожному ~0,4 г білка на кг ваги.',
      ],
      should: [
        'Fewer meals are fine too if the daily totals are there.',
        'Менше прийомів — теж нормально, якщо за день набирається потрібне.',
      ],
      why: [
        'Spreading protein over a few meals helps a bit, but daily totals matter far more than frequency.',
        'Розподіл білка на кілька прийомів трохи допомагає, але підсумок за день важить набагато більше за частоту.',
      ],
    },
  },

  vegan: {
    ex: [
      'can you build muscle as a vegan',
      'vegetarian bodybuilding',
      'plant-based protein sources',
      'vegan diet for lifting',
      'is plant protein as good as meat',
      "i don't eat meat, how do i get enough protein",
      'should vegans take creatine',
      'vegan bulking tips',
      'tofu and lentils enough for gains',
      'vegetarian and strength training',
      'b12 for vegans who lift',
      'pea protein vs whey',
      'plant based athlete diet',
      'going vegan, will i lose muscle',
    ],
    exUk: [
      'чи можна накачатися веганом',
      'вегетаріанство і тренування',
      'рослинні джерела білка',
      'веганська дієта для залу',
      'рослинний білок такий же як м’ясо',
      'я не їм м’яса, де брати білок',
      'веганам треба креатин',
      'масонабір на веганстві',
      'тофу і сочевиці вистачить для м’язів',
      'B12 веганам, які тренуються',
      'гороховий протеїн чи сироватковий',
      'перейду на рослинне харчування, втрачу м’язи',
      'без м’яса можна набрати масу',
      'можно ли качаться без мяса',
      'веган и спорт',
    ],
    facets: {
      how: [
        'Mix protein sources through the day: soy, tofu, lentils, seitan, pea protein.',
        'Змішуй джерела білка протягом дня: соя, тофу, сочевиця, сейтан, гороховий протеїн.',
      ],
      howMuch: [
        'Aim a bit higher on protein, around 2 g per kg of bodyweight.',
        'Білка трохи більше — приблизно 2 г на кг ваги.',
      ],
      should: [
        'Take B12. Creatine is worth considering and helps plant-based lifters even more than meat-eaters.',
        'Приймай B12. Креатин вартий уваги й допомагає тим, хто на рослинному, навіть більше, ніж м’ясоїдам.',
      ],
      why: [
        'Plant proteins are slightly less digestible and have less leucine, so a bit more total and a mix of sources makes up for it.',
        'Рослинний білок трохи гірше засвоюється й має менше лейцину, тож трохи більша кількість і різні джерела це компенсують.',
      ],
    },
  },

  cheat_meal: {
    ex: [
      'is a cheat meal ok',
      'i ate pizza, did i ruin my diet',
      'cheat day once a week',
      'i binged on junk food yesterday',
      'fast food after the gym, bad?',
      'does one cheat meal ruin progress',
      'should i do cardio after a cheat meal',
      'i blew my diet this weekend',
      'can i have a cheat day on a cut',
      'burger and fries, am i done',
      'ate way too much at a party',
      'how to get back on track after a cheat meal',
      'is a refeed the same as a cheat day',
      'junk food and gains',
    ],
    exUk: [
      'читміл можна',
      'з’їв піцу, все зіпсував',
      'читдей раз на тиждень',
      'вчора зірвався на фастфуд',
      'фастфуд після залу, погано',
      'один читміл зіпсує прогрес',
      'треба кардіо після зриву',
      'на вихідних зірвався з дієти',
      'можна читдей на сушці',
      'об’ївся на святі',
      'як повернутися після зриву',
      'шкідлива їжа і м’язи',
      'наївся бургерів, все пропало',
      'сорвался на пиццу что делать',
      'читмил раз в неделю можно',
    ],
    facets: {
      should: [
        'Yes, occasionally. One big meal won’t undo a week.',
        'Так, інколи можна. Один щедрий прийом не зіпсує тижня.',
      ],
      how: [
        'Enjoy it, then get back to normal at the next meal. No skipping meals or punishment cardio.',
        'Насолоджуйся й повертайся до звичного з наступного прийому. Без пропуску їжі й «покарання» кардіо.',
      ],
      why: [
        'Progress depends on weeks of eating, and a single meal barely moves that; the scale jump next day is mostly water.',
        'Прогрес залежить від тижнів харчування, а один прийом майже нічого не змінює; стрибок на вагах наступного дня — здебільшого вода.',
      ],
    },
  },

  sugar: {
    ex: [
      'is sugar bad for gains',
      'can i eat sweets and still lose fat',
      'chocolate on a diet',
      'should i cut out sugar',
      'dessert after dinner ok',
      'does sugar make you fat',
      'candy during training',
      'i have a sweet tooth, what do i do',
      'sugar before a workout',
      'is fruit sugar bad',
      'how much sugar is too much',
      'sweets on a bulk',
      'quit sugar completely?',
      'gummy bears after lifting',
    ],
    exUk: [
      'цукор шкідливий для м’язів',
      'можна їсти солодке і худнути',
      'шоколад на дієті',
      'чи відмовитися від цукру',
      'десерт після вечері можна',
      'від цукру товстіють',
      'цукерки під час тренування',
      'дуже люблю солодке, що робити',
      'солодке перед тренуванням',
      'скільки цукру забагато',
      'солодке на масі',
      'повністю кинути цукор',
      'мармеладки після залу',
      'сахар вреден для похудения',
      'можно ли сладкое на сушке',
    ],
    facets: {
      what: [
        'Sugar isn’t poison; it’s easy calories that are simple to overeat.',
        'Цукор — не отрута, а легкі калорії, яких просто переїсти.',
      ],
      should: [
        'No need to ban it: keep most of your food whole and fit sweets into your calories.',
        'Забороняти не треба: здебільшого їж цільну їжу, а солодке вписуй у калорії.',
      ],
      when: [
        'Around training is the best spot; a little sugar before or during a long session can even help.',
        'Найкраще — навколо тренування; трохи цукру до чи під час довгого тренування навіть допомагає.',
      ],
      howMuch: [
        'General guidance is to keep added sugar under about 10% of daily calories.',
        'Загальна рекомендація — доданого цукру не більше ~10% денних калорій.',
      ],
    },
  },

  late_eating: {
    ex: [
      'is eating late at night bad',
      'can i eat before bed',
      'does eating at night make you fat',
      'late dinner and fat loss',
      'food before sleep after an evening workout',
      'should i stop eating after 6 pm',
      'midnight snack ok',
      'eating right before bed and muscle',
      'is a late meal bad for sleep',
      'casein before bed',
      "i'm hungry at night, can i eat",
      'evening meals on a cut',
      'last meal how late',
      'cottage cheese before sleep',
    ],
    exUk: [
      'їсти пізно ввечері шкідливо',
      'можна їсти перед сном',
      'від їжі на ніч товстіють',
      'пізня вечеря і схуднення',
      'не їсти після 6 вечора треба',
      'перекус вночі норм',
      'їжа перед сном і м’язи',
      'пізня їжа заважає сну',
      'казеїн на ніч',
      'вночі голодний, можна поїсти',
      'сир перед сном',
      'їсти після вечірнього тренування пізно',
      'на ночь есть вредно',
      'можно ли кушать перед сном',
    ],
    facets: {
      should: [
        'Yes, eating late is fine; the day’s total decides weight, not the clock.',
        'Так, їсти пізно — нормально; вагу визначає загальна кількість за день, а не годинник.',
      ],
      what: [
        'A protein-rich meal before bed, like cottage cheese or yoghurt, is even useful for recovery.',
        'Білкова вечеря перед сном, як-от сир чи йогурт, навіть корисна для відновлення.',
      ],
      why: [
        'The “no food after 6 pm” rule works only because it cuts calories; timing itself doesn’t add fat.',
        'Правило «не їсти після 18:00» працює лише тому, що зменшує калорії; сам час не додає жиру.',
      ],
      howMuch: [
        'Keep it moderate so it doesn’t ruin sleep; a very large or heavy meal right before bed can.',
        'Помірна порція, щоб не зіпсувати сон; дуже велика чи важка їжа перед сном може заважати.',
      ],
    },
  },

  electrolytes: {
    ex: [
      'do i need electrolytes',
      'should i add salt to my water',
      'magnesium for lifting',
      'sodium before a workout',
      'potassium for cramps',
      'electrolyte drinks worth it',
      'i sweat a lot, do i need salt',
      'training in the heat and electrolytes',
      'salt for better pumps',
      'should i supplement magnesium',
      'sports drinks during the gym',
      'am i low on sodium',
      'electrolyte powder yes or no',
      'salt in the pre workout drink',
    ],
    exUk: [
      'чи потрібні електроліти',
      'додавати сіль у воду',
      'магній для тренувань',
      'натрій перед тренуванням',
      'калій від судом',
      'ізотоніки мають сенс',
      'сильно пітнію, треба сіль',
      'тренування в спеку і електроліти',
      'сіль для пампу',
      'пити магній чи ні',
      'спортивні напої в залі',
      'електроліти в порошку потрібні',
      'нужны ли электролиты',
      'магний для спортсменов',
    ],
    facets: {
      who: [
        'Mostly heavy sweaters and people training over 90 minutes in the heat; for others normal food covers it.',
        'Здебільшого тим, хто сильно пітніє або тренується понад 90 хвилин у спеку; іншим вистачає звичайної їжі.',
      ],
      how: [
        'A pinch of salt in your water bottle is usually enough.',
        'Зазвичай вистачає дрібки солі в пляшку води.',
      ],
      why: [
        'Sweat loses sodium; replacing it helps pumps, performance and prevents cramps.',
        'З потом виходить натрій; його поповнення допомагає пампу, результату й запобігає судомам.',
      ],
      should: [
        'Most people don’t need electrolyte products. With a heart, kidney or blood pressure condition, ask a doctor before adding salt.',
        'Більшості спеціальні електроліти не потрібні. При хворобах серця, нирок чи тиску — спитай лікаря, перш ніж додавати сіль.',
      ],
    },
  },

  fiber: {
    ex: [
      'how much fiber should i eat',
      'do i need vegetables to build muscle',
      'fibre intake per day',
      "i don't eat veggies, is that bad",
      'fruit on a cut',
      'best sources of fiber',
      'how many vegetables a day',
      'fiber for digestion on a bulk',
      'is fruit too much sugar',
      'high fiber foods for lifters',
      'veggies keep me full on a diet',
      'should i eat fruit after training',
      'grams of fibre daily',
      'bloated on a bulk, fiber?',
    ],
    exUk: [
      'скільки клітковини потрібно',
      'чи треба овочі для м’язів',
      'норма клітковини на день',
      'я не їм овочів, це погано',
      'фрукти на сушці',
      'найкращі джерела клітковини',
      'скільки овочів на день їсти',
      'клітковина для травлення на масі',
      'продукти з клітковиною',
      'овочі допомагають не голодувати на дієті',
      'фрукти після тренування',
      'грамів клітковини щодня',
      'на масі проблеми з травленням',
      'сколько клетчатки нужно',
      'овощи для набора массы нужны',
    ],
    facets: {
      howMuch: ['About 25–35 g of fibre a day.', 'Приблизно 25–35 г клітковини на день.'],
      how: [
        'Vegetables at two meals, some fruit, oats and beans cover it.',
        'Овочі у двох прийомах, фрукти, вівсянка й бобові — і норма є.',
      ],
      why: [
        'Fibre keeps you full on a cut and keeps digestion in order on a bulk.',
        'Клітковина тримає ситість на схудненні, а на наборі — травлення в порядку.',
      ],
      what: [
        'Fibre is the part of plant food you don’t digest: vegetables, fruit, whole grains, beans, nuts.',
        'Клітковина — частина рослинної їжі, яка не перетравлюється: овочі, фрукти, цільні злаки, бобові, горіхи.',
      ],
    },
  },

  // ---------------------------------------------------------------- smalltalk
  whats_up: {
    ex: [
      "what's up",
      'sup',
      'wassup',
      "what's new",
      'whats up atlas',
      'sup bro',
      "what's new with you",
      'anything new',
      "yo what's up",
      "what's going on",
      "what's happening",
      "what's the news",
      "how's life",
      'what are you up to',
    ],
    exUk: [
      'що нового',
      'як воно',
      'шо там',
      'що там',
      'як життя',
      'шо нового',
      'як ся маєш, що нового',
      'ну шо там у тебе',
      'що новенького',
      'як справи, що там',
      'шо робиш',
      'як воно нічого',
      'что нового',
      'как жизнь',
    ],
  },

  good_night: {
    ex: [
      'good night',
      'goodnight atlas',
      'night night',
      'going to bed',
      'off to bed',
      "i'm going to sleep",
      'time for bed',
      'heading to bed now',
      'sleep time',
      'gonna crash, night',
      'night',
      'calling it a night',
      "i'm off to sleep",
      'bedtime for me',
    ],
    exUk: [
      'на добраніч',
      'добраніч',
      'спокійної ночі',
      'йду спати',
      'я спати',
      'пішов спати',
      'пора спати',
      'лягаю спати',
      'все, я спатки',
      'солодких снів',
      'доброї ночі',
      'бувай, йду спати',
      'спокойной ночи',
      'иду спать',
    ],
  },

  tired: {
    ex: [
      "i'm tired",
      'so exhausted today',
      'no energy',
      'i feel drained',
      "i'm wiped out",
      'feeling sleepy',
      'zero energy right now',
      "i'm dead tired",
      "i'm too tired to train",
      'completely exhausted after work',
      "i'm running on empty",
      'barely slept, so tired',
      'i feel sluggish',
      'tired af',
    ],
    exUk: [
      'я втомився',
      'я втомилась',
      'нема сил',
      'немає сил',
      'я виснажений',
      'сонний сьогодні',
      'втома жахлива',
      'дуже втомився після роботи',
      'сил нуль',
      'я як вижатий лимон',
      'не виспався, втомлений',
      'сьогодні нема енергії',
      'я устал',
      'нет сил вообще',
    ],
  },

  bored: {
    ex: [
      "i'm bored",
      'so bored',
      'this is boring',
      'training is getting boring',
      'bored of my workouts',
      "i'm bored, entertain me",
      'boring day',
      'nothing to do, bored',
      'gym feels boring lately',
      'same routine is boring',
      'bored out of my mind',
      'my program is boring',
      "give me something, i'm bored",
      'bored af',
    ],
    exUk: [
      'мені нудно',
      'нудно',
      'нудьга',
      'тренування набридли, нудно',
      'нудно в залі',
      'нудно, розваж мене',
      'нудний день',
      'мені скучно',
      'та ну нудно все',
      'одне й те саме, нудно',
      'програма нудна',
      'нудьгую',
      'скучно',
      'скука смертная',
    ],
  },

  challenge: {
    ex: [
      'give me a challenge',
      'challenge me',
      'dare me',
      'any challenge for this week',
      'i want a challenge',
      'set me a challenge',
      "what's today's challenge",
      'throw me a challenge',
      'give me something hard to beat',
      'i need a new challenge',
      'weekly challenge please',
      'challenge accepted, what is it',
      'gym challenge for me',
      'dare me to do something',
    ],
    exUk: [
      'кинь виклик',
      'дай челендж',
      'хочу челендж',
      'дай мені виклик',
      'який виклик на цей тиждень',
      'челендж на тиждень',
      'придумай мені челендж',
      'дай завдання, щоб було важко',
      'виклик прийнято, що робити',
      'кинь мені якийсь челендж',
      'хочу новий виклик',
      'челендж для залу',
      'дай челлендж',
      'брось мне вызов',
    ],
  },

  fun_fact: {
    ex: [
      'tell me a fun fact',
      'fun fact',
      'tell me something interesting',
      'did you know anything cool',
      'random fact please',
      'give me a fitness fact',
      'something interesting about muscles',
      'teach me something new',
      'share a cool fact',
      'any interesting facts',
      'i want to learn a fact',
      "tell me something i don't know",
      'surprise me with a fact',
      'gym fact',
    ],
    exUk: [
      'розкажи цікавий факт',
      'цікавий факт',
      'розкажи щось цікаве',
      'факт про м’язи',
      'дай якийсь факт',
      'розкажи щось, чого я не знаю',
      'цікавинка про фітнес',
      'здивуй мене фактом',
      'знаєш щось цікаве',
      'хочу цікавий факт',
      'розкажи щось нове',
      'факт дня',
      'расскажи интересный факт',
      'расскажи что-нибудь интересное',
    ],
  },

  quote: {
    ex: [
      'give me a quote',
      'motivational quote',
      'inspire me',
      'share some wisdom',
      'quote of the day',
      'i need inspiration',
      'a famous quote about strength',
      'words of wisdom please',
      'inspirational quote',
      'any good quotes',
      'say something wise',
      'gym quote',
      'a quote to get me going',
      'give me some wisdom',
    ],
    exUk: [
      'дай цитату',
      'мотиваційна цитата',
      'надихни мене',
      'скажи щось мудре',
      'цитата дня',
      'потрібне натхнення',
      'цитата про силу',
      'мудрі слова',
      'надихаюча цитата',
      'якусь цитату для залу',
      'поділись мудрістю',
      'кинь цитатку',
      'вдохнови меня',
      'дай цитату про спорт',
    ],
  },

  laugh: {
    ex: [
      'lol',
      'haha',
      'hahaha',
      'lmao',
      'haha nice',
      'lol good one',
      "that's funny",
      'rofl',
      'hah',
      'lmao true',
      'haha okay',
      "lol you're funny",
      'hahaha love it',
      'lol ok',
    ],
    exUk: [
      'хаха',
      'ахах',
      'ахаха',
      'хахаха',
      'ржу',
      'кек',
      'смішно',
      'ахах класно',
      'хаха добре',
      'ржу не можу',
      'лол',
      'ахаха жиза',
      'хах ну ти даєш',
      'угар',
    ],
  },

  mood_down: {
    ex: [
      "i'm sad",
      'i feel depressed',
      'bad day',
      'i had an awful day',
      "i'm upset",
      'feeling down today',
      'i feel low',
      'not in a good mood',
      'everything is going wrong',
      'i feel terrible',
      'today was rough',
      "i'm feeling blue",
      'life sucks right now',
      "i'm in a bad place mentally",
      'feeling really low lately',
    ],
    exUk: [
      'мені сумно',
      'мені погано',
      'поганий день',
      'кепсько на душі',
      'настрій нуль',
      'я пригнічений',
      'все йде не так',
      'жахливий день',
      'мені зле на душі',
      'якось сумно сьогодні',
      'депресняк',
      'паршивий настрій',
      'хреново мені',
      'мне грустно',
      'плохое настроение',
    ],
  },

  mood_up: {
    ex: [
      'i feel great',
      'great day today',
      'feeling amazing',
      "i'm happy",
      'awesome day',
      'feeling great today',
      "i'm in a great mood",
      'life is good',
      'best day ever',
      'feeling fantastic',
      "i'm so pumped today",
      'i feel awesome',
      'on top of the world',
      'super happy right now',
    ],
    exUk: [
      'мені чудово',
      'чудовий день',
      'я щасливий',
      'настрій супер',
      'кайфовий день',
      'почуваюся круто',
      'класний настрій',
      'все супер',
      'у мене прекрасний день',
      'я на підйомі',
      'настрій огонь',
      'сьогодні просто кайф',
      'отлично себя чувствую',
      'прекрасное настроение',
    ],
  },

  lets_go: {
    ex: [
      "let's go",
      'lets go',
      'lesgo',
      'go go',
      "let's do this",
      "let's get it",
      "let's gooo",
      "ready, let's go",
      'time to go',
      "let's roll",
      'go time',
      "let's get to work",
      "come on let's go",
      'lfg',
    ],
    exUk: [
      'погнали',
      'поїхали',
      'вперед',
      'го',
      'го го',
      'давай погнали',
      'ну шо, погнали',
      'поїхали працювати',
      'до бою',
      'починаємо',
      'всьо, погнали',
      'го в зал',
      'поехали',
      'погнали уже',
    ],
  },

  nothing: {
    ex: [
      'nothing',
      'never mind',
      'nevermind',
      'just because',
      'no reason',
      'nm',
      'forget it',
      'nothing really',
      "it's nothing",
      'just checking',
      "doesn't matter",
      'ignore that',
      'nah nothing',
      'just saying hi, nothing',
    ],
    exUk: [
      'нічого',
      'просто так',
      'та нічо',
      'неважливо',
      'забудь',
      'та нічого',
      'не зважай',
      'та просто',
      'нічо, проїхали',
      'проїхали',
      'нічого такого',
      'та ні, нічого',
      'ничего',
      'просто',
    ],
  },

  rival_ai: {
    ex: [
      'are you better than chatgpt',
      'chatgpt is smarter than you',
      'why not just ask gpt',
      'gemini said something different',
      'siri can do this',
      'are you like alexa',
      'claude vs you',
      'copilot gave me a better answer',
      'is chatgpt a better coach',
      "i'll just ask chatgpt",
      "what's the difference between you and gpt",
      'are you using chatgpt',
      'gpt told me to do more sets',
      'you vs gemini',
    ],
    exUk: [
      'ти кращий за чатжпт',
      'чатжпт розумніший за тебе',
      'краще спитаю в гпт',
      'gemini сказав інакше',
      'сірі таке вміє',
      'ти як алекса',
      'чим ти відрізняєшся від chatgpt',
      'ти працюєш на гпт',
      'chatgpt кращий тренер',
      'гпт порадив інше',
      'claude чи ти',
      'copilot відповів краще',
      'ты лучше чем чатгпт',
      'спрошу лучше у chatgpt',
    ],
  },

  atlas_age: {
    ex: [
      'how old are you',
      "what's your age",
      'your age?',
      'how old is atlas',
      'when were you born',
      'are you old',
      'are you young',
      'what year were you made',
      'how long have you existed',
      'age?',
      'how old are you atlas',
      "what's your birthday",
      'tell me your age',
      'are you a baby ai',
    ],
    exUk: [
      'скільки тобі років',
      'скільки тобі',
      'який твій вік',
      'коли ти народився',
      'ти старий',
      'ти молодий',
      'скільки років атласу',
      'коли тебе створили',
      'який у тебе вік',
      'коли твій день народження',
      'давно ти існуєш',
      'скільки тобі рочків',
      'сколько тебе лет',
      'какой у тебя возраст',
    ],
  },

  atlas_sleep: {
    ex: [
      'do you sleep',
      'do you ever sleep',
      'you ever sleep',
      'when do you sleep',
      "don't you get tired",
      'are you always awake',
      'do you rest',
      'do you need sleep',
      'are you up all night',
      'do you take naps',
      'does atlas sleep',
      'do you dream',
      'you never sleep, right',
      'how much do you sleep',
    ],
    exUk: [
      'ти спиш',
      'ти коли спиш',
      'ти взагалі спиш',
      'ти не втомлюєшся',
      'ти завжди не спиш',
      'тобі потрібен сон',
      'ти відпочиваєш',
      'ти всю ніч не спиш',
      'атлас спить',
      'тобі сняться сни',
      'скільки ти спиш',
      'ти колись спиш',
      'ты спишь',
      'ты вообще спишь',
    ],
  },

  atlas_eat: {
    ex: [
      'what do you eat',
      'do you eat',
      "what's your diet",
      'your diet?',
      'do you eat protein',
      "what's your favourite food",
      'are you hungry',
      'do you ever eat',
      'what does atlas eat',
      'do you count macros',
      'what did you have for lunch',
      'do you like pizza',
      'do you need food',
      "what's for your dinner",
    ],
    exUk: [
      'що ти їси',
      'ти їси',
      'яка в тебе дієта',
      'твоя улюблена їжа',
      'ти голодний',
      'ти взагалі їси',
      'що їсть атлас',
      'ти рахуєш макроси',
      'що ти їв на обід',
      'ти любиш піцу',
      'тобі потрібна їжа',
      'шо ти їси взагалі',
      'что ты ешь',
      'ты кушаешь',
    ],
  },

  sing_poem: {
    ex: [
      'sing me a song',
      'write a poem',
      'can you rap',
      'sing something',
      'tell me a poem',
      'dance for me',
      'write me a gym poem',
      'can you sing',
      'drop a rap verse',
      'make up a song about lifting',
      'a short poem please',
      'do a little dance',
      'rhyme something for me',
      'compose a song',
    ],
    exUk: [
      'заспівай пісню',
      'напиши вірш',
      'зачитай реп',
      'заспівай щось',
      'розкажи вірш',
      'потанцюй',
      'танцюй',
      'вірш про зал',
      'ти вмієш співати',
      'придумай пісню про штангу',
      'короткий віршик',
      'зарифмуй щось',
      'спой песню',
      'напиши стих',
    ],
  },

  clock: {
    ex: [
      'what time is it',
      'time?',
      "what's the time",
      'what time is it now',
      'tell me the time',
      'current time',
      'what time is it right now',
      'got the time',
      'do you know what time it is',
      'time please',
      'what hour is it',
      'check the time',
      'time now',
      "what's the time atlas",
    ],
    exUk: [
      'котра година',
      'скільки часу',
      'котра зараз година',
      'скажи котра година',
      'скільки зараз часу',
      'поточний час',
      'котра година зараз',
      'підкажи час',
      'знаєш котра година',
      'скільки там часу',
      'шо по часу',
      'яка зараз година',
      'который час',
      'сколько времени',
    ],
  },

  which_day: {
    ex: [
      'what day is it',
      "what's the date",
      'what date is it today',
      "today's date",
      'what day of the week is it',
      "what's today's date",
      'is it monday',
      "what's the date today",
      'which day is it today',
      'what month is it',
      'tell me the date',
      "what's the day today",
      'date?',
      'current date',
    ],
    exUk: [
      'який сьогодні день',
      'яке сьогодні число',
      'яке число',
      'який день тижня',
      'сьогоднішня дата',
      'яке сьогодні число і місяць',
      'сьогодні понеділок',
      'яка сьогодні дата',
      'скажи дату',
      'який зараз місяць',
      'шо сьогодні за день',
      'яке число сьогодні',
      'какой сегодня день',
      'какое сегодня число',
    ],
  },

  you_dumb: {
    ex: [
      "you're dumb",
      "that's stupid",
      "you're useless",
      "you didn't understand",
      "you don't get it",
      'wrong answer',
      'not what i asked',
      "that's not what i meant",
      'you misunderstood me',
      'that makes no sense',
      "you're not helping",
      'that answer is wrong',
      'are you even listening',
      "try again, that's not it",
      'you missed the point',
    ],
    exUk: [
      'ти тупий',
      'ти дурний',
      'ти не зрозумів',
      'не те',
      'не про те',
      'я не це питав',
      'не та відповідь',
      'ти мене не зрозумів',
      'від тебе ніякої користі',
      'це взагалі не про те',
      'маячня якась',
      'ти не в темі',
      'не то',
      'ты тупой',
      'бесполезный бот',
    ],
  },
};
