/** Extra paraphrases for the partB topics (more diverse wording for retrieval). */
export const KB_B2: Record<string, { ex: string[]; exUk: string[] }> = {
  injury_status: {
    ex: [
      'rehab check',
      "how's the shoulder recovery tracking",
      'is my knee still flagged as injured',
      'what rehab phase is my hamstring in right now',
      'am i out of the protect stage yet',
      'my back injury, where does it stand',
      'how close am i to being cleared',
      'has my elbow moved to the next rehab step',
      'injury progress report please',
      'still stuck in stage one with my wrist?',
      'tell me how far my ankle rehab has come',
      'which of my injuries are still open',
      'is the tweaked hip still listed',
      'rehab stage for my lower back',
      'when do i graduate to the next phase of rehab',
      'my injured shoulder: current stage?',
      'did my last check-in move me up a stage',
      'am i fully cleared from the knee injury yet',
      "how's my injury tracker looking",
      "where's my rehab at",
      'what does my injury log say about my progress',
      'list my current injuries and their stages',
      'how many more good check-ins do i need for my shoulder',
      'is the groin strain still active in my profile',
      'give me an update on the injured knee',
    ],
    exUk: [
      'як там моє плече по реабілітації, який етап',
      'травма коліна ще висить активною?',
      'на якому кроці відновлення моя спина',
      'мене вже можна знімати з реабілітації?',
      'скільки ще до повного відновлення ліктя',
      'яка стадія в мого зап’ястя зараз',
      'чи перейшов я на наступну фазу після останньої відмітки',
      'покажи, які травми в мене зараз відкриті',
      'що з моїм гомілкостопом по етапах реабілітації',
      'я ще в фазі захисту чи вже ні?',
      'звіт по травмі',
      'реабілітація — де я зараз',
      'травмоване коліно вже закрите?',
      'як далеко просунулась реабілітація стегна',
      'скільки гарних відміток лишилось до наступної стадії',
      'коли мене переведуть на наступний етап реабілітації',
      'в якому стані мої травми за трекером',
      'потягнутий задній м’яз стегна ще активний у профілі?',
      'плече вже відновилось чи ще ні по етапах?',
      'шо там з реабілітацією спини, рухається?',
      'мою травму вже зняли?',
      'статус реабілітації по нозі',
      'какая стадия восстановления у моего плеча',
      'травма еще активна у меня?',
      'сколько еще отметок до следующего этапа',
    ],
  },
  overtraining: {
    ex: [
      'i feel beat up every single week',
      "my body's been wrecked for a month straight",
      'resting heart rate is up and my lifts are tanking, too much training?',
      "i'm dreading every session lately",
      'joints ache all the time since i upped my volume',
      'am i overcooked',
      'fried',
      'overreached?',
      'i train twice a day and feel like garbage',
      "can't shake this constant fatigue since i added more sets",
      'my motivation and my numbers are both dropping off a cliff after months of grinding',
      'is 30 sets for chest a week overkill',
      'how much training is too much',
      'i might be running myself into the ground in the gym',
      'irritable, sleeping badly and getting weaker, is it overtraining',
      'trained hard every day for 3 weeks and now everything feels flat',
      'is my program too much for me to recover from',
      'cns fatigue is killing me',
      'i never feel fresh anymore since i ramped up my training',
      "red flags that i'm doing too much volume",
      'does my weekly workload look excessive',
      'i keep getting run down and my lifts stall, too much gym?',
      'am i past my recoverable volume',
      'pushing hard 7 days a week, am i overdoing it',
      "overdoing the volume and now i'm cooked",
    ],
    exUk: [
      'кожного тижня почуваюсь розбитим',
      'я себе загнав тренуваннями',
      'місяць уже весь як побитий, це перетрен?',
      'не хочеться йти в зал, сили падають, може я переборщив',
      'суглоби ниють, відколи додав обсягу',
      'перегорів від заліза',
      'перетрен',
      'тренуюсь двічі на день і почуваюсь як вичавлений лимон',
      '30 сетів на груди за тиждень — не перебір?',
      'скільки тренувань це вже занадто',
      'пульс у спокої виріс і сила падає, я перетренувався?',
      'постійна втома, відколи додав підходів',
      'дратівливий, погано сплю і слабшаю — це перетренованість?',
      'три тижні пахав щодня, і тепер все як вата',
      'моя програма не занадто важка для відновлення?',
      'нервова система, здається, виснажена від тренувань',
      'взагалі не відчуваю себе свіжим уже кілька тижнів інтенсивних тренувань',
      'тренуюсь сім днів на тиждень, не перегинаю?',
      'чи не перевищую я обсяг, з якого можу відновитись',
      'мене вже тіпає від залу, походу перебрав',
      'переборщив з обсягом за останні тижні, організм не вивозить',
      'як відрізнити перетренованість від звичайної втоми',
      'постійно розбитий після залу, може це перетрен',
      'я себя загнал тренировками',
      'перетренировался наверное, постоянно разбитый',
    ],
  },
  train_sore: {
    ex: [
      'quads still wrecked from monday, leg day again today?',
      'can barely walk down stairs, should i still hit legs',
      'doms',
      'lifting on sore muscles, yes or no',
      'my chest is tender from bench, ok to press again',
      "is it fine to train a muscle that's still aching from last time",
      'back is stiff and sore from rows, pull day anyway?',
      'does training sore slow down growth',
      'delayed onset soreness, keep going with the plan?',
      'glutes are killing me after hip thrusts, gym tomorrow?',
      'should soreness stop me from working out',
      'sore arms, can i still do push-ups',
      "is it smart to hit a body part that hasn't stopped aching",
      "i'm stiff all over after yesterday's session, go or skip",
      'muscles feel tight and achy, will training make it worse',
      "still feel yesterday's workout, lift again?",
      'how sore is too sore to train',
      'legs feel like bricks from squats, should i train today',
      'shoulders sore after ohp, can i do upper body',
      'working through soreness vs taking the day off',
      'sore calves, can i still train calves today',
      'gym while achy from the last workout?',
      'does moving help doms or should i rest the sore muscle',
      'my lats are sore from pull-ups, pull day again?',
      'is it counterproductive to train sore',
    ],
    exUk: [
      'квадрицепси ще забиті з понеділка, знову ноги сьогодні?',
      'ледве спускаюсь по сходах, йти на ноги?',
      'крепатура',
      'тренуватись на забитих м’язах — так чи ні',
      'груди ниють після жиму, можна знову жати?',
      'чи нормально качати м’яз, який ще болить з минулого разу',
      'спина забита після тяг, тягова все одно?',
      'тренування на крепатурі гальмує ріст?',
      'сідниці болять після ягодичного мосту, завтра в зал?',
      'чи має крепатура мене зупиняти',
      'руки болять, віджиматись можна?',
      'все тіло ломить після вчорашнього тренування, йти чи ні',
      'наскільки сильна має бути крепатура, щоб пропустити',
      'ноги як дерев’яні після присідів, тренуватись сьогодні?',
      'плечі болять після армійського жиму, можна верх?',
      'крепатура не пройшла, продовжувати програму?',
      'рух допомагає від крепатури чи дати м’язу спокій',
      'найширші болять після підтягувань, знову спина?',
      'ще відчуваю вчорашнє тренування, знову тягати?',
      'литки болять, можна сьогодні знову на литки',
      'м’язи ниють, зал не зробить гірше?',
      'з забитими ногами на трєню норм?',
      'після вчорашнього все болить, в зал чи відлежатись',
      'мышцы забиты после вчерашнего, можно снова тренить?',
      'крепатура сильная, тренироваться или отдыхать',
    ],
  },
  weaker_today: {
    ex: [
      'bar felt like a ton today',
      'why was everything so hard today',
      'missed my bench triple that i hit easily last week',
      'zero pop in my lifts today',
      'my warmups felt like max attempts',
      'strength just vanished this session',
      'rough session, weights felt glued to the floor',
      'why did 100 kg feel like 130 today',
      'today i was noticeably weaker, what happened',
      'felt flat and weak at the gym',
      'had to drop the weight mid-workout, i was so weak',
      'is it normal to have random weak days',
      'squat moved like molasses today',
      "didn't get my reps on overhead press today for some reason",
      'bad day, lost 2 reps on every set',
      'weak as a kitten today',
      'the dumbbells felt twice as heavy this morning',
      "why do some days i'm strong and others i'm not",
      "today's session was way below my normal numbers",
      "deadlift wouldn't budge off the floor today",
      'i felt so weak in the gym today',
      'one bad workout where nothing moved, should i worry',
      'my strength was off today',
      'why am i randomly weaker this session',
      'barely got through sets i normally crush',
    ],
    exUk: [
      'штанга сьогодні як бетонна',
      'чого все так важко йшло сьогодні',
      'не взяв жим на три, хоча минулого тижня йшло легко',
      'розминочні ваги сьогодні як максималки',
      'сила кудись поділась на цьому тренуванні',
      'чому 100 кг сьогодні як 130',
      'сьогодні помітно слабший, що сталось',
      'довелось скинути вагу посеред тренування, сил не було',
      'це нормально, що бувають такі дохлі дні?',
      'присід сьогодні повз як черепаха',
      'станова сьогодні від підлоги не відривалась',
      'поганий день, на кожному сеті мінус два повтори',
      'гантелі сьогодні ніби вдвічі важчі',
      'чому одного дня я сильний, а іншого ні',
      'сьогодні сили як у кошеняти',
      'армійський жим не пішов сьогодні, не знаю чого',
      'сьогодні сильно нижче своїх звичних цифр',
      'ледве дотягнув підходи, які зазвичай роблю легко',
      'одне погане тренування, нічого не йшло, це страшно?',
      'сьогодні я якийсь ватний у залі',
      'чого я сьогодні такий слабкий',
      'не мій день, ваги не рухались',
      'сегодня штанга как чугунная',
      'почему сегодня всё тяжело шло',
      'сегодня даже разминка казалась тяжелой',
    ],
  },
  split_choice: {
    ex: [
      'arnold split any good',
      'upper/lower or ppl for 5 days',
      'should i hit each muscle twice a week with a split or do full body',
      'chest day, back day, arms day: is that outdated',
      'how do i organize my week by muscle group',
      'full body three times or a 4-day upper lower',
      'which split gives the best gains',
      'push pull legs vs bro split',
      'is a 5 day bro split good for naturals',
      'torso/limbs split thoughts',
      'help me pick between ppl and full body',
      'do i train legs on their own day or with upper body',
      'split recommendation for a busy dad training 3x',
      'best way to divide chest, back, legs, shoulders and arms over the week',
      'ppl run once or twice through the week',
      'which routine structure suits hypertrophy best, splits or full body',
      'what should each day focus on in a 4 day split',
      "i'm confused about splits",
      'phul or phat',
      'should i group chest and triceps together',
      'splits',
      'is training by body part better than full body sessions',
      'anterior posterior split, is it legit',
      "what's the smartest split for strength",
      'my gym bro says full body is for beginners only, true?',
    ],
    exUk: [
      'арнольдівський спліт норм?',
      'верх-низ чи ppl, якщо ходжу 5 днів',
      'груди-спина-руки по днях — це вже застаріло?',
      'як розкидати м’язові групи на тиждень',
      'тричі фулбоді чи чотири дні верх-низ',
      'який спліт дає найкращий приріст',
      'пуш-пул-легс проти класичного бро-спліту',
      'допоможи вибрати між ppl і фулбоді',
      'ноги окремим днем чи разом з верхом',
      'як поділити груди, спину, ноги, плечі й руки по тижню',
      'груди з трицепсом в один день ставити?',
      'качати по групах чи все тіло за раз — що дає більше',
      'спліт для сили який найрозумніший',
      'кажуть, фулбоді тільки для новачків, це правда?',
      'плутаюсь у сплітах',
      'що робити в кожен день, якщо спліт на 4 дні',
      'дводенний спліт чи триденний',
      'спина з біцепсом, груди з трицепсом — нормальна схема?',
      'яку схему тренувань по днях обрати для маси',
      'бро-спліт для натурала підходить?',
      'по скільки груп м’язів брати за день',
      'який сплітик взяти на три трєні',
      'как разбить мышцы по дням',
      'какой сплит лучше для массы, ppl или верх низ',
      'фулбоди три раза или сплит на четыре дня',
    ],
  },
  exercises_per_session: {
    ex: [
      'how many movements should i fit in one day',
      'my workout has 12 exercises, is that overkill',
      'just 3 lifts per session, enough?',
      'exercise count per workout',
      "what's a sensible number of exercises for leg day",
      'how many different exercises for chest in a single session',
      'should i cut some exercises from my session',
      'is doing 2 exercises a workout too few',
      'how many exercises is too many in one go',
      'i do like 9 different things each session, bad?',
      'should i do fewer exercises with more sets',
      'how many exercises per muscle in one workout',
      '5 or 7 exercises per session',
      'cramming too many exercises into one day?',
      'how many lifts per gym visit',
      'number of lifts per day',
      'full body day, how many exercises total',
      'more exercises or more sets per exercise',
      'ideal exercise list length for an hour session',
      'is one exercise per body part enough in a session',
      'how many moves should a push day include',
      'my trainer gave me 11 exercises, too many?',
      "what's the max number of exercises per workout",
      'how many exercises for arms on arm day',
      'should every workout have 4 to 6 exercises',
    ],
    exUk: [
      'скільки рухів вміщати в одне тренування',
      'у мене 12 вправ за тренування, це перебір?',
      'лише 3 вправи за заняття — вистачить?',
      'скільки вправ на день ніг нормально',
      'скільки різних вправ на груди за одне тренування',
      'може прибрати кілька вправ з тренування',
      '2 вправи за тренування — не замало?',
      'скільки вправ уже занадто за раз',
      'роблю штук 9 різних вправ кожного разу, погано?',
      'менше вправ, але більше підходів — так краще?',
      'скільки вправ на один м’яз за тренування',
      '5 чи 7 вправ за тренування',
      'скільки вправ на фулбоді загалом',
      'тренер дав 11 вправ, це не забагато?',
      'максимум вправ за одне заняття скільки',
      'скільки вправ ставити в день рук',
      'одна вправа на групу м’язів за тренування — достатньо?',
      'скільки вправ у пуш-день',
      'на годину тренування скільки вправ брати',
      'напхав купу вправ в одне тренування, це норм?',
      'скільки штук вправ робити за раз',
      'яка кількість вправ за заняття оптимальна',
      'сколько упражнений на одну тренировку нормально',
      '12 упражнений за раз это много?',
      'сколько упражнений на ноги за тренировку',
    ],
  },
  compound_isolation: {
    ex: [
      'big lifts vs small lifts',
      'are bicep curls pointless if i do chin-ups',
      'should i bother with lateral raises or just press',
      'multi-joint movements explained',
      'is bench enough for triceps or do i need pushdowns',
      "what's the point of single-joint exercises",
      'leg extensions, useful or fluff',
      'only compounds, will my arms still grow',
      'should isolation come at the end of the workout',
      'is a squat a compound or isolation move',
      'accessory work vs main lifts',
      "do i need flyes if i'm already benching",
      'compound lifts only program, good idea?',
      'which exercises work several muscles at once',
      'curls and extensions or just heavy basics',
      'why do people say compounds are king',
      'isolation movements or more compounds for size',
      'is a leg curl isolation',
      'the basics vs finishers',
      'can pull-ups replace curls',
      'compounds',
      'isolation',
      'how much isolation should i do compared to compounds',
      'are cable exercises isolation work',
      'should my program be mostly compound movements',
    ],
    exUk: [
      'великі вправи проти маленьких',
      'згинання на біцепс марні, якщо підтягуюсь?',
      'махи в сторони потрібні чи вистачить жимів',
      'багатосуглобові рухи — що це',
      'жиму лежачи вистачає на трицепс, чи ще розгинання на блоці?',
      'навіщо односуглобові вправи',
      'розгинання ніг у тренажері — корисно чи фігня',
      'тільки база, руки все одно ростимуть?',
      'ізоляцію ставити в кінець тренування?',
      'присід — це база чи ізоляція',
      'допоміжні вправи проти основних',
      'розводки потрібні, якщо я вже жму лежачи?',
      'програма тільки з базових — нормальна ідея?',
      'які вправи працюють кілька м’язів одночасно',
      'чому кажуть, що база рулить',
      'згинання ніг — це ізоляція?',
      'підтягування можуть замінити згинання на біцепс?',
      'скільки ізоляції робити порівняно з базою',
      'вправи на блоках — це ізоляція?',
      'програма має бути переважно з базових?',
      'базові вправи',
      'ізольовані вправи взагалі треба?',
      'добивочні вправи після бази мають сенс?',
      'базовые упражнения, что это',
      'изоляция нужна, если делаю базу?',
    ],
  },
  machines_free: {
    ex: [
      'is the smith machine cheating',
      'cable stack or dumbbells',
      'can i get strong using only machines',
      'pec deck vs dumbbell flyes',
      'are selectorized machines good for hypertrophy',
      'barbell purists say machines are useless, true?',
      'are machines worse for building stabilizer muscles',
      'leg press gains vs squat gains',
      'plate-loaded machines vs barbells',
      'is it fine to mostly use machines and a few dumbbells',
      'do machines make you weaker in real life',
      'hammer strength rows or barbell rows for back',
      'machines are safer than barbells, right?',
      'smith squat counts as a real squat?',
      'dumbbells or machine for shoulder press',
      'why do powerlifters avoid machines',
      'should i ditch the machines for free weights',
      'machine only workouts, will they work',
      'cables vs free weights for muscle',
      'fixed path machines vs free movement',
      'is a leg press as good as squatting',
      'machines',
      'free weights',
      'chest press machine enough for a big chest?',
      "what's better for a beginner, dumbbells or the machines",
    ],
    exUk: [
      'сміт — це читінг?',
      'кросовер чи гантелі',
      'реально стати сильним тільки на тренажерах?',
      'батерфляй чи розводка гантелей',
      'тренажери з блоками добрі для гіпертрофії?',
      'кажуть, тренажери — це для слабаків, правда?',
      'жим ногами дає стільки ж, як присід?',
      'тренажери з дисками проти штанги',
      'можна займатись в основному на тренажерах і трохи з гантелями',
      'тренажери роблять слабшим у житті?',
      'тяга в тренажері чи тяга штанги в нахилі для спини',
      'тренажери безпечніші за штангу, так?',
      'присід у сміті рахується як нормальний присід?',
      'жим на плечі гантелями чи в тренажері',
      'чому пауерліфтери не люблять тренажери',
      'кинути тренажери і перейти на вільні ваги?',
      'тренування лише на машинах — спрацює?',
      'блоки чи вільні ваги для м’язів',
      'фіксована траєкторія чи вільний рух — що краще',
      'тренажера для жиму грудей вистачить для великих грудей?',
      'залізо чи тренажери',
      'на тренажерах качатись — це несерйозно?',
      'смит или штанга для приседа',
      'на тренажерах можно накачаться?',
      'гантели или тренажеры, что лучше',
    ],
  },
  superset: {
    ex: [
      'pairing exercises back to back',
      'chest and back supersets, good idea?',
      'should i pair curls with pushdowns',
      'doing two lifts in a row with no rest between',
      'do supersets hurt strength on the main lift',
      'giant sets vs supersets',
      'how to superset in a crowded gym',
      'agonist superset or antagonist',
      'supersetting to shorten my workout',
      'combine lateral raises and face pulls as a pair?',
      'supersets',
      'is it bad to superset two leg exercises',
      'how do i structure paired sets',
      'circuits for lifting',
      'a1 a2 in my program, what does that mean',
      'how long do i wait after finishing both exercises in a pair',
      'can i superset deadlifts with anything',
      'pre-exhaust superset worth it',
      'should beginners do supersets',
      'i want to do triceps and biceps together back to back',
      'tri-set explained',
      'alternating two exercises without rest',
      'superset abs between sets of bench?',
      'do supersets give a better pump',
      'circuit style training for muscle, does it work',
    ],
    exUk: [
      'поєднувати дві вправи підряд без відпочинку',
      'суперсет груди-спина — гарна ідея?',
      'ставити біцепс у парі з трицепсом на блоці?',
      'дві вправи одна за одною без паузи — як це правильно',
      'гігантські сети чи суперсети',
      'як робити суперсети, коли в залі купа людей',
      'антагоністи в суперсеті чи на одну групу',
      'суперсетами скоротити тренування',
      'махи в сторони з тягою до обличчя в парі — норм?',
      'суперсети',
      'дві вправи на ноги суперсетом — погано?',
      'a1 a2 в програмі, що це значить',
      'скільки чекати після того, як зробив обидві вправи з пари',
      'станову можна ставити в суперсет?',
      'попереднє втомлення суперсетом — варто?',
      'новачкам можна суперсети?',
      'трисет — що це таке',
      'чергувати дві вправи без відпочинку',
      'прес між підходами жиму — суперсетом можна?',
      'суперсети дають кращий памп?',
      'кругове тренування для м’язів працює?',
      'суперсети знижують силу на основній вправі?',
      'робити вправи в парі — це як, розкажи',
      'как делать суперсеты',
      'суперсет на бицепс и трицепс норм?',
    ],
  },
  dropset: {
    ex: [
      'strip sets',
      "running the rack, what's that",
      'keep going with lighter weight after failure',
      'should i drop the weight and rep out after my top set',
      'mechanical drop sets',
      'triple drop on the cable stack',
      'drop sets vs rest-pause',
      'are drop sets too taxing',
      'drop the pin and keep repping on machines, good idea?',
      'how to set up plates for a quick drop set',
      'is stripping plates better than a normal set',
      'drop set on lateral raises, how much to drop',
      'do drop sets count as extra sets',
      'should i drop set every exercise',
      'going down the dumbbell rack after failing',
      'burnout set with lower weight at the end',
      'drop sets',
      'do drop sets save time compared to straight sets',
      'are dropsets good for beginners',
      '20 percent drop or 30 percent drop',
      'double drop set on leg press',
      'should the last set of curls be a drop set',
      'drops on the pec deck',
      'failure, reduce the load, go again: is that effective',
      'why do bodybuilders love drop sets',
    ],
    exUk: [
      'стрип-сети',
      'пробігтись по гантельному ряду вниз — що це',
      'після відмови взяти легше і добити',
      'після важкого сету скинути вагу і дожати ще',
      'механічний дропсет',
      'потрійний дроп на блоці',
      'дропсети чи відпочинок-пауза',
      'дропсети не занадто виснажують?',
      'переставити шпильку нижче і продовжити в тренажері — нормально?',
      'як підготувати млинці для швидкого дропсету',
      'знімати млинці і продовжувати краще за звичайний підхід?',
      'дропсет на махах, скільки скидати',
      'дропсет рахується як додатковий підхід?',
      'робити дропсет на кожній вправі?',
      'добивочний сет з меншою вагою в кінці',
      'дропсети',
      'дропсети підходять новачкам?',
      'скидати 20 чи 30 відсотків ваги',
      'подвійний дроп на жимі ногами',
      'дропи на батерфляї',
      'відмова, зменшив вагу, ще раз — це ефективно?',
      'чому бодібілдери так люблять дропсети',
      'дропсет економить час порівняно з простими підходами?',
      'как правильно делать дропсет',
      'сброс веса после отказа и дальше, это работает?',
    ],
  },
  rpe: {
    ex: [
      'how close to failure is rpe 7',
      "what does '2 rir' in my plan mean",
      'leave two in the tank, what does that mean',
      'rate of perceived exertion explained',
      'rpe 9.5',
      'how do i know if a set was an 8 or a 9',
      "i can't tell how many reps i have left",
      'is rpe 6 too easy for working sets',
      'rir 0',
      'effort rating',
      'why does the app ask how hard the set was',
      'what number do i put for a set that was really hard',
      'reps left in the tank scale',
      'how accurate is guessing reps in reserve',
      "my sets say @8, what's that",
      'what effort score should my top set be',
      'rpe for beginners, how to judge it',
      'does rpe 8 mean 80 percent',
      '1 rir vs 2 rir difference',
      'rpe',
      'how do i estimate how many more reps i could have done',
      'what should i enter for effort after a set',
      "rpe 7, 8, 9: what's the difference",
      'is rir the same as rpe backwards',
      'if my last rep was a grinder, what rpe is that',
    ],
    exUk: [
      'rpe 7 — наскільки близько до відмови',
      'що означає «2 rir» у плані',
      'залишити два в запасі — це як',
      'шкала суб’єктивного зусилля, поясни',
      'rpe дев’ять з половиною — це як',
      'як зрозуміти, сет був на 8 чи на 9',
      'не можу оцінити, скільки повторів ще лишилось',
      'rpe 6 не надто легко для робочих?',
      'rir нуль — це вже відмова?',
      'оцінка зусилля',
      'навіщо додаток питає, наскільки важкий був сет',
      'яку цифру ставити, якщо сет був дуже важкий',
      'наскільки точно можна вгадати повтори в запасі',
      'у мене в сетах написано @8, що це',
      'rpe 8 означає 80 відсотків?',
      'різниця між 1 rir і 2 rir',
      'як прикинути, скільки ще повторів я б зміг',
      'що вводити як зусилля після сету',
      'rpe 7, 8, 9 — в чому різниця',
      'rir — це те саме, що rpe навпаки?',
      'останній повтор ледве вичавив, це який rpe',
      'рпе це шо',
      'як новачку оцінювати rpe',
      'что значит rir',
      'rpe 8 это сколько повторов в запасе',
    ],
  },
  tempo: {
    ex: [
      'rep cadence',
      'should i pause at the bottom of each rep',
      'lowering phase speed',
      'how slow on the way down for hypertrophy',
      'do i need to control the eccentric',
      'bouncing reps vs controlled reps',
      'explode up, control down?',
      'what do the four numbers in a tempo mean',
      'is it bad to rush my reps',
      'should the concentric be fast',
      'time under tension',
      '2 seconds down 1 second up good?',
      'pause reps for muscle growth, worth it',
      'are slow negatives worth the lighter weight',
      'i do my reps super fast, is that a problem',
      'how long should i take to lower a squat',
      'tempo squats benefits',
      'speed of each repetition',
      'negatives',
      'is 40 seconds per set the magic number for growth',
      'does lifting slower make it harder in a good way',
      'should i squeeze at the top of every rep',
      'jerky fast reps vs smooth reps',
      'eccentric emphasis training',
      "what's a good rep speed for strength",
    ],
    exUk: [
      'каденція повторів',
      'робити паузу внизу кожного повтору?',
      'швидкість опускання ваги',
      'наскільки повільно опускати для гіпертрофії',
      'треба контролювати негативну фазу?',
      'відбивати чи робити підконтрольно',
      'вибухово вгору, повільно вниз — так?',
      'що означають чотири цифри в темпі',
      'погано, якщо я поспішаю з повторами?',
      'підйом має бути швидким?',
      'час під навантаженням',
      '2 секунди вниз, 1 вгору — нормально?',
      'повторення з паузою для росту — варто?',
      'повільні негативи варті меншої ваги?',
      'я роблю повтори дуже швидко, це проблема?',
      'скільки секунд опускатись у присіді',
      'темпові присідання — користь',
      'негативи',
      '40 секунд на підхід — це магічне число для росту?',
      'стискати м’яз у верхній точці кожного повтору?',
      'ривками чи плавно робити повтори',
      'акцент на ексцентрику',
      'з якою швидкістю робити повтори на силу',
      'как быстро опускать штангу',
      'темп 3-0-1-0, что значит',
    ],
  },
  warmup_sets: {
    ex: [
      'ramping sets',
      'how many build-up sets before my top set',
      'should warm-up sets be low reps',
      'empty bar first, then what',
      'percentages for ramping to a working set',
      'how many feeder sets',
      'do i warm up with sets on isolation exercises too',
      'is one warm-up set enough',
      'how much rest between warm-up sets',
      'how many jumps from the bar to my working weight',
      'my warm-up sets tire me out, doing too many?',
      'should warm-up sets be logged',
      'acclimation sets explained',
      'going straight to working weight without warm-up sets ok?',
      'if i work up to 140, what should the lighter sets be',
      'sets before working sets, how many',
      'light sets before the heavy ones',
      'how close should the last warm-up set be to working weight',
      'should i push warm-up sets hard',
      'ramp up',
      'warm-up sets for the third exercise of the day, needed?',
      'how many singles before a max attempt',
      'is it 50, 70, 90 percent for warm-ups',
      'how many light sets before working sets on a machine',
      'reps per ramp set as the weight goes up',
    ],
    exUk: [
      'скільки підвідних до топ-сету',
      'підвідні робити на малу кількість повторів?',
      'спочатку пустий гриф, а далі що',
      'відсотки для підвідних до робочої',
      'підвідні сети на ізоляцію теж треба?',
      'одного підвідного вистачить?',
      'скільки відпочивати між підвідними',
      'скільки кроків від грифа до робочої ваги',
      'підвідні мене втомлюють, роблю забагато?',
      'записувати підвідні підходи чи ні',
      'одразу на робочу вагу без підвідних — можна?',
      'якщо робоча 140, які мають бути підвідні',
      'легкі сети перед важкими, скільки',
      'наскільки близько останній підвідний до робочої',
      'підвідні треба робити важко чи легенько',
      'на третю вправу дня теж підвідні?',
      'скільки одиночок перед спробою на максимум',
      '50, 70, 90 відсотків — так робити розминочні сети?',
      'підвідні на тренажері скільки робити',
      'скільки повторів у кожному підвідному, коли вага росте',
      'підводка до робочої ваги — як',
      'розминочні підходи перед робочими, схема',
      'сколько подводящих подходов делать',
      'подводящие сеты на тренажерах нужны?',
      'как подходить к рабочему весу правильно',
    ],
  },
  stretch_before: {
    ex: [
      'static holds before squatting, good or bad',
      'does stretching pre-lift make me weaker',
      'touching my toes before deadlifts, helpful?',
      'long stretches before leg day ok?',
      'stretching routine before hitting weights',
      'is pre-workout stretching outdated',
      'leg swings or hamstring stretch before training',
      '30 second stretches before lifting hurt performance?',
      'i always stretch for 15 minutes before the gym, is that good',
      'do i need to stretch my chest before benching',
      'yoga before weights',
      'stretch or no stretch before a heavy session',
      'can static stretching before lifting cause injury',
      'pre-lift stretching',
      'should i stretch hamstrings before rdls',
      'i never stretch before the gym, am i doing it wrong',
      'stretching then squats or squats then stretching',
      "why do coaches say don't static stretch before lifting",
      'does stretching before a workout prevent injuries',
      'short stretches before training, harmful?',
      'holding a quad stretch before leg press',
      'dynamic stretches or long holds before lifting',
      'stretching pre workout reduce power?',
      'should i stretch my shoulders before overhead press',
      'passive stretching before the gym',
    ],
    exUk: [
      'статичні затримки перед присідом — добре чи погано',
      'від розтяжки перед залом я стаю слабшим?',
      'тягнутись до носків перед становою — допомагає?',
      'довго розтягуватись перед днем ніг — ок?',
      'розтяжка перед силовими застаріла?',
      'махи ногами чи розтяжка задньої поверхні перед тренуванням',
      'розтяжка по 30 секунд перед штангою шкодить?',
      'завжди розтягуюсь 15 хвилин перед залом, це добре?',
      'треба розтягнути груди перед жимом?',
      'йога перед силовим',
      'розтягуватись чи ні перед важким тренуванням',
      'статична розтяжка перед вагами може травмувати?',
      'розтяжка перед заліззям',
      'тягнути задню поверхню перед румункою?',
      'ніколи не розтягуюсь перед залом, це неправильно?',
      'спочатку тягнутись, потім присід, чи навпаки',
      'чому тренери кажуть не робити статику перед силовим',
      'розтяжка перед тренуванням захищає від травм?',
      'коротка розтяжка перед тренуванням шкідлива?',
      'розтяжка квадрицепса перед жимом ногами',
      'динамічна розтяжка чи довгі затримки перед вагами',
      'розтягувати плечі перед армійським жимом?',
      'растягиваться перед приседом надо?',
      'статика перед тренировкой снижает силу?',
      'растяжка перед становой нужна?',
    ],
  },
  mobility: {
    ex: [
      "i can't touch my toes",
      'tight hip flexors from sitting all day',
      'ankles too stiff to squat without heels',
      "can't get my arms overhead properly",
      'thoracic spine mobility drills',
      'how to open up my hips',
      "i'm stiff as a board",
      'flexibility',
      'mobility work, how often',
      'range of motion is limited in my shoulders',
      'tight calves limit my squat depth',
      "does yoga help lifters' mobility",
      'how to loosen tight hamstrings for good',
      'i feel like a rusty robot',
      'best stretches to improve hip mobility',
      "can't sit in a deep squat comfortably",
      'how long to become more flexible',
      'stiff upper back, how to free it up',
      'wrist flexibility for front squats',
      'desk job made me super inflexible',
      'joints feel locked up',
      'daily mobility routine ideas',
      'can i get flexible at 40',
      'tight pecs and lats restricting overhead position',
      'improve my range of motion',
    ],
    exUk: [
      'не можу дотягнутись до носків',
      'затиснуті згиначі стегна від сидіння цілий день',
      'гомілкостоп надто жорсткий, щоб присідати без підкладки',
      'не можу нормально підняти руки над головою',
      'мобільність грудного відділу, вправи',
      'як розкрити тазостегнові',
      'я дубовий як дошка',
      'гнучкість',
      'як часто робити мобільність',
      'обмежена амплітуда в плечах',
      'литки тугі, заважають глибоко сідати',
      'йога допомагає рухливості?',
      'як назавжди розслабити задню поверхню стегна',
      'почуваюсь як іржавий робот',
      'найкращі вправи на рухливість тазу',
      'не можу комфортно сидіти в глибокому присіді',
      'за скільки можна стати гнучкішим',
      'верх спини скутий, як розрухати',
      'гнучкість зап’ясть для фронтального присіду',
      'через сидячу роботу став зовсім негнучким',
      'суглоби ніби заклинило',
      'щоденна рутина на мобільність',
      'в 40 років ще можна стати гнучким?',
      'как стать гибче',
      'подвижность плеч как улучшить',
    ],
  },
  abs_daily: {
    ex: [
      'abs every day, yes or no',
      'six pack tips',
      'how do i get my abs to show',
      'how many ab sessions a week',
      'is core training daily overkill',
      'planks every day enough for abs',
      'i do 200 sit-ups a day and still no six pack',
      'abs are made in the kitchen, true?',
      'should i load my abs like other muscles',
      'cable crunches or leg raises for a six pack',
      'can i train abs on consecutive days',
      'belly is covered, where are my abs',
      'abs',
      'core workouts, how often',
      'how do people get that eight pack',
      'hanging leg raises daily ok',
      'do abs recover faster than other muscles',
      'ab circuit every morning, good idea',
      'rep range for abs',
      'do squats and deadlifts train abs enough',
      'how long until my abs pop',
      'weighted crunches make waist wider?',
      'can i hit abs at the end of every workout',
      'want a flat stomach with visible abs',
      'how often to hit the six pack muscles',
    ],
    exUk: [
      'прес щодня — так чи ні',
      'поради для кубиків',
      'як зробити, щоб прес проявився',
      'скільки разів на тиждень прес',
      'тренувати кор щодня — не забагато?',
      'планки щодня вистачить для преса?',
      'роблю 200 скручувань на день, а кубиків нема',
      'прес робиться на кухні — правда?',
      'навантажувати прес вагою, як інші м’язи?',
      'скручування на блоці чи підйоми ніг для кубиків',
      'качати прес кілька днів поспіль можна?',
      'прес під жирком, як його дістати',
      'прес',
      'висові підйоми ніг щодня — норм?',
      'прес відновлюється швидше за інші м’язи?',
      'кожного ранку коло на прес — гарна ідея?',
      'на прес краще багато повторів чи з вагою',
      'присід і станова качають прес достатньо?',
      'скручування з вагою роблять талію ширшою?',
      'можна качати прес в кінці кожного тренування?',
      'хочу плаский живіт з кубиками',
      'як часто качати кубики',
      'пресак щодня качати треба?',
      'как сделать кубики на животе',
      'почему не видно пресса, хотя качаю',
    ],
  },
  grip: {
    ex: [
      'bar keeps rolling out of my fingers on deads',
      'forearms give out before my lats',
      'crushing grip training',
      'thick bar training for grip',
      'my hands open up on heavy shrugs',
      'mixed grip or hook grip',
      'grip',
      'how to hold onto the bar longer',
      'pinch grip exercises',
      'wrist curls for grip, worth it',
      "can't hang from the bar for more than 20 seconds",
      'does a double overhand grip get stronger over time',
      'grip trainers, do they work',
      'sweaty hands slipping off the bar',
      'hook grip hurts my thumb, alternatives',
      'stronger hands',
      'fingers give out on heavy rows',
      'how do i stop losing my grip on kettlebell swings',
      'grippers vs heavy holds',
      'forearm strength for deadlifts',
      'grip strength keeps limiting my back day',
      'how to train my grip without straps',
      'rice bucket training worth it',
      'grip endurance for high rep deadlifts',
      'is my grip weak or my technique bad on deadlift',
    ],
    exUk: [
      'гриф викочується з пальців на становій',
      'передпліччя здаються раніше за найширші',
      'тренування стискаючого хвату',
      'товстий гриф для хвату',
      'руки розкриваються на важких шрагах',
      'різнохват чи замок',
      'хват',
      'як довше втримати гриф',
      'вправи на щипковий хват',
      'згинання зап’ясть для хвату — варто?',
      'не можу провисіти на турніку більше 20 секунд',
      'еспандер для кистей — працює?',
      'потіють руки, і гриф вислизає',
      'замок болить великому пальцю, що замість',
      'пальці здаються на важких тягах',
      'як не втрачати хват на махах гирею',
      'сила передпліч для станової',
      'хват постійно обмежує день спини',
      'як натренувати хват без лямок',
      'витривалість хвату на багатоповторній становій',
      'слабкий хват чи погана техніка на становій',
      'хватка слабка',
      'кисті забиваються на тягах, шо робити',
      'хват не держит на становой',
      'как натренировать кисти',
    ],
  },
  belt_straps: {
    ex: [
      'is a belt cheating',
      'lifting belt',
      'straps on deadlifts, yes or no',
      'wrist wraps for bench press',
      'velcro belt vs leather belt',
      'how tight should my belt be',
      'belt on warm-up sets or only heavy ones',
      'versa grips vs straps',
      'should i wear a belt for overhead press',
      'knee sleeves or knee wraps',
      'will straps make my grip weak',
      'how to put on lifting straps',
      'figure 8 straps for deadlift',
      'do i need a belt if i have a strong core',
      'belt for leg press?',
      'belt, straps, sleeves: which do i actually need',
      'is using wraps every set a crutch',
      '10mm or 13mm belt',
      'when do i start using straps',
      'belt placement, above or on the hips',
      'elbow sleeves worth it',
      'straps for lat pulldowns, is that weak',
      'powerlifting belt worth buying',
      'does wearing a belt protect my back',
      'beltless or belted squats',
    ],
    exUk: [
      'пояс — це читерство?',
      'атлетичний пояс',
      'лямки на становій — так чи ні',
      'бинти на зап’ястя для жиму лежачи',
      'пояс на липучці чи шкіряний',
      'наскільки туго затягувати пояс',
      'пояс на розминці чи тільки на важких',
      'гаки для тяги чи лямки',
      'пояс на армійський жим одягати?',
      'наколінники чи бинти на коліна',
      'від лямок хват стане слабким?',
      'як правильно намотувати лямки',
      'лямки-вісімки для станової',
      'пояс потрібен, якщо кор сильний?',
      'пояс на жим ногами?',
      'бинти на кожен сет — це милиця?',
      'пояс 10 мм чи 13 мм',
      'з якого моменту брати лямки',
      'де має сидіти пояс, на талії чи нижче',
      'налокітники варто брати?',
      'лямки на верхній блок — це слабкість?',
      'пауерліфтерський пояс варто купити?',
      'пояс захищає спину?',
      'присід з поясом чи без',
      'лямки на становую юзать нормально?',
    ],
  },
  breathing: {
    ex: [
      'big breath before each rep?',
      'should i breathe out at the top',
      'air into belly or chest before squatting',
      'i run out of air halfway through my set',
      'valsalva safe?',
      'exhale through the sticking point',
      'how to create intra-abdominal pressure',
      'do i breathe between reps on deadlift',
      'i see stars after heavy squats',
      'breathing',
      'bracing',
      'reset breath each rep or hold for several',
      'hiss on the way up?',
      'breathing pattern for high rep sets',
      '360 degree brace explained',
      'blowing out air at lockout',
      'hold air in on bench or breathe normally',
      'does grunting help lifting',
      'should my stomach push out when i brace',
      'breath control on heavy singles',
      'i gasp for air during 20 rep squats',
      'breathe through the nose or mouth when lifting',
      'is it normal to feel head pressure when bracing',
      'when exactly do i inhale on a squat',
      "brace like you're about to get punched, what does that mean",
    ],
    exUk: [
      'великий вдих перед кожним повтором?',
      'видихати у верхній точці?',
      'набирати повітря в живіт чи в груди перед присідом',
      'задихаюсь посеред сету',
      'вальсальва безпечна?',
      'видихати через мертву точку',
      'як створити внутрішньочеревний тиск',
      'дихати між повторами на становій?',
      'після важких присідів в очах іскри',
      'дихання',
      'як правильно робити брейсинг',
      'новий вдих на кожен повтор чи тримати кілька',
      'шипіти на підйомі — нормально?',
      'дихання на багатоповторних сетах',
      'брейсинг на 360 градусів — що це',
      'видувати повітря на локауті',
      'затримувати повітря на жимі чи дихати нормально',
      'кректати допомагає піднімати?',
      'живіт має випинатись, коли напружуюсь?',
      'контроль дихання на важких одиночках',
      'хапаю ротом повітря на присідах по 20 повторів',
      'дихати носом чи ротом під час вправ',
      'тиск у голові, коли напружую корпус — це нормально?',
      'коли саме вдихати на присіді',
      'как дышать на становой',
    ],
  },
  squat_form: {
    ex: [
      'is half squatting fine',
      'butt wink at the bottom',
      'my heels come up when i squat',
      'knee valgus fix',
      'hips shoot up first out of the hole',
      'breaking parallel, what does that mean',
      'how low is low enough',
      'knees drifting forward too much on squats?',
      'hip crease below the knee, is that the rule',
      'rounded lower back at the bottom of my squat',
      'my knees buckle inward under heavy load',
      'chest falls forward when i squat',
      'atg squats bad for knees?',
      'quarter squats count?',
      'should i touch my chest on every bench rep',
      'cat back deadlift',
      "can't reach depth without my back rounding",
      'should i push my knees out',
      'my squat is too shallow, how to fix',
      'do i need to squat to a box to learn depth',
      'squat depth check',
      'knees in front of toes, dangerous?',
      'bar touching belly or sternum on bench',
      'lumbar flexion on deadlifts, ok or not',
      'how deep do powerlifters squat',
    ],
    exUk: [
      'напівприсід — це норм?',
      'підкручує таз унизу присіду',
      'п’ятки відриваються, коли присідаю',
      'як виправити завал колін всередину',
      'таз вистрілює першим з нижньої точки',
      'пробити паралель — це як',
      'наскільки низько достатньо',
      'коліна сильно йдуть вперед на присіді?',
      'тазостегновий згин нижче коліна — це правило?',
      'поперек округлюється внизу присіду',
      'коліна завалюються під важкою вагою',
      'грудна клітка падає вперед при присіді',
      'присід до п’ят шкідливий для колін?',
      'чвертьприсід рахується?',
      'торкатись грифом грудей на кожному повторі?',
      'спина колесом на становій',
      'не можу дійти до глибини без округлення спини',
      'виводити коліна назовні?',
      'присідаю надто мілко, як виправити',
      'присідати на ящик, щоб відчути глибину?',
      'коліна перед носками — небезпечно?',
      'гриф на жимі опускати на живіт чи на груди',
      'мій присід достатньо глибокий?',
      'колени заваливаются внутрь при приседе',
      'спина круглая на становой, как исправить',
    ],
  },
  results_time: {
    ex: [
      'when do the gains start showing',
      'how many months until i look different',
      'six weeks in and the mirror looks the same',
      'will i see a difference in 30 days',
      'how soon do newbie gains kick in',
      'patience question: when does it pay off',
      "i've been going for 2 months, when will it show",
      'how long before my shirts get tighter',
      'when will my friends notice',
      'results timeline',
      'timeframe to look fit',
      "how long until i'm visibly stronger",
      'what can i expect after a year of training',
      'why is it taking so long to see a change',
      'when does the body actually start transforming',
      'how long till i look like i work out',
      'is 8 weeks enough to see results',
      'first results from lifting, when',
      'still look the same after all this training',
      'how long does it take to get in shape',
      'when will i notice strength going up',
      'how many weeks for a visible change in my arms',
      'i want to know when the payoff comes',
      'how long until i see progress in photos',
      'expected time to see changes',
    ],
    exUk: [
      'коли почне бути видно прогрес на тілі',
      'скільки місяців, щоб виглядати інакше',
      'шість тижнів ходжу, а в дзеркалі те саме',
      'за 30 днів буде різниця?',
      'як скоро з’являються перші результати в новачків',
      'два місяці ходжу, коли вже буде видно',
      'коли футболки стануть тіснішими',
      'коли друзі помітять',
      'терміни результатів',
      'за скільки можна прийти у форму',
      'чого так довго нема змін',
      'коли тіло реально почне мінятись',
      '8 тижнів достатньо, щоб побачити результат?',
      'перші результати від залу коли',
      'досі виглядаю так само після всіх тренувань',
      'що чекати після року тренувань',
      'скільки тижнів до видимих змін у руках',
      'коли вже буде віддача від залу',
      'за скільки часу видно різницю на фото',
      'скільки треба чекати на результат',
      'як довго до першого результату',
      'ходжу, ходжу, а толку не видно — коли буде',
      'через сколько будет видно результат',
      'когда тело начнет меняться от зала',
      'за месяц будет результат?',
    ],
  },
  muscle_gain_rate: {
    ex: [
      'how do i put on size',
      'hardgainer, how do i grow',
      'how many kg of muscle per year naturally',
      "i'm a twig, help me get jacked",
      'fastest way to pack on muscle',
      'is 1 kg of muscle a month realistic',
      'how to get swole',
      "can't gain muscle no matter what",
      'i want to be massive',
      'how quickly can i add lean mass as a natural',
      "what's the recipe for building muscle",
      'gaining muscle',
      'how to get jacked',
      'how much muscle can a beginner put on in the first year',
      'i want more muscle overall',
      'why is building muscle so slow',
      'what matters most for hypertrophy overall',
      'how to go from skinny to muscular',
      'rate of muscle growth for naturals',
      'can i gain 5 kg of muscle in 3 months',
      'i want to look bigger in general',
      'mass gain plan',
      'ectomorph trying to build muscle',
      'how to maximize muscle growth',
      'put on muscle as fast as possible',
    ],
    exUk: [
      'як набрати обсяг',
      'хардгейнер, як мені рости',
      'скільки кг м’язів на рік можна натурально',
      'я як тріска, допоможи накачатись',
      'найшвидший спосіб наростити м’язи',
      '1 кг м’язів на місяць — реально?',
      'як стати кабанчиком',
      'не можу набрати м’язи, хоч убий',
      'хочу бути масивним',
      'як швидко натурал може набрати суху масу',
      'рецепт набору м’язів',
      'набір м’язів',
      'скільки м’язів новачок набере за перший рік',
      'хочу більше м’язів загалом',
      'чому м’язи ростуть так повільно',
      'що найважливіше для гіпертрофії',
      'як з дрища стати накачаним',
      'швидкість росту м’язів у натуралів',
      '5 кг м’язів за 3 місяці можна?',
      'хочу виглядати більшим',
      'план на набір маси',
      'ектоморф, хочу наростити м’язи',
      'як максимально наростити м’язи',
      'как нарастить мышцы быстро',
      'сколько мышц можно набрать за год',
    ],
  },
  fat_loss: {
    ex: [
      'how do i get rid of my belly',
      'i want to drop 10 kg',
      'getting lean for summer',
      'how to lose the gut',
      'burn fat',
      "i'm overweight and want to slim down",
      'can i lose fat by lifting alone',
      'how to shed fat but not strength',
      'best approach to leaning out',
      "love handles won't go away",
      'how to reduce body fat percentage',
      'i need to lose weight for my health',
      'will side bends melt my muffin top',
      'is it possible to get lean without cardio',
      'how do i lose weight and still get stronger',
      'why am i not losing fat',
      'how to get rid of chest fat',
      'stubborn lower belly fat',
      "what's the best way to trim down",
      'fat loss tips',
      'going from skinny fat to lean',
      'can i lose fat in my face',
      "i've gained weight, how do i get back in shape",
      'losing weight while keeping my lifts',
      'how to get a leaner physique',
    ],
    exUk: [
      'як позбутися живота',
      'хочу скинути 10 кг',
      'підсушитись до літа',
      'як прибрати пузо',
      'спалити жир',
      'в мене зайва вага, хочу схуднути',
      'можна схуднути тільки силовими?',
      'як скинути жир, але не силу',
      'боки не йдуть',
      'як зменшити відсоток жиру',
      'треба схуднути для здоров’я',
      'нахили в сторони приберуть боки?',
      'можна висушитись без кардіо?',
      'як худнути і при цьому ставати сильнішим',
      'чому жир не йде',
      'як прибрати жир з грудей',
      'жир внизу живота не йде',
      'поради по схудненню',
      'як зі скінні-фет стати сухим',
      'можна схуднути в обличчі?',
      'набрав зайвого, як повернутись у форму',
      'худнути, зберігаючи свої ваги в залі',
      'як стати сухішим',
      'как убрать живот',
      'хочу сбросить лишний вес',
    ],
  },
  myth_bulky: {
    ex: [
      'will i end up looking like a man if i lift',
      'heavy deadlifts will make my waist thick, right?',
      'scared of big bulky thighs',
      'i just want to look toned and lean, not huge',
      'can lifting make a woman look masculine',
      'do women accidentally get huge from weights',
      "i'm a girl, will squats make my legs massive",
      'pink dumbbells or real weights for women',
      "i don't want big shoulders",
      'is it true you get bulky just by touching a barbell',
      'will my arms get too big if i train them',
      'i want a slim look, should i avoid heavy weights',
      'high reps light weight to stay slim',
      'can i lift and stay small',
      "i'm worried lifting will make me look stocky",
      'does strength training make girls bulky',
      'light weights to tone',
      'how do i get toned without muscle growth',
      'will glute training make my legs thick',
      "my wife won't lift because she thinks she'll get huge",
      'bulky myth',
      'do heavy weights make you look like a bodybuilder overnight',
      'is it possible to lift heavy and stay feminine',
      "i don't want to look too muscular",
      'will lifting heavy ruin my slim figure',
    ],
    exUk: [
      'я не стану схожою на чоловіка від залу?',
      'від важкої станової талія стане товстою?',
      'боюсь великих масивних стегон',
      'хочу просто підтягнуте тіло, а не гору м’язів',
      'силові можуть зробити жінку мужикуватою?',
      'жінки випадково не перекачуються від ваг?',
      'я дівчина, від присідів ноги не стануть здоровенними?',
      'дівчатам рожеві гантельки чи справжні ваги?',
      'не хочу широкі плечі',
      'правда, що від штанги одразу стаєш масивною?',
      'руки не стануть занадто великі, якщо їх тренувати?',
      'хочу стрункість, уникати важких ваг?',
      'багато повторів з малою вагою, щоб лишатись стрункою',
      'можна тягати і залишатись мініатюрною?',
      'боюсь, що від заліза стану кремезною',
      'силові роблять дівчат громіздкими?',
      'легкі гантелі для тонусу',
      'як прийти в тонус без росту м’язів',
      'від тренування сідниць ноги стануть товстими?',
      'дружина не йде в зал, бо думає, що перекачається',
      'міф про перекачаність',
      'можна тягати важке і лишатись жіночною?',
      'не хочу виглядати надто м’язистою',
      'не стану ли я как мужик от штанги',
      'боюсь накачать огромные ноги',
    ],
  },
  cardio_gains: {
    ex: [
      'interference effect',
      'will my 5k runs eat my quads',
      'does too much cardio shrink muscles',
      "i'm bulking, should i cut cardio completely",
      'cardio catabolic?',
      'can i keep my size and still do daily spin classes',
      'does steady state cardio hurt hypertrophy',
      'will swimming hold back my muscle growth',
      "i'm scared cardio will make me small",
      'do endurance athletes lose muscle from cardio',
      'cardio and gains, do they conflict',
      'will biking to work stop me gaining muscle',
      'does incline walking cost me muscle',
      'concurrent training and muscle growth',
      'my bro says cardio kills strength, is he right',
      'will rowing machine sessions affect my squat numbers',
      'cardio eating my gainz',
      'does conditioning work make me lose size',
      'does cardio slow down muscle building',
      'does the stairmaster burn muscle',
      'long runs and lean mass, compatible?',
      'can i do cardio and still get huge',
      'will jogging make me weaker',
      'does cardio blunt strength gains',
      'cardio muscle loss',
    ],
    exUk: [
      'ефект інтерференції',
      'пробіжки на 5 км з’їдять квадрицепси?',
      'від надлишку кардіо м’язи зменшуються?',
      'я на масі, повністю кинути кардіо?',
      'кардіо — це катаболізм?',
      'можна зберегти м’язи і щодня ходити на сайкл?',
      'рівномірне кардіо шкодить гіпертрофії?',
      'плавання гальмуватиме ріст м’язів?',
      'боюсь, що від кардіо здуюсь',
      'кардіо і ріст м’язів — конфліктують?',
      'їжджу на роботу на велику, це не заважає набору м’язів?',
      'ходьба на доріжці під нахилом забирає м’язи?',
      'кажуть, кардіо вбиває силу, це так?',
      'веслувальний тренажер вплине на мій присід?',
      'кардіо жере мої м’язи',
      'від кардіо сила падає чи ні',
      'кардіо сповільнює набір м’язів?',
      'степер спалює м’язи?',
      'довгі пробіжки і м’язова маса — сумісно?',
      'можна робити кардіо і все одно набрати масу?',
      'від пробіжок стану слабшим?',
      'кардіо гальмує прогрес у силі?',
      'втрата м’язів від кардіо',
      'кардио убьет массу?',
      'от бега мышцы уходят?',
    ],
  },
  sick: {
    ex: [
      "i've got a head cold, lift or rest",
      'stuffy nose, still train?',
      'running a temperature, gym today?',
      'chest congestion and a cough, should i work out',
      'stomach bug, can i train',
      'feeling feverish',
      'caught something from my kid, training ok?',
      'above the neck rule for exercising sick',
      'when is it safe to go back to the gym after the flu',
      "i'm under the weather",
      'body aches from a virus, work out anyway?',
      'is sweating out a cold a good idea',
      'i have a chest infection, do i skip my sessions',
      'sick',
      "pause training because i'm ill",
      'can i do a light workout with a cold',
      'just got over covid, how soon can i lift',
      "i'm sneezing all day, go to the gym or not",
      'tonsillitis and training',
      "i feel like i'm getting the flu",
      "should i hit the gym if i'm contagious",
      'food poisoning yesterday, training today?',
      'my throat is scratchy and i feel off, lift?',
      'been ill for a week, how to restart training',
      'does training with a cold make it worse',
    ],
    exUk: [
      'в мене нежить і закладений ніс, тренуватись?',
      'температура, сьогодні в зал?',
      'кашель і хрипи, займатись?',
      'отруївся, можна тренуватись?',
      'мене лихоманить',
      'підхопив щось від дитини, тренування ок?',
      'коли можна в зал після грипу',
      'мені зле, приболів',
      'ломить тіло від вірусу, все одно займатись?',
      'пропотіти застуду в залі — хороша ідея?',
      'хворію',
      'поставити тренування на паузу, бо захворів',
      'легке тренування при застуді можна?',
      'щойно перехворів ковідом, коли можна тягати',
      'цілий день чхаю, йти в зал чи ні',
      'ангіна і тренування',
      'здається, мене грип накриває',
      'чи йти в зал, якщо я заразний',
      'дере горло і якось не по собі, тренуватись?',
      'тиждень хворів, як відновити тренування',
      'тренування із застудою погіршить стан?',
      'шось мене простуда взяла, трєня відміняється?',
      'температурю, в зал не йти?',
      'простыл, можно в зал?',
      'температура, тренироваться можно?',
    ],
  },
  alcohol: {
    ex: [
      'few beers last night, still lift today?',
      'wine and muscle growth',
      'hanging from last night',
      'does booze wreck recovery',
      'how many drinks will hurt my progress',
      'is it bad to drink after leg day',
      'i drink every friday, am i sabotaging my gains',
      'hangover workout',
      'alcohol',
      'does vodka have less impact than beer on gains',
      'can i drink on a bulk',
      'still a bit drunk from last night, should i go lift',
      'headache and nausea from drinking, train?',
      'wedding this weekend, will a night of drinking undo my week',
      'does alcohol lower testosterone',
      'beer belly and lifting',
      'hungover leg day, good idea?',
      'how long after drinking should i wait to train',
      'sober for gains, necessary?',
      'can i have a glass of wine and still build muscle',
      'went out partying, skip the gym today?',
      'does drinking affect my lifts the next day',
      'is a couple of cocktails bad for recovery',
      'booze and the gym',
      'rough morning after drinking, lift or rest',
    ],
    exUk: [
      'вчора кілька пив, сьогодні тягати?',
      'вино і ріст м’язів',
      'голова тріщить після вчорашнього, в зал?',
      'бухло гробить відновлення?',
      'скільки випивки вже шкодить прогресу',
      'погано випити після дня ніг?',
      'п’ю щоп’ятниці, я гроблю свої результати?',
      'тренування з бодуна',
      'алкоголь',
      'горілка менше шкодить м’язам, ніж пиво?',
      'можна пити на масі?',
      'ще трохи п’яний з ночі, йти тягати?',
      'голова болить і нудить після пиятики, тренуватись?',
      'на вихідних весілля, одна ніч з алкоголем зведе тиждень нанівець?',
      'алкоголь знижує тестостерон?',
      'пивний живіт і зал',
      'день ніг з похмілля — ідея так собі?',
      'скільки чекати після випивки, щоб тренуватись',
      'келих вина завадить набору м’язів?',
      'вчора тусив, сьогодні пропустити зал?',
      'випивка впливає на силу наступного дня?',
      'пару коктейлів шкодять відновленню?',
      'бухав учора, тепер у зал чи відлежатись',
      'с бодуна в зал идти?',
      'пиво убивает мышцы?',
    ],
  },
  water: {
    ex: [
      'hydration',
      'how many glasses of water should a lifter have',
      'my pee is dark yellow, am i dehydrated',
      'sip water between sets or not',
      'how much should i drink during a 90 minute session',
      'is 2 litres a day enough when training',
      'drinking too much water, is that a thing',
      'i barely drink water, does it matter for the gym',
      'does dehydration make me weaker',
      'water per kg of bodyweight',
      'should i chug water before training',
      'does tea count as water intake',
      'i get thirsty mid-workout, is that bad',
      'how to remember to drink more water',
      'am i drinking too little',
      'water bottle size for the gym',
      'fluid intake on hot training days',
      'headaches after the gym, could it be lack of water',
      'how much water for muscle growth',
      'should i drink water before bed on training days',
      'h2o intake',
      'how many litres if i weigh 90 kg',
      'is sparkling water fine for hydration',
      'dry mouth during sets',
      'how much water on rest days',
    ],
    exUk: [
      'гідратація',
      'скільки склянок води треба тому, хто качається',
      'сеча темно-жовта, я зневоднений?',
      'пити між підходами чи ні',
      'скільки пити за півторагодинне тренування',
      '2 літри на день вистачить, якщо тренуюсь?',
      'можна випити забагато води?',
      'я майже не п’ю воду, це важливо для залу?',
      'від нестачі води я слабшаю?',
      'скільки води на кілограм ваги',
      'випивати багато води перед тренуванням?',
      'чай рахується як вода?',
      'хочеться пити посеред тренування, це погано?',
      'як не забувати пити воду',
      'п’ю замало води?',
      'скільки пити в спеку, коли тренуюсь',
      'голова болить після залу, може від нестачі води',
      'скільки води для росту м’язів',
      'скільки літрів, якщо важу 90 кг',
      'газована вода підходить для гідратації?',
      'в роті пересихає під час сетів',
      'скільки води у вихідні від тренувань',
      'норма води для спортсмена',
      'сколько литров воды надо спортсмену',
      'пить воду во время тренировки можно?',
    ],
  },
  sleep_better: {
    ex: [
      'lying awake till 2am every night',
      'how to wind down after a late session',
      'my mind races at bedtime',
      "wired after the gym, can't switch off",
      'melatonin for sleep, good idea',
      'i keep waking up at 4am',
      'tossing and turning all night',
      'how to get deeper sleep',
      'bedtime routine to sleep better',
      'screens before bed ruining my sleep?',
      "can't stay asleep",
      'restless sleep',
      'my sleep is garbage, how do i fix it',
      'how do i become a better sleeper',
      'sleep quality tips',
      'room temperature for better sleep',
      'shift worker, how to sleep properly',
      'wake up unrefreshed every morning, how to sleep better',
      'night training and insomnia',
      'how to reset my body clock',
      'i sleep like crap',
      'how to stop waking up in the middle of the night',
      "can't doze off",
      'falling asleep takes me an hour',
      'best habits for quality sleep',
    ],
    exUk: [
      'щоночі лежу до другої і не сплю',
      'як заспокоїтись після пізнього тренування, щоб заснути',
      'думки лізуть, не можу заснути',
      'після залу збуджений, не вимикаюсь',
      'мелатонін для сну — варто?',
      'постійно прокидаюсь о 4 ранку',
      'кручусь всю ніч',
      'як спати глибше',
      'ритуал перед сном для кращого сну',
      'телефон перед сном псує сон?',
      'не можу проспати всю ніч',
      'неспокійний сон',
      'сон жахливий, як виправити',
      'поради, як якісно висипатись',
      'яка температура в кімнаті для кращого сну',
      'працюю позмінно, як нормально спати',
      'прокидаюсь розбитим, як покращити сон',
      'вечірні тренування і безсоння',
      'як налаштувати біологічний годинник',
      'сплю як попало',
      'як перестати прокидатись серед ночі',
      'засинаю годину, не менше',
      'звички для якісного сну',
      'не могу нормально выспаться, что делать',
      'бессонница после тренировок',
    ],
  },
  time_of_day: {
    ex: [
      'morning lifter or night owl, which is better',
      'lunch break workouts, good idea?',
      'does lifting at 5am hurt performance',
      'am i stronger in the afternoon',
      'gym before work or after',
      'training at 10pm, any downside',
      'what time should i schedule my sessions',
      'does it matter if i lift at different times every day',
      'best hour for strength training',
      'early bird workouts vs late workouts for gains',
      'training late in the evening, worse results?',
      'circadian rhythm and lifting',
      'when am i usually at the gym',
      'should i train when the gym is empty at night',
      'morning sessions feel harder, should i switch to evenings',
      'is afternoon the best time to work out',
      'my usual workout time',
      'workout timing',
      'does training at night affect gains',
      'sunrise training worth it',
      'can i lift at midnight',
      'best time to train for fat loss, am or pm',
      'what hour do i normally lift at',
      'i can only train at 6am, is that ok',
      'does body temperature make evening lifting better',
    ],
    exUk: [
      'жайворонок чи сова — коли краще тягати',
      'тренування в обідню перерву — нормально?',
      'тренування о 5 ранку шкодить результатам?',
      'вдень я сильніший?',
      'зал до роботи чи після',
      'тренуватись о 22:00 — є мінуси?',
      'на яку годину ставити тренування',
      'важливо, якщо тренуюсь щодня в різний час?',
      'найкраща година для силових',
      'ранні тренування проти пізніх для прогресу',
      'пізно ввечері тренуватись — гірший результат?',
      'циркадні ритми і тренування',
      'коли я зазвичай буваю в залі',
      'зранку тренування важчі, перейти на вечір?',
      'вдень найкращий час для тренувань?',
      'мій звичний час тренувань',
      'тренування вночі впливає на прогрес?',
      'можна тягати опівночі?',
      'коли краще тренуватись для схуднення, зранку чи ввечері',
      'в який час у мене зазвичай тренування',
      'можу тільки о шостій ранку, це нормально?',
      'ранкова трєня чи вечірня, шо краще',
      'о котрій годині краще в зал ходити',
      'утром или вечером лучше в зал',
      'в какое время суток сила выше',
    ],
  },
  fasted: {
    ex: [
      'lifting on an empty tank',
      "haven't eaten since last night, can i still train",
      'working out during ramadan fasting',
      'fasted morning session, will i lose muscle',
      'training in a fasted state',
      'skipping breakfast before the gym',
      'no food before 7am lifts, is that ok',
      'i do 16:8, should i train before breaking my fast',
      'does lifting fasted hurt gains',
      'fasted lifting',
      'gym first thing, nothing eaten',
      'empty stomach workouts make me dizzy',
      'is it fine to lift before my first meal of the day',
      'fasted deadlifts ok?',
      'black coffee only and then the gym, ok?',
      'does fasting before training burn more fat',
      "i can't eat early, can i train without food",
      'training in the fasting window',
      'morning cardio before eating',
      'is working out hungry bad',
      'fasted training makes me feel light and strong, is it fine',
      'hitting weights before i eat anything all day',
      'is it dangerous to lift without eating',
      'no breakfast, straight to the gym',
      'does training on an empty stomach cost strength',
    ],
    exUk: [
      'тягати на порожній бак',
      'не їв з вечора, можна тренуватись?',
      'тренування під час посту',
      'ранкове тренування натщесерце — м’язи не згорять?',
      'тренуватись у голодному стані',
      'пропустити сніданок перед залом',
      'нічого не їм перед тренуванням о 7 ранку, це ок?',
      'роблю 16:8, тренуватись до першого прийому їжі?',
      'силові натщесерце шкодять прогресу?',
      'з самого ранку в зал, нічого не поївши',
      'на голодний шлунок паморочиться в голові на тренуванні',
      'можна тягати до першого прийому їжі за день?',
      'станова натщесерце — норм?',
      'лише чорна кава і в зал — нормально?',
      'голодування перед тренуванням спалює більше жиру?',
      'не можу рано їсти, можна тренуватись без їжі?',
      'тренування у вікні голодування',
      'ранкове кардіо до їжі',
      'тренуватись голодним — погано?',
      'натщесерце почуваюсь легким і сильним, це нормально?',
      'небезпечно тягати, нічого не з’ївши?',
      'без сніданку одразу в зал',
      'на голодний шлунок сила падає?',
      'тренироваться на голодный желудок вредно?',
      'кардио натощак жир жжет лучше?',
    ],
  },
  caffeine: {
    ex: [
      'pre-workout coffee',
      'is 400 mg of caffeine too much',
      'monster before leg day, bad idea?',
      'caffeine pills before lifting',
      'does coffee boost performance',
      'how long before training should i have my coffee',
      'caffeine and evening sessions',
      'should i cycle off caffeine',
      'coffee makes me jittery during sets',
      'caffeine',
      'double espresso before a max attempt',
      'pre-workout with 300mg caffeine, safe?',
      'does caffeine help endurance or strength more',
      'can i train without coffee, i feel useless',
      'red bull before the gym',
      'coffee stopped working for my workouts',
      'how many cups of coffee a day for a lifter',
      'is green tea enough caffeine for a workout',
      'caffeine crash mid-session',
      'decaf vs regular coffee before lifting',
      'does caffeine raise my heart rate too much during lifting',
      'energy drinks every workout, is that ok',
      'caffeine timing for a 6pm session',
      "i can't train without my caffeine hit",
      'coffee on training days only?',
    ],
    exUk: [
      'чашка кави перед трєнею',
      '400 мг кофеїну — це забагато?',
      'монстр перед днем ніг — погана ідея?',
      'кофеїн у таблетках перед тренуванням',
      'кава покращує результати в залі?',
      'за скільки до тренування пити каву',
      'кофеїн і вечірні тренування',
      'робити перерву від кофеїну?',
      'від кави трусить під час сетів',
      'кофеїн',
      'подвійне еспресо перед спробою на максимум',
      'передтрен з 300 мг кофеїну — безпечно?',
      'без кави не можу тренуватись, я як овоч',
      'ред булл перед залом',
      'кава перестала діяти на тренування',
      'скільки чашок кави на день можна тому, хто тренується',
      'зеленого чаю вистачить як кофеїну на тренування?',
      'відходняк від кофеїну посеред тренування',
      'енергетики на кожне тренування — це нормально?',
      'коли пити каву, якщо тренування о 18:00',
      'я підсів на каву перед кожним тренуванням',
      'каву тільки в дні тренувань?',
      'кава перед залом — сила росте?',
      'энергетик перед тренировкой вредно?',
      'сколько чашек кофе перед залом можно',
    ],
  },
  protein_timing: {
    ex: [
      'whey right after the last set?',
      'does it matter if i have my shake an hour later',
      'protein spread across the day or all at once',
      'slow protein at night',
      'when to take my shake',
      'shake timing',
      'protein first thing in the morning',
      'should i drink whey before going to sleep',
      'is post-workout protein overrated',
      'anabolic window',
      'protein every 3 hours for growth?',
      'should i have protein during my workout',
      'whey on off days',
      'i forgot my shake after training, did i waste the session',
      'casein vs whey timing',
      'pre-workout protein shake',
      'how long do i have after lifting to get protein in',
      'do i need protein immediately post workout if i ate before',
      'can i take my protein shake with breakfast instead',
      'timing of protein intake',
      'evenly split my protein between meals?',
      'is the post-gym shake window 2 hours',
      'cottage cheese before bed for muscle',
      'should my shake be before or after cardio',
      'does protein timing even matter if total intake is hit',
    ],
    exUk: [
      'протеїн одразу після останнього сету?',
      'важливо, якщо вип’ю шейк через годину?',
      'білок розподіляти на день чи весь за раз',
      'повільний білок на ніч',
      'коли приймати шейк',
      'час прийому протеїну',
      'протеїн одразу зранку',
      'пити сироватку перед сном?',
      'протеїн після тренування переоцінений?',
      'анаболічне вікно',
      'білок кожні 3 години для росту?',
      'пити протеїн під час тренування?',
      'сироватка у вихідні дні',
      'забув випити шейк після залу, тренування марне?',
      'казеїн чи сироватка — коли що пити',
      'протеїновий шейк перед тренуванням',
      'скільки часу є після залу, щоб закинути білок',
      'треба білок одразу після, якщо їв перед тренуванням?',
      'можна пити протеїн зі сніданком замість після залу?',
      'рівномірно ділити білок між прийомами їжі?',
      'вікно після залу — це 2 години?',
      'кисломолочний сир на ніч для м’язів',
      'чи має значення час прийому білка, якщо норма добита',
      'протик після трєні чи зранку',
      'протеин на ночь пить?',
    ],
  },
  travel: {
    ex: [
      'flying to spain for 10 days, how do i keep lifting',
      'hotel only has a treadmill and dumbbells up to 10 kg',
      'road trip workout plan',
      'staying in an airbnb for two weeks, no gym',
      'will a week at the beach cost me my gains',
      'keep training on holiday or take a break?',
      'visiting family over christmas, how to train',
      'workout in a hostel with no equipment',
      'business travel every week, how to stay consistent',
      'should i buy a day pass at a gym abroad',
      'cruise ship workouts',
      'going camping for a week, what about training',
      'jet lag and training',
      "i'll be out of town, pause my program?",
      'resistance band workouts for trips',
      'vacation mode',
      'holiday training',
      'backpacking through asia, how do i maintain muscle',
      'hotel gym is tiny, what do i do',
      'how to not lose progress while away',
      'trip next month, adjust my plan?',
      'packing light, what to do for workouts on the road',
      'on the road for work, keeping fit',
      'leaving for a ski trip, skip lifting?',
      "i'm abroad and my gym routine is falling apart",
    ],
    exUk: [
      'лечу в іспанію на 10 днів, як не закинути тренування',
      'в готелі тільки доріжка і гантелі до 10 кг',
      'план тренувань у дорозі на машині',
      'два тижні в квартирі подобово, залу нема',
      'тиждень на пляжі забере мої м’язи?',
      'у відпустці тренуватись чи відпочити від залу?',
      'їду до рідних на свята, як тренуватись',
      'бізнес-поїздки щотижня, як не збиватись з графіку',
      'купити разовий абонемент у залі за кордоном?',
      'їду в похід на тиждень, що з тренуваннями',
      'джетлаг і тренування',
      'мене не буде в місті, поставити програму на паузу?',
      'тренування з резинками в поїздках',
      'режим відпустки',
      'тренування у відпустці',
      'подорожую азією, як зберегти м’язи',
      'в готелі крихітний зал, що робити',
      'як не втратити прогрес, поки мене нема вдома',
      'поїздка наступного місяця, змінити план?',
      'їду налегке, що робити в дорозі для тренувань',
      'в роз’їздах по роботі, як тримати форму',
      'їду кататись на лижах, пропустити силові?',
      'я за кордоном, і весь режим тренувань розвалився',
      'еду в отпуск, как не потерять форму',
      'в отеле нет зала, что делать',
    ],
  },
  home: {
    ex: [
      'stuck at home, give me something to do',
      'living room workout',
      'push-up variations to build chest at home',
      'can bodyweight training make me strong',
      'no weights, how do i train back',
      'calisthenics for muscle',
      'only a pull-up bar at home, what can i do',
      "home workouts aren't hard enough anymore",
      'leg exercises with just my body',
      'garage workout with no gear',
      'can i skip the gym and train in my apartment',
      'i work from home and want to train between calls',
      'chair and floor workout',
      'how to overload squats without a barbell',
      'gym membership expired, how to train at home',
      'bodyweight training',
      'at-home routine for building muscle',
      'pistol squats and push-ups enough?',
      'working out in my bedroom with no equipment',
      'no gym nearby, what are my options',
      'equipment-free full body session',
      "can't afford a gym, how do i still get fit",
      'doorway rows and table rows at home',
      'home training',
      'rainy day, not leaving the house, workout ideas',
    ],
    exUk: [
      'сиджу вдома, дай якесь тренування',
      'тренування у вітальні',
      'варіанти віджимань, щоб качати груди вдома',
      'можна стати сильним на власній вазі?',
      'ваг нема, як тренувати спину',
      'калістеніка для м’язів',
      'вдома лише турнік, що можна робити',
      'домашні тренування вже не важкі',
      'вправи на ноги тільки з власною вагою',
      'тренуватись у квартирі замість залу — варіант?',
      'працюю з дому, хочу тренуватись між дзвінками',
      'тренування зі стільцем і на підлозі',
      'як ускладнити присідання без штанги',
      'абонемент закінчився, як займатись вдома',
      'домашня програма для набору м’язів',
      'пістолетики і віджимання — цього вистачить?',
      'займаюсь у спальні без обладнання',
      'поруч нема залу, які варіанти',
      'тренування на все тіло без інвентарю',
      'грошей на зал нема, як бути у формі',
      'тяга під столом вдома — працює?',
      'домашні тренування',
      'з дому не виходжу, ідеї для тренування',
      'тренировка дома с собственным весом',
      'дома без гантелей как качаться',
    ],
  },
  comeback: {
    ex: [
      'been off the gym for a year, how do i restart',
      'back after 3 months of nothing',
      'fell off the wagon, getting back into it',
      "haven't touched a barbell since summer",
      'restarting after a long layoff',
      'detrained, how fast will it come back',
      'back to training after exams',
      'lost my strength after a break, what now',
      "i quit for a while and now i'm back",
      'rebuilding after time away from lifting',
      'how much weight to start with after 2 months off',
      'first week back, how hard should i push',
      'after the new baby, returning to the gym',
      'does muscle come back faster the second time',
      "haven't lifted since covid lockdowns",
      'starting over',
      'picking lifting back up after two years',
      'returning lifter',
      "i'm rusty, been away from the gym",
      'missed three weeks, do i restart my program',
      "how long until i'm back to my old numbers after a break",
      'back from a long pause, will i be super sore',
      'i let myself go, want to get back to lifting',
      'been lazy for months, where do i begin again',
      'old lifter coming back after a decade',
    ],
    exUk: [
      'рік не ходив у зал, як відновитись',
      'повертаюсь після трьох місяців нічого',
      'зірвався і закинув, тепер повертаюсь',
      'не торкався штанги з літа',
      'знову починаю після довгого простою',
      'розтренувався, як швидко повернеться',
      'повертаюсь до тренувань після сесії',
      'втратив силу за перерву, що тепер',
      'кидав на якийсь час, тепер знову тут',
      'з якої ваги починати після двох місяців без залу',
      'перший тиждень після перерви, наскільки важко тягати',
      'після народження дитини повертаюсь у зал',
      'м’язи вдруге швидше повертаються?',
      'не тягав з часів карантину',
      'починаю з нуля заново',
      'пропустив три тижні, починати програму спочатку?',
      'коли повернусь до старих ваг після перерви',
      'після довгої паузи буде дика крепатура?',
      'запустив себе, хочу повернутись до заліза',
      'місяцями лінувався, з чого почати знову',
      'десять років не займався, повертаюсь',
      'заіржавів, давно не був у залі',
      'два роки перерви, знову хочу тягати',
      'долго не занимался, как вернуться',
      'вернулся в зал после паузы, какие веса брать',
    ],
  },
  rest_day: {
    ex: [
      'off day plans',
      'is it fine to do nothing at all on rest days',
      'yoga on my day off',
      'should i go hiking on a rest day',
      'light bike ride on off days, yes?',
      'can i do some mobility work on my recovery day',
      'non-training day, how active should i be',
      'recovery day ideas',
      'should i eat the same on off days',
      'is it lazy to just chill on a rest day',
      'light pump session on a rest day?',
      'what does a good rest day look like',
      'complete rest vs active rest',
      'can i do abs on my rest day',
      'how to keep moving on days without lifting',
      'day off from lifting, how to use it',
      'rest days',
      'am i allowed to exercise on a rest day',
      'active recovery ideas',
      'gardening counts as active recovery?',
      'should rest days be totally sedentary',
      'how much movement is ok on a recovery day',
      'rest day swim or just chill',
      'what to do between training days',
      'sunday is my off day, what should i do',
    ],
    exUk: [
      'плани на вихідний від залу',
      'нормально нічого не робити у вихідний від тренувань?',
      'йога у вихідний',
      'у день відпочинку можна в похід?',
      'легка велопрогулянка у вихідний — так?',
      'мобільність у день відновлення можна?',
      'день без тренування, наскільки бути активним',
      'ідеї для дня відновлення',
      'у вихідні від залу їсти так само?',
      'просто валятись у вихідний — це лінь?',
      'легкий памп у день відпочинку?',
      'як виглядає правильний день відпочинку',
      'повний відпочинок чи активний',
      'прес можна в день відпочинку?',
      'як рухатись у дні без заліза',
      'вихідні дні від тренувань',
      'можна займатись чимось у день відпочинку?',
      'ідеї для активного відновлення',
      'робота на городі — це активне відновлення?',
      'вихідний має бути зовсім без руху?',
      'скільки руху норм у день відновлення',
      'між тренуваннями що робити',
      'неділя в мене вихідна, чим зайнятись',
      'день отдыха от зала, как провести',
      'активное восстановление, это что',
    ],
  },
  beginner: {
    ex: [
      'total noob here',
      'first gym membership, no clue what to do',
      'never done weights, how do i begin',
      'starter program',
      "i'm 35 and just starting to lift",
      'what should a newbie focus on',
      'day one at the gym, where to begin',
      'i know nothing about lifting',
      'first steps in strength training',
      "novice lifter, what's the plan",
      'beginner',
      'what exercises should a novice learn first',
      'is 5x5 good for a beginner',
      'just signed up for a gym, help me start',
      'noob gains program',
      'first time lifting weights, how heavy should i go',
      'fresh to lifting',
      'absolute beginner routine',
      'what mistakes do beginners make',
      "i'm new, give me a simple plan",
      'how to start strength training from scratch',
      "first program for someone who's never trained",
      'new lifter tips',
      'just starting my fitness journey',
      'where should a complete beginner begin with weights',
    ],
    exUk: [
      'я повний нуб',
      'вперше купив абонемент, не знаю, що робити',
      'ніколи не займався з вагами, як почати',
      'стартова програма',
      'мені 35, і я тільки починаю тягати',
      'на чому новачку зосередитись',
      'перший день у залі, з чого почати',
      'нічого не знаю про силові',
      'перші кроки в силових тренуваннях',
      'початківець, який план',
      'новачок',
      'які вправи новачку вчити спочатку',
      '5x5 підходить новачку?',
      'щойно записався в зал, допоможи почати',
      'вперше тягаю залізо, яку вагу брати',
      'програма для абсолютного новачка',
      'які помилки роблять новачки',
      'я новенький, дай простий план',
      'як почати силові з нуля',
      'перша програма для людини, яка ніколи не тренувалась',
      'поради для тих, хто тільки почав тягати',
      'тільки починаю займатись спортом',
      'з чого почати зовсім зеленому в залі',
      'я новичок, что делать в зале',
      'первый раз в зале, с чего начать',
    ],
  },
  shoes: {
    ex: [
      'nikes for squatting, ok?',
      'heeled shoes for squats',
      'vans or chucks for deadlifts',
      'is lifting barefoot allowed',
      'my running shoes squish under heavy weight',
      'what sneakers do powerlifters wear',
      'do i need special footwear for the gym',
      'wrestling shoes for deadlifts',
      'should i buy oly shoes',
      'flat soles vs cushioned soles for lifting',
      'deadlift slippers',
      'shoes',
      'gym footwear',
      'can i squat in crossfit shoes',
      'are my air max bad for lifting',
      'socks only deadlifts',
      'do lifting shoes help squat depth',
      'hiking boots for leg day',
      'best budget shoes for lifting',
      'minimalist shoes for training',
      'heel elevation for squats, shoes or plates',
      'what do i wear on my feet for heavy squats',
      'stable shoes for leg press and squats',
      'trainers for lifting vs running trainers',
      'do shoes matter for bench press',
    ],
    exUk: [
      'найки для присідання — ок?',
      'взуття з підйомом п’ятки для присідань',
      'ванси для станової норм?',
      'можна тягати босим?',
      'бігові кроси проминаються під важкою вагою',
      'в чому тренуються пауерліфтери',
      'треба спеціальне взуття для залу?',
      'борцівки для станової',
      'купити важкоатлетки?',
      'плоска підошва чи амортизація для силових',
      'станова в чешках',
      'взуття',
      'взуття для залу',
      'можна присідати в кросфітках?',
      'мої ейр макси погані для тренувань?',
      'станова в шкарпетках — нормально?',
      'штангетки допомагають присісти глибше?',
      'трекінгові черевики на день ніг',
      'бюджетне взуття для силових',
      'мінімалістичне взуття для тренувань',
      'підйом п’ятки для присіду: взуття чи млинці',
      'що взути на важкі присідання',
      'кросівки для залу проти бігових',
      'взуття важливе для жиму лежачи?',
      'в чем делать становую, в кроссовках или босиком',
    ],
  },
};
