export const KB_R2: Record<string, { ex: string[]; exUk: string[] }> = {
  injury_status: {
    ex: [
      "how's my injured knee coming along in rehab",
      'is my shoulder injury healed yet',
      'update on my injury recovery pls',
      'how far along is my back injury',
      'am i still in rehab phase for my elbow',
      'check my logged injury progress',
      'how long till my hamstring strain is fully healed',
      'is my wrist injury still active in the app',
      'what phase of recovery is my ankle in',
      "can i go back to normal training, how's the injury",
      'injury progress report',
      "how's the rehab on my torn pec going",
      'is my knee injury getting better according to my logs',
      'when will my shoulder injury be cleared',
      'whats the current state of my injury',
    ],
    exUk: [
      'як там моя травма коліна, вже краще?',
      'на якій стадії відновлення мій травмований лікоть',
      'моя травма плеча вже зажила?',
      'скільки ще до повного відновлення після травми',
      'покажи прогрес реабілітації моєї травми',
      'як іде реабілітація спини',
      'я ще на реабілітації чи вже можна повноцінно',
      'шо там по моїй травмі',
      'травма ще активна чи вже закрита',
      'как там моя травма, уже зажила?',
      'на каком этапе восстановление после травмы',
      'как продвигается реабилитация плеча',
      'jak postępuje moja rehabilitacja po kontuzji',
      'czy moja kontuzja kolana już się zagoiła',
      'na jakim etapie jest moja kontuzja',
    ],
  },
  weaker_today: {
    ex: [
      'why do i feel so weak this session',
      'couldnt hit my usual weight today, why',
      'strength is way down today whats going on',
      'why did my lifts feel like garbage today',
      'normally i bench 80 but today 70 felt heavy, why',
      'feeling off today, why am i so weak',
      'why cant i lift what i did last week',
      "today i'm way weaker than usual, reason?",
      'why did i fail reps i usually get easily',
      'bad day, everything feels heavy, why',
      'why am i so drained and weak in the gym today',
      'lost strength overnight?? why',
      'why is my performance down today',
      'im gassed and weak today for no reason',
      'why do my working weights feel so heavy this time',
    ],
    exUk: [
      'чого я сьогодні такий слабкий',
      'сьогодні вага здається важчою ніж зазвичай, чому',
      'не зміг взяти свою звичну вагу, чому так',
      'сили сьогодні взагалі нема, що не так',
      'чому сьогодні жим пішов так погано',
      'щось я сьогодні дохлий, чому',
      'чого все так важко йде сьогодні',
      'сьогодні слабший ніж минулого тижня, в чому причина',
      'чому я не добив повтори які завжди роблю',
      'почему я сегодня такой слабый',
      'сегодня веса кажутся тяжелее обычного, почему',
      'нет силы сегодня, в чём дело',
      'dlaczego jestem dziś słabszy niż zwykle',
      'czemu dziś ciężary wydają się cięższe',
      'nie mam dziś siły, co jest nie tak',
    ],
  },
  split_choice: {
    ex: [
      'which training split would work best for me',
      'is bro split still a thing or should i do ppl',
      'upper lower vs full body for a beginner',
      'what split is optimal for 3 days a week',
      'should i switch from full body to a split',
      'ppl 6 days or upper lower 4 days, which is better',
      'best workout split for hypertrophy',
      'arnold split vs push pull legs',
      'how should i divide my muscle groups across the week',
      'is training each muscle once a week split bad',
      "what's the best split to build muscle",
      'which split gives the best results for intermediates',
      'should i do a bro split or full body',
      'good split for 5 days in the gym?',
      'is upper lower better than ppl for strength',
    ],
    exUk: [
      'який спліт краще обрати',
      'фулбаді чи верх-низ, що краще',
      'який спліт найкращий на 3 дні в тиждень',
      'пуш пул легс чи верх низ, шо ефективніше',
      "як краще розбити групи м'язів по днях",
      'який спліт для масонабору найкращий',
      'бро-спліт ще актуальний чи ні',
      'чи варто переходити з фулбаді на спліт',
      'який спліт вибрати на 4 тренування',
      'какой сплит лучше для набора массы',
      'фулбоди или сплит, что выбрать',
      'как лучше разбить мышцы по дням недели',
      'jaki split jest najlepszy',
      'FBW czy split, co lepsze',
      'push pull legs czy góra dół',
    ],
  },
  compound_isolation: {
    ex: [
      'should i focus on compound lifts or isolation moves',
      'are isolation exercises a waste of time',
      'is bicep curl isolation and should i bother',
      'multi joint vs single joint exercises',
      'can i build muscle with only compound movements',
      'which is better, big compound lifts or isolation work',
      'do i need both compound and isolation in my program',
      'what counts as an isolation exercise',
      'should compounds go before isolation in a workout',
      'is leg extension enough or do i need compounds',
      'are compound movements more effective than isolation',
      'only doing isolation, is that bad',
      'compound lifts vs accessory isolation exercises',
      "what's the difference between compound and isolation",
      'is it ok to skip isolation and just do the big lifts',
    ],
    exUk: [
      'що краще, базові вправи чи ізоляція',
      'чи потрібні взагалі ізолюючі вправи',
      'можна робити тільки базу без ізоляції',
      'багатосуглобові чи односуглобові вправи',
      'яка різниця між базою та ізоляцією',
      'спочатку база, а потім ізоляція?',
      'ізоляція це марна трата часу?',
      'чи вистачить тільки базових вправ для росту',
      'підйом на біцепс це ізоляція? чи треба він',
      'базовые или изолирующие упражнения, что лучше',
      'нужна ли изоляция, если делаю базу',
      'чем базовые упражнения отличаются от изолирующих',
      'ćwiczenia wielostawowe czy izolowane',
      'czy potrzebuję ćwiczeń izolowanych',
      'co lepsze, ćwiczenia złożone czy izolacja',
    ],
  },
  machines_free: {
    ex: [
      'is it bad to only use machines at the gym',
      'free weights vs machines for building muscle',
      'dumbbells or cable machine, which is better',
      'do machines build less muscle than barbells',
      'should i use the leg press instead of barbell squats',
      'are free weights better for stability',
      'is the smith machine worth using',
      'can i skip barbells and just use machines',
      'machines feel safer, is that ok for gains',
      'are cable exercises as good as dumbbells',
      'hammer strength machines vs free weights',
      'why do people say free weights are superior',
      'is chest press machine as good as bench press',
      'mostly machines or mostly dumbbells, what should i do',
      'are machines only for beginners',
    ],
    exUk: [
      "тренажери чи штанга, що краще для м'язів",
      'чи можна качатись тільки на тренажерах',
      'вільні ваги кращі за тренажери?',
      'гантелі чи блоки, шо ефективніше',
      'сміт чи звичайна штанга',
      'тренажери тільки для новачків?',
      'жим в тренажері не гірший за жим штанги?',
      "чи обов'язково працювати з вільними вагами",
      'жим ногами замість присіду нормально?',
      'тренажёры или свободные веса, что лучше',
      'можно ли качаться только на тренажёрах',
      'смит машина или обычная штанга',
      'maszyny czy wolne ciężary',
      'czy można budować mięśnie tylko na maszynach',
      'hantle czy maszyna, co lepsze',
    ],
  },
  superset: {
    ex: [
      'should i pair exercises back to back without rest',
      'is it worth doing antagonist supersets',
      'do supersets save time in the gym',
      'can i superset chest and back',
      'do supersets hurt strength gains',
      'how to set up supersets in my workout',
      'what exercises go well together in a superset',
      'is supersetting good for a short workout',
      'doing two exercises back to back, good idea?',
      'are supersets better than straight sets',
      'superset or rest between sets, which is better',
      'can i superset compound lifts like squats',
      'supersets for fat loss worth it?',
      "what's the point of supersets",
      'how many supersets should i do per workout',
    ],
    exUk: [
      'є сенс робити суперсети на масу?',
      'що таке суперсет і як його робити',
      'суперсет груди та спина норм?',
      'дві вправи підряд без відпочинку, це ок?',
      'суперсети економлять час?',
      'які вправи поєднувати в суперсет',
      'суперсети краще ніж звичайні підходи?',
      'чи шкодять суперсети силі',
      'як правильно робити суперсети на біцепс і трицепс',
      'стоит ли делать суперсеты',
      'что такое суперсет и зачем он нужен',
      'какие упражнения объединять в суперсет',
      'czy warto robić superserie',
      'co to jest superseria',
      'jak łączyć ćwiczenia w superserie',
    ],
  },
  dropset: {
    ex: [
      "what's a dropset and how does it work",
      'strip the weight and keep going, is that a drop set',
      'should i add dropsets to my last set',
      'are dropsets worth it for hypertrophy',
      'how much weight to drop in a dropset',
      'how many drops in a drop set',
      'dropsets vs rest pause',
      'can i do drop sets on every exercise',
      'do drop sets help build muscle faster',
      'is doing drop sets every workout too much',
      'what exercises are best for drop sets',
      'mechanical drop set meaning',
      'drop set on the last set of curls, good idea?',
      'do dropsets increase fatigue a lot',
      'reduce weight and continue to failure, is that effective',
    ],
    exUk: [
      'що таке дропсет і як його робити',
      'чи варто робити дропсети',
      'на скільки скидати вагу в дропсеті',
      "дропсети допомагають рости м'язам?",
      'дроп сет на останньому підході норм?',
      'скільки разів скидати вагу в дропсеті',
      'на яких вправах краще робити дропсети',
      'дропсет кожне тренування це не забагато?',
      'скидаю вагу і дороблюю, це дропсет?',
      'что такое дропсет',
      'стоит ли делать дропсеты для массы',
      'на сколько снижать вес в дропсете',
      'co to jest drop set',
      'czy drop sety są skuteczne',
      'ile zrzucać ciężaru w drop secie',
    ],
  },
  tempo: {
    ex: [
      'how slow should my reps be',
      'should i lower the weight for 3 seconds',
      'what does 3-1-1 tempo mean',
      'is fast lifting bad for muscle growth',
      'should i explode up and control down',
      'how many seconds per rep',
      'do slow negatives build more muscle',
      'is controlling the eccentric important',
      'should i pause at the bottom of each rep',
      'lifting speed for hypertrophy',
      'am i doing my reps too fast',
      'what tempo is best for bench press',
      'does rep speed matter',
      'what does the tempo number on my exercise mean',
      'should i lift fast or slow',
    ],
    exUk: [
      'який темп повторів найкращий',
      'як повільно опускати вагу',
      'що означає темп 3-1-1',
      'повільні повтори краще для росту?',
      'скільки секунд має тривати повтор',
      'чи треба робити паузу внизу',
      'я занадто швидко роблю повтори?',
      'негатив повільно чи як',
      'чи має значення швидкість виконання',
      'в каком темпе делать повторения',
      'медленно опускать вес или быстро',
      'что значит темп 3-1-1 в упражнении',
      'w jakim tempie robić powtórzenia',
      'jak wolno opuszczać ciężar',
      'czy tempo powtórzeń ma znaczenie',
    ],
  },
  warmup_sets: {
    ex: [
      'how many ramp up sets before working sets',
      'do i need warm up sets on every exercise',
      'how many warmup sets is too many',
      'should i do warmups for isolation exercises too',
      'general rule for number of warm up sets',
      'how many light sets before my first heavy set',
      'is one warmup set enough',
      'do warm up sets count towards volume',
      'how many reps on warmup sets',
      'warm up sets for the second exercise needed?',
      'how many feeder sets should i do',
      'do i warm up with empty bar every time',
      'how much should warmup sets tire me',
      'how many warmup sets before heavy lifting in general',
      'warmup sets: how many and how heavy',
    ],
    exUk: [
      'скільки розминочних підходів треба',
      'чи потрібні розминочні сети на кожну вправу',
      'скільки повторів у розминочних підходах',
      'одного розминочного підходу вистачить?',
      'розминочні підходи рахуються в обсяг?',
      'скільки легких підходів перед робочими',
      'чи треба розминатись перед ізоляцією',
      'скільки підвідних підходів робити',
      'розминочні сети загалом, скільки і з якою вагою',
      'сколько разминочных подходов делать',
      'нужны ли разминочные подходы на каждое упражнение',
      'сколько подводящих подходов перед рабочим весом',
      'ile serii rozgrzewkowych robić',
      'czy potrzebuję serii rozgrzewkowych przy każdym ćwiczeniu',
      'ile powtórzeń w seriach rozgrzewkowych',
    ],
  },
  stretch_before: {
    ex: [
      'is it ok to static stretch before i lift',
      'should i hold stretches before my workout',
      'does pre workout stretching prevent injury',
      'dynamic stretching or static before training',
      'i always stretch before squats, is that wrong',
      'should i do toe touches before lifting',
      'pre lift stretching good or bad',
      'does stretching before gym make you weaker',
      'is stretching part of a proper warm up',
      'should i stretch my hamstrings before deadlifts',
      'do i need to stretch before i hit the weights',
      'is it pointless to stretch before lifting',
      'stretching prior to training, yes or no',
      'should i foam roll or stretch before lifting',
      'will stretching before bench hurt my strength',
    ],
    exUk: [
      'чи треба тягнутись перед залом',
      'розтяжка до тренування шкідлива?',
      'статична чи динамічна розтяжка перед тренуванням',
      'розтяжка перед присідом зменшує силу?',
      'чи варто розтягувати ноги перед становою',
      'я завжди тягнусь перед тренуванням, це норм?',
      'розтяжка перед тренуванням захищає від травм?',
      'тягнутись до чи після тренування',
      'чи входить розтяжка в розминку',
      'нужно ли растягиваться перед тренировкой',
      'статическая растяжка перед тренировкой вредна?',
      'растяжка до или после зала',
      'czy rozciągać się przed treningiem',
      'rozciąganie statyczne przed treningiem szkodzi?',
      'stretching przed siłownią, tak czy nie',
    ],
  },
  mobility: {
    ex: [
      'how can i improve my hip mobility',
      "i'm super stiff, how do i loosen up",
      'best mobility drills for squats',
      "my ankles are tight, can't squat deep",
      'how to fix tight shoulders for overhead press',
      'what mobility routine should i do',
      'how do i get better range of motion',
      "i can't touch my toes, how to improve flexibility",
      'thoracic mobility exercises',
      'how often should i do mobility work',
      'my hip flexors are tight from sitting all day',
      'exercises to improve ankle dorsiflexion',
      'how to become more mobile as a lifter',
      'is yoga good for mobility',
      'stiff hamstrings limiting my deadlift, how to fix',
    ],
    exUk: [
      'як покращити рухливість кульшових суглобів',
      'я дуже задубілий, як стати гнучкішим',
      'вправи на мобільність для присіду',
      'гомілкостоп не гнеться, не можу глибоко присісти',
      'як розробити плечі',
      'не можу дістати до пальців ніг, як покращити гнучкість',
      'скільки разів на тиждень робити мобільність',
      'забиті згиначі стегна від сидіння, що робити',
      'як збільшити амплітуду рухів',
      'как улучшить подвижность суставов',
      'как стать гибче',
      'упражнения на мобильность для приседа',
      'jak poprawić mobilność bioder',
      'jak zwiększyć zakres ruchu',
      'ćwiczenia na mobilność kostek',
    ],
  },
  grip: {
    ex: [
      'how do i build a stronger grip',
      'my grip is my weak link on pull ups',
      'best exercises for grip strength',
      "can't hold onto the bar during heavy deadlifts",
      "should i do farmer's carries for grip",
      'how to train forearms for better grip',
      'hands open up before my back is tired',
      'mixed grip or hook grip for deadlift',
      'how to use hook grip',
      'does chalk help my grip',
      'dead hangs for grip, do they work',
      'my grip strength is terrible, help',
      'how to stop losing grip on rows',
      'bar keeps rolling out of my fingers',
      'how long to improve grip strength',
    ],
    exUk: [
      'як накачати хват сильніший',
      'хват здихає раніше за спину',
      'вправи на хват',
      'не можу втримати штангу на становій',
      'як тренувати передпліччя для хвату',
      'хук грип чи різнохват на становій',
      'магнезія допомагає хвату?',
      'вис на турніку для хвату працює?',
      'руки розтискаються на тязі, що робити',
      'как улучшить хват',
      'хват не держит на становой',
      'упражнения для силы хвата',
      'jak poprawić siłę chwytu',
      'chwyt mi puszcza na martwym ciągu',
      'ćwiczenia na chwyt',
    ],
  },
  belt_straps: {
    ex: [
      'do i need a weightlifting belt',
      'at what weight should i start using a belt',
      'is using straps on deadlifts cheating',
      'should beginners wear a lifting belt',
      'lever belt or prong belt',
      'will a belt weaken my core',
      'when should i use lifting straps',
      'are wrist wraps worth it for bench',
      'straps for rows and pulldowns, yes or no',
      'how tight should my lifting belt be',
      'do knee sleeves help',
      'is lifting gear necessary',
      'belt on every set or only heavy ones',
      'should i buy straps or a belt first',
      'does wearing a belt make you rely on it',
    ],
    exUk: [
      'чи потрібен атлетичний пояс',
      'з якої ваги одягати пояс',
      'лямки на становій це читерство?',
      'коли використовувати лямки',
      'пояс послаблює кор?',
      'чи варто новачку качатись у поясі',
      'кистьові бинти на жим потрібні?',
      'пояс на кожен підхід чи тільки важкі',
      'наскільки туго затягувати пояс',
      'нужен ли атлетический пояс',
      'лямки на становой это нормально?',
      'с какого веса надевать пояс',
      'czy potrzebuję pasa na siłownię',
      'paski do martwego ciągu to oszukiwanie?',
      'kiedy zakładać pas treningowy',
    ],
  },
  breathing: {
    ex: [
      'when do i inhale and exhale on a rep',
      'how to breathe properly during squats',
      'should i breathe out on the way up',
      'how do i brace my core',
      'holding breath while lifting, safe?',
      'breathing technique for heavy deadlifts',
      'i get dizzy from holding my breath on squats',
      'breathe in at the top or bottom of bench',
      'how to breathe during high rep sets',
      'belly breathing for lifting',
      'do i breathe every rep or hold for a few',
      'proper breathing pattern for overhead press',
      '360 bracing how to do it',
      'i forget to breathe when lifting',
      'exhale on effort, is that right',
    ],
    exUk: [
      'як правильно дихати при присіданні',
      'коли вдих, коли видих у повторі',
      'чи можна затримувати дихання на становій',
      'як правильно напружувати прес під вагою',
      'видихати на зусиллі чи як',
      'паморочиться голова від затримки дихання',
      'дихання в жимі лежачи як правильно',
      'дихати кожен повтор чи ні',
      'вальсальва це як дихати?',
      'как правильно дышать при приседаниях',
      'когда вдох а когда выдох в упражнении',
      'можно ли задерживать дыхание на тяге',
      'jak oddychać podczas przysiadu',
      'kiedy robić wdech a kiedy wydech',
      'jak się spinać przy ciężkich seriach',
    ],
  },
  squat_form: {
    ex: [
      'how low should i go on squats',
      'do i need to hit ass to grass',
      'is half squat enough',
      'my knees go way past my toes when i squat, is that bad',
      'how to stop knees caving in on squat',
      'hip crease below knee, is that the right depth',
      'should my heels come up when squatting',
      'how wide should my stance be for squats',
      'butt wink at the bottom of squat, how to fix',
      'leaning too far forward on squats',
      'parallel squat or deep squat, which is better',
      'is squatting deep bad for knees',
      'how to check my squat depth',
      'toes pointed out or straight on squat',
      'correct squat form tips',
    ],
    exUk: [
      'як глибоко треба присідати',
      'присід до паралелі чи нижче',
      'коліна виходять за носки, це погано?',
      'коліна зводяться всередину при присіді, як виправити',
      'глибокий присід шкідливий для колін?',
      "п'яти відриваються при присіданні",
      'яка ширина стійки для присіду',
      'підкручує таз внизу присіду, що робити',
      'сильно нахиляюсь вперед при присіді',
      'насколько глубоко приседать',
      'колени выходят за носки при приседе, это нормально?',
      'как правильно приседать со штангой',
      'jak głęboko robić przysiad',
      'kolana uciekają do środka przy przysiadzie',
      'czy przysiad poniżej równoległej jest konieczny',
    ],
  },
  results_time: {
    ex: [
      'how long before i actually look different',
      'when do beginner gains show up',
      'how many months until visible muscle',
      "i've been lifting 3 weeks, when will i see changes",
      'how soon will my body start changing',
      'how long to see abs or definition from lifting',
      'realistic timeline for seeing gym results',
      'how long does it take to notice strength gains',
      "when will people notice i've been working out",
      'how long till my arms get bigger',
      'am i expecting results too soon after a month',
      'when do results usually kick in',
      'how long to build noticeable muscle as a beginner',
      'will i see results in 30 days',
      'how long before the gym pays off',
    ],
    exUk: [
      'через скільки буде видно результат',
      "коли з'являться перші зміни від залу",
      "скільки місяців треба щоб побачити м'язи",
      'качаюсь місяць, а результату нема, коли буде',
      'як швидко зміниться тіло',
      "через скільки тижнів з'явиться сила",
      'коли люди помітять що я качаюсь',
      'реально за місяць побачити результат?',
      'скільки часу до помітних змін',
      'через сколько будет видно результат',
      'когда появятся первые результаты от зала',
      'сколько времени нужно чтобы накачаться',
      'kiedy zobaczę efekty treningu',
      'po jakim czasie widać efekty siłowni',
      'ile trwa zanim zobaczę mięśnie',
    ],
  },
  fat_loss: {
    ex: [
      'i want to lose 10kg, where do i start',
      'best way to lose fat and keep muscle',
      'how do i get shredded',
      'calorie deficit, how big for fat loss',
      "weight isn't dropping, how do i lose fat",
      'should i do more cardio or lift to lose weight',
      'how fast can i lose fat safely',
      'lose love handles how',
      "i'm skinny fat, how do i lose fat",
      'how to lose weight without losing strength',
      'diet for fat loss while training',
      'how do i slim down',
      'is lifting good for losing fat',
      'stuck on a plateau losing weight, what to do',
    ],
    exUk: [
      'як зігнати жирок',
      'хочу схуднути на 10 кг, з чого почати',
      "як спалити жир і не втратити м'язи",
      'як підсушитись',
      'вага стоїть, як схуднути далі',
      'кардіо чи зал щоб схуднути',
      'який дефіцит калорій для схуднення',
      'як швидко можна безпечно схуднути',
      'як позбутись боків',
      'как похудеть и сохранить мышцы',
      'как сбросить жир',
      'как быстро похудеть в зале',
      'jak schudnąć',
      'jak spalić tłuszcz i nie stracić mięśni',
      'jak zrzucić wagę na siłowni',
    ],
  },
  myth_bulky: {
    ex: [
      'will lifting heavy make me look huge',
      'i just want to tone, will weights make me big',
      'can women get bulky from weights',
      "i'm a girl, will squats make my legs too big",
      'worried weights will make me look manly',
      'does lifting make you bulky or toned',
      'will i accidentally get too muscular',
      'i want to be lean not big, should i lift',
      'is it a myth that weights make women bulky',
      'my wife is scared of getting bulky, is it true',
      'will i look like a bodybuilder if i lift',
      'lifting heavy vs light to avoid bulking up',
      'can i lift without getting big arms',
      'will weight training make my thighs thicker',
      'afraid of looking too big from strength training',
    ],
    exUk: [
      'я не стану занадто великою від залізa?',
      'від ваг жінка перекачається?',
      'боюсь стати масивною від тренувань',
      'хочу підтягнутись, а не накачатись, ваги норм?',
      'від присідань ноги стануть занадто товсті?',
      'я дівчина, мені можна важкі ваги?',
      'чи зроблять ваги мене схожою на бодібілдера',
      'це міф що від залу жінки стають великими?',
      'не хочу великі руки, можна качатись?',
      'девушка не перекачается от весов?',
      'я стану слишком большой от зала?',
      'боюсь накачаться слишком сильно',
      'czy od ciężarów zrobię się za duża',
      'czy kobieta przypakuje od siłowni',
      'boję się że będę zbyt umięśniona',
    ],
  },
  cardio_gains: {
    ex: [
      'will cardio eat my muscle',
      'does doing cardio stop muscle growth',
      'is cardio bad when trying to get big',
      'how much cardio before it hurts gains',
      'does hiit burn muscle',
      'will cycling hurt my leg gains',
      'does cardio interfere with hypertrophy',
      'can i do cardio without losing muscle',
      'interference effect is it real',
      'worried cardio will make me lose size',
      'does too much cardio make you lose muscle',
      'cardio catabolic myth or true',
      'will the stairmaster kill my gains',
      'can cardio slow down muscle growth',
      'is cardio after lifting bad for gains',
    ],
    exUk: [
      "кардіо спалює м'язи?",
      'чи заважає кардіо набору маси',
      "скільки кардіо можна щоб не втратити м'язи",
      "хіїт з'їдає м'язи?",
      'велосипед зашкодить росту ніг?',
      'кардіо на масі шкідливе?',
      'кардіо після залу вбиває результат?',
      'чи правда що кардіо катаболічне',
      "боюсь що кардіо з'їсть мою масу",
      'кардио сжигает мышцы?',
      'мешает ли кардио набору массы',
      'сколько кардио можно на массе',
      'czy cardio spala mięśnie',
      'czy cardio przeszkadza w budowaniu masy',
      'ile cardio można robić na masie',
    ],
  },
  sick: {
    ex: [
      'i have a cold, should i skip the gym',
      'is it ok to lift with a runny nose',
      "i've got a sore throat, can i work out",
      'coming down with something, train or rest',
      'can i train with covid',
      'i feel feverish, gym today or not',
      'is it bad to exercise while sick',
      'neck check rule for training when ill',
      'should i rest until my cold is gone',
      'stomach bug, can i train',
      "i'm getting sick, will training make it worse",
      'recovering from flu, when can i go back to the gym',
      'can light exercise help a cold',
      'got a chest cold, lift or not',
      'my nose is blocked, still go to the gym?',
    ],
    exUk: [
      'я застудився, йти в зал?',
      'можна тренуватись з нежиттю',
      'болить горло, тренуватись чи ні',
      'у мене температура, можна в зал?',
      'хворію, краще відпочити?',
      'після грипу коли можна повертатись в зал',
      'тренування під час хвороби шкідливі?',
      'шось мене ламає, тренуватись сьогодні?',
      'я приболів, пропустити тренування?',
      'можно ли тренироваться при простуде',
      'я заболел, идти в зал или нет',
      'с температурой можно тренироваться?',
      'czy mogę ćwiczyć z przeziębieniem',
      'jestem chory, iść na siłownię?',
      'trening podczas choroby, tak czy nie',
    ],
  },
  alcohol: {
    ex: [
      'does drinking beer ruin muscle growth',
      'is alcohol bad for gains',
      "how much alcohol is ok if i'm lifting",
      'i drank a lot last night, is training today a good idea',
      'does alcohol affect recovery',
      'can i have a few drinks and still build muscle',
      'does alcohol lower testosterone',
      'wine and gym, compatible?',
      'should i train hungover or rest',
      'will one night of drinking kill my progress',
      'drinking on weekends, will it ruin my gains',
      'is it ok to lift the day after drinking',
      'alcohol and muscle protein synthesis',
      'how long after drinking can i work out',
      'does booze slow fat loss',
    ],
    exUk: [
      "алкоголь шкодить м'язам?",
      'вчора бухав, можна сьогодні в зал?',
      'пиво вбиває результат?',
      'скільки можна пити щоб не шкодити тренуванням',
      'з похмілля тренуватись чи ні',
      'алкоголь заважає відновленню?',
      'випив на вихідних, це зіпсує прогрес?',
      'чи можна трохи випити і качатись',
      'через скільки після алкоголю можна тренуватись',
      'алкоголь убивает результаты в зале?',
      'можно ли тренироваться с похмелья',
      'пиво вредит росту мышц?',
      'czy alkohol szkodzi mięśniom',
      'mam kaca, iść na trening?',
      'czy piwo niszczy efekty treningu',
    ],
  },
  water: {
    ex: [
      'how many liters of water a day for lifting',
      'do i need more water when working out',
      'should i drink water between sets',
      "how do i know if i'm hydrated enough",
      'is 3 liters of water enough',
      'how much should i drink during a workout',
      'does drinking more water help muscle growth',
      'water intake for someone who trains daily',
      'do i need electrolytes or just water',
      'how much fluid should i have on gym days',
      'dehydrated during workouts, how much to drink',
      'how many glasses of water should i have',
      'can i drink too much water',
      'does coffee count toward my water intake',
      'water per kg body weight for athletes',
    ],
    exUk: [
      'скільки літрів води пити на день',
      'скільки пити води на тренуванні',
      'чи пити воду між підходами',
      "як зрозуміти що я п'ю достатньо води",
      '3 літри води вистачить?',
      'чи потрібні електроліти чи просто вода',
      'скільки води на кг ваги треба',
      'кава рахується як вода?',
      'у дні тренувань пити більше води?',
      'сколько воды пить в день',
      'сколько пить воды на тренировке',
      'можно ли пить воду между подходами',
      'ile wody pić dziennie',
      'ile pić wody podczas treningu',
      'czy piję wystarczająco dużo wody',
    ],
  },
  sleep_better: {
    ex: [
      'how do i fall asleep faster',
      'any tips to improve my sleep quality',
      'i wake up at night all the time, how to fix',
      "i'm wired after training at night, how to sleep",
      'does caffeine from preworkout ruin my sleep',
      'how to fix my sleep schedule',
      'what helps with deep sleep',
      "i can't stay asleep, advice?",
      'should i take melatonin',
      'how to get better rest at night',
      'bedtime routine to sleep better',
      'magnesium for sleep, does it work',
      "too much screen time, can't sleep, help",
      'how to stop waking up tired',
      'how do i improve my sleep',
    ],
    exUk: [
      'як швидше засинати',
      'погано сплю, що робити',
      'прокидаюсь вночі постійно, як виправити',
      'після вечірнього тренування не можу заснути',
      'як налагодити режим сну',
      'мелатонін допоможе заснути?',
      'порадь як покращити якість сну',
      'магній для сну працює?',
      'предтрен збиває сон, що робити',
      'как быстрее засыпать',
      'плохо сплю, что делать',
      'как улучшить качество сна',
      'jak lepiej spać',
      'nie mogę zasnąć po treningu',
      'jak szybciej zasypiać',
    ],
  },
  time_of_day: {
    ex: [
      'when is the best time to work out',
      'is lifting at night bad',
      'should i train early in the morning or after work',
      'does the time i train affect gains',
      "i'm stronger in the evening, is that normal",
      'is 6am workout worse than 6pm',
      'can i train late at night and still grow',
      'morning lifting vs evening lifting results',
      "what's the best hour to go to the gym",
      'i can only train at 5am, is that ok',
      'is training right before bed bad',
      'should i always train at the same time of day',
      'do evening workouts build more muscle',
      'lunchtime workout good idea?',
      'am vs pm training which is better',
    ],
    exUk: [
      'коли краще тренуватись, зранку чи ввечері',
      'чи погано тренуватись пізно ввечері',
      'о котрій годині найкраще йти в зал',
      'вранці я слабший, це нормально?',
      'тренування о 6 ранку гірше за вечірнє?',
      'чи треба тренуватись завжди в один час',
      'тренування перед сном шкідливе?',
      'час тренування впливає на результат?',
      'в обід тренуватись норм?',
      'когда лучше тренироваться утром или вечером',
      'можно ли тренироваться поздно вечером',
      'влияет ли время тренировки на результат',
      'lepiej ćwiczyć rano czy wieczorem',
      'o której godzinie najlepiej trenować',
      'czy trening późnym wieczorem jest zły',
    ],
  },
  fasted: {
    ex: [
      'can i lift without eating anything first',
      'is working out on an empty stomach bad',
      "i don't eat breakfast, can i still train in the morning",
      'fasted training while intermittent fasting',
      'will training fasted burn more fat',
      'lifting heavy fasted, will i lose strength',
      'do i need to eat before a morning workout',
      'training during ramadan fasting',
      'is fasted cardio better than fed',
      'i feel dizzy training fasted, is it normal',
      'should i take bcaa if i train fasted',
      'gym at 7am with no food, ok?',
      'does fasted training burn muscle',
      'skip breakfast and lift, good or bad',
      'training in a fasted state pros and cons',
    ],
    exUk: [
      'можна тренуватись на голодний шлунок',
      'не снідаю, можна зранку в зал?',
      'тренування натщесерце спалює більше жиру?',
      'інтервальне голодування і тренування',
      'треба їсти перед ранковим тренуванням?',
      'голова крутиться коли тренуюсь натще',
      'кардіо натщесерце ефективніше?',
      "тренування натщесерце спалює м'язи?",
      'в зал без сніданку це ок?',
      'можно ли тренироваться натощак',
      'кардио натощак лучше для похудения?',
      'нужно ли есть перед утренней тренировкой',
      'czy można trenować na czczo',
      'trening na pusty żołądek, dobrze czy źle',
      'cardio na czczo lepiej spala tłuszcz?',
    ],
  },
  protein_timing: {
    ex: [
      "when's the best time to take whey",
      'should i drink protein right after lifting',
      'does it matter when i have my protein shake',
      'protein shake in the morning or post workout',
      'how soon after training should i have whey',
      'is the anabolic window real',
      'should i drink a shake before bed',
      'casein at night good idea?',
      'protein shake on rest days too?',
      'pre workout protein or post workout protein',
      'do i need a shake within 30 minutes of training',
      'spreading protein through the day or all at once',
      'best timing for protein powder',
      'is drinking whey before training ok',
      'when should i take my protein on non training days',
    ],
    exUk: [
      'коли краще пити протеїн',
      'протеїн пити перед залом чи після',
      'чи є анаболічне вікно',
      "пити протеїн зразу після залу обов'язково?",
      'протеїн на ніч пити?',
      'казеїн перед сном норм?',
      'в дні відпочинку теж пити протеїн?',
      'коли пити вей, вранці чи після тренування',
      'чи важливо коли пити протеїновий коктейль',
      'когда пить протеин',
      'протеин до или после тренировки',
      'существует ли белковое окно',
      'kiedy pić białko',
      'białko przed czy po treningu',
      'czy okno anaboliczne istnieje',
    ],
  },
  travel: {
    ex: [
      "i'm travelling next week, how do i keep training",
      'hotel gym only has dumbbells, what do i do',
      'workouts on the road without a gym',
      'going abroad for 10 days, will i lose progress',
      'how to keep gains while on holiday',
      'traveling for work a lot, how to stay consistent',
      "what to do if there's no gym where i'm staying",
      'can i skip the gym during my vacation',
      'quick hotel room workout ideas',
      'how to train at a different gym while travelling',
      'is a week off on holiday bad for muscle',
      'camping trip, how do i train',
      'resistance bands for travel training',
      "i'm flying out tomorrow, how to adjust my plan",
      'vacation next month, should i pause my program',
    ],
    exUk: [
      'як тренуватись у відпустці',
      'їду у відрядження, як не пропускати тренування',
      'в готелі нема залу, що робити',
      "втрачу м'язи за два тижні відпочинку?",
      'шо робити в номері готелю замість залу',
      'подорожую, як зберегти форму',
      'на відпочинку можна не тренуватись?',
      'візьму резинки в поїздку, як з ними тренуватись',
      'як тренироваться в отпуске',
      'уезжаю в командировку, как тренироваться',
      'в отеле нет зала, что делать',
      'jak trenować w podróży',
      'jadę na wakacje, jak utrzymać formę',
      'trening w pokoju hotelowym',
      'їду в іншу країну, як бути з програмою',
    ],
  },
  home: {
    ex: [
      'can i get big working out at home',
      'i only have a pair of dumbbells at home',
      'best home workout to build muscle',
      'do push ups and squats at home build muscle',
      'what equipment should i buy for a home gym',
      'can i replace the gym with home workouts',
      'training at home with resistance bands',
      "can't afford a gym, how do i train at home",
      'calisthenics at home for gains',
      'home workout plan with no weights',
      'is working out at home as effective as the gym',
      'how to progress at home without heavy weights',
      'only a pull up bar at home, what can i do',
      'set up a home gym on a budget',
      'can i do my program at home',
    ],
    exUk: [
      'чи можна накачатись вдома',
      'тренування вдома з гантелями',
      'вдома тільки турнік, що робити',
      'які вправи робити вдома без залу',
      'домашні тренування так само ефективні як зал?',
      'що купити для домашнього залу',
      'нема грошей на зал, як тренуватись вдома',
      "віджимання і присідання вдома дадуть м'язи?",
      'тренування з резинками вдома',
      'можно ли накачаться дома',
      'тренировки дома без оборудования',
      'что купить для домашнего спортзала',
      'czy da się zbudować mięśnie w domu',
      'trening w domu bez sprzętu',
      'co kupić do domowej siłowni',
    ],
  },
  comeback: {
    ex: [
      'just got back to the gym after 6 months, how to start',
      'took a year off lifting, how heavy do i go',
      'returning after injury break, how to restart training',
      'i fell off for a month, how do i ease back in',
      'after a long break should i start with lighter weights',
      'will muscle memory help me come back',
      'how fast will i regain strength after time off',
      'back from a 3 week break, what weights to use',
      'getting back into lifting after years',
      'how to avoid soreness when returning to the gym',
      'lost my routine, starting again, tips',
      'restarting after holidays, go lighter?',
      'how long to get back to my old numbers after a break',
      'picking up training again after a pause',
      'first workout back after time off, what should it look like',
    ],
    exUk: [
      'повертаюсь в зал після пів року, з чого почати',
      'рік не тренувався, яку вагу брати',
      'після перерви починати з легших ваг?',
      "м'язова пам'ять допоможе швидко відновитись?",
      'як швидко поверну силу після перерви',
      'не ходив місяць, як повернутись у зал',
      'перше тренування після довгої перерви яке має бути',
      'як не забитись після перерви',
      'скільки часу повернутись до старих ваг',
      'возвращаюсь в зал после перерыва',
      'год не тренировался, с какого веса начать',
      'как вернуться к тренировкам после паузы',
      'wracam na siłownię po przerwie',
      'jak zacząć po długiej przerwie od treningów',
      'jaki ciężar po powrocie po przerwie',
    ],
  },
  rest_day: {
    ex: [
      'what should i do on my off day',
      'can i go for a light jog on rest days',
      'is yoga good on a rest day',
      'should i do nothing on rest days',
      'is it ok to swim on my rest day',
      'light activity ideas for days off',
      'can i do abs on rest day',
      'is it bad to be active on rest days',
      'how should i spend a rest day to recover better',
      'rest day, complete rest or active recovery',
      'can i play football on my rest day',
      'should i stretch on rest days',
      'is a bike ride ok on a non training day',
      'what do you recommend for rest days',
      'do rest days mean no exercise at all',
    ],
    exUk: [
      'що робити в день відпочинку',
      'можна в день відпочинку побігати легенько',
      'йога в день без залу норм?',
      'в дні відпочинку взагалі нічого не робити?',
      'можна плавати в день відпочинку',
      'активне відновлення це що і як',
      'можна прес в день відпочинку?',
      'покататись на велосипеді у вихідний від залу норм?',
      'як краще провести день відпочинку',
      'что делать в день отдыха',
      'активный отдых в день без тренировки это нормально?',
      'можно ли в день отдыха заниматься плаванием',
      'co robić w dzień wolny od treningu',
      'aktywna regeneracja w dzień odpoczynku',
      'czy w dzień wolny mogę pobiegać',
    ],
  },
  shoes: {
    ex: [
      'what footwear is best for lifting weights',
      'can i squat in nikes',
      'are converse good for deadlifts',
      'should i buy lifting shoes with a heel',
      'flat shoes or heeled shoes for squats',
      'is it ok to lift in running sneakers',
      'can i train in socks',
      'best shoes for leg day',
      'do squat shoes actually help',
      'what shoes for a mix of cardio and weights',
      'are cushioned shoes bad for lifting',
      'barefoot training in the gym, good idea',
      'should i wear minimalist shoes to lift',
      'is it worth buying olympic lifting shoes',
      'what trainers do you recommend for the gym',
    ],
    exUk: [
      'в якому взутті краще тренуватись',
      'можна присідати в бігових кросівках',
      'конверси для станової норм?',
      'чи варто купити штангетки',
      'плоска підошва чи з підбором для присіду',
      'можна тренуватись у шкарпетках',
      'босоніж у залі це нормально?',
      'які кросівки взяти для залу',
      "м'яка підошва погана для важких ваг?",
      'в какой обуви тренироваться в зале',
      'нужны ли штангетки для приседа',
      'можно ли приседать в беговых кроссовках',
      'w jakich butach trenować na siłowni',
      'czy mogę robić przysiady w butach do biegania',
      'czy warto kupić buty do podnoszenia ciężarów',
    ],
  },
  app_log_set: {
    ex: [
      'where do i tap to add a set',
      'how do i enter a set i just finished',
      'how to add weight and reps in the app',
      'how do i mark a set as done in the app',
      'i finished my set, where do i record it',
      'how to log sets in this app',
      'can i log a set by telling you',
      'how do i type in my reps',
      "how to add an extra set to today's workout log",
      "where's the button to save my set",
      'how do i edit a set i logged wrong',
      'log 5 reps at 100kg how',
      'how do i track my sets here',
      'how to input the weight i lifted',
      'how do i write down my set in the app',
    ],
    exUk: [
      'як додати підхід в застосунку',
      'де вписати вагу і повтори',
      'як зберегти сет у додатку',
      'як відмітити підхід як виконаний',
      'зробив підхід, як його записати',
      'де кнопка щоб записати сет',
      'як виправити неправильно записаний підхід',
      'як внести 10 повторів по 50 кг',
      'як логувати підходи в апці',
      'как записать подход в приложении',
      'где ввести вес и повторения',
      'как сохранить сет в приложении',
      'jak zapisać serię w aplikacji',
      'gdzie wpisać ciężar i powtórzenia',
      'jak dodać serię w apce',
    ],
  },
  app_turn_off: {
    ex: [
      'how can i disable you',
      'turn off the ai coach',
      'i want to switch atlas off',
      'how do i hide the coach chat',
      'can i deactivate atlas in settings',
      'get rid of atlas',
      "i don't need the coach, how to disable it",
      'how to turn off the chat bot',
      'where do i switch off atlas',
      'can i remove the coach feature',
      'shut down atlas please',
      'make atlas stop showing up',
      'opt out of the coach',
      'how do i disable coaching messages',
      'how to deactivate you',
    ],
    exUk: [
      'як тебе вимкнути',
      'як відключити атласа',
      'не хочу тренера в додатку, як прибрати',
      'де вимикається атлас в налаштуваннях',
      'можна деактивувати коуча',
      'прибери атласа',
      'як сховати чат з тренером',
      'вимкни себе',
      'як відключити бота',
      'как тебя отключить',
      'как выключить атласа',
      'где отключить тренера в настройках',
      'jak cię wyłączyć',
      'jak wyłączyć atlasa',
      'jak usunąć trenera z aplikacji',
    ],
  },
  app_role: {
    ex: [
      'should you be my main or secondary coach',
      'i already have a personal trainer, how do you fit in',
      'set you as my primary coach',
      'can you just give advice while my trainer does the plan',
      "what's the difference between main coach and extra coach",
      'make you my extra coach not main',
      'my pt writes my programme, can you support',
      'do you replace my real coach',
      'change your role to main coach',
      'what does extra coach mode do',
      'i work with a trainer, can you still help me',
      'can you run my whole program as main coach',
      'how do i change your coaching role',
      'are you the one planning my workouts or just helping',
      'switch from assistant coach to main coach',
    ],
    exUk: [
      'ти мій головний тренер чи допоміжний',
      'в мене є живий тренер, як ти з ним поєднуєшся',
      'зроби себе моїм основним тренером',
      'перемкни на режим додаткового тренера',
      'яка різниця між основним і додатковим тренером',
      'мій тренер пише програму, а ти що робиш',
      'ти заміняєш мого тренера?',
      'як змінити твою роль тренера',
      'можеш бути помічником а не основним',
      'ты мой основной тренер или дополнительный',
      'у меня есть личный тренер, зачем ты',
      'как переключить тебя на дополнительного тренера',
      'jesteś moim głównym trenerem',
      'mam trenera personalnego, jak mi pomożesz',
      'zmień się na dodatkowego trenera',
    ],
  },
  app_injury_log: {
    ex: [
      'where do i add an injury in the app',
      'how can i report an injury in the app',
      'i tweaked my back, how do i enter it in the app',
      'how to add my knee injury to my profile',
      'is there an injury section in the app',
      'how do i tell you about an injury so plan adjusts',
      'mark an injury in the app',
      'where is the injuries screen',
      'how to update or close an injury i logged',
      'can i log my shoulder injury here',
      'how to note an injury so workouts change',
      'add my wrist injury to the app',
      'where do i input injuries',
      'log new injury please',
      'how to register an injury in settings',
    ],
    exUk: [
      'де в додатку додати травму',
      'як відмітити травму в застосунку',
      'потягнув спину, як це внести в апку',
      'як додати травму коліна в профіль',
      'є розділ для травм у додатку?',
      'як закрити травму в додатку',
      'запиши мені травму плеча',
      'де вказати травму щоб програма підлаштувалась',
      'як зафіксувати травму в апці',
      'как добавить травму в приложении',
      'где отметить травму в приложении',
      'как записать травму колена в профиль',
      'jak dodać kontuzję w aplikacji',
      'gdzie zapisać kontuzję',
      'jak zgłosić kontuzję w apce',
    ],
  },
  are_you_ai: {
    ex: [
      'am i chatting with a real human',
      'is atlas a person or software',
      'are you artificial intelligence',
      'are you chatgpt',
      'is there a human behind this chat',
      "you're just a bot right",
      'are you a real trainer or a program',
      'is someone actually typing these replies',
      'what are you, a machine?',
      'are you powered by ai',
      'be honest, are you a robot',
      'is this an automated chat',
      'am i speaking to an actual coach',
      'are you human or ai',
      'is this a real person answering',
    ],
    exUk: [
      'ти штучний інтелект?',
      'я спілкуюсь з живою людиною?',
      'ти робот чи людина',
      'за тобою сидить людина?',
      'ти чатджпт?',
      'це автоматичні відповіді?',
      'ти справжній тренер чи програма',
      'скажи чесно, ти бот',
      'ти ші?',
      'ты искусственный интеллект?',
      'я общаюсь с живым человеком?',
      'ты бот или человек',
      'czy jesteś sztuczną inteligencją',
      'czy rozmawiam z prawdziwym człowiekiem',
      'jesteś botem?',
    ],
  },
  motivate: {
    ex: [
      'hype me up for leg day',
      'say something to get me off the couch',
      'i need a kick in the butt',
      'fire me up before my workout',
      'give me some motivation to lift',
      'tell me why i should go train',
      'get me pumped',
      'motivational quote please',
      'convince me to go to the gym',
      'pep talk before deadlifts',
      'encourage me to finish this workout',
      'hype me up',
      'say something inspiring',
      'give me energy to train',
      'push me, i need it',
    ],
    exUk: [
      'змотивуй мене',
      'дай мотивації на тренування',
      'скажи щось щоб я пішов у зал',
      'підбадьор мене трохи, треба йти в зал',
      'заряди мене перед тренуванням',
      'дай пенделя щоб я пішов качатись',
      'надихни мене',
      'мотивуюча фраза будь ласка',
      'переконай мене піти в зал',
      'мотивируй меня',
      'дай мотивации на тренировку',
      'вдохнови меня',
      'zmotywuj mnie',
      'daj mi motywację na trening',
      'przekonaj mnie żebym poszedł na siłownię',
    ],
  },
  done: {
    ex: [
      'all done for today',
      'finished my workout',
      'just wrapped up my session',
      'completed it',
      'workout complete',
      "that's it, done training",
      'smashed it, finished',
      'done with the session',
      "i'm done",
      'finished all sets',
      'trained today, done',
      'just got back from the gym, done',
      'session finished',
      "completed today's workout",
      'finito',
    ],
    exUk: [
      'все, закінчив',
      'тренування завершено',
      'все готово, потренувався',
      'відтренувався на сьогодні',
      'зробив тренування',
      'закінчив сьогоднішню тренку',
      'все зробив',
      'виконав',
      'відпрацював, готово',
      'закончил тренировку',
      'готово, всё сделал',
      'отзанимался',
      'skończyłem trening',
      'zrobione',
      'gotowe, po treningu',
    ],
  },
  bye: {
    ex: [
      'bye bye',
      'catch you later',
      'thanks, bye',
      'gotta go',
      'talk later',
      'cya',
      'good night',
      'see ya tomorrow',
      "that's all, bye",
      "i'm off, see you",
      'take care',
      'peace out',
      'thanks coach, later',
      'ok bye',
      'until next time',
    ],
    exUk: [
      'ну все, бувай',
      'до зустрічі, тренер',
      'папа, до завтра',
      'дякую, бувай',
      'до завтра',
      'все, я пішов',
      'на все добре',
      'добраніч',
      'давай, до побачення',
      'пока',
      'до свидания',
      'спасибо, пока',
      'cześć, na razie',
      'do zobaczenia',
      'pa pa',
    ],
  },
};
