export const KB_D2: Record<string, { ex: string[]; exUk: string[] }> = {
  plate_math: {
    ex: [
      'how do i make 100 kg with plates',
      'bar needs to read 125 kg, what goes on each end',
      'which discs do i slap on for 102.5',
      'load 60 for me',
      "i'm putting 180 on the bar, break it down per side",
      "what's the plate setup for 147.5 kg",
      'per side for 95 kg please',
      'tell me the plates to hit 110 kg',
      'what combination of plates makes 135 kg',
      '20 kg bar, target 100, what plates',
      'how many 20s and 10s for 140',
      'loading up 220 kg, which plates per side',
      'which plates make 87.5 kg',
      'what goes on the sleeves for 115 kg',
      'work out the plates for 165',
      'barbell loading for 105 kg',
      'i need the bar at 92.5, plate it out for me',
      'what do i stack on each side for 200',
      'how should i plate 57.5 kg',
      'figure out the plates for my 150 kg set',
      'one side for 120 kg, which plates',
      'can you do plate math for 72.5 kg',
      "i've got 25s, 20s, 10s and 5s, how do i build 155 kg",
      'red plates and what else for 110',
      'plates needed to load 250 kg',
    ],
    exUk: [
      'що вішати на 100 кг',
      'набери мені 125 кг млинцями',
      'як розкласти млинці на 102,5',
      'навішай 160, що на кожен бік',
      'яка комбінація блинів дає 135 кг',
      'скільки двадцяток і десяток на 140',
      'гриф 20, треба 100 кг, які млинці',
      'що накинути на гриф під 87,5',
      'розпиши млинці для 115 кг',
      'повісь мені 200 кг, що з кожного боку',
      'які диски почепити на 95',
      'хочу 57,5 кг, які млинці брати',
      'з одного боку на 120 кг — що вішати',
      'набрати 220 на штангу, по скільки з боку',
      'порахуй розкладку млинців на 150',
      'підкажи млинці під 72,5 кг',
      'маю млинці по 25, 20, 10 і 5, як зібрати 155',
      'як навісити 105 кг на штангу',
      'що нацепити на гриф на 165 кг',
      'скільки блинів треба на 250',
      'які млинці ставити щоб вийшло 92,5',
      'что вешать на 140 кг',
      'раскидай блины на 110 кг',
      'какие диски на штангу для 180',
      'сколько блинов с каждой стороны на 200',
    ],
  },
  reps_at_weight: {
    ex: [
      'with 90 on the bench, how many can i bang out',
      'how many would i get squatting 130',
      'if i load 150 on deadlift, how many reps is that for me',
      'how many clean reps at 60 on ohp',
      'rep estimate for 100 kg bench',
      'how deep a set can i do with 140 on squat',
      'reps i can hit with 200 kg deadlift',
      'at 70 kg overhead press, how many reps am i good for',
      'predict my reps on bench with 105',
      'how many times can i squat 110 kg',
      'how many deadlift reps at 170',
      'what rep count at 80 kg on rows',
      'if i try 95 on bench for reps, how many',
      'how many reps can i grind out at 125 on squat',
      'reps possible with 55 kg ohp',
      'how many would i get deadlifting 185',
      'bench 110, how many reps would i likely get',
      'how many reps can i do with 30 kg dumbbell press',
      'max reps with 80 kg on squat',
      'tell me my expected reps at 90 kg bench',
      'can i get 5 reps at 150 deadlift or fewer, how many',
      'how many pull-ups could i do with 10 kg added',
      'squat 140 for reps, how many',
      'how many reps at 120 kg on the deadlift',
      'reps to failure at 65 on the overhead press',
    ],
    exUk: [
      'скільки разів пожму 90',
      'присяду 130, на скільки разів мене вистачить',
      '150 у становій — скільки повторень зроблю',
      'скільки раз вижму 60 стоячи',
      'оцінка повторів на жимі з 100 кг',
      'скільки повторень присіду з 140',
      'скільки разів потягну 200 у становій',
      'армійський жим 70 кг, скільки раз',
      'на скільки повторень вистачить у жимі з 105',
      'скільки разів присяду з 110 кг',
      'скільки повторів у становій на 170',
      'тяга в нахилі 80 кг, скільки разів',
      'скільки повторень витисну з 95 лежачи',
      'скільки разів присяду 125',
      'скільки повторень на армійському з 55',
      'станова 185 — скільки разів потягну',
      'скільки раз пожму 110 кг',
      'максимум повторень з 80 у присіді',
      'скільки підтягнусь з обтяженням 10 кг',
      'скільки повторень зможу в становій із 120',
      'скільки разів підніму 65 над головою',
      'сколько раз пожму 90 кг',
      'на сколько повторов хватит в приседе со 130',
      'сколько раз потяну 150 в становой',
      'сколько повторений жим лежа с 105',
    ],
  },
  percent_max: {
    ex: [
      "what's 72.5% on bench",
      "i'm doing 3x5 at 80% squat, what weight",
      '85% deadlift, give me the number',
      'how heavy is 70% of my overhead press',
      "work sets at 75% on bench, what's that in kg",
      'what does 90% of my squat max come to',
      'percentage of 1rm: bench, 65',
      'calc 80% for my deadlift',
      'my program says 77.5% squat, how much is it',
      'tell me 60% of my ohp',
      'how many kilos is 95% of my bench',
      'i need a load at 70% of deadlift 1rm',
      'what weight should 82% bench be',
      'squat at 67% of max, what number',
      'give me 50 percent of my deadlift for speed work',
      '85% of 1rm on the bench is how much',
      "what's my squat at 75 percent",
      '70% overhead press weight',
      'program calls for deadlift at 88%, weight please',
      'convert 80% of my bench into kg',
      'what is ninety percent of my squat',
      'how much would 65% of my rows max be',
      'percent calc: 72% squat',
      '90% of my best deadlift',
      'at 75% of my bench max what do i load',
    ],
    exUk: [
      'скільки це 72,5% від жиму',
      'роблю 3 по 5 на 80% присіду, яка вага',
      '85% від станової, дай цифру',
      '70% від армійського це скільки кг',
      'робочі на 75% жиму, скільки кілограмів',
      '90% від максимуму в присіді скільки буде',
      'порахуй 80% від моєї станової',
      'у програмі 77,5% присіду, скільки вішати',
      '60% від жиму стоячи',
      '95% від жиму лежачи в кілограмах',
      'треба вага на 70% від станової',
      'яка вага 82% жиму лежачи',
      'присід на 67% від максу — скільки',
      '50 відсотків станової для швидкісної роботи',
      'скільки кг 85% від одноповторного на жимі',
      'присід на 75 відсотків, яка вага',
      '70% від армійського, скільки брати',
      'дев’яносто відсотків від присіду скільки',
      'переведи 80% жиму в кілограми',
      '65% від тяги в нахилі скільки',
      'сколько будет 85% от становой',
      '75 процентов от жима лежа это сколько',
      'посчитай 90% от приседа',
      'какой вес 70% от жима стоя',
      '80 процентов от максимума в становой',
    ],
  },
  warmup_lift: {
    ex: [
      'what should my ramp look like before bench',
      'give me warm-up jumps for squats',
      'how do i work up to a heavy deadlift',
      'list my warmup weights for ohp',
      'ramp me up to 140 on squat',
      'warm-up progression for the bench press',
      'what do i do before my working sets of deadlift',
      'how many kilos per jump when warming up squat',
      'warm up for pull-ups',
      'feeder sets for bench',
      'best way to get warm for heavy rows',
      "i'm about to squat heavy, how do i build up",
      'warmup scheme for romanian deadlift',
      'bench warmups before a top single',
      'should i start with the empty bar on squat and go up how',
      'warming up to 180 on deadlift, what steps',
      'how to prime for overhead press',
      'give me approach sets for bench',
      'ramp-up weights for front squat',
      'warm up protocol for leg press',
      "what's a good warm-up ladder to 100 on bench",
      'how do i warm up my deadlift without tiring myself out',
      'warmup for dips',
      'warming up for hip thrusts',
      'take me through a squat warm-up',
    ],
    exUk: [
      'як мені розігнатися до робочої на жимі',
      'підвідні підходи на присід, які ваги',
      'як вийти на важку станову',
      'розпиши розминочні ваги на армійський',
      'підведи мене до 140 у присіді',
      'розминка перед жимом, по кроках',
      'що робити перед робочими в становій',
      'з яким кроком піднімати вагу на розминці в присіді',
      'розминка на підтягування',
      'як розім’ятися на жим перед важким синглом',
      'підвідні на румунську тягу',
      'збираюся важко присідати, як підводитись',
      'з порожнього грифа до робочої в присіді — як',
      'розминка до 180 у становій',
      'як розігрітися на армійський жим',
      'підводящі на фронтальний присід',
      'розминочні сети на жим ногами',
      'як розминати станову щоб не втомитися',
      'розминка на бруси',
      'як розім’ятися на сідничний міст',
      'как подводиться к рабочему весу в жиме',
      'разминочные веса на становую',
      'как разогреться перед приседом',
      'подводки на армейский жим',
      'разминка на тягу в наклоне',
    ],
  },
  exercise_muscles: {
    ex: [
      'bench press hits what exactly',
      'what am i building with deadlifts',
      'which muscles get hammered in squats',
      'is overhead press a shoulder or tricep exercise',
      'pull-ups, what do they grow',
      'what are rows good for muscle wise',
      'does bench work triceps too',
      'what body parts does the leg press train',
      'hip thrust targets which muscles',
      "what's the main mover in a romanian deadlift",
      'which muscles fire during lunges',
      'what do face pulls hit',
      'is the deadlift a back or leg exercise',
      'muscles used in front squat',
      'what does the incline bench focus on',
      'lat pulldown, which muscles',
      'what does a chin-up train',
      'do dips hit chest or triceps',
      'which muscles do bulgarian split squats work',
      'what do good mornings strengthen',
      'does the overhead press work abs',
      'tell me the muscles in a barbell row',
      'what are the target muscles of the leg curl',
      'bicep curl, which muscles besides biceps',
      'primary and secondary muscles in the squat',
    ],
    exUk: [
      'жим лежачи що саме навантажує',
      'що я розвиваю становою',
      'які м’язи вбиває присід',
      'армійський жим — це на плечі чи трицепс',
      'підтягування що ростить',
      'тяга в нахилі на які м’язи',
      'жим лежачи трицепс теж качає?',
      'жим ногами на які частини тіла',
      'сідничний міст що тренує',
      'яка головна мишця в румунській тязі',
      'що працює у болгарських випадах',
      'фейс пул на що',
      'станова — це на спину чи на ноги',
      'фронтальний присід які м’язи задіює',
      'похилий жим на що впливає',
      'бруси — груди чи трицепс',
      'гуд монінг що зміцнює',
      'армійський жим прес теж навантажує?',
      'підйом на біцепс які ще м’язи працюють',
      'основні й допоміжні м’язи в присіді',
      'что работает в тяге штанги в наклоне',
      'на какие мышцы подтягивания',
      'жим ногами что качает',
      'какие мышцы в румынской тяге',
      'брусья на грудь или на трицепс',
    ],
  },
  alternatives: {
    ex: [
      'bench hurts my shoulder, what else could i do',
      'is there another option for squats',
      "what's a decent sub for deadlifts",
      "can't do pull-ups yet, what's similar",
      "what's comparable to leg press",
      'other options besides overhead press',
      'what exercise can stand in for dips',
      'what are some alternatives to barbell rows',
      'no cable machine, what instead of lat pulldown',
      "what's a good swap-in for romanian deadlift if my back is cranky",
      "gym's packed, rack is taken, what can i do instead of squats",
      'any bench press equivalents with dumbbells',
      'which movement replaces the deadlift for the same muscles',
      'is there something like lunges but easier on the knees',
      'hip thrust alternatives',
      'what else can i do if i hate front squats',
      "what's the closest thing to a chin-up",
      'suggest a replacement lift for the ohp',
      "i don't have a barbell, what can i do instead of rows",
      'leg press is broken, options',
      'what are my choices other than bulgarian split squats',
      'instead of face pulls, what works',
      'dumbbell version of bench press, what are the options',
      'what could i use in place of good mornings',
      'suggest alternatives for leg extensions',
    ],
    exUk: [
      'від жиму лежачи болить плече, що ще можна',
      'є інший варіант замість присіду',
      'яка нормальна заміна становій',
      'не вмію підтягуватися, що схоже',
      'що подібне до жиму ногами',
      'які є варіанти крім армійського жиму',
      'яка вправа може замінити бруси',
      'варіанти замість тяги штанги в нахилі',
      'нема блоку, що замість тяги верхнього блоку',
      'чим замінити румунську тягу якщо болить поперек',
      'стійка зайнята, що робити замість присіду',
      'аналоги жиму лежачи з гантелями',
      'яка вправа на ті ж м’язи що й станова',
      'щось як випади, але щоб коліна не боліли',
      'альтернативи сідничному мосту',
      'не люблю фронтальний присід, що є ще',
      'що найближче до підтягувань зворотним хватом',
      'нема штанги, чим замінити тягу в нахилі',
      'тренажер для жиму ногами зламаний, варіанти',
      'чим замінити болгарські випади',
      'что можно делать вместо жима лежа',
      'какая замена становой тяге',
      'аналог подтягиваний для новичка',
      'чем заменить жим ногами',
      'варианты вместо армейского жима',
    ],
  },
  sets_for_lift: {
    ex: [
      'how much bench volume per session in sets',
      'is 3 sets of squats enough',
      "what's a good set count for deadlift",
      'should i do 4 or 5 sets of overhead press',
      'how many rounds of pull-ups per workout',
      'how many sets do people usually do on rows',
      'optimal sets for romanian deadlift',
      'is 10 sets of bench overkill',
      'how many sets on leg press',
      'work sets for front squat, how many',
      'sets per workout for hip thrusts',
      'is one heavy set of deadlift enough',
      'how many sets of dips should i be doing',
      'set count for lat pulldown',
      'should i do more sets of bench to grow',
      'how many sets of curls',
      'how many sets for incline press',
      'how many sets per week on squats',
      'am i doing too many sets of deadlift with 6',
      'bench: 3 sets or 5',
      'how many sets for bulgarian split squats',
      'how many sets do i need on overhead press to progress',
      'number of sets for face pulls',
      'how many sets of chin-ups',
      'how many sets of barbell rows is ideal',
    ],
    exUk: [
      '3 підходи присіду вистачить?',
      'скільки сетів станової нормально',
      '4 чи 5 підходів на армійський',
      'скільки підходів підтягувань за трен',
      'оптимально скільки сетів румунської тяги',
      '10 сетів жиму — це перебір?',
      'скільки підходів на жим ногами',
      'робочі сети на фронтальний присід, скільки',
      'скільки підходів сідничного мосту',
      'одного важкого сету станової досить?',
      'скільки підходів на бруси треба',
      'скільки сетів тяги блоку',
      'щоб ріс жим, більше сетів робити?',
      'скільки підходів на біцепс зі штангою',
      'скільки сетів похилого жиму',
      'скільки підходів присіду на тиждень',
      '6 сетів станової це забагато?',
      'жим: 3 сети чи 5',
      'скільки підходів болгарських випадів',
      'скільки сетів тяги в нахилі ідеально',
      'сколько подходов становой делать',
      '3 подхода жима лежа хватит?',
      'сколько сетов подтягиваний',
      'сколько подходов армейского жима',
      'сколько подходов на брусья',
    ],
  },
  day_lookup: {
    ex: [
      "monday's session, what was in it",
      'what exercises were on wednesday',
      "pull up friday's training",
      'what did i lift tuesday',
      'thursday workout recap',
      'what did i get done on saturday',
      'what happened on sunday in the gym',
      'show what i logged on monday',
      'what was the workout this past wednesday',
      'i forgot what i did on friday',
      'which lifts did i do tuesday',
      'did i squat on thursday',
      "what was saturday's training",
      'what did i do at the gym on sunday',
      'show friday',
      'monday: what did i train',
      'tell me what my wednesday workout was',
      'what did i work on tuesday',
      "what was on thursday's log",
      'saturday session details',
      'what did i train sunday morning',
      'list what i did on monday',
      "can you show wednesday's session",
      'what sets did i do on friday',
      'what was my tuesday lifting',
    ],
    exUk: [
      'що було на тренуванні в понеділок',
      'які вправи були в середу',
      'покажи п’ятничне тренування',
      'що я тягав у вівторок',
      'четвергове тренування, що там було',
      'що я встиг зробити в суботу',
      'що було в залі в неділю',
      'покажи, що я записав у понеділок',
      'забув, що робив у п’ятницю',
      'які вправи були у вівторок',
      'я присідав у четвер?',
      'суботнє тренування покажи',
      'що я тренувала в неділю',
      'що було в середу в залі',
      'понеділок — що тренував',
      'які підходи я робив у п’ятницю',
      'що в мене було у вівторок',
      'покажи четвер',
      'що я качав у суботу',
      'нагадай, що було в неділю',
      'что было в пятницу на тренировке',
      'какие упражнения во вторник делал',
      'покажи тренировку в четверг',
      'что я качал в субботу',
      'что было в воскресенье в зале',
    ],
  },
  compare_weeks: {
    ex: [
      'am i ahead or behind last week',
      'did this week beat last week',
      "how's my week stacking up against the last one",
      'week to week, how am i doing',
      'am i training harder than last week',
      'put this week next to last week',
      'was this week lighter than the previous one',
      'more or fewer workouts this week than last',
      'compare my current week with the one before',
      'did my volume go up from last week',
      'how does this week look versus last',
      'this week or last, which was bigger',
      'is this week a step down from last week',
      'how different is this week from the last one',
      'did i slack compared to last week',
      'numbers this week vs numbers last week',
      'have i lifted more than last week so far',
      'am i on pace with last week',
      'this week against the previous week, sets and sessions',
      'is this week better or worse than last week',
      'last week vs this week, show me',
      'did i do fewer sets this week than the week before',
      'difference between this week and last week',
      'stack this week up against last week',
      'how do the two weeks compare, this and last',
    ],
    exUk: [
      'я випереджаю минулий тиждень чи відстаю',
      'цей тиждень кращий за минулий?',
      'як мій тиждень виглядає проти попереднього',
      'тиждень до тижня, як я',
      'я тренуюся більше ніж минулого тижня?',
      'постав поруч цей і минулий тиждень',
      'цей тиждень легший ніж попередній?',
      'більше чи менше тренувань цього тижня ніж минулого',
      'чи зріс обсяг порівняно з минулим тижнем',
      'який тиждень був об’ємніший, цей чи минулий',
      'я розслабився порівняно з минулим тижнем?',
      'цифри цього тижня проти минулого',
      'чим цей тиждень відрізняється від минулого',
      'я йду в темпі минулого тижня?',
      'менше сетів цього тижня ніж попереднього?',
      'різниця між цим і минулим тижнем',
      'минулий тиждень і цей — порівняй',
      'цей тиждень гірший чи кращий за минулий',
      'за сетами і тренуваннями цей тиждень проти минулого',
      'я вже зробив більше ніж минулого тижня?',
      'эта неделя лучше прошлой?',
      'сравни текущую неделю с предыдущей',
      'я тренируюсь больше чем на прошлой неделе?',
      'разница между этой и прошлой неделей',
      'меньше подходов на этой неделе чем на прошлой?',
    ],
  },
  short_on_time: {
    ex: [
      'got half an hour, make it count',
      'running late, only 20 min in the gym',
      "what's the most efficient thing i can do in 25 minutes",
      'i can squeeze in a quick one, maybe 30 min',
      'tight schedule today, shortest effective workout',
      '10 minutes is all i have',
      'gym closes in 35 minutes, what do i do',
      'lunch break workout, 40 minutes',
      'express session please',
      "what's worth doing if i only have a few minutes",
      "cut today's workout down, i'm pressed for time",
      'i have to leave soon, give me the essentials',
      'minimum effective dose today, 20 minutes',
      "i'm short on time, which exercises should i keep",
      'need to be out of here in half an hour',
      'quickest possible workout',
      'i only get 15 min between meetings',
      'hurry mode, 30 min',
      'what can i fit into 25 minutes',
      "don't have an hour today, maybe 35 minutes",
      "condensed version of my workout, i'm in a hurry",
      'busy day, is a 20 minute session worth it',
      "what's the priority if i've only got 30 minutes",
      'speed workout, limited time',
      'give me a shortened session, i have little time',
    ],
    exUk: [
      'маю пів години, зроби, щоб було ефективно',
      'запізнююсь, в залі лише 20 хв',
      'що найефективніше за 25 хвилин',
      'встигну хіба на 30 хвилин',
      'сьогодні щільний графік, найкоротше тренування',
      'в мене тільки 10 хвилин',
      'зал закривається через 35 хвилин, що робити',
      'тренування в обідню перерву, 40 хвилин',
      'експрес тренування дай',
      'скороти сьогоднішнє, бо часу обмаль',
      'мушу скоро йти, дай тільки головне',
      'мінімум на сьогодні, 20 хвилин',
      'часу мало, які вправи залишити',
      'треба звалити через пів години',
      'найшвидше тренування яке можна',
      'маю 15 хв між зустрічами',
      'що влізе в 25 хвилин',
      'години нема, десь 35 хвилин',
      'стиснута версія тренування, поспішаю',
      'що в пріоритеті, якщо є лише 30 хвилин',
      'у меня полчаса, что сделать',
      'времени мало, дай короткую тренировку',
      'есть 20 минут в зале',
      'спешу, что успею за 25 минут',
      'сократи тренировку, нет времени',
    ],
  },
  two_days_row: {
    ex: [
      'is it fine to hit legs back to back',
      'trained yesterday, can i go again today',
      'is lifting on consecutive days bad for recovery',
      'can i bench two days straight',
      'gym today and tomorrow, is that ok',
      'does training daily hurt gains',
      'same muscle group on back-to-back days, yes or no',
      'i went yesterday, should i skip today or go again',
      'working out seven days a week, good idea',
      'is it safe to deadlift on consecutive days',
      'back two days in a row too much',
      'can i train without a rest day between sessions',
      'lifting every single day, bad or fine',
      'two days straight of upper body, ok',
      'is daily training a problem',
      'hit shoulders yesterday, can i do them again today',
      'is it counterproductive to lift on back to back days',
      'do i need a day off between workouts',
      'can i squat on consecutive days',
      'arms yesterday and today, is that overtraining',
      'full body two days running, fine',
      'gym streak without rest days, safe',
      'train consecutive days as a beginner',
      'is it bad to go to the gym daily',
      'two workouts on two consecutive days for the same muscles',
    ],
    exUk: [
      'можна ноги два дні підряд',
      'тренувався вчора, можна і сьогодні',
      'тренування кожен день шкодить відновленню?',
      'жим два дні поспіль — нормально?',
      'зал сьогодні і завтра, це ок',
      'щоденні тренування заважають росту?',
      'одна група м’язів два дні поспіль, так чи ні',
      'був учора, йти сьогодні знову?',
      'тренуватися сім днів на тиждень — ідея?',
      'станова два дні підряд безпечно?',
      'спина два дні поспіль — не забагато',
      'можна без дня відпочинку між тренуваннями',
      'качатися кожен божий день — погано?',
      'верх два дні підряд норм',
      'вчора плечі, можна сьогодні знову',
      'потрібен вихідний між тренуваннями?',
      'присідати кілька днів поспіль можна',
      'руки вчора і сьогодні — це перетренованість?',
      'фулбоді два дні поспіль',
      'новачку можна тренуватися щодня?',
      'можно качаться два дня подряд',
      'тренировки без выходных это нормально',
      'ходить в зал ежедневно вредно?',
      'грудь два дня подряд можно',
      'вчера тренировался, сегодня можно опять?',
    ],
  },
  two_a_day: {
    ex: [
      'does splitting my training into am and pm sessions help',
      'gym in the morning and again at night',
      'is double day training worth it for a natural',
      'two lifting sessions in one day, good or bad',
      'should i train twice daily to grow faster',
      'morning weights, evening run, same day ok',
      'can i hit the gym two times in one day',
      'doubles like olympic lifters, should i',
      'two short workouts a day instead of one long',
      'is training twice per day overkill',
      'i want to do two sessions daily, how to structure',
      'cardio in the morning and weights at night, fine',
      'can i lift at 7 am and again at 6 pm',
      'twice-a-day training for fat loss',
      'is a second session the same day useful',
      'two workouts in one day, too much recovery wise',
      'should i break my workout into two a day',
      'am and pm training sessions',
      'is it okay to go to the gym morning and evening',
      'two-a-days for a beginner',
      'can i do legs in the morning and upper in the evening',
      'second workout later today, good idea',
      'how to recover when training twice a day',
      'does doing two sessions a day burn more fat',
      'i have time for two gym visits a day, should i',
    ],
    exUk: [
      'розбити тренування на ранок і вечір — є сенс',
      'зал зранку і ще раз увечері',
      'два тренування в один день натуралу варто?',
      'два силових за день — добре чи погано',
      'тренуватися двічі на день щоб швидше рости',
      'зранку залізо, ввечері біг в той самий день',
      'можна сходити в зал два рази за день',
      'два коротких тренування на день замість одного довгого',
      'двічі на день — перебір?',
      'хочу два тренування щодня, як побудувати',
      'кардіо зранку, штанга ввечері — нормально',
      'о 7 ранку і о 18 знову в зал',
      'друге тренування того ж дня корисне?',
      'два трени за день, відновлення витягне?',
      'ранкове і вечірнє тренування, чи варто',
      'новачку двічі на день можна',
      'ноги зранку, верх увечері',
      'як відновлюватися якщо тренуюсь двічі на день',
      'два заняття на день більше палять жиру?',
      'можу ходити в зал двічі на день, треба?',
      'две тренировки в один день, есть смысл',
      'качаться утром и вечером можно',
      'тренировки дважды в день для похудения',
      'утром кардио, вечером железо',
      'два раза в день в зал не много?',
    ],
  },
  health_conditions: {
    ex: [
      "i'm on blood pressure meds, can i lift heavy",
      'is strength training safe with hypertension',
      'type 1 diabetic, anything to watch in the gym',
      'exercise induced asthma and lifting',
      'had a heart attack last year, can i train',
      'i have a heart murmur, weights ok',
      'does holding my breath on squats matter with high bp',
      'lifting with atrial fibrillation',
      "blood sugar drops when i train, i'm diabetic",
      'my cardiologist cleared me, how should i lift',
      'insulin and weight training',
      'high blood pressure, should i avoid heavy deadlifts',
      'copd and the gym',
      'pre-diabetic, will lifting help',
      'tachycardia, is heavy lifting risky',
      'i have a pacemaker, can i do strength training',
      'managing asthma during workouts',
      "i have a chronic heart condition, what's safe",
      'hypertensive and want to bench, precautions',
      'gym tips for someone with type 2 diabetes',
      'is valsalva dangerous with high blood pressure',
      'lifting after a stroke',
      'i have high cholesterol and blood pressure, is weight training ok',
      'should diabetics lift fasted',
      'asthmatic lifter, how do i handle cardio days',
    ],
    exUk: [
      'п’ю таблетки від тиску, можна важко',
      'силові безпечні при гіпертонії?',
      'діабет першого типу, на що зважати в залі',
      'астма фізичного навантаження і штанга',
      'був інфаркт торік, можна тренуватися',
      'шуми в серці, ваги можна?',
      'затримка дихання в присіді при високому тиску — погано?',
      'фібриляція передсердь і силові',
      'цукор падає на тренуванні, я діабетик',
      'кардіолог дозволив, як тренуватися',
      'інсулін і силові тренування',
      'високий тиск — уникати важкої станової?',
      'переддіабет, силові допоможуть?',
      'тахікардія, важкі ваги небезпечно?',
      'у мене кардіостимулятор, можна силові',
      'хронічна хвороба серця, що безпечно',
      'після інсульту можна в зал?',
      'підвищений холестерин і тиск, силові ок?',
      'діабетику тренуватися натще можна',
      'астматик, як бути з кардіо',
      'гипертония, можно ли жать штангу',
      'сахарный диабет и тренажерный зал',
      'астма, можно ли тяжелые тренировки',
      'проблемы с сердцем, что можно в зале',
      'высокое давление и становая тяга',
    ],
  },
  peds: {
    ex: [
      'thinking about juicing, thoughts',
      'is a test cycle safe if done right',
      'how much test should a first cycle be',
      'what about anavar for cutting',
      'should i hop on gear',
      'sarms vs steroids, which is safer',
      'can you recommend a dosage of trenbolone',
      'my friend is on cycle and growing fast, should i',
      'is hgh worth it for muscle',
      "what's pct and do i need it",
      'can i get big without roids',
      'blast and cruise, is that a good idea',
      'which steroid has the least side effects',
      'is ostarine safe',
      'thoughts on enhanced vs natty training',
      'should i get on trt at 25',
      'how do steroids affect recovery',
      'is dianabol good for bulking',
      'are prohormones legal and safe',
      'chemically assisted lifting, worth it',
      'how long until i see results on a cycle',
      'do pros all use steroids',
      'is taking gear cheating in powerlifting',
      'would a small dose of test help my bench',
      'should women take anavar',
    ],
    exUk: [
      'думаю сісти на курс, що скажеш',
      'курс тесту безпечний якщо правильно',
      'скільки тестостерону на перший курс',
      'анавар на сушці — варто?',
      'може підколотися',
      'сарми чи стероїди, що безпечніше',
      'підкажи дозування тренболону',
      'друг на курсі швидко росте, мені теж?',
      'гормон росту варто брати',
      'що таке ПКТ і чи треба',
      'реально набрати без хімії?',
      'бласт і круїз — нормальна ідея',
      'який стероїд з найменшими побічками',
      'остарин безпечний?',
      'замісна терапія тестостероном в 25 років',
      'метан для набору маси',
      'прогормони легальні?',
      'усі профі на хімії?',
      'фарма в пауерліфтингу — це нечесно?',
      'невелика доза тесту підніме жим?',
      'стоит ли садиться на курс',
      'сколько колоть тестостерон новичку',
      'химия или натурал, что выбрать',
      'оксандролон для девушек можно',
      'посоветуй дозировку метана',
    ],
  },
  cycle: {
    ex: [
      "it's that time of the month, should i still lift",
      'does the luteal phase make me weaker',
      'should i deload on my period',
      'follicular phase, time to go heavy?',
      'bloated and crampy from my period, workout or rest',
      'how should women adjust training to their cycle',
      'is my bench worse before my period',
      'periods and pr attempts',
      'training through menstrual cramps',
      'why am i so tired during my period at the gym',
      'should i plan heavy days around ovulation',
      'on my period and feel weak, lower the weights?',
      'is it safe to deadlift on my period',
      'strength changes across the menstrual cycle',
      'does birth control affect my cycle and training',
      'pms is killing my motivation to lift',
      'light workout ideas for period days',
      'menstruation week, how should i train',
      'should i change my program every cycle phase',
      'cycle tracking for lifters',
      'my period started today, skip leg day?',
      'heavy flow day, should i still squat',
      'does training on my period help cramps',
      'when in my cycle am i strongest',
      'hormonal cycle and gym performance',
    ],
    exUk: [
      'в мене ці дні, тренуватися?',
      'лютеїнова фаза робить слабшою?',
      'розвантаження на місячних робити?',
      'фолікулярна фаза — час для важких ваг?',
      'здуття і спазми від місячних, зал чи відпочинок',
      'як жінкам підлаштовувати тренування під цикл',
      'перед місячними жим гірший?',
      'місячні і спроби рекорду',
      'тренуватися при болях від менструації',
      'чому я така втомлена в залі на місячних',
      'планувати важкі дні навколо овуляції',
      'на місячних слабкість, зменшити ваги?',
      'станова під час місячних безпечно?',
      'як змінюється сила протягом циклу',
      'протизаплідні впливають на цикл і тренування?',
      'пмс вбиває мотивацію',
      'легке тренування на критичні дні',
      'почались місячні, пропустити ноги?',
      'коли в циклі я найсильніша',
      'тренування допомагають від болю під час місячних?',
      'у меня месячные, идти в зал?',
      'как тренироваться в разные фазы цикла',
      'пмс и тренировки',
      'критические дни, можно приседать',
      'слабость на месячных, снизить вес?',
    ],
  },
  pregnancy: {
    ex: [
      'expecting a baby, can i keep squatting',
      'is lifting weights safe in the first trimester',
      'how should i modify training while pregnant',
      'can i still deadlift at 20 weeks pregnant',
      'six weeks postpartum, can i start lifting',
      'c-section recovery and weight training',
      'diastasis recti after birth, what exercises',
      'pregnant and want to stay strong, plan',
      'should pregnant women avoid lying on their back for bench',
      'second trimester lifting guidelines',
      'returning to heavy squats after having a baby',
      'pelvic floor and lifting after pregnancy',
      'how heavy can i lift while expecting',
      "i'm 30 weeks pregnant, what can i still do",
      'breastfeeding and strength training',
      'can i do core work while pregnant',
      'postnatal gym routine',
      'my wife is pregnant, can she keep lifting',
      'is it ok to keep training in late pregnancy',
      'baby is 3 months old, how do i get back into lifting',
      'prenatal strength training tips',
      'lifting during pregnancy, what to avoid',
      'is overhead press safe while pregnant',
      'when is it safe to run and lift after childbirth',
      'maternity workout adjustments',
    ],
    exUk: [
      'чекаю дитину, можна далі присідати',
      'силові в першому триместрі безпечні?',
      'як змінити тренування під час вагітності',
      'станова на 20 тижні вагітності можна?',
      'шість тижнів після пологів, можна в зал',
      'відновлення після кесаревого і силові',
      'діастаз після пологів, які вправи',
      'вагітна, хочу залишатися сильною',
      'вагітним не можна лежати на спині на жимі?',
      'силові в другому триместрі',
      'повернутися до важких присідів після народження дитини',
      'тазове дно і силові після вагітності',
      'яку вагу можна піднімати вагітній',
      'я на 30 тижні, що ще можна робити',
      'грудне вигодовування і силові',
      'прес під час вагітності можна?',
      'дружина вагітна, їй можна тренуватися?',
      'дитині 3 місяці, як повернутися в зал',
      'армійський жим вагітним безпечно?',
      'беременность и становая тяга',
      'когда можно в зал после кесарева',
      'тренировки в первом триместре',
      'что нельзя делать беременным в зале',
      'как вернуться к тренировкам после родов',
      'можно ли качать пресс беременной',
    ],
  },
  hr_zones: {
    ex: [
      'what bpm should my easy cardio be',
      'zone 2, how do i calculate it',
      'is 150 bpm too high for steady state',
      'conversational pace heart rate',
      "zone 5 vs zone 2, what's the difference",
      'heart rate for aerobic base building',
      '220 minus age, is that accurate for max heart rate',
      'my watch says zone 3, is that fine for fat loss',
      'what pulse should i keep on the bike',
      'how many beats per minute is zone two for a 30 year old',
      'should i stay under 140 bpm when jogging',
      'what does training in zone 4 do',
      'fat burning zone, real or myth',
      'low intensity steady state heart rate',
      'best heart rate zone for endurance',
      'why does my heart rate spike so fast on cardio',
      'what are the five heart rate zones',
      'can i do zone 2 on the stairmaster',
      'is my resting heart rate important for zones',
      'how hard should i breathe in zone 2',
      'target bpm for cardio sessions',
      'maf heart rate method',
      'lactate threshold heart rate, what is it',
      'does zone 2 help recovery between lifting days',
      'heart rate training for beginners',
    ],
    exUk: [
      'який пульс на легкому кардіо',
      'зона 2, як її порахувати',
      '150 ударів забагато для рівного кардіо?',
      'пульс, коли можеш розмовляти',
      'зона 5 і зона 2, в чому різниця',
      'пульс для аеробної бази',
      '220 мінус вік — це точно максимальний пульс?',
      'годинник показує зону 3, це ок для схуднення',
      'на якому пульсі крутити велик',
      'скільки ударів на хвилину зона два в 30 років',
      'треба тримати пульс нижче 140 на пробіжці?',
      'що дає тренування в зоні 4',
      'зона жироспалення — міф?',
      'найкраща пульсова зона для витривалості',
      'чому пульс так швидко злітає на кардіо',
      'які бувають пульсові зони',
      'пульс у спокої впливає на зони?',
      'як важко дихати в зоні 2',
      'цільовий пульс для кардіо',
      'пульс анаеробного порогу що це',
      'какой пульс держать на дорожке',
      'как рассчитать вторую пульсовую зону',
      'зона жиросжигания по пульсу',
      'пульс 160 на кардио это много?',
      'пульсовые зоны для новичка',
    ],
  },
  hiit: {
    ex: [
      'give me a sprint interval workout',
      '30 seconds on 30 off, is that good',
      'should i do intervals on rest days',
      'hiit vs liss for cutting',
      'how many hiit sessions a week alongside lifting',
      'rower intervals plan',
      'does high intensity interval training burn fat after',
      'emom conditioning for lifters',
      'air bike intervals, how long',
      'is tabata real hiit',
      'can hiit replace steady cardio',
      'work to rest ratio for intervals',
      'hill sprints how many',
      'hiit after leg day, bad idea?',
      '4x4 intervals, how to do them',
      'short intense cardio vs long slow cardio',
      'how hard should hiit feel',
      '10 minute interval finisher',
      'does hiit hurt recovery for squats',
      'sprint intervals on the treadmill for beginners',
      'how many minutes of hiit is enough',
      'interval cardio before or after weights',
      'tabata protocol explained',
      'burpee intervals worth it',
      "what's a good hiit warm-up and cooldown",
    ],
    exUk: [
      'дай тренування зі спринтами-інтервалами',
      '30 секунд робота 30 відпочинок — норм?',
      'інтервали в дні відпочинку робити?',
      'hiit чи рівне кардіо на сушці',
      'скільки інтервальних на тиждень разом із силовими',
      'інтервали на гребному тренажері',
      'високоінтенсивні інтервали спалюють жир після?',
      'емом кондиція для силовиків',
      'скільки робити інтервали на ейрбайку',
      'табата — це справжній хііт?',
      'інтервали можуть замінити звичайне кардіо?',
      'співвідношення роботи і відпочинку в інтервалах',
      'спринти в гору, скільки',
      'хііт після ніг — погана ідея?',
      'інтервали 4 по 4, як робити',
      'яким важким має бути хііт',
      '10 хвилин інтервалів на добивку',
      'інтервали заважають відновленню для присіду?',
      'скільки хвилин хііту достатньо',
      'інтервали до чи після заліза',
      'интервалы на беговой дорожке для начинающих',
      'сколько раз в неделю делать hiit',
      'табата протокол как работает',
      'интервальное кардио или обычное для сушки',
      'хиит после тренировки ног можно?',
    ],
  },
  running: {
    ex: [
      'i run 3 times a week, how do i fit lifting in',
      'half marathon training plus gym',
      'will jogging eat my muscle',
      'best split for a runner who lifts',
      'should runners squat heavy',
      'long run the day after leg day, ok?',
      'how to lift while training for a 10k',
      'hybrid athlete, running and strength',
      'can running make me a better lifter',
      'running on the same day as deadlifts',
      "i'm a runner, do i need the gym",
      'how many km a week can i run without losing strength',
      'couch to 5k while doing a strength program',
      'running after lifting or separate day',
      'trail running and weight training',
      'does running hurt squat progress',
      'strength training for marathon runners',
      'my legs are dead from running, should i still do leg day',
      'treadmill runs on upper body days',
      'will running slow down my bulk',
      'adding runs to my lifting plan',
      'tempo runs and heavy squats in one week',
      'should i reduce leg volume if i start running',
      'morning run, evening lift, how to recover',
      'running to get lean while keeping muscle',
    ],
    exUk: [
      'бігаю 3 рази на тиждень, як вписати зал',
      'підготовка до напівмарафону плюс зал',
      'біг з’їсть м’язи?',
      'спліт для бігуна, який качається',
      'бігунам треба важко присідати',
      'довгий біг наступного дня після ніг — ок?',
      'як качатися, коли готуюсь до 10 км',
      'гібридний атлет, біг і сила',
      'біг допоможе бути сильнішим у залі?',
      'бігати в день станової',
      'я бігун, мені потрібен зал?',
      'скільки км на тиждень бігати, щоб не втратити силу',
      'біг після залу чи в окремий день',
      'трейл і силові тренування',
      'біг гальмує присід?',
      'силові для марафонця',
      'ноги вбиті від бігу, робити день ніг?',
      'біг сповільнить набір маси?',
      'додати пробіжки до плану в залі',
      'якщо почну бігати, зменшити обсяг на ноги?',
      'бег съест мышцы?',
      'как совмещать бег и силовые',
      'подготовка к марафону и качалка',
      'бегать после тренировки или в отдельный день',
      'бег мешает приседу?',
    ],
  },
  steps: {
    ex: [
      'is 8k steps enough',
      'should lifters care about step count',
      'walking 15000 steps a day, too much for recovery',
      'does walking burn fat or just calories',
      'i sit all day, how many steps should i aim for',
      'neat and steps, how important',
      'should i walk on my rest days or stay still',
      'will more steps help me cut',
      'my step count is low, does it matter',
      'is walking after dinner useful',
      'how many steps equals a cardio session',
      'do i need 10k steps if i lift 4 times a week',
      'incline walking or just more steps',
      'daily walk vs treadmill cardio',
      'does walking hurt muscle gain',
      'step target on a bulk',
      'how much should i walk daily to stay lean',
      'is 5000 steps a day ok',
      'walk more or cardio more to lose weight',
      'does my phone step count matter',
      'should i increase steps during a cut',
      'walking is my only cardio, is that enough',
      'does a long walk help sore legs',
      'steps per day for general health',
      'how many kilometers should i walk each day',
    ],
    exUk: [
      '8 тисяч кроків вистачить?',
      'силовику варто стежити за кроками',
      '15000 кроків на день — не заважає відновленню?',
      'ходьба спалює жир чи просто калорії',
      'сиджу весь день, скільки кроків ставити за ціль',
      'побутова активність і кроки, наскільки важливо',
      'у дні відпочинку ходити чи лежати',
      'більше кроків допоможе на сушці?',
      'в мене мало кроків, це важливо?',
      'прогулянка після вечері корисна?',
      'скільки кроків дорівнює кардіо',
      'потрібно 10 тисяч кроків, якщо тренуюсь 4 рази',
      'ходьба в гору чи просто більше кроків',
      'ходьба заважає набору маси?',
      'скільки кроків на масі',
      'скільки ходити щоб бути сухим',
      '5000 кроків на день нормально?',
      'більше ходити чи більше кардіо щоб схуднути',
      'ходьба — моє єдине кардіо, достатньо?',
      'довга прогулянка допоможе від крепатури в ногах',
      '10 тысяч шагов обязательно?',
      'сколько ходить пешком для похудения',
      'шаги на сушке увеличивать?',
      'ходьба вместо кардио подойдет?',
      'сколько километров в день проходить',
    ],
  },
  posture: {
    ex: [
      'my shoulders roll forward, how do i fix that',
      'tech neck, what exercises',
      'anterior pelvic tilt fix',
      'i slouch all the time, can lifting help',
      'forward head posture exercises',
      'upper crossed syndrome routine',
      'how do i stand up straighter',
      'does bench press cause rounded shoulders',
      'desk job hunchback, what to train',
      'rows to fix posture, how many',
      'my back is rounded from sitting, help',
      'strengthen my upper back to stop slouching',
      'is my posture bad if my shoulders are uneven',
      'exercises to pull shoulders back',
      'does deadlifting fix posture',
      'i look hunched in photos, what can i do',
      'chest too tight, shoulders rolled in',
      'how long to fix posture with training',
      'gym routine for better posture',
      'does a weak core cause bad posture',
      'band pull-aparts for posture',
      'my lower back arches too much when standing',
      'fix hunching over the laptop',
      'i want better posture, where do i start',
      'stretches and exercises for rounded back',
    ],
    exUk: [
      'плечі завалюються вперед, як виправити',
      'шия вперед від телефона, які вправи',
      'передній нахил таза як виправити',
      'постійно сутулюся, зал допоможе?',
      'вправи від голови, висунутої вперед',
      'як стояти рівніше',
      'жим лежачи робить плечі круглими?',
      'сиджу в офісі, горблюсь, що тренувати',
      'тяги для постави, скільки робити',
      'спина кругла від сидіння, допоможи',
      'зміцнити верх спини, щоб не сутулитися',
      'плечі на різній висоті, це погана постава?',
      'вправи, щоб розвести плечі назад',
      'станова виправляє поставу?',
      'на фото виглядаю згорбленим, що робити',
      'скільки часу треба щоб виправити поставу',
      'слабкий прес псує поставу?',
      'поперек дуже прогинається, коли стою',
      'горблюсь за ноутбуком, як виправити',
      'хочу рівну спину, з чого почати',
      'как убрать сутулость в зале',
      'плечи вперед, что делать',
      'упражнения для ровной спины',
      'осанка от сидячей работы',
      'как выпрямить спину тренировками',
    ],
  },
  other_sport: {
    ex: [
      'i do judo, how should i structure my lifting',
      'strength program for a volleyball player',
      'how much gym work for a sprinter',
      'hockey player off-season lifting',
      'i play rugby, what should i focus on in the gym',
      'muay thai and weights, how to balance',
      'does lifting slow down a boxer',
      'wrestling season, how often to lift',
      'gym for a rower',
      'strength training for skiing',
      'lifting to improve my golf swing',
      'handball player gym routine',
      'i surf, what should i train',
      'track and field athlete, weights plan',
      'strength work for badminton',
      'crossfit alongside my football training',
      'should a cyclist squat heavy',
      'gym for a martial artist twice a week',
      'how to lift in-season for soccer',
      'does weight training help swimming speed',
      'climber here, should i do pull-ups in the gym',
      'strength and conditioning for jiu jitsu',
      'lifting schedule around basketball practice',
      'kickboxing plus gym, how many days',
      'gym plan for a tennis player off season',
    ],
    exUk: [
      'займаюсь дзюдо, як будувати силові',
      'силова програма для волейболіста',
      'скільки залу треба спринтеру',
      'хокеїст, силові в міжсезоння',
      'граю в регбі, на що робити акцент у залі',
      'тайський бокс і залізо, як поєднати',
      'силові роблять боксера повільнішим?',
      'сезон боротьби, як часто в зал',
      'зал для веслувальника',
      'силові для лиж',
      'зал для гольфу, щоб покращити удар',
      'легкоатлет, план силових',
      'кросфіт разом з футболом',
      'велосипедисту важко присідати треба?',
      'єдиноборства і зал двічі на тиждень',
      'як качатися під час футбольного сезону',
      'силові допомагають плавати швидше?',
      'скелелаз, підтягування в залі робити?',
      'розклад залу навколо баскетбольних тренувань',
      'кікбоксинг плюс зал, скільки днів',
      'качалка для борца',
      'силовые для хоккеиста',
      'как совмещать бокс и тренажерку',
      'зал для волейболиста',
      'силовая подготовка для бегуна на короткие дистанции',
    ],
  },
  home_equipment: {
    ex: [
      'i have 500 dollars, what gear for a home gym',
      'power rack or squat stands for home',
      'is a cheap barbell set worth buying',
      'kettlebell or dumbbells for my flat',
      'what weights should i get for home training',
      'best flooring for a garage gym',
      'do i need an olympic bar at home',
      'resistance bands worth buying',
      'home gym shopping list',
      'which adjustable bench should i buy',
      'how many plates do i need for a home setup',
      'is a cable machine worth it at home',
      "what's the first thing to buy for a basement gym",
      'doorway pull-up bar, any good',
      'fold-away rack for a small room',
      'buying used gym equipment, what to check',
      'what kettlebell weight to buy',
      "i'm setting up a gym in my spare room, what do i need",
      'trap bar for home, worth it',
      'rubber or iron plates for home',
      'treadmill or rower for home cardio',
      'home gym on a tight budget',
      'which dumbbell set should i order',
      'rings or pull-up bar for home',
      'what equipment gives the most bang for buck at home',
    ],
    exUk: [
      'маю 20 тисяч гривень, що купити в домашній зал',
      'силова рама чи стійки для дому',
      'дешевий набір зі штангою варто брати?',
      'гиря чи гантелі в квартиру',
      'які ваги купити для тренувань удома',
      'яке покриття на підлогу в гаражний зал',
      'олімпійський гриф додому потрібен?',
      'резинки варто купувати?',
      'список покупок для домашнього залу',
      'яку регульовану лаву купити',
      'скільки млинців треба для дому',
      'блоковий тренажер вдома — варто?',
      'що перше купити для залу в підвалі',
      'турнік у дверний проріз норм?',
      'складна рама для маленької кімнати',
      'купую вживане обладнання, на що дивитись',
      'яку вагу гирі купити',
      'облаштовую зал у вільній кімнаті, що потрібно',
      'гумові чи залізні млинці додому',
      'бігова доріжка чи гребний для дому',
      'какую скамью купить домой',
      'гиря или гантели для дома',
      'что нужно для зала в гараже',
      'стойки для приседа домой стоит брать?',
      'какой гриф купить для дома',
    ],
  },
  what_can_i_ask: {
    ex: [
      'what are you good for',
      'what do you help with exactly',
      'what kinds of things can i ask about',
      'give me a few sample questions',
      'what are your features',
      'help me figure out what to ask',
      'what can you answer',
      'what should i try asking you',
      'tell me what you can do for me',
      'what are you capable of',
      'what are some things people ask you',
      'can you show me some prompts',
      'where do i start with you',
      'what questions work best',
      'what do you cover',
      'any tips on what to ask',
      'suggest something to ask',
      'what are you here for',
      'menu of things you can do',
      "i'm new here, what can you help me with",
      'what can i talk to you about',
      'list your abilities',
      'which topics can you handle',
      'what are you able to answer about my training',
      'what kind of stuff do you know',
    ],
    exUk: [
      'на що ти здатен',
      'з чим саме ти допомагаєш',
      'про що взагалі можна тебе питати',
      'дай кілька прикладів питань',
      'які в тебе функції',
      'допоможи зрозуміти, що питати',
      'на що ти можеш відповісти',
      'що спробувати в тебе спитати',
      'розкажи, що ти можеш для мене зробити',
      'що в тебе зазвичай питають',
      'з чого з тобою почати',
      'які питання працюють найкраще',
      'які теми ти покриваєш',
      'підкажи, що спитати',
      'для чого ти тут',
      'я новенький, з чим допоможеш',
      'про що з тобою можна поговорити',
      'перелічи свої можливості',
      'що ти знаєш про тренування, що можна питати',
      'шо ти вмієш взагалі',
      'что у тебя можно спросить',
      'какие вопросы тебе задавать',
      'с чем ты помогаешь',
      'дай примеры вопросов',
      'о чем тебя можно спрашивать',
    ],
  },
  reminder: {
    ex: [
      'ping me tomorrow morning to train',
      'nudge me at 7 to go lift',
      'can you alert me before my workout',
      'reminder: gym on wednesday',
      "don't let me forget leg day",
      'remind me to drink water during the day',
      'can you remind me to eat protein',
      "schedule a reminder for friday's session",
      'set a daily reminder for training',
      'remind me in an hour to stretch',
      'can you text me to go to the gym',
      'i keep forgetting to train, can you remind me',
      'remind me to log my weight every morning',
      'set up gym reminders on weekdays',
      'alert me at 5 pm for my workout',
      'can i get a reminder before each session',
      'please remind me to sleep early',
      'put a reminder for my deload week',
      'remind me to buy creatine',
      'give me a heads up tomorrow about training',
      'wake me up for the gym',
      'reminder to take my supplements at night',
      'remind me saturday to go for a run',
      "can you remind me when it's time to rest",
      'set a workout reminder for thursday at 6',
    ],
    exUk: [
      'пінгани мене завтра зранку на тренування',
      'штурхни мене о 7 піти в зал',
      'можеш попередити перед тренуванням',
      'нагадування: зал у середу',
      'не дай мені забути про день ніг',
      'нагадуй пити воду протягом дня',
      'нагадай з’їсти протеїн',
      'заплануй нагадування на п’ятничне тренування',
      'щоденне нагадування про тренування',
      'нагадай через годину розтягнутись',
      'я забуваю тренуватися, нагадуй мені',
      'нагадуй зважуватися щоранку',
      'налаштуй нагадування в будні про зал',
      'о 17:00 нагадай про тренування',
      'нагадуй перед кожним тренуванням',
      'нагадай лягти спати раніше',
      'нагадай купити креатин',
      'завтра нагадай про трен',
      'нагадуй увечері про добавки',
      'нагадай у суботу побігати',
      'напомни завтра про зал',
      'поставь напоминалку на тренировку в четверг',
      'напоминай пить воду',
      'напомни купить протеин',
      'напоминание про тренировку в 7 утра',
    ],
  },
  memory_show: {
    ex: [
      'what have you saved about me',
      "what's in my profile",
      'what details have you kept on me',
      'remind me what you know about me',
      'what have you learned about me',
      'do you remember what i told you',
      'what do you remember about my back injury',
      "what's my info you have",
      "tell me everything you've stored on me",
      'do you remember my goal',
      'what facts about me do you have',
      'show my saved notes about me',
      'what do you think you know about me',
      'have you kept track of my injuries',
      'what did i tell you before about myself',
      'recall what you know about me',
      'which things about me do you remember',
      'do you know my name and goal',
      'what are you remembering about me right now',
      'dump your memory about me',
      'summarize what you know about me',
      'what personal info do you have',
      'do you still remember my knee issue',
      "what's on file for me",
      'show my memory',
    ],
    exUk: [
      'що ти про мене зберіг',
      'що в моєму профілі',
      'які дані ти про мене тримаєш',
      'нагадай, що ти про мене знаєш',
      'що ти про мене дізнався',
      'ти пам’ятаєш, що я тобі казав',
      'що пам’ятаєш про мою травму спини',
      'яка в тебе інфа про мене',
      'розкажи все, що ти про мене зберіг',
      'ти пам’ятаєш мою ціль',
      'які факти про мене в тебе є',
      'що я раніше розповідала про себе',
      'що ти про мене запам’ятав',
      'ти ще пам’ятаєш про моє коліно',
      'що записано про мене',
      'покажи мою пам’ять',
      'підсумуй, що знаєш про мене',
      'ти знаєш мою мету і травми?',
      'яку особисту інформацію ти маєш',
      'шо ти там про мене пам’ятаєш',
      'что ты обо мне запомнил',
      'что у тебя сохранено про меня',
      'ты помнишь мою травму',
      'какая у тебя инфа обо мне',
      'покажи, что ты обо мне помнишь',
    ],
  },
  memory_forget: {
    ex: [
      'delete what you remember about me',
      'reset your memory of me',
      'clear my memory',
      'unlearn everything about me',
      "i don't want you remembering that",
      'scrap everything you know about me',
      'forget my injury',
      'never mind that, forget it',
      'remove my personal info from your memory',
      'drop everything you stored on me',
      "please don't remember what i just said",
      'forget my goal',
      'start fresh, forget about me',
      'delete that from your memory',
      'purge your memory of me',
      'clear all the facts you have on me',
      'you can forget that',
      'forget what i said about my knee',
      'stop remembering me',
      'wipe your memory',
      'erase what i told you',
      "don't keep that, forget it",
      'remove everything you remember',
      'clean slate, forget all of it',
      'forget the stuff i told you earlier',
    ],
    exUk: [
      'видали, що ти про мене пам’ятаєш',
      'скинь свою пам’ять про мене',
      'очисти мою пам’ять',
      'не хочу, щоб ти це пам’ятав',
      'викинь з пам’яті все про мене',
      'забудь про мою травму',
      'не зважай, забудь',
      'прибери мої дані з пам’яті',
      'не запам’ятовуй, що я щойно сказав',
      'забудь мою ціль',
      'почнемо з нуля, забудь про мене',
      'видали це з пам’яті',
      'очисти всі факти про мене',
      'можеш це забути',
      'забудь, що я казала про коліно',
      'перестань мене пам’ятати',
      'зітри свою пам’ять',
      'зітри те, що я тобі розказав',
      'з чистого аркуша, забудь усе',
      'забудь те, що я раніше розповідав',
      'удали все, что обо мне знаешь',
      'забудь мою травму',
      'очисти память обо мне',
      'забудь, что я говорил',
      'сотри все данные обо мне',
    ],
  },
  act_rest: {
    ex: [
      '3 minutes rest on bench from now',
      'i want 2 minutes between squat sets',
      'bump deadlift rest to 4 minutes',
      'cut my pull-up rest to 60 seconds',
      'overhead press rest should be 2 min',
      'rest 90 sec on rows please',
      'lower bench rest to 2 minutes',
      'squat rest 180 seconds',
      'give me 5 minute rests on deadlift',
      'shorten rest on lat pulldown to 45 seconds',
      'increase rest for dips to 2 minutes',
      'rest timer 2:00 for leg press',
      'put my curls on 60 second rest',
      'set 4 min rest for front squat',
      'i need 3 minutes between bench sets, set it',
      'change the rest on hip thrust to 90 seconds',
      'romanian deadlift rest 2 and a half minutes',
      'rest between incline press sets: 2 min',
      'make overhead press rest 120 seconds',
      'update squat rest to 4 minutes',
      'let me rest 75 seconds on lunges',
      '1 minute rest on lateral raises',
      'rest for barbell rows should be 2 minutes, change it',
      'pause between bench sets 3 min please',
      'set deadlift rest 3:30',
    ],
    exUk: [
      '3 хвилини відпочинку на жимі відтепер',
      'хочу 2 хвилини між підходами присіду',
      'збільш відпочинок у становій до 4 хвилин',
      'зменш відпочинок на підтягуваннях до 60 секунд',
      'на армійському відпочинок 2 хв',
      'відпочинок 90 сек на тязі в нахилі',
      'присід — відпочинок 180 секунд',
      'дай 5 хвилин відпочинку на становій',
      'скороти відпочинок на тязі блоку до 45 секунд',
      'на бруси постав 2 хвилини паузи',
      'таймер 2:00 на жим ногами',
      'на біцепс відпочинок 60 секунд',
      'постав 4 хв відпочинку на фронтальний присід',
      'між сетами жиму 3 хвилини, встанови',
      'зміни паузу на сідничному мосту на 90 секунд',
      'румунська тяга — відпочинок дві з половиною хвилини',
      'оновити відпочинок у присіді на 4 хвилини',
      '75 секунд відпочинку на випадах',
      '1 хвилина відпочинку на махах гантелями',
      'на станову відпочинок 3:30',
      'отдых на становой 4 минуты',
      'поставь паузу 90 секунд на подтягивания',
      'отдых между подходами жима 2 минуты',
      'сделай отдых на армейском 150 секунд',
      'уменьши отдых в приседе до 2 минут',
    ],
  },
  act_swap: {
    ex: [
      'put dumbbell bench in place of barbell bench',
      'trade squats for leg press',
      'switch out deadlift for trap bar deadlift',
      "i'd rather do cable rows than barbell rows, swap them",
      'make it hack squat instead of back squat',
      'sub pull-ups with lat pulldown',
      'change my overhead press to landmine press',
      'replace romanian deadlift with good mornings',
      'use incline dumbbell press in place of bench press',
      'swap dips out for close-grip bench',
      'do goblet squats instead of front squats in my plan',
      'change lunges to bulgarian split squats',
      'replace hip thrust with glute bridge',
      'switch leg extensions to split squats',
      'exchange chin-ups for pull-ups',
      'put leg press where squat is',
      'swap my barbell rows for dumbbell rows',
      'replace the bench with push-ups',
      'trade deadlift for rack pulls',
      'swap out ohp for dumbbell shoulder press',
      'use seated rows instead of t-bar rows',
      'switch squat to safety bar squat',
      'change lat pulldown to pull-ups',
      'from now on do romanian deadlift instead of deadlift',
      'replace curls with hammer curls',
    ],
    exUk: [
      'постав жим гантелей на місце жиму штанги',
      'поміняй присід на жим ногами',
      'заміни станову на тягу з трап-грифа',
      'хочу тягу блоку замість тяги штанги, заміни',
      'зроби гак-присід замість присіду',
      'підтягування заміни на тягу верхнього блоку',
      'армійський жим поміняй на жим гантелей стоячи',
      'румунську тягу заміни на гуд монінг',
      'похилий жим гантелей замість жиму лежачи в плані',
      'бруси поміняй на жим вузьким хватом',
      'гоблет-присід замість фронтального',
      'випади заміни на болгарські присідання',
      'сідничний міст поміняй на ягодичний місток на підлозі',
      'підтягування зворотним хватом заміни на прямі',
      'тягу штанги поміняй на тягу гантелі',
      'жим лежачи заміни на віджимання',
      'станову поміняй на тягу з плінтів',
      'присід заміни на присід з безпечним грифом',
      'тягу верхнього блоку заміни на підтягування',
      'відтепер румунська тяга замість станової',
      'поменяй жим штанги на жим гантелей',
      'замени становую на румынскую тягу',
      'вместо подтягиваний поставь тягу блока',
      'присед замени на гакк-присед',
      'поменяй армейский жим на жим сидя',
    ],
  },
  act_avoid: {
    ex: [
      'take squats out of my program',
      'i never want to see deadlifts again',
      'ban bench press from my plan',
      'stop programming pull-ups for me',
      'delete overhead press from my plan',
      'no more barbell rows please',
      'get rid of lunges in my programme',
      "don't include dips anymore",
      'blacklist leg press',
      'cut romanian deadlift out of my routine',
      'strike hip thrust from the plan',
      'stop giving me front squats',
      'leave bulgarian split squats out of my program',
      "i'm done with good mornings, remove them",
      'keep deadlift out of my plan from now on',
      'never schedule overhead press',
      'no squats in my plan ever',
      'remove chin-ups permanently',
      'take bench off my programme',
      'exclude dips, they hurt my shoulders',
      'drop leg extensions from my routine',
      "don't program upright rows for me",
      'cross off lunges from my plan',
      'i want no deadlifts in my programme',
      'remove box jumps from my plan',
    ],
    exUk: [
      'прибери присід з програми',
      'не хочу більше бачити станову',
      'заборони жим лежачи в плані',
      'перестань ставити мені підтягування',
      'видали армійський жим з плану',
      'більше ніякої тяги в нахилі',
      'позбався випадів у програмі',
      'бруси більше не включай',
      'жим ногами в чорний список',
      'виріж румунську тягу з програми',
      'викресли сідничний міст із плану',
      'перестань давати фронтальний присід',
      'болгарські випади не став більше',
      'набридли гуд монінги, прибери їх',
      'станову більше не став у план',
      'ніколи не став мені армійський жим',
      'підтягування зворотним хватом прибери назавжди',
      'бруси прибери, від них болять плечі',
      'розгинання ніг викинь з програми',
      'ніяких випадів у плані',
      'убери жим лежа из плана',
      'больше не давай подтягивания',
      'выкинь выпады из программы',
      'не ставь мне становую тягу',
      'исключи брусья из плана навсегда',
    ],
  },
  act_move: {
    ex: [
      'push legs to friday',
      "can we do today's workout on thursday instead, move it",
      'bump push day to saturday',
      "i can't make it wednesday, put upper on thursday",
      'move my tuesday session to wednesday',
      'reschedule pull to monday',
      "put tomorrow's lower day on sunday",
      "slide today's training to tomorrow",
      'shift legs from monday to tuesday',
      "put friday's session on saturday instead",
      'move chest day to wednesday',
      "i'm busy today, move it to friday",
      'swap the day, legs on thursday not wednesday',
      'reschedule upper body to tuesday',
      "move sunday's workout to monday",
      'put pull day on friday',
      "delay today's session to tomorrow",
      'move back day to thursday',
      'shift the full body session to saturday',
      'leg day on wednesday instead please',
      "transfer thursday's workout to friday",
      'move my lower session to tuesday',
      "put today's workout on sunday",
      'postpone push day to thursday',
      "reschedule wednesday's training for thursday",
    ],
    exUk: [
      'перекинь ноги на п’ятницю',
      'давай сьогоднішнє тренування на четвер',
      'жимовий день посунь на суботу',
      'в середу не можу, постав верх на четвер',
      'перенеси вівторкове тренування на середу',
      'тягу перенеси на понеділок',
      'завтрашній низ постав на неділю',
      'посунь сьогоднішнє на завтра',
      'ноги з понеділка на вівторок',
      'п’ятничне тренування на суботу',
      'груди перенеси на середу',
      'сьогодні зайнятий, перенеси на п’ятницю',
      'верх перенеси на вівторок',
      'недільне тренування на понеділок',
      'тяговий день постав на п’ятницю',
      'відклади сьогоднішнє тренування на завтра',
      'день спини перенеси на четвер',
      'фулбаді посунь на суботу',
      'четвергове перенеси на п’ятницю',
      'день ніг хай буде в середу',
      'перенеси ноги на пятницу',
      'сегодняшнюю тренировку на четверг',
      'перенеси спину на субботу',
      'перенеси тренировку со среды на четверг',
      'передвинь верх на вторник',
    ],
  },
  act_start: {
    ex: [
      'fire up my workout',
      "open today's workout and start it",
      "i'm at the gym, start the session",
      'ok, start my training',
      'launch the workout',
      'begin the workout please',
      'start logging my workout',
      "start today's training session",
      "i'm ready, start my session",
      'get my workout going',
      'start the workout now',
      "let's begin my session",
      'start my gym session',
      'hit start on my workout',
      'time to train, start the workout',
      'start the planned workout',
      "i'm warmed up, begin my workout",
      "commence today's session",
      'open my session and start',
      'start the training',
      'begin my workout for today',
      "start today's lifting session",
      'i want to start my workout now',
      "kick off today's training",
      "press start on today's session",
    ],
    exUk: [
      'запускай тренування',
      'відкрий сьогоднішнє тренування і почни',
      'я в залі, починай тренування',
      'ок, почни моє тренування',
      'стартуємо заняття',
      'почни тренування, будь ласка',
      'почни записувати тренування',
      'почни сьогоднішнє заняття',
      'я готовий, починаємо тренування',
      'запусти мій трен',
      'починаймо тренування зараз',
      'час тренуватися, запускай заняття',
      'почни заплановане тренування',
      'розім’явся, починай тренування',
      'відкрий заняття і стартуй',
      'почнімо сьогоднішній трен',
      'хочу почати тренування зараз',
      'запусти тренування на сьогодні',
      'стартуй сьогоднішнє заняття',
      'натисни старт на тренуванні',
      'запускай тренировку',
      'я в зале, начинай тренировку',
      'начать занятие',
      'стартуем тренировку',
      'начни сегодняшнюю тренировку',
    ],
  },
  act_temper: {
    ex: [
      'go easy on me',
      'tone it down a bit',
      'stop being so soft',
      'be more gentle',
      'give it to me straight, no sugarcoating',
      'yell at me like a drill sergeant',
      'be more supportive',
      'be less harsh',
      'be ruthless',
      'i want tough love',
      'use a calmer tone',
      'be friendlier',
      'less nice, more strict',
      'talk to me like a hardcore coach',
      'be encouraging',
      'stop coddling me',
      'switch to a steady tone',
      'be warmer with me',
      "don't hold back, be brutal",
      'soften up',
      'be kind',
      'turn the strictness up',
      'be more direct',
      'be sweeter to me',
      'go full drill sergeant',
    ],
    exUk: [
      'будь поблажливішим',
      'трохи м’якше, будь ласка',
      'досить бути таким м’яким',
      'будь ніжнішим',
      'кажи прямо, без прикрас',
      'кричи на мене як сержант',
      'будь підтримуючим',
      'менш різко',
      'будь нещадним',
      'хочу жорсткої любові',
      'спокійнішим тоном',
      'будь привітнішим',
      'менше доброти, більше строгості',
      'говори як жорсткий тренер',
      'підбадьорюй мене',
      'не панькайся зі мною',
      'будь теплішим зі мною',
      'не стримуйся, будь брутальним',
      'будь добрим',
      'стань суворішим',
      'будь строже',
      'будь помягче со мной',
      'говори как сержант',
      'будь жестким',
      'будь добрее',
    ],
  },
  act_mute: {
    ex: [
      'mute',
      'mute everything today',
      'hush for today',
      'no notifications today please',
      'stop pinging me today',
      'mute alerts',
      'turn off pushes for today',
      'leave me alone today, mute',
      'silence for today',
      'mute the pings',
      "i don't want any messages today",
      'go silent today',
      'snooze notifications for today',
      'stop sending me stuff today',
      'mute now',
      'shh, no pushes today',
      'please be quiet today',
      "mute today's reminders",
      'no alerts from you today',
      'keep quiet today',
      'mute your pushes',
      'dnd for today',
      'turn notifications off for the day',
      'silence atlas today',
      'stop notifying me today',
    ],
    exUk: [
      'мут',
      'заглуши все сьогодні',
      'цить сьогодні',
      'сьогодні без сповіщень',
      'не пінгуй мене сьогодні',
      'вимкни алерти',
      'вимкни пуші на сьогодні',
      'дай спокій сьогодні, без повідомлень',
      'тиша на сьогодні',
      'не хочу сьогодні повідомлень',
      'мовчи сьогодні',
      'не надсилай нічого сьогодні',
      'замовкни',
      'не турбуй сьогодні',
      'вимкни нагадування на сьогодні',
      'сьогодні без пушів',
      'вимкни сповіщення на день',
      'не сповіщай мене сьогодні',
      'заглуши атласа сьогодні',
      'режим тиші на сьогодні',
      'не пиши мне сегодня',
      'без уведомлений сегодня',
      'помолчи сегодня',
      'отключи пуши на сегодня',
      'тишина сегодня',
    ],
  },
  act_bodyweight: {
    ex: [
      'scale says 83.4',
      "i'm 76 kg today",
      'weighed myself: 91 kg',
      'this morning i was 69.5 kg',
      'bodyweight 80.6',
      'put me down at 74 kg',
      "i'm at 88 kilos now",
      "today's weight 62.3",
      'stepped on the scale, 97 kg',
      'note my weight: 71 kg',
      "i'm 100 kg flat",
      'morning weight 78.2',
      'save weigh-in 85 kg',
      'hit 70 kg on the scale today',
      'current weight 93.5',
      "i'm down to 81 kg",
      'up to 86 kg today',
      'add weight entry 67 kg',
      'fasted weight today 75.1',
      'my weight right now is 82.7 kg',
      'i weigh exactly 90',
      'scale read 58 kg this morning',
      "i'm 79 kilos",
      'track 84.4 kg for today',
      'enter bodyweight 73',
    ],
    exUk: [
      'ваги показують 83,4',
      'я сьогодні 76 кг',
      'зважилася: 91 кг',
      'зранку було 69,5',
      'вага тіла 80,6',
      'запиши мені 74 кг',
      'я вже 88 кіло',
      'вага на сьогодні 62,3',
      'став на ваги, 97 кг',
      'занотуй вагу: 71 кг',
      'я рівно 100 кг',
      'ранкова вага 78,2',
      'збережи зважування 85 кг',
      'сьогодні на вагах 70',
      'поточна вага 93,5',
      'я схуд до 81 кг',
      'набрав до 86 кг',
      'додай запис ваги 67 кг',
      'натще сьогодні 75,1',
      'важу рівно 90',
      'вешу 76 кг сегодня',
      'весы показали 91',
      'запиши вес 80,5 кг',
      'утром было 69 кг',
      'мой вес сейчас 88 кило',
    ],
  },
  range_count: {
    ex: [
      'how many times have i been to the gym since new year',
      'session count for the past fortnight',
      'how many trainings in the last 10 days',
      'how many days did i lift this month',
      'count my workouts since march',
      'total sessions in the last 6 months',
      'how many gym visits last week',
      'how often did i show up in july',
      'number of workouts over the past 8 weeks',
      'how many days did i train in the last 2 weeks',
      'how many sessions have i logged this year',
      'how many workouts since may',
      'how many times did i lift in september',
      'tally my sessions for the last 3 months',
      'how many gym days in the past 60 days',
      'sessions completed this month',
      'how many trainings last month exactly',
      'workout count for the past 4 weeks',
      'how often have i been lifting since april',
      'how many workouts in the last 5 weeks',
      'how many sessions did i manage last week',
      'count of trainings in the last 90 days',
      'how many times did i go in june',
      'how many days at the gym this year so far',
      'how many sessions over the last month',
    ],
    exUk: [
      'скільки разів я був у залі з нового року',
      'кількість тренувань за останні два тижні',
      'скільки тренувань за останні 10 днів',
      'скільки днів я тренувався цього місяця',
      'порахуй тренування з березня',
      'скільки всього занять за останні 6 місяців',
      'скільки разів ходив у зал минулого тижня',
      'як часто я ходила в липні',
      'кількість тренувань за останні 8 тижнів',
      'скільки днів тренувань за останні 2 тижні',
      'скільки тренувань я записав цього року',
      'скільки тренувань з травня',
      'скільки разів у вересні качався',
      'скільки занять за останні 3 місяці, порахуй',
      'скільки разів був у залі за останні 60 днів',
      'скільки завершених тренувань цього місяця',
      'скільки тренувань за останні 4 тижні',
      'як часто я тренуюсь з квітня',
      'скільки разів я сходив минулого тижня',
      'скільки тренувань за останні 90 днів',
      'сколько раз ходил в зал в июле',
      'сколько тренировок за последние 2 недели',
      'посчитай тренировки с марта',
      'сколько тренировок в этом месяце',
      'сколько раз тренировался в этом году',
    ],
  },
  range_summary: {
    ex: [
      'how did the past fortnight go',
      'wrap up my last 10 days of training',
      'overview since new year',
      'rundown of july',
      "how's this month looking training wise",
      'digest of my training in the last 3 months',
      'give me the highlights from last month',
      'sum up my training since march',
      'breakdown of the last 6 weeks',
      'what happened in my training in august',
      'review my last 2 months',
      'how was my training last week overall',
      'summary of this year so far',
      'month in review for june',
      'how have the last 4 weeks been',
      "what's the story of my training since may",
      'brief report on the past 30 days',
      'quarterly summary, last 3 months',
      'my training recap for the last 8 weeks',
      'what did my training look like in april',
      'overview of my workouts this month',
      'how did my training go over the last 60 days',
      'give me a rundown of last week',
      'report on my gym work since january',
      'sum up the past 2 weeks for me',
    ],
    exUk: [
      'як минули останні два тижні',
      'підсумуй останні 10 днів тренувань',
      'огляд з нового року',
      'як пройшов липень',
      'як виглядає цей місяць по тренуваннях',
      'підсумок тренувань за останні 3 місяці',
      'головне з минулого місяця',
      'підсумуй мої тренування з березня',
      'розбір останніх 6 тижнів',
      'що було в тренуваннях у серпні',
      'огляд останніх 2 місяців',
      'як загалом пройшов минулий тиждень',
      'підсумок цього року',
      'огляд червня',
      'як пройшли останні 4 тижні',
      'короткий звіт за останні 30 днів',
      'звіт за квартал, останні 3 місяці',
      'як виглядали мої тренування у квітні',
      'огляд тренувань цього місяця',
      'звіт по залу з січня',
      'итоги за последние 2 недели',
      'как прошел июль',
      'обзор тренировок за этот месяц',
      'подведи итог с марта',
      'отчет за последние 30 дней',
    ],
  },
  range_lift: {
    ex: [
      'bench trend over the past fortnight',
      "how's my squat been since new year",
      'deadlift numbers for the last 10 days',
      'top overhead press in july',
      'has my bench moved since march',
      'squat e1rm over the last 6 months',
      'deadlift progress this month',
      'pull-ups over the last 8 weeks',
      'best bench since may',
      'is my squat up or down in the last 2 months',
      'rows trend over the past 3 months',
      'overhead press numbers since april',
      'how did my deadlift do in august',
      'bench history for the last 90 days',
      'heaviest squat last month',
      'how has leg press gone over the last 4 weeks',
      'dips progress since june',
      'romanian deadlift numbers this year',
      'front squat over the last 30 days',
      'did my deadlift improve since january',
      'bench peak in the past 6 weeks',
      'hip thrust progress in the last 3 months',
      'squat trend this month',
      "how's the overhead press been since february",
      'incline bench over the last 2 months',
    ],
    exUk: [
      'жим лежачи за останні два тижні',
      'як присід з нового року',
      'станова за останні 10 днів',
      'найкращий армійський у липні',
      'чи зрушив жим з березня',
      'присід за останні 6 місяців, динаміка',
      'прогрес у становій цього місяця',
      'підтягування за останні 8 тижнів',
      'кращий жим з травня',
      'присід виріс чи впав за останні 2 місяці',
      'тяга в нахилі за останні 3 місяці',
      'армійський жим з квітня',
      'як станова в серпні',
      'жим за останні 90 днів',
      'найважчий присід минулого місяця',
      'жим ногами за останні 4 тижні',
      'бруси з червня, прогрес',
      'румунська тяга цього року',
      'станова покращилась з січня?',
      'сідничний міст за останні 3 місяці',
      'жим лежа за последние 2 месяца',
      'присед с нового года как',
      'становая в августе',
      'прогресс подтягиваний за последний месяц',
      'армейский жим с апреля',
    ],
  },
  range_muscle: {
    ex: [
      'chest sets over the past fortnight',
      'how much back work since new year',
      'leg volume for the last 10 days',
      'shoulder volume in july',
      'biceps sets since march',
      'how many sets for glutes in the last 6 months',
      'quads worked this month, set count',
      'hamstring volume last week',
      'how much chest did i do in august',
      'triceps sets over the last 8 weeks',
      'back sets since may',
      'delt volume in the last 2 months',
      'how much did i hit calves in the last 30 days',
      'abs sets this month',
      'lats volume since april',
      'how many leg sets in the last 3 months',
      'chest volume this year',
      'how much shoulder work last month',
      'glute volume since june',
      'traps sets over the past 4 weeks',
      'arm volume in the last 6 weeks',
      'how much quad work since january',
      'forearm sets this month',
      'hamstrings in the last 90 days, how many sets',
      'rear delts volume last month',
    ],
    exUk: [
      'сети на груди за останні два тижні',
      'скільки роботи на спину з нового року',
      'обсяг ніг за останні 10 днів',
      'обсяг на плечі в липні',
      'підходи на біцепс з березня',
      'скільки сетів на сідниці за останні 6 місяців',
      'квадрицепс цього місяця, скільки підходів',
      'біцепс стегна минулого тижня, обсяг',
      'скільки грудей я робив у серпні',
      'сети на трицепс за останні 8 тижнів',
      'підходи на спину з травня',
      'обсяг на дельти за останні 2 місяці',
      'литки за останні 30 днів',
      'скільки сетів на прес цього місяця',
      'найширші з квітня, скільки підходів',
      'скільки сетів на ноги за останні 3 місяці',
      'об’єм на груди цього року',
      'сідниці з червня, скільки сетів',
      'трапеції за останні 4 тижні',
      'руки за останні 6 тижнів, обсяг',
      'сколько подходов на спину в июле',
      'объем на ноги за последние 2 недели',
      'подходы на плечи с марта',
      'сколько сетов на бицепс в этом месяце',
      'объем на грудь с нового года',
    ],
  },
  range_bw: {
    ex: [
      'weight change over the past fortnight',
      'bodyweight since new year',
      'what did the scale do in the last 10 days',
      'my weight in july',
      "how's my weight trending since march",
      'weight over the last 6 months',
      'have i gained weight this month',
      'bodyweight trend over the last 8 weeks',
      'weight since may',
      'am i heavier than i was over the last 2 months',
      'scale readings for the past 3 months',
      'how much did i weigh in august',
      'weight curve for the last 90 days',
      'did i lose weight last month',
      'bodyweight changes since april',
      'weigh-ins over the last 30 days',
      'how much weight did i put on since january',
      'weight graph this year',
      'average weight last week',
      'how has my bodyweight moved in the last 4 weeks',
      'cut progress on the scale since june',
      'weight trend in the last 6 weeks',
      'my weigh-ins this month',
      'did my bodyweight drop in september',
      'how much weight since february',
    ],
    exUk: [
      'зміна ваги за останні два тижні',
      'вага тіла з нового року',
      'що показували ваги за останні 10 днів',
      'моя вага в липні',
      'як іде вага з березня',
      'вага за останні 6 місяців',
      'я набрав вагу цього місяця?',
      'тренд ваги за останні 8 тижнів',
      'вага з травня',
      'показники ваг за останні 3 місяці',
      'скільки я важила в серпні',
      'вага за останні 90 днів, графік',
      'я схуд минулого місяця?',
      'зважування за останні 30 днів',
      'скільки набрав з січня',
      'вага цього року',
      'середня вага минулого тижня',
      'як змінилась вага тіла за останні 4 тижні',
      'сушка з червня, що з вагою',
      'вага у вересні впала?',
      'вес за последние 2 недели',
      'как менялся вес с нового года',
      'сколько я весил в июле',
      'похудел ли я в этом месяце',
      'вес за последние 6 месяцев',
    ],
  },
  then_vs_now: {
    ex: [
      'me today vs me 3 months ago',
      'how far have i come since 6 months ago',
      'am i any stronger than a year ago',
      'have i gotten weaker compared to 2 months ago',
      'better lifter now or 4 weeks ago',
      "what's changed since 5 months ago",
      'stronger than i was 8 weeks ago?',
      'compare now with 3 months ago',
      'did i improve compared to 10 weeks ago',
      'how do my numbers now stack up to a year ago',
      'am i stronger than 6 months ago or not',
      'progress check against 2 months ago',
      'have i regressed since 4 months ago',
      'is my squat better than 3 months ago',
      'now vs 12 weeks ago',
      'have i gained strength since 1 month ago',
      'how much stronger than 6 weeks ago',
      'am i lifting more than 2 years ago',
      'compare my strength now to 9 months ago',
      'did i get weaker than 3 weeks ago',
      'am i better than a month ago',
      'strength then and now, 5 months ago vs today',
      'is my deadlift stronger than 6 months ago',
      'look at me now vs 4 months ago',
      'how have my lifts changed since 7 weeks ago',
    ],
    exUk: [
      'я зараз проти мене 3 місяці тому',
      'наскільки я виріс порівняно з 6 місяцями тому',
      'я хоч трохи сильніший ніж рік тому',
      'я ослаб порівняно з 2 місяцями тому?',
      'я кращий зараз чи 4 тижні тому',
      'що змінилося порівняно з 5 місяцями тому',
      'сильніша ніж 8 тижнів тому?',
      'порівняй зараз і 3 місяці тому',
      'чи покращився я порівняно з 10 тижнями тому',
      'мої цифри зараз і рік тому',
      'сильніший ніж 6 місяців тому чи ні',
      'перевірка прогресу проти 2 місяців тому',
      'я регресував порівняно з 4 місяцями тому?',
      'присід кращий ніж 3 місяці тому?',
      'зараз проти 12 тижнів тому',
      'наскільки сильніший ніж 6 тижнів тому',
      'порівняй мою силу зараз і 9 місяців тому',
      'я кращий ніж місяць тому',
      'станова сильніша ніж 6 місяців тому?',
      'як змінились мої вправи порівняно з 7 тижнями тому',
      'я сильнее чем полгода назад',
      'сравни меня сейчас и 2 месяца назад',
      'я слабее чем год назад?',
      'есть прогресс по сравнению с 4 месяцами назад',
      'жим сильнее чем 3 месяца назад?',
    ],
  },
  compare_lifts: {
    ex: [
      'squat and deadlift side by side',
      'how does my bench stack up against my ohp',
      'which is further behind, bench or squat',
      'deadlift vs squat, which is stronger for me',
      'my front squat compared to my back squat',
      'is my ohp too weak relative to bench',
      'compare pull-ups and lat pulldown',
      'rows vs bench, are they balanced',
      "romanian deadlift against deadlift, what's the ratio",
      'squat versus leg press numbers',
      'bench press and incline bench comparison',
      'deadlift to bench ratio for me',
      'which lags more, overhead press or bench',
      'is my squat balanced with my deadlift',
      'hip thrust vs squat',
      'compare dips with bench press',
      'how far apart are my squat and bench',
      'my deadlift is way ahead of my squat, compare them',
      'bench next to rows, which is behind',
      'chin-ups vs pull-ups, which am i better at',
      'overhead press vs incline bench',
      'squat and bench, which should catch up',
      'deadlift or squat, which lags',
      'put my bench and deadlift next to each other',
      'is my rows number in line with bench',
    ],
    exUk: [
      'присід і станова поруч',
      'як мій жим лежачи проти армійського',
      'що більше відстає, жим чи присід',
      'станова чи присід, що в мене сильніше',
      'фронтальний присід порівняно з класичним',
      'армійський жим не заслабкий відносно жиму лежачи?',
      'порівняй підтягування і тягу верхнього блоку',
      'тяга в нахилі і жим лежачи збалансовані?',
      'румунська тяга проти станової',
      'присід проти жиму ногами',
      'жим лежачи і похилий жим, порівняння',
      'співвідношення станової і жиму',
      'що відстає, армійський чи жим лежачи',
      'присід збалансований зі становою?',
      'сідничний міст проти присіду',
      'бруси і жим лежачи, порівняй',
      'наскільки різняться мій присід і жим',
      'жим поруч із тягою в нахилі, що відстає',
      'присід і жим — що має догнати',
      'станова чи присід, що відстає',
      'сравни становую и присед',
      'жим лежа против армейского',
      'что отстает, присед или становая',
      'подтягивания и тяга блока, сравни',
      'жим и тяга в наклоне сбалансированы?',
    ],
  },
  why_today: {
    ex: [
      "what's the reasoning behind today's session",
      'explain why today is leg day',
      "why'd you put chest on today",
      'why is back scheduled today',
      "what's the logic of today's workout",
      'why am i training at all today',
      'why pull today and not push',
      'why is today upper body',
      'why a heavy day today',
      'why did today end up being lower',
      'why this particular session today',
      'why am i hitting shoulders today',
      "reason for today's workout",
      'how come today is a full body day',
      'why does today look like this',
      'why is today an easy session',
      "why today's training and not a rest day",
      'why legs again today',
      "explain today's plan choice",
      'why is today glutes and hamstrings',
      'why are we doing this workout today',
      "what's the point of today's session",
      'why is today a deload day',
      'why did you schedule arms for today',
      'why this session on a monday, today',
    ],
    exUk: [
      'яка логіка сьогоднішнього тренування',
      'поясни, чому сьогодні день ніг',
      'чого ти поставив груди на сьогодні',
      'чому сьогодні по плану спина',
      'а навіщо мені взагалі сьогодні тренуватись',
      'чому сьогодні тяга, а не жим',
      'чого сьогодні верх тіла',
      'чому сьогодні важкий день',
      'чого сьогодні вийшов низ',
      'чому саме це заняття сьогодні',
      'чого сьогодні плечі',
      'причина сьогоднішнього тренування',
      'чому сьогодні фулбаді',
      'чого сьогоднішнє таке',
      'чому сьогодні легке заняття',
      'чому сьогодні тренування, а не відпочинок',
      'чого знову ноги сьогодні',
      'навіщо ми робимо це тренування сьогодні',
      'у чому сенс сьогоднішнього заняття',
      'чому сьогодні розвантаження',
      'почему сегодня спина',
      'зачем сегодня грудь',
      'почему сегодня тяжелый день',
      'почему сегодня такая тренировка',
      'почему сегодня верх',
    ],
  },
  why_weight: {
    ex: [
      "what's the reason bench dropped to 80",
      "why'd you bump my squat up",
      'why so light on deadlift today',
      'explain the overhead press weight',
      'why is my bench still stuck at the same kg',
      "why'd squat go down 5 kg",
      'why 140 on the deadlift',
      'why is rows weight higher this time',
      'how come bench is heavier than i expected',
      'why did pull-ups get extra weight',
      'why am i lifting less on squat',
      'reason for the deadlift weight change',
      'why did my ohp load increase',
      'why is leg press so heavy today',
      'why did you cut the weight on bench',
      'why is my front squat weight lower',
      'why 60 kg on overhead press',
      "why hasn't my squat gone up",
      'why is romanian deadlift heavier',
      'how did you pick the bench weight',
      'why only 100 on squat today',
      'why the jump on deadlift',
      'why is bench lighter than last week',
      'why are my dips weighted now',
      'where does the hip thrust weight come from',
    ],
    exUk: [
      'чого жим впав до 80',
      'чому ти підняв вагу в присіді',
      'чого так легко на становій сьогодні',
      'поясни вагу на армійському',
      'чому жим досі на тій самій вазі',
      'чого присід знизився на 5 кг',
      'чому 140 на становій',
      'чого на тязі в нахилі більше ваги',
      'чому жим важчий ніж я думав',
      'чого на підтягуваннях додали обтяження',
      'чому я піднімаю менше в присіді',
      'чому змінилась вага в становій',
      'чого на армійському вага зросла',
      'чому жим ногами такий важкий сьогодні',
      'чого ти зрізав вагу на жимі',
      'чому 60 кг на армійському',
      'чого присід не росте',
      'як ти вибрав вагу на жим',
      'чому тільки 100 у присіді сьогодні',
      'чого стрибок ваги в становій',
      'почему становая легче сегодня',
      'почему на жиме 80 кг',
      'зачем снизил вес в приседе',
      'почему армейский тяжелее',
      'почему вес на жиме не растет',
    ],
  },
  why_plan: {
    ex: [
      "what's the thinking behind my program",
      'explain my split',
      'why did you set my plan up this way',
      'why train on these particular days',
      'why is the programme only 3 days',
      'why a push pull legs setup',
      'why is my plan 4 days a week',
      "what's the logic of this program",
      'why these weekdays for training',
      'how come you built me a full body plan',
      'why does my plan have a deload',
      'why is my week structured like this',
      'explain the reasoning behind my schedule',
      'why is there a rest day in the middle',
      'why did you choose this layout',
      'why this many days in my plan',
      "what's the rationale for my programme",
      'why is my plan so long',
      'why an upper lower instead of full body',
      'why am i on this program',
      'why do my sessions fall on these days',
      'why is the program set up in blocks',
      'why this weekly structure',
      'explain why my plan looks like this',
      'why did you go with this routine',
    ],
    exUk: [
      'яка ідея моєї програми',
      'поясни мій спліт',
      'чому ти так побудував план',
      'чому тренування саме в ці дні',
      'чому програма лише на 3 дні',
      'чого спліт жим-тяга-ноги',
      'чому план на 4 дні на тиждень',
      'яка логіка цієї програми',
      'чому ці дні тижня для залу',
      'чого ти дав мені фулбаді план',
      'навіщо в плані розвантаження',
      'чому мій тиждень так побудований',
      'поясни логіку розкладу',
      'чого вихідний посередині',
      'чому стільки днів у плані',
      'чого план такий довгий',
      'чому верх-низ, а не фулбаді',
      'чому я на цій програмі',
      'чому програма розбита на блоки',
      'чого така тижнева структура',
      'почему у меня такой план',
      'объясни мой сплит',
      'почему тренировки в эти дни',
      'зачем в программе разгрузка',
      'почему программа на 3 дня',
    ],
  },
  why_lift: {
    ex: [
      "what's the point of deadlifts in my program",
      "why'd you add bench press",
      'why do i have to do squats',
      'what are pull-ups doing in my plan',
      "why overhead press, what's it for",
      'why did you include romanian deadlift',
      'why are barbell rows on my list',
      "what's the reason for lunges in the plan",
      'why is leg press part of my program',
      'why lat pulldown in my routine',
      'why did dips end up in my plan',
      'why am i doing hip thrusts',
      'purpose of front squats in my program',
      'why incline bench and not flat',
      'why face pulls in my plan',
      'why the bulgarian split squat in my programme',
      'why do you have me doing good mornings',
      'why chin-ups in the plan',
      'why is the deadlift included at all',
      'why did you pick bench for me',
      "what's squat doing in my programme",
      'why curls in my plan',
      'why leg curls in my program',
      'why is overhead press there',
      'reason you gave me rows',
    ],
    exUk: [
      'який сенс станової в моїй програмі',
      'чого ти додав жим лежачи',
      'навіщо мені присідати',
      'що підтягування роблять у моєму плані',
      'армійський жим навіщо він',
      'чому ти включив румунську тягу',
      'чого тяга в нахилі в списку',
      'яка причина випадів у плані',
      'навіщо жим ногами в програмі',
      'чого тяга блоку в моїй програмі',
      'як бруси потрапили в план',
      'навіщо мені сідничний міст',
      'для чого фронтальний присід у програмі',
      'чому похилий жим, а не прямий',
      'навіщо фейс пул у плані',
      'чого болгарські випади в програмі',
      'навіщо гуд монінг',
      'чому підтягування зворотним хватом у плані',
      'навіщо взагалі станова',
      'чого ти вибрав мені жим',
      'почему становая в программе',
      'зачем мне приседать',
      'почему в плане подтягивания',
      'зачем румынская тяга',
      'зачем брусья в программе',
    ],
  },
};
