import type { Kb } from './types';

export const KB_A: Kb = {
  pain: {
    ex: [
      'my knee hurts when i squat',
      'sharp pain in my shoulder on bench',
      'lower back pain after deadlifts',
      'i think i hurt my back',
      'my elbow aches during curls',
      'i tweaked something in my hip',
      'should i train through the pain',
      'is it ok to lift if my wrist hurts',
      'i pulled a muscle yesterday',
      'pain in my neck after shrugs',
      'my hamstring hurts after rdls',
      'i got injured in the gym',
      'shoulder pain during overhead press what do i do',
      'my ankle hurts, can i still train legs',
      'it hurts when i press',
      'i felt a pop in my knee',
    ],
    exUk: [
      'болить коліно при присіданні',
      'болить плече на жимі лежачи',
      'біль у попереку після станової',
      'здається, я травмувався',
      'ниє лікоть після біцепса',
      'потягнув спину',
      'защемило в шиї',
      'чи можна тренуватись через біль',
      'болить зап’ястя, що робити',
      'після присяду болять коліна',
      'потягнув задню поверхню стегна',
      'болить плече коли жму над головою',
      'шось болить в спині після тяги',
      'в мене травма, можна в зал',
      'болит колено после приседа',
      'я травмировал плечо',
    ],
    facets: {
      why: [
        'Pain is a warning signal: loading a painful joint or muscle usually makes the problem worse and slows healing.',
        'Біль — це сигнал тривоги: навантаження на болючий суглоб чи м’яз зазвичай погіршує проблему й сповільнює загоєння.',
      ],
      how: [
        'Stop the movement that hurts, log it in Injury, and train around it with pain-free lifts and lighter loads. Return gradually as it settles.',
        'Зупини вправу, від якої болить, запиши це в «Травми» й тренуй інше — вправи без болю й легші ваги. Повертайся поступово, коли вщухне.',
      ],
      should: [
        "No, don't push through pain. Train other areas pain-free; see a doctor if the pain is sharp, swollen, getting worse or comes with numbness.",
        'Ні, через біль не тренуються. Тренуй інше без болю; до лікаря — якщо біль гострий, є набряк, гіршає чи німіє.',
      ],
      when: [
        'See a doctor right away for sharp pain, swelling, a pop, numbness or pain that gets worse. Otherwise return to the lift once everyday movement is pain-free.',
        'До лікаря одразу — при гострому болю, набряку, клацанні, онімінні чи якщо гіршає. Інакше повертайся до вправи, коли побутові рухи вже без болю.',
      ],
      where: [
        'Log it on the Injury screen; I then plan around the sore area and ease you back in.',
        'Запиши це на екрані «Травми» — тоді я плануватиму довкола болючого місця й повертатиму тебе поступово.',
      ],
    },
  },

  rest: {
    ex: [
      'how long should i rest between sets',
      'rest time between sets?',
      'how many minutes rest on squats',
      'how long to rest on bench press',
      'why do i need to rest so long',
      'is 1 minute rest enough',
      'optimal rest between sets for muscle',
      'should i rest longer on heavy sets',
      'how much rest between deadlift sets',
      'rest between sets for isolation exercises',
      'do i need 3 minutes between sets',
      'how long a break between sets',
      'why rest 2 and a half minutes',
      'rest period for compound lifts',
      'how long should i wait before the next set',
    ],
    exUk: [
      'скільки відпочивати між підходами',
      'скільки відпочинок між сетами',
      'яка пауза між підходами на присіді',
      'скільки хвилин перерва між сетами',
      'навіщо так довго відпочивати між сетами',
      'чи вистачить хвилини відпочинку',
      'оптимальний відпочинок між підходами',
      'скільки треба відпочивати на жимі',
      'скока відпочивати між підходами на становій',
      'яка перерва між сетами на біцепс',
      'довго відпочивати між сетами це нормально',
      'скільки паузу робити між підходами',
      'мені треба 3 хвилини між сетами',
      'сколько отдыхать между подходами',
      'какой отдых между сетами',
    ],
    facets: {
      why: [
        'Longer rest lets you repeat good-quality reps on the later sets, and total quality reps drive growth and strength.',
        'Довший відпочинок дає змогу повторити якісні повтори в наступних сетах, а саме сумарні якісні повтори дають ріст і силу.',
      ],
      howMuch: [
        'About 2:30 for heavy compound lifts, 1:30 for the rest, 1:00 after a warm-up set.',
        'Приблизно 2:30 на важких базових, 1:30 на решті, 1:00 після розминкового сету.',
      ],
      when: [
        "Rest longer when the muscle is already tired, after a bad night's sleep or when you're ill.",
        'Відпочивай довше, коли м’яз уже втомлений, після поганого сну чи коли хворієш.',
      ],
      should: [
        'Yes, rest long enough to hit your target reps on the next set; cutting rest short mostly costs reps.',
        'Так, відпочивай стільки, щоб у наступному сеті зробити цільові повтори; короткий відпочинок здебільшого з’їдає повтори.',
      ],
      where: [
        'The rest timer runs in the session after each set; you can set your own rest time per exercise.',
        'Таймер відпочинку запускається в тренуванні після кожного сету; для кожної вправи можна поставити свій час.',
      ],
    },
  },

  next_weight: {
    ex: [
      'what weight should i use on bench next time',
      'what weight for squats today',
      'how much should i put on the bar for deadlift',
      'next weight for overhead press',
      'should i add weight on bench',
      'how many kg on squat next session',
      'what load for rows today',
      'what should i lift on bench today',
      'next session bench weight?',
      'can i go up in weight on deadlift',
      'how heavy should i go on squat today',
      'what weight should i start with on leg press',
      'should i increase the weight on pull-ups',
      'how much to add to my ohp',
      'what kilos for bench today',
    ],
    exUk: [
      'яку вагу ставити на жим наступного разу',
      'скільки кг брати на присід сьогодні',
      'яку вагу на станову',
      'яка вага на жим стоячи далі',
      'чи додавати вагу на жимі',
      'скільки кіло ставити на присід',
      'яку вагу взяти на тягу сьогодні',
      'скільки навантаження на жим наступного разу',
      'шо ставити на жим сьогодні',
      'можна додати вагу на становій?',
      'скільки брати на жим ногами',
      'яку вагу на підтягуваннях додати',
      'наступна вага на жим лежачи',
      'какой вес ставить на жим',
      'сколько кг на присед сегодня',
    ],
    facets: {
      how: [
        'I look at your last top set on that lift: hit the top of the rep range on all sets and the weight goes up; miss it and you stay; stuck for a while and you back off and build again.',
        'Я дивлюся на твій останній найкращий сет у цій вправі: зробив верх діапазону на всіх сетах — вага вгору; не зробив — лишаєшся; довго стоїш — скидаєш і набираєш знову.',
      ],
      why: [
        'Adding weight only after you own the reps keeps progress steady and form clean.',
        'Додавати вагу тільки після того, як повтори вже твої, — так прогрес стабільний, а техніка чиста.',
      ],
      howMuch: [
        'Usually the smallest jump available: about 2.5 kg on upper-body lifts and 2.5–5 kg on squats and deadlifts.',
        'Зазвичай найменший крок: близько 2,5 кг на вправах для верху й 2,5–5 кг на присіді та становій.',
      ],
      should: [
        'Add weight only if you hit the target reps on every set last time with good form; otherwise stay and add a rep.',
        'Додавай вагу, лише якщо минулого разу зробив цільові повтори на всіх сетах з гарною технікою; інакше лишайся й додай повтор.',
      ],
      when: [
        'Go up the next session after you reach the top of the rep range on all working sets.',
        'Вгору — на наступному тренуванні після того, як дійшов до верху діапазону повторів на всіх робочих сетах.',
      ],
    },
  },

  best: {
    ex: [
      "what's my best bench",
      'my squat record',
      'what is my deadlift pr',
      'show my personal records',
      "what's my max on bench press",
      'best overhead press ever',
      'what are my prs',
      'my heaviest set on squat',
      'personal best on deadlift?',
      "what's my record on pull-ups",
      'tell me my best lifts',
      "what's the most i've benched",
      'my all-time best squat',
      'pr on rows',
      'what records do i have',
    ],
    exUk: [
      'який мій рекорд на жимі',
      'мій максимум у присіді',
      'який в мене рекорд на становій',
      'покажи мої рекорди',
      'найкращий результат на жимі лежачи',
      'мій особистий рекорд у жимі стоячи',
      'які в мене рекорди',
      'скільки мій макс на жимі',
      'найкращий сет у присіді',
      'мій рекорд на підтягуваннях',
      'шо в мене по рекордах',
      'максимальна вага, яку я жав',
      'мій найкращий результат у тязі',
      'какой мой рекорд в жиме',
      'мой максимум в приседе',
    ],
    facets: {
      what: [
        "Your best is the heaviest top set you've logged on that lift, shown with its reps and an estimated 1RM.",
        'Твій рекорд — найважчий найкращий сет, записаний у цій вправі, з кількістю повторів і розрахунковим 1ПМ.',
      ],
      how: [
        'I scan all finished workouts for the heaviest top set on each lift; without a lift named I show your three most-logged lifts.',
        'Я переглядаю всі завершені тренування й шукаю найважчий сет у кожній вправі; якщо вправу не названо — показую три найчастіші.',
      ],
      where: [
        'Ask me here, or open the exercise in your history to see its records.',
        'Спитай мене тут або відкрий вправу в історії, щоб побачити її рекорди.',
      ],
    },
  },

  progress_lift: {
    ex: [
      'how is my bench progressing',
      'is my squat improving',
      "how's my deadlift going",
      'am i making progress on overhead press',
      'my bench is stuck',
      'show my squat progress',
      'has my deadlift gone up',
      'is my bench getting better',
      'progress on pull-ups?',
      'how much has my squat improved',
      "why isn't my bench going up",
      "my ohp isn't moving",
      'bench progress over the last two months',
      'is my row getting stronger',
      'how has my leg press changed',
    ],
    exUk: [
      'як прогресує мій жим',
      'чи росте мій присід',
      'як іде станова',
      'є прогрес на жимі стоячи?',
      'жим застряг',
      'покажи прогрес у присіді',
      'станова росте чи ні',
      'яка динаміка на жимі лежачи',
      'жим стоїть на місці',
      'присід не росте, чому',
      'як справи з підтягуваннями',
      'наскільки виріс мій присід',
      'шо там з прогресом на жимі',
      'как прогрессирует мой жим',
      'есть прогресс в приседе?',
    ],
    facets: {
      how: [
        'I compare your top-set weight on that lift now with about 8 weeks ago and show the change in percent.',
        'Я порівнюю вагу найкращого сету в цій вправі зараз і приблизно 8 тижнів тому й показую зміну у відсотках.',
      ],
      should: [
        'If the lift is flat, keep the same weight and add one rep each session until it moves.',
        'Якщо вправа стоїть, лишай ту саму вагу й додавай по повтору щотренування, доки не зрушить.',
      ],
      howMuch: [
        'I need at least two logged sessions of the lift to judge; more history gives a clearer trend.',
        'Щоб судити, потрібно щонайменше два записані тренування з цією вправою; що більше історії, то чіткіша тенденція.',
      ],
      where: [
        'Ask me about a specific lift here, or open it in your history for the chart.',
        'Спитай мене про конкретну вправу тут або відкрий її в історії, щоб побачити графік.',
      ],
    },
  },

  volume_muscle: {
    ex: [
      'how many sets for chest this week',
      'how many sets did i do for back',
      'chest volume this week',
      'how many sets per week for quads',
      'am i doing enough sets for shoulders',
      'weekly sets for biceps',
      'is my hamstring volume enough',
      'how much volume for glutes',
      'sets for lats in the last 7 days',
      'too many sets for chest?',
      'how many weekly sets does triceps need',
      'calves volume',
      'how many sets should i do for back per week',
      "what's my shoulder volume",
      'am i doing too much volume for legs',
    ],
    exUk: [
      'скільки сетів на груди цього тижня',
      'скільки підходів я зробив на спину',
      'обсяг на груди за тиждень',
      'скільки підходів на тиждень на квадрицепс',
      'чи достатньо сетів на плечі',
      'скільки сетів на біцепс за тиждень',
      'обсяг на задню поверхню нормальний?',
      'скільки підходів на сідниці',
      'сети на широчайші за 7 днів',
      'забагато підходів на груди?',
      'скільки треба сетів на трицепс на тиждень',
      'який обсяг на ікри',
      'скока сетів на спину в тиждень',
      'сколько подходов на грудь в неделю',
      'объем на плечи за неделю',
    ],
    facets: {
      how: [
        "I count your hard sets per muscle over the last 7 days; warm-up sets don't count.",
        'Я рахую робочі сети на кожен м’яз за останні 7 днів; розминкові не враховуються.',
      ],
      howMuch: [
        'Most muscles grow well on roughly 10–20 hard sets a week; I show the productive range for each muscle.',
        'Більшість м’язів добре ростуть на приблизно 10–20 робочих сетах на тиждень; для кожного м’яза я показую робочий діапазон.',
      ],
      why: [
        'Weekly hard sets are the simplest measure of how much growth stimulus a muscle gets; too few stalls it, too many outpaces recovery.',
        'Робочі сети за тиждень — найпростіша міра стимулу для м’яза: замало — стоїть, забагато — не встигає відновитися.',
      ],
      should: [
        'Stay inside the productive range; add a couple of sets only if the muscle lags and you recover well.',
        'Тримайся робочого діапазону; додавай пару сетів, лише якщо м’яз відстає, а відновлюєшся ти добре.',
      ],
    },
  },

  weak: {
    ex: [
      'which muscles am i neglecting',
      'what muscle is lagging',
      'what am i undertraining',
      'is my training balanced',
      'do i have a muscle imbalance',
      'which body part is behind',
      'what am i skipping',
      'my weak points',
      'which muscles need more work',
      'am i forgetting any muscle group',
      "what's lagging this week",
      'am i neglecting legs',
      'what should i focus on more',
      'which muscle gets the least sets',
    ],
    exUk: [
      'які м’язи я недотреновую',
      'що в мене відстає',
      'чи збалансовані мої тренування',
      'є дисбаланс між м’язами?',
      'яка частина тіла відстає',
      'що я пропускаю',
      'мої слабкі місця',
      'яким м’язам треба більше уваги',
      'про які м’язи я забуваю',
      'є перекіс у тренуваннях?',
      'шо в мене недотреноване',
      'чи не забиваю я на ноги',
      'який м’яз отримує найменше сетів',
      'какие мышцы отстают',
      'что я недотренировываю',
    ],
    facets: {
      how: [
        'I take the muscles you trained in the last 4 weeks and rank them by hard sets this week; the two lowest are behind.',
        'Я беру м’язи, які ти тренував за останні 4 тижні, і сортую їх за робочими сетами цього тижня; два найнижчі — відстають.',
      ],
      should: [
        "Yes, put the lagging muscles first in your next session, while you're fresh.",
        'Так, став відстаючі м’язи першими на наступному тренуванні, поки ти свіжий.',
      ],
      why: [
        'A muscle that gets far fewer sets than the rest grows slower and can lead to imbalances over time.',
        'М’яз, який отримує значно менше сетів за інші, росте повільніше й з часом може дати дисбаланс.',
      ],
    },
  },

  recovery: {
    ex: [
      'am i recovered',
      'is my chest recovered',
      'which muscles are ready to train',
      'are my legs fresh enough',
      "what's still sore",
      'recovery status',
      'can i train back yet, is it recovered',
      'how recovered are my shoulders',
      'is my body ready for another session',
      'which muscles are still recovering',
      'are my quads ready',
      'still have doms in my legs',
      'how long until my chest recovers',
      'show muscle readiness',
      'is it too soon to hit chest again',
    ],
    exUk: [
      'чи я відновився',
      'груди вже відновились?',
      'які м’язи готові до тренування',
      'ноги свіжі?',
      'що ще не відновилось',
      'стан відновлення',
      'спина вже відновилась, можна тренувати?',
      'наскільки відновились плечі',
      'у мене крепатура в ногах',
      'які м’язи ще відновлюються',
      'квадрицепс готовий?',
      'забиті ноги після присіду',
      'коли відновляться груди',
      'покажи готовність м’язів',
      'мышцы восстановились?',
    ],
    facets: {
      how: [
        "I estimate each muscle's readiness from how many sets it got and how long ago, and show it as a percentage.",
        'Я оцінюю готовність кожного м’яза за кількістю сетів і часом від тренування й показую у відсотках.',
      ],
      should: [
        'Under about 85% readiness, train a different muscle today; above that, go ahead.',
        'Якщо готовність нижче приблизно 85% — сьогодні тренуй інше; вище — вперед.',
      ],
      when: [
        'Most muscles recover in 48–72 hours after a hard session; big leg and back sessions can take longer.',
        'Більшість м’язів відновлюються за 48–72 години після важкого тренування; важкі ноги й спина — довше.',
      ],
      why: [
        'Training a muscle before it recovers means weaker sets and more fatigue, not more growth.',
        'Тренувати невідновлений м’яз — це слабші сети й більше втоми, а не більше росту.',
      ],
    },
  },

  today: {
    ex: [
      'what should i train today',
      "what's the workout today",
      'what do i do today',
      "today's plan?",
      'what are we lifting today',
      'which muscles today',
      'what should i do at the gym today',
      "what's on for today",
      "i'm at the gym now, what do i do",
      'what should i work on today',
      "give me today's session",
      'is today a training day',
      'legs or upper today?',
      "what's my workout right now",
    ],
    exUk: [
      'що тренувати сьогодні',
      'яке тренування сьогодні',
      'що робимо сьогодні',
      'план на сьогодні',
      'що качати сьогодні',
      'які м’язи сьогодні',
      'я в залі, що робити зараз',
      'що сьогодні по плану',
      'сьогодні тренування чи відпочинок?',
      'шо седня тренуємо',
      'чим займатися сьогодні',
      'дай тренування на сьогодні',
      'що мені зараз робити в залі',
      'что тренировать сегодня',
      'что сегодня качаем',
    ],
    facets: {
      how: [
        "I take today's day from your programme if you have one, and check it against what's recovered and any injuries you've logged.",
        'Я беру сьогоднішній день із твоєї програми, якщо вона є, і звіряю з тим, що відновилося, та з записаними травмами.',
      ],
      why: [
        "Today's pick follows your plan and your recovery, so you train what's ready and don't repeat a tired muscle.",
        'Вибір на сьогодні спирається на план і відновлення, щоб ти тренував готове й не добивав утомлений м’яз.',
      ],
      where: [
        'Ask me here; the plan for today is also on the coach screen.',
        'Спитай мене тут; план на сьогодні також є на екрані тренера.',
      ],
    },
  },

  tomorrow: {
    ex: [
      'what should i train tomorrow',
      "what's tomorrow's workout",
      'do i train tomorrow',
      'is tomorrow a rest day',
      "tomorrow's plan",
      "what's on tomorrow",
      'which muscles tomorrow',
      'should i go to the gym tomorrow',
      'what am i doing tomorrow at the gym',
      'tomorrow legs or upper',
      'plan for tomorrow?',
      'am i lifting tomorrow',
      'what do i have tomorrow',
      "what will tomorrow's session be",
    ],
    exUk: [
      'що тренувати завтра',
      'яке тренування завтра',
      'завтра тренуюсь?',
      'завтра день відпочинку?',
      'план на завтра',
      'що завтра по плану',
      'які м’язи завтра',
      'йти в зал завтра?',
      'що робимо завтра в залі',
      'завтра ноги чи верх',
      'шо завтра качаємо',
      'у мене завтра тренування?',
      'що в мене на завтра',
      'что тренировать завтра',
      'завтра тренировка?',
    ],
    facets: {
      how: [
        "I read tomorrow's day from your programme and check it against how recovered your muscles will be.",
        'Я беру завтрашній день із програми й звіряю з тим, наскільки відновляться м’язи.',
      ],
      where: [
        'Ask me here, or look at the week view of your programme.',
        'Спитай мене тут або подивись тиждень у своїй програмі.',
      ],
    },
  },

  next_session: {
    ex: [
      'when is my next workout',
      'when do i train next',
      "what's my next session",
      'next training day?',
      'when should i go to the gym next',
      "what's the next workout in my plan",
      "when's my next gym day",
      'what is my next training session',
      'when do i lift again',
      'next workout?',
      'what comes next in my program',
      'which day is my next session',
      'when is the next leg day',
      'when am i training again',
    ],
    exUk: [
      'коли наступне тренування',
      'коли мені знову тренуватись',
      'яке наступне тренування',
      'наступний день тренування?',
      'коли йти в зал наступного разу',
      'що далі за програмою',
      'коли в мене наступний зал',
      'коли знову тренування',
      'наступне тренування яке',
      'в який день наступне заняття',
      'коли наступний день ніг',
      'коли там наступна трєня',
      'коли я знову тренуюсь',
      'когда следующая тренировка',
      'какая следующая тренировка',
    ],
    facets: {
      how: [
        'I look ahead up to 7 days in your programme and give the first planned day and its name.',
        'Я дивлюся в програмі на 7 днів уперед і називаю перший запланований день та його назву.',
      ],
      when: [
        "Without a programme there's no fixed day; the best next session is the soonest one you can make, ideally today.",
        'Без програми фіксованого дня нема; найкраще наступне тренування — найближче, яке зможеш, бажано сьогодні.',
      ],
      where: [
        'Your upcoming days are in the programme on the coach screen.',
        'Наступні дні — у програмі на екрані тренера.',
      ],
    },
  },

  last_session: {
    ex: [
      'what did i do last workout',
      'show my last session',
      'what did i train yesterday',
      'last workout summary',
      'how was my previous session',
      'what did i do last time at the gym',
      'my last training?',
      'how many sets did i do last workout',
      'how long was my last session',
      'what exercises did i do yesterday',
      'recap of my last workout',
      'what was my previous workout',
      'last gym session details',
      'when was my last workout',
    ],
    exUk: [
      'що я робив на минулому тренуванні',
      'покажи останнє тренування',
      'що я тренував учора',
      'підсумок останнього тренування',
      'як пройшло попереднє тренування',
      'що було минулого разу в залі',
      'моє останнє заняття',
      'скільки сетів було на останньому тренуванні',
      'скільки тривало останнє тренування',
      'які вправи я робив вчора',
      'шо я робив на прошлій трєні',
      'попереднє тренування яке було',
      'коли було останнє тренування',
      'что я делал на прошлой тренировке',
      'последняя тренировка',
    ],
    facets: {
      what: [
        'The summary shows the date, the number of working sets, the duration and the first few exercises of your latest finished workout.',
        'Підсумок показує дату, кількість робочих сетів, тривалість і перші вправи твого останнього завершеного тренування.',
      ],
      where: [
        'Full details are in your workout history; open the latest session.',
        'Повні деталі — в історії тренувань; відкрий останнє.',
      ],
      how: [
        'Warm-up sets are left out of the set count; the duration is from start to finish of the logged session.',
        'Розминкові сети в підрахунок не входять; тривалість — від початку до кінця записаного тренування.',
      ],
    },
  },

  week: {
    ex: [
      'how was my week',
      'weekly summary',
      'how many workouts this week',
      'my training this week',
      'how many sessions in the last 7 days',
      'week recap',
      'how did i do this week',
      'how many sets did i do this week',
      'am i on track this week',
      'weekly stats',
      'did i train enough this week',
      "this week's training summary",
      'how many times did i train this week',
      'show my week',
    ],
    exUk: [
      'як пройшов мій тиждень',
      'підсумок тижня',
      'скільки тренувань цього тижня',
      'моє тренування за тиждень',
      'скільки тренувань за останні 7 днів',
      'що за тиждень',
      'як я потренувався цього тижня',
      'скільки сетів за тиждень',
      'статистика за тиждень',
      'чи достатньо я тренувався цього тижня',
      'скільки разів я був у залі цього тижня',
      'покажи мій тиждень',
      'шо там по тижню',
      'итоги недели',
      'сколько тренировок на этой неделе',
    ],
    facets: {
      how: [
        'I count finished sessions and hard sets from the last 7 days and compare with how many sessions you usually do in a week.',
        'Я рахую завершені тренування й робочі сети за останні 7 днів і порівнюю з тим, скільки тренувань у тебе зазвичай на тиждень.',
      ],
      what: [
        "Hard sets are working sets; warm-ups aren't counted.",
        'Робочі сети — це основні підходи; розминкові не рахуються.',
      ],
      where: [
        'Ask me here; your history shows the same week day by day.',
        'Спитай мене тут; в історії той самий тиждень видно по днях.',
      ],
    },
  },

  streak: {
    ex: [
      "what's my streak",
      'how long is my streak',
      'how many days in a row',
      'current streak?',
      'did i break my streak',
      'streak count',
      'how many days is my streak now',
      'am i still on a streak',
      'show my training streak',
      "what's my consistency streak",
      'how many days in a row have i kept it up',
      'is my streak still alive',
      'my streak',
      'how long have i kept the streak going',
    ],
    exUk: [
      'яка в мене серія',
      'скільки днів поспіль',
      'яка серія зараз',
      'я не перервав серію?',
      'скільки днів підряд',
      'моя серія',
      'покажи серію тренувань',
      'серія ще жива?',
      'скільки триває моя серія',
      'скіко днів підряд у мене',
      'стрік який',
      'серія днів',
      'скільки днів поспіль я тримаюсь',
      'какая у меня серия',
      'сколько дней подряд',
    ],
    facets: {
      how: [
        "The streak counts days back from today since your first workout; unlogged past days count as rest, so an ordinary gap doesn't reset it. Today counts once you log something.",
        'Серія рахує дні назад від сьогодні з першого тренування; пропущені дні минулого вважаються відпочинком, тож звичайна перерва її не скидає. Сьогодні зараховується, щойно щось запишеш.',
      ],
      what: [
        'A consistency streak: the unbroken run of days that were either trained or counted as rest.',
        'Серія регулярності — безперервний ряд днів, які були або тренувальними, або зараховані як відпочинок.',
      ],
    },
  },

  total: {
    ex: [
      'how many workouts have i done in total',
      'total sessions logged',
      'how many sessions all time',
      'total number of workouts',
      'how many times have i trained altogether',
      'all-time workout count',
      'how many workouts since i started',
      'how many gym sessions have i logged',
      'total training sessions?',
      'count of all my workouts',
      'how many trainings in total',
      'lifetime session count',
      'how many workouts in the app',
      'total workouts ever',
    ],
    exUk: [
      'скільки всього тренувань',
      'загалом скільки тренувань записано',
      'скільки тренувань за весь час',
      'загальна кількість тренувань',
      'скільки разів я тренувався загалом',
      'скільки тренувань з початку',
      'усього тренувань скільки',
      'скільки занять я записав',
      'скока всього трєнь',
      'всього тренувань у додатку',
      'скільки я вже натренував загалом',
      'загальна кількість занять',
      'лічильник усіх тренувань',
      'сколько всего тренировок',
      'всего тренировок за все время',
    ],
    facets: {
      how: [
        'I count every finished workout in your log and give the date of the first one.',
        'Я рахую всі завершені тренування в журналі й називаю дату першого.',
      ],
      where: [
        'Your full history is in the workout history screen.',
        'Уся історія — на екрані історії тренувань.',
      ],
    },
  },

  sleep: {
    ex: [
      'how did i sleep',
      'how much did i sleep last night',
      'my sleep this week',
      'sleep average',
      'am i sleeping enough',
      'how many hours of sleep do i need',
      'does sleep matter for muscle',
      'i slept badly',
      'only slept 5 hours',
      'sleep stats',
      'how much sleep for recovery',
      'is 6 hours of sleep enough',
      'why is sleep important for training',
      'show my sleep',
      'my sleep last week',
    ],
    exUk: [
      'як я спав',
      'скільки я спав минулої ночі',
      'мій сон за тиждень',
      'середній сон',
      'чи достатньо я сплю',
      'скільки треба спати',
      'чи важливий сон для м’язів',
      'погано спав',
      'поспав лише 5 годин',
      'статистика сну',
      'скільки сну для відновлення',
      '6 годин сну вистачає?',
      'не виспався',
      'покажи мій сон',
      'сколько я спал',
    ],
    facets: {
      howMuch: [
        'Aim for 7+ hours a night; I show last night and your 7-night average.',
        'Ціль — 7+ годин на ніч; я показую минулу ніч і середнє за 7 ночей.',
      ],
      why: [
        'Recovery and muscle repair mostly happen during sleep; short sleep lowers performance and slows progress.',
        'Відновлення й відбудова м’язів відбуваються здебільшого уві сні; недосип знижує результати й гальмує прогрес.',
      ],
      where: [
        "Log sleep in the app's sleep tracking; I can only judge nights that are logged.",
        'Записуй сон у трекері сну в додатку; я можу судити лише записані ночі.',
      ],
      should: [
        "After a very short night, rest longer between sets and keep the session lighter; under 5 hours it's fine to skip.",
        'Після дуже короткої ночі відпочивай довше між сетами й роби тренування легшим; менше 5 годин — можна пропустити.',
      ],
    },
  },

  deload: {
    ex: [
      'when is my deload',
      'do i need a deload',
      'what is a deload week',
      'is this a deload week',
      'should i take an easy week',
      'how often should i deload',
      'how do i deload',
      "when's the lighter week",
      'is it time for a deload',
      'what do i do on a deload',
      'deload next week?',
      'why deload',
      'how much lighter on a deload',
      'should i deload if i feel beat up',
    ],
    exUk: [
      'коли розвантаження',
      'мені потрібен розвантажувальний тиждень?',
      'що таке розвантажувальний тиждень',
      'цей тиждень розвантажувальний?',
      'чи брати легкий тиждень',
      'як часто робити розвантаження',
      'як робити розвантаження',
      'коли легший тиждень',
      'вже час розвантажуватись?',
      'що робити на розвантаженні',
      'навіщо розвантажувальний тиждень',
      'наскільки легше на розвантаженні',
      'коли там дилоад',
      'когда разгрузочная неделя',
      'нужна ли разгрузка',
    ],
    facets: {
      what: [
        'A deload is a lighter week: fewer sets at the same weights, so fatigue drops while strength stays.',
        'Розвантаження — це легший тиждень: менше сетів з тими самими вагами, щоб спала втома, а сила лишилася.',
      ],
      when: [
        "In a programme it's the last week of each block; without one I deload you when your numbers start to drop.",
        'У програмі це останній тиждень кожного блоку; без програми я розвантажую тебе, коли цифри починають падати.',
      ],
      why: [
        'Fatigue builds over hard weeks; a lighter week lets you recover and come back stronger.',
        'За важкі тижні накопичується втома; легший тиждень дає відновитися й повернутися сильнішим.',
      ],
      how: [
        "Keep the same weights and exercises, cut the number of sets, and don't chase records that week.",
        'Лиши ті самі ваги й вправи, скороти кількість сетів і не женися за рекордами цього тижня.',
      ],
      howMuch: [
        'Roughly one lighter week every 4–8 weeks of hard training is common.',
        'Зазвичай один легший тиждень на кожні 4–8 тижнів важких тренувань.',
      ],
    },
  },

  plan: {
    ex: [
      'show my program',
      "what's my training plan",
      "what's my split",
      'my workout schedule',
      'do i have a programme',
      'write me a program',
      'what does my plan look like this week',
      'which days do i train',
      'how many weeks is my program',
      'can you make me a workout plan',
      "what's my weekly schedule",
      'show the plan',
      'my training program',
      "what's in my programme",
    ],
    exUk: [
      'покажи мою програму',
      'який мій план тренувань',
      'який у мене спліт',
      'мій розклад тренувань',
      'у мене є програма?',
      'напиши мені програму',
      'який план на цей тиждень',
      'в які дні я тренуюсь',
      'скільки тижнів у програмі',
      'склади мені план тренувань',
      'покажи план',
      'моя програма тренувань',
      'шо в мене по програмі',
      'покажи мою программу',
      'составь программу тренировок',
    ],
    facets: {
      how: [
        'Tap Write my programme and I build it from your history: training days, split, session length and a block of weeks ending in a lighter week.',
        'Натисни «Написати програму» — і я зберу її з твоєї історії: дні, спліт, тривалість тренувань і блок тижнів із легшим тижнем наприкінці.',
      ],
      where: [
        'Your programme is on the coach screen; the Write my programme button is at the top.',
        'Програма — на екрані тренера; кнопка «Написати програму» вгорі.',
      ],
      what: [
        'The plan lists your training days by weekday with the split for each, the current week of the block and the target session length.',
        'План показує дні тренувань за днями тижня зі сплітом для кожного, поточний тиждень блоку й цільову тривалість.',
      ],
    },
  },

  skip: {
    ex: [
      'can i skip the gym today',
      'is it ok to skip a workout',
      'should i skip today',
      'i want to take a day off',
      "can i miss today's session",
      'is it fine to skip leg day',
      "i don't feel like going, can i skip",
      'should i skip training if i slept badly',
      'skip today or not',
      'can i take today off',
      'is missing one workout bad',
      "should i skip if i'm sick",
      "i'm going to miss the gym today",
      'day off today?',
    ],
    exUk: [
      'можна сьогодні пропустити зал',
      'чи нормально пропустити тренування',
      'пропустити сьогодні?',
      'хочу вихідний',
      'можна не йти сьогодні',
      'можна пропустити день ніг',
      'не піду сьогодні в зал',
      'пропустити, якщо погано спав?',
      'чи страшно пропустити одне тренування',
      'пропускати, якщо хворію?',
      'сьогодні прогуляю зал',
      'беру вихідний сьогодні',
      'можна сьогодні не тренуватись',
      'можно пропустить тренировку',
      'пропущу сегодня зал',
    ],
    facets: {
      should: [
        "Skip if you're ill, injured or slept under 5 hours. Otherwise a short session beats none.",
        'Пропускай, якщо хворий, травмований чи спав менше 5 годин. Інакше коротке тренування краще за жодне.',
      ],
      howMuch: [
        "If you're unsure, do 30 minutes: the main lifts only, fewer sets.",
        'Якщо вагаєшся — 30 хвилин: лише основні вправи, менше сетів.',
      ],
      why: [
        "One missed session doesn't cost progress, but skipping becomes a habit fast; a short session keeps the routine.",
        'Одне пропущене тренування прогресу не зіпсує, але пропуски швидко стають звичкою; коротке тренування тримає ритм.',
      ],
    },
  },

  motivation: {
    ex: [
      "i don't want to train today",
      'no motivation to go to the gym',
      'i feel lazy',
      'too tired to work out',
      'how do i get motivated',
      "i'm exhausted, can't be bothered",
      'i have zero motivation',
      'feeling unmotivated lately',
      "i just don't want to lift",
      'how to stay motivated to train',
      "i'm so lazy today",
      'motivation is gone',
      "tired after work, don't want to go",
      'how do i make myself go to the gym',
    ],
    exUk: [
      'не хочу сьогодні тренуватись',
      'нема мотивації йти в зал',
      'мені лінь',
      'втомився, не хочу в зал',
      'як себе замотивувати',
      'немає сил на тренування',
      'нуль мотивації',
      'останнім часом нема мотивації',
      'ліньки йти в зал',
      'як не втрачати мотивацію',
      'лінуюсь сьогодні',
      'після роботи нема сил',
      'як змусити себе піти в зал',
      'не хочу тренироваться',
      'нет мотивации',
    ],
    facets: {
      how: [
        "Lower the bar to start: pack the bag, get to the gym and do the warm-up, then decide. Once you've started you rarely leave.",
        'Знизь поріг старту: збери сумку, дійди до залу й зроби розминку — тоді вирішуй. Коли вже почав, рідко йдеш.',
      ],
      why: [
        'Motivation follows action more often than it leads it; starting is the hard part, and the warm-up usually changes your mood.',
        'Мотивація частіше приходить після дії, а не до неї; найважче — почати, а розминка зазвичай змінює настрій.',
      ],
      should: [
        "Low motivation alone isn't a reason to skip; being ill or badly short on sleep is.",
        'Сама лише відсутність мотивації — не причина пропускати; хвороба чи сильний недосип — причина.',
      ],
    },
  },

  warmup: {
    ex: [
      'how should i warm up',
      'how to warm up before lifting',
      'do i need to warm up',
      'warm up before workout?',
      'how long should my warm-up be',
      'best warm-up for the gym',
      'should i do cardio to warm up',
      'why warm up',
      "what's a good warm-up routine",
      'how many minutes to warm up',
      'is warming up necessary',
      'general warm-up before training',
      'warm up routine for strength training',
      'can i skip the warm-up',
    ],
    exUk: [
      'як розминатись',
      'як правильно розімнутись перед тренуванням',
      'чи потрібна розминка',
      'розминка перед тренуванням?',
      'скільки має тривати розминка',
      'найкраща розминка для залу',
      'кардіо для розминки?',
      'навіщо розминка',
      'яка гарна розминка',
      'скільки хвилин розминатись',
      'розминка обов’язкова?',
      'як розігрітись перед залом',
      'можна без розминки',
      'шо робити на розминці',
      'как делать разминку',
    ],
    facets: {
      how: [
        'About 5 minutes of easy cardio, then 2–3 ramp-up sets on your first lift at roughly 50%, 70% and 85% of the working weight.',
        'Близько 5 хвилин легкого кардіо, потім 2–3 підвідні сети на першій вправі — приблизно 50%, 70% і 85% робочої ваги.',
      ],
      why: [
        'A warm-up raises body temperature and grooves the movement, so your working sets are stronger and safer.',
        'Розминка підвищує температуру тіла й налаштовує рух, тож робочі сети сильніші й безпечніші.',
      ],
      howMuch: [
        "Usually 5–10 minutes in total is enough; longer if you're older or it's cold.",
        'Зазвичай 5–10 хвилин загалом достатньо; довше, якщо ти старший чи холодно.',
      ],
      should: [
        'Yes, always warm up before heavy lifting; it takes a few minutes and pays off.',
        'Так, перед важкими вагами розминайся завжди — це кілька хвилин, які окупаються.',
      ],
      where: [
        'The app adds the ramp-up sets to your first lift for you.',
        'Додаток сам додає підвідні сети до першої вправи.',
      ],
    },
  },

  cooldown: {
    ex: [
      'should i cool down after lifting',
      'how to cool down after a workout',
      'do i need to stretch after training',
      'cool down routine',
      'what to do after the workout',
      'how long should a cool down be',
      'stretching after the gym?',
      'is stretching after lifting worth it',
      'why cool down',
      'best stretches after training',
      'cool-down after legs',
      'should i stretch at the end',
      'how do i start the cool-down in the app',
      'does cooling down help recovery',
    ],
    exUk: [
      'чи потрібна заминка після тренування',
      'як робити заминку',
      'треба розтягуватись після залу?',
      'заминка після тренування',
      'що робити після тренування',
      'скільки триває заминка',
      'розтяжка після залу?',
      'чи варто розтягуватись після силового',
      'навіщо заминка',
      'яку розтяжку робити після тренування',
      'заминка після ніг',
      'розтягуватись в кінці?',
      'як запустити заминку в додатку',
      'нужна ли заминка',
      'растяжка после тренировки',
    ],
    facets: {
      how: [
        '5–10 minutes of easy walking or cycling, then stretch the muscles you trained.',
        '5–10 хвилин легкої ходьби чи велосипеда, потім розтягни м’язи, які тренував.',
      ],
      howMuch: [
        '5–10 minutes is enough; hold each stretch for about 20–30 seconds.',
        '5–10 хвилин достатньо; кожну розтяжку тримай приблизно 20–30 секунд.',
      ],
      why: [
        "It brings your heart rate down gradually and helps you feel less stiff; it's optional, not magic for recovery.",
        'Вона поступово знижує пульс і зменшує скутість; це за бажанням, а не чарівна кнопка відновлення.',
      ],
      where: [
        'Start the cool-down block at the end of the session; rest stops counting while it runs.',
        'Запусти блок заминки наприкінці тренування — поки він іде, відпочинок не рахується.',
      ],
    },
  },

  cardio: {
    ex: [
      'should i do cardio',
      'cardio before or after weights',
      'how much cardio should i do',
      'can i run on lifting days',
      'treadmill after the gym?',
      'does cardio kill gains',
      'how long should cardio be',
      'is cycling good on rest days',
      'cardio on leg day?',
      'how often should i do cardio',
      'should i run before lifting',
      'best time for cardio',
      'how many minutes on the bike after lifting',
      'does cardio help recovery',
    ],
    exUk: [
      'чи робити кардіо',
      'кардіо до чи після силового',
      'скільки кардіо робити',
      'можна бігати в дні силових',
      'доріжка після залу?',
      'кардіо заважає росту м’язів?',
      'скільки має тривати кардіо',
      'велосипед у дні відпочинку',
      'кардіо в день ніг?',
      'як часто робити кардіо',
      'бігати перед тренуванням?',
      'коли краще робити кардіо',
      'скільки хвилин на велосипеді після тренування',
      'кардио до или после',
      'сколько делать кардио',
    ],
    facets: {
      when: [
        'After lifting, not before; longer sessions go on separate days.',
        'Після силового, не до; довші сесії — окремими днями.',
      ],
      howMuch: [
        '10–20 minutes easy on lifting days; longer sessions on separate days.',
        '10–20 хвилин легко в силові дні; довші сесії — в окремі дні.',
      ],
      why: [
        'Cardio before lifting tires you for the heavy sets; easy cardio after helps recovery and heart health.',
        'Кардіо перед силовим втомлює перед важкими сетами; легке кардіо після допомагає відновленню й серцю.',
      ],
      should: [
        'Yes, as long as it stays easy on lifting days; hard or long cardio right before lifting costs strength.',
        'Так, якщо в силові дні воно легке; важке чи довге кардіо перед залом забирає силу.',
      ],
    },
  },

  reps: {
    ex: [
      'how many reps should i do',
      'what rep range for muscle growth',
      'reps for strength?',
      'how many reps per set',
      'is 8 to 12 reps best',
      'low reps or high reps',
      'what rep range should i use',
      'how many reps for hypertrophy',
      'should i do 5 reps or 10',
      'rep range for my goal',
      'how many repetitions per set for size',
      'what reps for endurance',
      'when do i move up in reps',
      'why this rep range',
    ],
    exUk: [
      'скільки повторів робити',
      'який діапазон повторів для росту м’язів',
      'повтори для сили?',
      'скільки повторів у сеті',
      '8–12 повторів — найкраще?',
      'мало чи багато повторів',
      'який діапазон повторів мені',
      'скільки повторень на масу',
      '5 повторів чи 10',
      'діапазон повторів під мою ціль',
      'скільки разів робити в підході',
      'повтори на витривалість',
      'скока повторів робити',
      'сколько повторений делать',
      'сколько повторов на массу',
    ],
    facets: {
      howMuch: [
        'Strength: 3–6 reps; muscle: 6–12; endurance: 12–20, with the last 1–2 reps hard.',
        'Сила: 3–6 повторів; м’язи: 6–12; витривалість: 12–20, останні 1–2 повтори важкі.',
      ],
      why: [
        'Muscle grows across a wide range of reps if sets are close to failure; heavier, lower reps build more maximal strength.',
        'М’язи ростуть у широкому діапазоні повторів, якщо сети близькі до відмови; важчі ваги й менше повторів більше розвивають максимальну силу.',
      ],
      how: [
        'Work inside your range; when you hit the top of it on every set, add weight and start again at the bottom.',
        'Працюй у своєму діапазоні; коли дійшов до верху на всіх сетах — додай вагу й почни знову знизу.',
      ],
      what: [
        'A rep range is the span of reps per set you aim for, set by your focus in the programme.',
        'Діапазон повторів — це проміжок повторів у сеті, на який ти цілишся; його задає фокус у програмі.',
      ],
    },
  },

  failure: {
    ex: [
      'should i train to failure',
      'do i need to go to failure',
      'is training to failure bad',
      'failure on every set?',
      'how close to failure should i go',
      'should i take the last set to failure',
      'failure on squats?',
      'is failure needed for growth',
      'reps in reserve or failure',
      'can i go to failure on bench',
      'why not go to failure every set',
      'failure on isolation exercises',
      'going to failure on compounds',
      'how often should i hit failure',
    ],
    exUk: [
      'чи тренуватись до відмови',
      'треба до відмови?',
      'до відмови — це погано?',
      'відмова на кожному сеті?',
      'наскільки близько до відмови',
      'останній сет до відмови?',
      'до відмови на присіді?',
      'чи потрібна відмова для росту',
      'запас повторів чи до відмови',
      'можна до відмови на жимі',
      'чому не можна щосету до відмови',
      'відмова на ізолюючих',
      'як часто робити до відказу',
      'тренироваться до отказа',
      'нужно ли до отказа',
    ],
    facets: {
      should: [
        'Not on every set. Leave 1–2 reps in reserve on compounds; take isolation lifts to failure on the last set.',
        'Не на кожному сеті. На базових лишай 1–2 повтори в запасі; ізолюючі — до відмови на останньому сеті.',
      ],
      why: [
        'Failure on every set piles up fatigue and costs reps in later sets without adding much growth.',
        'Відмова щосету накопичує втому й забирає повтори в наступних сетах, майже не додаючи росту.',
      ],
      what: [
        "Failure means you can't complete another rep with good form.",
        'Відмова — це коли ти не можеш зробити ще один повтор з гарною технікою.',
      ],
      howMuch: [
        'Most working sets end 1–2 reps short of failure; save true failure for the last set of isolation work.',
        'Більшість робочих сетів закінчуй за 1–2 повтори до відмови; справжню відмову — на останньому сеті ізолюючих.',
      ],
    },
  },

  bodyweight: {
    ex: [
      "what's my body weight",
      'my last weigh-in',
      'how much do i weigh',
      'what did i weigh last time',
      'my weight?',
      'when did i last weigh in',
      'show my body weight',
      'current bodyweight',
      'what was my last weigh in',
      'how heavy am i now',
      'latest body weight',
      'my weight according to the app',
      'did i log my weight',
      "what's my weight right now",
    ],
    exUk: [
      'яка моя вага',
      'останнє зважування',
      'скільки я важу',
      'скільки я важив минулого разу',
      'моя вага тіла',
      'коли я востаннє зважувався',
      'покажи вагу тіла',
      'поточна вага тіла',
      'скільки я зараз важу',
      'остання вага',
      'яка в мене вага за додатком',
      'я записував свою вагу?',
      'шо там по вазі тіла',
      'сколько я вешу',
      'мой вес',
    ],
    facets: {
      how: [
        'I show your most recent logged weigh-in and its date.',
        'Я показую твоє останнє записане зважування та його дату.',
      ],
      when: [
        'Weigh in at the same time of day, ideally in the morning after the toilet, for comparable numbers.',
        'Зважуйся в той самий час, найкраще зранку після туалету — так цифри порівнювані.',
      ],
      where: [
        "Log weigh-ins in the app's body metrics, or just tell me your weight.",
        'Записуй зважування в показниках тіла в додатку або просто скажи мені свою вагу.',
      ],
    },
  },

  session_length: {
    ex: [
      'how long should a workout be',
      'how long are my workouts',
      'average workout duration',
      'how long do my sessions take',
      'is an hour workout enough',
      'how long should i train',
      'workout length?',
      'how many minutes should a session last',
      'my average session length',
      'is 90 minutes in the gym too long',
      'how long was my average workout',
      'ideal training duration',
      'how long do i spend in the gym',
      'planned session duration',
    ],
    exUk: [
      'скільки має тривати тренування',
      'скільки тривають мої тренування',
      'середня тривалість тренування',
      'скільки часу займають мої тренування',
      'години тренування достатньо?',
      'скільки часу тренуватись',
      'тривалість тренування',
      'скільки хвилин має бути заняття',
      'моя середня тривалість',
      '90 хвилин у залі — забагато?',
      'скільки часу я проводжу в залі',
      'ідеальна тривалість тренування',
      'як довго тренуватись',
      'сколько должна длиться тренировка',
      'сколько времени тренироваться',
    ],
    facets: {
      howMuch: [
        'The plan targets about 60 minutes by default; 45–75 minutes covers most effective sessions.',
        'За замовчуванням план розрахований приблизно на 60 хвилин; 45–75 хвилин вистачає для більшості ефективних тренувань.',
      ],
      how: [
        "I average the duration of your last 10 finished sessions and compare it with your plan's target.",
        'Я рахую середню тривалість твоїх останніх 10 завершених тренувань і порівнюю з цільовою за планом.',
      ],
      should: [
        "If sessions run long, it's usually extra rest chatter or too many exercises; keep the main lifts and superset the rest.",
        'Якщо тренування затягуються, зазвичай винні зайві паузи чи забагато вправ; лиши основні, решту — суперсетами.',
      ],
    },
  },

  swap: {
    ex: [
      'how do i swap an exercise',
      'can i replace bench press',
      'swap squats for something else',
      'what can i do instead of deadlifts',
      'the machine is taken, replace it',
      'how to substitute an exercise in my workout',
      'replace pull-ups',
      'alternative to overhead press',
      "can i change an exercise in today's session",
      'swap leg press',
      'how do i switch exercises mid-workout',
      'substitute for barbell rows',
      "don't have a squat rack, what instead",
      'exchange an exercise',
    ],
    exUk: [
      'як замінити вправу',
      'можна замінити жим лежачи',
      'заміни присід на щось інше',
      'що робити замість станової',
      'тренажер зайнятий, заміни',
      'як поміняти вправу в тренуванні',
      'заміна підтягувань',
      'альтернатива жиму стоячи',
      'можна змінити вправу в сьогоднішньому тренуванні',
      'замінити жим ногами',
      'що замість тяги штанги в нахилі',
      'нема стійки для присіду, що замість',
      'поміняй вправу',
      'как заменить упражнение',
      'чем заменить жим',
    ],
    facets: {
      how: [
        'In the session, tap the exercise, then Swap, and pick one of the offered lifts.',
        'У тренуванні тапни вправу, потім «Замінити», й обери одну із запропонованих.',
      ],
      what: [
        'I only offer lifts that train the same muscle and that your gym has.',
        'Я пропоную лише вправи на той самий м’яз, які є у твоєму залі.',
      ],
      where: [
        'The Swap option is on each exercise inside the active session.',
        'Опція «Замінити» — на кожній вправі всередині активного тренування.',
      ],
      should: [
        'Swapping is fine when equipment is busy or a lift causes pain; for long-term progress keep your main lifts mostly the same.',
        'Замінювати нормально, коли зайняте обладнання чи вправа болить; для довгого прогресу основні вправи краще лишати сталими.',
      ],
    },
  },

  technique: {
    ex: [
      'how to do a proper deadlift',
      'bench press technique',
      'how do i do squats correctly',
      'check my form',
      "what's the right form for overhead press",
      'how to do pull-ups properly',
      'is my technique ok',
      'form tips for rows',
      'how do i do a romanian deadlift',
      'correct form for lunges',
      'where can i see how to do an exercise',
      'technique video for bench',
      'how to improve my squat form',
      'proper technique for hip thrust',
    ],
    exUk: [
      'як правильно робити станову',
      'техніка жиму лежачи',
      'як правильно присідати',
      'перевір мою техніку',
      'яка правильна техніка жиму стоячи',
      'як правильно підтягуватись',
      'чи нормальна в мене техніка',
      'поради щодо техніки тяги',
      'як робити румунську тягу',
      'як правильно робити випади',
      'де подивитись, як робити вправу',
      'відео техніки жиму',
      'як покращити техніку присіду',
      'как правильно делать жим',
      'техника становой',
    ],
    facets: {
      how: [
        'Open the lift in the exercise library for photos, cues and Learn videos, then film one set from the side and compare.',
        'Відкрий вправу в бібліотеці — там фото, підказки й відео Learn, потім зніми один сет збоку й порівняй.',
      ],
      where: [
        'Technique lives in the exercise library: each lift has photos, cues and Learn videos.',
        'Техніка — в бібліотеці вправ: у кожної є фото, підказки й відео Learn.',
      ],
      why: [
        'Good technique lets you load the target muscle and add weight safely over time.',
        'Правильна техніка навантажує потрібний м’яз і дає безпечно додавати вагу з часом.',
      ],
      should: [
        'If form breaks down, lower the weight until every rep looks the same; if a lift hurts, stop it.',
        'Якщо техніка сиплеться, знижуй вагу, доки всі повтори не будуть однакові; якщо вправа болить — зупинись.',
      ],
    },
  },

  protein: {
    ex: [
      'how much protein do i need',
      'protein per day for muscle',
      'what should i eat to build muscle',
      'how many grams of protein per kg',
      'is my diet important for gains',
      'how much protein per meal',
      "what's a good diet for lifting",
      'do i need a protein shake',
      'how many meals a day for protein',
      'nutrition for strength training',
      'how much should i eat',
      'protein intake for a 80 kg guy',
      'is 100 g of protein enough',
      'food for muscle growth',
    ],
    exUk: [
      'скільки білка треба',
      'скільки білка на день для м’язів',
      'що їсти, щоб рости',
      'скільки грамів білка на кг',
      'чи важлива дієта для росту',
      'скільки білка за прийом їжі',
      'яке харчування для залу',
      'треба протеїн пити?',
      'скільки разів їсти для білка',
      'харчування для силових',
      'скільки мені їсти',
      'скільки білка при вазі 80 кг',
      '100 г білка вистачить?',
      'сколько белка нужно',
      'що по їжі для масонабору',
    ],
    facets: {
      howMuch: [
        'About 1.6–2.2 g of protein per kg of body weight a day, spread over 3–5 meals.',
        'Приблизно 1,6–2,2 г білка на кг ваги тіла на день, розподілено на 3–5 прийомів їжі.',
      ],
      why: [
        'Protein supplies the building blocks for muscle repair; enough total food lets you recover and grow.',
        'Білок — будівельний матеріал для відновлення м’язів; достатньо їжі загалом дає відновлюватися й рости.',
      ],
      should: [
        "A protein shake is optional: use it only if food alone doesn't get you to your daily target.",
        'Протеїновий коктейль — за бажанням: лише якщо їжею не добираєш денну норму.',
      ],
      where: [
        "Detailed meal tracking is the Nutrition app's job; I cover the training side.",
        'Детальний облік їжі — робота Nutrition; я відповідаю за тренувальну частину.',
      ],
    },
  },

  supplements: {
    ex: [
      'should i take creatine',
      'what supplements should i take',
      'is creatine safe',
      'how much creatine per day',
      'when to take creatine',
      'do i need pre workout',
      'best supplements for muscle',
      'are supplements worth it',
      'does creatine work',
      'creatine before or after workout',
      'is pre-workout necessary',
      'which supplements actually work',
      'should i load creatine',
      'bcaa or creatine',
    ],
    exUk: [
      'чи пити креатин',
      'які добавки приймати',
      'креатин безпечний?',
      'скільки креатину на день',
      'коли пити креатин',
      'треба передтрен?',
      'найкращі добавки для м’язів',
      'чи варті добавки грошей',
      'креатин працює?',
      'креатин до чи після тренування',
      'який спортпит реально працює',
      'бцаа чи креатин',
      'стоит ли пить креатин',
      'какие добавки нужны',
      'шо з добавок брати',
    ],
    facets: {
      what: [
        'Creatine monohydrate is the one supplement with solid evidence for strength and muscle; most others are mostly marketing.',
        'Креатин моногідрат — єдина добавка з міцними доказами для сили й м’язів; більшість інших — здебільшого маркетинг.',
      ],
      howMuch: [
        "3–5 g of creatine monohydrate a day; loading isn't necessary.",
        '3–5 г креатину моногідрату на день; фаза завантаження не обов’язкова.',
      ],
      when: [
        'Any time of day; taking it daily matters more than timing.',
        'Будь-коли протягом дня; важливіше приймати щодня, ніж у певний час.',
      ],
      should: [
        'Creatine is a reasonable choice for most healthy adults; with kidney issues, ask a doctor first.',
        'Креатин — розумний вибір для більшості здорових дорослих; якщо є проблеми з нирками — спершу до лікаря.',
      ],
      who: [
        'Most healthy adults who lift can use it; people with kidney problems should check with a doctor first.',
        'Більшості здорових дорослих, які тренуються, можна; людям із проблемами нирок — спершу порадитись із лікарем.',
      ],
    },
  },

  temper: {
    ex: [
      "you're too harsh",
      'why are you so rude',
      'can you be nicer',
      'be kinder to me',
      "you're being mean",
      'stop being so harsh',
      'can i change your tone',
      'how do i make you nicer',
      'your tone is too rude',
      'can you talk softer',
      "you're so strict",
      'why so harsh with me',
      "i don't like how you talk to me",
      'change your personality',
    ],
    exUk: [
      'ти занадто жорсткий',
      'чому ти такий грубий',
      'можеш бути добрішим',
      'говори м’якше',
      'ти грубо відповідаєш',
      'перестань бути таким злим',
      'як змінити твій тон',
      'як зробити тебе добрішим',
      'ти якийсь злий',
      'можна м’якше?',
      'ти надто суворий',
      'не подобається, як ти зі мною говориш',
      'змінити характер тренера',
      'ты слишком грубый',
      'будь добрее',
    ],
    facets: {
      how: [
        'Open settings with the gear icon, top right, and choose Temper to set how soft or hard I talk.',
        'Відкрий налаштування шестірнею вгорі праворуч і обери «Характер», щоб задати, наскільки м’яко чи жорстко я говорю.',
      ],
      where: ['Gear icon, top right, then Temper.', 'Шестірня вгорі праворуч → «Характер».'],
    },
  },

  who: {
    ex: [
      'who are you',
      'what can you do',
      'what do you do',
      'help',
      'what are you',
      'how can you help me',
      'what can i ask you',
      'what are you for',
      'introduce yourself',
      "what's atlas",
      'what kind of questions do you answer',
      'help me',
      'what are you able to do',
      'tell me about yourself',
    ],
    exUk: [
      'хто ти',
      'що ти вмієш',
      'що ти робиш',
      'допоможи',
      'як ти можеш допомогти',
      'що в тебе можна спитати',
      'для чого ти',
      'представся',
      'що таке atlas',
      'на які питання ти відповідаєш',
      'розкажи про себе',
      'шо ти можеш',
      'що вмієш',
      'кто ты',
      'что ты умеешь',
    ],
    facets: {
      what: [
        'Atlas, a strength coach that reads every set you log and answers from your own data.',
        'Atlas — тренер із силових, який читає кожен твій сет і відповідає на основі твоїх даних.',
      ],
      how: [
        'Ask about what to train today, rest times, the next weight on a lift, your records, recovery, sleep or your programme.',
        'Питай, що тренувати сьогодні, скільки відпочивати, яку вагу далі, про рекорди, відновлення, сон чи програму.',
      ],
    },
  },

  thanks: {
    ex: [
      'thanks',
      'thank you',
      'thx',
      'thanks a lot',
      'thank you so much',
      'thanks man',
      'thanks coach',
      'many thanks',
      'thanks for the help',
      'cheers, thanks',
      'thank you atlas',
      'ty thanks',
      'thanks, that helps',
      'big thanks',
    ],
    exUk: [
      'дякую',
      'дякую тобі',
      'дуже дякую',
      'дяки',
      'дякую, тренере',
      'щиро дякую',
      'дякую за допомогу',
      'дякую, атласе',
      'дякую, допомогло',
      'дякс',
      'спасибі',
      'спасибо',
      'спасибо большое',
      'велике дякую',
    ],
  },

  greeting: {
    ex: [
      'hi',
      'hello',
      'hey',
      'hey atlas',
      'hi there',
      'hello coach',
      'good morning',
      'good evening',
      'yo',
      'hey hey',
      'hiya',
      'morning',
      'hello again',
      'hi atlas',
    ],
    exUk: [
      'привіт',
      'привіт, атласе',
      'вітаю',
      'здоров',
      'здорово',
      'добрий ранок',
      'добрий день',
      'добрий вечір',
      'хай',
      'привіт, тренере',
      'здоровенькі були',
      'привет',
      'привет, атлас',
      'доброго ранку',
    ],
  },

  ack: {
    ex: [
      'ok',
      'okay',
      'got it',
      'fine',
      'sure',
      'ok got it',
      'alright',
      'okay then',
      'understood',
      'sounds good',
      'ok cool',
      'fine by me',
      'right',
      'noted',
    ],
    exUk: [
      'добре',
      'ок',
      'окей',
      'гаразд',
      'зрозумів',
      'ясно',
      'зрозуміла',
      'ок, ясно',
      'домовились',
      'зрозуміло',
      'лади',
      'ну добре',
      'хорошо',
      'понял',
    ],
  },

  muscle_last: {
    ex: [
      'when did i last train chest',
      'when was my last back workout',
      'last time i hit legs',
      'when did i train shoulders',
      'when did i last work biceps',
      'how long since i trained quads',
      'when was chest last trained',
      'last time i did hamstrings',
      'when did i hit glutes',
      'how many days since my last leg day',
      'when did i last train calves',
      'when was the last time triceps got worked',
      'when did i train lats',
      'last abs session',
    ],
    exUk: [
      'коли я востаннє тренував груди',
      'коли було останнє тренування спини',
      'коли я качав ноги',
      'коли я тренував плечі',
      'коли востаннє робив біцепс',
      'скільки днів тому я тренував квадрицепс',
      'коли були груди',
      'коли я робив задню поверхню',
      'коли тренував сідниці',
      'скільки днів від останнього дня ніг',
      'коли востаннє качав ікри',
      'коли був трицепс',
      'коли я тренував широчайші',
      'когда я последний раз качал грудь',
      'коли в мене були ноги',
    ],
    facets: {
      how: [
        'I find the latest finished workout where that muscle got working sets and show how many days ago it was and how many sets it got.',
        'Я шукаю останнє завершене тренування, де цей м’яз отримав робочі сети, і показую, скільки днів тому це було й скільки сетів.',
      ],
      where: [
        "Ask me here with the muscle name; your history shows each session's muscles too.",
        'Спитай мене тут, назвавши м’яз; в історії теж видно м’язи кожного тренування.',
      ],
    },
  },

  lift_last: {
    ex: [
      'when did i last do deadlifts',
      'when did i last bench',
      'last time i did squats',
      'when did i do overhead press',
      'when was my last deadlift session',
      'how long since i did pull-ups',
      'when did i last do rows',
      'last time i did leg press',
      'when have i done lunges',
      'when did i last do romanian deadlifts',
      'how many days since i benched',
      'when did i last do hip thrusts',
      'when was the last time i did dips',
      'last squat session',
    ],
    exUk: [
      'коли я востаннє робив станову',
      'коли я востаннє жав лежачи',
      'коли я робив присід',
      'коли робив жим стоячи',
      'коли була остання станова',
      'скільки днів тому я підтягувався',
      'коли я робив тягу в нахилі',
      'коли востаннє робив жим ногами',
      'коли я робив випади',
      'коли була румунська тяга',
      'скільки днів від останнього жиму',
      'коли я робив ягодичний міст',
      'коли востаннє були бруси',
      'когда я последний раз делал становую',
      'коли в мене був присід',
    ],
    facets: {
      how: [
        'I find the latest finished workout with that lift and show how long ago it was and the top set.',
        'Я шукаю останнє завершене тренування з цією вправою й показую, як давно це було та найкращий сет.',
      ],
      where: [
        'Ask me with the lift name, or open the exercise in your history for every session.',
        'Спитай, назвавши вправу, або відкрий її в історії, щоб побачити всі тренування.',
      ],
    },
  },

  lift_count: {
    ex: [
      'how often do i bench',
      'how many times have i done squats',
      'how often do i deadlift',
      'how many sessions with overhead press',
      'how frequently do i do pull-ups',
      'how many times did i bench this month',
      'how often do i do rows',
      'how many times have i squatted in total',
      'how regularly do i do leg press',
      'how often am i doing romanian deadlifts',
      'how many times have i done dips',
      'how often do i do lunges',
      'count of bench sessions',
      'how many deadlift sessions in the last month',
    ],
    exUk: [
      'як часто я жму лежачи',
      'скільки разів я робив присід',
      'як часто я роблю станову',
      'скільки тренувань із жимом стоячи',
      'як часто я підтягуюсь',
      'скільки разів я жав цього місяця',
      'як часто роблю тягу в нахилі',
      'скільки разів я присідав загалом',
      'як часто роблю жим ногами',
      'як часто в мене румунська тяга',
      'скільки разів робив бруси',
      'як часто я роблю випади',
      'скільки тренувань зі становою за місяць',
      'как часто я делаю жим',
      'скока разів я робив станову',
    ],
    facets: {
      how: [
        'I count finished workouts that include the lift: in total and in the last 4 weeks.',
        'Я рахую завершені тренування з цією вправою: загалом і за останні 4 тижні.',
      ],
      howMuch: [
        'For a main lift, 1–3 sessions a week is typical; twice a week is a good default for practice and progress.',
        'Для основної вправи типово 1–3 рази на тиждень; двічі на тиждень — хороший варіант для навички й прогресу.',
      ],
    },
  },

  e1rm: {
    ex: [
      "what's my estimated 1rm on bench",
      'my one rep max on squat',
      'estimate my deadlift max',
      "what's my e1rm for overhead press",
      'calculate my 1rm on bench',
      'what could i lift for one rep on squat',
      'estimated max on deadlift',
      'how much could i bench for a single',
      'one rep max for rows',
      'what is my calculated max on squat',
      '1rm estimate for pull-ups',
      "what's my theoretical max on bench",
      'how is the 1rm estimated',
      'should i test my 1rm on squat',
    ],
    exUk: [
      'який мій розрахунковий максимум на жимі',
      'мій одноповторний максимум у присіді',
      'порахуй мій максимум на становій',
      'розрахунковий 1пм на жимі стоячи',
      'скільки я пожму на раз',
      'скільки присяду на раз',
      'який разовий максимум на становій',
      'мій 1пм на жимі',
      'одноповторний максимум на тязі',
      'розрахунковий максимум у присіді',
      'як рахується 1пм',
      'чи перевіряти максимум на раз',
      'скіко я витисну на раз',
      'мой разовый максимум в жиме',
      'сколько я выжму на раз',
    ],
    facets: {
      what: [
        'An estimated 1RM is the weight you could likely lift for a single rep, calculated from a heavier set of several reps.',
        'Розрахунковий 1ПМ — вага, яку ти, ймовірно, піднімеш на один раз, обчислена з важкого сету на кілька повторів.',
      ],
      how: [
        'I use the Epley formula, weight × (1 + reps / 30), on your working sets of up to 12 reps from the last 12 sessions and take the highest.',
        'Я використовую формулу Епплі: вага × (1 + повтори / 30) для робочих сетів до 12 повторів з останніх 12 тренувань і беру найбільше.',
      ],
      should: [
        "It's an estimate; don't test a true max without a spotter or safety pins.",
        'Це оцінка; справжній максимум не перевіряй без страхувальника чи страхових упорів.',
      ],
      why: [
        'It lets you compare strength across different rep counts without the risk of maxing out.',
        'Він дозволяє порівнювати силу за різної кількості повторів без ризику тестувати максимум.',
      ],
    },
  },

  tonnage: {
    ex: [
      'how much weight did i lift this week',
      'total tonnage',
      'how many kg did i move this month',
      'total weight lifted',
      "what's my tonnage this week",
      'how much have i lifted in total',
      'how many tons did i lift',
      'total kg lifted in 4 weeks',
      'how much did i move last week',
      'weekly tonnage',
      'how much volume load in kg',
      'sum of all the weight i lifted',
      'how many kilos have i lifted lately',
      'what does tonnage mean',
    ],
    exUk: [
      'скільки ваги я підняв цього тижня',
      'загальний тоннаж',
      'скільки кг я підняв за місяць',
      'загальна піднята вага',
      'який тоннаж за тиждень',
      'скільки я підняв загалом',
      'скільки тонн я підняв',
      'скільки кг піднято за 4 тижні',
      'скільки кіло я підняв за останній тиждень',
      'тоннаж за тиждень',
      'що таке тоннаж',
      'скільки всього я перетягав кілограмів',
      'скока тонн я підняв',
      'сколько я поднял за неделю',
      'какой у меня тоннаж',
    ],
    facets: {
      what: [
        'Tonnage is the total weight moved: weight × reps summed over all working sets.',
        'Тоннаж — загальна піднята вага: вага × повтори, сумовані за всіма робочими сетами.',
      ],
      how: [
        'I add up weight × reps for every non-warm-up set over the last 7 days and the last 4 weeks.',
        'Я сумую вагу × повтори для всіх нерозминкових сетів за останні 7 днів і 4 тижні.',
      ],
      should: [
        'Tonnage is a rough workload number; for growth, weekly hard sets per muscle are a better guide.',
        'Тоннаж — груба міра навантаження; для росту краще орієнтуватися на робочі сети на м’яз за тиждень.',
      ],
    },
  },

  muscle_frequency: {
    ex: [
      'how often do i train chest',
      'how many times a week do i hit back',
      'how often should i train legs',
      'how frequently do i work shoulders',
      'how often do i train biceps',
      'is once a week enough for chest',
      'how often do i hit glutes',
      'how many times a week should i train each muscle',
      'how regularly do i train quads',
      'how often do i do hamstrings',
      'frequency for back training',
      'am i training chest often enough',
      'how often should i train arms',
      'how often do my calves get trained',
    ],
    exUk: [
      'як часто я треную груди',
      'скільки разів на тиждень я роблю спину',
      'як часто тренувати ноги',
      'як часто я тренував плечі',
      'як часто треную біцепс',
      'раз на тиждень на груди — достатньо?',
      'як часто я качаю сідниці',
      'скільки разів на тиждень тренувати м’яз',
      'як часто роблю квадрицепс',
      'як часто тренувати спину',
      'чи достатньо часто я треную груди',
      'як часто тренувати руки',
      'як часто в мене ікри',
      'как часто качать грудь',
      'скільки раз на тиждень качати ноги',
    ],
    facets: {
      howMuch: [
        'Twice a week per muscle is the sweet spot for growth for most people.',
        'Двічі на тиждень на м’яз — оптимум для росту для більшості людей.',
      ],
      how: [
        'I count sessions in the last 4 weeks where the muscle got at least one working set and divide by 4.',
        'Я рахую тренування за останні 4 тижні, де м’яз отримав хоча б один робочий сет, і ділю на 4.',
      ],
      why: [
        "Splitting a muscle's weekly sets over two sessions keeps each set higher quality than cramming them into one.",
        'Розподіл тижневих сетів на м’яз на два тренування робить кожен сет якіснішим, ніж усі в один день.',
      ],
    },
  },

  days_per_week: {
    ex: [
      'how many times a week should i train',
      'how often do i go to the gym per week',
      'how many days per week should i work out',
      'how many workouts per week do i average',
      'is 3 days a week enough',
      'should i train 5 days a week',
      'how often should i lift per week',
      'how many sessions a week is ideal',
      'can i train every day',
      'how many gym days a week',
      'is training twice a week enough',
      'how often do i work out weekly',
      "what's my average sessions per week",
      '4 or 5 workouts per week',
    ],
    exUk: [
      'скільки разів на тиждень тренуватись',
      'як часто я ходжу в зал на тиждень',
      'скільки днів на тиждень тренуватись',
      'скільки в середньому тренувань на тиждень',
      '3 рази на тиждень достатньо?',
      'тренуватись 5 днів на тиждень?',
      'як часто тренуватись в тиждень',
      'яка ідеальна кількість тренувань на тиждень',
      'можна тренуватись щодня?',
      'скільки днів у залі на тиждень',
      'двічі на тиждень вистачає?',
      'скільки в мене трєнь на тиждень',
      '4 чи 5 тренувань на тиждень',
      'сколько раз в неделю тренироваться',
      'сколько тренировок в неделю',
    ],
    facets: {
      howMuch: [
        '3–4 sessions a week is plenty for almost everyone; consistency beats extra days.',
        '3–4 тренування на тиждень вистачає майже всім; регулярність важливіша за додаткові дні.',
      ],
      how: [
        'I average your finished sessions over the last 4 weeks and compare with the number of days in your plan.',
        'Я рахую середнє завершених тренувань за останні 4 тижні й порівнюю з кількістю днів у плані.',
      ],
      should: [
        'Pick the number you can keep week after week; more days only help if you recover from them.',
        'Обирай стільки, скільки зможеш тримати тиждень за тижнем; більше днів допомагає, лише якщо від них відновлюєшся.',
      ],
    },
  },

  how_am_i_doing: {
    ex: [
      'how am i doing',
      'rate my training',
      'give me feedback',
      'review my progress',
      'how am i doing overall',
      'assess my training',
      'am i doing well',
      'what do you think of my training',
      "how's my training going overall",
      'give me an honest review',
      'evaluate my last month',
      'am i on the right track',
      'overall feedback on my workouts',
      'how am i progressing in general',
    ],
    exUk: [
      'як я тренуюсь',
      'оціни мої тренування',
      'дай відгук',
      'оціни мій прогрес',
      'як я загалом',
      'чи добре я тренуюсь',
      'що скажеш про мої тренування',
      'дай чесну оцінку',
      'оцінка за останній місяць',
      'чи я на правильному шляху',
      'як справи в мене з тренуваннями',
      'шо скажеш про мене',
      'як я прогресую загалом',
      'оцени мои тренировки',
      'как я тренируюсь',
    ],
    facets: {
      how: [
        'I compare your sessions in the last 4 weeks with the 4 weeks before, count new records, and list lifts that are stuck.',
        'Я порівнюю кількість тренувань за останні 4 тижні з попередніми 4, рахую нові рекорди й називаю вправи, що застрягли.',
      ],
      what: [
        "A lift counts as stuck when its top-set weight hasn't changed over the last 3 sessions.",
        'Вправа вважається застряглою, коли вага найкращого сету не змінилася за останні 3 тренування.',
      ],
      should: [
        "More sessions and new records mean you're on track; stuck lifts are the ones to work on next.",
        'Більше тренувань і нові рекорди — ти на правильному шляху; застряглі вправи — це те, над чим працювати далі.',
      ],
    },
  },

  prs_today: {
    ex: [
      'did i set any records today',
      'any prs today',
      'new records this session',
      'did i hit a pr today',
      'records today?',
      'what prs did i get today',
      'did i beat any records today',
      "today's personal records",
      'any new personal bests today',
      "did today's workout have a pr",
      'was that a pr today',
      'prs in this session',
      'what records did i break today',
      'any pr on bench today',
    ],
    exUk: [
      'чи були сьогодні рекорди',
      'є рекорди сьогодні?',
      'нові рекорди на тренуванні',
      'я поставив рекорд сьогодні?',
      'які рекорди сьогодні',
      'побив сьогодні якийсь рекорд?',
      'сьогоднішні рекорди',
      'були нові рекорди на тренуванні',
      'це був рекорд сьогодні?',
      'рекорди за сьогодні',
      'шо по рекордах сьогодні',
      'сьогодні є рекорд на жимі?',
      'що я сьогодні побив',
      'были рекорды сегодня?',
      'рекорды на тренировке сегодня',
    ],
    facets: {
      how: [
        "A record today means a lift's top-set weight beat every earlier session of that lift.",
        'Рекорд сьогодні — це коли вага найкращого сету у вправі перевищила всі попередні тренування з нею.',
      ],
      what: [
        'Only weight records on the top set count, and a lift needs earlier history to set one.',
        'Рахуються лише рекорди ваги в найкращому сеті, і для рекорду у вправи має бути попередня історія.',
      ],
      where: [
        'Ask me after you finish the session; records show up once the workout is saved.',
        'Спитай мене після завершення тренування; рекорди з’являються, коли тренування збережено.',
      ],
    },
  },

  plateau: {
    ex: [
      "i've hit a plateau",
      'how do i break a plateau',
      "i'm stuck and not progressing",
      'no progress for weeks',
      'my lifts have stalled',
      'why am i not progressing',
      "i'm plateauing, what do i do",
      'strength stalled',
      'which lifts are stuck',
      "i'm not getting stronger anymore",
      'plateau in the gym',
      'how to get past a strength plateau',
      'stalled for a month',
      'nothing is going up anymore',
    ],
    exUk: [
      'у мене плато',
      'як пробити плато',
      'я застряг і не прогресую',
      'нема прогресу кілька тижнів',
      'ваги не ростуть',
      'чому немає прогресу',
      'стою на місці, що робити',
      'сила не росте',
      'які вправи застрягли',
      'більше не стаю сильнішим',
      'як вийти з плато',
      'місяць стою на місці',
      'нічого не росте',
      'у меня плато',
      'как пробить плато',
    ],
    facets: {
      how: [
        "In this order: sleep 7+ hours, take full rest between sets, add one rep before adding weight; if it still won't move, drop 10% and build back over 3 weeks.",
        'У такому порядку: сон 7+ годин, повний відпочинок між сетами, спершу +1 повтор, потім вага; якщо не йде — скинь 10% і набирай 3 тижні.',
      ],
      why: [
        'Plateaus usually come from poor recovery, short rest or adding weight faster than you add reps.',
        'Плато зазвичай виникає через погане відновлення, короткий відпочинок чи додавання ваги швидше, ніж ростуть повтори.',
      ],
      what: [
        "A lift counts as stuck when its top-set weight hasn't changed over the last 3 sessions.",
        'Вправа вважається застряглою, коли вага найкращого сету не змінилася за останні 3 тренування.',
      ],
      howMuch: [
        'Drop about 10% and build back up over roughly 3 weeks.',
        'Скинь приблизно 10% і набирай назад приблизно 3 тижні.',
      ],
    },
  },
};
