export const KB_A2: Record<string, { ex: string[]; exUk: string[] }> = {
  pain: {
    ex: [
      'my lower back is killing me after deadlifts',
      'knee clicks and hurts on lunges',
      'shoulder feels wrong when i bench',
      'something went ouch in my back mid set',
      'hurt my wrist on front squats',
      'elbow pain',
      'hip is aching on leg day, keep going?',
      'pinched something in my upper back',
      'rotator cuff hurts on overhead press',
      'my lower back tightened up on rows and now it hurts to bend',
      'can i still lift with a bad shoulder',
      'tweaked my neck',
      'groin hurts after sumo deadlift',
      'my knees ache every time i go below parallel',
      'chest feels strained after heavy dips',
      'it hurts',
      'should i push through this pain in my shoulder',
      'back pain',
      'felt something pull in my calf on the leg press',
      'my ribs hurt when i brace',
      'front of my shoulder aches on incline press',
      'hurt myself at the gym today',
      'my forearm hurts when i grip the bar',
      'pain behind my knee after squats',
      'i strained my lower back, can i train legs',
    ],
    exUk: [
      'поперек болить після станової',
      'коліно клацає й болить на випадах',
      'щось не так із плечем на жимі',
      'щось стрельнуло в спині посеред підходу',
      'болить зап’ястя після фронтального присіду',
      'біль у лікті',
      'ниє стегно в день ніг, продовжувати?',
      'защемило між лопатками',
      'болить плече, коли жму штангу стоячи',
      'прихопило поперек на тязі, нахилитися боляче',
      'з хворим плечем можна тягати залізо?',
      'шию потягнув',
      'пах болить після сумо',
      'коліна ниють, коли сідаю нижче паралелі',
      'грудак потягнув на брусах',
      'болить',
      'терпіти біль у плечі чи ні',
      'спина болить',
      'щось смикнуло в литці на жимі ногами',
      'передня дельта ниє на похилому жимі',
      'передпліччя болить, коли тримаю гриф',
      'потягнул спину, можно ли качать ноги',
      'болит плечо при жиме',
      'ноет колено после приседаний',
      'что-то хрустнуло в спине и болит',
    ],
  },

  rest: {
    ex: [
      'how long between sets on heavy squats',
      'break between sets',
      'rest between sets',
      'i only rest 45 seconds, is that too short',
      'can i shorten the rest between curl sets',
      'gassed after a set of squats, how long do i wait before the next one',
      'how long should i chill between bench sets',
      '3 minutes between sets feels like forever',
      'pause between working sets for hypertrophy',
      "what's the ideal gap between sets of deadlifts",
      'do i rest less on arm exercises',
      'how much recovery time between sets for strength',
      'is 5 minutes between heavy sets overkill',
      'rest intervals',
      'how long between sets of lateral raises',
      'should i wait until i catch my breath before the next set',
      'minutes between sets',
      'is 30 seconds between sets too little',
      'why do strength guys rest so long between sets',
      'rest between sets on leg press',
      'when do i start my next set',
      'how long do i sit between sets of pull-ups',
      'between sets how long',
      'i rush my sets, how long should i rest',
      'longer rest or shorter rest for muscle growth',
    ],
    exUk: [
      'скільки чекати між сетами присіду',
      'перерва між підходами',
      'відпочинок між сетами',
      'відпочиваю 45 секунд, не замало?',
      'можна скоротити паузу між підходами на біцепс',
      'після сету присідань задихаюсь, скільки чекати до наступного',
      'скільки сидіти між сетами жиму',
      '3 хвилини між підходами — це вічність',
      'пауза між робочими підходами на масу',
      'який проміжок між сетами на становій',
      'на руки можна менше відпочивати між підходами?',
      'скільки перепочивати між сетами на силу',
      '5 хвилин між важкими підходами — не забагато?',
      'інтервали відпочинку між сетами',
      'скільки перерва між підходами на махи в сторони',
      'чекати, поки віддишусь, перед наступним підходом?',
      'хвилини між сетами',
      '30 секунд між підходами мало?',
      'коли починати наступний підхід',
      'скільки відпочивати між підходами підтягувань',
      'між сетами скільки',
      'довше чи коротше відпочивати між підходами для росту',
      'сколько ждать между подходами на жиме',
      'отдых между сетами на становой',
      'перерыв между подходами сколько минут',
    ],
  },

  next_weight: {
    ex: [
      'bench weight for today',
      'what number do i load for squats',
      'how heavy on rdl this session',
      "what's my working weight for incline press today",
      'deadlift, what do i pull today',
      'what should i hit on ohp next workout',
      'squat kg?',
      'tell me the weight for barbell rows',
      'which dumbbells for shoulder press today',
      'what am i benching today',
      'is it time to bump my squat up',
      'what do i put on the leg press sled today',
      'load for hip thrust next time',
      'next workout squat target weight',
      'what weight do i go for on lat pulldown',
      'do i stay at 80 on bench or go heavier',
      "what's the plan weight for my deadlift top set",
      'weighted pull-ups, how much weight today',
      'bench 60 felt easy, what next time',
      'how much do i squat next session',
      'romanian deadlift working weight next session',
      'what weight for dips today',
      'kg for curls today',
      'weight for front squats',
      'what should i load on the bar for bench this time',
    ],
    exUk: [
      'яка вага на жим сьогодні',
      'скільки вішати на присід',
      'яку вагу брати на румунку сьогодні',
      'з якою вагою робити жим на похилій сьогодні',
      'станова — скільки тягнути сьогодні',
      'що ставити на жим стоячи наступного тренування',
      'присід, скільки кіло?',
      'підкажи вагу на тягу штанги',
      'які гантелі брати на жим сидячи',
      'скільки я сьогодні жму',
      'вже можна підняти вагу на присіді?',
      'скільки млинців на жим ногами сьогодні',
      'вага на ягодичний міст наступного разу',
      'цільова вага на присід наступного тренування',
      'яку вагу ставити на тягу верхнього блоку',
      'лишатись на 80 на жимі чи йти важче',
      'з якою вагою робити підтягування з обтяженням сьогодні',
      'жим 60 пішов легко, а що наступного разу',
      'скільки присідати наступного разу',
      'робоча вага на брусах сьогодні',
      'скільки кг на біцепс штангою сьогодні',
      'с каким весом жать сегодня',
      'какой вес на становую в следующий раз',
      'сколько вешать на присед',
      'какой рабочий вес на тягу сегодня',
    ],
  },

  best: {
    ex: [
      'bench pr',
      'my squat pr?',
      "top deadlift i've ever pulled",
      'all my personal bests',
      "what's the record i set on ohp",
      'list my prs',
      'best bench set ever logged',
      'my all time deadlift',
      "what's my record for rdl",
      'personal record on leg press',
      "what's my best on pull-ups",
      'remind me of my squat pr',
      "what's the best number i've put up on bench",
      'record lifts',
      'best row set so far',
      'my hip thrust record',
      'pr list',
      'my top squat set ever',
      "what's my incline bench personal best",
      'records overview',
      'show me my best numbers',
      'deadlift personal record?',
      "most reps i've done on pull-ups",
      'my best dip',
      "what's my current pr on front squat",
    ],
    exUk: [
      'рекорд на жимі',
      'мій пр у присіді',
      'скільки я максимум тягнув на становій',
      'усі мої особисті рекорди',
      'який рекорд я поставив на жимі стоячи',
      'список моїх рекордів',
      'найкращий підхід на жимі за весь час',
      'мій рекорд на румунській тязі',
      'особистий рекорд на жимі ногами',
      'моє найкраще на підтягуваннях',
      'нагадай мій рекорд у присіді',
      'найкращий результат на тязі в нахилі',
      'рекорд на ягодичному мосту',
      'покажи мої найкращі цифри',
      'рекорд на становій?',
      'максимум повторів на підтягуваннях',
      'мій рекорд на брусах',
      'пр на фронтальному присіді',
      'рекорди по вправах',
      'шо в мене за пр на жимі',
      'мій особистий максимум на похилому жимі',
      'мой рекорд в становой',
      'личный рекорд в жиме лёжа',
      'какие у меня пр',
      'лучший результат в приседе',
    ],
  },

  progress_lift: {
    ex: [
      'is bench moving at all',
      'squat trend',
      'deadlift gains lately?',
      'has my ohp gone anywhere in the last month',
      'bench numbers going up or not',
      "how's the squat coming along",
      'did my rdl improve',
      'pull-ups progress',
      'rows trend over the last weeks',
      'how much weight have i added to my bench since march',
      "my deadlift hasn't budged",
      'is leg press progressing',
      'squat chart',
      'hip thrust progress so far',
      'bench feels stuck at 80, is it improving at all',
      'am i gaining on incline press',
      "what's the trend on my overhead press",
      'is my squat going in the right direction',
      'curl progress',
      'has my front squat gone up since i started',
      'deadlift percent change',
      "how's bench doing",
      'dips progression',
      'my bench went backwards?',
      'has lat pulldown improved',
    ],
    exUk: [
      'жим взагалі рухається?',
      'тенденція по присіду',
      'є прирости на становій останнім часом?',
      'жим стоячи хоч трохи виріс за місяць',
      'цифри на жимі ростуть чи ні',
      'як там мій присід',
      'румунська тяга покращилась?',
      'прогрес на підтягуваннях',
      'динаміка тяги в нахилі за останні тижні',
      'скільки я додав на жимі з березня',
      'станова ні з місця',
      'жим ногами прогресує?',
      'графік присіду',
      'як просувається ягодичний міст',
      'жим застиг на 80, є хоч якийсь рух',
      'чи росте похилий жим',
      'присідання йдуть у правильному напрямку?',
      'прогрес на біцепсі зі штангою',
      'фронтальний присід виріс відколи почав?',
      'станова: на скільки відсотків зросла',
      'как там мой жим',
      'растет ли становая',
      'динамика в жиме стоя',
      'прогресс на подтягиваниях',
      'жим пошёл назад?',
    ],
  },

  volume_muscle: {
    ex: [
      'chest sets',
      'how much back work did i do this week',
      'am i overdoing quads',
      'weekly volume for delts',
      'hard sets on hamstrings so far this week',
      'is 12 sets a week enough for biceps',
      'triceps sets per week',
      'how many working sets have my glutes had in 7 days',
      'lats getting enough volume?',
      'calf sets this week',
      'how much weekly volume for traps',
      'i did like 25 sets of chest this week, too much?',
      'abs volume per week',
      'rear delt volume',
      'am i hitting enough sets on legs this week',
      'volume check for arms',
      'how many sets should forearms get weekly',
      "what's the productive set range for chest",
      'quad volume, is it enough',
      'weekly set count for shoulders',
      'how many sets did my back get in the past week',
      'too little volume for hamstrings?',
      'side delts sets per week',
      'is my chest volume too low',
      'glute sets',
    ],
    exUk: [
      'сети на груди',
      'скільки роботи на спину цього тижня',
      'чи не перебираю з квадрицепсом',
      'тижневий обсяг на дельти',
      'робочі сети на біцепс стегна за цей тиждень',
      '12 сетів на тиждень на біцепс вистачить?',
      'підходи на трицепс за тиждень',
      'скільки робочих сетів на сідниці за 7 днів',
      'широчайшим вистачає обсягу?',
      'сети на литки цього тижня',
      'скільки підходів на трапецію на тиждень',
      'зробив десь 25 сетів на груди за тиждень, забагато?',
      'обсяг на прес на тиждень',
      'сети на задню дельту',
      'чи вистачає підходів на ноги цього тижня',
      'скільки сетів на передпліччя тижнево',
      'робочий діапазон сетів на груди',
      'обсягу на квадрицепс достатньо?',
      'скільки сетів мали плечі за тиждень',
      'замало підходів на задню поверхню?',
      'скока підходів на руки за тиждень',
      'сколько сетов на спину за неделю',
      'объем на бицепс нормальный?',
      'сколько подходов на ноги в неделю',
      'недельный объем на трицепс',
    ],
  },

  weak: {
    ex: [
      "what's behind",
      'lagging muscles',
      'which body part am i ignoring',
      'imbalances in my training?',
      'what muscle group needs attention',
      'am i skipping something',
      'where am i weakest',
      'which muscle am i shortchanging',
      'i feel like something is undertrained',
      'what should i prioritise',
      'is anything getting left out',
      'weak spots',
      'what am i slacking on',
      'my program feels lopsided',
      'which muscles are underworked',
      'what needs catching up',
      'what have i been neglecting lately',
      'are my upper and lower body balanced',
      "what's getting the fewest sets",
      'find my weak links',
      'am i missing a body part',
      'which muscles are falling behind',
      'do i skip anything important',
      'what muscle should i bring up',
      "where's the imbalance",
    ],
    exUk: [
      'що відстає',
      'відстаючі м’язи',
      'яку частину тіла я ігнорую',
      'є перекоси в тренуваннях?',
      'якій групі м’язів треба приділити увагу',
      'я щось пропускаю?',
      'де я найслабший',
      'який м’яз я обділяю',
      'здається, щось недотреноване',
      'що мені пріоритезувати',
      'щось випадає з тренувань?',
      'слабкі місця',
      'на що я забиваю',
      'програма якась однобока',
      'які м’язи недопрацьовані',
      'що треба підтягнути',
      'що я закинув останнім часом',
      'верх і низ збалансовані?',
      'що отримує найменше сетів',
      'які м’язи відстають від решти',
      'шо в мене просіло',
      'какие мышцы я забросил',
      'что у меня отстает',
      'есть ли перекос',
      'слабые места',
    ],
  },

  recovery: {
    ex: [
      'am i good to go',
      'legs feel like jelly still from monday',
      'is my back fresh',
      'readiness',
      'muscle readiness percentages',
      'which body parts are fully recovered',
      'chest still beat up from bench?',
      'can my shoulders handle another session yet',
      'are my hamstrings recovered from rdls',
      'how fresh am i',
      "what's recovered",
      '48 hours since legs, are they ready',
      'my quads are still toast',
      'is it safe to hit back again already',
      'recovered?',
      'how long do my legs need to recover',
      'how recovered is my body right now',
      'are biceps ready to go again',
      'my glutes still feel smashed from yesterday',
      'chest ready yet',
      'which muscles are still fried',
      'legs still wrecked from squats',
      'is my upper body fresh enough to train',
      'muscle recovery status',
      "what's fully recovered",
    ],
    exUk: [
      'я готовий?',
      'ноги досі ватні після понеділка',
      'спина свіжа?',
      'готовність',
      'відсотки готовності м’язів',
      'які частини тіла повністю відновились',
      'груди ще не відійшли від жиму?',
      'плечі вже витримають нове тренування?',
      'задня поверхня відновилась після румунки?',
      'наскільки я свіжий',
      'що вже відновилось',
      'минуло 48 годин після ніг, вони готові?',
      'квадрицепс досі вбитий',
      'вже можна знову на спину?',
      'відновився?',
      'скільки ногам треба на відновлення',
      'біцепс готовий знову',
      'сідниці ще забиті після вчора',
      'які м’язи ще вбиті',
      'ноги досі не відійшли після присідань',
      'верх тіла відновився?',
      'ноги как вата',
      'грудь уже восстановилась?',
      'какие мышцы готовы',
      'спина отошла после становой?',
    ],
  },

  today: {
    ex: [
      'today?',
      "what's on the menu today",
      'what are we hitting today',
      'push, pull or legs today',
      "just got to the gym, what's the plan",
      "what's today's session look like",
      "today's workout",
      'which day of my split is today',
      'what am i training this morning',
      "tonight's workout?",
      'do i train today or rest',
      'chest or back today',
      'what exercises today',
      'set me up for today',
      'about to head to the gym, what should i hit',
      "in the locker room, what's the workout",
      "what's the program say for today",
      'which muscle group today',
      'what are we doing right now',
      'any workout planned for today',
      "today's training",
      'what should i lift this evening',
      "what's the lineup today",
      'gym today, what do i do',
      'what day is it in my plan today',
    ],
    exUk: [
      'сьогодні що?',
      'що в меню сьогодні',
      'що качаємо сьогодні',
      'жим, тяга чи ноги сьогодні',
      'щойно прийшов у зал, який план',
      'як виглядає сьогоднішнє тренування',
      'тренування на сьогодні',
      'який сьогодні день спліта',
      'що треную зранку сьогодні',
      'що на вечір по тренуванню',
      'сьогодні треную чи відпочиваю',
      'груди чи спина сьогодні',
      'які вправи сьогодні',
      'збираюсь у зал, що робити',
      'я в роздягальні, яке тренування',
      'що каже програма на сьогодні',
      'яку групу м’язів сьогодні',
      'що зараз робимо',
      'сьогодні є тренування?',
      'що тягати ввечері',
      'шо на сьогодні',
      'что сегодня делаем',
      'какая тренировка сегодня',
      'я в зале, что делать',
      'что по плану на сегодня',
    ],
  },

  tomorrow: {
    ex: [
      'tomorrow?',
      "what's the session tomorrow",
      'tomorrow gym or rest',
      'planning tomorrow, what do i train',
      'what am i hitting tomorrow morning',
      "tomorrow's lineup",
      'will tomorrow be legs',
      'is there a workout scheduled tomorrow',
      'tomorrow push or pull',
      'what exercises tomorrow',
      'do i need to go in tomorrow',
      "what's the program for tomorrow",
      'gym tomorrow?',
      'is tomorrow a gym day',
      "what should i prep for tomorrow's workout",
      'tomorrow evening training, what muscles',
      'tomorrow chest?',
      "what's planned for tomorrow",
      "tomorrow's training",
      "heading in tomorrow, what's on",
      'what does tomorrow look like',
      'which day of the split is tomorrow',
      'lifting or resting tomorrow',
      'do i have legs tomorrow',
      'what will i train tomorrow',
    ],
    exUk: [
      'а завтра?',
      'яке заняття завтра',
      'завтра зал чи відпочинок',
      'плануюсь на завтра, що тренувати',
      'що качаю завтра зранку',
      'завтрашнє тренування',
      'завтра будуть ноги?',
      'на завтра є тренування?',
      'завтра жим чи тяга',
      'які вправи завтра',
      'мені завтра йти в зал?',
      'що в програмі на завтра',
      'в зал завтра?',
      'завтра тренувальний день?',
      'що завтра ввечері тренуємо',
      'завтра груди?',
      'що заплановано на завтра',
      'як виглядає завтра',
      'завтра тренуюсь чи відпочиваю',
      'у мене завтра ноги?',
      'шо на завтра',
      'что завтра по плану',
      'завтра в зал?',
      'какие мышцы завтра',
      'что я тренирую завтра',
    ],
  },

  next_session: {
    ex: [
      "when's the next one",
      'next gym day',
      'when am i back in the gym',
      'upcoming workout',
      "when's my next lift",
      'next training?',
      'how many days until my next workout',
      "what's coming up next",
      'when do i go again',
      "what's my next day in the plan",
      "when's my next push day",
      'when do i train back next',
      'next scheduled session',
      "when's the following workout",
      "after today, when's the next training",
      'when do i hit the gym again this week',
      "what's the next workout called",
      'next session?',
      'when is my next upper day',
      "when's my next chance to train",
      'next workout day',
      "what's up next in the program",
      "when's the next time i lift",
      'how soon is my next session',
      "when's my next scheduled training day",
    ],
    exUk: [
      'коли наступне',
      'наступний день у залі',
      'коли я знову в залі',
      'найближче тренування',
      'наступне заняття коли',
      'через скільки днів наступне тренування',
      'що далі на черзі',
      'коли знову йти',
      'який наступний день у плані',
      'коли наступний день жиму',
      'коли наступного разу спина',
      'наступне заплановане тренування',
      'після сьогодні коли наступне',
      'коли ще раз у зал цього тижня',
      'як називається наступне тренування',
      'наступна сесія?',
      'коли наступний верх',
      'наступний тренувальний день',
      'шо далі по програмі',
      'коли там наступна тренька',
      'коли зможу знову потренуватись за планом',
      'когда я снова в зале',
      'когда следующий день ног',
      'что дальше по программе',
      'через сколько дней следующая тренировка',
    ],
  },

  last_session: {
    ex: [
      'last workout?',
      'what did i hit last time',
      'how did my last session go',
      'previous workout details',
      "what was yesterday's session",
      'my most recent workout',
      'show the last one',
      'which lifts did i do last session',
      'how many sets last time',
      'last session duration',
      'remind me what i did at my last gym visit',
      'latest workout',
      'what was the last thing i trained',
      "yesterday's workout",
      'last training recap',
      'what was in my previous session',
      'what muscles did i hit last workout',
      'the last workout i logged',
      'what exercises were in my last session',
      'how long did i train last time',
      'when did i last go to the gym',
      'what did i lift yesterday',
      'last time at the gym, what did i do',
      'previous session breakdown',
      'what went down at the gym yesterday',
    ],
    exUk: [
      'останнє тренування?',
      'що я робив минулого разу',
      'як пройшло останнє заняття',
      'деталі попереднього тренування',
      'яке було вчорашнє тренування',
      'моє найсвіжіше тренування',
      'покажи останнє',
      'які вправи були минулого разу',
      'скільки сетів було минулого разу',
      'скільки тривало минуле тренування',
      'нагадай, що я робив у залі минулого разу',
      'що я тренував останнім',
      'вчорашнє тренування',
      'що було на попередньому занятті',
      'які м’язи я качав на минулому тренуванні',
      'останнє записане тренування',
      'скільки часу я тренувався минулого разу',
      'коли я останній раз був у залі',
      'що я тягав учора',
      'розбір минулого тренування',
      'шо було вчора в залі',
      'что я делал вчера в зале',
      'покажи последнюю тренировку',
      'какие упражнения были в прошлый раз',
      'как прошла прошлая тренировка',
    ],
  },

  week: {
    ex: [
      'week?',
      'this week so far',
      "how's my week looking",
      'sessions this week',
      'did i hit my weekly target',
      'weekly report',
      'sum up my week',
      'how many times have i been to the gym since monday',
      'total sets this week',
      'past 7 days overview',
      'was this a good week',
      'how productive was my week',
      'what did this week look like',
      'training count for the week',
      'am i behind this week',
      'how many workouts in the past 7 days',
      'week in review',
      'did i miss any sessions this week',
      'weekly numbers',
      "how's the week going training-wise",
      'number of gym visits this week',
      'quick look at my week',
      'did i train enough days this week',
      'last 7 days',
      "this week's workouts",
    ],
    exUk: [
      'тиждень?',
      'цей тиждень поки що',
      'як виглядає мій тиждень',
      'тренування цього тижня',
      'я виконав план на тиждень?',
      'звіт за тиждень',
      'підсумуй мій тиждень',
      'скільки разів я був у залі з понеділка',
      'всього сетів цього тижня',
      'огляд за останні 7 днів',
      'гарний був тиждень?',
      'наскільки продуктивний був тиждень',
      'скільки тренувань набралось за тиждень',
      'я відстаю цього тижня?',
      'огляд тижня',
      'я пропустив тренування цього тижня?',
      'цифри за тиждень',
      'як іде тиждень по тренуваннях',
      'скільки разів ходив у зал цього тижня',
      'глянь мій тиждень',
      'останні 7 днів',
      'шо я натренував за тиждень',
      'как прошла неделя',
      'сколько раз я был в зале на неделе',
      'статистика за неделю',
    ],
  },

  streak: {
    ex: [
      'streak?',
      'days in a row',
      "how long's my run",
      'streak status',
      'is my streak intact',
      'did yesterday break the chain',
      'how many days straight now',
      'my current run of days',
      'still going strong on the streak?',
      'streak number',
      'how many consecutive days',
      'did i lose my streak',
      "what's my current chain",
      'days without breaking the streak',
      'is the streak still on',
      'how far is my streak now',
      'check my streak',
      'consecutive days count',
      'streak today',
      'what streak am i on',
      'have i kept my streak',
      'is my run still alive',
      'streak length',
      'how many days am i at',
      "don't tell me i lost my streak",
    ],
    exUk: [
      'серія?',
      'днів поспіль',
      'яка довжина серії',
      'статус серії',
      'серія ціла?',
      'вчора не обірвав серію?',
      'скільки днів без перерви зараз',
      'моя поточна серія днів',
      'я ще тримаю серію?',
      'число серії',
      'скільки днів підряд уже',
      'я втратив серію?',
      'перевір мою серію',
      'серія ще триває?',
      'скільки днів у серії',
      'яка в мене зараз серія',
      'я зберіг серію?',
      'стрік живий?',
      'який у мене стрік',
      'тільки не кажи, що я втратив серію',
      'скільки там днів поспіль',
      'моя серия',
      'серия не прервалась?',
      'сколько дней в серии',
      'стрик живой?',
    ],
  },

  total: {
    ex: [
      'total workouts',
      'how many sessions have i ever done',
      'lifetime workouts',
      'workouts logged so far',
      'how many times have i been to the gym since joining',
      'overall session count',
      'how many trainings total in my log',
      'number of workouts since day one',
      'all-time sessions',
      'how many workouts have i completed',
      'since i started using the app, how many sessions',
      'how many gym trips in total',
      'grand total of workouts',
      'how many workouts in my history',
      'total number of sessions ever',
      'my workout count',
      'how many have i done so far',
      'cumulative workouts',
      'how many sessions altogether',
      'total trainings?',
      'how many workouts all together',
      'how many times have i lifted in total',
      'session tally',
      'how many workouts since my first one',
      'workouts completed overall',
    ],
    exUk: [
      'всього тренувань',
      'скільки тренувань я взагалі зробив',
      'тренувань за весь час',
      'скільки записано тренувань на цей момент',
      'скільки разів я був у залі відколи почав',
      'загальна кількість сесій',
      'скільки тренувань у журналі',
      'кількість тренувань з першого дня',
      'скільки тренувань я завершив',
      'скільки занять відколи користуюсь додатком',
      'скільки походів у зал загалом',
      'загальний підсумок тренувань',
      'скільки тренувань в історії',
      'мій лічильник тренувань',
      'сумарно тренувань',
      'скільки занять набралось загалом',
      'усього трєнь?',
      'скільки разів я тягав залізо загалом',
      'скільки тренувань із самого першого',
      'загалом завершених тренувань',
      'скільки всього занять за весь час',
      'сколько тренировок я сделал',
      'общее количество тренировок',
      'сколько раз я был в зале всего',
      'всего занятий',
    ],
  },

  sleep: {
    ex: [
      'sleep?',
      "last night's sleep",
      'how many hours did i get',
      'my sleep average this week',
      'barely slept',
      'slept like 4 hours',
      "how's my sleep been",
      'is my sleep enough for gains',
      'sleep and muscle growth',
      'got 6 hours, is that ok for training',
      'weekly sleep',
      "what's my average hours of sleep",
      "i've been sleeping short lately",
      'do gains happen while sleeping',
      'how important is sleep for recovery',
      'up late last night, only 5 hours',
      'sleep hours last night?',
      'is 7 hours of sleep the minimum',
      'poor sleep this week',
      'did i get enough sleep',
      'sleep data',
      'slept terribly',
      'are 8 hours of sleep needed',
      'how much should a lifter sleep',
      'short on sleep',
    ],
    exUk: [
      'сон?',
      'сон минулої ночі',
      'скільки годин я поспав',
      'мій середній сон за тиждень',
      'майже не спав',
      'спав години чотири',
      'як у мене зі сном',
      'сну вистачає для росту?',
      'сон і ріст м’язів',
      'поспав 6 годин, нормально для тренування?',
      'сон за тиждень',
      'скільки годин я в середньому сплю',
      'останнім часом мало сплю',
      'м’язи ростуть уві сні?',
      'наскільки сон важливий для відновлення',
      'ліг пізно, спав 5 годин',
      '7 годин сну — мінімум?',
      'поганий сон цього тижня',
      'я виспався?',
      'дані сну',
      'жахливо спав',
      'скільки має спати той, хто тренується',
      'недосипаю',
      'сколько часов я спал',
      'плохо спал',
    ],
  },

  deload: {
    ex: [
      'deload?',
      'light week coming up?',
      'when do i get an easy week',
      'i feel beat up, time to back off for a week',
      'is next week lighter',
      'deload frequency',
      'how does a deload week work',
      'what weights on deload',
      'do beginners need deloads',
      'joints feel cooked, deload?',
      'how many sets on a deload week',
      'should i deload every 4 weeks',
      'is this week the light one',
      'back-off week',
      "when's my recovery week",
      'can i skip the deload',
      "what's the point of a deload",
      'week off the heavy stuff?',
      'deload now or push another week',
      'how long is a deload',
      'do i keep the same weights when deloading',
      'light week',
      'unload week',
      'deloading',
      'how light should the deload be',
    ],
    exUk: [
      'розвантаження?',
      'скоро легкий тиждень?',
      'коли в мене полегшений тиждень',
      'почуваюся побитим, час на тиждень скинути',
      'наступний тиждень легший?',
      'як часто розвантажуватись',
      'як влаштований розвантажувальний тиждень',
      'які ваги на розвантаженні',
      'новачкам потрібне розвантаження?',
      'суглоби вже не тягнуть, розвантажуватись?',
      'скільки сетів на розвантажувальному тижні',
      'розвантажуватись кожні 4 тижні?',
      'цей тиждень полегшений?',
      'можна пропустити розвантаження',
      'який сенс розвантаження',
      'розвантажитись зараз чи ще тиждень потиснути',
      'скільки триває розвантаження',
      'на розвантаженні ваги ті самі?',
      'легкий тиждень',
      'дилоад',
      'наскільки легшим має бути розвантаження',
      'разгрузка',
      'когда легкая неделя',
      'как делать разгрузочную неделю',
      'пора на разгрузку?',
    ],
  },

  plan: {
    ex: [
      'program?',
      "what's my routine",
      'show the programme',
      'my current split',
      'build me a routine',
      'i need a program',
      "what's the schedule this week",
      'what days am i supposed to lift',
      "how's my program set up",
      'generate a training plan',
      'what week of the block am i in',
      'my plan',
      "where's my programme",
      'can you set up a routine for me',
      'weekly layout of my training',
      "what's my split set up as",
      'lay out my training week',
      'what does my program include',
      'i have no plan, make one',
      'how many days is my programme',
      'view my workout plan',
      'design a program for me',
      "what's my programme look like",
      'plan my training',
      'my routine for the week',
    ],
    exUk: [
      'програма?',
      'яка в мене програма',
      'покажи програму тренувань',
      'мій поточний спліт',
      'склади мені програму',
      'мені потрібна програма',
      'який розклад на цей тиждень',
      'в які дні мені тягати залізо',
      'як побудована моя програма',
      'згенеруй план тренувань',
      'на якому я тижні блоку',
      'мій план',
      'де моя програма',
      'налаштуй мені програму',
      'розклад тренувань на тиждень',
      'розпиши мені тиждень тренувань',
      'що входить у мою програму',
      'в мене нема плану, зроби',
      'скільки днів у моїй програмі',
      'розроби мені програму',
      'шо в мене за програма',
      'какая у меня программа',
      'мой сплит',
      'сделай мне план тренировок',
      'какое расписание тренировок',
    ],
  },

  skip: {
    ex: [
      'skip?',
      'can i bail on the gym today',
      'is it fine to miss one workout',
      'thinking of skipping tonight',
      'will skipping today hurt my progress',
      'can i ditch leg day',
      "i'm going to skip today, is that ok",
      'no gym today, is that bad',
      'one missed session, big deal?',
      'skip or go',
      'can i skip training because of work',
      'i might not make it to the gym today',
      "is it ok if i don't train today",
      "missed yesterday's workout, is that bad",
      'can i skip today and just go tomorrow',
      'skip the gym after a 4 hour night?',
      "i'm going to blow off the gym",
      'pass on training today?',
      'is skipping a session a problem',
      "can i drop today's workout",
      'is it bad to skip two sessions in a row',
      'not going today',
      'skipping legs again, is that fine',
      "i'll give the gym a miss today",
      "okay to miss this week's leg day",
    ],
    exUk: [
      'пропустити?',
      'можна сьогодні забити на зал',
      'нічого, якщо пропущу одне тренування',
      'думаю пропустити сьогодні ввечері',
      'пропуск сьогодні зашкодить прогресу?',
      'можна злитись з дня ніг',
      'я сьогодні пропущу, нормально?',
      'сьогодні без залу, це погано?',
      'одне пропущене тренування — це страшно?',
      'пропускати чи йти',
      'можна пропустити тренування через роботу',
      'мабуть, не встигну сьогодні в зал',
      'нормально, якщо сьогодні не треную?',
      'пропустив учорашнє тренування, це погано?',
      'пропущу сьогодні, піду завтра',
      'пропустити зал після 4 годин сну?',
      'сьогодні забиваю на зал',
      'пропустити два тренування підряд — погано?',
      'сьогодні не йду',
      'знов пропускаю ноги, це ок?',
      'можна скіпнути тренування?',
      'можно сегодня не идти в зал',
      'пропущу тренировку, ничего страшного?',
      'скипну сегодня зал',
      'пропуск одной тренировки это плохо?',
    ],
  },

  motivation: {
    ex: [
      "can't be bothered today",
      'no drive to lift lately',
      'i hate going to the gym lately',
      'lost my motivation',
      'how do i find the will to train',
      'i keep making excuses not to go',
      'gym feels like a chore now',
      'no desire to work out',
      "i've lost the passion for lifting",
      'how do i stop procrastinating on workouts',
      'lazy',
      "i don't feel like lifting",
      'i want to quit the gym',
      'motivation is at zero',
      'i just want to stay on the couch',
      "why can't i get myself to go",
      'i dread going to the gym',
      'not in the mood to train',
      'how to get the drive back',
      'i keep putting off my workout',
      'lifting feels pointless right now',
      "meh, don't wanna train",
      'how do i force myself to train',
      'feel like giving up on training',
      'zero will to go today',
    ],
    exUk: [
      'сьогодні взагалі не хочеться',
      'нема драйву тягати залізо останнім часом',
      'не хочу йти в зал',
      'втратив мотивацію',
      'де взяти бажання тренуватись',
      'раз у раз шукаю відмовки, щоб не йти',
      'зал став як обов’язок',
      'нема бажання тренуватись',
      'пропав запал до залу',
      'як перестати відкладати тренування',
      'лінь',
      'не хочеться тягати',
      'хочу кинути зал',
      'мотивація на нулі',
      'хочу просто лежати на дивані',
      'не можу себе заставити піти',
      'з жахом думаю про зал',
      'як повернути бажання тренуватись',
      'відкладаю тренування весь час',
      'ліньки',
      'неохота в зал',
      'лень идти в зал',
      'пропала мотивация',
      'не могу себя заставить тренироваться',
      'вообще не хочется в зал',
    ],
  },

  warmup: {
    ex: [
      'warm-up?',
      'how do i get warm before lifting',
      'what to do before the first set',
      'is 5 minutes on the bike a good warm-up',
      'do i really need to warm up',
      'best way to warm up for leg day',
      'warming up tips',
      'how long should i warm up for',
      'can i just go straight to heavy weights',
      'routine before lifting to get loose',
      "what's a proper warm-up",
      'warm up before training in a cold gym',
      'why bother warming up',
      'skip warm-up?',
      'what should my warm-up include',
      'how to prepare my body before lifting',
      'warm up for upper body day',
      'general warm up ideas',
      'do i warm up with cardio or light weights',
      'is jumping rope a good warm-up',
      'prep before lifting, what do i do',
      'how much warm-up before heavy lifting',
      'can i start lifting cold',
      'what to do at the start of a session',
      'quick warm-up routine',
    ],
    exUk: [
      'розминка?',
      'як розігрітись перед силовим',
      'що робити перед першим сетом',
      '5 хвилин на велосипеді — нормальна розминка?',
      'мені справді треба розминатись?',
      'як найкраще розім’ятись перед ногами',
      'поради щодо розминки',
      'скільки часу розминатись',
      'можна одразу братись за важкі ваги',
      'що має входити в розминку',
      'навіщо взагалі розминатись',
      'пропустити розминку?',
      'як підготувати тіло перед тренуванням',
      'розминка перед верхом',
      'розминатись кардіо чи легкими вагами',
      'скакалка як розминка підійде?',
      'можна починати без розігріву',
      'що робити на початку тренування',
      'швидка розминка',
      'розминка в холодному залі',
      'шо по розминці',
      'як розігріти суглоби перед залом',
      'нужна ли разминка',
      'как разогреться перед тренировкой',
      'сколько минут разминаться',
    ],
  },

  cooldown: {
    ex: [
      'cool down?',
      'what should i do right after lifting',
      'is walking after the workout useful',
      'post-workout stretching',
      'end of session routine',
      'do i need a cooldown',
      'stretch after leg day?',
      'how do i finish a workout',
      'what to do once lifting is over',
      'should i walk it off on the treadmill after',
      'cool-down worth it?',
      'stretches for after the gym',
      'how long to stretch after training',
      'best way to wind down after a heavy session',
      'cooldown after deadlifts',
      'heart rate still high after my workout, cooldown?',
      "where's the cool-down button",
      'how to begin the cool-down block',
      'is cooling down a waste of time',
      'light cardio after lifting to cool down',
      'stretch at the end of the workout or skip it',
      'after workout stretching routine',
      'cooling down',
      'what to do after the last set',
      'do cool-downs actually do anything',
    ],
    exUk: [
      'заминка?',
      'що робити одразу після тренування',
      'пройтись після тренування корисно?',
      'розтяжка після тренування',
      'як завершувати тренування',
      'мені потрібна заминка?',
      'розтягуватись після дня ніг?',
      'що робити, коли вже все відтягав',
      'походити на доріжці наприкінці?',
      'заминка варта того?',
      'розтяжки після залу',
      'скільки розтягуватись після тренування',
      'як правильно охолонути після важкого тренування',
      'заминка після станової',
      'пульс ще високий після тренування, заминка?',
      'де кнопка заминки',
      'заминка — це марна трата часу?',
      'легке кардіо після силового як заминка',
      'розтягуватись наприкінці чи ні',
      'шо робити після останнього сету',
      'заминка щось дає?',
      'заминка после тренировки',
      'как правильно делать заминку',
      'растягиваться после зала?',
      'что делать после тренировки',
    ],
  },

  cardio: {
    ex: [
      'cardio?',
      'how much cardio a week',
      'should i hit the bike after lifting',
      'stairmaster after weights ok?',
      'cardio first or lifting first',
      'should i add cardio to my routine',
      'is the rowing machine good cardio for lifters',
      'elliptical on off days',
      'how long on the treadmill after my workout',
      'do i need cardio if i lift',
      'cardio days',
      'can i do cardio on non-lifting days',
      'incline walking after the gym',
      'how many cardio sessions per week',
      'cardio before legs, bad idea?',
      'is cycling ok on leg day',
      'what kind of cardio should i do',
      'easy cardio for heart health',
      'cardio machines after lifting',
      'conditioning work, how much',
      '20 minutes cardio after lifting enough?',
      'do lifters need cardio',
      'when should i fit cardio in',
      'is walking on the treadmill enough cardio',
      'cardio on upper body day',
    ],
    exUk: [
      'кардіо?',
      'скільки кардіо на тиждень',
      'покрутити велик після силового?',
      'степер після залу нормально?',
      'спершу кардіо чи залізо',
      'чи додати кардіо в програму',
      'гребний тренажер як кардіо підійде?',
      'орбітрек у дні без силових',
      'скільки ходити на доріжці після тренування',
      'мені треба кардіо, якщо я качаюсь?',
      'ходьба під нахилом після залу',
      'скільки кардіо-тренувань на тиждень',
      'кардіо перед ногами — погана ідея?',
      'велосипед у день ніг — нормально?',
      'яке кардіо робити',
      'кардіо для серця',
      '20 хвилин кардіо після тренування вистачить?',
      'коли вставляти кардіо',
      'кардіо в день верху',
      'шо по кардіо',
      'кардіо між силовими днями можна?',
      'кардио нужно?',
      'сколько минут кардио после зала',
      'кардио перед тренировкой или после',
      'какое кардио делать',
    ],
  },

  reps: {
    ex: [
      'reps?',
      'how many reps for size',
      'rep scheme for building muscle',
      'heavy triples or sets of ten',
      "what's the best rep range",
      'reps to get stronger',
      'should i do high reps for toning',
      '5x5 or 3x10',
      'how many reps on squats',
      'rep count per set for growth',
      'is 15 reps too many',
      'doing sets of 20, is that ok for muscle',
      'low rep strength work, how many',
      'what reps should i aim for on bench',
      'range of reps for my goal',
      'hypertrophy rep range',
      'how many reps is best for arms',
      'high rep endurance, how many',
      'is 3 reps enough to grow',
      'when should i go for more reps',
      'why sets of 6 to 12',
      'reps per set for strength and size',
      'what counts as high reps',
      'how many reps should i be doing on curls',
      'do reps matter for growth',
    ],
    exUk: [
      'повтори?',
      'скільки повторів на масу',
      'схема повторів для набору м’язів',
      'важкі трійки чи десятки',
      'який найкращий діапазон повторів',
      'скільки повторів, щоб стати сильнішим',
      'багато повторів для рельєфу?',
      '5 на 5 чи 3 на 10',
      'скільки повторень на присіді',
      '15 повторів — забагато?',
      'роблю по 20 повторів, це ок для м’язів?',
      'скільки повторів на жимі робити',
      'діапазон повторень на гіпертрофію',
      'скільки повторів найкраще для рук',
      '3 повтори — достатньо для росту?',
      'коли збільшувати кількість повторів',
      'чому саме 6–12 повторів',
      'скільки разів у підході на силу',
      'скільки повторень на біцепс',
      'чи важлива кількість повторів',
      'скока раз робити в сеті',
      'по скільки повторів робити',
      'на сколько повторений делать подход',
      'сколько повторов на силу',
      'какой диапазон повторений лучше',
    ],
  },

  failure: {
    ex: [
      'failure?',
      'do i go all out every set',
      "should i push till i can't do another rep",
      'how many reps in reserve',
      'leave reps in the tank or not',
      'to failure on curls?',
      'is failing a rep bad',
      'grinding to failure on deadlifts, good idea?',
      'should my last set be to failure',
      'going until muscle failure',
      'how hard should my sets be',
      'is it okay to fail on bench',
      'do i need to empty the tank every set',
      'should i hit failure on lateral raises',
      'until failure or stop short',
      'failure training',
      'is failure necessary to build muscle',
      'how close to failure on squats',
      'stop 2 reps short?',
      'too much failure training',
      'can i train to failure every workout',
      'what does training to failure mean',
      'am i supposed to fail',
      'failure on machines vs free weights',
      'go to absolute failure?',
    ],
    exUk: [
      'до відмови?',
      'викладатись на повну кожен сет?',
      'дожимати, поки не зможу ще повтор?',
      'скільки повторів тримати в запасі',
      'лишати повтори в запасі чи ні',
      'до відмови на біцепсі?',
      'не дожати повтор — це погано?',
      'станову до відмови — нормальна ідея?',
      'останній підхід до відмови робити?',
      'до м’язової відмови',
      'наскільки важкими мають бути сети',
      'можна на жимі до відмови',
      'треба вичавлювати себе кожен сет?',
      'махи в сторони до відмови?',
      'до відмови чи зупинитись раніше',
      'тренування до відмови',
      'відмова обов’язкова для росту?',
      'наскільки близько до відмови на присіді',
      'зупинятись за 2 повтори до відмови?',
      'кожне тренування до відмови можна?',
      'що означає до відмови',
      'до отказа на жиме можно?',
      'работать до отказа или нет',
      'сколько повторов оставлять в запасе',
      'отказ нужен для роста?',
    ],
  },

  bodyweight: {
    ex: [
      'weight?',
      'what do i weigh',
      "what's the scale say",
      'latest weigh-in',
      'current weight in the app',
      'what was my body weight last time i logged it',
      'how many kilos am i',
      'bodyweight?',
      'when did i last step on the scale',
      "what's my logged weight",
      'remind me what i weigh',
      'body weight now',
      'what did i weigh in at',
      'do you have my weight',
      'what weight do you have for me',
      'my kg',
      'last recorded body weight',
      'how heavy am i according to you',
      'my weigh-in',
      "what's my body weight at the moment",
      'most recent weight',
      'when was my last weigh-in',
      'how much am i weighing these days',
      'current body mass',
      'weight on the scale',
    ],
    exUk: [
      'вага?',
      'що показують ваги',
      'моє останнє зважування яке',
      'поточна вага в додатку',
      'яку вагу я записував востаннє',
      'скільки в мене кіло',
      'вага тіла?',
      'коли я востаннє ставав на ваги',
      'яка записана вага',
      'нагадай, скільки я важу',
      'вага тіла зараз',
      'скільки я важив на останньому зважуванні',
      'ти знаєш мою вагу?',
      'яку вагу ти маєш про мене',
      'остання записана вага тіла',
      'скільки я важу, по-твоєму',
      'моє зважування',
      'яка в мене вага на даний момент',
      'найсвіжіша вага',
      'коли було останнє зважування',
      'скільки кіло показали ваги востаннє',
      'шо по вазі',
      'какой у меня вес',
      'последнее взвешивание',
      'сколько я сейчас вешу по приложению',
    ],
  },

  session_length: {
    ex: [
      'how long should i be in the gym',
      'workout duration',
      'average time per session',
      'my workouts take ages, is that normal',
      'two hours in the gym too much',
      'how many minutes is a good workout',
      'is 45 minutes enough',
      'how long does my typical session last',
      'ideal gym session length',
      'session length',
      'how long do i usually train',
      'should workouts be under an hour',
      'why are my sessions so long',
      'planned workout time',
      'time spent per workout',
      'is a 30 minute session enough',
      'how long is my average workout lately',
      'how long should leg day take',
      'target session duration in my plan',
      'minutes per workout on average',
      'is a long workout better',
      'how long are my gym sessions',
      'hour and a half training, overkill?',
      'duration of my workouts',
      'how long should a push day last',
    ],
    exUk: [
      'скільки бути в залі',
      'тривалість заняття',
      'середній час на тренування',
      'мої тренування тягнуться вічність, це нормально?',
      'дві години в залі — забагато?',
      'скільки хвилин — гарне тренування',
      '45 хвилин достатньо?',
      'скільки зазвичай триває моє тренування',
      'ідеальна довжина тренування',
      'скільки я зазвичай тренуюсь за часом',
      'тренування має бути менше години?',
      'чому мої тренування такі довгі',
      'запланований час тренування',
      'скільки часу йде на одне тренування',
      '30 хвилин тренування вистачить?',
      'скільки має тривати день ніг',
      'цільова тривалість у плані',
      'хвилин на тренування в середньому',
      'довге тренування краще?',
      'півтори години тренування — перебір?',
      'скока часу я сиджу в залі',
      'шо по тривалості тренувань',
      'сколько длится моя тренировка',
      'два часа в зале это много?',
      'какая длительность тренировки оптимальна',
    ],
  },

  swap: {
    ex: [
      'swap?',
      'how do i change an exercise mid session',
      'squat rack is busy, what now',
      "someone's on the cable machine, can i switch",
      'swap this exercise',
      'can i pick a different exercise for today',
      'how to change a movement in my workout',
      'bench is taken, give me something else',
      "i don't like lunges, swap them out",
      'can i trade leg extensions for something',
      'no dumbbells free, what can i do instead',
      "where's the swap button",
      'replace this one',
      'exercise swap',
      'can the app substitute an exercise for me',
      "gym doesn't have a hack squat, what to do",
      'my gym has no cable station, swap it',
      'change the exercise please',
      'i want a different chest exercise today',
      'can i switch out pull-ups for something easier',
      'how do i replace an exercise in the plan',
      'swap out deadlifts, my gym is packed',
      'lat pulldown occupied',
      'other exercise for the same muscle',
      'can i do something else instead of this',
    ],
    exUk: [
      'заміна?',
      'як поміняти вправу посеред тренування',
      'стійка для присіду зайнята, що тепер',
      'кросовер зайнятий, можна замінити',
      'заміни цю вправу',
      'можна взяти іншу вправу на сьогодні',
      'як змінити вправу в тренуванні',
      'лава зайнята, дай щось інше',
      'не люблю випади, заміни їх',
      'можна розгинання ніг на щось замінити',
      'вільних гантелей нема, що робити',
      'де кнопка заміни',
      'заміни оцю',
      'заміна вправи',
      'в залі нема гак-присіду, що робити',
      'в моєму залі нема блоку, заміни',
      'хочу іншу вправу на груди сьогодні',
      'як замінити вправу в плані',
      'верхній блок зайнятий',
      'інша вправа на той самий м’яз',
      'шо можна зробити натомість',
      'можна поміняти підтягування на щось легше',
      'тренажёр занят, что делать',
      'замени упражнение',
      'как поменять упражнение в тренировке',
    ],
  },

  technique: {
    ex: [
      'form check',
      'how do i set up for bench',
      'what cues for deadlift',
      'am i doing squats right',
      'how to hinge properly',
      'proper way to do lateral raises',
      "what's good form on rows",
      'technique tips',
      'how should my back look when i deadlift',
      'elbows tucked or flared on bench',
      'bar path on overhead press',
      'how to do a hip thrust',
      'i think my form is off',
      'how to perform a proper pull-up',
      'can you show me how to do a lunge',
      'form cues for rdl',
      'how to do a good push-up',
      'is my deadlift form safe',
      'where can i watch technique videos',
      'tips to fix my bench form',
      'how to keep my back straight on rows',
      'exercise demo',
      'how do i do face pulls',
      'learn video for squats',
      'proper form for curls',
    ],
    exUk: [
      'перевірка техніки',
      'як правильно лягти на жим',
      'які підказки для станової',
      'я правильно присідаю?',
      'як правильно робити гіперекстензію',
      'правильні махи в сторони',
      'як правильно тягнути штангу в нахилі',
      'поради по техніці',
      'яка має бути спина на становій',
      'лікті притиснуті чи розведені на жимі',
      'траєкторія грифа на жимі стоячи',
      'як робити ягодичний міст',
      'здається, в мене крива техніка',
      'як правильно виконати підтягування',
      'покажи, як робити випади',
      'підказки для румунської тяги',
      'як правильно віджиматись',
      'моя станова безпечна по техніці?',
      'де глянути відео техніки',
      'як виправити техніку жиму',
      'як тримати спину рівно на тязі',
      'як робити тягу до обличчя',
      'как правильно приседать',
      'техника подтягиваний',
      'как делать румынскую тягу',
    ],
  },

  protein: {
    ex: [
      'protein?',
      'how much protein for gains',
      'grams of protein a day',
      'am i eating enough protein',
      'protein goal for a 70 kg lifter',
      'daily protein target',
      'do i need 2 g per kilo',
      'what foods are high in protein',
      'diet for building muscle',
      'how important is protein for growth',
      'is chicken and rice enough for gains',
      'protein requirement for strength training',
      'can you eat too much protein',
      'how many eggs a day for protein',
      'nutrition basics for lifters',
      "does protein matter if i'm lifting",
      'how do i hit my protein number',
      'best protein sources',
      'is whey necessary',
      'how much protein should a woman who lifts eat',
      'i eat like 60 g of protein, is it enough',
      'eating for muscle',
      'protein per kilo of bodyweight',
      'what should my diet look like for strength',
      'food to grow',
    ],
    exUk: [
      'білок?',
      'скільки протеїну на масу',
      'грамів білка на добу',
      'я їм достатньо білка?',
      'норма білка при вазі 70 кг',
      'денна норма білка',
      'треба 2 г на кіло?',
      'які продукти з високим вмістом білка',
      'харчування для набору м’язів',
      'наскільки білок важливий для росту',
      'курка з рисом — вистачить для росту?',
      'скільки білка для силових',
      'можна переїсти білка?',
      'скільки яєць на день для білка',
      'як добрати свою норму білка',
      'найкращі джерела білка',
      'сироватковий протеїн обов’язковий?',
      'їм десь 60 г білка, це нормально?',
      'як харчуватись, щоб росли м’язи',
      'білок на кіло ваги',
      'шо їсти для сили',
      'сколько протеина в день',
      'сколько белка на кг веса',
      'что есть для роста мышц',
      'хватает ли мне белка',
    ],
  },

  supplements: {
    ex: [
      'supplements?',
      'creatine worth it',
      'which supps should i buy',
      'is creatine bad for you',
      'how many grams of creatine',
      'do i take creatine on rest days',
      'is pre-workout worth it',
      'does creatine cause hair loss',
      "what's actually proven in supplements",
      'should a beginner take creatine',
      'glutamine worth taking',
      'fish oil for lifters',
      'creatine loading phase needed?',
      'do bcaas do anything',
      'multivitamin for the gym',
      'what supplements help strength',
      'creatine monohydrate or hcl',
      'does creatine make you bloated',
      'is creatine safe long term',
      'is ashwagandha worth taking',
      'supplement stack for muscle growth',
      'cheap supplements that work',
      'do i need any supplements',
      'creatine every day?',
      'zma worth it',
    ],
    exUk: [
      'добавки?',
      'креатин вартий?',
      'який спортпит купити',
      'креатин шкідливий?',
      'скільки грамів креатину',
      'креатин у дні відпочинку пити?',
      'передтрен вартий грошей?',
      'від креатину випадає волосся?',
      'що з добавок реально доведено',
      'новачку пити креатин?',
      'глютамін варто брати?',
      'омега-3 для тих, хто тренується',
      'фаза завантаження креатину потрібна?',
      'бца щось дають?',
      'вітаміни для залу',
      'які добавки для сили',
      'креатин моногідрат чи гідрохлорид',
      'від креатину набрякаєш?',
      'креатин безпечний на довгий термін?',
      'мені взагалі потрібні добавки?',
      'креатин щодня?',
      'шо по спортпиту',
      'креатин стоит того?',
      'какой спортпит брать',
      'вредный ли креатин',
    ],
  },

  temper: {
    ex: [
      'tone it down',
      'less harsh please',
      'you sound angry',
      'can you be gentler',
      'stop yelling at me',
      'be more supportive',
      'why are you so mean to me',
      'that was rude',
      "you're too blunt",
      'soften up a bit',
      'can you be more encouraging',
      'switch to a friendlier tone',
      'i want a nicer coach',
      'make atlas less strict',
      'can you be tougher on me',
      'be harder on me',
      'go drill sergeant mode',
      "that attitude isn't helping",
      'less sarcasm please',
      'how do i change the way you talk',
      'can you be more polite',
      'you hurt my feelings',
      'chill with the tone',
      'speak kinder',
      'coach personality settings',
    ],
    exUk: [
      'збав тон',
      'менш жорстко, будь ласка',
      'ти звучиш сердито',
      'можеш бути лагіднішим',
      'не кричи на мене',
      'будь більш підтримуючим',
      'чому ти зі мною такий злий',
      'це було грубо',
      'ти занадто прямолінійний',
      'пом’якшись трохи',
      'говори дружніше',
      'хочу добрішого тренера',
      'зроби атласа менш суворим',
      'можеш бути жорсткішим зі мною',
      'будь суворішим до мене',
      'менше сарказму',
      'як змінити манеру твого спілкування',
      'можна ввічливіше',
      'ти мене образив',
      'полегше з тоном',
      'налаштування характеру тренера',
      'не будь таким грубим',
      'говори мягче',
      'почему ты такой злой',
      'будь строже со мной',
    ],
  },

  who: {
    ex: [
      'what is this',
      'what are you exactly',
      "what's your job",
      'what do you help with',
      "i'm new here, what do you do",
      'atlas?',
      'explain yourself',
      "what's this bot for",
      'so what can you do for me',
      'how does this coach thing work',
      'what are your features',
      'what can you tell me',
      'who am i talking to',
      "what's your purpose",
      'what are your abilities',
      'what kind of coach are you',
      'help pls',
      'i need help',
      "what's this chat",
      'what do you know how to do',
      'how do i use you',
      'what are you good at',
      'can you help',
      'your capabilities',
      "what's your deal",
    ],
    exUk: [
      'що це таке',
      'що ти таке',
      'яка твоя робота',
      'з чим ти допомагаєш',
      'я тут новенький, що ти робиш',
      'атлас?',
      'поясни, хто ти',
      'для чого цей бот',
      'то що ти можеш для мене зробити',
      'як працює цей тренер',
      'які в тебе функції',
      'з ким я говорю',
      'яке твоє призначення',
      'який ти тренер',
      'допоможи, будь ласка',
      'мені потрібна допомога',
      'що це за чат',
      'як тобою користуватись',
      'в чому ти сильний',
      'можеш допомогти',
      'твої можливості',
      'шо ти за бот',
      'что ты такое',
      'чем ты можешь помочь',
      'помоги',
    ],
  },

  thanks: {
    ex: [
      'thanks bro',
      'appreciate it',
      'much appreciated',
      'thanks buddy',
      'cheers',
      'thank u',
      'tysm',
      'thanks again',
      'thanks for that',
      'grateful, thanks',
      'thanks a bunch',
      "thanks, that's useful",
      'ta',
      'thanks dude',
      'appreciate the help',
      "thanks, i'll try that",
      'thank you kindly',
      'nice one, thanks',
      'thx a lot',
      'thanks heaps',
      'cheers mate',
      'thank you for explaining',
      'thanks for the tip',
      'really appreciate it',
      'merci',
    ],
    exUk: [
      'дякую, брате',
      'ціную',
      'дуже вдячний',
      'дякую, друже',
      'дяк',
      'дякую ще раз',
      'дякую за це',
      'вдячна',
      'дякую, корисно',
      'дякую, спробую',
      'красно дякую',
      'о, дякую',
      'дякую за пояснення',
      'дякую за пораду',
      'щиро вдячний',
      'дякую велике',
      'дякі',
      'дякую, виручив',
      'спасибі велике',
      'спс',
      'дякую, зрозуміло',
      'пасиба',
      'благодарю',
      'спасибо, помог',
      'спасибо за совет',
    ],
  },

  greeting: {
    ex: [
      'hey coach',
      'hello there',
      'heya',
      'good afternoon',
      'morning coach',
      'hi hi',
      'yo atlas',
      'howdy',
      'hey there',
      'evening',
      'hello atlas',
      'greetings',
      'hey buddy',
      'hi coach',
      'hey man',
      'hello hello',
      'hi again',
      'yo coach',
      'hey you',
      'good morning atlas',
      'hellooo',
      "hey, i'm back",
      "hi, it's me",
      'afternoon',
      'hola',
    ],
    exUk: [
      'привіт, тренер',
      'вітання',
      'привітик',
      'добридень',
      'доброго вечора',
      'привіт-привіт',
      'здоров, атласе',
      'хей',
      'салют',
      'ку',
      'добрий ранок, тренере',
      'вітаю, атласе',
      'здрастуй',
      'здрастє',
      'привіт ще раз',
      'я знову тут, привіт',
      'доброго дня',
      'хеллоу',
      'здоров був',
      'прівєт',
      'здравствуй',
      'доброе утро',
      'добрый вечер',
      'здорово, тренер',
      'хай, атлас',
    ],
  },

  ack: {
    ex: [
      'k',
      'kk',
      'cool',
      'roger',
      'copy that',
      'makes sense',
      'gotcha',
      'will do',
      'ok sure',
      'yep',
      'alright then',
      'fair enough',
      'all right',
      'understood coach',
      'clear',
      'okie',
      'ok noted',
      'got it coach',
      'that works',
      'yeah ok',
      'perfect',
      'sure thing',
      'i see',
      'ah ok',
      'okay makes sense',
    ],
    exUk: [
      'ок, зрозумів',
      'ясненько',
      'прийняв',
      'добре, зроблю',
      'логічно',
      'зрозуміло, тренере',
      'так, ок',
      'ага',
      'угу',
      'ну ок',
      'все ясно',
      'гаразд, тоді',
      'прийнято',
      'справедливо',
      'окей, ясно',
      'та добре',
      'зрозуміла все',
      'норм',
      'домовилися',
      'ладно',
      'ясно, понял',
      'ок, принял',
      'понятно',
      'харашо',
      'оке',
    ],
  },

  muscle_last: {
    ex: [
      'when did chest last get hit',
      'last back day?',
      'how many days since shoulders',
      'when were my arms last trained',
      'last time i worked traps',
      'when did i last do abs',
      'how long ago did i hit quads',
      'when did my hamstrings last get sets',
      'last delt session',
      'when was the last time i trained back',
      'days since glutes',
      'when did i last train forearms',
      'when did triceps last get work',
      'how long since biceps',
      'when was chest',
      'last time legs got trained',
      'when did i last hit rear delts',
      'calves last trained when',
      'has it been a while since i trained lats',
      'when did i do chest last',
      'how many days has it been since legs',
      'last session with shoulders in it',
      'when did my core last get trained',
      'when was my last arm day',
      'when did i last train upper back',
    ],
    exUk: [
      'коли груди востаннє отримали навантаження',
      'останній день спини?',
      'скільки днів минуло після плечей',
      'коли востаннє тренувались руки',
      'коли я останній раз робив трапецію',
      'коли востаннє качав прес',
      'як давно я робив квадрицепс',
      'коли задня поверхня стегна востаннє мала сети',
      'остання сесія на дельти',
      'днів після сідниць',
      'коли востаннє тренував передпліччя',
      'коли трицепс востаннє працював',
      'скільки часу минуло від біцепса',
      'коли ноги востаннє тренувались',
      'коли я качав задню дельту',
      'ікри востаннє коли',
      'давно я не тренував широчайші?',
      'коли я робив груди останнього разу',
      'скільки днів уже без ніг',
      'коли був останній день рук',
      'коли востаннє тренував верх спини',
      'давно не качав плечі, коли було востаннє',
      'когда я последний раз тренировал спину',
      'когда были плечи',
      'сколько дней прошло после ног',
    ],
  },

  lift_last: {
    ex: [
      'when was my last bench session',
      'last deadlift?',
      'how long ago did i squat',
      'when did i last press overhead',
      'days since my last deadlift',
      'when did i do pull-ups last',
      'last bench day',
      'when was incline press last',
      'how long has it been since i did rdls',
      'when did i last do curls',
      'last time i did lat pulldowns',
      'hip thrusts, when was the last time',
      'when did i last front squat',
      'when was the last barbell row',
      'how many days since squats',
      'when was my last dip session',
      'last time i did bulgarian split squats',
      'leg press last done when',
      'when did i last deadlift heavy',
      "it's been a while since i did overhead press, when was it",
      'when did i last pull deadlifts from the floor',
      'last session with bench press',
      'how long ago were face pulls',
      'walking lunges, when did i last do them',
      'when did i last do leg extensions',
    ],
    exUk: [
      'коли була моя остання сесія жиму',
      'остання станова?',
      'як давно я присідав',
      'коли востаннє жав над головою',
      'скільки днів від останньої станової',
      'коли я останній раз підтягувався',
      'останній день жиму',
      'коли був жим на похилій',
      'як давно була румунська тяга',
      'коли востаннє робив згинання на біцепс',
      'коли я робив тягу верхнього блоку',
      'ягодичний міст — коли було востаннє',
      'коли я востаннє робив фронтальний присід',
      'коли була остання тяга штанги в нахилі',
      'скільки днів після присідань',
      'коли я востаннє віджимався на брусах',
      'коли були болгарські випади',
      'жим ногами коли востаннє',
      'давно не робив жим стоячи, коли це було',
      'останнє тренування з жимом лежачи',
      'коли були тяги до обличчя',
      'коли востаннє робив розгинання ніг',
      'когда я последний раз жал лёжа',
      'когда был последний присед',
      'давно я не делал подтягивания?',
    ],
  },

  lift_count: {
    ex: [
      'bench frequency',
      'how many bench sessions have i logged',
      'how often am i squatting per week',
      'deadlift count',
      'how many times did i deadlift this month',
      'number of sessions with pull-ups',
      'how often do i press overhead',
      'how many workouts had rdls',
      'squat sessions in the last 4 weeks',
      'how often does incline press show up',
      'how many times have i done hip thrusts in total',
      'how regularly do i curl',
      'how many times have i front squatted',
      'lat pulldown frequency',
      'bench times per week',
      'how many sessions include deadlifts',
      'how often have i done dips lately',
      'total number of squat workouts',
      'how often do i do face pulls',
      "times i've done leg press this month",
      'how often do barbell rows come up',
      'how many times a week am i benching',
      'how many bulgarian split squat sessions',
      'how often do i train the deadlift',
      'number of times i did overhead press',
    ],
    exUk: [
      'частота жиму',
      'скільки сесій жиму я записав',
      'як часто я присідаю на тиждень',
      'кількість станових',
      'скільки разів я тягнув станову цього місяця',
      'скільки тренувань із підтягуваннями',
      'як часто я жму над головою',
      'скільки тренувань було з румункою',
      'скільки разів присід за останні 4 тижні',
      'як часто трапляється похилий жим',
      'скільки разів я робив ягодичний міст загалом',
      'як регулярно я роблю біцепс зі штангою',
      'скільки разів я робив фронтальний присід',
      'частота тяги верхнього блоку',
      'скільки разів на тиждень я жму',
      'скільки тренувань мали станову',
      'як часто останнім часом бруси',
      'загальна кількість тренувань з присідом',
      'як часто я роблю тягу до обличчя',
      'скільки разів жим ногами за місяць',
      'як часто в мене тяга в нахилі',
      'скока разів я підтягувався',
      'сколько раз я приседал в этом месяце',
      'как часто я делаю становую',
      'сколько тренировок с жимом стоя',
    ],
  },

  e1rm: {
    ex: [
      '1rm on bench?',
      'estimated max squat',
      'what would my deadlift single be',
      'bench one rep max estimate',
      'e1rm squat',
      "what's my projected max on ohp",
      'could i hit 100 on bench for one',
      'calc my deadlift 1rm from my sets',
      'how much could i squat for a single rep',
      "what's my 1 rep max on rows",
      'theoretical deadlift max',
      'estimated one-rep on incline press',
      "what's my true max on bench likely",
      'max single on front squat',
      'epley estimate for my bench',
      'work out my squat max',
      'what would i hit for a 1rm on rdl',
      'how strong am i on bench for one rep',
      'predicted 1rm for pull-ups',
      'deadlift one-rep estimate',
      'my bench 1rm',
      'guess my squat max',
      'estimated single on overhead press',
      "what's my max for one on hip thrust",
      'do i need to test my deadlift max or can you estimate it',
    ],
    exUk: [
      '1пм на жимі?',
      'прикинь мій максимум у присіді на раз',
      'скільки я витягну станову на раз',
      'оцінка разового максимуму на жимі',
      'е1пм присід',
      'прогнозований максимум на жимі стоячи',
      'пожму 100 на раз?',
      'порахуй мій 1пм у становій з моїх сетів',
      'скільки я присяду на один повтор',
      'мій 1пм у тязі в нахилі',
      'теоретичний максимум на становій',
      'розрахунковий разовий на похилому жимі',
      'максимум на раз у фронтальному присіді',
      'оцінка за епплі на жимі',
      'вирахуй мій максимум у присіді',
      'який 1пм на румунській тязі',
      'розрахунковий 1пм на підтягуваннях',
      'мій одноповторний на жимі',
      'вгадай мій максимум у присіді',
      'скільки підніму на раз на ягодичному мосту',
      'треба тестувати максимум на становій чи ти порахуєш',
      'скока я вижму на раз',
      'расчетный максимум в становой',
      'мой 1пм в приседе',
      'сколько я пожму на один раз',
    ],
  },

  tonnage: {
    ex: [
      'tonnage?',
      'how many kilos did i move this week',
      'total load lifted this month',
      'how much iron did i move',
      'weight times reps total',
      'tons lifted last week',
      'how much total weight in 7 days',
      'my monthly tonnage',
      'how many tonnes this month',
      'total kg moved',
      "what's my workload in kg",
      'tonnage for the last 4 weeks',
      'how much weight have i shifted lately',
      'sum of weight times reps',
      'did my tonnage go up this week',
      'kg lifted this week',
      'total volume in kilos',
      'what does tonnage tell me',
      'how many tons did i push this week',
      'total weight moved last month',
      'tonnage stats',
      'how heavy was my week in total kg',
      'how much did i lift altogether this week',
      'overall kilos lifted',
      'lifetime tonnage',
    ],
    exUk: [
      'тоннаж?',
      'скільки кіло я перетягав цього тижня',
      'загальне навантаження в кг за місяць',
      'скільки заліза я підняв',
      'вага на повтори в сумі',
      'тонн за минулий тиждень',
      'скільки загальної ваги за 7 днів',
      'мій тоннаж за місяць',
      'скільки тонн цього місяця',
      'усього кг піднято',
      'тоннаж за останні 4 тижні',
      'скільки я натягав останнім часом',
      'сума ваги на повтори',
      'тоннаж виріс цього тижня?',
      'кг за тиждень',
      'загальний обсяг у кілограмах',
      'що показує тоннаж',
      'скільки тонн я натягав за тиждень',
      'загальна вага за минулий місяць',
      'статистика тоннажу',
      'скільки кілограмів я підняв разом',
      'скока кіло за тиждень',
      'сколько тонн я поднял',
      'тоннаж за месяц',
      'сколько килограмм я поднял за неделю',
    ],
  },

  muscle_frequency: {
    ex: [
      'chest frequency',
      'how often am i hitting legs',
      'times per week for back',
      'shoulders twice a week or once',
      'how many days a week do my arms get trained',
      'frequency per muscle',
      'should i hit chest twice a week',
      'how often do glutes get worked',
      'how many sessions a week include quads',
      'is training back once a week too little',
      'how often should hamstrings be trained',
      'weekly frequency for delts',
      'can i train biceps every day',
      'how often should calves be hit',
      'am i training legs often enough',
      'how often do i train traps',
      'lats frequency',
      'how many times a week for triceps',
      'should i train each muscle 3 times a week',
      'how often should i train forearms',
      'how often do i hit rear delts',
      'is once a week per muscle enough',
      'legs once a week enough?',
      'chest days per week',
      'back training frequency on average',
    ],
    exUk: [
      'частота на груди',
      'як часто я качаю ноги',
      'скільки разів на тиждень спина',
      'плечі двічі на тиждень чи раз',
      'скільки днів на тиждень тренуються руки',
      'частота на м’яз',
      'качати груди двічі на тиждень?',
      'як часто працюють сідниці',
      'скільки тренувань на тиждень включають квадрицепс',
      'спина раз на тиждень — замало?',
      'як часто тренувати задню поверхню стегна',
      'частота на дельти за тиждень',
      'можна тренувати біцепс щодня?',
      'як часто качати литки',
      'чи достатньо часто я треную ноги',
      'як часто я роблю трапецію',
      'частота на широчайші',
      'скільки разів на тиждень на трицепс',
      'тренувати кожен м’яз 3 рази на тиждень?',
      'як часто качати передпліччя',
      'раз на тиждень на м’яз вистачить?',
      'ноги раз на тиждень — нормально?',
      'как часто я тренирую спину',
      'сколько раз в неделю качать плечи',
      'как часто тренировать ноги',
    ],
  },

  days_per_week: {
    ex: [
      'how many gym days should i do',
      'training frequency per week',
      'is 6 days a week too much',
      'is 4 days a week good',
      'how many days a week am i averaging',
      'workouts per week?',
      "what's a good number of sessions weekly",
      'can i lift 7 days a week',
      '3 or 4 days',
      'do i go to the gym enough times a week',
      'how many training days per week is best',
      'is lifting twice a week worth it',
      'how many times a week do i usually train',
      "what's my weekly session average",
      'how many days a week do most people lift',
      'should i add a fifth day',
      'gym every day ok?',
      "how many days should i lift if i'm busy",
      'every other day training?',
      'weekly training days',
      'how often should i hit the gym',
      "sessions per week i'm doing",
      'is going 5 times a week overkill',
      'optimal gym days per week',
      'is three days a week enough for strength',
    ],
    exUk: [
      'скільки днів ходити в зал',
      'частота тренувань на тиждень',
      '6 днів на тиждень — забагато?',
      '4 дні на тиждень — добре?',
      'скільки днів на тиждень у мене в середньому',
      'тренувань на тиждень?',
      'яка нормальна кількість тренувань на тиждень',
      'можна тягати залізо 7 днів на тиждень?',
      '3 чи 4 дні',
      'я достатньо разів на тиждень ходжу в зал?',
      'скільки тренувальних днів на тиждень найкраще',
      'двічі на тиждень у зал — є сенс?',
      'скільки разів на тиждень я зазвичай тренуюсь',
      'яка моя середня кількість тренувань на тиждень',
      'додати п’ятий день?',
      'в зал кожен день — нормально?',
      'скільки днів тренуватись, якщо зайнятий',
      'через день тренуватись?',
      'оптимальна кількість днів у залі на тиждень',
      '5 разів на тиждень — перебір?',
      'скока раз на тиждень ходити',
      'как часто ходить в зал',
      'сколько дней в неделю качаться',
      'можно каждый день тренироваться?',
      'сколько тренировок в неделю у меня',
    ],
  },

  how_am_i_doing: {
    ex: [
      'how am i getting on',
      'judge my training',
      'report card',
      'am i doing ok',
      'honest opinion on my progress',
      'grade me',
      "what's your verdict on my training",
      'am i improving overall',
      'give me a progress check',
      "how's everything looking",
      'what should i fix in my training overall',
      'review the last month for me',
      'am i heading in the right direction',
      'be honest, am i slacking',
      'how do i look on paper',
      'status check on my training',
      'critique my training',
      "what's your take on my progress",
      'overall assessment',
      'is my training working',
      'big picture, how am i doing',
      'rate my last few weeks',
      'am i on course',
      'feedback please',
      'are things going well with my training',
    ],
    exUk: [
      'як мої успіхи в залі',
      'оціни мене',
      'табель успішності',
      'я нормально тренуюсь?',
      'чесна думка про мій прогрес',
      'постав мені оцінку',
      'твій вердикт по моїх тренуваннях',
      'я загалом покращуюсь?',
      'перевір мій прогрес',
      'що мені виправити в тренуваннях загалом',
      'розбери мій останній місяць',
      'я рухаюсь у правильному напрямку?',
      'чесно, я халтурю?',
      'критикуй мої тренування',
      'твоя думка про мій прогрес',
      'загальна оцінка',
      'мої тренування працюють?',
      'якщо загалом, як я',
      'оціни останні кілька тижнів',
      'відгук, будь ласка',
      'все йде добре?',
      'шо скажеш по моєму прогресу',
      'как у меня дела с тренировками',
      'оцени мой прогресс',
      'я на правильном пути?',
    ],
  },

  prs_today: {
    ex: [
      'pr today?',
      'did i break anything today',
      'new pr this workout?',
      'any records from this session',
      "did today's session have new bests",
      'records set today',
      'was today a pr day',
      'did i beat my squat record today',
      "personal bests from today's workout",
      'did i set a new deadlift record today',
      'what did i pr on today',
      "today's prs",
      'any new maxes today',
      'did i top my best today',
      'session saved, any records',
      'did i hit a new bench pr this session',
      "records in today's workout",
      'new personal records today?',
      'did i get any prs this morning',
      'anything record-breaking today',
      'did i beat my previous best today',
      "did tonight's session have a pr",
      'any lifts hit a record today',
      'which lifts were prs today',
      'did i improve any record today',
    ],
    exUk: [
      'рекорд сьогодні?',
      'я сьогодні щось побив?',
      'новий пр на цьому тренуванні?',
      'рекорди з цього тренування',
      'сьогоднішнє тренування дало нові рекорди?',
      'рекорди, поставлені сьогодні',
      'сьогодні був день рекордів?',
      'я побив рекорд у присіді сьогодні?',
      'особисті рекорди з сьогоднішнього тренування',
      'поставив новий рекорд на становій сьогодні?',
      'на чому я сьогодні поставив рекорд',
      'пр сьогодні',
      'є нові максимуми сьогодні?',
      'перевершив свій рекорд сьогодні?',
      'тренування збережено, є рекорди?',
      'новий рекорд на жимі за це тренування?',
      'рекорди на сьогоднішньому тренуванні',
      'зранку були рекорди?',
      'щось рекордне сьогодні?',
      'в яких вправах сьогодні рекорди',
      'шо я сьогодні побив',
      'сегодня был рекорд?',
      'побил сегодня что-нибудь?',
      'новый рекорд на тренировке?',
      'какие рекорды сегодня',
    ],
  },

  plateau: {
    ex: [
      'stuck',
      'hit a wall',
      "strength isn't going anywhere",
      'no gains for two months',
      "everything's stalled",
      'how to bust through a plateau',
      'what do i do when progress stops',
      "i've been stuck at the same weights forever",
      'my progress flatlined',
      'nothing moves anymore, help',
      'how to break a stall',
      'i keep failing to add weight on anything',
      "weights haven't gone up in weeks",
      'plateaued',
      'stagnating in the gym',
      'how do i get unstuck',
      "i'm spinning my wheels",
      'progress has stopped completely',
      'stuck lifts',
      "what's stalling",
      'how do i restart progress',
      'been at the same numbers since summer',
      'no strength gains lately, why',
      'what causes a plateau',
      "can't progress anymore",
    ],
    exUk: [
      'застряг',
      'вперся в стіну',
      'сила нікуди не йде',
      'два місяці без приросту',
      'все стало',
      'як прорвати плато',
      'що робити, коли прогрес зупинився',
      'вічність на тих самих вагах',
      'прогрес завмер',
      'нічого не рухається, допоможи',
      'як зрушити з мертвої точки',
      'ваги не ростуть уже кілька тижнів',
      'вийшов на плато',
      'стагнація в залі',
      'як вибратись із застою',
      'прогрес повністю зупинився',
      'застряглі вправи',
      'що в мене стоїть на місці',
      'як відновити прогрес',
      'з літа ті самі цифри',
      'через що буває плато',
      'вже не прогресую',
      'застой в зале',
      'вышел на плато',
      'не растут веса, что делать',
    ],
  },
};
