export const KB_C2: Record<string, { ex: string[]; exUk: string[] }> = {
  app_log_set: {
    ex: [
      'just finished 5 reps on squat, how do i save it in the app',
      'where do i put my reps',
      'saving sets',
      'record reps and kg',
      'how does set entry work here',
      'which button saves a completed set',
      'i want to track each set as i go',
      'enter my working set',
      'where do i input what i lifted',
      'how do i log what i just did on bench',
      'tracking sets mid workout',
      "the app isn't saving my set, what do i tap",
      'how to put in 10 reps at 40',
      'set logging',
      'can i type weight and reps for each set',
      'how do i tick off a set',
      'log this set',
      "where's the spot to write reps",
      'how are sets recorded in the session screen',
      'adding reps to an exercise card',
      'i just finished a set of curls, how do i note it',
      'where do i log my lifts during training',
      'entering a set in the tracker',
      'how to save my reps after each set',
      'how do i input sets on the exercise card',
    ],
    exUk: [
      'куди тиснути щоб зберегти сет',
      'як вносити підходи по ходу тренування',
      'де ввести кілограми й повтори',
      'запис підходу',
      'зробила 12 повторів, як це зберегти',
      'як фіксувати кожен сет у додатку',
      'де поле для повторів',
      'як занотувати підхід',
      'як ввести робочий сет',
      'не можу знайти де зберігати підходи',
      'як записувати вагу й повтори на картці вправи',
      'як відмітити виконаний підхід',
      'де тут вносять сети',
      'як тут логати підходи',
      'записати підхід 10 по 50',
      'як додати повтори до вправи',
      'підхід зробив, куди його вписати',
      'як логувати сети в залі',
      'де вписати скільки я підняв',
      'запис сетів у тренуванні',
      'как внести подход',
      'где вводить вес и повторения',
      'як зберігати кожен підхід',
      'шо тиснути після сету',
      'как отметить подход выполненным',
    ],
  },

  app_rest_timer: {
    ex: [
      'rest countdown',
      'make the rest clock longer',
      'change my rest interval to 90 seconds',
      'the rest timer is annoying, can i adjust it',
      'timer alert settings',
      'where do i tweak the rest ring',
      'can i silence the rest beep',
      'set a 3 minute rest in the app',
      'rest timer',
      'how do i shorten the rest period in the timer',
      'phone screen goes dark during rest',
      'rest ring settings',
      "i can't hear the rest alarm",
      'make it buzz when rest is done',
      'how to set a custom rest duration',
      'rest timer sound on',
      'want the timer to ping me',
      'change the countdown between sets',
      'the timer ends too early',
      'how do i edit rest time for squats in the timer',
      'rest alarm',
      'does the timer vibrate',
      'how do i preview the timer alert',
      'can i keep the display awake while resting',
      'i want 2 and a half minutes on the timer',
    ],
    exUk: [
      'як налаштувати відлік відпочинку',
      'таймер між підходами',
      'зроби таймер на 90 секунд',
      'як поміняти тривалість паузи в таймері',
      'де налаштовується коло відпочинку',
      'таймер не вібрує',
      'хочу щоб таймер пікав',
      'постав відпочинок 3 хвилини',
      'таймер відпочинку',
      'екран тухне поки йде таймер',
      'як вимкнути вібрацію таймера',
      'не чую сигналу відпочинку',
      'як збільшити час на таймері',
      'як скоротити паузу в таймері',
      'звук таймера',
      'таймер закінчується зарано',
      'як протестувати сигнал',
      'будильник між підходами',
      'таймер відпочинку налаштування звуку',
      'шоб телефон вібрував коли пауза закінчилась',
      'как поменять время отдыха в таймере',
      'таймер не вибрирует',
      'поставь таймер на две минуты',
      'де міняти таймер',
      'таймер не пікає',
    ],
  },

  app_notifications: {
    ex: [
      'push notifications',
      "why isn't the app notifying me",
      'i never get any alerts',
      'notifications are off, how to fix',
      'allow the app to notify me',
      'how to get pushes on ios',
      'does spotter do push',
      'no pings from the app',
      'iphone push setup',
      'i want reminders to pop up on my phone',
      'notification permission',
      'the app never sends me anything',
      'how to enable alerts on android',
      'can i get push without installing',
      'how do i turn on app notifications on my phone',
      "notifications don't show up",
      'safari push not working',
      'why do i need to add it to the home screen',
      'no alerts on my lock screen',
      'pushes stopped coming',
      'set up notifications',
      'i blocked notifications by mistake',
      'how to receive notifications from atlas',
      'enable notifications for the web app',
      'does the app send push alerts',
    ],
    exUk: [
      'пуші',
      'чому мені нічого не приходить',
      'як дозволити пуш-сповіщення',
      'не бачу сповіщень на екрані блокування',
      'сповіщення вимкнені, як увімкнути',
      'як налаштувати пуші на айфоні',
      'сповіщення не працюють',
      'додаток не надсилає пушів',
      'випадково заборонила сповіщення',
      'як отримувати пуші на андроїд',
      'чи будуть сповіщення без встановлення',
      'навіщо додавати на головний екран для пушів',
      'нотифікації',
      'перестали приходити сповіщення',
      'як ввімкнути нотифікації в браузері',
      'хочу отримувати нагадування на телефон',
      'дозвіл на сповіщення',
      'нема жодних нотифікацій',
      'як налаштувати сповіщення',
      'як зробити щоб приходили пуші',
      'как включить пуши',
      'уведомления не работают',
      'не приходят пуши на андроид',
      'шо робити щоб були нотифікації',
      'айфон не показує сповіщення від спотера',
    ],
  },

  app_turn_off: {
    ex: [
      'disable atlas',
      'turn off the coach feature',
      'remove the ai from my app',
      'i just want a plain tracker without atlas',
      'how can i shut atlas down',
      'hide atlas',
      'switch the assistant off',
      "i'd rather not have a coach in the app",
      'can i turn off the chatbot completely',
      'deactivate the ai coach',
      "where's the option to disable atlas",
      'how to kill the coach',
      "don't need atlas anymore, how to turn it off",
      'shut off the ai',
      'how do i remove the bot from the strip',
      'turn off ai coaching',
      'option to disable atlas',
      'no coach please, just logging',
      'can i disable you in settings',
      'turning atlas off',
      'how to stop using atlas',
      'remove the assistant',
      'i want to switch the coach off',
      'disable coaching',
      'where do i switch you off',
    ],
    exUk: [
      'вимкнути атлас',
      'як відключити ші',
      'хочу просто трекер без тренера',
      'прибрати бота з додатку',
      'де відключається атлас',
      'як деактивувати тренера',
      'атлас мені не потрібен, як вимкнути',
      'як сховати атласа',
      'можна повністю вимкнути асистента',
      'вимкнути ші тренера',
      'де вимикається бот',
      'як прибрати тренера з додатку',
      'відключити атлас в налаштуваннях',
      'не хочу бота в додатку',
      'як вимкнути коуча',
      'без атласа можна користуватися',
      'де кнопка вимкнути атлас',
      'атлас заважає, як його прибрати',
      'як відключити штучного тренера',
      'вимкни себе',
      'как выключить атлас',
      'как убрать бота',
      'отключить ии тренера',
      'шо зробити щоб вимкнути бота',
      'як деактивувати атлас',
    ],
  },

  app_role: {
    ex: [
      'main coach or extra coach',
      'i already follow a program from my trainer',
      'can you just give feedback without changing my plan',
      'my pt programs for me, can you only comment',
      'set you as my primary coach',
      'i want you to take over programming',
      'extra coach mode',
      'switch to main coach mode',
      'what does extra coach mean',
      "i train with a coach irl, what's your job then",
      "can i keep my trainer's plan and still use atlas",
      'be my assistant coach',
      'you as a second coach',
      'i want atlas to build my plan from now on',
      'can you just observe my training',
      'difference between the coach modes',
      'coach role settings',
      'do you write the plan or just watch',
      'i have an online coach already',
      'make you a supporting coach',
      'stop writing my program, my coach does it',
      'who writes my programme, you or me',
      'should i set you to main or extra',
      'support coach instead of main',
      "i'd like you only as a backup coach",
    ],
    exUk: [
      'основний чи додатковий тренер',
      'в мене вже є програма від тренера',
      'можеш лише коментувати не міняючи план',
      'зробити тебе головним тренером',
      'хочу щоб ти вів мою програму',
      'режим додаткового тренера',
      'що означає додатковий тренер',
      'тренуюсь з живим тренером, а ти навіщо',
      'можна лишити план тренера і юзати атлас',
      'будь моїм помічником тренера',
      'атлас як другий тренер',
      'хочу щоб атлас складав мені план',
      'просто спостерігай за моїми тренуваннями',
      'яка різниця між режимами тренера',
      'перемкнути на основного тренера',
      'ти пишеш план чи тільки дивишся',
      'в мене онлайн тренер',
      'не пиши мені програму, її веде тренер',
      'роль атласа',
      'поставити тебе додатковим',
      'хто пише програму, ти чи мій тренер',
      'можешь быть вторым тренером',
      'хочу чтобы ты составлял программу',
      'у меня есть тренер, а ты кто тогда',
      'шо краще, основний чи додатковий',
    ],
  },

  app_injury_log: {
    ex: [
      'log injury',
      'how do i flag an injured area',
      'i tweaked my elbow, where do i enter that',
      'add a hurt body part',
      'injury settings',
      "where's the injury menu",
      'note a sprained ankle in the app',
      'register my lower back injury',
      'how do i mark my hamstring as hurt',
      'put my shoulder injury in the profile',
      'i pulled something, how do i add it to the app',
      'adding an injury',
      'how do i report an injury to the app',
      'save my knee problem so the plan adjusts',
      'where do i list injuries',
      'mark injured muscle',
      'can i record a strain in the profile',
      'how to input my neck injury',
      'injury entry',
      'i have tennis elbow, how do i put it in',
      'how do i select the hurt area',
      'profile injury section',
      'flag my wrist in the app',
      'how do i tell spotter my hip is hurt',
      'record a new injury',
    ],
    exUk: [
      'внести травму',
      'як позначити травмовану зону',
      'потягнув лікоть, де це вказати',
      'додати пошкоджену частину тіла',
      'де меню травм',
      'як записати розтягнення',
      'як вказати травму поперека в профілі',
      'як відмітити задню поверхню стегна травмованою',
      'щось потягнув, як додати в додаток',
      'як зареєструвати травму',
      'запиши травму коліна щоб план змінився',
      'де список травм',
      'позначити травмований м’яз',
      'як ввести травму шиї',
      'тенісний лікоть, як внести',
      'як вибрати травмовану ділянку',
      'розділ травм у профілі',
      'позначити зап’ястя як травмоване',
      'як сказати додатку що болить стегно',
      'нова травма, куди записати',
      'как отметить травму',
      'куда вписать травму колена',
      'где раздел с травмами',
      'як в профіль додати травму плеча',
      'шо натиснути щоб додати травму',
    ],
  },

  are_you_ai: {
    ex: [
      'are you a machine',
      'is this automated',
      'are you human',
      'real person or chatbot',
      'are you an actual human coach',
      'is this ai',
      'am i chatting with a program',
      "you're a bot right",
      'is atlas a person',
      'are you a computer',
      'is a real trainer answering me',
      'are these replies automatic',
      'you a robot',
      'is there a human on the other side',
      'are you an llm',
      'are you software',
      'be honest, are you ai',
      'are you a chatbot',
      'is anyone real here',
      'are you conscious',
      'do you have feelings or are you a program',
      "you're not a real person, are you",
      'automated coach?',
      'who is replying, a human or an ai',
      'are you powered by ai',
    ],
    exUk: [
      'ти робот',
      'це автоматично відповідає',
      'ти жива людина',
      'ти чатбот',
      'ти справжній тренер чи програма',
      'це ші',
      'я переписуюсь з програмою',
      'ти ж бот, так',
      'атлас це людина',
      'ти комп’ютер',
      'мені відповідає справжній тренер',
      'відповіді автоматичні',
      'з того боку є людина',
      'ти нейронка',
      'ти програма',
      'чесно, ти штучний',
      'ти маєш почуття чи ти код',
      'ти ж не людина',
      'хто пише, людина чи ші',
      'ти на штучному інтелекті',
      'ты робот',
      'ты нейросеть',
      'это автоматические ответы',
      'ти реальна людина чи ні',
      'ти свідомий',
    ],
  },

  who_made: {
    ex: [
      "who's your developer",
      'who coded you',
      'your creator?',
      'who invented you',
      "who's the team behind atlas",
      'who owns you',
      'which developers built atlas',
      'who trained you',
      'where were you made',
      'who put you together',
      'who is responsible for you',
      'who makes this app',
      "what's the origin of atlas",
      'who gave you your name',
      'why the name atlas',
      "who's your dad",
      'who came up with you',
      "who's the author of this bot",
      'who launched atlas',
      'company behind you',
      'who brought you to life',
      'who are your makers',
      'tell me about your creators',
      'who designed this coach',
      "atlas, what's with the name",
    ],
    exUk: [
      'хто твій розробник',
      'хто тебе закодив',
      'хто тебе вигадав',
      'яка команда за атласом',
      'кому ти належиш',
      'хто тебе навчив',
      'де тебе зробили',
      'хто за тебе відповідає',
      'хто робить цей додаток',
      'звідки взялось ім’я атлас',
      'хто дав тобі ім’я',
      'чого ти атлас',
      'хто автор цього бота',
      'хто тебе запустив',
      'яка фірма за тобою',
      'хто твої батьки',
      'хто тебе зібрав',
      'розкажи про своїх творців',
      'хто спроєктував атласа',
      'чому саме атлас',
      'кто твой разработчик',
      'кто тебя придумал',
      'почему тебя зовут атлас',
      'хто тебе такого розумного зробив',
      'шо за люди тебе створили',
    ],
  },

  motivate: {
    ex: [
      'pump me up',
      'say something motivating',
      'hype me',
      'gas me up before squats',
      'i need a push',
      'give me some fire',
      'motivational speech please',
      'yell at me to go lift',
      'light a fire under me',
      'some motivation please',
      'coach, get me hyped',
      'talk me into leg day',
      'need a boost to get to the gym',
      'make me want to train',
      'encourage me',
      'rally me',
      'drop a motivational line',
      'get me in the zone',
      'psych me up',
      'one word to get me moving',
      'push me harder',
      'tell me why i should go today',
      'give me energy to train',
      'hit me with motivation',
      'be my hype man',
    ],
    exUk: [
      'замотивуй',
      'скажи щось мотивуюче',
      'накрути мене перед присідом',
      'треба пинка',
      'дай вогню',
      'мотиваційну промову будь ласка',
      'накричи на мене щоб я пішов качатись',
      'підбадьор перед днем ніг',
      'дай заряду',
      'потрібна мотивація, давай',
      'надихни мене на тренування',
      'розкачай мене морально',
      'заряди мене',
      'скажи чого мені йти сьогодні',
      'підштовхни мене',
      'дай енергії на зал',
      'вмотивуй мене',
      'налаштуй мене на тренування',
      'будь моїм мотиватором',
      'підтримай мене перед залом',
      'замотивируй меня',
      'дай пинка',
      'подтолкни меня в зал',
      'скажи шось шоб я встав з дивана',
      'мотивашку дай',
    ],
  },

  joke: {
    ex: [
      'joke',
      'got a joke for me',
      'make me smile',
      'crack a joke',
      'say something hilarious',
      'gym humour please',
      'tell me something funny',
      'hit me with a joke',
      'any funny lifting stories',
      'i could use a joke',
      'give me a pun',
      'a gym pun please',
      'another joke',
      "bet you can't make me laugh",
      'make a joke about cardio',
      'tell a joke about protein shakes',
      'joke about skipping leg day',
      'lighten the mood',
      'be funny',
      'do you know jokes',
      'humor me',
      'something to laugh at',
      'tell me your best joke',
      'funny one about the bench',
      'say a joke',
    ],
    exUk: [
      'жарт',
      'пожартуй щось',
      'розвесели мене',
      'скажи щось кумедне',
      'знаєш анекдоти',
      'ще анекдот',
      'жарт про качків',
      'розкажи прикол',
      'кинь жарт',
      'смішне про кардіо',
      'анекдот про протеїн',
      'жарт про день ніг',
      'підніми настрій жартом',
      'будь смішним',
      'твій найкращий жарт',
      'розкажи щось смішне про жим',
      'хочу анекдот',
      'каламбур про зал',
      'а ще жарт є',
      'розсміши',
      'пошути',
      'анекдот давай',
      'расскажи анекдот про качалку',
      'розкажи шось смішне',
      'дай прикол',
    ],
  },

  insult: {
    ex: [
      'fuck this',
      'shut your mouth',
      'piss off',
      "you're a moron",
      'you piece of crap',
      'go away',
      'stupid bot, fuck off',
      'damn you',
      'screw this bot',
      'you are trash',
      'eat shit',
      'bugger off',
      "you're pathetic",
      'go fuck yourself',
      'i hate you so much',
      "you're annoying as hell",
      'leave me alone idiot',
      'get lost',
      'what a dumbass bot',
      'shut it',
      'you are garbage',
      'i despise you',
      'bite me',
      'son of a bitch',
      'you bloody idiot',
    ],
    exUk: [
      'стули пельку',
      'дебіл',
      'іди нафіг',
      'ти придурок',
      'задовбав',
      'закрий рот',
      'пішов нахрін',
      'ненавиджу',
      'ти мене дістав',
      'тупий бот',
      'ти лох',
      'іди до біса',
      'мовчи вже',
      'ти ніхто',
      'відчепись',
      'ти гівно',
      'ненавиджу тебе всім серцем',
      'курва',
      'бісиш',
      'дурень',
      'пошел ты',
      'заткнись уже, бот',
      'иди нахрен',
      'ненавижу тебя',
      'шоб ти згорів',
    ],
  },

  done: {
    ex: [
      'finished training',
      "i'm done with the gym for today",
      'workout complete',
      'all finished',
      'just got back from the gym',
      'trained today, done',
      'smashed it, done',
      "that's it for today",
      'session complete',
      'wrapped up my workout',
      'completed',
      'i worked out already',
      'all wrapped up at the gym',
      'went to the gym, done',
      'done and dusted',
      'hit the gym, all done',
      'workout finished',
      'i did my session',
      'just wrapped up training',
      "completed today's workout",
      'training over',
      "i'm finished lifting",
      'done with legs',
      'i completed the workout',
      "that's today's training done",
    ],
    exUk: [
      'все, я відтренувався',
      'відтренувалась',
      'позаймався',
      'закінчила',
      'тренування завершено',
      'відпрацював',
      'повернувся з залу',
      'все, відкачався',
      'на сьогодні все',
      'виконав',
      'сходив у зал',
      'тренування є',
      'я закінчив тренування',
      'зробила тренування',
      'відходив сьогодні',
      'позаймалась',
      'виконано',
      'закінчив з ногами',
      'відбув тренування',
      'фух, зробив',
      'сделал',
      'закончил',
      'все, потренировался',
      'шо, все зробив',
      'готово, відтренувався',
    ],
  },

  bye: {
    ex: [
      'cheers, bye',
      'take care',
      'talk to you later',
      'i gotta run',
      'later atlas',
      'peace out',
      "i'm out",
      'farewell',
      'ttyl',
      'catch you tomorrow',
      'see you next time',
      'bye for now',
      'have a good one, bye',
      'until next time',
      'logging off',
      "i'm leaving",
      'adios',
      'bye bye',
      'ciao',
      'later dude',
      "that's all, bye",
      'gotta bounce',
      'see you around',
      'heading out, bye',
      'until tomorrow',
    ],
    exUk: [
      'бувайте',
      'бай',
      'до наступного разу',
      'на все добре',
      'бувай, друже',
      'давай, до завтра',
      'я пішов',
      'до зв’язку',
      'побігла',
      'чао',
      'пока-пока',
      'ладно, бувай',
      'мені вже треба йти',
      'до вечора',
      'до скорої зустрічі',
      'щасти, бувай',
      'все, я пішла',
      'папа',
      'бб',
      'до встречи',
      'увидимся',
      'ну давай, па',
      'всього доброго',
      'всьо, бувай',
      'прощавай',
    ],
  },

  how_are_you: {
    ex: [
      "how's it going atlas",
      'how you been',
      'how are you feeling today',
      'u ok',
      'you doing alright',
      "how's everything",
      'how are you, coach',
      "hope you're well",
      "how's your mood",
      'hows it hanging',
      "how's your day going",
      'you all good',
      'doing well?',
      'are you okay',
      "how's the coach doing",
      'how are u',
      "how's your week",
      'you feeling good today',
      "how's tricks",
      'and how are you',
      'how r u',
      'are you having a good day',
      'you well?',
      'how are you getting on',
      "how's atlas today",
    ],
    exUk: [
      'як ся маєш, атласе',
      'як ти там',
      'як ти почуваєшся',
      'у тебе все ок',
      'в тебе все нормально',
      'як справи, тренере',
      'як твій настрій',
      'як минає день',
      'у тебе все гаразд',
      'як тижень',
      'а в тебе як',
      'як воно, нормально',
      'як себе почуваєш',
      'ну як ти',
      'як поживає атлас',
      'у тебе день добрий',
      'як ти взагалі',
      'шо як у тебе',
      'як ти сам',
      'в тебе все пучком',
      'как поживаешь',
      'как ты там',
      'как настроение',
      'як житуха',
      'шо там у тебе',
    ],
  },

  heaviest: {
    ex: [
      "biggest weight i've ever moved",
      "what's the most i've lifted on anything",
      'heaviest lift across all exercises',
      "the most kilos i've ever handled",
      'which exercise has my biggest load',
      'my heaviest weight overall',
      'heaviest set of all time in my history',
      'max weight across my whole log',
      "what's the heaviest bar i've had",
      'which lift has my top weight',
      'most kg in a single set',
      'biggest load in my history',
      "highest weight i've ever logged",
      "what's the heaviest exercise i do",
      'the heaviest thing i ever picked up in the gym',
      'heaviest top set overall',
      'which movement do i move the most weight on',
      "across all my lifts what's heaviest",
      'the biggest weight in my records',
      'heaviest weight logged',
      "what's the most weight i've handled in the gym",
      'my overall heaviest',
      "largest weight i've lifted",
      'heaviest load ever',
      'highest kg number in my history',
    ],
    exUk: [
      'найбільша вага в історії',
      'найважче що я колись брав',
      'яка вправа в мене найважча',
      'найбільше кілограмів за раз',
      'найважчий сет за весь час',
      'максимальна вага серед усіх вправ',
      'де в мене найбільша вага',
      'яка найбільша вага в моїх записах',
      'найважчий топ-сет',
      'найбільше кіло що я підняв',
      'на чому я тягаю найбільше',
      'найважча вага загалом',
      'найбільша вага за всю історію',
      'яку найбільшу вагу я записував',
      'найбільше навантаження у вправі',
      'найважча штанга яку я брав',
      'моя найважча вага взагалі',
      'у якій вправі в мене найбільші кіло',
      'найважче серед усіх вправ',
      'найважчий вес',
      'какой самый тяжелый вес в моих записях',
      'в каком упражнении у меня самый большой вес',
      'максимальный вес вообще',
      'шо в мене найважче',
      'найбільше шо я колись піднімала',
    ],
  },

  favourite_lift: {
    ex: [
      'my go-to exercise',
      'which movement do i do all the time',
      "what's my most repeated exercise",
      'exercise i log most frequently',
      'fav lift',
      'what exercise shows up most',
      'which lifts do i always do',
      'top 3 exercises i do',
      'which exercise have i logged most often',
      'what do i keep doing every session',
      'most common exercise in my workouts',
      'favourite movement',
      'my most used exercise',
      'which exercise do i rely on most',
      "what's my staple lift",
      'which one do i do the most',
      'most popular exercise in my log',
      'what do i always end up doing',
      'most frequent lifts',
      'my signature lift',
      'what exercise do i never skip',
      'rank my exercises by how often i do them',
      'which exercises are my favourites',
      'which lift do i love the most judging by my log',
      'exercise count ranking',
    ],
    exUk: [
      'моя улюблена вправа',
      'що я роблю постійно',
      'яку вправу я найбільше повторюю',
      'яка вправа найчастіше в журналі',
      'улюблена вправа в мене',
      'які вправи я завжди роблю',
      'топ 3 моїх вправи',
      'найчастіша вправа',
      'що я роблю кожне тренування',
      'найпоширеніша вправа в моїх тренуваннях',
      'моя фірмова вправа',
      'без якої вправи я не можу',
      'яку вправу я найбільше люблю',
      'рейтинг вправ за частотою',
      'мої улюблені вправи',
      'що в мене найпопулярніше',
      'які вправи в мене основні по кількості',
      'найчастіше записана вправа',
      'шо я найбільше люблю робити',
      'яку вправу я ніколи не пропускаю',
      'любимое упражнение',
      'что я делаю чаще всего',
      'самое частое упражнение',
      'яку вправу я найчастіше записувала',
      'мій топ вправ',
    ],
  },

  consistency: {
    ex: [
      'how regular am i',
      'am i showing up every week',
      'have i been sticking to my training',
      'how disciplined have i been',
      'am i consistent with the gym',
      'check my training regularity',
      'have i been skipping weeks',
      'how many weeks did i hit 2 sessions',
      'is my attendance good',
      'do i stick with it',
      'am i reliable with my workouts',
      'am i on and off with training',
      'my training regularity over two months',
      'how steady have i been',
      'rate my discipline',
      'do i fall off often',
      'have i been regular or all over the place',
      'am i training every week',
      "how's my adherence",
      'my attendance record',
      'how can i train more regularly',
      'i keep falling off, how do i stay consistent',
      'am i committed enough',
      'how solid is my routine',
      'consistency',
    ],
    exUk: [
      'як я регулярно ходжу',
      'чи ходжу я кожен тиждень',
      'чи я тримаюсь графіка тренувань',
      'наскільки я дисциплінована',
      'чи я пропускаю тижні',
      'скільки тижнів було по два тренування',
      'моя відвідуваність',
      'чи я не закинув тренування',
      'я тренуюсь стабільно',
      'чи в мене стабільний режим',
      'оціни мою дисципліну',
      'я часто зриваюсь з тренувань',
      'чи я тренуюсь щотижня',
      'як мені бути регулярнішим',
      'постійно кидаю, як тримати регулярність',
      'як у мене з постійністю',
      'регулярність',
      'чи я систематично займаюсь',
      'наскільки я постійний у залі',
      'перевір чи я не пропускаю',
      'я стабильно хожу в зал',
      'как у меня с регулярностью',
      'я дисциплинированный',
      'шо там з регулярністю',
      'як у мене зі стабільністю тренувань',
    ],
  },

  best_weekday: {
    ex: [
      'which days of the week are my gym days',
      'what weekday am i most likely to train',
      'do i usually lift on weekends',
      'my usual training days',
      'which day do i go to the gym most often',
      'what days do i tend to work out',
      'mondays or fridays, when do i train more',
      'my favourite day to train',
      'which weekdays do i lift most',
      "what's my busiest gym day",
      'do i tend to train on tuesdays',
      'on what days am i usually in the gym',
      'which day of the week is my training day',
      'pattern of my training days',
      'what days does my log show most',
      'when during the week do i usually lift',
      'is saturday my main gym day',
      'which days do i skip and which do i train',
      'my top gym weekdays',
      'weekday breakdown of my sessions',
      'most frequent weekday',
      'what are my regular training days',
      'which day am i at the gym most',
      'am i a weekend lifter',
      'best weekday',
    ],
    exUk: [
      'по яких днях я ходжу в зал',
      'в які дні тижня я найчастіше треную',
      'я зазвичай тренуюсь на вихідних',
      'мої тренувальні дні',
      'в який день я найчастіше в залі',
      'понеділок чи п’ятниця, коли я частіше тренуюсь',
      'мій улюблений день для залу',
      'по яких днях тижня я качаюсь',
      'який день у мене найзавантаженіший',
      'я тренуюсь по вівторках',
      'субота мій основний день',
      'розбивка тренувань по днях тижня',
      'в які дні я зазвичай качаюсь',
      'який день тижня в мене тренувальний',
      'по яким дням у мене зал',
      'найпопулярніший день тижня в мене',
      'мої звичайні дні для тренувань',
      'коли протягом тижня я ходжу',
      'я більше тренуюсь на вихідних чи в будні',
      'в какой день недели я чаще тренируюсь',
      'по каким дням я качаюсь',
      'мои тренировочные дни',
      'в які дні я найчастіше тренувалась',
      'шо за дні я зазвичай ходжу',
      'мій найчастіший день тижня',
    ],
  },

  rest_actual: {
    ex: [
      'how long am i really resting',
      'my actual rest periods',
      'real rest time in my last workout',
      'how many minutes did i sit between sets last time',
      'check how long my breaks were',
      'my median rest',
      'was i resting too much last session',
      'actual time between my sets',
      'how long did i take between sets',
      'track my real rest',
      'am i taking long breaks between sets',
      'what were my rest intervals yesterday',
      'how much time passes between my sets',
      'my typical break between sets',
      'do i take too much time between sets according to the log',
      'rest times from my log',
      'measured rest last workout',
      'how long do i chill between sets',
      'how much do i actually rest on average',
      'what was my average break',
      'actual rest',
      'how long were my pauses between sets',
      'do my breaks drag on',
      "what's my real rest per set",
      'how quick am i between sets',
    ],
    exUk: [
      'скільки я реально стою між сетами',
      'мої фактичні паузи',
      'реальний відпочинок у минулому тренуванні',
      'скільки хвилин я сидів між підходами минулого разу',
      'перевір які в мене були перерви',
      'скільки проходить між моїми сетами',
      'я не засиджуюсь між підходами',
      'фактичний час між підходами',
      'скільки я відпочивала між сетами',
      'реальні перерви між підходами',
      'мої інтервали відпочинку вчора',
      'скільки часу я витрачаю між сетами',
      'довгі в мене паузи чи ні',
      'середня перерва між підходами',
      'скільки я чілю між сетами',
      'фактичний відпочинок',
      'судячи з журналу я довго відпочиваю',
      'скільки тривали мої паузи',
      'виміряний відпочинок',
      'скільки я відпочиваю по факту',
      'сколько я реально стою между подходами',
      'мой средний отдых между сетами',
      'сколько я отдыхал на прошлой тренировке',
      'шо там з моїми паузами між сетами',
      'скільки я насправді перепочиваю',
    ],
  },

  warmup_habit: {
    ex: [
      'am i skipping warm ups',
      'do i actually warm up',
      'check my warm up consistency',
      'do my workouts begin with warm-up sets',
      'how often do i skip warming up',
      'have i warmed up in my recent sessions',
      'am i good about warming up',
      'do i jump straight into working sets',
      'warm up habit',
      'do i bother with warm ups',
      'is warming up part of my routine',
      'how many of my sessions had a warm up',
      'i never warm up, right',
      'look at my log, do i warm up',
      'warmups, do i do them',
      'am i warming up before heavy sets',
      'do i warm up often enough',
      'did i warm up last few workouts',
      'my warm up record',
      'am i lazy with warm ups',
      'do i go cold into my lifts',
      'have i been neglecting warm ups',
      'how consistent am i with warm-ups',
      'do my sessions start with a warm up',
      'warm up tracking',
    ],
    exUk: [
      'я пропускаю розминки',
      'чи я взагалі розминаюсь',
      'перевір чи регулярно я розминаюсь',
      'чи починаються мої тренування з розминки',
      'як часто я не розминаюсь',
      'чи розминалась я останні тренування',
      'одразу беруся за робочі сети без розминки',
      'звичка розминатися',
      'розминка є в моїх тренуваннях',
      'скільки тренувань було з розминкою',
      'я ніколи не розминаюсь, так',
      'подивись журнал, я розминаюсь',
      'чи розминаюсь я перед важкими сетами',
      'достатньо часто я розминаюсь',
      'чи я лінуюсь розминатись',
      'чи я на холодну йду у вправи',
      'я забиваю на розминку',
      'як у мене з розминками',
      'розминаюсь я чи ні судячи з записів',
      'мої розминки',
      'я пропускаю разминку',
      'делаю ли я разминку перед тренировкой',
      'как часто я разминаюсь',
      'шо, я знову без розминки тренуюсь',
      'чи я не забиваю на розминку',
    ],
  },

  cardio_done: {
    ex: [
      'cardio this week',
      'how many minutes did i move this week',
      'am i at 150 minutes yet',
      'weekly activity summary',
      'how much walking have i logged in the last 7 days',
      'cardio total for the week',
      'how many runs did i do this week',
      'how many activities have i logged this week',
      'my activity minutes over 7 days',
      'did i reach the weekly cardio goal',
      'how much conditioning have i done lately',
      'how much cycling did i do this week',
      'activity count this week',
      'how many cardio sessions this week',
      'weekly movement total',
      'how far am i from 150 minutes',
      'did i move enough this week',
      'how much aerobic work this week',
      'last 7 days of cardio',
      'sum of my activities this week',
      'how many walks this week',
      'my cardio minutes',
      'how much have i been walking lately',
      "what's my weekly cardio",
      'am i doing enough cardio lately',
    ],
    exUk: [
      'кардіо за тиждень',
      'скільки хвилин руху цього тижня',
      'я вже набрав 150 хвилин',
      'підсумок активності за тиждень',
      'скільки прогулянок за останні 7 днів',
      'скільки пробіжок цього тижня',
      'скільки активностей я записала за тиждень',
      'хвилини активності за 7 днів',
      'чи виконав я тижневу норму кардіо',
      'скільки я крутив велосипед цього тижня',
      'скільки кардіо сесій за тиждень',
      'скільки лишилось до 150 хвилин',
      'чи достатньо я рухався цього тижня',
      'кардіо за останні 7 днів',
      'сума активностей за тиждень',
      'мої хвилини кардіо',
      'скільки я находив за тиждень',
      'яке в мене кардіо за тиждень',
      'скільки я бігав цього тижня',
      'мій тижневий рух',
      'сколько я гулял за неделю',
      'сколько минут активности за неделю',
      'набрал ли я 150 минут',
      'шо з кардіо цього тижня',
      'скільки аеробки за тиждень',
    ],
  },

  my_gym: {
    ex: [
      'which gym do i go to',
      'where do i usually go to train',
      'which gym am i going to lately',
      'which gym do i use most',
      'my usual gym',
      'saved gyms',
      'what gym am i at most often',
      'how many gyms are saved in my account',
      'which location do i train at most',
      'my home gym in the app',
      "gyms i've added",
      'which gym has the most sessions',
      'where do i usually lift',
      'do i switch between gyms',
      'number of gyms saved',
      'my gyms list',
      'which club do i go to most',
      "what's my primary gym",
      'gym breakdown of my sessions',
      'which of my gyms do i visit most',
      'sessions per gym',
      'where have i been training mostly',
      'show my saved gyms',
      'favourite gym',
      'which gym am i at the most',
      'gym stats',
      'most frequented gym',
      'how many different gyms have i trained at',
    ],
    exUk: [
      'який зал я відвідую найчастіше',
      'мій звичайний зал',
      'збережені зали',
      'скільки залів у мене в акаунті',
      'в якій локації я тренуюсь найбільше',
      'додані зали',
      'в якому залі найбільше тренувань',
      'де я зазвичай тренуюсь',
      'я міняю зали',
      'кількість збережених залів',
      'список залів',
      'в який клуб я ходжу найчастіше',
      'мій основний зал',
      'тренування по залах',
      'який з моїх залів найчастіший',
      'покажи мої зали',
      'улюблений зал',
      'в скількох залах я тренувався',
      'статистика по залах',
      'мій головний зал',
      'в какой зал я хожу чаще',
      'мои залы',
      'сколько у меня залов',
      'шо за зали в мене збережені',
      'де я качаюсь найчастіше',
    ],
  },

  my_goal: {
    ex: [
      'my goal',
      'what am i aiming for',
      'what goal do i have',
      "remind me what i'm working toward",
      'change my goal',
      'update my physique target',
      'where are goals in the app',
      'which goal did i choose',
      'i want a different goal',
      'does my goal affect my plan',
      'what did i set as my target',
      'show me my current goal',
      'is a goal set on my account',
      'can i pick a new goal',
      'how does my goal shape training',
      'what is my target body',
      'my current aim',
      'goal settings',
      'i want to switch my goal',
      'when did i set my goal',
      'edit goal',
      "what's the goal i picked",
      'have i chosen a goal yet',
      'update my goal',
      "where do i change what i'm training for",
    ],
    exUk: [
      'моя ціль',
      'до чого я прагну',
      'яка в мене мета',
      'нагадай до чого я йду',
      'змінити мою ціль',
      'оновити ціль по фігурі',
      'де цілі в додатку',
      'яку мету я вибрав',
      'хочу іншу ціль',
      'ціль впливає на план',
      'що я поставила за ціль',
      'покажи поточну ціль',
      'в мене задана ціль',
      'можна вибрати нову мету',
      'як ціль впливає на тренування',
      'яка моя цільова фігура',
      'налаштування цілі',
      'коли я поставив ціль',
      'редагувати ціль',
      'я вже вибрала ціль',
      'де поміняти мету',
      'моя цель',
      'поменять цель',
      'где выбрать цель',
      'шо в мене за ціль стоїть',
    ],
  },

  bw_trend: {
    ex: [
      'am i getting heavier',
      'am i getting lighter',
      'which way is my weight heading',
      'has my weight gone up',
      'have i dropped any weight',
      'is my bodyweight climbing',
      'have i put on kilos',
      'is the scale moving',
      'weight trending up or down',
      'did i lose weight',
      'did i gain weight',
      'am i slimming down',
      'have i lost kilos lately',
      'how much weight did i put on',
      'is my weight rising',
      'have i gotten heavier recently',
      'is my weight stable or changing',
      'weight direction',
      'bodyweight going up?',
      'am i dropping pounds',
      'change in my weigh-ins',
      'am i bulking or cutting judging by the scale',
      'net weight change',
      'is my weight dropping off',
      "how's my weight trending",
    ],
    exUk: [
      'я поважчав',
      'я схудла',
      'куди йде моя вага',
      'вага пішла вгору',
      'я скинув хоч щось',
      'вага тіла росте',
      'я набрав кілограми',
      'ваги рухаються',
      'вага вгору чи вниз',
      'я схуд чи ні',
      'я поправилась',
      'я худію',
      'скільки кілограмів я набрала',
      'вага зростає',
      'вага стоїть чи міняється',
      'в який бік іде вага',
      'скільки я втратив ваги',
      'зміна по зважуваннях',
      'я набираю масу судячи з ваги',
      'тренд ваги тіла',
      'я поправился',
      'вес растет',
      'я похудел',
      'шо з вагою, падає чи росте',
      'я скидаю кіло чи ні',
    ],
  },

  strength_ratio: {
    ex: [
      'is my bench any good for my weight',
      'am i strong for my size',
      'is a 120 squat good at 80 kg',
      'how does my deadlift compare to my bodyweight',
      'is my press weak',
      'bodyweight bench, is that good',
      'is double bodyweight deadlift strong',
      'is my squat weak for my weight',
      'rate my bench',
      'is my ohp respectable',
      'is 60 kg bench ok for a guy my size',
      'is my squat above average',
      'am i weak on deadlift',
      'is my bench strong or weak',
      'how impressive is my squat',
      'do i bench a lot for my weight',
      'is 1.5x bodyweight squat decent',
      'is my deadlift good relative to bodyweight',
      'strength level of my bench',
      'is my pull up strong for my weight',
      'rate my squat relative to my weight',
      'is my bench above average',
      'am i strong on overhead press',
      'is my lift good or bad',
      'is my row good for my bodyweight',
    ],
    exUk: [
      'мій жим нормальний для моєї ваги',
      'я сильний для своєї комплекції',
      'присід 120 при вазі 80 це добре',
      'як моя станова відносно ваги тіла',
      'мій жим слабкий',
      'жим своєї ваги це добре',
      'станова дві ваги тіла це сильно',
      'присід слабкий для моєї ваги',
      'оціни мій жим',
      'мій армійський жим пристойний',
      '60 кг жиму для мене норм',
      'мій присід вище середнього',
      'я слабкий у становій',
      'мій жим сильний чи слабкий',
      'наскільки вражаючий мій присід',
      'я багато жму для своєї ваги',
      'присід півтори ваги тіла це нормально',
      'який рівень у мого жиму',
      'я сильно підтягуюсь для своєї ваги',
      'оціни присід відносно ваги',
      'это хороший присед для моего веса',
      'я сильный для своего веса',
      'моя становая это нормально',
      'шо, мій жим слабенький',
      'моя тяга в нахилі норм для моєї ваги',
    ],
  },

  month: {
    ex: [
      'this month so far',
      "how's my month looking",
      'monthly numbers',
      'sessions since the 1st',
      'how many workouts this month',
      'sum up my month',
      'what did i do in september',
      'month to date training',
      'how many sets since the start of the month',
      'hard sets this month',
      'how many days did i train this month',
      'monthly training total',
      'give me a month summary',
      'how active was i this month',
      'month',
      'stats for this month',
      'how many trainings this month',
      'my training this calendar month',
      'count my sessions this month',
      'monthly report',
      'month in review',
      'how much have i trained this month',
      "how's the month going gym-wise",
      'workouts so far in october',
      'how many hard sets have i done in october',
    ],
    exUk: [
      'цей місяць',
      'як у мене місяць',
      'цифри за місяць',
      'тренування з першого числа',
      'скільки тренувань за місяць',
      'підсумуй мій місяць',
      'що я зробив у вересні',
      'скільки сетів з початку місяця',
      'робочі сети за місяць',
      'скільки днів я тренувався цього місяця',
      'загалом за місяць',
      'дай підсумок місяця',
      'наскільки я активний цього місяця',
      'статистика цього місяця',
      'скільки тренувань у жовтні',
      'мої тренування за календарний місяць',
      'порахуй тренування за місяць',
      'місячний звіт',
      'огляд місяця',
      'скільки я натренувала за місяць',
      'итоги месяца',
      'сколько подходов за месяц',
      'статистика за месяц',
      'шо я наробив за місяць',
      'скільки було тренувань у вересні',
    ],
  },

  longest_session: {
    ex: [
      'longest workout',
      'my longest session',
      'shortest session',
      "what's my record for workout length",
      'which workout lasted longest',
      "the longest time i've spent in the gym",
      "quickest session i've logged",
      'which training was the shortest',
      'longest workout duration',
      'longest session in minutes',
      'when was my marathon session',
      'my fastest workout ever',
      'how many minutes was my shortest session',
      'what was my longest gym visit',
      'which session dragged on the most',
      'shortest and longest workouts',
      'my briefest workout',
      'how long did my longest session take',
      "the longest i've ever trained in one go",
      'workout duration record',
      'min and max session length',
      'which day did i train the longest',
      'which session was quickest',
      'my record long workout',
      'shortest gym session so far',
    ],
    exUk: [
      'найтриваліше тренування',
      'моє найдовше тренування',
      'найкоротше тренування в мене',
      'рекорд тривалості тренування',
      'яке тренування тривало найдовше',
      'найбільше часу в залі за раз',
      'найшвидше тренування що я записав',
      'яке тренування було найкоротшим',
      'найдовша тривалість тренування',
      'найдовше тренування в хвилинах',
      'моя найкоротша сесія',
      'скільки хвилин тривало найкоротше тренування',
      'найдовший візит у зал',
      'яке тренування найбільше затягнулось',
      'найкоротше й найдовше',
      'скільки йшло найдовше тренування',
      'найдовше я тренувалась за раз',
      'рекорд по тривалості',
      'мінімальна й максимальна тривалість тренувань',
      'в який день я тренувався найдовше',
      'самая короткая тренировка',
      'самая долгая тренировка',
      'сколько длилась самая длинная тренировка',
      'шо було найдовше тренування',
      'найкоротша тренуха',
    ],
  },

  grow_muscle: {
    ex: [
      'how do i build my glutes',
      'my shoulders are lagging',
      "chest won't grow",
      'calves not growing',
      'how to get wider',
      'how do i build thicker traps',
      'how to grow rear delts',
      'my quads are small',
      'hamstrings not developing',
      'how to get a bigger chest',
      'how to build a v taper',
      'how do i grow side delts',
      'how can i grow my lats',
      'how to thicken my back',
      'lagging chest, what do i change',
      'tips for bigger calves',
      'how to build my butt',
      'how to get boulder shoulders',
      "forearms won't grow",
      'how do i make my legs bigger',
      'grow my upper back',
      'bring up my weak hamstrings',
      'how do i get a thicker neck',
      'what builds the lower lats',
      'how to add size to my quads',
    ],
    exUk: [
      'як накачати попу',
      'плечі відстають',
      'груди не ростуть ніяк',
      'литки не ростуть взагалі',
      'як стати ширшим',
      'як наростити трапецію',
      'як накачати задні дельти',
      'в мене малий квадрицепс',
      'біцепс стегна не розвивається',
      'як збільшити груди',
      'як зробити v-силует',
      'як накачати середні дельти',
      'як накачати найширші',
      'як зробити спину товщою',
      'відстають груди, що міняти',
      'поради для великих литок',
      'як накачати сідничні',
      'як накачати ноги',
      'як накачати верх спини',
      'як накачати шию',
      'як збільшити квадри',
      'как накачать ягодицы',
      'как увеличить икры',
      'как накачать широчайшие',
      'шо робити щоб плечі росли',
    ],
  },

  arms: {
    ex: [
      'bigger arms',
      'how to grow my guns',
      'arm size tips',
      "my biceps and triceps won't grow",
      'how to build big arms',
      'stick arms, help',
      'how do i fill out my sleeves',
      'arm training for size',
      'arms are lagging',
      'how many sets for biceps and triceps',
      'how often to hit arms',
      'arm growth',
      'how to get 40 cm arms',
      'i want thicker arms',
      'how do i add inches to my arms',
      'how to pump up my arms',
      'arm workout to grow',
      'why are my arms still small',
      'arms stuck at the same size',
      'how to make arms huge',
      'bis and tris not growing',
      'best approach for arm size',
      'get jacked arms',
      'arms are my weak point',
      'how do i get bigger biceps and triceps',
    ],
    exUk: [
      'великі руки',
      'як накачати біцуху і трицуху',
      'поради для об’єму рук',
      'біцепс і трицепс не ростуть',
      'як накачати великі руки',
      'руки як палки, допоможи',
      'хочу щоб футболка на руках сиділа тісно',
      'тренування рук на масу',
      'руки відстають',
      'скільки підходів на біцепс і трицепс',
      'як часто качати руки',
      'ріст рук',
      'як накачати руки до 40 см',
      'хочу товстіші руки',
      'як збільшити обхват рук',
      'тренування рук щоб росли',
      'чому в мене досі маленькі руки',
      'руки стоять на місці',
      'як накачати здорові руки',
      'руки моє слабке місце',
      'как накачать бицепс и трицепс',
      'руки не растут что делать',
      'хочу большие руки',
      'шо робити з худими руками',
      'як наростити банки',
    ],
  },

  add_weight: {
    ex: [
      'when do i bump the weight',
      'how much do i add next time',
      'when to go heavier',
      'time to add plates?',
      'how big of a jump on squat',
      'should i go up 2.5 or 5',
      "how do i know i'm ready for more weight",
      'weight jumps on bench press',
      'progression increments',
      'how much to increase on lateral raises',
      'when should i move up in weight on curls',
      'how fast should i add weight',
      'when to load more on the bar',
      'how much weight to add each week',
      'should i add kilos or reps first',
      'i hit all my reps, add weight now?',
      'smallest jump for dumbbells',
      'how do i progress the weight',
      'adding weight on the deadlift, how much',
      'when do i up the weight',
      'increments on overhead press',
      'how many kg to add per step',
      'when is it time to go up',
      'should i increase the load',
      'how much more should i put on',
    ],
    exUk: [
      'коли піднімати вагу',
      'скільки додати наступного разу',
      'коли йти важче',
      'вже пора додавати блини',
      'який крок на присіді',
      'додати 2,5 чи 5',
      'як зрозуміти що готовий до більшої ваги',
      'крок ваги на жимі лежачи',
      'скільки додавати на махах',
      'коли збільшувати вагу на біцепсі',
      'як швидко додавати вагу',
      'скільки кг додавати щотижня',
      'спочатку додавати вагу чи повтори',
      'зробив всі повтори, додавати вагу',
      'найменший крок для гантелей',
      'як прогресувати по вазі',
      'скільки накинути на станову',
      'крок для армійського жиму',
      'коли пора підвищувати',
      'збільшувати навантаження вже',
      'скільки ще накинути',
      'когда добавлять вес',
      'сколько накидывать на присед',
      'когда пора повышать вес',
      'шо, вже можна додати кілограми',
    ],
  },

  strength_vs_size: {
    ex: [
      'strength or hypertrophy training',
      'should i train like a powerlifter or a bodybuilder',
      'reps for mass vs reps for strength',
      'is heavy low rep work good for size',
      'powerlifting vs bodybuilding style',
      'do high reps build strength',
      'can 20 reps grow muscle',
      'what rep range for size',
      'is 3 reps enough to grow',
      'heavy or light for muscle',
      'train for strength or for looks',
      'hypertrophy vs strength',
      'is the 8 to 12 range best for muscle',
      'big or strong, which should i chase',
      'does lifting heavy make you bigger',
      'can i get big with light weights',
      'which is better, 5x5 or 3x10',
      'muscle size or max strength',
      'high rep vs low rep training',
      'does strength training build mass',
      'should i focus on getting strong or getting big',
      'do you need to lift heavy for hypertrophy',
      'low reps for strength, high for size?',
      'difference between power and bodybuilding programs',
      'size vs strength',
    ],
    exUk: [
      'силове чи на гіпертрофію',
      'тренуватися як пауерліфтер чи як бодібілдер',
      'повтори на масу проти повторів на силу',
      'важкі малоповторні підходи для маси',
      'пауерліфтинг чи бодібілдинг',
      'багатоповторка дає силу',
      '20 повторів качають м’язи',
      'скільки повторів на гіпертрофію',
      '3 повтори достатньо для росту',
      'важко чи легко для м’язів',
      'тренуватися на силу чи на вигляд',
      'гіпертрофія проти сили',
      '8-12 повторів найкраще для м’язів',
      'бути великим чи сильним',
      'важкі ваги роблять більшим',
      'можна накачатися легкими вагами',
      'що краще, 5 на 5 чи 3 на 10',
      'об’єм м’язів чи максимальна сила',
      'силові тренування дають масу',
      'треба тягати важке для гіпертрофії',
      'на рельєф чи на силу качатися',
      'сила или масса',
      'сколько повторений на массу',
      'многоповторка или тяжелые веса',
      'шо краще, качати силу чи масу',
    ],
  },

  periodization: {
    ex: [
      'periodization',
      'mesocycles explained',
      "what's a macrocycle",
      'how do training phases work',
      'should i run my training in blocks',
      'block length',
      'how many weeks is a mesocycle',
      'undulating periodization',
      'what is dup',
      'do i need to cycle my training',
      'how do you structure my blocks',
      'when does this block finish',
      'what week of the block am i in',
      'accumulation and intensification phases',
      'planning training in cycles',
      "what's the point of periodizing",
      'linear periodization',
      'how are phases planned in my program',
      'should my program have waves',
      'is periodization necessary for beginners',
      'how long is a training cycle',
      "what's a microcycle",
      'do my blocks end with a lighter week',
      'periodised programming',
      'why train in blocks',
    ],
    exUk: [
      'періодизація',
      'мезоцикли',
      'що таке макроцикл',
      'як працюють фази тренувань',
      'тренуватися блоками',
      'тривалість блоку',
      'скільки тижнів у мезоциклі',
      'хвильова періодизація',
      'чи треба циклувати тренування',
      'як ти будуєш мої блоки',
      'коли закінчується цей блок',
      'на якому я тижні блоку',
      'фази накопичення й інтенсифікації',
      'планування тренувань циклами',
      'навіщо періодизація',
      'лінійна періодизація',
      'як сплановані фази в програмі',
      'чи потрібна періодизація новачку',
      'скільки триває тренувальний цикл',
      'що таке мікроцикл',
      'навіщо тренуватися блоками',
      'что такое мезоцикл',
      'сколько длится блок',
      'линейная периодизация',
      'шо таке ці цикли в програмі',
    ],
  },

  unilateral: {
    ex: [
      'left arm weaker',
      'one side is bigger than the other',
      'strength imbalance',
      'my right pec is bigger than my left',
      'single arm work',
      'unilateral exercises',
      'how to even out my sides',
      'one leg does more work in the squat',
      'my left quad is smaller',
      'asymmetry between left and right',
      'single leg training benefits',
      'fix a lopsided chest',
      'one bicep is bigger',
      'how do i balance my weak side',
      'should i do extra sets on the weak side',
      'uneven shoulders strength',
      'one-sided training',
      'dumbbells to fix imbalances',
      'my left glute is weaker',
      'one arm lags on bench',
      'how to correct asymmetry',
      'is unilateral work good',
      'bulgarian split squats for imbalance',
      'right leg stronger than left',
      'how to fix uneven strength',
    ],
    exUk: [
      'ліва рука слабша',
      'одна сторона більша за іншу',
      'дисбаланс сили',
      'права грудна більша за ліву',
      'вправи на одну руку',
      'однобічні вправи',
      'як вирівняти сторони',
      'одна нога більше працює в присіді',
      'лівий квадрицепс менший',
      'асиметрія між лівою і правою',
      'вправи на одну ногу користь',
      'як виправити перекіс грудей',
      'один біцепс більший',
      'як підтягнути слабшу сторону',
      'робити більше підходів на слабку сторону',
      'гантелі щоб виправити дисбаланс',
      'ліва сіднична слабша',
      'одна рука відстає на жимі',
      'як виправити асиметрію',
      'права нога сильніша за ліву',
      'асимметрия мышц',
      'одна нога слабее',
      'как выровнять стороны',
      'шо робити якщо одна рука слабша',
      'перекіс по силі',
    ],
  },

  pullup_zero: {
    ex: [
      '0 pull ups',
      "i can't pull myself up at all",
      'first pull up ever, how',
      "can't do one chin up",
      'never done a pull up',
      'how to go from zero to one pull up',
      'i just hang on the bar',
      'pull up progression for beginners',
      "i'm too weak for pull ups",
      "can't get my chin over the bar",
      'will negatives get me my first pull up',
      "how do i start training pull ups if i can't do any",
      'unable to do pull ups',
      'zero chin ups',
      'i want to do my first pull up',
      'assisted pull ups until i can do one',
      'how long to get a first chin up',
      'not even one pull up',
      'how do i build up to a pull up',
      'stuck at zero pull-ups',
      "can't do a pullup, help",
      'learning my first pull up',
      'pull ups impossible for me',
      'how to unlock the first pull up',
      'from dead hang to first rep',
    ],
    exUk: [
      '0 підтягувань',
      'взагалі не можу підтягнутися',
      'перше підтягування, як',
      'жодного разу не підтягнусь',
      'ніколи не підтягувався',
      'як з нуля до одного підтягування',
      'просто вишу на перекладині',
      'прогресія підтягувань для новачка',
      'я заслабка для підтягувань',
      'не можу дотягнути підборіддя до турніка',
      'негативи дадуть перше підтягування',
      'як тренувати підтягування якщо жодного не можу',
      'не вмію підтягуватися',
      'хочу зробити перше підтягування',
      'підтягування з допомогою поки не зможу сам',
      'скільки треба щоб підтягнутися перший раз',
      'навіть одного не можу',
      'застряг на нулі підтягувань',
      'підтягування для мене неможливі',
      'як навчитися підтягуватися новачку',
      'ни разу не подтягиваюсь',
      'как подтянуться первый раз',
      'не могу подтянуться',
      'шо робити якщо не підтягуюсь зовсім',
      'як нарешті підтягнутись хоч раз',
    ],
  },

  squat_vs_press: {
    ex: [
      'squats or leg press',
      'leg press vs squat',
      'is the leg press a squat replacement',
      'should i ditch squats for leg press',
      'leg press instead of squats',
      'do squats beat leg press for size',
      'can the leg press replace back squats',
      'machine press vs barbell squat for legs',
      'i hate squats, is leg press fine',
      'is leg press enough for quads',
      'squat or sled press for leg growth',
      'only leg press for legs, good idea?',
      'is leg pressing as effective as squatting',
      'do i have to squat or can i leg press',
      'leg press or back squat',
      'which is better for quads, squats or leg press',
      'squats bother my back, leg press ok?',
      'can i drop squats and keep leg press',
      'back squat vs leg press',
      'squat versus leg press',
      'is leg press cheating compared to squats',
      'do i need both squats and leg press',
      'should i squat or use the leg press',
      'leg press over squats',
      'squat or leg press for bigger quads',
    ],
    exUk: [
      'присідання чи жим ногами',
      'жим ногами проти присіду',
      'жим ногами замінює присід',
      'кинути присід і робити жим ногами',
      'жим ногами замість присідань',
      'присід кращий за платформу для маси',
      'тренажер чи штанга для ніг',
      'ненавиджу присід, жим ногами норм',
      'жим ногами досить для квадрицепса',
      'тільки платформа на ноги, нормально',
      'жим ногами такий же ефективний як присід',
      'обов’язково присідати чи можна жати ногами',
      'що краще для квадрів, присід чи жим ногами',
      'присід болить спина, жим ногами підійде',
      'прибрати присід і лишити жим ногами',
      'присід зі штангою проти жиму ногами',
      'жим ногами це читинг порівняно з присідом',
      'потрібні і присід і жим ногами',
      'присідати чи на платформу',
      'платформа чи присід',
      'жим ногами вместо приседа',
      'что лучше присед или жим ногами',
      'можно не приседать а делать жим ногами',
      'шо краще, присід чи платформа',
      'жим ногами чи присідання для ніг',
    ],
  },

  incline_flat: {
    ex: [
      'incline vs flat',
      'flat bench or incline',
      'upper chest',
      'how do i hit the upper pecs',
      'incline press angle',
      '30 or 45 degree incline',
      'is incline bench necessary',
      'flat press for chest size',
      'upper chest looks flat',
      'incline or flat first',
      'clavicular head chest exercises',
      'does incline work upper chest better',
      'only flat bench, is that enough',
      'can i skip flat and do incline',
      'incline dumbbell or flat barbell',
      'how to fill out the top of my chest',
      'bench angle for upper chest',
      'is flat bench better for mass',
      'my chest is all lower chest',
      'incline bench worth it',
      'which bench for upper chest',
      'flat or inclined pressing',
      'upper chest is weak',
      'should i swap flat bench for incline',
      'incline vs flat for pecs',
    ],
    exUk: [
      'похилий чи горизонтальний',
      'горизонтальна лава чи похила',
      'верх грудей',
      'як пропрацювати верх грудних',
      'кут жиму на похилій',
      '30 чи 45 градусів',
      'обов’язково жим на похилій',
      'горизонтальний жим на масу грудей',
      'верх грудей плаский',
      'спочатку похилий чи горизонтальний',
      'похилий жим краще качає верх',
      'лише горизонтальний жим, цього досить',
      'можна прибрати горизонтальний і робити похилий',
      'гантелі на похилій чи штанга лежачи',
      'як заповнити верх грудей',
      'кут лави для верху грудей',
      'горизонтальний краще для маси',
      'похилий жим варто робити',
      'яка лава для верху грудей',
      'слабкий верх грудей',
      'верх груди не растет',
      'наклонная или горизонтальная скамья',
      'какой угол для верха груди',
      'шо краще, похила чи горизонтальна',
      'замінити горизонтальний жим на похилий',
    ],
  },

  foam_roll: {
    ex: [
      'foam rolling',
      'is rolling worth it',
      'massage gun for recovery',
      'should i use a massage gun after lifting',
      'does massage help recovery',
      'foam roller use',
      'is the theragun worth buying',
      'how long to roll each muscle',
      'roll before lifting or after',
      'does foam rolling do anything',
      'percussion massage for sore muscles',
      'rolling out my it band',
      'lacrosse ball for tight spots',
      'is getting massages good for lifters',
      'myofascial release',
      'foam rolling vs stretching',
      'roller for tight calves',
      'do massage guns help growth',
      'should i roll my back',
      'is foam rolling a waste of time',
      'how often should i use a foam roller',
      'massage after heavy legs',
      'trigger point rolling',
      'does rolling release knots',
      'sports massage benefits',
    ],
    exUk: [
      'мфр',
      'ролик для м’язів',
      'масажний пістолет для відновлення',
      'масажер після тренування',
      'масаж допомагає відновленню',
      'як користуватися роликом',
      'чи варто брати масажний пістолет',
      'скільки катати кожен м’яз',
      'ролик перед тренуванням чи після',
      'мфр щось дає',
      'перкусійний масаж для забитих м’язів',
      'покатати іт-тракт',
      'м’ячик для тригерних точок',
      'масаж корисний для тих хто в залі',
      'ролик чи розтяжка',
      'ролик для литок',
      'масажний пістолет допомагає рости',
      'катати спину на ролику',
      'мфр це марна трата часу',
      'як часто катати ролик',
      'масаж після важких ніг',
      'массажный пистолет стоит брать',
      'мфр до или после тренировки',
      'массаж для восстановления',
      'шо дає ролик',
    ],
  },

  sauna_cold: {
    ex: [
      'sauna',
      'ice bath',
      'cold plunge',
      'is an ice bath good for recovery',
      'sauna after lifting ok',
      'can i do cold plunges on lifting days',
      'does cold water hurt muscle gains',
      'sauna for recovery',
      'ice bath after legs',
      'steam room after the gym',
      'cold therapy for lifters',
      'will a sauna help sore muscles',
      'hot or cold after training',
      'cryotherapy and gains',
      'contrast showers after the gym',
      'should i sit in the sauna after workouts',
      'is cold immersion bad for hypertrophy',
      'winter swimming and lifting',
      'sauna on rest days',
      'cold shower recovery',
      'ice bath timing',
      'can i hit the sauna right after training',
      'do cold baths stop muscle growth',
      'hot tub after workout',
      'sauna and muscle growth',
    ],
    exUk: [
      'сауна',
      'крижана ванна',
      'холодна купіль',
      'крижана ванна для відновлення',
      'сауна після силового норм',
      'можна холодну купіль в дні силових',
      'холодна вода шкодить росту м’язів',
      'сауна для відновлення',
      'крижана ванна після ніг',
      'парилка після залу',
      'холод для тих хто качається',
      'сауна допоможе від забитих м’язів',
      'гаряче чи холодне після тренування',
      'кріотерапія і м’язи',
      'контрастний душ після залу',
      'посидіти в сауні після тренування',
      'холодна ванна гальмує ріст',
      'сауна у дні відпочинку',
      'холодний душ для відновлення',
      'коли робити крижану ванну',
      'ледяная ванна после тренировки',
      'баня после тренировки',
      'холодная вода мешает росту мышц',
      'шо краще після залу, сауна чи холодний душ',
      'обливання холодною водою після качалки',
    ],
  },

  nap: {
    ex: [
      'nap',
      'should i nap today',
      'afternoon nap',
      'power nap',
      'how long to nap',
      'nap before the gym',
      'is a nap enough after a short night',
      'napping for recovery',
      'best nap length',
      'will a nap mess up my sleep',
      'quick nap before training',
      'daytime sleep for gains',
      'can i nap after lunch',
      'is a 90 minute nap ok',
      'nap or coffee before workout',
      'i slept badly, should i nap',
      'latest time for a nap',
      'do naps count as recovery',
      'can naps replace night sleep',
      'is it bad to nap in the evening',
      'a short snooze before lifting',
      'siesta and training',
      '30 minute nap good',
      'does napping help muscle recovery',
      'i want to nap, good idea?',
    ],
    exUk: [
      'денний сон',
      'поспати вдень сьогодні',
      'сон після обіду',
      'короткий сон',
      'скільки спати вдень',
      'поспати перед залом',
      'денного сну досить після короткої ночі',
      'денний сон для відновлення',
      'оптимальна тривалість денного сну',
      'денний сон зіб’є нічний',
      'швиденько поспати перед тренуванням',
      'можна поспати після обіду',
      'півтори години вдень це нормально',
      'поспати чи кава перед тренуванням',
      'погано спав, поспати вдень',
      'до котрої можна спати вдень',
      'денний сон рахується як відновлення',
      'подрімати перед силовим',
      'сієста і тренування',
      'подрімати пів години корисно',
      'дневной сон перед тренировкой',
      'сколько спать днем',
      'покемарить днем',
      'шо, можна подрімати вдень',
      'хочу подрімати, це нормально',
    ],
  },

  stress: {
    ex: [
      'stressed out, gym or rest',
      'is it ok to lift when stressed',
      'burnout and training',
      'work is crazy, should i still work out',
      'does exercise reduce stress',
      'life stress is wrecking my recovery',
      'anxious today, should i train',
      'stressful week, adjust training?',
      'cortisol and muscle gains',
      "stressed and can't recover",
      'does stress affect gains',
      'training under a lot of stress',
      "i'm overwhelmed, should i skip the gym",
      'gym to deal with stress',
      'exam season and lifting',
      'mental stress and strength',
      'should i lift to clear my head',
      'stress is high, how to train',
      'burned out mentally, lift or not',
      'can lifting help my anxiety',
      'stress',
      'stress and recovery from workouts',
      'stressful job, how to train',
      'how should i train on a stressful day',
      'nervous breakdown week, gym?',
    ],
    exUk: [
      'стрес',
      'стрес, зал чи відпочинок',
      'можна тренуватися в стресі',
      'вигорання і тренування',
      'на роботі капець, тренуватися',
      'спорт знімає стрес',
      'стрес заважає відновлюватися',
      'тривога, тренуватися сьогодні',
      'стресовий тиждень, міняти тренування',
      'кортизол і ріст м’язів',
      'стрес впливає на прогрес',
      'я перевантажений, пропустити зал',
      'зал щоб зняти стрес',
      'сесія і качалка',
      'психологічний стрес і сила',
      'потренуватися щоб розвантажити голову',
      'морально вигорів, качатись чи ні',
      'силові допомагають від тривоги',
      'стресова робота, як тренуватися',
      'як тренуватися коли сильний стрес',
      'стресс и тренировки',
      'на нервах, идти в зал',
      'стресс мешает росту мышц',
      'шо робити з тренуваннями коли стрес',
      'все на нервах, треную чи ні',
    ],
  },

  bench_alone: {
    ex: [
      'benching alone',
      'no spotter bench',
      'training solo, how to bench safely',
      'what if i get pinned on bench',
      'squatting alone safely',
      'how to set safety arms',
      'no one to spot me',
      'bench without a spot',
      'should i skip collars when alone',
      'how to dump a failed squat',
      'home gym safety without a partner',
      'stuck with the bar on my chest',
      'how low should the safeties be',
      'how to escape a failed bench',
      'is it dangerous to bench alone',
      'safety straps for bench',
      'heavy benching with nobody around',
      'failing a squat alone',
      'should i bench in the rack',
      'dumbbells instead of barbell when alone',
      'spotter arms setup',
      'home squat rack safety',
      "can't find a spotter",
      'solo heavy squats',
      "i'm scared of getting stuck under the bar",
    ],
    exUk: [
      'жму сам без нікого',
      'жати без підстраховки',
      'тренуюсь один, як безпечно жати',
      'якщо штанга придавить на жимі',
      'присідати самому безпечно',
      'як виставити страхувальні упори',
      'нема кому страхувати',
      'без страхувальника жати',
      'не ставити замки коли один',
      'як скинути невдалий присід',
      'безпека в домашньому залі без партнера',
      'штанга застрягла на грудях',
      'на якій висоті ставити обмежувачі',
      'як вибратися з-під штанги',
      'небезпечно жати самому',
      'ремені-страхувальники для жиму',
      'важкий жим коли нікого нема',
      'не доприсів сам',
      'жати в рамі',
      'гантелі замість штанги коли сам',
      'нікого немає щоб підстрахувати',
      'жим без страхующего',
      'как безопасно приседать одному',
      'боюсь застрять под штангой',
      'шо робити як не дожав і нема страховки',
    ],
  },

  age: {
    ex: [
      'too old for the gym',
      'starting at 50',
      'is 40 too late to build muscle',
      'lifting in my 60s',
      'can i gain muscle at 70',
      "i'm 48, is it worth starting",
      'age and muscle growth',
      'older and new to lifting',
      'strength training for older adults',
      'lifting over 50',
      'is it safe to lift heavy after 55',
      'does getting older kill gains',
      'training as a 45 year old',
      'recovery after 40',
      'masters lifter',
      "never lifted and i'm 52",
      'too old to get strong?',
      'is it pointless to start at my age',
      'does age limit muscle',
      'how to train in your fifties',
      'weights for a 65 year old',
      'is 35 too old to start',
      'can middle aged people build muscle',
      "i'm getting older, should i change how i train",
      'retired and want to lift',
    ],
    exUk: [
      'застарий для залу',
      'почати в 50',
      'в 40 пізно набирати м’язи',
      'силові в 60',
      'можна набрати м’язи в 70',
      'мені 48, варто починати',
      'вік і ріст м’язів',
      'немолодий і новачок у залі',
      'силові для людей старшого віку',
      'тренування після 50',
      'безпечно тягати важке після 55',
      'з віком прогрес пропадає',
      'тренування в 45 років',
      'відновлення після 40',
      'ніколи не тренувався, мені 52',
      'застарий щоб стати сильним',
      'нема сенсу починати в моєму віці',
      'як тренуватися в п’ятдесят',
      '35 це пізно для початку',
      'можна накачатися в середньому віці',
      'мені 60, можно в зал',
      'в 45 поздно начинать качаться',
      'качалка после 50',
      'на пенсії хочу в зал',
      'шо, в сорок п’ять ще можна почати',
    ],
  },

  gym_anxiety: {
    ex: [
      "i'm intimidated by the gym",
      'anxious about the gym',
      'people stare at me',
      "i'm self-conscious in the gym",
      'scared of looking stupid in the gym',
      "i feel like i don't belong there",
      'worried people will laugh at me',
      'free weight section scares me',
      'gymtimidation',
      'how to feel comfortable in the gym',
      'nervous to train in front of others',
      'i avoid the gym because of people',
      'all the big guys make me nervous',
      "i'm the weakest person in the gym and it's embarrassing",
      'afraid of doing exercises wrong in public',
      'social anxiety at the gym',
      'i feel judged at the gym',
      'too embarrassed to go',
      'how do i stop caring what others think at the gym',
      'going to the gym for the first time scares me',
      "i'm overweight and scared of the gym",
      'i feel awkward lifting around people',
      'nervous about the weights area',
      'i freeze up in the gym',
      'gym is scary',
    ],
    exUk: [
      'зал лякає',
      'тривожно йти в зал',
      'на мене витріщаються',
      'я соромлюсь у залі',
      'боюся виглядати тупо в залі',
      'почуваюсь там чужим',
      'боюсь що з мене сміятимуться',
      'зона вільних ваг лякає',
      'як почуватися комфортно в залі',
      'нервую тренуватися при інших',
      'уникаю зал через людей',
      'великі хлопці в залі мене бентежать',
      'я найслабша в залі і мені соромно',
      'боюся робити вправи неправильно при людях',
      'соціальна тривога в залі',
      'відчуваю що мене засуджують',
      'занадто соромно йти',
      'як перестати зважати на інших у залі',
      'в мене зайва вага і страшно в зал',
      'ніяково тягати при людях',
      'страшно йти в зал вперше',
      'стесняюсь в зале',
      'боюсь что надо мной будут смеяться',
      'стрёмно тренироваться при всех',
      'стрьомно заходити в зал',
    ],
  },

  app_backfill: {
    ex: [
      "add yesterday's workout",
      'log a missed session',
      "i trained but didn't log it",
      'enter a workout from last week',
      'how to record an earlier session',
      'backdate a workout',
      'past session entry',
      'i forgot to track my session',
      'log a workout with a different date',
      'add a workout i did on saturday',
      'missed logging, how to add it now',
      'how do i log a session after it happened',
      'late entry for a workout',
      'retro log a session',
      'put in an old workout',
      "didn't record friday, can i add it",
      'how to add a workout that already happened',
      'log workout for a previous day',
      'where do i add past sessions',
      'backlog my workouts',
      "enter last week's training",
      'can i set the date on a session',
      'log a session i forgot',
      'how to add history manually',
      'add a finished workout after the fact',
    ],
    exUk: [
      'додати вчорашнє тренування',
      'записати пропущене в журналі тренування',
      'тренувалась але не записала',
      'внести тренування з минулого тижня',
      'як записати раніше тренування',
      'записати тренування минулою датою',
      'забув зафіксувати тренування',
      'записати тренування з іншою датою',
      'додати тренування за суботу',
      'не записав, як додати зараз',
      'як записати тренування після того як воно було',
      'внести старе тренування',
      'не записав п’ятницю, можна додати',
      'як додати тренування яке вже було',
      'тренування за попередній день',
      'де додавати минулі тренування',
      'внести тренування минулого тижня',
      'можна поставити дату тренування',
      'записати забуте тренування',
      'як вручну додати в історію',
      'добавить вчерашнюю тренировку',
      'записать тренировку задним числом',
      'как внести старую тренировку',
      'шо робити якщо забув записати тренування',
      'як закинути тренування заднім числом',
    ],
  },

  app_units: {
    ex: [
      'lbs',
      'switch to kilos',
      'pounds instead of kg',
      'change kg to lbs',
      'use imperial',
      'metric units',
      'the gym machines are in pounds',
      'set one exercise to pounds',
      'unit settings',
      'display in lbs',
      'how to show kilograms',
      'can i track in pounds',
      'my dumbbells are in lb',
      'per exercise units',
      'cable stack in pounds, rest kg',
      'change the weight unit',
      "i'm american, i use pounds",
      'how to go back to kg',
      'where do i switch lb and kg',
      'set units',
      'kg to pounds setting',
      'can the app do pounds',
      'units for one machine',
      'measure weight in lbs',
      'change units',
    ],
    exUk: [
      'фунти',
      'перейти на кілограми',
      'фунти замість кг',
      'поміняти кг на фунти',
      'метрична система',
      'тренажери в залі у фунтах',
      'одна вправа у фунтах',
      'одиниці виміру',
      'показувати в фунтах',
      'як показувати кілограми',
      'можна записувати у фунтах',
      'гантелі в мене у фунтах',
      'одиниці для окремої вправи',
      'блок у фунтах, решта в кг',
      'змінити одиницю ваги',
      'як повернути кілограми',
      'де перемикати фунти й кг',
      'встановити одиниці',
      'додаток вміє у фунти',
      'одиниці для одного тренажера',
      'кг або фунти',
      'переключить на килограммы',
      'фунты вместо килограммов',
      'где поменять единицы веса',
      'шо зробити щоб було в кг',
    ],
  },

  app_language: {
    ex: [
      'language',
      'english please',
      'speak ukrainian',
      'switch the app to english',
      'i want the app in ukrainian',
      'change the language to english',
      'how to change language in settings',
      "i don't understand ukrainian",
      'english version',
      'ukrainian version',
      'can you reply in ukrainian',
      'can you talk in english',
      'wrong language',
      'the app language changed',
      'where do i pick the language',
      'language toggle',
      'switch to ua',
      'switch language',
      'translate the app to english',
      'why is everything in ukrainian',
      'can i have the app in english',
      'language option',
      'talk to me in english',
      'i prefer english',
      'english mode',
    ],
    exUk: [
      'мова',
      'англійською будь ласка',
      'говори українською',
      'перемкнути додаток на англійську',
      'хочу додаток українською',
      'поміняти мову на англійську',
      'як змінити мову в налаштуваннях',
      'не розумію англійської',
      'українська версія',
      'англійська версія',
      'можеш відповідати англійською',
      'не та мова',
      'мова в додатку змінилась',
      'де вибрати мову',
      'перемикач мови',
      'змінити мову',
      'чому все англійською',
      'можна додаток українською',
      'говори зі мною українською',
      'мені зручніше українською',
      'поменять язык',
      'переключи на русский',
      'можно на английском',
      'шо зробити щоб було англійською',
      'давай українською',
    ],
  },

  app_delete: {
    ex: [
      'delete set',
      'remove set',
      'how do i remove a set i logged wrong',
      'trash a workout',
      'delete this session',
      'undo last set',
      'erase an exercise',
      'wrong weight logged, delete it',
      'how to get rid of a set',
      'remove a session from history',
      'delete an exercise from today',
      'i accidentally logged a set',
      'can i restore a deleted set',
      'delete the whole session',
      "where's the bin icon",
      'delete workout',
      'remove a logged exercise',
      'how do i wipe a workout',
      'i logged the same workout twice',
      'cancel a set',
      'delete a mistake set',
      'clear a set',
      'how to delete old sessions',
      'remove extra set',
      'the set is wrong, remove it',
    ],
    exUk: [
      'видалити сет',
      'прибрати сет',
      'як видалити помилковий підхід',
      'стерти тренування',
      'видалити цю сесію',
      'скасувати останній сет',
      'стерти вправу',
      'записав не ту вагу, видалити',
      'як позбутися сету',
      'прибрати тренування з історії',
      'видалити вправу з сьогоднішнього тренування',
      'випадково записав підхід',
      'відновити видалений сет',
      'видалити все тренування повністю',
      'де кошик',
      'видалити вправу',
      'двічі записала тренування',
      'скасувати підхід',
      'видалити зайвий сет',
      'як видаляти старі тренування',
      'удалить сет',
      'удалить упражнение',
      'как удалить лишний подход',
      'шо робити якщо записав зайвий сет',
      'сет неправильний, видали',
    ],
  },

  app_playbook: {
    ex: [
      'playbook',
      'workout templates',
      'routines',
      'how do i save my workout as a template',
      'templates in the app',
      'start a saved routine',
      'my playbook days',
      "reuse last week's workout",
      'can i load my regular leg day',
      'where is the playbook',
      'how does the app learn my routine',
      'quick start my usual workout',
      'do i have to build my workout every time',
      'saved routine',
      'start my pull day from playbook',
      'how to use playbook',
      'repeat a workout',
      'workout presets',
      'the app remembers my usual days?',
      'how do i make a template',
      'open my routine',
      'load a previous session',
      'start the same workout as last time',
      'my routines list',
      'template workouts',
    ],
    exUk: [
      'плейбук',
      'шаблони тренувань',
      'рутини',
      'як зберегти тренування як шаблон',
      'шаблони в додатку',
      'запустити збережену рутину',
      'мої дні в плейбуку',
      'повторити тренування минулого тижня',
      'завантажити мій звичайний день ніг',
      'де плейбук',
      'як додаток вивчає мою рутину',
      'швидко запустити звичне тренування',
      'треба кожен раз збирати тренування',
      'збережена рутина',
      'запустити день тяги з плейбука',
      'як користуватися плейбуком',
      'повторити тренування',
      'заготовки тренувань',
      'як зробити шаблон',
      'відкрити мою рутину',
      'шаблоны тренировок',
      'как повторить прошлую тренировку',
      'где сохраненные тренировки',
      'шо таке playbook',
      'запустити те саме тренування що минулого разу',
    ],
  },

  app_streak_rules: {
    ex: [
      'streak rules explained',
      'how streaks work',
      'does resting break the streak',
      'what keeps my streak alive',
      'rules for the streak',
      'sick days and streak',
      'does walking count for my streak',
      'what resets a streak',
      'why did my streak reset',
      'does logging cardio save the streak',
      'deload week and streak',
      'vacation and streak',
      'do rest days count toward the streak',
      'what counts as a streak day',
      'will skipping a day end my streak',
      'streak explained',
      'how do i keep my streak going',
      'does an activity keep the streak',
      'does being ill reset the streak',
      'how does the app count streaks',
      'planned break and streak',
      'does a yoga session count for the streak',
      'my streak broke for no reason',
      'how is a streak day defined',
      'does the streak need a workout every day',
    ],
    exUk: [
      'за якими правилами рахується серія',
      'як працюють серії',
      'відпочинок ламає серію',
      'що зберігає серію',
      'правила стріку',
      'лікарняні і серія',
      'ходьба рахується в серію',
      'що скидає серію',
      'чому серія обнулилась',
      'запис кардіо зберігає серію',
      'розвантажувальний тиждень і серія',
      'відпустка і серія',
      'дні відпочинку рахуються в серію',
      'що рахується як день серії',
      'пропущу день і серія закінчиться',
      'як зберегти серію',
      'хвороба обнуляє серію',
      'як додаток рахує серію',
      'йога рахується в серію',
      'серія зламалась без причини',
      'правила стріку в додатку',
      'что сбрасывает серию',
      'болезнь ломает серию',
      'як не злити стрік',
      'шо треба щоб серія не згоріла',
    ],
  },

  app_sleep_tracking: {
    ex: [
      'sleep tracking',
      'track sleep',
      'auto sleep',
      'how do i add a night of sleep',
      'sleep schedule setup',
      'record my night',
      'the app logged my sleep wrong',
      'fix last night',
      'can spotter record sleep on its own',
      'how to log bedtime',
      'enable automatic sleep tracking',
      'change my sleep entry',
      'sleep log',
      "where's sleep in the app",
      'set bedtime and wake time',
      'my sleep entry is wrong',
      'how to edit a night in history',
      'auto log my sleep',
      'start tracking sleep in the app',
      'sleep settings',
      'does the app know when i sleep',
      'record sleep hours',
      'how do i stop a night',
      'adjust my sleep log',
      "log last night's sleep",
    ],
    exUk: [
      'трекінг сну',
      'відстежувати сон',
      'автосон',
      'як додати ніч сну',
      'налаштувати розклад сну',
      'записати ніч',
      'додаток неправильно записав сон',
      'виправити минулу ніч',
      'spotter сам записує сон',
      'як записати час відбою',
      'увімкнути автоматичне відстеження сну',
      'змінити запис сну',
      'журнал сну',
      'де сон у додатку',
      'задати час сну і підйому',
      'запис сну неправильний',
      'як відредагувати ніч в історії',
      'почати відстежувати сон',
      'налаштування сну',
      'записати години сну',
      'записать сон',
      'автозапись сна',
      'как исправить запись сна',
      'шо робити якщо сон записався криво',
      'як логати сон',
    ],
  },

  do_you_lift: {
    ex: [
      'you lift bro',
      'do you ever work out',
      "what's your bench",
      "what's your max deadlift",
      'can you squat',
      'you train yourself',
      'how much can you lift',
      'do you have muscles',
      'do you hit legs',
      'you do cardio',
      "what's your split",
      'bet you never lifted',
      'have you ever lifted weights',
      'are you jacked',
      'you ever touched a barbell',
      'what do you deadlift',
      'do you skip leg day',
      'do you practice what you preach',
      'can you even do a push up',
      'how big are your arms',
      'do you go to a gym',
      'do you do pull ups',
      'atlas, do you lift',
      "what's your pr",
      'do robots lift',
    ],
    exUk: [
      'ти сам тренуєшся',
      'а ти качаєшся',
      'скільки ти жмеш лежачи',
      'яка в тебе станова',
      'ти присідаєш',
      'скільки ти можеш підняти',
      'в тебе є м’язи',
      'ти качаєш ноги',
      'ти робиш кардіо',
      'а в тебе який спліт',
      'ти хоч раз піднімав залізо',
      'ти накачаний',
      'ти пропускаєш день ніг',
      'ти віджимаєшся',
      'які в тебе біцухи',
      'ти ходиш у качалку',
      'а сам то тягаєш',
      'атлас, ти качаєшся',
      'який в тебе рекорд',
      'роботи качаються',
      'а ты сам качаешься',
      'сколько ты жмешь',
      'ты ходишь в зал',
      'шо, сам то тренуєшся',
      'ти колись штангу тримав',
    ],
  },

  compliment: {
    ex: [
      "you're great",
      'awesome coach',
      "you're a legend",
      'love this coach',
      "you're brilliant",
      "atlas you're the goat",
      "you're the man",
      'super helpful coach',
      "you're killing it",
      'great job coach',
      "you're so good at this",
      'best trainer',
      "you're a genius",
      'i like you',
      "you're fantastic",
      'amazing coach',
      'you really know your stuff',
      "you're the goat",
      'top coach',
      "i'm a fan of yours",
      "you're incredible",
      "you're pretty cool",
      'smart bot',
      'love the coaching',
      'well done atlas',
    ],
    exUk: [
      'ти класний',
      'чудовий тренер',
      'ти легенда',
      'обожнюю тебе',
      'ти геній',
      'атлас ти топчик',
      'ти красава',
      'дуже корисний тренер',
      'ти бомбезний',
      'молодчина',
      'ти в цьому шариш',
      'найкращий тренер у світі',
      'ти мені подобаєшся',
      'ти неймовірний',
      'класно тренуєш',
      'ти шариш',
      'ти розумник',
      'я твій фанат',
      'ти огонь',
      'ти крутий тренер',
      'ты гений',
      'ты супер',
      'обожаю тебя',
      'атлас, ти найкращий',
      'ти чудовий',
    ],
  },

  sorry: {
    ex: [
      'sorry about that',
      'apologies',
      "i'm really sorry",
      'sorry i skipped',
      'sorry i was rude',
      'sorry, my fault',
      'pardon me',
      'sorry for missing the workout',
      'sorry coach',
      "didn't mean to be mean",
      'sorry i was lazy this week',
      'sorry for not training',
      'i owe you an apology',
      'sorry i bailed',
      'i apologise',
      'sorry, forgot to train',
      'sorry for yelling',
      'please forgive me',
      'sorry dude',
      'i feel bad, sorry',
      'sry',
      'sorry for the attitude',
      'my mistake',
      'sorry for the silence',
      'sorry i disappeared',
    ],
    exUk: [
      'вибач за це',
      'мені дуже шкода',
      'вибач що пропустила',
      'вибач за грубість з мого боку',
      'вибач, моя вина',
      'вибач що не прийшов на тренування',
      'вибач тренер',
      'не хотів грубити',
      'вибач що лінувався цього тижня',
      'вибач що не тренувалась',
      'вибач що злився',
      'пробач будь ласка',
      'вибач друже',
      'соррі',
      'вибачаюсь',
      'вибач що зник',
      'вибач що накричав',
      'сорі, моя помилка',
      'вибач, забув потренуватися',
      'прошу вибачення',
      'извините',
      'прости пожалуйста',
      'извини что пропал',
      'сорян, шо наговорив',
      'вибач що мовчала',
    ],
  },
};
