import type { Kb } from './types';

export const KB_C: Kb = {
  app_log_set: {
    ex: [
      'how do i log a set',
      'how do i record a set in the app',
      'where do i enter my reps and weight',
      'how to save a set',
      'i did 8 reps at 60 kg, how do i put that in',
      'how do i add a set to my workout',
      'log set',
      'where is the log button',
      'how to write down my sets during a session',
      'can i record sets while i train',
      'the set i just did, how do i save it',
      'how does logging work in spotter',
      'where do i type the weight i lifted',
      'how do i mark a set as done',
      'enter reps in the app',
      'whats the fastest way to log sets between exercises',
    ],
    exUk: [
      'як записати сет',
      'як записати підхід у додатку',
      'де вводити повтори й вагу',
      'як зберегти підхід',
      'зробив 8 по 60 кг, як це внести',
      'як додати сет у тренування',
      'де кнопка записати',
      'як записувати підходи під час тренування',
      'куди вписувати вагу',
      'як відмітити що підхід зроблено',
      'як внести повтори',
      'як тут записувати сети',
      'як заносити підходи в журнал',
      'як сохранить подход',
      'как записать сет в приложении',
      'шо нажимать щоб записати підхід',
    ],
    facets: {
      how: [
        'In the session, set the reps and weight on the exercise card and tap Log.',
        'У тренуванні вистав повтори й вагу на картці вправи й натисни «Записати».',
      ],
      where: [
        'On the exercise card inside an active session.',
        'На картці вправи в активному тренуванні.',
      ],
      what: [
        'Logging a set saves its reps and weight to the session, and the rest timer starts by itself.',
        'Запис сету зберігає повтори й вагу в тренуванні, а таймер відпочинку стартує сам.',
      ],
      when: [
        'Right after you finish the set, during the session; the rest timer starts on Log.',
        'Одразу після сету, під час тренування; таймер відпочинку стартує після запису.',
      ],
    },
  },

  app_rest_timer: {
    ex: [
      'how do i change the rest timer',
      'set rest timer to 2 minutes',
      'rest timer settings',
      'how do i make the timer vibrate',
      'can the rest timer make a sound',
      'turn off the timer sound',
      'timer doesnt beep',
      'how do i change the rest time between sets in the app',
      'keep the screen on during rest timer',
      'where do i set the rest target',
      'can i get a notification when rest is over',
      'how do i test the timer alert',
      'rest timer too short, how to adjust',
      'vibration on timer',
      'how to configure the rest countdown',
      'i want a longer rest timer',
    ],
    exUk: [
      'як змінити таймер відпочинку',
      'постав таймер на 2 хвилини',
      'налаштування таймера',
      'як зробити щоб таймер вібрував',
      'таймер може подавати звук',
      'вимкнути звук таймера',
      'таймер не пищить',
      'як змінити час відпочинку в таймері',
      'щоб екран не гас під час таймера',
      'де задати ціль відпочинку',
      'сигнал коли закінчився відпочинок',
      'як перевірити сигнал таймера',
      'таймер закороткий, як поміняти',
      'вібрація на таймері',
      'как настроить таймер отдыха',
      'шо з таймером, не чути звуку',
    ],
    facets: {
      how: [
        'Tap the rest ring during a session to set the rest target and choose alerts: vibrate, sound, keep screen on or a notification.',
        'Під час тренування тапни коло відпочинку, щоб задати ціль і вибрати сигнали: вібрація, звук, не гасити екран чи нотифікація.',
      ],
      where: [
        'The rest ring on the session screen opens the timer settings.',
        'Коло відпочинку на екрані тренування відкриває налаштування таймера.',
      ],
      what: [
        'The rest timer counts your rest after each logged set and alerts you when the target is reached; Test the alert shows what you will get.',
        'Таймер відпочинку рахує паузу після кожного записаного сету й сигналить, коли ціль досягнута; «Перевірити сигнал» покаже, що буде.',
      ],
    },
  },

  app_notifications: {
    ex: [
      'how do i turn on notifications',
      'enable push notifications',
      'i dont get notifications',
      'notifications not working on iphone',
      'why no push on my iphone',
      'how do i get alerts from the app',
      'can spotter send me notifications',
      'notifications on android',
      'allow notifications',
      'how to get a notification when rest ends',
      'no notifications at all',
      'do i need to install the app for notifications',
      'add to home screen for notifications',
      'turn on push',
      'how do i enable app alerts on ios',
    ],
    exUk: [
      'як увімкнути нотифікації',
      'як увімкнути сповіщення',
      'не приходять сповіщення',
      'на айфоні не працюють нотифікації',
      'чому нема пушів на iphone',
      'як отримувати сповіщення від додатку',
      'додаток може надсилати пуші',
      'дозволити сповіщення',
      'нотифікації на андроїді',
      'треба ставити на головний екран щоб були сповіщення',
      'пуши не приходять',
      'як включити уведомления',
      'не приходят уведомления на айфон',
      'як включити пуш',
      'чого не пілікають сповіщення',
    ],
    facets: {
      how: [
        'Turn them on in the rest settings or when Atlas asks. On iPhone, first add Spotter to the Home Screen via Share, then Add to Home Screen.',
        'Увімкни в налаштуваннях відпочинку або коли Atlas запитає. На iPhone спершу додай Spotter на головний екран: Поділитися → На початковий екран.',
      ],
      why: [
        'On iPhone, Apple allows web-app notifications only for apps added to the Home Screen.',
        'На iPhone Apple дозволяє нотифікації вебдодатків лише з головного екрана.',
      ],
      where: [
        'In the rest settings, opened from the rest ring during a session.',
        'У налаштуваннях відпочинку, які відкриваються з кола відпочинку під час тренування.',
      ],
    },
  },

  app_turn_off: {
    ex: [
      'how do i turn off atlas',
      'disable the coach',
      'i dont want atlas',
      'how to remove atlas',
      'stop atlas',
      'can i hide the chatbot',
      'switch off the ai coach',
      'get rid of atlas',
      'how do i disable you',
      'turn you off',
      'i want to use the app without the coach',
      'how to deactivate atlas',
      'atlas off',
      'where do i disable the assistant',
      'can i switch the bot off',
    ],
    exUk: [
      'як вимкнути атлас',
      'вимкнути тренера',
      'не хочу атласа',
      'як прибрати атлас',
      'видалити атлас',
      'можна сховати чатбот',
      'відключити ші тренера',
      'як тебе вимкнути',
      'як позбутися атласа',
      'хочу користуватися без тренера',
      'де відключити асистента',
      'атлас вимкнути',
      'как отключить атлас',
      'выключить бота',
      'як зробити щоб атлас не заважав',
    ],
    facets: {
      how: [
        'Gear icon, top right, then Turn Atlas off.',
        'Шестірня вгорі праворуч → «Вимкнути Atlas».',
      ],
      where: [
        'Behind the gear icon in the top-right corner.',
        'За шестірнею у правому верхньому куті.',
      ],
      what: [
        'Atlas stays in the strip after you turn it off, so you can switch it back on.',
        'Після вимкнення Atlas лишається в стрічці, тож його можна ввімкнути знову.',
      ],
    },
  },

  app_role: {
    ex: [
      'are you my main coach',
      'can you be my extra coach',
      'i have a human coach',
      'my coach writes my plan, what do you do',
      'switch you to extra coach',
      'i want a second opinion only',
      'can you just watch and comment',
      'make atlas my main coach',
      'i want you to write my programme',
      'what is the difference between main and extra coach',
      'i already have a personal trainer',
      'do you replace my coach',
      'can i keep my own plan and use you',
      'change coach role',
      'what role do you have',
    ],
    exUk: [
      'ти мій основний тренер',
      'можеш бути додатковим тренером',
      'у мене є живий тренер',
      'мій тренер пише план, а ти що робиш',
      'перемкнути тебе на додаткового',
      'хочу лише другу думку',
      'можеш просто спостерігати й коментувати',
      'зробити атлас основним тренером',
      'хочу щоб ти писав мені програму',
      'чим основний відрізняється від додаткового тренера',
      'у мене вже є персональний тренер',
      'ти заміниш мого тренера',
      'можна лишити свій план і користуватися тобою',
      'змінити роль тренера',
      'ты мой основной тренер',
    ],
    facets: {
      what: [
        'As main coach Atlas writes your programme; as extra coach your plan stays and Atlas only watches and comments.',
        'Як основний тренер Atlas пише програму; як додатковий — план лишається твоїм, Atlas лише спостерігає й коментує.',
      ],
      how: [
        'Switch between main and extra coach in settings.',
        'Перемикай основного й додаткового тренера в налаштуваннях.',
      ],
      who: [
        "Extra coach suits people whose plan is run by someone else; main coach suits those who want Atlas's programme.",
        'Додатковий — для тих, чий план веде хтось інший; основний — для тих, хто хоче програму від Atlas.',
      ],
      where: ['In settings.', 'У налаштуваннях.'],
    },
  },

  app_injury_log: {
    ex: [
      'how do i log an injury',
      'add injury',
      'where do i record an injury',
      'i hurt my shoulder, how do i tell the app',
      'record injury in the app',
      'where is the injury section',
      'mark my knee as injured',
      'can i add an injury so you avoid those muscles',
      'how do i let atlas know about my injury',
      'injury tracking',
      'how to save an injury in my profile',
      'enter an injury',
      'where can i note my back injury',
      'tell the app my wrist is injured',
      'log injured area',
    ],
    exUk: [
      'як записати травму',
      'додати травму',
      'де травми в додатку',
      'пошкодив плече, як це вказати в додатку',
      'де розділ травм',
      'відмітити коліно як травмоване',
      'можна додати травму щоб ти берег ці м’язи',
      'як повідомити атлас про травму',
      'як внести травму в профіль',
      'де вказати травму спини',
      'записати травмовану ділянку',
      'як додати травму зап’ястя',
      'как добавить травму',
      'где записать травму',
      'куди вписати шо в мене травма',
    ],
    facets: {
      how: [
        'Profile menu, then Injury, or from a pain answer in the chat. Pick the injured area.',
        'Меню профілю → «Травми» або з відповіді про біль у чаті. Обери ділянку.',
      ],
      where: ['In the profile menu under Injury.', 'У меню профілю, розділ «Травми».'],
      why: [
        'Once an area is logged, Atlas protects those muscles and brings them back in stages.',
        'Коли ділянку записано, Atlas захищає ці м’язи й повертає їх поетапно.',
      ],
    },
  },

  are_you_ai: {
    ex: [
      'are you ai',
      'are you a real person',
      'are you a bot',
      'am i talking to a robot',
      'is this a human',
      'are you real',
      'is there a person behind atlas',
      'are you artificial intelligence',
      'are you a language model',
      'are you just code',
      'is someone typing these answers',
      'are you alive',
      'bot or human',
      'are you a real coach',
    ],
    exUk: [
      'ти бот',
      'ти людина',
      'ти ші',
      'ти штучний інтелект',
      'ти справжній',
      'я говорю з роботом',
      'хто відповідає, людина чи програма',
      'ти мовна модель',
      'ти просто код',
      'за атласом стоїть людина',
      'ти живий',
      'бот чи людина',
      'ты бот',
      'ты живой человек',
    ],
  },

  who_made: {
    ex: [
      'who made you',
      'who built you',
      'who created you',
      'who developed atlas',
      'who is behind this bot',
      'who programmed you',
      'where do you come from',
      'why are you called atlas',
      'who wrote you',
      'whats the story behind your name',
      'who designed you',
      'which company made you',
      'who is your creator',
      'where does the name atlas come from',
    ],
    exUk: [
      'хто тебе створив',
      'хто тебе зробив',
      'хто тебе написав',
      'хто розробив атлас',
      'хто стоїть за цим ботом',
      'хто тебе запрограмував',
      'звідки ти взявся',
      'чому тебе звати атлас',
      'хто твій творець',
      'звідки назва атлас',
      'хто тебе придумав',
      'яка компанія тебе зробила',
      'кто тебя создал',
      'кто тебя сделал',
    ],
  },

  motivate: {
    ex: [
      'motivate me',
      'i need motivation right now',
      'give me a pep talk',
      'push me to go to the gym',
      'inspire me',
      'i dont feel like training, talk me into it',
      'say something to get me going',
      'hype me up',
      'convince me to train today',
      'i need a kick in the butt',
      'get me off the couch',
      'fire me up before my session',
      'give me a reason to train',
      'lazy today, motivate me',
      'cheer me on',
    ],
    exUk: [
      'мотивуй мене',
      'дай мотивацію',
      'надихни',
      'підбадьор мене',
      'не хочу тренуватися, вмов мене',
      'скажи щось щоб я пішов у зал',
      'дай пенделя',
      'запали мене перед тренуванням',
      'дай причину потренуватися',
      'лінь сьогодні, мотивуй',
      'підніми мене з дивана',
      'потрібен поштовх',
      'мотивируй меня',
      'дай мотивации',
      'штовхни мене в зал',
    ],
  },

  joke: {
    ex: [
      'tell me a joke',
      'make me laugh',
      'say something funny',
      'got any gym jokes',
      'joke please',
      'tell me a fitness joke',
      'cheer me up with a joke',
      'know any good jokes',
      'one more joke',
      'something funny about leg day',
      'funny gym joke',
      'i need a laugh',
      'entertain me with a joke',
      'tell me a dad joke about lifting',
    ],
    exUk: [
      'розкажи жарт',
      'розсміши мене',
      'скажи щось смішне',
      'є жарти про зал',
      'анекдот',
      'розкажи анекдот про спорт',
      'пожартуй',
      'ще один жарт',
      'щось смішне про день ніг',
      'хочу посміятися',
      'знаєш смішні жарти',
      'розкажи анекдот',
      'расскажи шутку',
      'рассмеши меня',
    ],
  },

  insult: {
    ex: [
      'fuck you',
      'shut up',
      'i hate you',
      'you idiot',
      'piece of shit',
      'screw you',
      'fuck off',
      'you are an idiot',
      'shut the hell up',
      'go to hell',
      'i hate this bot',
      'fucking bot',
      'stfu',
      'you suck',
    ],
    exUk: [
      'заткнись',
      'ненавиджу тебе',
      'ідіот',
      'відвали',
      'іди в сраку',
      'сука',
      'бля ну ти й ідіот',
      'пішов ти',
      'замовкни',
      'ненавиджу цього бота',
      'ти мене бісиш',
      'отвали',
      'заткнись уже',
      'йди геть',
    ],
  },

  done: {
    ex: [
      'done',
      'finished',
      'did it',
      'i trained',
      'workout done',
      'i trained today',
      'just finished',
      'all done',
      'session done',
      'finished my workout',
      'trained',
      'done for today',
      'just did it',
      'gym done',
    ],
    exUk: [
      'зробив',
      'готово',
      'закінчив',
      'потренувався',
      'відтренувався',
      'тренування зроблено',
      'закінчив тренування',
      'все, зробив',
      'сьогодні потренувалась',
      'відпахав',
      'зал зроблено',
      'готово на сьогодні',
      'я все',
      'потренировался',
    ],
  },

  bye: {
    ex: [
      'bye',
      'see you',
      'see you later',
      'later',
      'goodbye',
      'catch you later',
      'gotta go',
      'bye atlas',
      'talk later',
      'see ya',
      'ok bye',
      'im off',
      'cya',
      'see you tomorrow',
    ],
    exUk: [
      'бувай',
      'до зустрічі',
      'па',
      'па-па',
      'до побачення',
      'ну все, бувай',
      'побіг',
      'бувай атлас',
      'до завтра',
      'пока',
      'давай, бувай',
      'мені пора',
      'до скорого',
      'всьо, па',
    ],
  },

  how_are_you: {
    ex: [
      'how are you',
      "how's it going",
      'how are you doing',
      'how are things',
      'you good',
      'how do you feel',
      'how are you today atlas',
      'hows your day',
      'all good with you',
      'how have you been',
      'how you doing',
      'hows life',
      'everything ok with you',
      'how are you holding up',
    ],
    exUk: [
      'як ти',
      'як справи',
      'як ся маєш',
      'як ти сьогодні',
      'як у тебе справи',
      'як воно',
      'все добре в тебе',
      'як настрій',
      'як поживаєш',
      'шо як',
      'как дела',
      'как ты',
      'як твій день',
      'ти як',
    ],
  },

  heaviest: {
    ex: [
      "what is the heaviest weight i've lifted",
      'my heaviest lift',
      'most weight i ever lifted',
      'whats my biggest lift',
      "heaviest thing i've done",
      "what's the most weight i moved in any exercise",
      'which lift do i go heaviest on',
      'my all time heaviest set',
      'biggest number in my log',
      "what's the max weight i've ever had on the bar",
      'heaviest',
      'on which exercise do i lift the most',
      'top weight overall',
      "what's my heaviest ever",
    ],
    exUk: [
      'яка найважча вага яку я піднімав',
      'моя найважча вправа',
      'найбільша вага за весь час',
      'що я найбільше підняв',
      'найважчий сет у журналі',
      'у якій вправі в мене найбільша вага',
      'максимальна вага яку я брав',
      'найважче що я робив',
      'найбільша цифра в журналі',
      'найважчий підхід',
      'самый большой вес который я поднимал',
      'шо я найважче тягав',
      'найбільша вага на грифі в мене',
      'мій рекорд по вазі серед усіх вправ',
    ],
    facets: {
      what: [
        'The single heaviest top set across every lift in your log, shown with its weight and reps.',
        'Найважчий робочий сет серед усіх вправ у журналі — з вагою й повторами.',
      ],
      how: [
        'It takes the best top set of each logged exercise and picks the one with the most weight.',
        'Береться найкращий топ-сет кожної вправи з журналу й обирається той, де вага найбільша.',
      ],
    },
  },

  favourite_lift: {
    ex: [
      "what's my favourite exercise",
      'which exercise do i do most often',
      'my most done lift',
      'what do i log the most',
      'favorite lift',
      'which exercises do i repeat most',
      'what do i train most often',
      'my top exercises by count',
      'most frequent exercise in my log',
      'which lift is my go to',
      'what exercise have i done the most times',
      'my favourite movements',
      'which lifts show up most in my history',
      'most logged exercise',
    ],
    exUk: [
      'яка моя улюблена вправа',
      'яку вправу я роблю найчастіше',
      'що я найбільше роблю',
      'що найчастіше в журналі',
      'мої топ вправи',
      'які вправи я повторюю найчастіше',
      'улюблена вправа',
      'яку вправу я робив найбільше разів',
      'що я найчастіше треную',
      'найпопулярніша вправа в мене',
      'моя коронна вправа',
      'какое мое любимое упражнение',
      'що в мене найчастіше в історії',
      'шо я постійно роблю в залі',
    ],
    facets: {
      what: [
        'Your three most logged exercises, with how many times each appears.',
        'Три найчастіші вправи в журналі й скільки разів кожна трапляється.',
      ],
      how: [
        'Exercises are ranked by how many times they appear in your finished sessions.',
        'Вправи ранжуються за тим, скільки разів вони є в завершених тренуваннях.',
      ],
    },
  },

  consistency: {
    ex: [
      'am i consistent',
      'how consistent am i',
      'how regular is my training',
      'do i train regularly',
      "how's my discipline",
      'am i disciplined enough',
      'consistency check',
      'how often did i miss weeks',
      'have i been regular lately',
      'rate my consistency',
      'is my training consistent over the last two months',
      'do i show up enough',
      'how steady is my gym routine',
      'how many weeks did i actually train',
      'how do i become more consistent',
    ],
    exUk: [
      'чи я регулярно тренуюся',
      'наскільки я стабільний',
      'як у мене з регулярністю',
      'як моя дисципліна',
      'чи я дисциплінований',
      'перевір мою регулярність',
      'скільки тижнів я пропустив',
      'чи я постійно ходжу в зал',
      'оціни мою стабільність',
      'як регулярно я тренувався останні два місяці',
      'чи достатньо я ходжу',
      'як стати регулярнішим',
      'я регулярно занимаюсь',
      'шо там з моєю дисципліною',
    ],
    facets: {
      what: [
        'Consistency here means how many of the last 8 weeks had at least 2 sessions.',
        'Регулярність тут — скільки з останніх 8 тижнів мали щонайменше 2 тренування.',
      ],
      howMuch: [
        '7 or 8 of 8 weeks with 2+ sessions counts as consistent.',
        '7–8 тижнів із 8 з 2+ тренуваннями — це регулярність.',
      ],
      why: [
        'Regular training over months drives progress more than any single great session.',
        'Регулярні тренування місяцями дають більше прогресу, ніж будь-яке одне ідеальне.',
      ],
      how: [
        'Aim for at least 2 sessions every week; fix that before changing the programme.',
        'Ціль — щонайменше 2 тренування щотижня; виправ це раніше, ніж міняти програму.',
      ],
    },
  },

  best_weekday: {
    ex: [
      'which day do i train most',
      'what days do i usually go to the gym',
      'best day for me to train',
      'on which weekdays do i work out',
      'what day of the week do i train the most',
      'my most common training day',
      'do i train more on mondays',
      'which days am i most active',
      'what days do i usually lift',
      'when in the week do i usually train',
      'my typical gym days',
      'which weekday shows up most in my log',
      'what day do i hit the gym',
      'top training days',
    ],
    exUk: [
      'в які дні я зазвичай тренуюсь',
      'який день у мене найчастіший',
      'коли я зазвичай ходжу в зал',
      'по яких днях я тренуюся',
      'в який день тижня я тренуюсь найбільше',
      'мої звичні дні тренувань',
      'я частіше тренуюсь по понеділках',
      'який мій найкращий день для залу',
      'в які дні я найактивніший',
      'по яким дням я хожу в зал',
      'які дні тижня в мене тренувальні',
      'в какие дни я тренируюсь',
      'найчастіші дні тренувань',
      'шо в мене за дні зазвичай',
    ],
    facets: {
      how: [
        'Sessions from the last 12 weeks are counted by weekday and the top three are shown.',
        'Тренування за останні 12 тижнів рахуються за днями тижня й показуються три найчастіші.',
      ],
      what: [
        'Your most frequent training weekdays over roughly the last three months.',
        'Твої найчастіші тренувальні дні тижня приблизно за останні три місяці.',
      ],
    },
  },

  rest_actual: {
    ex: [
      'how long do i actually rest between sets',
      "what's my average rest time",
      'how much do i really rest',
      'my real rest between sets',
      'how long did i rest last session',
      'am i resting too long, check my log',
      'average rest in my workouts',
      'how many minutes do i actually take between sets',
      'measure my rest times',
      'do i rest longer than planned',
      'median rest last workout',
      'how long are my breaks really',
      'what rest am i actually taking',
      'how much rest do i take on average',
    ],
    exUk: [
      'скільки я насправді відпочиваю між сетами',
      'мій середній відпочинок',
      'скільки я реально відпочиваю',
      'скільки я відпочивав минулого тренування',
      'я не задовго відпочиваю, перевір',
      'середній відпочинок у моїх тренуваннях',
      'скільки хвилин я реально беру між підходами',
      'поміряй мій відпочинок',
      'я відпочиваю довше ніж планую',
      'медіана відпочинку',
      'які в мене реальні паузи',
      'сколько я на самом деле отдыхаю',
      'скільки я в середньому стою між підходами',
      'скільки я насправді сиджу між сетами',
    ],
    facets: {
      how: [
        'Rest is measured from the timestamps of sets logged live; warm-up sets are skipped and the median is shown.',
        'Відпочинок міряється за часом сетів, записаних наживо; розминкові не враховуються, показується медіана.',
      ],
      what: [
        'The median rest between working sets in your last session.',
        'Медіана відпочинку між робочими сетами в останньому тренуванні.',
      ],
      should: [
        'Log sets live during the session; sets entered afterwards give no real rest times.',
        'Записуй сети наживо під час тренування; внесені потім не дають реального часу відпочинку.',
      ],
    },
  },

  warmup_habit: {
    ex: [
      'do i warm up enough',
      'do i always warm up',
      'do i skip my warm up',
      'am i warming up properly based on my log',
      'how often do i do warm up sets',
      'do i usually warm up before lifting',
      'is my warm up habit ok',
      'check if i warm up',
      'do i do warm-ups',
      'am i skipping warmups',
      'have i been warming up lately',
      'do i start my sessions with a warm up',
      'my warm up routine, do i actually do it',
      'enough warming up in my workouts',
    ],
    exUk: [
      'чи я достатньо розминаюсь',
      'чи я завжди роблю розминку',
      'я пропускаю розминку',
      'чи я правильно розминаюсь судячи з журналу',
      'як часто я роблю розминкові підходи',
      'я зазвичай розминаюся',
      'перевір чи я розминаюсь',
      'чи я роблю розминку',
      'я розминаюсь останнім часом',
      'чи починаю я тренування з розминки',
      'достатньо розминки в моїх тренуваннях',
      'я делаю разминку',
      'шо з моєю розминкою',
      'розминку роблю чи ні',
    ],
    facets: {
      how: [
        'Your last 10 finished sessions are checked for whether they open with a warm-up.',
        'Перевіряються останні 10 завершених тренувань — чи вони починаються з розминки.',
      ],
      why: [
        'A short warm-up is cheaper than an injury and makes the first working sets feel better.',
        'Коротка розминка дешевша за травму й робить перші робочі сети легшими.',
      ],
      howMuch: ['About 5 minutes is enough.', 'Близько 5 хвилин достатньо.'],
    },
  },

  cardio_done: {
    ex: [
      'how much cardio did i do this week',
      'my cardio this week',
      'how many activities this week',
      'how many minutes of cardio this week',
      'how much did i walk this week',
      'activity minutes this week',
      'did i do enough cardio this week',
      'weekly cardio total',
      'how active was i this week',
      'cardio minutes so far this week',
      'have i hit 150 minutes this week',
      'how many walks did i log this week',
      'total activity time this week',
      'what cardio have i done this week',
    ],
    exUk: [
      'скільки кардіо я зробив цього тижня',
      'моє кардіо за тиждень',
      'скільки активностей цього тижня',
      'скільки хвилин кардіо за тиждень',
      'скільки я гуляв цього тижня',
      'хвилини активності за тиждень',
      'чи достатньо кардіо цього тижня',
      'скільки прогулянок я записав за тиждень',
      'наскільки я був активний цього тижня',
      'набрав я 150 хвилин за тиждень',
      'загальний час активності за тиждень',
      'сколько кардио за неделю',
      'шо там по кардіо за тиждень',
      'скільки руху в мене за тиждень',
    ],
    facets: {
      what: [
        'The number of finished activities in the last 7 days and their total minutes.',
        'Кількість завершених активностей за останні 7 днів і їхні загальні хвилини.',
      ],
      howMuch: [
        '150 minutes of moderate movement a week is the health baseline.',
        '150 хвилин помірного руху на тиждень — базова норма для здоров’я.',
      ],
      how: [
        'Minutes are summed from the activities you log; only finished activities count.',
        'Хвилини сумуються з записаних активностей; рахуються лише завершені.',
      ],
    },
  },

  my_gym: {
    ex: [
      'which gym do i go to most',
      'my gym',
      'which gyms do i have saved',
      'where do i train most often',
      'how many gyms have i saved',
      'what gym did i log most sessions at',
      'my main gym',
      'which gym is my usual',
      'list my gyms',
      'how many sessions at each gym',
      'do i train at more than one gym',
      'which gym have i been to the most',
      'what gyms are in my profile',
      'most visited gym',
    ],
    exUk: [
      'в якому залі я тренуюсь найчастіше',
      'мій зал',
      'які зали в мене збережені',
      'де я найчастіше тренуюсь',
      'скільки залів я зберіг',
      'який зал у мене основний',
      'мої зали',
      'скільки тренувань у кожному залі',
      'я тренуюсь у кількох залах',
      'в якому залі я був найбільше',
      'який зал мій звичний',
      'в каком зале я тренируюсь чаще',
      'список моїх залів',
      'шо за зал в мене основний',
    ],
    facets: {
      how: [
        'Sessions are counted per gym they are tied to; the gym with the most sessions is shown with the number of saved gyms.',
        'Тренування рахуються за залом, до якого прив’язані; показується зал з найбільшою кількістю та скільки залів збережено.',
      ],
      what: [
        'Your most used gym and how many gyms you have saved.',
        'Твій найчастіший зал і скільки залів збережено.',
      ],
    },
  },

  my_goal: {
    ex: [
      'what is my goal',
      "what's my current goal",
      'my physique goal',
      'did i set a goal',
      'what target am i working towards',
      'remind me of my goal',
      'how do i change my goal',
      'where do i set a goal',
      'what goal did i pick',
      'show my goals',
      'can i change my target physique',
      'what does my goal change',
      'set a new goal',
      'do i have a goal set',
    ],
    exUk: [
      'яка моя ціль',
      'яка в мене зараз мета',
      'моя ціль по фігурі',
      'чи я задав ціль',
      'до чого я йду',
      'нагадай мою ціль',
      'як змінити ціль',
      'де задати ціль',
      'яку ціль я обрав',
      'покажи мої цілі',
      'можна змінити ціль',
      'на що впливає ціль',
      'какая моя цель',
      'поставити нову ціль',
    ],
    facets: {
      what: [
        'Your physique goal and the date you set it.',
        'Твоя ціль по фігурі й дата, коли її задано.',
      ],
      where: ['In Goals.', 'У «Цілях».'],
      how: ['Pick or change it in Goals.', 'Обери або зміни її в «Цілях».'],
      why: [
        'The goal steers which muscles get more work.',
        'Від цілі залежить, які м’язи отримують більше роботи.',
      ],
    },
  },

  bw_trend: {
    ex: [
      'am i gaining weight',
      'am i losing weight',
      'my weight trend',
      'bodyweight trend over the last month',
      'is my weight going up or down',
      'how much weight have i gained',
      'how much have i lost',
      'am i putting on weight',
      'is my bodyweight dropping',
      'how has my weight changed',
      'weight change this month',
      'am i on track with my scale weight',
      'is the scale going up',
      'weight going down?',
    ],
    exUk: [
      'я набираю вагу',
      'я худну',
      'динаміка ваги',
      'вага росте чи падає',
      'скільки я набрав',
      'скільки я скинув',
      'як змінилася моя вага',
      'зміна ваги за місяць',
      'вага падає',
      'я скидаю вагу чи ні',
      'моя вага тіла за останній місяць',
      'я набираю или худею',
      'шо там з вагою, росте',
      'тренд ваги',
    ],
    facets: {
      how: [
        'The latest weigh-in is compared with one about 25+ days earlier (or the oldest one) and the change is shown in kg.',
        'Останнє зважування порівнюється з тим, що було 25+ днів тому (або найстарішим), і зміна показується в кг.',
      ],
      should: [
        'Log a few weigh-ins first; at least two are needed for a trend.',
        'Спершу запиши кілька зважувань; для тренду потрібно щонайменше два.',
      ],
      what: [
        'The change in bodyweight over roughly a month, with start and end weights.',
        'Зміна ваги тіла приблизно за місяць із початковою й кінцевою вагою.',
      ],
    },
  },

  strength_ratio: {
    ex: [
      'is my bench good',
      'is my squat strong',
      'is my deadlift decent for my weight',
      'is 100 kg bench impressive',
      'is my bench press strong for my bodyweight',
      'is my squat heavy enough',
      'is that a good deadlift',
      'how strong is my overhead press',
      'is my bench decent',
      'is my squat good compared to bodyweight',
      'is 140 on deadlift good',
      'is it a strong pull up number',
      'is my row weight good',
      'how good is my bench relative to my weight',
    ],
    exUk: [
      'чи добрий у мене жим',
      'чи сильний мій присід',
      'чи нормальна моя станова для моєї ваги',
      'це багато 100 кг жиму',
      'мій жим сильний відносно ваги тіла',
      'чи достатньо важкий мій присід',
      'це хороша станова',
      'чи сильний мій армійський жим',
      'чи нормальний у мене жим лежачи',
      'мій присід добрий порівняно з вагою',
      '140 в становій це багато',
      'чи мало я жму',
      'это нормальный жим',
      'мій жим це норм чи мало',
    ],
    facets: {
      how: [
        'Your best top set of the lift is divided by your latest bodyweight to give a bodyweight multiple.',
        'Найкращий топ-сет вправи ділиться на останню вагу тіла — виходить кратність ваги тіла.',
      ],
      where: [
        'Progress, then Standards shows your level for each lift.',
        'Рівень по кожній вправі — у Progress → Standards.',
      ],
      what: [
        'Your best set of that lift and how many times your bodyweight it is.',
        'Твій найкращий сет у вправі й у скільки разів він більший за вагу тіла.',
      ],
    },
  },

  month: {
    ex: [
      'how many sessions this month',
      'my month so far',
      'monthly summary',
      'how did i do this month',
      'how many workouts in september',
      'sets this month',
      "this month's training",
      'how many hard sets this month',
      'monthly stats',
      'how many times did i train this month',
      'month recap',
      'what have i done this month',
      'training volume this month',
      'month overview',
    ],
    exUk: [
      'скільки тренувань цього місяця',
      'мій місяць',
      'підсумок за місяць',
      'як я відтренувався цього місяця',
      'скільки сетів за місяць',
      'тренування в цьому місяці',
      'скільки робочих сетів цього місяця',
      'статистика за місяць',
      'скільки разів я тренувався цього місяця',
      'що я зробив за місяць',
      'обсяг за місяць',
      'сколько тренировок за месяц',
      'шо там за місяць',
      'місячний підсумок',
    ],
    facets: {
      what: [
        'The number of sessions and hard sets since the first day of the current calendar month.',
        'Кількість тренувань і робочих сетів від першого числа поточного календарного місяця.',
      ],
      how: [
        'Finished sessions since the 1st are counted; warm-up sets are excluded from hard sets.',
        'Рахуються завершені тренування з 1-го числа; розминкові сети не входять у робочі.',
      ],
    },
  },

  longest_session: {
    ex: [
      'what was my longest workout',
      'longest session ever',
      "shortest workout i've done",
      'my longest training session',
      'how long was my longest workout',
      'which session took the most time',
      'my shortest session',
      'longest gym session in my log',
      "what's the longest i've trained",
      'record duration workout',
      'quickest workout i did',
      'longest and shortest sessions',
      'when did i have the longest workout',
      'how long was the shortest training',
    ],
    exUk: [
      'яке моє найдовше тренування',
      'найдовше тренування',
      'найкоротше тренування',
      'скільки тривало найдовше тренування',
      'яке тренування зайняло найбільше часу',
      'моє найкоротше тренування',
      'найдовша сесія в журналі',
      'найдовше я тренувався скільки',
      'найшвидше тренування',
      'найдовше й найкоротше тренування',
      'коли було найдовше тренування',
      'самая длинная тренировка',
      'скільки хвилин було найдовше тренування',
      'найкоротша тренька',
    ],
    facets: {
      how: [
        'Duration is the time from start to finish of each logged session; the longest and shortest are shown with dates.',
        'Тривалість — від початку до кінця кожного тренування; показуються найдовше й найкоротше з датами.',
      ],
      what: [
        'Your longest and shortest finished sessions in minutes.',
        'Твої найдовше й найкоротше завершені тренування в хвилинах.',
      ],
    },
  },

  grow_muscle: {
    ex: [
      'how do i grow my chest',
      'how to build bigger shoulders',
      "my calves won't grow",
      'how to bring up my back',
      'how do i get bigger glutes',
      'tips to grow my quads',
      'my chest is not growing',
      'how to build wider lats',
      'best way to grow hamstrings',
      'how do i make my traps bigger',
      'how to build my delts',
      'bring up lagging calves',
      'how do i grow my forearms',
      'build a bigger back',
      'how to grow my abs',
      'how to build my triceps',
    ],
    exUk: [
      'як накачати груди',
      'як збільшити плечі',
      'литки не ростуть',
      'як підтягнути спину',
      'як накачати сідниці',
      'як зростити квадрицепс',
      'груди не ростуть',
      'як зробити ширшу спину',
      'як збільшити задню поверхню стегна',
      'як накачати трапеції',
      'як накачати дельти',
      'як збільшити передпліччя',
      'как накачать грудь',
      'как увеличить плечи',
      'шо робити щоб росли литки',
    ],
    facets: {
      how: [
        'Hard sets through a full range, with exercises that load the muscle in the stretch, trained about twice a week.',
        'Важкі сети в повній амплітуді, вправи з навантаженням у розтягнутій позиції, приблизно двічі на тиждень.',
      ],
      howMuch: [
        'Roughly 8–18 hard sets a week per muscle, depending on the muscle; calves and delts tolerate frequent work.',
        'Приблизно 8–18 робочих сетів на тиждень на м’яз залежно від м’яза; литки й дельти добре переносять часту роботу.',
      ],
      why: [
        'Muscles grow from progressive hard sets plus enough food and sleep; a lagging muscle usually needs more direct work.',
        'М’язи ростуть від прогресивних важких сетів плюс достатньо їжі й сну; відстаючому м’язу зазвичай бракує прямої роботи.',
      ],
    },
  },

  arms: {
    ex: [
      'how do i grow my arms',
      'how to get bigger arms',
      "my arms won't grow",
      'build bigger arms',
      'best way to grow biceps and triceps together',
      'how many sets for arms',
      'arm day tips for size',
      'how to make my arms bigger fast',
      'skinny arms, what do i do',
      'how often should i train arms to grow',
      "my arms aren't growing",
      'how to build arms',
      'arms not getting bigger',
      'how do i get big guns',
    ],
    exUk: [
      'як накачати руки',
      'як збільшити руки',
      'руки не ростуть',
      'як зробити руки більшими',
      'як наростити біцепс і трицепс разом',
      'скільки сетів на руки',
      'як часто тренувати руки щоб росли',
      'худі руки, що робити',
      'як накачати руки швидко',
      'руки не збільшуються',
      'как накачать руки',
      'руки не растут',
      'шо робити щоб руки росли',
      'як накачати банки',
    ],
    facets: {
      how: [
        'Train biceps and triceps with full range, including overhead triceps work, and eat enough.',
        'Тренуй біцепс і трицепс у повній амплітуді, включно з трицепсом з-за голови, і їж достатньо.',
      ],
      howMuch: [
        '8–14 sets each for biceps and triceps per week.',
        'По 8–14 сетів на тиждень на біцепс і на трицепс.',
      ],
      when: ['2–3 times a week.', '2–3 рази на тиждень.'],
      why: [
        'Without enough food arms tend to grow last.',
        'Без достатнього харчування руки ростуть останніми.',
      ],
    },
  },

  add_weight: {
    ex: [
      'when should i add weight',
      'how much weight should i add',
      'when to increase weight',
      'how much to add on bench',
      'increment for squats',
      'should i add 5 kg or 2.5 kg',
      'when do i go up in weight',
      'how big should my weight jumps be',
      'how much to add on dumbbells',
      'when to move up to heavier weight',
      'increase weight on deadlift how much',
      'how to know when to add weight',
      'weight increments for isolation exercises',
      'how often should i increase weight',
      'add weight or add reps',
    ],
    exUk: [
      'коли додавати вагу',
      'скільки додавати',
      'коли підвищувати вагу',
      'скільки додати на жимі',
      'крок ваги для присіду',
      'додавати 5 кг чи 2,5',
      'коли переходити на більшу вагу',
      'який крок ваги на гантелях',
      'скільки накидати на станову',
      'як зрозуміти що пора додати вагу',
      'крок ваги для ізолюючих вправ',
      'как часто повышать вес',
      'сколько добавлять вес',
      'коли вже пора накидати блінчики',
    ],
    facets: {
      when: [
        'When every set reaches the top of your rep range.',
        'Коли на всіх сетах дійшов до верху діапазону повторів.',
      ],
      howMuch: [
        '+2.5 kg on upper-body lifts, +5 kg on squats and deadlifts, +1–2 kg on dumbbells and isolation.',
        '+2,5 кг на верх тіла, +5 кг на присід і станову, +1–2 кг на гантелі й ізолюючі.',
      ],
      how: [
        'Build reps within the range first; once all sets hit the top, add the smallest step and start again at the bottom of the range.',
        'Спершу додавай повтори в діапазоні; коли всі сети на верху — додай найменший крок і почни знову знизу діапазону.',
      ],
    },
  },

  strength_vs_size: {
    ex: [
      'should i train for strength or size',
      'strength vs hypertrophy',
      'difference between training for strength and muscle',
      'how many reps for size vs strength',
      'hypertrophy or strength rep range',
      'do i need heavy weights to grow',
      "strength or size, what's better",
      'low reps or high reps for muscle',
      'can i build muscle with high reps',
      'is 5 reps good for hypertrophy',
      'training for mass vs power',
      'how do strength and hypertrophy programs differ',
      'do light weights build muscle',
      'what rep range builds the most muscle',
    ],
    exUk: [
      'тренуватися на силу чи на масу',
      'сила чи гіпертрофія',
      'різниця між тренуванням на силу і на масу',
      'скільки повторів на масу і на силу',
      'діапазон повторів для гіпертрофії',
      'чи потрібні великі ваги щоб рости',
      'маса чи сила, що краще',
      'мало повторів чи багато для м’язів',
      'чи ростуть м’язи від багатоповторки',
      'чи 5 повторів підходять для маси',
      'на силу чи на масу качатися',
      'чим силова програма відрізняється від масової',
      'на массу или на силу',
      'легкі ваги качають м’язи чи ні',
    ],
    facets: {
      what: [
        'Strength training uses 3–6 reps with long rest and frequent practice of the lift; size training uses 6–15 reps close to failure with more total sets.',
        'На силу — 3–6 повторів, довгий відпочинок і часта практика вправи; на масу — 6–15 повторів близько до відмови й більше сетів.',
      ],
      howMuch: [
        'Anything from about 5 to 30 reps builds muscle if the sets are hard.',
        'М’язи ростуть від приблизно 5 до 30 повторів, якщо сети важкі.',
      ],
      should: [
        'Choose by your goal; most lifters benefit from some heavy low-rep work plus moderate-rep volume.',
        'Обирай за ціллю; більшості корисно поєднувати трохи важкої малоповторної роботи з обсягом у середніх повторах.',
      ],
    },
  },

  periodization: {
    ex: [
      'what is periodization',
      'how does periodization work',
      'should i periodize my training',
      'what is a mesocycle',
      'how long should a training block be',
      'block periodization explained',
      'do i need training cycles',
      'how is my plan structured in blocks',
      'wave loading',
      'how many weeks per block',
      "what's a training block",
      'linear vs undulating periodization',
      'how do you periodize my programme',
      'when does my block end',
    ],
    exUk: [
      'що таке періодизація',
      'як працює періодизація',
      'чи треба періодизувати тренування',
      'що таке мезоцикл',
      'скільки має тривати блок',
      'блокова періодизація',
      'чи потрібні тренувальні цикли',
      'як мій план розбитий на блоки',
      'скільки тижнів у блоці',
      'що таке тренувальний блок',
      'лінійна чи хвиляста періодизація',
      'что такое периодизация',
      'як ти будуєш цикли',
      'коли закінчується мій цикл',
    ],
    facets: {
      what: [
        'Periodization organises training into blocks where volume or load climbs, followed by a lighter week.',
        'Періодизація — це блоки, у яких обсяг чи вага ростуть, а потім іде легший тиждень.',
      ],
      howMuch: [
        'Blocks typically last 4–8 weeks, with the last week lighter.',
        'Блоки зазвичай тривають 4–8 тижнів, останній тиждень легший.',
      ],
      why: [
        'Planned build-up and lighter weeks let fatigue clear so progress keeps coming.',
        'Плановий ріст навантаження й легші тижні дають втомі зійти, щоб прогрес тривав.',
      ],
      should: [
        'Yes for anyone past the beginner stage; beginners progress fine by simply adding weight.',
        'Так, якщо ти вже не новачок; новачки добре прогресують, просто додаючи вагу.',
      ],
    },
  },

  unilateral: {
    ex: [
      'one arm stronger than the other',
      'how to fix imbalance between sides',
      'my left leg is weaker than my right',
      'are unilateral exercises worth it',
      'single leg exercises for imbalance',
      'should i do one arm rows',
      'right side stronger, what to do',
      'how to fix a muscle imbalance left right',
      'which side should i start with on single arm work',
      'one leg weaker in squats',
      'benefits of unilateral training',
      'do split squats fix imbalances',
      'uneven strength between arms',
      'single arm press for imbalance',
    ],
    exUk: [
      'одна рука сильніша за іншу',
      'як виправити різницю між сторонами',
      'ліва нога слабша за праву',
      'чи варто робити вправи однією рукою',
      'вправи на одну ногу для дисбалансу',
      'робити тягу однією рукою',
      'права сторона сильніша, що робити',
      'як вирівняти ліву й праву сторону',
      'з якої сторони починати однобічні вправи',
      'одна нога слабша в присіді',
      'болгарські присіди виправляють дисбаланс',
      'одна рука сильнее другой',
      'перекіс між руками',
      'ліва права різна сила',
    ],
    facets: {
      how: [
        'Start with the weaker side and do the same reps with the stronger side.',
        'Починай зі слабшої сторони й роби сильною стільки ж повторів.',
      ],
      what: [
        'Unilateral work trains one side at a time: split squats, one-arm rows, single-arm presses.',
        'Однобічні вправи тренують одну сторону за раз: болгарські присіди, тяга однією рукою, жим однією.',
      ],
      why: [
        "Each side has to do its own work, so the stronger side can't cover for the weaker one.",
        'Кожна сторона працює сама, тож сильніша не підстраховує слабшу.',
      ],
    },
  },

  pullup_zero: {
    ex: [
      "i can't do a single pull up",
      'how to get my first pull up',
      "can't do pull ups at all",
      'zero pull ups, where to start',
      'how to learn pull ups from scratch',
      "i can't even do one pull up",
      'progression to first pull up',
      'how long until i can do a pull up',
      'are negatives good for learning pull ups',
      'band assisted pull ups to get the first one',
      "i hang there and can't pull myself up",
      'no pull ups yet, how do i train for it',
      'how do beginners get their first chin up',
      'cant do pull ups',
    ],
    exUk: [
      'не можу підтягнутися жодного разу',
      'як підтягнутися перший раз',
      'не підтягуюсь зовсім',
      'нуль підтягувань, з чого почати',
      'як навчитися підтягуватися з нуля',
      'не можу зробити жодного підтягування',
      'скільки часу щоб навчитися підтягуватися',
      'негативи допоможуть навчитися підтягуватися',
      'підтягування з резинкою щоб зробити перше',
      'вишу на турніку і не можу підтягнутися',
      'не могу подтянуться ни разу',
      'как научиться подтягиваться',
      'як навчитися підтягуватись дівчині',
      'жодного підтягування не виходить',
    ],
    facets: {
      how: [
        'Slow negatives (jump up, lower in about 5 seconds), band-assisted sets, pulldowns and rows.',
        'Повільні негативи (застрибнув і опускайся ~5 с), підтягування з резинкою, тяга верхнього блока й тяги.',
      ],
      when: ['Train it 2–3 times a week.', 'Тренуй це 2–3 рази на тиждень.'],
      howMuch: [
        'Most people get the first pull-up in 4–8 weeks.',
        'Більшість робить перше підтягування за 4–8 тижнів.',
      ],
    },
  },

  squat_vs_press: {
    ex: [
      'squat or leg press',
      'leg press or squat, which is better',
      'is leg press as good as squats',
      'can i replace squats with leg press',
      'squat vs leg press for quads',
      'do i need squats if i do leg press',
      'should i leg press instead of squatting',
      'which builds bigger legs, squat or leg press',
      'leg press only, no squats, ok?',
      'is the leg press enough for legs',
      'squats vs leg press for growth',
      'barbell squat or machine leg press',
      'can i skip squats and just press',
      'leg press better than squat?',
    ],
    exUk: [
      'присід чи жим ногами',
      'жим ногами чи присід, що краще',
      'жим ногами такий же хороший як присід',
      'можна замінити присід жимом ногами',
      'присід проти жиму ногами для квадрицепса',
      'чи потрібні присіди якщо роблю жим ногами',
      'що краще качає ноги, присід чи платформа',
      'тільки жим ногами без присідів, нормально',
      'жима ногами досить для ніг',
      'приседания или жим ногами',
      'присід зі штангою чи тренажер для ніг',
      'можна не присідати а жати ногами',
      'платформа замість присіду',
      'жим ногами кращий за присід',
    ],
    facets: {
      should: [
        'Do the one you progress on, or both; both grow legs.',
        'Роби ту, на якій прогресуєш, або обидві; ноги ростуть від обох.',
      ],
      what: [
        'Squats train more (back, bracing, balance); the leg press lets you push the quads harder with less fatigue.',
        'Присід вантажить більше (спина, корпус, баланс); жим ногами дає дотиснути квадрицепс з меншою втомою.',
      ],
      who: [
        'The leg press suits people who want quad volume without back loading; squats suit those who also want full-body strength and bracing.',
        'Жим ногами підходить тим, хто хоче обсяг на квадрицепс без навантаження на спину; присід — тим, кому потрібна ще й загальна сила й стабілізація.',
      ],
    },
  },

  incline_flat: {
    ex: [
      'incline or flat bench',
      'flat or incline for chest',
      'how to build upper chest',
      'is incline better than flat bench',
      'what angle for incline bench',
      'do i need incline press',
      'upper chest exercises',
      'flat bench vs incline for size',
      'my upper chest is lagging',
      'should i do incline or flat first',
      'best incline angle for upper chest',
      'can i only do incline bench',
      'upper pecs not growing',
      'is flat bench enough for chest',
    ],
    exUk: [
      'жим на похилій чи горизонтальній',
      'похилий чи горизонтальний для грудей',
      'як накачати верх грудей',
      'похилий жим кращий за горизонтальний',
      'який кут для похилої лави',
      'чи потрібен жим на похилій',
      'вправи на верх грудей',
      'верхня частина грудей відстає',
      'що робити першим, похилий чи горизонтальний',
      'найкращий кут лави для верху грудей',
      'можна робити лише похилий жим',
      'горизонтального жиму досить для грудей',
      'жим на наклонной или горизонтальной',
      'как накачать верх груди',
    ],
    facets: {
      what: [
        'Flat pressing works the chest overall and builds strength; incline pressing at about 30 degrees targets the upper chest.',
        'Горизонтальний жим працює на груди загалом і силу; похилий під кутом ~30° — на верх грудей.',
      ],
      should: ['Do both across the week.', 'Роби обидва протягом тижня.'],
      howMuch: [
        'An incline of around 30 degrees is enough for the upper chest.',
        'Для верху грудей достатньо кута близько 30°.',
      ],
    },
  },

  foam_roll: {
    ex: [
      'does foam rolling help',
      'should i foam roll',
      'is massage good for recovery',
      'foam roller before or after training',
      'is a massage gun worth it',
      'does foam rolling speed up recovery',
      'how long should i foam roll',
      'does rolling fix tight muscles',
      'sports massage for lifters',
      'can foam rolling replace stretching',
      'is myofascial release useful',
      'foam roll my quads after legs',
      'does massage help muscles grow',
      'roller for sore legs',
    ],
    exUk: [
      'чи допомагає мфр',
      'чи варто катати ролик',
      'масаж корисний для відновлення',
      'ролик до чи після тренування',
      'чи варто купувати масажний пістолет',
      'чи прискорює ролик відновлення',
      'скільки часу катати ролик',
      'ролик знімає скутість',
      'спортивний масаж для тих хто качається',
      'міофасціальний реліз це корисно',
      'масаж допомагає м’язам рости',
      'массажный ролик помогает',
      'покатати ноги на ролику після ніг',
      'чи треба ходити на масаж',
    ],
    facets: {
      what: [
        'Foam rolling and massage feel good and ease stiffness for a while.',
        'МФР і масаж приємні й на деякий час знімають скутість.',
      ],
      should: [
        "Use them if you like them, but they don't replace sleep and food.",
        'Користуйся, якщо подобається, але сон і їжу вони не замінюють.',
      ],
      howMuch: [
        'A few minutes on stiff areas is enough; the effect is short-lived.',
        'Кількох хвилин на скуті ділянки достатньо; ефект короткочасний.',
      ],
      when: [
        'Before training to loosen up or after to feel better; timing matters little.',
        'До тренування, щоб розкутися, або після, щоб стало легше; час мало впливає.',
      ],
    },
  },

  sauna_cold: {
    ex: [
      'is sauna good after lifting',
      'should i take an ice bath after training',
      'cold plunge after gym',
      'does a cold shower help recovery',
      'sauna after workout, ok?',
      'do ice baths kill gains',
      'cold water immersion and muscle growth',
      'can i go to the sauna on rest days',
      'is cold exposure good for lifters',
      'sauna before or after training',
      'does a cold plunge reduce hypertrophy',
      'should i do ice baths',
      'banya after gym',
      'cold shower after leg day',
    ],
    exUk: [
      'сауна після тренування це добре',
      'крижана ванна після залу',
      'холодний душ після тренування допомагає',
      'чи крижана ванна вбиває ріст м’язів',
      'можна в сауну у вихідний',
      'лазня після залу',
      'баня після тренування',
      'холод корисний для відновлення',
      'сауна до чи після тренування',
      'холодна вода гальмує гіпертрофію',
      'чи варто робити крижані ванни',
      'холодный душ после тренировки',
      'сауна после зала',
      'моржування і качалка',
    ],
    facets: {
      should: [
        'Sauna is fine any time; skip ice baths right after lifting if muscle growth is the goal.',
        'Сауна — будь-коли; якщо мета ріст м’язів, не роби крижану ванну одразу після силового.',
      ],
      why: [
        'Cold immersion right after lifting can blunt muscle growth.',
        'Холодове занурення одразу після силового може гальмувати ріст м’язів.',
      ],
      when: [
        'Sauna any time with water; keep cold plunges for non-lifting days.',
        'Сауна будь-коли з водою; крижані ванни — у дні без силових.',
      ],
    },
  },

  nap: {
    ex: [
      'should i take a nap',
      'is napping good for recovery',
      'how long should a nap be',
      'nap before training',
      'power nap after a bad night',
      'can a nap make up for bad sleep',
      'when is the best time to nap',
      'do naps help muscle growth',
      'is a 2 hour nap too long',
      'napping in the afternoon ok',
      'short sleep before the gym',
      'will napping ruin my night sleep',
      '20 minute nap worth it',
      'daytime nap and lifting',
    ],
    exUk: [
      'чи варто поспати вдень',
      'денний сон корисний для відновлення',
      'скільки має тривати денний сон',
      'подрімати перед тренуванням',
      'поспати вдень після поганої ночі',
      'денний сон компенсує недосип',
      'коли краще спати вдень',
      'дві години вдень це забагато',
      'подрімати після обіду нормально',
      'денний сон зіпсує нічний',
      '20 хвилин поспати має сенс',
      'дневной сон полезен',
      'поспать днем перед тренировкой',
      'покимарити вдень',
    ],
    facets: {
      howMuch: ['20–30 minutes.', '20–30 хвилин.'],
      when: [
        "Before about 3 pm so it doesn't cost you the night.",
        'До ~15:00, щоб не зіпсувати нічний сон.',
      ],
      should: [
        "Yes after a short night; a nap helps but doesn't replace a full night.",
        'Так, після короткої ночі; денний сон допомагає, але повну ніч не замінює.',
      ],
      why: [
        'A short nap restores alertness without the grogginess of deep sleep.',
        'Короткий сон повертає бадьорість без млявості від глибокої фази.',
      ],
    },
  },

  stress: {
    ex: [
      "i'm stressed, should i still train",
      'training when stressed out',
      'i feel burned out, gym or not',
      'does lifting help with stress',
      'work stress is killing my workouts',
      'should i train on a stressful day',
      'feeling anxious, is exercise good',
      'high stress and recovery',
      "i'm burned out from work, what do i do with training",
      'can stress stop muscle growth',
      'stress eating and gym',
      'nerves are shot, train or rest',
      'how does stress affect lifting',
      'exam stress and workouts',
    ],
    exUk: [
      'у мене стрес, тренуватися',
      'тренування під час стресу',
      'вигорів, іти в зал чи ні',
      'чи допомагає зал від стресу',
      'стрес на роботі заважає тренуванням',
      'тренуватися в нервовий день',
      'тривожно, спорт допоможе',
      'стрес і відновлення',
      'стрес заважає росту м’язів',
      'нерви ні к чорту, тренуватися чи відпочити',
      'як стрес впливає на силові',
      'стрес через сесію і тренування',
      'стресс, стоит ли тренироваться',
      'вигорання і качалка',
    ],
    facets: {
      should: [
        'Yes, train, but lighter than planned; if stress has lasted weeks, talk to someone.',
        'Так, тренуйся, але легше, ніж за планом; якщо стрес триває тижнями — поговори з кимось.',
      ],
      why: [
        'Exercise helps the head more than the muscles on a hard day, while heavy work adds to an already high stress load.',
        'У важкий день тренування допомагає голові більше, ніж м’язам, а важка робота додає до й так високого стресу.',
      ],
      how: [
        'Keep the session, drop the weight or sets a bit, and stop short of failure.',
        'Залиш тренування, трохи зменш вагу чи сети й не йди до відмови.',
      ],
    },
  },

  bench_alone: {
    ex: [
      'how to bench alone safely',
      'bench press without a spotter',
      'what if i fail a rep on bench alone',
      'is it safe to squat without a spotter',
      'i train alone, how do i stay safe',
      'got stuck under the bar, what to do',
      'safety pins for bench',
      'should i use collars when benching alone',
      'no spotter, heavy squats',
      'how to bail a squat',
      'lifting alone at home safety',
      'roll of shame bench',
      'how to set safeties in the rack',
      'failed bench with nobody around',
    ],
    exUk: [
      'як жати самому безпечно',
      'жим лежачи без страхувальника',
      'що робити якщо не дожав сам',
      'безпечно присідати без страховки',
      'тренуюсь сам, як не травмуватися',
      'застряг під штангою, що робити',
      'обмежувачі для жиму',
      'чи ставити замки коли жмеш сам',
      'важкі присіди без страховки',
      'як скинути штангу в присіді',
      'безпека коли тренуєшся сам вдома',
      'як виставити обмежувачі в рамі',
      'жим без страховки',
      'как жать одному безопасно',
    ],
    facets: {
      how: [
        'Bench in a rack with safety pins and without collars so you can tip the plates, or use dumbbells. Set squat safeties just below your bottom position.',
        'Жми в рамі з обмежувачами й без замків, щоб скинути млинці, або бери гантелі. У присіді став обмежувачі трохи нижче нижньої точки.',
      ],
      where: [
        'In a power rack with safeties set just below the lowest point of the lift.',
        'У силовій рамі з обмежувачами трохи нижче нижньої точки руху.',
      ],
      should: [
        'Skip collars when benching alone without safeties so you can tip the plates off.',
        'Коли жмеш сам без обмежувачів — не став замки, щоб можна було скинути млинці.',
      ],
    },
  },

  age: {
    ex: [
      'am i too old to start lifting',
      'is it too late to start at 45',
      'strength training after 50',
      'lifting after 40',
      'can older people build muscle',
      "i'm 60, is weight training safe",
      'does age slow down gains',
      'how should training change with age',
      'starting the gym late in life',
      'is it worth lifting at my age',
      'can i still get strong at 55',
      'older lifter recovery',
      'training for seniors',
      'what changes when you lift in your 40s',
    ],
    exUk: [
      'я не застарий щоб почати',
      'чи не пізно почати в 45',
      'силові після 50',
      'тренування після 40',
      'чи можуть старші люди набрати м’язи',
      'мені 60, силові безпечні',
      'вік гальмує прогрес',
      'як змінювати тренування з віком',
      'пізно почав ходити в зал',
      'чи варто качатися в моєму віці',
      'чи можна стати сильним у 55',
      'не поздно ли начинать в 50',
      'качалка після сорока',
      'я вже старий для залу',
    ],
    facets: {
      should: [
        "Yes, it's never too late; strength training matters more with age, not less.",
        'Так, ніколи не пізно; з віком силові важать більше, не менше.',
      ],
      how: [
        'Same principles with longer warm-ups and a bit more recovery between hard sessions.',
        'Ті самі принципи, довша розминка й трохи більше відновлення між важкими тренуваннями.',
      ],
      why: [
        'Muscle and bone are lost with age, and lifting is the most direct way to keep them.',
        'З віком втрачаються м’язи й кістки, а силові — найпряміший спосіб їх зберегти.',
      ],
      who: [
        'Anyone at any age; with health conditions, check with a doctor first.',
        'Будь-кому в будь-якому віці; за наявності хвороб — спершу порадься з лікарем.',
      ],
    },
  },

  gym_anxiety: {
    ex: [
      "i'm scared to go to the gym",
      'gym anxiety',
      'i feel embarrassed at the gym',
      'everyone looks at me in the gym',
      'nervous about going to the gym alone',
      'afraid people will judge me',
      "i'm too shy for the gym",
      'how to stop feeling awkward in the gym',
      'scared to use the free weights area',
      'i feel like everyone is watching me lift',
      "first time at the gym and i'm nervous",
      "embarrassed because i'm weak",
      'how to get over gym intimidation',
      'i feel out of place at the gym',
    ],
    exUk: [
      'мені страшно йти в зал',
      'соромно в залі',
      'всі дивляться на мене в залі',
      'боюся йти в зал сам',
      'боюся що мене засуджують',
      'я занадто сором’язливий для залу',
      'ніяково в залі',
      'страшно підходити до вільних ваг',
      'здається всі дивляться як я тренуюсь',
      'перший раз у залі, нервую',
      'соромно бо я слабкий',
      'мне стыдно в зале',
      'боюсь идти в качалку',
      'стрьомно в залі',
    ],
    facets: {
      how: [
        'Go at a quiet hour, have the plan open and headphones in.',
        'Приходь у тиху годину, з відкритим планом і в навушниках.',
      ],
      when: [
        'Quiet hours help; by week three it usually feels normal.',
        'Допомагають тихі години; на третій тиждень зазвичай уже звично.',
      ],
      why: [
        'Most people are focused on their own training, not on you.',
        'Більшість людей зосереджені на своєму тренуванні, а не на тобі.',
      ],
    },
  },

  app_backfill: {
    ex: [
      'i forgot to log my workout',
      'how do i add a past workout',
      'log a session from yesterday',
      'backfill a workout',
      'add an old session',
      'how to enter a workout i did last week',
      'can i log a workout after the fact',
      'forgot to log, how do i add it later',
      'add workout with a past date',
      'log past session',
      "i trained on monday but didn't record it",
      'how to change the date when logging a workout',
      'record a workout retroactively',
      'where do i log old workouts',
    ],
    exUk: [
      'забув записати тренування',
      'як додати минуле тренування',
      'записати тренування за вчора',
      'додати старе тренування',
      'як внести тренування за минулий тиждень',
      'можна записати тренування заднім числом',
      'забув записати, як додати потім',
      'додати тренування з минулою датою',
      'тренувався в понеділок але не записав',
      'як вказати дату тренування',
      'де записувати старі тренування',
      'забыл записать тренировку',
      'добавить прошлую тренировку',
      'внести тренування задніми числами',
    ],
    facets: {
      how: [
        'Today, then the ⟲ button in the bottom pill, then log a past session with its date and time.',
        '«Сьогодні» → кнопка ⟲ у нижній панелі → записати минуле тренування з датою й часом.',
      ],
      where: [
        'The ⟲ button in the bottom pill on the Today screen.',
        'Кнопка ⟲ у нижній панелі на екрані «Сьогодні».',
      ],
    },
  },

  app_units: {
    ex: [
      'how do i switch to pounds',
      'change units to kg',
      'can i use lbs',
      'change weight units',
      'kilograms or pounds setting',
      'one machine is in pounds, the rest in kg',
      'how to set lbs for one exercise',
      'switch from kg to lb',
      'units settings',
      'the app shows kg, i want pounds',
      'use pounds for a specific machine',
      'can i mix kg and lbs',
      'change to imperial units',
      'how to display weights in pounds',
    ],
    exUk: [
      'як перемкнути на фунти',
      'змінити одиниці на кілограми',
      'можна у фунтах',
      'змінити одиниці ваги',
      'кілограми чи фунти в налаштуваннях',
      'один тренажер у фунтах, решта в кг',
      'як поставити фунти для однієї вправи',
      'перейти з кг на фунти',
      'налаштування одиниць',
      'додаток показує кг, а я хочу фунти',
      'можна змішувати кг і фунти',
      'как поменять на фунты',
      'поменять единицы измерения',
      'де міняються одиниці',
    ],
    facets: {
      how: [
        "Set units account-wide in settings, or per exercise from that exercise's options.",
        'Одиниці задаються для всього акаунта в налаштуваннях або для окремої вправи в її опціях.',
      ],
      where: [
        "In settings for the whole account, or in an exercise's options for just that exercise.",
        'У налаштуваннях для всього акаунта або в опціях вправи — лише для неї.',
      ],
      what: [
        'A machine that is marked in pounds can stay in pounds while everything else is in kilograms.',
        'Тренажер із фунтами може лишитися у фунтах, поки все інше в кілограмах.',
      ],
    },
  },

  app_language: {
    ex: [
      'how do i change the language',
      'switch to english',
      'switch to ukrainian',
      'change app language',
      'can you speak english',
      'the app is in the wrong language',
      'language settings',
      'how to make the app ukrainian',
      'where is the language switch',
      'answer in english please',
      'can i use the app in english',
      'set language to english',
      'change interface language',
      'the app is in ukrainian, i need english',
    ],
    exUk: [
      'як змінити мову',
      'перемкнути на українську',
      'перемкнути на англійську',
      'змінити мову додатку',
      'можна українською',
      'додаток не тією мовою',
      'налаштування мови',
      'де перемикач мови',
      'відповідай українською',
      'як поставити англійську мову',
      'змінити мову інтерфейсу',
      'как поменять язык',
      'переключить на украинский',
      'шо зробити щоб було українською',
    ],
    facets: {
      how: [
        'Tap the flag in the top-right corner; Atlas follows the chosen language.',
        'Натисни прапорець у правому верхньому куті; Atlas підлаштується під обрану мову.',
      ],
      where: ['The flag in the top-right corner.', 'Прапорець у правому верхньому куті.'],
    },
  },

  app_delete: {
    ex: [
      'how do i delete a set',
      'remove a workout',
      'delete a session',
      'undo a set i logged by mistake',
      'how to remove an exercise from my workout',
      'delete wrong set',
      'i logged a set twice, how do i delete it',
      'how to delete a whole workout',
      'remove exercise from session',
      'can i undo deleting a set',
      'delete a workout from history',
      'i added the wrong exercise, how to remove it',
      'how to erase a session',
      'remove a duplicate workout',
    ],
    exUk: [
      'як видалити сет',
      'видалити тренування',
      'скасувати помилково записаний сет',
      'як прибрати вправу з тренування',
      'видалити неправильний підхід',
      'записав сет двічі, як видалити',
      'як видалити все тренування',
      'прибрати вправу з сесії',
      'можна скасувати видалення сету',
      'видалити тренування з історії',
      'додав не ту вправу, як прибрати',
      'как удалить тренировку',
      'как удалить подход',
      'видалити дубль тренування',
    ],
    facets: {
      how: [
        'A set or exercise: tap the bin icon next to it, with Undo right after. A whole session: open it from History, then Edit.',
        'Сет чи вправу — іконка кошика поруч, одразу є «Скасувати». Тренування повністю — відкрий в Історії → Редагувати.',
      ],
      where: [
        'The bin icon next to the set or exercise; for whole sessions, History, then Edit.',
        'Іконка кошика поруч із сетом чи вправою; для тренування — Історія → Редагувати.',
      ],
    },
  },

  app_playbook: {
    ex: [
      'what is the playbook',
      'how do templates work',
      'can i save a routine',
      'how do i start a template',
      'where are my routines',
      'what is a playbook day',
      'does the app have workout templates',
      'how does the playbook learn my days',
      'start my usual push day',
      'can i reuse a previous workout',
      'load my usual exercises in order',
      'how do i create a routine',
      'playbook explained',
      'saved workouts',
    ],
    exUk: [
      'що таке плейбук',
      'як працюють шаблони',
      'можна зберегти рутину',
      'як запустити шаблон',
      'де мої рутини',
      'що таке день у playbook',
      'чи є в додатку шаблони тренувань',
      'як плейбук вивчає мої дні',
      'запустити мій звичний день жиму',
      'можна повторити попереднє тренування',
      'як створити шаблон',
      'что такое плейбук',
      'где шаблоны тренировок',
      'збережені тренування',
    ],
    facets: {
      what: [
        'Playbook is your usual training days, learned from what you log.',
        'Playbook — твої звичні тренувальні дні, вивчені з журналу.',
      ],
      how: [
        'Start one of the days and the lifts load in your usual order.',
        'Запусти один із днів — вправи підтягнуться в твоєму звичному порядку.',
      ],
      why: [
        'It saves setting up the same session by hand each time.',
        'Це позбавляє від ручного складання того самого тренування щоразу.',
      ],
    },
  },

  app_streak_rules: {
    ex: [
      'how does the streak work',
      'what counts toward my streak',
      'does a rest day break my streak',
      'streak rules',
      'will being sick break my streak',
      'does a walk count for the streak',
      'how is the streak counted',
      'why did my streak break',
      'does cardio keep the streak',
      'planned rest and streak',
      'do i lose my streak on a deload',
      'does an activity count for streak',
      'what breaks a streak',
      'streak and holidays',
    ],
    exUk: [
      'як працює серія',
      'що рахується в серію',
      'вихідний ламає серію',
      'правила серії',
      'хвороба зламає серію',
      'прогулянка рахується в серію',
      'як рахується серія',
      'чому зламалась серія',
      'кардіо зберігає серію',
      'запланований відпочинок і серія',
      'що ламає серію',
      'як не втратити серію',
      'как считается серия',
      'серія зламається якщо я захворів',
    ],
    facets: {
      what: [
        'The streak counts days on which you trained or logged an activity.',
        'Серія рахує дні, коли було тренування або записана активність.',
      ],
      how: [
        "Each day with a session or logged activity extends it; planned rest periods and illness don't break it.",
        'Кожен день із тренуванням чи записаною активністю її подовжує; заплановані періоди відпочинку й хвороба не ламають.',
      ],
      should: [
        'Log walks or other activities; they count toward the streak.',
        'Записуй прогулянки та інші активності — вони рахуються в серію.',
      ],
    },
  },

  app_sleep_tracking: {
    ex: [
      'how do i track my sleep',
      'can the app log sleep automatically',
      'how to record sleep',
      'sleep tracking in the app',
      'set a sleep schedule',
      'automatic sleep logging',
      'how do i fix a wrong night',
      'does spotter track sleep',
      "edit last night's sleep",
      'turn on auto sleep log',
      'log my sleep',
      'where do i record how i slept',
      'sleep log settings',
      'correct my sleep entry',
    ],
    exUk: [
      'як відстежувати сон',
      'додаток може записувати сон автоматично',
      'як записувати сон',
      'відстеження сну в додатку',
      'задати розклад сну',
      'автоматичний запис сну',
      'як виправити неправильну ніч',
      'spotter відстежує сон',
      'змінити сон за минулу ніч',
      'увімкнути автозапис сну',
      'де записувати сон',
      'як відредагувати запис сну',
      'как записывать сон',
      'как отслеживать сон в приложении',
    ],
    facets: {
      how: [
        'Set a sleep schedule and turn on auto-log; nights then start and end by themselves.',
        'Задай розклад сну й увімкни автозапис — ночі починатимуться й закінчуватимуться самі.',
      ],
      where: [
        'Any night can be corrected from History.',
        'Будь-яку ніч можна виправити в Історії.',
      ],
      what: [
        'Auto-log records nights from your sleep schedule without you starting or stopping them.',
        'Автозапис фіксує ночі за твоїм розкладом сну без ручного старту й зупинки.',
      ],
    },
  },

  do_you_lift: {
    ex: [
      'do you lift',
      'do you train',
      'can you lift',
      'do you even lift',
      'do you work out',
      'how much do you bench',
      'do you go to the gym',
      'do you lift bro',
      'can you do a pull up',
      'what do you squat',
      'have you ever trained',
      'do you exercise',
      'are you strong',
      'you ever hit the gym',
    ],
    exUk: [
      'ти качаєшся',
      'ти тренуєшся',
      'а ти',
      'ти ходиш у зал',
      'скільки ти жмеш',
      'ти можеш підняти штангу',
      'ти займаєшся спортом',
      'а ти підтягуєшся',
      'ти сильний',
      'скільки ти присідаєш',
      'ты качаешься',
      'а ты тренируешься',
      'а ти сам качаєшся',
      'ти колись тренувався',
    ],
  },

  compliment: {
    ex: [
      "you're the best",
      'love you',
      'great coach',
      "you're awesome",
      'best coach ever',
      'you are amazing',
      "you're really helpful",
      'i love this bot',
      "you're so smart",
      'nice job atlas',
      'you are a great coach',
      'atlas is awesome',
      'you rock',
      'best app coach',
    ],
    exUk: [
      'ти найкращий',
      'люблю тебе',
      'класний тренер',
      'ти крутий',
      'найкращий тренер',
      'ти супер',
      'ти дуже допомагаєш',
      'ти розумний',
      'молодець атлас',
      'атлас класний',
      'ти топ',
      'ты лучший',
      'ты крутой',
      'ти просто бомба',
    ],
  },

  sorry: {
    ex: [
      'sorry',
      'my bad',
      'i apologize',
      'sorry i missed the gym',
      'sorry for skipping',
      'oops sorry',
      'sorry atlas',
      "i'm sorry",
      'my apologies',
      'sorry, i was lazy',
      'sorry for being rude',
      "sorry i didn't train",
      'forgive me',
      'so sorry',
    ],
    exUk: [
      'вибач',
      'пробач',
      'сорі',
      'перепрошую',
      'вибач що пропустив зал',
      'вибач за пропуск',
      'вибач атлас',
      'пробач що не тренувався',
      'вибач, лінувався',
      'вибач за грубість',
      'вибачте',
      'прости',
      'извини',
      'сорян',
    ],
  },
};
