export const KB_R4: Record<string, { ex: string[]; exUk: string[] }> = {
  hiit: {
    ex: [
      'are sprint intervals worth it',
      'is hiit better than steady state',
      'tabata any good for lifters',
      '30 sec on 30 sec off intervals, worth doing',
      'hiit vs liss which burns more fat',
      'do high intensity intervals mess with recovery',
      'can i do hiit on leg day',
      'whats a good interval workout on the bike',
      'is hiit enough or do i need long cardio too',
      'how long should a hiit session be',
      'is hiit bad for my knees',
      'emom sprints good for conditioning?',
      'short intense intervals vs jogging for fat loss',
      'i wanna try hiit, is it good',
      'does interval training keep my muscle better than jogging',
    ],
    exUk: [
      'чи варто робити інтервальні тренування',
      'hiit краще ніж звичайне кардіо?',
      'табата норм для тих хто качається',
      'спринти інтервалами корисні чи ні',
      'скільки хвилин має тривати hiit',
      'hiit чи повільна ходьба на доріжці що краще для жиросжигання',
      'інтервали на велотренажері це ок?',
      "чи не вб'є hiit відновлення після ніг",
      'хочу робити hiit, це взагалі корисно',
      'полезна ли интервальная тренировка',
      'hiit или обычное кардио что лучше',
      'табата для похудения работает?',
      'czy trening interwałowy jest dobry',
      'hiit czy zwykłe cardio co lepsze',
      'ile powinien trwać trening hiit',
    ],
  },
  running: {
    ex: [
      'i wanna train for a half marathon and keep lifting',
      'how do i fit runs into my lifting week',
      'should i run on leg day or rest day',
      'i run 3x a week, how do i plan my lifting around it',
      'can runners do heavy squats too',
      'best split for someone who runs and lifts',
      'running before or after lifting session',
      'marathon prep plus gym, doable?',
      'how many km per week can i run while lifting',
      'hybrid training running and strength how to start',
      'i jog most mornings, can i still hit the gym in the evening',
      'doing a 10k in spring, how to adjust my gym plan',
      'should i lift legs if i do long runs on weekends',
      'combine couch to 5k with my program?',
      'whats the best way to be a runner who also lifts',
    ],
    exUk: [
      'хочу бігати і ходити в зал одночасно, як поєднати',
      'готуюсь до напівмарафону, чи можна далі качатись',
      'бігати в день ніг чи у вихідний',
      'як вписати пробіжки в мій тижневий план',
      'бігаю зранку, а ввечері зал норм?',
      'скільки км на тиждень можна бігати якщо тренуюсь в залі',
      'біг до залу чи після',
      'гібридні тренування біг плюс штанга як почати',
      'готуюсь на 10 км, як змінити програму в залі',
      'как совмещать бег и тренажерный зал',
      'бегать до или после силовой',
      'готовлюсь к марафону можно ли качаться',
      'jak połączyć bieganie z siłownią',
      'biegać przed czy po treningu siłowym',
      'przygotowuję się do półmaratonu i chcę dalej ćwiczyć',
    ],
  },
  home_equipment: {
    ex: [
      'building a garage gym, what do i need first',
      'adjustable dumbbells or fixed set for home',
      'is a power rack worth it for my apartment',
      'what bench should i get for home',
      'home gym under 500 bucks, what to buy',
      'do i need a barbell at home or are dumbbells enough',
      'which kettlebells to buy for home training',
      'resistance bands worth buying for home?',
      'best pull up bar for a doorway',
      'rubber flooring for home gym, needed?',
      'want to train at home, what gear do i get',
      'squat stand vs full rack for small room',
      'what weight plates should i buy for my home setup',
      'minimal equipment list for working out at home',
      'cancelling my gym membership, what equipment should i buy',
    ],
    exUk: [
      'збираю зал у гаражі, що купити першим',
      'розбірні гантелі чи фіксовані для дому',
      'чи варто брати силову раму в квартиру',
      'яку лаву купити додому',
      'домашній зал на бюджет, що треба',
      'штанга вдома потрібна чи вистачить гантелей',
      'які гирі купити для дому',
      'який турнік взяти в дверний проєм',
      'хочу тренуватись вдома, яке обладнання брати',
      'что купить для домашнего спортзала',
      'какие гантели взять домой',
      'стойка для приседа дома стоит того?',
      'co kupić do domowej siłowni',
      'jakie hantle kupić do domu',
      'czy warto kupić stojak do przysiadów do mieszkania',
    ],
  },
  what_can_i_ask: {
    ex: [
      'what questions can i ask',
      'what topics do you cover',
      'give me example questions to ask you',
      'list the stuff i can ask about',
      'what kinds of things can i ask you about training',
      'can i ask you about nutrition too',
      'show me some sample questions',
      'what are you able to help me with, give examples',
      'i dont know what to ask, any ideas',
      'which questions do you understand',
      'what can i ask about my workouts',
      'suggest some questions for me',
      'what are good things to ask you',
      'help me out, what can i ask here',
      'any examples of questions you can answer',
    ],
    exUk: [
      'які питання можна тобі задавати',
      'дай приклади питань',
      'про що з тобою можна поговорити',
      'на які теми ти відповідаєш',
      'не знаю що спитати, підкажи',
      'покажи приклади що можна спитати',
      'а про харчування можна питати?',
      'які питання ти розумієш',
      'підкажи що в тебе можна запитати про тренування',
      'что у тебя можно спросить',
      'дай примеры вопросов',
      'о чём тебя можно спрашивать',
      'o co mogę cię zapytać',
      'podaj przykładowe pytania',
      'na jakie pytania odpowiadasz',
    ],
  },
  reminder: {
    ex: [
      'ping me at 7am to hit the gym',
      'set a reminder for leg day on friday',
      'remind me in 2 hours to work out',
      'can you nudge me tomorrow morning to train',
      'notify me at 5 to go lift',
      'reminder for my workout tonight please',
      'dont let me forget to train on saturday',
      'remind me every monday to go to the gym',
      'alert me at 18:00 for training',
      'put a reminder for my session tomorrow',
      'remind me to stretch tonight',
      'i need a reminder to train after work',
      'can you set a gym reminder for 6',
      'text me a reminder to lift later',
      'schedule a reminder to train at noon',
    ],
    exUk: [
      'нагадай о 7 ранку піти в зал',
      "постав нагадування на тренування в п'ятницю",
      'нагадай через дві години потренуватись',
      'не дай мені забути про тренування в суботу',
      'постав нагадалку на 18:00 на зал',
      'нагадуй кожен понеділок про тренування',
      'нагадай ввечері зробити розтяжку',
      'зроби напоминалку на завтра про трєньку',
      'нагадай після роботи піти качатись',
      'напомни мне завтра в 7 про тренировку',
      'поставь напоминание на тренировку',
      'напомни сходить в зал вечером',
      'przypomnij mi jutro o treningu',
      'ustaw przypomnienie na siłownię o 18',
      'przypomnij mi żebym poszedł na trening',
    ],
  },
  memory_show: {
    ex: [
      'show me what you have saved about me',
      'what info do you have on me',
      'what did i tell you about my goals',
      'list everything you remember about me',
      'do you remember my injuries',
      'what details have you stored about me',
      'show my profile you remember',
      'what do you think you know about me',
      'what facts have you saved from our chats',
      'do you remember what i said about my knee',
      'can i see what you remember',
      'recall what you know about me',
      'what personal info do you keep',
      'what have you learned about me so far',
      'show your notes about me',
    ],
    exUk: [
      'покажи що ти про мене зберіг',
      'яку інфу ти маєш про мене',
      'що я тобі казав про свої цілі',
      "що ти пам'ятаєш про мої травми",
      "перелічи все що ти про мене пам'ятаєш",
      'які дані про мене ти зберігаєш',
      'що ти вже про мене дізнався',
      "можна глянути що ти запам'ятав",
      'що ти знаєш про мене взагалі',
      'что ты обо мне помнишь',
      'покажи что ты про меня запомнил',
      'какую информацию обо мне хранишь',
      'co o mnie pamiętasz',
      'pokaż co o mnie zapisałeś',
      'jakie informacje o mnie masz',
    ],
  },
  memory_forget: {
    ex: [
      'delete everything you saved about me',
      'clear your memory of me',
      'erase my personal info',
      'forget what i said about my injury',
      'reset what you remember about me',
      'remove my data from your memory',
      'please stop remembering my stuff',
      'wipe my profile from your memory',
      'forget my goals i told you',
      'delete what you know about my weight',
      'can you forget everything i said',
      'clear all saved info about me',
      'i want you to forget my details',
      'purge your memory about me',
      'unlearn what i told you about myself',
    ],
    exUk: [
      'видали все що зберіг про мене',
      "очисти свою пам'ять про мене",
      'забудь що я казав про травму',
      'зітри мої дані',
      "скинь все що ти про мене запам'ятав",
      "не пам'ятай більше мої дані",
      'забудь мої цілі що я казав',
      'видали інфу про мою вагу',
      'хочу щоб ти все про мене забув',
      'удали всё что знаешь обо мне',
      'забудь что я тебе говорил',
      'сотри мои данные из памяти',
      'zapomnij wszystko o mnie',
      'usuń moje dane z pamięci',
      'wymaż co ci powiedziałem',
    ],
  },
  act_swap: {
    ex: [
      'replace bench with incline dumbbell press in my plan',
      'swap out squats for hack squats',
      'put lat pulldown in place of pull ups',
      'change my barbell curls to hammer curls',
      'switch leg extensions for lunges in my program',
      'sub in goblet squats for back squats today',
      'take out deadlifts and put rack pulls instead',
      'replace ohp with dumbbell shoulder press in my workout',
      'swap the rows in my plan for seated cable rows',
      'can you swap skullcrushers for pushdowns in my program',
      'change incline bench to machine press please',
      "in today's session swap dips for close grip bench",
      'update my plan, replace lunges with split squats',
      'exchange barbell squat for leg press in my routine',
      'i want hip thrusts instead of rdls in my plan, swap it',
    ],
    exUk: [
      'заміни в плані жим лежачи на жим гантелей на похилій',
      'постав тягу верхнього блоку замість підтягувань',
      'заміни присід на хак-присід у програмі',
      'поміняй станову на румунську в моєму плані',
      'заміни підйоми штанги на молотки',
      'сьогодні заміни віджимання на брусах на вузький жим',
      'в програмі поміняй випади на болгарські',
      'постав жим ногами замість присіду в моєму тренуванні',
      'замени жим штанги на жим гантелей в программе',
      'поменяй приседания на жим ногами',
      'поставь тягу блока вместо подтягиваний',
      'zamień wyciskanie sztangi na hantle w planie',
      'podmień przysiady na suwnicę',
      'wstaw wiosłowanie linką zamiast sztangi',
      'zmień w moim planie martwy ciąg na rumuński',
    ],
  },
  act_move: {
    ex: [
      'push my leg day to wednesday',
      "reschedule tomorrow's session to sunday",
      'can you move chest day to friday',
      'shift my workout from monday to tuesday',
      'i cant train today, move it to tomorrow',
      "bump today's session to the weekend",
      'move pull day back a day',
      'put upper body on thursday instead',
      'change my squat day from tue to wed',
      "postpone today's workout till saturday",
      "slide friday's session to saturday",
      'swap days, do legs thursday not tuesday',
      'move my next session to later in the week',
      'reschedule back day to monday please',
      'can i move this workout to another day',
    ],
    exUk: [
      'перенеси день ніг на середу',
      'посунь завтрашнє тренування на неділю',
      "перенеси груди на п'ятницю",
      'не можу сьогодні, перенеси на завтра',
      'переклади тренування з понеділка на вівторок',
      'перенеси спину на суботу',
      'хочу перенести сьогоднішню трєньку на вихідні',
      'зсунь тягу на день пізніше',
      'перенеси верх на четвер',
      'перенеси тренировку на завтра',
      'перенеси день ног на субботу',
      'сдвинь тренировку с понедельника на вторник',
      'przenieś nogi na czwartek',
      'przesuń dzisiejszy trening na jutro',
      'przenieś trening na sobotę',
    ],
  },
  act_start: {
    ex: [
      "start today's session",
      'open my workout for today',
      'begin my training now',
      'start logging my workout',
      'im at the gym, start the session',
      "fire up today's workout",
      'launch my push day',
      'start leg day now',
      'ok start the workout timer',
      "i'm ready, begin the session",
      'start tracking my training',
      "open today's plan and start",
      'begin workout please',
      'time to train, start it',
      "let's start today's training session",
    ],
    exUk: [
      'почни сьогоднішню трєньку',
      'запусти тренування',
      'я в залі, стартуй тренування',
      'відкрий і почни тренування на сьогодні',
      'погнали, стартуй тренування',
      'запусти день ніг',
      'старт тренування',
      'почни записувати моє тренування',
      'я готовий, почнімо тренування',
      'начни тренировку',
      'запусти сегодняшнюю тренировку',
      'я в зале, стартуй',
      'zacznij trening',
      'rozpocznij dzisiejszy trening',
      'włącz trening na dziś',
    ],
  },
  range_count: {
    ex: [
      'how many sessions did i log in the past 90 days',
      'count my workouts since january',
      'total workouts in the last 2 months',
      'how many days did i hit the gym last quarter',
      'number of trainings in september',
      'how many times did i work out in the past 6 weeks',
      'how many gym visits since spring',
      'workout count for the last 30 days',
      'how many trainings did i complete this year',
      'how many sessions between may and july',
      'tell me how many workouts i did in 2 months',
      'how many times was i at the gym in august',
      'did i train more than 20 times last month',
      'gym attendance count last 3 months',
      'how many workouts total since i started in march',
    ],
    exUk: [
      'скільки разів я тренувався за останні 2 місяці',
      'порахуй мої тренування з січня',
      'скільки тренувань у вересні',
      'скільки днів я був у залі за квартал',
      'скільки сесій за останні 30 днів',
      'скільки тренувань з травня по липень',
      'скільки разів ходив у зал в серпні',
      'кількість тренувань за останні 6 тижнів',
      'скільки тренувань за цей рік',
      'сколько тренировок было за последние 3 месяца',
      'сколько раз я был в зале в августе',
      'посчитай мои тренировки с января',
      'ile treningów miałem w ostatnich 3 miesiącach',
      'ile razy byłem na siłowni w sierpniu',
      'policz moje treningi od stycznia',
    ],
  },
  range_summary: {
    ex: [
      'give me a recap of the last 3 months',
      'overview of my training since june',
      'summarize my past 2 months of training',
      'how did august go for me training wise',
      'quarterly summary of my workouts',
      'what did my training look like in september',
      'review my last 6 weeks',
      'summary of my training this year so far',
      'break down what i did in the last 60 days',
      'recap of my spring training block',
      'how did my training go from may to july',
      'report on the past 3 months',
      'what have i done over the last quarter',
      'tell me about my training in july',
      'overall recap for last month please',
    ],
    exUk: [
      'підсумуй останні три місяці',
      'огляд тренувань з червня',
      'як пройшов серпень по тренуваннях',
      'зроби звіт за останні 6 тижнів',
      'що я робив у вересні в залі',
      'підсумуй мої тренування за квартал',
      'розкажи як я тренувався з травня по липень',
      'огляд за останні 2 місяці',
      'що я встиг за цей рік',
      'итоги тренировок за последние 3 месяца',
      'как прошёл июль по тренировкам',
      'сделай обзор за прошлый месяц',
      'podsumowanie ostatnich 3 miesięcy',
      'jak mi poszedł sierpień na siłowni',
      'przegląd treningów od czerwca',
    ],
  },
  range_lift: {
    ex: [
      'how has my squat gone up since march',
      'deadlift progress over the past quarter',
      'show my bench trend over the last 8 weeks',
      'did my ohp improve since summer',
      'best squat in the last 2 months',
      'how much did my bench go up since january',
      'row progress over last 3 months',
      'compare my deadlift now vs 3 months ago',
      'chart my squat since june',
      'heaviest bench in september',
      'has my pull up count improved since spring',
      'bench e1rm change over the last 6 weeks',
      'how did my incline press progress this quarter',
      'top deadlift set in august',
      'squat progression from may till now',
    ],
    exUk: [
      'як виріс присід з березня',
      'прогрес станової за квартал',
      'динаміка жиму лежачи за 8 тижнів',
      'чи покращився жим стоячи з літа',
      'найкращий присід за останні 2 місяці',
      'на скільки виріс жим з січня',
      'порівняй станову зараз і 3 місяці тому',
      'найважчий жим у вересні',
      'прогрес тяги в нахилі за останні 3 місяці',
      'прогресс жима с июня',
      'как вырос присед за последние 3 месяца',
      'лучшая становая в августе',
      'postęp w wyciskaniu od czerwca',
      'jak wzrósł mój przysiad od marca',
      'najlepszy martwy ciąg w sierpniu',
    ],
  },
  range_muscle: {
    ex: [
      'how many chest sets over the last 2 months',
      'back sets since june',
      'total leg volume in august',
      'how many sets for arms in the past 6 weeks',
      'quad sets over the last quarter',
      'shoulder volume in september',
      'how many glute sets did i do last month',
      'hamstring sets since the start of summer',
      'bicep volume in the last 30 days',
      'weekly avg sets for chest over 3 months',
      'how much back work did i do in july',
      'sets per muscle for last month',
      'did i train calves enough in the last 2 months, set count',
      'chest volume trend since spring',
      'triceps sets between may and july',
    ],
    exUk: [
      'скільки сетів на груди за останні 2 місяці',
      'сети на спину з червня',
      "об'єм на ноги в серпні",
      'скільки підходів на руки за 6 тижнів',
      'сети на плечі у вересні',
      'скільки сетів на сідниці минулого місяця',
      "об'єм на біцепс за останні 30 днів",
      'скільки підходів на спину в липні',
      "сети на кожну м'язову групу за минулий місяць",
      'сколько подходов на грудь за последние 2 месяца',
      'объём на спину с июня',
      'сколько сетов на ноги в августе',
      'ile serii na klatę w ostatnich 2 miesiącach',
      'objętość na plecy od czerwca',
      'ile serii na nogi w sierpniu',
    ],
  },
  range_bw: {
    ex: [
      'bodyweight trend over the past quarter',
      'how much weight did i lose since january',
      'show my weigh ins for the last 2 months',
      'did i gain weight since summer',
      'scale weight change over 8 weeks',
      'what was my weight in july vs now',
      'chart my body weight since june',
      'weight progress during my cut last 3 months',
      'how many kg did i put on this bulk since march',
      'average bodyweight in august',
      'weight change over the last 30 days',
      'am i lighter than 2 months ago',
      'graph of my weight since spring',
      'how has my body weight moved this year',
      'lowest weight in the last 3 months',
    ],
    exUk: [
      'як змінилась моя вага з січня',
      'графік ваги за останні 2 місяці',
      'скільки кг я скинув з літа',
      'яка була вага в липні і зараз',
      'динаміка ваги за квартал',
      'скільки набрав за масу з березня',
      'середня вага в серпні',
      'чи я легший ніж 2 місяці тому',
      'вага за останні 30 днів',
      'как изменился мой вес за 3 месяца',
      'сколько я сбросил с июня',
      'график веса за последние 2 месяца',
      'jak zmieniła się moja waga od czerwca',
      'ile schudłem w ostatnich 3 miesiącach',
      'wykres wagi z ostatnich 2 miesięcy',
    ],
  },
  compare_lifts: {
    ex: [
      'which is weaker, my bench or my squat',
      'is my ohp behind compared to my bench',
      'bench to squat ratio, is mine normal',
      'my squat vs deadlift, which one is lagging',
      'compare my deadlift with my bench',
      'is my squat too weak relative to my deadlift',
      'which of my lifts is lagging the most',
      'ohp vs bench ratio check',
      'my pull strength vs push strength, balanced?',
      'are my lifts balanced against each other',
      'squat is 120 dead is 180, is that a big gap',
      'which lift should i bring up compared to the others',
      'bench much higher than ohp, is that off',
      'is my row lagging behind my bench',
      'put my squat and deadlift side by side',
    ],
    exUk: [
      'що відстає, жим чи присід',
      'порівняй мою станову і присід',
      'співвідношення жиму і присіду в мене нормальне?',
      'чи відстає жим стоячи від жиму лежачи',
      'яка вправа в мене найбільш відстає',
      'станова 180 а присід 120, це великий розрив?',
      'порівняй жим і станову',
      'чи збалансовані мої основні вправи',
      'тяга відстає від жиму?',
      'что отстаёт, жим или присед',
      'сравни мою становую и присед',
      'соотношение жима и приседа нормальное?',
      'porównaj mój przysiad i wyciskanie',
      'co mi odstaje, martwy czy przysiad',
      'czy moje wyciskanie odstaje od przysiadu',
    ],
  },
  why_lift: {
    ex: [
      'why did you put rdls in my program',
      "what's the point of lunges in my plan",
      'why is incline bench in there',
      'why do i have face pulls in my workout',
      'why hip thrusts, whats the reason',
      'explain why deadlifts are in my routine',
      'why dips on push day',
      'whats the purpose of the rows you gave me',
      'why are there calf raises in my plan',
      'why include front squats instead of back squats',
      'why do you have me doing leg curls',
      'why is this exercise in my program, the lat pulldown',
      'reason for bulgarian split squats in my plan?',
      'why did you choose barbell rows for me',
      'what does the ohp do for me, why is it there',
    ],
    exUk: [
      'навіщо в моєму плані румунська тяга',
      'чому в програмі є випади',
      'навіщо мені жим на похилій',
      'чому ти дав мені тягу до обличчя',
      'для чого в плані ягодичний міст',
      'чому станова в моїй програмі',
      'навіщо віджимання на брусах в день жиму',
      'чому саме фронтальний присід',
      'навіщо мені підйоми на носки в плані',
      'зачем в моей программе становая',
      'почему в плане выпады',
      'для чего мне жим на наклонной',
      'po co mam martwy ciąg w planie',
      'dlaczego w moim planie są wykroki',
      'czemu dałeś mi wiosłowanie sztangą',
    ],
  },
  technique_lift: {
    ex: [
      'how do i brace for heavy squats',
      'whats proper grip width on bench',
      'my hips shoot up on deadlift, how to fix form',
      'how deep should i squat',
      'should my elbows tuck on bench press',
      'how to set up for a conventional deadlift',
      'tips to keep my back straight on rows',
      'how do i do a proper pull up',
      'bar path on the bench, whats correct',
      'how to hinge properly for rdl',
      'my knees cave on squats, form fix?',
      'how do i do hip thrusts right',
      'where should the bar sit for low bar squat',
      'cues for a better lat pulldown',
      'am i supposed to arch on bench',
    ],
    exUk: [
      'як правильно тримати спину в становій',
      'яка ширина хвату на жимі лежачи',
      'як правильно робити підтягування',
      'наскільки глибоко присідати',
      'таз підлітає на становій, як виправити техніку',
      'куди мають дивитись лікті на жимі',
      'як правильно робити румунську тягу',
      'коліна заходять всередину на присіді, що не так з технікою',
      'траєкторія грифа на жимі яка правильна',
      'как правильно делать становую',
      'техника жима лёжа подскажи',
      'как правильно приседать со штангой',
      'jak poprawnie robić przysiad',
      'technika martwego ciągu',
      'jak ustawić łokcie przy wyciskaniu',
    ],
  },
  pain_types: {
    ex: [
      'how do i tell muscle burn from joint pain',
      'whats the difference between doms and an injury',
      'is a dull ache after training normal or not',
      'stabbing pain vs soreness, how to know',
      'which kinds of pain mean i should stop',
      'good pain vs bad pain in the gym',
      'is burning during reps ok but sharp pain not?',
      'what type of pain is a warning sign',
      'achy vs sharp pain, which is worse',
      'how do i know if pain is just soreness',
      'throbbing pain vs tightness what does it mean',
      'is shooting pain down my leg a bad sign',
      'pinching pain vs muscle fatigue difference',
      'tingling or numbness while lifting, what kind of pain is that',
      'what does sharp pain mean compared to dull',
    ],
    exUk: [
      'як зрозуміти, це крепатура чи травма',
      'гострий біль і тупий у чому різниця',
      "пекучість у м'язі це нормально чи ні",
      'який біль означає що треба зупинитись',
      'хороший біль і поганий біль в залі',
      'простріл у ногу це поганий знак?',
      'ниючий біль після трені норм?',
      'як зрозуміти що це просто забитість а не травма',
      "колючий біль проти втоми м'язів, різниця",
      'как отличить крепатуру от травмы',
      'острая или тупая боль что это значит',
      'жжение в мышце это нормально?',
      'jak odróżnić zakwasy od kontuzji',
      'ostry czy tępy ból jaka różnica',
      'jaki ból oznacza że trzeba przerwać',
    ],
  },
  return_injury: {
    ex: [
      'doc cleared me after knee surgery, how do i start lifting again',
      'coming back from a torn hamstring, how to ease in',
      'first week back after a shoulder injury, what weights',
      'how long should i wait after a sprain before training',
      'how to rebuild after a herniated disc',
      'returning to the gym post injury, what % of my old weights',
      'is it ok to train again 2 weeks after a pulled muscle',
      'rehab done, how do i get back to squatting',
      'how slowly should i ramp up after an injury',
      'back to bench after a pec strain, how',
      'recovered from tennis elbow, how to return to pulling',
      'after my ankle healed, when can i do legs again',
      'coming back after injury, what should my first sessions look like',
      'how do i avoid reinjury when i start again',
      'can i train around an injury while it heals',
    ],
    exUk: [
      'лікар дозволив після операції на коліні, як повертатись у зал',
      'після розтягу задньої, як поступово починати',
      'які ваги брати перший тиждень після травми плеча',
      'скільки чекати після розтягнення перш ніж тренуватись',
      'як відновлюватись у залі після грижі',
      'реабілітацію пройшов, як повернутись до присідань',
      'як не травмуватися знову після повернення',
      'коли можна знову качати ноги після травми гомілки',
      'як поступово нарощувати вагу після травми',
      'как вернуться в зал после травмы колена',
      'когда можно тренироваться после растяжения',
      'с каким весом начинать после травмы спины',
      'kiedy mogę wrócić na siłownię po kontuzji',
      'jak wrócić do treningów po urazie barku',
      'jakie ciężary po powrocie z kontuzji',
    ],
  },
  ice_heat: {
    ex: [
      'should i put ice on my sore shoulder',
      'heating pad or ice pack for my lower back',
      'is icing after lifting good',
      'cold pack or warm compress for a tweaked knee',
      'does icing slow down muscle growth',
      'hot bath or ice bath after legs',
      'how long should i ice a sprained ankle',
      'should i use heat on a stiff neck after training',
      'ice bath worth it for recovery',
      'warm or cold on a pulled muscle',
      'when to switch from ice to heat after an injury',
      'is heat bad for a fresh injury',
      'cold plunge after workouts, good or bad',
      'put a hot water bottle on my sore hamstring?',
      'ice my elbow after pressing?',
    ],
    exUk: [
      'прикладати лід чи грілку на спину',
      'класти лід на плече після трені?',
      'холод чи тепло при розтягненні',
      "чи уповільнює лід ріст м'язів",
      'крижана ванна після ніг варто?',
      'гаряча ванна чи холодна після тренування',
      'скільки тримати лід на гомілці',
      'грілка на забиту шию допоможе?',
      'коли переходити з льоду на тепло',
      'лёд или тепло на больное колено',
      'прикладывать лёд после тренировки нужно?',
      'грелка или холод при растяжении',
      'lód czy ciepło na bolące kolano',
      'czy okładać lodem po treningu',
      'ciepły kompres czy zimny na naciągnięty mięsień',
    ],
  },
  painkillers: {
    ex: [
      'is it bad to pop advil before lifting',
      'can i train on ibuprofen for my knee',
      'does ibuprofen hurt muscle gains',
      'taking aspirin before workouts ok?',
      'should i take naproxen after a heavy session',
      'is lifting on painkillers dangerous',
      'can painkillers mask an injury while training',
      'voltaren gel before squats, fine?',
      'take tylenol for doms?',
      'do nsaids slow recovery from training',
      'ok to take a painkiller to finish my workout',
      'i took ibuprofen this morning, can i still deadlift',
      'are anti-inflammatories bad for hypertrophy',
      'is it safe to train on prescription painkillers',
      'can i combine ibuprofen and pre workout',
    ],
    exUk: [
      'чи можна тренуватись на ібупрофені',
      'випив знеболювальне, можна в зал?',
      "чи шкодить ібупрофен росту м'язів",
      'нурофен перед тренуванням норм?',
      'мазь диклофенак перед присідом можна?',
      'знеболювальні маскують травму на тренуванні?',
      'пити парацетамол від крепатури?',
      'чи сповільнюють нпзп відновлення',
      'можна поєднувати ібупрофен і передтрен',
      'можно ли тренироваться на обезболивающих',
      'нурофен перед тренировкой вредно?',
      'ибупрофен мешает росту мышц?',
      'czy mogę ćwiczyć po ibupromie',
      'tabletki przeciwbólowe przed treningiem to dobry pomysł',
      'czy leki przeciwzapalne hamują wzrost mięśni',
    ],
  },
  cut_deficit: {
    ex: [
      'how many calories below maintenance for a cut',
      'is 500 kcal under maintenance a good deficit',
      'whats a safe calorie deficit for lifters',
      'how aggressive should my deficit be',
      'i eat 2500 at maintenance, how much should i cut to',
      'what percent deficit to keep muscle',
      'is 1% bodyweight loss per week too fast',
      'how low can i drop calories while cutting',
      'deficit size for a slow cut',
      'small deficit or big deficit when cutting',
      'how many calories to eat to lose half a kilo a week',
      'my deficit is 800, is that too steep',
      "what deficit if i'm already pretty lean",
      'should my deficit be bigger if i have more fat',
      'cutting calories, how much under tdee',
    ],
    exUk: [
      'на скільки калорій нижче підтримки їсти на сушці',
      '500 ккал дефіциту це нормально?',
      "який безпечний дефіцит щоб не втратити м'язи",
      'наскільки агресивний дефіцит робити',
      'підтримка 2500, скільки їсти на сушці',
      'скільки кг на тиждень худнути на дефіциті',
      'дефіцит 800 ккал не забагато?',
      'який відсоток дефіциту від tdee',
      'малий чи великий дефіцит на сушці',
      'какой дефицит калорий делать на сушке',
      'сколько калорий ниже поддержки есть',
      'дефицит 1000 ккал это слишком?',
      'jaki deficyt kaloryczny na redukcji',
      'ile kalorii poniżej zapotrzebowania jeść',
      'czy 500 kcal deficytu to dobrze',
    ],
  },
  bulk_surplus: {
    ex: [
      'how many extra calories per day to lean bulk',
      'is 300 kcal over maintenance enough to bulk',
      'whats a good surplus to gain muscle not fat',
      'how much weight per month on a bulk',
      '500 surplus too much?',
      'how many calories above tdee for bulking',
      'bulking, how big a calorie surplus',
      'am i gaining too fast on my bulk, surplus size',
      'small surplus vs big surplus for gains',
      'how many kcal to add for a slow bulk',
      "i'm skinny, how much surplus should i run",
      'dirty bulk vs clean surplus which one',
      'how much over maintenance for a beginner bulk',
      'gaining 1kg a week on bulk, too much surplus?',
      'what calorie surplus to build muscle',
    ],
    exUk: [
      'скільки калорій зверху на масонабір',
      'профіцит 300 ккал достатньо?',
      "який профіцит щоб росли м'язи а не жир",
      'скільки кг на місяць набирати на масі',
      'профіцит 500 це забагато?',
      'чисту масу чи брудну робити',
      'я худий, який профіцит мені ставити',
      'скільки ккал додати до підтримки для маси',
      'набираю кг на тиждень, це не забагато?',
      'какой профицит калорий для набора массы',
      'сколько калорий сверх поддержки на массе',
      'грязный или чистый массонабор',
      'jaka nadwyżka kaloryczna na masę',
      'ile kalorii powyżej zapotrzebowania na masie',
      'ile kg miesięcznie przybierać na masie',
    ],
  },
  carbs: {
    ex: [
      'how many grams of carbs per day for lifting',
      'are carbs making me fat',
      'low carb while lifting, good idea?',
      'how many carbs on a cut',
      'carbs per kg bodyweight for gym people',
      'keto and weightlifting, does it work',
      'best carb sources for gains',
      'should i eat carbs at night',
      'oats or rice as my main carbs',
      'cutting out carbs completely, bad for training?',
      'how many carbs on rest days',
      'carb intake for a bulk',
      'is sugar bad for muscle building',
      'should i carb load before a heavy day',
    ],
    exUk: [
      'скільки грам вуглів на день треба',
      "чи потрібні вуглі для росту м'язів",
      'від вуглеводів товстіють?',
      'низьковуглеводна дієта і зал, норм?',
      'скільки вуглеводів на сушці',
      'кето і силові тренування сумісні?',
      'які найкращі джерела вуглеводів',
      'можна їсти вуглі ввечері',
      'скільки вуглеводів в день відпочинку',
      'сколько углеводов в день есть',
      'нужны ли углеводы для набора массы',
      'кето и качалка совместимы?',
      'ile węglowodanów dziennie jeść',
      'czy węgle tuczą',
      'ile węglowodanów na redukcji',
    ],
  },
  fats: {
    ex: [
      'how many grams of fat a day for lifters',
      'is low fat diet bad for testosterone',
      'how much fat on a cut',
      'are healthy fats important for gains',
      'fat per kg bodyweight',
      'is eating a lot of fat bad',
      'avocado nuts and olive oil, how much fat daily',
      'minimum fat intake for hormones',
      'should i cut fats or carbs to lose weight',
      'saturated fat bad for lifters?',
      'percentage of calories from fat',
      'how much fat on a bulk',
      'is keto too much fat',
      'do i need to track fat grams',
      'how low can fat go on a diet',
    ],
    exUk: [
      'скільки грамів жирів на день',
      'мало жирів шкодить тестостерону?',
      'скільки жирів на сушці',
      "корисні жири важливі для м'язів?",
      'скільки жиру на кг ваги',
      'мінімум жирів для гормонів',
      'авокадо горіхи олія скільки жирів в день',
      'різати жири чи вуглі щоб схуднути',
      'насичені жири шкідливі?',
      'сколько жиров в день есть',
      'сколько жиров на сушке',
      'низкожировая диета вредна для гормонов?',
      'ile tłuszczu dziennie jeść',
      'ile tłuszczów na redukcji',
      'minimalna ilość tłuszczu dla hormonów',
    ],
  },
  pre_meal: {
    ex: [
      'what should i eat an hour before lifting',
      'is it ok to train on an empty stomach',
      'banana before gym good?',
      'carbs or protein before a workout',
      'fasted training or eat first',
      'what to eat before morning workouts',
      'snack before evening gym session',
      'is coffee enough before lifting',
      'how big should my pre gym meal be',
      'oatmeal before training good idea',
      'i feel sick if i eat before lifting, what should i have',
      'what to eat 30 minutes before training',
      'best pre workout snack',
      'should i eat before leg day',
      'rice and chicken before the gym, how long before',
    ],
    exUk: [
      "що з'їсти за годину до залу",
      'можна тренуватись натщесерце',
      'банан перед тренуванням норм?',
      'що їсти перед ранковим тренуванням',
      'перекус перед вечірнім залом',
      'кави достатньо перед тренуванням?',
      'вівсянка перед залом хороша ідея',
      'за скільки до тренування їсти',
      "що з'їсти перед днем ніг",
      'что съесть перед тренировкой',
      'можно тренироваться на голодный желудок?',
      'за сколько до зала поесть',
      'co zjeść przed treningiem',
      'czy trenować na czczo',
      'przekąska przed siłownią',
    ],
  },
  post_meal: {
    ex: [
      'what should i eat after lifting',
      'protein shake right after the gym?',
      'how long after training can i eat',
      'best meal after leg day',
      'should i eat carbs after a workout',
      'is chocolate milk good after training',
      'eating late after an evening workout, ok?',
      'what to eat after morning gym',
      'post gym snack ideas',
      'do i need to eat right after training',
      'rice and chicken after workout good?',
      'can i skip eating after the gym',
      'post lift meal on a cut',
      'eat or sleep after a late workout',
      'what should dinner look like after training',
    ],
    exUk: [
      "що з'їсти після залу",
      'протеїн одразу після трені треба?',
      'коли їсти після тренування, одразу чи пізніше',
      'що їсти після дня ніг',
      'вуглі після тренування потрібні?',
      'можна не їсти після залу?',
      'пізно ввечері після тренування їсти норм?',
      'перекус після тренування ідеї',
      'що на вечерю після трені',
      'что съесть после тренировки',
      'протеин сразу после зала нужен?',
      'через сколько после тренировки есть',
      'co zjeść po treningu',
      'czy białko zaraz po siłowni',
      'posiłek po treningu nóg',
    ],
  },
  meals_count: {
    ex: [
      'how many times a day should i eat to build muscle',
      'is 2 meals a day enough',
      'does meal frequency matter for gains',
      'should i spread protein across meals',
      'intermittent fasting with 2 meals, bad for muscle?',
      'can i eat once a day and still grow',
      'how many meals per day on a bulk',
      'do more meals boost metabolism',
      '4 meals or 3 meals a day',
      'eating every few hours needed?',
      'how many feedings a day for protein',
      'is omad ok for lifting',
      'how to split my calories into meals',
      'should i snack between meals',
      'meal timing, how many meals daily',
    ],
    exUk: [
      'скільки разів на день треба їсти',
      'двох прийомів їжі вистачить?',
      "чи важлива частота їжі для м'язів",
      'треба їсти кожні 3 години?',
      'інтервальне голодування і масонабір',
      'можна їсти раз на день і рости?',
      'скільки прийомів їжі на масі',
      '3 рази чи 5 разів на день їсти',
      'як розподілити калорії на прийоми їжі',
      'сколько раз в день есть',
      'дробное питание нужно?',
      'два приёма пищи в день нормально?',
      'ile posiłków dziennie jeść',
      'czy trzeba jeść co 3 godziny',
      'dwa posiłki dziennie wystarczą',
    ],
  },
  cheat_meal: {
    ex: [
      'can i have a cheat day on my cut',
      'had burgers and beer last night, did i mess up',
      'is one cheat meal a week fine',
      'ate a whole pizza, did i ruin my progress',
      'refeed day vs cheat day',
      'how bad is a weekend of junk food',
      'went over my calories big time at a party',
      'is it ok to eat dessert while dieting',
      'ate way too much sweets, what now',
      'does a cheat meal boost metabolism',
      'planned cheat meal on a bulk?',
      'had mcdonalds after training, is that terrible',
      'blew my diet on the weekend',
      'can i eat junk food and still lose fat',
      'free meal once a week ok?',
    ],
    exUk: [
      'можна читміл на сушці',
      "з'їв піцу цілу, все пропало?",
      'один читміл на тиждень норм?',
      'зірвався на вихідних, що тепер',
      "з'їв купу солодкого, це погано?",
      'бургер після тренування це жах?',
      'перебрав калорій на вечірці',
      'чит день чи рефід що краще',
      'можна трохи десерту на дієті',
      'можно ли читмил на сушке',
      'сорвался на выходных съел кучу фастфуда',
      'съел пиццу, всё испортил?',
      'czy mogę mieć cheat meal na redukcji',
      'zjadłem całą pizzę, zepsułem dietę?',
      'cheat day raz w tygodniu jest ok',
    ],
  },
  tired: {
    ex: [
      'im so tired',
      'running on no sleep',
      'feeling exhausted',
      "i'm beat",
      'totally drained today',
      'zero energy man',
      'so sleepy rn',
      "i'm knackered",
      'barely awake',
      'i feel fatigued',
      'dead tired',
      "i'm worn out",
      'my body feels heavy and tired',
      'low energy today',
      'can barely keep my eyes open',
    ],
    exUk: [
      'я дуже втомлений',
      'сил нема',
      'нуль енергії',
      'я повністю виснажений сьогодні',
      'так хочу спати',
      'я вижатий',
      'вимотаний сьогодні',
      'не виспався зовсім',
      'я як вичавлений лимон',
      'я устал',
      'нет сил вообще',
      'я вымотан',
      'jestem zmęczony',
      'nie mam siły',
      'jestem wykończony',
    ],
  },
  mood_down: {
    ex: [
      'feeling down',
      "i'm so sad today",
      'rough day',
      'i feel low',
      'life sucks right now',
      "i'm really stressed and sad",
      'having a terrible day',
      'i feel lonely',
      "i'm not ok",
      'everything went wrong today',
      'feeling blue',
      "i'm in a bad mood",
      'crappy day',
      'i feel miserable',
      "i'm heartbroken",
    ],
    exUk: [
      'мені погано на душі',
      'сумно сьогодні',
      'жахливий день був',
      'настрій на нулі взагалі',
      'мені самотньо',
      'все пішло не так',
      'я засмучений',
      'депресняк',
      'на душі кішки шкребуть',
      'мне грустно',
      'плохой день',
      'настроение на нуле',
      'jest mi smutno',
      'mam zły dzień',
      'czuję się przybity',
    ],
  },
  mood_up: {
    ex: [
      "i'm in a great mood",
      'today was awesome',
      'feeling fantastic',
      'best day ever',
      'so happy right now',
      'i feel on top of the world',
      'life is good',
      "i'm stoked",
      'great vibes today',
      "i'm pumped and happy",
      'feeling good today',
      "i'm in a really good mood",
      'everything is going great',
      'what a day, feeling amazing',
      "i'm thrilled",
    ],
    exUk: [
      'у мене чудовий настрій',
      'сьогодні класний день',
      'мені дуже добре',
      'я такий щасливий сьогодні',
      'настрій просто супер',
      'почуваюсь на всі сто',
      'все клас',
      'сьогодні кайфовий денек',
      'настрій бомба',
      'у меня отличное настроение',
      'я счастлив',
      'день огонь',
      'mam świetny humor',
      'jestem szczęśliwy',
      'super dzień dzisiaj',
    ],
  },
  nothing: {
    ex: [
      'nah nothing',
      'nothing really',
      'no nothing',
      'all good nvm',
      'ignore that',
      'just testing',
      "doesn't matter",
      'nothing, just checking',
      'never mind lol',
      'oh nothing',
      'not important',
      'just saying hi, nothing',
      'skip it',
      'disregard',
    ],
    exUk: [
      'та нічого',
      'нічого, забий',
      'не важливо',
      'проїхали',
      'та просто так спитав',
      'ні нічого',
      'ігноруй',
      'пусте',
      'та ні, нічого',
      'ничего',
      'неважно',
      'да ничего, забей',
      'nic',
      'nieważne',
      'tak po prostu',
    ],
  },
  atlas_age: {
    ex: [
      'how old r u',
      'whats ur age atlas',
      'are you old or young',
      'how long have you existed',
      'when were you created',
      'what year were you made',
      'are you a kid or an adult',
      "what's your birthday",
      'atlas how old are you exactly',
      "you're how many years old",
      'how young are you',
      'when is your birthday',
      'how long have you been around',
      'age?',
      'tell me your age',
    ],
    exUk: [
      'а скільки тобі рочків',
      'який в тебе вік',
      'коли тебе створили',
      'коли в тебе день народження',
      'ти старий чи молодий',
      'скільки ти вже існуєш',
      'атлас скільки тобі',
      'якого ти року',
      'твій вік',
      'сколько тебе лет',
      'когда тебя создали',
      'какой у тебя возраст',
      'ile masz lat',
      'kiedy cię stworzono',
      'kiedy masz urodziny',
    ],
  },
  sing_poem: {
    ex: [
      'write me a poem about lifting',
      'sing a gym song',
      'drop a rap verse',
      'make up a song',
      'write a haiku',
      'rhyme something for me',
      'compose a poem about squats',
      'can you sing',
      'give me a little song',
      'write lyrics about protein',
      'make a poem for me',
      'freestyle something',
      'sing happy birthday',
      'write a short verse',
      'tell me a rhyme',
    ],
    exUk: [
      'напиши віршик',
      'заспівай щось для мене',
      'склади пісню про зал',
      'зачитай реп про качалку',
      'напиши вірш про присідання',
      'придумай пісеньку',
      'склади римовку',
      'заспівай мені',
      'напиши хайку',
      'напиши стих',
      'спой песню',
      'зачитай рэп',
      'napisz wiersz',
      'zaśpiewaj piosenkę',
      'zarapuj coś',
    ],
  },
  which_day: {
    ex: [
      "what's today's date",
      'is it monday today',
      'which day of the week is it',
      'what month is it',
      'date today?',
      'what is the date',
      'tell me the date',
      "what's the day today",
      'is today friday',
      'which date is it',
      'remind me what day it is',
      'day of the week?',
      "what's the current date",
      'what year is it',
    ],
    exUk: [
      'яке сьогодні число місяця',
      'сьогодні понеділок?',
      'яка сьогодні дата',
      'який зараз місяць',
      'скажи дату',
      'що за день сьогодні',
      "сьогодні п'ятниця?",
      'котре сьогодні число',
      'какое сегодня число',
      'какой сегодня день недели',
      'какая дата',
      'jaki dziś dzień',
      'którego dzisiaj',
      'jaka jest data',
    ],
  },
  you_dumb: {
    ex: [
      "you're so stupid",
      'wtf are you talking about',
      'that answer was dumb',
      'you suck at this',
      'bot is useless',
      'what a dumb reply',
      "you're an idiot",
      'that makes no sense',
      "you're not helpful at all",
      'worst bot ever',
      'are you broken',
      "that's the wrong answer dummy",
      'you never understand me',
      'useless ai',
      'you got it totally wrong',
    ],
    exUk: [
      'ти тупий бот',
      'що за дурня',
      'ти нічого не розумієш',
      'відповідь безглузда',
      'ти марний',
      'від тебе ніякої користі',
      'ти зламався?',
      'знову не зрозумів',
      'ну ти й дурень',
      'ты тупой',
      'бесполезный бот',
      'ты ничего не понимаешь',
      'jesteś głupi',
      'bezużyteczny bot',
      'nic nie rozumiesz',
    ],
  },
};
