import type { Kb } from './types';

export const KB_D: Kb = {
  // ---- calculators ----
  plate_math: {
    ex: [
      'plates for 100 kg',
      'what plates do i need for 140 kg',
      'how do i load the bar for 120 kg',
      'which plates go on each side for 100 kg',
      'load the bar to 85 kg',
      'plate math for 180 kg',
      'what do i put on the bar for 60 kg',
      'how many plates per side for 110 kg',
      'loading 142.5 kg, what plates',
      'i want 90 kg on the bar, which plates',
      'plates per side 200 kg',
      'help me load 75 kg on a barbell',
      "what's the plate breakdown for 130 kg",
      'how to load 160 kg with a 20 kg bar',
      'plate calculator 100kg',
      'what weights on each side for 70 kg total',
    ],
    exUk: [
      'млинці на 100 кг',
      'які млинці повісити на 120 кг',
      'скільки млинців з кожного боку на 140 кг',
      'що навісити на гриф щоб було 80 кг',
      'як набрати 100 кг на штанзі',
      'які блини на 90 кг',
      'повісити 150 кг — які млинці',
      'розклад млинців на 60 кг',
      'хочу 110 кг на грифі, що вішати',
      'навісити 70 кг, скільки з кожного боку',
      'млинці на кожну сторону для 130 кг',
      'порахуй млинці на 180 кг',
      'які блінчики накинути на 100',
      'какие блины повесить на 120 кг',
      'сколько блинов на каждую сторону на 100 кг',
    ],
    facets: {
      how: [
        'Subtract the bar (20 kg), halve the rest, and fill each side with the biggest plates first.',
        'Відніми гриф (20 кг), решту поділи навпіл і заповнюй кожен бік з найбільших млинців.',
      ],
      what: [
        'It splits a total bar weight into the plates for each side, assuming a 20 kg bar.',
        'Розкладає загальну вагу на млинці для кожного боку, з грифом 20 кг.',
      ],
      howMuch: [
        'Per side = (total − 20 kg) ÷ 2. For 100 kg that’s 40 kg a side.',
        'На кожен бік = (загальна − 20 кг) ÷ 2. Для 100 кг — 40 кг з боку.',
      ],
    },
  },
  reps_at_weight: {
    ex: [
      'how many reps can i do on bench at 80 kg',
      'how many reps at 100 kg on squat',
      'reps at 140 kg deadlift',
      'how many reps with 60 kg overhead press',
      'if i put 90 kg on bench how many reps',
      'how many reps can i get on squat with 120 kg',
      'deadlift 160 kg how many reps would i manage',
      'how many reps with 70 kg on rows',
      'bench 85 kg — how many reps to failure',
      'how many reps at 50 kg ohp',
      'how many reps could i do at 110 kg squat',
      'reps with 100 kg bench',
      'estimate my reps at 180 kg deadlift',
      'how many reps can i squeeze out on bench with 95',
    ],
    exUk: [
      'скільки повторів на жимі з 80 кг',
      'скільки разів присяду 100 кг',
      'на скільки повторів мене вистачить у становій з 140',
      'скільки повторів жим лежачи 90 кг',
      'скільки разів зможу зробити присід з 120 кг',
      'станова 160 кг — скільки повторів',
      'скільки повторів на армійському жимі з 50 кг',
      'скільки разів витисну 85 кг лежачи',
      'скільки повторів тяга в нахилі з 70 кг',
      'на скільки повторів 100 кг у присіді',
      'скільки раз пожму сотку',
      'скільки повторів зроблю в становій на 180',
      'сколько повторов на жиме с 80 кг',
      'сколько раз присяду 100 кг',
    ],
    facets: {
      how: [
        'It works backwards from your estimated max from recent sets: the further the weight is below it, the more reps.',
        'Рахую від розрахункового максимуму з останніх сетів: що нижча вага від нього, то більше повторів.',
      ],
      should: [
        'Treat it as an estimate to failure, not a target — for working sets leave 1–3 reps in reserve.',
        'Це оцінка до відмови, а не ціль — у робочих сетах лишай 1–3 повтори в запасі.',
      ],
      howMuch: [
        'Estimates are most reliable up to about 10–12 reps; beyond that they drift.',
        'Оцінка найточніша до ~10–12 повторів; далі похибка росте.',
      ],
    },
  },
  percent_max: {
    ex: [
      '70% of my squat',
      'what is 80% of my bench',
      '80 percent of my deadlift max',
      'how much is 75% of my bench press',
      'give me 85% of my squat max',
      'what weight is 90% on deadlift',
      '65% of my overhead press',
      'calculate 70 percent of my bench',
      "what's 60% of my squat 1rm",
      '80% bench',
      'i need 75 percent of my deadlift',
      'work out 85% of my ohp max',
      'percent of max: squat 70',
      'what is 90% of my best bench',
    ],
    exUk: [
      '70% від мого присіду',
      'скільки це 80% від жиму лежачи',
      '80 відсотків від максимуму в становій',
      'порахуй 75% від жиму',
      '85% від присіду це скільки',
      'яка вага 90% у становій',
      '65 відсотків від армійського жиму',
      '70 процентів від жиму лежачи',
      'скільки буде 60% від мого максимуму в присіді',
      '80% жим',
      'дай 75% від станової',
      '75 процентів від присяду',
      'сколько 80% от жима',
      '70 процентов от приседа',
    ],
    facets: {
      what: [
        'It’s a share of your estimated one-rep max, calculated from your recent sets and rounded to loadable weight.',
        'Це частка твого розрахункового максимуму на 1 повтор, порахованого з останніх сетів і округленого до реальної ваги.',
      ],
      howMuch: [
        'Roughly: 60–70% for volume work (8–12 reps), 75–85% for strength (3–6 reps), 90%+ for heavy singles and doubles.',
        'Орієнтовно: 60–70% — об’ємна робота (8–12 повт.), 75–85% — сила (3–6), 90%+ — важкі одиночні й двійки.',
      ],
      why: [
        'Percentages let you pick working weights that match your current strength instead of guessing.',
        'Відсотки дають підібрати робочу вагу під твою поточну силу, а не навмання.',
      ],
    },
  },
  warmup_lift: {
    ex: [
      'how should i warm up for bench',
      'warm up sets for squat',
      'give me a warmup for deadlift',
      'how to ramp up to my working weight on bench',
      'warm-up for overhead press',
      'what warm up sets before heavy squats',
      'warmup ladder for deadlift',
      'ramp-up sets for bench press',
      'how do i warm up for heavy deadlifts',
      'squat warm up please',
      'what weights to warm up with on bench',
      'how many warm up sets before squat',
      'warm up pyramid for ohp',
      'build up sets for rows',
    ],
    exUk: [
      'як розминатися перед жимом лежачи',
      'розминка для присіду',
      'підвідні підходи на станову',
      'розминочні сети для жиму',
      'як підійти до робочої ваги в присіді',
      'розминка перед становою тягою',
      'які підвідні на армійський жим',
      'як розігрітися на жим лежачи',
      'розминочні ваги для присіду',
      'підвідні на жим, які ваги',
      'скільки підвідних перед становою',
      'розминка на тягу в нахилі',
      'разминка перед жимом лежа',
      'подводящие подходы на присед',
    ],
    facets: {
      how: [
        'Empty bar × 10, then about 50% × 5, 70% × 3 and 85% × 1 of your working weight, then start work sets.',
        'Гриф × 10, далі приблизно 50% × 5, 70% × 3 і 85% × 1 від робочої ваги, потім робочі сети.',
      ],
      why: [
        'Ramp-up sets rehearse the movement and prepare joints and muscles, so the first work set feels solid.',
        'Підвідні сети повторюють техніку й готують суглоби та м’язи, щоб перший робочий сет пішов упевнено.',
      ],
      howMuch: [
        'Usually 3–5 ramp-up sets with falling reps; heavier working weights need more steps.',
        'Зазвичай 3–5 підвідних зі спадними повторами; що важча робоча вага, то більше кроків.',
      ],
      should: [
        'Yes, keep warm-ups easy — they shouldn’t tire you before the working sets.',
        'Так, але легкими — розминка не має втомлювати до робочих сетів.',
      ],
    },
  },

  // ---- exercise knowledge ----
  exercise_muscles: {
    ex: [
      'what muscles does bench press work',
      'which muscles do squats target',
      'what does deadlift work',
      'what muscles do pull-ups train',
      'rows work what',
      'what does the overhead press target',
      'which muscles are used in the deadlift',
      'what muscle groups does bench hit',
      'what do dips work',
      'does squat work glutes or quads',
      'muscles worked by barbell rows',
      'what does romanian deadlift target',
      'which muscles does lat pulldown work',
      'what do lunges hit',
      'what muscles are trained by pull ups',
    ],
    exUk: [
      'які м’язи працюють у жимі лежачи',
      'що качає присід',
      'на що станова тяга',
      'які м’язи працюють при підтягуваннях',
      'що працює в тязі в нахилі',
      'армійський жим на що',
      'які м’язи задіяні в становій',
      'віджимання на брусах що качає',
      'на які м’язи румунська тяга',
      'що працює у випадах',
      'які мязи тренує тяга верхнього блоку',
      'жим лежачи на що впливає',
      'что качает присед',
      'какие мышцы работают в становой',
    ],
    facets: {
      what: [
        'Each lift has a main (primary) muscle and helpers (secondary) that assist it.',
        'У кожної вправи є головний м’яз і допоміжні, що йому допомагають.',
      ],
      why: [
        'Knowing the muscles helps you balance your week and pick fair replacements.',
        'Знаючи м’язи, легше збалансувати тиждень і підібрати рівноцінну заміну.',
      ],
      where: [
        'Each exercise’s card in the app also shows its primary and secondary muscles.',
        'У картці кожної вправи в застосунку теж видно основні й допоміжні м’язи.',
      ],
    },
  },
  alternatives: {
    ex: [
      'alternative to bench press',
      'what can i do instead of squats',
      'replacement for deadlift',
      'substitute for pull-ups',
      'what to do instead of leg press',
      'alternatives for overhead press',
      "i can't do dips, what's a substitute",
      'swap options for barbell rows',
      'something similar to lat pulldown',
      'what can replace romanian deadlift',
      'no squat rack, alternative to back squat',
      'best substitute for bench',
      'what else hits the same muscles as deadlift',
      'other exercises instead of pull ups',
      'equivalent exercise to lunges',
    ],
    exUk: [
      'чим замінити жим лежачи',
      'альтернатива присіду',
      'що робити замість станової',
      'чим замінити підтягування',
      'альтернатива жиму ногами',
      'що замість армійського жиму',
      'не можу бруси, чим замінити',
      'замінити тягу в нахилі на щось',
      'альтернативи тязі верхнього блоку',
      'що можна замість румунської тяги',
      'нема стійки для присіду, що замість',
      'аналог жиму лежачи',
      'чем заменить присед',
      'альтернатива становой',
    ],
    facets: {
      how: [
        'I pick lifts with the same main muscle, ranked by what your usual gym has.',
        'Підбираю вправи з тим самим головним м’язом, з урахуванням того, що є у твоєму звичному залі.',
      ],
      should: [
        'Swap if a lift hurts or the kit isn’t there; otherwise changing lifts too often makes progress harder to track.',
        'Міняй, якщо вправа болить чи нема обладнання; інакше часті заміни ускладнюють відстеження прогресу.',
      ],
      where: [
        'To make a swap stick in your plans, say “swap bench for dumbbell press”.',
        'Щоб заміна закріпилась у планах, скажи «заміни жим лежачи на жим гантелей».',
      ],
    },
  },
  sets_for_lift: {
    ex: [
      'how many sets of bench should i do',
      'how many sets for squats',
      'sets of deadlift per session',
      'how many sets of pull-ups',
      'how many working sets on overhead press',
      'how many sets should i do for rows',
      'number of sets for bench press',
      'how many sets of squats is enough',
      'is 5 sets of bench too much',
      'how many hard sets of deadlift',
      'how many sets of dips',
      'sets for lat pulldown',
      'how many sets of lunges',
      'ideal number of sets on bench',
    ],
    exUk: [
      'скільки сетів жиму лежачи робити',
      'скільки підходів присіду',
      'скільки підходів станової за тренування',
      'скільки сетів підтягувань',
      'скільки робочих підходів на армійський жим',
      'скільки підходів тяги в нахилі',
      'скільки сетів на жим оптимально',
      '5 підходів присіду — не забагато',
      'скільки сетів станової робити',
      'скільки підходів на бруси',
      'скільки сетів випадів',
      'скільки підходів на тягу блоку',
      'сколько подходов жима лежа',
      'сколько подходов приседа делать',
    ],
    facets: {
      howMuch: [
        '3–4 hard sets per lift in a session is the sweet spot for most people.',
        '3–4 робочі сети на вправу за тренування — оптимум для більшості.',
      ],
      why: [
        'Past 3–4 hard sets each extra set adds less and costs more recovery.',
        'Після 3–4 робочих сетів кожен наступний дає менше, а відновлення забирає більше.',
      ],
      what: [
        'Only working sets count — warm-up sets don’t.',
        'Рахуються лише робочі сети — розминочні ні.',
      ],
    },
  },

  // ---- log by day ----
  day_lookup: {
    ex: [
      'what did i do on monday',
      'what did i train on tuesday',
      'what did i do on wednesday',
      'what did i train on thursday',
      'on friday what did i lift',
      'what did i do on saturday',
      'what did i train on sunday',
      "show me monday's workout",
      'what was my workout on wednesday',
      'remind me what i lifted on friday',
      'which exercises did i do on tuesday',
      'what did i hit on thursday',
      "what was on saturday's session",
      'last monday what did i train',
    ],
    exUk: [
      'що я робив у понеділок',
      'що я тренував у вівторок',
      'що я робив у середу',
      'що я тренував у четвер',
      'що було в пятницю',
      'що я робив у суботу',
      'що я тренував у неділю',
      'покажи тренування в понеділок',
      'які вправи я робив у середу',
      'нагадай що я робив у пятницю',
      'що я робила в четвер',
      'яке було тренування у вівторок',
      'что я делал в понедельник',
      'что я тренировал в среду',
    ],
    facets: {
      what: [
        'It shows your most recent session on that weekday (within the last week): lifts and top sets.',
        'Показує твоє останнє тренування в цей день тижня (за останній тиждень): вправи й найкращі сети.',
      ],
      where: [
        'The full session is in your workout history.',
        'Повне тренування — в історії тренувань.',
      ],
    },
  },
  compare_weeks: {
    ex: [
      'compare this week to last week',
      'this week vs last week',
      'how does this week compare to the previous week',
      'did i train more than last week',
      'this week versus the week before',
      'am i doing more sets than last week',
      'compare my training with last week',
      'was last week better than this one',
      'more sessions than last week or fewer',
      'how is this week compared with the previous week',
      'week over week comparison',
      'this week vs previous week volume',
      'less or more than last week',
      'compare last week and this week',
    ],
    exUk: [
      'порівняй цей тиждень з минулим',
      'цей тиждень проти минулого',
      'я тренувався більше ніж минулого тижня',
      'порівняння з минулим тижнем',
      'як цей тиждень порівняно з попереднім тижнем',
      'більше сетів ніж минулого тижня',
      'порівняти з попереднім тижнем',
      'цей тиждень краще ніж минулий',
      'менше чи більше ніж минулого тижня',
      'порівняй мої тренування з минулим тижнем',
      'а минулого тижня більше було ніж зараз',
      'тиждень до тижня порівняння, минулого тижня проти цього',
      'сравни эту неделю с прошлой',
      'больше чем на прошлой неделе',
    ],
    facets: {
      what: [
        'It compares sessions and working sets in the last 7 days with the 7 days before.',
        'Порівнює тренування й робочі сети за останні 7 днів із попередніми 7 днями.',
      ],
      why: [
        'Week-to-week swings are normal; look at trends over several weeks.',
        'Коливання від тижня до тижня — нормально; дивись на тенденцію за кілька тижнів.',
      ],
    },
  },

  // ---- time-pressed ----
  short_on_time: {
    ex: [
      'i only have 30 minutes',
      'no time today, what should i do',
      'short on time, quick workout',
      "i've got 20 minutes at the gym",
      'only 40 minutes today',
      'quick session, 25 minutes',
      'what can i do in 30 minutes',
      'in a rush, need something quick',
      'i have only 15 minutes',
      'short on time today',
      '45 minutes only, how to train',
      'gym in 30 minutes max',
      'time crunch, give me a quick workout',
      'no time for a full session',
    ],
    exUk: [
      'у мене тільки 30 хвилин',
      'нема часу, що робити',
      'мало часу, швидке тренування',
      'маю 20 хвилин у залі',
      'тільки 40 хвилин сьогодні',
      'що встигну за 30 хвилин',
      'немає часу на повне тренування',
      'швидко за 25 хвилин',
      'лише 15 хвилин є',
      'сьогодні мало часу',
      '45 хвилин тільки, як тренуватись',
      'поспішаю, треба щось швидко',
      'нет времени, только 30 минут',
      'мало времени сегодня',
    ],
    facets: {
      how: [
        'Pick 3 big lifts, do 3 hard sets each, pair them as supersets and rest 60–90 s.',
        'Візьми 3 базові вправи по 3 робочі сети, об’єднай у суперсети, відпочинок 60–90 с.',
      ],
      should: [
        'Yes, a short session is worth it — done beats perfect. Skip isolation work first.',
        'Так, коротке тренування варте того — зроблене краще за ідеальне. Першими пропускай ізолюючі.',
      ],
      howMuch: [
        'About 9–12 hard sets fit into 30 minutes with supersets.',
        'У 30 хвилин із суперсетами вміщається приблизно 9–12 робочих сетів.',
      ],
    },
  },
  two_days_row: {
    ex: [
      'can i train two days in a row',
      'is it ok to lift back to back days',
      'can i work out every day',
      'training the same muscle two days in a row',
      'is it bad to train consecutive days',
      'chest two days in a row okay',
      'can i squat two days in a row',
      'should i lift every day',
      'is back to back training fine',
      'legs two days in a row',
      'consecutive gym days, is that ok',
      'can i hit the gym every day',
      'training arms every day good or bad',
      'is working out 2 days in a row too much',
    ],
    exUk: [
      'можна тренуватись два дні поспіль',
      'чи ок тренуватись два дні підряд',
      'можна ходити в зал кожен день',
      'той самий м’яз два дні поспіль',
      'груди два дні підряд — нормально',
      'ноги два дні поспіль можна',
      'тренуватись щодня це погано',
      'чи можна качатись кожен день',
      'присідати два дні підряд',
      'шкідливо тренуватися щодня?',
      'руки кожен день можна',
      'два дні поспіль у залі — норм?',
      'можно тренироваться каждый день',
      'два дня подряд тренироваться нормально',
    ],
    facets: {
      should: [
        'Yes for different muscles if you recover; the same muscle two days running only if one of the days is light.',
        'Так для різних м’язів, якщо відновлюєшся; той самий м’яз два дні поспіль — лише якщо один із днів легкий.',
      ],
      when: [
        'Hard sessions for the same muscle want about 48 hours apart.',
        'Між важкими тренуваннями одного м’яза — приблизно 48 годин.',
      ],
      why: [
        'Muscles grow and adapt during recovery; hammering them again too soon eats into that.',
        'М’язи ростуть і адаптуються під час відновлення; зарано навантажити знову — з’їсти цей ефект.',
      ],
    },
  },
  two_a_day: {
    ex: [
      'can i train twice a day',
      'two sessions a day, good idea',
      'is two a day training worth it',
      'lifting in the morning and cardio in the evening same day',
      'should i do two workouts a day',
      'is training twice a day too much',
      'two a day splits for gains',
      'gym twice a day',
      'morning and evening workouts on the same day',
      'doubles: lifting twice a day',
      'two sessions a day to lose fat',
      'is it ok to work out two times a day',
      'can i do weights twice a day',
      'two training sessions a day okay',
    ],
    exUk: [
      'можна тренуватись двічі на день',
      'два тренування на день — норм',
      'два рази на день у зал',
      'зранку силове а ввечері кардіо',
      'чи варто тренуватись двічі на день',
      'двічі на день — не забагато',
      'два тренування на день щоб схуднути',
      'тренуватися два рази на день можна',
      'ранкове і вечірнє тренування в один день',
      'двічі на день качатися',
      'два трені на день',
      'два силові на день є сенс',
      'тренироваться два раза в день',
      'две тренировки в день нормально',
    ],
    facets: {
      should: [
        'Only if you split the load, like lifting in the morning and easy cardio in the evening, and sleep enough. Two hard lifting sessions a day is rarely worth it.',
        'Лише якщо розділити навантаження: силове вранці, легке кардіо ввечері — і висипатися. Два важкі силові на день рідко виправдані.',
      ],
      how: [
        'Keep one session hard and the other easy, and put at least 6 hours between them.',
        'Одне тренування важке, друге легке, а між ними щонайменше 6 годин.',
      ],
      who: [
        'Mostly for people with lots of time and recovery, or athletes who combine lifting with a sport.',
        'Здебільшого для тих, хто має багато часу й добре відновлюється, або спортсменів, що поєднують силові зі спортом.',
      ],
    },
  },

  // ---- health & safety ----
  health_conditions: {
    ex: [
      'can i lift with high blood pressure',
      'i have hypertension, is lifting safe',
      'training with diabetes',
      'i have asthma, can i work out',
      'i have a heart condition, can i lift weights',
      'is weightlifting ok with heart disease',
      'i have arrhythmia, is the gym safe',
      'lifting with type 2 diabetes',
      'does high blood pressure mean no heavy lifting',
      'asthma and heavy squats',
      'gym with hypertension tips',
      'my doctor says i have high blood pressure, can i still train',
      'is strength training good for diabetes',
      'working out with a heart problem',
    ],
    exUk: [
      'можна качатися з високим тиском',
      'у мене гіпертонія, силові безпечно',
      'тренування при діабеті',
      'у мене астма, можна в зал',
      'проблеми з серцем, можна з вагами',
      'аритмія і силові тренування',
      'в мене тиск скаче, можна важкі присіди',
      'діабет другого типу і зал',
      'з астмою можна присідати',
      'гіпертонія і штанга',
      'хворе серце, чи можна тренуватися',
      'силові корисні при діабеті?',
      'можно ли качаться с давлением',
      'у меня астма, можно тренироваться',
    ],
    facets: {
      should: [
        'Usually yes, lifting tends to help, but get your doctor’s OK first and tell them what you do.',
        'Зазвичай так, силові здебільшого допомагають, але спершу погодь із лікарем і розкажи, що саме робиш.',
      ],
      how: [
        'Keep breathing (no long breath-holds), build up gradually and avoid all-out grinders.',
        'Дихай рівно (без довгих затримок), навантаження збільшуй поступово, без виснажливих граничних повторів.',
      ],
      when: [
        'Stop right away with chest pain, dizziness or unusual breathlessness, and see a doctor.',
        'Зупиняйся одразу при болю в грудях, запамороченні чи незвичній задишці — і звертайся до лікаря.',
      ],
      who: [
        'Your doctor sets the limits for your condition — I can only give general training info.',
        'Межі для твого стану визначає лікар — я даю лише загальну інформацію про тренування.',
      ],
    },
  },
  peds: {
    ex: [
      'should i take steroids',
      'are sarms safe',
      'what do you think about trt',
      'how much faster would i grow on steroids',
      'is testosterone worth it for gains',
      'give me a steroid cycle',
      'anabolic steroids for beginners',
      'should i run sarms to break a plateau',
      'are peds worth it',
      'can you help me plan a testosterone cycle',
      'do i need steroids to get big',
      'is trt cheating',
      'anabolics side effects',
      'natural vs steroids, which is better',
    ],
    exUk: [
      'чи варто брати стероїди',
      'сарми безпечні',
      'що думаєш про тестостерон',
      'розпиши курс стероїдів',
      'анаболіки для новачка',
      'без хімії можна накачатися',
      'чи варто сідати на фарму',
      'тестостерон для масу',
      'стероїди — це погано?',
      'допоможи з курсом анаболіків',
      'побічки від стероїдів',
      'натурал чи на хімії',
      'стоит ли колоть стероиды',
      'посоветуй курс анаболиков',
    ],
    facets: {
      should: [
        'I don’t coach drugs; they carry real risks and belong only under a doctor’s care.',
        'Препарати я не веду: вони мають реальні ризики й можливі лише під наглядом лікаря.',
      ],
      why: [
        'Risks include the heart, liver, hormones and fertility, and some effects can be lasting.',
        'Ризики — серце, печінка, гормони, фертильність, і деякі наслідки можуть бути тривалими.',
      ],
      how: [
        'Progress for years comes from consistent training, enough protein and food, and good sleep.',
        'Прогрес роками дають регулярні тренування, достатньо білка та їжі й добрий сон.',
      ],
      who: [
        'Any hormone therapy such as TRT is a decision for a doctor after proper tests.',
        'Будь-яка гормональна терапія, як-от ЗТТ, — рішення лікаря після аналізів.',
      ],
    },
  },
  cycle: {
    ex: [
      'should i train on my period',
      'lifting during menstruation',
      'how does my cycle affect strength',
      'training around my menstrual cycle',
      'pms and workouts',
      'can i lift heavy on my period',
      'is it ok to work out during my period',
      'cycle syncing workouts, does it work',
      'i have cramps from my period, should i train',
      'menstrual cycle and gym performance',
      'should i change training by cycle phase',
      'am i weaker during my period',
      'period week workout tips',
      'train during pms or rest',
    ],
    exUk: [
      'чи можна тренуватись під час місячних',
      'силові під час менструації',
      'як цикл впливає на силу',
      'тренування за фазами циклу',
      'пмс і тренування',
      'можна важко під час місячних',
      'болить живіт через місячні, йти в зал?',
      'менструальний цикл і зал',
      'чи слабша я на місячних',
      'треба міняти тренування за циклом?',
      'у мене місячні, що робити в залі',
      'тренуватися в дні циклу',
      'можно ли тренироваться во время месячных',
      'тренировки и менструальный цикл',
    ],
    facets: {
      should: [
        'Yes, you can train through the whole cycle; on heavy-symptom days go lighter or do easy cardio.',
        'Так, тренуватися можна протягом усього циклу; у дні з сильними симптомами — легше або легке кардіо.',
      ],
      why: [
        'Strength differences between cycle phases are small in research — consistency matters more.',
        'За дослідженнями різниця в силі між фазами циклу невелика — важливіша регулярність.',
      ],
      how: [
        'Adjust by feel on the day rather than a fixed phase schedule.',
        'Орієнтуйся на самопочуття в конкретний день, а не на жорсткий графік за фазами.',
      ],
      when: [
        'See a doctor if pain or bleeding is severe or unusual for you.',
        'Звернися до лікаря, якщо біль чи кровотеча сильні або незвичні для тебе.',
      ],
    },
  },
  pregnancy: {
    ex: [
      'can i lift while pregnant',
      'training during pregnancy',
      'is it safe to squat pregnant',
      'postpartum workout plan',
      'when can i lift after giving birth',
      "i'm pregnant, what should i change",
      'weight training in the third trimester',
      'can pregnant women deadlift',
      'getting back to the gym postpartum',
      'exercises to avoid when pregnant',
      'is bench press ok while pregnant',
      'strength training in early pregnancy',
      'postpartum lifting, where to start',
      "i just found out i'm pregnant, keep lifting?",
    ],
    exUk: [
      'можна тренуватись під час вагітності',
      'силові при вагітності',
      'вагітна — можна присідати',
      'тренування після пологів',
      'коли можна в зал після пологів',
      'я вагітна, що змінити в тренуваннях',
      'які вправи не можна вагітним',
      'станова під час вагітності',
      'повернення в зал після пологів',
      'силові в третьому триместрі',
      'післяпологове відновлення і зал',
      'вагітним можна жим лежачи?',
      'можно ли качаться беременной',
      'тренировки после родов',
    ],
    facets: {
      should: [
        'Training is generally encouraged in pregnancy and after birth, but your doctor or midwife sets the limits.',
        'Тренування зазвичай рекомендують під час вагітності й після пологів, але межі визначає лікар чи акушерка.',
      ],
      what: [
        'Avoid lying flat on your back later on, heavy breath-holding, and anything that causes pain or pressure.',
        'Пізніше уникай лежання на спині, затримок дихання під вагою й усього, що дає біль чи тиск.',
      ],
      when: [
        'When to return after birth depends on the delivery and recovery — get cleared by your doctor first.',
        'Коли повертатися після пологів, залежить від пологів і відновлення — спершу отримай дозвіл лікаря.',
      ],
      who: [
        'Your doctor or midwife — they know your situation; I can only share general information.',
        'Лікар чи акушерка — вони знають твою ситуацію; я даю лише загальну інформацію.',
      ],
    },
  },

  // ---- conditioning ----
  hr_zones: {
    ex: [
      'what is zone 2',
      'zone 2 cardio for lifters',
      'what heart rate should i do cardio at',
      'heart rate zones explained',
      "how do i know i'm in zone 2",
      "what's my ideal heart rate for fat burning",
      'zone two training, is it worth it',
      'hr zones for cardio',
      'what heart rate is too high during cardio',
      'should my cardio be zone 2',
      'how to find my zone 2 heart rate',
      'heart rate target for easy runs',
      'what percent of max heart rate is zone 2',
      'low heart rate cardio benefits',
    ],
    exUk: [
      'що таке зона 2',
      'кардіо в зоні 2 для силовиків',
      'на якому пульсі робити кардіо',
      'пульсові зони пояснення',
      'як зрозуміти що я в зоні 2',
      'який пульс для спалення жиру',
      'пульс під час кардіо який має бути',
      'зона 2 — це скільки пульс',
      'який пульс занадто високий',
      'кардіо на низькому пульсі, є сенс',
      'як знайти свою пульсову зону',
      'пульс на легкій пробіжці',
      'что такое зона 2',
      'какой пульс для кардио',
    ],
    facets: {
      what: [
        'Zone 2 is easy steady cardio where you can still talk in full sentences, around 60–70% of max heart rate.',
        'Зона 2 — легке рівномірне кардіо, коли ще можеш говорити повними реченнями, приблизно 60–70% від макс. пульсу.',
      ],
      how: [
        'Use the talk test: full sentences but not singing. A heart-rate strap or watch helps confirm it.',
        'Тест розмови: повні речення вдаються, а співати — ні. Нагрудний датчик чи годинник допоможуть перевірити.',
      ],
      howMuch: [
        'Most of a lifter’s cardio can sit in zone 2, with a little high-intensity work on top.',
        'Більшість кардіо силовика може бути в зоні 2, плюс трохи інтенсиву зверху.',
      ],
      why: [
        'It builds your aerobic base and recovery with little fatigue, so it doesn’t hurt lifting.',
        'Розвиває аеробну базу й відновлення з малою втомою, тож не заважає силовим.',
      ],
    },
  },
  hiit: {
    ex: [
      'how do i do hiit',
      'is hiit good for fat loss',
      'hiit workout for lifters',
      'interval training plan',
      'how often should i do hiit',
      'tabata, is it worth it',
      'hiit or steady cardio',
      'how long should intervals be',
      'hiit on the bike or treadmill',
      'can i do hiit and lift',
      'sprint intervals protocol',
      'best hiit routine',
      'does hiit kill gains',
      'how many rounds of intervals',
    ],
    exUk: [
      'як робити hiit',
      'інтервальне тренування для схуднення',
      'hiit для силовиків',
      'план інтервальних тренувань',
      'як часто робити інтервали',
      'табата — варто?',
      'інтервали чи рівне кардіо',
      'скільки тривають інтервали',
      'інтервали на велотренажері',
      'hiit і силові разом',
      'скільки раундів інтервалів',
      'хііт вбиває масу?',
      'интервальные тренировки как делать',
      'табата для жиросжигания',
    ],
    facets: {
      how: [
        '20–30 s hard, 60–90 s easy, repeated for 6–10 rounds.',
        '20–30 с важко, 60–90 с легко, 6–10 раундів.',
      ],
      howMuch: [
        '1–2 sessions a week is plenty alongside lifting.',
        '1–2 рази на тиждень поряд із силовими — достатньо.',
      ],
      when: [
        'Keep it away from heavy leg days so it doesn’t hurt your squats and deadlifts.',
        'Подалі від важкого дня ніг, щоб не страждали присід і станова.',
      ],
      where: [
        'A bike or rower spares your legs and joints more than sprinting.',
        'Велотренажер чи гребний тренажер бережуть ноги й суглоби більше, ніж спринти.',
      ],
    },
  },
  running: {
    ex: [
      'can i run and lift',
      'running and strength training together',
      'how to combine running with the gym',
      'training for a 5k while lifting',
      'does running kill gains',
      'should i run before or after lifting',
      'marathon training and weights',
      'how much running is ok with lifting',
      'jogging on leg day',
      'i want to start running, i already lift',
      '10k plan alongside strength training',
      'run on rest days?',
      'how fast should i increase my running',
      'running hurts my squats, what to do',
    ],
    exUk: [
      'можна бігати і качатись',
      'біг і силові разом',
      'як поєднати біг із залом',
      'підготовка до 5 км і силові',
      'біг вбиває масу?',
      'бігати до чи після силового',
      'марафон і тренажерний зал',
      'скільки можна бігати, якщо тренуюсь у залі',
      'пробіжка в день ніг',
      'хочу почати бігати, вже качаюсь',
      'бігати у дні відпочинку',
      'як швидко збільшувати дистанцію бігу',
      'бег и качалка совместимы',
      'бегать до или после зала',
    ],
    facets: {
      how: [
        'Run mostly at an easy pace with one quality session a week, and lift legs on a different day or before the run.',
        'Бігай здебільшого в легкому темпі, одне якісне тренування на тиждень, а ноги — в інший день або перед бігом.',
      ],
      howMuch: [
        'Add at most about 10% distance a week.',
        'Додавай не більше ~10% дистанції на тиждень.',
      ],
      should: [
        'Yes, running and lifting go together fine if most runs are easy and volume grows slowly.',
        'Так, біг і силові добре поєднуються, якщо більшість пробіжок легкі, а обсяг росте поступово.',
      ],
      when: [
        'Lift legs before the run or on a separate day, not right after a hard run.',
        'Ноги — перед бігом або в окремий день, а не одразу після важкої пробіжки.',
      ],
    },
  },
  steps: {
    ex: [
      'how many steps a day should i walk',
      'is 10000 steps a day necessary',
      'does walking help fat loss',
      'daily step count goal',
      'should i track my steps',
      'walking on rest days',
      'is walking good for recovery',
      'how many steps to lose weight',
      'i only walk 3000 steps a day, is that bad',
      'walking vs cardio for fat loss',
      'does walking count as cardio',
      'how much walking per day',
      'step goal for lifters',
      '10k steps worth it',
    ],
    exUk: [
      'скільки кроків на день треба',
      '10000 кроків — обов’язково?',
      'ходьба допомагає схуднути',
      'ціль по кроках на день',
      'чи рахувати кроки',
      'ходити у дні відпочинку',
      'ходьба для відновлення',
      'скільки кроків щоб схуднути',
      'я проходжу лише 3000 кроків, це погано',
      'ходьба чи кардіо для схуднення',
      'скільки ходити щодня',
      'кроки для силовика',
      'сколько шагов в день нужно',
      'ходьба для похудения',
    ],
    facets: {
      howMuch: [
        '7–10k steps a day covers most of the health benefit.',
        '7–10 тис. кроків на день дають більшість користі для здоров’я.',
      ],
      why: [
        'Walking burns more energy over a week than you’d think and speeds up recovery without adding fatigue.',
        'Ходьба за тиждень спалює більше енергії, ніж здається, і пришвидшує відновлення без зайвої втоми.',
      ],
      should: [
        'Yes, if you’re well under 7k, adding steps is one of the easiest wins for health and fat loss.',
        'Так, якщо в тебе значно менше 7 тис., додати кроків — один із найпростіших виграшів для здоров’я й схуднення.',
      ],
      how: [
        'Build up gradually: add 1–2k a day each week, for example short walks after meals.',
        'Додавай поступово: +1–2 тис. на день щотижня, наприклад короткі прогулянки після їжі.',
      ],
    },
  },
  posture: {
    ex: [
      'how to fix bad posture',
      'rounded shoulders fix',
      'exercises for posture',
      'i hunch over my desk, what helps',
      'how to fix kyphosis with training',
      'does lifting improve posture',
      'forward shoulders from bench',
      "what's the correct posture",
      'upper back exercises for posture',
      'hunched back fix',
      'posture exercises for office workers',
      'stop slouching with training',
      'does face pull help posture',
      'rounded upper back from sitting',
    ],
    exUk: [
      'як виправити поставу',
      'сутулість як виправити',
      'вправи для постави',
      'сутулюся за комп’ютером, що допоможе',
      'округлені плечі',
      'силові покращують поставу?',
      'плечі вперед від жиму',
      'яка правильна постава',
      'вправи на верх спини для постави',
      'горб на спині як прибрати',
      'постава для офісних працівників',
      'face pull для постави',
      'как исправить сутулость',
      'упражнения для осанки',
    ],
    facets: {
      how: [
        'Do more pulling than pushing (rows, face pulls, rear delts), build a strong upper back and change positions often.',
        'Роби більше тяг, ніж жимів (тяги, face pull, задня дельта), зміцнюй верх спини й частіше змінюй положення.',
      ],
      what: [
        'There’s no single correct posture — the best posture is the next one, so keep moving.',
        'Єдиної правильної пози нема — найкраща та, що наступна, тож рухайся.',
      ],
      howMuch: [
        'A simple rule: at least as many sets of pulling as pushing each week.',
        'Просте правило: сетів тяг щотижня не менше, ніж жимів.',
      ],
      when: [
        'See a doctor or physio if posture comes with pain, numbness or a stiff curve that doesn’t change.',
        'Звернися до лікаря чи фізіотерапевта, якщо з поставою є біль, оніміння або вигин, що не змінюється.',
      ],
    },
  },
  other_sport: {
    ex: [
      'how should i lift for football',
      'strength training for boxing',
      'gym routine for bjj',
      'lifting weights as a tennis player',
      'should mma fighters lift',
      'strength training for climbing',
      'weights for cycling performance',
      'gym for swimmers',
      'lifting for basketball',
      'i play soccer, how often should i train in the gym',
      'strength work alongside boxing training',
      'how to combine bjj and lifting',
      'does lifting help my tennis',
      'gym plan for a climber',
    ],
    exUk: [
      'силові для футболу',
      'як качатися боксеру',
      'зал для єдиноборств',
      'силові тренування для тенісу',
      'як поєднати бокс і зал',
      'тренування в залі для баскетболу',
      'силові для скелелазіння',
      'зал для плавання',
      'граю у футбол, скільки разів ходити в зал',
      'силові тренування для вело',
      'чи потрібен зал боксеру',
      'плавання і силові тренування разом',
      'силовые для футболиста',
      'качалка для бокса',
    ],
    facets: {
      howMuch: [
        'About 2 sessions a week of big lifts at moderate volume.',
        'Приблизно 2 тренування на тиждень, базові вправи, помірний обсяг.',
      ],
      when: [
        'Put gym sessions far from your hardest sport days.',
        'Став зал подалі від найважчих спортивних днів.',
      ],
      why: [
        'The sport comes first; the gym makes you stronger and harder to injure.',
        'Спорт — першим; зал робить тебе сильнішим і стійкішим до травм.',
      ],
      should: [
        'Yes, most athletes benefit from lifting, as long as it doesn’t leave you too tired for your sport.',
        'Так, більшості спортсменів силові корисні, якщо не виснажують перед основним спортом.',
      ],
    },
  },
  home_equipment: {
    ex: [
      'what should i buy for a home gym',
      'home gym essentials',
      'best equipment to buy for home',
      'setting up a home gym on a budget',
      'dumbbells for home, which ones',
      'what to buy first for training at home',
      'is a squat rack worth it for a home gym',
      'adjustable dumbbells or fixed',
      'i want to buy equipment for my apartment',
      'minimum equipment for home workouts',
      'home gym starter kit',
      'what equipment do i need at home',
      'building a garage gym, where to start',
      'which is better to buy, bench or pull-up bar',
    ],
    exUk: [
      'що купити для домашнього залу',
      'домашній зал з чого почати',
      'яке обладнання для дому купити',
      'купити гантелі для дому, які',
      'мінімум обладнання для тренувань вдома',
      'розбірні гантелі чи звичайні',
      'чи варто купувати раму додому',
      'обладнання для дому на старт',
      'що купити першим для тренувань удома',
      'домашній зал за невеликі гроші',
      'турнік чи лава, що купити',
      'облаштувати домашній зал у гаражі',
      'что купить для домашнего зала',
      'какие гантели купить домой',
    ],
    facets: {
      what: [
        'By value: adjustable dumbbells, then a bench, a pull-up bar and bands; later a rack, barbell and plates.',
        'За цінністю: розбірні гантелі, потім лава, турнік і резинки; згодом рама, штанга й млинці.',
      ],
      why: [
        'Dumbbells, a bench, a pull-up bar and bands cover about 90% of exercises for little space and money.',
        'Гантелі, лава, турнік і резинки покривають ~90% вправ, займаючи мало місця й грошей.',
      ],
      when: [
        'Add a rack and barbell once dumbbells get too light for your squats and presses.',
        'Раму й штангу додавай, коли гантелей стає замало для присіду та жимів.',
      ],
    },
  },

  // ---- meta ----
  what_can_i_ask: {
    ex: [
      'what can i ask you',
      'what can you do',
      'give me some examples',
      'what should i ask',
      'what kind of questions do you answer',
      'how do i use you',
      'examples of questions',
      'what are you able to help with',
      'show me what to ask',
      'list of things i can ask',
      "i don't know what to ask",
      'what topics do you know',
      'any example questions',
      'what can i ask atlas',
    ],
    exUk: [
      'що можна спитати',
      'що ти вмієш',
      'приклади питань',
      'що питати',
      'про що тебе можна питати',
      'як тобою користуватися',
      'дай приклади запитань',
      'з чим ти можеш допомогти',
      'не знаю що спитати',
      'які теми ти знаєш',
      'покажи що можна питати',
      'шо в тебе можна питати',
      'что можно спросить',
      'что ты умеешь',
    ],
    facets: {
      what: [
        'Anything about your training: what to train today, next weight, recovery, progress, plates, percentages and alternatives.',
        'Будь-що про тренування: що тренувати сьогодні, наступна вага, відновлення, прогрес, млинці, відсотки й заміни.',
      ],
      how: [
        'Ask in your own words, then follow up with “why?” or “more” for detail.',
        'Питай своїми словами, а далі — «чому?» чи «детальніше».',
      ],
    },
  },
  reminder: {
    ex: [
      'remind me to train tomorrow',
      'set a reminder for my workout',
      'can you remind me to go to the gym',
      'remind me at 6 pm to lift',
      'set an alarm for training',
      'can you send me reminders',
      'workout reminder please',
      'remind me to take creatine',
      'do you have reminders',
      'remind me on monday about leg day',
      'how do i get gym reminders',
      'reminder to stretch every evening',
      'remind me to weigh myself',
      'can you set a reminder',
    ],
    exUk: [
      'нагадай мені про тренування завтра',
      'постав нагадування на тренування',
      'нагадай піти в зал',
      'нагадай о 18:00 про зал',
      'постав будильник на тренування',
      'можеш надсилати нагадування',
      'нагадування про тренування',
      'нагадай випити креатин',
      'в тебе є нагадування?',
      'нагадай у понеділок про ноги',
      'як отримувати нагадування',
      'нагадай зважитися',
      'напомни про тренировку',
      'поставь напоминание на зал',
    ],
    facets: {
      what: [
        'Atlas reminds you by itself when you skip a usual training day and on Sunday evening. Custom reminders aren’t available yet.',
        'Atlas сам нагадує, коли пропускаєш звичний день тренування, і в неділю ввечері. Власних нагадувань поки нема.',
      ],
      how: [
        'Turn on notifications for the app to get those reminders.',
        'Увімкни нотифікації застосунку, щоб отримувати ці нагадування.',
      ],
      when: [
        'When you miss a day you usually train, and on Sunday evening.',
        'Коли пропускаєш день, у який зазвичай тренуєшся, і в неділю ввечері.',
      ],
    },
  },
  memory_show: {
    ex: [
      'what do you know about me',
      'what do you remember about me',
      'what do you remember',
      'tell me what you know about me',
      'what have i told you about myself',
      'do you remember my injuries',
      'what info do you keep on me',
      'show me what you remember',
      'what do you know about my goals',
      "what's stored about me",
      'do you know anything about me',
      'what do you have in memory about me',
      'list what you remember about me',
      'what do you know about me so far',
    ],
    exUk: [
      'що ти знаєш про мене',
      'що ти пам’ятаєш про мене',
      'що ти памятаєш',
      'що ти про мене знаєш',
      'що я тобі розповідав про себе',
      'пам’ятаєш мої травми',
      'покажи, що ти пам’ятаєш',
      'що в тебе збережено про мене',
      'що знаєш про мене на даний момент',
      'ти щось знаєш про мене',
      'памятаєш мою мету',
      'що ти про мене памятаєш',
      'что ты знаешь обо мне',
      'что помнишь обо мне',
    ],
    facets: {
      what: [
        'Things you’ve told Atlas beyond your log: injuries, your goal, time per session, lifts you avoid.',
        'Те, що ти розповідав Atlas, окрім журналу: травми, мета, час на тренування, вправи, яких уникаєш.',
      ],
      how: [
        'Just tell Atlas in chat, like “my knee hurts” or “I have 45 minutes”, and it’s remembered.',
        'Просто скажи в чаті, напр. «болить коліно» чи «маю 45 хвилин», — і це запам’ятається.',
      ],
      why: [
        'So plans and answers fit you, for example going lighter on a sore area.',
        'Щоб плани й відповіді пасували тобі, наприклад легше там, де болить.',
      ],
    },
  },
  memory_forget: {
    ex: [
      'forget everything about me',
      'forget it',
      'wipe what you know about me',
      'erase everything you remember',
      'forget all that',
      'please forget what i told you',
      'forget me',
      'wipe all my info',
      'erase it all',
      'forget everything i said about my injury',
      'clear everything you know about me',
      'forget all of it',
      'i want you to forget everything',
      'wipe that',
    ],
    exUk: [
      'забудь усе про мене',
      'забудь це',
      'зітри все, що знаєш про мене',
      'забудь все',
      'стерти все про мене',
      'забудь, що я казав',
      'зітри це',
      'забудь мене',
      'хочу щоб ти забув усе',
      'зітри все про мої травми',
      'забудь про мене все',
      'забудь усе, що я розповідав',
      'забудь все обо мне',
      'сотри это',
    ],
    facets: {
      what: [
        'It wipes what you told Atlas (injuries, goal, lifts you avoid). Your workout log stays.',
        'Стирає те, що ти розповідав Atlas (травми, мету, вправи, яких уникаєш). Журнал тренувань лишається.',
      ],
      how: ['Say “forget it” and confirm with a tap.', 'Скажи «забудь» і підтверди натисканням.'],
    },
  },

  // ---- actions ----
  act_rest: {
    ex: [
      'set rest for bench to 3 minutes',
      'make rest on squat 2 minutes',
      'change rest for deadlift to 4 min',
      'set my rest time on pull-ups to 90 seconds',
      'put rest for overhead press at 2:30',
      'set rest between sets of rows to 2 minutes',
      'change bench rest to 150 seconds',
      'make squat rest 3 minutes from now on',
      'set rest on lat pulldown to 60 seconds',
      'use 2 min rest for dips',
      'set rest timer for deadlift to 5 minutes',
      'change rest for barbell rows to 90 sec',
      'rest on bench: set it to 3:00',
      'make rest 45 seconds for bicep curls',
    ],
    exUk: [
      'постав відпочинок для жиму лежачи 3 хвилини',
      'зроби відпочинок на присіді 2 хвилини',
      'зміни відпочинок у становій на 4 хв',
      'встанови паузу на підтягуваннях 90 секунд',
      'постав відпочинок 2:30 на армійському жимі',
      'зміни відпочинок між підходами тяги в нахилі на 2 хвилини',
      'хочу відпочинок 3 хвилини на присід',
      'постав паузу 60 секунд на тязі верхнього блоку',
      'зроби відпочинок 2 хв для брусів',
      'встанови таймер відпочинку на становій 5 хвилин',
      'постав перерву 90 сек на жим гантелей',
      'змінити відпочинок на жимі на 150 секунд',
      'поставь отдых на жиме 3 минуты',
      'сделай отдых в приседе 2 минуты',
    ],
  },
  act_swap: {
    ex: [
      'swap bench for dumbbell press',
      'replace squat with leg press',
      'switch deadlift to romanian deadlift',
      'change barbell rows to cable rows',
      'use dumbbell press instead of bench press',
      'give me lat pulldown instead of pull-ups',
      'replace overhead press with dumbbell shoulder press',
      'swap back squat for front squat',
      'switch dips to close-grip bench',
      'instead of deadlift do trap bar deadlift',
      'swap leg press for hack squat',
      'replace pull ups with lat pulldown in my plan',
      'change bench press to incline dumbbell press',
      'swap lunges for split squats',
    ],
    exUk: [
      'заміни жим лежачи на жим гантелей',
      'заміни присід на жим ногами',
      'поміняй станову на румунську тягу',
      'заміни тягу в нахилі на тягу горизонтального блоку',
      'жим гантелей замість жиму лежачи',
      'дай тягу верхнього блоку замість підтягувань',
      'поміняй армійський жим на жим гантелей сидячи',
      'заміни присід на фронтальний присід',
      'замість брусів жим вузьким хватом',
      'поміняти жим ногами на гак-присід',
      'заміню випади на болгарські присідання',
      'замість станової роби тягу з трап-грифом',
      'замени жим лежа на жим гантелей',
      'вместо приседа жим ногами',
    ],
  },
  act_avoid: {
    ex: [
      'remove deadlift from my plan',
      'drop bench press from my program',
      'never give me squats',
      'exclude pull-ups from the plan',
      'no more overhead press in my programme',
      'remove barbell rows from my plans',
      'drop dips from my plan for good',
      'never put lunges in my plan',
      'exclude leg press from my program',
      'remove the deadlift from the programme',
      'no more burpees from you',
      'drop romanian deadlift from my plans',
      'never give me good mornings',
      'exclude upright rows from my program',
    ],
    exUk: [
      'прибери станову з плану',
      'викинь жим лежачи з програми',
      'більше не давай присід',
      'виключи підтягування з плану',
      'прибери армійський жим з програми',
      'більше не пропонуй тягу в нахилі',
      'викинь бруси з плану назавжди',
      'виключи випади з програми',
      'прибрати жим ногами з плану',
      'більше не давай берпі',
      'прибери румунську тягу з програми',
      'викинь гуд моргнінг із плану',
      'убери становую из программы',
      'исключи присед из плана',
    ],
  },
  act_move: {
    ex: [
      'move legs to thursday',
      "move today's workout to tomorrow",
      'shift push day to friday',
      'reschedule legs to saturday',
      'move monday to tuesday',
      'move upper day to wednesday',
      "shift today's session to sunday",
      'reschedule pull day to thursday',
      "move tomorrow's workout to friday",
      'move lower to saturday',
      "shift friday's workout to saturday",
      'move full body from wednesday to thursday',
      'reschedule today to tomorrow',
      'move leg day to monday',
    ],
    exUk: [
      'перенеси ноги на четвер',
      'перенеси сьогоднішнє тренування на завтра',
      'пересунь жимовий день на пятницю',
      'перенести ноги на суботу',
      'перенеси понеділок на вівторок',
      'перенеси верх на середу',
      'перенеси сьогоднішнє на неділю',
      'пересунь тяговий день на четвер',
      'перенеси завтрашнє тренування на пятницю',
      'перенесемо низ на суботу',
      'перенеси пятницю на суботу',
      'перенести фулбаді з середи на четвер',
      'перенеси ноги на понеділок',
      'перенеси тренировку на завтра',
    ],
  },
  act_start: {
    ex: [
      'start my workout',
      'start a workout',
      "begin today's session",
      "let's go, start training",
      'kick off my workout',
      'start the session',
      'begin workout now',
      "start today's workout",
      'lets go gym',
      'start training now',
      'begin my training',
      'start a new session',
      'kick off the gym session',
      'start workout please',
    ],
    exUk: [
      'почни тренування',
      'почати тренування',
      'починаємо тренування',
      'стартуй тренування',
      'погнали тренуватись',
      'поїхали, тренування',
      'починай заняття',
      'почни сьогоднішнє тренування',
      'старт тренування',
      'погнали в зал',
      'почати заняття зараз',
      'починай трен',
      'начни тренировку',
      'начинаем тренировку',
    ],
  },
  act_temper: {
    ex: [
      'be nicer',
      'be kinder to me',
      'talk softer',
      'be meaner',
      'be harsher with me',
      'be stricter',
      'switch to drill sergeant',
      'become merciless',
      'talk to me in a warm tone',
      'be blunt',
      'speak gentler please',
      'be tougher on me',
      'switch tone to steady',
      'can you be a bit milder',
    ],
    exUk: [
      'будь добріше',
      'будь м’якше',
      'говори лагідніше',
      'будь жорсткіше',
      'будь суворіше зі мною',
      'стань безжальним',
      'перейди на сержанта',
      'будь теплим',
      'говори спокійніше',
      'будь прямим',
      'зміни тон на спокійний',
      'стань зліше',
      'будь мягче',
      'будь жестче',
    ],
  },
  act_mute: {
    ex: [
      'mute notifications today',
      'mute for today',
      'quiet today please',
      'silence notifications',
      'shut up today',
      'mute messages',
      'no pushes today, mute',
      'silence your notes today',
      'mute pushes',
      'quiet the notifications',
      'mute yourself today',
      'silence messages for today',
      'mute atlas notifications',
      'be quiet today, no notifications',
    ],
    exUk: [
      'вимкни сповіщення сьогодні',
      'не пиши сьогодні',
      'не надсилай повідомлення сьогодні',
      'замовкни сьогодні',
      'помовч сьогодні',
      'тихо сьогодні',
      'вимкни пуші',
      'заглуши сповіщення',
      'сьогодні не надсилай нотатки',
      'вимкни повідомлення на сьогодні',
      'не пиши мені сповіщення',
      'заглуши пуші на сьогодні',
      'замолчи сегодня',
      'выключи уведомления сегодня',
    ],
  },
  act_bodyweight: {
    ex: [
      'i weigh 82 kg',
      'i weigh 75.5 kg today',
      'my weight is 90 kg',
      'weighed 68 kg this morning',
      'log my weight 80 kg',
      'i weighed in at 77.3',
      'my weight today 84 kg',
      'weigh 72 kg',
      'i weigh 101 kg now',
      'morning weigh-in: 79.8 kg',
      'my weight 65 kg',
      'i weighed 88 this morning',
      'record my weight 70.2 kg',
      'i weigh 95',
    ],
    exUk: [
      'я важу 82 кг',
      'важу 75,5 кг сьогодні',
      'моя вага 90 кг',
      'зважився зранку — 68 кг',
      'зважилась, 57 кг',
      'запиши моя вага 80 кг',
      'сьогодні важу 84',
      'моя вага сьогодні 72,4 кг',
      'важу 101 кг',
      'зважився: 79,8',
      'моя вага 65 кг',
      'запиши, важу 88',
      'я вешу 82 кг',
      'мой вес 75 кг',
    ],
  },

  // ---- time windows ----
  range_count: {
    ex: [
      'how many workouts did i do last month',
      'how many sessions in the last 3 months',
      'how many times did i train this month',
      'how often did i go to the gym since june',
      'how many workouts last week',
      'how many sessions this year',
      'how many times did i train in the last 30 days',
      'how often have i trained over the last 6 weeks',
      'how many gym sessions since january',
      'how many workouts in the past 2 weeks',
      'number of sessions this month, how many',
      'how many times did i work out in august',
      'how often did i train last month',
      'how many workouts have i done this week',
    ],
    exUk: [
      'скільки тренувань було минулого місяця',
      'скільки тренувань за останні 3 місяці',
      'скільки разів я тренувався цього місяця',
      'як часто я ходив у зал з червня',
      'скільки тренувань минулого тижня',
      'скільки тренувань цього року',
      'скільки разів тренувався за останні 30 днів',
      'як часто я тренувався за останні 6 тижнів',
      'скільки тренувань з січня',
      'скільки занять за останні 2 тижні',
      'скільки разів у серпні був у залі',
      'скільки я тренувалась цього тижня',
      'сколько тренировок было в прошлом месяце',
      'сколько раз тренировался за последние 3 месяца',
    ],
    facets: {
      what: [
        'It counts finished sessions and working sets in that window, plus a per-week average for longer windows.',
        'Рахує завершені тренування й робочі сети за цей період, а для довших — ще й середнє на тиждень.',
      ],
      howMuch: [
        'For most goals, 2–4 sessions a week done consistently is plenty.',
        'Для більшості цілей 2–4 регулярні тренування на тиждень — достатньо.',
      ],
      where: [
        'For windows of 3+ weeks a sessions-per-week chart appears under the answer.',
        'Для періодів від 3 тижнів під відповіддю з’являється графік тренувань на тиждень.',
      ],
    },
  },
  range_summary: {
    ex: [
      'what did i do last month',
      'summary of the last 3 months',
      'recap of this month',
      'give me an overview of last week',
      'how was my training in august',
      'report for the last 30 days',
      'how did last month go',
      'recap since june',
      'summarize my training this year',
      'overview of the past 2 weeks',
      'what did i do this week',
      'how was the last 6 weeks',
      'monthly recap for september',
      'summary of my workouts since january',
    ],
    exUk: [
      'що я робив минулого місяця',
      'підсумок за останні 3 місяці',
      'підсумки цього місяця',
      'огляд минулого тижня',
      'як пройшов серпень у залі',
      'звіт за останні 30 днів',
      'як минув минулий місяць',
      'підсумок з червня',
      'як пройшли останні 2 тижні',
      'що я робив цього тижня',
      'огляд тренувань за цей рік',
      'як пройшли останні 6 тижнів',
      'итог за прошлый месяц',
      'что я делал за последние 3 месяца',
    ],
    facets: {
      what: [
        'A recap of the window: sessions, working sets, your most-done lifts and any new bests.',
        'Підсумок періоду: тренування, робочі сети, найчастіші вправи й нові рекорди.',
      ],
      how: [
        'New bests compare your estimated max in the window with everything logged before it.',
        'Нові рекорди — це порівняння розрахункового максимуму за період з усім, що було до нього.',
      ],
    },
  },
  range_lift: {
    ex: [
      'how did my bench progress over the last 3 months',
      'squat progress since june',
      'best deadlift this month',
      'how has my overhead press changed in the last 6 weeks',
      'bench max last month',
      'how is my squat going since january',
      'deadlift record this year',
      'did my bench grow in the last 2 months',
      'pull-ups progress over the past 4 weeks',
      'how did rows go last month',
      'my squat in the last 90 days',
      'bench press progress this year',
      'how has deadlift changed since march',
      'overhead press best in the last 3 months',
    ],
    exUk: [
      'як прогресував жим лежачи за останні 3 місяці',
      'прогрес у присіді з червня',
      'рекорд у становій цього місяця',
      'як змінився армійський жим за останні 6 тижнів',
      'максимум у жимі минулого місяця',
      'як росте присід з січня',
      'рекорд станової цього року',
      'чи зріс жим за останні 2 місяці',
      'прогрес у підтягуваннях за останні 4 тижні',
      'динаміка присіду за останні 90 днів',
      'як тяга в нахилі минулого місяця',
      'жим лежачи прогрес цього року',
      'как вырос жим за последние 3 месяца',
      'прогресс в приседе с июня',
    ],
    facets: {
      what: [
        'It shows the estimated max for that lift at the start and end of the window, the % change and the best.',
        'Показує розрахунковий максимум у вправі на початку й наприкінці періоду, зміну у % і найкращий результат.',
      ],
      how: [
        'Estimated max comes from your working sets of up to 12 reps in each session.',
        'Розрахунковий максимум — з робочих сетів до 12 повторів у кожному тренуванні.',
      ],
      where: [
        'With 2 or more sessions in the window a chart appears under the answer.',
        'Якщо за період 2+ тренування, під відповіддю з’являється графік.',
      ],
    },
  },
  range_muscle: {
    ex: [
      'how many sets for chest last month',
      'back volume in the last 3 months',
      'how many sets did i do for legs this week',
      'shoulder sets since june',
      'chest volume last week',
      'how much did i train biceps this month',
      'glute sets in the past 4 weeks',
      'how many sets for back in the last 30 days',
      'quad volume this month',
      'triceps work last month',
      'hamstring sets since august',
      'how many sets of chest in the last 2 weeks',
      'how much volume for delts this month',
      'calves sets over the last 6 weeks',
    ],
    exUk: [
      'скільки сетів на груди минулого місяця',
      'обсяг на спину за останні 3 місяці',
      'скільки підходів на ноги цього тижня',
      'сети на плечі з червня',
      'обсяг грудей минулого тижня',
      'скільки я тренував біцепс цього місяця',
      'скільки сетів на сідниці за останні 4 тижні',
      'навантаження на спину за останні 30 днів',
      'скільки підходів на квадрицепс цього місяця',
      'трицепс минулого місяця, скільки сетів',
      'сети на біцепс стегна з серпня',
      'обсяг на дельти цього місяця',
      'сколько подходов на грудь в прошлом месяце',
      'объем на спину за последние 3 месяца',
    ],
    facets: {
      what: [
        'Working sets for that muscle in the window, with a weekly average for windows of 2+ weeks.',
        'Робочі сети на цей м’яз за період, а для 2+ тижнів — середнє на тиждень.',
      ],
      howMuch: [
        'Roughly 10–20 hard sets per muscle a week works for most people.',
        'Приблизно 10–20 робочих сетів на м’яз за тиждень підходить більшості.',
      ],
      how: [
        'Sets are credited to a muscle based on each exercise’s primary and secondary muscles.',
        'Сети зараховуються м’язу за основними й допоміжними м’язами кожної вправи.',
      ],
    },
  },
  range_bw: {
    ex: [
      'how did my weight change in the last 3 months',
      'bodyweight since june',
      'my weight this month',
      'weight trend over the last 6 weeks',
      'how much did i weigh last month compared to now',
      'bodyweight change this year',
      'did i gain weight in the last 2 months',
      'how much weight have i lost since january',
      'scale trend last month',
      'my weigh-ins over the past 4 weeks',
      'bodyweight over the last 90 days',
      'weight change since march',
      'did my weight go down this month',
      'weight last week',
    ],
    exUk: [
      'як змінилась вага за останні 3 місяці',
      'моя вага з червня',
      'вага цього місяця',
      'динаміка ваги за останні 6 тижнів',
      'скільки я важив минулого місяця',
      'зміна ваги тіла цього року',
      'я набрав вагу за останні 2 місяці?',
      'скільки ваги скинув з січня',
      'зважування за останні 4 тижні',
      'вага тіла за останні 90 днів',
      'вага з березня',
      'вага минулого тижня',
      'как изменился вес за последние 3 месяца',
      'мой вес с июня',
    ],
    facets: {
      what: [
        'It compares your first and last weigh-in in the window and shows the change in kg.',
        'Порівнює перше й останнє зважування за період і показує зміну в кг.',
      ],
      how: [
        'Weigh in a few times a week, same time of day, and judge the trend, not single days.',
        'Зважуйся кілька разів на тиждень в один і той самий час і дивись на тенденцію, а не на окремі дні.',
      ],
      howMuch: [
        'It needs at least 2 weigh-ins in the window.',
        'Потрібно щонайменше 2 зважування за період.',
      ],
      where: [
        'Log weigh-ins by telling Atlas “I weigh 82 kg” or in body metrics.',
        'Записуй зважування, сказавши Atlas «я важу 82 кг», або в показниках тіла.',
      ],
    },
  },
  then_vs_now: {
    ex: [
      'am i stronger than 3 months ago',
      'compare me now to 6 months ago',
      'am i weaker than a year ago',
      'have i progressed since 2 months ago',
      'am i better than i was 4 weeks ago',
      'how have i changed since 3 months ago',
      'stronger now than last year',
      'compare my lifts to 6 weeks ago',
      'am i stronger than last month',
      'progress compared to half a year ago',
      'then vs now, 3 months ago',
      'is my bench stronger than 2 months ago',
      'am i weaker than i was in spring, 5 months ago',
      'compared to a year ago am i stronger',
    ],
    exUk: [
      'я сильніший ніж 3 місяці тому',
      'порівняй мене зараз і пів року тому',
      'я слабший ніж рік тому',
      'чи є прогрес порівняно з 2 місяцями тому',
      'я краще ніж 4 тижні тому',
      'як я змінився за 3 місяці',
      'сильніший ніж минулого року',
      'порівняти мої вправи з тим, що було 6 тижнів тому',
      'я сильніша ніж місяць тому',
      'прогрес порівняно з півроку тому',
      'чи жим сильніший ніж 2 місяці тому',
      'порівняй присід зараз і 3 місяці тому',
      'я сильнее чем 3 месяца назад',
      'сравни меня с тем, что было полгода назад',
    ],
    facets: {
      what: [
        'It compares your best estimated max around that time with the last 4 weeks, for your main lifts or one you name.',
        'Порівнює найкращий розрахунковий максимум тоді з останніми 4 тижнями — для основних вправ або названої.',
      ],
      how: [
        'It looks at a ±2-week window around the date back then, so a single off day doesn’t skew it.',
        'Береться вікно ±2 тижні навколо тієї дати, щоб один невдалий день не спотворив результат.',
      ],
      why: [
        'If you’re not stronger, common reasons are too little volume, poor recovery or stalled weights — worth a look.',
        'Якщо не сильніший, типові причини — замалий обсяг, погане відновлення чи застій у вазі — варто розібратися.',
      ],
    },
  },

  // ---- comparisons ----
  compare_lifts: {
    ex: [
      'compare my bench and squat',
      'bench vs squat',
      'is my deadlift stronger than my squat',
      'squat to deadlift ratio',
      'is my bench lagging behind my squat',
      'bench versus overhead press',
      'which is lagging, squat or deadlift',
      'compare deadlift and bench',
      'squat vs deadlift progress',
      'my bench is weaker than my squat, is that normal',
      'ratio of overhead press to bench',
      'pull-ups vs rows, which is stronger',
      'is my squat lagging compared to deadlift',
      'bench compared to squat ratio',
    ],
    exUk: [
      'порівняй жим лежачи і присід',
      'жим проти присіду',
      'станова сильніша ніж присід?',
      'співвідношення присіду і станової',
      'жим відстає від присіду',
      'жим лежачи проти армійського жиму',
      'що відстає, присід чи станова',
      'порівняти станову і жим',
      'присід і станова, порівняння прогресу',
      'мій жим слабший ніж присід, це нормально',
      'співвідношення армійського жиму і жиму лежачи',
      'підтягування проти тяги в нахилі',
      'сравни жим и присед',
      'становая сильнее чем присед?',
    ],
    facets: {
      what: [
        'It compares both lifts’ estimated max over the last 8 weeks, their ratio and which one is progressing slower.',
        'Порівнює розрахунковий максимум обох вправ за останні 8 тижнів, їхнє співвідношення й те, яка прогресує повільніше.',
      ],
      howMuch: [
        'Typical ratios: squat ≈ 1.2–1.3× bench, deadlift ≈ 1.2× squat. Individual builds vary.',
        'Типові співвідношення: присід ≈ 1,2–1,3× жиму, станова ≈ 1,2× присіду. У кожного по-різному.',
      ],
      should: [
        'Only worry about a lagging lift if it keeps stalling; then give it a bit more priority or volume.',
        'Переймайся вправою, що відстає, лише якщо вона стабільно стоїть; тоді дай їй трохи більше пріоритету чи обсягу.',
      ],
    },
  },

  // ---- reasons behind the plan ----
  why_today: {
    ex: [
      'why this workout today',
      'why am i training legs today',
      'why chest today',
      'how come today is back day',
      "why is today's session this one",
      'why do i have to train today',
      'why these muscles today',
      'why today and not tomorrow',
      'why did you pick this session for today',
      'why is today push day',
      "how come i'm doing upper today",
      'why this session',
      'why is today a lighter day',
      'why arms today',
    ],
    exUk: [
      'чому сьогодні це тренування',
      'чому сьогодні ноги',
      'чому груди сьогодні',
      'чого сьогодні спина',
      'навіщо сьогодні тренуватись',
      'чому ці м’язи сьогодні',
      'чому сьогоднішнє тренування таке',
      'чого сьогодні верх',
      'чому саме сьогодні',
      'нащо сьогодні руки',
      'чому цей день такий',
      'чому сьогодні легше',
      'почему сегодня ноги',
      'зачем сегодня эта тренировка',
    ],
    facets: {
      why: [
        'Today comes from your plan day for this weekday, or what you usually train on it, and it favours muscles that have recovered.',
        'Сьогоднішнє береться з дня плану на цей день тижня або з того, що ти зазвичай тренуєш у цей день, з перевагою відновлених м’язів.',
      ],
      how: [
        'Recovery is judged by days since each muscle was last trained.',
        'Відновлення оцінюється за днями від останнього тренування кожного м’яза.',
      ],
      when: [
        'On a planned lighter week the same day has fewer sets.',
        'У запланований легший тиждень той самий день має менше сетів.',
      ],
    },
  },
  why_weight: {
    ex: [
      'why is bench lighter today',
      'why did the weight go up on squat',
      'why so heavy on deadlift',
      'why did you drop my bench weight',
      'why 100 kg on squat',
      'why is my overhead press weight lower',
      'why more weight on rows',
      'how come the deadlift weight dropped',
      "why didn't the bench weight increase",
      'why is squat heavier than last time',
      'why less kg on bench this week',
      'why this weight for pull-ups',
      'why did you lower my squat',
      'why is the deadlift weight the same',
    ],
    exUk: [
      'чому жим лежачи легший сьогодні',
      'чому вага на присіді зросла',
      'чого так важко на становій',
      'чому ти зменшив вагу на жимі',
      'чому 100 кг на присіді',
      'чому армійський жим менше кг',
      'чому більше ваги на тязі в нахилі',
      'чого на становій скинув вагу',
      'чому на жимі вага не росте',
      'чому присід важчий ніж минулого разу',
      'чому менше кг на жимі цього тижня',
      'навіщо зменшувати вагу в присіді',
      'почему вес на жиме меньше',
      'почему в приседе тяжелее',
    ],
    facets: {
      why: [
        'Hit the top of the rep range and the weight goes up; not there yet and you add reps first; stalled 3 sessions and it backs off slightly.',
        'Дійшов до верху діапазону повторів — вага росте; ще ні — спершу більше повторів; застій 3 тренування — невеликий відкат.',
      ],
      when: [
        'It also drops on a lighter week, or where you told Atlas something is sore.',
        'Також менше в легший тиждень або там, де ти казав Atlas, що болить.',
      ],
      how: [
        'It’s based on your last top sets for that lift; with no history it starts light.',
        'Базується на твоїх останніх найкращих сетах у вправі; без історії починає легко.',
      ],
    },
  },
  why_plan: {
    ex: [
      'why this plan',
      'why is my program set up like this',
      'why these days',
      'why this split',
      'why 3 days a week in my programme',
      'how come my plan is on these days',
      'why this schedule',
      'why did you pick this program',
      'why is my plan so short',
      'why an upper lower split',
      'why is there a light week in my plan',
      'why is my programme built this way',
      'why these training days',
      'how come this split for me',
    ],
    exUk: [
      'чому такий план',
      'чому програма саме така',
      'чому ці дні',
      'чому такий спліт',
      'чому 3 дні на тиждень у програмі',
      'навіщо такий розклад',
      'чому ти вибрав таку програму',
      'чому план такий короткий',
      'нащо спліт верх-низ',
      'чому в плані легкий тиждень',
      'чого програма так побудована',
      'чому тренування в ці дні',
      'почему такая программа',
      'зачем такой сплит',
    ],
    facets: {
      why: [
        'The plan follows how you already train: your average sessions a week, your usual days, typical session length and rep range.',
        'План повторює те, як ти вже тренуєшся: середню кількість тренувань на тиждень, звичні дні, тривалість і діапазон повторів.',
      ],
      when: [
        'Every few weeks there’s a lighter week so you recover.',
        'Раз на кілька тижнів — легший тиждень для відновлення.',
      ],
      how: [
        'Change it by moving days or swapping lifts, for example “move legs to Thursday”.',
        'Змінюй, переносячи дні чи замінюючи вправи, напр. «перенеси ноги на четвер».',
      ],
    },
  },
  why_lift: {
    ex: [
      'why bench press in my plan',
      'why this exercise, squats',
      'why deadlift in my program',
      'why pull-ups in my plan',
      'why do you give me overhead press',
      'why is romanian deadlift in my plan',
      'why this lift, barbell rows',
      'why lunges this one',
      'how come leg press is in my plan',
      'why lat pulldown exercise',
      'why dips in my plan',
      'why this exercise, hip thrust',
      'why the front squat lift',
      'why incline bench in my plan',
    ],
    exUk: [
      'чому жим лежачи в плані',
      'навіщо ця вправа, присід',
      'чому станова у плані',
      'чому підтягування в плані',
      'навіщо армійський жим у плані',
      'чому румунська тяга в плані',
      'нащо ця вправа — тяга в нахилі',
      'чого випади в плані',
      'чому жим ногами у плані',
      'навіщо тяга верхнього блоку, ця вправа',
      'чому бруси в плані',
      'чому ви дали сідничний міст',
      'почему жим лежа в плане',
      'зачем это упражнение, присед',
    ],
    facets: {
      why: [
        'Either it’s one of your staples, so progress on it is easiest to track, or it’s the top pick for that muscle with your gym’s kit.',
        'Або це одна з твоїх основних вправ, тож прогрес по ній найлегше відстежити, або найкращий вибір для цього м’яза з обладнанням твого залу.',
      ],
      how: [
        'Don’t like it? Say “swap it for …” and the replacement goes into your plans.',
        'Не подобається? Скажи «заміни на …» — і заміна піде в плани.',
      ],
    },
  },
};
