import type { Kb } from './types';

export const KB_B: Kb = {
  injury_status: {
    ex: [
      'what stage is my injury at',
      'how is my injury rehab going',
      'injury status',
      'where am i with my shoulder rehab',
      "what's the status of my knee injury",
      'am i still in rehab',
      'which rehab stage am i on',
      'how far along is my injury recovery',
      'is my injury still marked active',
      'show my injury progress',
      'what phase of rehab is my back in',
      'how is the injured elbow coming along',
      'do i have any active injuries logged',
      'how many check-ins until the next rehab stage',
      'update me on my rehab',
      'is my wrist injury still in the protect phase',
    ],
    exUk: [
      'на якому етапі моя травма',
      'як там моя реабілітація',
      'статус травми',
      'який зараз етап відновлення після травми',
      'як просувається реабілітація плеча',
      'я ще на реабілітації?',
      'травма ще активна?',
      'покажи прогрес по травмі',
      'що там з моїм коліном по етапах',
      'скільки ще відміток до наступного етапу реабілітації',
      'на якій я стадії реабілітації спини',
      'в мене є активні травми?',
      'як стан травми ліктя',
      'шо там по травмі, де я зараз',
      'на каком этапе моя травма',
      'как идет реабилитация',
    ],
    facets: {
      what: [
        'Each logged injury moves through rehab stages, from protecting the area to gradually loading it again, until it is cleared.',
        'Кожна записана травма проходить етапи реабілітації: від захисту ділянки до поступового навантаження, аж поки її не закрито.',
      ],
      how: [
        'Check in on the Injury screen after sessions; two good check-ins in a row move you to the next stage.',
        'Відмічайся на екрані «Травми» після тренувань; два добрі відгуки поспіль переводять на наступний етап.',
      ],
      where: [
        'Profile menu, then Injury: it shows the current stage and the check-in button.',
        'Меню профілю, далі «Травми»: там видно поточний етап і кнопку відмітки.',
      ],
      should: [
        'Move on only when the area feels good in training; if pain returns or gets sharper, stay at the current stage and see a doctor or physio.',
        'Переходь далі лише тоді, коли ділянка добре почувається на тренуваннях; якщо біль повертається чи гострішає — лишайся на етапі й звернись до лікаря чи фізіотерапевта.',
      ],
    },
  },

  overtraining: {
    ex: [
      'am i overtraining',
      'am i doing too much',
      'is this too much volume for me',
      "i think i'm burning out",
      "how do i know if i'm overtrained",
      'signs of overtraining',
      'am i training too hard',
      'feeling burnt out from the gym',
      'is my weekly volume too high',
      'could i be overreaching',
      'too many sets this week?',
      'am i doing more than i can recover from',
      'training 6 days, is that overtraining',
      'burnout from lifting',
      'is overtraining real',
      'why do i feel fried after weeks of hard training',
    ],
    exUk: [
      'у мене перетренованість?',
      'я не перетреновуюсь?',
      'чи не забагато я тренуюсь',
      'здається, я вигорів від залу',
      'ознаки перетренованості',
      'забагато сетів цього тижня?',
      'чи не завеликий у мене обсяг',
      'я не перевантажую себе?',
      'вигорання від тренувань',
      'як зрозуміти що перетренувався',
      'тренуюсь 6 днів, це не забагато?',
      'чи встигаю я відновлюватись від такого обсягу',
      'шось я перетренувався походу',
      'я не перегружаю организм',
      'у меня перетрен?',
    ],
    facets: {
      what: [
        'True overtraining is rare; most people are simply under-recovered: poor sleep, not enough food, or weekly sets above what they can recover from.',
        'Справжня перетренованість рідкісна; частіше це просто недовідновлення: поганий сон, мало їжі або тижневих сетів більше, ніж встигаєш відновити.',
      ],
      how: [
        'Watch for falling performance over 2+ weeks, bad sleep, persistent fatigue and low mood. Compare your weekly sets per muscle with the recoverable limit.',
        'Стеж за падінням результатів 2+ тижні, поганим сном, постійною втомою й поганим настроєм. Порівняй тижневі сети на м’яз із межею відновлення.',
      ],
      should: [
        'If a muscle is over its recoverable limit, cut its sets by about a third; if sleep is short, fix that first.',
        'Якщо м’яз понад межу відновлення — зріж його сети приблизно на третину; якщо мало сну — спершу виправ це.',
      ],
      why: [
        'Growth happens during recovery; when volume, stress and short sleep exceed it, performance stalls and then drops.',
        'Ріст відбувається під час відновлення; коли обсяг, стрес і недосип його перевищують, результати стоять, а потім падають.',
      ],
    },
  },

  train_sore: {
    ex: [
      'should i train when sore',
      'can i work out with doms',
      'still sore from last session, should i train',
      'is it ok to lift while sore',
      'my legs are sore, should i squat today',
      'train through soreness?',
      "can i hit chest again if it's still sore",
      'should i skip the gym if my muscles ache',
      'is it bad to work out sore muscles',
      'sore from yesterday, gym or rest',
      'do i need to wait until soreness is gone',
      'can i deadlift with sore hamstrings',
      'working out with muscle soreness',
      'still have doms, is training ok',
      "should i lift if i'm really sore",
    ],
    exUk: [
      'чи можна тренуватись з крепатурою',
      'крепатура, йти в зал?',
      'болять м’язи після вчора, тренуватись?',
      'ноги болять, присідати сьогодні?',
      'чи варто пропустити, якщо ниють м’язи',
      'можна качати груди, якщо ще болять',
      'треба чекати поки пройде крепатура?',
      'тренуватись через крепатуру нормально?',
      'м’язи ще забиті після станової, можна йти?',
      'у мене крепатура, що робити з тренуванням',
      'болять м’язи, чи не шкідливо тренуватись',
      'крепатура жесть, йти чи ні',
      'можно ли тренироваться при крепатуре',
      'мышцы болят, идти в зал?',
      'з крепатурою в зал можна?',
    ],
    facets: {
      should: [
        'Yes, normal soreness is not a reason to skip: train other muscles, or the same ones lighter. Sharp or one-sided pain is not soreness, so stop.',
        'Так, звичайна крепатура — не причина пропускати: тренуй інші м’язи або ті самі легше. Гострий чи однобічний біль — не крепатура, тоді стоп.',
      ],
      why: [
        'Soreness mostly reflects new or unusual work, not damage that must fully heal; light training often eases it.',
        'Крепатура здебільшого означає нове чи незвичне навантаження, а не пошкодження, яке мусить повністю загоїтись; легке тренування часто її полегшує.',
      ],
      how: [
        'Warm up well; if the first sets feel fine, carry on, and if the muscle stays stiff and weak, go lighter or train something else.',
        'Добре розімнись; якщо перші сети йдуть нормально — продовжуй, а якщо м’яз лишається скутим і слабким — легше або інша група.',
      ],
      when: [
        'Soreness usually peaks 24–72 hours after training and fades as you get used to the work.',
        'Крепатура зазвичай пікує через 24–72 години після тренування і слабшає, коли звикаєш до навантаження.',
      ],
    },
  },

  weaker_today: {
    ex: [
      'why am i weaker today',
      'feel weak today',
      'no strength today',
      'why is the bar so heavy today',
      'weights feel way heavier than usual',
      "i'm weaker than last week, why",
      "couldn't hit my usual bench today",
      'why did my squat feel so heavy',
      'had no power in the gym today',
      'why did my numbers drop this session',
      'feeling weaker than normal',
      'lifts felt terrible today',
      "why can't i lift what i did last time",
      'failed reps i usually get',
      'off day, everything felt heavy',
    ],
    exUk: [
      'чому я сьогодні слабший',
      'сьогодні нема сили',
      'вага сьогодні не йде',
      'чого штанга така важка сьогодні',
      'не зміг пожати свою звичну вагу',
      'сьогодні слабша ніж зазвичай',
      'чому впала сила на тренуванні',
      'все здається важчим ніж завжди',
      'не дожав повтори, які завжди роблю',
      'присід сьогодні йшов дуже важко, чому',
      'сьогодні взагалі не той день, сил нуль',
      'чому не можу підняти те, що минулого разу',
      'почему я сегодня слабее',
      'сил нет, вес не идет',
      'сьогодні якийсь дохлий, вага не йде',
    ],
    facets: {
      why: [
        'The usual suspects are sleep, food, stress and too little rest between sets; one bad day rarely means lost strength.',
        'Звичні причини — сон, їжа, стрес і замало відпочинку між сетами; один поганий день рідко означає втрату сили.',
      ],
      should: [
        'Yes, keep training but drop the weight 5–10% and hit your reps rather than grinding failed sets.',
        'Так, тренуйся далі, але скинь вагу на 5–10% і зроби повтори, а не дотискай провалені сети.',
      ],
      howMuch: [
        'Drop about 5–10% for the day; if it keeps happening for 2+ weeks, look at sleep and recovery.',
        'Скинь приблизно 5–10% на сьогодні; якщо так триває 2+ тижні — дивись на сон і відновлення.',
      ],
      how: [
        'Rest a full 2–3 minutes between heavy sets, eat something 1–3 hours before, and warm up properly.',
        'Відпочивай повні 2–3 хвилини між важкими сетами, поїж за 1–3 години до тренування й добре розімнись.',
      ],
    },
  },

  split_choice: {
    ex: [
      'full body or split',
      'which split should i do',
      'is ppl better than upper lower',
      'best split for 4 days a week',
      'push pull legs or full body',
      'what training split is best',
      'should i do a bro split',
      'upper lower vs full body',
      'what split for 3 days a week',
      'is full body good for building muscle',
      'how should i split my training days',
      'ppl 6 days worth it',
      'which workout split for hypertrophy',
      'best way to split muscle groups across the week',
      'one muscle per day or full body',
    ],
    exUk: [
      'фулбоді чи спліт',
      'який спліт обрати',
      'ppl краще за верх низ?',
      'який спліт на 4 дні на тиждень',
      'тренування на все тіло чи по групах',
      'як розбити м’язи по днях',
      'верх низ чи фул боді',
      'який найкращий спліт для маси',
      'спліт на 3 дні який',
      'пуш пул легс чи фулбоді',
      'качати одну групу в день чи все тіло',
      'який розподіл по днях краще',
      'какой сплит выбрать',
      'фулбади или сплит',
      'шо краще, спліт чи на все тіло',
    ],
    facets: {
      should: [
        'Pick by how many days you can train: 2–3 days full body, 4 days upper/lower, 5–6 days push/pull/legs.',
        'Обирай за кількістю днів: 2–3 дні — все тіло, 4 дні — верх/низ, 5–6 днів — push/pull/legs.',
      ],
      why: [
        'Each muscle grows best when hit about twice a week; these splits make that fit your schedule.',
        'Кожен м’яз найкраще росте, коли його тренуєш приблизно двічі на тиждень; ці спліти вписують це у твій графік.',
      ],
      what: [
        'A split is how you divide muscles or movements across training days, for example upper/lower or push/pull/legs.',
        'Спліт — це як ти розподіляєш м’язи чи рухи по тренувальних днях, наприклад верх/низ або push/pull/legs.',
      ],
      who: [
        'Full body suits beginners and busy people; upper/lower and push/pull/legs suit those who can train 4–6 days.',
        'Все тіло підходить новачкам і зайнятим; верх/низ і push/pull/legs — тим, хто може тренуватись 4–6 днів.',
      ],
    },
  },

  exercises_per_session: {
    ex: [
      'how many exercises per workout',
      'how many exercises should i do in one session',
      'number of exercises per session',
      'is 8 exercises too many',
      'how many exercises per day at the gym',
      'how many different exercises in a workout',
      'should i do 3 or 6 exercises',
      'too many exercises in my workout?',
      'ideal number of exercises per training day',
      'how many movements per session',
      'how many lifts should one workout have',
      'is 4 exercises enough per workout',
      'how many exercises for one gym day',
      'doing 10 exercises a session, too much?',
    ],
    exUk: [
      'скільки вправ за тренування',
      'скільки вправ робити за одне тренування',
      'кількість вправ на тренуванні',
      '8 вправ це не забагато?',
      'скільки вправ на день в залі',
      '4 вправи за тренування достатньо?',
      'скільки різних вправ робити',
      'оптимальна кількість вправ',
      'роблю 10 вправ за раз, це норм?',
      'скільки вправ має бути в одному тренуванні',
      'скільки вправ ставити на день',
      'сколько упражнений за тренировку',
      'сколько упражнений делать',
      'скіки вправ робити за трєню',
    ],
    facets: {
      howMuch: [
        '4–6 exercises, 2–4 hard sets each, is enough for one session.',
        '4–6 вправ, по 2–4 робочі сети, — достатньо на одне тренування.',
      ],
      how: [
        'Put the big compound lifts first while you are fresh and finish with isolation work.',
        'Став базові вправи на початок, поки свіжий, а ізолюючі — в кінець.',
      ],
      why: [
        'Beyond that, extra exercises tend to be junk volume: done tired, they add fatigue more than growth.',
        'Понад це додаткові вправи зазвичай — порожній обсяг: виконані втомленим, вони більше втомлюють, ніж дають ріст.',
      ],
      should: [
        'If you do more than 6, cut the ones that repeat the same movement and keep the quality of the rest high.',
        'Якщо робиш більше 6 — прибери ті, що дублюють один рух, і тримай якість решти високою.',
      ],
    },
  },

  compound_isolation: {
    ex: [
      'compound vs isolation exercises',
      'what is a compound exercise',
      'do i need isolation exercises',
      'are compound lifts better',
      'compound or isolation first',
      'is isolation work a waste of time',
      'can i build muscle with only compound lifts',
      'should i do curls or just rows and pull-ups',
      'difference between compound and isolation',
      'what counts as an isolation exercise',
      'are squats and deadlifts enough or do i need leg extensions',
      'why do compound exercises first',
      'only big lifts or also isolation',
      'multi-joint vs single-joint exercises',
    ],
    exUk: [
      'базові чи ізолюючі вправи',
      'що таке базова вправа',
      'чи потрібні ізолюючі вправи',
      'базові краще за ізоляцію?',
      'що робити першим, базу чи ізоляцію',
      'ізоляція — це марна трата часу?',
      'можна накачатись лише на базі',
      'різниця між базовими та ізольованими вправами',
      'які вправи ізолюючі',
      'чи достатньо присіду і станової, чи ще розгинання ніг',
      'тільки база чи ще й ізоляція',
      'багатосуглобові чи односуглобові вправи',
      'базовые или изолирующие упражнения',
      'база чи ізолірка, шо краще',
    ],
    facets: {
      what: [
        'Compound lifts move several joints (squat, press, row, deadlift); isolation lifts move one (curl, lateral raise, calf raise).',
        'Базові вправи працюють кількома суглобами (присід, жими, тяги, станова); ізолюючі — одним (згинання на біцепс, махи, підйоми на литки).',
      ],
      why: [
        'Compounds load the most muscle with the most weight, so they build most of the strength and size.',
        'Базові навантажують найбільше м’язів найбільшою вагою, тож дають основну силу й масу.',
      ],
      when: [
        'Do compounds first in the session while you are fresh; isolation goes at the end.',
        'Базові — на початку тренування, поки свіжий; ізолюючі — в кінці.',
      ],
      should: [
        'Yes, add some isolation to fill gaps compounds leave, like arms, side delts and calves.',
        'Так, додай трохи ізоляції, щоб закрити прогалини базових: руки, середні дельти, литки.',
      ],
    },
  },

  machines_free: {
    ex: [
      'machines or free weights',
      'are machines worse than free weights',
      'can i build muscle on machines only',
      'barbell or machine for chest',
      'smith machine vs barbell squat',
      'are free weights better for strength',
      'is it bad to only use machines',
      'leg press or squat for legs',
      'should beginners start on machines',
      'dumbbells vs machines for growth',
      'machine chest press vs bench press',
      'do machines build real strength',
      'free weights vs machines which is better',
      'hack squat instead of barbell squat ok',
    ],
    exUk: [
      'тренажери чи вільні ваги',
      'тренажери гірші за вільні ваги?',
      'можна накачатись лише на тренажерах',
      'штанга чи тренажер для грудей',
      'сміт чи присід зі штангою',
      'вільні ваги краще для сили?',
      'погано займатись тільки на тренажерах?',
      'жим ногами чи присід',
      'новачку краще починати з тренажерів?',
      'гантелі чи тренажери для росту',
      'жим в тренажері замість жиму лежачи — норм?',
      'тренажеры или свободные веса',
      'машини чи штанга, шо краще',
      'тренажери дають справжню силу?',
    ],
    facets: {
      should: [
        'Use both: both build muscle, so pick what suits the exercise, your level and your gym.',
        'Використовуй обидва: від обох ростуть м’язи, тож обирай за вправою, рівнем і залом.',
      ],
      why: [
        'Free weights train balance and carry over better to real strength; machines let you push closer to failure safely.',
        'Вільні ваги вчать баланс і краще переносяться на реальну силу; тренажери дають безпечніше підійти до відмови.',
      ],
      who: [
        'Machines are handy for beginners, training alone or around injuries; free weights matter most if you want barbell strength.',
        'Тренажери зручні новачкам, тим, хто тренується сам чи з травмою; вільні ваги важливі, якщо мета — сила зі штангою.',
      ],
      how: [
        'A common setup: free-weight compounds first, then machines for extra volume near failure.',
        'Типова схема: спершу базові з вільними вагами, потім тренажери для додаткового обсягу близько до відмови.',
      ],
    },
  },

  superset: {
    ex: [
      'what is a superset',
      'should i do supersets',
      'are supersets good for muscle',
      'how do supersets work',
      'superset biceps and triceps',
      'can i superset bench and rows',
      'circuit training for strength',
      'do supersets save time',
      'is it ok to superset squats',
      "what's the difference between a superset and a circuit",
      'best exercises to superset',
      'supersets for hypertrophy',
      'rest between supersets',
      'antagonist supersets explained',
    ],
    exUk: [
      'що таке суперсет',
      'чи варто робити суперсети',
      'суперсети добрі для росту м’язів?',
      'як робити суперсет',
      'суперсет біцепс трицепс',
      'можна суперсетом жим і тягу',
      'кругове тренування для сили',
      'суперсети економлять час?',
      'присід у суперсеті — нормально?',
      'чим суперсет відрізняється від кола',
      'які вправи поєднувати в суперсет',
      'скільки відпочивати між суперсетами',
      'что такое суперсет',
      'суперсетами качатись норм?',
    ],
    facets: {
      what: [
        'A superset is two exercises back to back with rest after the pair; a circuit is three or more in a row.',
        'Суперсет — дві вправи підряд із відпочинком після пари; коло — три й більше підряд.',
      ],
      how: [
        'Pair opposing muscles, like chest with back or biceps with triceps, then rest after both.',
        'Поєднуй антагоністи, як-от груди зі спиною чи біцепс із трицепсом, і відпочивай після обох.',
      ],
      should: [
        'Yes for saving time on accessories; keep heavy compounds like squats and deadlifts as straight sets.',
        'Так, щоб зекономити час на допоміжних; важкі базові, як присід і станова, роби звичайними сетами.',
      ],
      why: [
        'Opposing muscles rest while the other works, so you do the same work in less time without losing much quality.',
        'Антагоністи відпочивають, поки працює інший, тож та сама робота займає менше часу майже без втрати якості.',
      ],
    },
  },

  dropset: {
    ex: [
      'what is a drop set',
      'are drop sets good',
      'how do i do a drop set',
      'should i do drop sets on bench',
      'drop sets for hypertrophy',
      'how much weight to drop in a dropset',
      'do drop sets build more muscle',
      'drop set on the last set?',
      'how many drops in a drop set',
      'are dropsets worth it for arms',
      'can i do drop sets on squats',
      'stripping weight and continuing the set',
      'running the rack on dumbbell curls',
      'how often to use drop sets',
    ],
    exUk: [
      'що таке дроп-сет',
      'дропсети корисні?',
      'як робити дроп-сет',
      'дропсет на жимі лежачи — варто?',
      'дропсети для росту м’язів',
      'на скільки знижувати вагу в дропсеті',
      'дроп-сети дають більше м’язів?',
      'дропсет на останньому підході',
      'скільки разів скидати вагу в дропсеті',
      'дропи на руки варто робити?',
      'можна дропсет на присіді',
      'что такое дропсет',
      'дропсеты полезны?',
      'дропи на біцуху — тема?',
    ],
    facets: {
      what: [
        'A drop set is a set taken to (near) failure, then the weight is cut and you keep going without rest.',
        'Дроп-сет — сет до (майже) відмови, після чого знижуєш вагу й продовжуєш без відпочинку.',
      ],
      howMuch: [
        'Drop about 20–30% of the weight, once or twice.',
        'Скидай приблизно 20–30% ваги, раз або двічі.',
      ],
      when: [
        'Use it on the last set of an isolation exercise.',
        'Став його на останній сет ізолюючої вправи.',
      ],
      should: [
        'Worth it on isolation work like curls or lateral raises; on heavy compounds like squats and deadlifts it mostly adds fatigue.',
        'Варто на ізолюючих, як згинання на біцепс чи махи; на важких базових, як присід і станова, це здебільшого зайва втома.',
      ],
    },
  },

  rpe: {
    ex: [
      'what is rpe',
      'what does rir mean',
      'what is reps in reserve',
      'how do i rate rpe',
      'what rpe should my sets be',
      'rpe 8 meaning',
      'explain the rpe scale',
      'how many reps in reserve should i leave',
      'is rpe 10 failure',
      'rpe vs rir',
      'what rpe for working sets',
      'how hard should a set feel on the effort scale',
      'do i need to rate every set',
      "what if i don't log rpe",
    ],
    exUk: [
      'що таке rpe',
      'що означає rir',
      'що таке повтори в запасі',
      'як оцінювати rpe',
      'який rpe має бути на робочих сетах',
      'rpe 8 це як',
      'поясни шкалу зусиль',
      'скільки повторів залишати в запасі',
      'rpe 10 — це відмова?',
      'rpe чи rir, в чому різниця',
      'треба оцінювати кожен сет?',
      'а якщо не ставлю rpe',
      'что такое rpe',
      'скіки повторів в запасі лишати',
    ],
    facets: {
      what: [
        'RPE rates effort from 1 to 10: RPE 10 means nothing left, RPE 8 means 2 reps left (RIR 2).',
        'RPE оцінює зусилля від 1 до 10: RPE 10 — нічого не лишилось, RPE 8 — ще 2 повтори в запасі (RIR 2).',
      ],
      howMuch: [
        'Most working sets belong at RPE 7–9, meaning 1–3 reps in reserve.',
        'Більшість робочих сетів — RPE 7–9, тобто 1–3 повтори в запасі.',
      ],
      how: [
        'After a set, ask how many more clean reps you could have done; subtract that from 10.',
        'Після сету спитай себе, скільки ще чистих повторів міг би зробити; відніми це від 10.',
      ],
      should: [
        'Rating sets helps but is optional: when you do not rate a set, the app estimates it.',
        'Оцінювати сети корисно, але не обов’язково: якщо не оцінюєш, додаток рахує сам.',
      ],
    },
  },

  tempo: {
    ex: [
      'what tempo should i lift at',
      'are slow reps better for muscle',
      'how fast should i lower the weight',
      'should i do slow eccentrics',
      'is time under tension important',
      'do negatives build more muscle',
      'how long should each rep take',
      'super slow reps worth it',
      'controlled negatives on bench',
      'should i lift explosively',
      '3 second eccentric good?',
      'rep speed for hypertrophy',
      'what does tempo 3010 mean',
      'fast or slow reps',
    ],
    exUk: [
      'який темп виконання повторів',
      'повільні повтори краще для м’язів?',
      'як швидко опускати вагу',
      'чи робити повільний негатив',
      'час під навантаженням важливий?',
      'негативні повтори дають більше росту?',
      'скільки секунд має тривати повтор',
      'надповільні повтори варто?',
      'опускати штангу на жимі повільно?',
      'піднімати вибухово чи повільно',
      'ексцентрика 3 секунди — норм?',
      'швидкість повторів для маси',
      'в каком темпе делать повторения',
      'медленные повторения лучше?',
    ],
    facets: {
      how: [
        'Control the lowering over about 2 seconds, then lift with intent.',
        'Опускай під контролем приблизно 2 секунди, а піднімай рішуче.',
      ],
      should: [
        "No need for super-slow reps: they don't build more muscle and just force you to use less weight.",
        'Надповільні повтори не потрібні: вони не дають більше м’язів і лише змушують брати меншу вагу.',
      ],
      howMuch: [
        'Around 2 seconds down and a strong 1 second or less up works for most lifts.',
        'Близько 2 секунд вниз і потужна секунда чи менше вгору підходять для більшості вправ.',
      ],
      why: [
        'Control keeps tension and technique; lifting with intent recruits the most muscle fibres.',
        'Контроль тримає напругу й техніку, а рішучий підйом залучає найбільше м’язових волокон.',
      ],
    },
  },

  warmup_sets: {
    ex: [
      'how many warm up sets should i do',
      'what warmup sets before heavy squats',
      'how to ramp up to my working weight',
      'warm up sets for bench',
      'what percentage for warmup sets',
      'do i need warmup sets for every exercise',
      'ramp up sets explained',
      'how many reps on warm up sets',
      'warmup sets before deadlift',
      'do warm up sets count toward volume',
      'building up to a heavy single',
      'how light should warmup sets be',
      'do i warm up again for the second exercise',
      'how to structure ramping sets',
    ],
    exUk: [
      'скільки робити розминочних сетів',
      'які підвідні сети перед важким присідом',
      'як підходити до робочої ваги',
      'розминкові сети на жим',
      'який відсоток ваги на підвідних',
      'чи потрібні підвідні сети на кожну вправу',
      'скільки повторів на розминочних сетах',
      'підвідні підходи перед становою',
      'розминочні сети рахуються в обсяг?',
      'наскільки легкими мають бути підвідні',
      'на другу вправу теж розминатись сетами?',
      'как делать разминочные подходы',
      'скільки підвідних робити',
      'як правильно робити підвідні сети',
    ],
    facets: {
      how: [
        'Before your first heavy lift: empty bar for 10, about 50% for 5, 70% for 3, 85% for 1, then working sets.',
        'Перед першою важкою вправою: гриф на 10, приблизно 50% на 5, 70% на 3, 85% на 1, далі робочі сети.',
      ],
      howMuch: [
        'Usually 3–4 ramp sets for the first heavy lift; later lifts need one light set at most.',
        'Зазвичай 3–4 підвідні сети на першій важкій вправі; наступним — щонайбільше один легкий сет.',
      ],
      why: [
        'Ramp sets rehearse the movement and prepare joints and muscles without tiring you before the work sets.',
        'Підвідні сети відточують рух і готують суглоби та м’язи, не втомлюючи перед робочими.',
      ],
      should: [
        'Keep them easy with low reps; they are not meant to count as hard sets.',
        'Роби їх легко й з малою кількістю повторів; вони не мають рахуватися як важкі сети.',
      ],
    },
  },

  stretch_before: {
    ex: [
      'should i stretch before lifting',
      'is stretching before a workout bad',
      'static stretching before squats',
      'stretch before or after gym',
      'does stretching before training reduce strength',
      'should i do stretches before deadlifts',
      'dynamic or static stretching before a workout',
      'do i need to stretch before weights',
      'stretching before bench press',
      'is it ok to skip stretching before lifting',
      'pre-workout stretching necessary?',
      'why not stretch before lifting',
      'should i hold stretches before training',
      'stretch first then lift?',
    ],
    exUk: [
      'чи треба розтягуватись перед тренуванням',
      'розтяжка перед силовим шкідлива?',
      'статична розтяжка перед присідом',
      'розтяжка перед чи після залу',
      'розтяжка перед тренуванням знижує силу?',
      'розтягуватись перед становою?',
      'динамічна чи статична розтяжка перед тренуванням',
      'можна не розтягуватись перед залом',
      'розтяжка перед жимом лежачи',
      'чому не можна розтягуватись перед силовим',
      'спершу розтяжка, потім вага?',
      'нужна ли растяжка перед тренировкой',
      'растяжка перед залом вредна?',
      'перед трєнькою тягнутись треба?',
    ],
    facets: {
      should: [
        'Skip long static stretches before lifting; do dynamic moves and warm-up sets instead.',
        'Довгі статичні розтяжки перед силовим пропусти; натомість динамічні рухи й розминкові сети.',
      ],
      why: [
        'Holding stretches for a long time right before lifting slightly reduces strength and power.',
        'Довге утримання розтяжки безпосередньо перед силовим трохи знижує силу й потужність.',
      ],
      when: [
        'Stretch after training or on rest days.',
        'Розтягуйся після тренування або у вихідні.',
      ],
      how: [
        'Before lifting: leg swings, arm circles, bodyweight squats, then ramp-up sets on the first lift.',
        'Перед силовим: махи ногами, обертання руками, присіди без ваги, потім підвідні сети на першій вправі.',
      ],
    },
  },

  mobility: {
    ex: [
      'how do i improve mobility',
      'how to get more flexible',
      'my hips are stiff',
      "can't squat deep because of mobility",
      'tight hamstrings, what to do',
      'how to improve shoulder mobility',
      'does lifting make you less flexible',
      'mobility routine for lifters',
      'i feel stiff all the time',
      'how to fix poor ankle mobility',
      'stiff lower back in the morning after training',
      'how to become more mobile',
      'is flexibility important for lifting',
      'my body feels tight, how to loosen up',
    ],
    exUk: [
      'як покращити мобільність',
      'як стати гнучкішим',
      'скуті стегна',
      'не можу глибоко присісти через гнучкість',
      'забиті задні стегна, що робити',
      'як покращити мобільність плечей',
      'силові роблять менш гнучким?',
      'вправи на мобільність для залу',
      'постійно відчуваю скутість',
      'погана рухливість гомілкостопу',
      'як розігнути скуте тіло',
      'гнучкість важлива для силових?',
      'как улучшить подвижность',
      'якийсь я задубілий, як розтягнутись',
    ],
    facets: {
      how: [
        'Lift through full range: deep squats, stretched-position exercises and paused reps, plus 5–10 minutes of stretching after sessions for the stiff spots.',
        'Працюй у повній амплітуді: глибокі присіди, вправи в розтягнутій позиції, паузи, плюс 5–10 хвилин розтяжки після тренування для скутих місць.',
      ],
      why: [
        'Loading muscles in a long position improves range of motion about as well as stretching does.',
        'Навантаження м’язів у розтягнутій позиції покращує амплітуду не гірше за розтяжку.',
      ],
      howMuch: [
        '5–10 minutes after sessions, focused on your stiffest spots, is enough for most people.',
        '5–10 хвилин після тренування на найскутіші місця — достатньо більшості.',
      ],
      when: [
        'After training or on rest days, and consistently over weeks.',
        'Після тренування або у вихідні, і регулярно протягом тижнів.',
      ],
    },
  },

  abs_daily: {
    ex: [
      'should i train abs every day',
      'how to get a six pack',
      'how often should i train abs',
      'can i do crunches daily',
      'how do i get abs',
      'abs workout every day ok',
      'how to get visible abs',
      'how many times a week for core',
      'do i need weighted ab exercises',
      "why can't i see my abs",
      'best way to build a six pack',
      'will 100 crunches a day give me abs',
      'how many reps for abs',
      'train core daily?',
    ],
    exUk: [
      'чи качати прес щодня',
      'як накачати кубики',
      'як часто тренувати прес',
      'можна скручування кожен день',
      'як накачати прес',
      'прес кожен день — нормально?',
      'як зробити прес видимим',
      'скільки разів на тиждень на кор',
      'прес з обтяженням потрібен?',
      'чому не видно преса',
      '100 скручувань щодня дадуть кубики?',
      'скільки повторів на прес',
      'как накачать пресс',
      'пресс каждый день качать можно?',
      'кубики як зробити',
    ],
    facets: {
      howMuch: [
        '2–3 hard sessions a week, weighted, 8–15 reps.',
        '2–3 важкі тренування на тиждень, з обтяженням, 8–15 повторів.',
      ],
      should: [
        'No need for daily abs: they are a muscle like any other and grow from hard, loaded work with recovery.',
        'Щодня прес не потрібен: це такий самий м’яз, він росте від важкої роботи з обтяженням і відновлення.',
      ],
      why: [
        'Seeing abs depends on body fat, not on how many crunches you do.',
        'Чи видно прес, залежить від рівня жиру, а не від кількості скручувань.',
      ],
      how: [
        'Pick loaded moves like cable crunches or hanging leg raises, progress them, and reduce body fat to reveal them.',
        'Обери вправи з обтяженням, як скручування в блоці чи підйоми ніг у висі, прогресуй у них і знижуй жир, щоб прес було видно.',
      ],
    },
  },

  grip: {
    ex: [
      'my grip gives out on deadlifts',
      'how to improve grip strength',
      'grip fails before my back',
      'forearms burn out first on rows',
      'how to stop the bar slipping out of my hands',
      'best grip exercises',
      'weak grip on pull-ups',
      'should i train forearms for grip',
      'does chalk help grip',
      'hands give up before the set is done',
      'how to build a stronger grip for deadlift',
      "farmer's walks for grip?",
      'dead hangs for grip strength',
      'grip is my weak link',
    ],
    exUk: [
      'хват не тримає на становій',
      'як покращити силу хвату',
      'хват здається раніше за спину',
      'передпліччя забиваються першими на тягах',
      'штанга вислизає з рук',
      'найкращі вправи на хват',
      'слабкий хват на підтягуваннях',
      'треба качати передпліччя для хвату?',
      'магнезія допомагає хвату?',
      'руки не витримують до кінця сету',
      'прогулянка фермера для хватки',
      'віси на турніку для хвату',
      'как улучшить хват',
      'кисті не тримають гриф',
    ],
    facets: {
      how: [
        "Heavy holds like farmer's walks and dead hangs, fewer straps on light sets, and chalk.",
        'Важкі утримання, як прогулянка фермера й віси, менше лямок на легких сетах і магнезія.',
      ],
      when: [
        'Save straps for the heaviest pulls so grip still gets trained on the rest.',
        'Лямки лиш на найважчих тягах, щоб хват тренувався на решті.',
      ],
      why: [
        'Grip often lags because it rarely gets direct heavy work while straps do the job for it.',
        'Хват часто відстає, бо рідко отримує пряме важке навантаження, а лямки роблять роботу за нього.',
      ],
      howMuch: [
        '2–3 sets of heavy holds or hangs, for 20–40 seconds, a couple of times a week is a good start.',
        '2–3 підходи важких утримань чи висів по 20–40 секунд пару разів на тиждень — добрий старт.',
      ],
    },
  },

  belt_straps: {
    ex: [
      'should i use a lifting belt',
      'when to wear a belt',
      'are lifting straps cheating',
      'do i need wrist wraps',
      'belt for squats or not',
      'should beginners use a belt',
      'when should i use straps on deadlifts',
      'does a belt weaken your core',
      'knee wraps for squats',
      'straps for rows and shrugs?',
      'is wearing a belt all the time bad',
      'at what weight should i start using a belt',
      'lever belt or prong belt',
      'straps for pull-ups ok',
    ],
    exUk: [
      'чи варто використовувати пояс',
      'коли надягати пояс',
      'лямки — це читінг?',
      'чи потрібні бинти на зап’ястя',
      'пояс на присід потрібен?',
      'новачку потрібен пояс?',
      'коли брати лямки на станову',
      'пояс послаблює кор?',
      'бинти на коліна для присіду',
      'лямки на тягу до пояса норм?',
      'постійно в поясі — це погано?',
      'з якої ваги одягати пояс',
      'нужен ли пояс для приседа',
      'кистьові лямки на станову юзати?',
    ],
    facets: {
      when: [
        'Belt for heavy squats and deadlifts, roughly above 80% of your max; straps when grip limits a back exercise.',
        'Пояс — для важких присідів і станової, приблизно понад 80% максимуму; лямки — коли хват обмежує вправу на спину.',
      ],
      should: [
        'Not for everything: neither a belt nor straps replaces learning to brace, so keep lighter sets without them.',
        'Не на все: ні пояс, ні лямки не замінюють уміння напружувати корпус, тож легші сети роби без них.',
      ],
      why: [
        'A belt gives your braced core something to push against, raising stability under heavy loads.',
        'Пояс дає напруженому корпусу опору, в яку можна впиратися, і підвищує стабільність під важкою вагою.',
      ],
      what: [
        'Straps loop around the bar to take grip out of back exercises; wraps support the wrists or knees.',
        'Лямки обмотують гриф і прибирають обмеження хвату у вправах на спину; бинти підтримують зап’ястя чи коліна.',
      ],
    },
  },

  breathing: {
    ex: [
      'how should i breathe when lifting',
      'how to brace for squats',
      'when to breathe during bench press',
      'what is the valsalva maneuver',
      'should i hold my breath on deadlifts',
      'breathing technique for heavy lifts',
      'how do i brace my core',
      'inhale or exhale on the way up',
      'breathe in on the way down?',
      'how to breathe during a heavy set',
      'belly breathing for lifting',
      'is holding breath dangerous when lifting',
      'i get dizzy holding my breath on squats',
      'how to brace properly',
    ],
    exUk: [
      'як правильно дихати під час вправ',
      'як напружувати корпус на присіді',
      'коли дихати на жимі лежачи',
      'що таке вальсальва',
      'затримувати дихання на становій?',
      'техніка дихання на важких вправах',
      'як напружити корпус',
      'вдих чи видих при підйомі',
      'дихання животом для силових',
      'затримка дихання небезпечна?',
      'як дихати під час важкого сету',
      'как правильно дышать при жиме',
      'як дихати на присяді щоб не паморочилось',
      'вдихати на опусканні?',
    ],
    facets: {
      how: [
        'Big breath into the belly, brace as if about to be punched, hold through the hard part, breathe out at the top.',
        'Глибокий вдих у живіт, напруж корпус, ніби зараз вдарять, тримай через найважчу частину, видих угорі.',
      ],
      when: [
        'Take the breath and brace before each heavy rep, not mid-movement.',
        'Вдих і напруження — перед кожним важким повтором, а не посеред руху.',
      ],
      why: [
        'Pressure in a braced trunk stabilises the spine so you can move more weight safely.',
        'Тиск у напруженому корпусі стабілізує хребет, тож можна безпечніше підняти більше.',
      ],
      should: [
        'Brief breath holds are normal on heavy reps; with high blood pressure or heart issues, ask a doctor first and breathe out more steadily.',
        'Коротка затримка дихання на важких повторах — норма; при підвищеному тиску чи проблемах із серцем спершу порадься з лікарем і видихай рівніше.',
      ],
      what: [
        'The Valsalva manoeuvre is holding a deep breath against a closed throat to build trunk pressure during a lift.',
        'Вальсальва — це затримка глибокого вдиху із закритою гортанню, щоб створити тиск у корпусі під час підйому.',
      ],
    },
  },

  squat_form: {
    ex: [
      'how deep should i squat',
      'is below parallel necessary',
      'should my knees go past my toes',
      'knees caving in on squats',
      'what is proper squat depth',
      'how to keep my knees out on squat',
      'is it bad if knees go over toes',
      'how deep should i go on the deadlift setup',
      'how low should the bar go on bench',
      'ass to grass or parallel',
      'my knees cave in on the way up',
      'how to hit depth on squats',
      'where should the bar touch on bench press',
      'back rounding on deadlift, how to fix',
    ],
    exUk: [
      'наскільки глибоко присідати',
      'треба присідати нижче паралелі?',
      'коліна можуть виходити за носки?',
      'коліна зводяться на присіді',
      'яка правильна глибина присіду',
      'як тримати коліна назовні в присіді',
      'погано, якщо коліна за носками',
      'глибина присіду — до паралелі чи нижче',
      'коліна заходять всередину при підйомі',
      'куди опускати гриф на жимі лежачи',
      'округлюється спина на становій',
      'как глубоко приседать',
      'колени за носки при приседе можно?',
      'до якої глибини сідати в присяді',
    ],
    facets: {
      howMuch: [
        'Squat at least until your hips reach knee height; deeper is fine if your back stays neutral.',
        'Присідай щонайменше до рівня, коли таз на висоті колін; глибше — нормально, якщо спина лишається рівною.',
      ],
      how: [
        'Feet about shoulder-width, knees track over the toes, chest up, brace hard, and film from the side to check.',
        'Стопи приблизно на ширині плечей, коліна йдуть за носками, груди вгору, корпус напружений, і зніми себе збоку для перевірки.',
      ],
      should: [
        'Knees passing the toes is fine as long as they follow the direction of the toes and heels stay down.',
        'Коліна за носками — нормально, якщо вони йдуть у напрямку носків, а п’яти на підлозі.',
      ],
      why: [
        'Full depth trains more muscle through a longer range; caving knees and rounding backs usually mean the weight is too heavy or control is lacking.',
        'Повна глибина тренує більше м’язів у більшій амплітуді; коліна, що зводяться, і округлена спина зазвичай означають, що вага завелика чи бракує контролю.',
      ],
    },
  },

  results_time: {
    ex: [
      'how long until i see results',
      'when will i see results from the gym',
      'how long does it take to see muscle',
      'how fast will i get stronger',
      'how many weeks until i notice changes',
      'been lifting a month, no results yet',
      'how long before people notice i lift',
      'when will my body start changing',
      'how quickly do gym results come',
      "why don't i see results yet",
      'how long to get a visible difference',
      'results after 3 months of lifting?',
      'how long until my clothes fit differently',
      'time to see gains',
    ],
    exUk: [
      'коли буде результат',
      'коли я побачу результат від залу',
      'скільки часу, щоб побачити м’язи',
      'як швидко я стану сильнішим',
      'через скільки тижнів будуть зміни',
      'тренуюсь місяць, результату нема',
      'коли тіло почне змінюватись',
      'як швидко приходять результати',
      'чому досі не бачу результату',
      'що буде через 3 місяці тренувань',
      'коли помітять, що я качаюсь',
      'когда будет результат',
      'как быстро будет результат от зала',
      'коли вже буде видно шо я хожу в зал',
    ],
    facets: {
      when: [
        'Strength rises within weeks, visible muscle takes 2–3 months of consistent training, and a real transformation takes about a year.',
        'Сила росте за тижні, помітні м’язи — за 2–3 місяці регулярних тренувань, а справжня зміна — приблизно рік.',
      ],
      why: [
        'Early strength gains come from the nervous system learning the lifts; muscle growth is slower and needs time to show.',
        'Перші прирости сили — це нервова система, яка вчиться рухів; ріст м’язів повільніший і потребує часу, щоб проявитися.',
      ],
      how: [
        'Track the log rather than the mirror: rising weights and reps show progress before visible change.',
        'Стеж за журналом, а не за дзеркалом: зростання ваг і повторів показує прогрес раніше, ніж видно зміни.',
      ],
      should: [
        'Stay consistent for at least 8–12 weeks before judging; missed sessions and poor sleep slow everything down.',
        'Тренуйся регулярно щонайменше 8–12 тижнів, перш ніж оцінювати; пропуски й поганий сон усе сповільнюють.',
      ],
    },
  },

  muscle_gain_rate: {
    ex: [
      'how do i gain muscle',
      'how to build muscle fast',
      'how much muscle can i gain in a month',
      'best way to put on mass',
      'how fast can a beginner build muscle',
      'i want to bulk up',
      'how to gain muscle mass',
      'what do i need to build muscle',
      'realistic muscle gain per year',
      'tips for gaining size',
      'how to get bigger',
      'can i gain muscle naturally quickly',
      "i'm skinny and want to build muscle",
      'muscle building basics',
    ],
    exUk: [
      'як набрати м’язи',
      'як швидко набрати масу',
      'скільки м’язів можна набрати за місяць',
      'найкращий спосіб набору маси',
      'як швидко новачок набирає м’язи',
      'хочу набрати масу',
      'що потрібно для набору м’язів',
      'реальний набір м’язів за рік',
      'як стати більшим',
      'я худий, хочу набрати м’язи',
      'основи набору маси',
      'як піти на масу',
      'как набрать мышечную массу',
      'хочу на масу, шо робити',
    ],
    facets: {
      how: [
        'Lift hard 3–5 times a week, add reps or weight over time, eat about 1.6–2.2 g of protein per kg, keep a slight calorie surplus and sleep 7+ hours.',
        'Важко тренуйся 3–5 разів на тиждень, додавай повтори чи вагу, їж близько 1,6–2,2 г білка на кг, тримай невеликий профіцит і спи 7+ годин.',
      ],
      howMuch: [
        'Beginners gain fastest; the rate slows every year of training.',
        'Новачки набирають найшвидше; з кожним роком тренувань темп сповільнюється.',
      ],
      why: [
        'Muscle grows when hard training signals it, protein supplies the building material and sleep allows repair.',
        'М’язи ростуть, коли важке тренування дає сигнал, білок постачає матеріал, а сон дає відновитись.',
      ],
      should: [
        'Eat in a slight surplus rather than a large one; going faster mostly adds fat.',
        'Тримай невеликий профіцит, а не великий; швидше — здебільшого додає жир.',
      ],
    },
  },

  fat_loss: {
    ex: [
      'how do i lose fat',
      'how to lose weight while lifting',
      'best way to get lean',
      'can i burn belly fat with exercises',
      'how to cut without losing muscle',
      'i want to lose weight',
      'does lifting help fat loss',
      'how fast should i lose weight',
      'how to lose fat and keep muscle',
      'spot reduction for love handles',
      'should i keep lifting heavy on a cut',
      'how to get shredded',
      'how many kg per week is safe to lose',
      'weights or cardio to lose fat',
    ],
    exUk: [
      'як схуднути',
      'як скинути жир',
      'як схуднути, займаючись у залі',
      'як спалити жир на животі вправами',
      'як сушитись без втрати м’язів',
      'хочу скинути вагу',
      'силові допомагають схуднути?',
      'як швидко можна худнути',
      'як скинути жир і зберегти м’язи',
      'можна прибрати жир з боків вправами?',
      'на сушці тренуватись важко?',
      'скільки кг на тиждень безпечно скидати',
      'как похудеть в зале',
      'хочу посушитись, шо робити',
    ],
    facets: {
      how: [
        'Create a calorie deficit, keep training heavy and keep protein high; lifting preserves muscle while the fat comes off.',
        'Створи дефіцит калорій, тренуйся важко й тримай багато білка; силові зберігають м’язи, поки йде жир.',
      ],
      howMuch: [
        'Aim to lose about 0.5–1% of body weight per week.',
        'Ціль — мінус приблизно 0,5–1% ваги тіла на тиждень.',
      ],
      should: [
        'Keep lifting heavy on a cut; drop the idea of spot reduction, since fat does not come off one area from training it.',
        'На сушці тренуйся важко далі; забудь про локальне спалювання: жир не йде з місця, яке тренуєш.',
      ],
      why: [
        'Fat loss happens only when you use more energy than you eat; training decides whether you lose fat or muscle.',
        'Жир іде лише тоді, коли витрачаєш більше енергії, ніж їси; тренування вирішують, що втратиш — жир чи м’язи.',
      ],
    },
  },

  myth_bulky: {
    ex: [
      'will lifting make me bulky',
      "i don't want to get bulky",
      'will weights make a woman look too muscular',
      'should girls lift heavy',
      "i'm afraid of getting too big",
      'will heavy squats make my legs huge',
      'can women build muscle like men',
      'lifting makes women bulky, true?',
      'i want to tone, not bulk',
      'will i look like a bodybuilder if i lift',
      'do light weights tone and heavy weights bulk',
      'is it safe for women to lift weights',
      'will i get big arms from lifting',
      'how to lift without getting big',
    ],
    exUk: [
      'я не перекачаюсь від залу?',
      'не хочу стати великою',
      'дівчатам можна піднімати важке?',
      'боюсь стати як качок',
      'від присідів ноги стануть величезними?',
      'чи можуть жінки накачатись як чоловіки',
      'силові роблять жінок масивними — правда?',
      'хочу тонус, а не масу',
      'не стану бодібілдеркою від штанги?',
      'легкі ваги для тонусу, а важкі для маси?',
      'не перекачаюсь, якщо качатиму руки',
      'боюсь перекачатися',
      'не стану ли я перекачанной',
      'девушкам можно тягать тяжелое?',
    ],
    facets: {
      why: [
        'Getting big takes years of hard training and deliberately eating for it; it does not happen by accident, especially for women with less testosterone.',
        'Стати великою чи великим — це роки важких тренувань і харчування саме під це; випадково так не буває, особливо в жінок із меншим рівнем тестостерону.',
      ],
      should: [
        'Yes, lift heavy: it makes you stronger and shapes the body, and you control your size with how you eat.',
        'Так, піднімай важке: це робить сильнішою й формує фігуру, а розмір контролюєш харчуванням.',
      ],
      what: [
        'Toning is simply building some muscle and losing some fat; heavy lifting does both better than light pumping.',
        'Тонус — це просто трохи м’язів і трохи менше жиру; важкі силові роблять це краще, ніж легкі повтори.',
      ],
      who: [
        'Everyone benefits: women and men gain strength, bone density and shape from lifting.',
        'Користь для всіх: і жінки, і чоловіки отримують від силових силу, міцні кістки й форму.',
      ],
    },
  },

  cardio_gains: {
    ex: [
      'does cardio kill gains',
      'will running ruin my muscle',
      'cardio while bulking bad?',
      'does cardio burn muscle',
      'can i run and still build muscle',
      'will cardio make me lose strength',
      'is cardio bad for gains',
      'does running interfere with leg day',
      'should i avoid cardio when building muscle',
      'cardio after lifting, does it hurt gains',
      'does cardio eat muscle',
      'running and lifting together, bad idea?',
      'will cycling hurt my squat',
      'cardio kills muscle myth',
    ],
    exUk: [
      'кардіо з’їсть м’язи?',
      'біг шкодить м’язам?',
      'кардіо на масі — погано?',
      'кардіо спалює м’язи?',
      'можна бігати й набирати м’язи',
      'від кардіо впаде сила?',
      'біг заважає дню ніг?',
      'уникати кардіо при наборі маси?',
      'кардіо після силового шкодить м’язам?',
      'біг і зал разом — погана ідея?',
      'велосипед заважатиме присіду?',
      'кардио сжигает мышцы?',
      'бег мешает набору массы?',
      'кардіо з’їсть мої м’язи чи ні',
    ],
    facets: {
      should: [
        'Keep it: moderate cardio does not kill gains and helps recovery, as long as you eat enough.',
        'Залиш: помірне кардіо не з’їдає м’язи й допомагає відновленню, якщо їси достатньо.',
      ],
      how: [
        'Keep it easy, and keep it apart from leg day or do it after lifting.',
        'Роби його легким і окремо від дня ніг або після силового.',
      ],
      why: [
        'Only very high amounts of hard cardio compete with muscle growth; easy work improves conditioning and blood flow.',
        'З ростом м’язів конкурує лише дуже великий обсяг важкого кардіо; легке покращує витривалість і кровообіг.',
      ],
      when: [
        'After lifting or on separate days; avoid hard running right before heavy squats or deadlifts.',
        'Після силового або в окремі дні; уникай інтенсивного бігу безпосередньо перед важким присідом чи становою.',
      ],
    },
  },

  sick: {
    ex: [
      "i'm sick, should i train",
      'can i work out with a cold',
      'should i go to the gym with a fever',
      'training while ill',
      'i have the flu, gym or rest',
      'can i lift with a runny nose',
      'is it ok to exercise when sick',
      'i have covid, can i train',
      'sore throat, should i work out',
      'how to pause my plan while sick',
      'when can i train after being sick',
      'got a cold, skip the gym?',
      'feeling ill, workout today?',
      'coming down with something, train or not',
    ],
    exUk: [
      'я захворів, тренуватись?',
      'можна тренуватись із застудою',
      'чи йти в зал з температурою',
      'тренування під час хвороби',
      'у мене грип, зал чи відпочинок',
      'нежить, можна в зал?',
      'чи можна займатись, коли хворієш',
      'в мене ковід, можна тренуватись',
      'болить горло, тренуватись?',
      'як поставити план на паузу під час хвороби',
      'коли можна тренуватись після хвороби',
      'застудився, пропустити зал?',
      'заболел, можно тренироваться?',
      'шось мене морозить, йти на трєню?',
    ],
    facets: {
      should: [
        'Fever or symptoms below the neck (chest, body aches, stomach): rest, no training. A mild head cold: a light session is OK.',
        'Температура чи симптоми нижче шиї (груди, ломота, шлунок) — відпочинок, без тренувань. Легкий нежить — можна легке тренування.',
      ],
      how: [
        'Log an illness rest period in the app: your streak and plan pause, and training eases back afterwards.',
        'Запиши в додатку період хвороби: серія й план стануть на паузу, а потім навантаження повертається поступово.',
      ],
      when: [
        'Return once the fever has been gone for a day or two, starting lighter; see a doctor if symptoms are severe or linger.',
        'Повертайся, коли температури нема день-два, і почни легше; при сильних чи затяжних симптомах звернись до лікаря.',
      ],
      why: [
        'Hard training with a fever or systemic illness adds stress the body cannot spare and can make things worse.',
        'Важке тренування з температурою чи загальною хворобою додає стрес, на який в організму нема ресурсу, і може погіршити стан.',
      ],
    },
  },

  alcohol: {
    ex: [
      "i'm hungover, should i train",
      'does alcohol kill gains',
      'can i work out after drinking',
      'had a party last night, gym today?',
      'is beer bad for muscle growth',
      'training with a hangover',
      'how does alcohol affect recovery',
      'drank a lot yesterday, lift or rest',
      'does drinking ruin muscle',
      'is one beer after the gym ok',
      'alcohol and strength training',
      'drinking on weekends and bodybuilding',
      'can i go to the gym drunk',
      'does alcohol affect protein synthesis',
    ],
    exUk: [
      'у мене похмілля, тренуватись?',
      'алкоголь шкодить м’язам?',
      'можна в зал після того, як випив',
      'вчора була вечірка, сьогодні зал?',
      'пиво шкодить набору маси?',
      'тренування з похмілля',
      'як алкоголь впливає на відновлення',
      'вчора багато випив, тягати чи відпочити',
      'одне пиво після залу — норм?',
      'алкоголь і силові',
      'бухав на вихідних, це вб’є прогрес?',
      'с похмелья можно в зал?',
      'алкоголь мешает росту мышц?',
      'вчора перебрав, йти сьогодні на трєню?',
    ],
    facets: {
      should: [
        'On a hangover day: water, food, and a lighter session or a walk instead of chasing records.',
        'У день похмілля: вода, їжа і легке тренування чи прогулянка замість рекордів.',
      ],
      why: [
        'Alcohol disrupts sleep and recovery for a day or two and blunts muscle repair, especially in larger amounts.',
        'Алкоголь на добу-дві ламає сон і відновлення та гальмує відновлення м’язів, особливо у великих кількостях.',
      ],
      howMuch: [
        'An occasional drink matters little; heavy or frequent drinking is what costs progress.',
        'Рідкісний келих мало на що впливає; прогрес забирає велика кількість чи часте вживання.',
      ],
      when: [
        'Give it a day or two after heavy drinking before pushing heavy sets again; never train while still drunk.',
        'Після сильного вживання дай день-два, перш ніж знову йти на важкі сети; ніколи не тренуйся напідпитку.',
      ],
    },
  },

  water: {
    ex: [
      'how much water should i drink',
      'how much water on training days',
      'am i drinking enough water',
      'does dehydration affect strength',
      'should i drink during my workout',
      'how to stay hydrated at the gym',
      'how many liters of water a day',
      'is 3 liters of water enough',
      'does water help build muscle',
      "how do i know if i'm dehydrated",
      'water intake for lifters',
      'drinking water between sets',
      'is gallon a day necessary',
      'hydration and performance',
    ],
    exUk: [
      'скільки води пити',
      'скільки пити води в дні тренувань',
      'я достатньо п’ю води?',
      'зневоднення впливає на силу?',
      'пити під час тренування?',
      'як не зневоднитись у залі',
      'скільки літрів води на день',
      '3 літри води — достатньо?',
      'вода допомагає м’язам рости?',
      'як зрозуміти, що мені бракує води',
      'пити воду між сетами',
      'сколько воды пить в день',
      'скільки треба пити водички',
      'гідратація і результат у залі',
    ],
    facets: {
      howMuch: [
        'Drink to thirst and a bit more on training days; there is no single number that fits everyone.',
        'Пий за відчуттям спраги й трохи більше в дні тренувань; єдиної цифри для всіх нема.',
      ],
      how: [
        'Check your urine: pale yellow means you are fine; sip water between sets during training.',
        'Дивись на сечу: світло-жовта — все гаразд; під час тренування пий потроху між сетами.',
      ],
      why: [
        'Losing just 1–2% of body weight as water already reduces performance.',
        'Навіть втрата 1–2% ваги тіла у вигляді води вже знижує результат.',
      ],
      when: [
        'Spread it through the day and top up around training, more in heat or when sweating a lot.',
        'Розподіляй протягом дня й додавай навколо тренування, більше в спеку чи коли сильно пітнієш.',
      ],
    },
  },

  sleep_better: {
    ex: [
      'how can i sleep better',
      "i can't sleep",
      'tips for better sleep',
      'i have insomnia',
      "can't fall asleep after evening workouts",
      'how to improve sleep quality',
      'i sleep badly, what should i change',
      'how to fall asleep faster',
      'i wake up at night a lot',
      'evening training keeps me awake',
      'how to fix my sleep schedule',
      'sleep hygiene tips for lifters',
      "can't sleep before a big lift day",
      'trouble sleeping',
    ],
    exUk: [
      'як краще спати',
      'не можу заснути',
      'поради для кращого сну',
      'в мене безсоння',
      'не засинаю після вечірнього тренування',
      'як покращити якість сну',
      'погано сплю, що змінити',
      'як швидше засинати',
      'часто прокидаюсь вночі',
      'як налагодити режим сну',
      'вечірні тренування не дають заснути',
      'не могу уснуть',
      'как лучше спать',
      'сплю погано, шо робити',
    ],
    facets: {
      how: [
        'Keep the same bed and wake time daily, a dark cool room, no screens or caffeine late, and train earlier if evening sessions wire you.',
        'Однаковий час відбою й підйому, темна прохолодна кімната, без екранів і кави ввечері, і тренуйся раніше, якщо вечірні заводять.',
      ],
      where: [
        'Set a sleep schedule in the Sleep screen and the app will remind you.',
        'Задай розклад на екрані «Сон» — додаток нагадає.',
      ],
      when: [
        'Stop caffeine about 8 hours before bed and put screens away in the last hour.',
        'Кофеїн — не пізніше ніж за 8 годин до сну, екрани — прибери за годину.',
      ],
      should: [
        'If poor sleep lasts for weeks despite good habits, or you snore heavily and wake unrested, talk to a doctor.',
        'Якщо поганий сон триває тижнями попри добрі звички, або ти сильно хропеш і прокидаєшся невиспаним, звернись до лікаря.',
      ],
    },
  },

  time_of_day: {
    ex: [
      'is it better to train in the morning or evening',
      'best time of day to lift',
      'morning or evening workouts',
      'am i weaker in the morning',
      'does training time matter',
      'should i work out at night',
      'is 6am a good time to lift',
      'what time do i usually train',
      'best time to go to the gym',
      'is training late at night bad',
      'morning workouts vs evening for strength',
      'when is the best time to work out',
      'does lifting after work give better results',
      'is it fine to switch between morning and evening sessions',
    ],
    exUk: [
      'коли краще тренуватись, вранці чи ввечері',
      'найкращий час для тренувань',
      'тренування зранку чи ввечері',
      'вранці я слабший?',
      'чи важить час тренування',
      'можна тренуватись пізно ввечері',
      'о 6 ранку добре тренуватись?',
      'о котрій я зазвичай тренуюсь',
      'о котрій краще йти в зал',
      'пізні тренування — погано?',
      'після роботи тренуватись краще?',
      'когда лучше тренироваться, утром или вечером',
      'в какое время лучше качаться',
      'зранку чи ввечері йти на трєню',
    ],
    facets: {
      when: [
        'Whenever you can do it consistently; most people are slightly stronger in the afternoon or evening.',
        'Тоді, коли зможеш регулярно; більшість трохи сильніші вдень чи ввечері.',
      ],
      why: [
        'Body temperature and alertness peak later in the day, which gives a small strength edge; consistency matters far more.',
        'Температура тіла й бадьорість пікують пізніше вдень, що дає невелику перевагу в силі; регулярність важить набагато більше.',
      ],
      should: [
        'Morning is fine: warm up a bit longer, and the body adapts to your usual training time.',
        'Ранок — нормально: розминайся трохи довше, і тіло підлаштується під твій звичний час.',
      ],
      how: [
        'If late sessions hurt your sleep, move them earlier or skip caffeine before them.',
        'Якщо пізні тренування заважають сну, перенеси їх раніше або не пий перед ними кофеїн.',
      ],
    },
  },

  fasted: {
    ex: [
      'is it ok to train fasted',
      'should i lift on an empty stomach',
      'fasted cardio good for fat loss',
      'can i work out before breakfast',
      'training without eating first',
      'fasted training while intermittent fasting',
      'lifting heavy fasted bad?',
      'morning workout without breakfast',
      'does fasted training burn more fat',
      'do i need to eat before the gym in the morning',
      'gym on an empty stomach',
      'is fasted weight training safe',
      'i feel weak lifting fasted',
      'working out before eating anything',
    ],
    exUk: [
      'можна тренуватись натщесерце',
      'піднімати вагу на голодний шлунок?',
      'кардіо натщесерце для схуднення',
      'тренування без сніданку',
      'тренуватись, нічого не поївши',
      'інтервальне голодування і тренування натщесерце',
      'важкі силові натщесерце — погано?',
      'ранкове тренування без сніданку',
      'натщесерце спалюється більше жиру?',
      'треба їсти перед ранковим залом?',
      'в зал на голодний желудок',
      'слабкий, коли тренуюсь натщесерце',
      'можно тренироваться натощак',
      'на голодняк в зал норм?',
    ],
    facets: {
      should: [
        'Fasted is fine for easy cardio; for heavy lifting, a small meal 1–3 hours before usually means better sets.',
        'Натщесерце — нормально для легкого кардіо; для важких силових невеликий прийом їжі за 1–3 години зазвичай дає кращі сети.',
      ],
      when: [
        'Eat a small meal 1–3 hours before heavy training.',
        'Невеликий прийом їжі — за 1–3 години до важкого тренування.',
      ],
      why: [
        'Fasted cardio does not burn more fat over the day; the daily calorie balance decides fat loss, while food before lifting supports performance.',
        'Кардіо натщесерце не спалює більше жиру за добу; схуднення визначає денний баланс калорій, а їжа перед силовим підтримує результат.',
      ],
      how: [
        'If you must train early, try something light like a banana or yogurt 30–60 minutes before.',
        'Якщо тренуєшся рано, спробуй щось легке, як банан чи йогурт, за 30–60 хвилин до.',
      ],
    },
  },

  caffeine: {
    ex: [
      'does caffeine help lifting',
      'coffee before the gym',
      'how much caffeine before a workout',
      'is an energy drink before training ok',
      'should i drink coffee before training',
      'best time to have caffeine before a workout',
      'can caffeine make me stronger',
      'too much coffee bad for gains',
      'caffeine late afternoon workout sleep',
      'how many mg of caffeine pre workout',
      'does coffee dehydrate you',
      'is caffeine a good pre-workout',
      'caffeine tolerance for training',
      'espresso before heavy squats',
    ],
    exUk: [
      'кава перед тренуванням допомагає?',
      'випити каву перед залом',
      'скільки кофеїну перед тренуванням',
      'енергетик перед тренуванням — норм?',
      'коли пити каву перед тренуванням',
      'кофеїн робить сильнішим?',
      'забагато кави шкодить?',
      'кава перед вечірнім тренуванням і сон',
      'скільки мг кофеїну брати',
      'кава зневоднює?',
      'кофеїн як передтрен',
      'кофе перед тренировкой',
      'сколько кофеина пить перед залом',
      'енергос перед трєнькою можна?',
    ],
    facets: {
      howMuch: [
        'About 3 mg per kg of body weight is an effective dose.',
        'Близько 3 мг на кг ваги тіла — ефективна доза.',
      ],
      when: [
        'Take it 30–60 minutes before training, and not within about 8 hours of bedtime.',
        'Приймай за 30–60 хвилин до тренування і не пізніше ніж за ~8 годин до сну.',
      ],
      why: [
        'Caffeine reduces perceived effort and slightly boosts strength and endurance.',
        'Кофеїн зменшує відчуття зусилля й трохи підвищує силу та витривалість.',
      ],
      should: [
        'Yes if you tolerate it; skip it late in the day and be careful with heart issues or anxiety.',
        'Так, якщо добре переносиш; не пий пізно ввечері й будь обережним при проблемах із серцем чи тривожності.',
      ],
    },
  },

  protein_timing: {
    ex: [
      'when should i drink my protein shake',
      'protein before or after workout',
      'is there an anabolic window',
      'do i need protein right after the gym',
      'protein timing for muscle growth',
      'should i have a shake immediately after lifting',
      'does it matter when i eat protein',
      'protein before bed',
      '30 minute window after training myth',
      'best time to take whey',
      'shake before training or after',
      'how soon after workout protein',
      'should i drink protein on rest days',
      'casein at night worth it',
    ],
    exUk: [
      'коли пити протеїн',
      'протеїн до чи після тренування',
      'анаболічне вікно існує?',
      'треба білок одразу після залу?',
      'коли краще їсти білок',
      'шейк одразу після тренування?',
      'чи важливо, коли їсти білок',
      'протеїн перед сном',
      'вікно 30 хвилин після тренування — міф?',
      'коли краще приймати протеїн',
      'протеїн у вихідний день пити?',
      'казеїн на ніч — варто?',
      'когда пить протеин',
      'протик до чи після трєні',
    ],
    facets: {
      when: [
        'A protein meal within a few hours around training is enough; there is no 30-minute window.',
        'Білковий прийом у межах кількох годин навколо тренування — достатньо; «вікна в 30 хвилин» нема.',
      ],
      why: [
        'Muscle growth depends mostly on total daily protein, so timing barely changes the result.',
        'Ріст м’язів залежить переважно від денної суми білка, тож час прийому майже не змінює результат.',
      ],
      how: [
        'Spread protein across 3–5 meals a day and have one of them around your session.',
        'Розподіли білок на 3–5 прийомів на день і один із них зроби навколо тренування.',
      ],
      should: [
        'Drink a shake whenever it helps you hit your daily total, including rest days and before bed.',
        'Пий шейк тоді, коли він допомагає добрати денну норму, зокрема у вихідні й перед сном.',
      ],
    },
  },

  travel: {
    ex: [
      'how to train while travelling',
      'going on vacation, what about my workouts',
      'workout in a hotel room',
      "i'm on a business trip, how to keep training",
      'will i lose gains on a two week holiday',
      'hotel gym workout ideas',
      'training on a trip with no equipment',
      'how to stay in shape on vacation',
      'travelling next week, what should i do',
      'can i skip training while on holiday',
      'minimal workout for travel',
      'how many sessions a week while traveling',
      'log a travel workout',
      'away for a month, how to keep my progress',
    ],
    exUk: [
      'як тренуватись у подорожі',
      'їду у відпустку, що з тренуваннями',
      'тренування в номері готелю',
      'я у відрядженні, як тренуватись',
      'втрачу м’язи за два тижні відпустки?',
      'що робити в готельному залі',
      'тренування в поїздці без обладнання',
      'як тримати форму у відпустці',
      'наступного тижня їду, що робити',
      'можна не тренуватись у відпустці',
      'скільки тренувань на тиждень у поїздці',
      'как тренироваться в отпуске',
      'в командировке как тренироваться',
      'їду на море, шо з трєнями',
    ],
    facets: {
      howMuch: [
        '2 short sessions a week are enough to keep what you have built.',
        '2 короткі тренування на тиждень достатньо, щоб зберегти набуте.',
      ],
      how: [
        'Push-ups, split squats, rows on a table, planks: 3 rounds, close to failure. Log them and they count.',
        'Віджимання, болгарські присіди, тяги за стіл, планка — 3 кола, близько до відмови. Записуй — це зарахується.',
      ],
      why: [
        'Muscle and strength are kept with far less work than it took to build them.',
        'М’язи й силу зберегти можна значно меншою роботою, ніж потрібно для їх набору.',
      ],
      should: [
        'A week or two off will not cost real muscle; short sessions simply make coming back easier.',
        'Тиждень-два перерви не заберуть справжніх м’язів; короткі тренування просто полегшують повернення.',
      ],
    },
  },

  home: {
    ex: [
      'workout at home without equipment',
      'no gym, what can i do',
      'bodyweight workout for muscle',
      'can i build muscle at home',
      'home training without weights',
      'gym is closed, give me a workout',
      'how to train legs at home with no equipment',
      'how to make home workouts harder',
      'no equipment chest workout',
      "i can't go to the gym, what now",
      'home workout for strength',
      'train at home with just a backpack',
      'effective exercises without equipment',
      'bodyweight only routine',
    ],
    exUk: [
      'тренування вдома без обладнання',
      'немає залу, що робити',
      'тренування з власною вагою для м’язів',
      'можна накачатись вдома?',
      'домашнє тренування без ваг',
      'зал закритий, дай тренування',
      'як тренувати ноги вдома без інвентарю',
      'як ускладнити домашні тренування',
      'груди без обладнання',
      'не можу піти в зал, що робити',
      'тренування вдома з рюкзаком',
      'как тренироваться дома без инвентаря',
      'тренировка дома без зала',
      'вдома без залізяк шо можна робити',
    ],
    facets: {
      how: [
        'Push-ups, pike push-ups, split squats, single-leg RDLs, table rows and planks, with slow reps close to failure.',
        'Віджимання, віджимання «щучкою», болгарські присіди, румунська на одній нозі, тяги за стіл і планка — повільно й близько до відмови.',
      ],
      should: [
        'Yes, you can build muscle at home as long as sets are taken close to failure.',
        'Так, м’язи можна будувати вдома, якщо підходи близькі до відмови.',
      ],
      what: [
        'For extra load, use a backpack filled with books.',
        'Для додаткового обтяження — рюкзак із книжками.',
      ],
      why: [
        'Muscle responds to effort near failure, not to the tool; bodyweight works if the sets are hard enough.',
        'М’язи реагують на зусилля близько до відмови, а не на інструмент; власна вага працює, якщо сети достатньо важкі.',
      ],
    },
  },

  comeback: {
    ex: [
      'coming back after a break',
      'returning to the gym after months off',
      "haven't trained in a while, where do i start",
      'missed a week, how heavy should i go',
      'back after a long break, what weights',
      'how long to regain strength after time off',
      'took a month off lifting',
      'starting again after a break',
      'did i lose all my gains after the break',
      'first workout after a long pause',
      'how to ease back into lifting',
      'after vacation, back to the gym',
      'muscle memory after time off',
      'i stopped training for half a year',
    ],
    exUk: [
      'повертаюсь після перерви',
      'повернення в зал після кількох місяців',
      'давно не тренувався, з чого почати',
      'пропустив тиждень, яку вагу брати',
      'після довгої перерви які ваги ставити',
      'як швидко повернеться сила після перерви',
      'пропустив місяць тренувань',
      'починаю знову після перерви',
      'я втратив усе за перерву?',
      'перше тренування після паузи',
      'м’язова пам’ять після перерви',
      'не тренувався пів року',
      'после перерыва с чего начать',
      'давно не ходив в зал, як вкатитись',
    ],
    facets: {
      howMuch: [
        'Start at about 80–90% of your old weights for a week or two.',
        'Почни з приблизно 80–90% старих ваг на тиждень-два.',
      ],
      why: [
        'Strength and muscle come back faster than they took to build, thanks to muscle memory.',
        'Сила й м’язи повертаються швидше, ніж набирались, завдяки м’язовій пам’яті.',
      ],
      how: [
        'Ease in with fewer hard sets and leave reps in reserve, then build back to your old numbers over a few weeks.',
        'Входь поступово: менше важких сетів і повтори в запасі, а за кілька тижнів повертайся до старих цифр.',
      ],
      should: [
        'Do not try to match your old best on day one; expect more soreness at first.',
        'Не намагайся в перший день повторити старий рекорд; спочатку чекай більшої крепатури.',
      ],
    },
  },

  rest_day: {
    ex: [
      'what should i do on a rest day',
      'what to do on my day off from the gym',
      'is active recovery good',
      'can i walk on rest days',
      'rest day activities',
      'should i do anything on off days',
      'light cardio on rest day ok',
      'how to spend a rest day',
      'is swimming ok on rest day',
      'should i eat less on rest days',
      'what counts as active recovery',
      'rest day stretching?',
      'can i log a walk on my rest day',
      'completely rest or move on rest days',
    ],
    exUk: [
      'що робити у вихідний від залу',
      'чим зайнятись у день відпочинку',
      'активне відновлення корисне?',
      'можна гуляти у вихідні дні',
      'що робити в день без тренування',
      'легке кардіо у вихідний — норм?',
      'як провести день відпочинку',
      'басейн у вихідний можна?',
      'їсти менше у вихідні?',
      'що вважається активним відновленням',
      'розтяжка у вихідний день',
      'повністю лежати чи рухатись у вихідний',
      'что делать в день отдыха',
      'шо робити у вихідний від трєні',
    ],
    facets: {
      how: [
        'Walk, an easy bike ride or swim, some mobility work, plus good sleep and enough food.',
        'Прогулянка, легкий велосипед чи басейн, трохи мобільності, плюс добрий сон і достатньо їжі.',
      ],
      where: [
        'If you move, log it as an activity in the app; it counts.',
        'Рухаєшся — запиши це в додатку як активність, це рахується.',
      ],
      why: [
        'Easy movement boosts blood flow and eases stiffness without adding fatigue.',
        'Легкий рух покращує кровообіг і знімає скутість, не додаючи втоми.',
      ],
      should: [
        'Keep eating normally, protein included: recovery happens on rest days.',
        'Їж як завжди, включно з білком: відновлення відбувається саме у вихідні.',
      ],
    },
  },

  beginner: {
    ex: [
      "i'm a beginner, where do i start",
      'how do i start lifting',
      'new to the gym, what should i do',
      'just started working out',
      'beginner workout plan',
      'first time in the gym, help',
      'how should a beginner train',
      'never lifted before, what program',
      'how to get started with weights',
      'beginner routine for muscle and strength',
      'what should my first month look like',
      'complete newbie, advice',
      'how many days a week should a beginner lift',
      'starting from zero at the gym',
    ],
    exUk: [
      'я новачок, з чого почати',
      'як почати займатись в залі',
      'новенький у залі, що робити',
      'тільки почав тренуватись',
      'програма для початківця',
      'вперше в залі, допоможи',
      'як тренуватись новачку',
      'ніколи не піднімав ваги, яка програма',
      'як почати з вагами',
      'яким має бути перший місяць',
      'скільки разів на тиждень тренуватись новачку',
      'я початківець, порадь',
      'с чего начать новичку в зале',
      'новачок повний, шо робити',
    ],
    facets: {
      how: [
        '3 full-body sessions a week, 5–6 big lifts, 2–3 sets of 8–12, and add a little weight when all sets reach 12.',
        '3 тренування на все тіло на тиждень, 5–6 базових вправ, 2–3 сети по 8–12, і додавай трохи ваги, коли всі сети по 12.',
      ],
      where: [
        "Take Atlas's programme in the app; it is built exactly this way.",
        'Візьми програму Atlas у додатку — вона побудована саме так.',
      ],
      why: [
        'Beginners progress fastest on simple, repeated full-body work where they practise the main lifts often.',
        'Новачки найшвидше прогресують на простих повторюваних тренуваннях на все тіло, де часто відпрацьовують основні вправи.',
      ],
      howMuch: [
        'Three sessions a week is enough to start; focus on showing up and adding small amounts of weight.',
        'Трьох тренувань на тиждень досить для старту; головне — ходити й потроху додавати вагу.',
      ],
    },
  },

  shoes: {
    ex: [
      'what shoes should i lift in',
      'are running shoes ok for squats',
      'should i deadlift barefoot',
      'do i need weightlifting shoes',
      'best sneakers for the gym',
      'flat shoes for deadlifts',
      'squat shoes worth it',
      'can i lift in socks',
      'are converse good for lifting',
      'cushioned trainers for heavy squats bad?',
      'lifting shoes with raised heel',
      'what footwear for leg day',
      'barefoot lifting pros and cons',
      'my shoes feel wobbly under the bar',
    ],
    exUk: [
      'в якому взутті тренуватись',
      'бігові кросівки для присіду підходять?',
      'станову тягнути босоніж?',
      'чи потрібні штангетки',
      'які кросівки для залу',
      'пласке взуття для станової',
      'штангетки для присіду варто?',
      'можна тренуватись у шкарпетках',
      'кеди для силових підходять?',
      'м’які кросівки під важкий присід — погано?',
      'яке взуття на день ніг',
      'в каких кроссовках приседать',
      'штангетки нужны?',
      'в чому присідати, в кросах чи босим',
    ],
    facets: {
      what: [
        'Use flat, firm soles for squats and deadlifts, or lifting shoes with a raised heel for squats.',
        'Для присідів і станової — пласка тверда підошва, або штангетки з підйомом п’яти для присідів.',
      ],
      why: [
        'Soft running shoes compress and make you wobble under heavy loads.',
        'М’які бігові кросівки стискаються й під важкою вагою хитаються.',
      ],
      should: [
        'Lifting shoes are optional; they help most if your ankles are stiff and you squat upright.',
        'Штангетки не обов’язкові; найбільше вони допомагають, якщо гомілкостоп скутий і ти присідаєш рівно.',
      ],
      who: [
        'Heeled shoes suit squatters with limited ankle mobility; flat shoes or socks suit deadlifts.',
        'Взуття з підйомом підходить тим, хто присідає з обмеженою рухливістю гомілкостопу; пласке чи шкарпетки — для станової.',
      ],
    },
  },
};
