/**
 * Polish, Lithuanian and Estonian phrasings, part C: how the app works.
 */
export const KB_PLLTET_2C: Record<string, string[]> = {
  app_tips: [
    'daj mi wskazówki do aplikacji',
    'jakieś triki w tej apce',
    'porady jak lepiej korzystać z aplikacji',
    'kokių patarimų turi apie šią programėlę',
    'kokių gudrybių yra šioje programėlėje',
    'patarimai kaip geriau naudotis programėle',
    'anna äpi kohta nippe',
    'mingeid nippe selle äpi jaoks',
    'nõuanded, kuidas äppi paremini kasutada',
  ],
  app_tour: [
    'jak działa ta aplikacja',
    'pokaż mi co potrafi ta apka',
    'oprowadź mnie po aplikacji',
    'kaip veikia ši programėlė',
    'parodyk ką moka ši programėlė',
    'aprodyk man programėlę',
    'kuidas see äpp töötab',
    'näita, mida see äpp oskab',
    'tutvusta mulle äppi',
  ],
  app_start_session: [
    'jak rozpocząć trening w aplikacji',
    'gdzie kliknąć żeby zacząć sesję',
    'jak włączyć nowy trening w apce',
    'kaip pradėti treniruotę programėlėje',
    'kur paspausti kad pradėčiau sesiją',
    'kaip įjungti naują treniruotę',
    'kuidas äpis trenni alustada',
    'kuhu vajutada, et sessiooni alustada',
    'kuidas uut trenni äpis käivitada',
  ],
  app_auto_session: [
    'jak działa automatyczna sesja',
    'aplikacja sama zaczęła trening, dlaczego',
    'auto sesja co to jest',
    'kaip veikia automatinė sesija',
    'programėlė pati pradėjo treniruotę, kodėl',
    'automatinė treniruotė, kas tai',
    'kuidas automaatne sessioon töötab',
    'äpp alustas ise trenni, miks',
    'automaatne trenn, mis see on',
  ],
  app_finish_session: [
    'jak skończyć trening w aplikacji',
    'gdzie jest przycisk zakończenia treningu',
    'jak zamknąć sesję w apce',
    'kaip baigti treniruotę programėlėje',
    'kur yra treniruotės pabaigos mygtukas',
    'kaip uždaryti sesiją',
    'kuidas äpis trenn lõpetada',
    'kus on trenni lõpetamise nupp',
    'kuidas sessioon sulgeda',
  ],
  app_home_set: [
    'jak zapisać trening w domu',
    'ćwiczę w domu, jak to zalogować',
    'trening domowy w aplikacji, jak dodać',
    'kaip įrašyti treniruotę namuose',
    'sportuoju namie, kaip užregistruoti',
    'namų treniruotė programėlėje, kaip pridėti',
    'kuidas kodust trenni kirja panna',
    'treenin kodus, kuidas seda salvestada',
    'kodutrenn äpis, kuidas lisada',
  ],
  app_rest_period: [
    'jak wstrzymać plan na chorobę',
    'wyjeżdżam, jak zapauzować treningi',
    'przerwa w planie bez utraty serii',
    'kaip sustabdyti planą ligos metu',
    'išvykstu, kaip pristabdyti treniruotes',
    'pertrauka plane neprarandant serijos',
    'kuidas kava haiguse ajaks peatada',
    'lähen ära, kuidas trennid pausile panna',
    'paus kavas ilma seeriat kaotamata',
  ],
  app_week_start: [
    'jak ustawić początek tygodnia na niedzielę',
    'tydzień zaczyna się od poniedziałku, zmienić',
    'pierwszy dzień tygodnia w ustawieniach',
    'kaip nustatyti kad savaitė prasidėtų sekmadienį',
    'savaitė prasideda pirmadienį, pakeisti',
    'pirmoji savaitės diena nustatymuose',
    'kuidas nädala algus pühapäevale panna',
    'nädal algab esmaspäevast, muuta',
    'nädala esimene päev seadetes',
  ],
  app_assign_program: [
    'jak przypisać plan klientowi',
    'jestem trenerem, jak dać podopiecznemu program',
    'wysłać program klientowi w aplikacji',
    'kaip priskirti programą klientui',
    'esu treneris, kaip duoti programą',
    'nusiųsti programą klientui programėlėje',
    'kuidas kliendile kava määrata',
    'olen treener, kuidas kliendile programmi anda',
    'saata kava kliendile äpis',
  ],
  app_apex: [
    'co to jest apex',
    'do czego służy apex w aplikacji',
    'apex co to za funkcja',
    'kas yra apex',
    'kam skirtas apex programėlėje',
    'apex kokia tai funkcija',
    'mis on apex',
    'milleks apex äpis on',
    'apex mis funktsioon see on',
  ],
  app_nutrition: [
    'jak działa aplikacja do żywienia',
    'gdzie liczyć kalorie w aplikacji',
    'moduł odżywiania co potrafi',
    'kaip veikia mitybos programėlė',
    'kur skaičiuoti kalorijas programėlėje',
    'mitybos modulis ką moka',
    'kuidas toitumise äpp töötab',
    'kus äpis kaloreid lugeda',
    'toitumise moodul, mida oskab',
  ],
  app_learn: [
    'co to jest aplikacja learn',
    'gdzie są lekcje i artykuły',
    'moduł nauki w apce',
    'kas yra learn programėlė',
    'kur yra pamokos ir straipsniai',
    'mokymosi modulis programėlėje',
    'mis on learn äpp',
    'kus on õppetunnid ja artiklid',
    'õppemoodul äpis',
  ],
  app_people: [
    'gdzie są ustawienia profilu',
    'jak wejść w mój profil',
    'gdzie zmienić dane konta w apce',
    'kur yra profilio nustatymai',
    'kaip patekti į savo profilį',
    'kur keisti paskyros duomenis',
    'kus on profiili seaded',
    'kuidas oma profiili pääseda',
    'kus kontoandmeid muuta',
  ],
  app_switch_apps: [
    'jak przełączać się między aplikacjami',
    'jak przejść z treningu do żywienia',
    'przełącznik aplikacji gdzie jest',
    'kaip persijungti tarp programėlių',
    'kaip pereiti iš treniruočių į mitybą',
    'kur yra programėlių perjungiklis',
    'kuidas äppide vahel vahetada',
    'kuidas trennist toitumisse minna',
    'kus on äppide vahetaja',
  ],
  app_progress_view: [
    'gdzie zobaczę swoje rekordy',
    'ekran postępów w aplikacji',
    'gdzie są wykresy postępu',
    'kur matyti savo rekordus',
    'progreso ekranas programėlėje',
    'kur yra progreso grafikai',
    'kus näen oma rekordeid',
    'arengu vaade äpis',
    'kus on arengu graafikud',
  ],
  app_lens: [
    'co to jest soczewka w postępach',
    'jak działa lens na ekranie postępów',
    'soczewka w zakładce progres',
    'kas yra lęšis progreso skiltyje',
    'kaip veikia lens progreso ekrane',
    'lens funkcija progrese',
    'mis on lääts arengu vaates',
    'kuidas lens arengu ekraanil töötab',
    'lens funktsioon arengus',
  ],
};
