/**
 * Polish, Lithuanian and Estonian phrasings for the hundred newer topics
 * (topicsMore*.ts) and the app help, which had only a few each — written
 * fresh, with and without diacritics, never copied from the exam.
 * Part A: programming, lifts, recovery.
 */
export const KB_PLLTET_2A: Record<string, string[]> = {
  k_amrap: [
    'co znaczy amrap w planie',
    'seria amrap ile powtórzeń robić',
    'ostatnia seria na maksa powtórzeń, jak to robić',
    'amrap czy zostawiać zapas',
    'ką reiškia amrap serija',
    'kiek pakartojimų daryti amrap serijoje',
    'paskutinė serija kiek galiu pakartojimų',
    'amrap iki nesėkmės ar ne',
    'mida tähendab amrap',
    'amrap seerias mitu kordust teha',
    'viimane seeria nii palju kordusi kui suudan, kuidas',
    'kas amrap tähendab lõpuni välja',
  ],
  k_emom: [
    'co to jest trening emom',
    'emom na 10 minut jak to działa',
    'każda minuta na minutę, o co chodzi',
    'kas yra emom',
    'kaip daryti emom treniruotę',
    'kiekvieną minutę po seriją, kaip tai veikia',
    'mis asi on emom',
    'kuidas emom trenn käib',
    'iga minuti alguses seeria, mis see on',
    'emom 12 minutit kuidas teha',
  ],
  k_cluster_sets: [
    'co to są serie klastrowe',
    'serie cluster jak robić',
    'krótkie przerwy w serii, cluster set',
    'kas yra klasterinės serijos',
    'cluster set kaip atlikti',
    'trumpos pauzės serijos viduje, kam to reikia',
    'kuidas klasterseeriaid teha',
    'lühikesed pausid seeria sees, milleks',
  ],
  k_rest_pause: [
    'na czym polega rest pause',
    'rest pause na biceps jak zrobić',
    'seria do upadku, krótka przerwa i dalej, co to',
    'kas yra rest pause metodas',
    'kaip daryti rest pause serijas',
    'rest pause ar tinka raumenų augimui',
    'mis on rest pause meetod',
    'kuidas rest pause seeriat teha',
    'kas rest pause sobib lihasmassiks',
  ],
  k_myo_reps: [
    'co to są myo reps',
    'jak robić myo powtórzenia',
    'myo reps czy klasyczne serie',
    'kas yra myo reps',
    'kaip daryti myo pakartojimus',
    'myo reps ar verta',
    'mis on myo reps',
    'kuidas myo kordusi teha',
    'kas myo reps on tõhus',
  ],
  k_double_progression: [
    'co to jest podwójna progresja',
    'progresja powtórzeń i ciężaru jak łączyć',
    'najpierw więcej powtórzeń potem ciężar, jak to działa',
    'kas yra dviguba progresija',
    'kaip taikyti dvigubą progresiją',
    'pirma pakartojimai, paskui svoris, ar tai gerai',
    'mis on topeltprogressioon',
    'kuidas kasutada kahekordset progressi',
    'enne kordused, siis raskus, kuidas',
  ],
  k_taper: [
    'jak zrobić taper przed zawodami',
    'odpuszczanie przed testem maksa',
    'ile tygodni odpoczywać przed zawodami',
    'kaip pasiruošti varžyboms, mažinti krūvį',
    'taper prieš maksimumo testą',
    'kiek sumažinti apimtį prieš varžybas',
    'kuidas enne võistlust koormust vähendada',
    'taper enne maksimumi testimist',
    'mitu nädalat enne võistlust kergemalt',
  ],
  k_top_backoff: [
    'top set i serie spadkowe, o co chodzi',
    'ile ująć ciężaru na seriach back off',
    'jedna ciężka seria a potem lżejsze',
    'kas yra top set ir back off serijos',
    'kiek numesti svorio po sunkiausios serijos',
    'viena sunki serija ir tada lengvesnės',
    'mis on top set ja back off seeriad',
    'kui palju raskust vähendada pärast raskeimat seeriat',
    'üks raske seeria ja siis kergemad',
  ],
  k_paused_reps: [
    'po co pauza w wyciskaniu na klatce',
    'przysiad z pauzą, co daje',
    'powtórzenia z zatrzymaniem, warto?',
    'kam reikalinga pauzė spaudime gulint',
    'pritūpimai su sustojimu apačioje, ką duoda',
    'ar verta daryti pakartojimus su pauze',
    'milleks paus pingil surumisel',
    'pausiga kükk, mis kasu',
    'kas pausiga kordused on seda väärt',
  ],
  k_eccentrics: [
    'czy wolne opuszczanie buduje mięśnie',
    'negatywy na podciąganiu, czy to działa',
    'faza ekscentryczna ile sekund',
    'lėtas nuleidimas ar augina raumenis',
    'negatyvūs prisitraukimai ar veikia',
    'ekscentrinė fazė kiek sekundžių',
    'aeglane langetamine, kas kasvatab lihaseid',
    'negatiivsed lõuatõmbed, kas aitavad',
    'ekstsentriline faas mitu sekundit',
  ],
  k_volume_landmarks: [
    'co to jest mev i mrv',
    'minimalna i maksymalna objętość, ile serii',
    'ile serii tygodniowo to za dużo, mrv',
    'kas yra mev ir mrv',
    'minimali ir maksimali apimtis kiek serijų',
    'kiek serijų per savaitę per daug',
    'mis on mev ja mrv',
    'minimaalne ja maksimaalne maht, mitu seeriat',
    'mitu seeriat nädalas on liiga palju',
  ],
  k_bfr: [
    'trening z okluzją czy działa',
    'opaski uciskowe na ramiona, bezpieczne?',
    'bfr na nogi, jak zakładać',
    'kraujotakos ribojimo treniruotė ar veikia',
    'bfr juostos ar saugu',
    'bfr treniruotė kojoms kaip',
    'verevoolu piiramisega treening, kas toimib',
    'bfr paelad kätele, kas ohutu',
    'bfr jalgadele kuidas teha',
  ],
  k_5x5: [
    'czy plan 5x5 jest dobry dla początkującego',
    'stronglifts 5 na 5 opinie',
    '5 serii po 5 powtórzeń, na siłę czy masę',
    'ar 5x5 programa gera pradedančiajam',
    'stronglifts 5x5 atsiliepimai',
    '5 serijos po 5 pakartojimus, jėgai ar masei',
    'kas 5x5 kava on algajale hea',
    'stronglifts 5x5 arvamus',
    '5 seeriat 5 kordust, jõuks või massiks',
  ],
  k_531: [
    'plan 5/3/1 jak działa',
    'wendler 531 dla kogo',
    'jak liczyć ciężary w 5 3 1',
    '5/3/1 programa, kaip ji sudaryta',
    'wendler 531 kam tinka',
    'kaip skaičiuoti svorius 5 3 1',
    '5/3/1 kava, kuidas see üles on ehitatud',
    'wendleri 531 kellele sobib',
    'kuidas raskusi arvutada 5 3 1 kavas',
  ],
  k_circuit_training: [
    'trening obwodowy na masę czy redukcję',
    'czy obwody budują mięśnie',
    'ćwiczenia jedno po drugim bez przerwy, dobre?',
    'ratinė treniruotė ar gera',
    'ar ratu treniruotė augina raumenis',
    'pratimai vienas po kito be poilsio',
    'kas ringtreening on hea',
    'kas ringtreening kasvatab lihaseid',
    'harjutused järjest ilma pausita, kas mõistlik',
  ],
  k_plyometrics: [
    'czy robić skoki pliometryczne',
    'pliometria na dynamikę',
    'wskoki na skrzynię, po co',
    'ar daryti pliometrinius šuolius',
    'šuoliai ant dėžės kam naudingi',
    'pliometrika sprogstamajai jėgai',
    'kas teha plüomeetrilisi hüppeid',
    'kastihüpped, milleks',
    'plüomeetrika plahvatuslikkuseks',
  ],
  k_front_squat: [
    'jak trzymać sztangę w przysiadzie przednim',
    'przysiad przedni boli nadgarstek',
    'front squat technika',
    'kaip laikyti štangą priekiniame pritūpime',
    'priekiniai pritūpimai skauda riešus',
    'front squat technika kaip',
    'kuidas eeskükis kangi hoida',
    'eeskükk teeb randmetele haiget',
    'front squat tehnika',
  ],
  k_hip_thrust: [
    'jak robić hip thrust poprawnie',
    'unoszenie bioder ze sztangą technika',
    'hip thrust gdzie oprzeć plecy',
    'kaip teisingai daryti hip thrust',
    'klubų kėlimas su štanga technika',
    'hip thrust kur remti nugarą',
    'kuidas puusatõstet õigesti teha',
    'hip thrust tehnika kangiga',
    'hip thrust kuhu selg toetada',
  ],
  k_rdl: [
    'martwy ciąg rumuński jak nisko schodzić',
    'rdl technika proste nogi',
    'rumuński martwy ciąg czuję plecy a nie dwójki',
    'rumuniška mirties trauka kaip žemai leistis',
    'rdl technika kojos beveik tiesios',
    'rumuniška trauka jaučiu nugarą, ne šlaunis',
    'rumeenia jõutõmme kui madalale minna',
    'rdl tehnika peaaegu sirged jalad',
    'rumeenia jõutõmbes tunnen selga, mitte reie tagakülge',
  ],
  k_bulgarian_split: [
    'przysiad bułgarski jak ustawić stopę',
    'wykrok bułgarski czuję tylko kolano',
    'bułgarskie przysiady na pośladki',
    'bulgariški pritūpimai kaip pastatyti koją',
    'bulgariški įtūpstai skauda kelį',
    'bulgariški pritūpimai sėdmenims',
    'bulgaaria kükk kuidas jalga asetada',
    'bulgaaria väljaaste valutab põlves',
    'bulgaaria kükk tuharatele',
  ],
  k_lunges: [
    'wykroki bolą mnie kolana, co źle robię',
    'jak robić wykroki bez bólu kolan',
    'wykroki chodzone technika',
    'įtūpstai skauda kelius, ką darau blogai',
    'kaip daryti įtūpstus be kelių skausmo',
    'išpuoliai einant technika',
    'väljaasted teevad põlvedele haiget, mida valesti teen',
    'kuidas väljaasteid ilma põlvevaluta teha',
    'kõndivad väljaasted tehnika',
  ],
  k_dips: [
    'czy pompki na poręczach szkodzą barkom',
    'dipy bolą z przodu barku',
    'jak głęboko schodzić na poręczach',
    'ar atsispaudimai ant lygiagrečių kenkia pečiams',
    'dipai skauda priekinę peties dalį',
    'kaip giliai leistis ant lygiagrečių',
    'kas rööbaspuudel surumine kahjustab õlgu',
    'dipid valutavad õla ees',
    'kui sügavale rööbaspuudel minna',
  ],
  k_face_pull: [
    'po co robić face pull',
    'face pull technika na wyciągu',
    'przyciąganie liny do twarzy, na co to',
    'kam daryti face pull',
    'face pull technika su trosu',
    'virvės traukimas prie veido, kam naudinga',
    'milleks face pulli teha',
    'face pull tehnika trossil',
    'nööri tõmbamine näo poole, mis kasu',
  ],
  k_lateral_raise: [
    'wznosy bokiem czuję tylko czworoboczny',
    'jak robić unoszenie hantli bokiem',
    'wznosy boczne technika',
    'šoniniai kėlimai jaučiu tik trapeciją',
    'kaip daryti hantelių kėlimą į šonus',
    'šoniniai kėlimai technika',
    'külgtõsted tunnen ainult trapetsis',
    'kuidas hantleid külgedele tõsta',
    'külgtõste tehnika',
  ],
  k_chinup_vs_pullup: [
    'podciąganie nachwytem czy podchwytem',
    'chin up a pull up różnica',
    'co lepsze na plecy, podchwyt czy nachwyt',
    'prisitraukimai plačiu ar siauru atvirkštiniu suėmimu',
    'chin up ir pull up skirtumas',
    'kas geriau nugarai, atvirkštinis ar tiesioginis suėmimas',
    'lõuatõmbed pealt- või altkäehaardega',
    'chin up ja pull up vahe',
    'kumb on seljale parem, alt- või pealthaare',
  ],
  k_bench_grip: [
    'jak szeroko łapać sztangę na ławce',
    'szerokość chwytu w wyciskaniu',
    'wąski czy szeroki chwyt na klatę',
    'kaip plačiai imti štangą spaudžiant gulint',
    'suėmimo plotis spaudime',
    'siauras ar platus suėmimas krūtinei',
    'kui laialt pingil kangist kinni võtta',
    'haarde laius pingil surumisel',
    'kitsas või lai haare rinnale',
  ],
  k_leg_drive: [
    'co to jest praca nóg w wyciskaniu',
    'jak używać nóg przy wyciskaniu na ławce',
    'leg drive na ławce',
    'kas yra kojų darbas spaudžiant gulint',
    'kaip naudoti kojas spaudime',
    'leg drive spaudžiant gulint',
    'mis on jalgade töö pingil',
    'kuidas pingil surudes jalgu kasutada',
    'leg drive pingil',
  ],
  k_high_low_bar: [
    'przysiad high bar czy low bar',
    'gdzie kłaść sztangę na plecach w przysiadzie',
    'wysoka czy niska pozycja gryfu',
    'aukšta ar žema štangos padėtis pritūpime',
    'kur dėti štangą ant nugaros',
    'high bar ar low bar pritūpimai',
    'kõrge või madal kangi asend kükis',
    'kuhu kang selja peal panna',
    'high bar või low bar kükk',
  ],
  k_good_morning: [
    'czy skłony ze sztangą good morning są dobre',
    'good morning ćwiczenie na dwójki',
    'good morning bezpieczne dla pleców?',
    'ar good morning pratimas geras',
    'good morning šlaunų užpakalinei daliai',
    'ar good morning saugus nugarai',
    'kas good morning harjutus on hea',
    'good morning reie tagaküljele',
    'kas good morning on seljale ohutu',
  ],
  k_farmer_carry: [
    'spacer farmera, co daje',
    'noszenie hantli w rękach, warto?',
    'farmer walk na chwyt',
    'ūkininko ėjimas ką duoda',
    'nešti hanteles rankose ar verta',
    'farmer walk gniaužtui',
    'farmeri kõnd, mis kasu',
    'hantlitega kõndimine, kas tasub',
    'farmer walk haardejõuks',
  ],
  k_calves: [
    'łydki mi nie rosną, co robić',
    'jak rozbudować łydki',
    'wspięcia na palce nic nie dają',
    'kaip priversti blauzdas augti',
    'kaip padidinti blauzdas',
    'pasistiebimai nieko neduoda',
    'sääremarjad ei kasva, mida teha',
    'kuidas sääri suuremaks saada',
    'varvastele tõusud ei aita',
  ],
  k_trap_bar: [
    'martwy ciąg na trap barze a klasyczny',
    'sztanga heksagonalna czy zwykła',
    'trap bar lepszy dla pleców?',
    'šešiakampė štanga ar įprasta trauka',
    'trap bar mirties trauka ar tokia pat gera',
    'trap bar geresnis nugarai?',
    'trap bar jõutõmme või tavaline',
    'kuusnurkne kang või tavaline',
    'kas trap bar on seljale parem',
  ],
  k_nordic_curl: [
    'nordic curl dla piłkarzy',
    'uginanie nordyckie jak zacząć',
    'ćwiczenie nordic na dwójki',
    'nordic curl futbolininkams',
    'šiaurietiški lenkimai kaip pradėti',
    'nordic curl šlaunies užpakaliui',
    'nordic curl jalgpallis vigastuste vastu',
    'põhjamaine painutus kuidas alustada',
    'nordic curl reie tagaküljele',
  ],
  k_pistol_squat: [
    'jak nauczyć się przysiadu pistolet',
    'przysiad na jednej nodze progresja',
    'pistol squat od czego zacząć',
    'kaip išmokti pistoletą pritūpime',
    'pritūpimas ant vienos kojos progresija',
    'pistol squat nuo ko pradėti',
    'kuidas püstolkükki õppida',
    'ühel jalal kükk progressioon',
    'pistol squat kust alustada',
  ],
  k_no_soreness: [
    'nie mam zakwasów po treningu, czy to źle',
    'brak bólu mięśni, czy rosnę',
    'przestałem czuć zakwasy, trening nie działa?',
    'neskauda raumenų po treniruotės, ar tai blogai',
    'nebejaučiu raumenų skausmo, ar augu',
    'nustojo skaudėti raumenis, ar treniruotė neveikia',
    'lihased ei valuta pärast trenni, kas see on halb',
    'enam ei tunne lihasvalu, kas kasvan',
    'lihasvalu kadus, kas trenn ei toimi',
  ],
  k_massage_gun: [
    'pistolet do masażu czy warto kupić',
    'masażer perkusyjny na regenerację',
    'theragun ma sens?',
    'masažinis pistoletas ar verta pirkti',
    'perkusinis masažuoklis atsigavimui',
    'theragun ar verta',
    'massaažipüstol kas tasub osta',
    'massaažirelv taastumiseks',
    'kas theragun on mõttekas',
  ],
  k_wearables: [
    'zegarek pokazuje niską regenerację, trenować?',
    'czy ufać hrv z opaski',
    'whoop mówi że nie jestem gotowy',
    'laikrodis rodo žemą atsigavimą, ar sportuoti',
    'ar pasitikėti apyrankės hrv',
    'whoop sako kad nesu pasiruošęs',
    'kell näitab madalat taastumist, kas treenida',
    'kas usaldada käevõru hrv-d',
    'whoop ütleb, et ma pole valmis',
  ],
  k_cns_fatigue: [
    'zmęczenie układu nerwowego istnieje?',
    'czy cns fatigue to mit',
    'przemęczenie ośrodkowego układu nerwowego po martwym',
    'ar centrinės nervų sistemos nuovargis tikras',
    'cns nuovargis mitas ar ne',
    'nervų sistemos nuovargis po mirties traukos',
    'kas kesknärvisüsteemi väsimus on päris',
    'cns väsimus müüt või tõde',
    'närvisüsteemi väsimus pärast jõutõmmet',
  ],
  k_detraining: [
    'ile mięśni stracę jak przestanę ćwiczyć',
    'po jakim czasie tracę siłę bez treningu',
    'dwa tygodnie przerwy, stracę efekty?',
    'kiek raumenų prarasiu nustojęs sportuoti',
    'po kiek laiko prarandama jėga be treniruočių',
    'dvi savaitės pertraukos, ar prarasiu rezultatus',
    'kui palju lihaseid kaotan, kui lõpetan treenimise',
    'kui kiiresti jõud ilma trennita kaob',
    'kaks nädalat pausi, kas kaotan tulemused',
  ],
  k_joint_supplements: [
    'glukozamina na stawy działa?',
    'kolagen na kolana, warto?',
    'suplementy na stawy dla ciężarowca',
    'ar gliukozaminas padeda sąnariams',
    'kolagenas keliams ar verta',
    'papildai sąnariams sportuojantiems',
    'kas glükoosamiin aitab liigeseid',
    'kollageen põlvedele, kas tasub',
    'liigestele toidulisandid jõusaalis käijale',
  ],
};
