/**
 * Polish, Lithuanian and Estonian phrasings, part B: food and supplements,
 * cardio, mobility, gear, people and life stages, the mind, the body.
 */
export const KB_PLLTET_2B: Record<string, string[]> = {
  k_creatine_myths: [
    'czy kreatyna powoduje wypadanie włosów',
    'od kreatyny puchnę, to normalne?',
    'kreatyna niszczy nerki czy to mit',
    'ar kreatinas sukelia plaukų slinkimą',
    'nuo kreatino pabrinkstu, ar normalu',
    'ar kreatinas kenkia inkstams',
    'kas kreatiin kahjustab neere',
    'kreatiinist tunnen end paistes, kas normaalne',
    'kas kreatiin on juustele ohtlik',
  ],
  k_protein_powder: [
    'jakie białko kupić, izolat czy koncentrat',
    'który proszek białkowy najlepszy',
    'odżywka białkowa jaka na początek',
    'kokius baltymus pirkti, izoliatą ar koncentratą',
    'koks baltymų miltelių tipas geriausias',
    'baltymų kokteilis kokį rinktis',
    'millist valgupulbrit valida, isolaat või kontsentraat',
    'milline proteiinipulber on parim',
    'valgujook mida algajale osta',
  ],
  k_protein_per_meal: [
    'ile białka na jeden posiłek ma sens',
    'czy organizm przyswoi 50 g białka naraz',
    'maksymalna porcja białka w posiłku',
    'kiek baltymų per vieną valgymą verta',
    'ar kūnas pasisavins 50 g baltymų iš karto',
    'maksimali baltymų porcija per valgį',
    'kui palju valku ühe söögikorra kohta mõistlik',
    'kas keha omastab 50 g valku korraga',
    'maksimaalne valgukogus ühes toidukorras',
  ],
  k_intra_workout: [
    'co pić podczas długiego treningu',
    'napój w trakcie treningu, woda czy izotonik',
    'czy pić coś słodkiego na treningu',
    'ką gerti per ilgą treniruotę',
    'gėrimas treniruotės metu, vanduo ar izotoninis',
    'ar gerti ką nors saldaus treniruotėje',
    'mida pika trenni ajal juua',
    'jook trenni ajal, vesi või spordijook',
    'kas trennis midagi magusat juua',
  ],
  k_vitamin_d: [
    'czy brać witaminę d zimą',
    'witamina d dla sportowca ile',
    'suplementacja d3 warto?',
    'ar vartoti vitaminą d žiemą',
    'vitaminas d sportuojančiam kiek',
    'd3 papildai ar verta',
    'kas võtta talvel d-vitamiini',
    'd-vitamiin sportlasele kui palju',
    'd3 lisamine kas tasub',
  ],
  k_magnesium: [
    'magnez na sen działa?',
    'czy brać magnez na skurcze',
    'magnez dla ćwiczących',
    'ar magnis padeda miegui',
    'ar vartoti magnį nuo mėšlungio',
    'magnis sportuojantiems',
    'magneesium enne magamist, kas mõjub',
    'kas võtta magneesiumi krampide vastu',
    'magneesium trenni tegijale',
  ],
  k_test_boosters: [
    'boostery testosteronu działają?',
    'tribulus na testosteron, ściema?',
    'suplementy podnoszące testosteron',
    'ar testosterono boosteriai veikia',
    'tribulus testosteronui, apgaulė?',
    'papildai testosteronui didinti',
    'kas testosterooni boosterid toimivad',
    'tribulus testosterooniks, kas pettus',
    'toidulisandid testosterooni tõstmiseks',
  ],
  k_fat_burners: [
    'czy spalacze tłuszczu mają sens',
    'tabletki na odchudzanie dla ćwiczących',
    'termogenik pomaga schudnąć?',
    'ar riebalų deginimo tabletės veikia',
    'lieknėjimo tabletės sportuojantiems',
    'termogenikas padeda numesti svorio?',
    'kas rasvapõletajad on mõttekad',
    'kaalulangetustabletid trennitegijale',
    'kas termogeenik aitab kaalu kaotada',
  ],
  k_reverse_diet: [
    'koniec redukcji, jak wracać do normalnego jedzenia',
    'po redukcji jak zwiększać kalorie',
    'dieta odwrotna, co to jest',
    'kaip išeiti iš lieknėjimo, reverse diet',
    'po dietos kaip didinti kalorijas',
    'atvirkštinė dieta, kas tai',
    'kuidas dieedist välja tulla, reverse diet',
    'pärast kaalulangetust kuidas kaloreid tõsta',
    'vastupidine dieet, mis see on',
  ],
  k_diet_break: [
    'przerwa od diety w trakcie redukcji',
    'dzień refeed czy potrzebny',
    'czy robić dzień ładowania węgli',
    'pertrauka nuo dietos lieknėjant',
    'refeed diena ar reikalinga',
    'ar daryti angliavandenių dieną',
    'dieedipaus kaalulangetuse ajal',
    'refeed päev kas vaja',
    'kas teha süsivesikute laadimise päev',
  ],
  k_scale_fluctuations: [
    'czemu waga rano skacze o kilogram',
    'przytyłem 2 kg w jeden dzień, jak to',
    'waga się waha codziennie, normalne?',
    'kodėl svarstyklės ryte šokinėja kilogramu',
    'priaugau 2 kg per dieną, kaip taip',
    'svoris kasdien svyruoja, ar normalu',
    'miks kaal hommikul kilo võrra kõigub',
    'võtsin päevaga 2 kg juurde, kuidas',
    'kaal kõigub iga päev, kas normaalne',
  ],
  k_keto: [
    'dieta keto a trening siłowy',
    'czy na keto można budować mięśnie',
    'keto i siłownia, dobry pomysł?',
    'keto dieta ir jėgos treniruotės',
    'ar keto dietoje galima auginti raumenis',
    'keto ir sporto salė, gera mintis?',
    'keto dieet ja jõutreening',
    'kas keto peal saab lihaseid kasvatada',
    'keto ja jõusaal, kas hea mõte',
  ],
  k_intermittent_fasting: [
    'post przerywany a budowa masy',
    'if 16 8 i trening, jak łączyć',
    'czy głodówka przerywana niszczy mięśnie',
    'protarpinis badavimas ir raumenų auginimas',
    '16 8 badavimas ir treniruotės',
    'ar protarpinis badavimas naikina raumenis',
    'kas 16 8 paastuga saab massi kasvatada',
    '16 8 paast ja trenn, kuidas ühendada',
    'kas vahelduv paast hävitab lihaseid',
  ],
  k_teen_supplements: [
    'czy nastolatek może brać odżywkę białkową',
    'kreatyna dla 16 latka?',
    'suplementy dla młodzieży ćwiczącej',
    'ar paauglys gali vartoti baltymų',
    'kreatinas šešiolikmečiui?',
    'papildai sportuojantiems paaugliams',
    'kas teismeline võib valgupulbrit võtta',
    'kreatiin 16 aastasele?',
    'toidulisandid treenivatele noortele',
  ],
  k_vo2max: [
    'jak zwiększyć vo2max bieganiem',
    'trening na wydolność tlenową',
    'podnieść pułap tlenowy, jakie interwały',
    'kaip padidinti vo2max',
    'treniruotė aerobinei ištvermei',
    'deguonies suvartojimo gerinimas, kokie intervalai',
    'kuidas vo2max-i tõsta',
    'treening aeroobse võimekuse jaoks',
    'hapnikutarbimise tõstmine, millised intervallid',
  ],
  k_incline_walk: [
    'chodzenie pod górę na bieżni, dobre cardio?',
    'marsz na bieżni z nachyleniem 12 3 30',
    'szybki marsz pod górkę zamiast biegania',
    'ėjimas įkalnėn ant takelio, geras kardio?',
    '12 3 30 bėgimo takelio treniruotė',
    'greitas ėjimas įkalnėn vietoj bėgimo',
    'kaldega kõndimine jooksulindil, hea kardio?',
    '12 3 30 jooksulindi trenn',
    'kiire kõnd ülesmäge jooksmise asemel',
  ],
  k_rowing_machine: [
    'jak prawidłowo wiosłować na ergometrze',
    'technika na wioślarzu',
    'wioślarz jako cardio, jak ustawić',
    'kaip teisingai irkluoti ant ergometro',
    'irklavimo treniruoklio technika',
    'irklavimas kaip kardio, kaip nustatyti',
    'kuidas sõudeergomeetril õigesti sõuda',
    'sõudemasina tehnika',
    'sõudmine kardioks, kuidas seadistada',
  ],
  k_jump_rope: [
    'skakanka na spalanie tłuszczu',
    'czy skakanie na skakance to dobre cardio',
    'ile skakać na skakance dziennie',
    'šokdynė riebalams deginti',
    'ar šokinėjimas per virvutę geras kardio',
    'kiek šokinėti per virvutę per dieną',
    'hüppenöör rasvapõletuseks',
    'kas hüppenööriga hüppamine on hea kardio',
    'kui palju päevas hüppenööriga hüpata',
  ],
  k_thoracic: [
    'sztywny odcinek piersiowy, ćwiczenia',
    'mobilność górnej części pleców',
    'jak rozruszać plecy między łopatkami',
    'sustingusi krūtinės ląstos stuburo dalis, pratimai',
    'viršutinės nugaros dalies judrumas',
    'kaip išjudinti nugarą tarp mentių',
    'jäik rinnaosa selg, harjutused',
    'ülaselja liikuvus',
    'kuidas abaluude vahelist selga liigutada',
  ],
  k_hip_flexors: [
    'spięte zginacze bioder od siedzenia',
    'jak rozciągnąć zginacze biodra',
    'biodra sztywne, biuro cały dzień',
    'įsitempę klubų lenkiamieji nuo sėdėjimo',
    'kaip ištempti klubų lenkiamuosius raumenis',
    'sustingę klubai, visą dieną biure',
    'pinges puusapainutajad istumisest',
    'kuidas puusapainutajaid venitada',
    'jäigad puusad, terve päev kontoris',
  ],
  k_hamstring_flex: [
    'nie dosięgam palców stóp, spięte dwójki',
    'jak rozciągnąć tył uda',
    'sztywne mięśnie kulszowo goleniowe',
    'nepasiekiu kojų pirštų, įsitempusios šlaunys',
    'kaip ištempti šlaunies užpakalinę dalį',
    'standūs dvigalviai šlaunies raumenys',
    'ei ulatu varvasteni, reie tagakülg kange',
    'kuidas reie tagakülge venitada',
    'jäigad tagareie lihased',
  ],
  k_shoulder_warmup: [
    'jak przygotować barki do ciężkiego wyciskania',
    'jak rozgrzać ramiona przed klatą',
    'ćwiczenia na rozgrzanie barków',
    'pečių apšilimas prieš spaudimą',
    'kaip apšildyti pečius prieš krūtinę',
    'pratimai pečiams apšilti',
    'õlgade soojendus enne surumist',
    'kuidas õlgu enne rinnatrenni soojendada',
    'harjutused õlgade soojendamiseks',
  ],
  k_wrist_mobility: [
    'bolą nadgarstki przy wyciskaniu',
    'nadgarstek boli w przysiadzie przednim',
    'jak wzmocnić nadgarstki',
    'skauda riešus spaudžiant',
    'riešas skauda priekiniame pritūpime',
    'kaip sustiprinti riešus',
    'randmed valutavad pingil',
    'ranne valutab eeskükis',
    'kuidas randmeid tugevdada',
  ],
  k_yoga: [
    'joga dla osób ćwiczących na siłowni',
    'czy joga pomaga w regeneracji',
    'joga i ciężary razem',
    'joga sportuojantiems sporto salėje',
    'ar joga padeda atsigauti',
    'joga ir svoriai kartu',
    'jooga jõusaalis käijatele',
    'kas jooga aitab taastuda',
    'jooga ja raskused koos',
  ],
  k_pilates: [
    'pilates a trening siłowy',
    'czy pilates coś daje na siłowni',
    'pilates na mięśnie głębokie',
    'pilatesas ir jėgos treniruotės',
    'ar pilatesas ką nors duoda',
    'pilatesas giliesiems raumenims',
    'pilates ja jõutreening',
    'kas pilates annab midagi juurde',
    'pilates süvalihastele',
  ],
  k_gloves: [
    'rękawiczki na siłownię, potrzebne?',
    'ćwiczyć w rękawiczkach czy bez',
    'odciski na dłoniach, rękawiczki pomogą?',
    'ar reikia sporto pirštinių',
    'sportuoti su pirštinėmis ar be',
    'nuospaudos delnuose, ar padės pirštinės',
    'kas jõusaalis on kindaid vaja',
    'treenida kinnastega või ilma',
    'käte villid, kas kindad aitavad',
  ],
  k_bar_weight: [
    'ile waży sam gryf olimpijski bez obciążenia',
    'waga sztangi bez talerzy',
    'czy gryf to 20 kg',
    'koks tuščio olimpinio grifo svoris',
    'štangos svoris be diskų',
    'ar grifas sveria 20 kg',
    'tühi olümpiakang, mitu kilo',
    'kangi kaal ilma ketasteta',
    'kas kang on 20 kg',
  ],
  k_weight_vest: [
    'kamizelka obciążeniowa, warto?',
    'chodzenie z kamizelką z obciążeniem',
    'podciąganie w kamizelce',
    'svorių liemenė ar verta',
    'vaikščiojimas su svorių liemene',
    'prisitraukimai su liemene',
    'raskusvest kas tasub',
    'kõndimine raskusvestiga',
    'lõuatõmbed vestiga',
  ],
  k_spotting_others: [
    'jak asekurować kogoś na ławce',
    'kolega poprosił o asekurację, co robić',
    'asekuracja w przysiadzie jak',
    'kaip apdrausti kitą spaudžiant gulint',
    'draugas paprašė apdrausti, ką daryti',
    'kaip apdrausti per pritūpimus',
    'kuidas kedagi pingil julgestada',
    'sõber palus julgestada, mida teha',
    'kuidas kükis julgestada',
  ],
  k_busy_gym: [
    'na siłowni tłok, wszystko zajęte',
    'ktoś zajął stojak, co robić',
    'godziny szczytu na siłowni, jak trenować',
    'sporto salėje minia, viskas užimta',
    'kažkas užėmė stovą, ką daryti',
    'piko valandos salėje, kaip treniruotis',
    'jõusaal on rahvast täis, kõik kinni',
    'keegi võttis resti ära, mida teha',
    'tipptund jõusaalis, kuidas treenida',
  ],
  k_gym_bag: [
    'co zabrać na siłownię',
    'co mieć w torbie treningowej',
    'lista rzeczy na trening',
    'ką pasiimti į sporto salę',
    'kas turi būti sporto krepšyje',
    'daiktų sąrašas treniruotei',
    'mida jõusaali kaasa võtta',
    'mis peab trennikotis olema',
    'asjade nimekiri trenniks',
  ],
  k_film_form: [
    'jak nagrać siebie żeby sprawdzić technikę',
    'z jakiego kąta filmować przysiad',
    'nagrywanie ćwiczeń telefonem',
    'kaip nusifilmuoti technikai patikrinti',
    'iš kokio kampo filmuoti pritūpimą',
    'pratimų filmavimas telefonu',
    'kuidas end tehnika kontrolliks filmida',
    'mis nurga alt kükki filmida',
    'harjutuste filmimine telefoniga',
  ],
  k_calisthenics: [
    'kalistenika jak robić postępy',
    'trening z masą ciała, progresja',
    'ćwiczenia bez sprzętu, jak utrudniać',
    'kalistenika kaip progresuoti',
    'treniruotė su savo svoriu, progresija',
    'pratimai be įrangos, kaip sunkinti',
    'kalisteenika kuidas areneda',
    'kehakaaluga trenn, progressioon',
    'harjutused ilma varustuseta, kuidas raskemaks teha',
  ],
  k_menopause: [
    'trening w okresie menopauzy',
    'menopauza a ciężary',
    'jak ćwiczyć po pięćdziesiątce kobieta menopauza',
    'treniruotės menopauzės metu',
    'menopauzė ir svoriai',
    'kaip sportuoti menopauzės laikotarpiu',
    'treening menopausi ajal',
    'menopaus ja raskused',
    'kuidas menopausi ajal treenida',
  ],
  k_postpartum: [
    'kiedy wrócić na siłownię po porodzie',
    'ćwiczenia po cesarce',
    'trening po ciąży od czego zacząć',
    'kada grįžti į salę po gimdymo',
    'pratimai po cezario pjūvio',
    'treniruotės po nėštumo nuo ko pradėti',
    'millal pärast sünnitust jõusaali naasta',
    'harjutused pärast keisrilõiget',
    'trenn pärast rasedust, kust alustada',
  ],
  k_pelvic_floor: [
    'popuszczam przy przysiadach, normalne?',
    'nietrzymanie moczu przy skokach',
    'mięśnie dna miednicy a dźwiganie',
    'prasiveržia šlapimas per pritūpimus, ar normalu',
    'šlapimo nelaikymas šokinėjant',
    'dubens dugno raumenys ir svorių kėlimas',
    'uriin lekib kükkides, kas normaalne',
    'uriinipidamatus hüpates',
    'vaagnapõhjalihased ja raskuste tõstmine',
  ],
  k_osteoporosis: [
    'osteoporoza a trening siłowy',
    'czy przy niskiej gęstości kości można dźwigać',
    'ćwiczenia na kości',
    'osteoporozė ir jėgos treniruotės',
    'ar su mažu kaulų tankiu galima kilnoti',
    'pratimai kaulams stiprinti',
    'osteoporoos ja jõutreening',
    'kas madala luutihedusega võib raskusi tõsta',
    'harjutused luude tugevdamiseks',
  ],
  k_arthritis: [
    'zwyrodnienie stawów a siłownia',
    'czy z artrozą można robić przysiady',
    'reumatoidalne zapalenie stawów i ćwiczenia',
    'sąnarių artritas ir sporto salė',
    'ar su artroze galima daryti pritūpimus',
    'reumatoidinis artritas ir treniruotės',
    'liigeste artroos ja jõusaal',
    'kas artroosiga võib kükitada',
    'reumatoidartriit ja trenn',
  ],
  k_habit: [
    'jak nie rzucić siłowni po miesiącu',
    'jak wyrobić nawyk treningu',
    'zawsze po dwóch tygodniach przestaję chodzić',
    'kaip nemesti sporto salės po mėnesio',
    'kaip įprasti sportuoti',
    'visada po dviejų savaičių nustoju eiti',
    'kuidas jõusaali mitte kuu ajaga maha jätta',
    'kuidas trenniharjumust tekitada',
    'alati kahe nädala pärast lõpetan käimise',
  ],
  k_program_boredom: [
    'znudził mi się plan, zmieniać wszystko?',
    'monotonia na siłowni, co robić',
    'ciągle te same ćwiczenia, nuda',
    'nusibodo programa, keisti viską?',
    'monotonija sporto salėje, ką daryti',
    'vis tie patys pratimai, nuobodu',
    'kava on igavaks läinud, kas kõike muuta',
    'monotoonsus jõusaalis, mida teha',
    'kogu aeg samad harjutused, igav',
  ],
  k_comparison: [
    'porównuję się do innych na siłowni',
    'na instagramie wszyscy lepsi ode mnie',
    'czuję się słaby przy innych',
    'lyginu save su kitais salėje',
    'instagrame visi geresni už mane',
    'jaučiuosi silpnas šalia kitų',
    'võrdlen end teistega jõusaalis',
    'instagramis on kõik minust paremad',
    'tunnen end teiste kõrval nõrgana',
  ],
  k_psych_up: [
    'jak się nakręcić przed ciężką serią',
    'przygotowanie psychiczne do rekordu',
    'stres przed maksem, co robić',
    'kaip nusiteikti prieš sunkią seriją',
    'psichologinis pasiruošimas rekordui',
    'stresas prieš maksimumą, ką daryti',
    'kuidas end raskeks seeriaks üles kütta',
    'vaimne ettevalmistus rekordiks',
    'stress enne maksimumi, mida teha',
  ],
  k_fear_heavy: [
    'mam lęk przed ciężarem, jak go przełamać',
    'strach przed dużym ciężarem na ławce',
    'nie mam odwagi dołożyć talerzy',
    'bijau sunkių svorių',
    'baimė didelio svorio spaudžiant',
    'neišdrįstu uždėti daugiau diskų',
    'kardan raskeid raskusi',
    'hirm suure raskuse ees pingil',
    'ei julge kettaid juurde panna',
  ],
  k_dance: [
    'tańczę, jak połączyć to z siłownią',
    'baletnica na siłowni, czy warto',
    'trening siłowy dla tancerza',
    'šoku, kaip derinti su sporto sale',
    'balerina sporto salėje, ar verta',
    'jėgos treniruotės šokėjui',
    'tantsin, kuidas jõusaaliga ühendada',
    'baleriin jõusaalis, kas tasub',
    'jõutreening tantsijale',
  ],
  k_progress_photos: [
    'jak robić zdjęcia sylwetki',
    'zdjęcia postępów, jak je robić',
    'porównanie sylwetki na zdjęciach',
    'kaip fotografuoti kūno formą',
    'progreso nuotraukos, kaip daryti',
    'kūno palyginimas nuotraukose',
    'kuidas vormipilte teha',
    'arengupildid, kuidas neid teha',
    'keha võrdlemine piltidel',
  ],
  k_measurements: [
    'jakie obwody mierzyć',
    'pomiary ciała centymetrem',
    'co mierzyć oprócz wagi',
    'kokius apimtis matuoti',
    'kūno matavimai centimetru',
    'ką matuoti be svorio',
    'milliseid ümbermõõte mõõta',
    'keha mõõtmine mõõdulindiga',
    'mida peale kaalu mõõta',
  ],
  k_body_fat: [
    'jak zmierzyć poziom tłuszczu',
    'procent tkanki tłuszczowej, jak sprawdzić',
    'waga z pomiarem tłuszczu dokładna?',
    'kaip išmatuoti riebalų kiekį',
    'riebalų procentas, kaip patikrinti',
    'svarstyklės su riebalų matavimu tikslios?',
    'kuidas rasvaprotsenti mõõta',
    'keharasva protsent, kuidas kontrollida',
    'kas rasvamõõtjaga kaal on täpne',
  ],
  k_bmi: [
    'bmi mówi że mam nadwagę, ale ćwiczę',
    'czy bmi ma sens dla ćwiczących',
    'dużo mięśni a bmi',
    'kmi sako, kad turiu antsvorio, bet sportuoju',
    'ar kmi turi prasmę sportuojantiems',
    'daug raumenų ir kmi',
    'kmi ütleb ülekaal, aga ma treenin',
    'kas kmi on treenijale mõttekas',
    'palju lihaseid ja kmi',
  ],
  k_recomp: [
    'czy można jednocześnie chudnąć i budować mięśnie',
    'rekompozycja sylwetki, jak',
    'spalić tłuszcz i zbudować mięśnie naraz',
    'ar galima kartu lieknėti ir auginti raumenis',
    'kūno rekompozicija, kaip',
    'deginti riebalus ir auginti raumenis vienu metu',
    'kas saab korraga kaalu kaotada ja lihaseid kasvatada',
    'keha rekompositsioon, kuidas',
    'rasva põletada ja lihaseid kasvatada korraga',
  ],
  k_mini_cut: [
    'mini redukcja ile tygodni',
    'krótka redukcja w trakcie masy',
    'mini cut jak zrobić',
    'mini lieknėjimas kiek savaičių',
    'trumpas lieknėjimas masės metu',
    'mini cut kaip daryti',
    'minikaalulangetus mitu nädalat',
    'lühike kaalulangetus massiperioodi ajal',
    'mini cut kuidas teha',
  ],
  k_climbing: [
    'jak łączyć ściankę wspinaczkową z siłownią',
    'bulderuję, jaki trening siłowy',
    'trening dla wspinacza',
    'laipiojimas ir sporto salė, kaip derinti',
    'boulderiuoju, kokios jėgos treniruotės',
    'treniruotės laipiotojui',
    'ronimine ja jõusaal, kuidas ühendada',
    'teen boulderingut, milline jõutrenn',
    'trenn ronijale',
  ],
  k_muscle_fibers: [
    'włókna szybkokurczliwe i wolnokurczliwe',
    'typy włókien mięśniowych',
    'czy trenować włókna szybkie',
    'greitosios ir lėtosios raumenų skaidulos',
    'raumenų skaidulų tipai',
    'ar treniruoti greitąsias skaidulas',
    'kiired ja aeglased lihaskiud',
    'lihaskiudude tüübid',
    'kas treenida kiireid lihaskiude',
  ],
  k_rotator_cuff: [
    'jak wzmocnić stożek rotatorów',
    'rotacja zewnętrzna barku, po co',
    'wzmocnić mięśnie rotujące bark',
    'pratimai sukamųjų raumenų manžetei',
    'peties išorinė rotacija, kam',
    'sustiprinti peties sukamuosius raumenis',
    'harjutused rotaatormanseti jaoks',
    'õla välisrotatsioon, milleks',
    'õla pöörajalihaste tugevdamine',
  ],
  k_delt_heads: [
    'jak trenować tylne aktony barków',
    'wszystkie trzy części barku, ćwiczenia',
    'przedni, boczny i tylny akton',
    'kaip treniruoti užpakalines deltas',
    'visos trys deltinio raumens dalys, pratimai',
    'priekinė, šoninė ir užpakalinė delta',
    'kuidas treenida õla tagumist osa',
    'deltalihase kõik kolm osa, harjutused',
    'eesmine, külgmine ja tagumine delta',
  ],
  k_ego_lifting: [
    'ego lifting, co to znaczy',
    'bujanie się na bicepsie, za duży ciężar',
    'za ciężko dla szpanu, czemu to złe',
    'ego lifting, ką tai reiškia',
    'sūpuojuosi darant bicepsą, per sunku',
    'per sunkiai dėl pasipuikavimo, kodėl blogai',
    'ego lifting, mida see tähendab',
    'kõigun biitsepsit tehes, liiga raske',
    'liiga raske edvistamiseks, miks halb',
  ],
  k_skip_legs: [
    'czy muszę robić nogi',
    'nie lubię treningu nóg, mogę pominąć?',
    'tylko góra bez nóg, źle?',
    'ar kojų dieną galima visai praleisti',
    'nemėgstu kojų dienos, ar galiu praleisti',
    'tik viršus be kojų, blogai?',
    'kas pean jalgu treenima',
    'mulle ei meeldi jalapäev, kas võin vahele jätta',
    'ainult ülakeha ilma jalgadeta, halb?',
  ],
  k_nausea: [
    'mdłości na treningu, dlaczego',
    'chce mi się wymiotować po przysiadach',
    'robi mi się niedobrze po interwałach',
    'pykinimas treniruotėje, kodėl',
    'norisi vemti po pritūpimų',
    'darosi bloga po intervalų',
    'iiveldus trennis, miks',
    'kükkide järel ajab oksendama',
    'intervallide järel hakkab halb',
  ],
  k_shaking: [
    'trzęsą mi się mięśnie w serii',
    'drżenie rąk pod ciężarem',
    'nogi się trzęsą przy przysiadach',
    'dreba raumenys serijoje',
    'rankos dreba po svoriu',
    'kojos dreba darant pritūpimus',
    'lihased värisevad seeria ajal',
    'käed värisevad raskuse all',
    'jalad värisevad kükkides',
  ],
  k_joint_clicking: [
    'strzela mi w barku przy wyciskaniu',
    'trzaskają mi kolana, groźne?',
    'chrupanie w stawach przy ćwiczeniach',
    'traška petys spaudžiant',
    'spragsi keliai, ar pavojinga',
    'traškėjimas sąnariuose sportuojant',
    'õlg naksub pingil',
    'põlved raksuvad, kas ohtlik',
    'liigeste ragin trenni ajal',
  ],
  k_stretch_marks: [
    'rozstępy od masy, da się uniknąć?',
    'rozstępy na ramionach od siłowni',
    'jak zapobiec rozstępom przy tyciu',
    'strijos nuo masės, ar galima išvengti',
    'strijos ant pečių nuo sporto',
    'kaip išvengti strijų priaugant svorio',
    'venitusarmid massist, kas saab vältida',
    'venitusarmid õlgadel jõusaalist',
    'kuidas vältida venitusarme kaalus juurde võttes',
  ],
};
