export const KB_R3: Record<string, { ex: string[]; exUk: string[] }> = {
  how_are_you: {
    ex: [
      'hey atlas how are you today',
      'how you doing coach',
      'hows your day going',
      'how r u',
      'whats up with you, all good?',
      'how are you feeling today atlas',
      'you doing alright?',
      "how's life treating you",
      'how have you been lately',
      'hey coach, how are things on your end',
      "how's your day been so far",
      'you ok today?',
      'sup, how you been',
      'how are you holding up',
      'how are you, coach? hope all is well',
    ],
    exUk: [
      'привіт, як ти там',
      'як справи в тебе, тренере',
      'як твій день',
      'шо там у тебе, все норм?',
      'як ся маєш сьогодні',
      'як поживаєш',
      'як ти, все добре?',
      'як настрій у тебе',
      'ну шо, як ти сьогодні',
      'как дела у тебя',
      'как ты, тренер?',
      'как поживаешь',
      'jak się masz',
      'co tam u ciebie',
      'jak leci, trenerze',
    ],
  },
  heaviest: {
    ex: [
      'whats the most kg i ever put on the bar',
      'my all time max weight on any lift',
      'heaviest weight i ever moved',
      "biggest number i've ever logged",
      "max weight i've ever lifted in the app",
      "what's my top weight ever across all exercises",
      "heaviest single i've hit",
      "most kilos i've ever pulled or pushed",
      'whats my record heaviest lift',
      "show me the heaviest weight i've done",
      "what's the biggest load i've handled",
      "heaviest i've ever squatted benched or deadlifted",
      'whats my all time heaviest',
      'my heaviest ever set, what was it',
    ],
    exUk: [
      'яку найбільшу вагу я колись підняв',
      'мій максимальний вага за весь час',
      'скільки кіло максимум я брав',
      'найважча вага в моїй історії',
      'шо саме важке я піднімав',
      'мій рекорд по вазі на штанзі',
      'найбільше кг яке я робив',
      'покажи мій найважчий підхід',
      'який мій абсолютний максимум',
      'какой самый большой вес я поднимал',
      'мой максимальный вес за всё время',
      'самый тяжёлый подход у меня',
      'jaki największy ciężar podniosłem',
      'mój najcięższy ciężar w historii',
      'ile najwięcej kg dźwignąłem',
    ],
  },
  favourite_lift: {
    ex: [
      'which exercise do i log the most',
      'what lift do i do all the time',
      'whats my most frequent exercise',
      'which movement shows up most in my workouts',
      'what exercise have i done the most times',
      'my go to exercise according to my logs',
      'what do i always end up training',
      'which lift is my favourite based on history',
      'most common exercise in my sessions',
      'what exercise do i never skip',
      'whats my top exercise by count',
      'which movement do i repeat most',
      'what lift am i obsessed with lol',
      'my number one exercise by frequency',
      'tell me my fav exercise from my data',
    ],
    exUk: [
      'яку вправу я роблю найчастіше',
      'моя улюблена вправа',
      'шо я найбільше записую в журнал',
      'яка вправа в мене найчастіше',
      'що я завжди треную',
      'моя топ вправа по кількості',
      'яку вправу я повторюю найбільше',
      'яка моя любима вправа',
      'шо в мене чаще всього в тренуваннях',
      'какое моё любимое упражнение',
      'что я делаю чаще всего',
      'какое упражнение у меня самое частое',
      'jakie jest moje ulubione ćwiczenie',
      'które ćwiczenie robię najczęściej',
      'co najczęściej loguję',
    ],
  },
  consistency: {
    ex: [
      'how consistent have i been over the months',
      'am i sticking to my training long term',
      'do i show up regularly or skip a lot',
      'how often do i miss workouts overall',
      'rate my consistency',
      'have i been regular with the gym lately',
      'am i disciplined with my training schedule',
      'how steady is my gym attendance',
      'do i keep a regular routine or am i all over the place',
      'how many weeks did i train consistently',
      'am i skipping too many sessions in general',
      'my attendance record, how is it',
      'am i consistent with going to the gym',
      'how reliable am i with my workouts',
      'have i been falling off lately',
    ],
    exUk: [
      'наскільки я стабільно тренуюсь',
      'чи я регулярно ходжу в зал',
      'як з моєю дисципліною',
      'я часто пропускаю тренування?',
      'оціни мою регулярність',
      'чи тримаю я режим тренувань',
      'наскільки я постійний у залі',
      'я стабільно ходжу чи як попало',
      'шо там з моєю регулярністю',
      'насколько я регулярно тренируюсь',
      'я стабильно хожу в зал?',
      'как у меня с дисциплиной',
      'jak regularnie trenuję',
      'czy jestem systematyczny na siłowni',
      'czy często opuszczam treningi',
    ],
  },
  best_weekday: {
    ex: [
      'which weekday do i hit the gym the most',
      'do i train more on mondays or fridays',
      'what day is my usual gym day',
      'which days of the week am i most active',
      "what's my most common training day",
      'do i mostly lift on weekends or weekdays',
      'on what day do i usually work out',
      'which day of the week do i skip most',
      'what day am i most likely to train',
      'my typical gym days of the week',
      'is tuesday my main training day',
      'which weekday has the most sessions',
      'what days do i tend to lift',
      'when during the week do i train usually',
      'breakdown of my workouts by weekday',
    ],
    exUk: [
      'в який день тижня я найчастіше тренуюсь',
      'в які дні я зазвичай ходжу в зал',
      'мій основний день для тренувань',
      "я більше тренуюсь в понеділок чи п'ятницю",
      'які дні тижня в мене найактивніші',
      'в вихідні чи в будні я частіше в залі',
      'який день я найчастіше пропускаю',
      'по яких днях я зазвичай качаюсь',
      'який мій типовий день тренувань',
      'в какой день недели я чаще тренируюсь',
      'по каким дням я обычно хожу в зал',
      'мой главный день тренировок',
      'w jaki dzień tygodnia najczęściej trenuję',
      'które dni tygodnia są moimi dniami treningowymi',
      'kiedy w tygodniu zwykle chodzę na siłownię',
    ],
  },
  rest_actual: {
    ex: [
      'how long am i really resting between my sets according to my logs',
      "what's my actual rest time on average",
      'do i rest too long between sets, check my data',
      'how many minutes do i rest in reality',
      'my measured rest times last workout',
      'average rest between sets in my sessions',
      'am i resting longer than i think',
      'check my rest periods from last week',
      'what rest did i take on squats yesterday',
      'how much time between sets did i actually take',
      'do i rush my rest, look at my history',
      'show my real rest timer data',
      'how long were my breaks between sets today',
      "what's my typical rest in the logs",
      'am i actually resting 3 minutes or less',
    ],
    exUk: [
      'скільки я реально відпочиваю між підходами',
      'мій середній відпочинок по даних',
      'скільки хвилин я насправді відпочивав минулого разу',
      'я не занадто довго відпочиваю? глянь в логах',
      'який в мене фактичний відпочинок',
      'покажи мій реальний час відпочинку',
      'скільки я відпочивав між сетами сьогодні',
      'я відпочиваю довше ніж думаю?',
      'шо по моєму відпочинку в останньому тренуванні',
      'сколько я реально отдыхаю между подходами',
      'мой средний отдых по логам',
      'сколько я отдыхал на прошлой тренировке',
      'ile faktycznie odpoczywam między seriami',
      'mój średni czas przerwy według danych',
      'jak długo odpoczywałem na ostatnim treningu',
    ],
  },
  cardio_done: {
    ex: [
      'how many cardio minutes have i logged this week',
      'did i do enough cardio this week',
      'total running and cycling this week',
      'how many km did i run this week',
      'how much cardio have i done lately',
      'my conditioning work this week, how much',
      'did i log any runs this week',
      'how many cardio sessions this week',
      'how much time on the bike or treadmill this week',
      'total walking distance this week',
      'my weekly cardio total',
      'how much cardio did i log last 7 days',
      'did i hit my cardio minutes this week',
      'how many activities besides lifting this week',
      'sum up my cardio for the week',
    ],
    exUk: [
      'скільки кардіо я зробив цього тижня',
      'скільки хвилин кардіо за тиждень',
      'скільки км я пробіг цього тижня',
      'моє кардіо за останні 7 днів',
      'чи достатньо кардіо я зробив цього тижня',
      'скільки я ходив пішки за тиждень',
      'скільки було пробіжок цього тижня',
      'скільки часу на велосипеді за тиждень',
      'підсумуй моє кардіо за тиждень',
      'сколько кардио я сделал на этой неделе',
      'сколько я пробежал за неделю',
      'моё кардио за неделю',
      'ile cardio zrobiłem w tym tygodniu',
      'ile minut cardio w tym tygodniu',
      'ile km przebiegłem w tym tygodniu',
    ],
  },
  my_gym: {
    ex: [
      'what gym am i training at',
      'show my saved gyms',
      'which gym location do i use most',
      'where do i usually work out',
      'list my gyms',
      "what's my home gym in the app",
      'which of my gyms do i visit most',
      'how many gyms do i have in my profile',
      'where did i train last time, which gym',
      'what gym is set as my default',
      'my gym locations',
      'which club do i go to most often',
      'do i have more than one gym saved',
      'tell me where i train',
      'whats the name of my gym',
    ],
    exUk: [
      'в який зал я ходжу',
      'мої збережені зали',
      'в якому залі я найчастіше тренуюсь',
      'де я зазвичай тренуюсь',
      'покажи список моїх залів',
      'скільки в мене залів збережено',
      'який мій основний зал',
      'в якій качалці я був останній раз',
      'як називається мій зал',
      'в какой зал я хожу',
      'мои сохранённые залы',
      'где я обычно тренируюсь',
      'na jaką siłownię chodzę',
      'moje zapisane siłownie',
      'gdzie najczęściej trenuję',
    ],
  },
  my_goal: {
    ex: [
      'what goal did i set in the app',
      "remind me what i'm training for",
      "what's my main objective right now",
      'what target weight did i set',
      'is my goal fat loss or muscle gain',
      'what am i aiming for',
      'show my current fitness goal',
      'what goal is on my profile',
      'did i pick strength or physique as my goal',
      "what's my end goal again",
      'whats the goal i chose',
      'remind me of my target',
      "what's my long term goal",
      'what am i working toward according to my profile',
      'my goal, what is it',
    ],
    exUk: [
      'яка в мене ціль',
      'нагадай яку ціль я поставив',
      'до чого я зараз іду',
      'яка моя поточна мета',
      'моя ціль схуднути чи набрати?',
      'яку цільову вагу я поставив',
      'покажи мою ціль у профілі',
      'на що я тренуюсь зараз',
      'шо за ціль в мене стоїть',
      'какая у меня цель',
      'напомни мою цель',
      'какую цель я поставил',
      'jaki jest mój cel',
      'przypomnij mi mój cel',
      'jaki cel ustawiłem',
    ],
  },
  bw_trend: {
    ex: [
      'is my bodyweight going up over time',
      'have i been putting on weight lately',
      'am i dropping weight or staying the same',
      'whats the trend on my weigh-ins',
      'how has my weight changed this month',
      'am i on track to lose weight based on the scale',
      'has my weight gone down since i started',
      'is the scale moving in the right direction',
      'weight change over the past few weeks',
      'am i trending up or down on bodyweight',
      'how many kg have i lost so far',
      'how much weight have i gained since january',
      'is my weight stable or changing',
      'graph of my weight over time',
      'did i gain or lose this month',
    ],
    exUk: [
      'я набираю вагу чи худну',
      'як змінилась моя вага за місяць',
      'вага йде вгору чи вниз',
      'скільки кг я скинув з початку',
      'тренд моєї ваги',
      'я худну чи стою на місці',
      'скільки я набрав за останні тижні',
      'чи падає моя вага',
      'як міняється моя вага по зважуваннях',
      'я набираю вес или худею',
      'как изменился мой вес за месяц',
      'сколько я сбросил с начала',
      'czy tyję czy chudnę',
      'jak zmieniła się moja waga w tym miesiącu',
      'ile kg schudłem od początku',
    ],
  },
  strength_ratio: {
    ex: [
      'is my squat good relative to my bodyweight',
      'how does my bench compare to my body weight',
      'am i strong for someone my size',
      'is a 1.5x bodyweight deadlift good',
      'is benching my bodyweight decent',
      'rate my lifts for my weight',
      'is my strength above average for my weight',
      'how strong am i compared to others my weight',
      'is 140 squat at 80kg bodyweight good',
      "what's a good bench to bodyweight ratio",
      'are my numbers strong or weak for my size',
      'is my overhead press impressive for my weight',
      'am i weak for my bodyweight',
      'strength standards, where do i stand',
      'how good is my deadlift for 75 kg',
    ],
    exUk: [
      'мій жим сильний для моєї ваги?',
      'чи нормальний присід для моєї ваги',
      'я сильний для своєї ваги?',
      'станова в півтори ваги тіла це добре?',
      'жим своєї ваги це нормально?',
      'оціни мої показники відносно ваги',
      'нормальна станова для 80 кг?',
      'який гарний жим відносно ваги тіла',
      'я слабкий для своєї ваги?',
      'мой жим хороший для моего веса?',
      'я сильный для своего веса?',
      'присед 120 при весе 75 это норм?',
      'czy moje wyciskanie jest mocne jak na moją wagę',
      'czy jestem silny jak na swoją wagę',
      'czy martwy ciąg 150 przy 80 kg to dobrze',
    ],
  },
  longest_session: {
    ex: [
      'what was the longest gym session i ever did',
      'my longest workout by duration',
      'what was my shortest session ever',
      'which workout took me the most time',
      "longest time i've spent in the gym in one go",
      'how many minutes was my longest session',
      'show my longest training day',
      "what's my record for workout length",
      'which session lasted the longest',
      'longest workout in my history',
      'my quickest ever workout',
      'how long did my longest lifting session last',
      "what's the most time i spent training in one session",
      'longest and shortest workout i logged',
      "what's the max duration of my workouts",
    ],
    exUk: [
      'яке моє найдовше тренування',
      'скільки тривало моє найдовше тренування',
      'моє найкоротше тренування',
      'який тренування зайняв найбільше часу',
      'найдовше я був у залі за раз',
      'рекорд по тривалості тренування',
      'яка сесія була найдовшою',
      'скільки хвилин моє найдовше тренування',
      'покажи найдовшу тренуню',
      'моя самая длинная тренировка',
      'сколько длилась моя самая долгая тренировка',
      'самая короткая тренировка у меня',
      'mój najdłuższy trening',
      'ile trwał mój najdłuższy trening',
      'najkrótszy trening jaki zrobiłem',
    ],
  },
  arms: {
    ex: [
      'my biceps are stuck, how do i make them grow',
      'how to add size to my arms',
      'tips for bigger biceps and triceps',
      'arms are lagging, what do i do',
      'how to get thicker arms',
      'why are my arms so small even though i train',
      'best exercises for arm growth',
      'how do i build bigger triceps',
      "my guns aren't growing lol help",
      'how many sets for arms to grow',
      'how to grow biceps faster',
      'arms not getting bigger what am i doing wrong',
      'how to fill out my sleeves',
      'arm day tips for size',
      'biceps peak, how do i get it',
    ],
    exUk: [
      'як накачати руки',
      'руки не ростуть, шо робити',
      'як збільшити біцепс',
      'як накачати трицепс',
      'в мене маленькі руки, як їх збільшити',
      'найкращі вправи для рук на масу',
      'чому не ростуть руки',
      'як зробити руки більшими',
      'біцуха стоїть на місці, допоможи',
      'как накачать руки',
      'руки не растут что делать',
      'как увеличить бицепс',
      'jak zbudować większe ramiona',
      'bicepsy nie rosną, co robić',
      'jak powiększyć tricepsy',
    ],
  },
  add_weight: {
    ex: [
      'when is it time to go heavier',
      'how do i know when to up the weight',
      'should i increase the load if i hit all reps',
      'how many kg to add each week on squat',
      'when do i progress to a heavier weight',
      'i hit 3x10, should i add weight now',
      'how fast should i add weight to the bar',
      'is 2.5 kg jump enough for bench',
      'when to bump the weight on deadlift',
      'should i add weight or reps first',
      'how big should my weight jumps be',
      'i got all my reps easy, time to go up?',
      'how much to increase on overhead press',
      'progressive overload, when to add kg',
      'how do i decide to add weight next session',
    ],
    exUk: [
      'коли додавати вагу',
      'скільки кг додавати на жимі',
      'коли час брати більшу вагу',
      'зробив всі повтори, додавати вагу?',
      'на скільки підвищувати вагу в присіді',
      'як часто додавати вагу на штангу',
      '2.5 кг додавати це норм?',
      'що спочатку, вага чи повтори',
      'як зрозуміти що пора додати вагу',
      'когда добавлять вес',
      'сколько кг добавлять на жиме',
      'сделал все повторы, пора добавлять вес?',
      'kiedy dodać ciężar',
      'ile kg dodawać na wyciskaniu',
      'zrobiłem wszystkie powtórzenia, dodać ciężar?',
    ],
  },
  strength_vs_size: {
    ex: [
      'should i focus on getting strong or getting big',
      'train for power or for muscle size',
      'is powerlifting or bodybuilding style better for me',
      'strength block or hypertrophy block',
      'do i want heavy triples or pump work',
      'can i build strength and size at the same time',
      'which goal should i pick, strength or aesthetics',
      'is getting stronger the same as getting bigger',
      'how does training for strength differ from training for size',
      'powerlifter vs bodybuilder training, which should i do',
      'i want to look big, not lift big, how to train',
      'should my focus be max strength or muscle mass',
      'hypertrophy or strength phase first',
      'big or strong, which should i chase',
      'does strength training make you bigger or just stronger',
    ],
    exUk: [
      'тренуватись на силу чи на масу',
      "сила чи об'єм, що вибрати",
      'пауерліфтинг чи бодібілдинг стиль',
      'чим відрізняється тренування на силу від тренування на масу',
      'можна одночасно на силу і масу?',
      'хочу бути великим, а не сильним, як тренуватись',
      'що спочатку, силовий блок чи гіпертрофія',
      'качатись на силу чи на рельєф',
      'сила чи гіпертрофія для мене',
      'тренироваться на силу или на массу',
      'сила или объём, что выбрать',
      'пауэрлифтинг или бодибилдинг',
      'trenować na siłę czy na masę',
      'siła czy hipertrofia, co wybrać',
      'czym różni się trening siłowy od trening na masę',
    ],
  },
  unilateral: {
    ex: [
      'my right arm is stronger than my left, how do i fix it',
      'one side of my chest is bigger',
      'should i add single leg exercises',
      'are bulgarian split squats worth doing',
      'how to even out a strength imbalance',
      'is single arm dumbbell work good for imbalances',
      'one leg does more of the work on squats',
      'do lunges help fix leg imbalance',
      'should i train one side at a time',
      'my left glute is weaker, what do i do',
      'benefits of unilateral training',
      'should i do extra reps on my weak side',
      'uneven biceps, how to fix',
      'one arm dumbbell press vs barbell for imbalance',
      'is single leg work necessary if i squat',
    ],
    exUk: [
      'одна рука сильніша за іншу, шо робити',
      'як виправити дисбаланс між сторонами',
      'ліва нога слабша за праву',
      'чи варто робити вправи на одну ногу',
      'болгарські присідання вони того варті?',
      'одна сторона грудей більша',
      'чи треба робити односторонні вправи',
      'як вирівняти дисбаланс в руках',
      'права рука качається краще за ліву',
      'одна рука сильнее другой, что делать',
      'как исправить дисбаланс сторон',
      'стоит ли делать упражнения на одну ногу',
      'jedna ręka silniejsza od drugiej, co robić',
      'jak wyrównać dysproporcje między stronami',
      'czy warto robić ćwiczenia na jedną nogę',
    ],
  },
  pullup_zero: {
    ex: [
      'i cant even do one pullup',
      'how to go from zero to one pull up',
      "can't lift myself up on the bar at all",
      'best way to get my first chin up',
      'pull ups are impossible for me, how to start',
      'do negatives help me get a pull up',
      'should i use bands to learn pull ups',
      "i just hang there and can't pull up",
      'how long to get a first pullup from nothing',
      "can't do a chin up, what exercises help",
      'lat pulldown to build to a pull up?',
      'never done a pull up, where to begin',
      'how to train for my first ever pull-up',
      'assisted pull up machine to get my first rep',
      '0 pull ups, how do i progress',
    ],
    exUk: [
      'не можу підтягнутись жодного разу',
      'як навчитись підтягуватись з нуля',
      'як зробити перше підтягування',
      'висю на турніку і не можу підтягнутись',
      'негативи допоможуть підтягнутись?',
      'з резинкою вчитись підтягуватись?',
      'нуль підтягувань, з чого почати',
      'шо робити якщо не підтягуюсь взагалі',
      'як прокачатись до першого підтягування',
      'не могу подтянуться ни разу',
      'как научиться подтягиваться с нуля',
      'как сделать первое подтягивание',
      'nie umiem zrobić ani jednego podciągnięcia',
      'jak nauczyć się podciągać od zera',
      'jak zrobić pierwsze podciągnięcie',
    ],
  },
  squat_vs_press: {
    ex: [
      'which is better for legs, squats or the leg press',
      'is leg press enough or do i need to squat',
      'do i really need barbell squats if i leg press',
      'leg press vs back squat for building quads',
      'is the leg press a cheat version of squats',
      'squats or leg press for bigger legs',
      'can leg press build legs as well as squat',
      'is squatting better than leg pressing for mass',
      'leg press safer than squats?',
      'do squats beat leg press for strength',
      'pros and cons of squat vs leg press',
      'leg press instead of squats, will i lose gains',
      'is leg press worse than squatting',
      'which builds more muscle, squat or leg press',
      'squat vs leg press, which one should i prioritize',
    ],
    exUk: [
      'присід чи жим ногами, що краще',
      'чи достатньо жиму ногами замість присіду',
      'жим ногами такий же ефективний як присід?',
      'що краще для квадрицепсів, присід чи платформа',
      'присідати чи жати ногами на масу',
      'платформа чи присід для ніг',
      'чи треба присідати якщо роблю жим ногами',
      'жим ногами безпечніше за присід?',
      'присед чи жим ногами, в чому різниця',
      'присед или жим ногами, что лучше',
      'жим ногами так же эффективен как присед?',
      'что лучше для ног, присед или платформа',
      'przysiad czy suwnica, co lepsze',
      'czy suwnica zastąpi przysiady',
      'przysiad czy wypychanie nogami na masę',
    ],
  },
  sauna_cold: {
    ex: [
      'is it ok to hit the sauna after lifting',
      'does an ice bath kill gains',
      'cold plunge right after training, good or bad',
      'sauna or cold shower after the gym',
      'should i do contrast therapy after workouts',
      'will ice baths hurt muscle growth',
      'how long in the sauna after a workout',
      'is steam room good for recovery',
      'cold water immersion after leg day',
      'does sauna help muscle recovery',
      'hot tub after gym ok?',
      'cryotherapy after lifting worth it',
      'is going to the banya after training fine',
      'sauna straight after weights, safe?',
      'does a cold bath reduce soreness',
    ],
    exUk: [
      'сауна після тренування це добре?',
      "крижана ванна після залу шкодить росту м'язів?",
      'холодний душ після тренування корисний?',
      'баня після залу норм?',
      'скільки сидіти в сауні після тренування',
      'моржування після залу, так чи ні',
      'контрастний душ після тренування',
      'холодна ванна зменшує крепатуру?',
      'парилка після качалки, можна?',
      'сауна после тренировки полезна?',
      'ледяная ванна после зала вредит?',
      'баня после тренировки нормально?',
      'sauna po treningu, dobrze czy źle',
      'czy lodowa kąpiel po siłowni hamuje wzrost mięśni',
      'zimny prysznic po treningu pomaga w regeneracji',
    ],
  },
  nap: {
    ex: [
      'is a midday nap good for gains',
      'how long should i nap before training',
      'does napping help muscle recovery',
      'should i sleep a bit after the gym',
      '20 min nap or 90 min nap',
      'will a nap ruin my night sleep',
      "i'm tired, should i nap before lifting",
      'best time of day for a nap',
      'can naps make up for bad sleep',
      'nap after workout good idea?',
      'power naps worth it for athletes',
      'i slept badly, will a nap help my session',
      'how long a nap to not feel groggy',
      'is napping every day ok',
      'does a short nap boost performance',
    ],
    exUk: [
      'чи варто поспати вдень',
      'денний сон корисний для відновлення?',
      'скільки спати вдень перед тренуванням',
      'поспати після залу це добре?',
      '20 хвилин чи півтори години подрімати',
      "денний сон зіб'є нічний?",
      'не виспався, подрімати перед залом?',
      'короткий сон допомагає відновитись?',
      'покемарити після тренування норм?',
      'стоит ли спать днём',
      'дневной сон полезен для восстановления?',
      'сколько спать днём перед тренировкой',
      'czy drzemka pomaga w regeneracji',
      'ile powinna trwać drzemka',
      'drzemka przed treningiem, dobry pomysł?',
    ],
  },
  stress: {
    ex: [
      'work is stressing me out, should i still lift',
      "i'm mentally exhausted, gym or rest",
      'does working out help with anxiety and stress',
      "stressed and can't focus, train anyway?",
      'i feel overwhelmed, should i skip today',
      'high stress week, how should i train',
      'will lifting help my stress levels',
      "i'm burned out from work, should i go to the gym",
      'stress affecting my recovery?',
      'feeling anxious and tired, should i train',
      'should i lower intensity when stressed',
      'life is stressful rn, how to keep training',
      'can stress kill my gains',
      'exam stress, still hit the gym?',
      'mentally drained, is a workout a good idea',
    ],
    exUk: [
      'в мене стрес, тренуватись чи ні',
      'на роботі жесть, йти в зал?',
      'спорт допомагає від стресу?',
      'я вигорів, чи варто тренуватись',
      'морально виснажений, зал чи відпочинок',
      'стрес впливає на відновлення?',
      'нерви шалять, піти потренуватись?',
      'на стресі краще легше тренуватись?',
      'дуже нервовий тиждень, як тренуватись',
      'у меня стресс, стоит ли тренироваться',
      'выгорел на работе, идти в зал?',
      'спорт помогает от стресса?',
      'jestem zestresowany, trenować czy nie',
      'czy trening pomaga na stres',
      'wypalenie w pracy, iść na siłownię?',
    ],
  },
  age: {
    ex: [
      "i'm 50, is it too late for me to lift",
      'can i build muscle in my 60s',
      'is weightlifting safe for older adults',
      'starting the gym at 55, realistic?',
      'am i too old to get strong',
      'does age limit muscle growth',
      "i'm in my forties, can i still get fit",
      'lifting weights for seniors, is it ok',
      'how should training change after 40',
      'can a 65 year old start strength training',
      'is it worth starting to lift at 48',
      'too old to squat heavy?',
      'muscle building after menopause possible?',
      "i'm 70, should i lift weights",
      'is there an age limit to start lifting',
    ],
    exUk: [
      'мені 50, не пізно починати качатись?',
      "чи можна набрати м'язи після 60",
      'я не застарий для залу?',
      'в 45 є сенс починати тренування?',
      'силові тренування для літніх людей безпечні?',
      "вік заважає росту м'язів?",
      'мені за сорок, можна ще стати сильним?',
      'як тренуватись після 50',
      'не поздно мне в зал в 55?',
      'мне 50, не поздно начинать?',
      'можно ли накачаться после 60',
      'я не слишком старый для зала?',
      'mam 50 lat, czy nie za późno na siłownię',
      'czy po 60 można budować mięśnie',
      'czy jestem za stary na trening siłowy',
    ],
  },
  gym_anxiety: {
    ex: [
      'i feel like everyone is judging me at the gym',
      'too shy to use the free weights section',
      'how do i stop feeling awkward at the gym',
      'i get nervous around big guys lifting',
      'afraid of looking stupid at the gym',
      'i feel self conscious working out in public',
      'intimidated by the gym, how to get over it',
      "i don't know what i'm doing and feel embarrassed",
      'scared to ask for equipment or share machines',
      'how to feel comfortable in a new gym',
      'social anxiety at the gym tips',
      'i avoid the squat rack because people watch',
      'feeling out of place at the gym',
      "i'm too embarrassed to go in",
      'how to be less nervous working out in front of people',
    ],
    exUk: [
      'соромлюсь ходити в зал',
      'мені здається всі на мене дивляться в залі',
      'боюсь виглядати дурнем у залі',
      'як перестати стидатись в качалці',
      'ніяково підходити до штанги при людях',
      'страшно йти в новий зал',
      'відчуваю себе не в своїй тарілці в залі',
      'соромно попросити тренажер',
      'як подолати страх перед залом',
      'стесняюсь ходить в зал',
      'мне кажется все смотрят на меня в зале',
      'боюсь выглядеть глупо в качалке',
      'wstydzę się chodzić na siłownię',
      'czuję że wszyscy na mnie patrzą na siłowni',
      'boję się że wyjdę na głupka na siłowni',
    ],
  },
  app_backfill: {
    ex: [
      'how do i log a workout i did last week',
      "i trained yesterday but didn't record it",
      'can i enter a past session',
      'add a workout with an earlier date',
      'i forgot to track my session on monday',
      'how to change the date of a logged workout to the past',
      'record a workout after the fact',
      "didn't have my phone at the gym, how to add it later",
      "log yesterday's lifts now",
      'can i retroactively add a workout',
      'missed logging, how do i add it',
      'enter old workouts into the app',
      'how to log a session from a few days ago',
      'i did legs saturday but forgot to log it',
      'add a past date workout to history',
    ],
    exUk: [
      'забув записати тренування',
      'як додати тренування за минулий день',
      'тренувався вчора але не записав',
      'як внести старе тренування',
      'можна додати тренування заднім числом?',
      'не було телефону в залі, як додати потім',
      'як змінити дату тренування на минулу',
      'записати вчорашнє тренування',
      'забив записати сесію в понеділок',
      'забыл записать тренировку',
      'как добавить прошлую тренировку',
      'можно внести тренировку задним числом?',
      'zapomniałem zapisać trening',
      'jak dodać trening z wczoraj',
      'jak wpisać trening z przeszłej daty',
    ],
  },
  app_delete: {
    ex: [
      'how do i get rid of a wrong set',
      'i logged a set twice, how to delete it',
      'how to erase a workout from history',
      'delete an exercise i added by accident',
      'remove a duplicate session',
      'how do i trash a whole workout',
      'accidentally logged a set, undo?',
      'can i delete an entry from my log',
      'how to clear a mistaken set',
      'delete my last logged set',
      "remove wrong entry from today's workout",
      "how to wipe a session i didn't do",
      "where's the delete button for sets",
      'i added the wrong exercise, how to remove it',
      'how to delete a workout in the app',
    ],
    exUk: [
      'як видалити підхід',
      'як видалити тренування',
      'записав підхід двічі, як прибрати',
      'як стерти помилковий сет',
      'випадково додав вправу, як видалити',
      'як видалити сесію з історії',
      'де кнопка видалити підхід',
      'як прибрати дубль тренування',
      'скасувати випадковий запис',
      'как удалить подход',
      'как удалить тренировку',
      'случайно записал сет, как убрать',
      'jak usunąć serię',
      'jak usunąć trening z historii',
      'przez pomyłkę dodałem ćwiczenie, jak usunąć',
    ],
  },
  app_playbook: {
    ex: [
      "what's the playbook feature",
      'how do i create a workout template',
      'where do i find my saved routines',
      'how to reuse a workout as a template',
      'can i make my own routine in the app',
      'what does the playbook section do',
      'how to start a workout from a saved routine',
      "save today's session as a template",
      'how to edit a template',
      'where are my workout templates',
      'can i build custom routines',
      'explain the playbook tab',
      'how do i duplicate a routine',
      'where do templates live in the app',
      'how to set up a routine i can repeat',
    ],
    exUk: [
      'що таке плейбук',
      'як створити шаблон тренування',
      'де мої збережені рутини',
      'як зберегти тренування як шаблон',
      'як почати тренування з шаблону',
      'що за розділ playbook',
      'можна зробити свою рутину в додатку?',
      'як редагувати шаблон',
      'де знайти шаблони',
      'что такое плейбук',
      'как создать шаблон тренировки',
      'где мои сохранённые шаблоны',
      'co to jest playbook',
      'jak stworzyć szablon treningu',
      'gdzie są moje zapisane rutyny',
    ],
  },
  app_streak_rules: {
    ex: [
      'what keeps my streak alive',
      'do rest days count for the streak',
      'how is the streak calculated',
      'does cardio count toward my streak',
      'if i miss a day do i lose my streak',
      'what breaks a streak',
      'is the streak daily or weekly',
      'can i freeze my streak when sick',
      'does logging a walk keep the streak going',
      'how many days off before the streak resets',
      'what are the rules for streaks',
      'does a planned rest day reset the streak',
      'do vacations break my streak',
      'what activity counts for streaks',
      'how does streak counting work in the app',
    ],
    exUk: [
      'як працює стрік',
      'що рахується в стрік',
      'день відпочинку ламає стрік?',
      'як рахується серія днів',
      'кардіо зараховується в стрік?',
      'пропустив день, стрік обнулиться?',
      'правила стріка',
      'можна заморозити стрік коли хворію',
      'скільки днів можна пропустити без втрати стріка',
      'как работает стрик',
      'что засчитывается в серию',
      'день отдыха сбросит стрик?',
      'jak działa passa',
      'co liczy się do passy',
      'czy dzień odpoczynku przerywa passę',
    ],
  },
  app_sleep_tracking: {
    ex: [
      'how do i log my sleep in the app',
      'can the app sync sleep from my watch',
      'where do i enter hours slept',
      'does the app track sleep automatically',
      'how to connect sleep data from apple health',
      'set up sleep tracking',
      "how to add last night's sleep",
      "where's the sleep log",
      'can i set a bedtime reminder in the app',
      'how does sleep tracking feature work',
      'import sleep from my fitbit',
      'how to edit my sleep entry',
      'where can i see my sleep history',
      "sleep tracking isn't working, how to fix",
      'how to record a nap in the app',
    ],
    exUk: [
      'як записати сон у додатку',
      'як відстежувати сон',
      'додаток сам рахує сон?',
      'як підключити сон з годинника',
      'де вносити години сну',
      'як налаштувати трекінг сну',
      'як додати сон за минулу ніч',
      'де подивитись історію сну',
      'не працює трекінг сну, шо робити',
      'как записать сон в приложении',
      'как отслеживать сон',
      'приложение само считает сон?',
      'jak zapisać sen w aplikacji',
      'jak śledzić sen',
      'czy aplikacja automatycznie mierzy sen',
    ],
  },
  do_you_lift: {
    ex: [
      'do u lift bro',
      'you ever hit the gym yourself',
      'how much can you bench atlas',
      'do you have muscles',
      'whats your max squat lol',
      'have you ever lifted a weight',
      'atlas do you go to the gym',
      'you even train bro?',
      'do bots lift weights',
      'can you do a pushup',
      "what's your favourite lift, atlas",
      'do you ever skip leg day',
      'are you jacked',
      'how strong are you coach',
    ],
    exUk: [
      'а ти сам качаєшся?',
      'ти ходиш в зал?',
      'скільки ти жмеш, атлас',
      "в тебе є м'язи?",
      'ти колись тренувався?',
      'а ти сам тренуєшся бро',
      'який в тебе присід лол',
      'ти вмієш віджиматись?',
      'ти пропускаєш день ніг?',
      'а ты сам качаешься?',
      'ты ходишь в зал?',
      'сколько ты жмёшь',
      'a ty ćwiczysz?',
      'ile wyciskasz, atlas',
      'chodzisz na siłownię?',
    ],
  },
  compliment: {
    ex: [
      "you're amazing coach",
      "honestly the best trainer i've had",
      'thanks atlas you rock',
      "you're so helpful",
      'great advice as always',
      'i love this coach',
      "you're killing it atlas",
      'best app coach ever',
      "you're really smart",
      'appreciate you a lot',
      "you're awesome at this",
      "nice one, you're great",
      "you're the goat",
      'such a good coach',
      'you always know what to say',
    ],
    exUk: [
      'ти найкращий',
      'ти супер тренер',
      'дякую, ти крутий',
      'обожнюю тебе атлас',
      'ти топ',
      'класний тренер',
      'ти дуже допомагаєш',
      'ти красава',
      'ти просто бомба',
      'ты лучший',
      'ты крутой тренер',
      'обожаю тебя',
      'jesteś najlepszy',
      'świetny trener z ciebie',
      'jesteś super',
    ],
  },
  sorry: {
    ex: [
      'sorry coach',
      'sorry i skipped yesterday',
      'my apologies atlas',
      'sorry for missing my workout',
      'oops my bad',
      "sorry i've been lazy",
      'apologies for ghosting the gym',
      "sorry i didn't follow the plan",
      'so sorry, i messed up',
      'sorry i ate junk',
      'forgive me coach',
      'sorry for being away so long',
      "sorry i didn't log",
      'sorry i was rude',
      "i'm sorry, won't happen again",
    ],
    exUk: [
      'вибач',
      'пробач тренер',
      'вибач що пропустив',
      'сорі',
      'моя вина',
      'вибачаюсь',
      'вибач що не був у залі',
      'пробач, я лінувався',
      'сорян',
      'извини',
      'прости что пропустил',
      'моя вина, извиняюсь',
      'przepraszam',
      'sorki, opuściłem trening',
      'wybacz trenerze',
    ],
  },
  warmup_lift: {
    ex: [
      'give me warm up sets for 100kg squat',
      'how do i warm up for a heavy deadlift day',
      'warm up progression for bench at 80 kg',
      'what weights should i warm up with before squats',
      'ramp up sets for overhead press',
      'build me a squat warm up',
      'warmup plan before my deadlift top set',
      'what should my warm up look like for 140 bench',
      'empty bar then what for bench warm up',
      'warm up before heavy pull ups',
      'specific warm up for barbell rows',
      'how to warm up my shoulders for bench',
      'give me warmup weights for deadlift 180',
      'prep sets before squatting heavy',
      'how should i work up to my bench working sets',
    ],
    exUk: [
      "як розім'ятись перед присідом",
      'розминочні підходи для жиму',
      'дай розминку для станової',
      'з якими вагами розминатись перед присідом на 100',
      'розминка перед жимом стоячи',
      'як розігрітись перед важкою становою',
      'розминочні ваги для жиму 80 кг',
      'як підводити вагу на жимі',
      'розминка плечей перед жимом лежачи',
      'разминка перед приседом',
      'разминочные подходы на жим',
      'как размяться перед становой',
      'rozgrzewka przed przysiadem',
      'serie rozgrzewkowe do wyciskania',
      'jak się rozgrzać przed martwym ciągiem',
    ],
  },
  alternatives: {
    ex: [
      'what can i do if the bench is taken',
      'good substitute for barbell squats',
      'exercise similar to deadlifts but easier on the back',
      'no pull up bar, what instead',
      "i hate lunges, what's a good alternative",
      'what exercise works the same as dips',
      'replacement for leg press at home',
      'alternatives to overhead press for bad shoulders',
      'what else hits chest like bench press',
      'similar movement to romanian deadlift',
      "can't do barbell rows, other options",
      'home alternative to lat pulldown',
      "what's a substitute for hip thrusts",
      'exercise instead of leg extension',
      'machine alternatives to free weight squats',
    ],
    exUk: [
      'чим замінити жим лежачи',
      'альтернатива присіду',
      'що робити замість станової',
      'лава зайнята, чим замінити',
      'замість підтягувань що робити',
      'ненавиджу випади, чим замінити',
      'схожа вправа на віджимання на брусах',
      'що замість жиму ногами вдома',
      'аналог тяги в нахилі',
      'чем заменить жим лёжа',
      'альтернатива приседу',
      'что делать вместо становой',
      'czym zastąpić wyciskanie na ławce',
      'alternatywa dla przysiadów',
      'co zamiast podciągania',
    ],
  },
  sets_for_lift: {
    ex: [
      'how many sets should i do on bench each workout',
      'is 3 sets of squats enough',
      'how many deadlift sets per session',
      'should i do 3 or 5 sets on overhead press',
      'number of working sets for rows',
      'how many sets of curls',
      'is 5 sets of bench too much',
      'how many sets on leg press per workout',
      'how many sets of lunges should i do',
      'sets per exercise for squat day',
      'how many hard sets for pull ups',
      '4 sets or 3 for bench, which is better',
      'how many sets of rdl',
      'how many sets should i do per lift',
      'enough sets on bench for growth?',
    ],
    exUk: [
      'скільки підходів робити на жимі',
      'скільки підходів присіду',
      '3 підходи станової вистачить?',
      'скільки сетів на жим стоячи',
      'скільки робочих підходів на тягу',
      '5 підходів жиму це забагато?',
      'скільки підходів на біцепс',
      'скільки підходів на вправу',
      'скільки підходів підтягувань',
      'сколько подходов на жим',
      'сколько подходов приседа делать',
      '3 подхода становой хватит?',
      'ile serii wyciskania robić',
      'ile serii przysiadów',
      'czy 3 serie martwego ciągu wystarczą',
    ],
  },
  compare_weeks: {
    ex: [
      'did i do better this week than last',
      'compare my volume with last week',
      'am i up or down vs last week',
      'week over week comparison',
      'more sets this week or last week',
      'how does my training this week stack up to last',
      'was last week harder than this one',
      'compare workouts count this week and previous',
      'did my volume increase from last week',
      'this week compared to the week before',
      'difference between this week and last week',
      'more or less training than last week?',
      'weekly comparison please',
      'last week vs this week numbers',
      'am i ahead of last week',
    ],
    exUk: [
      'порівняй цей тиждень з минулим',
      'цей тиждень проти минулого',
      'я тренувався більше ніж минулого тижня?',
      'порівняння по тижнях',
      "об'єм цього тижня vs минулого",
      'як цей тиждень відрізняється від попереднього',
      'більше чи менше тренувань ніж минулого тижня',
      'різниця між цим і минулим тижнем',
      'я краще ніж минулого тижня?',
      'сравни эту неделю с прошлой',
      'эта неделя против прошлой',
      'я тренировался больше чем на прошлой неделе?',
      'porównaj ten tydzień z poprzednim',
      'ten tydzień vs zeszły',
      'czy trenowałem więcej niż w zeszłym tygodniu',
    ],
  },
  short_on_time: {
    ex: [
      "i've got 25 mins what can i do",
      "quick workout, i'm in a rush",
      'only half an hour today, what should i hit',
      "what's the best 15 minute workout",
      'short session today, how to make it count',
      'limited time at the gym, give me something fast',
      'i need a fast workout, 30 min max',
      "how to shorten today's workout",
      'running late, only 20 minutes to train',
      'express workout please',
      "in a hurry, what's the minimum to do",
      'can i do a full body in 30 minutes',
      'time crunch today, what should i prioritize',
      'have just 45 min, how to fit my workout in',
      'super quick session ideas',
    ],
    exUk: [
      'в мене тільки 30 хвилин',
      'мало часу, що зробити',
      'швидке тренування на 20 хвилин',
      'поспішаю, дай коротке тренування',
      'лише півгодини в залі',
      'як скоротити тренування сьогодні',
      'що встигнути за 15 хвилин',
      'запізнююсь, маю 20 хв',
      'обмежений час, що пріоритетно',
      'у меня только 30 минут',
      'мало времени, что сделать',
      'быстрая тренировка на 20 минут',
      'mam tylko 30 minut',
      'szybki trening, mało czasu',
      'co zrobić w 20 minut',
    ],
  },
  two_days_row: {
    ex: [
      'is lifting on consecutive days bad',
      'can i hit the gym monday and tuesday back to back',
      'is it ok to train legs two days in a row',
      'can i train chest again the next day',
      'do i need a day off between sessions',
      'is it fine to work out day after day',
      'can i do upper yesterday and upper today',
      'is training daily too much',
      'can i go to the gym two days straight',
      'do muscles need 48 hours rest',
      'is it bad to lift every single day',
      'can i train the same muscle on consecutive days',
      'back to back gym days, safe?',
      'should i rest a day between workouts',
    ],
    exUk: [
      'можна тренуватись два дні підряд?',
      'чи нормально ходити в зал день у день',
      'можна качати ноги два дні поспіль?',
      'груди на наступний день знову, норм?',
      'чи потрібен день відпочинку між тренуваннями',
      'можна тренуватись кожен день?',
      'два дні підряд в залі, не шкідливо?',
      "м'язам треба 48 годин відпочинку?",
      'тренуватись щодня це забагато?',
      'можно тренироваться два дня подряд?',
      'нормально ходить в зал каждый день?',
      'нужен ли день отдыха между тренировками',
      'czy można trenować dwa dni z rzędu',
      'czy trening dzień po dniu jest ok',
      'czy trzeba dzień przerwy między treningami',
    ],
  },
  two_a_day: {
    ex: [
      'is doing two workouts in one day ok',
      'lift in the morning and again at night?',
      'should i split my session into am and pm',
      'is training twice daily good for gains',
      'cardio am weights pm same day, fine?',
      'doubles, are they worth it for regular people',
      'two gym sessions a day too much?',
      'can i do two short workouts instead of one long',
      'morning lift plus evening run, good idea',
      'twice a day training for fat loss',
      'does training 2x per day help',
      'am and pm sessions, how to recover',
      'two a days, pros and cons',
      'i want to train two times a day, is that smart',
      'can i split legs and upper into two sessions same day',
    ],
    exUk: [
      'можна тренуватись двічі на день?',
      'два тренування в день це норм?',
      'зранку зал а ввечері ще раз?',
      'ранком кардіо ввечері залізо, можна?',
      'дві сесії в день забагато?',
      'розбити тренування на ранок і вечір',
      'двічі на день тренуватись для схуднення',
      'два коротких тренування замість одного довгого?',
      'двухразові тренування варто?',
      'можно тренироваться два раза в день?',
      'две тренировки в день это нормально?',
      'утром зал вечером кардио, можно?',
      'czy można trenować dwa razy dziennie',
      'dwa treningi dziennie to dobry pomysł?',
      'rano siłownia wieczorem bieganie, ok?',
    ],
  },
  pregnancy: {
    ex: [
      'is weight training safe during pregnancy',
      "i'm pregnant, can i keep lifting",
      'what exercises to avoid while pregnant',
      'can i deadlift in my second trimester',
      'how to train after having a baby',
      'when can i go back to the gym postpartum',
      'safe workouts for pregnant women',
      'lifting heavy in the first trimester, ok?',
      'diastasis recti after birth, can i train abs',
      'pelvic floor exercises after pregnancy',
      "should i lower weights now that i'm expecting",
      'exercising while pregnant tips',
      'can i bench press pregnant',
      'returning to squats after c-section',
      'is it ok to do cardio while pregnant',
    ],
    exUk: [
      'чи можна тренуватись під час вагітності',
      'я вагітна, можна качатись?',
      'які вправи не можна вагітним',
      'станова на другому триместрі можна?',
      'коли можна в зал після пологів',
      'тренування після пологів',
      'безпечні вправи для вагітних',
      'діастаз після пологів, можна прес?',
      'після кесаревого коли присідати',
      'можно ли тренироваться беременной',
      'я беременна, можно в зал?',
      'когда можно в зал после родов',
      'czy można ćwiczyć w ciąży',
      'jestem w ciąży, czy mogę dźwigać',
      'kiedy wrócić na siłownię po porodzie',
    ],
  },
};
