/** Phrasings of the newer topics — for the understanding index (the worker), never the answers. */
export const NEW_TOPICS_EX: Record<string, { ex: string[]; exUk: string[] }> = {
  k_bench_arch: {
    ex: [
      'should i arch on bench',
      'is arching my back on bench cheating',
      'how much arch for bench press',
      'bench arch bad for lower back?',
      'do i need that powerlifter arch',
      'flat back or arch when benching',
      'arching on bench press yes or no',
      'my lower back hurts from arching on bench',
      'how to arch properly on the bench',
      'why do powerlifters arch so much',
      'is the bench arch safe',
      'should my back touch the bench when pressing',
      'arch vs flat back bench for chest growth',
      'can i bench with a flat back',
      'how do you set up an arch for bench',
      'does arching make bench easier',
      'is a big arch bad for you',
      'whats the point of arching on bench',
      'bench press back arch how much is too much',
      'ass comes off the bench when i arch is that ok',
    ],
    exUk: [
      'чи треба прогинатися на жимі лежачи',
      'прогин у спині на жимі це читинг?',
      'наскільки сильно прогинатися на жимі',
      'прогин на жимі шкодить попереку?',
      'жати з рівною спиною чи з прогином',
      'як правильно робити міст на жимі',
      'навіщо пауерліфтери так прогинаються',
      'чи безпечний прогин на лавці',
      'поперек болить від прогину на жимі',
      'спина має лежати на лавці чи ні',
      'прогин на жимі для грудей чи тільки для рекорду',
      'мостик на жимі потрібен?',
      'як поставити спину на жимі лежачи',
      'чи можна жати без прогину',
      'великий прогин це погано?',
      'сідниці відриваються від лавки коли прогинаюсь',
      'шо дає прогин на жимі',
      'жим лежачи прогибатись чи ні',
      'як зробити арку на жимі',
      'лопатки і прогин на жимі як',
      'нужно ли прогибаться в жиме лежа',
      'мост в жиме лежа вредно для спины?',
      'как правильно делать прогиб на жиме',
      'жать с ровной спиной или с мостом',
      'czy wyginać plecy przy wyciskaniu na ławce',
      'mostek na ławce to oszustwo?',
      'jak zrobić łuk przy wyciskaniu',
    ],
  },
  k_deadlift_rounding: {
    ex: [
      'my back rounds when i deadlift',
      'how to stop lower back rounding on deadlift',
      'rounded back deadlift fix',
      'is it bad if my back rounds on deadlifts',
      'back looks like a cat on deadlift',
      'why does my spine curve on deadlift',
      'how do i keep a flat back when deadlifting',
      'deadlift form back rounding help',
      'lower back flexes off the floor',
      'upper back rounding deadlift is that ok',
      'cant keep my back straight on deadlift',
      'my back caves on heavy pulls',
      'how to brace so my back doesnt round deadlift',
      'deadlift rounding at the start of the pull',
      'should i lower the weight if my back rounds',
      'keep a neutral spine deadlift tips',
      'back rounds on last reps of deadlift',
      'hunchback deadlift how to fix',
      'why do i round over on conventional deadlift',
      'rounding back on deadlift dangerous?',
    ],
    exUk: [
      'круглиться спина на становій',
      'як не круглити спину на становій тязі',
      'спина колесом на становій що робити',
      'поперек згинається на тязі',
      'чи погано що спина кругла на становій',
      'як тримати рівну спину на становій',
      'на важких повторах спина округлюється',
      'горбачусь на становій',
      'станова кругла спина як виправити',
      'чому спина круглиться на відриві від підлоги',
      'грудний відділ круглиться на тязі це норм?',
      'не можу тримати спину рівно на тязі',
      'як напружитись щоб спина не круглилась',
      'треба зменшити вагу якщо спина кругла?',
      'на останніх повторах спина їде',
      'спина як у кота на становій',
      'станова тяга поперек згинається небезпечно?',
      'шо робить щоб спина не гнулась на становій',
      'як правильно поставити спину на становій',
      'в мене поперек круглий на тязі, це проблема?',
      'круглится спина на становой',
      'как не округлять спину в становой тяге',
      'спина колесом на тяге что делать',
      'поясница гнется на становой',
      'zaokrąglam plecy przy martwym ciągu',
      'jak utrzymać proste plecy w martwym ciągu',
      'plecy mi się garbią na martwym',
    ],
  },
  k_knees_cave: {
    ex: [
      'knees cave in on squat',
      'my knees go inward when squatting',
      'knee valgus squat fix',
      'how to stop knees caving squats',
      'knees buckle in coming out of the hole',
      'is knee cave bad',
      'knees collapse inwards on heavy squats',
      'squat knees going in how to fix',
      'why do my knees point inwards when i squat',
      'knees touching each other on squat lol',
      'knees push in at the bottom of squat',
      'should i push my knees out when squatting',
      'valgus collapse on squats dangerous?',
      'band around knees squat does it help',
      'knees caving on leg press too',
      'my knees cave on the way up',
      'squat knees in weak glutes?',
      'how to keep knees out in squat',
      'knees roll in on squats what am i doing wrong',
      'knees cave in on lunges and squats',
    ],
    exUk: [
      'коліна зводяться при присіданні',
      'коліна йдуть всередину на присіді',
      'як не зводити коліна в присіді',
      'вальгус колін на присіданнях',
      'на підйомі коліна заходять всередину',
      'чи небезпечно коли коліна зводяться',
      'коліна складаються всередину на важкому присіді',
      'чому коліна йдуть всередину',
      'треба виводити коліна назовні при присіді?',
      'резинка на коліна для присіду допомагає?',
      'коліна ламаються всередину в присіді',
      'на випадах теж коліна зводяться',
      'як тримати коліна по лінії носків',
      'слабкі сідниці через це коліна зводяться?',
      'в мене коліна майже торкаються на присіді',
      'шо робить якщо коліна заходять всередину',
      'присід коліна всередину виправити',
      'коліна вальгус як прибрати',
      'на жимі ногами коліна теж зводяться',
      'коліна гуляють всередину на присіді',
      'колени сводятся при приседе',
      'колени уходят внутрь на приседаниях',
      'как не сводить колени в приседе',
      'вальгус коленей что делать',
      'kolana schodzą do środka przy przysiadzie',
      'jak nie schodzić kolanami w przysiadzie',
      'koślawienie kolan w przysiadzie',
    ],
  },
  k_butt_wink: {
    ex: [
      'what is butt wink',
      'butt wink squat bad?',
      'my pelvis tucks under at the bottom of squat',
      'how to fix butt wink',
      'lower back rounds at bottom of squat',
      'is a little butt wink ok',
      'tailbone tucks in deep squat',
      'butt wink dangerous for back',
      'why do i get butt wink',
      'should i squat less deep because of butt wink',
      'butt wink ankle mobility',
      'pelvic tuck at bottom of squat',
      'my hips tuck under when i go ass to grass',
      'butt wink with heavy weight',
      'does everyone have butt wink',
      'how to stop tucking at the bottom of squats',
      'butwink fix',
      'lumbar flexion at squat bottom normal',
      'squat bottom position back rounds a bit',
      'is butt wink why my back hurts after squats',
    ],
    exUk: [
      'що таке підкручування таза в присіді',
      'таз підкручується внизу присіду',
      'поперек круглиться внизу присіду',
      'butt wink це погано?',
      'як прибрати підкручування таза',
      'чи нормально що таз підгортається на присіді',
      'куприк підгортається в глибокому присіді',
      'підкрут таза небезпечно для спини?',
      'присідати менш глибоко через підкручування?',
      'таз заворачивається внизу присіду',
      'в мене поперек округлюється коли сідаю глибоко',
      'підкручування таза з важкою вагою',
      'чому таз підкручується',
      'гомілкостоп і підкручування таза',
      'всі так присідають з підкрутом?',
      'низ присіду спина трохи круглиться нормально?',
      'батвінк як виправити',
      'тазом «підмигую» на присіді',
      'спина болить після присіду через підкрут таза?',
      'на глибокому присіді таз іде під себе',
      'подкручивание таза в приседе',
      'что такое батт винк',
      'таз подворачивается внизу приседа',
      'поясница округляется в нижней точке приседа',
      'podwijanie miednicy w przysiadzie',
      'butt wink czy to niebezpieczne',
      'miednica ucieka pod siebie w przysiadzie',
    ],
  },
  k_ohp_lean: {
    ex: [
      'i lean back too much on ohp',
      'overhead press lower back arch',
      'how to stop leaning back on military press',
      'ohp turns into incline press',
      'lower back hurts on overhead press',
      'how much lean is ok on overhead press',
      'standing press arching my back',
      'military press form lean back fix',
      'should i squeeze glutes on ohp',
      'ohp back bending backwards',
      'how to keep ribs down overhead press',
      'overhead press bar path head',
      'shoulder press standing back hyperextend',
      'leaning back to finish ohp reps',
      'ohp cues for better form',
      'why does my back arch when i press overhead',
      'overhead press lockout head through',
      'strict press form tips',
      'overhead press lean back is it cheating',
      'my lower back takes over on ohp',
    ],
    exUk: [
      'відхиляюся назад на армійському жимі',
      'прогин у попереку на жимі стоячи',
      'як не прогинатись на армійському жимі',
      'армійський жим перетворюється на жим під кутом',
      'болить поперек від жиму стоячи',
      'наскільки можна відхилятись на жимі над головою',
      'сідниці напружувати на армійському?',
      'як тримати ребра на жимі стоячи',
      'траєкторія грифа на армійському жимі',
      'голова заважає грифу на армійському',
      'на останніх повторах відхиляюсь назад',
      'поперек перенапружується на армійському',
      'жим над головою техніка поради',
      'жим штанги стоячи прогин у спині',
      'чому спина вигинається коли жму над головою',
      'армійка як не валитись назад',
      'армійський жим відхилення це читинг?',
      'жим стоя прогинаюсь чи норм',
      'як правильно жати штангу над головою стоячи',
      'голова «у вікно» на армійському це як',
      'прогибаюсь назад на армейском жиме',
      'как не отклоняться на жиме стоя',
      'болит поясница от армейского жима',
      'поясница выгибается при жиме над головой',
      'odchylam się do tyłu przy wyciskaniu żołnierskim',
      'ból lędźwi przy OHP',
      'jak nie wyginać pleców przy wyciskaniu nad głowę',
    ],
  },
  k_sumo_conventional: {
    ex: [
      'sumo or conventional deadlift',
      'is sumo deadlift cheating',
      'which deadlift style is better',
      'should i switch to sumo',
      'sumo vs conventional for beginners',
      'sumo deadlift easier?',
      'conventional or sumo for my body type',
      'which deadlift builds more back',
      'sumo deadlift benefits',
      'am i built for sumo',
      'should i pull sumo or conv',
      'is conventional deadlift more natural',
      'sumo vs regular deadlift which one',
      'sumo deadlift hip pain vs conventional back pain',
      'why do some people deadlift sumo',
      'long arms sumo or conventional',
      'switching from conventional to sumo worth it',
      'sumo stance deadlift for strength',
      'conventional vs sumo which lifts more',
      'what deadlift stance should i use',
    ],
    exUk: [
      'сумо чи класика станова',
      'станова сумо це читинг?',
      'який стиль станової кращий',
      'переходити на сумо чи ні',
      'сумо чи класика для новачка',
      'станова сумо легша?',
      'яка станова мені підходить по статурі',
      'яка тяга краще качає спину',
      'плюси станової сумо',
      'мені тягнути сумо чи класикою',
      'класична станова чи сумо що обрати',
      'чому деякі тягнуть сумо',
      'довгі руки сумо чи класика',
      'станова з широкою постановкою ніг чи вузькою',
      'сумо більше навантажує ноги?',
      'в сумо можна більше підняти?',
      'сумо тягнуть тільки заради рекорду?',
      'яку становую робити для сили',
      'шо краще сумо чи класика',
      'як зрозуміти, моє сумо чи класика',
      'сумо или классика становая',
      'становая сумо это читинг?',
      'какую становую выбрать',
      'переходить ли на сумо',
      'martwy ciąg sumo czy klasyczny',
      'czy sumo to oszukiwanie',
      'który martwy ciąg lepszy',
    ],
  },
  k_row_lower_back: {
    ex: [
      'lower back tired from barbell rows',
      'bent over rows hurt my lower back',
      'barbell row lower back pump',
      'how to row without using lower back',
      'back gives out before lats on rows',
      'best row that doesnt kill my lower back',
      'chest supported row vs barbell row',
      'bent over row form lower back',
      'my back is fried after rows and deadlifts',
      'lower back ache after bent over rows is that normal',
      'should i swap barbell rows',
      'rows make my lower back sore',
      'how to brace on bent over rows',
      'pendlay row easier on back?',
      'row alternative for bad back',
      'dumbbell row instead of barbell row',
      'lower back rounding on rows',
      't bar row lower back pain',
      'how bent over should i be on rows',
      'i cheat rows with my hips',
    ],
    exUk: [
      'поперек втомлюється від тяги в нахилі',
      'тяга штанги в нахилі болить поперек',
      'як тягнути в нахилі без попереку',
      'поперек забивається на тязі штанги',
      'спина здається раніше за широчайші на тязі',
      'яка тяга не вбиває поперек',
      'тяга з упором грудьми чи в нахилі',
      'техніка тяги в нахилі поперек',
      'після тяги і станової поперек гуде',
      'нормально що поперек ниє після тяги в нахилі',
      'замінити тягу штанги в нахилі?',
      'тяга гантелі однією рукою замість штанги',
      'як тримати спину на тязі в нахилі',
      'тяга Пендлі легша для спини?',
      'тяга т-грифа болить поперек',
      'наскільки нахилятись на тязі штанги',
      'смикаю штангу тазом на тязі',
      'поперек круглиться на тязі в нахилі',
      'тяга в нахилі після станової це забагато?',
      'шо робить якщо тяга в нахилі гасить поперек',
      'поясница устает от тяги в наклоне',
      'тяга штанги в наклоне болит поясница',
      'чем заменить тягу в наклоне',
      'поясница забивается на тяге',
      'bolą mnie lędźwie od wiosłowania sztangą',
      'wiosłowanie w opadzie a dolny odcinek pleców',
      'czym zastąpić wiosłowanie sztangą',
    ],
  },
  k_sleeves_wraps: {
    ex: [
      'do i need knee sleeves',
      'are wrist wraps worth it',
      'knee sleeves for squats yes or no',
      'wrist wraps for bench press',
      'should i wear knee sleeves',
      'what do knee sleeves actually do',
      'wrist wraps are they cheating',
      'knee sleeves vs knee wraps',
      'my wrists bend back on bench should i get wraps',
      '7mm or 5mm knee sleeves',
      'do wrist wraps make you weaker',
      'knee sleeves for bad knees',
      'when to use wrist wraps',
      'are sleeves necessary for squatting',
      'do powerlifters need knee sleeves',
      'wrist straps or wrist wraps whats the difference',
      'should i wrap my wrists for ohp',
      'knee sleeves every set or just heavy',
      'rehband worth buying',
      'compression sleeves for knees in the gym',
    ],
    exUk: [
      'чи потрібні наколінники для присіду',
      'кистьові бинти варто купувати?',
      'наколінники на присід так чи ні',
      'бинти на кисті для жиму лежачи',
      'навіщо наколінники в залі',
      'бинти на зап’ястя це читинг?',
      'наколінники чи бинти на коліна',
      'кисть заламується на жимі купити бинти?',
      'наколінники 5 чи 7 мм',
      'від бинтів кисті слабшають?',
      'наколінники якщо болять коліна',
      'коли використовувати кистьові бинти',
      'без наколінників присідати нормально?',
      'фіксатори на зап’ястя для жиму',
      'різниця між лямками і бинтами на кисті',
      'наколінники на кожен підхід чи тільки на важкий',
      'бинти на руки для армійського жиму',
      'компресійні наколінники в зал треба?',
      'шо дають наколінники при присіданні',
      'напульсники на жим лежачи потрібні?',
      'нужны ли наколенники для приседа',
      'кистевые бинты стоит покупать?',
      'бинты на запястья для жима лежа',
      'наколенники или бинты на колени',
      'czy potrzebuję nakolanników do przysiadów',
      'owijki na nadgarstki warto kupić',
      'ściągacze na kolana na siłownię',
    ],
  },
  k_chalk: {
    ex: [
      'should i use chalk',
      'is chalk worth it for deadlift',
      'chalk vs straps',
      'liquid chalk good?',
      'my gym doesnt allow chalk what now',
      'does chalk help grip',
      'chalk for pull ups',
      'is using chalk cheating',
      'what chalk to buy for the gym',
      'chalk ball or loose chalk',
      'hands too sweaty to hold the bar',
      'bar slips out of my hands on deadlift',
      'do i need chalk as a beginner',
      'chalk for squats on the back',
      'is chalk bad for skin',
      'magnesium carbonate lifting',
      'chalk making my hands dry',
      'how much chalk to use',
      'can i use chalk on bench press',
      'chalk or gloves',
    ],
    exUk: [
      'чи варто користуватися магнезією',
      'магнезія для станової допомагає?',
      'магнезія чи лямки',
      'рідка магнезія нормальна?',
      'в залі заборонена магнезія що робити',
      'руки потіють гриф вислизає',
      'магнезія для турніка',
      'магнезія це читинг?',
      'яку магнезію купити для залу',
      'магнезія в кульці чи розсипна',
      'штанга вислизає з рук на становій',
      'чи потрібна магнезія новачку',
      'магнезія на спину для присіду',
      'магнезія шкодить шкірі?',
      'від магнезії сохнуть руки',
      'скільки магнезії наносити',
      'магнезія на жимі лежачи треба?',
      'магнезія чи рукавички',
      'тальк для рук в зал',
      'мел для рук на тягу',
      'стоит ли использовать магнезию',
      'магнезия или лямки',
      'руки потеют гриф скользит',
      'жидкая магнезия норм?',
      'czy używać magnezji na siłowni',
      'magnezja czy paski',
      'magnezja w płynie czy w proszku',
    ],
  },
  k_smith_machine: {
    ex: [
      'is the smith machine bad',
      'smith machine squats worth it',
      'smith machine vs barbell',
      'is smith machine cheating',
      'why do people hate the smith machine',
      'smith bench press good for chest',
      'can i build muscle with smith machine',
      'smith machine squat bad for knees',
      'how much does the smith bar weigh',
      'smith machine for beginners',
      'smith machine incline press ok?',
      'smith vs free squat which is better',
      'is smith machine safe to use alone',
      'does smith machine strength carry over',
      'smith machine split squats',
      'smith machine calf raises',
      'gym bros say smith machine is useless',
      'smith machine vs squat rack',
      'should i use smith machine for bench',
      'smith machine good or bad',
    ],
    exUk: [
      'машина Сміта це погано?',
      'присід у Сміті має сенс?',
      'Сміт чи штанга',
      'Сміт це читинг?',
      'чому всі хейтять машину Сміта',
      'жим у Сміті для грудей норм?',
      'можна набрати м’язи в Сміті',
      'присід у Сміті шкодить колінам?',
      'скільки важить гриф у Сміті',
      'машина Сміта для новачків',
      'жим під кутом у Сміті',
      'Сміт чи вільний присід що краще',
      'в Сміті безпечно тренуватись самому?',
      'сила з Сміта переходить на штангу?',
      'болгарські присідання в Сміті',
      'підйоми на носки в Сміті',
      'кажуть Сміт марний це правда',
      'Сміт чи силова рама',
      'жати в Сміті чи штангою',
      'тренажер Сміта корисний?',
      'машина Смита это плохо?',
      'присед в Смите есть смысл?',
      'Смит или штанга',
      'жим в Смите для груди',
      'czy maszyna Smitha jest zła',
      'przysiad na Smithu ma sens',
      'Smith czy wolna sztanga',
    ],
  },
  k_test_max: {
    ex: [
      'how do i test my 1rm',
      'how to max out safely',
      'whats the best way to find my one rep max',
      'should i test my max',
      '1rm testing warm up',
      'how often should i test my max',
      'max out day tips',
      'going for a pr single how to prepare',
      'test max bench without spotter',
      'how many attempts when testing max',
      'rest between max attempts',
      'should beginners test 1rm',
      'is testing max dangerous',
      'how to pick opening attempt',
      'test my squat max this week',
      'true 1rm vs estimated',
      'mock meet how to',
      'when to test maxes after deload',
      'hit a new max today how do i warm up for it',
      '1 rep max test protocol',
    ],
    exUk: [
      'як перевірити свій максимум',
      'як безпечно зробити одноповторний максимум',
      'як дізнатися свій 1ПМ',
      'чи варто тестувати максимум',
      'розминка перед максимумом',
      'як часто перевіряти максимум',
      'день максимуму поради',
      'йду на рекорд як підготуватись',
      'максимум на жимі без страхувальника',
      'скільки спроб на максимум',
      'скільки відпочивати між спробами на максимум',
      'новачкам треба перевіряти максимум?',
      'перевіряти максимум небезпечно?',
      'яку вагу брати на першу спробу',
      'хочу перевірити присід на раз',
      'реальний максимум чи розрахунковий',
      'коли тестувати максимум після розвантаження',
      'як пожати на раз і не вбитись',
      'протокол перевірки максимуму',
      'проходка на раз як краще',
      'как проверить свой максимум',
      'как безопасно сделать разовый максимум',
      'разминка перед максимумом',
      'проходка на раз как правильно',
      'jak bezpiecznie sprawdzić maksa',
      'test 1RM jak się rozgrzać',
      'ile prób na maksa',
    ],
  },
  k_shift_work: {
    ex: [
      'how to train with night shifts',
      'i work shifts how do i plan workouts',
      'gym schedule for shift workers',
      'training after a night shift',
      'rotating shifts and lifting',
      'should i train before or after my shift',
      'nurse 12 hour shifts how to work out',
      'best time to lift when working nights',
      'shift work killing my gains',
      'workout plan for irregular schedule',
      'i sleep during the day when do i train',
      'can i lift after night shift or sleep first',
      'shift work and muscle building',
      'how do i stay consistent with changing shifts',
      'train on days off only?',
      'working nights and going to the gym',
      'my schedule changes every week how do i train',
      'security job night shifts gym routine',
      'tired from shifts should i still lift',
      'flexible training plan for shifts',
    ],
    exUk: [
      'як тренуватись при нічних змінах',
      'працюю позмінно як планувати тренування',
      'графік залу для змінної роботи',
      'тренування після нічної зміни',
      'змінний графік і зал',
      'тренуватись до зміни чи після',
      'працюю по 12 годин як тренуватись',
      'коли краще в зал якщо працюю вночі',
      'сплю вдень коли тренуватись',
      'після нічної зміни в зал чи спати',
      'ковзаючий графік і тренування',
      'як бути регулярним якщо зміни постійно міняються',
      'тренуватись тільки у вихідні?',
      'працюю ночами і ходжу в зал',
      'графік щотижня різний як тренуватись',
      'змінна робота вбиває прогрес',
      'втомлений після зміни тренуватись чи ні',
      'гнучка програма під змінний графік',
      'працюю сутки через троє як тренуватися',
      'медсестра нічні чергування і спортзал',
      'как тренироваться при сменном графике',
      'работаю ночами когда ходить в зал',
      'тренировка после ночной смены',
      'график сутки через трое и тренировки',
      'jak trenować pracując na zmiany',
      'praca na nocki a siłownia',
      'trening po nocnej zmianie',
    ],
  },
  k_maintenance: {
    ex: [
      'minimum training to maintain muscle',
      'how little can i train and keep gains',
      'maintenance workout plan',
      'busy month how do i not lose muscle',
      'can i keep strength training once a week',
      'minimum effective dose lifting',
      'how many sets to maintain muscle',
      'life is crazy how do i keep my progress',
      'will i lose gains training twice a week',
      'maintenance phase training',
      'exams coming up how to keep muscle',
      'just want to maintain what i have',
      'how often do i need to lift to not lose strength',
      'maintain muscle with 1 workout a week',
      'cutting back training to maintain',
      'new baby minimal gym routine',
      'keep gains with less time',
      'how much volume to maintain',
      'once a week full body enough to maintain',
      'can i drop to two days and keep my progress',
    ],
    exUk: [
      'мінімум тренувань щоб не втратити м’язи',
      'як мало можна тренуватись і не злити результат',
      'підтримувальна програма',
      'завантажений місяць як не втратити м’язи',
      'раз на тиждень вистачить щоб тримати силу?',
      'мінімальна ефективна доза тренувань',
      'скільки підходів щоб підтримувати м’язи',
      'запара в житті як зберегти прогрес',
      'втрачу результат якщо тренуватись двічі на тиждень?',
      'фаза підтримки тренування',
      'сесія як не втратити форму',
      'хочу просто тримати те що є',
      'як часто треба в зал щоб не слабнути',
      'одне тренування на тиждень на все тіло достатньо?',
      'народилась дитина мінімальна програма',
      'зберегти форму маючи мало часу',
      'який обсяг для підтримки',
      'перейти на два дні і не просісти',
      'тренуватись менше але не злитись',
      'шо робить щоб не здуватись коли нема часу',
      'минимум тренировок чтобы не потерять мышцы',
      'раз в неделю хватит чтобы держать форму?',
      'как сохранить результат при нехватке времени',
      'поддерживающая программа тренировок',
      'ile trenować żeby nie stracić mięśni',
      'trening podtrzymujący raz w tygodniu',
      'jak utrzymać formę mając mało czasu',
    ],
  },
  k_holidays: {
    ex: [
      'how to train over christmas',
      'holidays and gym how do i not lose progress',
      'eating a lot over the holidays gains ruined?',
      'new year break training plan',
      'gym closed for holidays what do i do',
      'gained 3kg over christmas is it fat',
      'how to not fall off during the holidays',
      'holiday season workout tips',
      'family dinners every day how do i keep my diet',
      'should i take the holidays off from lifting',
      'easter weekend training',
      'thanksgiving and bulking lol',
      'how to balance holidays and fitness',
      'vacation week and my diet',
      'christmas week deload?',
      'working out during festive season',
      'all this holiday food will i get fat',
      'back from holidays feel bloated',
      'how many workouts over the holidays',
      'holiday maintenance plan',
    ],
    exUk: [
      'як тренуватись у свята',
      'свята і зал як не втратити прогрес',
      'об’ївся на свята, результати пропали?',
      'новорічні канікули план тренувань',
      'зал зачинений на свята що робити',
      'набрав 3 кг за свята це жир?',
      'як не злитися на свята',
      'поради на святковий період',
      'застілля кожен день як тримати харчування',
      'взяти вихідні від залу на свята?',
      'Великдень і тренування',
      'як поєднати свята і спорт',
      'святкова їжа я розтовстію?',
      'після свят відчуваю себе набряклим',
      'скільки тренуватись у свята',
      'тиждень свят як розвантаження?',
      'Різдво і дієта як бути',
      'олів’є і прогрес на масу',
      'свята вбили мій режим',
      'як повернутись у зал після новорічних',
      'как тренироваться в праздники',
      'новогодние праздники и тренировки',
      'набрал вес после праздников это жир?',
      'праздничные застолья и диета',
      'jak trenować w święta',
      'przytyłem w święta czy to tłuszcz',
      'święta a dieta jak nie przesadzić',
    ],
  },
  k_heat: {
    ex: [
      'training in hot weather tips',
      'gym has no ac how do i train',
      'is it safe to lift in the heat',
      'summer heat workouts',
      'why am i weaker when its hot',
      'how much water in hot weather training',
      'heat exhaustion signs gym',
      'running in the heat safe?',
      'should i train when its 35 degrees',
      'best time to work out in summer',
      'sweating like crazy do i need electrolytes',
      'dizzy training in the heat',
      'heatwave should i skip the gym',
      'outdoor workout hot day',
      'hot gym making me feel sick',
      'how to cool down fast after training in heat',
      'summer training performance drops',
      'garage gym is like an oven',
      'can i do cardio in the heat',
      'heat and heavy lifting',
    ],
    exUk: [
      'як тренуватись у спеку',
      'в залі нема кондиціонера як тренуватись',
      'чи безпечно тягати залізо в спеку',
      'літні тренування поради',
      'чому я слабший коли спекотно',
      'скільки пити води в спеку на тренуванні',
      'ознаки теплового удару в залі',
      'бігати в спеку безпечно?',
      'тренуватись при +35 чи ні',
      'коли краще тренуватись влітку',
      'дуже потію чи потрібні електроліти',
      'паморочиться голова на тренуванні в спеку',
      'спека пропустити зал?',
      'тренування на вулиці в жару',
      'в задушливому залі нудить',
      'як швидко охолонути після тренування',
      'влітку результати падають',
      'в гаражі як у печі тренуватись',
      'кардіо в спеку можна?',
      'жарко і важкі ваги',
      'как тренироваться в жару',
      'в зале нет кондиционера',
      'безопасно ли тренироваться в жару',
      'кружится голова в жару на тренировке',
      'jak trenować w upale',
      'trening w upał czy bezpieczny',
      'na siłowni nie ma klimy',
    ],
  },
  k_teen_lifting: {
    ex: [
      'is lifting safe for teens',
      'im 14 can i go to the gym',
      'does lifting stunt growth',
      'can a 15 year old lift weights',
      'my son wants to lift is it safe',
      'weights at 13 bad?',
      'teen workout plan',
      'will lifting make me shorter',
      'how heavy should a teenager lift',
      'is squatting bad for growing kids',
      '16 and want to start bodybuilding',
      'growth plates and weightlifting',
      'should my daughter do strength training',
      'high school lifting safety',
      'is creatine ok for teenagers',
      'what age can you start lifting weights',
      'teen deadlift safe?',
      'im 15 how often should i train',
      'lifting weights at a young age myths',
      'kids strength training good or bad',
    ],
    exUk: [
      'чи безпечно підліткам качатись',
      'мені 14 можна в зал',
      'від штанги перестають рости?',
      '15 років можна тягати залізо',
      'син хоче в зал це безпечно?',
      'ваги в 13 років шкідливо?',
      'програма тренувань для підлітка',
      'від тренувань я буду нижчим?',
      'яку вагу можна підлітку',
      'присідати зі штангою дітям шкідливо?',
      'мені 16 хочу займатись бодібілдингом',
      'зони росту і штанга',
      'доньці варто силові тренування?',
      'з якого віку можна в тренажерний зал',
      'креатин підліткам можна?',
      'станова для підлітка безпечна?',
      'мені 15 як часто тренуватись',
      'міфи про ваги в юному віці',
      'силові для дітей добре чи погано',
      'школяр і тренажерка з чого почати',
      'можно ли подросткам качаться',
      'с какого возраста можно в зал',
      'штанга останавливает рост?',
      'мне 15 можно тягать железо',
      'czy nastolatek może chodzić na siłownię',
      'od ilu lat można ćwiczyć z ciężarami',
      'czy siłownia hamuje wzrost',
    ],
  },
  k_older_lifter: {
    ex: [
      'how should training change as i get older',
      'lifting after 50 tips',
      'im 60 how should i train differently',
      'strength training for seniors',
      'recovery is slower now im 45',
      'should older lifters go heavy',
      'masters lifter program advice',
      'how to lift in your 40s',
      'joints ache more now im older',
      'best exercises for over 55',
      'lifting in my 50s longer warm up?',
      'age and recovery between workouts',
      'can you still build muscle at 65',
      'should i stop maxing out at my age',
      'older lifter rep ranges',
      'sarcopenia prevention training',
      'training frequency for over 50',
      'my dad is 70 what should he do in the gym',
      'adjusting program for age',
      'lifting for longevity',
    ],
    exUk: [
      'як змінювати тренування з віком',
      'тренування після 50 поради',
      'мені 60 як тренуватись інакше',
      'силові для людей похилого віку',
      'в 45 відновлення повільніше',
      'чи варто старшим тягати важке',
      'мені за 40 як тренуватись',
      'суглоби більше болять з віком',
      'найкращі вправи після 55',
      'в 50 довша розминка?',
      'вік і відновлення між тренуваннями',
      'в 65 можна набрати м’язи?',
      'в моєму віці вже не йти на максимуми?',
      'скільки повторів робити після 50',
      'тренування проти втрати м’язів з віком',
      'як часто тренуватись після 50',
      'татові 70 що йому робити в залі',
      'підлаштувати програму під вік',
      'тренування для довголіття',
      'в 55 качатися ще не пізно, але як правильно',
      'как тренироваться после 50',
      'восстановление после 45 медленнее',
      'силовые для пожилых',
      'как менять тренировки с возрастом',
      'trening siłowy po 50',
      'jak trenować z wiekiem',
      'regeneracja po 45 wolniejsza',
    ],
  },
  k_women_training: {
    ex: [
      'should women train differently',
      'workout plan for women vs men',
      'do girls need a different program',
      'can women lift heavy',
      'female strength training tips',
      'womens training volume',
      'is there a special program for women',
      'should i train like my boyfriend',
      'women and upper body strength',
      'girls should only do light weights?',
      'do women need more reps',
      'female lifter beginner program',
      'differences between male and female training',
      'can women use the same program as men',
      'will lifting heavy make women bulky',
      'women recover faster between sets?',
      'strength training for women benefits',
      'should women do pull ups and bench',
      'women only train glutes and legs?',
      'lifting advice for women',
    ],
    exUk: [
      'чи мають жінки тренуватись інакше',
      'програма для жінок і чоловіків відрізняється?',
      'дівчатам потрібна інша програма?',
      'жінкам можна важкі ваги?',
      'поради з силових для жінок',
      'обсяг тренувань для жінок',
      'чи є спеціальна програма для дівчат',
      'тренуватись як мій хлопець це ок?',
      'жінки і сила верху тіла',
      'дівчатам тільки легкі гантельки?',
      'жінкам треба більше повторів?',
      'програма для дівчини новачка',
      'різниця між чоловічими і жіночими тренуваннями',
      'чи можна жінці програму як у чоловіків',
      'жінки швидше відновлюються між підходами?',
      'користь силових для жінок',
      'дівчатам робити жим лежачи і підтягування?',
      'жінки тренують тільки сідниці і ноги?',
      'поради для жінок у залі',
      'я дівчина чи мені качати все тіло',
      'должны ли женщины тренироваться иначе',
      'программа для девушек отличается?',
      'девушкам можно тяжелые веса?',
      'женская программа тренировок',
      'czy kobiety powinny trenować inaczej',
      'trening siłowy dla kobiet',
      'czy dziewczyny mogą dźwigać ciężko',
    ],
  },
  k_pushup_progression: {
    ex: [
      'i cant do a single push up',
      'how to get my first push up',
      'push up progression for beginners',
      'knee push ups or incline',
      'how to build up to push ups',
      'cant do pushups from the floor',
      'my hips sag when i do push ups',
      'how long to do a full push up',
      'push ups too hard what to do instead',
      'wall push ups to real push ups',
      'how to get stronger at push ups',
      '0 push ups where to start',
      'negative push ups good?',
      'push ups arms shake cant go down',
      'how many push ups should a beginner do',
      'i can only do 2 push ups',
      'push up plan to do 10',
      'how to do more push ups',
      'incline push up progression',
      'girl push ups vs real ones',
    ],
    exUk: [
      'не можу віджатись жодного разу',
      'як зробити перше віджимання',
      'прогресія віджимань для новачка',
      'віджимання з колін чи від лавки',
      'як навчитися віджиматися',
      'не можу віджиматись від підлоги',
      'таз провисає коли віджимаюсь',
      'за скільки можна навчитися віджиматися',
      'віджимання дуже важкі що робити замість',
      'від стіни до підлоги віджимання',
      'як стати сильнішим у віджиманнях',
      'нуль віджимань з чого почати',
      'негативні віджимання допомагають?',
      'руки трусяться на віджиманнях',
      'скільки віджимань робити новачку',
      'можу віджатись лише 2 рази',
      'план щоб віджатись 10 разів',
      'як віджиматись більше',
      'віджимання від опори прогресія',
      'віджимання «жіночі» чи звичайні',
      'не могу отжаться ни разу',
      'как научиться отжиматься',
      'отжимания с колен или от скамьи',
      'могу отжаться только 2 раза',
      'nie umiem zrobić pompki',
      'jak nauczyć się robić pompki',
      'pompki na kolanach czy od ławki',
    ],
  },
  k_etiquette: {
    ex: [
      'gym etiquette rules',
      'what are the unwritten gym rules',
      'how to ask someone how many sets they have left',
      'can i work in with someone',
      'is it rude to curl in the squat rack',
      'do i have to wipe down equipment',
      'someone is hogging the bench what do i do',
      'how to share a machine at the gym',
      'should i re rack my weights',
      'is it ok to drop deadlifts',
      'gym manners for beginners',
      'someone on their phone on the machine for 10 min',
      'how to politely ask for equipment',
      'can i take the dumbbells to my bench',
      'is it weird to film in the gym',
      'should i correct someones form',
      'how long can i stay on one machine',
      'things not to do at the gym',
      'gym rules everyone should know',
      'is it rude to rest on a machine',
    ],
    exUk: [
      'правила поведінки в залі',
      'неписані правила спортзалу',
      'як спитати скільки підходів ще лишилось',
      'можна чергуватися з кимось на тренажері?',
      'біцепс у силовій рамі це неввічливо?',
      'треба протирати тренажери?',
      'хтось зайняв лавку надовго що робити',
      'як ділити тренажер',
      'треба розбирати штангу за собою?',
      'можна кидати штангу на становій?',
      'етикет у залі для новачків',
      'сидить у телефоні на тренажері 10 хвилин',
      'як ввічливо попросити тренажер',
      'можна брати гантелі до своєї лавки?',
      'знімати себе в залі це дивно?',
      'поправляти чужу техніку можна?',
      'скільки можна сидіти на одному тренажері',
      'чого не робити в залі',
      'правила залу які всі мають знати',
      'відпочивати на тренажері це погано?',
      'правила поведения в тренажерном зале',
      'как вежливо попросить тренажер',
      'неписаные правила качалки',
      'можно ли бросать штангу',
      'zasady zachowania na siłowni',
      'jak zapytać ile serii zostało',
      'czy można się wymieniać na maszynie',
    ],
  },
  k_beta_alanine: {
    ex: [
      'is beta alanine worth it',
      'does beta alanine work',
      'beta alanine tingles is that normal',
      'should i take beta alanine for lifting',
      'beta alanine dose',
      'beta alanine for crossfit',
      'why does my preworkout make my face itch',
      'beta alanine vs creatine',
      'when to take beta alanine',
      'beta alanine loading phase',
      'beta alanine for endurance',
      'pins and needles from supplement',
      'is beta alanine safe',
      'beta alanine for high reps',
      'does beta alanine help strength',
      'beta alanine every day?',
      'beta alanine side effects',
      'beta alanine for hypertrophy',
      'do i need beta alanine',
      'carnosine supplement lifting',
    ],
    exUk: [
      'чи варто пити бета-аланін',
      'бета-аланін працює?',
      'від бета-аланіну поколює це нормально?',
      'бета-аланін для залу треба?',
      'дозування бета-аланіну',
      'бета-аланін для кросфіту',
      'чому від передтрену свербить обличчя',
      'бета-аланін чи креатин',
      'коли приймати бета-аланін',
      'бета-аланін для витривалості',
      'мурашки по шкірі від добавки',
      'бета-аланін безпечний?',
      'бета-аланін для багатоповторки',
      'бета-аланін додає сили?',
      'бета-аланін щодня?',
      'побічки бета-аланіну',
      'бета-аланін для маси',
      'мені потрібен бета-аланін?',
      'карнозин добавка для спорту',
      'бета аланін є сенс чи гроші на вітер',
      'стоит ли принимать бета-аланин',
      'бета-аланин покалывание нормально?',
      'бета-аланин или креатин',
      'как принимать бета-аланин',
      'czy beta-alanina działa',
      'mrowienie po beta-alaninie',
      'beta-alanina czy kreatyna',
    ],
  },
  k_fish_oil: {
    ex: [
      'should i take fish oil',
      'is omega 3 good for lifters',
      'fish oil for muscle growth',
      'omega 3 supplement worth it',
      'does fish oil help recovery',
      'fish oil for joints gym',
      'how much omega 3 per day',
      'epa dha dose',
      'fish oil vs eating fish',
      'vegan omega 3 source',
      'fish oil reduces soreness?',
      'do bodybuilders take fish oil',
      'best time to take fish oil',
      'omega 3 burps',
      'is fish oil a waste of money',
      'fish oil and testosterone',
      'krill oil vs fish oil',
      'should lifters take omega 3s',
      'fish oil benefits for training',
      'omega 3 capsules any use',
    ],
    exUk: [
      'чи пити риб’ячий жир',
      'омега-3 для спортсменів корисна?',
      'риб’ячий жир для росту м’язів',
      'омега 3 варто купувати?',
      'риб’ячий жир для відновлення',
      'омега для суглобів у залі',
      'скільки омега 3 на день',
      'дозування EPA DHA',
      'риб’ячий жир чи просто їсти рибу',
      'веганська омега 3',
      'омега зменшує крепатуру?',
      'коли краще пити омегу',
      'від омеги відрижка рибою',
      'риб’ячий жир це викинуті гроші?',
      'омега-3 і тестостерон',
      'масло криля чи риб’ячий жир',
      'користь омеги для тренувань',
      'капсули омега-3 є сенс?',
      'шо дає омега для качка',
      'омега 3 треба якщо їм рибу раз на тиждень',
      'стоит ли пить рыбий жир',
      'омега-3 для спортсменов',
      'сколько омеги в день',
      'рыбий жир для суставов',
      'czy brać tran albo omega-3',
      'omega 3 dla sportowców',
      'ile omega-3 dziennie',
    ],
  },
  k_preworkout: {
    ex: [
      'is pre workout worth it',
      'do i need preworkout',
      'best pre workout ingredients',
      'pre workout vs coffee',
      'is preworkout bad for you',
      'preworkout makes my heart race',
      "what's actually in pre workout",
      'citrulline malate worth it',
      'pre workout every day ok?',
      'pre workout tolerance',
      'pre workout for evening training',
      'pump supplements do they work',
      'is c4 good',
      'stim free pre workout any good',
      'preworkout gives me jitters',
      'how long before gym take preworkout',
      'can beginners take pre workout',
      'preworkout crash after',
      'is pre workout a scam',
      'pre workout and sleep problems',
    ],
    exUk: [
      'чи варто брати передтрен',
      'передтренувальний комплекс потрібен?',
      'що має бути в передтрені',
      'передтрен чи кава',
      'передтрен шкідливий?',
      'від передтрену серце калатає',
      'що насправді в передтренику',
      'цитрулін малат варто?',
      'передтрен щодня нормально?',
      'звикання до передтрену',
      'передтрен на вечірнє тренування',
      'добавки для пампу працюють?',
      'передтрен без стимуляторів має сенс?',
      'від передтрену трусить',
      'за скільки до залу пити передтрен',
      'новачку можна передтрен?',
      'після передтрену відходняк',
      'передтрен це розвод?',
      'передтрен і погано сплю',
      'шо краще передтренік чи енергетик',
      'стоит ли брать предтрен',
      'предтрен или кофе',
      'от предтрена колотится сердце',
      'что внутри предтренировочного комплекса',
      'czy przedtreningówka ma sens',
      'przedtreningówka czy kawa',
      'po przedtreningówce serce wali',
    ],
  },
  k_bcaa: {
    ex: [
      'are bcaas worth it',
      'do i need bcaa',
      'bcaa vs whey',
      'bcaa during workout',
      'bcaa for muscle growth',
      'are bcaas a waste of money',
      'bcaa for recovery',
      'should i drink bcaa while cutting',
      'eaa vs bcaa',
      'bcaa fasted training',
      'do bodybuilders need amino acids',
      'bcaa before or after gym',
      'bcaa prevent muscle loss?',
      'amino acid drink during training',
      'is bcaa pointless',
      'bcaa or protein shake',
      'i drink bcaas all day is that good',
      'bcaa for beginners',
      'do bcaas reduce soreness',
      'aminos worth buying',
    ],
    exUk: [
      'чи варто пити BCAA',
      'бцаа потрібні?',
      'BCAA чи протеїн',
      'BCAA під час тренування',
      'BCAA для росту м’язів',
      'бцаа це викинуті гроші?',
      'амінокислоти для відновлення',
      'пити BCAA на сушці?',
      'EAA чи BCAA',
      'бцаа натщесерце на тренуванні',
      'амінки треба качкам?',
      'BCAA до чи після залу',
      'BCAA захищають м’язи?',
      'напій з амінокислотами на тренуванні',
      'BCAA марні?',
      'BCAA чи протеїновий коктейль',
      'п’ю бцаа весь день це добре?',
      'амінокислоти для новачка',
      'BCAA зменшують крепатуру?',
      'аміно варто купувати',
      'стоит ли пить BCAA',
      'бцаа или протеин',
      'аминокислоты во время тренировки нужны?',
      'BCAA на сушке',
      'czy BCAA mają sens',
      'BCAA czy białko',
      'aminokwasy podczas treningu',
    ],
  },
  k_core_stability: {
    ex: [
      'best core exercises',
      'core training for lifting',
      'exercises for core strength not crunches',
      'is plank enough for core',
      'how to train core for squats',
      'dead bug exercise worth it',
      'pallof press what is it',
      'core stability workout',
      'ab wheel good for core?',
      'how to strengthen my core for deadlifts',
      'core exercises for lower back health',
      'farmers carry for core',
      'how often train core',
      'side plank benefits',
      'core routine for beginners',
      'anti rotation exercises',
      'my core is weak what do i do',
      'hanging leg raises vs crunches',
      'is core training necessary if i squat',
      'functional core training',
    ],
    exUk: [
      'найкращі вправи на кор',
      'кор для силових тренувань',
      'вправи на м’язи кору крім скручувань',
      'планки достатньо для кору?',
      'як тренувати кор для присіду',
      'мертвий жук вправа корисна?',
      'жим Паллофа що це',
      'тренування на стабілізацію корпусу',
      'ролик для преса корисний?',
      'як зміцнити кор для станової',
      'вправи на кор для здорової спини',
      'прогулянка фермера для кору',
      'як часто тренувати кор',
      'бічна планка користь',
      'програма на кор для новачка',
      'вправи проти скручування',
      'в мене слабкий кор що робити',
      'підйоми ніг у висі чи скручування',
      'чи треба кор якщо присідаю',
      'м’язи кору як качати',
      'лучшие упражнения на кор',
      'как укрепить кор',
      'планки достаточно для кора?',
      'упражнения на стабилизацию корпуса',
      'najlepsze ćwiczenia na core',
      'jak wzmocnić mięśnie głębokie',
      'deska wystarczy na brzuch?',
    ],
  },
  k_ankle_mobility: {
    ex: [
      'my heels come up when i squat',
      'how to improve ankle mobility for squats',
      'heels lifting off the ground squat',
      'tight ankles squat fix',
      'should i squat with plates under my heels',
      'ankle dorsiflexion exercises',
      'weight shifts to my toes in squat',
      'squat shoes for ankle mobility',
      'knee to wall ankle test',
      'stiff calves squat depth',
      'cant squat deep because of ankles',
      'heel raise squat cheating?',
      'i fall backwards if i keep heels down',
      'how to stretch ankles for squatting',
      'goblet squat heels come up',
      'improve squat depth ankles',
      'ankle mobility routine',
      'heels come up on lunges too',
      'why do my heels lift squatting',
      'wedge board squats',
    ],
    exUk: [
      'п’яти відриваються при присіданні',
      'як покращити рухливість гомілкостопу для присіду',
      'п’ятки піднімаються в присіді',
      'скутий гомілкостоп присід',
      'присідати з млинцями під п’ятами?',
      'вправи на тильне згинання стопи',
      'вага переходить на носки в присіді',
      'штангетки для гомілкостопу',
      'тест коліно до стіни',
      'забиті литки заважають присідати',
      'не можу глибоко присісти через гомілкостоп',
      'підкладка під п’яти це читинг?',
      'якщо п’яти на підлозі падаю назад',
      'як розтягнути гомілкостоп для присіду',
      'гоблет присід п’яти відриваються',
      'глибина присіду і гомілкостоп',
      'комплекс на рухливість стопи',
      'на випадах теж п’ята відривається',
      'чому піднімаються п’яти на присіді',
      'клин під п’яти для присіду',
      'пятки отрываются при приседе',
      'как улучшить подвижность голеностопа',
      'приседать с блинами под пятками',
      'голеностоп не дает приседать',
      'pięty odrywają się w przysiadzie',
      'mobilność kostki do przysiadu',
      'przysiad z podkładkami pod pięty',
    ],
  },
  k_gassed: {
    ex: [
      'i get out of breath during sets',
      'gassed after high rep squats',
      'how to improve conditioning for lifting',
      'work capacity training',
      'why am i so winded after one set',
      'how to build stamina in the gym',
      'out of breath on 20 rep squats',
      'breathing hard between sets',
      'conditioning for mma',
      'cardio for football fitness',
      'how to not get tired so fast in workouts',
      'get puffed out easily',
      'circuit training makes me gasp',
      'improve endurance for boxing',
      'gpp training what is it',
      "i'm strong but no stamina",
      'how long to build conditioning',
      'sled push for conditioning',
      'heart pounding after lunges',
      'fitness for rugby preseason',
    ],
    exUk: [
      'задихаюсь під час підходів',
      'після багатоповторного присіду не можу віддихатись',
      'як покращити витривалість для залу',
      'робота на витривалість у залі',
      'чому так задихаюсь після одного підходу',
      'як підняти витривалість',
      'задишка на присіді на 20 повторів',
      'важко дихаю між підходами',
      'функціоналка для єдиноборств',
      'витривалість для футболу',
      'як не втомлюватись так швидко на тренуванні',
      'швидко видихаюсь',
      'кругове тренування і задихаюсь',
      'витривалість для боксу',
      'що таке ЗФП',
      'сильний але нема дихалки',
      'за скільки можна прокачати дихалку',
      'штовхання саней для витривалості',
      'серце вистрибує після випадів',
      'дихалка ні к чорту що робити',
      'задыхаюсь во время подходов',
      'как прокачать выносливость',
      'нет дыхалки в зале',
      'функционалка для единоборств',
      'brakuje mi tchu podczas serii',
      'jak poprawić kondycję na siłowni',
      'szybko się męczę na treningu',
    ],
  },
  k_sticking_point: {
    ex: [
      'how to fix a sticking point',
      'bench stalls halfway up',
      'i fail at lockout on bench',
      'squat sticking point fix',
      'stuck out of the hole on squat',
      'deadlift fails at the knees',
      'cant break the bar off the chest',
      'deadlift slow off the floor',
      'weak lockout triceps?',
      'pin press for sticking point',
      'paused bench for weak bottom',
      'why do i always fail at the same spot',
      'overhead press stuck at forehead',
      'sticking point exercises',
      'squat grinding halfway up',
      'weak off the chest bench',
      'deadlift hitching at lockout',
      'how to strengthen the bottom of my squat',
      'accessories for bench lockout',
      'my bar stops in the middle of bench',
    ],
    exUk: [
      'як подолати точку застою',
      'жим зупиняється на середині',
      'не можу дотиснути жим лежачи',
      'точка застою в присіді',
      'застрягаю внизу присіду',
      'станова зупиняється біля колін',
      'не можу зірвати штангу з грудей',
      'повільний відрив на становій',
      'слабкий дотиск трицепс?',
      'жим від упорів для мертвої точки',
      'жим з паузою для низу',
      'чому завжди зриваюсь в одній точці',
      'армійський жим застрягає на рівні лоба',
      'вправи для мертвої точки',
      'присід тягнеться на середині',
      'слабкий низ у жимі',
      'станова не дотягую вгорі',
      'як посилити низ присіду',
      'допоміжні вправи для дотиску',
      'мертва точка в жимі лежачи',
      'как пройти мертвую точку',
      'не могу дожать жим лежа',
      'застреваю внизу приседа',
      'срыв с груди в жиме',
      'martwy punkt w wyciskaniu',
      'nie mogę dopchnąć sztangi',
      'jak pokonać martwy punkt w przysiadzie',
    ],
  },
  k_more_pullups: {
    ex: [
      'how to do more pull ups',
      'increase pull up reps',
      'stuck at 5 pull ups',
      'pull up program',
      'grease the groove pull ups',
      'how to get 10 pull ups',
      'weighted pull ups to get more reps',
      'how often should i do pull ups',
      'pull up plateau',
      '20 pull ups goal how',
      'can do 3 pull ups want more',
      'best way to improve pullups',
      'do lat pulldowns help pull ups',
      'chin ups vs pull ups for reps',
      'pull up negatives to get more reps',
      'pull up training every day?',
      'military pull up test prep',
      'how long to go from 5 to 15 pull ups',
      'pull ups getting harder as i gain weight',
      'pull up volume routine',
    ],
    exUk: [
      'як підтягуватись більше разів',
      'збільшити кількість підтягувань',
      'застряг на 5 підтягуваннях',
      'програма на підтягування',
      'метод змащування шаблону підтягування',
      'як підтягнутись 10 разів',
      'підтягування з вагою для кількості',
      'як часто підтягуватись',
      'плато в підтягуваннях',
      'хочу 20 підтягувань як',
      'підтягуюсь 3 рази хочу більше',
      'тяга верхнього блоку допомагає підтягуванням?',
      'підтягування прямим чи зворотнім хватом на кількість',
      'негативні підтягування для кількості',
      'підтягуватись щодня?',
      'підготовка до нормативу з підтягувань',
      'за скільки з 5 до 15 підтягувань',
      'набрав вагу і підтягуюсь менше',
      'як прокачати турнік',
      'шо зробити щоб більше підтягуватись',
      'как увеличить количество подтягиваний',
      'застрял на 5 подтягиваниях',
      'программа на подтягивания',
      'как подтянуться 15 раз',
      'jak zwiększyć liczbę podciągnięć',
      'plan na podciąganie',
      'utknąłem na 5 podciągnięciach',
    ],
  },
  k_mind_muscle: {
    ex: [
      'i dont feel my lats on pulldowns',
      'cant feel my chest when benching',
      'mind muscle connection how to',
      'i only feel it in my arms on back day',
      'how to feel glutes working',
      'i feel squats only in my lower back',
      'does mind muscle connection matter',
      "not feeling the muscle i'm training",
      'how to activate lats',
      'bench press only hitting shoulders and triceps',
      'cant feel my biceps on curls',
      'rows only work my biceps',
      'hip thrust i feel it in my hamstrings not glutes',
      'do i need to feel the muscle to grow',
      'how to target chest not shoulders',
      'lateral raises only traps',
      'how to connect with the muscle',
      'pump in the wrong muscle',
      'feel exercises in the right muscle',
      'why cant i feel my back working',
    ],
    exUk: [
      'не відчуваю широчайші на тязі блоку',
      'не відчуваю груди на жимі',
      'зв’язок мозок-м’яз як розвинути',
      'в день спини відчуваю тільки руки',
      'як відчути роботу сідниць',
      'присід відчуваю тільки попереком',
      'чи важливо відчувати м’яз',
      'не відчуваю м’яз, який треную',
      'як включити широчайші',
      'жим лежачи б’є тільки в плечі і трицепс',
      'не відчуваю біцепс на згинаннях',
      'тяги працюють тільки руками',
      'на ягодичному мості відчуваю задню поверхню а не сідниці',
      'треба відчувати м’яз щоб він ріс?',
      'як навантажити груди а не плечі',
      'махи в сторони йдуть у трапецію',
      'нейром’язовий зв’язок',
      'памп не в тому м’язі',
      'як відчувати правильні м’язи',
      'чому не відчуваю спину',
      'не чувствую широчайшие',
      'не чувствую грудь на жиме',
      'нейромышечная связь как развить',
      'в тягах работают только руки',
      'nie czuję klatki przy wyciskaniu',
      'nie czuję najszerszych grzbietu',
      'połączenie mózg-mięsień jak poprawić',
    ],
  },
  k_partial_reps: {
    ex: [
      'full range of motion or partial reps',
      'are partial reps bad',
      'lengthened partials for growth',
      'half reps worth it',
      'should i go all the way down on every rep',
      'partials at the end of a set',
      'is full rom better for hypertrophy',
      'ego lifting half reps',
      'do partial reps build muscle',
      'top half reps for lockout',
      'bottom half reps better?',
      'how deep should reps be for growth',
      'partial reps on leg press',
      'i only go halfway on bench',
      'stretch position partials',
      'full range vs heavier weight',
      'range of motion and muscle growth',
      'is it ok to not lock out',
      'quarter squats useful?',
      'partials science',
    ],
    exUk: [
      'повна амплітуда чи часткові повтори',
      'часткові повтори це погано?',
      'часткові повтори в розтягнутій позиції для росту',
      'напівповтори мають сенс?',
      'треба опускати до кінця на кожному повторі?',
      'часткові повтори в кінці підходу',
      'повна амплітуда краще для маси?',
      'его ліфтинг напівповтори',
      'часткові повтори качають м’язи?',
      'верхня половина руху для дотиску',
      'нижня половина повторів краще?',
      'наскільки глибоко робити повтори для росту',
      'часткові на жимі ногами',
      'жму тільки до половини',
      'повтори в розтягнутому положенні',
      'повна амплітуда чи більша вага',
      'амплітуда і ріст м’язів',
      'не випрямляти руки до кінця нормально?',
      'чвертьприсіди корисні?',
      'часткова амплітуда наука',
      'полная амплитуда или частичные повторения',
      'частичные повторы вредны?',
      'неполная амплитуда для массы',
      'полуповторы есть смысл',
      'pełny zakres ruchu czy półpowtórzenia',
      'czy częściowe powtórzenia budują mięśnie',
      'niepełny zakres ruchu',
    ],
  },
  k_bands: {
    ex: [
      'are resistance bands effective',
      'can you build muscle with bands',
      'bands vs weights',
      'resistance band workout any good',
      'home workout with bands only',
      'are bands good for hypertrophy',
      'travel with resistance bands',
      'band pull aparts benefits',
      'which resistance bands to buy',
      'band assisted pull ups',
      'can bands replace dumbbells',
      'loop bands vs tube bands',
      'banded squats useful?',
      'how to progress with resistance bands',
      'resistance bands for beginners',
      'band snapped scared to use them',
      'bands for warm up',
      'mini bands glutes worth it',
      'bands for rehab and strength',
      'bands only for 3 months results?',
    ],
    exUk: [
      'чи ефективні гумові петлі',
      'можна накачатись з еспандерами',
      'петлі чи ваги',
      'тренування з резинками ефективне?',
      'домашні тренування лише з петлями',
      'резинки для росту м’язів',
      'брати петлі в поїздку',
      'розведення резинки для спини користь',
      'які фітнес-резинки купити',
      'підтягування з резинкою',
      'петлі можуть замінити гантелі?',
      'мінібенди для сідниць варто?',
      'присідання з резинкою корисні?',
      'як прогресувати з петлями',
      'еспандер для новачків',
      'боюсь що резинка лопне',
      'резинки для розминки',
      'гумові джгути для сили',
      '3 місяці тільки з резинками буде результат?',
      'трубчасті еспандери чи петлі',
      'эффективны ли резинки для тренировок',
      'можно накачаться с резинками',
      'резинки или гантели',
      'фитнес резинки для дома',
      'czy gumy oporowe są skuteczne',
      'trening z gumami w domu',
      'gumy czy hantle',
    ],
  },
  k_kettlebell_swing: {
    ex: [
      'how to do a kettlebell swing',
      'kettlebell swing form',
      'kettlebell swing lower back pain',
      'russian vs american swing',
      'should kettlebell swing be a squat',
      'what weight kettlebell to start',
      'kettlebell swings for fat loss',
      'how high should the kettlebell go',
      'kettlebell swing hinge tips',
      'my arms get tired on kb swings',
      'kettlebell swing muscles worked',
      'how many kettlebell swings a day',
      'two hand vs one hand swing',
      'swing kettlebell over head?',
      'kettlebell swing common mistakes',
      'kb swing hips or arms',
      'is kettlebell swing good for glutes',
      '10000 swing challenge',
      'kettlebell swings every day ok',
      'hardstyle swing technique',
    ],
    exUk: [
      'як правильно робити махи гирею',
      'техніка махів гирею',
      'від махів гирею болить поперек',
      'російський чи американський мах',
      'махи гирею це присід?',
      'з якої гирі почати',
      'махи гирею для схуднення',
      'наскільки високо має йти гиря',
      'махи гирею як тазом працювати',
      'руки втомлюються на махах гирі',
      'які м’язи працюють на махах гирею',
      'скільки махів робити',
      'махи двома руками чи однією',
      'мах гирею над головою треба?',
      'помилки в махах гирею',
      'мах гирею тазом чи руками',
      'махи гирею для сідниць',
      'махи гирею щодня нормально?',
      'як махати гирею щоб не зірвати спину',
      'махи з гантеллю замість гирі',
      'как правильно делать махи гирей',
      'техника махов гирей',
      'от махов болит поясница',
      'какой вес гири взять',
      'jak robić swing kettlebell',
      'technika swingu z kettlem',
      'ból pleców przy swingach',
    ],
  },
  k_program_hopping: {
    ex: [
      'should i change my workout often',
      'muscle confusion is it real',
      'how often to change program',
      'program hopping bad?',
      'switch routine every week',
      'bored of my program should i change',
      'does changing exercises help growth',
      'shock your muscles myth',
      'how long to stick with a program',
      'new program every month ok?',
      'keep the same workout for months?',
      'when to switch routines',
      'variety vs consistency in training',
      'change exercises every session',
      'i keep trying new programs',
      'is my body used to my workout',
      'switching splits every few weeks',
      'stuck because i always change my plan',
      'muscles adapt so i need to change?',
      'how many weeks per program',
    ],
    exUk: [
      'чи треба часто міняти програму',
      'шок для м’язів це правда?',
      'як часто міняти програму тренувань',
      'стрибати з програми на програму погано?',
      'міняти тренування щотижня',
      'набридла програма міняти?',
      'зміна вправ допомагає рости?',
      'міф про шокування м’язів',
      'скільки триматись однієї програми',
      'нова програма щомісяця норм?',
      'роками одна й та сама програма?',
      'коли міняти програму',
      'різноманіття чи сталість у тренуваннях',
      'міняти вправи щотренування',
      'постійно пробую нові програми',
      'організм звик до тренувань?',
      'міняю спліт кожні кілька тижнів',
      'м’язи адаптуються тому треба міняти?',
      'скільки тижнів на одну програму',
      'стою на місці бо постійно міняю план',
      'нужно ли часто менять программу',
      'шоковая тренировка мышц миф?',
      'как часто менять программу',
      'мышцы привыкают к нагрузке?',
      'jak często zmieniać plan treningowy',
      'czy mięśnie się przyzwyczajają',
      'zmiana planu co tydzień',
    ],
  },
  k_cardio_order: {
    ex: [
      'cardio before or after weights',
      'should i run before lifting',
      'treadmill before or after gym',
      'cardio first or weights first',
      'best order cardio and strength',
      'does cardio before lifting kill strength',
      'bike before leg day ok?',
      'cardio after weights for fat loss',
      'warm up on treadmill before lifting',
      'cardio and weights same day order',
      'hiit before or after lifting',
      'run after leg day?',
      'separate cardio and lifting days',
      'order of workout cardio',
      'lift then cardio or cardio then lift',
      'should i do cardio at the end',
      '20 min cardio before weights too much?',
      'cardio same session as legs',
      'morning run evening lift',
      'stairmaster after workout good?',
    ],
    exUk: [
      'кардіо до чи після силового',
      'бігати до залізу чи після',
      'доріжка до чи після тренування',
      'спочатку кардіо чи ваги',
      'порядок кардіо і силових',
      'кардіо перед залізом вбиває силу?',
      'велотренажер перед ногами можна?',
      'кардіо після силового для схуднення',
      'розминка на доріжці перед залізом',
      'кардіо і ваги в один день порядок',
      'HIIT до чи після залізу',
      'бігати після дня ніг?',
      'кардіо і силові в різні дні',
      'в якому порядку робити кардіо',
      'залізо потім кардіо чи навпаки',
      'кардіо в кінці тренування треба?',
      '20 хвилин кардіо перед вагами забагато?',
      'кардіо в один день з ногами',
      'зранку біг ввечері зал',
      'степер після тренування',
      'кардио до или после силовой',
      'бегать до тренировки или после',
      'сначала кардио или железо',
      'кардио после силовой для похудения',
      'cardio przed czy po treningu siłowym',
      'najpierw bieżnia czy ciężary',
      'kolejność cardio i siłowni',
    ],
  },
  k_exercise_order: {
    ex: [
      'what order should i do exercises',
      'compound or isolation first',
      'exercise order in a workout',
      'should squats be first',
      'does exercise order matter',
      'abs at start or end of workout',
      'bench before or after incline',
      'should i do arms before chest',
      'order of exercises for hypertrophy',
      'biceps before back?',
      'which exercise goes first leg day',
      'pre exhaust worth it',
      'deadlift before or after squats',
      'big lifts first always?',
      'how to arrange my workout',
      'isolation first to target lagging muscle',
      'should i train weak muscle first',
      'workout sequence tips',
      'does it matter if i do machines first',
      'best order push day exercises',
    ],
    exUk: [
      'в якому порядку робити вправи',
      'база чи ізоляція спочатку',
      'порядок вправ на тренуванні',
      'присід має бути першим?',
      'чи важливий порядок вправ',
      'прес на початку чи в кінці',
      'жим лежачи до чи після похилого',
      'руки перед грудьми можна?',
      'порядок вправ для маси',
      'біцепс перед спиною?',
      'що першим на день ніг',
      'попереднє втомлення має сенс?',
      'станова до чи після присіду',
      'важкі вправи завжди першими?',
      'як скласти порядок тренування',
      'ізоляцію першою для відстаючого м’яза',
      'тренувати слабкий м’яз першим?',
      'послідовність вправ поради',
      'тренажери спочатку це погано?',
      'порядок вправ у жимовий день',
      'в каком порядке делать упражнения',
      'база или изоляция сначала',
      'пресс в начале или в конце',
      'порядок упражнений на тренировке',
      'w jakiej kolejności robić ćwiczenia',
      'najpierw wielostawowe czy izolowane',
      'kolejność ćwiczeń na treningu',
    ],
  },
  k_imbalance: {
    ex: [
      'one side stronger than the other',
      'muscle imbalance fix',
      'left arm weaker than right',
      'one pec bigger than the other',
      'bar tilts when i bench',
      'shifting to one side on squat',
      'uneven biceps',
      'one leg weaker squat',
      'how to fix strength imbalance',
      'unilateral exercises for imbalance',
      'should i do extra sets on my weak side',
      'my right side does all the work',
      'one lat bigger',
      'is it normal to have a stronger side',
      'hips shift during squats',
      'dumbbells to fix imbalance',
      'uneven shoulders gym',
      'one glute bigger than the other',
      'asymmetry in muscles',
      'weak side catch up how long',
    ],
    exUk: [
      'одна сторона сильніша за іншу',
      'як виправити дисбаланс м’язів',
      'ліва рука слабша за праву',
      'один грудний більший за інший',
      'штанга перекошується на жимі',
      'зміщуюсь в один бік на присіді',
      'біцепси різні',
      'одна нога слабша на присіді',
      'як виправити дисбаланс сили',
      'вправи на одну руку для дисбалансу',
      'робити більше підходів на слабку сторону?',
      'права сторона все робить',
      'одна широчайша більша',
      'нормально що одна сторона сильніша?',
      'таз зміщується на присіді',
      'гантелі щоб вирівняти сторони',
      'плечі на різній висоті',
      'одна сіднична більша',
      'асиметрія м’язів',
      'за скільки слабка сторона наздожене',
      'одна сторона сильнее другой',
      'дисбаланс мышц как исправить',
      'левая рука слабее правой',
      'штанга перекашивается на жиме',
      'jedna strona silniejsza od drugiej',
      'asymetria mięśni',
      'lewa ręka słabsza od prawej',
    ],
  },
  k_knees_over_toes: {
    ex: [
      'knees over toes bad',
      'is it ok if my knees go past my toes',
      'knees past toes squat myth',
      'trainer says knees shouldnt pass toes',
      'knees in front of toes when squatting',
      'does knee over toe ruin knees',
      'knees over toes guy legit?',
      'lunges knees past toes',
      'should my knees stay behind my toes',
      'knees forward in squat dangerous',
      'is it bad form if knees pass toes',
      'front squat knees way forward',
      'old rule knees behind toes',
      'knee travel squat',
      'my knees go way past my toes deep squat',
      'knees over toes safe for knees',
      'shins forward squat ok',
      'atg split squat knees over toes',
      'knee over toe training',
      'should i sit back so knees dont go forward',
    ],
    exUk: [
      'коліна за носки це погано?',
      'чи можна щоб коліна виходили за носки',
      'міф про коліна за носками',
      'тренер каже коліна не мають виходити за носки',
      'коліна попереду носків при присіданні',
      'коліна за носки руйнують суглоби?',
      'випади коліна за носок',
      'коліна мають бути за носками?',
      'коліна вперед на присіді небезпечно?',
      'погана техніка якщо коліна виходять за носки',
      'фронтальний присід коліна далеко вперед',
      'старе правило коліна не за носки',
      'в глибокому присіді коліна далеко за носками',
      'коліна за носками безпечно для колін',
      'гомілки вперед у присіді ок?',
      'треба сідати назад щоб коліна не йшли вперед',
      'knees over toes метод це що',
      'коліно виходить за носок на болгарських',
      'присідання коліна за носки шкода',
      'чи треба тримати коліна над стопою',
      'колени за носки это плохо?',
      'можно ли выводить колени за носки',
      'колени выходят за носки при приседе',
      'миф про колени за носками',
      'kolana za palcami w przysiadzie',
      'czy kolana mogą wychodzić za palce',
      'kolana przed palcami źle?',
    ],
  },
  k_bail_squat: {
    ex: [
      'how to bail a squat',
      'failed squat what to do',
      'how to set safety pins for squats',
      'squat alone safely',
      'how high should safety bars be',
      'dump the bar behind on squat',
      'i got stuck at the bottom of a squat',
      'squatting without spotter safe?',
      'how to spot a squat',
      'safety straps vs pins',
      'what to do if you cant get up from a squat',
      'practice bailing squat',
      'fear of failing squat',
      'no rack at my gym how to squat safely',
      'stuck under the bar squat',
      'pins too high cutting my depth',
      'how to drop the bar safely',
      'squat failure technique',
      'home gym squat safety',
      'spotter for squats how',
    ],
    exUk: [
      'як безпечно скинути штангу на присіді',
      'не встав з присіду що робити',
      'як виставити страхувальні упори для присіду',
      'присідати самому безпечно',
      'на якій висоті ставити упори',
      'скинути штангу назад на присіді',
      'застряг внизу присіду',
      'присідати без страхувальника безпечно?',
      'як страхувати на присіді',
      'ремені чи упори в рамі',
      'що робити якщо не можу встати з присіду',
      'потренувати скидання штанги',
      'боюсь не встати з присіду',
      'в залі нема рами як присідати безпечно',
      'придавило штангою на присіді',
      'упори заважають глибині',
      'як правильно кинути штангу',
      'домашній зал безпека на присіді',
      'страховка на присіді як',
      'впав під штангою на присіді',
      'как безопасно сбросить штангу в приседе',
      'не встал с приседа что делать',
      'как выставить страховочные упоры',
      'приседать одному безопасно?',
      'jak bezpiecznie zrzucić sztangę w przysiadzie',
      'jak ustawić asekurację do przysiadów',
      'przysiad bez asekuracji',
    ],
  },
  k_personal_trainer: {
    ex: [
      'is a personal trainer worth it',
      'should i get a pt',
      'do i need a coach',
      'how to choose a personal trainer',
      'online coaching vs in person',
      'pt too expensive alternatives',
      'is my trainer any good',
      'signs of a bad personal trainer',
      'how many sessions with a trainer',
      'hire a coach to learn deadlift',
      'trainer vs doing it myself',
      'personal trainer for beginners worth the money',
      'what to ask a personal trainer',
      'coach for powerlifting worth it',
      'gym trainer keeps selling me supplements',
      'should i pay for online coaching',
      'is a pt worth it if im already experienced',
      'trainer or app',
      'how much should a personal trainer cost',
      'good coach qualities',
    ],
    exUk: [
      'чи варто брати персонального тренера',
      'чи потрібен мені тренер',
      'як вибрати персонального тренера',
      'онлайн тренер чи наживо',
      'персоналка дорого які альтернативи',
      'мій тренер нормальний?',
      'ознаки поганого тренера',
      'скільки занять з тренером треба',
      'найняти тренера щоб навчитись становій',
      'тренер чи самостійно',
      'персональний тренер для новачка вартий грошей?',
      'що спитати в персонального тренера',
      'тренер з пауерліфтингу варто?',
      'тренер в залі постійно продає добавки',
      'платити за онлайн-ведення?',
      'чи треба тренер якщо вже маю досвід',
      'тренер чи додаток',
      'скільки коштує персональний тренер',
      'яким має бути хороший тренер',
      'брати персоналки чи ні',
      'стоит ли брать персонального тренера',
      'нужен ли мне тренер',
      'как выбрать тренера',
      'онлайн ведение или персональные тренировки',
      'czy warto mieć trenera personalnego',
      'jak wybrać trenera personalnego',
      'trener online czy na żywo',
    ],
  },
};
