/**
 * A second round of phrasings for the topics of topicsMore.ts (part B: diet
 * phases, cardio, mobility, kit, gym life, special groups, mindset, measuring,
 * symptoms) and the app help of appTips.ts.
 */
export const MORE_TOPICS_EX2B: Record<string, { ex: string[]; exUk: string[] }> = {
  k_reverse_diet: {
    ex: [
      'coming off a cut how many calories to add',
      'after my diet how do i go back to maintenance',
      'reverse diet slowly or jump to maintenance',
      'post diet rebound how to avoid',
      'ending a cut what now',
      'jak wyjść z diety redukcyjnej',
      'ile kalorii dodać po redukcji',
      'kaip išeiti iš dietos',
      'kuidas dieedist välja tulla',
      'yak vyity z dietu',
    ],
    exUk: [
      'закінчив сушку скільки калорій додавати',
      'як повернутися на підтримку після дієти',
      'вихід з дієти поступово чи одразу',
      'як не набрати назад після сушки',
      'выход из диеты как правильно',
    ],
  },
  k_diet_break: {
    ex: [
      'maintenance week during a cut',
      'refeed days on a diet',
      'diet break metabolism',
      'should i eat at maintenance for a week while cutting',
      'high carb day during cut',
      'przerwa od diety na redukcji',
      'dzień refeed',
      'dietos pertrauka',
      'dieedipaus kaalulangetuse ajal',
      'pererva v dieti',
    ],
    exUk: [
      'тиждень на підтримці під час сушки',
      'вуглеводний день на сушці',
      'перерва в дієті для метаболізму',
      'рефід раз на тиждень',
      'диетический перерыв на сушке',
    ],
  },
  k_scale_fluctuations: {
    ex: [
      'weight went up 2 kg overnight',
      'scale says im heavier after gym',
      'why do i weigh more after a salty meal',
      'daily weight swings normal',
      'water retention weight gain',
      'weight up and down all week',
      'waga rano i wieczorem różna',
      'woda w organizmie waga',
      'svoris šokinėja',
      'kaal kõigub päevast päeva',
      'vaha skache',
    ],
    exUk: [
      'за ніч набрав 2 кг',
      'вага після залу більша',
      'чому вага більша після солоного',
      'щоденні коливання ваги норма',
      'вес скачет каждый день',
    ],
  },
  k_keto: {
    ex: [
      'keto diet and gym',
      'low carb for bodybuilding',
      'keto strength loss',
      'keto for fat loss while lifting',
      'ketosis and muscle',
      'dieta keto a siłownia',
      'keto na masę',
      'keto dieta ir raumenys',
      'keto dieet ja lihased',
      'keto dieta i zal',
    ],
    exUk: [
      'кето дієта і зал',
      'низьковуглеводка для набору мʼязів',
      'на кето падає сила',
      'кетоз і мʼязи',
      'кето диета и тренировки',
    ],
  },
  k_intermittent_fasting: {
    ex: [
      'intermittent fasting while lifting',
      '16 8 fasting and muscle gain',
      'eating window and bodybuilding',
      'if diet for fat loss',
      'one meal a day and gym',
      'post przerywany na siłowni',
      'okno żywieniowe 8 godzin',
      'protarpinis badavimas treniruojantis',
      'vahelduv paastumine treenides',
      'intervalne holoduvannia v zali',
    ],
    exUk: [
      'інтервальне голодування і тренування',
      'вікно харчування 8 годин',
      'їсти раз на день і зал',
      'голодування 16 на 8 для схуднення',
      'интервальное голодание и качалка',
    ],
  },
  k_teen_supplements: {
    ex: [
      'supplements for a teenager in the gym',
      'teen taking whey protein',
      'can a 16 year old use creatine',
      'pre workout for teens',
      'my kid wants protein powder',
      'suplementy dla nastolatka',
      'białko dla nastolatka',
      'papildai paaugliui',
      'toidulisandid teismelisele',
      'dobavky dlia pidlitka',
    ],
    exUk: [
      'добавки для підлітка',
      'протеїн у 15 років',
      'чи можна 16 річному креатин',
      'предтрен для підлітка',
      'добавки подростку',
    ],
  },
  k_vo2max: {
    ex: [
      'raise vo2 max',
      'vo2max training plan',
      'norwegian 4x4',
      'vo2 max intervals',
      'my garmin vo2max dropped',
      'jak zwiększyć vo2max',
      'trening vo2max',
      'vo2max treniruotės',
      'vo2max treening',
      'yak pidniaty vo2max',
    ],
    exUk: [
      'підняти vo2 max',
      'тренування на vo2max',
      'норвезькі інтервали 4 на 4',
      'впав vo2max на годиннику',
      'как поднять vo2max',
    ],
  },
  k_incline_walk: {
    ex: [
      'incline treadmill walk',
      '12 3 30 workout',
      'walking uphill on treadmill for cardio',
      'stair climber vs incline walk',
      'incline walking fat loss',
      'chodzenie na bieżni pod górę',
      'bieżnia nachylenie 12',
      'ėjimas takeliu įkalnėn',
      'jooksulint kaldega kõndimine',
      'khodba pid nakhylom',
    ],
    exUk: [
      'ходьба під нахилом на доріжці',
      '12 3 30 на доріжці',
      'степер чи ходьба під нахилом',
      'ходьба в гору для схуднення',
      'ходьба под наклоном',
    ],
  },
  k_rowing_machine: {
    ex: [
      'rower technique',
      'how to row on an erg',
      'rowing machine damper',
      'rowing machine workout',
      'is rowing good cardio',
      'ergometr wioślarski technika',
      'wioślarz w siłowni',
      'irklavimo treniruoklis technika',
      'sõudeergomeeter tehnika',
      'hrebnyi trenazher tekhnika',
    ],
    exUk: [
      'гребний тренажер техніка',
      'як правильно гребти',
      'демпфер на гребному',
      'гребля корисне кардіо',
      'гребля на тренажере',
    ],
  },
  k_jump_rope: {
    ex: [
      'jumping rope workout',
      'skipping for cardio',
      'jump rope shin splints',
      'how long should i skip rope',
      'double unders',
      'skakanka trening',
      'skakanka na spalanie',
      'šokdynė treniruotė',
      'hüppenöör treening',
      'skakalka trenuvannia',
    ],
    exUk: [
      'скакалка тренування',
      'скільки часу стрибати на скакалці',
      'скакалка для кардіо',
      'подвійні оберти скакалки',
      'прыжки на скакалке',
    ],
  },
  k_thoracic: {
    ex: [
      'upper back mobility drills',
      'stiff thoracic spine',
      'foam roller for upper back',
      'open book stretch',
      'thoracic rotation exercise',
      'mobilność piersiowego',
      'sztywny odcinek piersiowy',
      'krūtinės stuburo mankšta',
      'rinnaku lülisamba liikuvus',
      'rukhlyvist verkhu spyny',
    ],
    exUk: [
      'рухливість верху спини',
      'ролик для грудного відділу',
      'розгинання грудного відділу',
      'скручування грудного відділу вправа',
      'подвижность грудного отдела',
    ],
  },
  k_hip_flexors: {
    ex: [
      'hip flexor tightness',
      'tight hips from desk job',
      'couch stretch',
      'kneeling hip flexor stretch',
      'psoas release',
      'rozciąganie zginaczy biodra',
      'spięte biodra od siedzenia',
      'klubo lenkiamųjų tempimas',
      'puusapainutajate venitus',
      'roztiazhka zhynachiv stehna',
    ],
    exUk: [
      'затиснуті згиначі стегна',
      'розтяжка згиначів стегна на колінах',
      'від офісної роботи затиснуті стегна',
      'розслабити псоас',
      'растяжка сгибателей бедра',
    ],
  },
  k_hamstring_flex: {
    ex: [
      'improve hamstring flexibility',
      'tight hamstrings stretch',
      'cant reach my toes',
      'forward fold flexibility',
      'hamstring stretching routine',
      'rozciąganie dwugłowych',
      'nie sięgam do palców stóp',
      'šlaunies užpakalinių raumenų tempimas',
      'reie tagakülje venitus',
      'roztiahuvannia zadnoi poverkhni stehna',
    ],
    exUk: [
      'розтяжка задньої поверхні стегна',
      'не дістаю до пальців ніг',
      'нахил вперед гнучкість',
      'затиснуті біцепси стегна',
      'растяжка задней поверхности бедра',
    ],
  },
  k_shoulder_warmup: {
    ex: [
      'shoulder warm up for bench',
      'warm up rotator cuff before pressing',
      'band pull aparts before bench',
      'shoulder mobility before overhead press',
      'how to prep shoulders',
      'rozgrzewka barków',
      'rozgrzewka przed ławką',
      'pečių apšilimas',
      'õlgade soojendus',
      'rozminka plechei',
    ],
    exUk: [
      'розминка плечей',
      'розминка ротаторів перед жимом',
      'резинка перед жимом лежачи',
      'розминка плечових суглобів з резинкою',
      'разминка плеч',
    ],
  },
  k_wrist_mobility: {
    ex: [
      'wrist mobility drills',
      'wrist pain bench press',
      'wrists bend back on bench',
      'wrist stretches for lifters',
      'front rack wrist pain',
      'mobilność nadgarstków',
      'ból nadgarstka przy wyciskaniu',
      'riešų mankšta',
      'randmete liikuvus',
      'rukhlyvist zapiast',
    ],
    exUk: [
      'рухливість запʼясть',
      'біль у запʼясті на жимі',
      'запʼястя загинаються на жимі',
      'розтяжка запʼясть',
      'подвижность запястий',
    ],
  },
  k_yoga: {
    ex: [
      'yoga for weightlifters',
      'yoga on rest days',
      'is yoga enough exercise',
      'yoga and strength training',
      'power yoga before legs',
      'joga dla ćwiczących',
      'joga w dni wolne',
      'joga ir jėgos treniruotės',
      'jooga ja jõutreening',
      'yoha i sylovi',
    ],
    exUk: [
      'йога і силові',
      'йога в дні відпочинку',
      'йога замість залу',
      'силова йога перед ногами',
      'йога и силовые',
    ],
  },
  k_pilates: {
    ex: [
      'pilates and weight training',
      'is pilates enough',
      'pilates for core strength',
      'reformer pilates vs gym',
      'mat pilates lifting',
      'pilates i ciężary',
      'pilates czy siłownia',
      'pilatesas ir svoriai',
      'pilates ja raskused',
      'pilates i zal',
    ],
    exUk: [
      'пілатес і силові',
      'пілатес чи зал',
      'пілатес для корпусу',
      'реформер пілатес',
      'пилатес и зал',
    ],
  },
  k_gloves: {
    ex: [
      'lifting gloves',
      'gym gloves calluses',
      'do real lifters wear gloves',
      'gloves or chalk',
      'weight lifting gloves grip',
      'rękawiczki na siłownię',
      'rękawiczki czy magnezja',
      'pirštinės sporto salėje',
      'jõusaali kindad',
      'rukavychky dlia zalu',
    ],
    exUk: [
      'рукавички для залу',
      'рукавички від мозолів',
      'рукавиці чи магнезія',
      'чи носять рукавички в залі',
      'перчатки для тренажерки',
    ],
  },
  k_bar_weight: {
    ex: [
      'barbell weight in kg',
      'olympic bar 20 kg',
      'does the bar count in the weight',
      'how much does an ez bar weigh',
      'smith machine bar weight',
      'womens bar 15 kg',
      'ile waży gryf olimpijski',
      'waga gryfu łamanego',
      'kiek sveria olimpinis grifas',
      'olümpiakang kaal',
      'vaha hryfa',
    ],
    exUk: [
      'скільки важить олімпійський гриф',
      'гриф 20 кг',
      'чи рахувати гриф у вагу',
      'скільки важить гриф у сміті',
      'сколько весит олимпийский гриф',
    ],
  },
  k_weight_vest: {
    ex: [
      'weighted vest workout',
      'weight vest for walking',
      'weighted vest pull ups',
      'rucking with a vest',
      'how heavy should a weight vest be',
      'kamizelka z obciążeniem',
      'kamizelka do podciągania',
      'svorinė liemenė',
      'raskusvest',
      'obvazhuvalnyi zhylet',
    ],
    exUk: [
      'жилет з обважненням',
      'жилет для ходьби',
      'підтягування з жилетом',
      'яка вага жилета',
      'утяжелительный жилет',
    ],
  },
  k_spotting_others: {
    ex: [
      'how to spot bench press',
      'spotting squats properly',
      'what should a spotter do',
      'how much should the spotter help',
      'friend asked me to spot',
      'jak asekurować na ławce',
      'asekuracja przy przysiadzie',
      'kaip apdrausti spaudime',
      'kuidas julgestada lamades surumisel',
      'yak strakhuvaty druha',
    ],
    exUk: [
      'як страхувати на жимі',
      'як страхувати на присіданнях',
      'друг попросив пострахувати',
      'наскільки страхувальник має допомагати',
      'как страховать партнера',
    ],
  },
  k_busy_gym: {
    ex: [
      'bench is always taken',
      'squat rack occupied',
      'gym too crowded',
      'someone is hogging the machine',
      'when is the gym least busy',
      'siłownia pełna ludzi',
      'wszystkie maszyny zajęte',
      'sporto salėje daug žmonių',
      'jõusaal täis inimesi',
      'u zali bahato liudei',
    ],
    exUk: [
      'лавка завжди зайнята',
      'в залі купа народу',
      'хтось займає тренажер',
      'коли в залі найменше людей',
      'в зале много людей',
    ],
  },
  k_gym_bag: {
    ex: [
      'gym essentials to pack',
      'first time at the gym what to bring',
      'what goes in a gym bag',
      'gym bag checklist',
      'what do i take to the gym',
      'co spakować do torby na siłownię',
      'co wziąć na pierwszy trening',
      'ką įsidėti į sporto krepšį',
      'mida spordikotti panna',
      'shcho vziaty v zal',
    ],
    exUk: [
      'що взяти на перше тренування',
      'що покласти в сумку для залу',
      'що потрібно мати в залі',
      'список речей у спортзал',
      'что взять в спортзал',
    ],
  },
  k_film_form: {
    ex: [
      'film my squat form',
      'recording lifts for form check',
      'camera angle for deadlift',
      'where to put phone to film bench',
      'check my technique on video',
      'nagrać przysiad z boku',
      'kąt kamery do martwego ciągu',
      'nufilmuoti pritūpimą',
      'kükki filmida',
      'znimaty prysid zboku',
    ],
    exUk: [
      'зняти присід на відео',
      'ракурс для зйомки станової',
      'перевірити техніку по відео',
      'куди ставити телефон щоб зняти жим',
      'снимать технику на видео',
    ],
  },
  k_calisthenics: {
    ex: [
      'bodyweight progressions',
      'calisthenics for muscle',
      'harder push up variations',
      'progress without weights at home',
      'bodyweight only muscle growth',
      'kalistenika progresja',
      'trudniejsze pompki',
      'kalistenika raumenims',
      'kalisteenika lihastele',
      'kalistenika prohresiia',
    ],
    exUk: [
      'калістеніка для мʼязів',
      'складніші варіанти віджимань',
      'прогрес без ваг вдома',
      'мʼязи тільки з власною вагою',
      'калистеника прогрессия',
    ],
  },
  k_menopause: {
    ex: [
      'strength training after 50 for women menopause',
      'menopause belly fat workout',
      'hot flashes and training',
      'lifting weights menopause muscle loss',
      'perimenopause gym',
      'ćwiczenia w menopauzie',
      'siłownia a menopauza',
      'menopauzė ir treniruotės',
      'menopaus ja treening',
      'menopauza i sylovi',
    ],
    exUk: [
      'менопауза і силові',
      'клімакс і тренування',
      'припливи і тренування',
      'перименопауза зал',
      'климакс тренировки',
    ],
  },
  k_postpartum: {
    ex: [
      'working out after having a baby',
      'postpartum return to lifting',
      'diastasis recti exercises',
      'gym after c section',
      'when can i run after birth',
      'trening po ciąży',
      'powrót na siłownię po porodzie',
      'sportas po gimdymo',
      'treening pärast sünnitust',
      'trenuvannia pislia polohiv',
    ],
    exUk: [
      'тренування після пологів',
      'зал після кесаревого',
      'діастаз вправи',
      'коли бігати після пологів',
      'тренировки после родов',
    ],
  },
  k_pelvic_floor: {
    ex: [
      'pee when i lift heavy',
      'leaking during deadlifts',
      'pelvic floor weakness',
      'bladder leaks jumping',
      'incontinence while exercising',
      'nietrzymanie moczu podczas ćwiczeń',
      'mięśnie dna miednicy',
      'dubens dugno raumenys',
      'vaagnapõhja lihased',
      'tazove dno vpravy',
    ],
    exUk: [
      'тазове дно вправи',
      'нетримання під час станової',
      'підтікає коли піднімаю важке',
      'слабке тазове дно',
      'тазовое дно упражнения',
    ],
  },
  k_osteoporosis: {
    ex: [
      'osteoporosis exercise',
      'weights for bone density',
      'low bone density lifting safe',
      'osteopenia strength training',
      'build bone density',
      'osteoporoza ćwiczenia',
      'gęstość kości trening',
      'osteoporozė pratimai',
      'osteoporoos treening',
      'osteoporoz trenuvannia',
    ],
    exUk: [
      'остеопороз вправи',
      'як покращити щільність кісток',
      'остеопенія силові',
      'низька щільність кісток зал',
      'остеопороз упражнения',
    ],
  },
  k_arthritis: {
    ex: [
      'knee arthritis exercises',
      'hip osteoarthritis gym',
      'lifting weights with arthritis',
      'strength training for arthritic joints',
      'arthritis squats',
      'artroza ćwiczenia',
      'zwyrodnienie kolana siłownia',
      'artrozė pratimai',
      'artroos treening',
      'artroz vpravy',
    ],
    exUk: [
      'артроз вправи',
      'артроз кульшового суглоба зал',
      'силові при артриті',
      'присідання при артрозі',
      'артроз упражнения',
    ],
  },
  k_habit: {
    ex: [
      'how to stay consistent with working out',
      'build a gym routine',
      'make exercise a habit',
      'how to stop skipping the gym',
      'consistency tips gym',
      'jak wyrobić nawyk treningu',
      'regularność na siłowni',
      'kaip būti nuosekliam sporte',
      'kuidas trennis järjepidev olla',
      'yak ne kydaty zal',
    ],
    exUk: [
      'як тренуватися регулярно',
      'як виробити звичку ходити в зал',
      'як перестати пропускати зал',
      'регулярність у тренуваннях',
      'как не бросить зал',
    ],
  },
  k_program_boredom: {
    ex: [
      'bored with my routine',
      'training feels boring',
      'how to make workouts fun',
      'same program for months boring',
      'need variety in training',
      'nudna rutyna na siłowni',
      'jak urozmaicić trening',
      'nuobodžios treniruotės',
      'igav treeningukava',
      'nudni trenuvannia',
    ],
    exUk: [
      'нудна програма',
      'хочу різноманітності в тренуваннях',
      'як зробити тренування цікавими',
      'місяцями одне й те саме',
      'скучные тренировки',
    ],
  },
  k_comparison: {
    ex: [
      'everyone else is stronger than me',
      'social media fitness makes me insecure',
      'comparing to other lifters',
      'feel small next to big guys',
      'fitness influencers body',
      'porównywanie się z innymi na siłowni',
      'czuję się słaby przy innych',
      'lyginimas su kitais sporte',
      'enese võrdlemine teistega',
      'porivniannia z inshymy',
    ],
    exUk: [
      'всі сильніші за мене',
      'фітнес блогери а я',
      'порівнюю себе з іншими атлетами',
      'почуваюсь маленьким поруч з іншими',
      'сравниваю себя с другими',
    ],
  },
  k_psych_up: {
    ex: [
      'mental prep for a pr',
      'getting hyped for heavy sets',
      'focus before a max lift',
      'how to visualize a lift',
      'pre lift routine',
      'przygotowanie mentalne do rekordu',
      'jak się skupić przed ciężką serią',
      'psichologinis pasiruošimas rekordui',
      'vaimne ettevalmistus rekordiks',
      'mentalna pidhotovka do rekordu',
    ],
    exUk: [
      'ментальна підготовка до рекорду',
      'як зосередитися перед максимумом',
      'ритуал перед важким підходом',
      'як завестися на рекорд',
      'настрой перед рекордом',
    ],
  },
  k_fear_heavy: {
    ex: [
      'afraid to lift heavy',
      'scared of failing a squat',
      'fear under the barbell',
      'nervous about heavy weights',
      'scared to max out',
      'strach przed ciężarem',
      'boję się przysiadu z dużym ciężarem',
      'baimė kelti sunkų svorį',
      'hirm raskete raskuste ees',
      'strakh vazhkoi vahy',
    ],
    exUk: [
      'страх важкої ваги',
      'боюся провалити присід',
      'нервую перед важкою вагою',
      'страшно йти на максимум',
      'страх большого веса',
    ],
  },
  k_dance: {
    ex: [
      'strength training for dancers',
      'dancer lifting weights',
      'dance and gym combination',
      'lifting for ballet dancers',
      'will weights make me less flexible for dance',
      'trening siłowy dla tancerzy',
      'taniec i siłownia',
      'jėgos treniruotės šokėjams',
      'jõutreening tantsijatele',
      'sylovi dlia tantsivnykiv',
    ],
    exUk: [
      'силові для танцюристів',
      'танці і тренажерний зал',
      'залізо для балерини',
      'гнучкість для танців і силові',
      'силовые для танцоров',
    ],
  },
  k_progress_photos: {
    ex: [
      'progress photos',
      'how to take before and after pictures',
      'progress pics lighting',
      'how often progress photos',
      'transformation photos tips',
      'zdjęcia sylwetki',
      'zdjęcia przed i po',
      'nuotraukos prieš ir po',
      'enne ja pärast pildid',
      'foto do i pislia',
    ],
    exUk: [
      'фото до і після',
      'як часто фотографувати прогрес',
      'світло для фото прогресу',
      'фото трансформації поради',
      'фото до и после',
    ],
  },
  k_measurements: {
    ex: [
      'body measurements to track',
      'measure waist hips arms',
      'tape measure for progress',
      'how to measure biceps',
      'where to measure thigh',
      'pomiary obwodów ciała',
      'jak mierzyć talię',
      'kūno apimtys',
      'keha ümbermõõdud',
      'zamiry tila',
    ],
    exUk: [
      'заміри обхватів тіла',
      'як міряти біцепс',
      'де міряти стегно',
      'сантиметр для прогресу',
      'замеры обхватов',
    ],
  },
  k_body_fat: {
    ex: [
      'body fat percentage',
      'how accurate are body fat scales',
      'dexa scan body fat',
      'estimate my body fat',
      'calipers vs smart scale',
      'procent tkanki tłuszczowej',
      'jak zmierzyć tłuszcz w ciele',
      'riebalų procentas',
      'keharasva protsent',
      'vidsotok zhyru',
    ],
    exUk: [
      'відсоток жиру в тілі',
      'наскільки точні ваги з відсотком жиру',
      'dexa сканування',
      'каліпер чи ваги',
      'процент жира в организме',
    ],
  },
  k_bmi: {
    ex: [
      'bmi overweight but muscular',
      'bmi accurate for athletes',
      'body mass index lifting',
      'is my bmi bad',
      'bmi vs body fat',
      'bmi a mięśnie',
      'bmi dla sportowców',
      'kmi sportininkams',
      'kmi sportlastele',
      'imt dlia sportsmeniv',
    ],
    exUk: [
      'імт і мʼязи',
      'індекс маси тіла для спортсменів',
      'імт показує надмірну вагу',
      'імт чи відсоток жиру',
      'имт и мышцы',
    ],
  },
  k_recomp: {
    ex: [
      'body recomp',
      'recomposition for beginners',
      'lose fat gain muscle at same time',
      'skinny fat how to fix',
      'recomp or cut first',
      'rekompozycja sylwetki',
      'jednocześnie chudnąć i budować mięśnie',
      'kūno rekompozicija',
      'keha rekompositsioon',
      'rekompozytsiia',
    ],
    exUk: [
      'рекомпозиція',
      'скинути жир і набрати мʼязи одночасно',
      'худий з жирком як виправити',
      'рекомп чи спершу сушка',
      'рекомпозиция тела',
    ],
  },
  k_mini_cut: {
    ex: [
      'mini cut',
      'short cut during a bulk',
      'aggressive 4 week cut',
      'mini cut how many calories',
      'mini cut length',
      'mini redukcja na masie',
      'krótka redukcja',
      'trumpa dieta',
      'lühike kuivatus',
      'korotka sushka',
    ],
    exUk: [
      'міні-сушка',
      'коротка сушка під час набору',
      'агресивна сушка на 4 тижні',
      'міні сушка калорії',
      'короткая сушка',
    ],
  },
  k_climbing: {
    ex: [
      'bouldering and gym',
      'climbers strength training',
      'lifting for rock climbers',
      'climbing rest days lifting',
      'antagonist training for climbers',
      'wspinaczka i ciężary',
      'trening siłowy dla wspinaczy',
      'laipiojimas ir jėgos treniruotės',
      'ronimine ja jõusaal',
      'skelelazinnia i sylovi',
    ],
    exUk: [
      'скелелазіння і зал',
      'силові для скелелазів',
      'боулдерінг і силові',
      'антагоністи для скелелаза',
      'скалолазание и силовые',
    ],
  },
  k_muscle_fibers: {
    ex: [
      'fast twitch fibers training',
      'slow twitch muscle',
      'type 2 fibers',
      'muscle fiber types',
      'train fast twitch for explosiveness',
      'włókna mięśniowe typy',
      'włókna szybkie',
      'raumenų skaidulų tipai',
      'lihaskiudude tüübid',
      'typy miazovykh volokon',
    ],
    exUk: [
      'типи мʼязових волокон',
      'швидкі волокна',
      'повільні волокна',
      'волокна 2 типу',
      'типы мышечных волокон',
    ],
  },
  k_rotator_cuff: {
    ex: [
      'rotator cuff exercises',
      'external rotations',
      'rotator cuff prehab',
      'strengthen rotator cuff',
      'rotator cuff for bench press',
      'ćwiczenia na rotatory',
      'rotacja zewnętrzna barku',
      'rotatorių manžetės pratimai',
      'rotaatormanseti harjutused',
      'vpravy na rotatory',
    ],
    exUk: [
      'вправи на ротатори плеча',
      'зовнішня ротація',
      'зміцнити ротаторну манжету',
      'ротатори для жиму',
      'упражнения на ротаторы',
    ],
  },
  k_delt_heads: {
    ex: [
      'rear delts',
      'side delts',
      'front delts need isolation',
      'three heads of shoulder',
      'deltoid heads training',
      'tylne aktony barków',
      'boczne aktony barków',
      'galinės deltos',
      'tagumine deltalihas',
      'zadni delty',
    ],
    exUk: [
      'задні дельти',
      'середні дельти',
      'передні дельти окремо',
      'три пучки плеча',
      'задние дельты',
    ],
  },
  k_ego_lifting: {
    ex: [
      'ego lifting',
      'too heavy with bad form',
      'lifting to impress',
      'half reps heavy weight',
      'ego lift injury',
      'ego lifting co to',
      'za duży ciężar zła technika',
      'per didelis svoris bloga technika',
      'liiga suur raskus halb tehnika',
      'zavelyka vaha pohana tekhnika',
    ],
    exUk: [
      'его ліфтинг',
      'завелика вага погана техніка',
      'половинчасті повтори з великою вагою',
      'тягаю щоб вразити',
      'эго лифтинг',
    ],
  },
  k_skip_legs: {
    ex: [
      'skip leg day',
      'no leg day',
      'only train upper body',
      'is leg day necessary',
      'chicken legs',
      'czy trzeba trenować nogi',
      'pomijanie dnia nóg',
      'ar reikia treniruoti kojas',
      'kas jalapäeva on vaja',
      'propuskaty den nih',
    ],
    exUk: [
      'пропускати день ніг',
      'тільки верх тіла',
      'чи потрібен день ніг',
      'курячі ніжки',
      'пропускать день ног',
    ],
  },
  k_nausea: {
    ex: [
      'nausea during leg day',
      'feel sick after intervals',
      'throwing up at the gym',
      'nauseous during workout',
      'want to vomit after squats',
      'mdłości na treningu',
      'wymioty po treningu',
      'pykinimas sporto salėje',
      'iiveldus trennis',
      'nudota v zali',
    ],
    exUk: [
      'нудота на тренуванні',
      'нудить після присідань',
      'хочеться блювати в залі',
      'нудить в день ніг',
      'тошнота на тренировке',
    ],
  },
  k_shaking: {
    ex: [
      'muscles shaking',
      'legs trembling squats',
      'arms shaky bench',
      'shaking during plank',
      'why do i shake when lifting',
      'drżenie mięśni',
      'trzęsą mi się nogi',
      'raumenų drebulys',
      'lihaste värisemine',
      'tremtinnia miaziv',
    ],
    exUk: [
      'тремтіння мʼязів',
      'трусяться ноги на присіданнях',
      'дрижать руки на жимі',
      'тремчу в планці',
      'дрожь в мышцах',
    ],
  },
  k_joint_clicking: {
    ex: [
      'joints cracking',
      'knees popping squats',
      'shoulder clicking bench',
      'hip popping',
      'crunching sound knee',
      'trzeszczenie kolan',
      'strzelanie w barku',
      'traškantys sąnariai',
      'põlved naksuvad',
      'khrust u kolinakh',
    ],
    exUk: [
      'хруст у колінах',
      'клацає плече',
      'хрустить кульшовий',
      'тріщать суглоби',
      'хруст в коленях',
    ],
  },
  k_stretch_marks: {
    ex: [
      'stretch marks from gym',
      'stretch marks biceps',
      'avoid stretch marks bulking',
      'stretch marks chest',
      'stretch marks fade',
      'rozstępy na bicepsach',
      'rozstępy od siłowni',
      'tempimo žymės ant pečių odos',
      'venitusarmid õlgadel',
      'roztiazhky na plechakh',
    ],
    exUk: [
      'розтяжки на біцепсах',
      'розтяжки від залу',
      'як уникнути розтяжок',
      'розтяжки на грудях',
      'растяжки на плечах',
    ],
  },
};
