/**
 * Phrasings of the hundred topics in topicsMore.ts — for the understanding
 * index only (never the answers). English, Polish, Lithuanian, Estonian and
 * Ukrainian typed in Latin ride in `ex`; Ukrainian, surzhyk and Russian in `exUk`.
 */
export const MORE_TOPICS_EX: Record<string, { ex: string[]; exUk: string[] }> = {
  k_amrap: {
    ex: [
      'what is an amrap set',
      'what does amrap mean',
      'as many reps as possible set how to do it',
      'should i do amrap sets',
      'last set amrap how hard should it be',
      'amrap to failure or leave reps',
      'co to jest seria amrap',
      'kas yra amrap serija',
      'mis on amrap seeria',
      'shcho take amrap',
    ],
    exUk: [
      'що таке амрап',
      'що таке підхід amrap',
      'стільки повторів скільки зможеш як це',
      'амрап до відмови чи ні',
      'останній підхід амрап що це значить',
      'что такое amrap подход',
    ],
  },
  k_emom: {
    ex: [
      'what is emom',
      'emom workout explained',
      'every minute on the minute training',
      'how to do an emom',
      'emom squats good idea',
      'co to jest emom trening',
      'kas yra emom treniruotė',
      'mis on emom treening',
      'shcho take emom trenuvannia',
    ],
    exUk: [
      'що таке емом',
      'тренування emom як робити',
      'кожну хвилину на початку хвилини що це',
      'емом присідання це норм',
      'что такое емом тренировка',
    ],
  },
  k_cluster_sets: {
    ex: [
      'what are cluster sets',
      'cluster set training explained',
      'how to do cluster sets',
      'are cluster sets good for strength',
      'mini sets with 20 seconds rest what is that called',
      'co to są serie klastrowe',
      'kas yra klasterinės serijos',
      'mis on klastriseeriad',
      'shcho take klasterni pidkhody',
    ],
    exUk: [
      'що таке кластерні підходи',
      'кластери в тренуванні це що',
      'як робити кластерні сети',
      'міні підходи з короткою паузою як називаються',
      'что такое кластерные подходы',
    ],
  },
  k_rest_pause: {
    ex: [
      'what is rest pause',
      'how do rest pause sets work',
      'rest-pause training for hypertrophy',
      'is rest pause good',
      'rest 15 seconds and do more reps what is it',
      'co to jest rest pause',
      'kas yra rest pause serija',
      'mis on rest pause seeria',
      'shcho take rest pauza',
    ],
    exUk: [
      'що таке рест пауза',
      'як робити рест-паузу',
      'рест пауза чи дроп сет',
      'відпочив 15 секунд і дотискаю ще це рест пауза?',
      'что такое рест пауза',
    ],
  },
  k_myo_reps: {
    ex: [
      'what are myo reps',
      'myo-reps how to do them',
      'myoreps vs normal sets',
      'are myo reps effective',
      'activation set then mini sets breaths',
      'co to są myo reps',
      'kas yra myo reps',
      'mis on myo kordused',
      'shcho take mio povtory',
    ],
    exUk: [
      'що таке міо повтори',
      'міо-репс як робити',
      'чи ефективні міо повтори',
      'активаційний підхід і міні підходи що це',
      'что такое мио повторы',
    ],
  },
  k_double_progression: {
    ex: [
      'what is double progression',
      'how does double progression work',
      'reps first then weight method',
      'double progression for dumbbells',
      'when to go up in weight with 8-12 reps range',
      'co to jest podwójna progresja',
      'kas yra dviguba progresija',
      'mis on topeltprogressioon',
      'shcho take podviina prohresiia',
    ],
    exUk: [
      'що таке подвійна прогресія',
      'спочатку повтори потім вага як це працює',
      'подвійна прогресія в гантелях',
      'коли переходити на більшу вагу якщо діапазон 8-12',
      'что такое двойная прогрессия',
    ],
  },
  k_taper: {
    ex: [
      'how to taper before a powerlifting meet',
      'how do i taper',
      'peaking for a max test',
      'what to do the week before a competition',
      'tapering volume before a meet',
      'jak zrobić tapering przed zawodami',
      'kaip pasiruošti prieš varžybas mažinant krūvį',
      'kuidas teha taper enne võistlust',
      'yak zrobyty pidvodku pered zmahanniamy',
    ],
    exUk: [
      'як зробити підводку перед змаганнями',
      'що робити за тиждень до змагань з пауерліфтингу',
      'підводка перед тестом максимуму',
      'як зменшувати обсяг перед змаганнями',
      'как сделать подводку к соревнованиям',
    ],
  },
  k_top_backoff: {
    ex: [
      'what is a top set',
      'top set and back off sets',
      'how to do back-off sets',
      'how much to drop for back off sets',
      'one heavy set then lighter sets',
      'co to jest top set i serie back off',
      'kas yra top set ir back off serijos',
      'mis on top set ja back off seeriad',
      'shcho take top set',
    ],
    exUk: [
      'що таке топ сет',
      'топ-сет і бек-оф підходи',
      'на скільки знижувати вагу після топ сету',
      'один важкий підхід а потім легші як це називається',
      'что такое топ сет и бэк офф',
    ],
  },
  k_paused_reps: {
    ex: [
      'are paused squats worth it',
      'paused bench press benefits',
      'should i do pause reps',
      'pause deadlift what for',
      'how long to pause on paused squats',
      'czy warto robić przysiady z pauzą',
      'ar verta daryti pritūpimus su pauze',
      'kas tasub teha pausiga kükke',
      'chy varto robyty prysidannia z pauzoiu',
    ],
    exUk: [
      'чи варто робити присідання з паузою',
      'жим з паузою на грудях навіщо',
      'повтори з паузою що дають',
      'станова з паузою над підлогою',
      'приседания с паузой зачем',
    ],
  },
  k_eccentrics: {
    ex: [
      'do negatives build muscle',
      'eccentric training benefits',
      'slow negatives worth it',
      'what are negative reps',
      'lowering the weight slowly better for growth',
      'czy negatywy budują mięśnie',
      'ar negatyvai augina raumenis',
      'kas negatiivid kasvatavad lihaseid',
      'chy dayut nehatyvy masu',
    ],
    exUk: [
      'чи будують мʼязи негативні повтори',
      'що таке негативи в тренуванні',
      'ексцентрична фаза повільно опускати навіщо',
      'негативні повтори для підтягувань',
      'негативы качают мышцы?',
    ],
  },
  k_volume_landmarks: {
    ex: [
      'what is mev and mrv',
      'maximum recoverable volume',
      'minimum effective volume per muscle',
      'mev mav mrv explained',
      'how many sets is too many sets per week mrv',
      'co to jest mev i mrv',
      'kas yra mev ir mrv',
      'mis on mev ja mrv',
      'shcho take mev i mrv',
    ],
    exUk: [
      'що таке mev і mrv',
      'максимальний відновлюваний обсяг що це',
      'мінімальний ефективний обсяг на мʼяз',
      'мев мрв поясни',
      'что такое mev mrv',
    ],
  },
  k_bfr: {
    ex: [
      'does blood flow restriction training work',
      'bfr training',
      'occlusion training with bands',
      'kaatsu training worth it',
      'is bfr safe',
      'how tight should bfr bands be',
      'czy trening okluzyjny działa',
      'ar veikia kraujotakos ribojimo treniruotė',
      'kas verevoolu piiramisega treening töötab',
      'bfr trenuvannia chy pratsiuie',
    ],
    exUk: [
      'чи працює тренування з обмеженням кровотоку',
      'bfr тренування що це',
      'оклюзійне тренування з джгутами',
      'джгути на руки для тренування безпечно?',
      'окклюзионные тренировки работают?',
    ],
  },
  k_5x5: {
    ex: [
      'is 5x5 a good program',
      'stronglifts 5x5 worth it',
      'should i do stronglifts',
      '5 by 5 for beginners',
      'madcow 5x5 or other',
      'czy program 5x5 jest dobry',
      'ar 5x5 programa gera',
      'kas 5x5 programm on hea',
      'chy dobra prohrama 5x5',
    ],
    exUk: [
      'чи хороша програма 5х5',
      'стронгліфтс 5 на 5 варто',
      'програма 5 на 5 для новачка',
      'стронглифтс 5х5 норм?',
      '5х5 хорошая программа?',
    ],
  },
  k_531: {
    ex: [
      'how does 5/3/1 work',
      'wendler 531 explained',
      'is 5 3 1 good',
      'boring but big program',
      'what is a training max in 531',
      'jak działa program 5/3/1',
      'kaip veikia 5/3/1 programa',
      'kuidas 5/3/1 programm töötab',
      'yak pratsiuie prohrama 531',
    ],
    exUk: [
      'як працює програма 5/3/1',
      'вендлер 531 що це',
      '5 3 1 для середнього рівня',
      'тренувальний максимум в 531',
      'программа 531 вендлера как работает',
    ],
  },
  k_circuit_training: {
    ex: [
      'is circuit training good',
      'circuit workouts for fat loss',
      'circuit training vs normal sets',
      'full body circuit no rest',
      'should i do circuits',
      'czy trening obwodowy jest dobry',
      'ar ratinė treniruotė gera',
      'kas ringtreening on hea',
      'chy dobre kruhove trenuvannia',
    ],
    exUk: [
      'чи добре кругове тренування',
      'кругові тренування для схуднення',
      'кругове чи звичайні підходи',
      'кругова на все тіло без відпочинку',
      'круговая тренировка это хорошо?',
    ],
  },
  k_plyometrics: {
    ex: [
      'should i do plyometrics',
      'box jumps worth it',
      'plyo training for lifters',
      'how many jumps per session',
      'jump training to jump higher',
      'czy robić plyometrię',
      'ar verta daryti pliometriką',
      'kas teha plüomeetrikat',
      'chy varto robyty pliometryku',
    ],
    exUk: [
      'чи варто робити пліометрику',
      'стрибки на тумбу корисно',
      'пліометрика для тих хто качається',
      'як навчитися вище стрибати',
      'плиометрика нужна ли',
    ],
  },
  k_front_squat: {
    ex: [
      'how to front squat',
      'front squat form',
      'front squat grip hurts wrists',
      'front squat elbows drop',
      'front squat vs back squat',
      'jak robić przysiad przedni',
      'kaip daryti priekinį pritūpimą',
      'kuidas teha eeskükki',
      'yak robyty frontalnyi prysid',
    ],
    exUk: [
      'як правильно робити фронтальний присід',
      'фронтальні присідання техніка',
      'фронтальний присід лікті падають',
      'як тримати гриф у фронтальному присіді',
      'фронтальные приседания техника',
    ],
  },
  k_hip_thrust: {
    ex: [
      'how to do hip thrusts',
      'hip thrust form',
      'barbell hip thrust feel it in hamstrings',
      'hip thrust vs glute bridge',
      'best glute exercise hip thrust',
      'jak robić hip thrust',
      'kaip daryti klubų kėlimą su štanga',
      'kuidas teha puusatõstet',
      'yak robyty hip trast',
    ],
    exUk: [
      'як правильно робити ягідний місток зі штангою',
      'хіп траст техніка',
      'сідничний міст зі штангою як',
      'хіп траст відчуваю в задній поверхні стегна',
      'ягодичный мост со штангой техника',
    ],
  },
  k_rdl: {
    ex: [
      'how to do romanian deadlift',
      'rdl form',
      'romanian deadlift how low',
      'rdl how many sets and reps',
      'rdl feel in lower back not hamstrings',
      'jak robić martwy ciąg rumuński',
      'kaip daryti rumunišką trauką',
      'kuidas teha rumeenia jõutõmmet',
      'yak robyty rumunsku tiahu',
    ],
    exUk: [
      'як робити румунську тягу',
      'румунська тяга техніка',
      'наскільки низько опускати в румунській тязі',
      'румунка відчуваю поперек а не біцепс стегна',
      'румынская тяга техника',
    ],
  },
  k_bulgarian_split: {
    ex: [
      'how to do bulgarian split squats',
      'bulgarian split squat form',
      'rear foot elevated split squat',
      'bulgarian split squat glutes or quads',
      'bulgarians balance problems',
      'jak robić przysiad bułgarski',
      'kaip daryti bulgarišką pritūpimą',
      'kuidas teha bulgaaria kükki',
      'yak robyty bolharski vypady',
    ],
    exUk: [
      'як робити болгарські випади',
      'болгарський спліт присід техніка',
      'болгарки на сідниці чи квадрицепс',
      'болгарські присідання не можу втримати рівновагу',
      'болгарские выпады техника',
    ],
  },
  k_lunges: {
    ex: [
      'how to do lunges',
      'lunges hurt my knees',
      'lunge form tips',
      'walking lunges or reverse lunges',
      'knee pain when lunging',
      'jak robić wykroki',
      'kaip daryti įtupstus',
      'kuidas teha väljaasteid',
      'yak robyty vypady',
    ],
    exUk: [
      'як робити випади щоб не боліли коліна',
      'випади техніка',
      'болять коліна від випадів',
      'зворотні випади чи випади в русі',
      'выпады болят колени',
    ],
  },
  k_dips: {
    ex: [
      'are dips bad for shoulders',
      'how to do dips',
      'dips shoulder pain',
      'how deep should i go on dips',
      'chest dips vs tricep dips',
      'czy pompki na poręczach są szkodliwe dla barków',
      'ar atsispaudimai ant lygiagrečių kenkia pečiams',
      'kas dipid on õlgadele halvad',
      'chy shkidlyvi brusy dlia plechei',
    ],
    exUk: [
      'чи шкідливі віджимання на брусах для плечей',
      'бруси болить плече',
      'як глибоко опускатися на брусах',
      'бруси на груди чи на трицепс',
      'брусья вредны для плеч?',
    ],
  },
  k_face_pull: {
    ex: [
      'how to do face pulls',
      'face pull form',
      'why do face pulls',
      'are face pulls necessary',
      'rope face pull how high',
      'jak robić face pull',
      'kaip daryti face pull',
      'kuidas teha face pulli',
      'yak robyty feis pul',
    ],
    exUk: [
      'як робити тягу канату до обличчя',
      'фейс пул навіщо',
      'тяга до обличчя техніка',
      'фейспули обовʼязково?',
      'тяга каната к лицу зачем',
    ],
  },
  k_lateral_raise: {
    ex: [
      'how to do lateral raises',
      'lateral raise form',
      'side raises feel it in traps',
      'lateral raises how heavy',
      'lateral raise elbows or hands',
      'jak robić wznosy bokiem',
      'kaip daryti šoninius kėlimus',
      'kuidas teha külgtõsteid',
      'yak robyty makhy v storony',
    ],
    exUk: [
      'як правильно робити махи в сторони',
      'махи гантелями в сторони техніка',
      'махи відчуваю трапеції а не дельти',
      'яка вага для махів в сторони',
      'махи в стороны техника',
    ],
  },
  k_chinup_vs_pullup: {
    ex: [
      'chin ups vs pull ups',
      'difference between chin up and pull up',
      'which is better chin up or pull up',
      'underhand or overhand pull ups',
      'neutral grip pull ups better',
      'podciąganie podchwytem czy nachwytem',
      'prisitraukimai delnais į save ar nuo savęs',
      'lõuatõmbed alt- või pealthaardega',
      'pidtiahuvannia priamym chy zvorotnym khvatom',
    ],
    exUk: [
      'підтягування прямим чи зворотним хватом',
      'в чому різниця підтягувань різним хватом',
      'зворотний хват на біцепс чи на спину',
      'нейтральний хват підтягування краще?',
      'подтягивания прямым или обратным хватом',
    ],
  },
  k_bench_grip: {
    ex: [
      'how wide should my bench grip be',
      'bench press grip width',
      'wide grip or close grip bench',
      'where to put hands on bench press',
      'should i tuck my elbows on bench',
      'jaki chwyt przy wyciskaniu na ławce',
      'kaip plačiai laikyti štangą spaudžiant gulint',
      'kui lai peaks olema haare lamades surumisel',
      'yakyi khvat u zhymi lezhachy',
    ],
    exUk: [
      'який має бути хват у жимі лежачи',
      'ширина хвату на жимі',
      'широкий чи вузький хват жим лежачи',
      'лікті в жимі притискати чи розводити',
      'какой хват в жиме лежа',
    ],
  },
  k_leg_drive: {
    ex: [
      'what is leg drive on bench',
      'how to use leg drive bench press',
      'legs on bench press',
      'my butt lifts when i use leg drive',
      'feet position bench press',
      'jak pracować nogami przy wyciskaniu',
      'kaip naudoti kojas spaudime gulint',
      'jalgade kasutamine lamades surumisel',
      'robota nohamy v zhymi',
    ],
    exUk: [
      'що таке робота ногами в жимі лежачи',
      'як упиратися ногами в жимі',
      'куди ставити ноги на жимі лежачи',
      'таз відривається коли тисну ногами',
      'как работать ногами в жиме лежа',
    ],
  },
  k_high_low_bar: {
    ex: [
      'high bar or low bar squat',
      'low bar vs high bar',
      'where to put the bar when squatting',
      'is low bar squat better',
      'low bar squat hurts elbows',
      'przysiad z wysoką czy niską sztangą',
      'aukšta ar žema štangos padėtis pritūpime',
      'kõrge või madala kangiga kükk',
      'vysokyi chy nyzkyi hryf prysid',
    ],
    exUk: [
      'присід з високим чи низьким грифом',
      'де тримати гриф на спині при присіді',
      'низький гриф краще?',
      'лоу бар чи хай бар',
      'высокий или низкий гриф в приседе',
    ],
  },
  k_good_morning: {
    ex: [
      'goodmornings exercise with a barbell for hamstrings',
      'bending forward with the bar on my back exercise is it safe',
      'hinge with the bar on the back for spinal erectors',
      'czy skłony ze sztangą good morning są dobre',
      'ar good morning pratimas geras',
      'kas good morning harjutus on hea',
      'chy khorosha vprava hud mornin',
    ],
    exUk: [
      'чи хороша вправа гуд морнінг',
      'гуд морнінг техніка',
      'нахили зі штангою на плечах навіщо',
      'гуд морнінг безпечно для спини',
      'гуд морнинг упражнение',
    ],
  },
  k_farmer_carry: {
    ex: [
      'are farmers carries worth it',
      'farmers walk benefits',
      'how heavy for farmer carries',
      'suitcase carry core',
      'loaded carries what for',
      'czy spacer farmera jest dobry',
      'ar ūkininko ėjimas naudingas',
      'kas farmeri kõnd on kasulik',
      'prohulianka fermera navishcho',
    ],
    exUk: [
      'чи варто робити прогулянку фермера',
      'фермерська ходьба з гантелями навіщо',
      'перенесення ваги в одній руці',
      'яка вага для прогулянки фермера',
      'прогулка фермера польза',
    ],
  },
  k_calves: {
    ex: [
      'my calves wont grow',
      'calf raises not working',
      'stubborn calves',
      'seated or standing calf raise',
      'łydki nie rosną co robić',
      'blauzdos neauga ką daryti',
      'säärelihased ei kasva',
      'lytky ne rostut',
    ],
    exUk: [
      'литки не ростуть що робити',
      'підйоми на носки не допомагають',
      'литки стоячи чи сидячи',
      'икры не растут что делать',
    ],
  },
  k_trap_bar: {
    ex: [
      'is trap bar deadlift as good',
      'trap bar vs straight bar',
      'hex bar deadlift worth it',
      'trap bar deadlift for beginners',
      'hex bar deadlift easier on back',
      'martwy ciąg z trap bar czy klasyczny',
      'trap bar trauka ar klasikinė',
      'trap bar jõutõmme või tavaline',
      'trep hryf chy zvychaina stanova',
    ],
    exUk: [
      'чи трап гриф такий самий добрий як станова',
      'станова з трап-грифом чи звичайна',
      'шестикутний гриф для новачка',
      'трэп гриф легше для спини?',
      'трэп гриф или обычная становая',
    ],
  },
  k_nordic_curl: {
    ex: [
      'are nordic curls worth it',
      'nordic hamstring curl',
      'how to do nordic curls',
      'nordics hamstring injury prevention',
      'nordic curl progression',
      'czy warto robić nordic curls',
      'ar verta daryti nordic curls',
      'kas nordic curl on väärt',
      'nordychni zghynannia',
    ],
    exUk: [
      'чи варто робити нордичні згинання',
      'нордік керл як робити',
      'нордичні згинання профілактика травм',
      'нордики на задню поверхню стегна',
      'нордические сгибания',
    ],
  },
  k_pistol_squat: {
    ex: [
      'how to learn pistol squat',
      'pistol squat progression',
      'one leg squat how to',
      'cant do a pistol squat',
      'pistol squat balance',
      'jak nauczyć się przysiadu na jednej nodze pistolet',
      'kaip išmokti pistoleto pritūpimą',
      'kuidas õppida püstolkükki',
      'yak navchytysia pistoletyk',
    ],
    exUk: [
      'як навчитися присідати пістолетиком',
      'присід на одній нозі як навчитися',
      'не виходить пістолетик',
      'пістолет присідання прогресія',
      'как научиться приседать пистолетиком',
    ],
  },
  k_no_soreness: {
    ex: [
      'not sore anymore is my workout working',
      'no soreness after workout',
      'do i need to be sore to grow',
      'no doms does that mean no growth',
      'workout didnt make me sore',
      'nie mam zakwasów czy trening działa',
      'neskauda raumenų ar treniruotė veikia',
      'lihased ei valuta kas trenn töötab',
      'mene ne krepaturyt',
    ],
    exUk: [
      'мене більше не крепатурить тренування ще працює',
      'нема крепатури значить нема росту?',
      'після тренування нічого не болить це погано',
      'чи треба щоб мʼязи боліли для росту',
      'не болят мышцы после тренировки это нормально',
    ],
  },
  k_massage_gun: {
    ex: [
      'are massage guns worth it',
      'theragun worth the money',
      'massage gun for recovery',
      'percussion massager does it work',
      'how to use a massage gun',
      'czy pistolet do masażu jest wart',
      'ar masažinis pistoletas vertas',
      'kas massaažipüstol on väärt',
      'chy varto masazhnyi pistolet',
    ],
    exUk: [
      'чи варто купувати масажний пістолет',
      'перкусійний масажер працює',
      'масажний пістолет для відновлення',
      'як користуватися масажним пістолетом',
      'массажный пистолет стоит ли',
    ],
  },
  k_wearables: {
    ex: [
      'should i trust my hrv',
      'whoop recovery score accurate',
      'my watch says low recovery should i train',
      'garmin body battery low',
      'resting heart rate higher than usual',
      'oura readiness score',
      'czy ufać hrv z zegarka',
      'ar pasitikėti laikrodžio hrv',
      'kas usaldada kella hrv-d',
      'chy doviriaty hrv z hodynnyka',
    ],
    exUk: [
      'чи довіряти hrv з годинника',
      'годинник каже низьке відновлення тренуватись?',
      'пульс спокою вищий ніж зазвичай',
      'оцінка відновлення whoop точна?',
      'часы показывают низкое восстановление',
    ],
  },
  k_cns_fatigue: {
    ex: [
      'is cns fatigue real',
      'central nervous system fatigue from deadlifts',
      'my cns is fried',
      'how long does cns take to recover',
      'cns burnout lifting',
      'czy zmęczenie ośrodkowego układu nerwowego jest prawdziwe',
      'ar cns nuovargis tikras',
      'kas kesknärvisüsteemi väsimus on päris',
      'vtoma tsns isnuie',
    ],
    exUk: [
      'чи існує втома цнс',
      'цнс перевантажена після станової',
      'скільки відновлюється нервова система',
      'втома нервової системи від важких ваг',
      'усталость цнс это правда',
    ],
  },
  k_detraining: {
    ex: [
      'how fast do you lose muscle if you stop training',
      'will i lose gains in 2 weeks off',
      'how long before losing muscle',
      'muscle memory is it real',
      'how quickly does strength go away',
      'jak szybko traci się mięśnie bez treningu',
      'kaip greitai prarandami raumenys nesportuojant',
      'kui kiiresti kaovad lihased ilma trennita',
      'yak shvydko propadut miazy',
    ],
    exUk: [
      'як швидко я втрачу мʼязи якщо перестану тренуватися',
      'за 2 тижні без залу все піде?',
      'мʼязова памʼять існує',
      'як швидко падає сила без тренувань',
      'за сколько уходят мышцы без тренировок',
    ],
  },
  k_joint_supplements: {
    ex: [
      'do joint supplements work',
      'glucosamine for knees',
      'is collagen good for joints',
      'chondroitin worth it',
      'supplements for tendons',
      'czy glukozamina działa',
      'ar gliukozaminas veikia',
      'kas glükoosamiin töötab',
      'chy pratsiuie hliukozamin',
    ],
    exUk: [
      'чи працюють добавки для суглобів',
      'глюкозамін для колін',
      'колаген для звʼязок',
      'хондроїтин варто пити',
      'глюкозамин хондроитин работает?',
    ],
  },
  k_creatine_myths: {
    ex: [
      'does creatine cause hair loss',
      'creatine bloating',
      'is creatine bad for kidneys',
      'creatine water retention',
      'creatine makes me look puffy',
      'creatine side effects',
      'czy kreatyna powoduje wypadanie włosów',
      'ar kreatinas kenkia inkstams',
      'kas kreatiin põhjustab juuste väljalangemist',
      'chy vid kreatynu vypadaie volossia',
    ],
    exUk: [
      'чи креатин викликає випадіння волосся',
      'креатин шкодить ниркам',
      'від креатину набряки',
      'креатин затримує воду',
      'від креатину випадає волосся правда',
      'креатин выпадение волос',
    ],
  },
  k_protein_powder: {
    ex: [
      'which protein powder should i buy',
      'best protein powder',
      'whey concentrate or isolate',
      'plant protein powder any good',
      'what whey to buy',
      'jakie białko kupić',
      'kokį baltymų miltelius pirkti',
      'millist proteiinipulbrit osta',
      'yakyi protein kupyty',
    ],
    exUk: [
      'який протеїн купити',
      'концентрат чи ізолят сироватки',
      'рослинний протеїн нормальний',
      'який протеїн найкращий',
      'какой протеин купить',
    ],
  },
  k_protein_per_meal: {
    ex: [
      'how much protein can you absorb at once',
      'max protein per meal',
      'is 30g protein per meal limit true',
      'can body absorb 60g protein in one meal',
      'protein absorption per sitting',
      'ile białka przyswaja się w jednym posiłku',
      'kiek baltymų pasisavinama per vieną valgį',
      'kui palju valku imendub ühe söögikorraga',
      'skilky bilka zasvoiuietsia za raz',
    ],
    exUk: [
      'скільки білка засвоюється за один прийом їжі',
      'правда що більше 30 грам білка не засвоюється',
      'можна зʼїсти 60 г білка за раз',
      'скільки протеїну за раз засвоїться',
      'сколько белка усваивается за раз',
    ],
  },
  k_intra_workout: {
    ex: [
      'should i drink during my workout',
      'intra workout drink',
      'carbs during workout',
      'what to drink while training',
      'sports drink during lifting',
      'co pić podczas treningu',
      'ką gerti treniruotės metu',
      'mida trenni ajal juua',
      'shcho pyty pid chas trenuvannia',
    ],
    exUk: [
      'чи треба щось пити під час тренування',
      'що пити під час тренування',
      'вуглеводи під час тренування',
      'ізотонік під час залу',
      'что пить во время тренировки',
    ],
  },
  k_vitamin_d: {
    ex: [
      'should i take vitamin d',
      'vitamin d for lifters',
      'how much vitamin d per day',
      'vitamin d in winter',
      'does vitamin d increase testosterone',
      'czy brać witaminę d',
      'ar vartoti vitaminą d',
      'kas võtta d-vitamiini',
      'chy pryimaty vitamin d',
    ],
    exUk: [
      'чи варто приймати вітамін д',
      'скільки вітаміну d на день',
      'вітамін д взимку',
      'вітамін d для спортсменів',
      'витамин д пить?',
    ],
  },
  k_magnesium: {
    ex: [
      'does magnesium help sleep',
      'magnesium for cramps',
      'should i take magnesium',
      'magnesium glycinate or citrate',
      'zma worth it',
      'czy magnez pomaga na sen',
      'ar magnis padeda miegui',
      'kas magneesium aitab und',
      'chy dopomahaie mahnii',
    ],
    exUk: [
      'чи допомагає магній зі сном',
      'магній від судом',
      'магній гліцинат чи цитрат',
      'чи варто пити магній',
      'магний для сна',
    ],
  },
  k_test_boosters: {
    ex: [
      'do testosterone boosters work',
      'test booster worth it',
      'tribulus does it work',
      'ashwagandha for testosterone',
      'natural testosterone booster',
      'czy boostery testosteronu działają',
      'ar testosterono stiprikliai veikia',
      'kas testosterooni boosterid töötavad',
      'chy pratsiuiut bustery testosteronu',
    ],
    exUk: [
      'чи працюють бустери тестостерону',
      'трибулус працює',
      'ашваганда для тестостерону',
      'як підняти тестостерон добавками',
      'бустеры тестостерона работают?',
    ],
  },
  k_fat_burners: {
    ex: [
      'do fat burners work',
      'fat burner pills',
      'should i take a fat burner',
      'thermogenic supplements',
      'l carnitine for fat loss',
      'czy spalacze tłuszczu działają',
      'ar riebalų degintojai veikia',
      'kas rasvapõletajad töötavad',
      'chy pratsiuiut zhyrospaliuvachi',
    ],
    exUk: [
      'чи працюють жироспалювачі',
      'пігулки для спалювання жиру',
      'л карнітин для схуднення',
      'жиросжигатель пити чи ні',
      'жиросжигатели работают?',
    ],
  },
  k_reverse_diet: {
    ex: [
      'what is reverse dieting',
      'how to reverse diet after a cut',
      'what to eat after finishing a cut',
      'increase calories slowly after diet',
      'reverse diet worth it',
      'co to jest reverse diet',
      'kas yra atvirkštinė dieta',
      'mis on vastupidine dieet',
      'shcho take reversyvna dieta',
    ],
    exUk: [
      'що таке реверсивна дієта',
      'як виходити з сушки',
      'як піднімати калорії після дієти',
      'реверс дієта після сушки',
      'как выходить из сушки',
    ],
  },
  k_diet_break: {
    ex: [
      'should i take a diet break',
      'refeed day during cut',
      'what is a refeed',
      'diet break for metabolism',
      'maintenance break during a long cut',
      'czy robić przerwę w diecie',
      'ar daryti dietos pertrauką',
      'kas teha dieedipausi',
      'shcho take refid',
    ],
    exUk: [
      'чи робити перерву в дієті',
      'що таке рефід',
      'рефід на сушці',
      'перерва в дієті для метаболізму',
      'рефид на сушке нужен?',
    ],
  },
  k_scale_fluctuations: {
    ex: [
      'why does my weight fluctuate every day',
      'gained 2 kg overnight',
      'weight up after a cheat meal',
      'scale weight jumps',
      'why am i heavier in the evening',
      'dlaczego waga skacze codziennie',
      'kodėl svoris kasdien šokinėja',
      'miks kaal iga päev kõigub',
      'chomu vaha shchodnia skache',
    ],
    exUk: [
      'чому моя вага щодня скаче',
      'за ніч плюс 2 кг',
      'вага стрибає вгору вниз',
      'чому зранку і ввечері різна вага',
      'почему вес скачет каждый день',
    ],
  },
  k_keto: {
    ex: [
      'is keto good for lifting',
      'keto and building muscle',
      'low carb diet for gym',
      'keto flu training',
      'can you bulk on keto',
      'czy keto jest dobre dla siłowni',
      'ar keto dieta tinka sporto salei',
      'kas keto sobib jõusaaliks',
      'keto i trenuvannia',
    ],
    exUk: [
      'чи підходить кето для силових тренувань',
      'кето дієта і набір мʼязів',
      'низьковуглеводна дієта для залу',
      'можна набирати масу на кето',
      'кето и качалка',
    ],
  },
  k_intermittent_fasting: {
    ex: [
      'is intermittent fasting good for muscle',
      'intermittent fasting and lifting',
      '16:8 fasting while bulking',
      'can you build muscle with if',
      'intermittent fasting gym',
      'post przerywany a budowa mięśni',
      'protarpinis badavimas ir raumenys',
      'vahelduv paastumine ja lihased',
      'intervalne holoduvannia i masa',
    ],
    exUk: [
      'чи підходить інтервальне голодування для набору мʼязів',
      'голодування 16 8 і тренування',
      'інтервальне голодування і зал',
      'можна набрати мʼязи на if',
      'интервальное голодание и массанабор',
    ],
  },
  k_teen_supplements: {
    ex: [
      'should a teenager take protein',
      'can a 15 year old take creatine',
      'supplements for teens gym',
      'is whey safe for teenagers',
      'im 16 should i take creatine',
      'czy nastolatek może brać kreatynę',
      'ar paauglys gali vartoti kreatiną',
      'kas teismeline võib kreatiini võtta',
      'chy mozhna pidlitku kreatyn',
    ],
    exUk: [
      'чи варто підлітку приймати протеїн',
      'мені 15 можна креатин',
      'добавки для підлітка в зал',
      'протеїн у 16 років шкідливо?',
      'можно ли подростку креатин',
    ],
  },
  k_vo2max: {
    ex: [
      'how to improve vo2max',
      'what is vo2 max',
      'increase vo2max training',
      'norwegian 4x4 intervals',
      'vo2max low on my watch',
      'jak poprawić vo2max',
      'kaip pagerinti vo2max',
      'kuidas parandada vo2maxi',
      'yak pokrashchyty vo2max',
    ],
    exUk: [
      'як покращити vo2max',
      'що таке максимальне споживання кисню',
      'інтервали 4 на 4 для vo2max',
      'годинник показує низький vo2max',
      'как повысить мпк',
    ],
  },
  k_incline_walk: {
    ex: [
      'is incline walking good cardio',
      '12 3 30 workout',
      'treadmill incline walk for fat loss',
      'incline walking vs running',
      'stairmaster good cardio',
      'czy chodzenie pod górę na bieżni jest dobre',
      'ar ėjimas takeliu į kalną geras kardio',
      'kas kaldega kõndimine on hea kardio',
      'khodba pid nakhylom na dorizhtsi',
    ],
    exUk: [
      'ходьба на доріжці під нахилом це хороше кардіо',
      '12 3 30 тренування',
      'похила ходьба для схуднення',
      'степер чи доріжка під нахилом',
      'ходьба в горку на дорожке',
    ],
  },
  k_rowing_machine: {
    ex: [
      'how to use a rowing machine',
      'rowing machine technique',
      'rower damper setting',
      'is the rowing machine good cardio',
      'concept2 rowing form',
      'jak wiosłować na ergometrze',
      'kaip taisyklingai irkluoti treniruoklyje',
      'kuidas sõudeergomeetril õigesti sõuda',
      'yak hrebty na trenazheri',
    ],
    exUk: [
      'як правильно гребти на гребному тренажері',
      'гребний тренажер техніка',
      'демпфер на гребному тренажері',
      'гребля в залі як правильно',
      'гребной тренажер техника',
    ],
  },
  k_jump_rope: {
    ex: [
      'is jump rope good cardio',
      'skipping rope workout',
      'jumping rope for fat loss',
      'how long to jump rope',
      'jump rope shin pain',
      'czy skakanka to dobre cardio',
      'ar šokdynė geras kardio',
      'kas hüppenöör on hea kardio',
      'chy dobra skakalka',
    ],
    exUk: [
      'чи хороше кардіо скакалка',
      'скільки стрибати на скакалці',
      'скакалка для схуднення',
      'від скакалки болять гомілки',
      'скакалка хорошее кардио?',
    ],
  },
  k_thoracic: {
    ex: [
      'how to improve thoracic mobility',
      'upper back stiff',
      't spine mobility drills',
      'thoracic extension foam roller',
      'stiff upper back overhead press',
      'jak poprawić mobilność odcinka piersiowego',
      'kaip pagerinti krūtinės ląstos stuburo paslankumą',
      'kuidas parandada rindkere liikuvust',
      'rukhlyvist hrudnoho viddilu',
    ],
    exUk: [
      'як покращити рухливість грудного відділу',
      'скутий верх спини',
      'грудний відділ не гнеться',
      'вправи на рухливість грудного відділу',
      'подвижность грудного отдела',
    ],
  },
  k_hip_flexors: {
    ex: [
      'how to fix tight hip flexors',
      'hip flexor stretch',
      'tight hips from sitting',
      'front of hip tight',
      'psoas tight',
      'jak rozciągnąć zginacze bioder',
      'kaip ištempti klubo lenkiamuosius',
      'kuidas venitada puusapainutajaid',
      'zatysnuti zhynachi stehna',
    ],
    exUk: [
      'що робити із затиснутими згиначами стегна',
      'затиснутий псоас',
      'розтяжка згиначів стегна',
      'від сидіння затиснуті стегна',
      'забитые сгибатели бедра',
    ],
  },
  k_hamstring_flex: {
    ex: [
      'tight hamstrings cant touch toes',
      'how to touch my toes',
      'hamstring flexibility',
      'how to stretch hamstrings',
      'improve forward fold',
      'nie mogę dotknąć palców u stóp',
      'negaliu pasiekti kojų pirštų',
      'ei ulatu varvasteni',
      'ne distaiu do paltsiv nih',
    ],
    exUk: [
      'затиснуті задні мʼязи стегна не дістаю до пальців',
      'як дістати руками до підлоги',
      'розтяжка задньої поверхні стегна',
      'гнучкість біцепса стегна',
      'не достаю до пальцев ног',
    ],
  },
  k_shoulder_warmup: {
    ex: [
      'how to warm up shoulders before bench',
      'shoulder warm up routine',
      'warm up before overhead press',
      'band pull aparts warm up',
      'shoulder prep for pressing',
      'jak rozgrzać barki przed wyciskaniem',
      'pečių paruošimas prieš spaudimą virš galvos',
      'kuidas õlgu enne surumist soojendada',
      'yak rozimiaty plechi',
    ],
    exUk: [
      'як розімʼяти плечі перед жимом',
      'розминка плечей перед жимом лежачи',
      'розминка для плечових суглобів',
      'що робити з резинкою перед жимом',
      'разминка плеч перед жимом',
    ],
  },
  k_wrist_mobility: {
    ex: [
      'my wrists hurt on bench',
      'wrist pain front squat',
      'wrist pain push ups',
      'how to improve wrist mobility',
      'wrists bend back when pressing',
      'bolą nadgarstki przy wyciskaniu',
      'skauda riešus spaudime',
      'randmed valutavad surumisel',
      'boliat zapiastia na zhymi',
    ],
    exUk: [
      'болять запʼястя на жимі',
      'болять запʼястя у фронтальних присіданнях',
      'болять кисті від віджимань',
      'рухливість запʼясть',
      'болят запястья при жиме',
    ],
  },
  k_yoga: {
    ex: [
      'is yoga good for lifters',
      'yoga and weightlifting',
      'should i do yoga on rest days',
      'hot yoga before leg day',
      'yoga for bodybuilders',
      'czy joga jest dobra dla ćwiczących siłowo',
      'ar joga naudinga sportuojantiems su svoriais',
      'kas jooga sobib jõutreenijale',
      'chy korysna yoha',
    ],
    exUk: [
      'чи корисна йога для тих хто тягає залізо',
      'йога і силові',
      'йога в дні відпочинку',
      'йога замість розтяжки',
      'йога для качков',
    ],
  },
  k_pilates: {
    ex: [
      'is pilates good with lifting',
      'pilates vs weights',
      'reformer pilates and gym',
      'can pilates replace strength training',
      'pilates for core',
      'czy pilates jest dobry razem z siłownią',
      'ar pilatesas tinka kartu su svoriais',
      'kas pilates sobib jõusaaliga',
      'pilates i sylovi',
    ],
    exUk: [
      'чи корисний пілатес разом із силовими',
      'пілатес чи зал',
      'реформер пілатес і силові',
      'пілатес замінить силові?',
      'пилатес и качалка',
    ],
  },
  k_gloves: {
    ex: [
      'should i wear gym gloves',
      'lifting gloves worth it',
      'gloves for calluses',
      'are gloves bad for grip',
      'weightlifting gloves',
      'czy ćwiczyć w rękawiczkach',
      'ar treniruotis su pirštinėmis',
      'kas trennida kinnastega',
      'chy trenuvatys v rukavychkakh',
    ],
    exUk: [
      'чи варто тренуватися в рукавичках',
      'рукавички для залу потрібні',
      'рукавички від мозолів',
      'рукавиці заважають хвату?',
      'перчатки для зала нужны?',
    ],
  },
  k_bar_weight: {
    ex: [
      'how much does the barbell weigh',
      'olympic bar weight',
      'how heavy is the empty bar',
      'ez bar weight',
      'womens barbell weight',
      'ile waży gryf',
      'kiek sveria štanga be svorių',
      'kui palju kang kaalub',
      'skilky vazhyt hryf',
    ],
    exUk: [
      'скільки важить гриф штанги',
      'вага олімпійського грифа',
      'скільки важить пустий гриф',
      'скільки важить ez гриф',
      'сколько весит гриф',
    ],
  },
  k_weight_vest: {
    ex: [
      'is a weighted vest worth it',
      'weighted vest training',
      'walking with a weight vest',
      'pull ups with weighted vest',
      'how heavy weighted vest',
      'czy warto ćwiczyć w kamizelce obciążeniowej',
      'ar verta sportuoti su svorine liemene',
      'kas raskusvest on väärt',
      'zhylet z obvazhennyam',
    ],
    exUk: [
      'чи варто тренуватися з обважнювальним жилетом',
      'жилет з обважненням для ходьби',
      'підтягування з жилетом',
      'яку вагу жилета брати',
      'утяжелительный жилет стоит ли',
    ],
  },
  k_spotting_others: {
    ex: [
      'how do i spot my friend on bench press',
      'what does a good spotter do',
      'spotting technique squat',
      'someone asked me to spot them',
      'how to be a good spotter',
      'jak asekurować kogoś przy wyciskaniu',
      'kaip apdrausti kitą spaudime gulint',
      'kuidas kedagi lamades surumisel julgestada',
      'yak strakhuvaty koho na zhymi',
    ],
    exUk: [
      'як правильно страхувати когось на жимі лежачи',
      'мене попросили пострахувати',
      'як страхувати в присіданнях',
      'як бути хорошим страхувальником',
      'как страховать на жиме',
    ],
  },
  k_busy_gym: {
    ex: [
      'gym is packed what do i do',
      'the squat rack is taken',
      'equipment always busy at my gym',
      'can i ask to work in',
      'crowded gym tips',
      'siłownia jest pełna co robić',
      'sporto salė perpildyta ką daryti',
      'jõusaal on rahvast täis mida teha',
      'zal perepovnenyi shcho robyty',
    ],
    exUk: [
      'зал переповнений і тренажер зайнятий що робити',
      'рама зайнята а мені присідати',
      'в залі завжди людно',
      'можна попроситися працювати по черзі',
      'в зале толпа что делать',
    ],
  },
  k_gym_bag: {
    ex: [
      'what should i bring to the gym',
      'what to pack in gym bag',
      'gym bag essentials',
      'what do i need for my first day at the gym',
      'what to take to the gym',
      'co zabrać na siłownię',
      'ką pasiimti į sporto salę',
      'mida jõusaali kaasa võtta',
      'shcho braty v zal',
    ],
    exUk: [
      'що брати з собою в зал',
      'що покласти в спортивну сумку',
      'що потрібно на перше тренування',
      'що взяти в спортзал',
      'что брать в зал',
    ],
  },
  k_film_form: {
    ex: [
      'how to film myself lifting',
      'best angle to film squat',
      'filming for form check',
      'where to put my phone to record deadlift',
      'record my lifts to check technique',
      'jak nagrywać się na siłowni',
      'kaip filmuoti save sporto salėje',
      'kuidas end jõusaalis filmida',
      'yak znimaty sebe v zali',
    ],
    exUk: [
      'як знімати себе щоб перевірити техніку',
      'з якого ракурсу знімати присід',
      'куди ставити телефон щоб зняти станову',
      'записати відео техніки',
      'как снимать себя в зале',
    ],
  },
  k_calisthenics: {
    ex: [
      'how to progress bodyweight exercises',
      'calisthenics progression',
      'make push ups harder',
      'bodyweight workout getting too easy',
      'how to build muscle with bodyweight only',
      'jak progresować w ćwiczeniach z masą ciała',
      'kaip progresuoti pratimuose su savo svoriu',
      'kuidas kehakaaluharjutustes progresseeruda',
      'yak prohresuvaty z vlasnoiu vahoiu',
    ],
    exUk: [
      'як прогресувати у вправах з власною вагою',
      'калістеніка прогресія',
      'віджимання стали легкими що далі',
      'як ускладнити вправи без ваги',
      'как прогрессировать с собственным весом',
    ],
  },
  k_menopause: {
    ex: [
      'how should i train during menopause',
      'lifting in menopause',
      'perimenopause strength training',
      'menopause weight gain gym',
      'training after menopause',
      'jak trenować w menopauzie',
      'kaip sportuoti menopauzės metu',
      'kuidas treenida menopausis',
      'yak trenuvatysia v menopauzi',
    ],
    exUk: [
      'як тренуватися в менопаузі',
      'силові в клімаксі',
      'менопауза і зал',
      'перименопауза тренування',
      'как тренироваться при климаксе',
    ],
  },
  k_postpartum: {
    ex: [
      'when can i lift after giving birth',
      'postpartum workout',
      'returning to gym after baby',
      'exercise after c section',
      'diastasis recti training',
      'kiedy wrócić na siłownię po porodzie',
      'kada grįžti į sporto salę po gimdymo',
      'millal pärast sünnitust trenni teha',
      'koly mozhna trenuvatysia pislia polohiv',
    ],
    exUk: [
      'коли можна повернутися до тренувань після пологів',
      'тренування після кесаревого',
      'діастаз після пологів вправи',
      'повернення в зал після народження дитини',
      'когда можно в зал после родов',
    ],
  },
  k_pelvic_floor: {
    ex: [
      'i leak when i lift',
      'leaking when jumping',
      'pelvic floor and heavy lifting',
      'bladder leak during squats',
      'peeing a little during double unders',
      'popuszczam moczu przy ćwiczeniach',
      'šlapimo nelaikymas treniruojantis',
      'uriinipidamatus treeningul',
      'pidtikaie pid chas vprav',
    ],
    exUk: [
      'у мене трохи підтікає під час вправ',
      'тазове дно і важкі ваги',
      'підтікання сечі при стрибках',
      'нетримання під час присідань',
      'подтекает при прыжках',
    ],
  },
  k_osteoporosis: {
    ex: [
      'is lifting safe with osteoporosis',
      'weight training for low bone density',
      'osteopenia exercise',
      'can lifting increase bone density',
      'strength training for bones',
      'czy siłownia jest bezpieczna przy osteoporozie',
      'ar saugu sportuoti sergant osteoporoze',
      'kas jõutreening on osteoporoosi korral ohutu',
      'sylovi pry osteoporozi',
    ],
    exUk: [
      'чи безпечні силові при остеопорозі',
      'низька щільність кісток і зал',
      'остеопенія які вправи',
      'силові для кісток',
      'остеопороз и тренировки',
    ],
  },
  k_arthritis: {
    ex: [
      'can i lift with arthritis',
      'osteoarthritis knee weight training',
      'strength training for arthritis',
      'arthritic hips gym',
      'lifting with rheumatoid arthritis',
      'czy mogę ćwiczyć z artrozą',
      'ar galiu sportuoti sergant artritu',
      'kas artroosiga võib jõusaalis käia',
      'chy mozhna sylovi pry artrozi',
    ],
    exUk: [
      'чи можна займатися силовими при артрозі',
      'артроз коліна і зал',
      'артрит і тренування з вагою',
      'гонартроз присідання можна',
      'артроз можно ли в зал',
    ],
  },
  k_habit: {
    ex: [
      'how do i make the gym a habit',
      'how to be consistent with the gym',
      'how to stick to working out',
      'i always quit the gym after a month',
      'build a workout routine that lasts',
      'jak zrobić z siłowni nawyk',
      'kaip sporto salę paversti įpročiu',
      'kuidas teha jõusaalist harjumus',
      'yak zrobyty zal zvychkoiu',
    ],
    exUk: [
      'як зробити спортзал звичкою',
      'як не кидати зал',
      'завжди кидаю тренування через місяць',
      'як тренуватися регулярно',
      'как сделать спорт привычкой',
    ],
  },
  k_program_boredom: {
    ex: [
      'im bored of my workouts',
      'workouts feel boring',
      'same routine every week boring',
      'should i change my program because im bored',
      'how to make training fun again',
      'nudzą mnie treningi',
      'man nusibodo treniruotės',
      'trennid on igavaks muutunud',
      'nabrydly trenuvannia',
    ],
    exUk: [
      'мені набридли тренування змінити все',
      'нудно тренуватися одне й те саме',
      'тренування стали нудними',
      'як зробити тренування цікавішими',
      'надоели тренировки',
    ],
  },
  k_comparison: {
    ex: [
      'i keep comparing myself to others at the gym',
      'everyone at the gym is bigger than me',
      'instagram makes me feel small',
      'comparing my body to fitness influencers',
      'feel weak compared to other guys',
      'porównuję się z innymi na siłowni',
      'lyginu save su kitais sporto salėje',
      'võrdlen end jõusaalis teistega',
      'porivniuiu sebe z inshymy',
    ],
    exUk: [
      'я постійно порівнюю себе з іншими в залі',
      'всі в залі більші за мене',
      'інстаграм фітнес блогери а я',
      'почуваюсь слабким порівняно з іншими',
      'сравниваю себя с другими в зале',
    ],
  },
  k_psych_up: {
    ex: [
      'how to get mentally ready for a heavy lift',
      'how to psych up for a max',
      'mental preparation before heavy squat',
      'visualization lifting',
      'how to focus before a heavy set',
      'jak się nastawić psychicznie na ciężką serię',
      'kaip psichologiškai pasiruošti sunkiam kėlimui',
      'kuidas end raskeks tõsteks vaimselt valmis panna',
      'yak nalashtuvatysia na vazhkyi pidkhid',
    ],
    exUk: [
      'як психологічно налаштуватися на важкий підхід',
      'як завестися перед максимумом',
      'ментальна підготовка до рекорду',
      'як зосередитися перед важким підходом',
      'как настроиться на тяжелый подход',
    ],
  },
  k_fear_heavy: {
    ex: [
      'im scared of heavy weights',
      'afraid to go heavy on squats',
      'fear of getting stuck under the bar',
      'scared of failing a rep',
      'how to stop being afraid of lifting heavy',
      'boję się dużych ciężarów',
      'bijau didelių svorių',
      'kardan raskeid raskusi',
      'boiusia vazhkykh vah',
    ],
    exUk: [
      'я боюся важких ваг',
      'страшно брати велику вагу на присід',
      'боюся застрягти під штангою',
      'страх провалити повтор',
      'боюсь больших весов',
    ],
  },
  k_dance: {
    ex: [
      'i dance how do i combine it with lifting',
      'strength training for dancers',
      'lifting and ballet',
      'dance classes and gym same week',
      'will lifting make me a worse dancer',
      'tańczę jak połączyć to z siłownią',
      'šoku kaip suderinti su sporto sale',
      'tantsin kuidas seda jõusaaliga ühendada',
      'ya tantsiuiu yak poiednaty z zalom',
    ],
    exUk: [
      'я танцюю як поєднати це з силовими',
      'силові для танцюристів',
      'танці і зал в один тиждень',
      'балет і тренажерний зал',
      'танцую как совмещать с залом',
    ],
  },
  k_progress_photos: {
    ex: [
      'how to take progress photos',
      'progress pictures tips',
      'best lighting for progress pics',
      'how often to take progress photos',
      'before and after photos gym',
      'jak robić zdjęcia postępów',
      'kaip daryti progreso nuotraukas',
      'kuidas teha progressipilte',
      'yak robyty foto prohresu',
    ],
    exUk: [
      'як правильно робити фото прогресу',
      'фото до і після як знімати',
      'як часто фотографувати прогрес',
      'яке світло для фото прогресу',
      'как делать фото прогресса',
    ],
  },
  k_measurements: {
    ex: [
      'what body measurements should i track',
      'how to measure my waist',
      'tape measure progress',
      'where to measure arms',
      'body measurements for bulking',
      'jakie pomiary ciała robić',
      'kokius kūno matmenis sekti',
      'milliseid kehamõõte jälgida',
      'yaki zamiry tila robyty',
    ],
    exUk: [
      'які заміри тіла варто відстежувати',
      'як міряти талію',
      'заміри сантиметром прогрес',
      'де міряти обхват руки',
      'какие замеры тела делать',
    ],
  },
  k_body_fat: {
    ex: [
      'how to measure body fat percentage',
      'smart scale body fat accurate',
      'dexa scan worth it',
      'calipers body fat',
      'what body fat percentage am i',
      'jak zmierzyć procent tkanki tłuszczowej',
      'kaip išmatuoti riebalų procentą',
      'kuidas mõõta keharasva protsenti',
      'yak vymiriaty vidsotok zhyru',
    ],
    exUk: [
      'як виміряти відсоток жиру в тілі',
      'розумні ваги показують жир точно?',
      'калипер для заміру жиру',
      'який в мене відсоток жиру',
      'как измерить процент жира',
    ],
  },
  k_bmi: {
    ex: [
      'is bmi accurate for lifters',
      'bmi says im overweight but im muscular',
      'bmi for bodybuilders',
      'does bmi matter if i lift',
      'body mass index muscle',
      'czy bmi jest dokładne dla ćwiczących',
      'ar kmi tikslus sportuojantiems',
      'kas kmi on jõutreenijale täpne',
      'chy tochnyi imt',
    ],
    exUk: [
      'чи точний імт для тих хто тренується',
      'індекс маси тіла каже що в мене надмірна вага',
      'імт і мʼязи',
      'bmi для спортсменів',
      'имт для спортсменов',
    ],
  },
  k_recomp: {
    ex: [
      'can i lose fat and build muscle at the same time',
      'body recomposition',
      'recomp or bulk',
      'skinny fat what should i do',
      'lose fat gain muscle simultaneously',
      'czy można jednocześnie spalać tłuszcz i budować mięśnie',
      'ar galima kartu deginti riebalus ir auginti raumenis',
      'kas saab samal ajal rasva kaotada ja lihaseid kasvatada',
      'rekompozytsiia tila',
    ],
    exUk: [
      'чи можна одночасно скидати жир і набирати мʼязи',
      'рекомпозиція тіла',
      'худий але з жирком що робити',
      'рекомп чи набір',
      'можно ли одновременно худеть и набирать мышцы',
    ],
  },
  k_mini_cut: {
    ex: [
      'what is a mini cut',
      'how long should a mini cut be',
      'mini cut during bulk',
      'short aggressive cut',
      '4 week cut',
      'co to jest mini redukcja',
      'kas yra mini dieta',
      'mis on minikuivatus',
      'shcho take mini sushka',
    ],
    exUk: [
      'що таке міні сушка',
      'скільки має тривати міні сушка',
      'коротка сушка посеред набору',
      'міні кат',
      'что такое мини сушка',
    ],
  },
  k_climbing: {
    ex: [
      'how to combine climbing with lifting',
      'bouldering and weight training',
      'gym for climbers',
      'lifting on climbing rest days',
      'strength training for rock climbing',
      'jak łączyć wspinaczkę z siłownią',
      'kaip suderinti laipiojimą su sporto sale',
      'kuidas ühendada ronimist jõusaaliga',
      'skelelazinnia i zal',
    ],
    exUk: [
      'як поєднати скелелазіння з силовими',
      'боулдерінг і зал',
      'силові для скелелаза',
      'лазіння і тренажерний зал',
      'скалолазание и качалка',
    ],
  },
  k_muscle_fibers: {
    ex: [
      'fast twitch vs slow twitch',
      'what are fast twitch fibers',
      'type 1 and type 2 muscle fibers',
      'how to train fast twitch muscle',
      'slow twitch fibers high reps',
      'włókna szybkokurczliwe i wolnokurczliwe',
      'greitosios ir lėtosios raumenų skaidulos',
      'kiired ja aeglased lihaskiud',
      'shvydki i povilni volokna',
    ],
    exUk: [
      'що таке швидкі й повільні мʼязові волокна',
      'швидкі волокна як тренувати',
      'волокна 1 і 2 типу',
      'повільні волокна багато повторів',
      'быстрые и медленные волокна',
    ],
  },
  k_rotator_cuff: {
    ex: [
      'what is the rotator cuff',
      'should i train my rotator cuff',
      'rotator cuff exercises',
      'external rotation exercise',
      'rotator cuff prehab',
      'co to jest stożek rotatorów',
      'kas yra rotatorių manžetė',
      'mis on rotaatormansett',
      'shcho take rotatorna manzheta',
    ],
    exUk: [
      'що таке ротаторна манжета',
      'чи треба тренувати ротатори плеча',
      'вправи на ротаторну манжету',
      'зовнішня ротація плеча вправа',
      'вращательная манжета плеча упражнения',
    ],
  },
  k_delt_heads: {
    ex: [
      'how to train all three heads of the shoulders',
      'front side rear delts',
      'rear delt exercises',
      'three deltoid heads',
      'do i need front raises',
      'jak trenować wszystkie trzy aktony barków',
      'kaip treniruoti visas tris deltos galvas',
      'kuidas treenida kõiki kolme deltalihase osa',
      'yak trenuvaty tri puchky delt',
    ],
    exUk: [
      'як тренувати всі три пучки дельт',
      'передні середні задні дельти',
      'вправи на задню дельту',
      'чи треба окремо передню дельту',
      'три пучка дельт',
    ],
  },
  k_ego_lifting: {
    ex: [
      'what is ego lifting',
      'am i ego lifting',
      'ego lifting bad',
      'lifting too heavy with bad form',
      'swinging weights to lift more',
      'co to jest ego lifting',
      'kas yra ego kilnojimas',
      'mis on ego tõstmine',
      'shcho take eho liftynh',
    ],
    exUk: [
      'що таке его ліфтинг',
      'беру завелику вагу з поганою технікою',
      'чим поганий его ліфтинг',
      'розгойдуюсь щоб підняти більше',
      'что такое эго лифтинг',
    ],
  },
  k_skip_legs: {
    ex: [
      'do i really need to train legs',
      'is it ok to skip leg day',
      'why train legs',
      'can i just train upper body',
      'never train legs what happens',
      'czy muszę trenować nogi',
      'ar būtina treniruoti kojas',
      'kas jalgu on vaja treenida',
      'chy treba trenuvaty nohy',
    ],
    exUk: [
      'чи справді треба тренувати ноги',
      'можна не качати ноги',
      'навіщо тренувати ноги',
      'тільки верх тіла тренувати можна',
      'можно не качать ноги',
    ],
  },
  k_nausea: {
    ex: [
      'why do i feel sick during hard workouts',
      'nausea during workout',
      'feel like throwing up after leg day',
      'want to puke after squats',
      'nauseous after hiit',
      'mdli mnie podczas treningu',
      'pykina treniruotės metu',
      'treeningu ajal on iiveldus',
      'nudyt pid chas trenuvannia',
    ],
    exUk: [
      'чому мене нудить під час важких тренувань',
      'нудить після дня ніг',
      'хочеться блювати після присідань',
      'нудота на тренуванні',
      'тошнит на тренировке',
    ],
  },
  k_shaking: {
    ex: [
      'why do my muscles shake during a set',
      'legs shaking during squats',
      'arms shake when benching',
      'trembling muscles when lifting',
      'shaky on the last reps',
      'dlaczego mięśnie drżą podczas serii',
      'kodėl raumenys dreba serijos metu',
      'miks lihased seeria ajal värisevad',
      'chomu tremtiat miazy',
    ],
    exUk: [
      'чому мʼязи тремтять під час підходу',
      'ноги трусяться на присіданнях',
      'руки дрижать на жимі',
      'тремтіння в мʼязах на останніх повторах',
      'почему трясутся мышцы при подходе',
    ],
  },
  k_joint_clicking: {
    ex: [
      'my joints click when i lift',
      'knees crack when squatting',
      'shoulder popping on bench',
      'joint cracking no pain',
      'clicking hip during exercises',
      'strzelają mi stawy przy ćwiczeniach',
      'spragsi sąnariai treniruojantis',
      'liigesed naksuvad treenides',
      'khrustiat suhloby',
    ],
    exUk: [
      'суглоби клацають і хрустять коли тренуюся',
      'хрустять коліна при присіданнях',
      'клацає плече на жимі',
      'хруст у суглобах без болю',
      'хрустят суставы при приседаниях',
    ],
  },
  k_stretch_marks: {
    ex: [
      'will i get stretch marks from bulking',
      'stretch marks on shoulders from gym',
      'how to avoid stretch marks when gaining muscle',
      'stretch marks chest bulk',
      'do stretch marks go away',
      'rozstępy od budowania masy',
      'tempimo žymės ant odos nuo masės auginimo',
      'venitusarmid massikasvatusest',
      'roztiazhky vid naboru masy',
    ],
    exUk: [
      'чи зʼявляться розтяжки від набору маси',
      'розтяжки на плечах від залу',
      'як уникнути розтяжок при наборі',
      'розтяжки на грудях від масонабору',
      'растяжки от набора массы',
    ],
  },
};
