/**
 * A second round of phrasings for the topics of topicsMore.ts (part A: programming,
 * lifts, recovery, supplements) — more wording, slang, typos and languages.
 */
export const MORE_TOPICS_EX2A: Record<string, { ex: string[]; exUk: string[] }> = {
  k_amrap: {
    ex: [
      'amrap set how many reps left in the tank',
      'my plan has a plus set, what does the + mean',
      'last set as many as i can, is that safe on squats',
      'amrap on deadlift good idea',
      'how do i use amrap to see if i got stronger',
      'max reps set at the end what is it for',
      'amrap sets to failure or not',
      'seria na maksymalną liczbę powtórzeń co to',
      'amrap do upadku czy nie',
      'maksimalus pakartojimų skaičius serijoje',
      'amrap iki nesėkmės ar ne',
      'maksimaalne korduste arv seerias mis see on',
      'amrap kuni läbikukkumiseni',
      'amrap pidkhid do vidmovy',
    ],
    exUk: [
      'підхід на максимум повторів навіщо',
      'в програмі плюс сет що це',
      'амрап на присіданнях безпечно',
      'останній підхід на скільки зможу це амрап',
      'амрап до відказу чи ні',
      'подход на максимум повторений зачем',
    ],
  },
  k_emom: {
    ex: [
      'emom 10 minutes 3 reps meaning',
      'every minute do a set and rest the rest of the minute',
      'emom pull ups good for getting more reps',
      'what weight for an emom squat',
      'emom vs amrap workout',
      'on the minute training for conditioning',
      'emom trening co minutę',
      'jak dobrać ciężar do emom',
      'emom kas minutę treniruotė',
      'emom treening iga minuti alguses',
      'emom kerge või raske kaal',
      'emom trenuvannia shcho tse',
    ],
    exUk: [
      'емом 10 хвилин по 3 повтори що це',
      'кожну хвилину підхід а решту відпочинок',
      'емом підтягування щоб більше підтягуватись',
      'яку вагу брати на емом',
      'емом чи амрап',
      'емом тренировка что значит',
    ],
  },
  k_cluster_sets: {
    ex: [
      'break a set into mini sets with short rest between',
      'cluster sets for strength gains',
      'clusters 5 x 2 with 20 seconds rest',
      'intra set rest what is that',
      'do clusters help with heavy triples',
      'cluster training powerlifting',
      'serie klastrowe na siłę',
      'przerwy w serii kilkanaście sekund',
      'klasteriai jėgai',
      'klastriseeriad jõu jaoks',
      'klasterni pidkhody dlia syly',
    ],
    exUk: [
      'розбити підхід на міні підходи з паузою',
      'кластери для сили',
      'кластери 5 по 2 з відпочинком 20 секунд',
      'відпочинок всередині підходу що це',
      'кластерные подходы для силы',
    ],
  },
  k_rest_pause: {
    ex: [
      'rest pause training explained',
      'go to failure rest 15 seconds and keep going',
      'rest pause on machines good idea',
      'is rest pause good for arms',
      'rest pause vs drop sets',
      'rest pause on squats dangerous',
      'rest pause jak robić',
      'rest pause czy drop set',
      'rest pause kaip atlikti',
      'rest pause kuidas teha',
      'rest pauza yak robyty',
    ],
    exUk: [
      'до відмови 15 секунд пауза і ще повтори',
      'рест пауза на тренажерах',
      'рест пауза на руки працює',
      'рест пауза проти дроп сетів',
      'рест-пауза на присіданнях небезпечно',
      'рест пауза как делать',
    ],
  },
  k_myo_reps: {
    ex: [
      'myo reps on lateral raises',
      'activation set then mini sets of 3 to 5',
      'myo reps save time in the gym',
      'myo reps vs rest pause difference',
      'myo reps for hypertrophy',
      'breathe 5 times then do more reps',
      'myo reps na bicepsie',
      'myo powtórzenia jak robić',
      'myo pakartojimai hipertrofijai',
      'myo kordused kuidas teha',
      'mio povtory na biceps',
    ],
    exUk: [
      'міо повтори на махах',
      'активаційний підхід потім міні підходи по 3-5',
      'міо повтори економлять час',
      'міо репс проти рест паузи',
      'мио повторы для массы',
    ],
  },
  k_double_progression: {
    ex: [
      'when do i add weight on dumbbell curls if i use 8-12 reps',
      'hit the top of the rep range then go heavier',
      'progress reps first then weight',
      'how to progress on machines with big weight jumps',
      'rep range progression method',
      'double progression for beginners',
      'progresja powtórzeń potem ciężaru',
      'kiedy zwiększyć ciężar hantli',
      'pirma kartojimai paskui svoris',
      'kõigepealt kordused siis raskus',
      'spochatku povtory potim vaha',
    ],
    exUk: [
      'коли додавати вагу на гантелях якщо діапазон 8-12',
      'дійшов до верху діапазону повторів що далі',
      'спершу повтори потім вага',
      'як прогресувати в тренажерах з великим кроком ваги',
      'сначала повторы потом вес',
    ],
  },
  k_taper: {
    ex: [
      'deload before a meet or taper',
      'peak for a 1rm test',
      'how many days rest before a max attempt',
      'last week before competition training',
      'tapering for powerlifting meet',
      'how to peak strength',
      'ostatni tydzień przed zawodami trening',
      'jak zrobić peaking',
      'paskutinė savaitė prieš varžybas',
      'viimane nädal enne võistlust',
      'ostannii tyzhden pered zmahanniamy',
    ],
    exUk: [
      'останній тиждень перед змаганнями як тренуватися',
      'підводка до рекорду',
      'скільки днів відпочивати перед тестом максимуму',
      'пікова форма до змагань як вийти',
      'последняя неделя перед соревнованиями',
    ],
  },
  k_top_backoff: {
    ex: [
      'what are back off sets',
      'drop weight after my heavy set',
      'top single then backoffs',
      'how many back off sets after top set',
      'heavy set followed by lighter volume sets',
      'back off sets percentage',
      'serie back off po ciężkiej serii',
      'ile serii back off',
      'back off serijos po sunkios',
      'back off seeriad pärast rasket seeriat',
      'bek of pidkhody',
    ],
    exUk: [
      'що таке бек оф підходи',
      'знизити вагу після важкого підходу',
      'топ сингл потім легші',
      'скільки бекоф підходів після топ сету',
      'бэк офф подходы сколько процентов',
    ],
  },
  k_paused_reps: {
    ex: [
      'pause bench benefits',
      'paused squats for strength out of the hole',
      'how long should i pause on bench',
      'pause deadlifts off the floor',
      'should i pause every rep on bench',
      'dead stop reps',
      'wyciskanie z pauzą na klatce',
      'martwy ciąg z pauzą',
      'spaudimas su pauze ant krūtinės',
      'pausiga lamades surumine',
      'zhym z pauzoiu na hrudiakh',
    ],
    exUk: [
      'жим з паузою на грудях користь',
      'присід з паузою внизу для сили',
      'скільки тримати паузу на жимі',
      'станова з паузою над підлогою навіщо',
      'жим с паузой на груди',
    ],
  },
  k_eccentrics: {
    ex: [
      'slow eccentrics for hypertrophy',
      'negative pull ups to get stronger',
      'lowering phase slow better',
      'eccentric overload training',
      'negatives cause more soreness',
      'heavy negatives with a spotter',
      'faza ekscentryczna wolno',
      'negatywne podciąganie',
      'lėta ekscentrinė fazė',
      'aeglane ekstsentriline faas',
      'nehatyvni pidtiahuvannia',
    ],
    exUk: [
      'повільна ексцентрика для росту',
      'негативні підтягування щоб стати сильнішим',
      'повільно опускати вагу краще',
      'від негативів сильніша крепатура',
      'негативы с помощью напарника',
    ],
  },
  k_volume_landmarks: {
    ex: [
      'maximum recoverable volume per muscle',
      'mev for chest how many sets',
      'am i above my mrv',
      'volume landmarks renaissance periodization',
      'mav maximum adaptive volume',
      'too much volume mrv signs',
      'mev dla klatki ile serii',
      'maksymalna objętość do regeneracji',
      'mrv požymiai',
      'mrv märgid',
      'mev i mrv poiasny',
    ],
    exUk: [
      'максимальний обсяг від якого відновлюєшся',
      'мев на груди скільки підходів',
      'як зрозуміти що я вище mrv',
      'орієнтири обсягу мев мав мрв',
      'mrv признаки',
    ],
  },
  k_bfr: {
    ex: [
      'bfr bands for arms',
      'occlusion training for rehab',
      'blood flow restriction with light weights',
      'how tight should occlusion cuffs be',
      'bfr training after knee surgery',
      'kaatsu bands worth it',
      'trening okluzyjny opaski',
      'bfr po kontuzji',
      'kraujotakos ribojimas po traumos',
      'bfr treening pärast vigastust',
      'okliuziine trenuvannia',
    ],
    exUk: [
      'джгути bfr на руки',
      'оклюзійне тренування для реабілітації',
      'обмеження кровотоку з легкою вагою',
      'наскільки туго затягувати манжети bfr',
      'окклюзия тренировки после травмы',
    ],
  },
  k_5x5: {
    ex: [
      'starting strength or stronglifts',
      '5 sets of 5 program for beginners',
      'stronglifts stalled what now',
      'is stronglifts enough for arms',
      '5x5 every session add weight',
      'madcow program',
      'program 5x5 dla początkujących',
      'stronglifts co dalej',
      '5x5 programa pradedantiesiems',
      '5x5 algajatele',
      'prohrama 5 na 5',
    ],
    exUk: [
      'програма 5 підходів по 5',
      'стронгліфтс застряг що далі',
      'стронгліфтс мало на руки',
      '5х5 кожне тренування додавати вагу',
      'стронглифтс для новичка',
    ],
  },
  k_531: {
    ex: [
      '531 training max',
      'jim wendler program',
      '5/3/1 for beginners',
      'what is bbb in 531',
      '531 amrap last set',
      'how much to add each 531 cycle',
      'program wendlera',
      '5/3/1 maks treningowy',
      'wendlerio programa',
      'wendleri programm',
      'vendler 531',
    ],
    exUk: [
      'програма вендлера',
      '531 тренувальний максимум',
      '5 3 1 для початківців',
      'скільки додавати кожен цикл 531',
      'программа вендлера',
    ],
  },
  k_circuit_training: {
    ex: [
      'circuit workout for fat loss',
      'circuits vs straight sets for muscle',
      'full body circuit with no rest',
      'circuit training for beginners',
      'metabolic circuit finisher',
      'station training',
      'trening obwodowy na spalanie',
      'obwód na całe ciało',
      'ratinė treniruotė riebalams',
      'ringtreening rasvapõletuseks',
      'kruhove trenuvannia dlia skhudnennia',
    ],
    exUk: [
      'кругове тренування для схуднення',
      'кругові чи звичайні підходи для мʼязів',
      'кругова на все тіло без пауз',
      'кругове для початківців',
      'круговая тренировка на жиросжигание',
    ],
  },
  k_plyometrics: {
    ex: [
      'plyo exercises for athletes',
      'how to jump higher',
      'depth jumps safe',
      'box jumps or squats for vertical',
      'plyometric training for runners',
      'how many box jumps per session',
      'ćwiczenia plyometryczne',
      'jak skakać wyżej',
      'kaip šokti aukščiau',
      'kuidas kõrgemale hüpata',
      'yak strybaty vyshche',
    ],
    exUk: [
      'як стрибати вище',
      'глибинні стрибки безпечно',
      'стрибки на тумбу чи присідання для стрибка',
      'пліометрика для бігунів',
      'как прыгать выше',
    ],
  },
  k_front_squat: {
    ex: [
      'front squat technique tips',
      'front rack position hurts',
      'clean grip front squat',
      'cross arm front squat',
      'front squat bar keeps rolling forward',
      'front squat for quads',
      'przysiad przedni technika',
      'przysiad przedni bolą nadgarstki',
      'priekinis pritūpimas technika',
      'eeskükk tehnika',
      'frontalki tekhnika',
    ],
    exUk: [
      'фронтальний присід техніка',
      'фронтальний хват болять кисті',
      'фронтальні присідання гриф котиться вперед',
      'фронталки на квадрицепс',
      'фронтальный присед как держать гриф',
    ],
  },
  k_hip_thrust: {
    ex: [
      'glute bridge with barbell',
      'hip thrust best glute builder',
      'hip thrusts lower back pain',
      'hip thrust bench height',
      'hip thrust foot position',
      'barbell glute bridge how heavy',
      'hip thrust technika',
      'unoszenie bioder ze sztangą',
      'klubų tiltelis su štanga',
      'puusasild kangiga',
      'yahidnyi mistok zi shtanhoiu',
    ],
    exUk: [
      'ягідний місток зі штангою техніка',
      'хіп траст болить поперек',
      'хіп траст положення стоп',
      'сідничний міст яка вага',
      'хип траст техника',
    ],
  },
  k_rdl: {
    ex: [
      'romanian deadlift technique',
      'rdl form tips',
      'how far should the bar go on rdl',
      'rdl knees bent or straight',
      'romanian deadlift for hamstrings',
      'romanian deadlift hamstring stretch cue',
      'martwy ciąg rumuński technika',
      'rdl jak nisko',
      'rumuniška trauka technika',
      'rumeenia jõutõmme tehnika',
      'rumunska tiaha tekhnika',
    ],
    exUk: [
      'румунська тяга техніка',
      'румунка коліна зігнуті чи прямі',
      'румунська тяга на задню поверхню',
      'румунська тяга скільки підходів',
      'румынская тяга как опускать',
    ],
  },
  k_bulgarian_split: {
    ex: [
      'bulgarian split squat technique',
      'rear foot elevated split squat form',
      'bulgarian split squats hurt my knee',
      'bulgarians for glutes',
      'how far should my front foot be on bulgarians',
      'split squat with back foot on bench',
      'przysiad bułgarski technika',
      'bułgarskie przysiady na pośladki',
      'bulgariškas pritūpimas technika',
      'bulgaaria kükk tehnika',
      'bolharski prysidannia tekhnika',
    ],
    exUk: [
      'болгарські присідання техніка',
      'болгарки болить коліно',
      'болгарські випади на сідниці',
      'як далеко ставити передню ногу на болгарських',
      'болгарские выпады техника',
    ],
  },
  k_lunges: {
    ex: [
      'lunges form',
      'reverse lunges vs forward lunges',
      'walking lunges technique',
      'lunges bad for knees',
      'how long should my lunge step be',
      'dumbbell lunges tips',
      'wykroki technika',
      'wykroki bolą kolana',
      'įtūpstai technika',
      'väljaasted tehnika',
      'vypady tekhnika',
    ],
    exUk: [
      'випади техніка',
      'випади назад чи вперед',
      'випади в русі як правильно',
      'випади шкідливі для колін',
      'выпады техника',
    ],
  },
  k_dips: {
    ex: [
      'dips technique',
      'how to do dips safely',
      'weighted dips shoulder',
      'bench dips bad',
      'dips for chest or triceps',
      'cant do a single dip',
      'pompki na poręczach technika',
      'dipy na klatkę',
      'atsispaudimai ant lygiagrečių',
      'dipid rinnale',
      'brusy tekhnika',
    ],
    exUk: [
      'бруси техніка',
      'віджимання на брусах на груди',
      'бруси з вагою болить плече',
      'не можу віджатися на брусах жодного разу',
      'брусья техника',
    ],
  },
  k_face_pull: {
    ex: [
      'face pulls for shoulder health',
      'face pulls rear delts',
      'face pull rope height',
      'band face pulls at home',
      'face pulls every workout',
      'face pulls sets and reps',
      'face pull technika',
      'face pull na tylne barki',
      'face pull technika pečiams',
      'face pull tehnika',
      'feis puly',
    ],
    exUk: [
      'тяга канату до обличчя техніка',
      'фейс пули для плечей',
      'фейс пул з резинкою вдома',
      'фейспули скільки повторів',
      'фейс пул зачем',
    ],
  },
  k_lateral_raise: {
    ex: [
      'side delt raises form',
      'lateral raises traps taking over',
      'dumbbell lateral raise technique',
      'cable lateral raise',
      'lateral raises how many reps',
      'lateral raise thumbs up or down',
      'wznosy hantli bokiem technika',
      'wznosy bokiem czuję kaptury',
      'šoniniai kėlimai technika',
      'külgtõsted tehnika',
      'makhy hanteliamy tekhnika',
    ],
    exUk: [
      'махи гантелями в сторони техніка',
      'на махах працюють трапеції',
      'махи в кросовері',
      'махи в сторони скільки повторів',
      'махи в стороны трапеция забивается',
    ],
  },
  k_chinup_vs_pullup: {
    ex: [
      'underhand vs overhand pullups',
      'chin ups work biceps more',
      'which grip for pull ups',
      'neutral grip pullups',
      'chin up or pull up for back',
      'wide grip pull ups vs chin ups',
      'podciąganie chwyt neutralny',
      'podchwyt czy nachwyt',
      'prisitraukimai siauru ar plačiu rankų laikymu',
      'lõuatõmbed millise haardega',
      'pidtiahuvannia yakym khvatom',
    ],
    exUk: [
      'підтягування яким хватом',
      'зворотний хват більше на біцепс',
      'нейтральний хват підтягування',
      'широким хватом чи зворотним',
      'подтягивания каким хватом',
    ],
  },
  k_bench_grip: {
    ex: [
      'bench press hand placement',
      'close grip vs wide grip bench',
      'where do my hands go on the bar',
      'elbows flare on bench',
      'bench grip width for shoulder pain',
      'index finger on the rings bench',
      'szerokość chwytu przy wyciskaniu',
      'łokcie przy wyciskaniu',
      'rankų plotis ant štangos spaudime',
      'haarde laius lamades surumisel',
      'shyryna khvatu zhym',
    ],
    exUk: [
      'де ставити руки на грифі в жимі',
      'вузький чи широкий хват жим',
      'лікті розводяться на жимі',
      'ширина хвату при болю в плечах',
      'ширина хвата жим лежа',
    ],
  },
  k_leg_drive: {
    ex: [
      'leg drive bench press',
      'how to use legs on bench',
      'feet flat or on toes bench',
      'my butt comes up when benching',
      'pushing with legs on bench press',
      'where to put feet when benching',
      'praca nóg przy wyciskaniu',
      'gdzie stawiać stopy przy wyciskaniu',
      'kojų darbas spaudime',
      'jalgade töö lamades surumisel',
      'nohy v zhymi lezhachy',
    ],
    exUk: [
      'ноги в жимі лежачи',
      'як упиратися ногами на жимі',
      'ноги на всю стопу чи на носки в жимі',
      'таз відривається від лавки на жимі',
      'ноги в жиме лежа',
    ],
  },
  k_high_low_bar: {
    ex: [
      'low bar squat vs high bar',
      'bar position on back squat',
      'high bar squat for quads',
      'low bar squat shoulder pain',
      'where should the bar sit when squatting',
      'high bar or low bar for beginners',
      'przysiad low bar czy high bar',
      'gdzie trzymać sztangę na plecach',
      'štangos padėtis pritūpime',
      'kangi asend kükis',
      'hryf na spyni de trymaty',
    ],
    exUk: [
      'де тримати штангу на спині',
      'низький гриф присід болять плечі',
      'високий гриф на квадрицепс',
      'хай бар чи лоу бар для новачка',
      'где держать штангу на спине',
    ],
  },
  k_good_morning: {
    ex: [
      'goodmorning lift for posterior chain',
      'bar on back hip hinge accessory',
      'hinge with barbell on shoulders for hamstrings',
      'good mornings or rdl for hamstrings',
      'skłony ze sztangą na plecach',
      'good morning ćwiczenie',
      'lenkimasis su štanga ant pečių',
      'kallutus kangiga õlgadel',
      'nakhyly zi shtanhoiu na plechakh',
    ],
    exUk: [
      'гуд морнінг техніка',
      'нахили зі штангою на плечах',
      'гуд морнінг чи румунська тяга',
      'гуд морнінг на задню поверхню',
      'наклоны со штангой на плечах',
    ],
  },
  k_farmer_carry: {
    ex: [
      'farmers walk how far',
      'farmer carries for grip',
      'suitcase carry for obliques',
      'loaded carries benefits',
      'farmers walk with kettlebells',
      'carrying heavy dumbbells walking',
      'spacer farmera na chwyt',
      'noszenie hantli',
      'ūkininko ėjimas su hanteliais',
      'farmeri kõnd hantlitega',
      'prohulianka fermera na khvat',
    ],
    exUk: [
      'прогулянка фермера на хват',
      'ходьба з важкими гантелями',
      'перенесення гантелі в одній руці',
      'фермерська прогулянка скільки метрів',
      'прогулка фермера польза',
    ],
  },
  k_calves: {
    ex: [
      'calf training tips',
      'how often to train calves',
      'calf raises reps',
      'skinny calves genetics',
      'standing vs seated calf raises',
      'calves not growing at all',
      'jak trenować łydki',
      'łydki genetyka',
      'kaip treniruoti blauzdas',
      'kuidas sääri treenida',
    ],
    exUk: ['литки генетика', 'підйоми на носки скільки повторів', 'литки стоячи чи сидячи'],
  },
  k_trap_bar: {
    ex: [
      'hex bar deadlift',
      'trap bar vs conventional',
      'is trap bar deadlift cheating',
      'trap bar high handles',
      'trap bar deadlift for athletes',
      'trap bar easier on lower back',
      'martwy ciąg trap bar',
      'trap bar czy klasyczny',
      'trap bar trauka',
      'trap bar jõutõmme',
      'stanova z trep hryfom',
    ],
    exUk: [
      'станова з трап грифом',
      'трап гриф це читинг',
      'високі ручки трап грифа',
      'трап гриф легше для попереку',
      'становая с трэп грифом',
    ],
  },
  k_nordic_curl: {
    ex: [
      'nordic hamstring exercise',
      'nordics for sprinters',
      'nordic curls at home',
      'hamstring strain prevention exercise',
      'nordic curl progression for beginners',
      'nordics soreness',
      'nordic curls w domu',
      'ćwiczenie nordic na dwugłowe',
      'nordic curls namuose',
      'nordic curl kodus',
      'nordychni zghynannia vdoma',
    ],
    exUk: [
      'нордичні згинання вдома',
      'нордики для спринтерів',
      'профілактика травм задньої поверхні стегна',
      'нордичні скільки повторів',
      'нордические сгибания дома',
    ],
  },
  k_pistol_squat: {
    ex: [
      'pistol squat progressions',
      'single leg squat to a box',
      'cant balance on pistol squats',
      'pistol squats bad for knees',
      'one legged squat training',
      'pistol squat heel lifts',
      'przysiad pistolet progresja',
      'przysiad na jednej nodze',
      'pritūpimas ant vienos kojos',
      'kükk ühel jalal',
      'prysid na odnii nozi',
    ],
    exUk: [
      'пістолетик прогресія',
      'присідання на одній нозі до лавки',
      'не тримаю рівновагу на пістолетику',
      'пістолетик шкідливий для колін',
      'пистолетик как научиться',
    ],
  },
  k_no_soreness: {
    ex: [
      'no more doms after workouts',
      'workout not effective if not sore',
      'muscles stopped getting sore',
      'is soreness a sign of growth',
      'why dont i get sore anymore',
      'never sore after leg day now',
      'brak zakwasów czy mięśnie rosną',
      'nie czuję zakwasów',
      'raumenys nebeskauda po treniruotės',
      'lihasvalu enam ei tule',
      'nemaie krepatury',
    ],
    exUk: [
      'немає крепатури після тренувань',
      'крепатура ознака росту?',
      'чому мене більше не крепатурить',
      'мʼязи перестали боліти після тренувань',
      'нет крепатуры значит нет роста',
    ],
  },
  k_massage_gun: {
    ex: [
      'percussion gun before workout',
      'hypervolt worth it',
      'massage gun on sore muscles',
      'massage gun vs foam roller',
      'how long to use massage gun per muscle',
      'massage gun dangerous',
      'pistolet do masażu przed treningiem',
      'pistolet do masażu czy roller',
      'masažinis pistoletas ar voleliai',
      'massaažipüstol või rull',
      'masazhnyi pistolet chy rolyk',
    ],
    exUk: [
      'масажний пістолет перед тренуванням',
      'масажний пістолет чи ролик',
      'скільки часу масажувати пістолетом',
      'перкусійний масаж після залу',
      'массажный пистолет или ролик',
    ],
  },
  k_wearables: {
    ex: [
      'low hrv should i train',
      'apple watch recovery',
      'whoop strain and recovery',
      'body battery garmin training',
      'resting heart rate up after training',
      'is hrv tracking useful',
      'niskie hrv czy trenować',
      'tętno spoczynkowe wyższe niż zwykle',
      'žemas hrv ar sportuoti',
      'madal hrv kas treenida',
      'nyzkyi hrv chy trenuvatys',
    ],
    exUk: [
      'низький hrv чи тренуватись',
      'пульс спокою підвищився',
      'відновлення на whoop низьке',
      'body battery на гарміні',
      'низкий hrv тренироваться ли',
    ],
  },
  k_cns_fatigue: {
    ex: [
      'fried cns after heavy deadlifts',
      'central nervous system burnout',
      'neural fatigue from max lifts',
      'cns recovery time',
      'is cns fatigue a myth',
      'deadlifts drain my nervous system',
      'zmęczenie cns po martwym ciągu',
      'układ nerwowy przemęczony',
      'cns nuovargis po trauku',
      'kesknärvisüsteemi väsimus',
      'nervova systema vtomylas',
    ],
    exUk: [
      'нервова система перевтомлена після станової',
      'втома нервової системи від максимумів',
      'скільки відновлюється цнс',
      'втома цнс міф чи ні',
      'цнс устала после становой',
    ],
  },
  k_detraining: {
    ex: [
      'how long until muscle loss after stopping',
      'break from the gym lose gains',
      'two weeks off gym muscle loss',
      'does muscle come back faster after a break',
      'detraining how fast',
      'i stopped lifting for a month',
      'ile czasu zanim stracę mięśnie',
      'przerwa od siłowni utrata mięśni',
      'kiek laiko prarandami raumenys',
      'kui kiiresti lihased kaovad',
      'skilky chasu propadaiut miazy',
    ],
    exUk: [
      'за скільки часу зникнуть мʼязи без тренувань',
      'два тижні без залу чи втрачу масу',
      'мʼязи повертаються швидше після перерви',
      'як швидко йде сила без залу',
      'через сколько пропадают мышцы',
    ],
  },
  k_joint_supplements: {
    ex: [
      'collagen for tendons',
      'glucosamine chondroitin worth it',
      'supplements for knee pain',
      'best joint supplement for lifters',
      'does collagen help ligaments',
      'joint health supplements',
      'kolagen na stawy',
      'glukozamina na kolana',
      'kolagenas sąnariams',
      'kollageen liigestele',
      'kolahen dlia suhlobiv',
    ],
    exUk: [
      'колаген для сухожиль',
      'глюкозамін хондроїтин варто',
      'добавки для колін',
      'колаген для звʼязок працює',
      'коллаген для суставов',
    ],
  },
  k_creatine_myths: {
    ex: [
      'creatine and hair loss',
      'creatine kidney damage myth',
      'does creatine make you bloated',
      'creatine puffy face',
      'is creatine safe long term',
      'creatine side effects bald',
      'kreatyna wypadanie włosów',
      'kreatyna a nerki',
      'kreatinas plaukų slinkimas',
      'kreatiin juuste väljalangemine',
      'kreatyn i nyrky',
    ],
    exUk: [
      'креатин і випадіння волосся',
      'креатин шкодить нирках?',
      'від креатину набрякає обличчя',
      'креатин безпечний довго пити',
      'креатин лысеют',
    ],
  },
  k_protein_powder: {
    ex: [
      'best whey protein',
      'whey isolate vs concentrate',
      'vegan protein powder good',
      'which protein powder for lactose intolerance',
      'cheap protein powder worth it',
      'casein or whey',
      'najlepsze białko serwatkowe',
      'izolat czy koncentrat',
      'geriausi baltymai',
      'parim vadakuproteiin',
      'yakyi protein krashchyi',
    ],
    exUk: [
      'найкращий сироватковий протеїн',
      'ізолят чи концентрат сироватки',
      'рослинний протеїн нормальний',
      'казеїн чи сироватка',
      'какой протеин лучше',
    ],
  },
  k_protein_per_meal: {
    ex: [
      '30 grams protein per meal myth',
      'can you eat too much protein at once',
      'is 60g protein in one meal wasted',
      'protein absorption limit',
      'big protein meal absorbed',
      'max protein you can absorb',
      'limit białka na posiłek',
      'ile białka na raz',
      'kiek baltymų per kartą',
      'kui palju valku korraga',
      'skilky bilka za raz',
    ],
    exUk: [
      '30 грамів білка за прийом це міф',
      'можна зʼїсти забагато білка за раз',
      '60 г білка за раз не засвоїться',
      'ліміт засвоєння білка',
      'сколько белка за один прием',
    ],
  },
  k_intra_workout: {
    ex: [
      'intra workout carbs',
      'sports drink while lifting',
      'drink during training',
      'what to sip during long workouts',
      'bcaa during workout',
      'gatorade during gym',
      'napój podczas treningu',
      'co pić na siłowni',
      'gėrimas treniruotės metu',
      'jook trenni ajal',
      'napii pid chas treniuvannia',
    ],
    exUk: [
      'напій під час тренування',
      'що пити в залі',
      'ізотонік під час тренування',
      'bcaa під час тренування',
      'что пить во время тренировки',
    ],
  },
  k_vitamin_d: {
    ex: [
      'vitamin d3 dose',
      'vitamin d deficiency lifting',
      'should i supplement vitamin d in winter',
      'vitamin d and testosterone',
      'how much vitamin d do i need',
      'vitamin d with k2',
      'dawka witaminy d',
      'witamina d zimą',
      'vitamino d dozė',
      'd vitamiini annus',
      'vitamin d doza',
    ],
    exUk: [
      'дозування вітаміну d',
      'нестача вітаміну д',
      'вітамін д3 взимку',
      'вітамін d і тестостерон',
      'витамин д3 сколько пить',
    ],
  },
  k_magnesium: {
    ex: [
      'magnesium before bed',
      'magnesium for muscle cramps',
      'magnesium glycinate for sleep',
      'best form of magnesium',
      'zma supplement',
      'do lifters need magnesium',
      'magnez na sen',
      'magnez na skurcze',
      'magnis miegui',
      'magneesium une jaoks',
      'mahnii dlia snu',
    ],
    exUk: [
      'магній перед сном',
      'магній від судом у мʼязах',
      'гліцинат магнію для сну',
      'яку форму магнію пити',
      'магний для сна',
    ],
  },
  k_test_boosters: {
    ex: [
      'natural test booster',
      'tribulus terrestris',
      'ashwagandha benefits',
      'boost testosterone naturally supplements',
      'test booster pills scam',
      'tongkat ali',
      'naturalny booster testosteronu',
      'ashwagandha na testosteron',
      'natūralus testosterono stipriklis',
      'looduslik testosterooni booster',
      'buster testosteronu',
    ],
    exUk: [
      'натуральний бустер тестостерону',
      'трибулус чи ашваганда',
      'як підняти тестостерон добавками',
      'бустери тестостерону обман',
      'бустер тестостерона',
    ],
  },
  k_fat_burners: {
    ex: [
      'fat burner supplements',
      'thermogenic pills',
      'l carnitine fat loss',
      'fat burning pills safe',
      'do fat burners help lose weight',
      'green tea extract fat loss',
      'spalacz tłuszczu',
      'tabletki na spalanie tłuszczu',
      'riebalų deginimo tabletės',
      'rasvapõletaja tabletid',
      'zhyrospaliuvach',
    ],
    exUk: [
      'жироспалювачі пити',
      'таблетки для спалювання жиру',
      'карнітин для схуднення',
      'жироспалювач безпечний',
      'жиросжигатель пить',
    ],
  },
};
