/**
 * How the app works — written from the app's own screens (labels as in the UI),
 * so Atlas never makes up a button. Understood by example; en/uk answers.
 */
import type { Intent } from './intentKit';

export const APP_TOPICS: {
  id: string;
  ask: [string, string];
  answer: [string, string];
  ex: string[];
  exUk: string[];
}[] = [
  {
    id: 'app_custom_exercise',
    ask: ['How do I add my own exercise?', 'Як додати свою вправу?'],
    answer: [
      "Type its name when you add an exercise in a session: if it isn't in the list, tap “Create “…”” and tag the muscles and equipment — it's yours from then on. Trainers can also add exercises to the shared library (Programs → Exercises → New exercise).",
      'Під час тренування додай вправу й напиши її назву: якщо такої немає — «Створити «…»», познач мʼязи й обладнання, і вона твоя. Тренери можуть додавати вправи й у спільну бібліотеку (Програми → Вправи → «Нова вправа»).',
    ],
    ex: [
      'how do I add my own exercise in the app',
      "my exercise isn't in the list, how can I create it",
      'can I create a custom exercise?',
      "how to add a new exercise that's not in the app",
      'where do I create a custom movement',
      "the app doesn't have cable crossover with a rope, can I add it myself",
      'add custom exercise',
      'cant find my exercise in the list how do i make a new one',
      "is there a way to add exercises that aren't in your database",
      'how do i create exercize',
      "I do a weird machine at my gym that's not listed, how do I add it to the app",
      "where's the button to make a new exercise",
      'can I name my own exercise and pick which muscles it works',
      'how do I add a custom lift to Spotter',
      'missing exercise - how to add it',
      'can I make my own exercise and use it in workouts here',
      'create new exercise in app',
      'how to add an exercise the app doesnt know about',
      'jak dodać własne ćwiczenie w aplikacji',
      'nie ma mojego ćwiczenia na liście, jak je stworzyć',
      'czy mogę utworzyć własne ćwiczenie?',
      'gdzie jest przycisk do tworzenia nowego ćwiczenia',
      'jak dodac cwiczenie ktorego nie ma w apce',
      'dodaj własne ćwiczenie',
      'brakuje ćwiczenia w bazie, jak je dodać samemu',
      'da się stworzyć ćwiczenie z własną nazwą i wybrać mięśnie?',
      'jak dodać nowe ćwiczenie do listy w aplikacji',
      'w siłowni mam maszynę której nie ma w apce, jak ją dodać',
      'kaip programėlėje pridėti savo pratimą',
      'mano pratimo nėra sąraše, kaip jį sukurti',
      'ar galiu susikurti savo pratimą?',
      'kur mygtukas sukurti naują pratimą',
      'kaip pridet pratima kurio nera programeleje',
      'sukurti savo pratimą',
      'trūksta pratimo sąraše, kaip pridėti pačiam',
      'ar galima sukurti pratimą su savo pavadinimu ir pasirinkti raumenis?',
      'kaip čia pridėti naują pratimą',
      'sporto salėje yra treniruoklis kurio nėra programėlėje, kaip jį įdėti',
      'kuidas äpis oma harjutust lisada',
      'minu harjutust pole nimekirjas, kuidas seda luua',
      'kas ma saan luua oma harjutuse?',
      'kus on nupp uue harjutuse loomiseks',
      'kuidas lisada harjutust mida äpis pole',
      'loo oma harjutus',
      'harjutus puudub nimekirjast, kuidas ise lisada',
      'kas saab teha harjutuse oma nimega ja valida lihased?',
      'kuidas siin uus harjutus lisada',
      'jõusaalis on masin mida äpis pole, kuidas see lisada',
    ],
    exUk: [
      'як додати свою вправу в додатку',
      'моєї вправи немає в списку, як її створити',
      'чи можна створити власну вправу?',
      'де тут кнопка створити нову вправу',
      'як додати вправу, якої немає в базі додатку',
      'в апці немає тяги на тренажері який у нас в залі, як його додати',
      'створити свою вправу',
      'не можу знайти вправу в списку, як зробити нову',
      'як додати кастомну вправу',
      "можна самому додати вправу і вказати які м'язи вона качає?",
      'як створити нову вправу тут',
      'хочу додати свою вправу якої нема в спотері',
      'як добавити вправу в додаток',
      'де в додатку створюються власні вправи',
      'немає потрібної вправи, як її додати самому',
      'як додати свою вправу щоб потім юзати в тренуваннях',
      'чи можна тут дописати свою вправу вручну',
      'як створити вправу з власною назвою в апці',
      'додати нову вправу в список як',
      'как добавить своё упражнение в приложении',
      'нету моего упражнения в списке, как создать',
      'як добавить своє упражнєніє сюди',
    ],
  },
  {
    id: 'app_export',
    ask: ['Can I export my data?', 'Чи можна експортувати дані?'],
    answer: [
      "There's no personal export or backup button yet — your log is stored in your account and syncs to every device you sign in on, so nothing is lost if you change phones. A trainer can export a program as CSV; an admin can export a member's data.",
      'Особистого експорту чи резервної копії поки немає — журнал зберігається в акаунті й синхронізується на кожен пристрій, де ти входиш, тож при зміні телефона нічого не пропаде. Тренер може експортувати програму в CSV, адмін — дані учасника.',
    ],
    ex: [
      'how do I export my workout data',
      'can I download all my workouts as CSV',
      'is there a way to back up my data from the app',
      'export to csv',
      'how to get my training log out of Spotter',
      "I want a backup of everything I've logged, how",
      'can I export my history to excel',
      "where's the export button",
      'download my data',
      'how do i save my workouts to a file',
      'switching phones and want a backup of my workouts first, can I export',
      'can i get a copy of all my lifts in a spreadsheet',
      'does the app let you export data',
      'how to backup workots',
      'I want to analyse my data in google sheets, how do I export it from the app',
      'export training history',
      'is there a file export for my sessions',
      'how do I download a backup of my account data',
      'jak wyeksportować moje treningi',
      'czy mogę pobrać wszystkie treningi jako CSV',
      'jak zrobić kopię zapasową danych z aplikacji',
      'eksport do csv',
      'gdzie jest przycisk eksportu',
      'chce pobrac swoje dane z apki',
      'czy da się wyeksportować historię do excela?',
      'zmieniam telefon, jak zrobić backup treningów',
      'jak zapisać treningi do pliku',
      'czy aplikacja ma eksport danych',
      'kaip eksportuoti savo treniruotes',
      'ar galiu atsisiųsti visas treniruotes CSV formatu',
      'kaip padaryti duomenų atsarginę kopiją iš programėlės',
      'eksportas į csv',
      'kur eksporto mygtukas',
      'noriu atsisiusti savo duomenis is programeles',
      'ar galima eksportuoti istoriją į excel?',
      'keičiu telefoną, kaip pasidaryti treniruočių backup',
      'kaip išsaugoti treniruotes į failą',
      'ar programėlėje yra duomenų eksportas',
      'kuidas oma treeninguid eksportida',
      'kas saan kõik treeningud CSV-na alla laadida',
      'kuidas teha äpist andmete varukoopia',
      'eksport csv-sse',
      'kus on ekspordi nupp',
      'tahan oma andmed äpist alla laadida',
      'kas ajalugu saab excelisse eksportida?',
      'vahetan telefoni, kuidas treeningutest backup teha',
      'kuidas treeninguid faili salvestada',
      'kas äpis on andmete eksport',
    ],
    exUk: [
      'як експортувати мої тренування',
      'чи можна завантажити всі тренування в CSV',
      'як зробити бекап даних з додатку',
      'експорт в csv',
      'як вивантажити мій журнал тренувань зі спотера',
      'хочу резервну копію всього що я записав, як',
      'можна експортувати історію в ексель?',
      'де тут кнопка експорту',
      'завантажити мої дані',
      'як зберегти тренування у файл',
      'міняю телефон, хочу спочатку зберегти бекап тренувань, як',
      'можна отримати всі мої підходи в таблиці?',
      'чи є в додатку експорт даних',
      'як скачати свої дані з апки',
      'хочу проаналізувати дані в гугл таблицях, як їх експортувати звідси',
      'експорт історії тренувань',
      'як зробити резервну копію тренувань в додатку',
      'чи можна вивантажити дані файлом',
      'як завантажити архів моїх даних',
      'как экспортировать тренировки из приложения',
      'можно скачать все данные в csv?',
      'як сдєлать бекап тренувань тут',
    ],
  },
  {
    id: 'app_history',
    ask: ['Where is my workout history?', 'Де історія тренувань?'],
    answer: [
      'Today → “History” shows the last days; “See all history” opens the full list — tap a session to open it. For one exercise: its clock icon → “Open history”.',
      'Сьогодні → «Історія» показує останні дні; «Уся історія» — повний список, тапни тренування, щоб відкрити. Для однієї вправи: іконка годинника → «Відкрити історію».',
    ],
    ex: [
      'where can I see my past workouts',
      'how do I view my workout history',
      "where's the log of my previous sessions",
      'workout history',
      'how to find what I did last monday in the app',
      'where do old workouts go after I finish them',
      'can I see all my previous trainings somewhere',
      'show my past sessions',
      'i finished a workout, where do i find it now',
      "how do I look back at last week's leg day",
      'where is the history tab',
      'is there a calendar of my workouts in the app',
      'how to see previous workouts',
      'where do i check what weights i used last time in the app',
      'list of all my completed workouts',
      'wher is my workout log',
      'how to open an old workout here',
      'where can i browse my training log by date',
      'gdzie zobaczę moje poprzednie treningi',
      'jak otworzyć historię treningów',
      'historia treningów',
      'gdzie jest dziennik poprzednich sesji w aplikacji',
      'skończyłem trening, gdzie go teraz znaleźć',
      'jak sprawdzic co robilem w zeszly poniedzialek',
      'czy w apce jest kalendarz treningów',
      'gdzie sprawdzić jakie ciężary brałem ostatnio',
      'lista wszystkich zakończonych treningów',
      'gdzie jest zakładka historii',
      'kur pamatyti ankstesnes treniruotes',
      'kaip atidaryti treniruočių istoriją',
      'treniruočių istorija',
      'kur programėlėje ankstesnių treniruočių žurnalas',
      'baigiau treniruotę, kur ją dabar rasti',
      'kaip pasitikrint ka dariau praeita pirmadieni',
      'ar programėlėje yra treniruočių kalendorius',
      'kur pažiūrėti kokius svorius kėliau paskutinį kartą',
      'visų užbaigtų treniruočių sąrašas',
      'kur istorijos skirtukas',
      'kus näen oma varasemaid treeninguid',
      'kuidas avada treeningute ajalugu',
      'treeningute ajalugu',
      'kus on äpis eelmiste treeningute logi',
      'lõpetasin treeningu, kust ma selle nüüd leian',
      'kuidas vaadata mida tegin eelmisel esmaspäeval',
      'kas äpis on treeningute kalender',
      'kus näha milliseid raskusi viimati kasutasin',
      'kõigi lõpetatud treeningute nimekiri',
      'kus on ajaloo vaheleht',
    ],
    exUk: [
      'де подивитися мої минулі тренування',
      'як відкрити історію тренувань',
      'де журнал попередніх тренувань',
      'історія тренувань',
      'як знайти що я робив в понеділок в додатку',
      'куди діваються тренування після завершення',
      'де тут всі мої попередні тренування',
      'показати минулі тренування',
      'закінчив тренування, де його тепер знайти',
      'як подивитися минулий день ніг',
      'де вкладка історії',
      'чи є в апці календар тренувань',
      'як переглянути попередні трені',
      'де глянути які ваги я брав минулого разу',
      'список усіх завершених тренувань',
      'де мій лог тренувань в додатку',
      'як відкрити старе тренування тут',
      'де переглянути тренування по датах',
      'де в спотері історія',
      'где посмотреть историю тренировок',
      'куда пропадают прошлые тренировки в приложении',
      'де подивитись шо я робив минулого тижня',
    ],
  },
  {
    id: 'app_edit_workout',
    ask: ['How do I edit a past workout?', 'Як виправити минуле тренування?'],
    answer: [
      'Open the session from History — it opens for editing. Tap a set to change it or “Delete set”; the exercise menu can clear sets or delete the exercise; the bin at the top deletes the whole workout. Then press “Save” at the top — leaving without it drops the changes.',
      'Відкрий тренування з Історії — воно відкриється для редагування. Тапни підхід, щоб змінити, або «Видалити підхід»; у меню вправи — очистити підходи чи видалити вправу; кошик угорі видаляє все тренування. Потім «Зберегти» вгорі — без цього зміни не збережуться.',
    ],
    ex: [
      'how do I edit a past workout',
      'I logged the wrong weight yesterday, how do I fix it',
      'can I change reps on an old set',
      'how to correct a mistake in a finished workout',
      'edit set',
      'typed 800kg instead of 80 lol how do i change it',
      'how do I change the weight of a set I already saved',
      "can I delete a set from yesterday's workout",
      'where do I edit a logged session in the app',
      'forgot to add an exercise to my last workout, can I add it now',
      'fix reps in completed workout',
      'how to edit old workot',
      'can I change the date of a workout I logged',
      'the app saved wrong numbers for my bench, how to edit',
      'is it possible to modify a workout after finishing it',
      'how do i remove a set i logged by accident',
      'edit weight on previous set',
      'can I go back and update the reps from last session',
      'jak edytować poprzedni trening',
      'wpisałem wczoraj zły ciężar, jak to poprawić',
      'czy mogę zmienić powtórzenia w starej serii',
      'jak poprawić błąd w zakończonym treningu',
      'edytuj serię',
      'wpisalem 800 kg zamiast 80, jak zmienic',
      'jak usunąć serię dodaną przez przypadek',
      'czy da się zmienić datę zapisanego treningu?',
      'zapomniałem dodać ćwiczenie do ostatniego treningu, mogę dodać teraz?',
      'gdzie w aplikacji edytuje się zapisany trening',
      'kaip redaguoti ankstesnę treniruotę',
      'vakar įvedžiau blogą svorį, kaip pataisyti',
      'ar galiu pakeisti pakartojimus senoje serijoje',
      'kaip ištaisyti klaidą užbaigtoje treniruotėje',
      'redaguoti seriją',
      'ivedžiau 800 kg vietoj 80, kaip pakeist',
      'kaip ištrinti seriją, kurią pridėjau per klaidą',
      'ar galima pakeisti įrašytos treniruotės datą?',
      'pamiršau pridėti pratimą į paskutinę treniruotę, ar galiu dabar?',
      'kur programėlėje redaguojama išsaugota treniruotė',
      'kuidas eelmist treeningut muuta',
      'sisestasin eile vale raskuse, kuidas parandada',
      'kas saan vana seeria kordusi muuta',
      'kuidas parandada viga lõpetatud treeningus',
      'muuda seeriat',
      'panin 800 kg 80 asemel, kuidas muuta',
      'kuidas kustutada kogemata lisatud seeria',
      'kas salvestatud treeningu kuupäeva saab muuta?',
      'unustasin viimasesse treeningusse harjutuse lisada, kas saan nüüd lisada?',
      'kus äpis salvestatud treeningut muudetakse',
    ],
    exUk: [
      'як відредагувати минуле тренування',
      'вчора записав не ту вагу, як виправити',
      'чи можна змінити повтори в старому підході',
      'як виправити помилку в завершеному тренуванні',
      'редагувати підхід',
      'ввів 800 кг замість 80 ахах як змінити',
      'як змінити вагу підходу який вже зберіг',
      'чи можна видалити підхід з вчорашнього тренування',
      'де в додатку редагувати записане тренування',
      'забув додати вправу в останнє тренування, можна додати зараз?',
      'виправити повтори в завершеному тренуванні',
      'як редагувати старе тренування тут',
      'можна поміняти дату тренування яке я записав?',
      'апка зберегла неправильні цифри по жиму, як відредагувати',
      'чи можна змінити тренування після завершення',
      'як видалити підхід який я випадково додав',
      'змінити вагу в попередньому підході',
      'як повернутися і поправити повтори з минулого тренування',
      'помилився з вагою в минулому тренуванні, як поправити в додатку',
      'как отредактировать прошлую тренировку',
      'как изменить вес в старом подходе',
      'як поміняти кількість повторів в старому трєніровці',
    ],
  },
  {
    id: 'app_account',
    ask: ['How do I sign in or change my password?', 'Як увійти чи змінити пароль?'],
    answer: [
      'Accounts are by invite: ask your admin or trainer for an invite link, sign in with username and password. Change the password in Profile → Settings → “Password”; “Sign out” is there too — your log comes back when you sign in again.',
      'Акаунти — за запрошенням: попроси в адміна чи тренера invite-посилання, входь з іменем користувача й паролем. Пароль змінюється в Профіль → Налаштування → «Пароль»; там же «Вийти» — журнал повернеться, коли увійдеш знову.',
    ],
    ex: [
      'how do I sign up',
      'how to register an account in Spotter',
      'I need an invite, how do I get one',
      'how do I log in',
      'forgot my password',
      'how do I change my password in the app',
      'how to sign out',
      "where's the logout button",
      "can't sign in to the app, what do I do",
      'how do i create an account',
      'is registration invite only?',
      'how to reset password',
      'can I log in with google',
      'how do I change the email on my account',
      'log out of the app',
      'where do i get an invite code',
      'sign in not working',
      'how to make acount here',
      'jak się zarejestrować',
      'jak założyć konto w aplikacji',
      'potrzebuję zaproszenia, skąd je wziąć',
      'jak się zalogować',
      'zapomniałem hasła',
      'jak zmienić hasło w apce',
      'jak się wylogować',
      'nie moge sie zalogowac, co robic',
      'czy mogę zalogować się przez google?',
      'gdzie dostanę kod zaproszenia',
      'kaip užsiregistruoti',
      'kaip susikurti paskyrą programėlėje',
      'reikia pakvietimo, kur jį gauti',
      'kaip prisijungti',
      'pamiršau slaptažodį',
      'kaip pakeisti slaptažodį programėlėje',
      'kaip atsijungti',
      'negaliu prisijungt, ka daryti',
      'ar galima prisijungti per google?',
      'kur gauti pakvietimo kodą',
      'kuidas registreeruda',
      'kuidas äpis kontot luua',
      'vajan kutset, kust seda saada',
      'kuidas sisse logida',
      'unustasin parooli',
      'kuidas äpis parooli muuta',
      'kuidas välja logida',
      'ei saa sisse logida, mida teha',
      'kas saab googlega sisse logida?',
      'kust saada kutsekood',
    ],
    exUk: [
      'як зареєструватися',
      'як створити акаунт у спотері',
      'потрібне запрошення, де його взяти',
      'як увійти в додаток',
      'забув пароль',
      'як змінити пароль в додатку',
      'як вийти з акаунту',
      'де кнопка виходу',
      'не можу залогінитися в апку, що робити',
      'як створити обліковий запис',
      'реєстрація тільки по інвайту?',
      'як скинути пароль',
      'чи можна увійти через гугл',
      'як змінити пошту в акаунті',
      'вийти з додатку',
      'де взяти інвайт код',
      'не працює вхід',
      'як зарегатись тут',
      'як поміняти пароль від акаунту',
      'как зарегистрироваться в приложении',
      'забыл пароль, как войти',
      'як вийти з акаунта в апці, шось не бачу',
    ],
  },
  {
    id: 'app_sync',
    ask: ['Does my data sync between devices?', 'Чи синхронізуються дані між пристроями?'],
    answer: [
      "Yes — it syncs by itself across every device you sign in on and works offline; changes upload when you're back online. The chip at the top shows Synced / Syncing / Offline.",
      "Так — синхронізується сама на всіх пристроях, де ти входиш, і працює офлайн; зміни відправляться, щойно з'явиться мережа. Статус угорі: «Синхронізовано / Синхронізація / Офлайн».",
    ],
    ex: [
      'does my data sync between phone and computer',
      'will my workouts show up on my laptop too',
      'does the app work offline',
      'can I log a workout without internet',
      'will I lose my data if I switch phones',
      'is my data saved in the cloud',
      'sync between devices',
      "I logged on my phone but don't see it on the web version, why",
      'what happens if I lose signal mid workout in the app',
      'no wifi at my gym, will the app still save sets',
      'are workouts stored on the server or just on my phone',
      'if i delete the app do i lose everything',
      'does spotter sync across devices',
      'can I use the app on two phones with the same account',
      'offline mode?',
      'does it sync automaticaly',
      'my tablet and phone show different workouts, is sync broken',
      'will my data be lost if I clear the browser',
      'czy dane synchronizują się między telefonem a komputerem',
      'czy aplikacja działa offline',
      'czy mogę zapisać trening bez internetu',
      'czy stracę dane jak zmienię telefon',
      'synchronizacja między urządzeniami',
      'zapisałem na telefonie a w wersji web nie widze, czemu',
      'na siłowni nie ma zasięgu, czy apka zapisze serie?',
      'jak usunę aplikację to wszystko zniknie?',
      'czy dane są w chmurze czy tylko w telefonie',
      'czy mogę używać apki na dwóch urządzeniach z jednym kontem',
      'ar duomenys sinchronizuojasi tarp telefono ir kompiuterio',
      'ar programėlė veikia be interneto',
      'ar galiu įrašyti treniruotę offline',
      'ar prarasiu duomenis jei pakeisiu telefoną',
      'sinchronizacija tarp įrenginių',
      'irasiau telefone o web versijoj nematau, kodel',
      'salėje nėra ryšio, ar programėlė išsaugos serijas?',
      'jei ištrinsiu programėlę, viskas dings?',
      'ar duomenys saugomi debesyje ar tik telefone',
      'ar galiu naudoti programėlę dviejuose įrenginiuose su ta pačia paskyra',
      'kas andmed sünkroonivad telefoni ja arvuti vahel',
      'kas äpp töötab ilma internetita',
      'kas saan treeningu offline salvestada',
      'kas kaotan andmed kui telefoni vahetan',
      'sünkroonimine seadmete vahel',
      'salvestasin telefonis aga veebis ei näe, miks',
      'jõusaalis pole levi, kas äpp salvestab seeriad?',
      'kui äpi kustutan, kas kõik kaob?',
      'kas andmed on pilves või ainult telefonis',
      'kas saan äppi kasutada kahes seadmes sama kontoga',
    ],
    exUk: [
      'чи синхронізуються дані між телефоном і компом',
      'мої тренування будуть видно і на ноуті?',
      'чи працює додаток без інтернету',
      'можна записати тренування офлайн?',
      'чи втрачу я дані якщо поміняю телефон',
      'дані зберігаються в хмарі?',
      'синхронізація між пристроями',
      'записав на телефоні а в веб версії не бачу, чому',
      "що буде якщо в залі пропаде зв'язок посеред тренування",
      'в залі нема вайфаю, апка збереже підходи?',
      'тренування зберігаються на сервері чи тільки в телефоні',
      'якщо видалю додаток то все пропаде?',
      'спотер синхронізує між пристроями?',
      'можна юзати апку на двох телефонах з одним акаунтом',
      'є офлайн режим?',
      'воно синхронізується автоматично?',
      'на планшеті і телефоні різні тренування, синхра зламалась?',
      'чи пропадуть дані якщо почистити браузер',
      'чи не злетять мої дані з додатку',
      'синхронизируются ли данные между телефоном и компом',
      'работает ли приложение без интернета',
      'шо буде з даними якщо телефон загублю',
    ],
  },
  {
    id: 'app_programs',
    ask: ['How do I build my own program?', 'Як створити свою програму?'],
    answer: [
      'Programs → “Build a program” → add days and exercises → “Activate”. Or ask me — as main coach I can write one from your history. Trainers can also assign programs to clients.',
      'Програми → «Створити програму» → додай дні й вправи → «Активувати». Або попроси мене — як основний тренер я напишу її з твоєї історії. Тренери ще й можуть призначати програми клієнтам.',
    ],
    ex: [
      'how do I create my own program in the app',
      'how to build a training program here',
      'can I make a custom workout plan and activate it',
      'how do I set a program as active',
      'create program',
      'I want to put my PPL split into the app, how',
      'where do I build a weekly routine',
      'how to add days and exercises to a program',
      'how do i activate the program i made',
      'can I make my own routine instead of using yours',
      'how to make a 4 day split in spotter',
      'where is the program builder',
      'how to set up a workout plan in the app',
      'my coach gave me a program on paper, how do I enter it here',
      'how to switch to a different program',
      'make my own progam',
      'can i create a routine template and reuse it',
      'how do I start following a program in the app',
      'jak stworzyć własny plan treningowy w aplikacji',
      'jak zbudować program treningowy tutaj',
      'jak ustawić program jako aktywny',
      'stwórz program',
      'chcę wrzucić mój split PPL do apki, jak',
      'jak dodać dni i ćwiczenia do planu',
      'jak aktywowac program ktory zrobilem',
      'gdzie jest kreator planów',
      'trener dał mi plan na kartce, jak go tu wpisać',
      'jak przełączyć się na inny program',
      'kaip programėlėje susikurti savo treniruočių programą',
      'kaip čia sudaryti treniruočių planą',
      'kaip padaryti programą aktyvią',
      'sukurti programą',
      'noriu įkelti savo split į programėlę, kaip',
      'kaip pridėti dienas ir pratimus į programą',
      'kaip aktyvuot programa kuria sukuriau',
      'kur programų kūrimo įrankis',
      'treneris davė programą ant popieriaus, kaip ją čia suvesti',
      'kaip pereiti prie kitos programos',
      'kuidas äpis oma treeningkava luua',
      'kuidas siin treeningprogrammi koostada',
      'kuidas kava aktiivseks teha',
      'loo kava',
      'tahan oma PPL spliti äppi panna, kuidas',
      'kuidas kavasse päevi ja harjutusi lisada',
      'kuidas aktiveerida kava mille tegin',
      'kus on kava koostaja',
      'treener andis kava paberil, kuidas see siia sisestada',
      'kuidas teisele kavale üle minna',
    ],
    exUk: [
      'як створити свою програму в додатку',
      'як скласти програму тренувань тут',
      'чи можна зробити свій план і активувати його',
      'як зробити програму активною',
      'створити програму',
      'хочу закинути свій спліт в апку, як',
      'де скласти тижневу програму',
      'як додати дні і вправи в програму',
      'як активувати програму яку я зробив',
      'можна зробити свою програму замість вашої?',
      'як зробити 4-денний спліт в спотері',
      'де конструктор програм',
      'як налаштувати план тренувань в додатку',
      'тренер дав програму на папері, як внести її сюди',
      'як переключитися на іншу програму',
      'як створити шаблон тренування і використовувати його',
      'як почати займатися по програмі в апці',
      'де тут додати свою програму',
      'як запустити програму яку склав сам',
      'как создать свою программу в приложении',
      'как активировать программу тренировок',
      'як сдєлать програму і включити її',
    ],
  },
  {
    id: 'app_gyms',
    ask: ['How do I add my gym and its equipment?', 'Як додати свій зал і обладнання?'],
    answer: [
      "Gyms tab → find your gym (search or “Nearby”) → “Add this gym”. In it, “Inventory” lets you tick the equipment you have; I also suggest kit I've seen in your workouts there.",
      'Вкладка «Зали» → знайди свій (пошук або «Поблизу») → «Додати цей зал». У ньому «Інвентар» — познач обладнання, яке є; я ще й підкажу те, що бачив у твоїх тренуваннях там.',
    ],
    ex: [
      'how do I add my gym in the app',
      'where do I set what equipment my gym has',
      'how to set gym inventory',
      'add gym',
      'my gym has no leg press, how do I tell the app',
      'can I list the machines available at my gym',
      'how to add a second gym location',
      'where do I choose which equipment I have at home',
      'how do i edit the equipment list for my gym',
      'I train at home with only dumbbells, how do I set that up here',
      'can I switch between gyms in the app',
      'where is gym settings',
      'how to mark that my gym has a smith machine',
      'set up home gym equipment',
      "how do I remove equipment my gym doesn't have",
      'how to ad my gym',
      'can the app know what gear my gym has',
      'where do i configure available equipment',
      'jak dodać moją siłownię w aplikacji',
      'gdzie ustawić jaki sprzęt ma moja siłownia',
      'dodaj siłownię',
      'na mojej siłowni nie ma suwnicy, jak to ustawić w apce',
      'jak dodać drugą siłownię',
      'ćwiczę w domu tylko z hantlami, jak to tu ustawić',
      'jak edytowac liste sprzetu',
      'gdzie są ustawienia siłowni',
      'czy mogę przełączać się między siłowniami w aplikacji?',
      'jak zaznaczyć że mam maszynę smitha',
      'kaip programėlėje pridėti savo sporto salę',
      'kur nurodyti kokia įranga yra mano salėje',
      'pridėti salę',
      'mano salėje nėra kojų preso, kaip tai nurodyti programėlėje',
      'kaip pridėti antrą salę',
      'sportuoju namie tik su hanteliais, kaip tai čia nustatyti',
      'kaip redaguot irangos sarasa',
      'kur salės nustatymai',
      'ar galiu programėlėje perjungti sales?',
      'kaip pažymėti kad salėje yra smito treniruoklis',
      'kuidas äpis oma jõusaali lisada',
      'kus määrata milline varustus mu jõusaalis on',
      'lisa jõusaal',
      'minu saalis pole jalapressi, kuidas seda äpis märkida',
      'kuidas teist jõusaali lisada',
      'treenin kodus ainult hantlitega, kuidas seda siin seadistada',
      'kuidas varustuse nimekirja muuta',
      'kus on jõusaali seaded',
      'kas saan äpis jõusaalide vahel vahetada?',
      'kuidas märkida et saalis on smithi masin',
    ],
    exUk: [
      'як додати свій зал в додатку',
      'де вказати яке обладнання є в моєму залі',
      'як налаштувати інвентар залу',
      'додати зал',
      'в моєму залі нема жиму ногами, як це вказати в апці',
      'можна перелічити тренажери які є в залі?',
      'як додати другий зал',
      'де вибрати яке обладнання є вдома',
      'як редагувати список обладнання залу',
      'тренуюсь вдома тільки з гантелями, як це налаштувати тут',
      'можна перемикатися між залами в додатку?',
      'де налаштування залу',
      'як відмітити що в залі є сміт',
      'налаштувати домашній зал',
      'як прибрати обладнання якого в залі нема',
      'як добавити свою качалку в апку',
      'де вказати інвентар в спотері',
      'як задати тренажери свого залу',
      'додати обладнання в зал',
      'как добавить свой зал в приложении',
      'где указать оборудование зала',
      'як вказати шо в мене є штанга і турнік вдома',
    ],
  },
  {
    id: 'app_bodyweight_log',
    ask: ['Where do I log my body weight?', 'Де записати вагу тіла?'],
    answer: [
      'Profile → “Body” → “Body metrics” → “Add weight”. Height, body fat, waist and other measurements are there too, plus a weight goal.',
      'Профіль → «Тіло» → «Показники тіла» → «Додати вагу». Там же зріст, відсоток жиру, талія й інші виміри, а ще ціль по вазі.',
    ],
    ex: [
      'where do I log my body weight',
      'how do I add my weight in the app',
      'can I track body measurements here',
      'log bodyweight',
      'how to record my waist and arm measurements in the app',
      'where do I enter my weight each morning',
      'is there a weight tracker in spotter',
      'how to update my current bodyweight',
      'can i see a graph of my body weight in the app',
      'where to add body fat %',
      'how do I log chest measurement',
      'weighed myself today, where do I put it',
      'track weight over time',
      'how to add wieght entry',
      'where are body measurements in the app',
      'can the app track my bicep size',
      'how do I change my weight in the profile',
      'where do i record weigh-ins',
      'gdzie zapisać wagę ciała',
      'jak dodać moją wagę w aplikacji',
      'czy mogę tu śledzić wymiary ciała',
      'zapisz wagę',
      'jak wpisać obwód talii i ramion w apce',
      'zważyłem się dziś, gdzie to wpisać',
      'czy jest wykres wagi w aplikacji?',
      'gdzie dodać procent tkanki tłuszczowej',
      'jak zaktualizowac aktualna wage',
      'gdzie są pomiary ciała w apce',
      'kur įrašyti savo kūno svorį',
      'kaip programėlėje pridėti savo svorį',
      'ar galiu čia sekti kūno matmenis',
      'įrašyti svorį',
      'kaip įvesti liemens ir rankų apimtis programėlėje',
      'šiandien pasisvėriau, kur tai įrašyti',
      'ar programėlėje yra svorio grafikas?',
      'kur pridėti riebalų procentą',
      'kaip atnaujint dabartini svori',
      'kur programėlėje kūno matmenys',
      'kus oma kehakaalu salvestada',
      'kuidas äpis oma kaalu lisada',
      'kas saan siin kehamõõte jälgida',
      'salvesta kaal',
      'kuidas sisestada äppi vöö- ja käeümbermõõt',
      'kaalusin end täna, kuhu see kirjutada',
      'kas äpis on kaalu graafik?',
      'kuhu lisada rasvaprotsent',
      'kuidas praegust kaalu uuendada',
      'kus on äpis kehamõõdud',
    ],
    exUk: [
      'де записати свою вагу тіла',
      'як додати вагу в додатку',
      'чи можна тут відстежувати заміри тіла',
      'записати вагу тіла',
      'як внести обхват талії і рук в апку',
      'де щоранку вводити вагу',
      'чи є в спотері трекер ваги',
      'як оновити поточну вагу',
      'можна побачити графік ваги в додатку?',
      'куди додати відсоток жиру',
      'як записати обхват грудей',
      'зважився сьогодні, куди це вписати',
      'відстежувати вагу з часом',
      'де тут заміри тіла',
      'як поміняти вагу в профілі',
      'де записувати зважування',
      'як вести облік ваги в додатку',
      'куди вносити заміри',
      'как записать вес тела в приложении',
      'где добавить замеры',
      'де вписать свій вес тут',
      'як добавити вагу тіла в апці',
    ],
  },
  {
    id: 'app_share',
    ask: ['How do I share a workout?', 'Як поділитися тренуванням?'],
    answer: [
      'Open a finished session → “Share workout” → pick Story or Square → share, download or copy the image.',
      'Відкрий завершене тренування → «Поділитися» → обери Story чи квадрат → поділись, завантаж або скопіюй картинку.',
    ],
    ex: [
      'how do I share my workout',
      'can I post my workout to instagram from the app',
      'how to share results with friends',
      'share workout card',
      "where's the share button after a workout",
      'how do I send my session to a friend',
      'can I share my new PR on stories',
      'how to make that summary card to post',
      'share to insta',
      'is there a way to share a workout link',
      'how do i share my training with my buddy in the app',
      'I want to flex my deadlift PR, how do I share it from spotter',
      'how to screenshot/share workout summary',
      'can I share workouts to whatsapp',
      'how do I post my results',
      'shar my workout',
      'send workout to friend',
      'how to share a workout I did last week',
      'jak udostępnić trening',
      'czy mogę wrzucić trening na instagrama z aplikacji?',
      'jak podzielić się wynikami ze znajomymi',
      'gdzie jest przycisk udostępnij po treningu',
      'jak wysłać trening koledze',
      'chce wrzucic nowy rekord na relacje, jak',
      'karta z podsumowaniem treningu do udostępnienia',
      'czy można udostępnić link do treningu',
      'jak wrzucić wyniki na insta',
      'udostępnij trening na whatsappie',
      'kaip pasidalinti treniruote',
      'ar galiu iš programėlės įkelti treniruotę į instagramą?',
      'kaip pasidalinti rezultatais su draugais',
      'kur mygtukas dalintis po treniruotės',
      'kaip nusiųsti treniruotę draugui',
      'noriu ikelt nauja rekorda i stories, kaip',
      'treniruotės santraukos kortelė dalinimuisi',
      'ar galima pasidalinti nuoroda į treniruotę',
      'kaip įkelti rezultatus į insta',
      'pasidalinti treniruote per messenger',
      'kuidas treeningut jagada',
      'kas saan äpist treeningu instagrami postitada?',
      'kuidas tulemusi sõpradega jagada',
      'kus on jagamise nupp pärast treeningut',
      'kuidas treeningut sõbrale saata',
      'tahan uue rekordi storysse panna, kuidas',
      'treeningu kokkuvõtte kaart jagamiseks',
      'kas treeningu linki saab jagada',
      'kuidas tulemusi instasse panna',
      'jaga treeningut whatsappis',
    ],
    exUk: [
      'як поділитися тренуванням',
      'можна запостити тренування в інстаграм з додатку?',
      'як поділитися результатами з друзями',
      'картка тренування для сторіс',
      'де кнопка поділитися після тренування',
      'як скинути тренування другу',
      'можна поділитися новим рекордом в сторіс?',
      'як зробити ту картку з підсумком щоб запостити',
      'поділитись в інсту',
      'чи можна поділитися посиланням на тренування',
      'як поділитися тренуванням з другом в апці',
      'хочу похвалитися рекордом в становій, як поділитися зі спотера',
      'як відправити тренування в телеграм',
      'як запостити свої результати',
      'відправити тренування другу',
      'як поділитися тренуванням з минулого тижня',
      'де тут шерінг тренування',
      'як викласти підсумок тренування в сторіс',
      'як зашерити трєню',
      'как поделиться тренировкой в инстаграм',
      'как отправить тренировку другу из приложения',
      'як скинуть результати в інсту звідси',
    ],
  },
  {
    id: 'app_goals',
    ask: ['Where do I set goals?', 'Де задати цілі?'],
    answer: [
      'Programs → “Goals”: set a physique target and which muscles to grow, hold or ease this block. A body-weight goal lives in Profile → Body metrics.',
      'Програми → «Цілі»: ціль фігури й які мʼязи цього блоку ростити, тримати чи розвантажити. Ціль по вазі — в Профіль → Показники тіла.',
    ],
    ex: [
      'where do I set my goals in the app',
      'how do I change my goal to muscle gain',
      'can I pick focus muscles',
      'set physique goal',
      'where to choose which muscles I want to prioritise',
      'how do i tell the app I want bigger shoulders',
      'how to update my training goal',
      'where are goal settings',
      'I want to switch from cutting to bulking goal in spotter, where',
      'can I set a target physique here',
      'how to select focus areas like glutes',
      'change goal',
      'where did I set my goal when signing up, can I change it',
      'how to set goals in app',
      'can i set arms as focus muscle',
      'where do I edit my fitness target in the profile',
      'how do I set a goal for the app to follow',
      'set my gaol',
      'gdzie ustawić cele w aplikacji',
      'jak zmienić cel na budowę masy',
      'czy mogę wybrać priorytetowe mięśnie',
      'gdzie wybrać partie na których chcę się skupić',
      'jak powiedziec apce ze chce wieksze barki',
      'gdzie są ustawienia celu',
      'chcę zmienić cel z redukcji na masę, gdzie',
      'zmień cel',
      'jak ustawić pośladki jako priorytet',
      'czy mogę tu ustawić docelową sylwetkę',
      'kur programėlėje nustatyti tikslus',
      'kaip pakeisti tikslą į raumenų auginimą',
      'ar galiu pasirinkti prioritetinius raumenis',
      'kur pasirinkti kurias raumenų grupes noriu stiprinti',
      'kaip pasakyt programelei kad noriu didesniu peciu',
      'kur tikslų nustatymai',
      'noriu pakeisti tikslą iš lieknėjimo į masę, kur',
      'pakeisti tikslą',
      'kaip nustatyti sėdmenis kaip prioritetą',
      'ar galiu čia nustatyti norimą kūno formą',
      'kus äpis eesmärke seada',
      'kuidas muuta eesmärk lihasmassi kasvatamiseks',
      'kas saan valida fookuslihased',
      'kus valida lihasrühmad millele keskenduda',
      'kuidas öelda äpile et tahan suuremaid õlgu',
      'kus on eesmärgi seaded',
      'tahan muuta eesmärgi kaalulangetuselt massile, kus',
      'muuda eesmärki',
      'kuidas tuharad prioriteediks määrata',
      'kas saan siin sihtfüüsise määrata',
    ],
    exUk: [
      'де встановити цілі в додатку',
      'як змінити ціль на набір маси',
      "чи можна вибрати пріоритетні м'язи",
      'встановити ціль по фігурі',
      "де вибрати які м'язи хочу підтягнути в першу чергу",
      'як сказати апці що хочу більші плечі',
      'як оновити ціль тренувань',
      'де налаштування цілей',
      'хочу змінити ціль з сушки на масу в спотері, де',
      'чи можна тут задати бажану фігуру',
      'як вибрати фокус на сідниці',
      'змінити ціль',
      'при реєстрації вибирав ціль, як її тепер змінити',
      'як поставити цілі в апці',
      "можна поставити руки як пріоритетні м'язи?",
      'де в профілі редагувати ціль',
      "як налаштувати фокусні м'язи",
      'де поміняти свою мету в додатку',
      'де ставиться ціль в спотері',
      'где поставить цель в приложении',
      'как выбрать приоритетные мышцы',
      'як поміняти ціль на похудєніє тут',
    ],
  },
  {
    id: 'app_install',
    ask: ['How do I install the app on my phone?', 'Як встановити додаток на телефон?'],
    answer: [
      "It's a web app — no store needed. iPhone: in Safari, Share → “Add to Home Screen”. Android: browser menu ⋮ → “Install app”. The sign-in screen has a “Create a shortcut” button with the steps.",
      'Це веб-додаток — магазин не потрібен. iPhone: у Safari «Поділитися» → «На початковий екран». Android: меню браузера ⋮ → «Встановити застосунок». На екрані входу є кнопка «Створити ярлик» з інструкцією.',
    ],
    ex: [
      'how do I install the app on my phone',
      'is there an app in the App Store',
      'can I get spotter on android',
      'how to add the app to my home screen',
      'is it on google play',
      'install app',
      'I only have the website, is there a real app',
      'how to put the app icon on my iphone home screen',
      'is there an ios app',
      'how do i download spotter',
      'can i use it as an app instead of in the browser',
      'add to home screen how',
      'where can I download the app',
      'how to install on iphone from safari',
      'is there a desktop app',
      'instal on android',
      "why can't I find spotter in the app store",
      'is it a PWA? how do I install it',
      'jak zainstalować aplikację na telefonie',
      'czy jest aplikacja w App Store',
      'czy jest wersja na androida',
      'jak dodać apkę do ekranu głównego',
      'czy jest w google play?',
      'mam tylko stronę, jest normalna aplikacja?',
      'jak zainstalowac na iphonie przez safari',
      'skąd pobrać aplikację',
      'czy mogę używać jako apki a nie w przeglądarce',
      'zainstaluj aplikację',
      'kaip įsidiegti programėlę telefone',
      'ar yra programėlė App Store',
      'ar yra versija androidui',
      'kaip pridėti programėlę į pagrindinį ekraną',
      'ar ji yra google play?',
      'turiu tik svetainę, ar yra tikra programėlė?',
      'kaip idiegti iphone per safari',
      'iš kur atsisiųsti programėlę',
      'ar galiu naudoti kaip programėlę, o ne naršyklėje',
      'įdiegti programėlę',
      'kuidas äppi telefoni installida',
      "kas äpp on App Store'is",
      'kas androidile on versioon',
      'kuidas äppi avaekraanile lisada',
      'kas see on google plays?',
      'mul on ainult veebileht, kas päris äpp on olemas?',
      "kuidas iphone'i safari kaudu installida",
      'kust äppi alla laadida',
      'kas saan kasutada äpina, mitte brauseris',
      'installi äpp',
    ],
    exUk: [
      'як встановити додаток на телефон',
      'чи є додаток в App Store',
      'чи є спотер на андроїд',
      'як додати апку на головний екран',
      'він є в гугл плей?',
      'встановити додаток',
      'в мене тільки сайт, є нормальний додаток?',
      'як винести іконку на робочий стіл айфона',
      'є додаток для ios?',
      'як скачати спотер',
      'можна юзати як апку а не в браузері?',
      'як додати на домашній екран',
      'звідки завантажити додаток',
      'як встановити на айфон через сафарі',
      "чи є версія для комп'ютера",
      'як поставити апку на андроід',
      'чому не можу знайти спотер в ап сторі',
      'як встановити додаток з сайту',
      'де скачати апку',
      'как установить приложение на телефон',
      'есть ли приложение в эпстор',
      'як скачать додаток на тєлєфон',
    ],
  },
  {
    id: 'app_delete_account',
    ask: ['How do I delete my account?', 'Як видалити акаунт?'],
    answer: [
      "You can't delete the account yourself — ask your admin, they can remove it. You can delete single workouts, nights or exercises, and clear my chat in my settings.",
      'Видалити акаунт самостійно не можна — попроси адміна, він це зробить. Окремі тренування, ночі сну чи вправи можна видаляти самому, а мій чат — очистити в моїх налаштуваннях.',
    ],
    ex: [
      'how do I delete my account',
      'I want to delete all my data from the app',
      'how to remove my account permanently',
      'delete account',
      'can I erase everything and start over',
      "where's the delete account option",
      'how do i close my spotter account',
      'please delete my profile and data',
      'how to wipe all my workouts',
      "I'm leaving the app, how do I delete my info",
      'GDPR - how do I get my data deleted',
      'how to deactivate account',
      'can I delete my account from inside the app',
      'remove all my data',
      'how to reset the account and delete all history',
      'delet my acount',
      'if I delete my account is everything gone forever',
      'how do I cancel and delete my account',
      'jak usunąć konto',
      'chcę usunąć wszystkie moje dane z aplikacji',
      'jak trwale usunąć konto',
      'usuń konto',
      'gdzie jest opcja usunięcia konta',
      'czy mogę wszystko skasować i zacząć od nowa?',
      'jak usunac wszystkie treningi',
      'odchodzę z apki, jak usunąć moje dane',
      'czy mogę usunąć konto w aplikacji',
      'jak usunę konto to wszystko zniknie na zawsze?',
      'kaip ištrinti paskyrą',
      'noriu ištrinti visus savo duomenis iš programėlės',
      'kaip visam laikui ištrinti paskyrą',
      'ištrinti paskyrą',
      'kur paskyros ištrynimo parinktis',
      'ar galiu viską ištrinti ir pradėti iš naujo?',
      'kaip istrint visas treniruotes',
      'išeinu iš programėlės, kaip ištrinti savo duomenis',
      'ar galiu ištrinti paskyrą programėlėje',
      'jei ištrinsiu paskyrą, viskas dings visam laikui?',
      'kuidas kontot kustutada',
      'tahan kõik oma andmed äpist kustutada',
      'kuidas konto jäädavalt kustutada',
      'kustuta konto',
      'kus on konto kustutamise valik',
      'kas saan kõik kustutada ja otsast alata?',
      'kuidas koik treeningud kustutada',
      'lahkun äpist, kuidas oma andmed kustutada',
      'kas saan konto äpis kustutada',
      'kui konto kustutan, kas kõik kaob jäädavalt?',
    ],
    exUk: [
      'як видалити акаунт',
      'хочу видалити всі свої дані з додатку',
      'як видалити акаунт назавжди',
      'видалити акаунт',
      'можна стерти все і почати заново?',
      'де опція видалення акаунту',
      'як закрити акаунт в спотері',
      'видаліть мій профіль і дані',
      'як стерти всі тренування',
      'йду з апки, як видалити свою інфу',
      'як видалити свої дані по GDPR',
      'як деактивувати акаунт',
      'чи можна видалити акаунт прямо в додатку',
      'видалити всі мої дані',
      'як обнулити акаунт і видалити всю історію',
      'якщо видалю акаунт все пропаде назавжди?',
      'де тут видалення профілю',
      'як повністю видалитися з додатку',
      'хочу щоб мої дані видалили',
      'как удалить аккаунт',
      'как удалить все свои данные из приложения',
      'як удалить акаунт в апці',
    ],
  },
  {
    id: 'app_superset',
    ask: ['How do I make a superset?', 'Як зробити суперсет?'],
    answer: [
      "In a session: the exercise's menu → “Superset with…” and pick the partner; “Ungroup” undoes it. In the program editor you can group selected exercises as a superset.",
      'У тренуванні: меню вправи → «Суперсет із…» і обери пару; «Розгрупувати» — скасувати. У редакторі програми можна обʼєднати вибрані вправи в суперсет.',
    ],
    ex: [
      'how do I make a superset in the app',
      'how to group two exercises together',
      'can I link exercises into a superset',
      'create superset',
      'how do I pair bicep curls and tricep pushdowns as a superset here',
      "where's the superset option",
      'how to do a giant set / circuit in the app',
      'how do i superset exercises in my workout',
      'link exercises',
      'how to ungroup a superset',
      'can I add a superset to my program',
      'how to mark two exercises as back to back',
      'superset button where',
      'how to make supperset',
      'can spotter do supersets',
      'how do I combine 3 exercises into a circuit in the app',
      'how to log a superset',
      'how do i join exercises together',
      'jak zrobić superserię w aplikacji',
      'jak zgrupować dwa ćwiczenia',
      'czy mogę połączyć ćwiczenia w superserię',
      'stwórz superserię',
      'gdzie jest opcja superserii',
      'jak zrobic obwod z 3 cwiczen w apce',
      'jak rozdzielić superserię',
      'czy mogę dodać superserię do planu?',
      'jak połączyć biceps i triceps w superserię tutaj',
      'jak zapisać superserię',
      'kaip programėlėje padaryti supersetą',
      'kaip sugrupuoti du pratimus',
      'ar galiu sujungti pratimus į supersetą',
      'sukurti supersetą',
      'kur superseto parinktis',
      'kaip padaryt rata is 3 pratimu programeleje',
      'kaip išskirti supersetą',
      'ar galiu pridėti supersetą į programą?',
      'kaip sujungti bicepsą ir tricepsą į supersetą čia',
      'kaip įrašyti supersetą',
      'kuidas äpis superseeriat teha',
      'kuidas kahte harjutust grupeerida',
      'kas saan harjutused superseeriaks ühendada',
      'loo superseeria',
      'kus on superseeria valik',
      'kuidas teha äpis 3 harjutusega ringtreening',
      'kuidas superseeriat lahti võtta',
      'kas saan superseeria kavasse lisada?',
      'kuidas biitseps ja triitseps siin superseeriaks ühendada',
      'kuidas superseeriat logida',
    ],
    exUk: [
      'як зробити суперсет в додатку',
      'як згрупувати дві вправи',
      "чи можна об'єднати вправи в суперсет",
      'створити суперсет',
      'як поєднати біцепс і трицепс в суперсет тут',
      'де опція суперсету',
      'як зробити гігантський сет або коло в апці',
      'як зробити суперсет в тренуванні',
      "зв'язати вправи",
      'як розгрупувати суперсет',
      'можна додати суперсет в програму?',
      'як позначити що дві вправи йдуть підряд',
      'де кнопка суперсету',
      'як зробити супер сет',
      'чи вміє спотер суперсети',
      "як об'єднати 3 вправи в коло в додатку",
      'як записати суперсет',
      "як з'єднати вправи разом",
      'як тут робити суперсети',
      'как сделать суперсет в приложении',
      'как объединить два упражнения',
      'як сдєлать суперсєт в апці',
    ],
  },
  {
    id: 'app_warmup_set',
    ask: ['How do I mark a warm-up set?', 'Як позначити розминочний підхід?'],
    answer: [
      "Tap the set → “Set type” → “Warm-up”. Dropset, reverse dropset and static-dynamic are there too. Warm-ups don't count toward your working sets.",
      'Тапни підхід → «Тип підходу» → «Розминка». Там же дроп-сет, зворотний дроп-сет і статодинаміка. Розминочні не рахуються в робочі підходи.',
    ],
    ex: [
      'how do I mark a set as warm-up',
      'how to set a set type to dropset in the app',
      "can I label a set as warmup so it doesn't count",
      'warm up set',
      'where do I change set type',
      'how do i log a drop set',
      'how to tag a set as failure',
      'my warm-up sets are counting toward volume, how do I mark them',
      'how to switch a set to warmup in spotter',
      'set type options',
      'can I mark sets as W or D like in other apps',
      'how do i make a set a warm up one',
      "where's the warmup toggle on a set",
      'how to change normal set to drop set',
      'mark warmup',
      'how to log warmups separately in the app',
      'tap on set number to change type?',
      'how do I set warmp set',
      'jak oznaczyć serię jako rozgrzewkową',
      'jak zmienić typ serii na drop set w aplikacji',
      'seria rozgrzewkowa',
      'gdzie zmienić typ serii',
      'jak zapisac drop set',
      'serie rozgrzewkowe liczą się do objętości, jak je oznaczyć',
      'jak oznaczyć serię do upadku',
      'czy mogę oznaczać serie jako W albo D?',
      'jak przełączyć serię na rozgrzewkę w apce',
      'jakie są typy serii w aplikacji',
      'kaip pažymėti seriją kaip apšilimo',
      'kaip programėlėje pakeisti serijos tipą į drop set',
      'apšilimo serija',
      'kur pakeisti serijos tipą',
      'kaip irasyt drop seta',
      'apšilimo serijos įskaičiuojamos į apimtį, kaip jas pažymėti',
      'kaip pažymėti seriją iki nesėkmės',
      'ar galiu žymėti serijas W ar D?',
      'kaip perjungti seriją į apšilimą programėlėje',
      'kokie serijų tipai yra programėlėje',
      'kuidas märkida seeria soojendusseeriaks',
      'kuidas äpis seeria tüüpi drop setiks muuta',
      'soojendusseeria',
      'kus seeria tüüpi muuta',
      'kuidas drop setti logida',
      'soojendusseeriad lähevad mahu sisse, kuidas neid märkida',
      'kuidas märkida seeria läbikukkumiseni',
      'kas saan seeriaid märkida W või D?',
      'kuidas seeriat äpis soojenduseks lülitada',
      'mis seeria tüübid äpis on',
    ],
    exUk: [
      'як позначити підхід як розминочний',
      'як змінити тип підходу на дропсет в додатку',
      'чи можна позначити підхід як розминку щоб не рахувався',
      'розминочний підхід',
      'де змінити тип підходу',
      'як записати дропсет',
      'як позначити підхід до відмови',
      "розминочні підходи рахуються в об'єм, як їх позначити",
      'як переключити підхід на розминку в спотері',
      'які є типи підходів',
      'можна позначати підходи як W чи D як в інших апках?',
      'як зробити підхід розминочним',
      'де перемикач розминки на підході',
      'як змінити звичайний підхід на дроп сет',
      'позначити розминку',
      'як записувати розминку окремо в додатку',
      'натиснути на номер підходу щоб змінити тип?',
      'як відмітити розминочний сет тут',
      'де вибрати тип сету в апці',
      'как отметить подход как разминочный',
      'как сделать дропсет в приложении',
      'як помітить подхід як розминку',
    ],
  },
  {
    id: 'app_activity',
    ask: ['How do I log a run or other cardio?', 'Як записати біг чи інше кардіо?'],
    answer: [
      'Outside the gym: Today → “Log activity” → pick run, bike, swim, walk, yoga… → start now or log a past one. In a gym session, the Cardio tab in the exercise picker adds a machine.',
      'Поза залом: Сьогодні → «Активність» → біг, велосипед, плавання, ходьба, йога… → почати зараз або записати минулу. У тренуванні в залі — вкладка «Кардіо» у виборі вправ додає тренажер.',
    ],
    ex: [
      'how do I log a run in the app',
      'can I track cardio here',
      'how to add a bike ride',
      'log swimming',
      'where do I record yoga sessions',
      'I went hiking today, how do I add that to spotter',
      'how to log an activity outside the gym',
      'can I add a football game as an activity',
      'how do i record cardio like treadmill in the app',
      'where to log my morning jog',
      'add activity',
      'can the app track steps or running distance',
      'how to log a 5k run with time',
      'is there a way to log sports other than lifting',
      'how do I add a cycling session with distance',
      'log cardoi',
      'where do I put my pilates class in the app',
      'how to add non-gym workout',
      'jak zapisać bieganie w aplikacji',
      'czy mogę tu śledzić cardio',
      'jak dodać jazdę na rowerze',
      'zapisz pływanie',
      'gdzie zapisać zajęcia jogi',
      'bylem dzis w gorach, jak to dodac do apki',
      'jak dodać aktywność poza siłownią',
      'czy mogę dodać mecz piłki jako aktywność?',
      'jak zapisać bieg na 5 km z czasem',
      'dodaj aktywność',
      'kaip programėlėje įrašyti bėgimą',
      'ar galiu čia sekti kardio',
      'kaip pridėti važiavimą dviračiu',
      'įrašyti plaukimą',
      'kur įrašyti jogos užsiėmimus',
      'siandien buvau zygyje, kaip ikelt i programele',
      'kaip įrašyti veiklą ne sporto salėje',
      'ar galiu pridėti futbolą kaip veiklą?',
      'kaip įrašyti 5 km bėgimą su laiku',
      'pridėti veiklą',
      'kuidas äpis jooksu logida',
      'kas saan siin kardiot jälgida',
      'kuidas rattasõitu lisada',
      'logi ujumine',
      'kus joogatunde salvestada',
      'kaisin tana matkal, kuidas see äppi lisada',
      'kuidas logida tegevust väljaspool jõusaali',
      'kas saan jalgpalli tegevusena lisada?',
      'kuidas logida 5 km jooks koos ajaga',
      'lisa tegevus',
    ],
    exUk: [
      'як записати пробіжку в додатку',
      'чи можна тут відстежувати кардіо',
      'як додати поїздку на велосипеді',
      'записати плавання',
      'де записувати заняття йогою',
      'сьогодні ходив в гори, як додати це в спотер',
      'як записати активність поза залом',
      'можна додати футбол як активність?',
      'як записати кардіо типу доріжки в апці',
      'де записати ранкову пробіжку',
      'додати активність',
      'чи рахує додаток кроки або дистанцію бігу',
      'як записати забіг на 5 км з часом',
      'чи можна записувати інший спорт крім залу',
      'як додати велотренування з дистанцією',
      'куди вписати пілатес в додатку',
      'як додати тренування не в залі',
      'як записати біг тут',
      'де в апці кардіо',
      'как записать пробежку в приложении',
      'как добавить плавание или вело',
      'як добавить бєг в апку',
    ],
  },
  {
    id: 'app_library',
    ask: ['Where are the exercise instructions?', 'Де інструкції до вправ?'],
    answer: [
      'Programs → “Exercises” → “Library”: search any exercise — each has form photos and instructions. Videos in the Learn app are still coming.',
      'Програми → «Вправи» → «Бібліотека»: знайди будь-яку вправу — у кожної фото техніки й інструкції. Відео в «Навчанні» ще готуються.',
    ],
    ex: [
      'where can I see exercise technique in the app',
      'are there videos showing how to do exercises',
      "where's the exercise library",
      'how do I see instructions for an exercise',
      'exercise library',
      'tap on exercise to see how to do it?',
      'is there a demo video for romanian deadlift in the app',
      'where to find form tips for exercises here',
      'how do i open the exercise description',
      'does spotter have technique guides',
      'browse all exercises',
      'where do I look up how an exercise is done',
      'can I see which muscles an exercise works in the app',
      'how to watch the exercise video',
      'exersise instructions where',
      'is there a gif or animation for each exercise',
      "where's the list of all exercises with descriptions",
      'how to view technique for an exercise in my workout',
      'gdzie zobaczę technikę ćwiczenia w aplikacji',
      'czy są filmiki jak robić ćwiczenia',
      'gdzie jest biblioteka ćwiczeń',
      'jak zobaczyć instrukcję do ćwiczenia',
      'biblioteka ćwiczeń',
      'czy w apce jest film z martwym ciagiem rumunskim',
      'jak otworzyć opis ćwiczenia',
      'czy mogę zobaczyć w aplikacji jakie mięśnie pracują',
      'gdzie lista wszystkich ćwiczeń z opisami',
      'jak obejrzeć technikę ćwiczenia podczas treningu',
      'kur programėlėje pamatyti pratimo techniką',
      'ar yra vaizdo įrašų kaip atlikti pratimus',
      'kur pratimų biblioteka',
      'kaip pamatyti pratimo instrukciją',
      'pratimų biblioteka',
      'ar programeleje yra rumuniskos traukos video',
      'kaip atidaryti pratimo aprašymą',
      'ar galiu programėlėje pamatyti kokie raumenys dirba',
      'kur visų pratimų sąrašas su aprašymais',
      'kaip pažiūrėti pratimo techniką treniruotės metu',
      'kus äpis harjutuse tehnikat näha',
      'kas on videoid kuidas harjutusi teha',
      'kus on harjutuste teek',
      'kuidas harjutuse juhendit näha',
      'harjutuste teek',
      'kas apis on rumeenia jõutõmbe video',
      'kuidas harjutuse kirjeldust avada',
      'kas saan äpis näha milliseid lihaseid harjutus töötab',
      'kus on kõigi harjutuste nimekiri kirjeldustega',
      'kuidas treeningu ajal harjutuse tehnikat vaadata',
    ],
    exUk: [
      'де в додатку подивитися техніку вправи',
      'чи є відео як робити вправи',
      'де бібліотека вправ',
      'як подивитися інструкцію до вправи',
      'бібліотека вправ',
      'натиснути на вправу щоб побачити як її робити?',
      'чи є в апці відео румунської тяги',
      'де тут поради по техніці',
      'як відкрити опис вправи',
      'чи є в спотері гайди по техніці',
      'переглянути всі вправи',
      'де глянути як правильно робиться вправа',
      "можна побачити в додатку які м'язи працюють у вправі?",
      'як подивитися відео вправи',
      'де інструкції до вправ',
      'чи є гіфка або анімація для кожної вправи',
      'де список усіх вправ з описами',
      'як переглянути техніку вправи під час тренування',
      'де тут каталог вправ',
      'где в приложении техника упражнений',
      'есть ли видео упражнений в приложении',
      'де подивиться як робить вправу в апці',
    ],
  },
  {
    id: 'app_trainer',
    ask: ['How do trainers and clients work here?', 'Як тут працюють тренер і клієнти?'],
    answer: [
      'A trainer adds clients with an invite link and sees their history live (read-only), assigns programs from the client page. To get a trainer, ask your admin to assign one — who can see your data is listed in Profile → Settings.',
      'Тренер додає клієнтів через invite-посилання, бачить їхню історію наживо (лише перегляд) і призначає програми зі сторінки клієнта. Щоб мати тренера — попроси адміна призначити; хто бачить твої дані, видно в Профіль → Налаштування.',
    ],
    ex: [
      'how do I get a personal trainer in the app',
      'can a trainer see my workouts',
      'how do I add a client as a coach',
      'is there a coach feature in spotter',
      'how to connect with my trainer in the app',
      'my PT wants to see my logs, how do I give access',
      'how do I invite my coach',
      'find a trainer',
      "I'm a personal trainer, how do I manage clients here",
      'can my coach assign me a program through the app',
      'how to link my account to a trainer',
      'hire personal trainer in app',
      'how does the trainer see what I did',
      'where do I add clients',
      "how to remove my trainer's access",
      'can i get coaching through spotter',
      'how to add my personal traner',
      'trainer mode how does it work',
      'jak znaleźć trenera personalnego w aplikacji',
      'czy trener może widzieć moje treningi',
      'jak dodać podopiecznego jako trener',
      'jak połączyć się z moim trenerem w apce',
      'mój trener chce widzieć moje treningi, jak dać dostęp',
      'jestem trenerem, jak tu prowadzic klientow',
      'czy trener może przypisać mi plan przez aplikację?',
      'jak zaprosić trenera',
      'jak odebrać trenerowi dostęp',
      'gdzie dodać klientów',
      'kaip programėlėje rasti asmeninį trenerį',
      'ar treneris gali matyti mano treniruotes',
      'kaip treneriui pridėti klientą',
      'kaip prisijungti prie savo trenerio programėlėje',
      'mano treneris nori matyti mano įrašus, kaip suteikti prieigą',
      'esu treneris, kaip cia valdyt klientus',
      'ar treneris gali priskirti man programą per programėlę?',
      'kaip pakviesti trenerį',
      'kaip atimti treneriui prieigą',
      'kur pridėti klientus',
      'kuidas äpis personaaltreenerit leida',
      'kas treener näeb mu treeninguid',
      'kuidas treenerina klienti lisada',
      'kuidas äpis oma treeneriga ühenduda',
      'mu treener tahab mu logisid näha, kuidas ligipääsu anda',
      'olen treener, kuidas siin kliente hallata',
      'kas treener saab mulle äpi kaudu kava määrata?',
      'kuidas treenerit kutsuda',
      'kuidas treeneri ligipääs eemaldada',
      'kus kliente lisada',
    ],
    exUk: [
      'як знайти персонального тренера в додатку',
      'чи може тренер бачити мої тренування',
      'як додати клієнта як тренер',
      'чи є в спотері функція тренера',
      'як підключитися до свого тренера в апці',
      'мій тренер хоче бачити мої записи, як дати доступ',
      'як запросити свого тренера',
      'знайти тренера',
      'я персональний тренер, як тут вести клієнтів',
      'чи може тренер призначити мені програму через додаток',
      "як прив'язати акаунт до тренера",
      'найняти тренера в додатку',
      'як тренер бачить що я робив',
      'де додати клієнтів',
      'як забрати доступ у тренера',
      'чи можна отримати тренера через спотер',
      'як працює режим тренера',
      'як додати свого тренера в апку',
      'як тренеру підключити підопічного',
      'как найти тренера в приложении',
      'как добавить клиента тренеру',
      'як тренер може бачить мої трєні тут',
    ],
  },
];

export const INTENTS_APP: Intent[] = APP_TOPICS.map((t) => ({
  id: t.id,
  all: [['__never__']],
  answer: (_c, _p, L) => L(t.answer[0], t.answer[1]),
}));
