/**
 * The canonical question for each topic — used for "did you mean…" chips when
 * a question is only half understood, and for "what can I ask you".
 * Chit-chat (greetings, thanks…) is left out on purpose.
 */
import { NEW_TOPICS } from './kb/topicsNew';
import { APP_TOPICS } from './appTopics';

export const ASKS: Record<string, [string, string]> = {
  // part 1
  pain: ['Something hurts — what do I do?', 'Щось болить — що робити?'],
  rest: ['How long should I rest between sets?', 'Скільки відпочивати між підходами?'],
  next_weight: ['What weight next time on bench?', 'Яку вагу ставити наступного разу на жим?'],
  best: ['What are my best lifts?', 'Які мої рекорди?'],
  progress_lift: ['How is my bench progressing?', 'Як прогресує мій жим?'],
  volume_muscle: ['How many sets for chest this week?', 'Скільки сетів на груди цього тижня?'],
  weak: ['What are my weak points?', 'Які в мене слабкі місця?'],
  recovery: ['Am I recovered?', 'Я відновився?'],
  today: ['What should I train today?', 'Що тренувати сьогодні?'],
  tomorrow: ['What’s tomorrow?', 'Що завтра?'],
  next_session: ['What’s my next session?', 'Яке наступне тренування?'],
  last_session: ['How was my last session?', 'Як пройшло останнє тренування?'],
  week: ['How was my week?', 'Як пройшов тиждень?'],
  streak: ['What’s my streak?', 'Яка в мене серія?'],
  total: ['How many workouts have I done?', 'Скільки всього тренувань?'],
  sleep: ['How does my sleep affect training?', 'Як сон впливає на тренування?'],
  deload: ['When is my deload?', 'Коли розвантаження?'],
  plan: ['What’s my programme?', 'Яка в мене програма?'],
  skip: ['Can I skip today?', 'Можна пропустити сьогодні?'],
  motivation: ['I have no motivation', 'Нема мотивації'],
  warmup: ['How should I warm up?', 'Як розминатися?'],
  cooldown: ['Do I need a cool-down?', 'Чи потрібна заминка?'],
  cardio: ['How much cardio should I do?', 'Скільки кардіо робити?'],
  reps: ['How many reps should I do?', 'Скільки повторів робити?'],
  failure: ['Should I train to failure?', 'Чи тренуватися до відмови?'],
  bodyweight: ['What’s my bodyweight?', 'Яка моя вага?'],
  session_length: ['How long should a workout be?', 'Скільки має тривати тренування?'],
  swap: ['How do I swap an exercise?', 'Як замінити вправу?'],
  technique: ['How do I check my technique?', 'Як перевірити техніку?'],
  protein: ['How much protein do I need?', 'Скільки білка треба?'],
  supplements: ['Should I take creatine?', 'Чи приймати креатин?'],
  temper: ['How do I change your tone?', 'Як змінити твій тон?'],
  who: ['Who are you?', 'Хто ти?'],
  // part 2
  muscle_last: ['When did I last train legs?', 'Коли я востаннє тренував ноги?'],
  lift_last: ['When did I last bench?', 'Коли я востаннє жав лежачи?'],
  lift_count: ['How often do I squat?', 'Як часто я присідаю?'],
  e1rm: ['What’s my estimated max on bench?', 'Який мій розрахунковий максимум у жимі?'],
  tonnage: ['How much did I lift in total this week?', 'Скільки тонн я підняв цього тижня?'],
  muscle_frequency: ['How often should I train chest?', 'Як часто тренувати груди?'],
  days_per_week: ['How many days a week should I train?', 'Скільки днів на тиждень тренуватися?'],
  how_am_i_doing: ['How am I doing?', 'Як мій прогрес?'],
  prs_today: ['Any records today?', 'Є сьогодні рекорди?'],
  plateau: ['I’m stuck — what now?', 'Я застряг — що робити?'],
  injury_status: ['How is my injury?', 'Як моя травма?'],
  overtraining: ['Am I overtraining?', 'Я перетреновуюсь?'],
  train_sore: ['Can I train while sore?', 'Чи можна тренуватися з крепатурою?'],
  weaker_today: ['Why am I weaker today?', 'Чому я сьогодні слабший?'],
  split_choice: ['Which split is best?', 'Який спліт найкращий?'],
  exercises_per_session: ['How many exercises per workout?', 'Скільки вправ за тренування?'],
  compound_isolation: ['Compound or isolation?', 'Базові чи ізолюючі?'],
  machines_free: ['Machines or free weights?', 'Тренажери чи вільні ваги?'],
  superset: ['Should I do supersets?', 'Чи робити суперсети?'],
  dropset: ['What are drop sets?', 'Що таке дропсети?'],
  rpe: ['What is RPE?', 'Що таке RPE?'],
  tempo: ['What tempo should I lift at?', 'У якому темпі робити повтори?'],
  warmup_sets: ['How many warm-up sets?', 'Скільки розминочних підходів?'],
  stretch_before: ['Should I stretch before lifting?', 'Чи розтягуватися перед тренуванням?'],
  mobility: ['How do I improve mobility?', 'Як покращити рухливість?'],
  abs_daily: ['Can I train abs every day?', 'Чи можна качати прес щодня?'],
  grip: ['How do I improve my grip?', 'Як покращити хват?'],
  belt_straps: ['Should I use a belt or straps?', 'Чи потрібен пояс чи лямки?'],
  breathing: ['How should I breathe when lifting?', 'Як дихати під час вправ?'],
  squat_form: ['How deep should I squat?', 'Наскільки глибоко присідати?'],
  results_time: ['When will I see results?', 'Коли буде результат?'],
  muscle_gain_rate: ['How do I build muscle?', 'Як набрати м’язи?'],
  fat_loss: ['How do I lose fat?', 'Як схуднути?'],
  myth_bulky: ['Will lifting make me bulky?', 'Чи стану я занадто великим від ваг?'],
  cardio_gains: ['Does cardio kill gains?', 'Чи кардіо «з’їдає» м’язи?'],
  sick: ['Can I train when sick?', 'Чи тренуватися, коли хворію?'],
  alcohol: ['Does alcohol hurt gains?', 'Чи алкоголь шкодить результатам?'],
  water: ['How much water should I drink?', 'Скільки пити води?'],
  sleep_better: ['How do I sleep better?', 'Як краще спати?'],
  time_of_day: ['Morning or evening training?', 'Тренуватися зранку чи ввечері?'],
  fasted: ['Can I train fasted?', 'Чи можна тренуватися натщесерце?'],
  caffeine: ['Is coffee before the gym ok?', 'Чи можна каву перед залом?'],
  protein_timing: ['When should I drink a protein shake?', 'Коли пити протеїн?'],
  travel: ['How do I train while travelling?', 'Як тренуватися в подорожі?'],
  home: ['Can I train at home?', 'Чи можна тренуватися вдома?'],
  comeback: ['How do I come back after a break?', 'Як повернутися після перерви?'],
  rest_day: ['What should I do on rest days?', 'Що робити в дні відпочинку?'],
  beginner: ['I’m a beginner — where do I start?', 'Я новачок — з чого почати?'],
  shoes: ['What shoes should I lift in?', 'У якому взутті тренуватися?'],
  app_log_set: ['How do I log a set?', 'Як записати підхід?'],
  app_rest_timer: ['How does the rest timer work?', 'Як працює таймер відпочинку?'],
  app_notifications: ['How do I turn on notifications?', 'Як увімкнути сповіщення?'],
  app_turn_off: ['How do I turn you off?', 'Як тебе вимкнути?'],
  app_role: ['Main coach or extra coach?', 'Основний чи додатковий тренер?'],
  app_injury_log: ['How do I log an injury?', 'Як записати травму?'],
  are_you_ai: ['Are you an AI?', 'Ти штучний інтелект?'],
  who_made: ['Who made you?', 'Хто тебе створив?'],
  motivate: ['Motivate me', 'Змотивуй мене'],
  // part 3
  heaviest: ['What’s the heaviest I’ve lifted?', 'Яка найбільша вага, яку я піднімав?'],
  favourite_lift: ['What’s my favourite exercise?', 'Яка моя улюблена вправа?'],
  consistency: ['How consistent am I?', 'Наскільки я регулярний?'],
  best_weekday: ['Which day do I usually train?', 'У які дні я зазвичай тренуюсь?'],
  rest_actual: ['How long do I actually rest?', 'Скільки я насправді відпочиваю?'],
  warmup_habit: ['Do I warm up enough?', 'Чи достатньо я розминаюсь?'],
  cardio_done: ['How much cardio did I do this week?', 'Скільки кардіо я зробив цього тижня?'],
  my_gym: ['Which gym do I go to?', 'У який зал я ходжу?'],
  my_goal: ['What’s my goal?', 'Яка моя мета?'],
  bw_trend: ['Am I gaining or losing weight?', 'Я набираю чи скидаю вагу?'],
  strength_ratio: ['Is my bench strong for my weight?', 'Чи сильний мій жим для моєї ваги?'],
  month: ['How many workouts this month?', 'Скільки тренувань цього місяця?'],
  longest_session: ['What was my longest workout?', 'Яке моє найдовше тренування?'],
  grow_muscle: ['How do I grow my chest?', 'Як накачати груди?'],
  arms: ['My arms aren’t growing', 'Руки не ростуть'],
  add_weight: ['When should I add weight?', 'Коли додавати вагу?'],
  strength_vs_size: ['Strength or size?', 'Сила чи маса?'],
  periodization: ['What is periodization?', 'Що таке періодизація?'],
  unilateral: ['Should I do single-leg work?', 'Чи робити вправи на одну ногу?'],
  pullup_zero: ['I can’t do a pull-up', 'Не можу підтягнутися'],
  squat_vs_press: ['Squat or leg press?', 'Присід чи жим ногами?'],
  incline_flat: ['Incline or flat bench?', 'Похилий чи горизонтальний жим?'],
  foam_roll: ['Is foam rolling useful?', 'Чи корисний масажний ролик?'],
  sauna_cold: ['Sauna or ice bath after the gym?', 'Сауна чи крижана ванна після залу?'],
  nap: ['Do naps help?', 'Чи допомагає денний сон?'],
  stress: ['I’m stressed — should I train?', 'Я в стресі — тренуватися?'],
  bench_alone: ['Can I bench without a spotter?', 'Чи можна жати без страхувальника?'],
  age: ['Am I too old to start?', 'Чи не пізно мені починати?'],
  gym_anxiety: ['I feel awkward at the gym', 'Мені ніяково в залі'],
  app_backfill: ['I forgot to log a workout', 'Забув записати тренування'],
  app_units: ['How do I switch to pounds?', 'Як перейти на фунти?'],
  app_language: ['How do I change the language?', 'Як змінити мову?'],
  app_delete: ['How do I delete a set?', 'Як видалити підхід?'],
  app_playbook: ['What is the Playbook?', 'Що таке Playbook?'],
  app_streak_rules: ['How does the streak work?', 'Як рахується серія?'],
  app_sleep_tracking: ['How does sleep tracking work?', 'Як працює трекінг сну?'],
  // part 4
  plate_math: ['Plates for 100 kg', 'Млинці на 100 кг'],
  reps_at_weight: [
    'How many reps can I do with 80 kg on bench?',
    'Скільки повторів я зроблю з 80 кг у жимі?',
  ],
  percent_max: ['What’s 80% of my bench?', 'Скільки це 80% від мого жиму?'],
  warmup_lift: ['Warm-up sets for squat', 'Розминочні підходи для присіду'],
  exercise_muscles: ['What muscles does the deadlift work?', 'Які м’язи працюють у становій?'],
  alternatives: ['Alternative to bench press', 'Чим замінити жим лежачи'],
  sets_for_lift: ['How many sets of squats?', 'Скільки підходів присіду?'],
  day_lookup: ['What did I do yesterday?', 'Що я робив учора?'],
  compare_weeks: ['This week vs last week', 'Цей тиждень проти минулого'],
  short_on_time: ['I only have 30 minutes', 'Маю лише 30 хвилин'],
  two_days_row: ['Can I train two days in a row?', 'Чи можна тренуватися два дні поспіль?'],
  two_a_day: ['Can I train twice a day?', 'Чи можна тренуватися двічі на день?'],
  health_conditions: ['Can I lift with high blood pressure?', 'Чи можна тягати залізо з тиском?'],
  peds: ['What about steroids?', 'А що зі стероїдами?'],
  cycle: ['How does my cycle affect training?', 'Як цикл впливає на тренування?'],
  pregnancy: ['Can I lift while pregnant?', 'Чи можна тренуватися вагітній?'],
  hr_zones: ['What are heart-rate zones?', 'Що таке пульсові зони?'],
  hiit: ['Is HIIT good?', 'Чи корисний HIIT?'],
  running: ['Can I run and lift?', 'Чи поєднувати біг і зал?'],
  steps: ['How many steps a day?', 'Скільки кроків на день?'],
  posture: ['How do I fix my posture?', 'Як виправити поставу?'],
  other_sport: ['How should I lift for football?', 'Як тренуватися в залі для футболу?'],
  home_equipment: ['What should I buy for a home gym?', 'Що купити для домашнього залу?'],
  what_can_i_ask: ['What can I ask you?', 'Що в тебе можна спитати?'],
  reminder: ['Remind me to train', 'Нагадай потренуватися'],
  // part 5
  memory_show: ['What do you know about me?', 'Що ти про мене знаєш?'],
  memory_forget: ['Forget what I told you', 'Забудь, що я казав'],
  act_rest: ['Set bench rest to 3 minutes', 'Постав відпочинок на жим 3 хв'],
  act_swap: ['Swap bench for dumbbell press', 'Заміни жим на жим гантелей'],
  act_avoid: ['Remove lunges from my plan', 'Прибери випади з плану'],
  act_move: ['Move legs to Thursday', 'Перенеси ноги на четвер'],
  act_start: ['Start today’s workout', 'Почни сьогоднішнє тренування'],
  act_temper: ['Be nicer', 'Будь м’якше'],
  act_mute: ['Mute notifications today', 'Не пиши сьогодні'],
  act_bodyweight: ['I weigh 82 kg', 'Я важу 82 кг'],
  range_count: [
    'How many workouts in the last 3 months?',
    'Скільки тренувань за останні 3 місяці?',
  ],
  range_summary: ['Summary of last month', 'Підсумок минулого місяця'],
  range_lift: ['Bench progress since June', 'Прогрес жиму з червня'],
  range_muscle: ['Chest sets this month', 'Сети на груди цього місяця'],
  range_bw: ['Bodyweight over the last 2 months', 'Вага за останні 2 місяці'],
  then_vs_now: ['Am I stronger than 3 months ago?', 'Чи я сильніший, ніж 3 місяці тому?'],
  compare_lifts: ['Bench vs squat', 'Жим чи присід — що відстає?'],
  why_today: ['Why this workout today?', 'Чому сьогодні саме це?'],
  why_weight: ['Why this weight on bench?', 'Чому така вага на жимі?'],
  why_plan: ['Why this programme?', 'Чому така програма?'],
  why_lift: ['Why is squat in my plan?', 'Чому присід у моєму плані?'],
  // part 6
  technique_lift: ['How to squat properly?', 'Як правильно присідати?'],
  pain_types: [
    'Sharp or dull pain — what’s the difference?',
    'Гострий чи тупий біль — у чому різниця?',
  ],
  return_injury: ['When can I train after an injury?', 'Коли тренуватися після травми?'],
  ice_heat: ['Ice or heat?', 'Лід чи тепло?'],
  painkillers: ['Can I take painkillers and train?', 'Чи можна тренуватися на знеболювальних?'],
  tendon: ['What helps tendon pain?', 'Що допомагає при болі в сухожиллі?'],
  cramps: ['Why do I get cramps?', 'Чому зводить м’язи?'],
  numbness: ['My hand goes numb', 'Німіє рука'],
  calories: ['How many calories do I need?', 'Скільки калорій мені треба?'],
  cut_deficit: ['How big a deficit?', 'Який дефіцит калорій?'],
  bulk_surplus: ['How big a surplus to bulk?', 'Який профіцит для набору?'],
  carbs: ['How many carbs?', 'Скільки вуглеводів?'],
  fats: ['How much fat should I eat?', 'Скільки жирів їсти?'],
  pre_meal: ['What to eat before the gym?', 'Що їсти перед залом?'],
  post_meal: ['What to eat after the gym?', 'Що їсти після залу?'],
  meals_count: ['How many meals a day?', 'Скільки разів на день їсти?'],
  vegan: ['Can I build muscle as a vegan?', 'Чи можна набрати м’язи на рослинному харчуванні?'],
  cheat_meal: ['Is a cheat meal ok?', 'Чи можна читміл?'],
  sugar: ['Is sugar bad?', 'Чи шкідливий цукор?'],
  late_eating: ['Is eating late bad?', 'Чи погано їсти пізно?'],
  electrolytes: ['Do I need electrolytes?', 'Чи потрібні електроліти?'],
  fiber: ['How much fibre?', 'Скільки клітковини?'],
};

// Topics added later bring their own canonical question.
for (const t of NEW_TOPICS) ASKS[t.id] ??= t.ask;
for (const t of APP_TOPICS) ASKS[t.id] ??= t.ask;
