/**
 * Topics added from the knowledge files as whole units: understood by example,
 * plus a keyword rule for the words that only this topic uses (chalk, Smith,
 * sumo…), answered from the file, with its own deeper layers.
 */
import type { Intent } from './intentKit';
import { NEW_TOPICS } from './kb/topicsNew';

const BENCH = ['bench*', 'жим*', 'жати', 'лав*'];
const KEYS: Record<string, string[][]> = {
  k_bench_arch: [['arch', 'arching', 'arched', 'прогин*', 'прогина*', 'вигина*', 'місток'], BENCH],
  k_deadlift_rounding: [
    ['round*', 'curved', 'горб*', 'округл*', 'кругл*', 'question mark', 'знак питання'],
    ['deadlift*', 'станов*', 'тяг*', 'pull*', 'from the floor', 'з підлоги'],
  ],
  k_knees_cave: [
    [
      'cave',
      'caving',
      'knees in',
      'valgus',
      'вальгус',
      'всередину',
      'одне до одного',
      'зводяться',
      'завалюються',
    ],
    ['knee*', 'колін*'],
  ],
  k_butt_wink: [
    [
      'butt wink',
      'buttwink',
      'баттвінк',
      'підкручу*',
      'tuck* under',
      'pelvis tuck*',
      'таз підкручу*',
    ],
  ],
  k_ohp_lean: [
    ['lean*', 'відхиля*', 'відкида*', 'arch*', 'прогин*', 'місток', 'lower back', 'поперек*'],
    [
      'ohp',
      'overhead',
      'military',
      'армійськ*',
      'над головою',
      'жим стоячи',
      'жимі стоячи',
      'standing press',
    ],
  ],
  k_sumo_conventional: [['sumo', 'сумо']],
  k_sleeves_wraps: [
    ['sleeve*', 'wraps', 'wrist wraps', 'knee wraps', 'наколінник*', 'бинт*', 'неопрен*'],
  ],
  k_chalk: [
    [
      'chalk',
      'магнезі*',
      'крейд*',
      'white powder',
      'білий порошок',
      'sweaty palms',
      'мокрі долоні',
      'долоні мокрі',
      'пітніють долоні',
    ],
  ],
  k_smith_machine: [['smith', 'сміт*', 'rails', 'на рейках', 'напрямн*']],
  k_test_max: [
    [
      'test',
      'testing',
      'перевірити',
      'протестувати',
      'протестую',
      'як підійти',
      'how to approach',
      'attempt',
      'спробувати',
    ],
    [
      'one rep max',
      '1rm',
      '1пм',
      'heavy single',
      'max single',
      'одиночн*',
      'на один раз',
      'максимум',
    ],
  ],
  k_shift_work: [
    ['night shift*', 'shift work', 'shifts', 'нічн* змін*', 'змін*', 'позмінн*', 'графік змін'],
  ],
  k_maintenance: [
    [
      'maintain',
      'maintenance',
      'keep my muscle',
      'не втратити',
      'підтримувати',
      'підтримка',
      'зберегти м*язи',
    ],
  ],
  k_holidays: [
    [
      'holiday*',
      'vacation',
      'christmas',
      'new year',
      'відпустк*',
      'свят*',
      'новий рік',
      'канікул*',
    ],
  ],
  k_heat: [
    ['heat', 'hot weather', 'heatwave', 'спек*', 'жар*', 'жарко', 'без кондиціонера', 'no air con'],
  ],
  k_teen_lifting: [
    ['teen*', 'teenager', 'підліт*', '14', '15', '16', 'school', 'школяр*'],
    ['lift*', 'train*', 'gym', 'трен*', 'зал*', 'штанг*', 'ріст', 'growth', 'stunt*'],
  ],
  k_older_lifter: [
    [
      '50',
      '55',
      '60',
      '65',
      '70',
      'older',
      'senior',
      'пенсі*',
      'літн*',
      'старш*',
      'після 50',
      'after 50',
      'over 50',
      'over 60',
    ],
  ],
  k_women_training: [['woman', 'women', 'female', 'girl', 'girls', 'жінк*', 'дівчат*', 'дівчин*']],
  k_pushup_progression: [
    ['push-up*', 'pushup*', 'push up', 'push ups', 'віджиман*', 'віджатися', 'віджимат*'],
  ],
  k_etiquette: [
    [
      'etiquette',
      'rude',
      'unwritten rules',
      'rerack',
      're-rack',
      'етикет*',
      'неписан* правил*',
      'грубо',
      'ввічлив*',
      'займати тренажер',
    ],
  ],
  k_beta_alanine: [
    ['beta alanine', 'beta-alanine', 'бета аланін', 'бета-аланін', 'tingl*', 'поколюван*'],
  ],
  k_fish_oil: [
    ['fish oil', 'omega*', 'омега*', "риб'ячий жир", 'рибячий жир', 'риб*ячий', 'epa', 'dha'],
  ],
  k_preworkout: [['pre-workout', 'preworkout', 'pre workout', 'предтрен*', 'передтрен*']],
  k_bcaa: [['bcaa', 'bcaas', 'бцаа', 'амінокислот*', 'amino*', 'eaa', 'eaas']],
  k_core_stability: [
    [
      'core',
      'кор',
      'корпус*',
      'bracing',
      'brace',
      'стабіліз*',
      'anti-rotation',
      'plank*',
      'планк*',
    ],
  ],
  k_ankle_mobility: [
    [
      'ankle*',
      'гомілкостоп*',
      'щиколот*',
      'dorsiflexion',
      'п*ятки відрива*',
      'heels come up',
      'heels lift',
    ],
  ],
  k_gassed: [
    ['gassed', 'out of breath', 'winded', 'задиха*', 'задишк*', 'видихаюсь', 'сдихаю'],
    ['set*', 'сет*', 'підход*', 'squat*', 'присід*', 'high rep*', 'багатоповтор*'],
  ],
  k_sticking_point: [
    [
      'sticking point',
      'stuck halfway',
      'mid-range',
      'мертв* точк*',
      'застряга* посередині',
      'на середині',
      'halfway',
    ],
  ],
  k_more_pullups: [
    [
      'pull-up*',
      'pullup*',
      'pull up*',
      'chin-up*',
      'chinup*',
      'підтягуван*',
      'підтягнутися',
      'підтягуватися',
    ],
    [
      'more',
      'improve',
      'increase',
      'first',
      'більше',
      'покращити',
      'збільшити',
      'перше',
      'хоча б',
      'навчитися',
    ],
  ],
  k_mind_muscle: [
    [
      'mind muscle',
      'mind-muscle',
      'feel the muscle',
      "can't feel",
      'cant feel',
      'не відчуваю',
      'відчувати м*яз*',
      'зв*язок м*яз*',
    ],
  ],
  k_partial_reps: [
    [
      'partial*',
      'half rep*',
      'lengthened partial*',
      'частков* амплітуд*',
      'неповн* амплітуд*',
      'напівповтор*',
      'партіал*',
    ],
  ],
  k_bands: [['band*', 'резинк*', 'стрічк*', 'еспандер*', 'mini band', 'resistance band*']],
  k_kettlebell_swing: [
    ['swing*', 'свінг*', 'мах* гир*', 'махи з гирею'],
    ['kettlebell*', 'kb', 'гир*', 'свінг*', 'swing*'],
  ],
  k_program_hopping: [
    [
      'program hopping',
      'switch program*',
      'change program*',
      'new program',
      'змінювати програм*',
      'міняти програм*',
      'нову програму',
      'перескакую',
      'стрибаю між',
    ],
  ],
  k_cardio_order: [
    ['cardio', 'кардіо', 'run', 'біг*'],
    ['before', 'after', 'до', 'після', 'first', 'спочатку', 'order', 'порядок'],
  ],
  k_exercise_order: [
    ['order', 'порядок', 'first', 'спочатку', 'which comes first', 'що першим', 'послідовн*'],
    ['exercise*', 'вправ*', 'lift*', 'compound*', 'isolation', 'базов*', 'ізоляц*'],
  ],
  k_imbalance: [
    [
      'imbalance',
      'uneven',
      'one side',
      'left side',
      'right side',
      'weaker side',
      'дисбаланс*',
      'одна сторона',
      'ліва',
      'права',
      'слабша сторона',
      'асиметрі*',
      'asymmetr*',
    ],
  ],
  k_knees_over_toes: [
    [
      'over toes',
      'past toes',
      'past my toes',
      'over my toes',
      'за носки',
      'за пальці',
      'за шкарпетки',
      'виходять за носк*',
    ],
  ],
  k_bail_squat: [
    [
      'bail',
      'bailing',
      'dump the bar',
      'fail a squat',
      'failed squat',
      'скинути штангу',
      'кинути штангу',
      'завалив присід',
      'не встав',
      'не встану',
      'застряг внизу',
      'safety pins',
      'страхувальн* упори',
      'упори',
      'стійки',
    ],
  ],
  k_personal_trainer: [
    ['personal trainer', 'pt', 'coach', 'персональн* тренер*', 'тренер*', 'найняти'],
    ['hire', 'worth', 'need', 'pay', 'варто', 'найняти', 'потрібен', 'платити', 'сенс'],
  ],
  k_row_lower_back: [
    ['row*', 'тяга в нахилі', 'тягу в нахилі', 'тязі в нахилі', 'bent-over', 'bent over'],
    ['lower back', 'поперек*', 'back', 'спин*'],
  ],
};

export const INTENTS_NEW: Intent[] = NEW_TOPICS.map((t) => ({
  id: t.id,
  all: KEYS[t.id] ?? [['__never__']],
  answer: (_c, _p, L) => L(t.answer[0], t.answer[1]),
  more: (_c, _p, L, depth) => (t.more[depth] ? L(t.more[depth][0], t.more[depth][1]) : null),
}));
