/**
 * The hundred topics of kb/topicsMore.ts as intents: understood by example,
 * plus a keyword rule for the words only that topic uses (AMRAP, EMOM,
 * myo-reps, Nordic curl…), answered from the file with one deeper layer and
 * chips to related topics. Keywords stay narrow on purpose: a loose one
 * ("good morning", "shake", "bodyweight") would pull other topics' questions.
 */
import type { Intent } from './intentKit';
import { MORE_TOPICS } from './kb/topicsMore';
import { ASKS } from './asks';

const CREATINE = ['creatin*', 'креатин*', 'kreatyn*', 'kreatin*'];
const PROTEIN_WORDS = [
  'protein',
  'whey',
  'білк*',
  'белк*',
  'протеїн*',
  'протеин*',
  'białk*',
  'baltym*',
  'valku',
  'valk',
];

const KEYS: Record<string, string[][]> = {
  k_amrap: [['amrap', 'амрап*', 'as many reps as possible']],
  k_emom: [['emom', 'емом', 'every minute on the minute']],
  k_cluster_sets: [['cluster', 'clusters', 'кластер*', 'klastr*', 'klaster*']],
  k_rest_pause: [['rest pause', 'restpause', 'рест пауз*', 'рестпауз*']],
  k_myo_reps: [['myo', 'myoreps', 'міо', 'мио', 'міорепс*']],
  k_double_progression: [['double progression', 'подвійна прогресія', 'подвійну прогресію']],
  k_taper: [['taper*', 'peaking', 'підводк*', 'подводк*']],
  k_top_backoff: [['top set', 'back off', 'backoff', 'топ сет*', 'бек оф', 'бекоф']],
  k_paused_reps: [
    ['pause', 'paused', 'пауз*'],
    ['squat*', 'bench*', 'deadlift*', 'присід*', 'присідан*', 'жим*', 'станов*'],
  ],
  k_eccentrics: [
    [
      'negatives',
      'eccentric*',
      'негатив*',
      'ексцентр*',
      'эксцентр*',
      'negatyw*',
      'negatyv*',
      'negatiiv*',
    ],
  ],
  k_volume_landmarks: [
    [
      'mev',
      'mrv',
      'мев',
      'мрв',
      'maximum recoverable',
      'minimum effective volume',
      'too many sets',
      'too much volume',
      'junk volume',
      'забагато підходів',
      'забагато сетів',
      'слишком много подходов',
      'za dużo serii',
      'per daug serijų',
      'liiga palju seeriaid',
    ],
  ],
  k_bfr: [
    [
      'bfr',
      'occlusion',
      'kaatsu',
      'blood flow restriction',
      'оклюз*',
      'окклюз*',
      'обмеженням кровотоку',
    ],
  ],
  k_5x5: [['5x5', 'stronglifts', 'стронгліфтс', 'стронглифтс', 'madcow', '5х5']],
  k_531: [['531', '5 3 1', 'wendler*', 'вендлер*', 'boring but big']],
  k_circuit_training: [['circuit*', 'кругов*', 'obwod*']],
  k_plyometrics: [
    [
      'plyo*',
      'box jump*',
      'пліометр*',
      'плиометр*',
      'тумбу',
      'тумбі',
      'skrzyni*',
      'pliometr*',
      'plüomeetri*',
    ],
  ],
  k_front_squat: [['front squat*', 'фронтальн*', 'eeskük*', 'przysiad przedni']],
  k_hip_thrust: [
    [
      'hip thrust*',
      'хіп траст*',
      'хип траст*',
      'ягідний місток',
      'сідничний міст',
      'ягодичный мост',
    ],
  ],
  k_rdl: [
    ['rdl', 'romanian', 'румунськ*', 'румынск*', 'румунк*', 'rumuń*', 'rumuniš*', 'rumeenia'],
  ],
  k_bulgarian_split: [
    ['bulgarian*', 'болгарськ*', 'болгарк*', 'болгарск*', 'bułgar*', 'bulgariš*', 'bulgaaria'],
  ],
  k_lunges: [['lunge*', 'lunging', 'випад*', 'выпад*', 'wykrok*', 'įtupst*', 'väljaaste*']],
  k_dips: [['dips', 'dipy', 'бруси', 'брусах', 'брусья', 'брусьях', 'poręcz*', 'lygiagreč*']],
  k_face_pull: [
    ['face pull*', 'facepull*', 'фейс пул*', 'фейспул*', 'канату до обличчя', 'каната к лицу'],
  ],
  k_lateral_raise: [['lateral raise*', 'side raise*', 'махи', 'махів', 'wznos* bokiem']],
  k_chinup_vs_pullup: [
    ['chin up*', 'chinup*', 'chin ups', 'зворотн* хват*', 'обратн* хват*', 'podchwyt*'],
  ],
  k_bench_grip: [
    ['grip', 'хват', 'хвату', 'chwyt*'],
    ['bench', 'жим лежачи', 'жимі лежачи', 'жиме лежа', 'ławce'],
  ],
  k_leg_drive: [
    [
      'leg drive',
      'робота ногами',
      'работа ногами',
      'упиратися ногами',
      'працювати ногами',
      'працюють ноги',
      'praca nóg',
      'kojų darb*',
      'jalgade töö',
    ],
  ],
  k_high_low_bar: [
    ['low bar', 'high bar', 'lowbar', 'highbar', 'низьк* гриф*', 'висок* гриф*', 'лоу бар'],
  ],
  k_good_morning: [['гуд морнінг*', 'гуд морнинг*']],
  k_farmer_carry: [['farmer*', 'suitcase carry', 'loaded carr*', 'фермер*', 'farmera']],
  k_calves: [['calf', 'calves', 'литк*', 'икр*', 'łyd*', 'blauzd*']],
  k_trap_bar: [['trap bar', 'hex bar', 'трап гриф*', 'шестикутн* гриф*', 'трэп гриф*']],
  k_nordic_curl: [['nordic*', 'нордик*', 'нордичн*', 'нордическ*']],
  k_pistol_squat: [['pistol squat*', 'пістолетик*', 'пистолетик*', 'pistolet*']],
  k_no_soreness: [
    ['not sore', 'no soreness', 'no doms', 'не крепатур*', 'нема крепатури', 'не болят мышцы'],
  ],
  k_massage_gun: [
    ['massage gun*', 'theragun*', 'percussion', 'масажн* пістолет*', 'массажн* пистолет*'],
  ],
  k_wearables: [['hrv', 'whoop', 'oura', 'body battery', 'пульс спокою', 'resting heart rate']],
  k_cns_fatigue: [['cns', 'цнс', 'nervous system', 'нервов* систем*']],
  k_detraining: [
    [
      'muscle memory',
      'мязова память',
      'мышечная память',
      'detrain*',
      'stop training',
      'stop lifting',
      'month off',
      'weeks off',
      'перестану тренуватися',
      'pamięć mięśniowa',
      'stracę mięśnie',
      'miesiąc przerwy',
      'przerwa od siłowni',
      'теряются мышцы',
      'потеряю мышцы',
      'теряю мышцы',
      'мышцы уйдут',
      'втрачу мʼязи',
      'втрачу мязи',
      'втрачу м’язи',
      'втрачаються мʼязи',
      'prarandu raumen*',
      'prarasiu raumen*',
      'kaotan lihas*',
      'raumenų atmint*',
      'lihasmälu',
    ],
  ],
  k_joint_supplements: [
    [
      'glucosamine',
      'chondroitin',
      'collagen',
      'глюкозамін*',
      'глюкозамин*',
      'хондроїтин*',
      'колаген*',
      'коллаген*',
    ],
  ],
  k_creatine_myths: [
    CREATINE,
    [
      'hair',
      'bald*',
      'bloat*',
      'kidney*',
      'side effect*',
      'волосся',
      'волос*',
      'нирк*',
      'почк*',
      'набряк*',
      'nerk*',
      'włos*',
      'wzdęc*',
      'inkst*',
      'plauk*',
      'neer*',
      'juuks*',
    ],
  ],
  k_protein_powder: [
    ['whey', 'isolate', 'сироватк*', 'ізолят*', 'protein powder'],
    ['buy', 'best', 'which', 'купити', 'купить', 'який', 'кращий', 'or'],
  ],
  k_protein_per_meal: [
    [
      'absorb*',
      'засвою*',
      'усваива*',
      'per meal',
      'one sitting',
      'at once',
      'за раз',
      'за один прийом',
      'przyswaja*',
      'na raz',
      'pasisavin*',
      'per kartą',
      'imendu*',
      'korraga',
    ],
    PROTEIN_WORDS,
  ],
  k_intra_workout: [
    [
      'intra',
      'during my workout',
      'during workout',
      'during training',
      'під час тренування',
      'во время тренировки',
    ],
    ['drink*', 'пити', 'пить', 'напій*', 'carbs', 'вуглевод*', 'ізотонік*'],
  ],
  k_vitamin_d: [['vitamin d', 'вітамін d', 'вітамін д', 'витамин д', 'witamin* d']],
  k_magnesium: [['magnesium', 'zma', 'магній', 'магнію', 'магний', 'magnez*']],
  k_test_boosters: [['booster*', 'tribulus', 'ashwagandha', 'бустер*', 'трибулус', 'ашваганд*']],
  k_fat_burners: [
    ['fat burner*', 'thermogenic*', 'жироспалюв*', 'жиросжигат*', 'carnitine', 'карнітин*'],
  ],
  k_reverse_diet: [
    [
      'reverse diet*',
      'reverse dieting',
      'реверсивн*',
      'виходити з сушки',
      'вийти з сушки',
      'вихід з сушки',
      'выходить из сушки',
      'выйти из сушки',
      'wyjść z redukcji',
    ],
  ],
  k_diet_break: [['refeed*', 'diet break', 'рефід*', 'рефид*', 'перерву в дієті']],
  k_scale_fluctuations: [['fluctuat*', 'скаче', 'скачет', 'стрибає', 'коливан*', 'колебан*']],
  k_keto: [['keto', 'ketogenic', 'кето']],
  k_intermittent_fasting: [
    ['intermittent', 'інтервальн* голодув*', 'интервальн* голодан*', '16:8'],
  ],
  k_teen_supplements: [
    [
      'teen*',
      'підлітк*',
      'подрост*',
      'nastolat*',
      'paaugl*',
      'teismeli*',
      '14 year old',
      '15 year old',
      '16 year old',
      '17 year old',
      'мені 14',
      'мені 15',
      'мені 16',
      'мені 17',
      'im 14',
      'im 15',
      'im 16',
      'im 17',
    ],
    [...CREATINE, ...PROTEIN_WORDS, 'добавк*', 'supplement*'],
  ],
  k_vo2max: [['vo2max', 'vo2', 'мпк']],
  k_incline_walk: [
    ['incline', 'нахилом', 'stairmaster', 'степер*', '12 3 30'],
    ['walk*', 'ходьб*', 'treadmill', 'доріжц*', 'stairmaster', 'степер*', '12 3 30'],
  ],
  k_rowing_machine: [
    [
      'rowing machine',
      'rower',
      'erg',
      'concept2',
      'гребн* тренажер*',
      'гребл*',
      'ergomet*',
      'веслува*',
      'весла',
      'гребн*',
      'irklav*',
      'irklu*',
      'soudeergo*',
      'sõudeergo*',
      'soudmis*',
      'sõudmis*',
    ],
  ],
  k_jump_rope: [
    ['jump rope', 'skipping rope', 'jumping rope', 'скакалк*', 'skakank*', 'šokdyn*', 'hüppenöör*'],
  ],
  k_thoracic: [['thoracic', 't spine', 'upper back', 'грудн* відділ*', 'грудн* отдел*']],
  k_hip_flexors: [['hip flexor*', 'psoas', 'згинач* стегна', 'псоас', 'сгибател* бедра']],
  k_hamstring_flex: [
    ['touch my toes', 'touch toes', 'дістаю до пальців', 'дістати руками', 'не достаю'],
  ],
  k_shoulder_warmup: [
    ['warm up', 'warmup', 'розімя*', 'розминк*', 'разминк*'],
    ['shoulder', 'shoulders', 'плечі', 'плечей', 'плеч'],
  ],
  k_wrist_mobility: [
    [
      'wrist',
      'wrists',
      'запястя',
      'запястях',
      'запястья',
      'nadgarst*',
      'riešus',
      'riešai',
      'randm*',
    ],
    [
      'hurt*',
      'pain',
      'mobility',
      'болять',
      'болят',
      'болить',
      'біль',
      'рухлив*',
      'bolą',
      'skauda',
      'valut*',
    ],
  ],
  k_yoga: [['yoga', 'йога', 'йогу', 'йоги', 'йогою', 'joga', 'jooga']],
  k_pilates: [['pilates', 'пілатес*', 'пилатес*', 'reformer', 'реформер*']],
  k_gloves: [
    ['glove*', 'рукавичк*', 'рукавиц*', 'перчатк*', 'rękawiczk*', 'pirštin*', 'kindad', 'kinnas*'],
  ],
  k_bar_weight: [
    ['barbell', 'гриф', 'грифа', 'empty bar', 'olympic bar', 'ez bar', 'gryf'],
    ['weigh', 'weighs', 'важить', 'весит', 'waży', 'sveria', 'kaalub'],
  ],
  k_weight_vest: [['vest', 'жилет*', 'kamizelk*', 'liemen*']],
  k_spotting_others: [
    [
      'spot someone',
      'spot a friend',
      'spot my friend',
      'spot my buddy',
      'spot him',
      'spot her',
      'spot his',
      'spot them',
      'spotting someone',
      'good spotter',
      'страхувати',
      'пострахувати',
      'страховать',
      'asekur*',
      'julgesta*',
    ],
  ],
  k_busy_gym: [['packed', 'crowded', 'work in', 'переповнен*', 'людно', 'толпа']],
  k_gym_bag: [
    ['gym bag', 'bring to the gym', 'брати з собою', 'що взяти в', 'сумк*', 'брать в зал'],
  ],
  k_film_form: [
    [
      'film myself',
      'filming',
      'record myself',
      'record my lifts',
      'знімати себе',
      'зняти себе',
      'снимать себя',
      'nagrywa*',
      'nagrać',
      'nagrać się',
      'się nagrać',
      'filmuo*',
      'filmida',
    ],
  ],
  k_calisthenics: [
    [
      'calisthenics',
      'bodyweight exercise*',
      'bodyweight workout*',
      'власною вагою',
      'собственным весом',
      'калістенік*',
      'калистеник*',
      'masą ciała',
      'kehakaal*',
    ],
  ],
  k_menopause: [['menopaus*', 'perimenopaus*', 'менопауз*', 'клімакс*', 'климакс*']],
  k_postpartum: [
    [
      'postpartum',
      'giving birth',
      'after baby',
      'c section',
      'пологів',
      'родов',
      'кесарев*',
      'діастаз*',
      'diastasis',
      'porodzie',
      'gimdymo',
      'sünnitus*',
    ],
  ],
  k_pelvic_floor: [
    [
      'leak when',
      'leaking',
      'i leak',
      'pee a little',
      'i pee',
      'peeing',
      'wet myself',
      'pelvic floor',
      'підтіка*',
      'подтека*',
      'тазове дно',
      'нетриман*',
      'popuszcza*',
    ],
  ],
  k_osteoporosis: [
    ['osteopor*', 'osteopeni*', 'bone density', 'остеопор*', 'остеопен*', 'щільність кісток'],
  ],
  k_arthritis: [
    ['arthritis', 'osteoarthritis', 'артроз*', 'артрит*', 'гонартроз*', 'artroz*', 'artrit*'],
  ],
  k_habit: [['habit', 'звичк*', 'привычк*', 'nawyk*', 'įprot*', 'harjumus*']],
  k_program_boredom: [
    [
      'bored of',
      'boring',
      'набридли',
      'набридло',
      'нудно',
      'надоели',
      'nudzą',
      'nusibodo',
      'igav*',
    ],
  ],
  k_comparison: [
    ['comparing', 'compare myself', 'порівнюю', 'сравниваю', 'porównuję', 'lyginu', 'võrdlen'],
  ],
  k_psych_up: [['psych*', 'mentally', 'visualiz*', 'психологічно', 'налаштуватися', 'настроиться']],
  k_fear_heavy: [
    ['scared', 'afraid', 'fear', 'боюся', 'боюсь', 'страшно', 'boję', 'bijau', 'kardan'],
    [
      'dużego',
      'heavy',
      'weights',
      'важк*',
      'вагу',
      'ваг',
      'весов',
      'штанг*',
      'ciężar*',
      'svor*',
      'raskus*',
      'fail*',
      'провал*',
      'застрягти',
    ],
  ],
  k_dance: [
    ['dance', 'dancer*', 'dancing', 'ballet', 'танц*', 'балет*', 'tańcz*', 'šoku', 'tants*'],
    [
      'lift*',
      'gym',
      'strength',
      'weights',
      'combine',
      'силов*',
      'зал',
      'залом',
      'поєднати',
      'совмещать',
      'siłown*',
      'sporto',
      'jõusaal*',
    ],
  ],
  k_progress_photos: [
    [
      'progress photo*',
      'progress pic*',
      'progress picture*',
      'фото прогресу',
      'фото прогресса',
      'before and after',
      'до і після',
      'zdjęcia postęp*',
      'progreso nuotrauk*',
      'progressipilt*',
    ],
  ],
  k_measurements: [
    ['measurements', 'замір*', 'замер*', 'pomiar*', 'matmen*', 'kehamõõt*', 'tape measure'],
  ],
  k_body_fat: [
    [
      'body fat percent*',
      'bodyfat percent*',
      'fat percentage',
      'dexa',
      'caliper*',
      'відсоток жиру',
      'процент жира',
      'калипер*',
      'каліпер*',
      'tkanki tłuszczowej',
      'keharasva',
    ],
  ],
  k_bmi: [['bmi', 'імт', 'имт', 'body mass index', 'індекс маси тіла', 'kmi']],
  k_recomp: [
    [
      'recomp*',
      'рекомп*',
      'skinny fat',
      'скінні фет',
      'худий але з жирком',
      'lose fat and build muscle',
      'build muscle and lose fat',
      'muscle and lose fat',
      'fat and gain muscle',
      'fat and build muscle',
      'gain muscle and lose fat',
      'скидати жир і набирати',
      'худнути і набирати',
      'схуднути і набрати',
      'худнути і качатися',
      'похудеть и набрать',
      'худеть и набирать',
      'schudnąć i zbudować',
      'numesti ir priaugti',
      'kaalust alla ja lihaseid',
      'rekompozy*',
    ],
  ],
  k_mini_cut: [['mini cut', 'minicut', 'міні сушк*', 'мини сушк*', 'міні кат']],
  k_climbing: [
    [
      'rock climbing',
      'climbing',
      'bouldering',
      'boulder',
      'скелелаз*',
      'скалолаз*',
      'боулдер*',
      'лазіння',
      'wspinacz*',
      'laipioj*',
      'ronim*',
    ],
  ],
  k_muscle_fibers: [
    ['twitch', 'muscle fibers', 'muscle fibres', 'волокн*', 'włókna', 'skaidul*', 'lihaskiud*'],
  ],
  k_rotator_cuff: [
    ['rotator*', 'ротатор*', 'external rotation', 'зовнішня ротація', 'ротаторн* манжет*'],
  ],
  k_delt_heads: [
    ['delt', 'delts', 'deltoid*', 'дельт*'],
    ['head*', 'пучк*', 'пучок', 'rear', 'front', 'задн*', 'передн*', 'three', 'три'],
  ],
  k_ego_lifting: [['ego', 'эго', 'его ліфтинг', 'его лифтинг']],
  k_skip_legs: [
    [
      'skip leg*',
      'skipping leg*',
      'skipped leg*',
      'never train legs',
      'не качати ноги',
      'не качать ноги',
      'пропускати ноги',
      'пропускать ноги',
    ],
  ],
  k_nausea: [
    [
      'нудить після',
      'тошнит после',
      'nauseous after',
      'nausea',
      'nauseous',
      'throw up',
      'throwing up',
      'puke',
      'нудить',
      'нудота',
      'тошнит',
      'блювати',
      'mdli',
      'pykina',
      'iiveldus',
    ],
  ],
  k_shaking: [
    [
      'shaking',
      'shaky',
      'trembl*',
      'тремт*',
      'трусяться',
      'трусятся',
      'дрижать',
      'трясутся',
      'drżą',
      'dreba',
      'värise*',
    ],
  ],
  k_joint_clicking: [
    [
      'clicking',
      'clicks',
      'crack',
      'cracking',
      'cracks',
      'popping',
      'клацає',
      'клацають',
      'хрустять',
      'хрустит',
      'хруст',
      'strzelaj*',
      'spragsi',
      'naksu*',
    ],
    [
      'joint*',
      'knee*',
      'shoulder*',
      'hip*',
      'суглоб*',
      'колін*',
      'плеч*',
      'сустав*',
      'stawy',
      'kolan*',
      'sąnari*',
      'kel*',
      'liiges*',
      'põlv*',
    ],
  ],
  k_stretch_marks: [
    ['stretch marks', 'розтяжк*', 'растяжк*', 'rozstęp*', 'tempimo žym*', 'venitusarm*'],
  ],
};

// Their canonical questions (registered here: asks.ts is imported above).
for (const t of MORE_TOPICS) ASKS[t.id] ??= t.ask;

/**
 * Keywords spelled the way messages are normalised (nlu.normalize): accents
 * dropped (ę → e, š → s, ū → u), ¨ kept (ä, ü), apostrophes gone.
 */
export function keyForm(k: string): string {
  return k
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, (m) => (m === '̈' || m === '̆' ? m : ''))
    .normalize('NFC')
    .replace(/[’'`ʼ]/g, '');
}
export const keyGroups = (gs: string[][]): string[][] =>
  gs.map((g) => [...new Set(g.flatMap((k) => [k, keyForm(k)]))]);

export const INTENTS_EXTRA: Intent[] = MORE_TOPICS.map((t) => ({
  id: t.id,
  all: keyGroups(KEYS[t.id] ?? [['__never__']]),
  answer: (_c, _p, L) => L(t.answer[0], t.answer[1]),
  more: (_c, _p, L, depth) => (t.more[depth] ? L(t.more[depth][0], t.more[depth][1]) : null),
  suggest: (L) =>
    t.chips.flatMap((id) => {
      const a = ASKS[id];
      return a ? [L(a[0], a[1])] : [];
    }),
}));
