/**
 * Localized exercise names (uk/pl/lt/et), keyed by the canonical English name.
 * English is always the stored identity; these are display-only. Names we
 * cannot localize idiomatically are simply absent — the app then shows English.
 *
 * Data is generated by scripts/exname_compose.py (idiomatic composer + idiom
 * overrides). Regenerate that script rather than hand-editing the JSON.
 */
import RAW from './exerciseNames.generated.json';
import { canonicalExerciseName } from './exercises';
import type { LocaleId } from '../i18n';

type Tr = Partial<Record<Exclude<LocaleId, 'en'>, string>>;
const MAP = RAW as Record<string, Tr>;
const NON_EN: Exclude<LocaleId, 'en'>[] = ['uk', 'pl', 'lt', 'et'];

/** The localized name for a locale, or null when none exists / locale is en. */
export function localizedExerciseName(name: string, locale: LocaleId): string | null {
  if (locale === 'en') return null;
  const eng = canonicalExerciseName(name);
  return MAP[eng]?.[locale as Exclude<LocaleId, 'en'>] ?? null;
}

/**
 * How an exercise name should render: the prominent primary plus an optional
 * smaller English secondary line (only when a non-English locale is active and
 * a localized name exists that differs from English).
 */
export function exerciseDisplay(
  name: string,
  locale: LocaleId,
): { primary: string; secondary: string | null } {
  const loc = localizedExerciseName(name, locale);
  if (!loc) return { primary: name, secondary: null };
  const eng = canonicalExerciseName(name);
  return { primary: loc, secondary: eng && eng !== loc ? eng : null };
}

/** Every known name variant for an exercise (English + all locales) — for search. */
export function exerciseNameVariants(name: string): string[] {
  const eng = canonicalExerciseName(name);
  const out = [name, eng];
  const tr = MAP[eng];
  if (tr) for (const l of NON_EN) if (tr[l]) out.push(tr[l] as string);
  return out;
}
